### PR TITLE
Update extension: Bing Wallpaper

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

- Update grid layout

## Screencast

bing-wallpaper-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Would you mind changing the empty-view to png?

**Comment by koinzhang** [comment]
Hi @pernielsentikaer I have updated the placeholder image for emptyview and it is now in png format

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Could you trim the image for empty space, I'm not able to open an image editor right now 😊

image

**Comment by koinzhang** [comment]
Already modified, but as I said before, png images will be blurred compared to svg images
image

**Pull request merged**
