### PR TITLE
New extension: Image Converter

### PR DESCRIPTION
**Pull request by Lp-Francois**
## Description

Add a new extension to convert images to a different format, such JPG to PNG, or PNG to JPG. 

A standard workflow would be to copy an image path or an image reference (JPG) and then to have it saved in the same folder but in JPG format.

It automatically detects file references or file paths from your clipboard. From copying from the Finder, or from the native File extension of Raycast

## Screencast

This screencast shows a PNG file taken from the File Raycast extension using the shortcut `CMD + .`, and then using the image converter to JPG, the file gets copied to the clipboard. To show it on the screencast, I pasted it on the Desktop.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Lp-Francois  👋 

Thanks for your contribution 🔥

I'm having problems with this extension, no matter what I do, it says `The file doesn't seem like an image path or reference.`.

If I log out `text` it just says the filename of the file which could be `8x3eU3MvCowG9gMh.jpg`

Full error is here: 
```
07:39:39.817 /Users/pnt/Documents/extensions/extensions/image-converter/src/components/convert.tsx:18
      throw new Error(`The file doesn't seem like an image path or reference.`);
            ^

Error: The file doesn't seem like an image path or reference.
    at Object.Convert (/Users/pnt/Documents/extensions/extensions/image-converter/src/components/convert.tsx:18:13)
    at async MessagePort.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:1:2278)
```

Could also just be me that can't figure out how to use it 😄 

Could you upload [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) too, if you need help, let me know 💯 

Looking forward to testing it out again 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pernielsentikaer** [comment]
Hi @Lp-Francois 👋 

I can't remember where we are with this after our [Slack](https://raycastcommunity.slack.com/) conversation, can you update me on problems? Do you need anything from us?

**Comment by pernielsentikaer** [comment]
I gave feedback in [Slack](https://raycastcommunity.slack.com/) on a possible way to fix the issue, converting it to a draft for now.

**Comment by Lp-Francois** [comment]
TODO: 
- [ ] Check how the file picker works on this extension https://github.com/raycast/extensions/blob/main/extensions/transmission/src/addNewTorrent.tsx 

I'll keep you updated!

**Comment by pernielsentikaer** [comment]
Do you need some help @Lp-Francois

**Comment by pernielsentikaer** [comment]
I'm closing this due to inactivity; feel free to open it again or comment in the thread when you're ready to continue working on it 🙂

You can also catch me in [Slack](https://www.raycast.com/community) if you want to discuss 😄

**Pull request closed without merging**
