### PR TITLE
Add new extension "NixPkgs Search"

### PR DESCRIPTION
**Pull request by aiotter**
## Description

Add a new extension "NixPkgs Search".
This extension performs a search on NixPkgs using [NixOS's Elasticsearch API](https://github.com/NixOS/nixos-search/issues/296).

<details>
<summary>Resolved error</summary>

When I ran `npm run build` I always get the following error:
```
$ npm run build

> build
> ray build -e dist

info  -  entry points [src/index.tsx]
src/index.tsx:224:7 - error TS2739: Type 'AbortSignal' is missing the following properties from type 'AbortSignal': addEventListener, removeEventListener

224       signal: signal,
          ~~~~~~


Found 1 error in src/index.tsx:224

TypeScript check failed (exit status 2)
```

Is this safe to be ignored?

</details>

## Screencast

https://user-images.githubusercontent.com/37664775/186431068-371671cd-ec30-43fd-b11d-8d2f24827806.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by aiotter** [comment]
Oh, node-fetch version was the problem! It seems Raycast's extension template have to be updated

**Comment by sxn** [comment]
yeah, [this update](https://github.com/node-fetch/node-fetch/commit/bcfb71c7d10da252280d13818daab6925e12c368) was the culprit. 😅
We're looking into a proper fix, but for now I've pinned `node-fetch` to an older version.

**Comment by aiotter** [comment]
I pushed 2 commits to fix a bug which is rare to be occurred.
This PR is ready to be merged. Are there anything preventing it from merging?

**Comment by sxn** [comment]
🎉

**Comment by aiotter** [comment]
Thanks! I'm wondering what is the best shortcut keys. I'll keep using it and seek for better ones.
If anyone have some idea about it, please share your thought.

**Pull request merged**
