### PR TITLE
Confluence

### PR DESCRIPTION
**Pull request by ahoereth**
## Description

Re-creation of #6144 and #5075, renaming `confluence` to `confluence-search` as requested by https://github.com/raycast/extensions/pull/6144#issuecomment-1532524980.

## Screencast

See #6144 and #5075

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Let's get this merged and see how it goes

**Comment by TreZc0** [comment]
Sorry, got surprised by this. Did this merge fully remove support for on-premise hosted confluence instances?

**Comment by href** [comment]
> Sorry, got surprised by this. Did this merge fully remove support for on-premise hosted confluence instances?

It seems to have done so, I found no way of using on-premise.

**Comment by lukasnoebauer** [comment]
@ahoereth this PR broke the extension for everyone with self-hosted data center instances...

**Comment by ahoereth** [comment]
@pernielsentikaer should I revert the replacement of `confluence-search` and move this new implementation back to `confluence` instead?

**Comment by TreZc0** [comment]
Yes pls. For now, this is a pretty hefty downgrade :/

**Comment by pernielsentikaer** [comment]
Is there no way to have them both in the same extension?

**Comment by andrewip** [comment]
Any news on whether we might be able to get back the previous version of confluence-search so that on-prem customers can use it?

**Pull request merged**
