### PR TITLE
Add trefle extension

### PR DESCRIPTION
**Pull request by j3lte**
## Description

Lookup information about plants using the [Trefle API](https://trefle.io/)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you know anyone working on Trefle? It looks like their certificate is expired 🙂

image

**Comment by j3lte** [comment]
@pernielsentikaer Hmmm it worked before, but indeed, the certificate seems to have expired or changed. I converted it to a draft and will check it later. Is it ok to ping you when this issue is resolved? Or should we close the PR and resubmit when they have figured this out?

**Comment by j3lte** [comment]
I have contacted Trefle, see if I can figure it out. If the service is discontinued, I'll close the PR

**Comment by pernielsentikaer** [comment]
Let's keep it as a draft for now. Hopefully, it's resolved soon 🙂

**Comment by j3lte** [comment]
Unfortunately no reply from Trefle, so I'm closing this PR...

**Pull request closed without merging**
