### PR TITLE
Add bugzilla extension

### PR DESCRIPTION
**Pull request by vkhitrin**
## Description

Adds a [Bugzilla](https://bugzilla.org) extension that allows querying bugs from multiple Bugzilla instances.

I can provide steps to build a self-hosted Bugzilla container to test this extension if required.

## Screencast

https://github.com/raycast/extensions/assets/32794653/826b7461-54d7-4013-b011-ff41e80b5427

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- If you only have one instance, would it then be possible to skip the instance selection view?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by vkhitrin** [comment]
@pernielsentikaer, thanks for the review :)

> * If you only have one instance, would it then be possible to skip the instance selection view?

I want to ask for your guidance on how from a user experience, this can be achieved?

Open questions on my end:
1. If there are no instances, will all commands open the menu interface?
2. In a scenario with a single instance, how will a user be prompted to add an instance without maintaining an extra command to manage instances?

**Comment by pernielsentikaer** [comment]
> 1. If there are no instances, will all commands open the menu interface?

I think that makes sense yes

> 2. In a scenario with a single instance, how will a user be prompted to add an instance without maintaining an extra command to manage instances?

You could add a action panel item to create a new instance (and handle current ones)

**Comment by vkhitrin** [comment]
Sorry for the long delay, @pernielsentikaer 😞 

Thanks for the feedback. I will work on it and propose a new draft.

**Comment by vkhitrin** [comment]
Hey @pernielsentikaer, I have refactored this extension to use native dropdown menus instead of a proprietary menu.
Updated the screenshots.

**Comment by pernielsentikaer** [comment]
Hi @vkhitrin 👋 

I updated the code a bit, can you have a look? 🙂

If you're able still able to, I'd like some credentials, you can find me in our [Slack](https://www.raycast.com/community) or check my GH profile on how to reach out to me 🙂

**Comment by vkhitrin** [comment]
Thank you @pernielsentikaer, shared credentials privately in Slack.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The login field when setting up an instance, should that re renamed to username?

- The extensions suffer from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

- I would switch the subtitle and the title field here, if needed, and add keywords={[]} to the list to add more to search for. 

bugzilla 2023-10-09 at 08 36 43

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by vkhitrin** [comment]
Thank you @pernielsentikaer!

> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * The login field when setting up an instance, should that re renamed to username?

Done, thanks for raising this.

> * The extensions suffer from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

https://github.com/raycast/extensions/assets/32794653/86196496-ed2f-4327-a37b-aa4bd8edd6ee

Do you think it looks better?  The default state will start from `No Bugs Found` and will be populated with bugs if they were fetched.


> * I would switch the subtitle and the title field here, if needed, and add keywords={[]} to the list to add more to search for.
> 
> bugzilla 2023-10-09 at 08 36 43

I was thinking about it and don't have a strong opinion on this matter right now.
I know that the Jira extension is following your recommendation.

I have added `keywords` to allow filtering for bug IDs and bug summaries.

> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by vkhitrin** [comment]
@pernielsentikaer, I have fixed the flickering and re-introduced a loading prompt.
I have also improved the search (filtering) of fetched bugs.

I have restarted my Bugzilla instance and will share the new API key privately in Slack.

**Comment by pernielsentikaer** [comment]
Awesome, I'll test again and DM you

**Comment by pernielsentikaer** [comment]
DM'ed on [Slack](https://www.raycast.com/community)

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I found two more things we can address:

- The extensions suffer from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) - In my test it went from loading: true false false false true false - this should only go from true to false to avoid flicker

- Don't change `navigationTitle` in the root of a command, it's only for nested views

**Comment by vkhitrin** [comment]
Hey @pernielsentikaer, revisiting this PR.
I have fixed the unnecessary navigation title renaming.

I cannot reproduce the empty state flicker on my end. Could you please point me to where it is occurring for you?

https://github.com/raycast/extensions/assets/32794653/0e6e0e1b-26a8-4e8a-8faf-f830d4f4dea2

I will re-share the credentials with you on Slack on Monday.

**Pull request closed without merging**
