### PR TITLE
Add Caffeinate For to Coffee Extension

### PR DESCRIPTION
**Pull request by bibixx**
## Description
The Amphetamine app supports setting the _"caffeination"_ time, so that the _"caffeination"_ will be turned off some time. The `caffeinate` command present on MacOS supports this feature with `-t` flag.
This PR adds a "Caffeinate For" command that adds support for this.

Additionally to easily support this I did a teeny-tiny refactor of the `Caffeinate` and `CaffeinateWhile`

## Type of change

- Improvement for somebody else's extension. Extension author: @mooxl 

## Screencast

https://user-images.githubusercontent.com/14880213/150954842-3301dbb9-f8d2-4617-9f91-6e49bca61056.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by mooxl** [comment]
Looks good to me!

**Review by mooxl — APPROVED** [review]

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @bibixx 👋 

Thanks for your contribution 💯 

A few comments:
- You could add yourself as “contributor” in `package.json` if you want
- I think I would [popToRoot](https://developers.raycast.com/api-reference/user-interface/window-and-search-bar#poptoroot) after setting interval

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by bibixx** [comment]
@pernielsentikaer thanks for review!
As far as I understand the `showHUD` function (that is being called inside the `Caffeinate` function) closes the Raycast altogether, so I'm not too sure if the `popToRoot` would make any difference. Please correct me if I'm wrong.

As for the contributions, sure will do that!

**Comment by pernielsentikaer** [comment]
Hi @bibixx 

Right now is the behaviour like this

https://user-images.githubusercontent.com/38033107/151258766-3f873814-1b35-4e70-b1d2-e30a1eb87846.mp4

My suggestion would be to add poptoroot, so it will do this (when opening again)

https://user-images.githubusercontent.com/38033107/151259167-9d142a8f-a8fe-4576-a9e3-ab14caf75f95.mp4

Let me know if you have any questions at all regarding this 😄

**Comment by fe9lix** [comment]
Hey @bibixx, did you have a chance looking into @pernielsentikaer's feedback?

**Comment by bibixx** [comment]
@fe9lix Yes I did, sorry. However I didn't have change to implement them (was in process of changing jobs, didn't have laptop for some time). I'll look into this today (or tomorrow tops)

**Comment by bibixx** [comment]
@pernielsentikaer @fe9lix just updated the PR
* Added the `popToRoot`
* Added an option to change the unit of the specified duration
yKrsN0OktBd1ZcMT

**Review by pernielsentikaer — APPROVED** [review]
Hi @bibixx 👋 

It does also look good to me, accepted 🎊

**Pull request merged**
