### PR TITLE
fix: handle another pipe-command selection error

### PR DESCRIPTION
**Pull request by iloveitaly**
## Description
Similar to 7e6b36d4c. Fixes another text selection error I've run into.

## Screencast
NA

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the update @iloveitaly 

@pomdtr could you have a look?

**Comment by pernielsentikaer** [comment]
Could you check this, if you have time, @pomdtr 🙂

**Comment by pernielsentikaer** [comment]
Could you resolve this merge conflict @iloveitaly

**Comment by iloveitaly** [comment]
@pernielsentikaer done!

**Comment by pomdtr** [comment]
Looks good to me, thanks for the contribution @iloveitaly !

**Pull request merged**
