### PR TITLE
Add a QQ Music controls extension

### PR DESCRIPTION
**Pull request by jwickers**
Signed-off-by: Jeremy Wickersheimer <jwickers@gmail.com>

## Description

A basic extension to control [QQ Music](https://y.qq.com/) macOS client.

Supports basic controls with ApplesScript via "System Events".

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @jwickers 👋 

Thanks for creating an extension, I have some feedback for now to address:

- You have added a file in `docs/.gitbook/assets`, could you please remove that one?

- Your metadata image is not following the [screenshot guideline](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) about padding, let me know if you need help.

- The image linked in the README should be the one from metadata when it's fixed.

I don't think I'm able to test it out, but I'd love to help get it merged 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by jwickers** [comment]
Made the changes. I think when I started there was no template for screenshots, though I noticed mine seem a few pixels short in height compared to the template, I guess that's not too important (had the same issue on another extension).

I've also added the link to the app website in the README if you wanted to test it. It's in Chinese but there is a download link with a Mac icon (alongside Windows / Android / IOS)  at the very bottom of their page although I can remember for sure if it requires you to login ...

**Comment by koinzhang** [comment]
> Made the changes. I think when I started there was no template for screenshots, though I noticed mine seem a few pixels short in height compared to the template, I guess that's not too important (had the same issue on another extension).

Hi @jwickers . If you want to make metadat screenshots quickly, you can try this extension [Capture Raycast Metadata](https://www.raycast.com/koinzhang/capture-raycast-metadata)

**Review by pernielsentikaer — APPROVED** [review]
Hi @jwickers 👋 

Thanks! Much better! 🔥

**Pull request merged**
