### PR TITLE
Add github-code-search extension

### PR DESCRIPTION
**Pull request by tdkn**
## Description

- You can perform searches on GitHub Code Search directly from Raycast.
- You can configure filter options as necessary.

## Screencast

https://github.com/raycast/extensions/assets/1296540/724446ee-f8b7-4471-8786-8d3bc2207b76

## Screenshots

| 1 | 2 | 3 |
| :---: | :---: | :---: |
| github-code-search-1  | github-code-search-2  | github-code-search-3  |

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@thomaslombart, would this fit into the current GitHub extension, or does it make sense to have it as a standalone?

**Comment by thomaslombart** [comment]
@pernielsentikaer It could be the case, yes, especially since it would be possible to retrieve the user's organizations, which could be an improvement here.

**Comment by pernielsentikaer** [comment]
What do you think about that, @tdkn - I'm not that much into the GitHub extension as @thomaslombart is, so if we're missing something, please enlighten us 🙂

**Comment by tdkn** [comment]
I think it would be great to add Code Search functionality to an existing GitHub Extension and would prefer it if possible. I'm not familiar with the existing Extension, but can I use Code Search functionality without setting a Personal Access Token (PAT)? My Extension uses a public endpoint, so Code Search works without a PAT.

**Comment by thomaslombart** [comment]
@tdkn This shouldn't be a problem in the current extension.

**Comment by pernielsentikaer** [comment]
Would you be up for that @tdkn

**Pull request closed without merging**
