### PR TITLE
Adding the new Gemini models.

### PR DESCRIPTION
**Pull request by arthrod**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
If I'm not mistaken, then it's already being done here: https://github.com/raycast/extensions/pull/15949

**Comment by pernielsentikaer** [comment]
CC @EvanZhouDev

**Comment by d0zingcat** [comment]
> If I'm not mistaken, then it's already being done here: #15949

Hi pernielsentikaer

Definitely you are correct.
 I've added the new models to the implementation of this PR.

**Comment by arthrod** [comment]
Apologies!

**Comment by pernielsentikaer** [comment]
All good 🙂

**Pull request closed without merging**
