### PR TITLE
SABnzbd: Add history

### PR DESCRIPTION
**Pull request by jesse-c**
## Description

A new command is added that lists complete downloads from the history.

An improvement to https://github.com/raycast/extensions/pull/206.

## Type of change

- Bug fix / improvement for my extension

## Screencast

N/A

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @jesse-c 👋 

Thanks for the addition for the extension 💯 

Could you maybe like last time make a screencast of the feature(s) to help us review it?

**Comment by PitNikola** [comment]
Gonna merge it, seems like straightforward addition. Thanks @jesse-c!

**Comment by jesse-c** [comment]
Sorry for the lack of screencast again!

Is there an easy way to blank out some data during a screencast? Or perhaps I could setup a little VM that has "fake" data for SABnzbd.

**Comment by PitNikola** [comment]
@jesse-c, in this case you might want to just make screenshots with different states. It can be enough. Cleanshot has some nice tools for pixelating areas of the screenshot to hide data.

**Comment by jesse-c** [comment]
That's a good idea! I'll do that best time. Thank you.

**Pull request merged**
