### PR TITLE
update Wolfram Alpha instructions, fixes #8613

### LINKED ISSUE #8613: [Wolfram Alpha] Readme should specify API type
### Extension

https://www.raycast.com/mathieudutour/wolfram-alpha

### Description

When creating an App ID, Wolfram Alpha requires to select the API type. Users need to select "Simple API" for the extension to work, but this is not documented at the moment.

Screenshot 2023-09-29 at 15 41 33

### Steps To Reproduce

1. Create an App ID with the API type other than "Simple API"
2. Execute any query

### Current Behaviour

Error: Invalid App ID

### Expected Behaviour

Extension's readme states the API type

### PR DESCRIPTION
**Pull request by danielkleinert**
## Description

Simple update to the plugin instructions, which were out of date
Should resolve #8613

### CODE REVIEW

**Review by mathieudutour — APPROVED** [review]

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
@danielkleinert I can't create an API key, I keep getting error code 500, could you add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) 🙂

**Comment by pernielsentikaer** [comment]
Are you still around @danielkleinert

**Comment by thxbeats** [comment]
I'm not able to make an API key to use Wolfram in RayCast. Instructions are not clear, seems like wolfram now wants to know what API you want to use (I need to select an API: Full Request, Simple API, short answers ...).
If I choose Full Request API (or others), then paste it into the box in RayCast, there occurs problem "Invalid APP ID".

CleanShot 2024-01-27 at 14 01 15@2x
CleanShot 2024-01-27 at 14 01 44@2x

**Comment by pernielsentikaer** [comment]
You should use the `Simple API` as [stated here](https://raw.githubusercontent.com/danielkleinert/extensions/wolfram-alpha-instructions/extensions/wolfram-alpha/README.md) - maybe it's working for you 🙂

**Comment by thxbeats** [comment]
> You should use the `Simple API` as [stated here](https://raw.githubusercontent.com/danielkleinert/extensions/wolfram-alpha-instructions/extensions/wolfram-alpha/README.md) - maybe it's working for you 🙂

Unfortunately, not working for me :C

How can I contact with someone to help me? Maybe mail or discord? I can show screen recording video in order to find out what's wrong... I think I'm doing everything right, but...
I really don't understand what's the problem, tried so many variations (e.g. reopen raycast, reinstall wolfram extension, different variations of API Key, reload my mac...) to solve it, but nothing works

**Comment by pernielsentikaer** [comment]
There is not much we can do actually since it's an issue in Wolfram, so you need to contact them 🙁

**Pull request closed without merging**
