### PR TITLE
Quick open project

### PR DESCRIPTION
**Pull request by Loskir**
## Description
Big update for Quick Open Project extension by @zerowidth 

- Added IDE detection for each project
- Added support for some of JetBrains IDEs (Webstorm and PyCharm for now)
- Added support for [Git Fork](https://git-fork.com)
- Added recursive search
- Added ignored paths

## Type of change

- Bug fix / improvement for somebody else's extension

## Screencast

https://user-images.githubusercontent.com/21295738/138677472-6f5c7a1f-ff8d-4bff-ba19-51963a58cc8d.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by zerowidth — CHANGES_REQUESTED** [review]
This PR bundles more changes than I'm really comfortable with, and I'm not sure they're all changes I want to incorporate.

> Added IDE detection for each project
> Added support for some of JetBrains IDEs (Webstorm and PyCharm for now)

This is an interesting idea. It feels too presumptive (or, rather, presumptive in a different way from this extension's assumptions). For example, I have IntelliJ installed but I prefer to browse java projects with the hardcoded vscode.

What do you think about making these additional IDEs a checkbox in prefs? That is: if you have Pycharm installed and you've enabled the option, checking the box makes that the default action over vscode and otherwise it just uses VSCode.

For the global default, what I'm hoping for is a "preferred application" preference so the top-level vscode/iterm defaults can be changed. (cc #98)

> Added support for Git Fork

👍 seems fine, are there other apps that should be added here? GitHub Desktop, GitKraken, Git Tower, etc?

> Added recursive search

The directory list already supports globbing -- for example, I index my golang code with `~/go/src/*/*`. The recursive search you've implemented here feels more complicated than necessary -- do you usually have `project{x, y z}` dirs alongside a `subprojects/{a,b,c}` container?

This is definitely a documentation issue if nothing else, I need to make sure globbing support is mentioned somewhere. (cc #277)

> Added ignored paths

👍 This is a nice addition.

---

Would it be possible to split this up into smaller PRs?

**Comment by PitNikola** [comment]
Hey @Loskir, just wanted to double check if you plan to address suggestions by @zerowidth? Let me know if you have any questions.

**Comment by Loskir** [comment]
@zerowidth thanks for review!

> It feels too presumptive
I agree with that. I turned out to be very hard to make a script that accurately predicts appropriate IDE for a project. I'm thinking about detecting all installed IDEs and maybe using a dedicated frecency instance for choosing an IDE for every project. This would solve presumptions for VSCode and JetBrains IDEs and also allow users to more precisely adjust tools for each project.
If this looks like a good idea, the easiest way to do this would be to disable project type detection entirely and just let users train their frecencies for their needs. After that we may add project type detection back but as a recommendation system, not as a filter for IDEs. Though it might require some complex algorithms and I'm not really qualified in that field.

> do you usually have project{x, y z} dirs alongside a subprojects/{a,b,c} container?
Yes, I have `~/Projects` directory which contains both `~/Projects/some-small-project` and `~/Projects/some-big-project/repo-{a,b,c}`. I made the extension detect `~/Projects/some-small-project` and `~/Projects/some-big-project/repo-{a,b,c}`, but not the `~/Projects/some-big-project/` itself.
But it might actually have been an overkill. As there are not so many `some-big-project`s, I could just specify `~/Projects, ~/Projects/big-project-{a,b,c}` as scanning path and add `~/Projects/big-project-{a,b,c}` to ignored dirs.
I don't really know how to make it work the best so I'd like to hear some suggestions.

> are there other apps that should be added here?
Yeah, It would be nice to add more IDEs, terminals, git tools, maybe something else.

> Would it be possible to split this up into smaller PRs?
I'll try to isolate smaller changes into separate PRs

Unfortunately, I don't have much spare time to work on this project, but i'll try my best. Anyway, all help and suggestions are welcome!

**Comment by mattisssa** [comment]
@Loskir @zerowidth What's up with this PR, since this one is still awaiting something. 
@Loskir Can you please resolve the conflicts so we could simply merge one?

**Comment by zerowidth** [comment]
We can close this for now, but will consider these requests/patches for future updates.

**Pull request closed without merging**
