### PR TITLE
Semantic Scholar: Research Paper Search by Keywords

### PR DESCRIPTION
**Pull request by blainerothrock**
## Description

Added a new extension for [Semantic Scholar](https://www.semanticscholar.org). This application uses Semantic Scholar's [open API](https://www.semanticscholar.org/product/api#Documentation) to search for research papers by keyword. There are a few more pieces of functionality I would like to add, but as a PhD student, this is already very helpful for quickly searching papers!

## Screencast
Screen Shot 2022-02-16 at 20 58 00

Screen Shot 2022-02-16 at 20 37 23

Screen Shot 2022-02-16 at 20 20 20

Screen Shot 2022-02-16 at 20 53 23

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @blainerothrock 👋 

Thanks for your contribution 💯 

I left some feedback for you to address. Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @blainerothrock 👋 

Sorry for the late reply! I just gave it a spin again and only have one suggestion left for you:

When you open the extension is calls`performSearch` with an empty string which is unnecessary, when this is fixed, then I'm sure we're ready to proceed to final stage 💯  💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Review by pernielsentikaer — APPROVED** [review]
Hi @blainerothrock 👋 

Much better, awesome work!

I'm going to approve it, let's send it to the last stage 💪

**Comment by sxn** [comment]
nice! 🎉

**Pull request merged**
