### PR TITLE
[idonthavespotify] new commands and bug fixes

### PR DESCRIPTION
**Pull request by sjdonado**
## Description

This PR adds new commands and restructures the extension to make link validation on the client side more flexible.
Fixes issue [#13488](https://github.com/raycast/extensions/issues/13488).
Updates the screenshots to match the latest visual updates.

## Screencast

https://github.com/user-attachments/assets/d6559f46-09a6-4807-8506-9a4616e9580f

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mil3na — CHANGES_REQUESTED** [review]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

Testing your extension, I tried to put a apple music link on this command and gave me this error. I would suggest to make this error more user friendly, it doesn't say much to a non-tech person. Also, if you only accept Spotify links, please state on the command "from Spotify to X", so it is not confusing.
CleanShot 2024-07-17 at 10 35 32

Also, with the same song, I get different results here. Why is that?

CleanShot 2024-07-17 at 10 37 24

CleanShot 2024-07-17 at 10 37 34

**Comment by sjdonado** [comment]
> Hi! Thank you for your contribution! My name is Milena and I will be reviewing it today.
> 
> Testing your extension, I tried to put a apple music link on this command and gave me this error. I would suggest to make this error more user friendly, it doesn't say much to a non-tech person. Also, if you only accept Spotify links, please state on the command "from Spotify to X", so it is not confusing. CleanShot 2024-07-17 at 10 35 32
> 
> Also, with the same song, I get different results here. Why is that?
> 
> CleanShot 2024-07-17 at 10 37 24
> 
> CleanShot 2024-07-17 at 10 37 34

Hi Milena, thank you for the review! Regarding the first screenshot, the Reverse Search is only available for YouTube Music links, but I plan to include Apple Music and SoundCloud later this week. I will fix the error to make it more user-friendly, but renaming the commands seems a bit misleading.

I will check the misbehavior in the second and third screenshots. It is 100% related to the server response, so it is not a blocker for the changes introduced to the extension

Let me know your thoughts :)

**Comment by sjdonado** [comment]
@mil3na comments addressed :)

**Comment by LitoMore** [comment]
I'd prefer to implement these commands into one command. And use an action list to select the target platform when converting. You can make a preference item to let users save their most frequent platform or always move the last selection to the top.

I usually try to keep the number of commands as short as possible, because too many commands will make searching cumbersome and you will need to type more characters to hit the command you want.

What do you think?

**Comment by sjdonado** [comment]
> I'd prefer to implement these commands into one command. And use an action list to select the target platform when converting. You can make a preference item to let users save their most frequent platform or always move the last selection to the top.
> 
> I usually try to keep the number of commands as short as possible, because too many commands will make searching cumbersome and you will need to type more characters to hit the command you want.
> 
> Especially the word "convert". There are too many tools with the convert function. When you type "convert", you may see a lot of irrelevant commands, and it is difficult to locate the result you want.
> 
> On the other hand, too many commands will also increase the file size of the plugin exponentially. Maybe this is not a big burden for us, but we still need to pay attention to it.
> 
> What do you think?

Good point. The idea of having multiple commands is to only activate the ones you frequently use (and to attach to them a hotkey). I can disable all of them by default and add instructions in the README to make this clear. What do you think?

On the other hand, the main command `search` already performs a general search (including all links), so an action list is not necessary.

**Review by LitoMore — APPROVED** [review]

**Comment by sjdonado** [comment]
@mil3na waiting for your approval :)

**Comment by mil3na** [comment]
I tried your extension again. Got a Spotify link converted to Deezer. Then, tried to convert back to Spotify and I got an "invalid link" response. 
It is very confusing which conversions I can and cannot do. Maybe you should make it clear on your README? Also, the only command that was disabled by default was the "convert to. Tidal".

**Comment by sjdonado** [comment]
> I tried your extension again. Got a Spotify link converted to Deezer. Then, tried to convert back to Spotify and I got an "invalid link" response. It is very confusing which conversions I can and cannot do. Maybe you should make it clear on your README? Also, the only command that was disabled by default was the "convert to. Tidal".

Command descriptions have been updated to clearly indicate which links can be converted 264d71d.

> Also, the only command that was disabled by default was the "convert to. Tidal".
To see these changes you have to uninstall and reinstall the extension.

Please let me know if everything works fine on your local. :)

**Review by mil3na — APPROVED** [review]
LGTM!

**Pull request merged**
