### PR TITLE
Add PATCH method and change methods icons as per issue request #4218

### PR DESCRIPTION
**Pull request by jonathangiardino**
## Description

Add PATCH method and change methods icons as per issue request [#4218](https://github.com/raycast/extensions/issues/4218)

## Screencast

N/A

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jonathangiardino** [comment]
> Hi @jonathangiardino 👋
> 
> Awesome update; what do you think about adding this look instead? I could add the code (since I already did) 😊
> 

Totally dig it @pernielsentikaer!

Go ahead, seems like a nice touch! 🔥

**Comment by pernielsentikaer** [comment]
Please feel free to change it so it matches your style.

Change whatever you like, I'm not that skilled as you 😊

**Comment by jonathangiardino** [comment]
> Please feel free to change it so it matches your style.
> 
> Change whatever you like, I'm not that skilled as you 😊

I would not change anything honestly, if all is good I would merge it like this, I really like the tag, it's clearer than before. 🔥

**Comment by pernielsentikaer** [comment]
Can you give it a last spin @jonathangiardino 😊

**Comment by jonathangiardino** [comment]
> Can you give it a last spin @jonathangiardino 😊

Looking ready to ship 🚀 @pernielsentikaer! The last color differentiation was a great addition.
Thanks for the refinements! 🔥

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
