### PR TITLE
Add NextDNS extension

### PR DESCRIPTION
**Pull request by itsmingjie**
## Description

Added extension for [NextDNS](https://nextdns.io) with basic allowlist/denylist management for now.

## Screencast

https://github.com/raycast/extensions/assets/13333578/f97670dc-8918-4153-98c7-2a62c52ef85c

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The function `isValidDomain` doesn't seems to work, it always give me this

nextdns 2024-01-22 at 06 52 39

- You could actually do everything inside a single command instead, which shows everything and uses a dropdown to change type of nessacary - that would maybe be better than having 4 commands?

- Does the action `Add Domain to Allowlist` make sense in this list?

nextdns 2024-01-22 at 06 56 10


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
@itsmingjie are you still working on this?

**Comment by pernielsentikaer** [comment]
I'll convert this to a draft for now, I still think it would be a very nice extension @itsmingjie

**Comment by pernielsentikaer** [comment]
@itsmingjie I actually think it also could be fine to keep the two list commands, and inside them we could have the add domain, what do you think about that?

**Comment by pernielsentikaer** [comment]
Hi @itsmingjie 

Do you want to continue on this extension, or should I do it? I think we can keep the current commands, it actually makes sense 🙂

**Comment by xmok** [comment]
@pernielsentikaer I've been following this PR for a month or so as I have a "NextDNS" account. I think if it looks good to you you can get this merged and I'd be willing to act as a contributor/maintainer/owner whichever is required until the author can get back.

**Comment by pernielsentikaer** [comment]
I was about to do the same @xmok and was waiting for it to get closed, but let's continue.

I added you as a contributor. I think the original author has been pinged enough 🙂

**Comment by pernielsentikaer** [comment]
Anything you think we should look into before the initial release?

**Comment by xmok** [comment]
> Anything you think we should look into before the initial release?

So far the few features are working perfectly fine. The only thing I'm missing right now is when running some actions e.g. removing a domain from Allowlist or adding a domain to Denylist, there's no loading indicator nor animated toast shown so there's a second or two before I get a success toast that action has completed.

But this isn't a blocker - probably the first feature I'd want to implement in the next version otherwise LGTM 🚀.

**Comment by pernielsentikaer** [comment]
Regarding commands; we might want to change that before the release. I can look into merging them later this evening 🙂

**Comment by pernielsentikaer** [comment]
So we're aiming for two commands, right?

**Comment by pernielsentikaer** [comment]
I added you to my fork @xmok - feel free to catch me in Slack if you're there - didn't get that far yesterday as I wanted but let's do it 🙂

**Comment by pernielsentikaer** [comment]
Closed in favor of #14259

**Pull request closed without merging**
