### PR TITLE
Add splix extension

### PR DESCRIPTION
**Pull request by cwooldridge1**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @cwooldridge1 👋 

Do you mind fixing the CI errors 🙂

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Can you remove `assets/command-icon.png`

- I would use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) to control it, you need validation of the fields which useForm has - otherwise it will crash like this

splix 2024-01-23 at 12 09 31

- Missing [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Is this ready for another review, if so, request a new review 🙂

**Comment by cwooldridge1** [comment]
> Is this ready for another review, if so, request a new review 🙂

Hey! Yes this ready for review. How do I request one?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
