### PR TITLE
Displayplacer

### PR DESCRIPTION
**Pull request by eluce2**
## Description

This is primarily a quality-of-life update. I've added a new command that acts like a wizard to help new users with all the steps they need for this extension to work properly. This also adds more feedback instead of failing silently when the "Load Preset by #x" commands don't do anything (e.g. the preset or utility is missing)

## Screencast

CleanShot 2022-04-25 at 19 06 24@2x

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I spoke with @eluce2 about this in our [community](https://raycastcommunity.slack.com/), awaiting a push to verify

**Comment by douglassimaging** [comment]
Sorry I’m really new with this, could you give me a step by step way to put this into a keyboard shortcut please 🙏

**Comment by eluce2** [comment]
@pernielsentikaer I've added an image to help illustrate this, but it's not loading properly. Am I doing something incorrectly?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @eluce2 👋 

It looks much better, could you look into some better icons for white/dark appearance for those two icons:

CleanShot 2022-04-29 at 06 56 39@2x

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pernielsentikaer** [comment]
Awesome, thanks @eluce2 🔥

**Pull request merged**
