### PR TITLE
Dropstab raycast

### PR DESCRIPTION
**Pull request by Motion-Up**
## Description

# DropsTab Dropstab Crypto Toolbox

### Search

Dropstab Crypto Toolbox displays the price, market capitalization, and rank of any cryptocurrency, and also allows quick access to the project's page on Dropstab.com or its X (Twitter) profile.

DropsTab

### Wallets

Dropstab Crypto Toolbox allows you to instantly find and view any crypto address in the blockchain explorer.
DropsTab

### Ethereum Gas Tracker

Get the latest gas prices for Ethereum. This feature provides real-time information on the current gas prices required for transactions on the Ethereum network.

DropsTab

### Macro View

Get the latest macroeconomic data. This feature provides a comprehensive overview of key macroeconomic indicators such as stock indices, commodities, and other financial instruments.

DropsTab

### Gainers & Losers

Get the latest gainers and losers. This feature displays the top-performing and worst-performing cryptocurrencies over the last 24 hours.

DropsTab

### CEX Pairs Search

Search for pairs on CEX. This feature allows users to search for trading pairs on centralized exchanges (CEX).

DropsTab

_Made with ❤ for the Decentralized World._

### Added

- Ethereum Gas Tracker
- Macro View
- Gainers & Losers
- CEX Pairs Search

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your update 🔥

Can you only push the changed files? I can't see what's changed - it seems like you pushed the entire extension 🙂

**Comment by Motion-Up** [comment]
> Thanks for your update 🔥
> 
> Can you only push the changed files? I can't see what's changed - it seems like you pushed the entire extension 🙂

Yes, I removed the old dropstab_raycast folder and kept only the dropstab folder. In the new update, almost every file has code changes. These changes were made to optimize and improve the readability of the code.

**Comment by pernielsentikaer** [comment]
Could you install your own extension from the store and then find it an hit `Fork` - this will make a correct fork instead - you're still pushing all files as it was the frist time 

When you have changed your files, then you can `git add .` and then run `npx @raycast/api@latest publish`

**Comment by Motion-Up** [comment]
I forked the repository [https://github.com/raycast/extensions/tree/4c9ae993980654c1234bf3796e0fbbde5bf88727](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html), switched to the branch dropstab_raycast, deleted the dropstab_raycast folder, and updated the code in the dropstab folder. After that, I ran git add . and committed the code. Then I used the command npx @raycast/api@latest publish and got the following error:
ready - validate git repository
ready - getting fork
error - preparing clone
extension path in fork: found more than one extension with name dropstab.
What do I need to do?

**Comment by pernielsentikaer** [comment]
Seems like you pushed everything again, can you try this flow: 

1) Delete the https://github.com/Drops-Team/extensions/tree/dropstab_raycast branch
2) Fork the extension
3) Add new stuff
4) git add .
5) git commit -m "Update"
6) npx @raycast/api@latest pull-contributions
7) npx @raycast/api@latest publish

**Pull request closed without merging**
