### PR TITLE
Open JetBrains Projects: Add better feedback when cli tools are missing

### PR DESCRIPTION
**Pull request by gdsmith**
## Description

If user has not installed the CLI tools, give them a prompt to do so

## Type of change

- Bug fix / improvement for my extension

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by gdsmith** [comment]
@pyinto tried adding handling for when CLI tools are not installed, if you can confirm that you don't have them installed that would be helpful.

**Comment by pyinto** [comment]
@gdsmith by CLI tools you mean `xcode-select --install`? I do have them installed if so.

**Comment by gdsmith** [comment]
> @gdsmith by CLI tools you mean `xcode-select --install`? I do have them installed if so. `Generate shell scripts` is also enabled in the Toolbox app.

Just the second part. What is the path you have selected for "Generate shell scripts" (under Shell scripts location)?

**Comment by pyinto** [comment]
> > @gdsmith by CLI tools you mean `xcode-select --install`? I do have them installed if so. `Generate shell scripts` is also enabled in the Toolbox app.
> 
> Just the second part. What is the path you have selected for "Generate shell scripts" (under Shell scripts location)?

it's `/usr/local/bin`

**Comment by pernielsentikaer** [comment]
Hi @gdsmith 👋 

I'm on the M1 chip and having problems getting through the information screen

1B9Boqkebxx7O3YS

Scz2YtvxNFgGEGIu

Is there something specific that needs to be done?

**Comment by gdsmith** [comment]
Okay, looks like I customised the shell scripts location and forgot about it, will look into it

**Comment by gdsmith** [comment]
@pernielsentikaer this should be fixed now, I've updated with better ways to locate the correct tools using some previously unknown (to me) hidden json files. I'm also using a different method to determine if the tools are available which should help.

**Comment by pernielsentikaer** [comment]
Hi @gdsmith 👋 

It looks a lot better now, I have PHPStorm and AppCode installed and it showed the list fine this time - then I installed a few more systems and got this baby:

P3Drcr1vukkKGomN

```
TypeError: Cannot read properties of undefined (reading 'shell_script_name')

          const tool = await which(history.item.intellij_platform.shell_script_name, {path: bin})
                                                                  ^

<anonymous>:recent.tsx:69:67

---
66:         .then(json => json.history.pop())
67:         .then(async (history: History) => {
68:           const icon = icons.find(icon => icon.title.startsWith(history.item.name))?.path ?? JetBrainsIcon
69:           const tool = await which(history.item.intellij_platform.shell_script_name, {path: bin})
70:             .catch(() => '');
71:           return {
72:             title: history.item.name,
---

    at async Promise.all (index 4)
```

Seems like it wasn't too happy about that 😄

**Comment by gdsmith** [comment]
@pernielsentikaer thanks, I've updated again with better handling when it's missing those expected elements (and an attempt to use the protocol url if the tools are missing) if you can re-test it that would be great.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @gdsmith 

Just a few things and were soon ready to merge 💯 

- The provided logo in the extension is not provided in 512x512 pixels. Please modify this according to [Extension Icon guideline](https://developers.raycast.com/basics/prepare-an-extension-for-store#extension-icon)
- If I change "tools bin folder" in preferences it still just works?

And then just a few NITs, could improve the UI
- Now that you have the icon on the left, is there any other data that could be relevant in accessoryTitle?
- When having too many apps then the search bar text goes out of the box, maybe don't show apps? 

pauZNPP5fyrMdQFn

- I would remove the word "Open" from the command title, otherwise, it looks a bit crazy 😄 

aQ8ywuRrcJvuIg6N

**Comment by gdsmith** [comment]
@pernielsentikaer thanks for the review. Updated for you as per the following:

> The provided logo in the extension is not provided in 512x512 pixels

Done

> If I change "tools bin folder" in preferences it still just works?

It will fall back to using the protocol url if it can't find a cli tool, but I've found those are a bit flakey (e.g. doesn't always bring app/window to the front), so prefer the cli tools

> Now that you have the icon on the left, is there any other data that could be relevant in accessoryTitle?

Icon was always on the left, I can't think of anything else, any suggestions?

> When having too many apps then the search bar text goes out of the box, maybe don't show apps?

Removed it.

> I would remove the word "Open" from the command title, otherwise, it looks a bit crazy 😄

That's only in development mode though right? Normally that is `Open Command` there? Regardless, I see in VS Code you have used Search Recent Projects so I've updated it to that.

**Comment by pernielsentikaer** [comment]
@gdsmith Thanks for the update, lets get it merged! 💯

**Pull request merged**
