### PR TITLE
Add background-sounds extension

### PR DESCRIPTION
**Pull request by sebdanielsson**
## Description

Lets the user toggle macOS native background sound feature on and off.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
That's awesome, @sebdanielsson 🔥

The toggle command works as expected; however, if I use the change sound and volume, I end up here. Is that expected?

Raycast22042024-ZarG8YKf png@2x

**Comment by sebdanielsson** [comment]
> That's awesome, @sebdanielsson 🔥
> 
> The toggle command works as expected; however, if I use the change sound and volume, I end up here. Is that expected?
> 
> Raycast22042024-ZarG8YKf png@2x

Oh that's really strange. I just retested and I end up at this settings pane:

image

May I ask what version of macOS you are running? I'm on 14.4.1.

**Comment by pernielsentikaer** [comment]
I'm running the exact same, 14.4.1 (23E224)

**Comment by sebdanielsson** [comment]
Turns out something is messed up on my end. Asked a friend to try it out, and he had the same problem as you did. The good news is that I used the wrong name for the preference pane, and now it works perfectly for both of us.😃

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by sebdanielsson** [comment]
> Hi 👋 
> 
> 
> 
> Looks good to me, approved 🔥

Thank you!

**Pull request merged**
