### PR TITLE
Update transmission extension

### PR DESCRIPTION
**Pull request by FOR0x00**
## Description

Add a dedicated field for the default download directory

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @zhangjiepro 🔥 

@FezVrasta could you check this?

**Comment by FezVrasta** [comment]
I would suggest to add a dedicated preference field for the default download path

**Comment by j3lte** [comment]
@FezVrasta I second this. Probably make this a [CachedState](https://developers.raycast.com/utilities/react-hooks/usecachedstate) so it stay saved between command executions.

**Comment by pernielsentikaer** [comment]
That sounds like a good idea, @zhangjiepro can you look into this?

**Comment by zhangjiepro** [comment]
@j3lte you mean keep this or add a dedicated preference field? the download diretory only be used in `Add Torrent` command only? could you give some sugestion more? thanks

**Comment by danpalmer** [comment]
+1 to @FezVrasta's suggestion of a dedicated default download directory. I think some users will want the option every time and for them the first option in their quick directories has no significance and may even cause them to forget to set the right directory.

**Comment by zhangjiepro** [comment]
I have added a dedicated field for the default download directory, could you check again, thanks
@FezVrasta @pernielsentikaer

**Review by FezVrasta — APPROVED** [review]

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
