### PR TITLE
Add aranet-co2 extension

### PR DESCRIPTION
**Pull request by WilliamWelsh**
## Description

Adds a command to view Aranet4 data (CO2, Humidity, Pressure, Temperature) and a menu bar command that shows your CO2 level (refreshes every 5 minutes)

## Screencast

vengeance2023-12-31 at 14 00 20@2x

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Thanks for your contribution 🔥 

I installed it and selected `Celcius` and ended up with the below screen, could you look into that?

aranet-co2 2024-01-10 at 09 49 52

```
09:51:29.416 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/pernielsentikaer/.config/raycast/extensions/aranet-co2/aranet.js:2135:18
    at Cr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:20793)
    at Bn (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:39553)
    at /Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:37905
    at Lu (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:1:1694)
    at Immediate.zu [as _onImmediate] (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:1:2088)
    at process.processImmediate (node:internal/timers:478:21)
09:51:29.441 
SyntaxError: Unexpected end of JSON input

AranetCommand:aranet.tsx:28:15

---
25: };
26: 
27: export default function AranetCommand() {
28:   const data = useGetData();
29: 
30:   const tempType = getPreferenceValues<{
31:     temperature: TemperatureType;
---

Dr:index.js:11:2490
    at ray-navigation-stack
Lo:index.js:11:2088
```

**Comment by WilliamWelsh** [comment]
@pernielsentikaer Did you install Aranet from the app store and the claranet CLI? I put it in the README. If you didn't, what do you suggest for telling them to do so? I could make maybe the dialog error thing, or replace my list of data with a list of links?

**Comment by pernielsentikaer** [comment]
You can see how extensions like [Eagle](https://www.raycast.com/Yukai/eagle) does it, I think you can do something similar

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
There seems to be an issue with the menubar command that doesn't unload correctly, could you look into this? Might be because its getting a wrong response back?

It should always return false if not loading

**Pull request closed without merging**
