### PR TITLE
Add remove-whitespace-characters extension

### PR DESCRIPTION
**Pull request by klkvsky**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by klkvsky** [comment]
P.S. I created this extension for the sole purpose of using it in combination with Raycast AI. I noticed that when I try to format text for better segmentation while copying code from an IDE and surrounding it in ``` tags, it does not detect it properly due to all the whitespaces. So I started using other online tools for that. However, removing new lines, spaces, and tabs actually has its benefits. You use fewer tokens and can input a larger file. AI still understands your code, has no issues with readability, and helps to separate the actual prompt from the context I provide.

**Comment by pernielsentikaer** [comment]
That might already be possible with the [Pipe Commands](https://www.raycast.com/pomdtr/pipe-commands) extension 🙂 

Could you check that extension out 🚀

**Comment by klkvsky** [comment]
Oh, you're right! But I wish this extension would allow me to set a hotkey for some action or choose one of those as a "quick" action. To achieve the same result as my extension, I have to search for the proper subcommand each time.

**Comment by klkvsky** [comment]
@iloveitaly Is that something you were considering implementing, or is it even possible with the current API? I would love to contribute to your extension!

**Comment by pernielsentikaer** [comment]
Quick actions could be a thing, the extension it made by @pomdtr 🙂

You can make a feature request by using this action

Raycast 2024-01-09 at 10 54 27

**Comment by iloveitaly** [comment]
@klkvsky you could definitely trim whitespace chars with the current API, not sure about hotkeys. Could be something to look into, totally down for adding hotkeys in!

**Pull request closed without merging**
