### PR TITLE
New Extension: MenuTime

### PR DESCRIPTION
**Pull request by Ek2100**
Jazz up your menubar with customization your way with MenuTime! Add custom text that you can chose from the menutime preferences!
mac-os-x-os-x-big-sur-hd-wallpaper-preview
SCR-20221005-mjg

### CODE REVIEW

**Comment by Ek2100** [comment]
Sorry,  not sure why first image is so blurry

**Comment by pernielsentikaer** [comment]
Hi 👋 

The time `MenuTime` doesn't really make any sense, maybe better call it `MenuItem` or something like that, it does the same as [this app](https://mermodynamics.com/doonething/) - what do you think about naming?

**Comment by TopClips** [comment]
> Hi 👋
> 
> The time `MenuTime` doesn't really make any sense, maybe better call it `MenuItem` or something like that, it does the same as [this app](https://mermodynamics.com/doonething/) - what do you think about naming?

I guess but I’m not sure

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Ek2100 👋 

I added some new stuff and updated the extension, could you give it the last spin before adding it to the store?

**Comment by Ek2100** [comment]
> Hi @Ek2100 👋
> 
> I added some new stuff and updated the extension, could you give it the last spin before adding it to the store?

Im not really working on the extension anymore. You can take over the extension.

**Comment by Ek2100** [comment]
I am very glad to see how the extension has grown. Great job.

**Comment by Ek2100** [comment]
This was the first ever development project i have ever done. i am a student so i will maybe make another project for raycast.

**Pull request merged**
