### PR TITLE
Add Finnish Dictionary

### PR DESCRIPTION
**Pull request by albertoxamin**
## Description

MacOS has a great dictionary, but it's not available for Finnish. This extension adds a Finnish dictionary at your fingertips.

## Screencast

image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by sxn** [comment]
hi @albertoxamin - nice work! One suggestion: could you add an [EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) when either of the commands is started? Greeting the user with a `No Results` screen feels a bit harsh 😺 

image

**Comment by albertoxamin** [comment]
I've added an EmptyView! 
image

**Comment by sxn** [comment]
hi @albertoxamin - hope you don't mind, I did a couple of fixes:
- once I started typing, the empty view disappeared and the `No results` screen was shown briefly, so I fixed the condition so this doesn't happen anymore
- once the search text changed, we then performed an API call for each result, potentially resulting in tens of unnecessary calls. I updated the extension so that this is done "on demand", i.e. only when a particular item is selected.

https://user-images.githubusercontent.com/1155589/162731616-44e45fed-1c7a-40a6-934f-c6da61f0ec80.mov

Additionally, I've noticed that quite often, definitions look "broken" due to the markup the API returns. Do you think there's something we can do there? Either make the links work or clean them up?

image

**Comment by albertoxamin** [comment]
Thanks for fixing that, that was the behaviour I originally had in mind, unfortunately I'm quite new to react.
I'll look into adding more regexes to make it look cleaner!

**Comment by sxn** [comment]
nice! 🎉

**Comment by albertoxamin** [comment]
Great! However I noticed the screenshots are missing from the store page, how do I fix that? @sxn

**Pull request merged**
