### PR TITLE
Hypersonic: New version 0.0.3

### PR DESCRIPTION
**Pull request by tonimasc**
## Description

- Update Raycast to "@raycast/api": "1.39.2"
- Update Raycast to "@raycast/utils": "1.4.0"
- Update Notion to "@notionhq/client": "2.2.0"
- Major refactor of the code using the new useCachedPromise hook.
- Added support for custom properties database names.
- Added support to complete tasks using the new status property from notion.
- Added support for In progress status when using the new status property.
- Better integration with notion fetching todos created directly from there without date and name.
- Change authorize command to `cmd + shift + A`.
- New menu bar command to interact with your todos and background fetching

## Screencast
unknown (1)

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by prrrcl — APPROVED** [review]
Looks great!! 

Thanks for your contribution! @tonimasc

**Comment by tonimasc** [comment]
All the requested changes have been applied in the latest commit @pernielsentikaer

**Review by pernielsentikaer — COMMENTED** [review]
Hi @tonimasc 👋 

When I opened the first two times I got into this screen, the text in the Emptyview is not matching the ActionPanel, is this something you can look into?

CleanShot 2022-09-20 at 07 35 44

When I opened it the third time it was looking like that

CleanShot 2022-09-20 at 07 40 41@2x

I don't have anything from the console to share since I didn't have the console open, maybe it was just a quirk?

**Comment by tonimasc** [comment]
> Hi @tonimasc 👋
> 
> When I opened the first two times I got into this screen, the text in the Emptyview is not matching the ActionPanel, is this something you can look into?
> 
> CleanShot 2022-09-20 at 07 35 44 [ CleanShot 2022-09-20 at 07 35 44 ](https://user-images.githubusercontent.com/38033107/191175773-44c9bc87-cc96-4101-998d-e226369246bb.gif) [ ](https://user-images.githubusercontent.com/38033107/191175773-44c9bc87-cc96-4101-998d-e226369246bb.gif)
> 
> When I opened it the third time it was looking like that
> 
> CleanShot 2022-09-20 at 07 40 41@2x
> 
> I don't have anything from the console to share since I didn't have the console open, maybe it was just a quirk?

After analysing this issue, found that in some cases when you authorize first and then change the authorized database the app has a buggy behaviour due to the caching strategy.

Is there a way to do conditional fetching between useCachedPromise similar to [swr](https://swr.vercel.app/docs/conditional-fetching) ? I couldn't find the use case in the docs.

If not I may use only one useCachedPromise hook that includes the getDatabase and the getTodos operations, this way I can simplify the fetch operation.

The only bad think of this strategy is that on revalidation it will make the both fetch operations when only the getTodos is needed.

Any advice on this? @pernielsentikaer

**Comment by mathieudutour** [comment]
> Is there a way to do conditional fetching between useCachedPromise similar to [swr](https://swr.vercel.app/docs/conditional-fetching) ?

Yes, you can set `execute: false` in the options of the hook:

> options.execute is a boolean to indicate whether to actually execute the function or not. This is useful for cases where one of the function's arguments depends on something that might not be available right away (for example, depends on some user inputs). Because React requires every hook to be defined on the render, this flag enables you to define the hook right away but wait until you have all the arguments ready to execute the function.

**Comment by tonimasc** [comment]
In the latest commit the execute options was applied to the useTodos hook, also added some custom error messages.

With this changes the extension should be more stable when handling user auth changes.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by rdewolff** [comment]
Looks really amazing, thanks for the clean work!

**Pull request merged**
