### PR TITLE
Add blockchain-gas-tracker extension

### PR DESCRIPTION
**Pull request by vonernue**
## Description
An extension to track and caculate gas fees on various blockchain network

### API Keys
Add API keys in extension preferences to utilize API without being rate limited.
image
### Feature Screenshots
blockchain-gas-tracker-1
blockchain-gas-tracker-2
blockchain-gas-tracker-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I'm not really into this blockchains and such, is this a bit like https://www.raycast.com/vinch/ethereum-gas-tracker

**Comment by vonernue** [comment]
> I'm not really into this blockchains and such, is this a bit like https://www.raycast.com/vinch/ethereum-gas-tracker

Yes it is. 
However, I added support for different blockchains and designed it in commands instead of taking up menu bar spaces. 😄

**Comment by pernielsentikaer** [comment]
If it's the same data, why not make a PR to the current one and add it as a new command instead? 😊

**Comment by vonernue** [comment]
> If it's the same data, why not make a PR to the current one and add it as a new command instead? 😊

For the added functionalities and the difference in UI, I don't think it's good choice to merge them together. Even the naming will make it a bit misleading, IMO.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
