### PR TITLE
Add touchdesigner extension

### PR DESCRIPTION
**Pull request by iplanwebsites**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by iplanwebsites** [comment]
Not sure why prettier isn't working. Can you please let know how to fix it? 
repo: https://github.com/iplanwebsites/raycast-touchdesigner

**Comment by pernielsentikaer** [comment]
I fixed the linting issue, can you check the CI error now?

**Comment by pernielsentikaer** [comment]
Do you need any help here?

**Comment by iplanwebsites** [comment]
Hi!
Yes not too sure what's missing to bring this tiny extension accross the
finish line 😅
F

**Comment by pernielsentikaer** [comment]
Can you check that I didn't break something? 🙂

**Comment by iplanwebsites** [comment]
looks good!

**Comment by pernielsentikaer** [comment]
I'm not sure if the command naming is correct (I don't know since I'm not familiar with this service). Can you check?

**Pull request closed without merging**
