### PR TITLE
feat: add default action pref for npm search

### PR DESCRIPTION
**Pull request by FezVrasta**
## Description

Users can now decide what to do when they press Enter on a entry row.

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @mrmartineau

## Screencast

https://user-images.githubusercontent.com/5382443/142480174-67d4be39-15fa-4ea5-bf97-9953047125ce.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @FezVrasta 👋 

Seems like a good addition, and it works as it should — do you have any feedback @mrmartineau 😄

**Review by mrmartineau — CHANGES_REQUESTED** [review]
Other than the `key` issue that @pernielsentikaer mentioned, I think this is a great addition to the extension. Once that is sorted, I am happy with the changes.

**Comment by FezVrasta** [comment]
Fixed

**Review by pernielsentikaer — APPROVED** [review]
Hi @FezVrasta 👋 

Much better, let's get this great addition added 🚀

**Pull request merged**
