### PR TITLE
Update to Raindrop.io extension

### PR DESCRIPTION
**Pull request by lardissone**
## Description

Adds the sort parameter to Raindrop API to always display results sorted by descendant creation date.
In their docs it's the default but in practice it didn't worked.

## Type of change

- Bug fix / improvement for my extension

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi @lardissone 👋 

I have now tested this and confirming that nothing breaks with this new PR 💪 

It seems like `Latest Bookmarks` suffers from [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) - could you address this?

**Comment by lardissone** [comment]
hi @pernielsentikaer sorry for the delay.

I think it's already covered here: https://github.com/raycast/extensions/blob/cd8b6ab1a88460690ddab6870e6b31c35901993d/extensions/raindrop/src/latest_bookmarks.tsx#L14

Maybe another issue?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @lardissone 👋 

Thats correct, but your initial state is set to loading = false [right here](https://github.com/raycast/extensions/blob/main/extensions/raindrop/src/utils.ts#L22) - change that to `true` and the flicker should be gone 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by lardissone** [comment]
Hi @pernielsentikaer!

Got it! Just fixed it! 
Thank you for your help!

**Review by pernielsentikaer — APPROVED** [review]
Awesome @lardissone, much better 🔥 

Thanks a lot for your contribution 💪 

I'm going to accept it and then will my colleague do a final review before it's finally merged 🚀

**Pull request merged**
