### PR TITLE
[Amazon AWS] feat: glue command

### PR DESCRIPTION
**Pull request by b0lle**
This reopens https://github.com/raycast/extensions/pull/13316

I implemented the changes required in the mentioned PR from @jfkisafk. This improves the performance of the feature very well!

### CODE REVIEW

**Comment by b0lle** [comment]
I am facing issues when changing the account, sorry.

**Comment by pernielsentikaer** [comment]
Do you need any help @b0lle

**Comment by b0lle** [comment]
Hey @pernielsentikaer, when I run the extension with `npm run dev --verbose`, it runs as expected.
But when I build it, using `npm run build`, I am facing this screen
image
May you have a look?

**Comment by pernielsentikaer** [comment]
I'm not sure how to test this since I don't use AWS - do you @jfkisafk?

**Comment by b0lle** [comment]
May you have any idea @pernielsentikaer ? I think this is not an issue with the aws resources itself, but with the way of how I query those. Unfortunately I am a beginner in Typescript. For my understanding I tried to make sure that no process is loading and that the functions attribute is already loaded, but correct me, if I am wrong.

**Comment by pernielsentikaer** [comment]
What happens if you debug it, adding console.log() right before calling `GlueRun` - at some point it must be null?

**Comment by b0lle** [comment]
it logs me the correct object. Its not null - otherwise debugging this would be less complicated ;)

**Comment by pernielsentikaer** [comment]
I'm not sure how I can test this, I'd like to give it a go but I don't have anything related to AWS. Could we add a simple check for it, just in case?

**Comment by b0lle** [comment]
No with this issue I wouldnt give it a go ;)

**Comment by b0lle** [comment]
@pernielsentikaer fixed it, ready for review

**Review by pernielsentikaer — APPROVED** [review]
Let's merge it and see how it goes 🙂

**Pull request merged**
