### PR TITLE
Update file-manager extension

### PR DESCRIPTION
**Pull request by fengtianze**
## Description

I have modified the shortcut for "Move to Trash" (cmd + T -> ctr + X) so that it is consistent with the shortcuts for "File Search", "Folder Search" and other deletion operations. 

This may be inconvenient for users who are used to the old shortcuts, but it is more user-friendly for new users and those who use other plugins at the same time.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by BalliAsghar — COMMENTED** [review]
Changing the hotkeys from cmd + t to ctrl + x will affect existing users who are used to the old hotkeys. There is no need for that!

**Comment by urwrstkn8mare** [comment]
If this is something that you'd really like consider adding it as an optional feature users can enable.

**Comment by fengtianze** [comment]
> Changing the hotkeys from cmd + t to ctrl + x will affect existing users who are used to the old hotkeys. There is no need for that!

It is indeed the case, but ctr + x is more user-friendly for those accustomed to using other plugins.

How about adding a configuration option with a default value of cmd + T?

However, raycast plugins usually don't support custom shortcuts, so users may not know that it is configurable. Is there a solution to use cmd + T when updating the plugin and ctr + X when installing the plugin for the first time? @urwrstkn8mare

**Comment by fengtianze** [comment]
@urwrstkn8mare @BalliAsghar I pushed new code, please check age.

I don't know enough about raycast and file manager.  very sorry for taking up your
 time.

**Comment by fengtianze** [comment]
@urwrstkn8mare @BalliAsghar Please check this PR again and provide some feedback. 
or i can close this PR, if you don't like this change,

**Review by urwrstkn8mare — APPROVED** [review]
yep lgtm 👍 

(sry wasn't notified before for some reason)

**Comment by BalliAsghar** [comment]
> @urwrstkn8mare @BalliAsghar Please check this PR again and provide some feedback. or i can close this PR, if you don't like this change,

Please slove merge conflicts!

**Comment by urwrstkn8mare** [comment]
Woops mb for not seeing that 👀

**Review by urwrstkn8mare — APPROVED** [review]
lgtm 👍

**Comment by fengtianze** [comment]
> > @urwrstkn8mare @BalliAsghar Please check this PR again and provide some feedback. or i can close this PR, if you don't like this change,
> 
> Please slove merge conflicts!

done.

**Review by urwrstkn8mare — APPROVED** [review]

**Review by BalliAsghar — APPROVED** [review]
Ready to merge! 👍

**Comment by fengtianze** [comment]
@pernielsentikaer Please check this

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
