### PR TITLE
[Raycast Notification] Added success and failure notification types

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- Moved screenshots to metadata folder and used raycast colors for the command icon.
- Supported success and failure notification types with Toast API.

## Screencast

Added new screenshots in metadata.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

* closes https://github.com/raycast/extensions/issues/13957
* closes https://github.com/raycast/extensions/issues/13956

### CODE REVIEW

**Comment by maxnyby** [comment]
Thanks for the improvements @jfkisafk !
If the toast API some day supports launchType background (or if someone comes up with a hack to prevent the flickering Raycast window) we can improve upon it even further then.

But for now, this looks great!

**Comment by jfkisafk** [comment]
Cool thanks @maxnyby ! @pernielsentikaer can you please take a look and merge when you find some time?

**Comment by jfkisafk** [comment]
Hello @pernielsentikaer, can we please get some traction here?

**Comment by njthebaud** [comment]
Exactly what I was looking for...looks great! Hopefully they allow for it to run in the background...that's the only thing keeping me from using it at the moment.

**Pull request merged**
