### PR TITLE
Update google-chrome extension for Google Chrome tabs and history, bookmarks search

### PR DESCRIPTION
**Pull request by flyyuan**
## Description
Add Google Chrome tabs and history, bookmarks search

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by flyyuan** [comment]
#11202

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @flyyuan 🔥 

@rgomezcasas can you check this?

**Comment by a-laughlin** [comment]
@raycastbot keep this issue open

**Comment by a-laughlin** [comment]
@raycastbot reopen this issue

**Comment by flyyuan** [comment]
> @raycastbot reopen this issue

You could clone my repo for it, if you want to use it now.

**Comment by a-laughlin** [comment]
It takes a fair amount of work to put in a PR, and closing it as stale disrespects that effort.

I haven't tested this PR, though the code looks equivalent in quality to the rest of the extension code.

@pernielsentikaer , can we trust that @flyyuan didn't break the extension and merge this?

Not sure about others on the list, but I don't remember how to even test that the changes don't break the extension, and don't want to spend time relearning how to work on the extension, and manually test it, for a feature I don't use. Ideally we could trust that the author didn't break the extension, but if they do, have a raycastbot command to roll it back so we don't have to put in more work to re-learn and verify changes.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
First thing I notice is this view, and yes, I don't have any bookmarks, but I guess that `Search All` should search across all tabs, history and bookmarks?

google-chrome 2024-06-04 at 12 10 45

**Review by a-laughlin — COMMENTED** [review]
Thanks for checking it @pernielsentikaer 

@flyyuan I added two suggested changes to fix the error and improve code understandability.

**Comment by flyyuan** [comment]
Yes, I will fix some errors

**Comment by cdbattags** [comment]
Any updates here? I'm seeing that tab search is broken and more than happy to fix it myself but want to work off of this effort.

**Comment by a-laughlin** [comment]
I created a [new PR](https://github.com/raycast/extensions/pull/13836) since this one is stalled

**Pull request closed without merging**
