### PR TITLE
Update crisp extension, make Supabase session fetching faster

### PR DESCRIPTION
**Pull request by remorses**
## Description

Before this change calling `setSession` was taking 500ms on average, now it only takes 15ms

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mil3na — COMMENTED** [review]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

I was not able to test this, as creating an account asks me for a payment method. Is there another way to try your extension? A video/screencast might be useful as well.

Also, could you please clean up the debug console.logs?

**Comment by remorses** [comment]
> Is there another way to try your extension?

Hi, unfortunately right now there is no way to try the extension without buying the Crisp plugin but the previous PR was already reviewed and the extension was tested working, this is just a small change to make the command load faster.

If you really want to try the extension yourself maybe i can find a way but it would be different than the typical user workflow so I don't think it serves any utility.

> Also, could you please clean up the debug console.logs?

I want to keep the profiling logs so you can clearly see what parts of the extension takes the most time, the logs are shown only in development so it does not impact users.

**Comment by remorses** [comment]
Here is a screen recording of the extension working

https://github.com/raycast/extensions/assets/31321188/a51f1bb4-0c4e-40e1-87d3-9b9f1e38faba

**Comment by remorses** [comment]
I removed the console logs and fixed a type error that appeared in the Raycast bug tracker

**Review by mil3na — APPROVED** [review]
👍

**Pull request merged**
