### PR TITLE
Color Picker: Use Raycast Swift Macro

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

Migrate the extension to use the [Raycast Swift Macro](https://github.com/raycast/raycast-extension-macro) instead of manually compiling the Swift code into a binary.

There should be no changes feature-wise.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaspaulmann — APPROVED** [review]
Thanks for updating it to our Swift helpers! Very nice how much simpler the setup got.

**Comment by otakustay** [comment]
Hi, I'm working on #8534 and encountered a swift compile problem

```
npm run build

> build
> ray build -e dist

info  -  entry points [src/pick-color.ts src/menu-bar.tsx src/organize-colors.tsx]
error -  compiling swift package
build failed (src/pick-color.ts:5:26 import { pickColor } from "swift:../swift/color-picker";): failed to compile swift:
exit status 1

If this is unexpected, try to delete the color-picker/swift/color-picker/.raycast-swift-build folder and run this command again
```

After the switch to Raycast Swift Macro, I'm not able to figure out how to build it, I've read [the official docs](https://github.com/raycast/raycast-extension-macro) but get no clue, can you give some help on this?

**Comment by otakustay** [comment]
I tried to upgrade it to 1.0.0 which uses `@raycast` instead of `#exportFunction` and `#handleFunctionCall`, however I can't build it via `build` script.

I don't have background knowledge of swift development, do I need to open XCode to compile this extension, or I could just get to sucess by simply using `npm run build`?

**Comment by thomaslombart** [comment]
@otakustay Thinking about it, it may be a bit complex to do this migration, especially since the Swift Macro is quite new. I'll migrate it and get back to you 🙂

**Pull request merged**
