### PR TITLE
Add support for Zen Browser Desktop bookmarks.

### PR DESCRIPTION
**Pull request by theherk**
## Description

This is an amalgam of the Firefox implementation in the same extension and the seach method used in the Zen Browser extension.

Fix: #15130

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I gave this a try, but I can't see any bookmarks from Zen after enabling it? I also tried restarting Zen and Raycast without any changes 🫠

image

**Comment by theherk** [comment]
Interesting. Assuming your have Zen selected in the Select Browser interface, have you checked your profile folder in about:profiles. If it isn't the alpha suffix, we may have to work on the select profiles logic.

**Comment by theherk** [comment]
Screenshot 2024-11-25 at 13 16 31

I see. For me, just the one. So, I'm not sure the best way to handle that. But when I'm no longer at work, I can try some things. Maybe we need a select other profile option. So even if it finds the alpha profile, one can select another if the other is housing the bookmarks. Open to suggestions.

**Comment by theherk** [comment]
@pernielsentikaer: This should be fixed now. Give it another whirl. The path was being constructed badly. I even added some test multi-profile setups and the profile switcher works fine now.

**Comment by pernielsentikaer** [comment]
That was better 🙂

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
