### PR TITLE
Add user-agent extension

### PR DESCRIPTION
**Pull request by third774**
## Description

Adds an extension that grabs selected text and parses any available User-Agent information from it to display.

## Screencast

https://github.com/raycast/extensions/assets/8732191/56ce26d4-b131-49a2-9efc-ab2584ad3c5f

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Add a [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

- Handle this gracefully (if no text is selected)

https://github.com/raycast/extensions/assets/38033107/69cf786e-d757-4437-b8e8-0e9a98e3ca3f

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by third774** [comment]
Hrm, it says that the metadata image is too small, but I generated it using Raycast's built-in method of capturing it. Will capture one manually and update soon. 😅

image

**Comment by third774** [comment]
Ah, I took the screenshot on my non-HDR monitor which resulted in a smaller image. Should [these docs](https://developers.raycast.com/basics/prepare-an-extension-for-store#adding-screenshots) be updated to include a note about this?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
