### PR TITLE
Update dust-tt extension

### PR DESCRIPTION
**Pull request by vineus**
## Description

small design update: add icons

## Screencast

Links look better 😉 

image

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by vineus** [comment]
Failing test: https://github.com/raycast/extensions/actions/runs/7141734286/job/19449546598?pr=9610

> Error: Parameter token or opts.auth is required

😬 

(I have a changelog)

**Comment by pernielsentikaer** [comment]
I'll look into the issue with the changelog bot @vineus 🙂

**Comment by vineus** [comment]
> I'll look into the issue with the changelog bot @vineus 🙂

thank you so much! I edited the changelog as the date on the last one was wrong 🤦 

I tried to remove the changes to no avail (I cancelled the tentative fix)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
