### PR TITLE
Added support for Threads Insights.

### PR DESCRIPTION
**Pull request by chrismessina**
Quickly post to Threads and follow users.

Uses Threads's Web Intents as a base.

### Added
- New command: "Open Threads Insights" to quickly access Threads Insights for different time periods (7, 14, or 30 days).

### Changed

Tweaked ESLint configuration and fixed some minor formatting issues.

## Screenshot

threads-8

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npx ray build -e dist` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @chrismessina 👋 

Could you try to get the extension from the store and make a Fork? Feels like something is wrong with this one too 🙂

**Comment by chrismessina** [comment]
> Could you try to get the extension from the store and make a Fork? Feels like something is wrong with this one too 🙂

Oy, strange this keeps happening. Yes, I'll try. Meanwhile, will convert this to a draft so I have the changes in case they go missing locally.

**Comment by chrismessina** [comment]
Bumping.

**Comment by chrismessina** [comment]
Bumping.

**Comment by chrismessina** [comment]
Working on this tonight.

**Pull request closed without merging**
