### PR TITLE
Add NBA Viewer Extension 🏀

### PR DESCRIPTION
**Pull request by AbhinavPalacharla**
## Description

Added NBA Viewer Extension, has commands to display upcoming NBA games, and to display team rankings

## Screencast

Screenshot

Screenshot-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mattisssa — CHANGES_REQUESTED** [review]
Hey! Thanks for the extension, everything seems to be good and I like the icon very much 👍 

One thing I noticed is that the views don't show the loading indicator properly. Check my screencast to understand what I mean:
https://user-images.githubusercontent.com/15333662/170470351-346f47f4-1569-4d5d-b5dc-279dc70668f5.mp4

It could happen due to returning an empty array to the `List`. Let me know if you need any help with it.

**Comment by AbhinavPalacharla** [comment]
I'm glad you liked the icon, I took inspiration from the F1 Standings extension icon. Just fixed the flashing loading bug.

**Review by mattisssa — APPROVED** [review]
Good! Thank you for the quick fix.

**Comment by mattisssa** [comment]
@AbhinavPalacharla oh! What I completely forgot post with suggestions is Subtitles for your commands 🙈 
Let me quickly add them into the `main` branch`

**Comment by AbhinavPalacharla** [comment]
Alright sounds good. I'm good with whatever you add.

**Comment by mattisssa** [comment]
I've done it 😉 
It should be on the `main`.

**Pull request merged**
