### PR TITLE
feat: Updated Gitpod Extension for Raycast Public Store

### PR DESCRIPTION
**Pull request by henit-chobisa**
## Description

https://github.com/raycast/extensions/assets/72302948/c76fbcce-afa4-483f-953c-9eee67f70a9a

# Key Features
## Navigating Contexts
With the `Open Context from Github` Command, it's incredibly easy to navigate contexts such as `Repositories`, `Branches`, `Pull Requests` and `Issues`.

### Browsing and Filtering 
- You can browse Repositories and also any context URL inside of the repository i.e. it's branches, PR or Issues
Browse Repository

Inside Repository

- Along with that we make sure that your browsing experience should be super smooth with the help of filtering 
You can filter and search further using the following tags
      - `/b` for branch
      - `/p` for PRs 
      - `/i` for Issues
      - `/me` for anything and everything related to 
         - eg. `/me /p` would refer to your Pull Requests in a particular repository!

### Displaying Contexts
Say you're a product manager or an OSS maintainer, you're tired of opening GitHub again and again browsing through issues/prs to find the right one to solve/review, we got you covered by providing context previews, so that you can have a glimpse on Issues/PRs on the fly.

Search PR Open

### Pinning Contexts for Faster Access
We pin every context that you open with Gitpod, for faster access and if you wish to manually add any context to your Recents/Pinned list, you can achieve by a single command `cmd` + `R` and bingo!
Issue Recent Success
Add To Recent Issue

### Opening Contexts with Github
If Context Display is not enough and you need a deep dive in conversation or add any labels, you can open contexts directly in Github with a single command `cmd` + `RETURN`
View in Github Issue

### Starting Workspaces (Requires Gitpod Access Token)
Using the `Managing Workspace` Command, you can *Start* and *launch* your workspaces in your preferrred IDE.
The extension shows you all the stages of your workspaces, Running, Progressing and Stopped.

https://github.com/gitpod-samples/Gitpod-Raycast-Extension/assets/72302948/5cb4887f-b6b2-4a55-941c-ea77706ec8a4

https://github.com/gitpod-samples/Gitpod-Raycast-Extension/assets/72302948/5cafa2ed-9276-4a3a-9325-bbe4962eae96

Wait!! There is more, with `Menubar Workspace` Menubar command, to do this which is the key feature for `Gitpod Accessibility faster than local.`

https://github.com/gitpod-samples/Gitpod-Raycast-Extension/assets/72302948/6ce6ebb7-5f3e-48ce-909d-8e624349eff7

### Stopping Workspaces (Requires Gitpod Access Token)
You can use a simple command `Cmd + s`, on the running workspaces and you can see them stopping in real time, just like magic ✨

https://github.com/gitpod-samples/Gitpod-Raycast-Extension/assets/72302948/c0288710-ec4e-4e4a-add1-31d53f74230a

### Selecting Default Editor to Open
You can also select your favourite editor for opening your workspaces, just go to Command Preferences of the Raycast extension with `cmd + ,` and change the default editor, currently the extension supports `VSCode Browser`, `VSCode Desktop` and `SSH` (in your default ssh client with which you can even use VIM, checkout [axonasif/dotsh](https://github.com/axonasif/dotsh).

Changing Editor

## Creating New Workspaces
Currently the extension supports two types of creating workspaces, 
1. Creating Workspaces from Context
2. Creating Empty Workspaces 

### Creating Workspaces from Context 
( Requires Gitpod Access token)
You can browse through contexts in the `Open Context from Github` Command and can create a workspace directly from the there just by using `cmd + g`, g for Gitpod.

https://github.com/gitpod-samples/Gitpod-Raycast-Extension/assets/72302948/51dd9170-2f6c-46f1-bca5-7531eaf8f872

### Creating Empty Workspaces 
For creating empty workspaces on the go, say for some quick experimentation, you can use both the `Open Context Command` or `Menubar` Command

https://github.com/gitpod-samples/Gitpod-Raycast-Extension/assets/72302948/73e39949-a2f2-46a1-8604-d5f3917d1133

https://github.com/gitpod-samples/Gitpod-Raycast-Extension/assets/72302948/a6d30561-bf38-49ad-b0cb-d5819e8c3f4a

## Feedback
At last, we would love 🧡 to hear from you to improve the extension, hence we also put a command called `feedback`, so that you can report any issue in the extension or you can make a feature extension.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Palanikannan1437** [comment]
Hey @pernielsentikaer, please check this out, thanks...tons of exciting changes 😄

**Comment by jobenjada** [comment]
cant wait for this!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
- I can't submit this form, do I miss something?

https://github.com/raycast/extensions/assets/38033107/02207492-6780-4984-b822-d480cfe3e11e

- Don't change the `navigationTitle` in the root command - it will be automatically set to the command name. Use `navigationTitle` only in nested screens to provide additional context.

**Comment by henit-chobisa** [comment]
Hey @pernielsentikaer, I have updated the feedback form, it responds with Success Message on submission. ✌🏼
gitpod-6
gitpod-7

**Comment by pernielsentikaer** [comment]
Hi 👋 

I rewrote the feedback command, I hope you're okay with it 🙂 Let me know if I broke something 🙂

**Comment by henit-chobisa** [comment]
> Hi 👋 
> 
> 
> 
> I rewrote the feedback command, I hope you're okay with it 🙂 Let me know if I broke something 🙂

Thanks! @pernielsentikaer

**Comment by Palanikannan1437** [comment]
> Hi 👋 
> 
> I rewrote the feedback command, I hope you're okay with it 🙂 Let me know if I broke something 🙂

Thanks for taking the time @pernielsentikaer, you're amazing!!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
