### PR TITLE
feat: add preferences to Banca d'Italia Currency Converter

### PR DESCRIPTION
**Pull request by FezVrasta**
## Description

Users can now specify how many decimals they want to see in the extension. Also, the last set of currencies will be remembered the next time the user opens the extension.

## Screencast

CleanShot 2022-02-16 at 6 25 56@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by Aayush9029** [comment]
Is it just me or the title says "add Emoji extension #923" and I don't see this being related to Emoji at all.

**Comment by FezVrasta** [comment]
my bad, github strikes again

**Comment by pernielsentikaer** [comment]
Hi @FezVrasta 👋 

Awesome work 🔥 

A question, does it make sense that `From Amount`'s default value is formatted with decimals?

Shouldn't that just show 1 as default?

Works as expected, well done though 🔥

**Review by pernielsentikaer — APPROVED** [review]
Hi @FezVrasta 👋 

MUCH better 🔥

**Review by mathieudutour — APPROVED** [review]

**Pull request merged**
