### PR TITLE
F1: Try to fetch Formula1.com driver/race/constructor links.

### PR DESCRIPTION
**Pull request by sxn**
## Description

Updates extension to try to link driver/constructor/races to their respective Formula1.com page. It does this by making a request to the standings' respective `formula1.com` page and crawling the result 😅 

I've also passed all of the assets through ImageOptim, hence the high number of changed files.

## Screencast

https://user-images.githubusercontent.com/1155589/160470772-aaeba4ed-90ec-4ed7-a616-47e93f0bc3ca.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by csigritz** [comment]
@sxn Thx. Great addition
But I would be careful when using official F1 Assets (the icon in the action section). I heard that they are not the nicest guys when it comes to copyright.

**Comment by sxn** [comment]
good point @csigritz. Checking the FIA's guidelines https://www.formula1.com/en/toolbar/guidelines.html it indeed seems like we're _probably_ not allowed to use the logos. Weird, since it's the favicon, but yeah let's change it. I'll use the extension's logo for the empty view, and the flag icon for the Formula1.com action 🤔 unless you have other suggestions of course!

**Comment by sxn** [comment]
The F1™ logo should be gone now, and added the new icon you made:

https://user-images.githubusercontent.com/1155589/160768057-5a46aaf7-021a-40c3-9214-556321d1d3b0.mov

**Comment by sxn** [comment]
F1™ logo's now gone. I've also replaced the `command-icon` with the new one you made, and used (a smaller version of) it on the empty view as well.

https://user-images.githubusercontent.com/1155589/160768752-3156f086-f94a-4f5e-bd04-9bcaca36af03.mov

**Comment by csigritz** [comment]
Looks good now. I only found one small thing. The Wiki Action in RaceSchedule is still titled "Open in Browser". In Driver and Constructor Standings it is called "View on Wikipedia.org". Should we align the titles?

Race Schedule:
Bildschirmfoto 2022-03-30 um 09 08 56

Driver Standings:
Bildschirmfoto 2022-03-30 um 09 09 13

**Comment by sxn** [comment]
oops - good catch! should be fixed now 😅

**Review by csigritz — APPROVED** [review]

**Pull request merged**
