### PR TITLE
Himalaya: Add background sync

### PR DESCRIPTION
**Pull request by jesse-c**
## Description

Emails come and go. This adds a `no-view` command that gets the envelopes and folders. It uses the cache as a pass-between it and the `index` command. I'd use `useCachedState` but I don't think you can in a `no-view` or `menu-bar` command.

As some people may have very large inboxes, there's still improvements to be made around state and cache.

Along with this, I've refactored some of the code to be split into modules. Again, there's still room to be done here later.

## Screencast

N/A

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the update @jesse-c 🔥 Do you mind adding a changelog entry 😊

**Comment by jesse-c** [comment]
Thanks for the linting too! And the reminder about the changelog. 🤦🏻 I've updated the changelog now.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by jesse-c** [comment]
Thanks again!

**Pull request merged**
