### PR TITLE
Add renaming extension

### PR DESCRIPTION
**Pull request by theodaguier**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You can use [GetSelectedFinderItems](https://developers.raycast.com/api-reference/environment#getselectedfinderitems) from our API to get selected files

- You should use runAppleScript from [@raycast/utils](https://www.npmjs.com/package/@raycast/utils) instead of doing it yourself 

 - I was a bit confused about the "Preserve base name", I would move it first in the fold and only show the New Name field if unticked

- Bonus, you could also show a live preview of the new filename - not sure if that's doable 🙂

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by theodaguier** [comment]
@pernielsentikaer Thank you for your detailed feedback. I just updated the extension according to the requested changes 🙂

**Comment by theodaguier** [comment]
> Hi 👋
> 
> I fixed a bug in the preview if no action was performed, also made so it's remembering state of `Preserve base name` since I think that most of the users will keep the setting.
> 
> Could you give it a spin to ensure I didn't break something 🙂

Everything is perfect thanks !

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
