### PR TITLE
Update howlongtobeat extension

### PR DESCRIPTION
**Pull request by whitespacecode**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Cronos87** [comment]
For me it's perfect, nothing to say about it! Thank you very much @whitespacecode for the fix!

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

I still get 404 when testing this PR, did it break again? 🙂

howlongtobeat 2024-08-07 at 07 18 02

**Comment by whitespacecode** [comment]
Apparently they automatically change the api with a new hash after x time.. 
https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/issues/25

Not sure what the best way would be to get that hash updated every time ?

**Comment by pernielsentikaer** [comment]
Would it make sense to reach out to them to see if there is a better solution

**Comment by whitespacecode** [comment]
I have found a way to get the required hash. 
What would be preferable to save the hash? Using preferences or cache?

**Comment by pernielsentikaer** [comment]
We can't use preferences since you can't update values there. I think the most suitable place for this is the cache 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
