### PR TITLE
Create 'Code Stash' store extension

### PR DESCRIPTION
**Pull request by ben-greenwood**
## Description
As the saying goes: "Searching git.. now you have two problems"

This is a simple extension to temporarily stash code that you do not need at that particular moment in time.

I often find myself needing to keep hold of some code that might not be relevant to my current branch or will potentially be used later down the line. Atm, I just stick that code into a craft doc but it can be difficult to find that code later - enter this extension.

With this extension you can create new code stashes, filter by programming language, copy the stash to your clipboard and remove old stale stashes.

## Screencast
https://share.cleanshot.com/VuEZfm

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ben-greenwood 👋 

Thanks for your contribution 🔥 

I gave it a quick spin and it works almost as expected 💪 

If I create a new file then I'm not able to change the language, could you look into this?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by ben-greenwood** [comment]
> Hi @ben-greenwood 👋
> 
> Thanks for your contribution 🔥
> 
> I gave it a quick spin and it works almost as expected 💪
> 
> If I create a new file then I'm not able to change the language, could you look into this?
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Good spot, should be all fixed now.

Do you have any plans to support syntax highlighting in the future for code blocks?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ben-greenwood 👋 

I gave it a new spin and it works as expected 🔥 

- An idea for now or net version, support for editing the content 😄 

- Do you think we should add validation for a title(and content)?

CleanShot 2022-06-09 at 12 46 51@2x

CleanShot 2022-06-09 at 12 47 25@2x

It looks a bit weird without the validation 😄 

We might look into some syntax highlights later on 😄 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
It's not yet added to the API but it's something that we're working on.

Until then you have to use a Toast with Failure style :)

**Review by pernielsentikaer — APPROVED** [review]
Much better 🔥

**Pull request merged**
