### PR TITLE
feat(uuid-generator): History management in generated uuids

### PR DESCRIPTION
**Pull request by harsh-devx**
## Description

- Added generated uuid history management
- Added actions on history management

## Screencast

https://github.com/user-attachments/assets/505f9c6e-44dd-442d-b650-9ea667009e8c

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by harsh-devx** [comment]
@pernielsentikaer please have a look in this because uuid is hard to search in copy history with other things there.

**Comment by pernielsentikaer** [comment]
It looks like a nice update, what about doing something like this?

```ts
import {
  ActionPanel,
  List,
  Action,
  getPreferenceValues,
  Clipboard,
  Keyboard,
  showToast,
  Toast,
  Icon,
  confirmAlert,
} from "@raycast/api";
import { useEffect, useState } from "react";

import { getHistory as fetchHistory, clearHistory as clearStoredHistory, deleteHistoryEntry } from "./uuidHistory";
import { HistoryEntry } from "./uuidHistory";

interface Preferences {
  defaultAction: string;
}

export default function ViewHistory() {
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const { defaultAction } = getPreferenceValues<Preferences>();

  useEffect(() => {
    async function loadHistory() {
      const historyData = await fetchHistory();
      setHistory(historyData);
    }

    loadHistory();
  }, []);

  const clearHistory = async () => {
    await confirmAlert({
      title: "Clear History",
      icon: Icon.Trash,
      message: "You can't undo this action. Are you sure you want to clear the history?",
      primaryAction: {
        title: "Clear History",
        onAction: () => {
          clearStoredHistory();
          setHistory([]); // Clear the history state after clearing the stored history
        },
      },
    });
  };

  const deleteEntry = async (uuid: string) => {
    const updatedHistory = await deleteHistoryEntry(uuid);
    setHistory(updatedHistory); // Update the state with the history after deletion
  };

  const copyOrPasteAllUUIDs = async () => {
    const allUUIDs = history.map((entry) => entry.uuid).join("\r\n"); // Join all UUIDs with newline

    if (defaultAction === "copy") {
      await Clipboard.copy(allUUIDs);
      showToast(Toast.Style.Success, "Copied all UUIDs to clipboard.");
    } else if (defaultAction === "paste") {
      await Clipboard.paste(allUUIDs);
      showToast(Toast.Style.Success, "Pasted all UUIDs.");
    }
  };

  return (
    <List>
      {history.map((entry, index) => {
        const date = new Date(entry.timestamp);

        return (
          <List.Item
            key={index}
            title={entry.uuid}
            accessories={[
              { tag: entry.type, tooltip: "Type", icon: Icon.Tag },
              { date: date, tooltip: date.toLocaleString(), icon: Icon.Clock },
            ]}
            actions={
              <ActionPanel>
                <Action.CopyToClipboard content={entry.uuid} />
                <Action
                  title={`${defaultAction === "copy" ? "Copy" : "Paste"} All UUIDs`}
                  icon={Icon.Clipboard}
                  onAction={copyOrPasteAllUUIDs}
                />
                <ActionPanel.Section>
                  <Action
                    title="Delete Entry"
                    onAction={() => deleteEntry(entry.uuid)}
                    icon={Icon.Trash}
                    style={Action.Style.Destructive}
                    shortcut={{ modifiers: ["ctrl"], key: "x" }}
                  />
                  <Action
                    title="Clear History"
                    onAction={clearHistory}
                    icon={Icon.Trash}
                    style={Action.Style.Destructive}
                    shortcut={{ modifiers: ["ctrl", "shift"], key: "x" }}
                  />
                </ActionPanel.Section>
              </ActionPanel>
            }
          />
        );
      })}
    </List>
  );
}
```

**Comment by harsh-devx** [comment]
It looks neat 🚀.

**Comment by pernielsentikaer** [comment]
Do you mind updating it or should I?

**Comment by harsh-devx** [comment]
@pernielsentikaer I have update it.

**Comment by pernielsentikaer** [comment]
Wouldn't it be better to have the newest at the top? Right now, it's showing the oldest first 🙂

**Comment by harsh-devx** [comment]
Have updated the order as well.

**Comment by pernielsentikaer** [comment]
@jmaeso do you want to check this?

**Comment by harsh-devx** [comment]
@jmaeso let us know if you want to add anything here.

**Comment by LunaticMuch** [comment]
LGTM 🚀

**Comment by harsh-devx** [comment]
@pernielsentikaer let me know if we can proceed ahead.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
