### PR TITLE
Add GitCommiter extension

### PR DESCRIPTION
**Pull request by chihkang**
## Description

GitCommiter is an AI-powered tool designed to generate meaningful Git commit messages by analyzing repository changes. This extension simplifies your commit process by providing context-aware commit summaries and detailed descriptions.

## Screencast

gitcommiter-1
gitcommiter-2
gitcommiter-3

## Checklist

- [✅] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [✅] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [✅] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [✅] I checked that files in the `assets` folder are used by the extension itself
- [✅] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥

This extension looks a bit like below, did you see them?

* https://www.raycast.com/gianfranco/git-buddy
* https://www.raycast.com/popalay/ai-git-assistant

**Comment by chihkang** [comment]
> Hi 👋
> 
> Thanks for your contribution 🔥
> 
> This extension looks a bit like below, did you see them?
> 
> * https://www.raycast.com/gianfranco/git-buddy
> * https://www.raycast.com/popalay/ai-git-assistant

https://www.raycast.com/popalay/ai-git-assistant
⬆️ This is different from mine. It needs to use finder to go to the specified folder, and I have not successfully generated messages.

https://www.raycast.com/gianfranco/git-buddy
⬆️ This one is also different. The information it produces is less and not rich, and it cannot quickly switch between multiple repos.

**Comment by pernielsentikaer** [comment]
It would be better to enhance one of the options above with the features you're missing so we don't end up with a third option that will confuse users even more - I'm sure both extensions are up for enhancement

**Comment by chihkang** [comment]
Thank you for your suggestion! I’ve considered contributing to the existing plugin, but for now, I prefer to continue using my own plugin because:
	1.	Stability: My plugin is already optimized for specific needs and running stably.
	2.	Customization: The existing plugin may require significant changes to fully adapt to these needs.
	3.	User clarity: Maintaining separate plugins allows users to choose based on their requirements without adding unnecessary complexity.

**Comment by pernielsentikaer** [comment]
That's where enhancements are useful. I believe your corrections could apply to both of them, and I'm confident that both extensions would benefit from these improvements, rather than creating another similar extension, as also mentioned in our [extensions guidelines](https://manual.raycast.com/extensions).

**Pull request closed without merging**
