### PR TITLE
[Quest] quest is now called checklist

### PR DESCRIPTION
**Pull request by zeekrey**
## Description

The other day, I had a chat with a friend who also uses Raycast. He was looking for an extension that offers the same functionality as Quest, but unfortunately, he couldn't find it.

That's why I propose renaming the extension to *Checklist*. This pull request implements this change.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by erics118** [comment]
I think just adding a `keywords` field could be a better option, as it keeps the unique name, but also allows for searching with `checklist`

kinda unrelated:
the [todo list extension](https://www.raycast.com/maggie/todo-list) seems extremely similar...

**Comment by pernielsentikaer** [comment]
I do agree, keywords could also be the solution here @zeekrey

**Comment by zeekrey** [comment]
Thank you guys for the feedback. I apologize for the delay in my response. I thought about it and I have come to the conclusion that "Quest" was not the most suitable name initially. In my opinion, a tool or extension should be named based on its functionality and how it can assist users. Therefore, I believe **Checklist** is a better choice.

I also appreciate the suggestion of adding keywords. I have taken that advice and included some relevant keywords to enhance the visibility of the extension.

Furthermore, I took the time to explore the Todo list extension. It is a straightforward implementation of a todo list. On the other hand, Quest/Checklist is an extension that enables the creation of checklists (which can also be referred to as todo lists) that can be completed repeatedly. By utilizing a checklist, the overall quality of repetitive tasks can be significantly improved.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
