### PR TITLE
Adds GitIgnore Search

### PR DESCRIPTION
**Pull request by superhighfives**
## Description

Adds the [GitIgnore Search](https://github.com/superhighfives/gitignore-search) extension, which makes it quick and easy to grab the contents of a [github/gitignore](https://github.com/github/gitignore/) `.gitignore` template.

Powered by [gitignore-fetch](https://github.com/superhighfives/gitignore-fetch).

## Type of change

- New extension

## Screencast

gitignore-search-screenshot

https://user-images.githubusercontent.com/449385/143944796-6c37c5c9-0195-466f-b1a0-d7e71e0ddda9.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by fe9lix — COMMENTED** [review]
Hey @superhighfives, thanks for your contribution!
Currently the gitignore templates are bundled into the assets folder – could you think of a way to keep the them up-to-date automatically? (e.g. downloading them in the background and caching to the support folder...)

**Comment by superhighfives** [comment]
Hey @fe9lix—yeah, great point. I was asking about this in the [Raycast Slack](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1638205759420100), to see if I could asynchronously grab the `.gitignore` files on copy to clipboard, which would be a way around having them locally.

In lieu of that, I could download the `.gitignore` files (there's 100+ or so) and put them in [Raycast storage](https://developers.raycast.com/api-reference/storage). It doesn't look like there is currently a way to expire that storage, though.

Happy to make any changes, especially if there are any anti-patterns I can avoid.

**Comment by unnamedd** [comment]
@superhighfives do you know about the existence of the https://gitignore.io? 
They also have an API: https://docs.gitignore.io/use/api

I have this alias for `git` here:
`gi = "!gi() { curl -L -s https://www.gitignore.io/api/$@; }; gi"`

which helps me in the creation of my `.gitignore` file, maybe you can consume that API and then you won't need to download/embed any files which might bring problems to keep them updated.

**Comment by superhighfives** [comment]
So, it looks as though https://gitignore.io matches all my requirements, so I've [started on a new branch](https://github.com/superhighfives/gitignore-search/tree/use-gitignore-io). I'm keen to implement caching before I submit, so going to close this in the short term, and will reopen when I have the finalised gitignore.io version.

**Comment by superhighfives** [comment]
(And thanks for reviews and suggestions, @fe9lix and @unnamedd. 👍)

**Comment by unnamedd** [comment]
Nice that you didn't give up @superhighfives! If you need help, suggestions or anything like that, please, share with us on Slack as well! Will be a pleasure to assist you on this funny journey! :D

**Comment by superhighfives** [comment]
Never give up! 😊 Sounds good—will ping you on Slack, @unnamedd. 👍

**Pull request closed without merging**
