### PR TITLE
[Lorem-Ipsum] Visual Improvements for prompts and command arguments

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- Replaced HUDs with Toasts (after closing the window) for color coding prompts
- Fail-fast AI generation in case user doesn't have access to AI
- Made command argument placeholders more meaningful

## Screencast

Screenshot 2024-07-11 at 2 49 44 PM
Screenshot 2024-07-11 at 2 50 44 PM
Screenshot 2024-07-11 at 2 50 21 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by AntonNiklasson — APPROVED** [review]
Looks good to me! I’d prefer to check it out locally on my machine before approving, but I’m out in a camping trip without my computer. 🏕️

**Comment by jfkisafk** [comment]
Thanks for the review and approval @AntonNiklasson ! The changes are pretty trivial visual refresh.

Hey @mil3na, can you please review and merge when you find some time?

**Review by mil3na — APPROVED** [review]
LGTM! @AntonNiklasson let me know if it is okay to merge or if you still want to take a look!

**Comment by AntonNiklasson** [comment]
All good from my side ☺️

**Pull request merged**
