### PR TITLE
feat(bitcoin-price): add style, source, volume, supply, market cap

### PR DESCRIPTION
**Pull request by gutenye**
## Description

See CHANGELOG.md

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by gutenye** [comment]
Added screenshots

**Comment by gutenye** [comment]
Updated to support more coins: Ethereum, BNB, etc. The name `Bitcoin Price` does not fit well anymore. @pernielsentikaer Should I create a new extension?

Screenshot 2024-02-09 at 13 41 38

**Comment by pernielsentikaer** [comment]
So what does it do now that you added more currencies? Trying to see if it already exists in the store 🙂

**Comment by gutenye** [comment]
Basically, it displays prices for different coins. This will make the existing extension 'Bitcoin Price' and 'Ethereum Price' obsolete. Besides, it also displays some more information like volume in 24 hours, supply, and market cap. I have more ideas for this extension like displaying the Bitcoin fee, and Ethereum gas price, but it's not planned at the moment. It's like an all-in-one extension for cryptocurrency information. And I plan to name it 'Crypto Price'

**Comment by pernielsentikaer** [comment]
I guess that could work, so you don't want to add anything to this extension, right?

**Comment by gutenye** [comment]
> so you don't want to add anything to this extension, right?

No, I don't want. Will create a new PR

**Comment by gutenye** [comment]
Replaced by #10806

**Comment by koinzhang** [comment]
Hi @gutenye. I just took a screenshot using the [Shottr](https://shottr.cc/) screenshot tool and added some post-processing
1. move the extended menu bar icon as far to the right as possible
2. choose the right size (2000x1250 as per the official specification) for the screenshot
3. remove the extra menu bar icons with the eraser tool (Shottr makes this easy)

**Comment by gutenye** [comment]
@koinzhang Thanks

**Pull request closed without merging**
