### PR TITLE
feat(network-service-toggler): Add New Extension

### PR DESCRIPTION
**Pull request by FlorianWendelborn**
## Description

Add Network Service Toggler Extension

## Screencast

network-service-toggler-1
network-service-toggler-2
network-service-toggler-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by FlorianWendelborn** [comment]
I can’t make the pipelines pass as I don’t have a retina display to screenshot this on... never thought that’d one day be the reason why my pipelines don’t pass... 😅

**Comment by pernielsentikaer** [comment]
Hi @FlorianWendelborn 👋 

Thanks for your contribution 🔥 

I tested the extension and got this error while trying to disable wifi:

CleanShot 2022-09-19 at 10 57 25@2x

```
10:58:19.126 
Error: Command failed: /usr/sbin/networksetup -setnetworkserviceenabled "Wi-Fi" off

ChildProcess.exithandler:node:child_process:397:12
ChildProcess.emit:node:events:390:28
maybeClose:child_process:1064:16
Socket.<anonymous>:child_process:450:11
Socket.emit:node:events:390:28
Pipe.<anonymous>:node:net:672:12
```

Here are some images you can use
network-service-toggler-4
network-service-toggler-5

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by FlorianWendelborn** [comment]
@pernielsentikaer what macOS are you on, and what happens when you run these 2 commands from terminal?

```sh
networksetup -setnetworkserviceenabled "Wi-Fi" off
which networksetup
```

**Comment by pernielsentikaer** [comment]
I'm running macOS Ventura (Beta 7), here is the output for you

CleanShot 2022-09-19 at 11 43 56@2x

**Comment by FlorianWendelborn** [comment]
@pernielsentikaer can you try again? I added a commit that attempts to request the user password to run the command with `sudo`. It’s entirely opt-in, so it WILL fail for you and give you a suggestion on how to fix it. Please also test that that part is somewhat understandable as it’s hard to reproduce on my system

Let me know if you have any questions or suggestions on how to better implement this, I’m not particularly happy with it but I can’t think of a better way right now and tried to mitigate what I can

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @FlorianWendelborn 👋 

It works as expected, but I get an error when I don't enter the password

CleanShot 2022-09-21 at 21 03 48@2x

Can you look into dying gracefully here too 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by FlorianWendelborn** [comment]
@stale I'll try to finish it up, please don't yeet

**Pull request closed without merging**
