### PR TITLE
Update json-format extension

### PR DESCRIPTION
**Pull request by devloos**
## Description

Hey, @Destiner and @Aayush9029 I found it very useful to view the formatted json before I copy.

I went ahead and created another action that allows the user to either view or copy the formatted json.

I also changed the Form.TextArea to a Form.TextField since a user pasting into the input box does not need to have it expand in my opinion.

## Screencast

https://user-images.githubusercontent.com/58356571/229960638-2325ca1f-81f6-4581-8bb7-af3bf4a17440.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by devloos** [comment]
Hey @Destiner and @Aayush9029 let me know if you have a chance to tackle this anytime soon.

**Comment by Aayush9029** [comment]
@devloos Is there anything you need help with?

I'm not sure what to tackle with.

**Comment by thomaslombart** [comment]
@Aayush9029 I think he meant reviewing the PR. On my end, I have one feedback: the first element should still be `Form.TextArea` because you can't easily see your full input with a textfield. Also, new lines are not handled for text fields.

**Comment by devloos** [comment]
Hey @thomaslombart thank you for letting me know changing it now.

**Pull request merged**
