### PR TITLE
Music Extension - issue fix - feature

### LINKED ISSUE #1294: [Music] ...
# Extension – [Music](https://github.com/raycast/extensions/tree/e656b46965d4367c43056d6a4f35e1bddcaf969a/extensions/music/)
Author: @Rawnly

## Description
"Search & Play Library Track" for songs with the same title defaults to the first result in the list, instead of the one selected.

## Steps To Reproduce

1. Add songs with the same name, case insensitive. 
Example: 
[STAY by The Kid LAROI & Justin Bieber](https://music.apple.com/album/stay/1574378620?i=1574378625)
[Stay by Zedd and Alessia Cara](https://music.apple.com/album/stay/1445043155?i=1445043157)
2. "Search & Play Library Track" for "stay"
3. Select the one on the bottom of the list

## The current behavior
Trying to play Stay by Zedd which is at the bottom of the list, but plays STAY by The Kid LAROI instead.

## The expected behavior
Play Stay by Zedd

### Raycast version
Version: 1.31.0

### PR DESCRIPTION
**Pull request by rawnly**
## Description
- Adds `set rating` feature (requested in #1568) 
- Refactored apple-scripts and utils for a clean project organization
- Fixed #1294 
- #1295 cannot be fixed due to an `AppleScript` limitation.

## Screencast
https://user-images.githubusercontent.com/16429579/166721104-48011ef8-1157-4f70-ae7e-42bd20894646.mp4
> PS: Any UI suggestion is welcome

## Checklist
- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Rawnly** [comment]
Sorry for "last minute" edits, but I tought that merging the fixes branch would have speed up the release process. ✌️

**Comment by pernielsentikaer** [comment]
Hi @Rawnly 👋 

Did you have time to look into this yet?

**Comment by pernielsentikaer** [comment]
Hi @Rawnly 👋 

Did you have time to look into this yet?

**Comment by pernielsentikaer** [comment]
Hi @Rawnly 👋 

If you look [here](https://developers.raycast.com/basics/prepare-an-extension-for-store#navigation-title) it states:

* Don't change the navigationTitle in the root command - it will be automatically set to the command name. Use navigationTitle only in nested screens to provide additional context.

I added a suggestion for you a bit up in the thread, do you think we can figure this out 😄 🔥

**Comment by pernielsentikaer** [comment]
Let's get it merged @Rawnly 🔥 Thanks for your contribution 💪

**Pull request merged**
