### PR TITLE
[Bluesky] fix 'Search Timeline' not working

### LINKED ISSUE #14643: [Bluesky] Cannot search timeline
### Extension

https://www.raycast.com/dharamkapila/bluesky

### Raycast Version

1.83.1

### macOS Version

15.1 Beta 5

#### Error:
```
FetchError: invalid json response body at https://search.bsky.social/search/posts?q=brasil reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

index.js:273:31

---
270: 			try {
271: 				return JSON.parse(buffer.toString())

### Steps To Reproduce

1. Open the Timeline command
2. Enter the search term

### Current Behaviour

An error message appears

### Expected Behaviour

See search results

### LINKED ISSUE #14707: FetchError: invalid json response body at...
### Extension

https://www.raycast.com/dharamkapila/bluesky

### Raycast Version

1.83.1

### macOS Version

14.6.1

#### Error:
```
FetchError: invalid json response body at https://search.bsky.social/search/posts?q=1960 reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

index.js:273:31

---
270: 			try {
271: 				return JSON.parse(buffer.toString())

### Steps To Reproduce

1. Open "Timeline" command
2. Start typing

### Current Behaviour

Shows "Something went wrong" window.

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by xmok**
## Description

Closes #14643.
Closes #14707.
- Updated the Search Timeline to use new method from client.
- Updated deps

In the latest version of client, some types are being treated as `unknown` which is the reason I've explicitly cast some constants in `extensions/bluesky/src/utils/parser.ts`.

## Screencast

https://github.com/user-attachments/assets/0b6fa11a-7535-4037-96fc-8457c423a633

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by dkapila** [comment]
@xmok , I'm hitting an error "FormData is not defined" when trying to run your changes using `npm run dev`:

CleanShot 2024-09-29 at 23 59 32@2x

This seems to be coming from here, which is hit during the `agent.login` call from `atp.ts`: https://github.com/bluesky-social/atproto/blob/98d9a158f9c8e7d5f47dd0799fce5ab0c89394a0/packages/xrpc/src/util.ts#L151, as FormData is not natively available in Raycast? 

Any clue on how to fix this?

**Comment by xmok** [comment]
Hi @dkapila! Great extension 😄
I did come across the same issue during testing which is why I switched to `cross-fetch/polyfill` but I can confirm that if logged out, this shows up when trying to log in. I think we should be able to fix this by setting `global.FormData` to cross-fetch FormData. It's not very TS friendly but should work. Let me try it.

**Comment by xmok** [comment]
Please see the screencast showing before and after - seems to work:

https://github.com/user-attachments/assets/f94480dc-5999-4360-989b-84b752826046

**Comment by dkapila** [comment]
thanks a lot! and yes, it seems to be working well (the search timeline and authenticating). Any idea though what is going on here? This should show the Onboard view (animating the text characters one by one, like in the official version currently). But if there is some issues, you can remove that animation all-together

image


> [xmok](/xmok)

**Comment by xmok** [comment]
Hmm 🤔.
I love the animation but finding it difficult to identify where the race condition is. If we pre-fill the "Title" and then fade in the "Tips" the animation is in order but then the `Continue` action seems buggy - the pop() doesn't always work. My guess is that the order of windows is being messed up due to later version of raycast and `useCallback` - I am removing the animation for now but is worth re-visiting it in future.

rn the Onboard component seems to work OK 4 times out of 5. Every now and then it bugs out and the `Continue` action is funky.

Here's an updated screencast but notice how after the `pop` the view is a bit buggy and does not show loading indicator. One method we could use is `popToRoot` instead of `pop` after Onboard - it might remove the buggy view but it might also lead to worsened UX?

https://github.com/user-attachments/assets/2c22be75-1c6b-41dd-806e-a5a06474bd0d

**Comment by dkapila** [comment]
@xmok , not sure why there is no loading indicator the first time. Besides that it seems fine. Maybe this can be re-visited and improved in the future. 

Otherwise looks good to me, and don't have any other comments :) thanks on fixing these issues.

**Comment by xmok** [comment]
Sounds great 😄. Let me just run the linter to make the bot happy then we are good to go 👍.

**Review by pernielsentikaer — APPROVED** [review]

**Comment by dkapila** [comment]
@xmok extension seems to be crashing when I open the timeline now:

CleanShot 2024-10-01 at 21 47 17@2x

CleanShot 2024-10-01 at 21 46 53@2x

**Comment by xmok** [comment]
@dkapila I am unable to reproduce. Could you check your https://www.raycast.com/extension-issues page for more details? Bluesky released a new version recently maybe there was some API update that we need to account for.

**Comment by dkapila** [comment]
> @dkapila I am unable to reproduce. Could you check your https://www.raycast.com/extension-issues page for more details? Bluesky released a new version recently maybe there was some API update that we need to account for.

Here's the details on Raycast. We might need to add a null check for post.record (could be due to the recent Bluesky release).: 

CleanShot 2024-10-02 at 23 25 29@2x

**Pull request merged**
