### PR TITLE
[New Extension]: ImprovMX

### PR DESCRIPTION
**Pull request by MuhaddiMu**
## Description

ImprovMX is a free email forwarding service. This extension allows you to create a masked email address quickly, add a new domain, and create an alias and SMTP credentials. An account with ImprovMX and ImprovMX API key is required to use this extension.

## Screencast

improvmx-1
improvmx-2
improvmx-3
improvmx-4
improvmx-5
improvmx-6

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I just tried this with a free account and it works sometimes (but always with an error toast) - could you try to use this key `sk_416a6a9daf4445b7a338e0789b0edffd` - there is nothing on this account, that's why I share it 😊

If it's because the account is free we should show that to the user instead 😊

**Comment by MuhaddiMu** [comment]
@pernielsentikaer Thank you for reviewing. 

I have made the necessary changes, so you should not encounter the same problem again. Please review and let me know if you have any further feedback. Thank you :)

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Much better @MuhaddiMu 🔥 

Only getting one error, could you look into this?

Uploading Raycast-Ftg8PTG6.mp4…

**Comment by MuhaddiMu** [comment]
@pernielsentikaer, good catch! It was a broken validation code. 
I have just pushed a fix. Could you please review again? Thank you!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Pull request merged**
