### PR TITLE
Ext/material icons

### PR DESCRIPTION
**Pull request by 201549BL**
## Description

Added a Grid view to the extension. 

I left the original list view per [this comment](https://github.com/raycast/extensions/pull/8554#issuecomment-1760641296) in case there would be any conflicts with PR #8761.

## Screencast

Raycast 2023-10-13 at 10 27 58
Raycast-2
Raycast-3
Raycast-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- It would be better to have just one command and make it possible to change the view with a [preference](https://developers.raycast.com/api-reference/preferences) instead.

-  There are some CI errors and merge conflicts. Can you resolve them too?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Should we consider using the same colors for the icons in both views? For me, black/white would make sense 🙂

Could you look into this @201549BL?

 @creasty could you look into this 🙂

**Comment by 201549BL** [comment]
@pernielsentikaer 

I agree. In "grid view" I'm using `tintColor: Color.PrimaryText` to make the icons contrast from the background. But I can definitely make them black/white for both the "list view" and "grid view" if that is preferred?

**Comment by pernielsentikaer** [comment]
I think that would be the best way here yes 🙂

**Comment by pernielsentikaer** [comment]
Awesome, then we just need @creasty do have a look 🙂

**Comment by pernielsentikaer** [comment]
Pinging @creasty one more time

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
