### PR TITLE
Add extension: Large Type

### PR DESCRIPTION
**Pull request by gon250**
## Description

Large Type allows you to show text in large characters across your screen

## Type of change
- New extension

## Screencast

https://user-images.githubusercontent.com/1652286/146803323-73d2bd8f-59ae-47fb-9258-55b7dfcb1869.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Comment by gon250** [comment]
This is the first version of this extension. I'll add more features while working on this. 

Also I will update the plugin with more styling when raycast starts to add more styling features. 

All suggestions are welcome 😊

**Review by fe9lix — CHANGES_REQUESTED** [review]
Hey @gon250 – may I ask what the exact use case for this extension is?
Before we continue reviewing, please also check the guidelines regarding extension title, command title and command subtitle: https://developers.raycast.com/basics/prepare-an-extension-for-store

**Comment by gon250** [comment]
> Hey @gon250 – may I ask what the exact use case for this extension is? Before we continue reviewing, please also check the guidelines regarding extension title, command title and command subtitle: https://developers.raycast.com/basics/prepare-an-extension-for-store

The idea is just to display a message.

It is a functionality I use a lot when I am in meetings.
1.  I am in a phone call and I want to tell them while I share the screen to give me 1 min.
2. I enter in a meeting ahead of time or I am waiting for them to enter and I want to leave a message on the screen while I share the screen.
3. Leave the written message in case someone from home comes to touch my computer and I don't want to.
I think this is veri usefull, in case you think it is not usefull for the community I will keep this for my self.

I would like to center the message in some way. I have tried some solutions and I was not able to do that. I guess with future new features I will be able to do more stuffs. 

Also I checked the guidelines before create the PR, not sure what its wrong on my side :/ 

Screenshot 2021-12-21 at 11 38 54

**Comment by fe9lix** [comment]
Hey @gon250 – I was just curious. I don't seem to have such use cases myself but that doesn't mean it might not be useful for other people. Maybe add something to the extension description that highlights some use cases?

Regarding names and titles:
- The command name should ideally be verb/action form, something like: "Show Large Type"
- The subtitle is not meant to contain longer phrases and in your case, you can probably just leave it empty

**Comment by TheMightyPenguin** [comment]
Alfred has this same feature and it's be useful, especially when presenting something!

**Review by fe9lix — APPROVED** [review]

**Pull request merged**
