### PR TITLE
Update tidyread---streamline-your-daily-reading extension

### PR DESCRIPTION
**Pull request by DophinL**
## Description

- add quickly generating sources by user interest
- add retryCount and retryDelay setting to decrease article summarizing error 
- improve speed of batch import sources
- improve error handling and error message
- add Delete All Sources
- add doc for two commands
- fix fetch large html content memory leak

## Screencast

tidyread---streamline-your-daily-reading-7
tidyread---streamline-your-daily-reading 2024-01-24 at 00 45 50

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by DophinL** [comment]
The main thing I've done with this PR is to add the onboard page to make it faster for users to get up and running, which was a suggestion from Thomas, thank you very much! I've also made a few other optimizations. 
Can @pernielsentikaer  take a look at it or another?

**Comment by DophinL** [comment]
Currently this PR is complete and there will be no more commits. Looking forward to REVIEW @pernielsentikaer

**Comment by DophinL** [comment]
Currently this PR is complete and there will be no more commits. Looking forward to REVIEW @pernielsentikaer 

But it seems there is a bug that occurs when running long tasks during deactivating the Raycast window. It may fail silently without any error message.

**Comment by DophinL** [comment]
Currently this PR is complete and there will be no more commits. Looking forward to REVIEW @pernielsentikaer 

But it seems there is a bug that occurs when running long tasks during deactivating the Raycast window. It may fail silently without any error message.
When window is active, I never saw this.

**Comment by pernielsentikaer** [comment]
Which "long tasks" are we talking about?

**Comment by DophinL** [comment]
> Which "long tasks" are we talking about?

Generate digest, when you have lot of reading sources need to be processed in one day.

Here are some sources you can use to batch import:
```json
[
    {
        "rssLink": "https://news.ycombinator.com/rss",
        "timeSpan": "1",
        "title": "Hacker News",
        "schedule": "everyday",
        "url": "https://news.ycombinator.com/",
        "tags": [
            "Technology"
        ],
        "favicon": "https://news.ycombinator.com/y18.svg"
    },
    {
        "url": "https://www.phdeck.com/",
        "timeSpan": "1",
        "schedule": "everyday",
        "title": "PH Deck",
        "rssLink": "https://www.producthunt.com/feed",
        "tags": [
            "Product"
        ],
        "favicon": "https://www.phdeck.com/favicon.ico"
    },
    {
        "rssLink": "https://rsshub.app/ainvest/article",
        "tags": [
            "AI"
        ],
        "url": "https://www.ainvest.com/",
        "title": "AInvest",
        "schedule": "everyday",
        "timeSpan": "1",
        "favicon": "https://www.ainvest.com/wencai-ssr/_nuxt/icons/icon_64x64.d7847c.png"
    },
    {
        "schedule": "everyday",
        "rssLink": "https://www.technologyreview.com/feed/",
        "tags": [
            "Technology"
        ],
        "url": "https://www.technologyreview.com/",
        "timeSpan": "1",
        "title": "MIT Technology Review",
        "favicon": "https://www.technologyreview.com/static/media/favicon.1cfcdb44759a0f93ddf5feb5405dd4cc.ico"
    },
    {
        "url": "https://www.investopedia.com",
        "title": "Investopedia",
        "schedule": "everyday",
        "rssLink": "https://www.investopedia.com/feedbuilder/feed/getfeed?feedName=rss_articles",
        "timeSpan": "1",
        "tags": [
            "Finance"
        ],
        "favicon": "https://www.investopedia.com/favicon.ico"
    },
    {
        "rssLink": "https://feeds.businessinsider.com/custom/all",
        "tags": [
            "Finance"
        ],
        "url": "https://www.businessinsider.com/",
        "timeSpan": "1",
        "title": "Business Insider",
        "schedule": "everyday",
        "favicon": "https://www.businessinsider.com/public/assets/BI/US/favicons/apple-touch-icon-192x192.png?v=2023-11"
    },
    {
        "timeSpan": "1",
        "tags": [
            "Finance"
        ],
        "schedule": "everyday",
        "url": "https://www.economist.com/",
        "rssLink": "https://rsshub.app/economist/latest",
        "title": "The Economist",
        "favicon": "https://www.economist.com/favicon.ico"
    },
    {
        "schedule": "everyday",
        "url": "https://www.buzzfeednews.com",
        "rssLink": "https://www.buzzfeednews.com/news.xml",
        "title": "BuzzFeed News",
        "timeSpan": "1",
        "tags": [
            "General"
        ],
        "favicon": "https://www.buzzfeednews.com/static-assets/img/favicon.40f4055ea10bb11593f4c85d55164232.ico"
    },
    {
        "title": "HuffPost",
        "url": "https://www.huffpost.com/",
        "timeSpan": "1",
        "tags": [
            "General"
        ],
        "schedule": "everyday",
        "rssLink": "https://chaski.huffpost.com/us/auto/vertical/world-news",
        "favicon": "https://www.huffpost.com/favicon.ico"
    }
]
```

**Comment by DophinL** [comment]
Sorry, accidentally readme submitted some test content. I just removed it. @pernielsentikaer

**Comment by DophinL** [comment]
Can this be merged? I'm going to do some promoting, thanks! @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
