### PR TITLE
Add extension to search files in Google Drive 

### PR DESCRIPTION
**Pull request by vishaltelangre**
## Description

Adds an extension to fuzzy search files in the locally mounted Google Drive

## Screencast

Google-Drive-1

Google-Drive-2

Google-Drive-3

Google-Drive-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @vishaltelangre 👋 

Thanks for your contribution 🔥I'm already reviewing #1354, which seems to do the same.

Maybe you and @nametake can collaborate if your version has anything besides that.

What do you think about that?

**Comment by vishaltelangre** [comment]
Thanks, @pernielsentikaer.

From the initial looks, it seems both #1354 and this PR can be merged together (if @nametake is willing to do so).

This extension adds the following major things -

- Fuzzy search the absolute path (overrides the default search feature, see the third screenshot above)
- Sorts results by match score + file's modified date (so recently modified files appear first)
- File details on the right-side detail panel (see the above screenshots)
- Preference to show/hide hidden files in the search results
- Some error handling

The extension added in #1354 seems to have these features -

- Preference to specify the mounted Google Drive's root path
- Preference to specify a set of paths to exclude from the search results
- File search

I may be biased, but it seems that this PR has more convenient features in quantum if compare with #1354. I like the preference to explicitly configure the mounted Google Drive's root path (can default to `~/Google Drive` like in this PR) from #1354. If @nametake is okay with it, maybe we can copy that feature from his PR and add it to this and continue with this PR?

Besides these, I also have a couple of things in mind that we can add further to this extension  -

- Ability to star/unstar a result
- Either
  - Divide results into "Favorites" and "Recent files" sections (when the search term is empty)
  - OR add right-side dropdown filters - "Recent files" and "Favorites"
- Build a cache of all the file paths + file details in LocalStorage (recurringly, say daily) so as to speed up the initial boot (useful if one has a Google Drive containing tons of files)

@pernielsentikaer @nametake Wdyt?

**Comment by nametake** [comment]
Thank you @vishaltelangre and @pernielsentikaer !

I also think #1503 extension is more convenient than #1354.

So I'll close #1354.

If possible, I would like to see the directory exclusion feature implemented.

Thanks!

**Comment by vishaltelangre** [comment]
> If possible, I would like to see the directory exclusion feature implemented.

@nametake Absolutely. It would be great if you could contribute that feature (because it is your idea and you had actually implemented it in your version!) once this gets merged in.

--

@pernielsentikaer I think this is ready for the initial review (and for the initial release, feature-wise!). I have added file preview support as well.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @vishaltelangre 👋 

Thanks for the contribution and the updates 🔥 

When I toggle `Show Hidden Files` I get this error: 

CleanShot 2022-04-26 at 22 07 55@2x

When not toggled it seems to work as expected, can you look into this?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by vishaltelangre** [comment]
@pernielsentikaer Interesting. That setting seems to work as expected for me.

image

**Comment by pernielsentikaer** [comment]
Are you in [Slack](https://raycastcommunity.slack.com/), catch me there and we can try debug it 😄

**Comment by vishaltelangre** [comment]
Pinged you in Slack!

**Review by pernielsentikaer — APPROVED** [review]
Hi @vishaltelangre 👋 

Thanks for the debug session and cooperation 🔥

**Comment by vishaltelangre** [comment]
@nametake Since this has been merged and published, cannot wait for your PR to add the "directory exclusion feature"! Thanks.

**Comment by afanjul** [comment]
Hi there, this extension is pretty pretty important nowdays due to the lack of official support by Apple (spotlight) for Google mounted Drives. So thanks a lot!!!

Just a question/suggestion? Could you **add this extension to the possibles fallback extensions**? So we could use more easily alike File Search extension?
image

image


Thanks a lot! you saved my life!

**Comment by vishaltelangre** [comment]
@afanjul Glad to hear that you are using this extension. It looks like there's no public API to make it act as a fallback search provider. There's already a similar open request (https://github.com/raycast/extensions/issues/1668) that maybe you can upvote to bump up its priority. Thanks!

**Comment by afanjul** [comment]
> @afanjul Glad to hear that you are using this extension. It looks like there's no public API to make it act as a fallback search provider. There's already a similar open request (#1668) that maybe you can upvote to bump up its priority. Thanks!

Thanks, I have added a comment and an upvote on https://github.com/raycast/extensions/issues/1668

I hope they release a Fallback API or anything

**Pull request merged**
