### PR TITLE
[IMDb] Add separate command and details view

### PR DESCRIPTION
**Pull request by kgrhartlage**
## Description

The following changes were made to the extension:

### Introduce separate commands for movie and TV series search

The extension previously combined movie and TV series search in a single command. The [OMDb API](https://www.omdbapi.com/) has a fixed page size of 10 results, which means if you are searching for a movie in the sense that, for example, you only remember one word from the title, this becomes much more cumbersome because the results will likely include multiple TV series. On top of that, aside from the very first search result, there is no indication at all as to whether a given search result is a movie or a TV series. This gets worse for movies and TV series with the exact same title. Having dedicated commands for movies and TV series makes the search much more purposeful and effective.

### (almost) Remove client-side filtering

The extension previously filtered out any results that had either no rating or no plot. This, unfortunately, leads to a very wide range of titles not being searchable, most notably older and non-Hollywood movies in general. For example, [Blind Beast](https://www.imdb.com/title/tt0140384/), has 3.6K votes on IMDB, but does not appear in the search results.

<details>
<summary>"blind beast" search</summary>

CleanShot 2023-05-25 at 05 58 26@2x

</details>

I therefor removed client-side filtering apart from filtering out results without an IMDb ID. I was not able to actually find such results, but since the extension is named IMDb I suppose it does not make sense to handle results that would not allow opening the IMDb page.

### Add Details view

The API returns a bunch data that was previously not visualized, like Director, Writers, Actors, Runtime and so on. This information is now accessible via the Details view for each result.

<details>
<summary>Details view</summary>

imdb-3

</details>

### Refactor List view

I believe that displaying the truncated plot as the subtitle has little value to the user and mostly only creates noise and or frustration, especially since the truncated part is not accessible by subsequent actions. I opted to instead display the director for movie results, the number of seasons for TV series. The plot is instead now accessible in its entirety on the Details view.

<details><summary>List view</summary>

CleanShot 2023-05-25 at 06 12 43@2x

CleanShot 2023-05-25 at 06 13 02@2x

CleanShot 2023-05-25 at 06 13 12@2x

</details> 

I opted to remove the list sections ("Best Match" and "Similar"). This does **not** in any way change the order of the results, since the "Best Match" was simply the first item in the results array. I merely removed the section titles themselves. Aside from the section titles taking away real estate from the search results and leading to more scrolling, I find the distinction ambiguous and potentially misleading. For example, the literal match for a search query often shows up under "Similar"

<details><summary>sections</summary>
<p>

CleanShot 2023-05-24 at 17 23 54@2x

</p>
</details> 

### Add action to open YouTube trailers

<details><summary>YouTube Trailer action</summary>
<p>

CleanShot 2023-05-25 at 06 23 44@2x

</p>
</details>

### New extension icon

I found the previous one to be very generic (in the context of Raycast icons) and due to the combination of its size within the application and the lack of contrast it mostly looked like a yellow square. I personally cannot tell that there is a film reel icon inside. My motivation was to replace it with something that stands out a bit more in regards to shape, color and contrast.

<details><summary>icon comparison</summary>
<p>

CleanShot 2023-05-25 at 06 36 15@2x

</p>
</details> 

### MIsc

- replaced `node-fetch` with Raycast's `useFetch` hook
- upgraded dependencies
- refactored typing
- added new metadata screenshots

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @kgrhartlage 🔥 

@ryan-exe do you mind checking this?

**Comment by ryan-exe** [comment]
I'll check this out over the weekend

**Review by ryan-exe — APPROVED** [review]
Hey @kgrhartlage 👋 Thanks for your contribution. I've tested all the changes and it looks good. You've made some great enhancements, thanks for all the effort. 🎉

All good on my end @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
