### PR TITLE
Update dropstab_main extension

### PR DESCRIPTION
**Pull request by Motion-Up**
## Description

# DropsTab Dropstab Crypto Toolbox

### Search

Dropstab Crypto Toolbox displays the price, market capitalization, and rank of any cryptocurrency, and also allows quick access to the project's page on Dropstab.com or its X (Twitter) profile.

DropsTab

### Wallets

Dropstab Crypto Toolbox allows you to instantly find and view any crypto address in the blockchain explorer.
DropsTab

### Ethereum Gas Tracker

Get the latest gas prices for Ethereum. This feature provides real-time information on the current gas prices required for transactions on the Ethereum network.

DropsTab

### Macro View

Get the latest macroeconomic data. This feature provides a comprehensive overview of key macroeconomic indicators such as stock indices, commodities, and other financial instruments.

DropsTab

### Gainers & Losers

Get the latest gainers and losers. This feature displays the top-performing and worst-performing cryptocurrencies over the last 24 hours.

DropsTab

### CEX Pairs Search

Search for pairs on CEX. This feature allows users to search for trading pairs on centralized exchanges (CEX).

DropsTab

_Made with ❤ for the Decentralized World._

### Added

- Ethereum Gas Tracker
- Macro View
- Gainers & Losers
- CEX Pairs Search

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Looks like the same issue. Are you in our Slack community? There, we have a channel called #extensions where they can help you figure out what's wrong

**Comment by Motion-Up** [comment]
@pernielsentikaer I'm not in your Slack community.

**Comment by Motion-Up** [comment]
@pernielsentikaer I wrote in the Slack community, waiting for a response.

**Comment by Motion-Up** [comment]
Is it possible to delete the two folders dropstab and dropstab_raycast? Can I do this, or can you do it? After that, I would fork the repository, create a single folder dropstab with all the up-to-date code, and then make a pull request.

**Comment by Motion-Up** [comment]
@pernielsentikaer No solution to our problem has been provided yet. Should we consider using the option I sent?

**Pull request closed without merging**
