### PR TITLE
feat: added Refresh WiFi extension

### PR DESCRIPTION
**Pull request by natterstefan**
## Description

Quickly turn your WiFi on and off again.

## Screencast

404 :)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by natterstefan** [comment]
@pernielsentikaer For some reason, this does not work in Raycast. I tried different solutions with `run-applescript`, and `osascript-tag` for instance. Nothing worked. 🤔  But running it outside of Raycast does.

Do you have any clue why it doesn't work?

image

```bash
>> err Error: Command failed with ENOENT: networksetup -listallhardwareports
spawn networksetup ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn networksetup',
  path: 'networksetup',
  spawnargs: [ '-listallhardwareports' ],
  originalMessage: 'spawn networksetup ENOENT',
  shortMessage: 'Command failed with ENOENT: networksetup -listallhardwareports\n' +
    'spawn networksetup ENOENT',
  command: 'networksetup -listallhardwareports',
  escapedCommand: 'networksetup -listallhardwareports',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: fa<…>
```

**Comment by Aayush9029** [comment]
@natterstefan Ooo I was about to work on similar extension looks like you already made it!! 🎉

BTW if you're open to it here's an icon I designed for it feel free to use it!

wifi-extension-icon

I used Raycast icon template to make it! Feel free to ignore :D

**Comment by Aayush9029** [comment]
> Do you have any clue why it doesn't work?


Feel free to look at m-cli's implementation 

https://github.com/rgcr/m-cli/blob/master/plugins/wifi


Here's their implemention of this feature!

``` bash

_W_DEVICE=${_W_DEVICE:-en0}
wifi_off(){
    networksetup -setairportpower ${_W_DEVICE} off
}

wifi_on(){
    networksetup -setairportpower ${_W_DEVICE} on
}

```

**Comment by natterstefan** [comment]
Hi @Aayush9029,

thanks for the feedback and link to `m-cli`. The way they do it is also how I do it using the [`manage-wifi` package](https://github.com/sindresorhus/manage-wifi/blob/a0bce2ddf94b2af367df37dbbc184bfbb12d1f34/index.js#L54-L59). So I guess its a different problem. 🤔 

Thanks for sharing your icon as well, I will think about it :)

**Pull request merged**
