### PR TITLE
Update imdb extension

### PR DESCRIPTION
**Pull request by bibixx**
## Description
 - Add new combined command
 - Add new search games command
 - Add an option to show Games in search results (disabled by default)
 - Add arguments to all of the commands
 - Disable old, individual commands by default
 - Update the icon
   - Alternatively we could use this icon
    
 - Replace the `number` and `YouTube` icons with Raycast icons
 - Add more robust response validation
 - Updated the screenshots to match the new icon

<details>
  <summary><h2>Screenshots</h2></summary>

  
imdb-1
imdb-2
imdb-3
imdb-4
imdb-5
</details>

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @bibixx 👋 

That looks like a really awesome update 🔥

@ryan-exe do you mind checking this?

**Comment by ryan-exe** [comment]
Hi @bibixx 👋 Thanks for your contribution! All looks really good and thanks for keeping those individual commands available if any legacy users want to keep using them. The individual commands were part of the [last contribution to the extension](https://github.com/raycast/extensions/pull/6760). 
 
As there's no official affiliation with IMBd I think your alternative icon is a better choice. If you could switch to that icon and update the screenshots I'd be happy to get this merged in 🎉

**Comment by bibixx** [comment]
@ryan-exe 
✅ Icon Change
✅ Screenshot Change

**Comment by ryan-exe** [comment]
Cheers @bibixx 

@pernielsentikaer Looks good to me 🍿

**Pull request merged**
