### PR TITLE
[GitLab] Improve GitLab Flavored Markdown rendering.

### PR DESCRIPTION
**Pull request by metakirby5**
## Description

- Render emojis from GitLab Flavored Markdown.
- Hide inline HTML tags from GitLab Flavored Markdown.

## Screencast

Screen Shot 2022-06-29 at 20 04 56

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by danielsequeira** [comment]
> Thank you for your contribution! 🎉
> 
> 🔔 @tonka3000 @Loskir @immint023 @duboiss you might want to have a look.

Looks good to me 🙂 

Since I don't use GitLab though, it would be good to have one of you testing it out.

**Comment by metakirby5** [comment]
@tonka3000 @Loskir @immint023 @duboiss Hello! When you have a moment, please take a look 🙏

**Comment by tonka3000** [comment]
@metakirby5 I check the PR. Emoji works. But when I have following inline html tag is seems not to work correctly.

CleanShot 2022-07-07 at 19 36 52@2x

CleanShot 2022-07-07 at 19 37 29@2x

**Review by tonka3000 — APPROVED** [review]
Works 👍 

CleanShot 2022-07-07 at 20 06 34@2x

**Pull request merged**
