### PR TITLE
Update fantastical extension

### PR DESCRIPTION
**Pull request by ramsaysewell**
## Description

Adds notification for when an event is added as per this feature request: #12894 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by xilopaint** [comment]
Are you sure you used the `Organize Imports` command? It doesn't seem so.

**Comment by ramsaysewell** [comment]
> Are you sure you used the `Organize Imports` command? It doesn't seem so.

I have used JetBrains' organising imports functionality and have double checked with VS Code's version. All files have had their imports organised as expected.

**Comment by xilopaint** [comment]
Weird. This is how imports are sorted for me:

fan-add-event-editable tsx

And this is where I find the `Organize Imports` command in VS Code (also works with ⇧⌥O):

Screenshot 2024-06-14 at 19 21 21

**Comment by pernielsentikaer** [comment]
Can you give it a quick spin to ensure I didn't break anything 🙂

**Comment by ramsaysewell** [comment]
> Can you give it a quick spin to ensure I didn't break anything 🙂

Your changes look good to me.

**Comment by pernielsentikaer** [comment]
@xilopaint do you have any corrections before merge?

**Comment by xilopaint** [comment]
1) This PR broke the `Quickly Add Fantastical Reminder` command. The command is currently adding an event instead of a reminder.
2) I suggest removing the title of the new setting created and using `Hide Raycast on Add` as a label.
3) `import { runAppleScript } from "@raycast/utils";` should be the second line in each file.

**Comment by ramsaysewell** [comment]
@xilopaint I'm confused why `runAppleScript` import needs to be on the second line. The only way to ensure that everyone's IDEs organises the imports the same way would be to set something up in prettier or eslint.

I've updated the preference from your suggestion

**Comment by pernielsentikaer** [comment]
Can you check again @xilopaint - first point on you list should be fixed

**Comment by xilopaint** [comment]
> @xilopaint I'm confused why `runAppleScript` import needs to be on the second line.

Because after @pernielsentikaer's change `runAppleScript` is being imported from `@raycast/utils` instead of `run-applescript`. If you run `Organize Imports` again it will be on the second line.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
