### PR TITLE
Add openai-vision extension

### PR DESCRIPTION
**Pull request by aeither**
## Description

Get image insights with OpenAI Vision.
- ask selected image
- ask clipboard image

## Screencast

openai-vision 2024-06-01 at 11 37 46
Raycast 2024-06-01 at 11 14 27

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by erics118** [comment]
btw, the existing [ChatGPT extension](https://www.raycast.com/abielzulio/chatgpt) already supports vision

CleanShot 2024-06-02 at 13 46 49

**Comment by aeither** [comment]
hey erics, thanks for mentioning. I didn't know about it.

I installed the extension. 
ok I have just tried it.. here are few differences i have notice.

the chatgpt extension doesn't allow me to ask a selected image. I have to open the command and search the image from there.
the chatgpt extension doesn't allow me to ask a image copied to the clipboard neither.

If you haven't told me, It is hard for me to find out. When installing it. "vision" wasn't mentioned in the extension description and also there is no command that state it can ask image. I had to open "models" command to find out it can enable "vision capabilities". once enabled i still can't paste or select the image right in front of me. to later i had to figure out I have to  open "Full Text Input" by hitting Enter to be able to "open file"

the ability to ask more than 1 images looks useful, but the steps to reach there and not be able to know if it provides vision before installing it are not good

**Comment by pernielsentikaer** [comment]
I would also think it would be better to enhance the current GPT extension where we update the keywords to also include "vision"

**Comment by aeither** [comment]
> I would also think it would be better to enhance the current GPT extension where we update the keywords to also include "vision"

Build it into current ChatGPT extension
https://github.com/raycast/extensions/pull/12929

**Pull request closed without merging**
