### PR TITLE
[two-factor-authentication-code-generator] change to paste from copy

### PR DESCRIPTION
**Pull request by gusghrlrl101**
## Description

Change to paste from copy

## Screencast

https://user-images.githubusercontent.com/38372691/214731929-4f97944a-8586-4304-b184-24f22ebdaf9a.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
Would it make sense to expose a preference for this change? We have something similar in other extensions already. Then the user can pick which action they want with a dropdown.

**Comment by pernielsentikaer** [comment]
Hi @gusghrlrl101 👋 

As @thomaspaulmann said, we might add an option to let the user change this.

Can you look into this?

**Comment by gusghrlrl101** [comment]
@pernielsentikaer 

how about this?
- `Paste Code` is default command (enter)
- `Copy Code` is second command (cmd + enter)

I think most people use to paste code from 2fa to type code!

https://user-images.githubusercontent.com/38372691/217551224-ba035d76-4230-49dd-843f-116d7125fafd.mov

**Comment by thomaspaulmann** [comment]
While most folks use paste, I would add a preference for this that exisiting users aren't confused.

**Comment by pernielsentikaer** [comment]
Yeah, letting the user know what's the best to do here. Do you need an example to do o?

**Comment by gusghrlrl101** [comment]
Is it possible user changes command's shortcut in Raycast?

(If I add paste code command, I want to change shortcut of paste code 😅)

**Comment by pernielsentikaer** [comment]
Hi @gusghrlrl101 👋 

You can see how it can be done here:

* https://github.com/raycast/extensions/pull/4746/files#diff-ea0d66946a8b39c97204169089b674f19878ed6011e82faad3d9567202bc730eR14-R24
https://github.com/raycast/extensions/pull/4746/files#diff-d2a854fd07e64f213b5c2ea1be20f0204adbd6fe44f4778254303f788233c5c4R17-R36

You can add [shortcuts](https://developers.raycast.com/api-reference/user-interface/actions#props) too, but for the first two items in the list, it will show the primary and secondary shortcut, but the assigned still works

**Comment by gusghrlrl101** [comment]
@pernielsentikaer 

Thank you for example!

I add preference for default action (`Copy`, `Paste`)

For existing users, default option is `Copy`.

스크린샷 2023-02-17 오전 11 30 52

**Comment by pernielsentikaer** [comment]
Hi @gusghrlrl101 👋 

Do you mind checking that I didn't break anything 🔥 The CLI error is not related to anything code wise, it's the same of the extension that is to long for a GitHub label 😊

**Comment by pernielsentikaer** [comment]
Seems like my machine won't lint this, do you mind trying @gusghrlrl101

**Comment by gusghrlrl101** [comment]
@pernielsentikaer 
Thank you!
I changed `totp.ts` and all checks passed!

**Comment by pernielsentikaer** [comment]
@cjdenio do you mind checking this 😊

**Comment by gusghrlrl101** [comment]
@pernielsentikaer @cjdenio 

Hi.
Can you check this?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
