### PR TITLE
Update teleport extension

### PR DESCRIPTION
**Pull request by lamberttraccard**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @lamberttraccard 👋 

It seems like you pushed the extension again, could you only push the changes 🙂

**Comment by lamberttraccard** [comment]
> Hi @lamberttraccard 👋
> 
> It seems like you pushed the extension again, could you only push the changes 🙂

the weird thing is that i just did a npm run publish 🤔

**Comment by lamberttraccard** [comment]
@pernielsentikaer I resolved the conflicts and everything is good now :)

**Comment by pernielsentikaer** [comment]
I'm only missing a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry 🙂

**Comment by lamberttraccard** [comment]
@pernielsentikaer should be good now :)

**Comment by lamberttraccard** [comment]
@pernielsentikaer, I was wondering if you had a chance to take a look at the latest updates? 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
