### PR TITLE
[Jira] Implements the possibility to type before loading credentials

### PR DESCRIPTION
**Pull request by igor9silva**
## Description

Implements the possibility to type before loading credentials.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaslombart — CHANGES_REQUESTED** [review]
Hey @igor9silva, thanks a lot for your contribution! 💪 

As far as it looks, changing `Detail` to `List` is enough to fix the bug, there's no need for other changes. Let me know if that works for you.

**Comment by igor9silva** [comment]
@thomaslombart I just tested and even though I'm able to type, it doesn't properly update the list.

With current PR code:
image

Swapping `Detail` for `List` only.
image

**Review by thomaslombart — COMMENTED** [review]
Indeed, it's not working out by just swapping out the component, good catch. 

Last thing before merging: could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

**Comment by igor9silva** [comment]
Done. Sorry for missing that.

**Review by thomaslombart — APPROVED** [review]

**Comment by thomaslombart** [comment]
Thanks for the fix! 🚀

**Pull request merged**
