### PR TITLE
Add time-machine extension

### PR DESCRIPTION
**Pull request by SuoweiHu**
## Description

This extension helps the TimeMachine user to start, stop backup, and reveal/browse historical backup on different destination. Hope you will like it 👍 

## Screencast / Video

https://github.com/user-attachments/assets/6f44f327-140e-47c2-9c37-23786d7fab5c

2024-07-10T113200

2024-07-10T113220

2024-07-10T113228

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by SuoweiHu** [comment]
Hello @mil3na, thank you for your detailed attention. Yes, it is ready to review (just spotted a few issue yesterday and quickly patching them with those commits)

**Review by mil3na — CHANGES_REQUESTED** [review]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

I have a few requests for you:
- Could you please fix the identation on your package.json file?
- Could you please remove commented actions on your cmd-list-destination.tsx file?
- Please, look for typos like this one:
CleanShot 2024-07-12 at 14 06 22

- When I do not have any backups, this error is shown:
CleanShot 2024-07-12 at 14 06 10

I will be waiting for your response :)

**Comment by SuoweiHu** [comment]
Hello Milena,

Thank you for spotting those issues ! 

Lemme fix those and get back to you (・ω・)b

**Comment by SuoweiHu** [comment]
Hello @mil3na, I've got the nominated issue/problems patched:

- [ ] Fix indentation of `package.json` via prettier 
- [ ] Remove un-used action for `cmd-list-destination.tsx`
- [ ] Fix `[]:[]` error via show `<List.EmptyView>` when no backup can be found on the destination (see demo video: [link](https://share.cleanshot.com/Jvg80CW4lMXkcWdlBHL1))

Please let me know if there's anything else you feel like need extra work !

**Comment by mil3na** [comment]
Hi! Thanks for updating your PR.
However, I still get that same error page when using the `List Backup` command.
I never did a Time Machine backup in this machine, if that helps debugging.

**Comment by SuoweiHu** [comment]
> Hi! Thanks for updating your PR. However, I still get that same error page when using the `List Backup` command. I never did a Time Machine backup in this machine, if that helps debugging.

Ah sorry about that, with your provided detail I think I can guess where the issue can be, lemme try patching that again and get back to you, won't be long.

**Comment by SuoweiHu** [comment]
> > Hi! Thanks for updating your PR. However, I still get that same error page when using the `List Backup` command. I never did a Time Machine backup in this machine, if that helps debugging.
> 
> Ah sorry about that, with your provided detail I think I can guess where the issue is, lemme try patching that again and get back to you, won't be long.

I think i've got it fixed now (see video: [link](https://share.cleanshot.com/WbS38Vd460BXYzNtxhg6)), may I bother you to take another look ? 😊

**Review by mil3na — APPROVED** [review]
LGTM!

In the future, maybe improve the error messages and do not allow start/stop backups if there's no backup disk :)

**Comment by SuoweiHu** [comment]
> LGTM!
> 
> In the future, maybe improve the error messages and do not allow start/stop backups if there's no backup disk :)

Most definitely. 
Thanks a ton for bearing with my long conversation for bugs ! 
Appreciated your time and have a nice day !

**Pull request merged**
