### PR TITLE
[Color Picker] Add color wheel feature command

### PR DESCRIPTION
**Pull request by ridemountainpig**
## Description
Add `Color Wheel` command for issue #12924.

## Screencast

https://github.com/raycast/extensions/assets/92412722/25674063-46b4-40dd-88e5-3d7d42202588

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by LitoMore** [comment]
The color wheel PNG image you provided is too low. The picture is severely distorted. Please note that the Raycast bot will always compress PNG files before merging.

You can use other image formats like WebP for the best quality.

**Comment by ridemountainpig** [comment]
Hi @LitoMore, thank you for your advice. I have changed the color wheel image to the WebP format.

**Comment by LitoMore** [comment]
This image is still in low quality. You may need to find a better color wheel image source.

image

When you zoom in, you will notice that the colors in the picture are uneven and have irregular streaks. This will affect the accuracy of picking colors.

**Comment by LitoMore** [comment]
Let's use this image file instead: [color-wheel.webp.zip](https://github.com/user-attachments/files/16097226/color-wheel.webp.zip). Your image doesn't need to be so large (10000x10000).

I picked the color wheel image from https://commons.wikimedia.org/wiki/File:Color_circle_(RGB).png. I also used [cwebp](https://developers.google.com/speed/webp/docs/cwebp) to convert the PNG to WebP. The CLI command is below:

```shell
cwebp -q 100 color-wheel.png -o color-wheel.webp
```

To make its meaning clearer, we can rename the file from `color-wheel.webp` to `rgb-color-wheel.webp`.

In addition, I would like to mention that I have tried using SVG vector images. Raycast has a rasterizing process on SVG files when rendering, which will severely distort the SVG images. So WebP is still the best solution.

**Comment by mil3na** [comment]
Would be an option to programmatically generate this wheel? Like using https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/conic-gradient

**Comment by ridemountainpig** [comment]
@LitoMore, thank you for your image. I have updated it.

Also, thank you for @mil3na's suggestion, but the `conic-gradient()` seem does not appear to be usable in Raycast extensions.

**Comment by mil3na** [comment]
@LitoMore are you happy with the image at the moment?
One thing that looks strange to me is that, even though it is a color wheel command, I can pick colors outside of that image, and even outside Raycast. Is that intentional? Can we fix that?

**Comment by LitoMore** [comment]
@mil3na This is by far the best solution unless Raycast core makes changes, which is unlikely at the moment.

**Review by LitoMore — APPROVED** [review]

**Review by mil3na — APPROVED** [review]
LGTM!

**Comment by mohammadazeemwani** [comment]
How do you folks change hue and all for a color picked using color wheel

**Pull request merged**
