### PR TITLE
Update vivapb extension

### PR DESCRIPTION
**Pull request by codrkoaz**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Metadata images are meant for showing Raycast and not third party extension. You can still include it in the README but then you'll need to have them in a folder called `images` instead

**Comment by codrkoaz** [comment]
> Metadata images are meant for showing Raycast and not third party extension. You can still include it in the README but then you'll need to have them in a folder called `images` instead

I did that before it, but never showed up on Raycast I thought I did something wrong.

**Comment by pernielsentikaer** [comment]
Looks like there is some merge conflicts in the README file, could you look into them?

**Comment by pernielsentikaer** [comment]
You still have the images in a folder called `metadata`. Could you move them to a folder called `images` and change the references in the README

**Comment by codrkoaz** [comment]
> You still have the images in a folder called `metadata`. Could you move them to a folder called `images` and change the references in the README

I changed and updated it.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
