### PR TITLE
Add WhatsApp extension

### PR DESCRIPTION
**Pull request by vimtor**
## Description

This extension aims to interact with WhatsApp application. For now, it only has one command which grabs all your Apple contacts and shows them to open in WhatsApp desktop or web apps. Also, it includes functionality to pin contacts so you can access them quickly.

Since the extension now only has that command I did not name it "WhatsApp".

The first time the extension asks for "Contact" permissions to grab all the contacts, which takes 4-10 seconds the first time, after this it gets cached. I am no Mac expert, so maybe there is a better way to get these contacts from JavaScript. 

As a side note, I saw that the built-in Raycast list filter ignores phone numbers (or numbers in general). I am unsure about how to deal with this since creating a custom filter for this seems like an overkill. 

## Type of change

- New extension

## Screencast

For privacy reasons I decided to only include images so I can blur them using CleanShot

CleanShot 2021-11-21 at 13 34 26

CleanShot 2021-11-21 at 18 30 38@2x
CleanShot 2021-11-21 at 19 06 17@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by vimtor** [comment]
Sadly WhatsApp groups cannot be automatically detected, but there is a way to add them manually.

I can imagine 2 commands:
1. Create Chat (WhatsApp)
2. Open Chat (WhatsApp)

The 1st one would ask the user to add a phone number or group ID while the second one will be the same but with CRUD capabilities.

The thing I am unsure about is if Apple contacts usage fits into this new approach. Maybe it could be another command "Import Contact".

What do you think @pernielsentikaer?

**Comment by vimtor** [comment]
I was thinking about making this extension simpler by removing the Apple Contacts integration and adding instead the following commands:

- Add Chat
- Add Group (or as an option in the "Add Chat" command)
- Open Chat

This provides full flexibility and will allow users to add groups (not possible currently) or use the extension without Apple's Contacts app. That being said adding all the contact manually can be tedious so I may add a command "Import Contacts".

**Comment by EliasGcf** [comment]
This looks awesome, congratulations!

**Review by mattisssa — COMMENTED** [review]
Hey! Thanks for the contribution 👍 

I tried to **Create Chat** that already exists with name test, and in **Open Chat** this chat is titled as Test, but in the WhatsApp app it is called differently (as I titled it in contacts). Not sure if we can do anything here, let me know if it's possible to check and improve.

I'm not sure what can be wrong here, but the Import Contacts takes very long, for me it was about 3 mins. Seeing the animating toast for 3 mins does not feel great, let me think what can be better here. 
CleanShot 2021-11-23 at 17 06 03@2x

Does it work for you properly?

**Comment by mattisssa** [comment]
>As a side note, I saw that the built-in Raycast list filter ignores phone numbers (or numbers in general). I am unsure about how to deal with this since creating a custom filter for this seems like an overkill.

Yeah, this is the bug that will be fixed with the next release 😉

**Comment by vimtor** [comment]
Hey @mattisssa!

1. I'm not sure what is the problem you faced when using the command `Create Chat` with `test` as a name. I think you should be able to have 2 contacts with the same name, since you can meet 2 people with the same name. If you are referring to forcing the name to match the WhatsApp one, this is currently impossible because WhatsApp does not offer any kind of public API. Once they release it we can simply use it in the `Open Chat` and modify the `Create Chat` or `Create Group` to actually create a group in WhatsApp.
2. The `Import Contacts` takes a long time for me too. I am fairly new to the Apple ecosystem and AppleScript, but I did not find a faster way to retrieve the contact information. The built-in `Search Contacts` is super fast, so my guess is that there is a better solution out there.
3. I will include the phone number with and without the `+` symbol in the `keywords` so they work in the next release 😄

**Comment by mattisssa** [comment]
1. ok 👍 
2. Do we really need this command in your extension? I'm not a heavy whats app user, but not sure if it's really important to have one since it's such a slow 😃 
3. Do this before the publishing command please, once the release will be delivered your command will work as expected automatically 😉 

I've noticed another issue in your extension. I created a group with a name and a Random "Group Code" (Should this be random or how does it work?). 
I can see the group in **"Open Chat"** command, but once I open the group I see this:

CleanShot 2021-11-23 at 21 59 23@2x

**Review by mattisssa — CHANGES_REQUESTED** [review]
Requesting changes for the `keywords` we discussed in the comments

**Comment by vimtor** [comment]
2. It's not really necessary to be honest. However, without it will be kind of slow to setup since you will have to create your most common contacts manually. I will try something like [node-mac-contacts](https://www.npmjs.com/package/node-mac-contacts) to see if it loads faster. I am open to delete the command, tell me what you think 😄 
3. 👍 
4. I forgot to a `README.md` explaining how to get the WhatsApp group code. I sent you a Slack message with a real WhatsApp group I created.

If you don't have WhatsApp I can show you in a Slack call how the extension works.

**Review by mattisssa — COMMENTED** [review]
I've just checked your readme file and updates about the group code. Well, now I'm completely confused 😄 

Could you please clarify:
What does **Create Group** really do? I don't get the point of this command if I need to open the WhatsApp application to "create" the group. 

Does it just _add_ the group that already exists in WhatsApp to the Raycast extension? Kinda sync? 

Because for me, the point of having this command installed is that you wouldn't need to open the WhatsApp application at all.

**Comment by vimtor** [comment]
The problem here is that WhatsApp does not have an available API yet.

The `Create` commands just add the group or contact to the extension so you can use them in the `Open Chat` command. That's why I added the `Import Contacts` command. There is not way to create groups from outside WhatsApp.

I can rename the commands to `Add Group` and `Add Contact` so it becomes clear (or even `Add Existing Group`).

Now maybe you understand why I added the `Import Contacts` command.

Sorry for the confusion :)

**Comment by mattisssa** [comment]
@vimtor Ooookay, I thought this is the way it works 😄 👍 
Yes, these commands should be definitely renamed, because having "Create" in the title assumes creation and does not add to the extension. I'd call them "Add Existing Group" and "Add Contact" as you mentioned. 👍 

About "Important Contacts" command I'll be back a little bit later, want to discuss this with the team again.

**Comment by vimtor** [comment]
Awesome! I will change the command names and explain them a bit more in the `README`.

Let me know if you have some ideas about the `Import Contacts`. I thought about compiling some native code, but I am unsure if that will have security implications for you :)

**Comment by vimtor** [comment]
Any news of the `Import Contacts` command?

I think we can omit it if we want, since the extension works without it. It is a nice to have but non blocking.

**Comment by vimtor** [comment]
Hey @mattisssa I removed the `Import Contacts` command since it makes the whole thing more complicated to understand and it was simply a patch before WhatsApp releases their official API

Feel free to publish the extension :)

**Comment by mattisssa** [comment]
Hey @vimtor! Sorry for the long awaited, we published a message with a small info that the entire team was off for a while. Let me check everything again and finally make the merge

**Review by mattisssa — APPROVED** [review]
Ok, I'm approving it. But let's, please do the proper import for contacts and groups in the future, because it's really too complex to configure everything before you can use the commands. 

I assume people will probably just use the WhatsApp application rather than the extension because making this manual import will take a long time.

**Pull request merged**
