### PR TITLE
Bonk price - The price of $BONK on your menu bar

### PR DESCRIPTION
**Pull request by AnishDe12020**
## Description

A menu bar command that shows the price of the $BONK token on the Solana blockchain. It also has some more shortcuts to the token page on Solscan, the Solana explorer and swapping it on Jupiter. 

It takes one preference value - `bonkAmount` - the amount of bonk one holds. It is multiplied by the current price of BONK and displayed. The default is 25,000,000,000 as that is exactly how much $BONK many Solana developers were airdropped.

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @AnishDe12020 👋 

Do you mind checking the extension icon 😊

**Comment by AnishDe12020** [comment]
Fixed it!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @AnishDe12020 👋 

Do you mind adding a metadata image as good as you can (if you're able to), something like this:

https://files.raycast.com/e7kq551dfvo63bcavawo6n78vgsc

**Comment by AnishDe12020** [comment]
> Hi @AnishDe12020 👋
> 
> Do you mind adding a metadata image as good as you can (if you're able to), something like this:
> 
> https://files.raycast.com/e7kq551dfvo63bcavawo6n78vgsc

Didn't get it, like a symbol on the menu bar trigger?

**Comment by pernielsentikaer** [comment]
Metadata of what your extension does, where it's open so people can see it, can you make that?

**Comment by AnishDe12020** [comment]
> Metadata of what your extension does, where it's open so people can see it, can you make that?

gotcha, added it!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
