### PR TITLE
Add personio extension

### PR DESCRIPTION
**Pull request by Boosteblume**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Boosteblume** [comment]
@marcjulianschwarz here is our pr

**Comment by marcjulianschwarz** [comment]
This extension is based on the API for the [personio](https://www.personio.de/) HR platform. 

Commands:
- Find Employee Number (shows a list of employee names with their employee IDs)
- Track Time (uses the employee number, start time, end time and break time to track working time)
- Attendances (uses the employee number to list all attendances in the current year)

First Use:
- Provide a client secret and id (see README)
- Find your employee number
- Put the employee number in the according preference

**Comment by marcjulianschwarz** [comment]
No screencast here because of sensitive information but a few screenshots with comments.

## Find Employee Number Command
personio 2024-04-08 at 08 01 36

with actions "Copy Employee Number" and "Paste Employee Number".

## Track Time Command
personio 2024-04-08 at 08 03 10

Select start, end and break time. Actions: "Submit" and "Change Employee Number".

## Attendances Command
personio 2024-04-08 at 08 03 22

List all attendances of the current year (this will be changed to a preference to select a custom time period).

**Comment by marcjulianschwarz** [comment]
The commit adds a month selector for the attendances command and uses the Raycast Cache to cache API tokens and data that doesn't change as often.

personio 2024-04-09 at 10 24 15

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for the contribution 🔥 

Sorry for the long response time. Due to the Easter vacation, we have a slightly increased response time, but it should soon return to normal.

Is this PR ready to be reviewed?

**Comment by marcjulianschwarz** [comment]
Hi @pernielsentikaer, no worries.

I think @Boosteblume is still working on some final touches. Should we ping you when it's ready?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Converted to draft until you're ready 🙂

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Do you mind taking another look @marcjulianschwarz

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
The extension crashes when you enters the wrong credentials, could we handle that gracefully?

personio 2024-04-16 at 15 36 12

**Comment by Boosteblume** [comment]
@pernielsentikaer Could you please tell me how I can reproduce your error? Because if I remove the credentials and clear my cache I only get the 403 errors.

**Comment by pernielsentikaer** [comment]
I just entered some random data 🙂

Raycast16042024-SxGsMkNH png@2x

**Comment by Boosteblume** [comment]
@pernielsentikaer We added a toast message telling the user to re-check his credentials.

**Comment by pernielsentikaer** [comment]
That looks much better, do you think we can stop the loading indicator too?

**Comment by marcjulianschwarz** [comment]
done @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
One last thing about Timezones, will this be an issue that we don't support more in preferencs?

**Comment by Boosteblume** [comment]
@pernielsentikaer Since Personio is only used in Europe we only added some timezones. To provide a broader usability we added GMT+-10 times.

**Pull request merged**
