### PR TITLE
Update passphrase-generator extension

### PR DESCRIPTION
**Pull request by iwex**
## Description

Enhance the dictionary words by adding capitalization and numbers to make it universally applicable for password requirements.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by omBratteng — COMMENTED** [review]
I think it is better to make it an option to have the words capitalised.

And for numbers, either an option to add the number at the end, or convert words to l33t (lite) speak. I.e. `somaplasm-savagize-vaticinant` -> `s0m4pl4sm-s4v4g1ze-v4t1c1n4nt`. As this is based on the [XKCD 936](https://xkcd.com/936/) Correct Horse Battery Staple generator idea.

**Comment by pernielsentikaer** [comment]
Thanks for the review, @iwex can you have a look 🙂

**Comment by iwex** [comment]
I don't think it's necessary to make many different generators with options and sub-options. The solution should be simple for end users. Most sites or applications ask for such password rules: 1 uppercase letter, 1 lowercase letter, a number, and a special character. I believe that the case when we capitalise letters, add dashes and numbers is ideal for any usecase.


If we want a complex set of letters, we already have such a generator - ASCII characters with punctuation

**Comment by pernielsentikaer** [comment]
I'm up for sticking with how it is now, what do you think @omBratteng

**Comment by iwex** [comment]
> I'm up for sticking with how it is now, what do you think @omBratteng

Why?

**Comment by pernielsentikaer** [comment]
I agree with you @iwex 🙂

**Comment by iwex** [comment]
But it may be worth adding only one digit as Bitwarden.
https://bitwarden.com/password-generator/
0r1HbwFm@2x

**Comment by pernielsentikaer** [comment]
Fine with me, at least

**Comment by omBratteng** [comment]
> But it may be worth adding only one digit as Bitwarden or Keeper. [bitwarden.com/password-generator](https://bitwarden.com/password-generator/) 0r1HbwFm@2x
> 
> [keepersecurity.com/features/passphrase-generator](https://www.keepersecurity.com/features/passphrase-generator/) dtWXSpMw@2x

Doing it like that is fine. Can do it to the pronouncable generator too, not just dictionary.

**Comment by iwex** [comment]
@omBratteng 
Pronouncable extends Dictionary, so it will work the same way
xFhFiOFb

**Comment by omBratteng** [comment]
Ah, good.

**Comment by iwex** [comment]
@pernielsentikaer

**Comment by pernielsentikaer** [comment]
Let's get it merged, thanks for flagging 🔥

**Pull request merged**
