### PR TITLE
Add time-tracker extension

### PR DESCRIPTION
**Pull request by iampoul**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

We already have a few time tracker extensions on our store. Does yours provide anything extra that the others do not?
https://www.raycast.com/EinLinuus/time-tracking
https://www.raycast.com/ThatNerd/timers
https://www.raycast.com/melkstam/tyme-3-time-tracker
https://www.raycast.com/asubbotin/pomodoro
https://www.raycast.com/jameslyons/session
https://www.raycast.com/tm.wrnr/tim
https://www.raycast.com/thomas/work-time-countdown
etc

**Comment by iampoul** [comment]
It's simpler and not quite the same

**Comment by mil3na** [comment]
Well, unless you can explain why, I will need to close your PR and mark as duplicated.

**Comment by iampoul** [comment]
Compared to https://www.raycast.com/EinLinuus/time-tracking

It does the same, but also details what existing timers have each of their market share. And under each timer you can see log entries when the time was clocked. Instead of list titles it's colored icon tiles to simplify things. None of the others does or has those features.

**Comment by iampoul** [comment]
It also only does one timer at time, so no dual activities to keep the time separated and force you to plot your time the best way possible

**Comment by mil3na** [comment]
I believe that you can add these functionalities to our existing extensions.
I'm closing this due to duplication. 
Feel free to contact me on Slack if you would like to discuss it further. https://raycast.com/community

**Comment by iampoul** [comment]
🤷

**Pull request closed without merging**
