### PR TITLE
[Apple Reminders] Add create reminders with selected text

### PR DESCRIPTION
**Pull request by ridemountainpig**
## Description
Add create reminders with selected text in the "Create Reminder" command for issue #13853.

## Screencast

https://github.com/user-attachments/assets/6e500180-9385-4a7e-b60e-630ecffc6749

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaslombart** [comment]
Thanks for your PR! I'm having some text pasted in the command even when I don't select any text. Is it the same for you?

**Comment by ridemountainpig** [comment]
> Thanks for your PR! I'm having some text pasted in the command even when I don't select any text. Is it the same for you?

Thank you for your review. I have fixed the problem. Please check.

https://github.com/user-attachments/assets/d4d7bf8e-9261-4702-ae2a-1219cd98e0e3

**Comment by thomaslombart** [comment]
Thanks for the fix. It's still not working reliably on my end. Sometimes it's pasting the old selected text, sometimes it's pasting the text, then clearing out, and then pasting it again.

I don't think there's anything wrong with your implementation though as `getSelectedText` is technically constrained by macOS's APIs 😕

I'll check with the team if we can do anything about it. I'll put your PR on hold in the meantime.

https://github.com/user-attachments/assets/16fed442-b5cd-4d10-8e3b-10cd7ad7db2a

**Comment by ridemountainpig** [comment]
> Sometimes it's pasting the old selected text, sometimes it's pasting the text, then clearing out, and then pasting it again.

This issue arises from not selecting any text and using `getSelectedText()`. This function retrieves the most recent clipboard content. If `getSelectedText()` returns null or an empty string when no text is selected, it can resolve this problem.

**Pull request closed without merging**
