### PR TITLE
docs(lifecycle): correct number of arguments

### PR DESCRIPTION
**Pull request by baboon-king**
## Description

Just only Documentation. 🥳

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the correction, I added it manually to main branch 🔥

**Comment by baboon-king** [comment]
LGTM!
But.
Is this a mistake or an accident, as in the picture from "https://developers.raycast.com/information/lifecycle/arguments"
image

**Comment by pernielsentikaer** [comment]
It's a bit confusing, let me try to explain the flow:

- You make the PR on `main` branch
  - On merge, `main` pushes changes to `gh-pages`

If you push to `gh-pages`, then it will overwrite next time something is merged from `main`

**Comment by baboon-king** [comment]
I got.😀

I mean, "Edit on Github" on the documentation site points to the gh-pages branch. Is this the right?

What I'm wondering is: since I should open “PR” to the main branch, should this “Edit on Github” point to the main branch.

I think I know why, and it's because of the relationship between main/docs and gh-pages. and gitbook base on gh-pages branch. So "Edit on Github" points to the gh-pages branch

**Comment by pernielsentikaer** [comment]
That's correct, it should indeed show the main branch, but it's not what it's built on 🙂

**Pull request closed without merging**
