### PR TITLE
[Liveblocks] Refactor and updates for v2

### PR DESCRIPTION
**Pull request by andreaselia**
## Description

Still a little testing to do, but ready for a general review of the code/functionality.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hey! I converted it to a draft as you marked as WIP. Just mark as ready for review when you are ready :)

**Comment by mil3na** [comment]
Is this ready for review now?

**Comment by andreaselia** [comment]
> Is this ready for review now?

@mil3na a preliminary review would be great, please.

**Review by mil3na — CHANGES_REQUESTED** [review]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

My first concern is that, I accidently entered the wrong key and this error popped up. Can you please make it is handled better?
CleanShot 2024-07-26 at 14 37 42

Second, as I don't have enough data to test the extension, do you mind sending a video with the basic usage of it?

I've also seen `console.log` on the code. Can you please remove them before the final version?

**Comment by andreaselia** [comment]
@mil3na I'll provide a video, but in terms of the error, the message itself is self explanatory, and a toast error isn't clear enough for this scenario, what would you recommend doing instead?

**Comment by mil3na** [comment]
No, you should never throw an error like this at the user. You should handle it and show a more intuitive message. Either on the bottom left or a separate panel.

**Comment by andreaselia** [comment]
> No, you should never throw an error like this at the user. You should handle it and show a more intuitive message. Either on the bottom left or a separate panel.

Yeah, I know a user shouldn't see stack trace error, that's why I asked for a suggestion, I'll look at adding an empty view for this. I wonder if there'd be a feature request in here somewhere for adding your own validation to preference fields? 😄

**Comment by mil3na** [comment]
What kind of validation are you missing? As it is a form, you can use the form validation: https://developers.raycast.com/api-reference/user-interface/form

**Comment by andreaselia** [comment]
> What kind of validation are you missing? As it is a form, you can use the form validation: https://developers.raycast.com/api-reference/user-interface/form

That form is provided by Raycast automatically via the preferences in the package.json file, so we have no control over that or validating it at the moment as far as I'm aware?

```json
"preferences": [
  {
    "name": "secret",
    "type": "password",
    "required": true,
    "title": "Secret Key",
    "description": "You can find your Secret Key in the Liveblocks Dashboard."
  }
],
```

It would be cool to be able to validate this with custom validation though, other than just what's allowed here such as `required`.

I'll work on catching this error and try to pass it through to its own detail view.

**Comment by andreaselia** [comment]
Ah yes, I need to produce the video. I'll do this ASAP so you can see it working with data and approve @mil3na 👍

**Comment by andreaselia** [comment]
@mil3na instead of a video, I thought I'd just provide screenshots of a few states and fixes.

The "active users" details:

CleanShot 2024-08-24 at 22 46 15@2x

Rooms list with the new room for the "active users" listed above:

CleanShot 2024-08-24 at 22 46 22@2x

Gracefully handled the wrong API secret being provided:

CleanShot 2024-08-24 at 22 46 36@2x

**Comment by pernielsentikaer** [comment]
I would maybe use `List.EmptyView` to show the error instead of the markdown view. Then you can also add the `Icon.Warning` icon 🙂

**Comment by andreaselia** [comment]
> Hi @andreaselia 👋
> 
> Awesome that you're working on an update on this extension 🔥
> 
> I would maybe use `List.EmptyView` to show the error instead of the markdown view. Then you can also add the `Icon.Warning` icon 🙂
> 
> Is the data dynamic on the user? Instead of just showing the json string, could we parse and show it as metadata?

Updated it to use `List.EmptyView`, good suggestion!

I did originally have the data parsing (might be in the commit history), but it didn't make sense to me as the data can have many different types of values and lengths, so it wouldn't always be readable.

**Comment by pernielsentikaer** [comment]
Do you by any chance have a secret key I can test with? You can DM me on Slack 🙂

**Comment by andreaselia** [comment]
@pernielsentikaer to have a look when he gets back 😁

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
