### PR TITLE
Add duckduckgo-email extension

### PR DESCRIPTION
**Pull request by Hugo-Persson**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋

Sorry for the long response time. Due to the Easter vacation, we have a slightly increased response time, but it should soon return to normal.

Is there no other way to get the token?

**Comment by Hugo-Persson** [comment]
> Hi 👋
> 
> Sorry for the long response time. Due to the Easter vacation, we have a slightly increased response time, but it should soon return to normal.
> 
> Is there no other way to get the token?

Hello!

I do not think there exist any other way than what I explained in README.

**Comment by pernielsentikaer** [comment]
Thank you for the clarification. It's definitely not the best way but if no other way is possible it might be sufficient 🙂

- Could you provide me with a screencast of the flow since I don't have duckduckgo

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

**Comment by Hugo-Persson** [comment]
@pernielsentikaer The page to get duckduckgo email looks like this:

image

The extension has no menu that can show a screenshot. When running command the only output is a toast message and that we push text to the clipboard.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
There is currently no error handling, if you insert a wrong token you'll just see the success HUD

Could you look into that?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Hugo-Persson** [comment]
@pernielsentikaer I have added error handling now. An HUD message is shown if the token is invalid or similar 

image

**Pull request merged**
