### PR TITLE
add extension notion-ctrl

### PR DESCRIPTION
**Pull request by nbr41to**
## Description

- Link to Notion Database
- Post Content to Linked Notion Database
- By Notion API(https://developers.notion.com/)

## Screencast

https://user-images.githubusercontent.com/59198478/162627006-6ba5e737-ac96-4f96-baa3-82e7bb271a40.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @nbr41to 👋 

Thanks for your contribution 💯 

I'm not that into Notion, but would it make sense to merge it into the current [Notion extension](https://www.raycast.com/HenriChabrand/notion) if it has some additional features?

**Comment by nbr41to** [comment]
@pernielsentikaer 

Thank you for your review🙏

It is indeed similar to this Notion extension.

The extension I created is
It has enough shortcuts to keep track of what you have typed in the last time and to make other functions quicker to use.

It is designed to allow you to post to the same Database in a centralized manner.

**Comment by pernielsentikaer** [comment]
Hi @nbr41to 👋 

Thanks for the clarification 💯 

What do you think about merging the feature into the other extension instead of adding a new extension?

**Comment by pernielsentikaer** [comment]
I'm closing this due to inactivity; feel free to open it again or comment in the thread when you're ready to continue working on it 🙂

You can also catch me in [Slack](https://www.raycast.com/community) if you want to discuss 😄

**Pull request closed without merging**
