### PR TITLE
Add mute-microphone extension

### PR DESCRIPTION
**Pull request by quentin23soleil**
## Description

As suggested [here](https://raycastcommunity.slack.com/archives/C01AC2X0GMN/p1686596670686899) 
A mute/unmute audio input (microphone) extension with a menu bar item to see the current state and toggle it between mute/unmute.

This commands saves the default non-zero mic value to restore it when you unmute. This means that if your mic level was let's say 51% and you mute it, when you unmute it won't be at 100% but the extension will restore it to 51%. Because we're nice like that. 

## Screencast
image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
We just released our own version of `runAppleScript`, I switched to that since it has some configuration for Raycast built-in 🙂

This seems to be working as expected when `MacBook Pro Microphone` is the selected input, if having a USB microphone connected it doesn't seem to work as expected (It kept saying that it set it to 51% only)

I can record a video or help with some debug data if needed 🙂

**Comment by quentin23soleil** [comment]
thanks for the runAppleScript

I'll look into that, can you confirm that you can manually change the input volume of your usb mic in the macos audio settings?

**Comment by pernielsentikaer** [comment]
In this video you can see it, I didn't capture the HUD but it kept saying 67 in this video for Instra360 🙂

https://github.com/raycast/extensions/assets/38033107/36a05aa1-d32a-45bf-9e20-c777e4e74314

**Comment by quentin23soleil** [comment]
oh very useful video thanks! I'll fix that and request review :)

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by quentin23soleil** [comment]
@pernielsentikaer as discussed, added a HUD to say it's not supported sorry about that

**Comment by pernielsentikaer** [comment]
Are you okay with this @quentin23soleil

**Comment by quentin23soleil** [comment]
Absolutely

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
