### PR TITLE
Add cron-manager extension

### PR DESCRIPTION
**Pull request by CarterMcAlister**
## Description
This extension is a tool for easily managing cron jobs locally, and viewing logs for the jobs.
It uses crontab to list and update the user's cron jobs, and parses /var/mail/{username} for cron job run history and output.

## Screencast
cron-manager-1
cron-manager-2
cron-manager-3
cron-manager-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
How does this work? I tried to add a cronjob but nothing is shown in the extension? 

Raycast28102024-m6gunXAx png@2x

**Comment by CarterMcAlister** [comment]
@pernielsentikaer Thanks for taking a look

The extension requires cron jobs to have `Name` and `Description` comments (if added through the extension, it adds them automatically.) I note this in the readme here: https://github.com/raycast/extensions/pull/15027/files#diff-f8d925ec6a96f539203e33718107f5ba434f701ee345977711584709c9182b91R45

I did overlook that it's not possible to add a job through the extension if no jobs already exist, I've now added that.

**Comment by pernielsentikaer** [comment]
Is this ready for another review?

**Comment by CarterMcAlister** [comment]
@pernielsentikaer Yes, it's ready for review

**Comment by pernielsentikaer** [comment]
The extensions suffer from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) - could you handle that?

Is it correct that we're only showing cronjobs added from Raycast and not if any was added from outside with crontab -e

**Pull request closed without merging**
