### PR TITLE
Add markdown-codeblock extension

### PR DESCRIPTION
**Pull request by lacherogwu**
## Description

# Markdown Codeblock

Wraps your code in a Markdown code block.

This works well when chatting with AI, as it provides more context for the code block.

## Recommended Hotkey

`⌘;`

### Paste from Clipboard

1. copy the code you want to wrap in a codeblock and run the command
2. select the language you want to use for the codeblock and press enter (⏎)

### Paste from Selection

1. select the code you want to wrap in a codeblock and run the command
2. select the language you want to use for the codeblock and press cmd + enter (⌘⏎)

markdown-codeblock-2

## Example

I have the following code in my clipboard:

```go
package main

import "fmt"

func main() {
    fmt.Println("Hello, World!")
}
```

I run the command and select `go` as the language for the codeblock:

and the codeblock is inserted in the markdown file:

````markdown
```go
package main

import "fmt"

func main() {
    fmt.Println("Hello, World!")
}
```
````

## Credits

Thanks for icons from [vscode-material-icon-theme](https://github.com/material-extensions/vscode-material-icon-theme)

## Screencast
markdown-codeblock-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

The first time I opened the extension, I ended up in this view

markdown-codeblock 2024-11-15 at 12 47 18

Try uninstalling your extension and installing it again. Could you look into this? The first time you search, it loads the list as expected😊

Would it be possible to support just selecting text too, or doesn't that make any sense?

**Comment by lacherogwu** [comment]
> Hi 👋
> 
> The first time I opened the extension, I ended up in this view
> 
> markdown-codeblock 2024-11-15 at 12 47 18
> 
> Try uninstalling your extension and installing it again. Could you look into this? The first time you search, it loads the list as expected😊
> 
> Would it be possible to support just selecting text too, or doesn't that make any sense?

Hi thanks for checking this out, of course I'll take a look right now and push a fix.

about the selecting text, let me make sure I got it right, you want instead of copy, just select select, text open this command, select laguage hit enter and it will wrap it in a codeblock? is this your intention? if yes, yeah it makes sense and I can support this as well.

**Comment by lacherogwu** [comment]
@pernielsentikaer fixed bug and added your suggestion :) clicking ⌘+⏎ it will take the selected text instead of the clipboard text

**Comment by pernielsentikaer** [comment]
Is this ready for another review or not yet?

**Comment by lacherogwu** [comment]
> Is this ready for another review or not yet?

yes it does

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
