### PR TITLE
Netlify Extension: update icon

### PR DESCRIPTION
**Pull request by peduarte**
## Description

New Icon for Netlify

## Screencast

(ಠ ›ಠ) — @peduarte — qnRQO89X000846@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jasonbarry** [comment]
@peduarte Very snazzy! I see `icon.png` was removed, however that flat logo is still in use as the icon for a few of the Action menus. Maybe keep that png around?

**Comment by peduarte** [comment]
@jasonbarry good shout, I overlooked this. Normally extension icons are only used for that! Will add it back. Thanks for the heads up!

**Comment by peduarte** [comment]
@jasonbarry all done, to avoid confusion, I called the extension icon `extension-icon` which is a pattern we try to follow anyway, and the other one `netlify-icon`. Cheers!

**Review by jasonbarry — APPROVED** [review]
LGTM, thanks for the fresh look!

**Comment by peduarte** [comment]
Cool, just waiting for final confirmation from Nichlas.

**Comment by peduarte** [comment]
Updated icon by our designer

**Pull request merged**
