### PR TITLE
[Toggle Audio Input (microphone)] not restoring last audio input LEVEL

### PR DESCRIPTION
**Pull request by aliaksandrZh**
## Description
Issue: https://github.com/raycast/extensions/issues/12516
Audio input level is maintained by default

## Screencast
[Screen Recording 2024-05-28 at 11.23.00.webm](https://github.com/raycast/extensions/assets/108681764/d883265f-b4b9-4934-85d3-5eb3767dee8a)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @aliaksandrZh 🔥 

@quentin23soleil  do you want to check this

**Comment by quentin23soleil** [comment]
@pernielsentikaer won't have time before next week so I'll pass sorry

**Comment by pernielsentikaer** [comment]
All good, I'm giving it a spin 🙂

**Comment by pernielsentikaer** [comment]
Hi @aliaksandrZh 👋 

I think it makes sense to just have the preferences in extension level and not in both commands, is there a reason why you would have one command to do something different than the other one?

**Comment by pernielsentikaer** [comment]
And do we even need the preferences? I think a toggle should switch on/off and maintain the current level if possible. That would make the preference redundant

**Comment by aliaksandrZh** [comment]
> And do we even need the preferences? I think a toggle should switch on/off and maintain the current level if possible. That would make the preference redundant

Actually I agree that the keep input volume value by default is more convenient but there are a lot of flags in the code and I didn't want to change the core logic (May be It has some hidden sense 😅).

If you don't mind I would prefer to rid of that logic and preferences, and maintain the current level

**Comment by pernielsentikaer** [comment]
I would suggest that we remove the preference and clean up the code, as it's a toggle extension

**Comment by NotFiliberto** [comment]
I have a problem with it, when i toggle it with keyboard shortcut it is also triggered raycast (the search bar is showed up)

**Comment by 1activegeek** [comment]
Same here as reported above. Good news - it is in fact saving the level and restoring it. But it is quite annoying that the raycast window opens afterward. I'm guessing this may just be a bug someone can identify quickly. 🤞🏻

**Comment by iamyeizi** [comment]
and the option I had added doesn't work as expected 🙂

CleanShot 2024-05-31 at 12  27 53

**Comment by aliaksandrZh** [comment]
Will test it

**Comment by aliaksandrZh** [comment]
Hi, @NotFiliberto @1activegeek @iamyeizi
Thank you for the finding bugs

Could you take a look? https://github.com/raycast/extensions/pull/12685

**Comment by NotFiliberto** [comment]
Hi @aliaksandrZh, seems working fine now. Last (mini)bug is that if you try to use the hotkey when you opened the menubar toggle, it does not change, but I don't know if you can do something about that or it works like this. Take a look of the screenrec

https://github.com/raycast/extensions/assets/49571243/f6cc1647-9170-439f-a9e7-6bf5aa388b25

**Comment by iamyeizi** [comment]
I've tried that too, I thought he had included it. Whit a shortcut set or the toggle button from the menu bar icon it doesn't work as expected.

**Pull request merged**
