### PR TITLE
Fix for #4835, adds support for less than 1 day due date

### LINKED ISSUE #4835: [Beeminder] Show hours before goal is due
### Extension

https://www.raycast.com/vivgui/beeminder

### Description

The current behavior is to show the number of days before the goal is due:

image

Instead, it could be useful to show hours left.

### Who will benefit from this feature?

People who have non-midnight deadlines

### Anything else?

Thanks a lot for this cool extension!

### PR DESCRIPTION
**Pull request by vivgui**
## Description

On the beeminder extension, adds support for less than 1 day due date. Fixes #4835.

## Screencast
beeminder-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Did you consider moving the ball icon in the accessories all to the right so it's not confusing the eye 😊

**Comment by vivgui** [comment]
> Did you consider moving the ball icon in the accessories all to the right so it's not confusing the eye 😊

Great idea! Just pushed that improvement.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Comment by clouedoc** [comment]
@vivgui hey, thanks a lot for taking the time to do this!

**Comment by vivgui** [comment]
> @vivgui hey, thanks a lot for taking the time to do this!

No problem, thanks for reporting the bug!

**Pull request merged**
