### PR TITLE
Update Arc extension

### PR DESCRIPTION
**Pull request by hinzed1127**
## Description

Add ability to filter by tab type in the Arc 'Search Tabs' command via dropdown

## Screencast
screenshot showing an active query with only unpinned tabs being searched
Screenshot 2024-03-05 at 3 43 00 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by xilopaint** [comment]
This is a good idea, but it would be much better implemented as a dropdown.

**Comment by hinzed1127** [comment]
@xilopaint good call, I updated things to use that approach

**Comment by loris** [comment]
This is a great addition, especially using the dropdown, which is now the most standardised pattern to do that in Raycast.
I would like to have that dropdown filter also in the "Search Arc" command, which i'm personnaly using most, let me know if you are OK to add it as part of your PR, otherwise I will find some time in the week to do it
Thanks!

**Comment by xilopaint** [comment]
@hinzed1127 You have conflicts to resolve.

**Comment by pernielsentikaer** [comment]
Yes, could you look into the conflicts 🙂

**Comment by hinzed1127** [comment]
@loris I don't have time to add that functionality at the moment. Let's address that in a separate PR, if you don't mind.

@pernielsentikaer conflicts resolved. Ready to merge this whenever if it looks go to you!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
