### PR TITLE
List pipelines without execution history

### PR DESCRIPTION
**Pull request by JonathanWbn**
## Description

This solves the bug described in #721. The case of pipelines without any executions was not handled and resulted in an infinite loading state. This is now fixed by resolving the promise with `null` in such a case.

While I was at it I also fixed the status icon namings and added a missing one (see commits).

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @victor-falcon

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @JonathanWbn 👋 

Awesome, thanks for your contribution 💪

@victor-falcon do you have any feedback?

**Comment by victor-falcon** [comment]
Thanks for the fix!

**Review by pernielsentikaer — APPROVED** [review]
Hi @JonathanWbn 🚀 

Thanks for the contribution! 💪 I'm going to accept it and then will my colleague do a final review before it's finally merged.

**Review by mathieudutour — APPROVED** [review]
Looking good :+1:

**Pull request merged**
