### PR TITLE
[Notion] Separate page to edit page property

### LINKED ISSUE #12751: [Notion] Editing existing database pages
### Extension

https://www.raycast.com/notion/notion

### Description

Hi, 
I started using the Create Database Page command a lot lately, and something that I'm missing and still have to go to the app for is editing existing pages. I love the interface of the Create Database Page command, as well as its functionality, and I'd love for it to be implemented in a command that will allow to search for a specific page in a database, and then edit different properties. 
I tried creating such extension, but failed miserably since I am not a developer and have no clue how to code... 

### Who will benefit from this feature?

Everyone who has a need to update/edit existing database pages. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bkeys818**
## Description

Close #12751
- `Edit Page Properties` action now pushes to separate view.
- All database pages in search view show the `Edit Page Properties` action.

I definitely need someone to help me with testing this. There are a lot of changes, and I want to be sure everything works before we roll it out.

## Screencast

https://github.com/user-attachments/assets/ef65b420-2d42-4ec8-97f8-0f39557f412e

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaslombart** [comment]
I'll need to revisit how this extension works to properly review it and help you test it. I'll probably do that within the next week.

**Review by thomaslombart — COMMENTED** [review]
Thanks for the PR! I'm getting this error while editing a page:

https://github.com/user-attachments/assets/fdeb71eb-88dc-44e9-9d3d-33109e44cf24

I'm also wondering if it would be better to turn `CreatePageForm.tsx` into a `PageForm.tsx` file that can be used to both create and edit database pages. That way, most of the code can be shared.

**Comment by bkeys818** [comment]
I like the idea of creating a single `PageForm.tsx`. I initially wanted to do that, but it would have been super complicated due to how page properties are handled.

As I mentioned in [my last PR](https://github.com/raycast/extensions/pull/13579#pullrequestreview-2199247614), the way property components really need to be reworked. I've been dreading it, but it's a constant roadblock.

I'm going to put this PR on hold and get to work on handling the page property components. I'll open a draft soon.

**Comment by thomaslombart** [comment]
Sounds good, I've marked it as draft. Let me know when it's ready to review again 🙂

**Pull request closed without merging**
