### PR TITLE
Add vocabulary extension

### PR DESCRIPTION
**Pull request by 2eha0**
## Description

Search words on vocabulary.com

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @2eha0 👋

Thanks for your contribution 🔥

How does this extension compare to the one we already have in [our store](https://www.raycast.com/datadeer/vocab)?

**Comment by 2eha0** [comment]
@pernielsentikaer The original one doesn't have a detail page, so every time I need to check details, I have to open a browser. As you can see from the screenshots, I've now included the detail page here, which allows me to complete most of my inquiries without needing to leave Raycast :)

**Comment by pernielsentikaer** [comment]
Having two extensions serving the same purpose doesn't make sense. It would be a nice enhancement to the one in the store by @DATADEER 🙂

**Comment by mil3na** [comment]
Hi! As Per said, this would be a nice addition to an already existing extension. 
I will be closing this PR due to that.
If you would like to discuss it further or need help with anything, feel free to contact us on our Slack community! https://raycast.com/community

Cheers!

**Pull request closed without merging**
