### PR TITLE
Add saved-items extension

### PR DESCRIPTION
**Pull request by sunny0826**
## Description

Save some items (eg. quick replies) and insert or copy them.

## Screencast

saved-items-1
saved-items-3
saved-items-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

This feels a bit like `Snippets` inside Raycast, the only difference I can spot is you can have images in yours (but I haven't figured that out yet) - is that the reason for making this extension? 🙂

**Comment by sunny0826** [comment]
In fact, I didn't know about Snippets before 😂. But after using Snippets, I think `saved-items` is a lighter version of Snippets with only one command.

**Comment by pernielsentikaer** [comment]
`Snippets` also have the possibility to expand using a keyword. 

Ouf of curiosity, how do you add an image in yours?

**Comment by sunny0826** [comment]
Set `enableMarkdown` in `Form.TextArea` and enter the image address in Markdown format in detail.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You can add [destructive](https://developers.raycast.com/api-reference/user-interface/actions#action.style) style to your delete action, maybe also a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) if you think it's worth it 🙂

- I would use cmd+n for new item and ctrl+x to delete as the rest of Raycast does it


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by sunny0826** [comment]
@pernielsentikaer Sorry I just got off a long business trip. Have updated the code as per your feedback.

**Pull request merged**
