### PR TITLE
Brave Search extension

### PR DESCRIPTION
**Pull request by CoinFundApp**
## Description

Brave Search with autosuggestion

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
What about adding this command to the [Brave](https://www.raycast.com/ron-myers/brave) extension instead?

**Comment by Spl0itable** [comment]
> What about adding this command to the [Brave](https://www.raycast.com/ron-myers/brave) extension instead?

Possible, but I don't use the Brave browser. So, this extension is browser agnostic.

**Comment by pernielsentikaer** [comment]
I was about to merge this and saw that another version was added #4094

Is there something in that one that could benefit this extension, or does it superseed yours?

**Comment by VishwasShashidhar** [comment]
@Spl0itable As @pernielsentikaer mentioned, I've created a similar extension in #4094 with a few more features (like Opening in specific browsers, keeping history etc.), if you think you can add those features, I'll be happy to close my PR.

**Comment by Spl0itable** [comment]
> 

Yes, the one from @VishwasShashidhar has added features like from the Google Search extension. Feel free to close my PR and use theirs. 👍

**Comment by pernielsentikaer** [comment]
Let's do that, but I think we should add you as contributor anyway in the #4094

**Comment by VishwasShashidhar** [comment]
Thank you @Spl0itable & @pernielsentikaer  👍

**Comment by Spl0itable** [comment]
Thank you @VishwasShashidhar 🙌

**Pull request closed without merging**
