### PR TITLE
Add color-hunt extension

### PR DESCRIPTION
**Pull request by bxb100**
## Description

Color Palettes for Designers and Artists

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I woud remove the command `Clear Cache` and just built it into `Search Palettes` instead
- I would remove the command `Favorite Palettes` into `Seach Palettes` in a new secion in top

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by bxb100** [comment]
@pernielsentikaer Thanks for the review.

> I woud remove the command Clear Cache and just built it into Search Palettes instead

That sounds good, but I prefer to keep this command for myself, and the `search` page had lots of actions, so I chose to keep it

> I would remove the command Favorite Palettes into Seach Palettes in a new secion in top

Good idea, and I implement it on the latest commit

**Comment by pernielsentikaer** [comment]
Can we set it `disabledByDefault` then, I don't think most of the users knows what it is, and is there a reason why we need to do that in the first place?

**Comment by bxb100** [comment]
LOL, it's just my OCD needs a place to know how many files have been downloaded and the cache size.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
You might need to have a `try {} catch {}` around the thing that runs `clear` since the main command now crashes 🙂

**Comment by bxb100** [comment]
@pernielsentikaer Thanks to the review, this problem has been fixed

**Comment by pernielsentikaer** [comment]
Should we consider to only have one action for pin/unpin like rest of Raycast? We also have a default shortcut for that in `Keyboard.Shortcut.Common.Pin`

**Comment by bxb100** [comment]
Good idea and it seems a bug exists, I will fix it ASAP

**Comment by bxb100** [comment]
Previously, every fetch required updating the 'clear' subcommand subtitle, causing significant performance lag due to counting the local files. Therefore, I have removed it and added a new index action.

SCR-20240521-qkte
SCR-20240521-qkug

**Comment by pernielsentikaer** [comment]
Should we remove favorites from the normal list, I think it would make sense?

**Comment by bxb100** [comment]
done 

SCR-20240521-rncj-3

**Review by pernielsentikaer — COMMENTED** [review]
I might have explained myself incorrectly, sorry about that. I kind of liked that "Favorites" was on top in it's own section, but it was also present in the "regular grid" which didn't make sense - do you think we can do that?

**Comment by bxb100** [comment]
Do you mean this?

SCR-20240521-rytn
SCR-20240521-ryxq

SCR-20240521-saem

**Comment by bxb100** [comment]
👌 it has been reverted

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
