### PR TITLE
Add french-verb-conjugation extension

### PR DESCRIPTION
**Pull request by J0**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @J0 👋 

I just tested the extension but was not able to get it to work, ended up with errors like below:

image

Can you record a video of how it work for me?

**Comment by J0** [comment]
Sure thing, Here's a [video demo](https://youtu.be/J1JBEgB2kCo). It's quite basic for now, planning to add additional features (e.g. allow and correct for verbs with one typo)

**Comment by pernielsentikaer** [comment]
I really like the table view, but is it the best for this?

I'm not a regular user of an extension like this so I can judge - if you added it as a `List` you would be able to get copy functions too, like below

french-verb-conjugation 2023-05-22 at 14 27 07

What do you think?

**Comment by J0** [comment]
Hey @pernielsentikaer,

Thanks for the swift reply! I quite like the List view as well as it would be nice to be able to copy conjugations on the fly. I do have a concern though - when I search for a verb conjugation I often don't know what the exact name of the tense is (imparfait/subjunctive/etc).  This might be just me because I'm not a native speaker and have only recently started learning. What I would then do is search for the verb itself (e.g. aller) and  then look for the corresponding tense [on a conjugation site like this](https://conjugator.reverso.net/conjugation-french-verb-aller.html). Thus, when I initially wrote this I was somewhat hoping to replicate that flow.

Do you have any suggestions on how this might be replicated in a List setup? (e.g. allow user to quickly view all tense-conjugations for the verb)

Let me know!

**Comment by pernielsentikaer** [comment]
You could use `keyword` on `List.Item` to append imparfait/subjunctive/etc - also still grouping it in sections, would that help? 🙂

**Comment by J0** [comment]
Yeah! That sounds good, will give that a go and get back to you

**Comment by pernielsentikaer** [comment]
Awesome, let me know if you need any help

**Comment by J0** [comment]
Hey @pernielsentikaer,

Apologies for the long delay - here's how it looks like right now:
Screenshot 2023-06-05 at 6 06 35 PM

Quick question: how did you get the  `je, tu,il`  in this [image](https://github.com/raycast/extensions/pull/6254#issuecomment-1557136847) to turn white?  Have been looking around the API docs but wasn't able to find the right property - wondering if you could point me in the right direction

**Comment by pernielsentikaer** [comment]
I didn't do anything else than select a dark theme since the list is theme aware

Raycast-f6atVG08@2x

**Comment by J0** [comment]
Ah cool! Thought there was an API feature I didn't know about 😅 Let me put some final touches on the PR  later this week (e.g. errors, proper 404 etc) and I'll send it back for review.

Thanks!

**Comment by pernielsentikaer** [comment]
You can add [tags](https://developers.raycast.com/api-reference/user-interface/list#list.item.accessory) that can have colors, that can maybe also be used for something 🙂

**Comment by J0** [comment]
Hey @pernielsentikaer,

Thanks for patiently waiting. Was wondering if I could trouble you for a re-review on the extension when a slots frees up. Here's a video showing how it works now:

https://github.com/raycast/extensions/assets/8011761/5be3484e-ab12-48e9-880b-5c9cbb6b8456


## Major Changes
- I've removed the option to indicate tense and mode as I realised I personally don't use the options when on a [French Conjugation Site](https://www.frenchconjugation.com)
- Swapped the layout to be a list so that we can hit enter to copy

I've left out tags out for now as I can't think of clear icons that would signal the differences in tenses. Will revisit for a v2 though.

Let me know if there are any questions/concerns.

Thanks!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
- Maybe add a better logo without the developer lines on, something like this

fr_icon

- Instead of the kitten I would maybe just rescale the above image to 128x128 and add that as icon instead 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by J0** [comment]
Hey @pernielsentikaer,

Wanted to bump this in case it was missed.  Really hoping to push this across the line! Let me know if there are any issues or changes you'd like to see made.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by J0** [comment]
Nice! Thanks for all the guidance so far @pernielsentikaer Really appreciate it :)

**Pull request merged**
