### PR TITLE
Add feishu-document-creator extension

### PR DESCRIPTION
**Pull request by rokcso**
## Description

Create Feishu/Lark document in one click using native Feishu/Lark URLs.

Read more: https://github.com/rokcso/feishu-document-creator

## Screencast

Feishu Document Creator Preview-1

Feishu Document Creator Preview-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

How is this compared with [this extension](https://www.raycast.com/tmk/lark) by @tmkx - would it be possible to enhance or is it two completely different things?

**Comment by rokcso** [comment]
> Hi 👋
> 
> How is this compared with [this extension](https://www.raycast.com/tmk/lark) by @tmkx - would it be possible to enhance or is it two completely different things?

Hi @pernielsentikaer.

The main function of [this extension](https://www.raycast.com/tmk/lark) you mentioned is to log in to the specified Lark account and search for the Lark document under that account, and then you can open the Lark document.

The main function of my extension is to create a blank Lark document more quickly and conveniently, and there is no need to log in to any account. By default, create a new blank Lark document under the account that the user's current browser has logged in to.

These two extensions are not solving the same problem.

At the same time, I have searched all the current extension of Raycast about Lark/Feishu, and it can be said that my extension is solving a problem that has not been solved yet.

**Comment by rokcso** [comment]
> I think this extension is more like a quicklink collection 🤔, and it can be added to https://www.raycast.com/chyroc/lark-applink, do u think so?

I quite agree that this extension is a quicklink collection, but this extension is not quite the same as [Lark Applink](https://www.raycast.com/chyroc/lark-applink), which is mainly aimed at the AppLink of the Feishu/Lark client, and all its quicklink is used to quickly open a page in the Feishu/Lark client.

My extension focuses on quickly creating new Feishu/Lark blank documents, and I think the need to open a page in the Feishu/Lark client through quicklink and the need to quickly create new Feishu/Lark blank documents are not necessarily the common needs of the same group of users, so I still hope that the extension can be independent for a dedicated extension for creating Feishu/Lark blank documents.

That's why this extension is named Feishu Document Creator.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
