### PR TITLE
[dict.cc] feat: Play audio support

### PR DESCRIPTION
**Pull request by sjdonado**
## Description

Add an action menu option that allows to play the translation pronunciation audio.
Changes added to the source library https://github.com/natterstefan/dictcc/pull/44.

Thanks @natterstefan for your support in the previous PR :)

## Screencast
(Please turn on audio)

https://user-images.githubusercontent.com/27580836/217369631-6da14336-38ba-43e1-b231-367efab9c3d5.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
There is no such property called `targetTranslationAudioUrl` according to `node_modules/dictcc/dist/cjs/types.d.ts` - is there a newer version that contains that @sjdonado?

**Comment by natterstefan** [comment]
Hi @pernielsentikaer,

I still have to deploy an update of `dictcc` (see https://github.com/natterstefan/dictcc/pull/44). This PR depends on that, and I think @sjdonado used his local version that works compared to the one you see here.

I will let you know when it's published.

**Comment by pernielsentikaer** [comment]
Awesome, thanks for the explanation 🔥

**Comment by natterstefan** [comment]
Hi @sjdonado @pernielsentikaer.

A new version of `dictcc` (https://www.npmjs.com/package/dictcc) was just published. Please, update it @sjdonado accordingly, and then you can review it again, @pernielsentikaer.

Have a nice day you two.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Waiting for a request review then 😊

**Comment by sjdonado** [comment]
@pernielsentikaer `package.json` updated accordingly, and all checks green :)

**Comment by natterstefan** [comment]
@pernielsentikaer Do I have to review it as the author of the extension as well?

**Comment by pernielsentikaer** [comment]
If you like, sure - if you deny it we might drop it 😉

**Review by natterstefan — APPROVED** [review]

**Comment by natterstefan** [comment]
Congrats and thank you @sjdonado!

**Pull request merged**
