### PR TITLE
Brew: Add support for searching and managing casks

### PR DESCRIPTION
**Pull request by nhojb**
## Description

Adds support for searching and managing casks in addition to formulae.

## Type of change

Enhancement.

Screenshot 2021-10-29 at 12 58 07

Screenshot 2021-10-29 at 12 58 24

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I'm using the M1 chip and I can't get it to work properly.

- Show Installed: Gives me one package, the first few times opening it I had 50+ on the list.

Xxlz09oW0RhXEMlF

- Show Outdated: Gives me one package (Had a lot of entries the first few runs)

cP8VRMNL6XfaynRb

- Search Formulae: Gives a lot of packages but can't install anyone of them, I'm just getting "Install failed"

JYmsIHhJhRfAnEKR

```
2021-11-02 08:12:43.604 F  Raycast[780:6095d] [com.raycast.extensions.brew:search] Error: Command failed: /opt/homebrew/bin/brew install aamath
fatal: Could not resolve HEAD to a revision
Warning: No available formula or cask with the name "aamath".
Error: No similarly named formulae found.
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/opt/homebrew/bin/brew install aamath',
  stdout: '==> Searching for similarly named formulae...\134n' +
    '==> Searching for a previously deleted formula (in the last month)...\134n',
  stderr: 'fatal: Could not resolve HEAD to a revision\134n' +
    'Warning: No available formula or cask with the name "aamath".\134n' +
    'Error: No similarly named formulae found.\134n' +
    'Error: No previously deleted formula found.\134n' +
    '==> Searching taps on GitHub...\134n' +
    'Error: No formulae found in taps.\134n'
```

**Comment by nhojb** [comment]
@pernielsentikaer thanks for the feedback and error reports. I'll look into M1 support again. Obviously something is wrong.

**Comment by nhojb** [comment]
@pernielsentikaer I've improved error handling and also tweaked the way I discover paths on M1. However, I'm not sure this will address your issues with the Install action. Do you have any customisations set for brew e.g. in your shell environment?

**Comment by PitNikola** [comment]
@pernielsentikaer, let John know if you still experience these issues so he can address them in separate PR. Will merge it for now.

**Comment by sfwn** [comment]
Issue still exists if you have installed brew of both two arch:
- /usr/local/Homebrew/bin/brew
- /opt/homebrew/bin/brew

It works on terminal correctly,
image

But broken on raycast,
image

I have set PATH via `~/.profile`,
image

**Comment by pernielsentikaer** [comment]
Hi @sfwn 👋 

Could you open an [Extension Issue](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2C+bug&template=extension_bug_report.md&title=) with the above instead 😄

**Comment by sfwn** [comment]
> Hi @sfwn 👋
> 
> Could you open an [Extension Issue](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2C+bug&template=extension_bug_report.md&title=) with the above instead 😄

yes, #1701 created :)

**Pull request merged**
