### PR TITLE
add image-host extension

### PR DESCRIPTION
**Pull request by clkefe**
## Description

Adds a new extension, image-host

## Screencast

image-host-1

image-host-2

## Checklist
- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

We don't support submodules, could you submit your extension to the `extensions` folder 🙂

**Comment by SuleymanEfe** [comment]
Hello! I updated it 👍

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you add a `isLoading` property to your `<Form>` and add an error toast with the error message if any?

- Maybe use useForm in your form so you can clear it after successfully submit OR popToRoot()

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by SuleymanEfe** [comment]
Woaw! Thank you for the suggestions!! I changed the code, so now it uses `useForm` and errorToasts.

Thank you!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
