### PR TITLE
Add raycast-arcade extension

### PR DESCRIPTION
**Pull request by EvanZhouDev**
## Description
A new extension that allows you to play good old ASCII games.
Currently, we have these 3 following games:
- Tetris
- Chrome Dino
- Daily Wordle

(Snake removed because @tonka3000 already has a Snake game on Raycast)

With more to come!

## Screencast
raycast-arcade-1
raycast-arcade-2
raycast-arcade-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by EvanZhouDev** [comment]
Will be implementing more games until release so that this is not a duplicate of @tonka3000's Snake extension.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I guess there is no way to make it a bit bigger? It's pretty hard to see the "lane"

raycast-arcade 2023-08-02 at 11 59 23

- In Snake, food can spawn inside the worm - did you consider levels and faster moving speed?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by EvanZhouDev** [comment]
Hello! Yeah, for Tetris, there's no way to make it larger while fitting it in the viewing window of Raycast. I have written a custom ASCII rendering engine that uses the Top and Bottom Half ASCII block characters to fit Tetris in a smaller space. Any form of scaling won't work, sadly.

Also, frankly, I couldn't figure out why the food can spawn inside the Snake. The code already prevents this in theory, but I'll take a look at this. And as for levels, sure, why not...

I will also be adding one more game, Chrome Dino, that will hopefully be the best one yet...

**Comment by tonka3000** [comment]
> Will be implementing more games until release so that this is not a duplicate of @tonka3000's Snake extension.

Snake will still be a duplicate 🤦‍♂️

**Comment by EvanZhouDev** [comment]
@tonka3000 Would you like me to remove it?

**Comment by EvanZhouDev** [comment]
@pernielsentikaer I think it's ready for another review...

**Comment by EvanZhouDev** [comment]
@pernielsentikaer What do you think? I still need to add the last game, Daily Wordle, and fix up the promo images, but other than that, I think its good for release. Probably will take a few more hours 😅

**Comment by pernielsentikaer** [comment]
You can maybe make games like `Dino` work better by using the [textSize from environment](https://developers.raycast.com/api-reference/environment#properties)

There is a a lot of unused space when using small text size 🙂

raycast-arcade 2023-08-08 at 11 16 08

Does it make sense to change this?

**Comment by EvanZhouDev** [comment]
This completely slipped my mind! I thought about doing something like this a while ago, but I forgot 😅...

It's all done now, and Tetris looks better than ever in this new sizing... Were you on the Medium text size for that first Tetris screenshot you sent me?

raycast-arcade-3

**Comment by pernielsentikaer** [comment]
Hi @EvanZhouDev 👋 

Here is Tetris compared to first small text size, and then big 🙂

### Small (Where there is a scrollbar)
image

### Big
image


Wordle nad Chrome Dino looks really good in both modes 🙂

**Comment by EvanZhouDev** [comment]
@pernielsentikaer There is literally no way to fit the larger board, even in the small text size… the scrollbar’s all that I can do (even though it has scroll, you can still see the whole thing without scroll)…

The only solution as far as I’m concerned is to have the consistently smaller board on both sizes. (Unless you have a different solution?)

**Comment by EvanZhouDev** [comment]
I’m not really getting what you would like me to change?

**Comment by pernielsentikaer** [comment]
No, I don't think it's necessary, just if it was an easy fix 🙂

**Comment by EvanZhouDev** [comment]
I can’t think of anything off the top of my head, but if you have any ideas, it will be great!

**Comment by pernielsentikaer** [comment]
I think we should aim to push for v1 today 🙂 I'm not sure standard Tetris shows the next block, does it? Some does 🙂

**Comment by EvanZhouDev** [comment]
Hmm.. I can't seem to upload my latest changes. Can you try pulling them from https://github.com/EvanZhouDev/raycast-arcade? Thanks!

**Comment by EvanZhouDev** [comment]
@pernielsentikaer Any updates?

**Comment by EvanZhouDev** [comment]
🥳 Just got it to work

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
