### PR TITLE
Add my-github extension

### PR DESCRIPTION
**Pull request by chikalaka-raycast**
## Description

Commands to list your GitHub pull requests and repositories.
1. My Pull Requests - List pull requests you created, participated in, or were mentioned in.
2. My Repositories - List your repositories.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by edan-kodem** [comment]
Hi @mil3na,
My extension is faster, has another command to see my repositories, and overall I think the list has a better UX, i.e. show all the info you need and open in browser on click. Another thing, the [GitHub Review Requests](https://www.raycast.com/resessh/github-review-requests) is not working as I would expect - when I open a PR, I don't see it on the list

**Comment by mil3na** [comment]
Hi @edan-kodem ! 
I believe that the justification you gave me are good reasons for expand the extension that already exists, rather than adding one more extension with the same goals. Please, consider contributing to the existing extension instead. Let me know if you need any help doing so.

**Comment by edan-kodem** [comment]
Hi,
The two extensions have very different code and methods, plus, the existing extension doesn't work as expected. Furthermore, my extension has more commands and I plan making it even faster and maybe add more commands. 
I think you should use both before you decide.
Anyway, me and 2 teams in my company currently prefer mine and we will keep using it locally.
Thank you,
Edan

**Comment by thomaslombart** [comment]
Hey @edan-kodem, have you looked at our [GitHub](https://www.raycast.com/raycast/github) extension? It seems it has everything you're looking for with your extension.

**Comment by edan-kodem** [comment]
Of course.
It is a great extension but it lacks the UX and performance our teams want.
For example: 
- It is very rare one would like to get additional details for a PR, so I've added the necessary details inside the list and open it directly in the browser.
- See only open branches
- See in the title and subtitle branch and repo names
- Loading is much much faster (you are retrieving a lot of data that we don't use)

And I have another command to fetch all my GitHub repos.

I suggest using my extension to see for yourself :)

**Comment by thomaslombart** [comment]
Thanks for the feedback! As @mil3na said, the way to go would be to contribute to the [GitHub extension](https://www.raycast.com/raycast/github) as we don't want the store to be bloated with many GitHub extensions making it difficult for someone to find the right one.

There are many ways to use GitHub as it's a product used by millions so it's quite tricky to implement an extension that fits most workflows. I'm happy to review your contributions on the existing one 🙌

**Pull request closed without merging**
