### PR TITLE
Add share-my-code extension

### PR DESCRIPTION
**Pull request by jairaume**
## Description
This is an extension to easily share **code snippets**, links, texts between people by sharing a simple slug. 

Taking advantage of the already existing service [**ShareMyCode**](https://sharemycode.fr), this extension simplifies the process by avoiding users to open their web browsers, fiddle with the url to get the correct content, etc...

It also **tracks** recently created  snippets and stores them. Any snippet can be also added to the _recents_ list to be kept.

> ⚠️ I am not the owner of [**ShareMyCode**](https://sharemycode.fr) and am simply porting this service as an extension to Raycast.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jairaume** [comment]
> Hi 👋
> 
> I just get this error when I test it, does it work for you?
> 
> share-my-code 2024-02-12 at 12 38 14

Hi 👋

Sorry for the inconvenience, there indeed seems to be an error when using random slug :(
I am working on it to try and figure it out asap! 
Should i convert this pr to draft for now while I investigate ? 😁

Thanks!

**Comment by pernielsentikaer** [comment]
Let's convert it, let me know if you need any help

**Comment by jairaume** [comment]
Hi again 👋

I finally found the cause of the bug !
It should work fine now with some small featured I added along the way :)

Let me know if I can/have to do anything 🙂

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for the corrections 🔥 

I would popToRoot() with a toast after submitting the form instead of the push, when you hit `escape` you end up in the previous view where you can submit data with the same slug again

What do you think?

**Comment by jairaume** [comment]
Thanks so much for the feedback ! 

Indeed hitting `escape` allows for modifications of the content which might be confusing and totally be an unexpected behavior 🥲

I think what lead me to this choice was that I thought it would be interesting to give the user a preview of what he just shared without him having to launch another command to check if everything went well!

I will implement your suggestions right-away but in the mean time I had a small concern about a choice I made and I would love to have your thoughts on it : 
Is it ok to copy some content (here the link of the *ShareMyCode* he just created) to the user's clipboard without a mindful action from him (here it's triggered on form submission)?

Thanks 🙂

**Comment by pernielsentikaer** [comment]
You could always make it a preference, this way the user can disable(or enable) if they want 🙂

**Comment by jairaume** [comment]
Didn't even consider that, thanks!
Changes have been made now 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
