### PR TITLE
[Simple Youdao Translation]: delete translate clipboard or selection content, support config max input length

### PR DESCRIPTION
**Pull request by mricefox**
## Description

- user experience enhancement
1. delete translate clipboard or selection content to improve fluency of input
2. support config max input length
3. use macOS 'say' cmd to pronounce firstly  to reduce latency

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mricefox** [comment]
@raycastbot This pull request alert report was aborted or timed out while running. You can try to re-run the report at any time. What can I do to process this PR？

**Comment by pernielsentikaer** [comment]
Hi @mricefox 👋

Thanks for your contribution 🔥 

@xeric do you mind checking this

**Comment by xeric** [comment]
Hi @mricefox 
Thanks for your suggestion.

**- delete translate clipboard or selection content to improve fluency of input**
A: go to extension configruation and uncheck the clipboard support feature.
Will not disable selection support since this is user's reaction.

**- support config max input length**
What is the purpose of configuring max input length? would you mind clarify what is the use case?

**- use macOS 'say' cmd to pronounce firstly to reduce latency**
This need more evaluation, say command by default only works for English, and need manual -v parameter to switch to pronounce with other language support, and I only see the mapping with voice locale-name.
In youdao's API, there's no locale information like fr_FR, so can't map to proper voice name.
I need to find a idea way to find out which voice name I should use for pronounce the content if we hope to use say command.

**Comment by mricefox** [comment]
> Hi @mricefox Thanks for your suggestion.
> 
> **- delete translate clipboard or selection content to improve fluency of input** A: go to extension configruation and uncheck the clipboard support feature. Will not disable selection support since this is user's reaction.
> 
> **- support config max input length** A: What is the purpose of configuring max input length? would you mind clarify what is the use case?
> 
> **- use macOS 'say' cmd to pronounce firstly to reduce latency** A: This needs more evaluation, say command by default only works for English, and need manual -v to switch to pronounce with other language support, and I only see the mapping with voice locale-name (see: say -v ?). In youdao's API, there's no locale information like fr_FR for French, so can't map to proper voice name. I need to find a idea way to find out which voice name I should use for pronounce the content if we hope to use say command.

1. It would be helpful to have an option to turn on or off auto translation of selected text, but I prefer to delete this feature that may confuse users.
2. The 50-character limit is too low to support translation of longer sentences.
3. Regular expressions can be used to check languages.

I appreciate you developing this plugin. Since my primary use case is Chinese-English translation, I tend to simplify the plugin's functions and improve its usability.

**Comment by xeric** [comment]
> > Hi @mricefox Thanks for your suggestion.
> > **- delete translate clipboard or selection content to improve fluency of input** A: go to extension configruation and uncheck the clipboard support feature. Will not disable selection support since this is user's reaction.
> > **- support config max input length** A: What is the purpose of configuring max input length? would you mind clarify what is the use case?
> > **- use macOS 'say' cmd to pronounce firstly to reduce latency** A: This needs more evaluation, say command by default only works for English, and need manual -v to switch to pronounce with other language support, and I only see the mapping with voice locale-name (see: say -v ?). In youdao's API, there's no locale information like fr_FR for French, so can't map to proper voice name. I need to find a idea way to find out which voice name I should use for pronounce the content if we hope to use say command.
> 
> 1. It would be helpful to have an option to turn on or off auto translation of selected text, but I prefer to delete this feature that may confuse users.
> 2. The 50-character limit is too low to support translation of longer sentences.
> 3. Regular expressions can be used to check languages.
> 
> I appreciate you developing this plugin. Since my primary use case is Chinese-English translation, I tend to simplify the plugin's functions and improve its usability.

Hi @mricefox

1. As I said, I considered "select text" as a user-controllable interaction, and my assumption is that the end user will not call out raycast for translating when he is selecting something on screen. Anyway, I will consider adding an additional option in the next version, especially if I get more feedback from others.
2. I feel you want to use this plugin to translate long text content, right? I should say this is a plugin for Youdao Dictionary, guess the name Youdao translator confuses everyone it is a tool like DeepL, but unfortunately, based on my testing, the behavior of translating long text is not so good. I will spend more time checking if any Youdao cloud service can do long text translation and plan to merge function into this extension.
3. regex can't do anything without source text. Our requirement is, first, after translation finished, I should get a language or locale information from the result; second, this language or locale information contains part of text from the voice name. Now, since there's no mapping relationship, regex can't help anything here. I will take your suggestion and try to see any possibility there.

Again, THANKS for all your advice and suggesrion for this extension, I will keep this ticket opened, and update when I find something.

**Comment by mricefox** [comment]
> > > Hi @mricefox Thanks for your suggestion.
> > > **- delete translate clipboard or selection content to improve fluency of input** A: go to extension configruation and uncheck the clipboard support feature. Will not disable selection support since this is user's reaction.
> > > **- support config max input length** A: What is the purpose of configuring max input length? would you mind clarify what is the use case?
> > > **- use macOS 'say' cmd to pronounce firstly to reduce latency** A: This needs more evaluation, say command by default only works for English, and need manual -v to switch to pronounce with other language support, and I only see the mapping with voice locale-name (see: say -v ?). In youdao's API, there's no locale information like fr_FR for French, so can't map to proper voice name. I need to find a idea way to find out which voice name I should use for pronounce the content if we hope to use say command.
> > 
> > 
> > 
> > 1. It would be helpful to have an option to turn on or off auto translation of selected text, but I prefer to delete this feature that may confuse users.
> > 2. The 50-character limit is too low to support translation of longer sentences.
> > 3. Regular expressions can be used to check languages.
> > 
> > I appreciate you developing this plugin. Since my primary use case is Chinese-English translation, I tend to simplify the plugin's functions and improve its usability.
> 
> Hi @mricefox
> 
> 1. As I said, I considered "select text" as a user-controllable interaction, and my assumption is that the end user will not call out raycast for translating when he is selecting something on screen. Anyway, I will consider adding an additional option in the next version, especially if I get more feedback from others.
> 2. I feel you want to use this plugin to translate long text content, right? I should say this is a plugin for Youdao Dictionary, guess the name Youdao translator confuses everyone it is a tool like DeepL, but unfortunately, based on my testing, the behavior of translating long text is not so good. I will spend more time checking if any Youdao cloud service can do long text translation and plan to merge function into this extension.
> 3. regex can't do anything without source text. Our requirement is, first, after translation finished, I should get a language or locale information from the result; second, this language or locale information contains part of text from the voice name. Now, since there's no mapping relationship, regex can't help anything here. I will take your suggestion and try to see any possibility there.
> 
> Again, THANKS for all your advice and suggesrion for this extension, I will keep this ticket opened, and update when I find something.

I agree that the current complexity and fluency of this plugin affect its adoption. Perhaps simplifying it to Chinese-English translation and optimizing fluency can increase its number of users. I am currently using my own branch locally, but I strongly suggest that you try my branch and compare the fluency. There may be some things worth referring to. Thank you for your reply.

**Comment by xeric** [comment]
@mricefox
I reviewed your PR, unfortunately, I can't merge it because it will break the original function which does not only serve for English-Chinese translation, that was not my intention.
I understand that for a lot of users in China, the major use case is Chinese->English or English->Chinese, but due to the capability of the Youdao API and original design of this extension, I can't make any incompatible changes in the new version by reducing the function scope of it.

**I plan to add an option that allows opting out of the selection translation based on your suggestion**, but not remove this feature.

For the other features, I will not plan them.

Max input size as I explained, the Youdao API does not work well for long content translation; it works like a dictionary.
But if one day the Youdao API can support long content translation well, I will enable configuring the size of input with another command in this extension, the current interaction design is not for long content input.

Say command I saw you hardcode it with the voice name "Samantha", it only works for English, and I saw you remove the "read translated" feature, that was a feature requested by other end users, so I can't remove it.

I appreciate your contribution and ideas, maybe keep maintaining a local version and publish in your own organization would be a good choice which perfectly matches your requirement, that's the beauty of open source:)

**Comment by pernielsentikaer** [comment]
Thanks for taking your time @xeric - so we close this and when you're ready you make an update for some of this?

**Comment by xeric** [comment]
@pernielsentikaer yes please close it, thank you.

@mricefox if any concern, please AT me anytime.

**Comment by mricefox** [comment]
I will publish a new plugin with my ideas when I have time, thank you everyone.

**Pull request closed without merging**
