### PR TITLE
[Authy] Prepare for store update

### PR DESCRIPTION
**Pull request by guga4ka**
## Description

- Migrate extension to Raycast api v1.30.0
- Update dependencies
- Pop to root after copy/paste action
- Update README.md, add metadata
- #1171  add preference to sort list by recent usage
 
## Screencast
none 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by guga4ka** [comment]
I have unchecked 5th task here is a [slack thread](https://raycastcommunity.slack.com/archives/C028DTXTW3Y/p1647851849037619) regarding it

**Comment by guga4ka** [comment]
@lukekarrys could you pls take a look at the latest commit, in case you have time? 
@pernielsentikaer i guess we good to merge

**Comment by pernielsentikaer** [comment]
I have noted that you're looking into the redraw of the list after selecting, is that correct @guga4ka

**Comment by lukekarrys** [comment]
Apologies for never taking a look at it. I just updated my extension so I'm using it now and it looks great. great work @guga4ka! 🎉

**Pull request merged**
