### PR TITLE
Update codesnipper extension

### PR DESCRIPTION
**Pull request by omit2c**
## Description

The Raycast extension for CodeSnipper is a small addition for the Mac exclusive app. You can create new snippets and search your database to paste snippets into your IDE with ease.

You can download the beta version here: [https://testflight.apple.com/join/rA4oGfml](https://testflight.apple.com/join/rA4oGfml)

## Screencast

Bildschirmfoto 2023-12-27 um 15 27 40
Bildschirmfoto 2023-12-27 um 15 27 28
Bildschirmfoto 2023-12-27 um 15 27 18

https://github.com/raycast/extensions/assets/67875249/d70a0e6e-8369-4651-b6c2-f8a7ea0e4639

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
I don't see any snippets when using the action `Copy Snippet` eventhough I added a few, is that a bug?

**Comment by omit2c** [comment]
Hi @pernielsentikaer,

this is not a bug, rather it is related to Apples background refreshing of the database. Changes, such a creating or deleting snippets may not directly appear in the database, only after a period of time. I don't know why Apple made this decision, but you only have to wait for some amount of time until the create snippets will also appear in the raycast extension. Unfortunately there is no way around it.

Thank you and kind regards,
Timo

**Comment by pernielsentikaer** [comment]
I still don't have anything in the view after more than 15 hours, I don't think that's expected?

Raycast09012024-OZ1hKmbx png@2x

**Comment by omit2c** [comment]
Thank you for the input. I will revise and open the pull request again, if I have fixed the issue.

**Pull request closed without merging**
