### PR TITLE
Update date-format-converter extension

### PR DESCRIPTION
**Pull request by yisshengyouni**
## Description

The input interface has been optimized to make it easier to operate.

before
image

after
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@yangxyo could you check this too

**Comment by pernielsentikaer** [comment]
I think it looks much better, let's see what @yangxyo thinks 🙂

**Comment by yisshengyouni** [comment]
Hi @pernielsentikaer , @yangxyo  He doesn't seem to be active, can you help merge this request?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
