### PR TITLE
Add Setapp extension

### PR DESCRIPTION
**Pull request by lardissone**
## Description

Allows to search apps in Setapp catalog and filter by installed or mobile apps.

## Screencast

https://github.com/raycast/extensions/assets/59826/8c0377f6-77bc-48e0-a013-5c322a87239d

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @lardissone 👋 

On the first load I just end up here, could you look into showing the data, right now I have to go re-enter the command to see some data 🙂

setapp 2023-06-29 at 08 33 47

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
> Question, is there a way to know Background Refresh status of another command?

You could set the current timestamp in the cache every time it runs and then way you'll know if it's enabled or not, if that's necessary I don't know 🔥

**Comment by lardissone** [comment]
@pernielsentikaer good suggestion. I just added a lastSync cache key to force sync if it's older than the background refresh interval.

**Comment by mil3na** [comment]
Hi @lardissone ! Thanks for the changes!
I'm wondering, why `Background Refresh Setapp Cache` needs to be a command. It seems necessary in order to show the installed/not installed apps, so why not just make it a default behavior?

This is my screen  the first time I search for Setapp apps
CleanShot 2023-07-04 at 11 33 31@2x

Even though I have quite a few of them installed.

**Comment by lardissone** [comment]
@mil3na thanks for your review. After reading your comment, I realized that you're right, I don't need a background refresh command. It's not a thing that is going to change that frequently.

Can you try again? I've removed all background refresh logic.

**Comment by mil3na** [comment]
Awesome! This is more an extra mile than an actual requirement, but have you tried using Setapp's deep link instead of opening it on the browser? Example here: https://setapp.com/apps/sip there's a `Launch App` button that opens that app on the Setapp window :)

**Comment by mil3na** [comment]
Great it works here, but a bug appeared: the first time I open the extension, they show nothing installed. Calling it again, everything works as expected. Do you think any kinda async issues are happening here?

**Comment by lardissone** [comment]
@mil3na how are you trying it? I can't replicate it by using dev: `npm run dev`.

**Review by mil3na — APPROVED** [review]
Nevermind, I cannot reproduce it again. Might have been a fluke. Thanks for your effort, you should see this extension soon on our Store :D

**Pull request merged**
