### PR TITLE
Update spotify-player extension

### PR DESCRIPTION
**Pull request by efmmoncada**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by peduarte** [comment]
Hi, we already have an Add to Queue Action, which is more contextual to the song/artist/playlist you want to listen to next

(ಠ ›ಠ) — @peduarte — MDp2jeeq002592@2x

I'm not sure this command offers a good UX, you'll be adding a potentially unexpected item to your queue, since there is no search.

**Comment by peduarte** [comment]
Also, just a heads up for the future, before creating a PR, it may be worth creating an issue so we can debate, or at least provide enough context in the description. It's hard to understand why we need this otherwise. Thanks!

**Comment by efmmoncada** [comment]
Thanks for the heads up! I'll note to raise an issue next time. I totally hear you on the issue where you potentially add something unexpected to the queue. I guess the functionality I had in mind was similar to the "Just Play" action, but instead of overriding what you have playing, just add it to the queue instead, keeping the behavior of selecting the first/most popular result matching the query, just like "Just Play" does

**Comment by peduarte** [comment]
I hear you, but I think adding something to a playlist is different than "just playing". When you play something that's not what you expect, you can easily skip, play something else, etc. When you add something to the playlist, its not as easy to remove it. It needs to be a fully conscious decision

**Pull request closed without merging**
