### PR TITLE
add llm toolkit

### PR DESCRIPTION
**Pull request by jul-sh**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Thanks for your contribution 🔥 

Could you look into the CI errors 🙂

**Comment by jul-sh** [comment]
Your changeling enforcer fails if the changelog file has the MD extension capitalized. It's a lil counterintuitive and hard to debug the failure, but got there eventually.

**Comment by jul-sh** [comment]
> I didn't see there was two extensions in the PR, could we split them into two?

done, removed one extension

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Could you add your own metadata images , seems like the one if from the original extension 🙂

**Comment by jul-sh** [comment]
done!

**Comment by pernielsentikaer** [comment]
Could you use the [screenshot tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) to make it 🙂

**Pull request closed without merging**
