### PR TITLE
Add rayvops extension

### PR DESCRIPTION
**Pull request by Clement-Beudot**
## Description

This Raycast extension is designed to boost productivity by providing quick and easy tools for common tasks. It includes features for modifying JSON data, handling strings, and opening multiple links at once.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Thanks for your contribution 🔥 

Sorry for the long response time. Due to the Easter vacation, we have a slightly increased response time, but it should soon return to normal.

Maybe it would be better to focus on the command opening multiple URLs at once and the other features could maybe fit into the [Toolbox extension](https://www.raycast.com/Kang/toolbox)

**Comment by Clement-Beudot** [comment]
> Hi 👋
> 
> Thanks for your contribution 🔥
> 
> Sorry for the long response time. Due to the Easter vacation, we have a slightly increased response time, but it should soon return to normal.
> 
> Maybe it would be better to focus on the command opening multiple URLs at once and the other features could maybe fit into the [Toolbox extension](https://www.raycast.com/Kang/toolbox)

Hello @pernielsentikaer , thank you for your comment. I check the Toolbox Extension, that is nice, but there is no way to configure shortcuts for commands :/ . This extension was built to chain action (ex : Extract value from a Json attribute, then concatenate those values, etc). 

What do you think ?

**Comment by pernielsentikaer** [comment]
I tried the `Extract Json Fields Valiues` by having `{"hello": "you"}` in the clipboard, but I just gets an error:

rayvops-1

Seems to be the same with other commands, can you look into that?

**Comment by Clement-Beudot** [comment]
> I tried the `Extract Json Fields Valiues` by having `{"hello": "you"}` in the clipboard, but I just gets an error:
> 
> rayvops-1
> 
> Seems to be the same with other commands, can you look into that?

Hello @pernielsentikaer . Thank you for testing. Commands to extract Json attribute values or modify them in batch are made to process many lines on data (like array of object). I add a fix to check if Json is an array. 
So 
 {
    "hello": "you"
 }
will be treated in the same way as : 
[
  {
    "hello": "you"
  },
  {
    "hello": "there"
  }
]

**Comment by pernielsentikaer** [comment]
That part works a lot better now, where does the name of the extension come from? 🙂

**Comment by Clement-Beudot** [comment]
> That part works a lot better now, where does the name of the extension come from? 🙂

Thx, the name comes from a play on words between Raycast and Revops (Revenue Operation Team).

**Review by pernielsentikaer — COMMENTED** [review]
It does feel like it's more an internal tool (Also by reading the description of the extension) rather than being something that would work for everyone, is that the case?

**Comment by Clement-Beudot** [comment]
> It does feel like it's more an internal tool (Also by reading the description of the extension) rather than being something that would work for everyone, is that the case?

Hello, 
For sure this extension will be used a lot internally, but not only. 
In my business, it's often useful to be able to extract data from a Json result (or a CSV, but that could be for a future update), concatenate strings to use them in SQL queries, and open urls easily from these results. 

I could publish the extension locally, but people outside my organization wouldn't be able to take advantage of it. 
Is it possible to publish an extension across several organizations?

**Comment by pernielsentikaer** [comment]
You can push it to all the organizations you want if you change the owner of them yes 🙂

I think it's the mix of json/string manipulation that feels a bit weird to me, also descriptions is not really saying anything besides showing love 🙂

We can do somepush to get it in the store but we might need some more polishing 🙂

**Pull request closed without merging**
