### PR TITLE
Add duck-duck-go-search extension

### PR DESCRIPTION
**Pull request by justspacedog**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tegola** [comment]
Hey! Sorry for being late. Seems like you replaced the whole package, which is causing conflicts. You might want to contribute by checking out the existing code and pushing only changes?

**Comment by pernielsentikaer** [comment]
Hi 👋 

I'm not sure if this is the case, but there was a bug in `Fork` and `publish`, see below

> We have just fixed a bug that caused the `puslish` command to publish all files as new in some edge cases, the fix should be included in the next release which is `1.50.0`.

> Until the fix is out, do you have the possibility to only add the changed files (checkout from main) manually and update this PR or close this PR and only add the changed files manually

**Comment by tegola** [comment]
> So I just run `publish` again when 1.5 is out?

I guess?

**Comment by pernielsentikaer** [comment]
That should fix it, or manually rebase only the changes into this PR - if it's only a few files you can also do it manually instead 😊

**Pull request closed without merging**
