### PR TITLE
Update work-time-countdown extension

### PR DESCRIPTION
**Pull request by krsntn**
## Description
- Added a new command to display the remaining percentage until the end of the workday.
- Fixed a minor issue where setting the start time as 8:30, 9:30, 10:30, etc., would cause the menu bar to appear at the beginning of the work day.

## Screencast
screenshot

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for taking your time to contribute 🔥

Instead of adding another command, why not add the subtitle to the current command instead?

Raycast24042024-jmBSSgGD png@2x

**Comment by krsntn** [comment]
Oh, I hadn't thought of that! Yeah, just adding the subtitle to the current command would be a lot simpler. 😅

**Comment by pernielsentikaer** [comment]
It would yes, then we also need to move preferences (which would be reset)

**Comment by krsntn** [comment]
Understood. I've made the changes. The progress command is removed, and I've integrated its features into the existing menu bar command. I've also reverted the preferences placement. Could you please check if everything looks okay now?

**Review by pernielsentikaer — APPROVED** [review]
Approved 🙂

**Pull request merged**
