### PR TITLE
[Bugfix] [Network Speed] Fix no loading animation

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

- Add information display during speed measurement

## Screencast

https://github.com/raycast/extensions/assets/36128970/ed8d4069-8e39-4d09-aa37-ae0c64c29fc0

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I don't see anything else than this when running it 🫠

Raycast-wbBrwc0i

**Comment by koinzhang** [comment]
Hi @pernielsentikaer, must be upgraded to the latest sonoma to display the data during the measurement. Which Mac system version do you have?
I just submitted a commit to add placeholder characters for a lower version of the system.

**Comment by pernielsentikaer** [comment]
> Which Mac system version do you have?

I'm on Sonoma 14.1 Beta (23B5056e)

**Comment by koinzhang** [comment]
Sonoma is enough.
Could you please try using the `networkQuality` command in the terminal to see if the test process is displayed in real time

https://github.com/raycast/extensions/assets/36128970/435bf7d6-0392-46c1-9108-971dff58bf18

**Comment by koinzhang** [comment]
Also, what does the page performance look like now during your speed tests with this extension? Can you take a screenshot if you can?

**Comment by pernielsentikaer** [comment]
Sure @koinzhang 

Raycast-sLPgt2ax

**Comment by koinzhang** [comment]
Hi @pernielsentikaer. It looks like different versions of sonoma (I'm using 14.0 on my device), networkQuality returns different strings, I've submitted a commit to fix this, please retest!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
