### PR TITLE
Add iTerm capability to ssh-manager

### LINKED ISSUE #2005: [SSH Connection Manager] Add iTerms Supports
# Extension – [SSH Connection Manager](https://github.com/raycast/extensions/tree/754283da0ce398f1bb3db2e72ad966058e69b8a0/extensions/ssh-manager/)
Author:

pls support open with iTerms2

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
## Description

This PR aims to bring iTerm to the ssh-manager extension.

Applescript bases on this one:
https://github.com/raycast/script-commands/blob/master/commands/apps/iterm/iterm-run-shell-command.applescript

Closes #2005 

## Screencast

Screen Shot 2022-06-25 at 10 06 29

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
I am going to fix the linter issue later today

**Comment by AaronDavidSchneider** [comment]
Could you test @wglassly?

**Comment by pernielsentikaer** [comment]
Hi @scopsy 👋 

Can you give it a spin and approve? 🙂

**Review by pernielsentikaer — APPROVED** [review]
Works as expected 🔥 Thanks for your contribution 💪

**Comment by wglassly** [comment]
> Could you test @wglassly?

Good Job!  It works well while the iTerm2  front tab is the local one.  When the remote tab is fronted, an error occurs.
image

**Comment by AaronDavidSchneider** [comment]
> > Could you test @wglassly?
> 
> Good Job! It works well while the iTerm2 front tab is the local one. When the remote tab is fronted, an error occurs. image

The issue you are facing is that you are then trying to ssh to some destination from a remote computer.
It just uses your local session.

**Pull request merged**
