### PR TITLE
Update connect-to-vpn extension

### PR DESCRIPTION
**Pull request by stonerl**
## Description
Add a background refresh to the menu bar item, to update the status, when a connection has been changed outside of the menu bar item.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by stonerl** [comment]
I encountered some issues with the initial PR. After some time the menu bar item would use up all available file descriptors, this is fixed now.

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @stonerl 

@rasmusbe, do you want to check this?

**Comment by pernielsentikaer** [comment]
Congratulations @rasmusbe 🔥 No worries, I'll check it. Go have a wonderful time 😊

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
