### PR TITLE
Update folder search extension

### PR DESCRIPTION
**Pull request by ridemountainpig**
## Description

The pins can now be ordered by the user using the "Move Pin Up" and "Move Pin Down" actions, addressing issue #14057.

## Screencast

https://github.com/user-attachments/assets/b583d051-72ce-43e2-bb93-61d029285836

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @ridemountainpig 

Thanks for an awesome update 🔥 

It seems to crash if you try to move it before it's actually pinned. We should only show the move actions when it's pinned 🙂

**Comment by ridemountainpig** [comment]
> Hi @ridemountainpig
> 
> Thanks for an awesome update 🔥
> 
> It seems to crash if you try to move it before it's actually pinned. We should only show the move actions when it's pinned 🙂

@pernielsentikaer Thank you for your review. I have fixed the problem. Please check.

**Comment by pernielsentikaer** [comment]
Can you run `npx @raycast/migration@latest .` too, you might need to do this manually first: https://developers.raycast.com/misc/migration/v1.48.8

Then you can also use `Keyboard.Shortcut.Common.MoveUp`

**Comment by ridemountainpig** [comment]
> Can you run `npx @raycast/migration@latest .` too, you might need to do this manually first: https://developers.raycast.com/misc/migration/v1.48.8
> 
> Then you can also use `Keyboard.Shortcut.Common.MoveUp`

@pernielsentikaer, I have migrated the code and changed the shortcut to use `Keyboard.Shortcut.Common.MoveUp` and `Keyboard.Shortcut.Common.MoveDown`. Please check. Thank you.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
