### PR TITLE
Add prism-launcher extension

### PR DESCRIPTION
**Pull request by lockieluke**
## Description

New extension for launching [Prism Launcher](https://prismlauncher.org/) Minecraft instances

## Screencast

https://github.com/raycast/extensions/assets/25424409/15b7f686-7ee5-4aa6-addc-d3d5313e8a40

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- If a user doesn't have Prism, could you then handle it gracefully?

prism-launcher 2024-01-09 at 13 51 45

- Could you add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) to the extension 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by lockieluke** [comment]
image

The extension now shows an error message when Prism Launcher is not detected, the [username] in the screenshot is not hardcoded

**Comment by pernielsentikaer** [comment]
It really looks awesome, I think you'll need to try-catch it since it still crashes here 🙂

prism-launcher 2024-01-10 at 08 49 27

**Comment by lockieluke** [comment]
image

Added an early return when PrismLauncher is not installed or the `instances` folder is not found

**Comment by pernielsentikaer** [comment]
Then we're ending up with a never ending loading indicator 🙂

Raycast10012024-t8u32oIC png@2x

**Comment by lockieluke** [comment]
I apologise for the bad code, I’ll spend more time fixing it when I get home 🙏

**Comment by lockieluke** [comment]
Silly me, I accidentally flipped a tertiary operator statement, I also added to code to prevent the Not Installed screen from showing before instances are fully crawled

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by lockieluke** [comment]
Linked my account

**Pull request merged**
