### PR TITLE
Add plain-text-to-bold-italic-unicode-converter extension

### PR DESCRIPTION
**Pull request by ubergraham**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Hi @ubergraham. Have you tried the [Text Decorator](https://www.raycast.com/koinzhang/text-decorator) extension? The extension you submitted seems to do the same thing as Text Decorator.

**Comment by ubergraham** [comment]
LOL nope, didn’t come across it when I searched! Oh well, was a good experience to learn how to build an extension!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for your contribution 🔥 

Did you see [this extension](https://www.raycast.com/koinzhang/text-decorator) before opening the PR, they looks kinda similar 🙂

**Comment by pernielsentikaer** [comment]
Closing as duplicate

**Pull request closed without merging**
