### PR TITLE
[BItwarden] Download own CLI binary and improve troubleshooting and bug reporting

### PR DESCRIPTION
**Pull request by jomifepe**
## Description

Second try of attempting to transition into downloading the CLI binary instead of requiring a local installation.

Pull request of the first attempt: https://github.com/raycast/extensions/pull/8315

What has changed since the first attempt?
- Now, if the download fails, the user will see a crash screen, but the next launch will revert to the locally installed CLI so that the user can continue to use the extension. This way the crash is going to be reported in the issues dashboard.

Other changes:
- The troubleshooting screen now is more descriptive
- New bug report data collection action, which outputs the following info:
```json
{
  "raycast": {
    "version": "1.67.1"
  },
  "system": {
    "arch": "arm64",
    "version": "14.0",
    "buildVersion": "23A344"
  },
  "homebrew": {
    "arch": "arm64",
    "version": "4.1.11"
  },
  "node": {
    "arch": "arm64",
    "version": "v20.9.0"
  },
  "cli": {
    "type": "installed",
    "version": "2023.8.2"
  },
  "preferences": {
    "has_clientId": true,
    "has_clientSecret": true,
    "fetchFavicons": true,
    "repromptIgnoreDuration": "-1",
    "has_serverCertsPath": false,
    "has_serverUrl": false,
    "shouldCacheVaultItems": true,
    "transientCopySearch": "passwords",
    "windowActionOnCopy": "close"
  }
}
```
  

### Download demonstration
https://github.com/raycast/extensions/assets/7235666/d26a357c-7bf8-4940-9e26-a068a4f776e7

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by szarbartosz** [comment]
Excited for this update - I downloaded bitwarden extension recently (`arm`) - had problems with `bitwarden-cli` installed via `brew` - ended up installing it via `npm` and creating symlink in `/opt/homebrew/bin/bw` where bitwarden extension expects it to be - seems that it will no longer be an issue :rocket:

**Comment by jomifepe** [comment]
> Excited for this update - I downloaded bitwarden extension recently (`arm`) - had problems with `bitwarden-cli` installed via `brew` - ended up installing it via `npm` and creating symlink in `/opt/homebrew/bin/bw` where bitwarden extension expects it to be - seems that it will no longer be an issue 🚀

Thanks for the support! Feel free to test it before release 🙏 
FYI: You can specify the path of your installation in the extension settings.

**Review by jomifepe — COMMENTED** [review]
Might be better to merge after: https://github.com/raycast/extensions/pull/10926 and https://github.com/raycast/extensions/pull/10939

**Comment by pernielsentikaer** [comment]
Is this ready to be merged now @jomifepe 🙂

**Comment by jomifepe** [comment]
> Is this ready to be merged now @jomifepe 🙂

Let's do it 💥

**Pull request merged**
