### PR TITLE
Add search-pypi extension

### PR DESCRIPTION
**Pull request by patrick91**
## Description

This PR adds a new extension for search PyPI packages, I plan to add new features in future, for now it implements a basic search and favourite system

## Screencast

https://github.com/raycast/extensions/assets/667029/0bdd6926-5bbf-4900-b984-2636ffc79a4b

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
The [Python](https://www.raycast.com/ahmedivy/python) extension seems to include a search pypi function

**Comment by pernielsentikaer** [comment]
That's correct, it was added yesterday 🙂

**Comment by pernielsentikaer** [comment]
Closing as duplicate, let's discuss further if needed

**Comment by patrick91** [comment]
I totally missed it! thanks 😊

**Pull request closed without merging**
