### PR TITLE
new extension: add stopwatch extension

### PR DESCRIPTION
**Pull request by ungario**
## Description

I added a stopwatch extension

## Screencast
Screenshot 2022-08-25 at 13 24 59

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Just a quick question before reviewing it @ungarmichael, it looks like it should work for only one timer, but the code actually adds multiple files every time you start a new timer. What about storing it in localStorage instead and then allowing multiple timers (with a list view)

I'd like to help with the rewrite of the extension if needed 🙂

**Comment by ThatNerdSquared** [comment]
Hey there :wave:

My new update to the Timers extension (#2858) adds some similar stopwatch functionality, which also includes the ability to have multiple concurrent stopwatches and a view to check up on all of them:
image

What do you think about merging the functionality of this extension into Timers? Maybe @pernielsentikaer can give his thoughts on this as well.

**Comment by pernielsentikaer** [comment]
I think that could make sense if @ungarmichael also thinks it could be a good idea, then he would be contributor to the `timers` extension, what do you think @ungarmichael

**Comment by ungarmichael** [comment]
> I think that could make sense if @ungarmichael also thinks it could be a good idea, then he would be contributor to the `timers` extension, what do you think @ungarmichael

What do you mean with being contributor to the `timers` extension? The implementation for a stopwatch in `timers` already exists, doesnt it?

**Comment by ThatNerdSquared** [comment]
Yes, I have already added a stopwatch implementation to `timers`. If you would like, you can contribute any functionality you consider missing from `timers`, and I could add you to the contributors list in the extension. You can also choose not to, and we could just merge my extension as-is - no pressure.

**Pull request closed without merging**
