### PR TITLE
Slack status deeplinks

### PR DESCRIPTION
**Pull request by thomaspaulmann**
## Description

@sxn as discussed, this adds an option to show the form to create a status from a deeplink. Ideally, I could also just set the status via a deeplink without opening the form first. This could be super helpful for some automations.

I also migrated the API to the latest version.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by sxn** [comment]
thanks @thomaspaulmann!
I've pushed a bunch of changes as well:
- added a `Copy Deeplink` action
- when the command starts, checks if the command passed via context (if any) can be exactly mapped to a preset. If it can, the status is directly set

This allows directly setting a status via deeplink/command launching. It's not perfect though, as it introduces flickering:

https://user-images.githubusercontent.com/1155589/230378781-4025e3da-dddd-41f3-b1b7-d05c6594eb15.mov

**Review by PitNikola — APPROVED** [review]
LGTM

**Comment by thomaspaulmann** [comment]
@sxn shall we merge it or hold off until we find a way to avoid the flickering?

**Comment by sxn** [comment]
@thomaspaulmann I'd hold off until we either find how to avoid the flickering or come up with a better way of doing this.

**Pull request closed without merging**
