### PR TITLE
Bitwarden: Add password generation

### PR DESCRIPTION
**Pull request by jomifepe**
## Description

This Pull Request adds a command to generate passwords using the Bitwarden CLI, similarly to the browser extension.

**Main features**:
- Copy password to clipboard
- Regenerate password
- Tweak generator options (characters, length, passphrase, ...)
  - Persistent options

Screenshot 2022-02-23 at 00 04 04

### Demonstration

<details>
<summary>More screenshots</summary>
<br />

Screenshot 2022-02-23 at 00 03 16
 <br />
Screenshot 2022-02-23 at 00 04 04
<br />
Screenshot 2022-02-23 at 00 07 12
<br />
Screenshot 2022-02-23 at 00 07 14

</details>

<details>
  <summary>Videos</summary>
  <br />

https://user-images.githubusercontent.com/7235666/155241484-3e6a3e8a-c6b5-41ea-b5a6-6bff63dfbb0a.mov
</details>

### Limitations/Issues
<details>
  <summary>Navigation issue</summary>
  <br />
When navigating between the generator and the options screen, the password "added" to the navigation history, and when you start going back, old passwords are restored. See video below.

https://user-images.githubusercontent.com/7235666/155241484-3e6a3e8a-c6b5-41ea-b5a6-6bff63dfbb0a.mov
</details>

### Future improvements
<details>
<summary>Password history</summary>
<br />

As of today, the Bitwarden CLI doesn't have a password history. This could be added in the future using LocalStorage or Node.js APIs, with probably some kind of encryption. Ideally, this feature would use the Bitwarden CLI (when it gets that feature implemented), as a custom solution would probably raise some security concerns. That said, I decided not to develop it for now, but warn the user with an alert when entering the command for the first time.

Screenshot 2022-02-23 at 00 03 47

</details>

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by pomdtr** [comment]
Looks good! However I am not conviced by the current UI.
What do you think of using a single screen instead ? Ex:

image

**Comment by jomifepe** [comment]
Yeah, that would also look good. I thought about changing it, as this List layout posed some issues, but I thought it would be better because it has better navigation. I'm gonna experiment with that single-page UI and I'll post it here.

Thank you for the feedback!

> Looks good! However I am not conviced by the current UI. What do you think of using a single screen instead ? Ex:
> 
> image

**Comment by pomdtr** [comment]
Raycast forms also support keyboard navigation (you can use `tab` to switch between fields) :)

**Comment by jomifepe** [comment]
> Raycast forms also support keyboard navigation 😉 (you can use `tab` to switch between fields)

After some testing, I'm having issues implementing the form, as the only component available to display the password is the `Description`, but turns out that it's not made for dynamic content. On the docs they have a warning saying `Do not use this component to show validation messages for other form fields`, which explains the misbehavior. 

<details>
<summary>Here's a video to demonstrate, you can see that the password doesn't update when the component re-renders</summary>

https://user-images.githubusercontent.com/7235666/155422881-e1aec0e6-7ee1-422c-ab16-09f783bef894.mov
</details>

### Alternatives:

<details>
<summary>Displaying the password on an animated toast</summary>
<br/>

Downsides:

- Cannot display any other toasts, because they replace the animated one. Currently, I'm displaying the text fields validation messages using Toast, so I would have to rethink that.
- Not that much space to display long passwords

https://user-images.githubusercontent.com/7235666/155424293-7a52e756-71df-4992-82ad-3effb58b3d6c.mov
</details>

<details>
<summary>Displaying the password on the navigation title</summary>
<br/>

Downsides:

- Not very visible
- Not that much space to display long passwords

https://user-images.githubusercontent.com/7235666/155424877-3506d2c8-4c4a-4152-a09a-9173199de44f.mov
</details>

<details>
<summary>Displaying the password on an action label</summary>
<br/>

Downsides:

- Not very visible
- Not that much space to display long passwords

https://user-images.githubusercontent.com/7235666/155425145-0a94e44b-7149-491a-b367-6c3ee7631821.mov
</details>

<details>
<summary>Displaying the password on an alert</summary>
<br/>

Downsides:

- Obstructive, blocks the rest of the UI

https://user-images.githubusercontent.com/7235666/155425833-6f33901b-80a2-4ea9-8868-765381eef286.mov
</details>

---

What do you think? Personally I find the **original implementation (using a list)** and the **animated toast** to be the best approaches, despite the downsides.

**Comment by mathieudutour** [comment]
> turns out that it's not made for dynamic content. On the docs they have a warning saying Do not use this component to show validation messages for other form fields, which explains the misbehavior.

No I'm pretty sure it's a bug. I'll look at it

**Comment by pomdtr** [comment]
> No I'm pretty sure it's a bug in the API. I'll look at it

Thanks! @jomifepe are you willing to wait for the issue to be corrected by the excalidraw team ?

**Comment by mathieudutour** [comment]
FYI, I found the bug, it'll be fixed in the next release

**Comment by jomifepe** [comment]
> FYI, I found the bug, it'll be fixed in the next release

That's great, thank you for looking into it!

> Thanks! @jomifepe are you willing to wait for the issue to be corrected by the raycast team ?

Yeah sure, no rush 🙂

**Comment by jomifepe** [comment]
> FYI, I found the bug, it'll be fixed in the next release

Hello, is there any update on this? I just updated the `@raycast/api` to version `1.29.1` and the bug is still there. 
I'm still not able to use the `Form.Description` to display dynamic data.

I'm asking this because this PR was labeled as `status: awaiting response from dev`.

**Comment by mathieudutour** [comment]
It'll be fixed in 1.30.0 which should be released on Wednesday

**Comment by jomifepe** [comment]
@pomdtr I just finished changing to a Form with the 1.30.0 fix, please take another look 🙂

<details>
  <summary>Here's a demonstration</summary>

https://user-images.githubusercontent.com/7235666/158039215-7e5ed79e-9fd0-445d-b265-1ccda974ea22.mp4
</details>

@mathieudutour My username is not being accepted on the `contributors`, what am I missing? 😕

**Comment by pomdtr** [comment]
Some small nitpicks on the UI side:
- I'm not a fan of the toast `field must be a number between 5 and 128`. If I change the number of char from the default `14` to `20`, I encouter it. Could there be an higher cooldown to avoid it ?
- I think a `Paste Password` secondary action would be welcome :)

Awesome work !

**Comment by jomifepe** [comment]
> Some small nitpicks on the UI side:
> 
> * I'm not a fan of the toast `field must be a number between 5 and 128`. If I change the number of char from the default `14` to `20`, I encouter it. Could there be an higher cooldown to avoid it ?
> * I think a `Paste Password` secondary action would be welcome :)
> * I don't think it should be mandatory to enter my vault password to generate a new password. The `bw` cli does not require it
> 
> Awesome work !

Great suggestions! All done! 

I increased the delay to 1 second. I hope it's enough, as displaying validations is not that easy with a limited API, I tried to use the `Form.Description` component, but the experience is worse, as there's no `onBlur` event on the `TextField`.

**Review by mathieudutour — APPROVED** [review]
Looking good :+1:

**Comment by jomifepe** [comment]
Thanks everyone 🙂

**Pull request merged**
