### PR TITLE
Add Chinese Support

### PR DESCRIPTION
**Pull request by zkytech**
## Description

Add Chinese support for search-notion

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @reckoning-dev

## ScreenShot
CleanShot 2022-02-03 at 00 57 17@2x
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @zkytech 👋 

I'm not a power user of Notion myself, I will ask @reckoning-dev and maybe @HenriChabrand to help test if there are any side effects with this 🔥

**Comment by mattisssa** [comment]
Hey @sadanand-singh or @HenriChabrand 
Could you please take a look at the PR and say if it's alright to do the change?

**Comment by sadanand-singh** [comment]
I can confirm that this is good to be merged. Thanks @zkytech for this quick fix.

**Review by pernielsentikaer — APPROVED** [review]
Thanks @sadanand-singh 💯 

I'm going to approve this, lets get it merged 🚀

**Review by pernielsentikaer — APPROVED** [review]
Thanks @sadanand-singh 💯 

I'm going to approve this, let's get it merged 🚀

**Pull request merged**
