### PR TITLE
Update openweathermap extension

### PR DESCRIPTION
**Pull request by larkov**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by tonka3000 — COMMENTED** [review]
Code looks good to me. The switch to V3 is required because v2.5 get closed.

I can not test the runtime behavior, maybe @pernielsentikaer or @mil3na can check it.

**Comment by larkov** [comment]
I couldn't get it to work with my api keys without signing up for a subscription. The first 1000 requests per day are free and i set a limit on 1000 requests. So technically i won't be needing to pay for anything.

**Comment by pernielsentikaer** [comment]
This is what I get with the current store version, I also though that it would work with the default free API key

openweathermap 2024-05-15 at 10 25 57

**Comment by tonka3000** [comment]
@larkov I need to add a payment to be able to subscribe, right?

**Comment by tonka3000** [comment]
@pernielsentikaer FYI https://openweathermap.org/api/one-call-3

**Comment by pernielsentikaer** [comment]
What's the current status of this on, should we just merge it @tonka3000

**Comment by tonka3000** [comment]
@pernielsentikaer I think it can be merged . I did not check the readme (sub required).

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
