### PR TITLE
Filamentphp doc search

### PR DESCRIPTION
**Pull request by aurawindsurfing**
## Description

Upgrade to version 3.x of filament docs

## Screencast

n/a

## Checklist

- [ x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ x] I checked that files in the `assets` folder are used by the extension itself
- [ x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Can we move the GIF outside the repository so we don't add 24mb extra? 🙂

- Could you update the [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) - are you using a very old version of Raucast?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Also, there is a conflict you should solve 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by aurawindsurfing** [comment]
Thank you!

🎉🎉🎉

**Pull request merged**
