### PR TITLE
Update keyboard-shortcut-sequences extension

### PR DESCRIPTION
**Pull request by devloos**
## Description

- Added ability to create applications
- Store sequences in applications

## Screencast

keyboard-shortcut-sequences-1
keyboard-shortcut-sequences-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by devloos** [comment]
Im not sure why its flagging everything as new.

I might just resolve conflicts this happened twice already.

**Comment by pernielsentikaer** [comment]
Hi 👋 

We have just fixed a bug that caused the `puslish` command to publish all files as new in some edge cases, the fix should be included in the next release which is `1.50.0`.

Until the fix is out, do you have the possibility to only add the changed files (checkout from main) manually and update this PR or close this PR and only add the changed files manually

**Comment by devloos** [comment]
Hey @pernielsentikaer 🙌

Yea I can definitely do that, but I am wondering how something like that would get done with `npm run publish`

**Comment by pernielsentikaer** [comment]
There were some errors in the script that check if it's a new or an update, 1.50.0 should be on it's way 😊

**Pull request closed without merging**
