### PR TITLE
Add UniFi Extension

### PR DESCRIPTION
**Pull request by tonka3000**
## Description

Manage Unifi Controller

- Search Devices

  CleanShot 2023-08-12 at 22 14 01@2x

- Search Clients

  CleanShot 2023-08-12 at 22 15 02@2x

- Open in Browser

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tonka3000** [comment]
Unstale 😁

**Comment by tonka3000** [comment]
???

**Comment by tonka3000** [comment]
@pernielsentikaer @mil3na

**Comment by pernielsentikaer** [comment]
Checking this @tonka3000

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Could you add some [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

**Comment by tonka3000** [comment]
I will add some

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
