### PR TITLE
Add simpletexocr extension

### PR DESCRIPTION
**Pull request by zhuozhiyongde**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

**Comment by zhuozhiyongde** [comment]
@pernielsentikaer I want to know if there is a reexamination?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
`LaTeX OCR Config` should be handled by [preferences](https://developers.raycast.com/api-reference/preferences) instead 🙂

**Comment by pernielsentikaer** [comment]
Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by zhuozhiyongde** [comment]
I think that localStorage is a better way to configure my extension than preference, cuz I think the user may often switch the format. It's very inconvenient to repeatedly open the extension panel instead of switching directly.

So I'd like to ask if it's possible to merge this PR without modifying the configuration method to preference (and I couldn't find an api to quickly set the preference without open extension panel in the relevant documentation), thx.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
