### PR TITLE
[Todo List] implement editing and opening urls

### PR DESCRIPTION
**Pull request by maggie-j-liu**
## Description

Implements changes requested in #460 (editing items and opening URLs), as well as fixes the extension to work with the new 1.30.0 update.

## Screencast

https://user-images.githubusercontent.com/63619830/157789803-f7b0b766-36a1-4197-821e-a7d3ce4d72ce.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @maggie-j-liu 👋 

Thanks for your update, however, I can't get it to work 😢 

When I try to add an item, it just does nothing at all, am I doing something wrong here?

https://user-images.githubusercontent.com/38033107/157975240-51509290-2d3f-47ea-8e37-75cbd9fe2bf5.mp4

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by maggie-j-liu** [comment]
Not sure what's happening; it works for me? DMed you on Slack to try to debug the problem.

**Comment by pernielsentikaer** [comment]
As we spoke about @maggie-j-liu, you did everything right – we're looking into this, and it should be resolved later today 😄 

I'll let you know when I have some new information in this case 😄

**Review by pernielsentikaer — APPROVED** [review]
Hi @maggie-j-liu 👋 

Thanks for the update, everything works as expected, awesome 🔥 

Once again, sorry for the inconvenience, glad we were able to sort it out 😄

**Pull request merged**
