### PR TITLE
Add fvm extension

### PR DESCRIPTION
**Pull request by leoafarias**
## Description

Extension allows to manage Flutter SDK versions by using FVM. You can view more [here](https://github.com/leoafarias/fvm)

## Screencast

https://github.com/raycast/extensions/assets/435833/a50797f5-71f8-48f4-9551-cb8f9075d5a9

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

I started testing your extension without having fvm installed. Maybe the first thing a user should see if fvm is not installed, is a screen asking for installing it, right? It would avoid screens like this:
CleanShot 2024-03-26 at 14 34 09

Now, I just installed fvm and I get this error in every command:

```
Error: Command failed with exit code 69: /Users/milena/Library/Application Support/com.raycast.macos/extensions/fvm/cli/fvm/fvm api context
MapperException: Failed to encode (GetContextResponse).context(FVMContext).generators(_Map<Type, (FVMContext) => ContextService>).key[LoggerService]: Unknown type Type. Did you forgot to annotate the class or register a custom mapper?


Please run command with  --verbose if you want more information

    at /Users/milena/.config/raycast/extensions/fvm/list-command.js:23561:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Do you mind taking a look at these issues?

**Comment by leoafarias** [comment]
Hi @mil3na sorry about that the issue was with the CLI install within the raycast extension. If you clear the open support directory and clear the `cli` folder it will download the latest version, which should fix the issue.

**Comment by mil3na** [comment]
Where would these folders be? Also, this would not fix the problem when the user doesn't have fvm installed. I just re-installed your extension and I'm getting the same error.

**Comment by leoafarias** [comment]
The extension installs the binary of the CLI, so you don't need fvm installed separately. The CLI is downloaded into the Raycast extension "Support Directory."

I'm not sure if uninstalling the extension clears that directory or not or if it needs to be done separately.

**Comment by mil3na** [comment]
By reinstall, I mean removing the entire extension folder and adding it again. 
I don't like the idea that the CLI is installed without user knowledge. It is nowhere on the README. Shouldn't the user already have FVM installed by themselves to use the extension?

**Comment by leoafarias** [comment]
I have added a note to the README.

I am following the same flow as the `xcodes` extension: https://github.com/raycast/extensions/blob/91167157c2cbffcc085605d7361d256a201a316a/extensions/xcodes/src/lib/cli.ts

There are many different ways the user can install the FVM CLI, with some compatibility with the versions, similar to the workflow of the `xcodes` extension.

I also updated with a lower update check time to ensure it downloads the latest version of the CLI for you. Hopefully, this works!

**Comment by leoafarias** [comment]
Hi! Please let me know if there js anything pending on my end.

**Comment by mil3na** [comment]
Hi @leoafarias, sorry for the delay, I was sick last week. Me or Per will take a look at this this week.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
