### PR TITLE
Add nippon colors extension

### PR DESCRIPTION
**Pull request by nagauta**
## Description

This extension enbale to explore nippon(japanese) colors! which are collected at the site below!

NIPPON COLORS is made by [Takehiko Ono](https://onopko.read.cv/), who is a web designer and developer in Japan!
https://nipponcolors.com/

## Screencast
nippon-colors-1
nippon-colors-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by nagauta** [comment]
@sxn thanks! oh my goodness, I'm ashamed of myself.
 it's totally alright with me. I appriciate you!!!

**Comment by sxn** [comment]
Overall, the extension looks pretty good! One thing that I noticed is that it is _pretty_ slow, and it is hitting the website pretty hard every time the command gets loaded.

As it's the first time I've heard of nipponcolors, I'm not aware e.g. how exactly it's used. Do the colors change often? Do they ever change? if they don't change, I'd suggest to move the fetching to a separate script, that can be run manually by you, or maybe automatically on install / build / etc. That way the extension will be fast, and we're not constantly making requests to the website.

If the colors do change, we should then figure out how often, and only fetch new data if the cache is absent or outdated.

Does that make sense? 😸

**Comment by sxn** [comment]
of course! there are a couple other extensions that work kind of the same way. For example [dot-new](https://github.com/raycast/extensions/blob/main/extensions/dot-new/package.json#L45), [Bible](https://github.com/raycast/extensions/blob/main/extensions/bible/package.json#L70), [Lucide Icons](https://github.com/raycast/extensions/blob/main/extensions/lucide-icons/package.json#L39) etc, so hopefully you can find some inspiration.

If you get stuck, just ping me here or on Slack and we can figure out whatever we need. 😸

**Comment by nagauta** [comment]
Thanks!, I'm gonna study them. I will work on it soon🔥!!!

**Comment by sxn** [comment]
oh, that's much better! 👏 let's get this merged! :shipit:

**Comment by nagauta** [comment]
Thanks you for reviewing lol

**Pull request merged**
