### PR TITLE
Add new extension: Craftdocs

### PR DESCRIPTION
**Pull request by kudrykv**
## Description

Allows you to search for the Craft documents. The search works through all spaces that Craft has locally available.

## Screencast

https://user-images.githubusercontent.com/12697803/166889264-6e8ca5a8-2774-4289-989c-f4e3cbee00f9.mp4

https://user-images.githubusercontent.com/12697803/166889278-5d7904f5-6e54-4b01-8c58-0d52f984c032.mp4

CleanShot 2022-05-05 at 11 41 53

It works in either "block mode" or "document mode." It allows finding and seeing either a specific block or the document with the block. Either way, the search result is the same; the representation is a bit different.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @kudrykv 👋 

Is this ready for a review?

**Comment by pernielsentikaer** [comment]
Hi @kudrykv 👋 

Is this ready for a review?

**Comment by kudrykv** [comment]
@pernielsentikaer yes

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @kudrykv 👋 

Instead of using your custom `<AppNotInstalled />` I would go for something like this:

CleanShot 2022-05-10 at 13 18 55@2x

Where I used: [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) and [Toast](https://developers.raycast.com/api-reference/feedback/toast)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by kudrykv** [comment]
It now looks this way:
CleanShot 2022-05-10 at 17 33 19

**Comment by kudrykv** [comment]
@pernielsentikaer updated to use a smaller image for the empty list
CleanShot 2022-05-20 at 09 14 15@2x

**Review by pernielsentikaer — APPROVED** [review]
Let's get it merged 🔥

**Pull request merged**
