### PR TITLE
massCode: Add detail of the snippet to the view

### PR DESCRIPTION
**Pull request by mkitane**
## Description

Added a detail view to the massCode extension

## Screencast
Capture d’écran 2022-05-03 à 00 32 35

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by unnamedd** [comment]
Hello @mkitane,

Based on the `<List.Item.Detail />`'s documentation you should avoid to make use of the accessories in the `<List.Item />` and bring those informations to the markdown content.

> When shown, it is recommended not to show any accessories on the List.Item and instead bring those additional information in the List.Item.Detail view.
https://developers.raycast.com/api-reference/user-interface/list#list.item.detail

In the way you presented in the screenshot, you have no space to show the subtitle nor the "Kubernetes" word.

**Comment by mkitane** [comment]
> Hello @mkitane,
> 
> Based on the `<List.Item.Detail />`'s documentation you should avoid to make use of the accessories in the `<List.Item />` and bring those informations to the markdown content.
> 
> > When shown, it is recommended not to show any accessories on the List.Item and instead bring those additional information in the List.Item.Detail view.
> > https://developers.raycast.com/api-reference/user-interface/list#list.item.detail
> 
> In the way you presented in the screenshot, you have no space to show the subtitle nor the "Kubernetes" word.

Good point, I moved that piece of info to the Detail view.

**Comment by antonreshetov** [comment]
@mkitane It looks cool. We also need to update the changelog.

**Comment by antonreshetov** [comment]
@mkitane I don't know if it's an implementation bug, but I faced a random bug. Sometimes the code is cut off in the preview. 
preview

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @mkitane 👋 

Thanks for the update 🔥 

It beginning to look quite nice! It seems like breaks disappear when using plaintext, is that something that you can do something about?

CleanShot 2022-05-03 at 05 23 03@2x

**Comment by mkitane** [comment]
> It beginning to look quite nice! It seems like breaks disappear when using plaintext, is that something that you can do something about?

Unfortunately, Raycast only allows markdown for `List.Item.Detail`, which means that the plaintext is treated as markdown (and hence why you see the line break disappear). 
A workaround would be:
-  to wrap it around a code block, just like it is done for the other languages.
- Use a txt to markdown converter, but I couldn't find a good one.

An ideal solution would be to have Raycast support a text field additionally to the markdown one.

How do you think we should approach it?

**Comment by pernielsentikaer** [comment]
Hi @mkitane 👋

I think I would just wrap it inside a block actually 😄 And after this is merged we can look into if we can find a better solution, but this is a nice enhancement that could be awesome to have out public 💯 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by mkitane** [comment]
> @mkitane I don't know if it's an implementation bug, but I faced a random bug. Sometimes the code is cut off in the preview.

@antonreshetov I updated the changelog.
Also, I can't reproduce this issue, the view is never cutoff for me.

**Review by pernielsentikaer — APPROVED** [review]
Awesome @mkitane 🔥

**Comment by antonreshetov** [comment]
> I updated the changelog.

Adding a new feature increases the minor version, not the patch. 
https://semver.org/

**Comment by antonreshetov** [comment]
@pernielsentikaer Can this be fixed?

**Pull request merged**
