### PR TITLE
Add PagerDuty extension

### PR DESCRIPTION
**Pull request by horimislime**
## Description

This extension helps making [PagerDuty](https://www.pagerduty.com/) operations easier.

- A command `View PagerDuty Incidents` shows recent incident activities
- In each activity user can operate status update (for now, only supports acknowledge/resolve) of incident

## Screencast

raycast-pagerduty-demo

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪

It looks really good, I was able to get a list of my incidents but I couldn't acknowledge it, there I got an error 400, do you know what might cause it?

image

```
14:32:12.294 [AxiosError: Request failed with status code 400] {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'Token token=u+r-dL3oRVV53PEr9bPg',
      'User-Agent': 'axios/0.27.2',
      'Content-Length': 56
    },
    baseURL: 'https://api.pagerduty.com',
    method: 'put',
    url: '/incidents/Q2AEDMTDTRC4LY',
    data: '{"incident":{"type":"incident","status":"acknowledged"}}'
  },
  request: <ref *1> Clie<…>
```

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by horimislime** [comment]
Hi @pernielsentikaer, thank you for reviewing my code!
I finally found what's wrong in your case, and commited following changes.

1. Display error message using Toast when API error occurs
2. Use more concise description about API token in setting page

If you test in the latest commit, you would see error message like this.
Screen Shot 2022-09-13 at 21 53 27

API token you need to set up is "User API token", but I assume you are using "Account API token" (it's very confusing😅)
So I updated description in extension setting to note that "User" API token is required. The difference is described in the following page.
https://support.pagerduty.com/docs/api-access-keys#section-generate-a-user-token-rest-api-key

Could you follow this guide to generate a new token and test my code again?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by horimislime** [comment]
@pernielsentikaer Thank you for your review and some additional fixes 😄

**Pull request merged**
