### PR TITLE
Add Chatwork Search Extension!!

### PR DESCRIPTION
**Pull request by nagauta**
## Description
Add following command to search chatwork.com
* Search Chats

used following official api
https://developer.chatwork.com/docs

## Screencast
chatwork-search-1
chatwork-search-2
chatwork-search-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @nagauta 👋 

I just tested the extension and it seems to be working as expected, only thing I'm a little quirious about is the messages in the list - they are not information since it's just a bunch of tags

image

Is there a way to format this better, or?

**Comment by nagauta** [comment]
Hi @pernielsentikaer  👋
Thank you for update some code missing and your review and.
 I'm happy taht you reviewed my code!

> Is there a way to format this better, or?
Yes, there should be a way to format this better.
Chatwork provide those tags with user to style text.
e.g. [info][/info] will surround text inside.

I'm thinking format this using regexp as there are rule for the tags 💪

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by nagauta** [comment]
> Hi 👋
> 
> Looks good to me, approved 🔥

Thank you for review. I'm so excited for Published!!!🔥

**Pull request merged**
