### PR TITLE
feat(Timers): menu bar quality-of-life upgrades and configurability

### PR DESCRIPTION
**Pull request by ThatNerdSquared**
## Description
- Rename "Show Menu Bar Item When" preference to "Show Menu Bar Icon When" to better reflect what it actually does
- Fix default icon setting for menu bar icons
- Add ability to show menu bar icon when no timer/stopwatch is running, and hide it when one is
- Don't show hours in menu bar title times if the countdown/elapsed time is <1hr
- Add "Configure Presets in Menu Bar" command that lets you choose which custom/default timer presets to show in the Timers Menu Bar
- Upgrade deps

## Screencast

Screenshot 2024-01-23 at 01 26 39

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Looks like a solid nice update @ThatNerdSquared 🔥 

Could we the `Start X minute Timer` `disabledByDefault` so we don't have 19 commands in the extension - this will only happen for new installations and users know that they are there?

**Comment by ThatNerdSquared** [comment]
Hi @pernielsentikaer - do you think this would lead to those commands being too hidden? Would new users still be able to find them?

**Comment by pernielsentikaer** [comment]
They do, we did the same in the [Spotify](https://www.raycast.com/mattisssa/spotify-player) extension where only 5 or 19 is visible by default 🙂

Raycast 2024-01-23 at 10 56 49

**Comment by ThatNerdSquared** [comment]
@pernielsentikaer change made 👍

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
I made a small correction, untitled custom timers have "<Untitled>" as subtitle

timers 2024-01-23 at 11 58 52

I hope it's okay 🙂

**Pull request merged**
