### PR TITLE
Add Horoscope extension

### PR DESCRIPTION
**Pull request by xmok**
## Description

This is a simple extension that uses https://horoscope-app-api.vercel.app/ to show you Daily, Weekly, Monthly horoscope.

## Screencast

https://github.com/raycast/extensions/assets/30526133/e4a249d3-5a07-4a37-aeaa-d30b89a5030d

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Maybe it could make sense to add a preference to set the default sign and make the placeholder in the commands show default sign

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by xmok** [comment]
Hi 👋.

Thanks for the quick response. Love the idea of a default sign for horoscope. I'm confused as to what you mean by "make the placeholder in the commands show default sign"? Is it possible to dynamically change placeholder of argument dropdown using the Preference? Or did you mean to say instead of placeholder/argument just use the Preference directly?

I'm assuming you mean the latter but please let me know if you intend something else.

**Comment by pernielsentikaer** [comment]
I was simply just talking about setting the sign argument optional and set a placeholder like below, and in preferences make it possible to set the default sign

Raycast 2024-05-16 at 07 21 02

**Comment by xmok** [comment]
Thank you for the clarification 💯.

I have updated the extension with the new preference. Also updated Raycast API.

horoscope-update

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
