### PR TITLE
[Badges][Color Picker] Expose and use color wheel feature

### PR DESCRIPTION
**Pull request by LitoMore**
### Color Picker

- Bump dependencies
- Expose Color Wheel ability through [Raycast Cross-Extension Conventions](https://github.com/LitoMore/raycast-cross-extension-conventions)
- Update API documentation

### Badges - shields.io

- Bump dependencies
- Use color wheel for picking colors

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hey! Thanks for your PR!
Do you mind making different PRs for each extension? That would make it easier for testing and separating concerns.
Cheers!

**Comment by LitoMore** [comment]
Sorry, I don't think so. Those changes are important for each other. I have many this kind of PRs before. And Per all approved and merged.

**Comment by mil3na** [comment]
Sure. I can still review, it just a matter of making things easier and cleaner. I will come back to this.

**Review by mil3na — APPROVED** [review]
LGTM!

**Pull request merged**
