### PR TITLE
Update zotero extension

### PR DESCRIPTION
**Pull request by chnyutao**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by chnyutao** [comment]
This PR fixes #11097. Sorry about the wrong link in the commit message :)

This is a work-in-progress. I have tested this fix on my device with Zotero 7.0.0-beta.68+c31a40c74 and [zotero-better-bibtex](https://github.com/retorquere/zotero-better-bibtex) 6.7.169. Need to make sure this fix does not break on previous Zotero builds.

**Comment by chnyutao** [comment]
It seems somewhere between release `v6.7.131`and `v6.7.132` ([compare](https://github.com/retorquere/zotero-better-bibtex/compare/v6.7.131...v6.7.132)), zotero-better-bibtex (bbt for short) decided to
- drop `better-bibtex-search.sqlite` in favor of `better-bibtex.sqlite` (https://github.com/retorquere/zotero-better-bibtex/commit/94c0634988ff1f1fa07e0abe992bc81cedb7b81a, https://github.com/retorquere/zotero-better-bibtex/commit/b634c04234f5a54b62f7b700860c64477dadaeea)
- use `citationKey` instead of `citekey` (https://github.com/retorquere/zotero-better-bibtex/commit/63028dcd03ada843d6f55dfd6745bc92d6587ab2)

The implication is that this fix will break for users using bbt prior to `v6.7.132`, which was released in Oct, 2023.

I assume a few users would turn off auto-update for bbt and thus still using an older version. In this case, this fix actually breaks their extension.

**Comment by pernielsentikaer** [comment]
@sadanand-singh could you check this?

**Comment by sadanand-singh** [comment]
Can you please find a way to support both. Seems two changes were not triggered at the same time, so we need to consider both independently. Though, I am not what is optimal way to fix it, but one possible solution I can think of is:
1. look for existence of `better-bibtex.sqlite` file, if it fails, try checking for `better-bibtex-search.sqlite`. If that fails as well, may be show error to the user.
2. Use try block when attempting `BIBTEX_SQL` query. when it fails try with older `BIBTEX_SQL_OLD` query that uses `citekeys`.

Would really appreciate if you try to find a solution. Otherwise, I can find some free time next weekend, so if needed I could try something then.

Thanks for the contribution!

**Comment by chnyutao** [comment]
I agree that the straightforward solution would be trying the new one and then falling back to the old one if the new one fails.

I'll try looking into this maybe Wednesday :)

**Comment by chnyutao** [comment]
I've tested this with an previous bbt version (`v6.7.117`) on my device. Seems everything works fine. PTAL.

**Comment by pernielsentikaer** [comment]
Awesome @chnyutao 🔥

**Comment by retorquere** [comment]
> The implication is that this fix will break for users using bbt prior to `v6.7.132`, which was released in Oct, 2023.
> 
> I assume a few users would turn off auto-update for bbt and thus still using an older version. In this case, this fix actually breaks their extension.

I really wish people wouldn't do this.

**Comment by sadanand-singh** [comment]
> > The implication is that this fix will break for users using bbt prior to `v6.7.132`, which was released in Oct, 2023.
> > I assume a few users would turn off auto-update for bbt and thus still using an older version. In this case, this fix actually breaks their extension.
> 
> I really wish people wouldn't do this.

Latest update in the code will NOT suffer from this @retorquere

**Comment by sadanand-singh** [comment]
> I've tested this with a previous bbt version (`v6.7.117`) on my device. Seems everything works fine. PTAL.

This looks great. Thanks @chnyutao

**Comment by retorquere** [comment]
> > I really wish people wouldn't do this.
> 
> Latest update in the code will NOT suffer from this @retorquere 

As in "I really wish people wouldn't stick to older versions of BBT".

**Comment by chnyutao** [comment]
Cheers!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
