### PR TITLE
Added Bitrise Start Builds extension

### PR DESCRIPTION
**Pull request by ChristianSteffensen**
## Description

This is an extension to start builds on the Bitrise CI/CD service. The extension lists all projects connected to your account and then you can select which branch and workflow you want to build with. It uses the Bitrise API to fetch this information, which is why an API token is required. This is handled by Raycast Preferences. 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ChristianSteffensen 👋 

Thanks for your contribution 🔥 

I gave your extension a quick spin and can see that it dies when entering the wrong credentials. Could you do this gracefully by returning an empty array and adding an error toast?

image

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by ChristianSteffensen** [comment]
Hi @pernielsentikaer

Thanks for the review! I've fixed the issue you mentioned by showing a toast and an empty view in the list.

**Comment by ChristianSteffensen** [comment]
> Hi @ChristianSteffensen 👋 
> 
> Thanks for the corrections, much better! 🔥
> 
> Just a thought, why are we not building this feature into the [existing extension](https://www.raycast.com/ubuntudroid/bitrise) instead?

Hi @pernielsentikaer 

To be honest, I didn't even realize it was possible to contribute to an existing extension until after making this. 

I'm perfectly fine with building it into the existing extension instead. I suppose I need to merge my extension with the other one and request another review? :)

**Comment by pernielsentikaer** [comment]
I didn't remember about it myself, sorry about that! 😄 

@ubuntudroid made the other extension, and I'm pretty sure that it would be a really nice addition to have that feature included in the same command (if possible) or as a separate, but I don't know much about Bitrise to guide 😄 

What do you think @ubuntudroid, are you okay with this?

**Comment by pernielsentikaer** [comment]
And yes, it's possible, it's the power of the community, we have so many extensions with multiple contributors 😄 

And yes, instead you just "modify" the other extension and make a new PR with the corrections

Let's await @ubuntudroid to have some feedback first, is that okay with you @ChristianSteffensen

**Comment by ChristianSteffensen** [comment]
Sure, sounds good to me 🔥

**Comment by ubuntudroid** [comment]
@ChristianSteffensen @pernielsentikaer Sure, that looks like a great addition. Go for it! 👍

**Comment by pernielsentikaer** [comment]
@ChristianSteffensen could you create a new PR with the corrections? Would love to see the addition in the current extension 🙂

**Comment by pernielsentikaer** [comment]
I'm closing this due to inactivity; feel free to open it again or comment in the thread when you're ready to continue working on it 🙂

You can also catch me here or in [Slack](https://www.raycast.com/community) if you want to discuss 😄

**Pull request closed without merging**
