### PR TITLE
Add Cyberduck extension

### PR DESCRIPTION
**Pull request by scottaglia**
## Description

Search and open Cyberduck bookmarks and history

Thanks to @thomaspaulmann, I used the source code of Visual Studio Code Recent Projects as a reference while building this extension.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/15358419/153512001-c990cc3e-b33d-4578-b785-27bcd428423e.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
Oh that brings back memories. Haven’t used cyberduck in a loooong time 🦆

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @scottaglia 👋 

Awesome extension, well done! 💪 I don't have anything to correct! 🚀 

One thing you could consider adding is a Failure toast if Cyberduck is not installed, it was done in other extensions, something like this:

```
  async function IsCyberduckInstalled() {
    const applications = await getApplications();
    return applications.some(
        ({ bundleId }) => bundleId === "ch.sudo.cyberduck"
    );
  }
  ``` 

And a failure toast with a message like
- title: Cyberduck is not installed
- message: Install it from: https://cyberduck.io

WDYT?

**Comment by scottaglia** [comment]
Hi @pernielsentikaer!, thank you for the nudge in the right direction. I added the check, let me know if something is wrong

**Review by pernielsentikaer — APPROVED** [review]
Awesome @scottaglia 💪 

Looks very nice! 💯

**Pull request merged**
