### PR TITLE
File manager

### PR DESCRIPTION
**Pull request by es183923**
## Description

creates an extension to manage files from Raycast

features:
- view files
  - [x] directories first preference
  - [x] case sensitive preference
  - [x] show dotfiles preference
  - [x] copy directory/file path
  - [x] show directory/file in finder
  - [x] open file in an app
  - [x] show file size
  - [ ] ~~show directory size~~
  - [ ] custom start location
  - [ ] works with symlinks (partially)
  - [ ] ~~input slash or path to go to that location~~
  - [ ] ~~integrate with Finder tags~~
  - [x] show file permissions (optional)
  - [ ] favorites (optional)
  - [ ] custom files to always hide
- manage files
  - [x] create file
  - [x] create directory
  - [ ] delete file (not adding until confirmation can be created)
  - [ ] delete directory (not adding until confirmation can be created)
  - [ ] ~~create symlink~~
- metadata
  - [x] screencast/screenshots
  - [x] non-default icon
  - [x] update package.json for names and descriptions

## Type of change

- New extension

## Screencast

* todo

## Checklist

- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I read the [extension guidelines](https://developers.raycast.com/information/review-process#guidelines)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by pomdtr** [comment]
I have built a similar extension during the alpha. I can share the code with you if you are interested!

**Comment by es183923** [comment]
Added create file and directory commands

**Comment by pomdtr** [comment]
In my extension, I added some alias available in any directory (`~`, `/` and `..`). Using the `..` alias would allow you to go back to the Users directory from the home directory.

**Review by PitNikola — CHANGES_REQUESTED** [review]
Pretty cool extension! Few things from my side that I noticed while testing:

- The permission number in the subtitle might be slightly confusing, especially since it's enabled by default. Is there more user friendly alternative to it? It's not something you would see in Finder... Right now if a user doesn't know what this number stands for, they can end up assuming it's something else (number of files inside the folder, size, etc).
- Using navigation title for the file path might not scale well because it has a limited width. We also want to disallow changing navigation title in the root because developers misuse it causing jumping in the floating tab when opening the command. I would suggest 2 alternative solutions to this: either using list section title for the path or using search bar placeholder to indicate folder you're in. If you go with the first root, you will need to merge directories and files in one section when you have "Directories first", but I think it's okay – it's clear what is folder and what is file.
- Placeholder is missing in the search bar when going inside folders. Let's add it there as well.
CleanShot 2021-11-02 at 16 34 59@2x
- When I run your extension locally, I got a warning about missing `key` attributes. Please keep an eye on those warnings because not specifying appropriate key can affect performance.

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Directory`. See https://reactjs.org/link/warning-keys for more information.
    at null.DirectoryItem (/Users/pitnikola/dev/raycast/extensions/extensions/file-manager/src/utils.tsx:97:29)
    at null.Directory (/Users/pitnikola/dev/raycast/extensions/extensions/file-manager/src/utils.tsx:243:48)
    at Command
    at ray-navigation-stack
    at rm (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:13009)
    at ul (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:13114)
    at Ps (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:12230)
    at JO (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:9717)
    at ray-root
    at yf (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:12534)
```
- Is there any way to move up a directory to explore folders and files outside of user folder? Maybe some action like `⌘ [` could act like go up?

**Comment by aesign** [comment]
Hello @es183923! Awesome extension, so useful. Thank you for working on it.

Though, I'm getting a weird error when I try to open a symlink item. The curious thing is that opening others symlinks (but also directories and files) works inside the same directory.

CleanShot 2021-11-04 at 10 01 28@2x

**Comment by tonka3000** [comment]
@es183923 cool extension 🚀

**Comment by es183923** [comment]
> * The permission number in the subtitle might be slightly confusing, especially since it's enabled by default. Is there more user friendly alternative to it? It's not something you would see in Finder... Right now if a user doesn't know what this number stands for, they can end up assuming it's something else (number of files inside the folder, size, etc).

I'll make the default as off.

> * Using navigation title for the file path might not scale well because it has a limited width. We also want to disallow changing navigation title in the root because developers misuse it causing jumping in the floating tab when opening the command. I would suggest 2 alternative solutions to this: either using list section title for the path or using search bar placeholder to indicate folder you're in. If you go with the first root, you will need to merge directories and files in one section when you have "Directories first", but I think it's okay – it's clear what is folder and what is file.

To fix this, I'll put the path as the search bar placeholder instead.

> * Placeholder is missing in the search bar when going inside folders. Let's add it there as well.

That'll be fixed with the previous issue.

> - When I run your extension locally, I got a warning about missing `key` attributes. Please keep an eye on those warnings because not specifying appropriate key can affect performance.

I'll try to fix this.

> * Is there any way to move up a directory to explore folders and files outside of user folder? Maybe some action like `⌘ [` could act like go up?

I originally wanted to do this, but it would prevent the normal push/pop of views from working correctly. I think that the best way to go is by letting the user set a directory to start from, which I'll add soon.

**Comment by es183923** [comment]
> Though, I'm getting a weird error when I try to open a symlink item. The curious thing is that opening others symlinks (but also directories and files) works inside the same directory.

Does Raycast have the `Full Disk Access` permission in Finder? This might be why, but I'm not sure.

**Comment by thomaspaulmann** [comment]
Any help needed here? 

As to permissions, I think we have that as an open issue already. Right now you get the same access as Raycast.

**Comment by aesign** [comment]
@es183923 @thomaspaulmann  sorry for the late reply, I figured out the issue the same day I reported it. The problem was the content of the folder, not the folder itself: a file without an extension. Unfortunately I can't find that file anymore in the Bin.

**Comment by pernielsentikaer** [comment]
@es183923 Is this ready for review or do you need help with anything?

**Comment by es183923** [comment]
I need some help with the unique key prop error. My code seems to add the key prop, but it still raises the error. Other than that, it should be good for review.

**Comment by es183923** [comment]
Hm, the build is failing, saying that it can't open the `package-lock.json` file, but it's there.

**Comment by pernielsentikaer** [comment]
Hi @es183923 👋 

You're right, it's indeed added to the repository, but you have placed it inside the src/ folder 😄 

MeARUYjUPvW9UC0X

**Comment by es183923** [comment]
Fixed.

**Comment by unnamedd** [comment]
> I need some help with the unique key prop error. My code seems to add the key prop, but it still raises the error. Other than that, it should be good for review.

Send me a DM on Slack and I will help you, I had exactly the same problem few days ago and with @fe9lix help, I understood the problem!

**Comment by pernielsentikaer** [comment]
Hi @es183923 👋 

I'm still struggling with this extension, this is how I can reproduce it:

- Set root to ~ and tick everything except dotfiles (Should be irrelevant)
- Go to desktop and create a new folder
- The new folder can not be accessed right away
- Go one back to ~ and go back to Desktop folder
- See that the path is from within a subfolder and its not possible to get back to ~/Desktop

https://user-images.githubusercontent.com/38033107/141733569-7c68fdd9-ff51-4c34-8d28-7141498505e1.mp4

Let me know if I can help debug it, I'm at Slack for the next 6 hours and later again.

**Comment by PitNikola** [comment]
Maybe let's merge this one and ship fixes in a follow-up PRs? Otherwise we might get stuck with it for very long time. @es183923, when you do you think you'll be able look into the issue @pernielsentikaer brought up?

@pernielsentikaer was there anything else except for the bug you discovered?

**Comment by es183923** [comment]
Yes, I've spent a while investigating the issue that he found, but I haven't found a solution. I'll remove the "create file" and "create folder" commands for now, and add them back in a follow-up PR.

**Comment by es183923** [comment]
Oops, accidentally deleted this branch while cleaning up other branches.

**Comment by pernielsentikaer** [comment]
@PitNikola The same strange behavior happens with create file when navigating around after creating the file. 

https://user-images.githubusercontent.com/38033107/142146321-e282c3a6-36ca-42c7-ad71-13718fb78855.mp4

**Review by pernielsentikaer — APPROVED** [review]
@PitNikola — Now that the two create commands are removed, I can't find anything not working when browsing 💪

**Comment by kerryj89** [comment]
I tried setting "Start Directory" to `/` but it gives me a "Something went wrong" error.

**Pull request merged**
