### PR TITLE
Add mastodon extension

### PR DESCRIPTION
**Pull request by sevi418**
Ref: #6156

## Description

**Raycast Extension for Mastodon**

overview

The original version was baseed on [Raycast-Akkoma](https://www.raycast.com/SevicheCC/akkoma), thanks to the generous contributions of @BasixKOR  and @pernielsentikaer, many new features have been added.

**Features**:
- Boost / favourite / bookmark / reply / edit / delete status
- Write status with markdown support.(Only if the instant supports Markdown)
- Publish simple status with text.
- Publish scheduled status with natural date format.
- Publish status with attachments (image, video, files); add alt text to the image when only one image is attached.
- Save draft status.
- View your bookmarked statuses.
- View your latest statuses.
- View home timeline.
- Open the latest published status that was published from Raycast through the actions.

### Login

Input your Mastodon instance's URL, then click the "Continue" button in the bottom-right corner.

### Mark status as sensitive 
Toggle the "Sensitive" checkbox to mark the attached image as sensitive, or add a content warning to the status.

### Write status with markdown
Toggle the "Markdown" checkbox to render markdown in the text file. Markdown shortcuts are also supported (e.g., pressing `⌘` + `B` will add `**bold**` around the selected text, `⌘` + `I` will make the selected text italic, etc.).

### Available Settings

If the instance supports Markdown, please select the `Built-in Markdown Support` checkbox. 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Sevichecc** [comment]
**TODO**  - Move some #5001 features: 
- [ ] Search account 
- [ ] Home timeline 
- [ ] Display custom emoji

**Comment by Sevichecc** [comment]
I feel that the PR is almost ready to go. @pernielsentikaer, would you mind taking a look?

**Comment by pernielsentikaer** [comment]
I started the review but ran into some internal issues with the oAuth, will hopefully be able to continue soon

**Comment by pernielsentikaer** [comment]
I think we narrowed down the issue, please make sure the `authorize` method is only ever called once at a time, it seems like it's called twice in useMe 🙂

**Comment by Sevichecc** [comment]
> I think we narrowed down the issue, please make sure the `authorize` method is only ever called once at a time, it seems like it's called twice in useMe 🙂

I was not sure  when to authorize, so I invoked the authorize method when the command was called. I have now removed the unnecessary authorize method call in useMe. Does it work as intended now?

**Comment by Sevichecc** [comment]
Any progress with this? I have been waiting over a month now for an opportunity to have it reviewed.

**Comment by danielsequeira** [comment]
@Sevichecc sorry for the delay here. I will finalise the review.

**Review by danielsequeira — APPROVED** [review]

**Pull request merged**
