### PR TITLE
Add http-status-code-lookup extension

### PR DESCRIPTION
**Pull request by ishaanbedi**
## Description

This extension provides a list of HTTP status codes and their descriptions.

Users can search for a specific status code or its description to get more information about it such as it's description, category, usage, etc.

## Screencast

https://github.com/user-attachments/assets/433bad43-a475-4074-8808-d2de34d179b7

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by LitoMore** [comment]
There is already a similar extension [HTTP Status Code](https://www.raycast.com/Alex_/http-status-codes). What do you think is the difference that warrants a new extension?

**Comment by ishaanbedi** [comment]
> There is already a similar extension [HTTP Status Code](https://www.raycast.com/Alex_/http-status-codes). What do you think is the difference that warrants a new extension?

Hi @LitoMore , thanks for highlighting that extension.

My extension also includes the unofficial codes (exclusive to some servers or services) baked in, which might be useful for users who might encounter them as a special case. The search uses fuzzy logic regarding searching with code type, name, category and even description of the status code, making it easier to find more info, not only from code but from related information as well.

Also, the description of the status code and usage information is provided within the extension itself in a `Detail` view, without redirection to MDN or any other online resource.

Rest, if you think this might be a duplicate and won't add value to users, I have no issue with closing this PR 😀

**Comment by lucasmezencio** [comment]
I simply **love** this!

And I think I'm with @LitoMore on this one., Although I kinda understand your points @ishaanbedi, I really think it's worth adding this to the existing extension.

To simply put, this was going to be my next add to the HTTP Status Codes (I just didn't have the time).

I'd be more than happy to help you if needed. 😉

**Comment by lucasmezencio** [comment]
Hey @ishaanbedi! Want to work on this change together?

**Comment by ishaanbedi** [comment]
Hey @lucasmezencio , sorry for the late reply.
Absolutely yes! I'll try to go through the extension this weekend, and then implement new things as we discuss, how does that sound?

**Comment by lucasmezencio** [comment]
@ishaanbedi sure! Amazing!

**Comment by ishaanbedi** [comment]
Hey @lucasmezencio , sorry for the delay, been busy with work!
I had a look at the extension, and I am super excited to contribute.
Can you please let me know the next steps, and what I should start with?

**Pull request closed without merging**
