### PR TITLE
Add stashpad-docs extension

### PR DESCRIPTION
**Pull request by tsmarin**
## Description

This introduces the Stashpad Docs extension! Stashpad Docs is a tool for writing and collaborating on documents. You can learn more at https://stashpad.com and try it out at https://stash.new.

This extension has two commands: Create Doc and Search Docs. Create Doc creates a new document and opens it in your browser. Search Docs allows you to search for your recent docs and navigate to the doc of your choice in your browser.

## Screencast

stashpad-docs-1

stashpad-docs-2

stashpad-docs-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The extension crashes when you enters a wrong key, could you handle that gracefully?

stashpad-docs 2024-04-23 at 13 41 40 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by tsmarin** [comment]
Thanks for the review @pernielsentikaer! 

We're now showing a failure toast if something went wrong. Also, I've added the loading indicator, and commented out `localhost` URLs for now. 

Please let me know if you see anything else that should be improved.

**Comment by pernielsentikaer** [comment]
Could you stop the loading indicator if an error occurs too?

**Comment by tsmarin** [comment]
Done!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
