### PR TITLE
[Pokédex] use svg icon, update type filter

### PR DESCRIPTION
**Pull request by anhthang**
## Description

- Add type filter, split view for Moves
- Add categories
- Use SVG icon for better render
- Add changelog

## Screencast

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @anhthang 🔥 

Thanks for another great update, you're rocking it! 🪨 

Couldn't find anything that I would like to corrected, would you be able to add [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) before merging it?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 👋 

I have added `metadata` folder, please help me review it.

**Comment by pernielsentikaer** [comment]
Only one thing @anhthang, there can only be 6 images in total in metadata, can you skip one, and then we're ready to go 💪 🔥

**Comment by anhthang** [comment]
Hi @pernielsentikaer 

It's ready now 💪

**Review by pernielsentikaer — APPROVED** [review]
Thanks 🔥

**Pull request merged**
