### PR TITLE
Port manager

### PR DESCRIPTION
**Pull request by lucaschultz**
## Description

- *Show Info* action (`⌘` + `i`) to display process information
- *Show in Finder* action (`⌘` + `f`) to reveal the executable of a process in Finder
- *Kill Parent* action (`⌘` + `p`) to kill the parent process of a process opening a port
  - For obvious reasons not available if the PID of the parent process is either 0 (kernel) or 1 (launchd)
- Some changed wording
  - Navigation title of *Kill Port* command is now, well, *Kill Port*
  - Improved description of the extension
- Improved README
- Added a changelog
- Added screenshots

## Screencast

https://user-images.githubusercontent.com/45899273/179182451-976305ca-ab02-46a8-80e7-47c8e1075190.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

> Kill Parent action (⌘ + p) to kill the parent process of a process opening a port
For obvious reasons not available if the PID of the parent process is either 0 (kernel) or 1 (launched)

I can't get above to work, did you forget to add this? 🙂

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
It was just me not testing enough, it works 🔥

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Awaiting @lucaschultz

**Comment by lucaschultz** [comment]
@pernielsentikaer Like discussed on Slack, I renamed the command back to `open-ports` whilst leaving the `title` as  *Kill Port*. 

I also highlighted in the changelog why the *Kill Parent* action (`⌘` + `p`) might not be available for a given process 😃

It's certainly a niche feature as most processes opening ports will be children of `launchd`. But It was an easily realized given the parent PID was available anyways.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
