### PR TITLE
[LaLiga] Enhanced Match Information

### PR DESCRIPTION
**Pull request by anhthang**
## Description

- Added match lineups to provide detailed information about the starting players and substitutes for each team.
- Included upcoming and previous matches directly in the standings view for easier navigation.

## Screencast

laliga-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by anhthang** [comment]
Hi @pernielsentikaer 

Thanks for your fixes, but I wonder what's wrong with the lint in my end. Do you know why it's failed?

**Comment by pernielsentikaer** [comment]
I have no clue actually, does it still fail for you?

**Comment by anhthang** [comment]
@pernielsentikaer no, just failed in the PR checks

**Pull request merged**
