### PR TITLE
Add bech32-converter extension

### PR DESCRIPTION
**Pull request by Zygimantass**
## Description

This extension adds a new command to convert Cosmos blockchain bech32 formatted addresses with different prefixes.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Could it make senes to make it a no-view command instead and using arguments to get the input instead?

Raycast 2024-06-17 at 15 01 12

**Comment by johnletey** [comment]
I agree, no view is much cleaner!

**Comment by Zygimantass** [comment]
ask and you shall receive @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
