### PR TITLE
feat(todoist): Add new "Search tasks" command

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

- Added a new command to search across all your tasks with the ability to filter by project
- Added new scheduling options: "in two days" and "no due date"
- Rename `utils.ts` to `helpers.ts`

## Screencast

https://user-images.githubusercontent.com/16003285/163243170-8ced011d-0044-4868-8c3c-3cf71177c3e1.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi @thomaslombart 👋 

Thanks for the update, it works as expected 🔥

**Comment by al3jandrocabrera** [comment]
Hi, the search command is gone. It was the best feature. Is there a way to bring it back?

**Comment by thomaslombart** [comment]
Hi @al3jandrocabrera, you can see all your tasks in the `Home` command by selecting `All Tasks` in the dropdown. To have a quick access to this view, you can use the `Create View Quicklink` action: https://github.com/raycast/extensions/blob/181109b47c490c360cca035316a54d656d47d051/extensions/todoist/README.md#create-tasks-view

Note that it's also possible to create quicklinks for projects and labels.

**Comment by al3jandrocabrera** [comment]
Hi @thomaslombart, thanks. Honestly, the Search command was the only one I used from the extension and it saved me a lot of time accessing any task on any screen I was on. I don't understand why it has to be removed. All the best.

**Comment by thomaslombart** [comment]
It's been removed to avoid having an extension bloated with commands and provide a simpler experience. But like said above, you can make use of a quick-link to bring it back in a simple way using the `Create View Quicklink` action.

**Comment by al3jandrocabrera** [comment]
Hi Thomas, thanks. I appreciate your efforts. To be honest, I don't think you've achieved simplicity by removing an essential feature like 'search' and adding 'home' and having to create a quicklink and all that just to get back to where it was. I can't even get the extension to work anymore. It's your call.

**Comment by thomaslombart** [comment]
Hey @al3jandrocabrera, you can now search for all your tasks again using the new `Search` command of the Todoist extension. See #6908.

**Pull request merged**
