### PR TITLE
Change case multi lines

### PR DESCRIPTION
**Pull request by nagauta**
## Description
This is proposal.
### issue
Trying to change the case for multiple lines, it didn't work property.
1. words before changing case
change Case
change Case
change Case

2. words after changing case
change_case_change_case_change_case

as you can see new line is gone...

### solution
allow multiple lines to be changed at once.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Could you give this a spin @es183923 🙂

**Comment by es183923** [comment]
Looks good

**Comment by nagauta** [comment]
on working

**Comment by nagauta** [comment]
@pernielsentikaer 
the author told us "Looks good"

could you take a look again please?

additionary I improve some stuff below
- fix typo
- update api
- update author name as it is changed on [raycast.com](https://www.raycast.com/erics118)
- fix shortcut bug

thanks in advance.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
