### PR TITLE
feat: Add `pwgen`

### PR DESCRIPTION
**Pull request by omBratteng**
## Description

This password generator has 6 different algorithms for generating passwords.
Also includes some preferences for setting.
- default password strength
- default password length
- word delimiter
- max word length

## Screencast

https://user-images.githubusercontent.com/1681525/163876168-9098a7bd-ac8c-4ce9-990f-506656f4afc1.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Hi @omBratteng 👋
[Extensions for generating passwords](https://www.raycast.com/textnav/random-password-generator) already exist in the store. Is there any difference between your extension and it?

**Comment by omBratteng** [comment]
@koinzhang it features two different commands, one for generating passwords by strength, and one by length.
Plus it's configurable, and I plan on adding a few more settings like configuring the special characters. Basically I want to make almost all the the constants into a setting, so that people can tweak it however they like, just submitted this as a first edition.

**Comment by pernielsentikaer** [comment]
Hi @omBratteng 👋 

Thanks for your contribution 💪 Sorry for the long response time; it's my bad!

 I have two questions:

- Would it make sense to merge this into one of the two extensions as commands that already generate passwords?
- If not, do you then have an idea for a better name since this has 100% the name of another extension 😄 

Let me know what you think 😄

**Comment by omBratteng** [comment]
Hi @pernielsentikaer 

> * Would it make sense to merge this into one of the two extensions as commands that already generate passwords?

I think it would require a lot of refactoring of the others to implement these. And I think it should be possible to have multiple to choose from.

> * If not, do you then have an idea for a better name since this has 100% the name of another extension 😄

Could rename it to Passphrase Generator? Does it crash because of `pwgen` or because it has Password generator in the name?
I do like how VS Code has it, the extensions have the authors username in it, like `omBratteng.password-generator`, and allow an open market for extensions.

**Comment by pernielsentikaer** [comment]
Hi @omBratteng 👋 

It's just because another extension has the same name
CleanShot 2022-05-12 at 06 33 13@2x

As I asked a few times, the best output would be to merge into one of the current ones, but it would be good to have a unique name since we're continuing on its own

Here you'll get an URL with your username in, that's the best we can do 😄

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @omBratteng 👋 

Do you want to complete this extension? Let's find a solution 😄 

Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by omBratteng** [comment]
Sorry, I've just been overloaded at work. I'll try to rename the extension to something else this week.

**Comment by pernielsentikaer** [comment]
I can also take over the last part if you're busy @omBratteng, I just need a "OK" 🙂

**Comment by pernielsentikaer** [comment]
I think we're here @omBratteng 🔥

**Comment by omBratteng** [comment]
Awesome, thanks @pernielsentikaer

**Pull request merged**
