### PR TITLE
Add proton-version extension

### PR DESCRIPTION
**Pull request by flavienbonvin**
## Screenshots

Default view of the version of deployed Proton products
proton-version-1

Possible to search to filter the list of products
proton-version-2

Beta version of Proton product is also supported
proton-version-3

Actions allow going to Proton GitHub, tag release, product home
proton-version-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Would it be possible to first return data when all calls have been made instead of as now where it shows undefined for some time? 😊

**Comment by pernielsentikaer** [comment]
What do you think about making it something like this?
Raycast-doO9LttN@2x

That would make the list jump less and maybe even be a better UI/UX 😊

**Comment by flavienbonvin** [comment]
Thanks for the review, I agree that the result is way nicer the way you did it!

**Comment by pernielsentikaer** [comment]
I committed the code now, correct anything you'd like 😊

**Comment by flavienbonvin** [comment]
> I committed the code now, correct anything you'd like 😊

Everything good on my side, thanks a lot for the insights and proposition

**Comment by pernielsentikaer** [comment]
Awesome! I added myself as contributor to help you out in the future 😊

**Pull request merged**
