### PR TITLE
[Simple Reminder]: Fix the quoted topics not triggering notifications

### LINKED ISSUE #11349: [Simple Reminder] Reminder topic with quotes fails to notify
### Extension

https://www.raycast.com/comoser/simple-reminder

### Description

When reminder topics are set with quotes ("") in its content, then when the extension should notify the user of the reminder, it breaks instead with the stack trace described below.

### Stack Trace
```
Error: Command failed with exit code 1: osascript -e display notification "clear the " vaccuum "" with title "Simple Reminder" sound name "default" 
32:41: syntax error: A identifier can’t go after this “"”. (-2740)

pr:error.js:60:10

---
57: 		error.originalMessage = error.message;
58: 		error.message = message;
59: 	} else {
60: 		error = new Error(message);
61: 	}
62: 
63: 	error.shortMessage = shortMessage;
---

reminderNotifications.js:5:10351
```

### Steps To Reproduce

1. Run in dev mode to get the logs
2. Create a reminder with quotes e.g. Remind me to "clean" the house in one minute
3. Wait for the notification time to arrive and see that the logs present an error

### Current Behaviour

The extension is unable to notify users when reminder topics are set with quotes in its content

### Expected Behaviour

The extension is ABLE to notify users when reminder topics are set with quotes in its content

### PR DESCRIPTION
**Pull request by comoser**
## Description

Fixes the issue with the extension not being able to notify the user when quoted words were present in the topic set for the reminder.

- sanitize topic for apple script notification send
- correctly parse quotes in the reminder extraction function

## Screencast

N/A

# Related Issue
Fixes #11349

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the update 🔥 

Could you use `runAppleScript` from @raycast/utils instead 🙂

**Comment by comoser** [comment]
> Thanks for the update 🔥
> 
> Could you use `runAppleScript` from @raycast/utils instead 🙂

It's done, had to update some more dependencies, but seems to work exactly the same, ty :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Thanks for the update 🔥

**Pull request merged**
