### PR TITLE
Add url-shortener extension

### PR DESCRIPTION
**Pull request by Visual-Studio-Coder**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Visual-Studio-Coder** [comment]
I'm okay with the changes you made @pernielsentikaer 
If everything is okay, go ahead and merge!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Maybe add a preference so it's possible to copy to clipboard OR paste to active window

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Visual-Studio-Coder** [comment]
@pernielsentikaer I will get this done asap.

**Comment by Visual-Studio-Coder** [comment]
I have returned!!!! 🤣
Basically, I just added a new required preference where you can choose between saving the URL to clipboard or pasting it to the active window.

I also updated the README to highlight why this URL shortener is so revolutionary including the fact that it's free and offers domain customizability.

**Comment by pernielsentikaer** [comment]
Seems like you forgot to add the preference to paste/copy to all scenarios, changed a bit more

Could you test it?

**Comment by Visual-Studio-Coder** [comment]
@pernielsentikaer Whoops, I'm sorry for that mistake I made. I have also added some fixes to the readme and things, but the extension works fine, so that's a good thing.

**Comment by Visual-Studio-Coder** [comment]
Whoops, I forgot to click "request re-review!" I still have a lot to learn about Github 🤣

**Comment by Visual-Studio-Coder** [comment]
@pernielsentikaer I really felt the need for simplicity and speed with this extension. I did not want to have to do any more keyboard clicks than I had to. I can try to create another SEPARATE command that accepts an argument, but I really want to keep a command that uses only selected text as well.

**Comment by Visual-Studio-Coder** [comment]
> One last thing, don't you think it would be nice if it's supported an argument with URL so it's not only can be used for selected text?

Is there a way I can programmatically change the mode of input? So if there's no selected text currently, an argument is expected, but if there is selected text, then it just works?

**Comment by Visual-Studio-Coder** [comment]
@pernielsentikaer 
Okay, so I just added a new command that is "Shorten URL Using Arguments" and renamed the old one to "Shorten URL Using Selected Text"

They both perform the same things, except the the using arguments one just copies the new link, and the one using selected text either copies or pastes.

I feel like now that I added this new command, maybe the preference is unnecessary, but you never know what the user would want . . .

**Comment by Visual-Studio-Coder** [comment]
Okay one more thing. I will have to get home and edit the README with the updated changes so I don't confuse any users.

**Comment by pernielsentikaer** [comment]
You should be able to do both in the same command 🙂

You could first check if argument is set, if so, use that value, if not, try to use the selected text - this way both should work as intended

**Comment by Visual-Studio-Coder** [comment]
@pernielsentikaer  how would the user know that they have the ability to choose between selected text and argument? there's not really a place in the extension where i can indicate the user of that (other than the readme which I don't know if anybody actually reads).

I think I prefer having a two commands thinking about it now.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
