### PR TITLE
[GitLab] Fix Merge Request Details error.

### PR DESCRIPTION
**Pull request by metakirby5**
## Description

Fix the following error that occurs when viewing Merge Request Details.

```
Could not get Merge Request Details: Type mismatch on variable $id and argument id (ID! / MergeRequestID!)
```

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Can you check this @tonka3000 🔥

**Comment by tonka3000** [comment]
@metakirby5 Thanks for the contribution. Works great.

Could it be that you be on a GitLab instance >= 15.0 e.g. gitlab.com? This seems to be a breaking change in >= 15.0. So we need to add a version switch to choose your change only when the instance is >= 15.0.

@Loskir Can you check this change on your instance. You had an instance < 15.0 when I remember correctly.

**Comment by tonka3000** [comment]
@metakirby5 @pernielsentikaer I check with GitLab 14.0.12 via docker and the type is not ID. So I assume we can merge it.

**Comment by tonka3000** [comment]
@metakirby5 Works great. Thanks for adding.

@pernielsentikaer For me it would be ready to merge.

**Review by pernielsentikaer — APPROVED** [review]
Let's get it merged @metakirby5 🔥

**Comment by pernielsentikaer** [comment]
Thank for all the verification @tonka3000 💪

**Pull request merged**
