### PR TITLE
Update reclaim-ai extension with support for new prioritization features, bug fixes, and authorship.

### PR DESCRIPTION
**Pull request by ajohnson1200**
## Description

- Updates to multiple parts of the extension to support the new prioritization work that's available in beta (https://help.reclaim.ai/en/articles/8291694-priorities-overview)
- Backed out recent changes around duplicate events which caused numerous customer support cases
- Update to authorship as original author is no longer a Reclaim employee

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by lightbody** [comment]
@shkreios This PR reverts your recent changes that came in. We got some customer tickets reporting some issues, so we want to temporarily revert it. But I think your changes are good ones we should merge back in soon. We just need some time to dig deeper and understand what happened. I hope that is OK. 🙏

**Comment by shkreios** [comment]
@lightbody, Yes, I apologize for any inconvenience caused. Upon further review, I realized that the filter logic could benefit from refinements. I've been testing a version locally that seems effective in my current setup. However, I'm concerned that it might not scale well with a larger number of accounts or meetings. Hence, I haven't submitted a new PR yet.

One significant challenge I encountered was distinguishing whether an event has been synced from another. I didn't filter all the `reclaimManaged && personalSync` events primarily because external calendars linked to Reclaim (and subsequently synced to a Reclaim-linked Google calendar) appear only once in the events endpoint.

@lightbody, if you have insights or suggestions about which properties or endpoints might be relevant for this issue, I'd greatly appreciate it. I'm eager to collaborate and provide any assistance.


This is my current fulter logic used locally

```tsx
/**
 * Filter out events that are synced, managed by Reclaim and part of multiple calendars
 * @param events
 * @returns
 */
export const filterMultipleOutDuplicateEvents = <Events extends ApiResponseEvents | undefined>(events: Events) => {
  if (!events) return events;

  // Create a map to store counts of each start-end combination
  const eventTimeCounts = new Map<string, number>();

  events.forEach((event) => {
    const key = `${event.eventStart}-${event.eventEnd}`;
    eventTimeCounts.set(key, (eventTimeCounts.get(key) ?? 0) + 1);
  });

  const res = events.filter((event) => {
    const key = `${event.eventStart}-${event.eventEnd}`;
    const count = eventTimeCounts.get(key) as number;

    // If the event has both personalSync and reclaimManaged and there's more than one event with the same start-end combination, we don't include it
    return !(event.personalSync && event.reclaimManaged && count > 1);
  });

  console.log(res.map((event) => [event.title, event.color]));

  return res;
};
```

**Comment by pernielsentikaer** [comment]
Is this ready to merge or do we want to change the author in package.json to another Raycast handle?

**Comment by ajohnson1200** [comment]
if it's possible to change it, then yes, we'd like to have the author changed to either myself or to @lightbody (CEO of Reclaim.ai).

**Review by webergnr — APPROVED** [review]

**Pull request merged**
