### PR TITLE
Improve UI copy for preserve case settings

### PR DESCRIPTION
**Pull request by chrismessina**
## Description

Small improvement to some UI copy meant to make the lowercasing behavior for Title and Sentence Case transformations clearer.

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by chrismessina — COMMENTED** [review]
Made the requested changes.

**Review by PWrzesinski — APPROVED** [review]
Thanks!

**Comment by pernielsentikaer** [comment]
Do you also want to check this @erics118

@chrismessina could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

**Review by erics118 — APPROVED** [review]

**Comment by chrismessina** [comment]
> Do you also want to check this @erics118
> 
> @chrismessina could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

Looks like @erics118 handled that? I'll be sure to change the changelog in any subsequent updates!

**Pull request merged**
