### PR TITLE
[AWS] Support Multiple Profiles

### PR DESCRIPTION
**Pull request by JonathanWbn**
## Description

This removes the hardcoded AWS Profile and Region setting in favor of a simple profile select.

This approach comes with several advantages:
- extension becomes zero-config
- adds profile switching inside the extension via list dropdown _(cached between commands)_
- supports all credential providers ([config and credentials files](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html), [environment variables](https://docs.aws.amazon.com/sdkref/latest/guide/environment-variables.html), [SSO](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sso/index.html)...)
- simplifies the extension by relying on the built-in behavior of the v3-SDK
- solves
  - #3057
- relates to
  - #3222 
  - #3022

### Demo 1 - Profile Switching

_Notice how the profile is persisted between the "tables" and "stacks" commands._

https://user-images.githubusercontent.com/19997520/203145075-eeeabaf0-9a35-40f0-8d11-472f62a4b705.mov

### Demo 2 - SSO

_In this example, the default profile uses credentials from the `~/.aws/credentials` file, while the `test_sso_profile` uses the `/.aws/config` file to read credentials. Notice that the CLI-login step is only required when the user is logged out. In most workflows, I expect the user to be already logged in._

https://user-images.githubusercontent.com/19997520/204146519-aa4d0321-caf0-4525-8755-4996ce509d6e.mp4

### CODE REVIEW

**Comment by duboiss** [comment]
I've been waiting for support for this for a long time, I didn't even think we could go this far. Thanks a lot, I will try to take the time to test it.

**Comment by pernielsentikaer** [comment]
Looking forward to the tests 🔥 

Awesome @JonathanWbn 🚀

**Comment by JonathanWbn** [comment]
@duboiss, did you get a chance to test this yet?

**Comment by victor-falcon** [comment]
Great, nice feature. This makes the extension a lot better 🎉

**Comment by duboiss** [comment]
> @duboiss, did you get a chance to test this yet?

It turns out that at work we changed the configuration. The `config` file now contains the profiles but using sso in the following format:
```
[default]
sso_start_url = XXX
sso_region = eu-central-1
sso_account_id = XXX
sso_role_name = PowerUserAccess
region = eu-central-1
output = json

[profile XXX]
sso_start_url = XXX
sso_region = eu-central-1
sso_account_id = XXX
sso_role_name = PowerUserAccess
region = eu-central-1
output = json

[profile XXX]
sso_start_url = XXX
sso_region = eu-central-1
sso_account_id = XXX
sso_role_name = PowerUserAccess
region = us-east-1
output = json

...
```

And that we now have no more `credentials` file. As a result, even before testing your changes, the current state of the extension no longer works for me.
image
I haven't yet taken the time to see if I can continue to use the extension from now on... by changing something.

**Comment by JonathanWbn** [comment]
> It turns out that at work we changed the configuration. The config file now contains the profiles but using sso

@duboiss I have taken this as an opportunity to re-think the whole approach and ended up with something much better: Just setting the `AWS_PROFILE` environment variables and letting the AWS SDK v3 do the rest. This happens to support **all** credentials providers (including SSO). With these changes, I expect the extension to work for you again (see demo 2 in the PR description)

@duboiss @victor-falcon This new approach required significant changes. I have updated the description accordingly. I appreciate any review or testing.

**Comment by duboiss** [comment]
Awesome ! After a reminder to use `aws sso login`, everything works great.
Howerver, I have a weird behavior for S3. As a reminder, S3 is a global service.

```ini
[profile A]
sso_start_url = XXX
sso_region = eu-central-1
sso_account_id = XXX
sso_role_name = PowerUserAccess
region = us-east-1
output = json

[profile B]
source_profile = XXX
region = eu-central-1
output = json
role_arn = XXX
```
On the profiles above, for the second one, "B", I got this :
image
A bucket that I should not have access.
image

I can also show you an other profile where I see rds snapshot bucket...
image

Thanks a lot, you made a great work

**Comment by duboiss** [comment]
@JonathanWbn My bad. By selecting a profile on the console I have these same files. I thought it was at AWS.
Except for a bucket that I can open on the console and not in Raycast (second screenshot above), everything is good.

**Comment by JonathanWbn** [comment]
@duboiss Thanks for the feedback! I have addressed the S3 problem. Do you mind testing again?

**Comment by pernielsentikaer** [comment]
It's really awesome to follow this extension, good work @JonathanWbn 🔥

**Comment by duboiss** [comment]
image
Do you think that we can add a button to run "aws sso login" without the need to open our own terminal ?
Maybe complicated. The output of this command terminates only when we click on "Allow" on the AWS page that opened (or with ctrl+c).
Once clicked, it seems that cmd + r reloads this error directly into the display. But maybe it can also be automated.

For your update @JonathanWbn, now I have this
image

**Comment by JonathanWbn** [comment]
> Do you think that we can add a button to run "aws sso login" without the need to open our own terminal ?

@duboiss I have tried this before, but I gave up on it eventually.

> For your update @JonathanWbn, now I have this

Then unfortunately my workaround is not robust. At this point, I would instead choose good error handling than try to cover a bunch of edge cases. So here's the error screen you should see now:
Screenshot 2022-11-29 at 19 19 10

@duboiss Could you confirm that this error handling is working for you? If so, I would love to get this PR merged.

**Comment by duboiss** [comment]
Same behavior as you, much better. That's ok for me, thanks.

**Comment by JonathanWbn** [comment]
> Same behavior as you, much better. That's ok for me, thanks.

Great!
@pernielsentikaer I would now consider this PR ready to be merged. 🚢

**Review by pernielsentikaer — APPROVED** [review]
Thanks for your hard work @JonathanWbn (and all contributors/testers)

**Comment by arabshapt** [comment]
Hi everyone, is it possible to open e.g. secretsmanager in specific profile? In raycast I can switch profiles with cmd+P and then search for secrets within that profile, but when I open it in browser by hitting cmd+K and then navigating to "open Secret" I need to switch the profile manually in the browser... Is It possible to add that information in the query(in URL) to switch the profile automatically? It would also be great to have a shortcut to open that specific secret(or anything else like) without cmd+K plus navigation.
Thank you for this extension!

**Pull request merged**
