### PR TITLE
Update ext/waktu solat

### PR DESCRIPTION
**Pull request by sayuthisobri**
- Fix some issue and logic on menubar
- Monotone icon in menubar

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Wouldn't it be better to always show the icon instead of only when there is not recent prayers?

**Comment by sayuthisobri** [comment]
> Hi 👋
> 
> Wouldn't it be better to always show the icon instead of only when there is not recent prayers?

Hi 👋,

I've make changes to address that, but is it ok that checking based on user preference that one still remain? mean if icon enabled in preference we always display the icon otherwise we just display text based notification on event similar to Calendar extension 👉👈.

**Comment by pernielsentikaer** [comment]
That should be fine 🙂

**Comment by pernielsentikaer** [comment]
Is this ready for review then?

**Pull request merged**
