### PR TITLE
Adds Brazilian Portuguese support to Google Translate

### PR DESCRIPTION
**Pull request by jeanfbrito**
## Description

Adds Brazilian Portuguese support to the languages list

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by metakirby5** [comment]
LGTM 👍

**Comment by pernielsentikaer** [comment]
Are you sure that it's working as expected @jeanfbrito 

CleanShot 2022-10-10 at 13 36 16@2x

**Comment by obetomuniz** [comment]
Looks like that `pt` is enough to provide a universal Portuguese translation. In the [docs](https://cloud.google.com/translate/docs/languages), there are no descriptions for regional subcategories. Same for English, Spanish, etc.

**Comment by jeanfbrito** [comment]
I really thought that was strange that didn't had `pt-br`. Really sorry for not checking directly in the docs. 🙈

**Pull request closed without merging**
