### PR TITLE
Workflowy Extension

### PR DESCRIPTION
**Pull request by pomdtr**
## Description

Browse your Workflowy tree from Raycast.

## Screencast

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @pomdtr 👋 

I tested the extension, and it seems to work as expected 🔥 

My only concern is that the user has to find the session ID and if the user signs out, then the session ID is invalidated. Is there a better way to handle this? 

Seems like there is an [unofficial API](https://github.com/johansatge/workflowy-php) written in PHP, maybe it's possible to extract some functionality - Workflowy is referring to this API themself

**Comment by pomdtr** [comment]
The sessionId cookie is long-lived (at least several months), and since there is no login api I would not bother with implementing their authentication logic. However, I will add some messaging to signal the user if the cookie is invalid or expired.

I will add the additional files, thanks for mentionning them :)

**Comment by pernielsentikaer** [comment]
Ah, I was just testing out every way to get it to crash, and it did when I logged out, since it's killed my session 😄

**Comment by pomdtr** [comment]
Not sure I have a maintainable way to fix this issue. I agree that this is not a good experience for raycast users, I'll keep this extension for my personal use.

**Pull request closed without merging**
