### PR TITLE
Add toggle dark mode extension

### PR DESCRIPTION
**Pull request by pindab0ter**
## Description

Adds a new 

## Screencast

https://user-images.githubusercontent.com/5128166/234675755-e4c830c1-c2c6-4e15-9dbc-1b11028165b7.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by andreaselia** [comment]
Awesome extension @pindab0ter, I guess the only thing left to do is to run `npm run fix-lint` to fix the styling issues and then it's good for review.

I look forward to using this when it is merged 😁

**Comment by pindab0ter** [comment]
I honestly can't believe this didn't exist already. I wouldn't be surprised if it does exist in some form that I haven't been able to find yet.

**Comment by pernielsentikaer** [comment]
Hi @pindab0ter 👋 

We already have `Toggle System Apperance` built-in which should be doing the exact same thing, can you confirm that?

**Comment by pindab0ter** [comment]
Yeah, yup. That's exactly what I was looking for. I had disabled it, probably because I didn't realise what it did.

Naming is hard. macOS uses both "Dark Mode" in their control centre as well as the more generic "Appearance" in their Settings.

**Pull request closed without merging**
