### PR TITLE
Add md-to-excel extension

### PR DESCRIPTION
**Pull request by victor-coding-gagent**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by victor-defi** [comment]
CleanShot 2023-04-25 at 22 46 42@2x

CleanShot 2023-04-25 at 22 48 14@2x
CleanShot 2023-04-25 at 22 49 44@2x

**Comment by victor-defi** [comment]
“md-to-excel” quickly converts markdown tables to excel tables

**Comment by victor-defi** [comment]
I've run `npm run fix-lint` to make sure there's no extra code

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
