### PR TITLE
Add alacritty extension

### PR DESCRIPTION
**Pull request by jose-elias-alvarez**
## Description

This extension adds a few commands to control the [Alacritty](https://github.com/alacritty/alacritty) terminal emulator:

- Edit File in Alacritty: opens the selected Finder item(s) in a new Alacritty window using `$EDITOR`
- Open Folder in Alacritty: opens an Alacritty window at the selected Finder folder
- Run Command from Clipboard: runs the current clipboard content as a shell command
- Run Command from Selection: runs the currently selected text as a shell command

The extension should work out-of-the-box for users with a standard Alacritty installation (i.e. an `Alacritty.app` bundle in `/Applications`) but also provides configuration.

## Screencast

Edit file:

https://github.com/raycast/extensions/assets/54108223/8cf2b1d1-0965-45e4-912f-f0db8e461a01

Open folder:

https://github.com/raycast/extensions/assets/54108223/9273b406-d640-40e6-9e75-d13d927645d6

Run command from selection (same idea for clipboard):

https://github.com/raycast/extensions/assets/54108223/46135598-9dfc-4703-803a-52f7ba18d11f

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jose-elias-alvarez** [comment]
This is my first time working with the Raycast API, and I'm having an issue adding a message to a [Toast](https://developers.raycast.com/api-reference/feedback/toast). It works as expected as long as the main Raycast window stays focused:

Screenshot 2023-07-12 at 5 53 11 PM

But if the Raycast window becomes unfocused as a result of the command, I get a popup, but it doesn't include the specified message:

Screenshot 2023-07-12 at 5 53 28 PM

This is a problem for the extension, since messages thrown by Alacritty (e.g. if the specified shell isn't executable) are caught but not shown to the user.

I tried searching through issues and wasn't able to find anything. Is this expected behavior? If so, is there a recommended workaround? I could use a [HUD](https://developers.raycast.com/api-reference/feedback/hud), but it doesn't have styling and doesn't show as much of the message.

**Comment by mil3na** [comment]
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

The HUD will show up when the error would close the Raycast window and the user would not have the chance to see it. I think it is fine the way it is. My only concern about your PR is the quality of your icon. It looks stretched out and not so good on the app. Do you mind taking a look at that?

**Review by mil3na — APPROVED** [review]
Usually these small changes on icon quality makes a difference for retina screens. Just keep it mind, maybe for a future update? I'm approving the PR :D

**Comment by jose-elias-alvarez** [comment]
Thanks! I've got some ideas for future improvements so I'll also look into the icon issue once I'm ready to put in a follow-up.

**Pull request merged**
