### PR TITLE
[MapleStory.gg] Use WebP icon

### PR DESCRIPTION
**Pull request by LitoMore**
## Description

This pull request is similar to #13545. I changed my extension icon from PNG to WebP. This can save some disk spaces for users.

I also want to try if this can work properly. Which means we can convert all extension icons from PNG to WebP to get a better performance.

This CI fails. The linting part from Ray CLI seems not open-source. So I can't help to update it.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi! Your extension is currently not passing all the checks. I will mark it as a draft. Please, mark as "Ready for review" as soon as you fix it :)
Cheers!

**Comment by LitoMore** [comment]
@mil3na As I mentioned in decription, I can't fix this since the error is from Ray CLI. I just want to let your team notice the WebP stuff so I created this PR.

I am looking forward to the WebP support for icons and metadata screenshots.

**Comment by mil3na** [comment]
To be fair , I don't think this change would be necessary. Icons are already super small and you wouldn't see much change on only one icon. @pernielsentikaer what do you think?

**Comment by mil3na** [comment]
Are you having performance issues on loading icon images?

**Comment by LitoMore** [comment]
I noticed that your web store display page has processed the images into WebP before displaying them. If we use WebP directly in the source files, it can also save you the work in this regard.

**Comment by mil3na** [comment]
It will not make the repo smaller tho, because Git stores history. So it would be even worse, having those 2 image formats.
This concerns more the app than the website. I understand when optimising for the website, but for the extension which will be bundled and so on, I don't think that a few hundred KB will make any difference.

**Comment by LitoMore** [comment]
Now you have the opportunity to slow down its growth, isn't it good?

Whether to use WebP depends on you. For me, hundreds of KB is not a small number, and it has a lot of space for optimization.

Thank you for your reply. Let's see what other members think about this topic.

**Comment by pernielsentikaer** [comment]
I agree that it might be something we'll look into in the future, but for now, we're not ready for it since I'm pretty sure that AppKit on `macOS 12 Mojave` doesn't support `.webp` out of the box, which would be the preferred way without the need for custom code. As soon as it's fully supported, it makes sense to allow that.

As stated earlier, it doesn't make the repository smaller if you clone it directly since it's in the history, but shallow cloning does, of course.

Does it make sense, @LitoMore? So, it's more of a "not right now" than a decline

**Comment by LitoMore** [comment]
@pernielsentikaer Agree!

**Comment by pernielsentikaer** [comment]
Thanks for your understanding, let's circle back to this as soon as possible 🙂

**Pull request closed without merging**
