### PR TITLE
Add wordpress-directory extension

### PR DESCRIPTION
**Pull request by oberonlai**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by oberonlai** [comment]
Hi there, I am a WordPress plugin developer and a big fan of Raycast. I always need search plugins for reference. So, I have created an extension specifically for searching WordPress plugins. You can use keywords to search and obtain detailed information about the plugins. Additionally, I have integrated a third-party service to facilitate quick plugin testing. I hope you enjoy it!

**Comment by pernielsentikaer** [comment]
Hi @oberonlai 👋 

Thanks for your contribution, did you see [this extension](https://www.raycast.com/edmundcwm/wordpress-plugins) by @edmundcwm - it seems very similar

**Comment by oberonlai** [comment]
Hi @pernielsentikaer 

I have seen another WordPress plugin extension in Raycast store. I can understand if you wouldn't merge my version. You could close this PR.

**Comment by pernielsentikaer** [comment]
It doesn't make sense to have two almost identical extensions in the store, but you might have some improvements to the other extension that would enhance it.

**Pull request closed without merging**
