### PR TITLE
Add Capture Raycast Metadata extension

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

Capture a screenshot for Raycast extension's metadata.

- **Capture Raycast Metadata**: Capture a screenshot for Raycast Extension's metadata.

**Tips**: 🌟🌟🌟How to use **Capture Raycast Metadata**:

- Set a shortcut for this command, open Raycast, and run the command with the shortcut to take a screenshot. Screenshots will be saved in the Download directory.
- Please keep the Raycast main window visible
- Please close other Raycast windows, such as the Preferences window

**Warning**: ⚠️⚠️⚠️This extension currently only works properly in some resolutions

- It works fine when the actual resolution(Resolution) is two times the view resolution(UI Looks like). You can check the monitor screen information by typing `/usr/sbin/system_profiler SPDisplaysDataType` command in terminal.
- Devices confirmed to work properly: MacBook Pro 2019 13' built-in display, external 4K display (Resolution: 3840 x 2160,UI Looks like: 1920 x 1080).
- If the image size becomes 1000x625, please adjust the screen resolution in the system settings and then try to capture a screenshot. Or you can enlarge it twice in the preview or other app.

Here is the sample output of `/usr/sbin/system_profiler SPDisplaysDataType`, where **Resolution** and **UI Looks like** are the ones to watch
```
      Displays:
        Color LCD:
          Display Type: Built-In Retina LCD
          Resolution: 2560 x 1600 Retina
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Mirror: On
          Mirror Status: Hardware Mirror
          Online: Yes
          Automatically Adjust Brightness: Yes
          Connection Type: Internal
        LG HDR 4K:
          Resolution: 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition)
          UI Looks like: 1920 x 1080 @ 60.00Hz
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Main Display: Yes
          Mirror: On
          Mirror Status: Master Mirror
          Online: Yes
          Rotation: Supported
          Connection Type: Thunderbolt/DisplayPort
```

**Preferences**

- _Screenshot Name_: Default is Metadata
- _Screenshot Format_:
  - PNG
  - JPEG
  - PDF
  - TIFF

## Screencast

Metadata

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Aayush9029** [comment]
@koinzhang Amazing Extension! *this will remove tons of friction*

However it doesn't seem to be working on my end!

CleanShot 2022-04-11 at 10 38 48


> Screen Resolution: (1920 x 1080) 
> 
> MacOS Version: 12.3.1

**Comment by koinzhang** [comment]
> @koinzhang Amazing Extension! _this will remove tons of friction_
> 
> However it doesn't seem to be working on my end!
> 
> CleanShot 2022-04-11 at 10 38 48
> 
> > Screen Resolution: (1920 x 1080)
> > MacOS Version: 12.3.1

Hi, @Aayush9029 Thanks for the testing!
 I'm an idiot, I submitted the PR without extensive testing, I will now try to fix the problem.
But since I'm busy until the 20th, I may not be able to fix it quickly in the meantime, so I'll change the pr to draft first.

**Comment by koinzhang** [comment]
Hi @Aayush9029 
I have updated the extension, can you please test it to see if it works on your device?
If it still doesn't work, can you give me your device model information, monitor information?

It works fine on MacBook Pro 2019 13' built-in display or external 4K display (Resolution: 3840 x 2160,UI Looks like: 1920 x 1080). You can check the monitor screen information by typing `/usr/sbin/system_profiler SPDisplaysDataType` command in terminal.

**Comment by Aayush9029** [comment]
@koinzhang Great Job! 🎉  Here's the final output:

CleanShot 2022-04-12 at 13 48 39

**Note the size is smaller but that is expected**: *I'm wondering if we'll need to resize it later? so it's 2000 x 1250*

**Comment by koinzhang** [comment]
> @koinzhang Great Job! 🎉 Here's the final output:
> 
> CleanShot 2022-04-12 at 13 48 39
> 
> **Note the size is smaller but that is expected**: _I'm wondering if we'll need to resize it later? so it's 2000 x 1250_

Hi @Aayush9029, Thanks for the test.
It has to do with your screen resolution.
You can adjust the screen resolution to a different scaling in the system settings and try capturing the screenshot again.

**Comment by josmithua** [comment]
You could calculate the pixel ratio (scaling factor) by getting the resolution from `system_profiler SPDisplaysDataType` and then dividing the result by the `bounds of the window of the desktop`

**Comment by josmithua** [comment]
This works:

```applescript
set screenWidth to 2nd item of words of (do shell script "system_profiler SPDisplaysDataType | grep 'Resolution:'")

tell application "Finder" to get bounds of window of desktop
set scaledWidth to 3rd item of result

set scaleFactor to (screenWidth / scaledWidth)

**Comment by koinzhang** [comment]
Hi, @josmithua. Thanks for the advice.
Your advice is important. I will try to use it, but I can't guarantee that it will eventually solve the problem

**Comment by koinzhang** [comment]
> This works:
> 
> ```applescript
> set screenWidth to 2nd item of words of (do shell script "system_profiler SPDisplaysDataType | grep 'Resolution:'")
> 
> tell application "Finder" to get bounds of window of desktop
> set scaledWidth to 3rd item of result
> 
> set scaleFactor to (screenWidth / scaledWidth)
> ```

I performed a test, but this value did not help me.
In fact, I now calculate the scaling using the actual width of the Raycast (which seems to be fixed at 750) and the width required by Metadata (1500), and the scaling is basically 2.

But this scaling will fail when the actual pixels are equal to the View pixels (bounds of window of desktop), resulting in a 1000*625 image.
This is because Screencapture takes screenshots based on View pixels. When the actual pixels are equal to the View pixels, the Raycast will always be cut to 750x450, plus the border which is 1000x625.

**Comment by josmithua** [comment]
Yeah sorry I didn't completely understand the issue. Your current solution looks good. One thing I would suggest is using some constants :). Something like

```
const SCREENSHOT_WIDTH_PX = 2000;
const SCREENSHOT_HEIGHT_PX = 1250;
const SCREENSHOT_PADDING_X_PX = 250;
const SCREENSHOT_PADDING_Y_PX = 150;
const DESIRED_RAYCAST_WIDTH_IN_SCREENSHOT_PX = SCREENSHOT_WIDTH_PX - SCREENSHOT_PADDING_X_PX * 2;
```

**Comment by koinzhang** [comment]
> Yeah sorry I didn't completely understand the issue. Your current solution looks good. One thing I would suggest is using some constants :). Something like

Hi, @josmithua Thanks for the suggestion, I've submitted Commit for the change.

**Pull request merged**
