### PR TITLE
Add chrome-profile-switcher extension

### PR DESCRIPTION
**Pull request by onurcagan**
## Description

Adding a new extension.

1. Pulls available profiles from Google Chrome, 
2. Once you select a profile it creates a new window with that profile if there are no active windows with that profile,
3. If you already had an active window using that profile, switches to that window instead of opening a new one,
4. Closes the Raycast window using `closeMainWindow` to provide a seamless user experience.

## Screencast

image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by onurcagan** [comment]
[This issue](https://github.com/raycast/extensions/issues/15528#issuecomment-2500131677) was the problem I and seemingly others were facing. Existing solutions have their caveats so I quickly put together an extension. Lmk if I'm missing anything.

**Comment by pernielsentikaer** [comment]
Did you see [this extension](https://www.raycast.com/frouo/google-chrome-profiles) before creating this, it seems similar to each other?

**Comment by pernielsentikaer** [comment]
So the issue is that the current one opens a new tab and you want it not to?

**Comment by onurcagan** [comment]
Correct, it asks you to choose a webpage to open a new tab in that profile you chose to switch to. There's another profile switcher app in the store, [this one](https://www.raycast.com/skydiver/browsers-profiles) and it does a similar thing, instead of opening a selected website in a new tab, it just opens a new window in that profile you selected. Neither achieving what we want.

**Comment by pernielsentikaer** [comment]
What about adding a preference to one of them and enhancing it? Do you need my help to talk to the authors? It would be better not to add a third one😊

**Comment by onurcagan** [comment]
I'm not sure how I'd go about doing that, and I just lack the time to dive into their code and find out how it'd be done. But I understand why you'd not want multiple extensions doing similar things. We can close the PR, thank you for your time.

**Comment by pernielsentikaer** [comment]
Let's submit a feature request for the most suitable extension, so either I or another community member can help

**Pull request closed without merging**
