### PR TITLE
Add Apple Music extension

### PR DESCRIPTION
**Pull request by gbougakov**
## Description

An extension that allows you to explore the Apple Music catalog. Pairs nicely with the [Music](https://www.raycast.com/fedevitaledev/music) extension. Please see the README.md for more info — it goes into detail about the features and has screenshots :)

### Why a separate extension and not contribute to [Music](https://www.raycast.com/fedevitaledev/music)?
There's a really fitting [paragraph](https://github.com/raycast/extensions/blob/main/docs/basics/prepare-an-extension-for-store.md#contributing-to-existing-extensions-vs-creating-a-new-one) in the docs about this.

> One extension could be "Spotify Controls" and only uses AppleScript to play/pause songs, while another extension can provide deeper integration via the API and require an access token setup.

In this case, the "Spotify Controls" extension is the [Music](https://www.raycast.com/fedevitaledev/music) extension and the one with deeper integration via the API is this one. 

Also, the Music app and Apple Music are two different things. You can access the Apple Music catalog via the Music app, but you can also use the Music app with your own files — in which case, you will only need the functionality of the [Music](https://www.raycast.com/fedevitaledev/music) extension.

### How is user authentication and access to the Apple Music API handled?
When you open the extension, it calls a Cloudflare Worker ([source code](https://github.com/gbougakov/raycast-music-login/blob/219e2c68f7b296a3e4fc13fb4f26647bde05e26e/src/index.ts#L17)) to get a developer token, which allows the extension to access the Apple Music API directly.

If you want to use any features that require authentication, you are redirected to the above-mentioned Cloudflare Worker. You click the big rounded button, and get redirected to idmsa.apple.com where you log in with your Apple ID and get redirected back to the extension. 

**Your credentials are never seen by the extension or the Cloudflare Worker because you enter them on apple.com. Your access token is never seen by the Cloudflare Worker because user authentication is handled fully client-side.**

## Screencast

https://user-images.githubusercontent.com/11464592/227634490-a0e780b5-c94a-4220-8546-43b3eb8244fb.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Seems like a nice extension for sure, and it doesn't make sense to add it to @Rawnly's `Music` extension.

((I think we're looking into only having one Spotify extension too since it's more confusion))

**Comment by Rawnly** [comment]
I was literally working on the same thing yesterday evening! 

I would love to see a PR to add this to the music extension. If you'd like any help, feel free to ping me on Slack at fedevitaledev, or Twitter (same handle) ✌️

My plan is to fully replace the AppleScript core functions with music kit where possible

**Comment by gbougakov** [comment]
@Rawnly I actually think that it is great that your extension uses AppleScript — because of that

- It works offline
- It works even if the user does not have an Apple Music subscription and only uses Music.app as a player for their own files
- It does not require authentication

And also, I'm pretty sure that most of the functionality of your extension can't be replicated with the Apple Music API, the only way would be to build a companion app (or just a binary, if possible) that would use [Apple MusicKit](https://developer.apple.com/documentation/MusicKit/) to locally control the Music.app

CleanShot 2023-03-31 at 11 44 55@2x

**Comment by Rawnly** [comment]
I think that we can mix music kit and AppleScript for the best UX, I had problems with library related stuff, it has a lot of workarounds and I'd love to use some more stable api 😅

https://github.com/raycast/extensions/issues?q=is:issue+is:open+sort:updated-desc+label:%22extension:+music%22

E.g #4145 - #4300 - #4994 etc

As you can see AppleScript is good for simple operations but once you get a bit deeper is kinda hell 🥲

**Comment by Rawnly** [comment]
https://github.com/raycast/extensions/blob/776613103967beed7b38738b4cd5de95d44d2631/extensions/music/src/util/scripts/current-track.ts#L15-L25

In this case I had to add fallback script in order to make "add to library" works with every localisation and edge case :/

**Comment by peterdev22** [comment]
This looks great, a perfect addition to Raycast's Apple music support! 😄

**Comment by rayan1812109** [comment]
"MusConv makes it so easy to move your music library between different services, whether you're switching to a new platform or just backing up your tracks. Highly recommend: http://www.musconv.com/ #musicmigration #musictool #musconv"

**Comment by pernielsentikaer** [comment]
I'm a bit confused about this, what's the status? Did you come to an agreement with @Rawnly

**Comment by Rawnly** [comment]
@pernielsentikaer yes! I'm implementing those features in the new version of the music extensions. It's taking me a while I'm kinda busy with work in this period 🥲

**Comment by pernielsentikaer** [comment]
And what about @gbougakov - what do you think about having it in the extension @Rawnly made?

**Comment by gbougakov** [comment]
While I think that it is essential for Raycast to have an extension that allows offline local-only control, I have talked with Federico, and agree that his extension can be greatly improved by using the Apple Music API instead of the AppleScript hacks, so the main distinction between mine and his extension (that Federico's extension is offline-only, while mine interacts only with the Apple Music catalog) will somewhat go away. So, if Federico does end up adding more Apple Music API-specific features, it does make sense to merge our extensions. 

Right now, however, our extensions provide very distinct feature sets that compliment the other extension quite well, so I think it would be great if you approved this extension in the meantime, and when Federico adds more Apple Music specific features, we can work together to merge our extensions.

**Comment by pernielsentikaer** [comment]
It's just impossible to "migrate" users from one extension to another - so we might end up with two pretty similar extensions in the end, or?

Could you both give me your take?

**Comment by Rawnly** [comment]
I think that my update will be ready by the end of next week. If it's ok for u all, I'd say to wait and see. If some features are missing is always possibile to open a new PR and contribute :)

**Comment by gbougakov** [comment]
Okay then, seems reasonable to me— George B.On 28 Apr 2023, at 14:09, Federico ***@***.***> wrote:﻿
I think that my update will be ready by the end of next week. If it's ok for u all, I'd say to wait and see. If some features are missing is always possibile to open a new PR and contribute :)

**Comment by gbougakov** [comment]
Hey, just remembered about this randomly, are there any updates? @rawnly 

just wondering if I should revive my version or not, because I'd love to use it personally

**Comment by rawnly** [comment]
Hey, you can try revive for sure, i'm not a music user anymore, so my extension right now is mostly maintainance. 

I tried making a v2 a year ago with the music kit api and oauth, then Raycast team asked me to develop a server integration but i didn't had the time to continue it

**Pull request closed without merging**
