### PR TITLE
Update ssh-manager extension

### PR DESCRIPTION
**Pull request by solid-pixel**
## Description

- SSH Config Parsing: Fixed a bug where wildcard entries like `Host *` defined in `~/.ssh/config` would show up as connections.
- SSH Config Parsing: Fixed a bug where RemoteCommand in SSH configurations was incorrectly parsed, leading to incomplete commands being sent to the terminal. Previously, commands containing spaces were truncated at the first space, resulting in incomplete execution (e.g., a command like cd /path && do_something was shortened to just cd). The parsing logic has been updated to correctly handle spaces within RemoteCommand values, ensuring that the entire command is read and executed as intended.

## Before:
image

## After:
image

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@scopsy do you mind checking this 🔥

**Comment by pernielsentikaer** [comment]
@solid-pixel do you mind fixing the merge conflicts here

**Comment by solid-pixel** [comment]
> @solid-pixel do you mind fixing the merge conflicts here

done, but please test it if you can as I'm on a long trip with very little time and I've only fixed it from the web editor without testing it on my machine (though the resolution was pretty obvious and I don't think it would break anything, but just to make sure..)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
