### PR TITLE
Add snapask extension

### PR DESCRIPTION
**Pull request by renzo4web**
## Description

SnapAsk is a lightweight Raycast extension designed for quick AI-powered information retrieval and problem-solving. Key features include:

- Instant access to AI responses through Raycast
- Configurable to work with any OpenAI API-compatible LLM
- Customizable API endpoint and model selection
- Minimal setup required: just add an API key and start asking questions

This extension aims to streamline the process of getting quick answers, making it an efficient tool for developers and tech professionals who need rapid information access without leaving their workflow.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
- When using the extension for the first time I was not sure which API key I should enter and it felt a bit weird to me - I'm not sure if others will have to check the code what it does? I understand that it works for multiple LLMs - but maybe it's better suited for one?

I guess most would probably just use https://www.raycast.com/abielzulio/chatgpt

**Comment by renzo4web** [comment]
> * When using the extension for the first time I was not sure which API key I should enter and it felt a bit weird to me - I'm not sure if others will have to check the code what it does? I understand that it works for multiple LLMs - but maybe it's better suited for one?
> 
> I guess most would probably just use https://www.raycast.com/abielzulio/chatgpt

Thank you for your feedback and for highlighting the ChatGPT extension. While that tool is useful for OpenAI-specific interactions, our extension offers broader compatibility.
Our design allows it to work with multiple LLM providers, not just OpenAI. A key feature is the ability to customize the base URL, enabling users to connect with various AI services that follow the OpenAI-compatible API standard. This includes providers like Anthropic, OpenRouter,DeepSeek,Groq, and even self-hosted models.
The flexibility in API key and base URL settings ensures adaptability to new LLM providers without requiring frequent updates. While this may seem less straightforward initially, it provides users with more choices and future-proofs the extension.

**Comment by pernielsentikaer** [comment]
Then what about [PromptLab](https://www.raycast.com/HelloImSteven/promptlab), it can also have custom endpoints afaik?

**Comment by renzo4web** [comment]
> Then what about [PromptLab](https://www.raycast.com/HelloImSteven/promptlab), it can also have custom endpoints afaik?

While both extensions offer customization options, they're designed for different needs and workflows.
My extension focuses on quick, simple queries (one-shot), ideal for users needing immediate answers without complex setups. I'm centering on simplicity and speed for everyday questions.
PromptLab, on the other hand, offers more advanced features, suited for users requiring detailed prompt engineering and multi-step interactions.
I believe there's room for both approaches in the Raycast ecosystem, serving different preferences and use cases. My aim is to complement, not compete with, more comprehensive tools like PromptLab.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
