### PR TITLE
Add get-path extension

### PR DESCRIPTION
**Pull request by nguyenvanduocit**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Thanks for your contribution 🔥 Did you see [this extension](https://www.raycast.com/koinzhang/copy-path) before creating this one?

**Comment by nguyenvanduocit** [comment]
i saw it right after submitting the ext, but i think it is good to have
multiple ext for that.

**Comment by pernielsentikaer** [comment]
If they do exactly the same it only confuses the end user to have multiple extensions doing the same purpose - if you have something in yours it might be better to enhance the current extension instead 🙂

**Comment by nguyenvanduocit** [comment]
I think it is exactly the same. no enhance.

**Comment by pernielsentikaer** [comment]
Closing as dublicate

**Comment by nguyenvanduocit** [comment]
I believe that Raycast should allow users to describe the extensions they want to use, rather than imposing the team's opinion. If duplicate extensions are not allowed, there will be no competition, which will make it difficult for the platform to grow.

For example, let's say I create a small extension that is later rejected. If the extension had been approved, I would have had the opportunity to improve it over time by adding new features. This would have made my extension better and different from other extensions, which would have forced them to adapt. However, since my extension was rejected, I have no incentive to improve it.

I think this is a shortsighted approach. By allowing users to create and use the extensions they want, Raycast can create a more vibrant and competitive ecosystem. This will benefit everyone, including the platform itself.

**Pull request closed without merging**
