### PR TITLE
feat: add screenshot OCR translate command

### PR DESCRIPTION
**Pull request by tisfeng**
### ✨ New Features

- Added OCR screenshot translation command, thanks to [aidevjoe](https://github.com/aidevjoe)'s PR https://github.com/tisfeng/Raycast-Easydict/pull/41

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @tisfeng 👋 

We can't guarantee that the end user has Xcode installed so you should instead compile it into a binary package, you can see how it's done in [this extensions](https://www.raycast.com/thomas/color-picker)

**Comment by tisfeng** [comment]
OK, thanks for your reminder, I hadn't thought about that.

**Comment by pernielsentikaer** [comment]
Could you add the same structure as the mentioned PR so I'm able to build from package.json too? 🙂

**Comment by tisfeng** [comment]
Thank you for your guidance, sorry, I am an amateur JS, not too familiar with the development environment, I did what you said, do you see any other problems?

**Comment by tisfeng** [comment]
@pernielsentikaer  No problem, thanks for the Review, I forgot to remove the extra code.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
