### PR TITLE
[One Thing]: Add preferences to the extension

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

- Add optional prefix and suffix preferences to prepend or append to the one thing (e.g emojis)
- Add a preference to close Raycast's window defaulting to `true`
- Set the one thing text field to use by default the cached value

## Screencast

CleanShot 2022-11-18 at 11 20 16@2x

https://user-images.githubusercontent.com/16003285/202679536-aa540722-c937-4e7f-9825-d10f2750694b.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folded

### CODE REVIEW

**Comment by thomaslombart** [comment]
There's one annoying bug with the preferences: the menu bar command is re-launched after each modification in the preferences which triggers the `Set One Thing` command (as clicking on the menu bar launches this command)

https://user-images.githubusercontent.com/16003285/202680069-9902bb08-7fa9-4be1-967c-25e430bbc616.mp4

**Review by mathieudutour — APPROVED** [review]

**Comment by pernielsentikaer** [comment]
Both ways work for me; I like the first since it keeps it simple - do you have a solution for that?

If everything goes wrong, then solution 2 works too, which is also nice 😁

**Comment by mathieudutour** [comment]
@sxn do you think we could do something like that? Perhaps launch the menu bar in background mode if supported?

**Comment by sxn** [comment]
It could make sense to launch the command with launchType `background` if it's supported, yeah.
Regardless of that, if `MenuBarExtra` had an `onAction`, we could differentiate between these two situations, and the `MenuItem` component wouldn't be necessary… 🤔

**Comment by thomaslombart** [comment]
Yeah, `onAction` on `MenuBarExtra` would work as well. It makes also more sense from a DX point of view in my opinion.

**Comment by pernielsentikaer** [comment]
So what are we going with? 😊

**Comment by pernielsentikaer** [comment]
Is this ready @thomaslombart

**Comment by thomaslombart** [comment]
The bug is still there and still pending for a solution on the Raycast API, so not ready at the moment 😊

**Pull request closed without merging**
