### PR TITLE
feat(power-management): add extension

### PR DESCRIPTION
**Pull request by erics118**
## Description

redo of #9873 by @sasivarnan

An extension to toggle the Power Management settings of the macOS without fiddling around the ever-changing macOS settings.

Commands available

1. Toggle Low Power Mode

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I don't have such thing in as `lowpowermode` in `Sonoma`

Raycast14022024-FJ5sLz0e png@2x

**Comment by erics118** [comment]
It still errors? The code should be `grep` ing for `powermode` to first determine the correct. I've removed some more unnecessary logic that should make it work better.

**Comment by pernielsentikaer** [comment]
Could you look into the CI errors so I can give it another spin 🙂

**Comment by erics118** [comment]
CI errors fixed. Turns out I didn't sparse checkout properly, leaving an old file present 😅

**Review by pernielsentikaer — APPROVED** [review]

**Comment by h-bernardo** [comment]
Hey! Great job! i though I was the only one struggling with this!
Is there a way to not have to always approve the change with user password?

**Comment by erics118** [comment]
I won't add this to the extension, but if you were to add
```sh
{username} ALL=(root) NOPASSWD: /usr/bin/pmset -a powermode 0
{username} ALL=(root) NOPASSWD: /usr/bin/pmset -a powermode 1
{username} ALL=(root) NOPASSWD: /usr/bin/pmset -a powermode 2
```
where `{username}` is your username, to `/etc/sudoers.d/pmset`

And change line 27 of `powerManagement.tsx` from
```js
await runAppleScript(`do shell script "pmset -a powermode ${value}" with administrator privileges`);
```
to
```js
execSync(`sudo /usr/bin/pmset -a powermode ${value}`);
```

You can toggle low power mode without needing your password.

**Comment by Cassius0924** [comment]
> And change line 27 of `powerManagement.tsx` from

Where can I find this file `powerManagement.tsx` ?

The extra step of entering the password is too inconvenient for me.

**Pull request merged**
