### PR TITLE
Add initial Brave extension

### PR DESCRIPTION
**Pull request by ron-myers**
## Description

Adds an extension for the [Brave browser](https://brave.com/).

The initial commands are:

* Search Brave Tabs
* Search Brave History
* New Brave Tab

Based on the [google-chrome extension](https://www.raycast.com/Codely/google-chrome)

## Screencast

https://user-images.githubusercontent.com/10678906/153683651-dedafdb0-f40e-4713-be11-d5e3222777a6.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by s-r-aman** [comment]
Hey @ron-myers, Looks awesome. Amazing work! Can you please clarify if it also supports profile management?

**Comment by ron-myers** [comment]
Thanks @s-r-aman - most of the work is based on the [Google Chrome extension](https://www.raycast.com/Codely/google-chrome).  So shout out to the maintainers of that extension.

No profile support currently.  Could be added - for the Google extension this is a separate extension.  For Brave - I think I would prefer to maintain one extension with support for everything Brave related.

**Review by pernielsentikaer — COMMENTED** [review]
Hi @ron-myers 👋 

Just a quick question, should all commands open in Brave? Tried `New Brave Tab` and it opens in Chrome, is that how it supposed to be?

**Comment by ron-myers** [comment]
Hey @pernielsentikaer !! 

`New Brave Tab` should always open Brave.   The phrase `Chrome` doesn't exist in the extensions codebase.

After reviewing the code for ways this could happen, there are two calls to `OpenInBrowserAction` within the extension.  My thought is Chrome is your default browser and when you use the `Recently Close` list it opens in your default browser(Chrome).

I will remove the calls to `OpenInBrowserAction` and back-port the change into the Chrome extension.

I confirmed this with the `New Tab`, under the `recently closed` section, from the Chrome extension opens `Brave` on my machine where Brave is my default browser.

Since this is an existing issue, I will leave it to your discretion if we merge this now or wait for correction on the above.

**Comment by pernielsentikaer** [comment]
I would expect both `New Tab` commands to open a new tab with the right browser, the rest of the command could follow default browser. I'm not sure if it can help in any way, but in the latest API version, we added [appPicker](https://github.com/raycast/extensions/blob/main/examples/api-examples/package.json#L161-L168) - is that any help?

**Comment by pernielsentikaer** [comment]
Hi @ron-myers 👋 

Could you run Prettier, so the linter is happy? Let me know if you need any help 😄

**Comment by ron-myers** [comment]
Done.  😄 

That confused me for a minute @pernielsentikaer. Locally there were no errors, my version of `raycast/api` was out of date and needed an upgrade to get the same lint errors as on CI.  Adding a check for this may be worth considering.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks @ron-myers 🔥 

Much better, works as expected 👍 

Since you started this extension we have shipped `1.30.2` – It could be an idea to update, and see if there is anything that should be changed since a lot happened.

We're now adding support for [categories](https://developers.raycast.com/basics/prepare-an-extension-for-store#categories), [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) and [changelog](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) – do you have time for adding this too

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by ron-myers** [comment]
Meta data added @pernielsentikaer

**Pull request merged**
