### PR TITLE
Add ip-tools extension

### PR DESCRIPTION
**Pull request by meguoe**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Thanks for your contribution 🔥 

Did you see [this extension](https://www.raycast.com/Yansong/cidr) by @Yansongsongsong, it seems like their both pretty similar 🙂

**Comment by meguoe** [comment]
> Hi 👋
> 
> Thanks for your contribution 🔥
> 
> Did you see [this extension](https://www.raycast.com/Yansong/cidr) by @Yansongsongsong, it seems like their both pretty similar 🙂

Yes, I see this extension only provides a single CIDR to IP range conversion, while my extension is a toolkit that handles IPv4 and IPv6. The CIDR conversion is just one function of this toolkit. In addition, there are other functions like IP conversion to number, number conversion to IP, IPv4 conversion to IPv6, etc. You can check out the details in my [ip-toolkit](https://github.com/meguoe/ip-toolkit) project. Going forward, I will implement all the features from that Nodejs project in this extension.

**Comment by pernielsentikaer** [comment]
Wouldn't it make sense to have it in one extension, since the functionality overlaps with the current one?

**Comment by Yansongsongsong** [comment]
@meguoe hi there! so excited to see that you have such one great [ip-toolkit](https://github.com/meguoe/ip-toolkit) project.

if you dont mind. do you want merge these two extensions together?

**Comment by meguoe** [comment]
> Wouldn't it make sense to have it in one extension, since the functionality overlaps with the current one?

I think the positioning of the functions of these two plugins is not exactly the same. What I want to do is a toolkit extension specialized in handling IPs, but the CIDR plugin you mentioned only does simple CIDR conversion. Therefore, I think from the name, functions to future plans, these two plugins may not be suitable for simple merging.

**Comment by meguoe** [comment]
> [Yansongsongsong](/Yansongsongsong)



> @meguoe hi there! so excited to see that you have such one great [ip-toolkit](https://github.com/meguoe/ip-toolkit) project.
> 
> if you dont mind. do you want merge these two extensions together?

thank you for your recognition. the extension you published is also great, but I feel that the name of the extension you published has already limited the scope of the extension's functions. What I want to do is a toolkit specialized in handling IP addresses, it's not limited to parsing CIDR.

**Comment by pernielsentikaer** [comment]
I can see that it might be best to have it as a separate extension, thanks for the clarification @meguoe 🙂

**Comment by meguoe** [comment]
> I can see that it might be best to have it as a separate extension, thanks for the clarification @meguoe 🙂

🤝，Do you need me to do anything else?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by meguoe** [comment]
> Hi 👋
> 
> Looks good to me, approved 🔥
 
Thank you for your approval

**Pull request merged**
