### PR TITLE
add iTerm extension

### PR DESCRIPTION
**Pull request by ron-myers**
## Description

Adds an extension to control [iTerm](https://iterm2.com/)

## Screencast

https://user-images.githubusercontent.com/10678906/210175545-51ef021f-b97f-4f07-a478-5c18e3ba113c.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ron-myers 👋 

It might be a permission issue in my end but it would be nice if you could catch the error and die gracefully instead - I'll try to check my permissions 😊

Raycast-BERIl2Qj@2x

**Comment by ron-myers** [comment]
Hey @pernielsentikaer 👋 

I agree we should handle the permission error. 

To confirm what it is, I played around with my permissions and replicated the issue by changing this permission under Automation.  Can you confirm that is what breaks/fixes it for you? `Automation > Raycast > iTerm`  I will add an error screen to handle this scenario to this PR.

OnPaste 20230109-080257

**Comment by ron-myers** [comment]
Hey @pernielsentikaer 👋  - I added a permission screen when the required permission is unavailable.

Let me know if you have any additional feedback before merging.  😃

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ron-myers 👋 

I'm getting this screen now, is this supposed to look like this?

Raycast-k9SiRLKf@2x

**Comment by ron-myers** [comment]
Hey @pernielsentikaer 👋 , I was worried there was another permission we might hit for this.  Once we find out what it is, I can also add a check for that permission.

That screen means the tab creation failed. Can you copy the message at the bottom?  If not, I can update the screen to show the entire message.

Another permission is likely disabled under iTerm.  Can you check your permissions for
`Privacy & Security` > `Automation` > `iTerm` and let me know if any are unchecked.  My gut says it may be the `System Events` permission that would cause the error you are seeing.  

Thanks!

**Comment by pernielsentikaer** [comment]
I get this in a console if I try to run it
```
13:47:59.502 Error: Command failed with exit code 1: osascript -e 
  tell application "iTerm"
    activate
    repeat until application "iTerm" is running
      delay 0.1
    end repeat
    
    if windows of application "iTerm" is {} then
      create window with default profile
    end if
  
    activate
    tell application "iTerm" to tell the first window to create tab with default profile
    activate
  end tell 
166:168: execution error: Ikke godkendt til at sende Apple Events til iTerm. (-1743)
    at makeError (/Users/pernielsentikaer/.config/raycast/extensions/iterm/new-iterm-tab.js:1084:17)
    at handlePromise (/Users/pernielsentikaer/.config/raycast/extensions/iterm/new-iterm-tab.js:1847:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runAppleScript (/Users/pernielsentikaer/.config/raycast/extensions/iterm/new-iterm-tab.js:1994:22) {
  shortMessage: 'Command failed with exit code 1: osascript -e \n' +
    '  tell application "iTerm"\n' +
    '    acti<…>
```

I only have this permission inside macOS

Raycast-ZfkwwIIN@2x

**Comment by ron-myers** [comment]
@pernielsentikaer - I updated the permission check to use a portion of the message that is always English.  :)

**Comment by pernielsentikaer** [comment]
It was also just an accident; I had the language in Danish, and I had to test something about localization 😊

Works as expected now 💣

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
