### PR TITLE
[Bitwarden] Reorganize and cleanup codebase

### PR DESCRIPTION
**Pull request by jomifepe**
### Why?
1. The current code organization is a bit all over the place
2. In order to more easily develop new features, I felt like the code needed more structure
3. Improved developer experience, ease of creating a new feature

### What was done
1. Separated the code into separate files and directories with meaningful names, reducing the size and complexity of each file
2. Reduced prop drilling in favor of context
4. Added TS import paths
5. Removed some unused/unnecessary code
6. Updated every dependency (because why not)
7. (The only feature, I guess) Added some more useful info (text) to the Troubleshooting Guide

### Tests
- [X] Overall `Search Vault` functionality, listing correctly, displaying images and folders, etc
- [X] Copying/displaying values (password, username, and all the other fields)
- [X] Generate password, changing the password generator options
- [X] Login, logout, lock, and vault sync
- [X] Reprompting password option
- Self-Hosted Server (Maybe @daniel-stoneuk can help here)

### I know this doesn't really make it justice, but here's a video of the main features working as expected. But if you can, please test it locally while reviewing the PR 🙏 

https://user-images.githubusercontent.com/7235666/222596279-ad46c12e-b179-47e3-be5a-b32606a3a2b3.mp4

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jomifepe** [comment]
Hey @pernielsentikaer, I see that the `Extensions / Check` action is failing because I change the file name of the entry point for the `search` command. It builds fine on my machine, am I not able to change the name of this file?

**Comment by jomifepe** [comment]
@pomdtr @eth-p @daniel-stoneuk If you have the time, mind taking a look at the code? 🙂

**Comment by pomdtr** [comment]
This was badely needed, thanks for you work!

**Comment by pernielsentikaer** [comment]
Hi @jomifepe 👋 

Seems like it was a minor error in one of the files, I corrected the error now 😊

Do you mind that we keep the current names for the two commands defined in `package.json` so users don't lose there rank/alias/hotkeys?

**Comment by jomifepe** [comment]
> Hi @jomifepe 👋
> 
> Seems like it was a minor error in one of the files, I corrected the error now 😊
> 
> Do you mind that we keep the current names for the two commands defined in `package.json` so users don't lose there rank/alias/hotkeys?

Hey, thank you! For some reason those changes weren't pushed. Are you referring to the file name of the commands? (`search.tsx` and `generatePassword.tsx`)

**Comment by pernielsentikaer** [comment]
Those two, if we keep the old one despite they might be a bit odd we keep all rank/aliases/hotkey that the user set up

Raycast-LqH2SdyQ@2x

**Comment by jomifepe** [comment]
> Those two, if we keep the old one despite they might be a bit odd we keep all rank/aliases/hotkey that the user set up
> 
> Raycast-LqH2SdyQ@2x

No worries, I was wondering it was a good idea to change them. I'm gonna change them back.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
