### PR TITLE
[Todoist] Today's Frog

### PR DESCRIPTION
**Pull request by aromeronavia**
## Description
Added a Menu Bar Command to display Today's Frog, which means the most important task you need to finish Today.
How I implemented it:
1. Added a Preferences Variable to set the label that will filter Today's Frog (Defaulted to `frog`)
2. Added a Menu Bar Command to Package.json
3. Added a `today-frog.tsx` file with the logic to filter `today|overdue` tasks to identify if there's a frog, and if not, it will just display the first task in the list of Today's tasks

## Screencast

https://user-images.githubusercontent.com/13922607/188230644-f70b54df-cd42-4482-993e-71fc54c935bf.mov

## Checklist
- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaslombart** [comment]
Hey @aromeronavia, thanks for the contribution! 🎉 

It looks good to me except for the "frog" part which feels too opinionated to be part of the Todoist extension since the latter is designed to manage Todoist tasks in a generic way.

**Comment by aromeronavia** [comment]
Hey @thomaslombart! Appreciate you taking a look at this.

I wonder if we can swap Frog with "Focus"? `Today's Focus` would be the Command name, and we could replace the `Frog` tag with `Focus` one. I will do this change and will let you know when it's done

**Comment by aromeronavia** [comment]
@thomaslombart PR ready to review again 👍

**Review by thomaslombart — APPROVED** [review]
Sorry for the late review. It looks good to me 👍 

Maybe the last suggestion would be to rename the command `Today's Focus` to `Today's Tasks`. The focus part seems to be secondary here 🙂

**Comment by aromeronavia** [comment]
Hey @thomaslombart!

Sorry again for taking so long to respond. Regarding your comment, there is already a Today Tasks command in the extension, so I think it will be more confusing if we add `Today's Tasks`. Some proposals for naming:

- Focus Task
- Menu Bar Task
- Show Tasks in Menu Bar

**Comment by thomaslombart** [comment]
Not sure if it's that confusing since Raycast clearly indicates it's a menu bar command:

Here's an example with Google Workspace:
Raycast 2022-10-13 at 16 23 33

What do you think?

**Comment by thomaslombart** [comment]
It shouldn't be stale. @aromeronavia should I take back this PR?

**Comment by thomaslombart** [comment]
@aromeronavia There's another PR for the menu bar command that is packed with more features: https://github.com/raycast/extensions/pull/3597.

**Comment by aromeronavia** [comment]
I agree with closing this one in favor of the other PR, I actually like it more. I'm closing by now 👍

**Pull request closed without merging**
