### PR TITLE
New call function and improved number validation

### PR DESCRIPTION
**Pull request by chrismessina**
### Added

- Phone number validation function.
- Separate command to use selected text or clipboard content as phone number.

quick-call

### Changed

- Can now initiate phone call from main view.
- Upgraded dependencies.

### Fixed

- TypeError: Cannot read properties of undefined (reading 'replace')## Description

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @chrismessina 👋 

Thanks for the update 🔥 Can you move the update for google-maps-search out of this PR so our bot is happy 😂

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @chrismessina 👋 

Thanks for the update 🔥 Can you move the update for google-maps-search out of this PR so our bot is happy 😂

**Comment by chrismessina** [comment]
> Hi @chrismessina 👋
> 
> Thanks for the update 🔥 Can you move the update for google-maps-search out of this PR so our bot is happy 😂

When I attempt to discard those changes, I get an error. Can you help or provide me with some steps to remedy this issue? 

2024-08-13 (17 39 45) Arc

**Comment by pernielsentikaer** [comment]
I'll ask my colleague to remove it properly 🙂

**Comment by pernielsentikaer** [comment]
Did you know that the current command in `Quick Call` already supports selection and clipboard? Don't you think it should be enough with just one multi-purpose command?

**Comment by chrismessina** [comment]
> Did you know that the current command in `Quick Call` already supports selection and clipboard? Don't you think it should be enough with just one multi-purpose command?

I originally tried that approach, but couldn't figure out how to grab the selected text or clipboard, clean or validate it as a phone number, and then execute it with a `no-view` command.

I would prefer a single multi-purpose command so if you can point me to a `no-view` example that processes input from the selected text or clipboard, I can make the changes.

**Comment by pernielsentikaer** [comment]
Wrote you on slack 🙂

**Comment by pernielsentikaer** [comment]
Can you try the fork method we spoke about? Seems like you keep adding the old google-search files over and over again 🙂

**Pull request closed without merging**
