### PR TITLE
Update obsidian extension

### PR DESCRIPTION
**Pull request by rakoort**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Feel free to add the text you want in a comment, and I'll take care of it for you 🙂

**Comment by pernielsentikaer** [comment]
How did you add this PR? With the fork tool? If so, you can just edit, add and push again 🙂

**Comment by pernielsentikaer** [comment]
Maybe it would be an idea to make it a preference so the user can decide if he wants this change?

What do you think @KevinBatdorf

**Comment by KevinBatdorf** [comment]
Yeah since this would effect everyone making configurable is a good idea. 

Otherwise @rakoort could it be a template like is being used elsewhere?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
