### PR TITLE
Update api and Replicate name

### PR DESCRIPTION
**Pull request by KevinBatdorf**
## Description

This updates to the latest Raycast API, tweaks the Grid component, and makes a few cosmetic name changes.

cc: @bfirsh

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
Could you check on the Grid component for me? It doesn't seem to be persisting the value after exiting the extension and returning. It's probably staring right at me. Thanks.

**Comment by pernielsentikaer** [comment]
Should @bfirsh check the PR, or are you talking about me, @KevinBatdorf - sorry for the confusion 😊

**Comment by KevinBatdorf** [comment]
The grid comment was for you or the Raycast team :) I didn't want to just tag anyone outright as I wasn't sure who would be checking. 

bfirsh is at [Replicate](https://replicate.com/) (this extension interfaces with their API) and pointed out the naming change so I tagged them just to make them aware the change was PR'd here.

Anyone can look into the Grid component though who wants to :P

**Comment by KevinBatdorf** [comment]
@pernielsentikaer On Slack @mathieudutour noted the behavior above is a bug in Raycast, so I believe this PR is ok to go in at your convenience!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
