### PR TITLE
Add trakt-manager extension

### PR DESCRIPTION
**Pull request by thesobercoder**
## Description

Trakt Manager enables you to control your Trakt account directly from Raycast. It provides a set of commands to perform various actions on your account like adding shows to watchlist, checking-in on shows, and more. It allows you to sign in to your Trakt account using OAuth and then perform actions on your account.

## Screencast

CleanShot 2024-06-12 at 13 37 10

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The extension crashes If you try to run `Refresh` before authenticating is done

trakt-manager 2024-06-17 at 16 08 06

- Maybe add [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) and `style={Action.Style.Destructive}` to remove actions

- Use our [screenshot tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) to make the images of the extension

- What is backgorund.png for?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by thesobercoder** [comment]
Hi @pernielsentikaer,

Thank you for your feedback. I will fix the Refresh command, and publish the update soon.

> * Maybe add confirmAlert and style={Action.Style.Destructive} to remove actions

Can you please explain this a bit further? I'm not sure I understand where to put this.

> * Use our [screenshot tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) to make the images of the extension

Since I don't have a MacBook Pro and I use a Mac Studio with an LG external monitor. Whenever I try to take a screenshot with the Raycast screenshot tool, it never matches the screenshot dimensions required by the linter. For this reason, I had to, create a separate `background.png` file and manually place the screenshots within that background image using Pixelmator Pro. Last I checked, the linter was happy with the image that I created.

**Comment by pernielsentikaer** [comment]
Did you change anything with the oAuth, I can't connect and getting this error when returning to Raycast after allowing Trakt to use my account

trakt-manager 2024-06-19 at 11 57 56

```
11:57:43.300 
FetchError: request to https://trakt.tv/oauth/token failed, reason: connect ECONNREFUSED 127.0.0.1:9090

ClientRequest.<anonymous>:index.js:108:10

---
105:            };
106: 
107:            request_.on('error', error => {
108:                    reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error));
109:                    finalize();
110:            });
111: 
---

ClientRequest.emit:node:events:526:35
ClientRequest.emit:node:domain:488:12
index.js:2:38805
```

**Comment by thesobercoder** [comment]
> Did you change anything with the oAuth, I can't connect and getting this error when returning to Raycast after allowing Trakt to use my account

That is strange. I haven't pushed anything new to this PR. I was able to log in just fine. Tried it just now. Maybe something in your network is blocking the requests?

Anyway, I would really appreciate it if you can clarify my questions that I asked above. Thanks a ton!

**Comment by thesobercoder** [comment]
Hi @pernielsentikaer I have updated the PR addressing the Refresh command issues and also added some robust error handling for all possible situations. Please feel free to check and let me know what you think. Also, I have tested the login scenario multiple times, and it has not failed ever a single time. I'm not sure why yours isn't working. If you can ask someone else to try and let me know, might give me some insights.

**Comment by pernielsentikaer** [comment]
Seems like I had a network issue but it should be resolved now 🙂

Shouldn't I be able to see the two items in Watchlist? I tried to open the command a few times but it's always empty.

Raycast19062024-5PQ8JYzN png@2x

**Comment by thesobercoder** [comment]
> Seems like I had a network issue but it should be resolved now 🙂
> 
> Shouldn't I be able to see the two items in Watchlist? I tried to open the command a few times but it's always empty.
> 
> Raycast19062024-5PQ8JYzN png@2x

I think the problem is you are on the movie page and there are no movies added to your watchlist. What is even stranger is, I don't see the search bar accessory to select movies or shows. I hope your Raycast version is updated, not sure what else could go wrong here.

CleanShot 2024-06-19 at 20 16 03

**Comment by thesobercoder** [comment]
@pernielsentikaer I think I figured out the issue. Working on it.

**Comment by thesobercoder** [comment]
@pernielsentikaer I'm not sure what happened, but auth stopped working. It won't just go past the sign-in overlay screen in Raycast. I've been debugging it for the last 2 hours, but I'm unable to figure out why. What is strange is the `no-view` Refresh command is authenticating perfectly and working fine. I'm out of ideas at this point. Would really appreciate some help.

**Comment by rsefer** [comment]
@thesobercoder I have had similar issues since updating to 1.77 today (see here: https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1718820854528979)

**Comment by thesobercoder** [comment]
@pernielsentikaer Everything is working now after the 1.77.1 update. I did some refactoring to clean things up further. This is ready for your review.

**Comment by pernielsentikaer** [comment]
Is this ready for another review?

**Comment by thesobercoder** [comment]
@pernielsentikaer Please hold on. I'm switching all the commands to native pagination using the `useCachedPromise` hook. I will request for a new review when it's ready. Thanks!

**Comment by pernielsentikaer** [comment]
I'll convert it to a draft until 🙂

**Comment by thesobercoder** [comment]
@pernielsentikaer This is ready for your review.

**Comment by mil3na** [comment]
Hi! I saw that you added a few more commits. Is it ready for review now?

**Comment by thesobercoder** [comment]
@mil3na Yes it's ready. Sorry, found some last-minute improvements. 🙈

**Comment by mil3na** [comment]
Thank you so much for your contribution again. I have a few comments:

- Why is the Refresh command needed?
- The performance is not the best. There is a lot of blinking when showing cards for the items. I wonder if it would make sense gathering more than 10 items per request and waiting for the first batch of images before showing anything to the user (loading page in between is ok). What do you think?

**Comment by thesobercoder** [comment]
@mil3na Thanks for taking the time to review my code.

>  Why is the Refresh command needed?

The Refresh command is needed to calculate the shows that users are watching that are shown in the `Up Next` command, as there may be new episodes that have been released for a show, and the user has not watched them. This calculation, unfortunately, has to be done on the client side, as the Trakt API does not provide a way to retrieve this data directly from the API. The process involves getting every single show the user has watched, and then querying a different endpoint for the progress. If the number of episodes watched is less than the number of episodes released, then the show appears in the `Up Next` command. To avoid making the user wait for an extended period every time they open the `Up Next` command, the Refresh command is used to fetch the up-next shows in the background and cache the results.

> The performance is not the best. There is a lot of blinking when showing cards for the items. I wonder if it would make sense gathering more than 10 items per request and waiting for the first batch of images before showing anything to the user (loading page in between is ok). What do you think?

This is a much more challenging problem than I initially anticipated. I intentionally kept the image loading at the grid item level so that each item can fetch its own images when it loads. Batching 10 items might work, but it could be very difficult to orchestrate. I'm open to any ideas you might have on how to improve the process. On a separate note, once the image links are fetched the first time, they are cached to avoid performing a network call again.

**Comment by mil3na** [comment]
Hey! I don't believe this Refresh command should be needed. It should be transparent to the user. I would recommend drafting this extension and improving on performance/usage before submitting again. Our slack community might be a good place to ask for help: https://raycast.com/community

**Comment by thesobercoder** [comment]
> Hey! I don't believe this Refresh command should be needed. It should be transparent to the user. I would recommend drafting this extension and improving on performance/usage before submitting again. Our slack community might be a good place to ask for help: https://raycast.com/community

May I ask why you think the Refresh command is not needed? The Trakt API specifically mentions that any client using the API should calculate up next on client side. Also, it would be helpful if you can exactly state what "performance" improvements you are mentioning so that I can work on it. Is it only the images?

I will mark the PR as draft for now.

CleanShot 2024-07-03 at 18 30 13

https://trakt.docs.apiary.io/#reference/users/watchlist

**Comment by mil3na** [comment]
What I meant is that it shouldn't be needed from a UX point of view. The user should not need to refresh manually, it should be done automatically behind the scenes.

**Comment by thesobercoder** [comment]
> What I meant is that it shouldn't be needed from a UX point of view. The user should not need to refresh manually, it should be done automatically behind the scenes.

That is precisely what it does. It is configured to run in the background every 6 hours. I don't expect the user to run the command. I couldn't find any configuration option that hides that command from the user, which is why you're seeing it in the command list.

**Comment by thesobercoder** [comment]
@mil3na I've asked the community for help, but no one replied. I checked everything from my end and don't see any performance issues. The flickering is something that I don't believe actually causes any memory pressure or performance issues, which I have verified. I'm a bit out of ideas at this point on how to improve this perceived performance problem. If you still think my extension is not acceptable, I guess I will just go ahead and close the PR. I have been using React for a very long time (and have been a developer for 15 years), and I'm pretty pedantic about performance issues in general, but I'm out of ideas at this point. Please let me know your thoughts.

https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1720886607399709

**Comment by mil3na** [comment]
Hey! Sorry that no one answer your claim. The flickering is kind of a no-no for us, according to our internal guideline. Per will be back on Monday, I wonder if he has any better insight. I will get back to this then.

**Comment by thesobercoder** [comment]
@mil3na Thanks. I will wait for @pernielsentikaer's insight.

**Comment by pernielsentikaer** [comment]
Hi @thesobercoder 👋

I think we'll add it now and see if we can find ways to improve it in a later version 🙂

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
- Could you redo the [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension to use our tool instead 🙂

**Comment by thesobercoder** [comment]
Hi @pernielsentikaer,

The Raycast screenshot tool doesn't seem to work best for non-retina monitors. The reason I manually created those screenshots of desired sizes is because of this limitation. Please take a look at the image below.

CleanShot 2024-07-25 at 20 11 03

**Comment by pernielsentikaer** [comment]
Added a simple metadata image for now

**Pull request merged**
