### PR TITLE
[google-translate] Add details view.

### PR DESCRIPTION
**Pull request by metakirby5**
## Description

Add details view so the full text of translations can be previewed.

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by gebeto** [comment]
@metakirby5 You can also use `Translate Form` command, you can see more text there

also there is more useful key shortcuts like switch languages or you can easily change translatable language


translate 2022-07-06 at 16 00 03

**Comment by metakirby5** [comment]
@gebeto Thank you for the information about the shortcuts! I didn't know they existed.

I default to the `Translate Form` command because it works without further input whether I paste in English or Japanese (the languages I have set). 90% of the time the text fits on one line, and for the 10% of the time it doesn't, it's very convenient to drill in with one keystroke. So, it would be great if we could still merge in this feature 😄

**Comment by metakirby5** [comment]
@pernielsentikaer Hi! Since this PR is approved, are there any blockers to getting it merged?

**Review by pernielsentikaer — APPROVED** [review]
No I think we're good to go @metakirby5 🔥

**Pull request merged**
