### PR TITLE
New Extensions: ChatGPT

### PR DESCRIPTION
**Pull request by abielzulio**
## Description
A quick way to interact with the OpenAI's ChatGPT using their official API. This PR is the updated one from #3849. Three commands are available:

1. `Ask` →   Start a new conversation with ChatGPT by asking a question
2. `Conversations` →  Continue recent conversations without losing context
3.  `Models` → Collection of the user's default and custom models
4. `Saved Answer` → Collection of the user's saved question and its answer
5. `History`→  Collection of all the user's questions plus the answers

## Screencast

https://user-images.githubusercontent.com/7030944/224075479-d87ce1d4-ee93-458a-b9f8-8a20a11f10dd.mp4

(Sorry for the low video quality due to upload size limitation)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Would it make sense to enhance the [current extension in the store](https://www.raycast.com/simicvm/openai-gpt3) so we don't end up with too many of the same "thing" doing almost the same?

**Comment by abielzulio** [comment]
> Hi 👋 
> 
> 
> 
> Would it make sense to enhance the [current extension in the store](https://www.raycast.com/simicvm/openai-gpt3) so we don't end up with too many of the same "thing" doing almost the same?

Hi!

I think this particular extension is focused only on utilizing the new ChatGPT API which has a `chatCompletion` feature making the users have a seamless experience having conversations with the ChatGPT.

With that being said, we both have different solution for different use case by looking the feature that we provided.

**Comment by jonathanlaniado** [comment]
Agreed, while both extensions use AI, this is a very different use case.

**Comment by abielzulio** [comment]
Any updates on the submission? Please do let me know if there's anything I've missed! @pernielsentikaer 🙏

**Comment by pernielsentikaer** [comment]
What about #5157 in the queue, they seem pretty similar - could you check that out?

**Comment by abielzulio** [comment]
> I understand your dissatisfaction.
> 
> 
> 
> We must evaluate each extension on its own merits. In this case, we had four extensions that served the same purpose, which would be confusing for users. We are attempting to avoid this scenario. Due to the need to coordinate between multiple users, the process can be more complex in some cases.
> 
> 
> 
> Apologies for the inconvenience.

All good! Appreciated all the efforts that you guys doing. Please do let me know if you need something else from me. 🙏

**Comment by erodactyl** [comment]
Can we add options to: 

1. Not save conversations by default as this can create a lot of clutter over time. If this is opt-in or opt-out is up to you.
2. Allow models to have no prompt. Having the option to have prompts is awesome, but a generic prompt like `You are a helpful assistant` adds unnecessary tokens to the request, over time costing users more money than necessary.

**Comment by Cobular** [comment]
I'd really like to see the current conversation persisted through opens, currently when Raycast goes back to the main menu through being closed you loose the current context. This really sucks because gpt4 is so slow right now, it'll routinely take me 30s to get a single completion, so it's easy to get distracted and loose the session.

On that note, could you add `gpt-4` to the selector menu? I've tested this in a fork and it works perfectly fine if you have it activated on your account.

**Comment by jonathanlaniado** [comment]
@abielzulio, fantastic job implementing all the requests in this thread so quickly. GPT-4 would certainly be a welcome addition for those who have beta access, including myself.

I think all the feature additions in this PR make this an extremely robust extension in the Store.

**Comment by abielzulio** [comment]
> I'd really like to see the current conversation persisted through opens, currently when Raycast goes back to the main menu through being closed you loose the current context. This really sucks because gpt4 is so slow right now, it'll routinely take me 30s to get a single completion, so it's easy to get distracted and lose the session.
> 
> On that note, could you add `gpt-4` to the selector menu? I've tested this in a fork and it works perfectly fine if you have it activated on your account. 

> please add support for gpt4 😊 

> @abielzulio, fantastic job implementing all the requests in this thread so quickly. GPT-4 would certainly be a welcome addition for those who have beta access, including myself.
> 
> I think all the feature additions in this PR make this an extremely robust extension in the Store.

Just added a support for `GPT-4`! 🙏

**Comment by pernielsentikaer** [comment]
If you have a model which is not working as expected, then it never stops loading - we should maybe cancel the loading indicator and write that something is wrong as the toast says

https://user-images.githubusercontent.com/38033107/227433216-537c75df-59b9-43a1-ac57-85cb67972949.mp4

**Review by pernielsentikaer — APPROVED** [review]
Let's get merged into the store 🔥

**Comment by dandv** [comment]
I installed Raycast and the ChatGPT extension yesterday. Can't seem to be able to use GPT-4 though I do have it enabled for my API key, and I see `gpt-4*` in the list of models:

image

So I've created a model based on gtp-4-0134 and got this:

image

Then I created another one based on `gpt-4`, with the system prompt "Be helpful and brief", and got this:

image

**Comment by SniperUsopp** [comment]
I can not see the "gpt-4" options in model list.
image

**Comment by abielzulio** [comment]
> I can not see the "gpt-4" options in model list.
> 
> image
> 
> 

Hi! The model option is served based on your account support. If you can't see the GPT-4 model option then you have no access to the GPT-4 model yet. Have you joined their waitlist?

**Comment by SniperUsopp** [comment]
> > I can not see the "gpt-4" options in model list.
> > image
> 
> Hi! The model option is served based on your account support. If you can't see the GPT-4 model option then you have no access to the GPT-4 model yet. Have you joined their waitlist?

I have a gpt plus member. I can use GPT-4 in OpenAI's webpage. hhhh
image

**Comment by SniperUsopp** [comment]
> > > > I can not see the "gpt-4" options in model list.
> > 
> > 
> > > > image
> > 
> > 
> > > 
> > 
> > 
> > > Hi! The model option is served based on your account support. If you can't see the GPT-4 model option then you have no access to the GPT-4 model yet. Have you joined their waitlist?
> > 
> > 
> > I have a gpt plus member. I can use GPT-4 in OpenAI's webpage. hhhh
> > image
> 
> Having a GPT Plus account doesn’t mean you have the API access to the GPT-4 model. It’s a different thing. 😊
> 
> Please refer to this: https://openai.com/waitlist/gpt-4-api

Got it. Sorry to bother you guys~

**Pull request merged**
