### PR TITLE
MDN quick look-up in raycast

### PR DESCRIPTION
**Pull request by blackmann**
## Description

MDN quick look-up so you don't have to go through Google first. Definition/detail of terms are displayed right inside Raycast and not just redirects to MDN's site.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/5024388/141125475-c554c853-e1fd-4cb0-8188-eddf5cea8074.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @blackmann 👋 

It's always awesome when a new PR is incoming ❤️

I think we already have a similar extension with the same purpose #102 (https://www.raycast.com/krzysztofzuraw/search-mdn) - could you try to check it out - maybe you have something different or extra feature in yours that could be added in the other one that would make sense

**Comment by Garrett1Tolbert** [comment]
I do like how the information is accessible via Raycast rather than opening up a new tab. Maybe this piece can be embedded into the existing extension

**Comment by pernielsentikaer** [comment]
Also seems like they are not searching on the same dataset, only compared by searching, haven't checked

5yaHzPqi86RM0jFe

**Comment by blackmann** [comment]
@pernielsentikaer I checked out the other version and seems we're using different strategies entirely. What does this mean for Raycast? Are there ways to collaborate on the same extension; and also indicate multiple authors? Also will this mean, there can't be competing extensions?

**Comment by pernielsentikaer** [comment]
Hi @blackmann 👋 

Just wanted to check in and tell you that you're not forgotten, we just have to discuss this internally within the team.

I'll get back to you asap 💪

**Comment by PitNikola** [comment]
Hey guys! These two extensions are indeed very close to each other. Two main differences that I spotted it that one relies on API and opens everything in browser, and another one uses search index and opens results as markdown.

Ideally we would find a way to merge it into one extension considering that both are trying to solve the same problem. 

However, if authors prefer to keep those extensions separately, we will allow it because they have slightly different functionality. 
I understand that right now all credits for an extension goes to the original author making it less appealing to collaborate. In the future, we want add support for collaborators to acknowledge contributions from other developers.

@krzysztofzuraw, would you be up for accepting contribution from @blackmann? E.g. displaying docs as markdown or considering using search index instead of API (not sure what's the big difference between these approaches)?

**Comment by krzysztofzuraw** [comment]
Hey 👋🏻 

Sorry for such long response - I was on holiday. I all in for accepting contribution from @blackmann. 

For details - I'm wondering as well what is the difference and what is better to use 🤔 . @blackmann do you maybe have an idea about it?

**Comment by blackmann** [comment]
Hello @krzysztofzuraw please make pull and try it to experience the difference.

1. I use MDNs search index to locate the doc
2. The doc is converted into markdown and displayed right inside Raycast without having to visit with your browser.

**Comment by krzysztofzuraw** [comment]
@blackmann I just checked your extension and tbh I do not have preference or idea what is better: API or search index; about displaying markdown in Raycast - awesome idea but it is my personal preference to view MDN in the browser with all styling etc. applied. 

To sum it up: I think we either can merge those two extensions by deciding what approach to search use or have two separate extensions.

**Comment by blackmann** [comment]
I think we have conflict of preference. Can we have this as a separate extension? 

Are there other ways to share an extension with friends for installation?

@pernielsentikaer @krzysztofzuraw @PitNikola

**Comment by PitNikola** [comment]
Before we give up on the idea of merging these two extensions, I have an idea of how we could make it work:

- Add support for showing it as markdown as a separate action, and add a preference to choose which one to use as primary action. This way it wouldn't break existing behavior and will give ability to see docs in Raycast for those who prefer it more. Check out similar preference in Clipboard History:
CleanShot 2021-11-23 at 09 39 10@2x
- As for the search, if index provides as good and relevant results as API, then I would go with using index file, it's just much faster.

Let me know what you guys think!

**Comment by PitNikola** [comment]
@blackmann, in regards to sharing an extension with friends. They can just check out this PR and then run `npm install && npm run dev` in terminal, the extension will automatically get installed.

**Comment by krzysztofzuraw** [comment]
@PitNikola this is very good idea as I'm thinking about it right now 🤔 . 

We cloud add even option for the user to open term in MDN straight away instead of markdown summary or details.

@blackmann will you be able to change my original MDN extension with:
* switching into index file
* adding preference option that allow user to select what will be the default action available for searched term?

**Comment by fe9lix** [comment]
Closing this PR due to inactivity – feel free to reopen later.

**Pull request closed without merging**
