### PR TITLE
Added Gitfox extension

### PR DESCRIPTION
**Pull request by azlekov**
Gitfox extension

## Description

I'm using a modified version of the existing Tower extension by @tdwesten but adjusted to work with [Gitfox](https://www.gitfox.app)

## Screencast

https://user-images.githubusercontent.com/2267270/154073050-fc9ed528-b4d5-4867-bcd0-8d8dae119a73.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @L3K0V 👋 

Thanks for your awesome contribution 💯 

I do have problems when running the command:

- I installed Gitfox and added CLI(Path in extension setting is the correct one), but still get below error: 

oPUHgLNShqHyKAxS

Do you need anything from me, catch me in Slack if we need to debug this together 😄

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @L3K0V 👋 

Thanks for the chat in Slack, it was so much helpful 🔥 

Everything works as expected, the only thing I'm thinking about is when the path is wrong in preferences then I see this:

9AK4apvOLo30wOpp

But I have installed the CLI tools, just wrong path 😄

Do you have an idea to improve this part?

**Comment by L3K0V** [comment]
Hey @pernielsentikaer,

Thanks for the feedback. What about changing wording and explanation as the source actually checks if the CLI path exists?
Do you think such change will be sufficient:

image

**Review by pernielsentikaer — APPROVED** [review]
That's much better @L3K0V 🔥 

I'm going to approve this, and then we're moving to the final stage 🚀

**Pull request merged**
