### PR TITLE
add recent tags picker to drafts extension

### PR DESCRIPTION
**Pull request by FlohGro-dev**
## Description

- Migrated to new API version
- added Recent Tags picker to Create Draft command (resolve issue #3834)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by FlohGro-dev** [comment]
HI @pernielsentikaer 
I wanted to update the screenshots using the built in Screenshot tool, but as you can see its storing them in the wrong resolution - I don't know if I can change that behavior, since the docs just say I should use it and I assume it would work..
Can you please have a look and let me know what I can do to fix this (or if you can: I would appreciate it if you  just update the screenshots?)

**Comment by pernielsentikaer** [comment]
Hi @FlohGro-dev 👋 

Did you take the metadata images on your build-in retina screen? This might be the way to go - could you try that?

**Comment by FlohGro-dev** [comment]
I will try that next time, I used my external monitor to take the screenshot. Maybe add this to the documentation.

Unfortunately I can't do it myself anymore cause I'm on vacation now.
I will have a look in a bit over three weeks then to take the screenshots.

**Comment by pernielsentikaer** [comment]
Let me take a new metadata image of the new one and remove the old one, then you can make a PR when you have time again

**Comment by FlohGro-dev** [comment]
Thanks @pernielsentikaer this is much appreciated!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
