### PR TITLE
[Airtable] update the OAuth ID to fix login not working (scope mismatch)

### LINKED ISSUE #15159: [Airtable] OAuth errors connecting to Raycast
### Extension

https://www.raycast.com/marks/raycast-airtable-extension

### Raycast Version

1.84.7

### macOS Version

14.5 (23F79)

### Description

When I try to connect Airtable to Raycast, I get the following error:
> Your OAuth application requested the scope "schema.bases:read data.records:read data.records:write" which your application does not have access to. You can edit this in your OAuth Application's settings 

Note that this error happens even though the Raycast web page says that I'm "Successfully connected to Airtable."

Also, the "Open Raycast" button on the Raycast website doesn't seem to work.

### Steps To Reproduce

1. Install the Airtable extensions
2. Run the "List Bases" command
3. Try to perform OAuth.

### Current Behaviour

An OAuth error is received:
> Your OAuth application requested the scope "schema.bases:read data.records:read data.records:write" which your application does not have access to. You can edit this in your OAuth Application's settings 

### Expected Behaviour

It should connect to OAuth correctly.

### PR DESCRIPTION
**Pull request by xmok**
## Description

This will close #15159 and fix the scope issue by replacing the ID with a new one.
The Airtable Team hasn't update the scopes yet so we switch to another one that has proper scopes. I have mentioned it in README so if future changes are needed, one knows who to reach out to.

I have added comments for the logic of hard coding OAuth IDs and checking them.

## Screencast

N/A - logs in fine. 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@marks, could you take a look here? I don't use Airtable myself

**Comment by marks** [comment]
I do not use Airtable anymore either. At quick glance, this change looks fine, though I think it would have been better to have Airtable update the existing OAuth app :\ (but it seems @xmok tried and hence the need for this PR)

**Comment by xmok** [comment]
I'll send another email as maybe the first one got drowned in other threads?

It makes sense to use the OG OAuth App as it doesn't break UX. The only reason I can think of for a new App is so it's easier/quicker if we need to update scopes again in the future but keeping the old one makes more sense to me still as we can always ask Support to update accordingly and it won't log out existing users.

I suppose it's your call @marks as the author.
We can wait and I'll email them again otherwise yeah we can proceed with this PR.

**Comment by marks** [comment]
Hey @xmok - I agree having Airtable fix is the purest solution, but it sounds like you're unfortunately not getting good responsiveness from them (sorry).

Since #14864 is already merged and people are running into this issue, I guess it makes sense for you to change the client ID.

@pernielsentikaer - do you all usually expect individuals to own default client IDs like this?

**Comment by pernielsentikaer** [comment]
No I don't think we do that often, let's merge and see how it goes 🙂

**Pull request merged**
