### PR TITLE
Update unicode-symbols extension

### PR DESCRIPTION
**Pull request by j3lte**
## Description

- Upgraded `@raycast/api@^1.63.0` and other dependencies
- Added 'Grid' view (now the default view)
- Added a Character set selector to the search bar
- Added an option to copy the HEX code of the selected character (used in development of html/css)
- Added an option to copy the HTML entity of the selected character (used in development of html)
- Added extra character sets, totalling to 4940 characters
- Refactored a large portion of the code to make it more maintainable
- Updated screenshots

## Screencast

unicode-symbols-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
@mmazzarolo do you have time to check this?

@j3lte awesome update 🔥 Would it be an idea to add a preference to set size of the grid, like this extension does: https://www.raycast.com/josephschmitt/gif-search

**Comment by j3lte** [comment]
> @j3lte awesome update 🔥 Would it be an idea to add a preference to set size of the grid, like this extension does: [raycast.com/josephschmitt/gif-search](https://www.raycast.com/josephschmitt/gif-search)

@pernielsentikaer Great idea, I'll add this a.s.a.p.

**Comment by pernielsentikaer** [comment]
Awesome @j3lte 🔥 

@mmazzarolo do you have time?

**Comment by j3lte** [comment]
@mmazzarolo bump...

**Review by mmazzarolo — APPROVED** [review]
Hey @j3lte , @pernielsentikaer , I don't have time to try this out anytime soon sadly. I gave it a quick review, and it looks good overall! Great work!
If you need a more in-depth review and someone to give it a try, I would wait for someone else first, though (or for me, I'll have some time early Jan I think).

**Comment by pernielsentikaer** [comment]
I gave it a spin, let's get it out then 🙂

**Pull request merged**
