### PR TITLE
Apple Reminders: Initial version.

### PR DESCRIPTION
**Pull request by shakedlokits**
## Description

Search and manage all your Apple reminders in one convenient place, without switching between apps. Save time and increase your productivity with the ability to easily search and mark reminders as completed.

Currently supports: 

- Search apple remiders
- Get reminders by list
- Render priority icons
- Present note body
- Show due date in human readable form
- Mark reminder as done

## Technical Details

- Uses AppleScript JS(JXA) to interface with apple reminders
- Apple's local APIs are slow, so polling slices of data is required, to avoid throttling (i.e Reminder[] => Name[])
- Caching each request and uses optimistic updates to avoid unnecessary waiting time and improve overall UX

## Screencast

apple-reminders-1

apple-reminders-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Just out of curiosity; what's the difference between this and `My Reminders` in Raycast?

**Comment by shakedlokits** [comment]
@pernielsentikaer Hi there! Could you please elaborate? I wan not able to find a reminders app
image
image
image

**Comment by shakedlokits** [comment]
It wasn't disabled, just couldn't find it on the search. 
Maybe because it was called "My Reminders"? 
Or maybe because it was built-in and I assumed it would be in the store?
And I developed it because other people couldn't find it. 
This sucks..

**Comment by pernielsentikaer** [comment]
I'm sorry that you didn't find it; simply searching for `Reminder` should find it, can you confirm that?

Raycast-ZkduQliB@2x

**Comment by shakedlokits** [comment]
It didn't, but now it does 😅 Added an alias
image

**Comment by pernielsentikaer** [comment]
I will close this since it's a standard feature in Raycast. Sorry for the inconvenience

**Pull request closed without merging**
