### PR TITLE
Add just-breathe extension

### PR DESCRIPTION
**Pull request by khlebobul**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The markdown is not in the middle when using Raycast in larger text mode, you can find the textSize in [environment](https://developers.raycast.com/api-reference/environment#properties) - Maybe you could make it fit in large mode too

just-breathe 2024-06-24 at 07 03 39

  

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by khlebobul** [comment]
Hello, thank you, to be honest I have never used larger text mode so I didn't take that into account. I'll fix it

**Comment by pernielsentikaer** [comment]
Same here, but I know we have a good amount of users using it and I'ld like to look awesome for everyone - I like your idea 🙏

**Comment by khlebobul** [comment]
Totally agree, I will redo it soon

**Comment by pernielsentikaer** [comment]
I can't see any new [code here](https://github.com/raycast/extensions/pull/13141/commits/b4a21b94334111a090496bf105ece539f0b51ea0), did you get it all pushed?

**Comment by pernielsentikaer** [comment]
Sorry for explaining it wrong, it's my bad 🙂 I was talking about the "graphics"

Raycast24062024-TX2fIGSy png@2x

**Comment by khlebobul** [comment]
Now I understand, thank you

**Comment by pernielsentikaer** [comment]
Would you be up for that, otherwise I can also do it :)

**Comment by khlebobul** [comment]
Of course, I'll make the changes soon

**Comment by khlebobul** [comment]
Good evening, I was able to center the element in large text mode. I also made the elements via txt to improve the code
P.S. This solution was inspired by Thomas (Party Parrot)

**Comment by pernielsentikaer** [comment]
Awesome, approved ✅

**Comment by khlebobul** [comment]
Thank you!

**Pull request merged**
