### PR TITLE
Improve Things Extension

### PR DESCRIPTION
**Pull request by loris**
## Description

- [x] Add complete/cancel/delete actions
- [x] Add "Add New To-Do" command and fallback action
- [x] Add "Search in Things" fallback action
- [x] Fix i18n issue (https://github.com/raycast/extensions/issues/299)
- [x] Add todos count in section subtitle
- [x] Replace built-in list filtering with better one
- [x] Display tags in List subtitle (instead of notes)
- [x] Add project and area in actions
- [x] Search in project and area tags

## Type of change

- Bug fix / improvement for my extension

## Screencast

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by loris** [comment]
@mattisssa @pernielsentikaer Hi guys, the PR is now ready for review! Thanks

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @loris 👋 

Thanks for the update, it's going to add so much value!

Tested it and only found a single comment, maybe I'm just wrong 😄 

- I'm not sure that I can see the todo count in section subtitle, maybe I'm not doing it the right way? Does it require more than one list

W4ZJ1IzfMCAUCSsO

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by loris** [comment]
Hi @pernielsentikaer Thanks  a lot for the review!
Interesting feedback, Right now the count is displayed on the List.Section items which are displayed when grouping to-dos by their parent projects. So orphan to-dos (like on your screenshot) are at the top level of the List component and thus no count is displayed.
I missed it because I tends to classify all my todos in projects.
One idea could be to add them in a "No project" section or something like this, what do you think?
image

Or maybe add a global count in the navigation title?
image

**Comment by pernielsentikaer** [comment]
Hi @loris 👋 

I'm actually not sure what would be the best output, it doesn't add much value to add “No Project” since a lot also uses it without a project — Guess it's better to keep as is — thanks for the clarification 🙏 

Comments: 
- When a new item is added, it changes the view to the list. However, most of the time I would personally go to another action, and then I have to hit escape twice to go “out”
- When hitting one escape (to go back) the form is not “cleared”

If anything above is unclear, feel free to catch me in Slack 😄

**Comment by loris** [comment]
@pernielsentikaer as discussed on Slack, I ensured the form values are cleared on form submission and added a secondary form action to allow the user to go to the todo list:

image

**Comment by loris** [comment]
@pernielsentikaer Thanks! it happens if Things is not running, I just pushed a better error hander to replace the stacktrace error with a Markdown Detail View (in addition to the Toast, which is not very visible):

image

**Comment by pernielsentikaer** [comment]
Hi @loris 👋 

There is now a flicker for every command showing the right data before showing that Things is not installed, can we look into this? For me it was only a problem when Things was not open when I added - I'm not sure if its the same for you?

Can we do something about this?

**Review by pernielsentikaer — APPROVED** [review]
Hi again @loris 🔥 

Thanks for the conversation, and as we spoke about we have the “flicker” issue on the list to find a better solution when it's possible for now people have things open anyway.

I have accepted it, and we await final review before merging 🚀 

Thanks for your update!

**Pull request merged**
