### PR TITLE
Improve CoinMarketCap extensions

### PR DESCRIPTION
**Pull request by Yukaii**
## Description

- Add favorite command and change output style for coinmarketcap extension
- Add currency converter

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @moojing 

### Favorites

https://user-images.githubusercontent.com/4230968/145671653-81226f6a-4751-475d-b9cf-a3cb64d52d06.mp4

### Currency Converter

https://user-images.githubusercontent.com/4230968/145677342-50c2d9f6-2dda-44a0-8e61-deda615a7ae2.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

## TODOs

- [ ] Prefetch favorite coins' prices

### CODE REVIEW

**Comment by moojing** [comment]
looks great!!

**Review by mattisssa — APPROVED** [review]
Hey! Looks good, I've updated some titles and added a shortcut for the Favorite action.

I still don't like the idea of loading data for the selection changes for a currency. When I do this, I get the error:
https://user-images.githubusercontent.com/15333662/145704442-b6ac4f51-0411-428c-80da-a782217f7a57.mp4

I assume this happens because of multiple loading calls. Probably would be better to cancel the previous request if there is a new selection changes callback received? 
I understand that the idea is to have as many prices as possible on the screen. But this makes the extension and Raycast really slow, so I would definitely do something about it.

And I could already mention this, but loading the price for every selection change is also not the best idea since it can cause the problems from above 😄 

So, I'd propose to you to find a way lo load the list of tickets (or currencies) with price at single request 😉 

Let me know what do you think, I'll keep the PR open for a while. @moojing @Yukaii

**Comment by Yukaii** [comment]
@mattisssa Sorry for the late reply, kind of busy this week.

The idea is not to use CMC's Pro API for now, because it has quota limits and needs further setup. 

The ideal solution is using the official API, and even the currency exchange calculation can be done in real-time with that API, but I want to keep a minimum usable extension for now.

Maybe I can update the code with your proposed solution (request cancelation) and leave other changes in future pull requests?

**Comment by mattisssa** [comment]
>@mattisssa Sorry for the late reply, kind of busy this week.

No worries 😉 Take your time 🙌 

>Maybe I can update the code with your proposed solution (request cancelation) and leave other changes in future pull requests?

Sure, let's do it in this way. Let's probably get it merged and you can create another PR with the changes we discussed?

**Comment by mattisssa** [comment]
Hey @tumispro!
 I think this report is probably worth [to create an Issue](https://github.com/raycast/extensions/issues/new?assignees=&labels=extension%2C+bug&template=extension_bug_report.md&title=) to easily keep track of what's going on there and don't mix the conversations 😉

**Comment by tumispro** [comment]
Will do!

**Pull request merged**
