### PR TITLE
Update pomodoro extension

### PR DESCRIPTION
**Pull request by mikikiv**
## Description

* Adds the option for a user to add in their own GIPHY api key to get back random gifs 
* Moves typescript types around into a types.ts file
* bumps raycast/api version up

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mikikiv** [comment]
While a user can now input their own api key, I wonder if its possible to keep an application level api key in Raycast or somewhere so that users don't need to input their own?

**Comment by pernielsentikaer** [comment]
Could you check this @KELiON - do you have some input of the new additions here

**Comment by mikikiv** [comment]
The latest commit adds customization options to the api so that users can further define what kind of gif plays at the end of their timer
CleanShot 2023-12-13 at 11 05 48@2x

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
