### PR TITLE
Added initial version of extension "rsync-commands".

### PR DESCRIPTION
**Pull request by maxfahl**
## Description

Save your commonly used rsync commands in one place and run them with ease. Supports SSH endpoint configuration together
with all the options supported by rsync.

#### Features:

1. Create, update, delete and duplicate pre-configured rsync commands.
2. Pin your most used commands.
3. Run one of your save commands directly from Raycase.
4. Copy a rsync command to the clipboard to run it manually.

#### Requirements:

- rsync version 3+ (tested only on 3.2.3 so far).
- rsync has to be in your PATH.

#### Known Issues:

- After first selecting `Source` or `Destination` for `SSH` in your commands, you can't simply swap to the other option without first selecting `None`. I can't figure out why this doesn't work since the state for where the fields should render is updating correctly. The view doesn't seem to agree with this somehow and refuses to change position of the fields. 

## Screencast

[Watch here](https://streamable.com/cjgccw)

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by maxfahl — COMMENTED** [review]
Made toasts more consistent with eachother, keeping just the title.

**Comment by sxn** [comment]
> After first selecting Source or Destination for SSH in your commands, you can't simply swap to the other option without first selecting None. I can't figure out why this doesn't work since the state for where the fields should render is updating correctly. The view doesn't seem to agree with this somehow and refuses to change position of the fields.

Did a bit of digging and it seems to be an issue on our side. Could you please create a bug ticket for this? I'll look into fixing it in next release. 😸

**Comment by maxfahl** [comment]
@sxn here's the issue related to what we discussed yesterday: https://github.com/raycast/extensions/issues/1663

**Comment by maxfahl** [comment]
I just tested the extension, and everything seems to work smoothly on 1.35.1, bugs squashed.

**Comment by pernielsentikaer** [comment]
Awesome @maxfahl 🔥 I'll get it another spin! 😄

**Comment by maxfahl** [comment]
Thanks @pernielsentikaer, I have some upcoming additions as well that I've been keeping on a separate branch. Will create a new PR for them in the coming week or so.

**Review by pernielsentikaer — APPROVED** [review]
Let's get the first version live! 🔥

**Pull request merged**
