### PR TITLE
Update capture-fullpage-of-website extension

### LINKED ISSUE #11870: Needs to be updated[Capture Fullpage of Website] ...
### Extension

https://www.raycast.com/Coun1er/capture-fullpage-of-website

### Description

Failed taking screenshot of website
Error: : Executable doesn't exist at /Users/
asgeirti2/Library/Caches/ms-playwright/
chromium-1005/chrome-mac/Chromium.app/
Contents/MacOS/Chromium...

### Steps To Reproduce

Chromium 124.0.6367.29 (playwright build v1112) is the latest

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by j3lte**
## Description

- Update dependencies & make sure chromium is installed (`npm postinstall`) (fix #11870, #12149)
- Add setting for Output Directory

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
@Coun1er do you want to check this before merge?

**Comment by pernielsentikaer** [comment]
@Coun1er pinging you one last time 🙂

**Comment by j3lte** [comment]
@pernielsentikaer I'm thinking @Coun1er is inactive, when looking at his Github activity...

**Comment by mil3na** [comment]
Hey @j3lte it seems to be the case, yes. It looks good to me, I will be merging this.

**Pull request merged**
