### PR TITLE
Add `Import Quicklinks From Browser` Extension

### PR DESCRIPTION
**Pull request by pomdtr**
## Description

Add a new extension allowing to import quicklinks from chromium based browsers.

## Screencast

screenshot-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @pomdtr 👋 

I like the idea, at the moment I don't have any chromium-based browsers installed, but the loader just keeps spinning, do you think you can come up with a solution where the loader stops and maybe a toast?

image

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pomdtr** [comment]
Thanks for the review @pernielsentikaer ! It should be good now :)

**Comment by pernielsentikaer** [comment]
Hi @pomdtr 👋 

Thanks for the update; that's much better!

Where does it get the links? I just downloaded Vivaldi and struggling to find out where the links are taken from? Since the links in this list use {query} and Vivaldi, it's using %s. Also the amount of links are not the same 😄 

Let me know if we need to debug it 😄 

CleanShot 2022-05-15 at 08 59 02@2x

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pomdtr** [comment]
It looks like vivaldi use some custom logic, so I dropped support for it the extension. Please try using edge, brave, chrome or chromium.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @pomdtr 👋 

I was just checking old PRs through, and I saw that I didn't catch this one, sorry about that!

I just checked this with a Chrome browser, but I'm still not able to get it to work, is this the wrong place to save them?

CleanShot 2022-06-27 at 13 30 59@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pomdtr** [comment]
Yeah I kind of forgot to update it. I'll take another look at it, probalby limiting it to chrome since it is the only browser I currently use.

**Comment by pernielsentikaer** [comment]
Did you see the latest version of Raycast where we have enabled auto-fill from almost every browser except a few, is that any help or is this still better?

CleanShot 2022-06-30 at 21 15 58@2x

**Comment by danielsequeira** [comment]
@pomdtr ping here 🙂

**Comment by pomdtr** [comment]
I'll close this, I do not use it anymore ;)

**Pull request closed without merging**
