### PR TITLE
Music: Fixed command "love track"

### PR DESCRIPTION
**Pull request by peterdev22**
## Description

Fixes the command "Love track" so it loves the track instead of adding to library.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Rawnly** [comment]
Thanks @peterdev22! Super fast!

**Comment by Rawnly** [comment]
Can you do a super easy edit to te package.json and try to add me to the contributors as well? It might fix the issue mention 🙃

**Comment by peterdev22** [comment]
Added.

**Comment by pernielsentikaer** [comment]
It depends on where the issue is opened from, if you do it from with Raycast it adds the author, if from the store on the webpage it doesn't do it. 

We're soon releasing an improved solution for this 😁

**Pull request merged**
