### PR TITLE
[Night Light] Add preference setting to close Raycast window

### PR DESCRIPTION
**Pull request by kgrhartlage**
## Description

- add preference setting to close main Raycast window
- shorten UI strings for error messages so that they don't get truncated (see screenshots)
- upgrade project dependencies

## Screenshots

<details>
<summary>UI errors before vs. after</summary>

CleanShot 2023-05-12 at 08 14 24@2x

CleanShot 2023-05-12 at 11 05 39@2x

CleanShot 2023-05-12 at 11 12 03@2x

</details>

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @kgrhartlage 🔥 

@devmoath do you mind checking this?

**Comment by kgrhartlage** [comment]
I'll add the preference setting

**Comment by kgrhartlage** [comment]
@pernielsentikaer  I added the preference setting to close the main Raycast window when the command is triggered and updated the PR description accordingly. It is ready for review.

`clearSearchBar()` does not seem to work anymore 😕 Am I missing something or did this potentially break with a recent release? `popToRoot({ clearSearchBar: true })` works perfectly fine

**Comment by pernielsentikaer** [comment]
I just tested with the below code and it seems to work for me

```
import { List, clearSearchBar } from "@raycast/api";
import { useEffect } from "react";
import { setTimeout } from "timers";

export default function SystemMonitor() {
  useEffect(() => {
    setTimeout(() => {
      clearSearchBar();
    }, 3000);
  }, []);

  return <List />;
}
```

**Comment by kgrhartlage** [comment]
@pernielsentikaer this needs your attention. It's ready for review/approval from my side

**Comment by sxn** [comment]
hey @devmoath, any objections? the PR's been hanging around for ~6 weeks, and since it seems like a useful contribution, it'd be neat to get it merged.😺

**Comment by devmoath** [comment]
LGTM ✅

**Pull request merged**
