### PR TITLE
Add momentum extension

### PR DESCRIPTION
**Pull request by LeOndaz**
## Description

An extension that scaffolds your new projects (cookiecutter), comes integrated with React/Vue/Vite (all supported templates), Node.js & an empty project.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by LeOndaz** [comment]
Okay, The CI is failing beacuse of this, I'll wait for someone to help with it (already asked on Slack)

image

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I just tested this extension and I get an error when I try to create a new project

Raycast 2024-02-28 at 11 55 02

I get this error code in the terminal
image

Can you look into this?

**Comment by LeOndaz** [comment]
@pernielsentikaer 

I think the error is because I'm sourcing some directories that you don't have, since we are all mac users, we're using .zprofile & .zshrc, but mac comes with bash installed and .bashrc/.profile templates as well, so I assumed some users will be using them, or even bash itself as a default shell. I also assumed those files will exist in everyone's case which clearly is a mistake of mine, I now added a test to check if the file exists before sourcing it and changed the default shell to zsh, I also fixed `vue` because I think I forgot to do it the last time.

Please have a look when you have time.

**Comment by pernielsentikaer** [comment]
Hi 👋

I'm getting this error now, I got a empty folder created before it crashes

```
13:56:57.907 running development mode
13:56:57.925 which npm
13:56:58.456 creating...
13:56:58.459 cd /Users/pernielsentikaer/Desktop/tmptmp && npm create vite test -- --template react-ts
13:56:59.387 ProcessOutput {
  stdout: '',
  stderr: 'npm ERR! code ENOENT\n' +
  'npm ERR! syscall spawn sh\n' +
  'npm ERR! path /Users/pernielsentikaer/Desktop/tmptmp\n' +
  'npm ERR! errno -2\n' +
  'npm ERR! enoent spawn sh ENOENT\n' +
  'npm ERR! enoent This is related to npm not being able to find a file.\n' +
  'npm ERR! enoent \n' +
  '\n' +
  'npm ERR! A complete log of this run can be found in: /Users/pernielsentikaer/.npm/_logs/2024-02-29T12_56_59_087Z-debug-0.log\n',
  signal: null,
  exitCode: 254
}
13:56:59.387 Error: npm failed to create project /Users/pernielsentikaer/Desktop/tmptmp/test
    at Object.create (/Users/pernielsentikaer/.config/raycast/extensions/momentum/project-react.js:15927:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/pernielsentikaer/.config/raycast/extensions/momentum/project-react.js:16088:3
    at async Object.<anonymous> (/Users/pernielsentikaer/.config/raycast/extensions/momentum/project-react.js:16059:7)
```

**Comment by LeOndaz** [comment]
@pernielsentikaer 

Hey, happy weekend, when you are available, can you provide me with the following outputs:


```shell
cat /etc/shells
```

**Comment by LeOndaz** [comment]
@pernielsentikaer 
Well, `  'npm ERR! syscall spawn sh\n'` means it's trying to spawn sh, even though this should have spawned either zsh or bash, It's highly unlikely that you've a shell problem but, can you tell me the output of

```
# get current shell name, run in the default shell, probably in -terminal- app
ps -p $$ -o 'comm='
```

also, when you are testing, do you only enter the directory name or a path? because the extension expects the directory name only like the image below

image

Assuming that you've set in the command settings that your projects should lie in `~/projects` and you enter a project name or `my_project`

You should expect `~/projects/my_project` to exist and have the command `create vite...` result.

From `/Users/pernielsentikaer/Desktop/tmptmp`, I can understand that you chose desktop to be your projects directory, while tmptmp is the name of the project, if this is fine, does Raycast have permissions to access the Desktop on your machine?

**Comment by pernielsentikaer** [comment]
The output gives me `-zsh` and yes, full disk access and the folder `my_project` is added to the tmptmptmp folder 🫠

**Comment by LeOndaz** [comment]
@pernielsentikaer well, it seems like I have no clue, let me investigate

**Comment by LeOndaz** [comment]
@pernielsentikaer can you assign one more reviewer? I need someone to test it with us, I'm thinking that you've got a problem related to raycast, the extension spawns zsh, but for some reason, it only spawns sh on your machine, I need to confirm my suspicion

**Comment by pernielsentikaer** [comment]
@mil3na can you help test this extension, as you can see it doesn't work for me

**Comment by mil3na** [comment]
I tried testing it and, creating a React project, but it just keeps loading and loading. Just a folder was created.

**Comment by LeOndaz** [comment]
@mil3na can I get your logs as well?

**Comment by mil3na** [comment]
Hmmm the logs do show something interesting. My first trial had a space on the project's name. I tried creating one with a simple name and it worked! However, trying with a space again, I get infinite loading:

```
13:27:49.401 running development mode
13:27:49.401 which npm
13:27:49.815 creating...
13:27:49.854 cd /Users/milena && npm create vite test -- --template react-ts
13:28:13.227 running development mode
13:28:13.231 which npm
13:28:13.634 creating...
13:28:13.800 cd /Users/milena && npm create vite $'milena project' -- --template react-ts
```

**Comment by LeOndaz** [comment]
> Hmmm the logs do show something interesting. My first trial had a space on the project's name. I tried creating one with a simple name and it worked! However, trying with a space again, I get infinite loading:
> 
> ```
> 13:27:49.401 running development mode
> 13:27:49.401 which npm
> 13:27:49.815 creating...
> 13:27:49.854 cd /Users/milena && npm create vite test -- --template react-ts
> 13:28:13.227 running development mode
> 13:28:13.231 which npm
> 13:28:13.634 creating...
> 13:28:13.800 cd /Users/milena && npm create vite $'milena project' -- --template react-ts
> ```

@mil3na 
Interesting, this is a `zx` behavior, I already knew about it and thought I disabled it, I'll see what I can do

**Comment by LeOndaz** [comment]
@pernielsentikaer  @mil3na 

Issues found:
1. Escape issues, related to zx library 
2. PNPM/NPM both open the interactive mode when the name has spaces, which makes the loading stuck


Both should be fixed

**Comment by pernielsentikaer** [comment]
I'll do some more testing but I just tried it quickly and it worked as expected 

Raycast08042024-XG44azVI png@2x

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
