### PR TITLE
Add laravel-tips extension

### PR DESCRIPTION
**Pull request by godruoyi**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

I'm not into Rust, how can I compile it myself, also, is there a way to only have one binary - I don't think both are necessary, are they?

Wouldn't it be simpler to have it in a JSON file somewhere?

**Comment by godruoyi** [comment]
> is there a way to only have one binary - I don't think both are necessary, are they?

Hi @pernielsentikaer thank your reply, Yes, it would be better to keep only one binary file in this extension. I plan to optimize it in the next version. Can I keep it as is for this initial version?

> Wouldn't it be simpler to have it in a JSON file somewhere?

I don't quite understand what this means, could you  please be more specific? That would be even better if you could give me an example.

**Comment by pernielsentikaer** [comment]
> I plan to optimize it in the next version. Can I keep it as is for this initial version?
It will just add 10+ MB to the repository which could be only half of it and we can't really make it disappear from the history so users will need to download it while checking the repository out.

> I don't quite understand what this means, could you please be more specific? That would be even better if you could give me an example.
I was thinking that a simple JSON API would be more sufficient for this job instead of having a binary with the data. 

Can also be that I'm missing something 🙂

**Comment by godruoyi** [comment]
Hi @pernielsentikaer Now there is only one binary file, can you help take a look?

**Comment by pernielsentikaer** [comment]
That's a lot better @godruoyi 🔥 

Is there a way I can compile it from the source myself?

**Comment by godruoyi** [comment]
@pernielsentikaer hi buddy can you please take a look?

**Comment by godruoyi** [comment]
hi @pernielsentikaer This pull request has been blocked for several days. Is there anything I need to know?

**Pull request merged**
