### PR TITLE
Add drupal-api extension

### PR DESCRIPTION
**Pull request by BossElijah**
## Description

This extension lets you search Drupal API documentation directly from Raycast.

## Screencast
drupal-api-1
drupal-api-3
drupal-api-5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

Would it make sense to add to this [extension](https://www.raycast.com/hussainweb/drupal-org) by @hussainweb and mke that one a more general one instead?

**Comment by BossElijah** [comment]
Hi @pernielsentikaer.
 I thought about it as well, but it seems hussainweb wants their extension to be more general, while I like the simplicity of this one. Being able to browse through the API is a crucial part of every day Drupal module development while the other extension seems to be more directed at developers developing Drupal itself.

I just defended why I want is as a separate extension, but you're more than welcome to tell me if you think otherwise.

Thank you!

**Comment by pernielsentikaer** [comment]
Having it in the same extension might not be bad, both things is developer related, right?

Let's see what @hussainweb says :)

**Comment by hussainweb** [comment]
Thanks for writing this. It's a really good idea. It's also one of the things I want to include in my extension anyway. Considering that this extension is also reading the details from Drupal.org, I think there is a strong overlap. I can't think of any advantage in having a separate extension for API documentation when it is already in scope of the [`drupal-org`](https://github.com/hussainweb/raycast-drupal-org) extension.

To that end, I am happy to help merge this functionality in my extension. If you agree, let's discuss on what's a good way to do that. Of course, I would also like to credit you as the author. I have to check how Raycast attributes multiple authors/contributors on an extension.

**Comment by BossElijah** [comment]
Alright @hussainweb, sounds good. What is the procedure then? Do we close this PR and I make a PR on the other extension? I'll be happy to try to integrate it into your extension if that's ok with you.

**Comment by hussainweb** [comment]
That's great. Do you want to directly add it to my repo and we can then submit a combined PR here? This model of a mega repository is a bit new to me and I'm open to other ideas.

@pernielsentikaer what do you suggest is the best way forward in this scenario?

**Comment by pernielsentikaer** [comment]
The easiest way is to download the [extension](https://www.raycast.com/hussainweb/drupal-org) inside Raycast and use the action `Fork extension`. Then open in your editor and run `npx @raycast/migration@latest .` this way it updates to the newest version of everything and then you can add your changes with `git commit -am "update"` and use `npx @raycast/api@latest publish` to open a PR

**Comment by BossElijah** [comment]
Just created a PR for the other drupal extension: https://github.com/raycast/extensions/pull/12239

@pernielsentikaer should we close this PR?

**Comment by pernielsentikaer** [comment]
Let's close this yes 🙂

**Pull request closed without merging**
