### PR TITLE
Slack: Add unread messages command

### PR DESCRIPTION
**Pull request by momme-rtf**
## Description

I added a new built-in `unread messages` command to the Slack extension which enables the user to browse through unread dms, channels and groups and to mark them as read.

## Screencast
slack-02

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by momme-rtf** [comment]
@mattisssa Feel free to check it out:) Thanks for the inspiration! Hope that you like the outcome!

**Comment by pernielsentikaer** [comment]
Hi @momme-rtf 👋 

I just tested the new command and I just keep getting this error, can you look into this?

CleanShot 2022-04-19 at 22 13 20@2x

```
22:12:03.128 Failed reading cache Error: ENOENT: no such file or directory, open '/Users/pnt/Library/Application Support/com.raycast.macos/extensions/slack/swr-cache'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at null.provider (/Users/pnt/Documents/Raycast/tmp/slack/src/shared/client/CacheProvider.tsx:14:19)
    at null.<anonymous> (/Users/pnt/Documents/Raycast/tmp/slack/node_modules/swr/dist/index.mjs:500:25)
    at mountState (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:6052:24)
    at Object.useState (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:6537:20)
    at useState (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react/react.development.js:1533:23)
    at null.SWRConfig$1 (/Users/pnt/Documents/Raycast/tmp/slack/node_modules/swr/dist/index.mjs:498:24)
    at renderWithHooks (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:5637:22)
    at mountIndeterminateComponent (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:7757:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/pnt/Library/Application Support/com.raycast.macos/extensions/slack/swr-cache'
} 
    at null.SWRConfig$1 (/Users/pnt/Documents/Raycast/tmp/slack/node_modules/swr/dist/index.mjs:492:23)
    at null.CacheProvider (/Users/pnt/Documents/Ray<…>
22:12:05.350 Failed reading cache Error: ENOENT: no such file or directory, open '/Users/pnt/Library/Application Support/com.raycast.macos/extensions/slack/swr-cache'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at null.provider (/Users/pnt/Documents/Raycast/tmp/slack/src/shared/client/CacheProvider.tsx:14:19)
    at null.<anonymous> (/Users/pnt/Documents/Raycast/tmp/slack/node_modules/swr/dist/index.mjs:500:25)
    at mountState (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:6052:24)
    at Object.useState (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:6537:20)
    at useState (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react/react.development.js:1533:23)
    at null.SWRConfig$1 (/Users/pnt/Documents/Raycast/tmp/slack/node_modules/swr/dist/index.mjs:498:24)
    at renderWithHooks (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:5637:22)
    at mountIndeterminateComponent (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:7757:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/pnt/Library/Application Support/com.raycast.macos/extensions/slack/swr-cache'
} 
    at null.SWRConfig$1 (/Users/pnt/Documents/Raycast/tmp/slack/node_modules/swr/dist/index.mjs:492:23)
    at null.CacheProvider (/Users/pnt/Documents/Ray<…>
22:13:16.345 Failed reading cache Error: ENOENT: no such file or directory, open '/Users/pnt/Library/Application Support/com.raycast.macos/extensions/slack/swr-cache'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at null.provider (/Users/pnt/Documents/Raycast/tmp/slack/src/shared/client/CacheProvider.tsx:14:19)
    at null.<anonymous> (/Users/pnt/Documents/Raycast/tmp/slack/node_modules/swr/dist/index.mjs:500:25)
    at mountState (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:6052:24)
    at Object.useState (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:6537:20)
    at useState (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react/react.development.js:1533:23)
    at null.SWRConfig$1 (/Users/pnt/Documents/Raycast/tmp/slack/node_modules/swr/dist/index.mjs:498:24)
    at renderWithHooks (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:5637:22)
    at mountIndeterminateComponent (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:7757:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/pnt/Library/Application Support/com.raycast.macos/extensions/slack/swr-cache'
} 
    at null.SWRConfig$1 (/Users/pnt/Documents/Raycast/tmp/slack/node_modules/swr/dist/index.mjs:492:23)
    at null.CacheProvider (/Users/pnt/Documents/Ray<…>
```

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by momme-rtf** [comment]
Hi @pernielsentikaer 
the intention behind that screen was to inform the users (who have already installed the slack extension) that the required permission scopes for the slack token have been changed. As soon as you open the README (by pressing enter) it won't appear again. If you have any ideas for making it more clear to the user let me know.

By the way, the logs that you attached are not connected to this issue. They're just saying that no cache has been created yet - that will change after the first slack api call.

I also contacted you on slack if you have any further questions

**Comment by pernielsentikaer** [comment]
We're still debugging this in [Slack](https://raycastcommunity.slack.com/)

**Review by pernielsentikaer — APPROVED** [review]
Hi @momme-rtf 👋 

Thanks for the contribution, it works as expected now 💣

**Pull request merged**
