### PR TITLE
Add superwhisper extension

### PR DESCRIPTION
**Pull request by nchudleigh**
## Description

Superwhisper is an offline voice to text application for Mac OS adopting a spotlight style bar that shows the live soundwave and resulting text which may be post-processed by an offline language model.

## Screencast

https://github.com/raycast/extensions/assets/5580824/406a5e44-c0c0-478e-aadd-20ded2775200

SuperWhisper Twitter post (2)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by nchudleigh** [comment]
Welcome back!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you add a check if superwhisper is installed? Extensions like [Eagle](https://www.raycast.com/Yukai/eagle) does that 🙂

Could you add metadata images [this way](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Hi @nchudleigh 🔥 

Do you mind checking that I didn't break something before merging 🙂

**Comment by nchudleigh** [comment]
Sure I can test it out.. but is the loading state really necessary? Its reading from filesystem, max ten json files. Should be instant (not going over network)

**Comment by pernielsentikaer** [comment]
Hi @nchudleigh 

The problem I had was that the loading indicator never stopped spinning since I tested when it was not installed - which make sense with `!state.items && !state.error` - if you have a better idea to ensure that it stops loading if an error occurs, please feel free to modify 🙂

**Comment by nchudleigh** [comment]
@pernielsentikaer Ah okay that makes sense, didn't know thats what you were trying to fix! 

Followed up here with setting an error if the app isn't installed. Seems to not have UI flashing and also cancel the load if the app isnt installed.

Heres a video of me testing with superwhisper uninstalled.

https://github.com/raycast/extensions/assets/5580824/55608d36-bcfe-44ee-b281-735b762b2897



Check out the video below for review!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by nchudleigh** [comment]
Thank you for all your help @pernielsentikaer 🥳

**Pull request merged**
