### PR TITLE
fix(slack): fetching of conversations when hitting the the api limit of 1k conversations

### PR DESCRIPTION
**Pull request by momme-rtf**
## Description

Bug fix for:
- [Slack Thread](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1652361353663179?thread_ts=1652110252.377359&cid=C02HEMAF2SJ)
- [GitHub Issue](https://github.com/raycast/extensions/issues/2300)

Since I haven't faced these issues (because the slack workspace I'm working with doesn't push the limit), it would be nice if someone who faced them could test the solution.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Could you test it out @eddyw @aesign or are you also below 1k?

**Comment by aesign** [comment]
> Could you test it out @eddyw @aesign or are you also below 1k?

Sadly yes, small org

**Comment by jdrzjph** [comment]
Hi, @momme-rtf! I've just tested this solution and it works like a charm! Looking forward to seeing this released 🙂

BTW - is there any chance to get Search Command from this extension available in Raycast root's search Fallback Commands? It would be super helpful. I would create a feature request, but I couldn't find any proof that's even possible.

**Comment by momme-rtf** [comment]
@jdrzjph Thanks for testing!

@pernielsentikaer I've added another fix for fetching not only more than 1k conversations but also users.
And I made channels shared via Slack Connect show up. (This could have also led to the confusion that channels are missing - this was also mentioned in a separate [issue](https://github.com/raycast/extensions/issues/1454))

**Comment by pernielsentikaer** [comment]
> BTW - is there any chance to get Search Command from this extension available in Raycast root's search Fallback Commands? It would be super helpful. I would create a feature request, but I couldn't find any proof that's even possible.

That is not yet possible due to limitations in the API

@momme-rtf are you ready for a merge and see how it goes?

**Comment by momme-rtf** [comment]
@pernielsentikaer Yes, I'm ready - let's merge it :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
