### PR TITLE
[GitHub] Add more options to Clone action

### PR DESCRIPTION
**Pull request by JavaLangRuntimeException**
## Description

This PR integrates the enhanced repository cloning functionality from a separately developed extension (#13606) into the existing GitHub extension.

- **Branch Selection**: Users can now select a specific branch when cloning a repository.
- **Custom Clone Path**: Added the ability to specify a custom path when cloning a repository.

## Screencast
choose an individual or organizational account
ScreenShot 2024-07-26 14 11 14
Select a repository
ScreenShot 2024-07-26 14 11 31
If you are logged in with OAuth, enter the branch.
ScreenShot 2024-07-26 14 11 46
If you are logged in with PersonalAccessToken, you can select a branch.
ScreenShot 2024-07-26 14 12 37
You can enter the path to clone or select it from the finder.
ScreenShot 2024-07-26 14 17 37
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by LitoMore** [comment]
Can you make this command as a new action inside of the Search Repositories command?

**Comment by JavaLangRuntimeException** [comment]
I completely agree with your approach. And I added this functionality as an action to the "Search Repositories" command. Specifically, you've modified the existing "Clone and Open" command to "Clone with Options" as an action. When users select this option, they're presented with a screen to choose both the path and branch for cloning. After inputting these details and initiating the clone process, the system automatically opens the repository in the IDE. Moreover, I implemented a smart error prevention feature: if a directory with the same name already exists, your system automatically adds a number to the end of the directory name.

**Comment by thomaslombart** [comment]
Hey @JavaLangRuntimeException, I noticed the code could be simplified for this feature so I went a head and did some changes. Let me know if it looks good to you.

**Comment by JavaLangRuntimeException** [comment]
Thank you for the simplified code you fixed! I agree with your changes.

**Pull request merged**
