### PR TITLE
Add scrapbook extension

### PR DESCRIPTION
**Pull request by not-first**
## Description

This is an extension for a hackclub website: [Scrapbook](https://scrapbook.hackclub.com/). It is a website where people can post what they are currently working on. Using its public api, this extension allows browsing of recent posts, and even searching of users. There are also links to open user profiles and posts in the browser, and in slack.
The extension provides no actions to be taken, it simply is a manner to browse.

## Screencast

scrapbook-1
scrapbook-2
scrapbook-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
When you open Search Users and search for a user and uses the `View User's Posts` then this is printed to the console: 

```
08:33:52.367 Looks like the command is rendering a lot without any changes. This might indicate an rendering loop caused by a `setState` not being wrapped in a `useEffect`.
This will degrade the performances of Raycast and Raycast might arbitrarily decide to terminate the extension if it happens too many times.
08:33:53.215 Looks like the command is rendering a lot without any changes. This might indicate an rendering loop caused by a `setState` not being wrapped in a `useEffect`.
This will degrade the performances of Raycast and Raycast might arbitrarily decide to terminate the extension if it happens too many times.
08:33:53.216 Looks like the command is rendering a lot without any changes. This might indicate an rendering loop caused by a `setState` not being wrapped in a `useEffect`.
This will degrade the performances of Raycast and Raycast might arbitrarily decide to terminate the extension if it happens too many times.
08:37:10.028 Looks like the command is rendering a lot without any changes. This might indicate an rendering loop caused by a `setState` not being wrapped in a `useEffect`.
This will degrade the performances of Raycast and Raycast might arbitrarily decide to terminate the extension if it happens too many times.
08:37:10.765 Looks like the command is rendering a lot without any changes. This might indicate an rendering loop caused by a `setState` not being wrapped in a `useEffect`.
This will degrade the performances of Raycast and Raycast might arbitrarily decide to terminate the extension if it happens too many times.
08:37:10.766 Looks like the command is rendering a lot without any changes. This might indicate an rendering loop caused by a `setState` not being wrapped in a `useEffect`.
This will degrade the performances of Raycast and Raycast might arbitrarily decide to terminate the extension if it happens too many times.
```

Could you look into this 🙂

**Comment by not-first** [comment]
Ah, I'll take a look. I haven't come across that when testing and building it, I'll see if I can find out what is causing it.

**Comment by not-first** [comment]
Alrighty, I fixed the issue! It was caused by a stray setSearchText where it didn't have to be. Everything should still be functional. I have committed the changes.

**Comment by pernielsentikaer** [comment]
Would it make sense to add some conditional text in the List.Emptyview based on before searching and no results? 🙂

**Comment by not-first** [comment]
That would be a good idea! I'll try and implement that now.

**Comment by not-first** [comment]
There we go, added some more info in the List.EmptyView titles and descriptions.

**Review by pernielsentikaer — APPROVED** [review]
Let's merge it 🙂

**Pull request merged**
