### PR TITLE
Add base-stats extension

### PR DESCRIPTION
**Pull request by 0xOsprey**
## Description

This is an extension to view stats and leverage an automatically updating menu bar command for Coinbase's Layer-2 Blockchain: Base. It requires an API key from basescan.org as mentioned in the extension details.

## Screencast

base-stats-1
base-stats-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Thanks for your contribution 🔥 

There is already a lot of extensions in the store, https://www.raycast.com/search?q=eth - did you check them out before creating this?

**Comment by 0xOsprey** [comment]
Hello! Yes I'm familiar with many of them, but none of them support this functionality for Base. My goal is to build this out further as I find time and get feedback from other Base community members and users.

**Comment by pernielsentikaer** [comment]
What about: https://www.raycast.com/nikolayqwerty/dropstab - it already have some support for https://basescan.org

**Comment by 0xOsprey** [comment]
I just checked out DropsTab - has no support for Base gas tracking or stats (only token pairs).

**Comment by jessepollak** [comment]
Please approve this, thank you!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
