### PR TITLE
Add flomo extension

### PR DESCRIPTION
**Pull request by LogicOber**
## Description

This is an extension which allows you to send memos to flomo app through Raycast directly and attach tags conveniently just by checkbox.

## Screencast

image
flomo-0
flomo-1
flomo-2
flomo-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @LogicOber 👋 

Did you see [this extension](https://www.raycast.com/ahonn/send-to-flomo) before making yours? Seems like they are similar

**Comment by pernielsentikaer** [comment]
If your extension has the same functionality, then we can ask @ahonn if it makes sense to make this superseed the other one 🙂

**Review by pernielsentikaer — COMMENTED** [review]
End users can always just disable functionality that they don't use.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Remove command-icon.png since it's not in use

- Move `screenshot0` to the folder called `readme-assets` and use it in top of your README instead

- Remove `screenshot5` since it's not showing the Raycast extension

- Use [metadata generator](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) to take the metadata images instead.
- At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
What do you say @ahonn - could this superseed your Flomo extension?

**Comment by pernielsentikaer** [comment]
Are you still available @ahonn

**Comment by ahonn** [comment]
> What do you say @ahonn - could this superseed your Flomo extension?

I'm sorry I didn't notice this before. I think the two are different, I still prefer my own, I prefer to modify the my extension if more functionality is needed, and provide the necessary switches, this extension does not appear to be able to turn off some of the functionality. It's too complicated for me.

**Comment by pernielsentikaer** [comment]
What are the differences besides more functionality? Your extension can send messages to Flomo, so can this, right?

**Comment by ahonn** [comment]
> What are the differences besides more functionality? Your extension can send messages to Flomo, so can this, right?

Yes, both can send messages to flomo. 
This one just has some additional functionality. So I think it's just a matter of preference and we should add these functionalities on top of the original extension instead of creating a new one separately. I am happy to merge these optional configurations as long as they can be turned off when not needed.

**Pull request closed without merging**
