### PR TITLE
[Docsearch]: Add more documentation

### PR DESCRIPTION
**Pull request by AnishDe12020**
Extension author: @Fatpandac 
Extension Name: Docsearch - https://www.raycast.com/Fatpandac/docsearch

## Description

Added support for [Clerk](https://clerk.dev), [Apollo](https://www.apollographql.com/docs/), [Supabase](https://supabase.io/docs), [Slidev](https://sli.dev) (english language) docs

## Screencast

https://user-images.githubusercontent.com/63192115/201331346-26fa9e76-35d8-4bfe-adcf-fc2be750aca1.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Fatpandac** [comment]
Thanks so much! It is excellent for me.

**Comment by AnishDe12020** [comment]
Added some more docs (apollo, supabase, slidev english)

**Comment by AnishDe12020** [comment]
image

Not sure how I am supposed to make the typescript test pass. Here is the code block - 
```ts
          } else if ("url" in res.hits[0] && !(res.hits[0].url as string).startsWith("http")) {
            res.hits = res.hits.map((hit: any) => {
              hit.url = currentAPI.homepage + hit.url;

              return hit;
            });
```

I am checking if the property `url` exists in the code before using it. The extensions does work fine without any errors (that is the property does exist in the object sometimes and if it doesnt the code in there isnt executed)

**Comment by Fatpandac** [comment]
Maybe you can try the code below
```ts
          } else if ("url" in res.hits[0] && !((res.hits[0] as any).url as string).startsWith("http")) {
            res.hits = res.hits.map((hit: any) => {
              hit.url = currentAPI.homepage + hit.url;

              return hit;
            });
          }
```

**Comment by AnishDe12020** [comment]
> Maybe you can try the code below
> 
> ```ts
>           } else if ("url" in res.hits[0] && !((res.hits[0] as any).url as string).startsWith("http")) {
>             res.hits = res.hits.map((hit: any) => {
>               hit.url = currentAPI.homepage + hit.url;
> 
>               return hit;
>             });
>           }
> ```

Yep that worked!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
