### PR TITLE
Add Laravel activity log, Browsershot and laravel medialibrary commands to spatie documentation package

### PR DESCRIPTION
**Pull request by danyelkeddah**
## Description

Add new commands to spatie documentation package

## Screencast
Screen Shot 2022-02-23 at 2 18 23 PM
Screen Shot 2022-02-23 at 2 18 33 PM
Screen Shot 2022-02-23 at 2 18 41 PM

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @danyelkeddah 🔥 

Thanks for the update 💪 

A few comments: 
- Could you move screenshots to a folder called `media` instead, so they're not bundled with the extension 😄  
- Could it be an idea to move INDEX, APPID and APIKEY and most of the code to a helper instead, seems like most of the files actually just are with the same content?
- Until there are at least two versions of the documentation, is version check could be required = false?

Let me know what you think 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by danyelkeddah** [comment]
Hey @pernielsentikaer 👋, just moved some of the code and types to helper file and created config file for algolia search parameters.

**Review by pernielsentikaer — COMMENTED** [review]
Hi @danyelkeddah 👋 

Thanks for the update, seems to almost do as expected 💪 

I just have one question, no matter what I search for in Browsershot, it says “No Results” – is that as expected?

**Comment by danyelkeddah** [comment]
@pernielsentikaer Yes that is expected since the documentation owner didn't index the docs with Algolia yet, you can test the search on this [page](https://spatie.be/docs/browsershot/v2/introduction) (it has the same behavior)

**Review by pernielsentikaer — APPROVED** [review]
Hi @danyelkeddah 👋 

Ah, then it makes sense then, it should be available as soon as they push to Algolia, I think that's fine for now 🔥

**Pull request merged**
