### PR TITLE
Add translate extension

### PR DESCRIPTION
**Pull request by Hongbusi**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Hongbusi** [comment]
Thank you so much for bringing the Youdao translators in the store to my attention. I really appreciate your effort to help. However, I'm afraid that I'm not able to contribute to them at this time. But again, thank you for your suggestion.

**Comment by pernielsentikaer** [comment]
What is special about this extension that the others don't solve?

**Comment by Hongbusi** [comment]
No, otherwise I wouldn't take the time to realize it.

**Comment by pernielsentikaer** [comment]
If this is more or less a copy of the other one it doesn't make sense to add another one, then it would be better to enhance one of the current ones in the store

**Comment by Hongbusi** [comment]
Although the code may look similar to other extensions, the interaction is completely different. I'm not sure if other extension developers need the kind of interaction that I like. Therefore, I tend to release a standalone extension.

**Pull request closed without merging**
