### PR TITLE
Add code-saver extension

### PR DESCRIPTION
**Pull request by Gnosnay**
## Description

Store your code snippets and export them freely when you need it.

Pure local managed Snippet store. You should 
1. Pick one local data store first. 
2. Create one Library then
3. Create snippet that you need.
4. Brower the snippts you created.

## Screencast

code-saver-1
code-saver-2
code-saver-3
code-saver-4
code-saver-5
code-saver-6
code-saver-7
code-saver-8
code-saver-9
code-saver-10

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @Yansongsongsong 👋 

Do you think it's possible to use [useSql](https://developers.raycast.com/utilities/react-hooks/usesql) from `@raycast/utils` instead?

**Comment by Yansongsongsong** [comment]
> Hi @Yansongsongsong 👋
> 
> Do you think it's possible to use [useSql](https://developers.raycast.com/utilities/react-hooks/usesql) from `@raycast/utils` instead?

oh yes. I did consider using `useSql`. Because i notice that the `useSql` will accept one pure sql statement, which means i need to handle the sql injection manually.

after trying i decide to use one orm instead. i will switch to `useSql` if raycast supports some features that will prevent the sql injection.

Thank you for your review and your suggestion!

**Comment by pernielsentikaer** [comment]
After switching to `useSql` then we can remove all the binaries, right?

**Comment by Gnosnay** [comment]
> After switching to `useSql` then we can remove all the binaries, right?

yep!
for now, the only thing blocked me to use the `useSql` is that `useSql` can not avoid the sql injection. cuz it will execute raw sql directly.

If `useSql` can help to prevent sql injection I am willing to use `useSql` instead of embedding one wasm binary.

Thank you for your understanding!!! @pernielsentikaer

**Comment by Gnosnay** [comment]
@pernielsentikaer hi sorry for my fault. i deleted the branch by mistake.

https://github.com/raycast/extensions/pull/9241

Please have one look on this new PR to continue.. Thank you and sorry for inconvenience

**Pull request closed without merging**
