### PR TITLE
Add medre-se extension

### PR DESCRIPTION
**Pull request by tlherysr**
## Description

I have added my own application medre.se's extension to Raycast in this PR. My application (medre.se) performs searches in our Holy Book, the Quran, using various search algorithms. We use the Quran in our daily lives constantly, and this app will be using its API. It would be beneficial to access the app directly from Raycast. If more information is needed, pressing Enter will take users to the appropriate link, where they can use the app.

**Note:** The app is in Turkish for now. I will add English support later.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tlherysr** [comment]
- I have fixed the icon size
- Run prettier on the code and fixed the issues.

**Comment by pernielsentikaer** [comment]
Before I dive into the review of the extension, it seems similar to [this extension](https://www.raycast.com/BalliAsghar/the-noble-quran), is that correct? Maybe that one already does what yours do?

**Comment by tlherysr** [comment]
Hello,

This extension and also the app only gives the english meaning of the verses, mine gives Turkish. Additionally, my application enables semantic search across the entire Quran, not just verse lookup. When you search for 'cesaret,' which means 'courage' in Turkish, you will find all the verses that include the word 'courage' or have a similar meaning in the sentence. That's why I wanted to create another extension.

**Comment by pernielsentikaer** [comment]
It's also possible to enhance the current or even superseed if so much better, what do you think @BalliAsghar

**Comment by tlherysr** [comment]
For now, mine only works for Turkish and @BalliAsghar's extension works for English. I'm happy to work together. Maybe like you said, we can get the English meanings from there and Turkish from mine. I am thinking to add English support to my app but it's still not there yet.

**Comment by tlherysr** [comment]
Hello @pernielsentikaer, is there any improvement here?

**Comment by pernielsentikaer** [comment]
I tried to ping @BalliAsghar in our community, will try one last time

**Comment by BalliAsghar** [comment]
> It's also possible to enhance the current or even superseed if so much better, what do you think @BalliAsghar

I will look into it today!

**Comment by BalliAsghar** [comment]
#12578 I have added all available translations from the [Al-Quran API.](https://alquran.cloud/)

**Comment by pernielsentikaer** [comment]
@tlherysr can you check the update extension from @BalliAsghar

**Comment by pernielsentikaer** [comment]
ping again @tlherysr

**Pull request closed without merging**
