### PR TITLE
Update clean-keyboard extension

### PR DESCRIPTION
**Pull request by xilopaint**
## Description

- Updated command title for clarity and to avoid confusion with the extension name.
- Conformed command subtitle to Raycast guidelines.
- Updated search bar placeholder.
- Updated navigation title.
- Avoided redundancy in list item titles.

## Screenshot

Screenshot 2024-08-30 at 01 01 54

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Looks like a nice update, could you update the other metadata image too since the contrast of Raycast is different on the new image

**Comment by pernielsentikaer** [comment]
@ike-gg do you want to check this too?

**Comment by xilopaint** [comment]
> Looks like a nice update, could you update the other metadata image too since the contrast of Raycast is different on the new image

Done.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
