### PR TITLE
Update adonisjs-documentation extension

### PR DESCRIPTION
**Pull request by craigharman**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @craigharman 👋 

Is this only about AdonisJS with this update? It seems like it's a lot of other frameworks?

There is an extension called [DocSearch](https://www.raycast.com/Fatpandac/docsearch) where it might fit in

**Comment by craigharman** [comment]
AdonisJS also maintains and *strongly* recommends the use of the additional packages I've added with this update. I'd expect that a high percentage of AdonisJS users would also be using Edge (AdonisJS template system), Lucid (Adonis ORM) and VineJS (Adonis validation).

**Comment by mil3na** [comment]
Hi! Do you mind pointing where I could read more about this that would justify adding this extra documentation to the extension?

**Comment by craigharman** [comment]
Sure. So on the official AdonisJS docs they have details on each of the sub-frameworks I have added. 

- Lucid (ORM): https://docs.adonisjs.com/guides/database/lucid The first sentence states "Lucid is a SQL query builder, and an Active Record ORM built on top of [Knex](https://knexjs.org/) created and maintained by the AdonisJS core team"
- Edge (Templating): https://docs.adonisjs.com/guides/views-and-templates/edgejs "Edge is a simple, Modern, and batteries included template engine created and maintained by the AdonisJS core team"
- VineJS (Validation): https://docs.adonisjs.com/guides/basics/validation#configuring-vinejs
- etc. etc.

I hope this assists. Please let me know if you need anything else.

**Comment by thetutlage** [comment]
Hey guys!

I am the creator of AdonisJS and all other related libraries mentioned in this PR. While these libraries are framework agnostic, they are heavily used by the users of AdonisJS.

It might make sense to have them as separate apps, but I suspect the usage of separate apps will be quite low. So yeah, it will be nice if the AdonisJS app can bundle the docs for the mentioned libraries as well.

**Review by mil3na — APPROVED** [review]
Sounds good to me!

**Pull request merged**
