### PR TITLE
Add: OSS Insight Extension

### PR DESCRIPTION
**Pull request by k8scat**
## Description

Search Trending Repos in [OSS Insight](https://ossinsight.io/)

## Screencast

image

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by k8scat** [comment]
@pernielsentikaer any comments?

**Comment by pernielsentikaer** [comment]
Hi @k8scat 👋 

It seems like it's failing with an error when you're typing slowly, can you look into this 😊

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Hi @k8scat 👋 

I update the code, so it's super fast and only fetching once and letting Raycast sort it instead 🔥

**Pull request merged**
