### PR TITLE
Add forcequit extension

### PR DESCRIPTION
**Pull request by boxpositron**
## Description

This extension allows you to quickly force quit running or stalled applications from Raycast.

## Screencast

output

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Hi @boxpositron Seems similar to the Quit Applications extension?

**Comment by boxpositron** [comment]
I just checked it out. It's similar. I'll add the other features I had saved for the next update. Thanks for the feedback.

**Comment by pernielsentikaer** [comment]
It would be better to enhance the current one instead of adding a new one with the same purpose - from a user perspective, having two doing the same is confusing. What do you think about enhancing?

**Comment by boxpositron** [comment]
Alright, since thats an option. I'll be open to doing that.

**Comment by pernielsentikaer** [comment]
I think that it could be nice to enhance the current one from @mackopes

**Comment by boxpositron** [comment]
I've enhanced the existing extension. Here's the PR

https://github.com/raycast/extensions/pull/8436

**Comment by pernielsentikaer** [comment]
Closing in favor of #8436

**Pull request closed without merging**
