### PR TITLE
[Tuya] Add toggle and work mode settings for light source devices

### PR DESCRIPTION
**Pull request by andreivettor**
## Description

Added commands to set Status and Work Mode for Light Source devices.

## Screencast

Screenshot 2023-02-28 at 04 38 58

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by andreivettor** [comment]
There is one non-breaking issue. Because of how the initial implementation was done, it's not easy to set the initial light status so you have to click twice to synchronise the state with the physical device status.

**Comment by andreivettor** [comment]
Closes #5027

**Review by AndresMorelos — APPROVED** [review]
LGTM

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Tested with success, let's go! 🧑‍🚒

**Pull request merged**
