### PR TITLE
Update search-astro-docs extension

### PR DESCRIPTION
**Pull request by ElianCodes**
## Description

- updates the README
- update the items to be fetched over an API
	- This way we can add / remove items without needing to update the extension itself
- cache the API response
- add reload items in actionpanel
- add language support over the API

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Updated the code since useFetch already caches the results 🙂 Are you okay with this?

**Comment by ElianCodes** [comment]
> Updated the code since useFetch already caches the results 🙂 Are you okay with this?

Nice! I didn't know that!
Sounds good to remove the manual cache then!

**Comment by ElianCodes** [comment]
Looks good to merge to me @pernielsentikaer!

**Comment by pernielsentikaer** [comment]
Hi @ElianCodes 👋 

Do you know how to not push the images again? It seems like you're pushing them once more 🙂

**Comment by pernielsentikaer** [comment]
Are you still around @ElianCodes

**Comment by ElianCodes** [comment]
Hey @pernielsentikaer! I'm around for sure!
Not totally sure on the images tho. I din't change them and made the PR right from the `npm run publish` command

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
