### PR TITLE
[cURL] Allow custom header keys

### LINKED ISSUE #7539: [cURL] Add custom headers
### Extension

https://www.raycast.com/jonathangiardino/curl

### Description

Currently, we can only choose headers from the pre-determined list that CURL gives us. However, often custom web applications have custom headers. Thus, we should allow the `key` and `value` of each header to be customisable.

Thank you for your work @jonathangiardino  

If permitted, I'd be happy to help implement this feature.

### Who will benefit from this feature?

Those using cURL for web development!

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bkeys818**
## Description

You can now use a custom value for a header key. Just type a value into the dropdown search box, and you'll see it as an option. Closes #7539.

In addition, the dropdown search box filters the options.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@jonathangiardino do you mind checking this? 🙂

**Comment by jonathangiardino** [comment]
Will check this out ASAP @pernielsentikaer @bkeys818 💪

**Comment by pernielsentikaer** [comment]
@jonathangiardino did you have time to check this yet?

**Comment by jonathangiardino** [comment]
Hey @pernielsentikaer not yet unfortunately, I was afk this last week.

Will check it out by end of the week.

**Comment by pernielsentikaer** [comment]
Awesome, thanks! 🙂

**Review by jonathangiardino — CHANGES_REQUESTED** [review]
Other than the comment I made a looks good @bkeys818.
Could you also update the README and the changelog?

**Review by jonathangiardino — APPROVED** [review]

**Comment by bkeys818** [comment]
Never really meant to close this

**Comment by pernielsentikaer** [comment]
Awesome @bkeys818 - let me know when it's ready 🙂

**Comment by bkeys818** [comment]
Everything should be good!

**Comment by bkeys818** [comment]
I'd suggest squash and merge.

**Comment by bkeys818** [comment]
@pernielsentikaer, Can you review this PR?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
