### PR TITLE
fix: storage.json path changes in new version of VScode

### PR DESCRIPTION
**Pull request by cy-98**
## Description

VScode changed the storage.json path.

## Screencast
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by telmen** [comment]
When can this be merged? : )

**Review by pernielsentikaer — APPROVED** [review]
Hi @cy-98 👋 

Thanks for the update; it works as intended! 🔥 

If you want to be added as a contributor, send me your raycast username here, and I'll add it for you 😄

**Comment by pernielsentikaer** [comment]
Now @telmen 🔥 😄

**Comment by cy-98** [comment]
> Hi @cy-98 👋
> 
> Thanks for the update; it works as intended! 🔥
> 
> If you want to be added as a contributor, send me your raycast username here, and I'll add it for you 😄

Thanks !
username: cy-98 
nickname: 才越

**Pull request merged**
