### PR TITLE
[espanso] add Toggle Espanso and Add Match commands

### PR DESCRIPTION
**Pull request by nbbaier**
## Description

This update adds two commands to the espanso extension:

- Add Match: add a new match to any of your Espanso config files
- Toggle Espanso: disable or enable Espanso

It also adds an action to the Search Matches command that pastes a replacement to the frontmost application.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you mind checking this @kud 🙂

**Comment by nbbaier** [comment]
Hey @kud, any feedback? I'd love to get this merged!

**Comment by nbbaier** [comment]
Just trying to bump this to get it merged @kud

**Comment by kud** [comment]
Hey,

Had an issue with my GitHub notifications. I will check this soon, thanks!

**Review by kud — APPROVED** [review]

**Comment by kud** [comment]
It's ok for me, cheers!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by kud** [comment]
Grumpf.

```
Error: ENOENT: no such file or directory, scandir '/Users/xxx/Library/Application Support/espanso/match'

Object.readdirSync:node:fs:1452:3
o0:addMatch.js:36:4541
Object.<anonymous>:addMatch.js:39:231
Module._compile:loader:1254:14
```

**Pull request merged**
