### PR TITLE
Comodoro: Initial commands

### PR DESCRIPTION
**Pull request by jesse-c**
## Description

Similar to https://www.raycast.com/jns/himalaya, but for https://github.com/soywod/comodoro instead. Let's you get the current status (and keeps it in the menu bar), and start/stop a Pomodoro.

## Screencast

comodoro-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Could you look into that the commands dies gracefully, seems like all of them are crashing

Raycast-m4PuKEwC@2x

* Is this the same as https://www.raycast.com/asubbotin/pomodoro?
  

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by jesse-c** [comment]
> Could you look into that the commands dies gracefully, seems like all of them are crashing

✅

> Is this the same as https://www.raycast.com/asubbotin/pomodoro?

Whilst they're both about the Pomodoro concept, that one is one that is standalone and Raycast only. This one uses https://github.com/soywod/comodoro instead!

**Comment by pernielsentikaer** [comment]
Makes sense, just wanted to learn a bit more about it 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
