### PR TITLE
add: ones extensions

### PR DESCRIPTION
**Pull request by k8scat**
## Description

[Raycast](https://www.raycast.com/) extensions for [ones.ai](https://ones.ai).

Original repository: [k8scat/raycast-ones-extensions](https://github.com/k8scat/raycast-ones-extensions)

- Search Content
    - Project
        - [x] project
        - [x] task
            - [x] record manhour
            - [x] delete task
        - [x] sprint
        - [x] resource
    - Wiki
        - [x] space
        - [x] page
        - [x] resource
- Manage Manhour
    - [x] query
    - [x] modify
    - [x] record
    - [x] delete

## Type of change

New extension

## Screencast

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @k8scat 👋 

Thanks for the PR, it looks like an awesome extension you're building! 🔥 

Unfortunately, I don't have a way to test it since I don't have an account (or can create) — could you do a quick screen recording of the different commands?

One thing I've stumbled on is that errors needs to be handled gracefully, could you look into this? (Using showToast(ToastStyle.Failure, , ..., .)

0EANjXud8ueZuMa6

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pernielsentikaer** [comment]
Hi @k8scat 👋 

Is this ready for a review, or is there still work that has to be done?

**Comment by k8scat** [comment]
> Hi @k8scat 👋
> 
> Is this ready for a review, or is there still work that has to be done?

yes, it is, but there is not a quick screen recording.

**Comment by pernielsentikaer** [comment]
Hi @k8scat 👋 

Can you look into the errors the linter is complaining about, seems like the PR is so old that it's before the new prettier requirement, can you fix this also?

Let me know if you need any help with that 🔥

**Comment by k8scat** [comment]
> Hi @k8scat 👋
> 
> Can you look into the errors the linter is complaining about, seems like the PR is so old that it's before the new prettier requirement, can you fix this also?
> 
> Let me know if you need any help with that 🔥

fixed

**Review by pernielsentikaer — APPROVED** [review]
Hi @k8scat 👋 

Is all the assets in use, I couldn't see where, if not, could you remove them? There also seems to be console.log debugs, could they be removed?

The extension is so huge, and I don't have a way to test it. I'm going to accept it and then will my colleague do a final review before it's finally merged. 

I checked the code and couldn't find anything critically, so if something is messing up when going live, we're going to open an issue to look into the problems

Thanks for your contribution 🔥

**Comment by k8scat** [comment]
> Hi @k8scat 👋
> 
> Is all the assets in use, I couldn't see where, if not, could you remove them? There also seems to be console.log debugs, could they be removed?
> 
> The extension is so huge, and I don't have a way to test it. I'm going to accept it and then will my colleague do a final review before it's finally merged.
> 
> I checked the code and couldn't find anything critically, so if something is messing up when going live, we're going to open an issue to look into the problems
> 
> Thanks for your contribution 🔥

Yeah, I removed the redundant assets and debug log.

Cause that https://ones.ai is only available in China now, maybe you can try to use it behind a proxy. (Good news is that the universal ones.com is coming soon in 2022).

And if there is any problems, I will be here!

**Pull request merged**
