### PR TITLE
New extension: Pomodoro Timer

### PR DESCRIPTION
**Pull request by frankdilo**
## Description

It's a simple Pomodoro timer.

## Screencast

https://user-images.githubusercontent.com/715405/208315298-ed6e0369-5304-43c1-96d8-32abb767187e.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @frankdilo 👋 

Do you mind if we close this in favor of #3970, since it's had a lot more functionality

**Comment by frankdilo** [comment]
Not at all, excited to try it

**Comment by pernielsentikaer** [comment]
Thanks @frankdilo 🔥 Should be out later

**Comment by pernielsentikaer** [comment]
It's added now @frankdilo https://www.raycast.com/asubbotin/pomodoro

**Pull request closed without merging**
