### PR TITLE
Add seo-lighthouse extension

### PR DESCRIPTION
**Pull request by guelug**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by guelug** [comment]
Extension for SEO professionals who want run fast over raycast a lighthouse test for get the data from google lighthouse. 
Interesting to get feedback and improve the last report to bring more intereting data from json report that brings data that html report is not showing.

**Comment by guelug** [comment]
Added the settings for introduce the lighthouse path manually and improve the function to search the lighthouse path.

**Comment by guelug** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> I just installed lighthouse with `npm` and it was installed here: `~/.nvm/versions/node/v21.5.0/bin/lighthouse` so I can't use it
> 
> Maybe add a preference to set it manually?
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Done!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
A few more things I found

- How long time should the report take to generate? Waited 5 minutes and nothing happened.

seo-lighthouse 2024-11-25 at 11 31 43

- Only have one action for preferences, maybe call it `Open Extension Preferences` 
- Set a default path for output, maybe Download or Desktop folder.

**Comment by guelug** [comment]
> A few more things I found
> 
> * How long time should the report take to generate? Waited 5 minutes and nothing happened.
> 
> seo-lighthouse 2024-11-25 at 11 31 43
> 
> * Only have one action for preferences, maybe call it `Open Extension Preferences`
> * Set a default path for output, maybe Download or Desktop folder.

hmm weird, it took me like 1 minut:

image

Probably still something to do with the lighthouse auto path selecting maybe?  I will check again, and add the recommendations!

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
