### PR TITLE
Add co-authored-commits extension

### PR DESCRIPTION
**Pull request by mateusjunges**
## Description
This extension allows you to add multiple Co-Authors to your commits

## Screencast
https://github.com/raycast/extensions/assets/19756164/07494b1e-cec4-4780-9784-5fce1241c29f

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
This seems to be doing the same as [this extension](https://www.raycast.com/nickradford/git-co-authors) - did you see that one before making this PR

**Comment by mateusjunges** [comment]
@pernielsentikaer yes, I saw that one. The problem is that it does not allow me to select multiple co-authors. I have to open the extension one time for each co-author I'm adding to the commit

**Comment by pernielsentikaer** [comment]
Then it would be better to enhance the current extension with that functionality, so we don't end up with too many of the same extensions, which causes confusion among the users.

**Comment by mateusjunges** [comment]
@pernielsentikaer that's true. I opened a new PR to update the existing extension: https://github.com/raycast/extensions/pull/10737

**Pull request closed without merging**
