### PR TITLE
Update bear extension

### PR DESCRIPTION
**Pull request by ramsaysewell**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @ramsaysewell 👋 

Do you mind checking the merge conflicts here?

**Comment by ramsaysewell** [comment]
> Hi @ramsaysewell 👋 
> 
> 
> 
> Do you mind checking the merge conflicts here?

Sure, I'll get this resolved shortly.

**Comment by pernielsentikaer** [comment]
Thanks for the update 🔥 

@hmarr do you want to check this?

**Comment by mil3na** [comment]
Hey @ramsaysewell ! Thank you so much for your contribution!
LGTM!

**Pull request merged**
