### PR TITLE
New Extension: PlayCover Community Edition

### PR DESCRIPTION
**Pull request by JoseMoreville**
## Description

This extension allows you to use PlayCover via RayCast
- Sideloading
- Show and open apps installed with PlayCover
- Launch PlayCover

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @JoseMoreville 👋 

Could you try to make some new screenshots from your MacBooks screen? Looks like you used an external monitor to make them 😊

**Comment by JoseMoreville** [comment]
> Hi @JoseMoreville 👋
> 
> Could you try to make some new screenshots from your MacBooks screen? Looks like you used an external monitor to make them 😊

Hi @pernielsentikaer  , i'm on it

**Comment by pernielsentikaer** [comment]
I can help with the screenshots @JoseMoreville 😄

* One thing I noticed is the `Sideload with PlayCover` where you have to drag a file in, the first time you do that without the `Keep window always visible during development` turned on, then Raycast closes and unloads the extension.

We're working on a file/folder picker, we might need to wait for that before this would work.

* One of the commands throws an error If you don't have PlayCover installed, whereas the other one handles this. Can you look into handling that too here?

CleanShot 2022-10-27 at 08 45 29@2x

I'm looking forward to testing this extension again 🔥

**Comment by JoseMoreville** [comment]
Thanks @pernielsentikaer I'll be working tomorrow according to the feedback provided and tag you here as soon as it is done. Thanks again for the screenshot help, I appreciate it.

**Pull request closed without merging**
