### PR TITLE
Create MBTA Tracker extension

### PR DESCRIPTION
**Pull request by djpowers**
## Description

This extension allows you to look up departure times for subway, bus, and commuter rail lines operated by the [Massachusetts BayTransportation Authority](https://www.mbta.com/). Data is retrieved using the [MBTA API](https://api-v3.mbta.com/).

## Screencast

https://github.com/raycast/extensions/assets/4978418/62b6ed1e-8c73-4e78-89a8-67da3e242bdd

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
One thing I miss is seeing if the current stop is a favorite (maybe add an icon) and change the action to unfavourite, is that possible?

mbta-tracker 2023-08-09 at 13 59 25

**Comment by djpowers** [comment]
Thanks for the review and good suggestion, @pernielsentikaer. I just pushed up some changes to implement better favorite handling, dynamically adjusting the action and text, as well as displaying an icon to indicate if a stop is saved as a favorite.

Quick demo showing the new functionality:

https://github.com/raycast/extensions/assets/4978418/2e370020-d6f8-498e-ad32-eb473685bd40

I wasn't sure if there was an easy way to get the component to rerender once the local storage contents change, but I think this is definitely an improvement in the user experience.

**Comment by pernielsentikaer** [comment]
After adding a favourite it's not redrawn and it's possible to add it once more before it's updated, can you look into this or do you need help?

**Comment by djpowers** [comment]
Yes, that was the part I was a bit stuck on. Any assistance you can provide would be much appreciated. Or I'm not sure if there's a similar example somewhere to look at of how to handle this.

**Comment by djpowers** [comment]
After revisiting this, I was able to fix the redraw issues by using the `useState` and `useEffect` hooks. Now any of the favoriting actions should update the list and related UI elements accordingly.

Should be ready for another look, @pernielsentikaer. Thanks!

One more demo with an example of the changes:

https://github.com/raycast/extensions/assets/4978418/374461da-0e69-4387-9770-cce5b8e9f8f2

**Comment by djpowers** [comment]
@pernielsentikaer, could this please could get another review? It should be all set based on your most recent feedback. Looking forward to it being merged!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
