### PR TITLE
Add Otter bookmarking companion

### PR DESCRIPTION
**Pull request by mrmartineau**
# Otter bookmarking companion

## Description

Add Otter bookmarking companion extension. Otter is an open-source, self-hosted bookmarking app.

### Recent items with `showDetailView` preference set to `true` (default)

https://github.com/raycast/extensions/assets/64883/0ac0a59c-5838-4ebb-aad7-7aeccd38c631

### Search with `showDetailView` preference set to `true`

https://github.com/raycast/extensions/assets/64883/032b346e-c5fb-4d20-b05a-b9111e69f1c1

### Search with `showDetailView` preference set to `false`

https://github.com/raycast/extensions/assets/64883/2b3512b2-8bba-41f2-be91-d06c15150d18

### Add new bookmark

https://github.com/raycast/extensions/assets/64883/83dae21a-5de4-4fd6-9d9e-4d1baab5dfb4

### Search
otter-1

### Menubar command

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Could we add some more validation of fields so it doesn't crash, I just entered a lot of test data 🙂

otter 2024-03-08 at 14 45 09

**Comment by mrmartineau** [comment]
As in you entered test values in the extension settings? If so, I can guard against that.

**Comment by mrmartineau** [comment]
@pernielsentikaer I have added much better error handling now.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
