### PR TITLE
Improve Dub link list view

### PR DESCRIPTION
**Pull request by steven-tey**
## Description

Show the short URL in the Dub extension link list view

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by quuu** [comment]
@steven-tey  fair, I mainly used the originalLink since having a list of 

Dub.co/12345
Dub.co/32626

Was hard to read compared to

GitHub.com
Google.com

**Comment by steven-tey** [comment]
@quuu yeah, I can see where you're coming from, just wanted to match the UX on dub.co as closely as possible + the destination URL is also shown on the right panel when you toggle through the list 😄

**Comment by quuu** [comment]
> @quuu yeah, I can see where you're coming from, just wanted to match the UX on dub.co as closely as possible + the destination URL is also shown on the right panel when you toggle through the list 😄

True, let's try it! Otherwise if my fear is right about many dub.co/<ID> that isn't distinguishable enough, we can always add a settings toggle to change between the 2 -- showing the dub.co vs showing the original link

**Comment by pernielsentikaer** [comment]
You can also make a setting to let the user select what the want to see?

**Comment by steven-tey** [comment]
Ooooh `subtitle` might be the way to go here – we could use the shortened link as the title + the destination URL as the subtitle?

**Comment by steven-tey** [comment]
I added it to the PR – if everything looks good here, would love to get this merged :)

**Comment by quuu** [comment]
> I added it to the PR – if everything looks good here, would love to get this merged :)

ooh this looks great -- I'd be down to add a settings toggle for which is the primary vs sub later, doesn't look like too big of a change :D

otherwise looks good to me!!

**Comment by pernielsentikaer** [comment]
Is this ready, seems like something is missing

**Comment by quuu** [comment]
> Is this ready, seems like something is missing


What looks missing? Looks good to me for a quick fix! 

Not planning on adding the setting right now

**Comment by steven-tey** [comment]
@pernielsentikaer this PR is ready to merge! Please LMK if there's anything else that's needed to make that happen!

**Comment by quuu** [comment]
hey @pernielsentikaer bumping this review

I can't push changes to this branch but if I could, i'd append

```
## [Enhancement] Show the shortened and long URL in the list view
- Be consistent with the web app and show both the short and long URL for each item in the list view

```

as a new entry in the changelog

**Comment by steven-tey** [comment]
@pernielsentikaer bumping this up again! Thank you :)

**Comment by steven-tey** [comment]
@quuu added that! :)

**Review by peduarte — APPROVED** [review]
Nice improvements 👌

**Pull request merged**
