### PR TITLE
Update discogs extension

### PR DESCRIPTION
**Pull request by vigosan**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

**Comment by vigosan** [comment]
Screenshot added! thanks a lot for the review.

**Comment by pernielsentikaer** [comment]
I added inverted extension icon so it works in dark mode too

Raycast20022024-lv0V6vi9 png@2x

**Pull request merged**
