### PR TITLE
Add Display Placer extension

### PR DESCRIPTION
**Pull request by eluce2**
## Description

This extension allows super easy use of the [displayplacer homebrew utility](https://github.com/jakehilborn/displayplacer) for changing your system display settings between various presets. The extension lets you save a preset based on your current display settings, then switch to any of your presets using the primary command, or via a global hotkey with the additional commands included with this extension that bypass the UI.

## Type of change

- New extension

## Screencast

https://www.dropbox.com/s/ufb4k7ghnrs5ggc/displayplacer.mp4?dl=0

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @eluce2 👋 

Thanks for your contribution, didn't know about this tool, but I can see it become quite handy. 

### I found a few things in the first run:
- An ActionPanel.Item is missing the icon
7hTYpMt2zhJS9uGL

- I would suggest finding another icon for the "currently used" star, not sure which yet, but there is something that doesn't make sense - I'm confused 😄 I can check later, I'm not at my default machine at the moment 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by eluce2** [comment]
Ok, I've updated those icons and a few more. I also changed the star to a blue dot. It's meant to show you that that preset already matches your current display settings, so if you select it nothing will happen

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @eluce2 👋 

Thanks for the update 💯 I was confused about the star icon because I thought it was my favourite so I checked the code and found out, I think others might be confused too 😄 You could use `Icon.Checkmark` if you haven't found a better icon

I had an external monitor connected and tried it with just with the laptop, it gave some issues:

- Default is selected, no blue dot, nothing in the console:
2lYxwJuKQY9DHECe

- I'm able to change the view but it fails:
myMaUxdzccPLYipG

```
Error: Command failed: zsh -l -c 'displayplacer "id:373C5A7B-7F32-A496-0857-D6964E3302DB res:3440x1440 hz:50 color_depth:8 scaling:off origin:(0,0) degree:0" "id:37D8832A-2D66-02CA-B9F7-8F30A301B230 res:1680x1050 hz:60 color_depth:8 scaling:on origin:(-1680,300) degree:0"'
Unable to find screen 373C5A7B-7F32-A496-0857-D6964E3302DB - skipping changes for that screen


Unable to find screen 373C5A7B-7F32-A496-0857-D6964E3302DB - skipping changes for that screen

checkExecSyncError:node:child_process:826:11
execSync:node:child_process:900:15
switchSettings:displayplacer.ts:91:3
onAction:displayplacer.tsx:203:27
```
I guess that it's because of I don't have the external monitor connected anymore (and its a part of the setup), is there a way to prevent crash and doing it gracefully somehow?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by eluce2** [comment]
Ah, thanks for catching that. I've added some catching for that so it should now fail gracefully and show a toast and not close the main window.

**Comment by eluce2** [comment]
To confirm, are you saying that you expected to see a blue dot next to your "Default" preset? If that preset was made with an external monitor connected and you're taking this screenshot without it (or vice-versa) that would be correct behavior, as the display settings are actually different and dependent on the external monitors

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @eluce2 👋 

Thank you for the update, now it don't crash 💪 

I added 1/2 while having the external screen on, and now that I don't have the screen on, I have an issues:

- I can switch to the profile, and the blue dot don't change (because of the one screen) — trying to switch to the same again flashes animated toast and then for 2ms an error toast, but it closes pretty fast. We have to address this issue (not happening with the one added only for this display)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Review by pernielsentikaer — APPROVED** [review]
Hi @eluce2 👋 

Thanks for the conversation in Slack regarding this extension 🥇 

I'm going to approve this and then my colleague will do the last check-up before merging it 💯 

Thanks for your contribution

**Comment by Anoninz** [comment]
Amazing !!!! I love this extension !!!

**Pull request merged**
