### PR TITLE
[google-translate] add Text To Speech support

### PR DESCRIPTION
**Pull request by strikerlulu**
## Description

Add Text to Speech support for google-translate with `Cmd + t` shortcut

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @strikerlulu 👋 

Thanks for your contribution 🔥 

@gebeto do you want to check this?

**Review by gebeto — APPROVED** [review]
Looks good to me

Thanks for your contribution!

**Comment by gebeto** [comment]
> Hi @strikerlulu 👋
> 
> Thanks for your contribution 🔥
> 
> @gebeto do you want to check this?

Yep, thanks for reminding! Looks good to me

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by strikerlulu** [comment]
you could close https://github.com/raycast/extensions/issues/10256

**Pull request merged**
