### PR TITLE
Add lyric-search extension

### PR DESCRIPTION
**Pull request by johnstclair**
## Description

This is the initial commit. It includes one command that is about to use the Genius Lyrics API to search for songs, using bits of lyrics.

## Screencast

Open Command

Search for the lyrics you remember

Open in browser, or copy the result you wish to clipboard

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

We already have an extension that queries the Genius API. https://www.raycast.com/tkdkid1000/genius-lyrics
Does yours do anything different that would justify having a second extension?

**Comment by johnstclair** [comment]
Hello!

The extension you mentioned, Genius Lyrics, uses the Genius API to search for song lyrics using song titles. It utilizes this API link:

https://genius.com/api/search?q

Whereas the Lyric Search extension I developed search's using partial lyrics to find song titles. It utilizes this API link:

https://genius.com/api/search/lyrics?q=

I figured that would be a big enough difference to separate the two.

**Comment by mil3na** [comment]
I don't think this is enough for a new extension. It is the same service! Please, update the existing extension if you would like to add this feature. I will be closing this PR for now. Feel free to contact me on Slack (https://raycast.com/community) if you have any doubts or want to discuss this further.

**Comment by mil3na** [comment]
That's odd. You can try this link https://join.slack.com/t/raycastcommunity/shared_invite/zt-2m9uewog6-qPeqEbmYl988VSOJHLcaEw

**Pull request closed without merging**
