### PR TITLE
Update pixabay extension

### PR DESCRIPTION
**Pull request by j3lte**
## Description

- Update dependencies to latest versions
- Refactor code base, splitted in proper components
- Fix `Search Videos`, preview url not working
- Update video save filename to include the size
- Enable Download Folder in preferences
- Enable Safe Search

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
This looks like a nice update @j3lte 

@tonka3000 do you mind checking this too

**Comment by j3lte** [comment]
Any updates? @tonka3000 @pernielsentikaer

**Comment by mjherich** [comment]
@pernielsentikaer What is the easiest way for me to test these changes locally? I tried running `npx @raycast/api@latest pull-contributions` but I assume that only works once this PR is merged.

Do I need to clone the entire `raycast/extensions` repo and use `gh pr checkout 11871`?

**Comment by pernielsentikaer** [comment]
@mjherich you can do a sparse checkout of the repo

**Comment by mjherich** [comment]
> @mjherich you can do a sparse checkout of the repo

Thanks for the tip @pernielsentikaer, I'll try that today or tomorrow just to see these changes in action but I'm on board with the updates overall. I believe @tonka3000 will need to give the final approval though.

**Comment by pernielsentikaer** [comment]
If you can get it a spin and it works, then we can merge it @mjherich - thanks for testing 🔥

**Comment by mjherich** [comment]
Got a chance to try out your updates @j3lte, liking the changes! Let's merge this @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
