### PR TITLE
Jira Search (self-hosted) - add "assignee" field as new filter for searching issues in Jira

### PR DESCRIPTION
**Pull request by rnprest**
## Description

Added a new filter based on the assignee of a ticket. This filter can accept either the email address of the user, or the user's full name in quotes.

Usage:
```
See all of your open tickets:
-----------------------------
!open %john.smith@gmail.com
!open %"john smith"
```

## Screencast

I would add a screencast/screenshot, but unfortunately I haven't set up a local jira server yet and the data in my test instance is confidential. If anyone would be able to generate these metadata images for me, I'd greatly appreciate it!

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by rnprest** [comment]
I chose to use % as the prefix as @ was already taken — if there is a better symbol / character to use, then please let me know!

**Comment by emanguy** [comment]
Hey, thanks for your contribution! I'll try to test it and get you feedback by the end of this week.

**Review by emanguy — APPROVED** [review]
Changes look good, and it appears to work based on my testing. Approved!

**Review by pernielsentikaer — APPROVED** [review]
Hi @rnprest 👋 

Thanks for your contribution. Looks good to me 😄 

Thanks for your review, @emanguy 🔥

**Pull request merged**
