### PR TITLE
Add alarm extension

### PR DESCRIPTION
**Pull request by aurnik**
## Description

This extension parses text passed as an argument to create alarms. Alarms can be set using a specific date and time or using a duration.

## Screencast
Creating an alarm
Viewing a list of alarms

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @aurnik 👋 

Thanks for your contribution 🔥  It looks like we have something very similar in the [store already](https://www.raycast.com/comoser/simple-reminder), could you check that out?

**Comment by aurnik** [comment]
Hey @pernielsentikaer thanks for getting back to me -- yes I did see that extension but thought this provided some useful differences:
1. The mentioned extension uses a background service running on a 1 minute interval to set its notifications, whereas this one schedules the notification using a shell command. This avoids the regularly running background service and notifies the user at the exact time they've scheduled.
2. This extension allows creating alarms that don't have a "topic", such as setting an alarm for 15 minutes (and these are created without going to a separate view using command arguments)
3. This has the additional setting to use dialog boxes instead of notifications (can be seen even when Focus is on)

It seemed like adding these to that extension would fundamentally change the design choices that the developer made, so I rolled this out separately. I'm open to any feedback though, appreciate your time.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The command `List Alarms` suffers from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

- I would add a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) before deleting

- Would be nice with an icon here 🙂

alarm 2023-06-06 at 11 52 27

- Why is `refresh.ts` necessary, I can't figure out what it brings, can you clarify that for me 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by aurnik** [comment]
> * The command `List Alarms` suffers from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

✅ Fixed 

> * I would add a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) before deleting


✅ Fixed 

> * Would be nice with an icon here 🙂

Which part are you referring to? At least in that photo, I'm seeing icons for the extension itself as well as each list item.

> * Why is `refresh.ts` necessary, I can't figure out what it brings, can you clarify that for me 🙂

Because this extension schedules the timers instead of constantly checking if the time is up, this file handles the actual scheduling. It only needs to be run once, but it does need to happen in the background or else the user would need to run a command every time Raycast was started in order to reschedule alarms . The interval could be anything though. If there's a better way to do this, I'm happy to change it.

**Comment by mil3na** [comment]
Hey @aurnik ! Is this PR ready for re-review? Are you still having issues with the publish command?

**Comment by aurnik** [comment]
@mil3na Thanks for getting back, and yes I'm still unable to use the publish command.

This was my message from the Slack group:
> Hey team, I'm trying to publish updates to an extension I submitted some time ago, and I've updated my fork of `raycast-extensions` but now when I try to run `npm run publish` it tells me I need to pull new contributions, and when I try doing that I get an error `fatal: Not possible to fast-forward, aborting.` from the command `git pull origin ext/alarm --ff-only`. Any advice on how to move forward?

And the git pull command is a part of `npx @raycast/api@latest pull-contributions`

**Pull request closed without merging**
