### PR TITLE
[google-chrome] Pop to root after opening a browser link

### PR DESCRIPTION
**Pull request by bromanko**
## Description

When opening a history url pop back to the Raycast root. 

## Type of change

- Bug fix / improvement for my extension

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @bromanko - we have added validation of package.json and added to label is required - could you please correct according to the validation error?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by bromanko** [comment]
Added.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Awesome @bromanko 💪 

Now when I use the "New Tab" command I get this (seems to be because of the setting for extracting the favicon) - Could it be done somehow gracefully instead? I'm not sure if it's caused by this update though

TRg9xB0JdbDyHTXs

```
Error: Command failed with exit code 1: osascript -e
      set _output to ""
      tell application "Google Chrome"
        set _window_index to 1
        repeat with w in windows
          set _tab_index to 1
          repeat with t in tabs of w
            set _title to get title of t
            set _url to get URL of t
            set _favicon to execute of tab _tab_index of window _window_index javascript ¬
                    "document.head.querySelector('link[rel~=icon]').href;"
            set _output to (_output & _title & "~~~" & _url & "~~~" & _favicon & "~~~" & _window_index & "~~~" & _tab_index & "\134n")
            set _tab_index to _tab_index + 1
          end repeat
          set _window_index to _window_index + 1
          if _window_index > count windows then exit repeat
        end repeat
      end tell
      return _output

301:438: execution error: Google Chrome got an error: Executing JavaScript through AppleScript is turned off. To turn it on, from the menu bar, go to View > Developer > Allow JavaScript from Apple Events. For more information: https://support.google.com/chrome/?p=applescript (12)

		error = new Error(message);
		        ^

Error: Command failed with exit code 1: osascript -e
      set _output to ""
      tell application "Google Chrome"
        set _window_index to 1
        repeat with w in windows
          set _tab_index to 1
          repeat with t in tabs of w
            set _title to get title of t
            set _url to get URL of t
            set _favicon to execute of tab _tab_index of window _window_index javascript ¬
                    "document.head.querySelector('link[rel~=icon]').href;"
            set _output to (_output & _title & "~~~" & _url & "~~~" & _favicon & "~~~" & _window_index & "~~~" & _tab_index & "\134n")
            set _tab_index to _tab_index + 1
          end repeat
          set _window_index to _window_index + 1
 <…>
```

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by bromanko** [comment]
Can we merge this and open an issue for that other behavior? I didn't write either of those actions so I'd need to familiarize myself with the code to fix them. It would make sense to tag the author of those actions as well.

**Comment by pernielsentikaer** [comment]
Let's do that

**Pull request merged**
