### PR TITLE
feat(Timers): choice of alert sound for custom timer

### PR DESCRIPTION
**Pull request by lokot0k**
## Description

Implementation of alert sound choice dropdown when creating/starting custom timer

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by lokot0k** [comment]
@ThatNerdSquared, please check. Also, there is one bug in extension with these changes. If custom timer is created while it's still running,  this created timer will use default sound. I made this because I can't explicitly access selected sound from code. I have 2 solutions for this, but they're requiring some architect changes or just look bad:
1. Take name of sound from timer file, so it'll needed to write not just timer's name, but name of sound in timer file too.
2. Replace all of timers with custom timers, because in fact user can't create non-custom timer😅  
So, it's up to you. You can write which option you prefer or maybe suggest new solution and I'll implement it

**Review by ThatNerdSquared — COMMENTED** [review]
Hey @lokot0k, thanks for contributing! The code looks good to me in general.

> Also, there is one bug in extension with these changes. If custom timer is created while it's still running, this created timer will use default sound.

I'm not entirely sure what you mean here - do you mean when an existing running timer is saved as a preset, the running version of it will still use the default sound? Other than that, the only problem I see is that there's no way to change the sound of a running timer or existing preset. You're right that this would require substantial changes though, both in terms of architecture and UI.

I think your changes are ready to ship - these problems don't seem like too big of a deal for now. I'm also in the middle of working on major changes to how the timers work entirely (in preparation for the Alarms feature), so I don't think it's worth investing in additional code to handle functionality that I am currently rewriting 😅 

If you think the flaws mentioned above are a blocker for merging this PR, I'd advise you to PR your changes to [ThatNerdSquared/timers-for-raycast](https://github.com/ThatNerdSquared/timers-for-raycast) instead so I can merge with my refactors before we ship. But, as mentioned before, I think your PR looks good.

Also, please add yourself to `contributors` in the `package.json`!

**Comment by lokot0k** [comment]
Thanks for quick review!
> existing running timer is saved as a preset, the running version of it will still use the default sound

Almost that. Running version'll use selected sound, but saved preset of this timer will use default sound.
But it's not a big deal for the moment, I guess🤔 Will wait for the new version!
> add yourself to contributors in the package.json

With great pleasure!

**Comment by pernielsentikaer** [comment]
Are we ready to merge or awaiting extra fixes?

**Comment by ThatNerdSquared** [comment]
It's good to go @pernielsentikaer :)

**Pull request merged**
