### PR TITLE
Add bitbucket-power extension

### PR DESCRIPTION
**Pull request by skuio**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

We already have extensions for [bitbucket](https://www.raycast.com/search?q=bitbucket) in the store, maybe it could fit into one of them?

**Comment by skuio** [comment]
> Hi 👋
> 
> We already have extensions for [bitbucket](https://www.raycast.com/search?q=bitbucket) in the store, maybe it could fit into one of them?

Yes, I use it but it didn't meet my needs.  Does not have pipelines functionality for example.  Should I attempt a PR on that package instead?

**Comment by pernielsentikaer** [comment]
Do you think it will fit in @Lp-Francois

**Comment by Lp-Francois** [comment]
> Do you think it will fit in @Lp-Francois

@pernielsentikaer yes it makes more sense, like the Github extension groups PRs, pipelines, etc in the same extension :)

**Comment by pernielsentikaer** [comment]
Totally agree, could you look into moving it into that extension @skuio

**Pull request closed without merging**
