### PR TITLE
✨ New Extension: Jira2Git

### PR DESCRIPTION
**Pull request by ipiranhaa**
## Description

The tool for making Jira and Git work together smoothly as silk for a better development experience.

## Features

- Transform Jira URL to Git branch name

## Screencast

jira2git

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Would it make sense to build it into one of the already existing JIRA extensions? I don't use JIRA myself so I might not be the right to judge 😊

image

**Comment by ipiranhaa** [comment]
👋 Hi @pernielsentikaer,

From my understanding, the mentions plugin creating for Jira management but my plugin does not manage anything. It just grabs some data from Jira to make something for developers to make them work smoothly.

Thank you for your advice 😃

**Comment by ipiranhaa** [comment]
@pernielsentikaer Already updated the screen casting to align with your update.

jira2git

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
