### PR TITLE
Add Url Dissect extension

### PR DESCRIPTION
**Pull request by NicolasMontone**
## Description

I did this extension for me and I use it a lot so I want to share it. 
Basically breaks down the URL and you can easily can copy each part of it

## Screencast
url-dissect-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thank you for your contribution 🔥

I am currently reviewing this extension: #11011. Do you think it will suit your needs? We could enhance that one with features from yours

**Comment by NicolasMontone** [comment]
> Hi 👋
> 
> Thank you for your contribution 🔥
> 
> I am currently reviewing this extension: #11011. Do you think it will suit your needs? We could enhance that one with features from yours

Maybe can be another command from that extension, but I built this as a quick way to manipulate an URL and copy and paste fast, I can add it, or see if it can fit in that extension!

**Comment by pernielsentikaer** [comment]
We just released the other with copy paste functions, could you check it out again?

**Comment by NicolasMontone** [comment]
I will close this since it no makes more sense!

**Pull request closed without merging**
