### PR TITLE
Commit new extension jb-project,For search the JetBrains product without JetBrains Tool box.

### PR DESCRIPTION
**Pull request by kunpehx**
## Description

Commit new extension jb-project,For search the JetBrains product without JetBrains Tool box.

## Type of change

# introduce
Support Jetbrains product
Intellij IDEA,WebStorm,PhpStorm,CLion,GoLand,Pycharm,Rider,DataGrip,AppCode.

How to use?
1. Install cli
   select menu `Tools` -> Create Command-line Launcher

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @kunpehx 👋 

Thanks for the PR 💪 Are you aware of that there already is [such extension](https://www.raycast.com/gdsmith/jetbrains) doing almost the same as yours already exists?

**Comment by kunpehx** [comment]
> Hi @kunpehx 👋
> 
> Thanks for the PR 💪 Are you aware of that there already is [such extension](https://www.raycast.com/gdsmith/jetbrains) doing almost the same as yours already exists?

Yeah,But that extension need JetBrains Toolbox app and no good user experience.

**Comment by pernielsentikaer** [comment]
We aim to only have one of each “extension” – the right thing here would be to have a chat with @gdsmith about extending the current one, making it more awesome 💪 

I tried to create the “Command line launcher” and just got this:

XJgDiu2yelLUxWHk

And in the toolbox there is already a command line enabled for, e.g., PhpStorm

**Comment by fe9lix** [comment]
Hey @kunpehx and @pernielsentikaer, what's the status on this PR? It has been stale for a while...

**Comment by gdsmith** [comment]
Sorry, only just seeing this now. @kunpehx is the main difference here, or are there some other things you have done that would be good to add to the toolbox extension?

**Pull request closed without merging**
