### PR TITLE
Add extension: Network Speed

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

Quickly check your internet connection speed

This extension uses the Mac's built-in **networkQuality** tool to measure network speed without installing third-party applications or command-line tools.

## Screencast

network-speed-1

https://user-images.githubusercontent.com/36128970/197983371-b8e16731-9ea6-4db2-ba8d-c09f38c12609.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* Only have one loading spinner, adding 14MB loading spinners feels overkill 😊
* Then one you pick, could you set a height of a max of 100px and let the width follow the propositions?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by koinzhang** [comment]
Hi @pernielsentikaer Thanks for your review.
I have compressed the Gif images and now the total size is reduced to 3.9M, plus removed some of the loading Gifs and only kept 4. Please keep reviewing

**Comment by koinzhang** [comment]
Hi @pernielsentikaer. Thanks for your review.
Now only one loading animation is kept and the total size is reduced to 5.6M, please keep reviewing

**Comment by pernielsentikaer** [comment]
It's much better, but it looks a bit funny with the text/description all the bottom, I was more thinking about this size so the text doesn't look misplaced (I know I broke the GIF 😊)

image

**Comment by koinzhang** [comment]
Compressing the size will make the gif unclear, this is the effect after compression, if you think it's still ok I'll submit a PR to update it
image

**Comment by koinzhang** [comment]
Hi @pernielsentikaer. I submitted a PR to update the loading gif and now it's size and title will be a bit more standardized, but also a bit unclear

**Comment by pernielsentikaer** [comment]
I think we have to do that for now, thin lines are always unclear in small sizes 😊

**Comment by pernielsentikaer** [comment]
Copy Summary looks like this
```

[2K==== SUMMARY ====
Uplink capacity: 192.874 Mbps
Downlink capacity: 182.084 Mbps
Uplink Responsiveness: High (1168 RPM)
Downlink Responsiveness: Medium (404 RPM)
Idle Latency: 39.083 milliseconds
```

Is that intended? ([2K)

**Comment by koinzhang** [comment]
> Copy Summary looks like this
> Is that intended? (�[2K)

Yes, this is intentionally designed so that copying the network speed information will get the original information returned by the **networkQuality** CLI tool

**Comment by koinzhang** [comment]
I just noticed the extra characters at the beginning ��[2K, this should be a bug, I'll look into it

**Comment by koinzhang** [comment]
The extra characters **[2K** are supposed to be a bug in MacOS 13. I don't know the exact cause, but I fixed it by intercepting the string. Please keep reviewing.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
