### PR TITLE
[toggl-track] Create functionality for project tasks

### LINKED ISSUE #7933: [Toggl Track] Time tracking for tasks
### Extension

https://www.raycast.com/franzwilhelm/toggl-track

### Description

It is not possible to track time per task on projects. It would be helpful to have to possibility to select project and then pick a task from a list of tasks (could be optional). 

It should be possible: https://developers.track.toggl.com/docs/api/tasks

### Who will benefit from this feature?

Anyone tracking time per multiple clients / projects which can have different tasks. It is sometimes needed to hand to clients or to connect these entries with a kanban board.

### Anything else?

I can help create a PR.

### PR DESCRIPTION
**Pull request by bkeys818**
## Description

This enables the user to pick a [project task](https://support.toggl.com/en/articles/2220738-tasks) when creating a new time entry.

Closes #7933.

## Screencast

Screenshot 2023-08-20 at 12 19 39 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Works as expected for me 🔥 

@franzwilhelm do you mind checking this?

**Comment by bkeys818** [comment]
I don't have premium, so I wrote this blind. Make sure you check it closely.

**Comment by franzwilhelm** [comment]
Neither do I, so cannot check :P @bkeys818

**Comment by franzwilhelm** [comment]
But @bkeys818 what is up with all the reordering of functions etc? It makes for a lot of noise in the PR

**Review by franzwilhelm — APPROVED** [review]

**Pull request merged**
