### PR TITLE
Add Confluence extension 

### PR DESCRIPTION
**Pull request by yufeikang**
This is the content of the PR on top, including #5075 and #5337. #5075 is a great contribution. However, the PR was closed due to timeout as the author was unable to cooperate with the review. I have initiated a new PR, merging these two contents.

# Atlassian's Confluence Extension.

## Description

* Add Search allowing you to search all pages/blogs 
* Add Popular command to view a list of what's trending 
* Add People command to search for people
* Add Go command to quickly jump to useful places in Confluence
* Add Recent command for super snappy access to pages you've viewed
* Add Create Page, Create Blog
* Add Switch Site command to allow to change connected Confluence site
* Remove confluence-search Extension
* Move confluence-search Extension fun to this ext
* feat: Add functionality to open Confluence page for edit
* feat: support sort by title, created, modified
* feat: show last modified date

## Screencast

image

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by yufeikang** [comment]
@raycastbot

**Comment by pernielsentikaer** [comment]
You can't have both `confluence` and `confluence-search`, you should probably remove `confluence`, right?

Also you added a folder in the root you need to remove

**Comment by yufeikang** [comment]
> You can't have both `confluence` and `confluence-search`, you should probably remove `confluence`, right?
> 
> Also you added a folder in the root you need to remove

My English is not good, so I may not have expressed myself clearly, sorry. What I meant is that I have added `confluence`. Since `confluence` includes the functionality of `confluence-search`, I removed `confluence-search`. Currently, `confluence-search` is in the store.  `confluence` is a new extension.

**Comment by pernielsentikaer** [comment]
Since this has to superseed the current, then we need it to replace the content in `confluence-search` - this way it will be seen as an update and seeded to everyone having the current extension installed

**Comment by ahoereth** [comment]
How come this was closed? Should I reopen, but move to the confluence-search directory? Plugin is very functional, using it productively.

**Pull request closed without merging**
