### PR TITLE
[Bitwarden] Add vault timeout and password reprompt for other sensitive values

### PR DESCRIPTION
**Pull request by jomifepe**
## Description

Issue #5139

### What was done:
- [X] Added a **Vault Timeout** feature (thought it was implemented with the reprompt feature) 
  - Repurposed the `Skip Reprompt` preference for this
  - This feature works by saving the `last activity time` every time a CLI command is run, and comparing it when accessing the Search Vault command
- [X] Added password reprompt for fields like **Notes**, **Card** and **Identity Details**, this matches Bitwarden's behaviour
- [X] Display lock reason in the unlock form
- [X] Refactored the vault actions
  - Moved them into separate files and used context to avoid passing the `selected item` around

### Vault timeout

225781494-9794efac-36a4-4485-b0d1-0cedd5e89d54 (1)

### Reprompt

https://user-images.githubusercontent.com/7235666/227747126-3c9eb008-af01-4731-82a4-8c9597e451d0.mp4

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hello 👋

I gave it a quick spin, works as expected, approved 🔥

**Comment by byumov** [comment]
Doesn't work in my fresh installation. Found some logs:

`time:2023-03-27T20:49:02Z,type:exception,key:extension_bitwarden.search__5fdb86d3-dfcc-45a7-8969-8113b51434ab,message:Error: Command failed with exit code 1: /usr/local/bin/bw lock
You are not logged in.
time:2023-03-27T20:49:00Z,type:cmdLoading,ext:bitwarden,cmd:search,dev:false,mode:view,launchType:userInitiated
time:2023-03-27T20:48:01Z,type:cmdUnloading,ext:bitwarden,cmd:search,dev:false,mode:view,launchType:userInitiated
time:2023-03-27T20:48:01Z,type:exception,key:extension_bitwarden.search__5fdb86d3-dfcc-45a7-8969-8113b51434ab,message:Error: Command failed with exit code 1: /usr/local/bin/bw lock
You are not logged in.
time:2023-03-27T20:48:00Z,type:cmdLoading,ext:bitwarden,cmd:search,dev:false,mode:view,launchType:userInitiated
time:2023-03-27T20:43:33Z,type:cmdUnloading,ext:bitwarden,cmd:search,dev:false,mode:view,launchType:userInitiated
time:2023-03-27T20:43:33Z,type:exception,key:extension_bitwarden.search__5fdb86d3-dfcc-45a7-8969-8113b51434ab,message:Error: Command failed with exit code 1: /usr/local/bin/bw lock
You are not logged in.`

I use my own server and all settings is correct - server address and API credentials. I even tried to change API key.

if I try to run command manually in terminal, it works:
```
⟩ /usr/local/bin/bw lock
Your vault is locked.

```
```
⟩ bw status
{"serverUrl":"https://bw.XXX.YY","lastSync":"2023-03-26T09:44:33.216Z","userEmail":"XXXXX@gmail.com","userId":"XXXX","status":"locked"}`
```

**Comment by jomifepe** [comment]
> Doesn't work in my fresh installation. Found some logs:
> 
> `time:2023-03-27T20:49:02Z,type:exception,key:extension_bitwarden.search__5fdb86d3-dfcc-45a7-8969-8113b51434ab,message:Error: Command failed with exit code 1: /usr/local/bin/bw lock You are not logged in. time:2023-03-27T20:49:00Z,type:cmdLoading,ext:bitwarden,cmd:search,dev:false,mode:view,launchType:userInitiated time:2023-03-27T20:48:01Z,type:cmdUnloading,ext:bitwarden,cmd:search,dev:false,mode:view,launchType:userInitiated time:2023-03-27T20:48:01Z,type:exception,key:extension_bitwarden.search__5fdb86d3-dfcc-45a7-8969-8113b51434ab,message:Error: Command failed with exit code 1: /usr/local/bin/bw lock You are not logged in. time:2023-03-27T20:48:00Z,type:cmdLoading,ext:bitwarden,cmd:search,dev:false,mode:view,launchType:userInitiated time:2023-03-27T20:43:33Z,type:cmdUnloading,ext:bitwarden,cmd:search,dev:false,mode:view,launchType:userInitiated time:2023-03-27T20:43:33Z,type:exception,key:extension_bitwarden.search__5fdb86d3-dfcc-45a7-8969-8113b51434ab,message:Error: Command failed with exit code 1: /usr/local/bin/bw lock You are not logged in.`
> 
> I use my own server and all settings is correct - server address and API credentials. I even tried to change API key.
> 
> if I try to run command manually in terminal, it works:
> 
> ```
> ⟩ /usr/local/bin/bw lock
> Your vault is locked.
> ```
> 
> ```
> ⟩ bw status
> {"serverUrl":"https://bw.XXX.YY","lastSync":"2023-03-26T09:44:33.216Z","userEmail":"XXXXX@gmail.com","userId":"XXXX","status":"locked"}`
> ```

That's odd, I don't see how these changes could affect the self-hosted server support. 

I'm trying to setup a server to test it. 

Where did you found these logs?

**Comment by byumov** [comment]
@jomifepe Extension Diagnostic:
image

Sorry, I'm not sure if this PR is the problem.
I decided to go back to Raycats after a few months on Alfred, installed the extension and immediately found this rather voluminous PR... But I have already used this extension with my server before and everything worked.

Thanks.

**Comment by jomifepe** [comment]
> @jomifepe Extension Diagnostic: image
> 
> Sorry, I'm not sure if this PR is the problem. I decided to go back to Raycats after a few months on Alfred, installed the extension and immediately found this rather voluminous PR... But I have already used this extension with my server before and everything worked.
> 
> Thanks.

Just saw the issue, the vault tries to lock while unauthenticated, open a [PR](https://github.com/raycast/extensions/pull/5609) to fix this.

**Comment by jomifepe** [comment]
> @jomifepe Extension Diagnostic: image
> 
> Sorry, I'm not sure if this PR is the problem. I decided to go back to Raycats after a few months on Alfred, installed the extension and immediately found this rather voluminous PR... But I have already used this extension with my server before and everything worked.
> 
> Thanks.

Should be fixed now, try it out

**Pull request merged**
