### PR TITLE
Add Jokes extension

### PR DESCRIPTION
**Pull request by xmok**
## Description

This is a simple extension to display up to 10 jokes at a time via [https://v2.jokeapi.dev/](https://v2.jokeapi.dev/).

## Screencast

https://github.com/raycast/extensions/assets/30526133/9ce36eff-0b1f-45e7-ae62-323c6c71a521

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

In the sidebar you'll also find the joke with a title called `title` - I guess that it should be removed from the sidebar? Sometimes it's also called `Setup` and `Delivery`

Raycast09042024-5y4jzTR0 png@2x

Raycast09042024-7HWzAK3p png@2x


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by xmok** [comment]
Hi!

Thank you for the review.

It's sometimes called `Title` and other times `Setup` & `Delivery` since it depends on the type of joke.
But I agree it seems redundant so have removed from the Detail.Metadata. I also removed "Error" as it is always `false` when  joke is received so also redundant.

Finally, I updated the images to match the changes.

Best!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
I think we should only show family-friendly jokes, as racist, sexist, and religious jokes should not be allowed - sorry for not catching that in the first place

Would you be okay if I make that change @xmok

**Comment by xmok** [comment]
Hi.
Yes definitely I'm onboard with that! It's why I added a disclaimer in the README and disabled flags by default. Yes you can go ahead and makes those changes but if you like, I can push a PR with the changes within the next hour as the extension is fresh in my mind.

**Pull request merged**
