### PR TITLE
[Badges][Color Picker][Brand Icons] Add social/dynamic/endpoint badges support

### PR DESCRIPTION
**Pull request by LitoMore**
### Badges Changes

- Add `Create Social Badge` command.
- Add `Create Dynamic Badge` command.
- Add `Create Endpoint Badge` command.
- Polish extension icon with gradient overlay.
- Add Color Picker support.
- Add the `crossExtensions` field. This allows extension providers to get to know who is using their extension API. This is introduced in https://github.com/LitoMore/raycast-cross-extension-conventions?tab=readme-ov-file#consumer-usage.

### Color Picker Changes

- Expose its ability through `raycast-cross-extension`

### Simple Iocns Changes

- Use `raycast-cross-extension`

## Screencast

All screenshots have been updated to metadata.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by LitoMore** [comment]
Hi @pernielsentikaer

> i guess you can't really use this extension to it's fully without having simple icons installed? I can see in the catch we just try to open it when launchCommand failed

The open command is used to open the extension Store page. I missed the import of `open` here. This should be fixed now.

> In Social badge command, nothing happens when I click edit in `logoColor`.

The `default` means no `logoColor` parameter. And the `#FF6363` is the brand color. The default color is the same as the Raycast brand color `#FF6363` in the case. But default color is not always the same. You can change the logo to `Node.js` to see the difference.

**Comment by pernielsentikaer** [comment]
I havent forgot about this one, I just have an issue compiling it so I have to fix that before I can have a look 🙂

**Comment by pernielsentikaer** [comment]
So the `pick` only launches the color-picker command and copies it and then you manually have to open the badges extension and insert the value, is that correct @LitoMore

**Comment by LitoMore** [comment]
> So the pick only launches the color-picker command and copies it and then you manually have to open the badges extension and insert the value, is that correct

No. When it finishes the pick action, the color-picker will automatically call `launchCommand()`. Like the logo feature does. Here is the documentation of `raycast-cross-extension`: https://github.com/LitoMore/raycast-crosss-extension.

Let me take a video for you:

https://github.com/raycast/extensions/assets/8186898/12d8f507-7943-4552-a51d-6bd7566d4f87

**Comment by pernielsentikaer** [comment]
Lets merge it and see how it goes 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
