### PR TITLE
Update ffmpeg extension

### PR DESCRIPTION
**Pull request by blekmus**
## Description

Added more error handling and updated the `ffprobe` command, which extracts data from various video file formats, extending support beyond just MP4s.
Cleaned up parts of the code.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by RenderCoder — COMMENTED** [review]
It looks like the code is more elegant 👍

Checking out the latest changes and testing them, this may take some time...

**Review by RenderCoder — APPROVED** [review]
Thank you for your modification! I have no problem using it. The implementation is better than the original. 👍

**Comment by blekmus** [comment]
@pernielsentikaer updated the changelog  🙌

My Raycast handle is already in `package.json` from my previous contribution 😆

**Comment by pernielsentikaer** [comment]
Ah, sure, I was misreading the tags 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
