### PR TITLE
[Simple Youdao] provide an option to enable official modern translation page

### PR DESCRIPTION
**Pull request by xeric**
## Description

An `Simple Youdao Translate` enhancement which provides an option that end user can choose using official modern translation page instead of the default mobile version, this is much more user friendly for desktop user. 

## Screencast

modern page:
image

old mobile version:
image

## Checklist

- [√ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [√ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ √] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ √] I checked that files in the `assets` folder are used by the extension itself
- [ √] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @xeric 👋 

Why not just have the new version instead?

**Comment by pernielsentikaer** [comment]
Hi @xeric 👋 

Why not just have the new version instead?

**Comment by xeric** [comment]
Hi @pernielsentikaer 
I did not see any attribute I can define the version of extension in package.json, may I know how to define the version?

**Comment by pernielsentikaer** [comment]
Can you try to rephrase that a bit? I don't understand 😞 

When it's getting updated, everyone having the extension receives the new version.

Why should we keep the old "design"? Does it make sense to toggle between the two designs?

**Comment by xeric** [comment]
@pernielsentikaer you mean, I should not keep the old mobile version webpage, just use the modern page to replace old one? is it right?
If yes, here is the reason, the mobile version is recoomended by official API, since the deeplink of the page is in the translation API response which binds with query context.
```json
{
  "errorCode":"0",
  "query":"good",
  "translation": [
      "好"
  ],
  "basic":{
      "phonetic":"gʊd",
      "uk-phonetic":"gʊd", 
      "us-phonetic":"ɡʊd",
      "uk-speech": "XXXX",
      "us-speech": "XXXX",
      "explains":[
          "好处",
          "好的",
          "好",
      ]
  },
  "web":[
      {
          "key":"good",
          "value":["良好","善","美好"]
      },
      {...}
  ],
  "dict":{
      "url":"yddict://m.youdao.com/dict?le=eng&q=good"
  },
  "webdict":{
      "url":"http://m.youdao.com/dict?le=eng&q=good" // it is here
  },
  "l":"EN2zh-CHS",
  "tSpeakUrl":"XXX",
  "speakUrl": "XXX"
}
```
The modern webpage link is not provided officially, it is composed by myself, I parsed language value "l" in above sample, and get a EN string which is a mandtory value in modern page, but I did not see if "l" attribute value is always with format `xx2xx`, so by default I turn this feature off, and leave it to end user such as:
https://github.com/raycast/extensions/issues/1823
Who like it.

**Pull request merged**
