### PR TITLE
Update work-time-countdown extension

### PR DESCRIPTION
**Pull request by aalhaif**
### Enhancements:
- Added more work intervals (6:30, 7:30, 8:30 etc.)
- Made the necessary changes to make the newly added intervals work.

## Screencast

PixelSnap 2023-11-29 at 13 01 16

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by aalhaif** [comment]
> Hi @aalhaif 👋
> 
> Could you look into the CI errors, let me know if you need help 🙂

It was a code style issue, I have fixed it 👍🏻

**Comment by Abdullah-ALHaif** [comment]
Hi, I'm just following up and please let me know if I have to check or change anything 😬

@pernielsentikaer @thomaspaulmann

**Comment by pernielsentikaer** [comment]
Checking again 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
