### PR TITLE
New extension: Steam

### PR DESCRIPTION
**Pull request by KevinBatdorf**
## Description

This adds a command to search the Steam API for information about games, etc. Optionally a user may enter their API + Steam ID in the preferences to bring in additional features.

- Search the entire Steam library
- View random games 
- Install/launch/open in Steam

If logged in:
- View your game library
- View your recently played games
- View your most played games

## Screencast

steam-02

Logged out

https://user-images.githubusercontent.com/1478421/170874069-e4fd3911-5b8c-4381-a04d-8d4cf622046b.mov

Logged in

https://user-images.githubusercontent.com/1478421/170874084-6b8cbd15-4446-4dc2-a1f5-26015d587983.mov

If accessing a logged in area without being logged in

log-in-notice

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
Any tips on how to resolve the screenshot error? The workflow reporting 2002px but Figma/VS code/Finder locally are telling me 2000px.

**Comment by KevinBatdorf** [comment]
The screenshot process is pretty painful for someone like me with two left eyes for design. I can't get it lined up perfectly and my screenshots look blurry to me as well. If anyone wants line these up I've attached some source files (Or feel free to make your own). Otherwise I'll try to give it another shot this week sometime. 

I feel like this could be solved with a webapp where you just upload a screenshot of the application (the "capture selected window" variety), fix the shadows, and select a bg?

[screenshots.zip](https://github.com/raycast/extensions/files/8793667/screenshots.zip)

**Comment by Namaskar-1F64F** [comment]
I've used this: https://www.raycast.com/koinzhang/capture-raycast-metadata THere are some caveats on what monitors it works on, but it might help ya

**Comment by KevinBatdorf** [comment]
Thanks @Namaskar-1F64F I'll give this a try in a bit :)

**Comment by KevinBatdorf** [comment]
This is ready for review now. 

The screenshot extension worked well. Thanks for that suggestion!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @KevinBatdorf 👋 

Thanks for an awesome extension 🔥 

If I enter wrong credentials I see the screen below, is there a way to tweak it so I don't see `My Games`?

CleanShot 2022-06-08 at 07 41 01@2x

I tried to obtain a key without any luck, do you have any suggestions? I have two or three games in my account but only see this:

CleanShot 2022-06-08 at 07 50 26@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by KevinBatdorf** [comment]
> If I enter wrong credentials I see the screen below, is there a way to tweak it so I don't see My Games?

What would you recommend? Maybe just clear out the token if the auth fails?

> I tried to obtain a key without any luck, do you have any suggestions? I have two or three games in my account but only see this:

Not really sure. I can message you my key though. It's read only and I can release it when you're done testing. I'll message you on Slack with it after I make the access changes.

**Comment by KevinBatdorf** [comment]
I added an extra check for when an API token fails. It will cache the bad key and recheck if that value changes. 

I tested it with no key/ID, with one good, one bad, both bad, one bad but different, etc, then both good.

I think it's decent experience now, but let me know.

For the token, send me a message on slack, I'm Kevin Batdorf (I posted that silly "catch the devil" grid game last night)

**Comment by KevinBatdorf** [comment]
@pernielsentikaer are you waiting on anything from me? Just checking in.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @KevinBatdorf 👋 

No it's not waiting for you, it's on me 🙂

I gave it a new spin, and it looks really good 💪 

I have some feedback for you: 

- It seems like the extension is missing icons, if some actions have then every item should have, could you add the missing icons?

- First time I launched I got this error, might be due to no cache at first load though

CleanShot 2022-06-16 at 07 34 23@2x

- Shouldn't the keys be changed to type=password instead?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by KevinBatdorf** [comment]
Thanks @pernielsentikaer 

- I added a check for the cache now. You may also want to check on [the sentry extension cache too](https://github.com/raycast/extensions/blob/main/extensions/sentry/src/cache.ts) in the same regard just in case.

- I updated the API token to a password, but the steam ID is public info so I left that one text area

For the icons. I've actually not added any myself, but Raycast will add a globe icon on `Action.OpenInBrowser`. I'm not sue I can come up with _useful_ icons for the other commands and don't see a way to remove the globe. 

For example, here are the actions I have:
1. View My Games
2. View Most Played Games
3. View Recently Played Games
4. View Random Games
5. View Game Details

Should I just add circles or something? 

The icons only show when hovering on a game though, and are separated with a divider.

https://user-images.githubusercontent.com/1478421/174116830-f9185783-83e3-44a2-b28e-92e3270a8e78.mov

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @KevinBatdorf 👋 

Thanks for all the corrections, you're on 🔥 

> I added a check for the cache now. You may also want to check on [the sentry extension cache too](https://github.com/raycast/extensions/blob/main/extensions/sentry/src/cache.ts) in the same regard just in case.

Thanks for doing the check, I actually also have that problem in one of my extensions as well 😄 

> I updated the API token to a password, but the steam ID is public info so I left that one text area

Makes sense, thanks for taking care 💯 

> For the icons. I've actually not added any myself, but Raycast will add a globe icon on Action.OpenInBrowser

In the [developer documentaion](https://developers.raycast.com/basics/prepare-an-extension-for-store#action-panel) it says: 
>> Provide icons for actions if there are other actions with icons in the list
>> Avoid having a list of actions where some have icons and some don't

I would go with `Sidebar` or `List` for the missing one, even though I understand the struggle and confusion

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by KevinBatdorf** [comment]
Updated the icons now. Some repetition but I guess it looks better after all :) 

ezgif com-gif-maker

**Review by pernielsentikaer — APPROVED** [review]
Hi @KevinBatdorf 🔥 

I think we're ready. Thanks for your cooperation. It has been such a pleasure to work with you  💯

**Pull request merged**
