### PR TITLE
feat(iTranslate): translate by capture

### PR DESCRIPTION
**Pull request by 404J**
## Description

- Add new command `Translate by OCR`

## Screencast

itranslate-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your update 🔥 However, if having this setting it doesn't work as it is right now since the extension is unloaded before it's done.

I'm not sure we can work around this at the moment 😕

**Comment by 404J** [comment]
@pernielsentikaer Which setting are you talking about?

**Comment by pernielsentikaer** [comment]
@404J strange! I'm sure I included the image I prepared, here it is 😊

image

**Comment by 404J** [comment]
@pernielsentikaer This command has a configuration item that defaults value is false and gives some hints when the user wants to change its value. This will prevent the extension from being unloaded before it's done.
CleanShot 2022-09-28 at 16 03 16@2x

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
