### PR TITLE
feat [Deepcast]: add commands to translate selected test into every possible language

### PR DESCRIPTION
**Pull request by mooxl**
## Description

This PR adds commands to my extension which allows faster translation into the desired target language.

## Screencast

https://user-images.githubusercontent.com/35741000/154805651-412aa3e5-bd14-4b4a-8e6f-d4decb76d560.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by mooxl** [comment]
Hey! 
Is there any way I can add parameters to the entry point file in the manifest? 
If yes, one could save the redundancy with the 'one file for each language'.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @mooxl 👋 

Thanks for your contribution, what I miss is a README (so I know how to get an API Key)

And for now it's not possible to pass arguments, but you can follow this issue #59 😄 

Do you have time to make a simple README? 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by mooxl** [comment]
Hey @pernielsentikaer,

> And for now it's not possible to pass arguments, but you can follow this issue #59 😄

Ahh cool! Is there an ETA for this Issue?

I hope the added README is enough for the first pass.

**Comment by pernielsentikaer** [comment]
Unfortunately, there is no ETA for this yet, but it's popping up quite often at the moment 😄 

One last thing I reccommend is to add "selected" to description, so it's like "Translate selected text into Chinese using DeepL" so the user is aware of how it actually works :)

When this is corrected, then I can't find anything else 😄 💪

**Comment by mooxl** [comment]
Ahh okay, let's hope that this issue will be resolved soon. Then you could save all the different files for each command. 😍
I just ran the CI again, but unfortunately I still get an error. Can you help me with this? @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi @mooxl 👋 

Thanks for your update! Yes, we do have some issue with the linter at the moment, I got [top men](https://www.youtube.com/watch?v=Fdjf4lMmiiI) on the job to resolve it! :)

**Comment by sxn** [comment]
🎉

**Pull request merged**
