### PR TITLE
Spotify Beta: Add keyboard shortcuts to copy URL or open Spotify

### PR DESCRIPTION
**Pull request by thomaspaulmann**
## Description

I added keyboard shortcuts for the actions to copy the URL or open Spotify. This way, you can quickly share a song/artist/etc. or jump to the Spotify app/website to continue.

## Screencast

CleanShot 2023-04-19 at 9 28 21
CleanShot 2023-04-19 at 9 28 29

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by sxn — APPROVED** [review]

**Review by peduarte — APPROVED** [review]
Thanks. You probably noticed that none of the actions had shortcuts, this was on purpose. I wanted to see if anyone would bring it up (no-one did)

**Comment by thomaspaulmann** [comment]
Yeah, I noticed that. I like to have keyboard shortcuts for the common ones. Copying and sharing a URL seems like one of those. Maybe it's just me 🙃

**Comment by thomaspaulmann** [comment]
Fine merging the PR then?

**Comment by peduarte** [comment]
sacha-baron-cohen-yes-gif-by-amazon-prime-video

**Pull request merged**
