### PR TITLE
fix(elgato-key-light): Fix error when toggling light

### LINKED ISSUE #3326: [Elgato Key Light] ...
# Extension – [Elgato Key Light](https://github.com/raycast/extensions/tree/4479d612107d01bc93466c2ce7049e8b6fa79bfe/extensions/elgato-key-light/)
Author: thomas

## Description
After the most recent Raycast update, the Elgato extension fails to toggle the key light. When you run the `Toggle On/Off` action the following error is reported: `Toggling Key Light Failed`. I have confirmed the light is on the network, available, and toggleable through the native control center. I have also rebooted the light and restarted raycast.

## Environment
- Elgato Control Center 1.3 (10415)
- Raycast 1.42.1

## Steps To Reproduce

1. Install Elgato Extension
2. Start Raycast, select the `Toggle On/Off` action for the Elgato key light

### Raycast version
- Raycast 1.42.1

### LINKED ISSUE #3487: [Elgato Key Light] No longer able to control key light
# Extension – [Elgato Key Light](https://github.com/raycast/extensions/tree/4479d612107d01bc93466c2ce7049e8b6fa79bfe/extensions/elgato-key-light/)
Author:

## Description

The extension is no longer able to toggle the Key Light. Executing the RayCast command gives an error which says "Failed toggling Key Light". The light can be controlled via the Elgato Control Centre in the Mac menu bar. I suspect this may be linked to a recent update to the Elgato software.  

## Steps To Reproduce

1. Select "Toggle key light" command in RayCast

## The current behavior
"Failed toggling Key Light" error from extension in RayCast.

## The expected behavior
Light toggles, glorious illumination, happiness.

### Raycast version

RayCast 1.43.2
Elgato Control Center 1.3 (10415), firmware version 1.0.3 (216)
Mac OS X 12.6.1

### LINKED ISSUE #3700: [Elgato Key Light] ...Doesn't seem to be working
### Extension

https://www.raycast.com/thomas/elgato-key-light

### Description

None of the functions work. I just get a message that says "Can't discover any key lights in this network" even though the control center app works seamlessly.

### Steps To Reproduce

_No response_

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by zach-fuller**
## Description

Resolves error when using the latest Elgato firmware.

 - Replaces `service.host` with `service.referer.address`
 - Updates `@raycast/api` and `axios` dependencies

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

## Related Issues
closes #3700, closes #3487, closes #3326

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @zach-fuller 🔥 

Thanks for your contribution 💯 

@thomaspaulmann can you review this?

**Comment by thomaspaulmann** [comment]
Oh thanks for the fix! My keylights stopped working recently and I couldn't figure out why.

**Comment by thomaspaulmann** [comment]
Mmh, just checked again and unfortuantely this didn't solve my problem. Looks like I need to dig a bit deeper.

**Comment by Docproc** [comment]
Thanks, this solves the issue I had! #3487

**Comment by qor72** [comment]
Thank you! Confirm that this fixes #3326 and the issues I reported.

**Pull request merged**
