### PR TITLE
Add eudic extension

### PR DESCRIPTION
**Pull request by tears330**
## Description

An extension can interact with [Eudic](https://www.eudic.net/v4/en/app/eudic). Support search & speak any words via Raycast.

## Screencast
Raycast 2024-06-13 at 22 56 01

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥

It looks like [EasyDict](https://www.raycast.com/isfeng/easydict), could you check that out? It might be similar :)

**Comment by tears330** [comment]
Nope, it is a completely different extension. This extension's proposal is to interact with Eudic, one of the most popular dictionary apps in China, which means you must install Eudic first.

EasyDict is more like a client that integrates with various translation APIs, allowing you to access them easily.

**Comment by koinzhang** [comment]
In fact, Easy Dictionary uses the icon of the Eudic iOS version.

**Comment by pernielsentikaer** [comment]
Thanks for the clarification both 🙂

- The extension crashes if you don't have the application installed, could you please add some gracefully error handling like, maybe like the extension [Eagle](https://www.raycast.com/Yukai/eagle) handles it?

**Comment by tears330** [comment]
Thank you for the notice, @pernielsentikaer. I have already implemented a fallback logic for this, but I encountered an issue with the Ray CLI when I tried to publish. I navigated to the branch on my fork repo and clicked "Sync fork" on github which should have pulled the latest changes from the main repo. 

However, I received the following error when I ran `npm run publish` at my local:

```
error - checking for new contributions
Some contributions are available. Pull them using `npx @raycast/api@latest pull-contributions`
```

It seems that my local repository is behind the remote branch. I tried using `npx @raycast/api@latest pull-contributions` to fix this, but I encountered another error:

```
wait - pulling new contributions.failed running git command 'git pull origin ext/eudic --ff-only', exit status 128

From https://github.com/tears330/raycast-extensions
 * branch              ext/eudic  -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.
```

I attempted to hard reset my fork repository to make the CLI workflow work, but the repository is too large, and due to my network issues, I cannot clone it locally. Do you have any suggestions on how I can resolve this issue?

**Comment by mathieudutour** [comment]
Can you try to run those commands in your terminal:
```
cd ~/.config/raycast/public-extensions-fork
git pull origin ext/eudic --rebase
```
and then try to publish again?

**Comment by tears330** [comment]
There is another issue about generating screenshots for extensions that do not have their own view. In this case, the "Save to Meta" checkbox will not display (may current extension ID may not be found at command panel). In this case, eudic commands will directly trigger an AppleScript and do not require any view. Therefore, I have added the screenshots manually, hope the path and naming conventions are correct.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by mil3na** [comment]
Hi!
I'm doing one last review before getting it merged, but I don't think it is working as expected. The `Speak Word` (which I believe would be better called `Pronounce Word`) does work. However, the other two commands don't do anything after I input a word. What would be the expected outcome of them?

**Comment by tears330** [comment]
Hey! Thanks for your test. 🫶

> However, the other two commands don't do anything after I input a word. What would be the expected outcome of them?

The issue with the `activate` statement not being able to bring the Eudic app to the foreground has been resolved. The implementation has been changed to use the URL Scheme version to address this problem.

> (which I believe would be better called Pronounce Word)

Excuse my poor English, this has been corrected.

**Review by mil3na — APPROVED** [review]
Thanks for the effort! LGTM!

**Pull request merged**
