### PR TITLE
Add images-compression extension

### PR DESCRIPTION
**Pull request by okooo5km**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by okooo5km** [comment]
💡Oh, and just a quick addition: Download the latest version of [Zipic](https://zipic.5km.tech/Zipic.dmg) for a dream integration with Raycast✨.

**Review by pernielsentikaer — APPROVED** [review]
👍 Approved

**Review by pernielsentikaer — APPROVED** [review]
👍 Approved

**Comment by okooo5km** [comment]
🥳🥳🥳

I'm truly grateful for the heads up. It's really exciting to see the extension successfully listed on the store. 
Kudos to all your hard work!✨🫶🏼

**Pull request merged**
