### PR TITLE
[Update] [Open Path] Peek url in safari

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

- Web pages can be quickly previewed in Safari (by installing the shortcut [Peek Url](https://www.icloud.com/shortcuts/2364c358fbe7498aa6b18bd229d0f7de) and selecting **Peek in Safari** in Settings)

## Screencast

open-path-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Just after testing this it works first time, second time it pops the `add shortcut` dialog, I didn't change any settings, can we avoid that?

**Comment by koinzhang** [comment]
Can you confirm that you have a shortcut command called **Peek Url** in your Shortcuts? If not, you need to follow the pop-up instructions to install it.

You can see all the shortcuts by typing shortcuts list in the terminal, make sure it contains the **Peek Url**
image

**Comment by pernielsentikaer** [comment]
I'm not sure what caused it, doesn't happen now - I only hear two beeps while running it, is that something from Raycast and do you hear the same?

**Comment by koinzhang** [comment]
This is a bug in the Raycast API, I've raised an issue about it before, this issue doesn't affect the extension use.
**System will emit a NSBeep sound when getSelectedText() report error.** #1497

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
