### PR TITLE
Update groq extension

### PR DESCRIPTION
**Pull request by polymathiq**
## Description

- Upgrading to Llama3 from Llama2
- Updated inference cost calculator (Groq currently offers Llama 3 70B at a price of $0.59 (input) and $0.79 (output) per 1M tokens.)
- Added Groq's Llama3 70B inference speed at 250 token/s 
- Changed default LLM endpoint to Llama3

Source: https://artificialanalysis.ai/models/llama-3-instruct-70b

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by maximilianzuern** [comment]
Thank you for your contribution!
I already opened a PR few days ago #11900 which adds the new Llama 3 models.

**Comment by pernielsentikaer** [comment]
@polymathiq could you correct the conflicts in this PR so I can have a look 🙂

**Comment by maximilianzuern** [comment]
Since the changes have already been updated by past merges, I suggest closing this PR @pernielsentikaer

**Comment by pernielsentikaer** [comment]
Sounds like a good idea @maximilianzuern - closing as requested

**Pull request closed without merging**
