### PR TITLE
Update scrcpy extension: select previous used device automatically.

### LINKED ISSUE #7805: Option to set default, favourite devices to run by default.
### Extension

https://www.raycast.com/zcfan/scrcpy

### Description

Right now whenever I run an extension I need to select the device always, is there any way I can set the default device to run to skip device selection each time?

### Who will benefit from this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by zcfan**
## Description

Select previous used device automatically. Fixed #7805

## Screencast

skip

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by zcfan** [comment]
@pernielsentikaer It seems the "Extensions/Check" failed because of network connectivity problem, should I just ignore it?

**Comment by mil3na** [comment]
Hi @zcfan!
Thanks for this improvement! My name is Milena and I will be reviewing it today.
I don't have an Android device available. Do you mind sharing a screen record of this change?

**Comment by zcfan** [comment]
@mil3na 

https://github.com/raycast/extensions/assets/1666185/aa3a3132-ace1-4d8b-a9db-c4598cb91666

**Review by mil3na — APPROVED** [review]
Thanks for the video!
LGTM.

**Pull request merged**
