### PR TITLE
[Things] Preference to disable date parsing for todo classification, sending all todo(s) to inbox.

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

Preference to disable date parsing for todo classification, sending all todo(s) to inbox.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

* closes https://github.com/raycast/extensions/issues/13441

### CODE REVIEW

**Review by thomaslombart — COMMENTED** [review]
Thanks for the PR! I'd suggest using a similar approach to the one in `Quick Add Reminder` (Apple Reminders extension) for this command. If the goal is to simply send a todo to the Things inbox, we shouldn't run the AI, which will make the command faster to run.

**Comment by jfkisafk** [comment]
> I'd suggest using a similar approach to the one in Quick Add Reminder (Apple Reminders extension)

Sounds like a plan, @thomaslombart ! I even retained the list matching and deadline parsing from Apple Reminders. Please take a look when you have some time.

**Comment by thomaslombart** [comment]
Thanks for the improvements. Could you also add these details in the `README.md` file so that people know how to use the command?

**Review by thomaslombart — APPROVED** [review]
Awesome, great job! 🙌

**Pull request merged**
