### PR TITLE
Update cursor extension

### PR DESCRIPTION
**Pull request by pedrotmr**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by erics118** [comment]
I'm curious why this was separated from the vscode extension. Since Cursor basically is a based on the same [`Code - OSS`](https://github.com/Microsoft/vscode) as vscode, the internals work identically to VSCode. Currently, the implementation is just to switch the "build" to Cursor, and everything works just fine.

**Comment by pernielsentikaer** [comment]
As @erics118 mentions we already have an extension for `Cursor` which works inside [this extension](https://www.raycast.com/thomas/visual-studio-code) - I would rather add some keywords to that extension instead so it can be found if you search for `cursor`, `codium` and so on

**Comment by pedrotmr** [comment]
Visually it makes difference. Ok, I can launch cursor with the vscode extension, but icons are still from vscode, action names as well. It does have the functionality, but the look/interface is not what we are looking for. Unless there's a way to toggle the name of the actions and icons as well...

**Comment by pernielsentikaer** [comment]
Since Cursor is built on VSCode, it makes sense to only have one extension to maintain. Otherwise, it will be impossible to keep both up to date with the exact same features

**Comment by pernielsentikaer** [comment]
Closing since it doesn't make sense to add a 1:1 copy

**Pull request closed without merging**
