### PR TITLE
Add notion_researcher extension

### PR DESCRIPTION
**Pull request by razgaon**
## Description
This extension lets you add Arxiv papers to Notion instantly. The added page includes information about the paper (authors, date, subject). It also gathers the references from the papers, and explains the main topics using GPT 3.5.

## Screencast

https://github.com/raycast/extensions/assets/43913869/878a1e91-f660-4aec-aa30-726a502408e0

https://github.com/raycast/extensions/assets/43913869/25018997-3123-4edf-b27c-85e10f639b9f

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by razgaon** [comment]
Hi Milena! 
I appreciate you taking the time to review the extension!
1. The [Notion search](https://developers.notion.com/reference/post-search) API searches by title, so I don't think there is a workaround for this.
2. The Readwise key is optional, but I added an explanation and another Optional warning.
3. Will update the Readme right now to be more clear. Hoping to add more than just Arxiv soon!
Is there anything else I need to do?

Thank you!

**Comment by mil3na** [comment]
I was wondering if you could actually say that you need to have a title on your page for that error message.

And I think links to Readwise and Arxiv would make the description better. 

After those small fixes, I guess we can merge your extension :)

**Comment by razgaon** [comment]
I made changes based on your comments :)
I hope I understood what you meant correctly. Please let me know if there are any additional changes you'd like me to make!

**Review by mil3na — APPROVED** [review]
Good enough! Thanks again for your contribution!

**Pull request merged**
