### PR TITLE
Add irish-rail extension

### PR DESCRIPTION
**Pull request by dave-kav**
## Description

Queries the Irish Rail API for trains due in the next 90 minutes by station and destination.

## Screencast

Screen Recording Jan 09

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
- Could you a [metadata image](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

- Whatever I search for ends here, not sure if it's because that it doesn't work

irish-rail 2024-01-14 at 07 33 43

**Comment by dave-kav** [comment]
@pernielsentikaer interesting, all is working fine in dev mode for me. I wonder if it's geo-restrictians on the API the extension calls. Can you share steps to reproduce what you're seeing please?

**Comment by dave-kav** [comment]
Sorry, I see what you mean, I've fixed it locally, and will push later.

**Comment by pernielsentikaer** [comment]
I tried the latest version and I still don't get any results, I added some debug logs to see where it goes wrong

Raycast15012024-LAQcjamy png@2x

https://api.irishrail.ie/realtime/realtime.asmx/getStationDataByNameXML?StationDesc=Belfast gives me this data:
Raycast15012024-wzQvdzZh png@2x

Is there something I can try, maybe it's my combination?

**Comment by dave-kav** [comment]
@pernielsentikaer Its potentially a data issue... please can you try the following to see if you get similar results:

Origin: Dublin Belfast
Destination: Leave blank.

Results should appear as below:
Screenshot 2024-01-15 at 10 49 58

Then use the search to filter for any of e.g. Bray, Howth, Malahide:
Screenshot 2024-01-15 at 10 52 01

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by dave-kav** [comment]
Thanks for the review @pernielsentikaer! 🙇

**Pull request merged**
