### PR TITLE
Added argument to quick task command

### PR DESCRIPTION
**Pull request by marcmagn1**
## Description

Added an argument to the quick add command so that it can be used for automation via Raycast deeplink scheme

### CODE REVIEW

**Comment by clayton-knapp** [comment]
@marcmagn1 looks like you have a conflict after a PR of mine got merged. Go ahead and fix and I will review

**Comment by pernielsentikaer** [comment]
@marcmagn1 can you fix the merge conflict?

**Comment by pernielsentikaer** [comment]
CC @SandyGifford (maybe)

**Comment by SandyGifford** [comment]
Thanks @pernielsentikaer -

This one could use a little iteration anyway, I think - the argument is an interesting way to prompt the user for input, but I'm not sure it's immediately solving any problems.

If the author returns I'm happy to work through this with them, otherwise I think it's okay to let this one get auto-closed

**Comment by pernielsentikaer** [comment]
Let's close it and revive it if needed

**Pull request closed without merging**
