### PR TITLE
Add custom-folder extension

### PR DESCRIPTION
**Pull request by Ph-lo**
## Description

Create custom MacOS folder images from `png`.
## Screencast
custom-folder-1
custom-folder-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Does it only work with some images? I tried a few times with different images and always getting:

custom-folder 2024-08-02 at 11 46 18

- Could you check the CI errors

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Ph-lo** [comment]
Hi @pernielsentikaer, thank you for the quick review. 
Would you be able to share one of the images you used for your test ?

**Comment by Ph-lo** [comment]
Thanks!
It turns out that it's working as expected. As of now, it only works with PNG images that have a transparent background, which can be seen as simple masking. The behavior you're expecting should be ready in the next version 🙂.

**Comment by pernielsentikaer** [comment]
Can you upload an image so I can test it 🙂

**Comment by Ph-lo** [comment]
Of course, here as an example 
php_logo
You could also test with any png from [www.freepng.fr](https://www.freepng.fr)

**Comment by Ph-lo** [comment]
I ended up adding the feature as an option in the creation form, so the image on the folder can either be a filled mask or shaded tones.

**Comment by pernielsentikaer** [comment]
Let's go 🔥

**Pull request merged**
