### PR TITLE
Update `Slugify` extension - support 'strict' especially useful for apostrophes

### PR DESCRIPTION
**Pull request by xmok**
## Description

Quick little update because I was using the extension today to slugify some blog post titles and the _apostrophes_ were not removed which is not ideal for post URLs. So the extension also shows `Strict` slugs.

## Screencast

https://github.com/user-attachments/assets/42d90620-5764-4b56-a016-60c481c9e33a

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by unreadablename** [comment]
Thanks @xmok for such great finding and work. But let's keep old number of menu items but make them strict (without strict badge)
What do you think?

**Comment by xmok** [comment]
I'm fine with that but just to give the option, we could do what I did in a previous iteration of the extension i.e. we can move the Strict options into a `List.Dropdown` defaulting to **Strict** - this way on the off-chance someone _does_ want the non-strict option, they can select it.

**Comment by xmok** [comment]
Updated screencast 😄.

https://github.com/user-attachments/assets/fa78f179-7a52-49e3-b7a9-49e97719b5d7

**Comment by unreadablename** [comment]
@xmok thanks, let's go this way

**Pull request merged**
