### PR TITLE
Add `HestiaCP` (Admin) extension

### PR DESCRIPTION
**Pull request by xmok**
## Description

This is a Raycast extension for [Hestia Control Panel](https://hestiacp.com/) Admin level accounts. With this extension you can manage Users, Domains, Mail Domains, Databases, and more. This is an extension I started in February but only recently got the time to work more on. Thus, there are a LOT of features/endpoints/commands that I have NOT yet incorporated but will in the future as I am running HestiaCP (see last section of README).

## Screencast

https://github.com/raycast/extensions/assets/30526133/94dc81d5-a38e-4669-ad2f-326e521f6f4d

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

Do you know if there is a way to get a demo/sample API from Hestia? At the moment, I don't have access to it, which makes it difficult for testing.

**Comment by mil3na** [comment]
Well, based on the video you provided, it seems to be okay. Can you give an extra test on possible error cases, like when the user is not logged in or missing preferences? Then, we should be good to merge.

**Comment by xmok** [comment]
I sightly tweaked the error handling to make it more robust and made the README a little easier.

All Preferences in the extension are `required` but if they are incorrect, here are some error cases:

1 Invalid URL e.g. w/o "https"
hestiacp-admin-1-invalid-url

2 API is Disabled in HestiaCP
hestiacp-admin-2-api-disabled

3 IP is not whitelisted in HestiaCP
hestiacp-admin-3-ip-not-allowed

4 Invalid Auth e.g. invalid length of Hash
hestiacp-admin-4-invalid-auth-1

5 Invalid Auth e.g. incorrect Key
hestiacp-admin-5-invalid-auth-2

6 Trying to add a DB when you have exceeded the limit
hestiacp-admin-6-db-limit

**Review by mil3na — APPROVED** [review]
LGTM!

**Pull request merged**
