### PR TITLE
Add Wikipedia extension

### PR DESCRIPTION
**Pull request by vimtor**
## Description

Add basic Wikipedia extension to search article summaries and show random articles for fun

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/36263538/144423994-49fe8ac5-ac5a-44e4-83dc-2d9a91e2f43c.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Comment by unnamedd** [comment]
Hello @vimtor, 

would be very interesting if you show a brief description about each item in the list coming from the Wikipedia's page, like we have here, in the `Define Word`:

image

Here, for example I have one endpoint where you can get some structured information about the Wikipedia's page:
`https://en.wikipedia.org/api/rest_v1/page/summary/Apple` (You can change the `/Apple` to something else)

And here is the response for the URL above:
image

I'm pretty sure this will enrich your extension!

**Comment by vimtor** [comment]
Awesome @unnamedd I will add this suggestion 😄

**Comment by pernielsentikaer** [comment]
Are you going to add this in this PR @vimtor 😄

**Comment by vimtor** [comment]
Hey @pernielsentikaer and @unnamedd I added the mentioned things and also a new `Featured Article` command :)

https://user-images.githubusercontent.com/36263538/144924720-a495bbc2-ae27-45cf-9c9e-59b34cf9f6e5.mp4

Feel free to publish the extension if you find it ready :)

**Comment by unnamedd** [comment]
@vimtor amazing result!! ❤️

**Comment by pernielsentikaer** [comment]
Hi @vimtor 👋 

Awesome addition, it was a great idea! Is it on purpose it only shows first paragraph of the content or that a bug?

GWEgvUKAwBtqU43X

I would also suggest to call "Copy Extract" "Copy Content" instead 😄

**Comment by vimtor** [comment]
`Copy Content` seems better

Right now is only showing a summary of the page. We can try to use the whole page but I am unsure about how it will look.

**Comment by pernielsentikaer** [comment]
@vimtor I think it would be awesome to try and check how it looks, I didn't get it so I think others will think the same, are you able to try it out?

Awesome extension 🔥

**Comment by vimtor** [comment]
Hey after some hacking I got it working:

https://user-images.githubusercontent.com/36263538/145679243-87f4e70d-c5c1-47d9-b98a-449f6896760b.mp4

A few considerations:
- I renamed the command to `Copy Summary` which only copies the first paragraph like before. We could add one for copying the markdown but does not seem useful to be honest.
- Also, I removed images from the article since they did not load (specially images inside links).
- I had to add special rules for transforming the HTML of Wikipedia to markdown, but further testing should be done to prevent edge cases

**Comment by pernielsentikaer** [comment]
What an update @vimtor 🔥 I think it's a shame that summary is not a part of the content anymore, is that an error?

**Comment by vimtor** [comment]
> What an update @vimtor 🔥 I think it's a shame that summary is not a part of the content anymore, is that an error?

Ohh you are right, I will bring it back no worries :)

**Comment by pernielsentikaer** [comment]
@vimtor if you need help with anything, please let me know, and I will do my best to assist 😄

**Pull request merged**
