### PR TITLE
[New Extension] Add timezone-converter extension

### PR DESCRIPTION
**Pull request by joaom182**
## Description

It's a handy timezone converter tool, that converts any timezone to any timezone.

## Screencast

https://user-images.githubusercontent.com/3612098/219062404-a239fc46-f376-4a6a-938b-9655b6b5f73d.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Thanks for your contribution 🔥 

I changed the code a bit; could you check the corrections out? 

It feels like some timezones are missing, but I can't be sure 😄

Would it make sense to add the time diff after the entries in the list?

Raycast-Io1O9OXB@2x

**Comment by joaom182** [comment]
Hi @pernielsentikaer

> I changed the code a bit; could you check the corrections out?

Good catches, thank you!

> It feels like some timezones are missing, but I can't be sure 

I'm using [ECMAScript Internationalization](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) API.

> Would it make sense to add the time diff after the entries in the list?

That's a great ideia, what about like this?

Screen Shot 2023-02-17 at 00 19 26
Screen Shot 2023-02-17 at 00 19 16

**Comment by pernielsentikaer** [comment]
It looks awesome @joaom182 🔥  I added a few details - can you give it another spin?

**Comment by joaom182** [comment]
Great, I like the confirm action and the indication with colors of a destructive action in the menu! 🔥

I've changed the `Colors.Red` to `Colors.Orange` on the time diff tag item, to have a more neutral communication to not indicate something good/bad.

Also there is something odd happening with the list component 🤔

https://user-images.githubusercontent.com/3612098/219658885-40d3d33d-8ffb-4b83-948d-c8ebc4d43e8e.mov

**Comment by pernielsentikaer** [comment]
> Also there is something odd happening with the list component 🤔

It's a bug in Raycast; you didn't do anything wrong.

We can wait a few days and see if we can fix it before the next release or just release and hope it's fixed soon

What do you think?

**Comment by joaom182** [comment]
@pernielsentikaer Let me remove that time diff for now, because that is what is causing the line break on the tags list. Once the issue is fixed, I bring that feature back.

Let's do it just for the time being to keep a consistent experience.

Does that sound good to you?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Comment by sxn** [comment]
this issue _should_ have been fixed in 1.57.0. Mind checking?

**Comment by joaom182** [comment]
@sxn sure! I'll check it this weekend.

**Pull request merged**
