### PR TITLE
Add oxford-collocation-dictionary extension

### PR DESCRIPTION
**Pull request by guivictorr**
## Description

This extension scrapes the [Online Oxford Collocation Dictionary](https://www.freecollocation.com) allowing the user to look up word collocations.

## Screencast

https://github.com/user-attachments/assets/4829de7b-e8d2-4900-ab8e-b3b0c0dece17

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The logo in List.Emptyview is not looking good in light mode, you can set both one for dark and light mode

oxford-collocation-dictionary 2024-08-20 at 12 00 28

- Showing another image while searching should be avoided

oxford-collocation-dictionary 2024-08-20 at 12 01 23

- The extension suffers from [Empty State Flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) when you use the action `View Collocations as List`

- Should it support arguments and get selected text from the clipboard too?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by guivictorr** [comment]
I don't know exactly why the flicker is happening but I've implemented a fake loading of 500ms and it's working

About the last point, I didn't understand what do you meant by supporting arguments and getting the selected text. Today the user can copy the collocation to the clipboard.

**Comment by pernielsentikaer** [comment]
You can get the [selected text](https://developers.raycast.com/api-reference/environment#getselectedtext) to use when opening the command, also [arguments](https://developers.raycast.com/information/lifecycle/arguments) could maybe make sense

First take selected text if set, then the argument

**Comment by guivictorr** [comment]
I'll try to implement this selected text, it's a good feature. And maybe take a look if I can do something with arguments

**Comment by pernielsentikaer** [comment]
Is this ready for another review?

**Comment by guivictorr** [comment]
Yeah sure, I've created a separate command to search the selected text

**Comment by pernielsentikaer** [comment]
Awesome corrections 🙂

A bit more you could do: 

-  I would use the same image for both the extension and the List.EmptyView 🙂

-  The image for List.EmptyView should be around 96x96 or 128x128; it looks way too big right now 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
