### PR TITLE
[Dub] Fixed retry for shortening failures

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

Fixed retry for shortening failures and open short links within toast with a push.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jfkisafk** [comment]
Hello @steven-tey / @devkiran / @quuu , can you please take a look?

**Comment by jfkisafk** [comment]
Hello @peduarte / @pernielsentikaer , can you please take a look and merge the fix if possible? I could not get traction from other contributors.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by jfkisafk** [comment]
Thanks @pernielsentikaer , can we merge this too?

**Comment by pernielsentikaer** [comment]
Yes we can 🙂

**Pull request merged**
