### PR TITLE
Update laravel-tips extension

### PR DESCRIPTION
**Pull request by godruoyi**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Can I compile like last time @godruoyi

**Comment by godruoyi** [comment]
Wow, thank you for the quick reply @pernielsentikaer. Yes, you can compile it, but don't forget to specify the target using `--target` as shown below:

```
cargo build --release --target x86_64-apple-darwin
```

Because my computer has an M1 chip, the binary files compiled by default cannot run on x86 platforms. However, we can specify the `target` as x86 so that the binary can run on both M1 and x86 platforms.

**Comment by pernielsentikaer** [comment]
Can you see if I compiled correct @godruoyi

**Comment by godruoyi** [comment]
Hi @pernielsentikaer, I downloaded your compiled binary and tested it on my local M1/Intel environment. It worked without any issues.

Here is my test setup:

```
# remove old data and binary
rm ./laraveltips*
rm ./.db3


# download
wget --no-check-certificate https://github.com/raycast/extensions/raw/3c8edf815e5f64f739e757801998db39b78d1a98/extensions/laravel-tips/assets/laraveltips

chmod +x ./laraveltips

./laraveltips --path ./ sync
./laraveltips --path ./ -o json random
```

I use the same test setup on my M1 and inter computer, it's work fine for me.
image
CleanShot 2023-06-21 at 11 17 41@2x

**Pull request merged**
