### PR TITLE
Add DekuDeals extension

### PR DESCRIPTION
**Pull request by rrroyal**
## Description
This PR adds [DekuDeals](https://dekudeals.com) extension, allowing users to search for various games (or other items) listed on DekuDeals.
Extension requires `rack.session` cookie (README includes instructions on how to grab it).

## Screencast
https://user-images.githubusercontent.com/23171377/169994594-397ea8b4-6694-4ba1-a529-5218e1eb0a81.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

This is not the best solution since not all users know how to do this, do you think there are other ways to do this, like generating an API token in the interface behind?

**Comment by rrroyal** [comment]
heyo!
not to my knowledge - DekuDeals doesn't expose any actual API (as you can see by the scrapping code) :/

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @rrroyal 👋 

Sorry for the long response time; my bad! 

What is the session cookie being used for?

I just tried to enter `hello` and it seems to be giving me examples, can you have a look?

It seems like I have to enter at least three characters before it's giving me results, maybe this should be afflicted in the [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview)?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by rrroyal** [comment]
hi!
it looks like the session token was made optional in the time between first version and this pr - I've made it optional, as it will come in handy if I decide to add support for adding stuff to favourites!

i've also added the search query disclaimer as you've suggested - take a look!

**Review by pernielsentikaer — APPROVED** [review]
Thanks for the contribution, much better 🔥

**Pull request merged**
