### PR TITLE
[Apple Notes] #3652 Correct issue where searching for notes failed

### PR DESCRIPTION
**Pull request by ron-myers**
## Description

Added error handling for failing to open notes towards #3652

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you mind testing this @tumispro

**Comment by tumispro** [comment]
> Do you mind testing this @tumispro

Yeah I'll schedule some time tonight!

**Comment by tumispro** [comment]
Not sure if this is supposed to work like this, but I tried to open a deleted note and got this:

Screenshot 2022-12-10 at 12 38 42

**Comment by ron-myers** [comment]
Thanks for testing this @tumispro.  

I have a few thoughts on the deleted note opening and related to this extension:

1. this pull request is to correct escaping titles when opening around #3652 - this shouldn't change the behavior of deleted notes.  I created a note with that same name, searched for it, opened it, deleted it, searched for it, and then opened it successfully. My gut says that note is in your search cache but not available in your notes app - is that true?
2. we should add a filter to remove deleted notes from the search
3. we add a preference to keep them in the search for people that prefer them to be available.
4. we should make searching using SQL the default, add a preference for what source people want to use for their notes.

I prefer to merge this to see if we correct #3652, I will work on the above over the holidays.  How does that sound?

**Comment by tumispro** [comment]
Good stuff. Seems to work fine now with folders containing special characters like "Themes & Names." as in the mentioned issue, so I think this can be merged now @pernielsentikaer.

As for your comment about the deleted note: I both deleted it and then emptied trash, and then tried to open it while the list wasn't yet refreshed. But I think this is an edge case that we don't really have to handle, as it is really rare and resolves itself right after. Still, I agree with your second point about being able to filter them out. 

I don't really have much time to work on it currently, but I'm glad to help test stuff that you build :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
