### PR TITLE
🍿⏱️: Add binge-clock extension

### PR DESCRIPTION
**Pull request by Aayush9029**
## Description

- Ability to search for a movie or TV show
- Ability to get complete watch time information for a movie or TV show

## Screencast
binge-clock-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Add a better [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) with explanation about you have to type four characters.

* Add a toast about copy to clipboard, otherwise it felt like nothing happened

* Add OpenInBrowser too 🙂  

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Aayush9029** [comment]
- [x] List.Empty View on empty search results or empty search term.
- [x] Toast for copy to clipboard
- [x] Open in browser

**Review by Aayush9029 — COMMENTED** [review]
LGTM

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
