### PR TITLE
Update pipedrive extension

### PR DESCRIPTION
**Pull request by cimnine**
## Description

- Updates the dependencies
- Makes the org name copyable

## Screencast

grafik

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

I'm having trouble testing your changes as nothing loads when I try the extension. @ahpatel do you mind testing this and telling us if you are okay with the changes?

**Comment by ahpatel** [comment]
@mil3na doing a quick skim of the changes, there is some code missing for executing the shortcut Action.  And, there is probably an updated library that broke something.   

I am traveling through the end of the month and don't have access to my device to test so I won't be able to look at it until I return in August.

**Comment by ahpatel** [comment]
@mil3na there looks to be some code missing for the shortcut Action.  And, the blanket library updates likely broke something.  

I am traveling through the end of the month so won't have a chance to look at it until I return in August.  But, should be an easy add once I review.

**Comment by cimnine** [comment]
@ahpatel it'd appreciate your feedback on this.

**Comment by ahpatel** [comment]
This functionality already exists, using Cmd+N from the action menu.  

@cimnine - are you not able to use the existing functionality?

**Comment by pernielsentikaer** [comment]
@ahpatel are you back yet?

**Comment by ahpatel** [comment]
@pernielsentikaer yes, I'm back.  Please reject these changes.  I have an implementation I was using locally for the last few months and will publish the changes this week.

**Comment by pernielsentikaer** [comment]
Will it cover what @cimnine is doing and please add `cmdr` as contributor

**Pull request closed without merging**
