### PR TITLE
Add code-saver extension

### PR DESCRIPTION
**Pull request by Gnosnay**
## Description

Store your code snippets and export them freely when you need it.

Pure local managed Snippet store. You should 
1. Pick one local data store first. 
2. Create one Library then
3. Create snippet that you need.
4. Brower the snippts you created.

## Screencast

code-saver-1
code-saver-2
code-saver-3
code-saver-4
code-saver-5
code-saver-6
code-saver-7
code-saver-8
code-saver-9
code-saver-10

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Gnosnay** [comment]
@pernielsentikaer

sorry again, the original extension repo is broken. I refactored it and use another way to download the binary dynamically. 

https://github.com/raycast/extensions/pull/9241#issuecomment-1809852880

the reason why i have to use sqlite driver binary is that i have to manage the table migration. In other words, it seems that raycast API doesn't give one way to manage the sqlite table definition change...

Without this sqlite driver and drizzle orm, it will be very trivial and troublesome to maintain the DB migration...
I am so sorry for that i can not use `useSql` directly. Because it seems that `useSql` can not execute DDL.

feel free to point it out if you still have concern for this change. Thank you so much!!

**Comment by pernielsentikaer** [comment]
Hi @Gnosnay 👋 

Do you have a clue on how to fix this error, I can't install the extension 🙂

Raycast-MVaMqp6b@2x

**Comment by Gnosnay** [comment]
> Hi @Gnosnay 👋
> 
> Do you have a clue on how to fix this error, I can't install the extension 🙂
> 
> Raycast-MVaMqp6b@2x

image
hi @pernielsentikaer this is my installation. let me have one look on this.

**Comment by Gnosnay** [comment]
image
@pernielsentikaer it seems that react-devtools is using electron v1.8.8.

let me change the version of react-devtools

**Comment by pernielsentikaer** [comment]
Do you use it? You're right, removing it solved that part 🙂

**Comment by Gnosnay** [comment]
@pernielsentikaer hi something wrong with the `raycast api pull contribution`.
i have to create one more PR. sorry for that.
new PR can be found https://github.com/raycast/extensions/pull/9340

**Pull request closed without merging**
