### PR TITLE
OpenAI Text Completion and DALL•E Image Generator Extension

### PR DESCRIPTION
**Pull request by josephschmitt**
## Description

The `ai-gen` extension provides commands that use the OpenAI [Image Generation](https://beta.openai.com/docs/guides/images) API — colloquially known as [DALL·E 2](https://openai.com/dall-e-2/) — and the [Text Completion](https://beta.openai.com/docs/guides/completion) API to generate results from a text-based prompt.

### API Keys

In order to use OpenAI's APIs, you have to create an account and create [a new API key](https://beta.openai.com/account/api-keys). Once you have a key, paste it into the extenion's settings.

Please make sure to [familiarize yourself](https://beta.openai.com/docs/guides/images/introduction) with the API's limits. While it's super fun to just start immediately generating images, the Create Image API is heavily rate-limited (you'll be limited to 10 images per minute, and 25 per 5 minutes) and even the Text Completion API can run up a bill if you push it hard enough.

When you create a free account, you're granted $18 worth of credits for 12 months. Once you blow through your free credits, you'll be blocked from making more requests until you enter billing information.

## [Pricing](https://openai.com/api/pricing/)

The DALL·E Create Image API is priced based on image dimensions:

| Size       | Price          |
| ---------- | -------------- |
| 1024×1024  | $0.020 / image |
| 512×512    | $0.018 / image |
| 256×256    | $0.016 / image |

The [GPT-3](https://beta.openai.com/docs/models/gpt-3) Text Completion API is priced based on [token](https://beta.openai.com/tokenizer) usage:

| AI Model                | Price
| ----------------------- | -------------------- |
| Ada (Fastest)           | $0.0004  / 1K tokens |
| Babbage                 | $0.0005  / 1K tokens |
| Curie                   | $0.0020  / 1K tokens |
| Davinci (Most powerful) | $0.0200  / 1K tokens |

## Screenshots
ai-gen-1
ai-gen-2
ai-gen-3
ai-gen-4
ai-gen-5
ai-gen-6

## Known Issues

Generating images is literally not free, and is computationally expensive. Therefore this extension uses a Form UI so that the text prompt can be crafted without worrying about submitting an API request too early. However, the results that are displayed are still rendered in a Grid. This is fine, except for the fact that there's no way to disable searching in a Grid view. There's no useful metadata to filter on, the API just returns image url's. So I'm just displaying the prompt as a placeholder and then do nothing if a user accidentally types in it. Not the greatest. If you have a better suggestion, let me know.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* Please select if metadata images should be shown in light or dark theme, don't mix em' 😊

* Nothing in the `package.json` mentions DALL-E - is that correct?

* If the wrong API is used it never stops loading, would be nice to handle this too 😊

CleanShot 2022-11-07 at 13 57 21@2x


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by josephschmitt** [comment]
> Please select if metadata images should be shown in light or dark theme, don't mix em'
Oops, those aren't supposed to be there, I forgot I had the plugin in Raycast still saving files there

> Nothing in the package.json mentions DALL-E - is that correct?
I don't believe so, why?

> If the wrong API is used it never stops loading, would be nice to handle this too 😊
What do you mean by the wrong API?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for the corrections 💪 

Checked it again and I like the solutions, well done 👨‍🍳 

* When submitting "Create Image" there is [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

* Would it be possible to add a title/description to the Emptyview?

CleanShot 2022-11-08 at 08 39 20@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by josephschmitt** [comment]
> * When submitting "Create Image" there is [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)
> * Would it be possible to add a title/description to the Emptyview?

Done! 

I also customized the empty state for when there's an error:
ai-gen 2022-11-08 at 11 03 11

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
