### PR TITLE
Add Google Trends extension

### PR DESCRIPTION
**Pull request by kkange**
## Description

Daily and real-time trend data from each country provided by Google Trends.

- ### command
```
- The "Show daily" command shows the daily trends.
- The "Show Realtime" command shows the real-time trends.
```

- ### action
```
- The "Open Artlcle in Browser" action shows the trends article.
- The "Open Trend in Browser" action shows the google trends page.
```

## Type of change

- New extension

## Screencast
[Show daily](https://imgur.com/Pe579G0)
[Show Realtime](https://imgur.com/ME6j9hk)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi @kkange 👋 

What an extension to start out with 💪 

Couldn't find anything that should be changed, so I'm going to accept it as it is, well done!

My colleague will do the last check before merging it 💯

**Comment by moskalukigor** [comment]
Hi @kkange. How do I change the country and language? After choosing this the first time, I cannot change anything.

**Comment by kkange** [comment]
> Hi @kkange. How do I change the country and language? After choosing this the first time, I cannot change anything.

Hi

You can find and change the toolbox in the Raycast Settings extension item.

**Comment by pernielsentikaer** [comment]
@moskalukigor as @kkange wrote, check the settings:

eODLXKfMEFiTK1SX

**Comment by moskalukigor** [comment]
@kkange @pernielsentikaer 
I somehow didn’t notice it. Thanks!

**Pull request merged**
