### PR TITLE
remove deprecated commands for scrcpy

### PR DESCRIPTION
**Pull request by lukutism**
## Description

Removed deprecated flags for scrcpy extension.
https://github.com/Genymobile/scrcpy/blob/master/doc/keyboard.md
https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by bxb100 — COMMENTED** [review]
https://github.com/Genymobile/scrcpy/blob/master/doc/keyboard.md#uhid
`it works over TCP/IP (wirelessly) (contrary to --keyboard=aoa)`

it seems can remove `USB only`

**Comment by lukutism** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/doc/keyboard.md#uhid `it works over TCP/IP (wirelessly) (contrary to --keyboard=aoa)`
> 
> https://github.com/lukutism/extensions/blob/0c0e9f21360b7952d5d16f246807874d40ab471f/extensions/scrcpy/src/index.tsx#L83-L84
> 
> using `uhid` can work on both wireless and USB, so can we remove `USB only`?
> 
> and @lukutism you forgot to write CHANGELOG

Thanks for review, done :)

**Review by bxb100 — APPROVED** [review]
LGTM

**Comment by lukutism** [comment]
@bxb100 It's possible please merge. :)

**Comment by bxb100** [comment]
don't know, I'm just a contributor like you

**Pull request merged**
