### PR TITLE
Feature/unblock build action

### PR DESCRIPTION
**Pull request by bennnym**
## Description

Add an unblock pipeline action to the MyBuilds command

## Checklist

- [ ✅ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ✅ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [✅  ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ✅ ] I checked that files in the `assets` folder are used by the extension itself
- [ ✅ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
There is something wrong with the file structure here, can you look into that?

**Comment by bennnym** [comment]
What do you mean exactly @pernielsentikaer ?

As far as I know I just added one file. Do you have some particular file format you're trying to adhere to?

**Comment by pernielsentikaer** [comment]
You added 32 files 🙂

**Comment by bennnym** [comment]
I'll check it out

**Pull request closed without merging**
