### PR TITLE
Update battery-health extension

### PR DESCRIPTION
**Pull request by menahishayan**
## Description

feat: ✨ added the ability to view your battery's health relative to when it was new

## Screencast

Screenshot 2024-12-24 at 2 02 43 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by o1y** [comment]
Danke für deine Contribution. Die Health Angabe scheint nicht übereinzustimmen mit der Angabe der maximalen Kapazität im Systembericht. Meines Wissens nach lässt sich dieser Wert nicht wie 


```

**Comment by o1y** [comment]
Thanks for your contribution @menahishayan! As far as I understand, the Health value cannot be accurately represented using the following calculation:

```javascript
values["health"] = ((AppleRawMaxCapacity / DesignCapacity) * 100).toFixed(1) + "%";
```

The result doesn't align with the health information displayed in the system report. When I developed the extension, I couldn't find a reliable way to extract that value directly. In my case, the calculated value is significantly lower than the one provided by Apple, which could be confusing for users.

**Comment by menahishayan** [comment]
Hey @o1y,

Thanks for the info. I've compared this value with other popular apps like [CoconutBattery](https://coconut-flavour.com/coconutbattery/) and the value is consistent with what they display. 

While it may not be exactly the same as the System Report, it's close enough to a point where I believe it's more useful to **_show_** the value than to omit it entirely.

**Comment by menahishayan** [comment]
Update: I've changed the calculation to be slightly more accurate to the System Report value. It's not 100% but the margin of error is now smaller.

**Comment by o1y** [comment]
I've added the Maximum Capacity value from the system profiler in #16032.

**Review by 0unsalalcin0 — APPROVED** [review]

**Comment by menahishayan** [comment]
Closing in favor of https://github.com/raycast/extensions/pull/16032

**Comment by menahishayan** [comment]
Closing in favor of https://github.com/raycast/extensions/pull/16032

**Pull request closed without merging**
