### PR TITLE
GitLab: adds option to filter "My Merge Requests"

### PR DESCRIPTION
**Pull request by wierdbytes**
## Description

Before this PR command "My Merge Requests" displayed MRs with any state (opened, closed, merged, ...). I found this not convinient for my workflow. This changes will provide ability to choose option in preferences to specify which state of MRs should be displayed.

## Screencast

изображение

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Loskir** [comment]
Thank you for your contribution! 

Have you tried using [list dropdown](https://developers.raycast.com/api-reference/user-interface/list#dropdown) instead?

**Comment by danielsequeira** [comment]
> Thank you for your contribution!
> 
> Have you tried using [list dropdown](https://developers.raycast.com/api-reference/user-interface/list#dropdown) instead?

I was actually going to propose the same thing. I think that in terms of UX makes a lot more sense to have this as a list dropdown inside the "My Merge Requests" command instead of having it as a preferences setting.

**Comment by Loskir** [comment]
I see, interesting...
Could someone from Raycast give an advice?

**Comment by tonka3000** [comment]
@wierdbytes @Loskir Use [ActionPanel.Submenu](https://developers.raycast.com/api-reference/user-interface/action-panel#actionpanel.submenu). With this you can achieve the same. Use the cache features from raycast api if you wanna remember the action.

**Comment by metakirby5** [comment]
Another suggestion is to have a checkbox preference to toggle which control gets to be shown as the list filter. Then, users can see the one that fits their preference.

**Pull request closed without merging**
