### PR TITLE
Update some extension icon with a better look and style

### PR DESCRIPTION
**Pull request by RaffeYang**
…size.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
Oh thanks for doing this. Was there a specific workflow that you used to achieve a consistent size?

**Comment by Jax0rz** [comment]
> Oh thanks for doing this. Was there a specific workflow that you used to achieve a consistent size?

I think this [script](https://github.com/elrumo/macOS_Big_Sur_icons_replacements) is very useful.
You could force developers to use fixed size and rounded corner style icons, just like iOS mandates, so that raycast interactions would be more coordinated and uniform,here is a example showcase :
CleanShot 2022-09-19 at 14 47 13@2x

**Review by thomaspaulmann — CHANGES_REQUESTED** [review]
@Jax0rz looks like some images are not the correct size. Can you please fix and re-request a review?

**Review by thomaspaulmann — CHANGES_REQUESTED** [review]
Thanks for fixing it quickly. Looks like you added a new extensions called `chinese-numbers` as a git submodule. Could you please remove the extension? And if you want to publish it, open a new pull request without being it a submodule. Then, we should be ready to merge this change.

**Review by Jax0rz — COMMENTED** [review]
Update some extension icon

**Review by Jax0rz — COMMENTED** [review]
Update some extension icon

**Review by Jax0rz — COMMENTED** [review]
Update some extension icon with a better look and style

**Review by Jax0rz — COMMENTED** [review]
Add more icon

**Comment by peduarte** [comment]
good effort!

**Pull request merged**
