### PR TITLE
Create LoL esports extension

### PR DESCRIPTION
**Pull request by vimtor**
## Description

Raycast extension to show [LoL eSports (League of Legends)](https://lolesports.com/schedule) upcoming matches and rankings.

## Screencast

https://share.cleanshot.com/mgcq2N1K

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @vimtor 🔥

I tried to test the two commands, but both gave me this error. Did you experience that before?

**Comment by vimtor** [comment]
It's working for me. What error is it giving you @pernielsentikaer?

**Comment by pernielsentikaer** [comment]
I'm just getting this

```
08:05:06.797 Error: Bad Request
    at Object.defaultParsing [as current] (/Users/pernielsentikaer/.config/raycast/extensions/lol-esports/show-standings.js:4134:15)
    at /Users/pernielsentikaer/.config/raycast/extensions/lol-esports/show-standings.js:4156:39
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by vimtor** [comment]
Hi @pernielsentikaer!

I'm unsure how to proceed with this. I've tried reinstalling the extension, and it works fine.

What do you suggest?

**Comment by pernielsentikaer** [comment]
@mil3na does this extension work for you?

**Comment by mil3na** [comment]
@pernielsentikaer it doesn't work. I get the following error:
```
Error: Bad Request
    at Object.defaultParsing [as current] (/Users/milena/.config/raycast/extensions/lol-esports/show-schedule.js:4134:15)
    at /Users/milena/.config/raycast/extensions/lol-esports/show-schedule.js:4156:39
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by pernielsentikaer** [comment]
Exact same error as I got -  are you logged in @vimtor

**Comment by vimtor** [comment]
@pernielsentikaer I'm not logged in. In theory, I'm using their unofficial API. The request below should provide you with a list of match results.

```
curl 'https://esports-api.lolesports.com/persisted/gw/getSchedule?hl=es-ES&leagueId=98767991302996019' \
  -H 'accept: application/json' \
  -H 'x-api-key: 0TvQnueqKa5mxJntVWt0w4LpLfEkrV1Ta8rQBb9Z'
  ```

Does it give you the same error?

**Comment by pernielsentikaer** [comment]
No, that works as expected @vimtor 

Raycast25022024-vpsV9bq6 png@2x

**Comment by vimtor** [comment]
@pernielsentikaer, I've just added the missing `Accept` header for you to see if that was the issue (I suspect it is not).

The `useFetch` hook might be adding extra headers, causing the error. The `useAPI` hook uses a basic `useFetch` version of the `curl` command. Maybe you know something more about `useFetch` that I don't?

Have you checked if the error is resolved by visiting https://lolesports.com/schedule?leagues=lec,emea_masters?

**Comment by pernielsentikaer** [comment]
So the issue is that `Intl.DateTimeFormat().resolvedOptions().locale` in my case returns `en-DK-u-hc-h23` - is hardcoding it to `es-ES` makes it work as expected.

**Comment by vimtor** [comment]
Thank you for looking into it, @pernielsentikaer

It was really obvious in hindsight 🤦‍♂️ 

I've hardcoded the `en-US` value, so the extension should work now.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
