### PR TITLE
New Extension: Pinata

### PR DESCRIPTION
**Pull request by stevedylandev**
## Description

I'm submitting a new extension for [Pinata](https://pinata.cloud), a Web3 media distribution platform using IPFS. The extension requires users to input their Pinata API keys, which instructions in the readme file. After inputing the required keys the user can upload files, list files, share or view files, and generated time sensitive links for private files. 

## Screencast

[Link to Video!](https://pinata-media.mypinata.cloud/ipfs/QmNY29kxvkJK6fUqG31ivaN3di4ujhVnw9dUCvPnH6VU6Y?stream=true)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @stevedsimkins 👋 

I just created a test account (testuser@raycast.com). Can you somehow help me with a PRO plan for a couple of days so I can test or share some keys for me to test with? Can you DM me in [Slack](https://www.raycast.com/community) or in [Twitter](https://twitter.com/pertikaer/)?

**Comment by stevedsimkins** [comment]
Hey @pernielsentikaer! 

I just applied a coupon to your test account that will give you the Picnic plan 30 days free! Could you try visiting the [billing](https://app.pinata.cloud/billing) page and select the Picnic plan?

**Comment by stevedsimkins** [comment]
If that doesn't work I can absolutely provide some API keys and a gateway to use :)

**Comment by pernielsentikaer** [comment]
That didn't work, just seeing this 
Raycast-pHZAPrqH@2x

I guess we have to do the other thing instead 😊

**Comment by stevedsimkins** [comment]
Ahh sorry bout that! I'm sending a DM now via Slack :)

**Comment by stevedsimkins** [comment]
@pernielsentikaer Made the changes to listSubmarineFiles! I also might do one last touch to see if I can bring back the loading gif for listFiles since that call takes a while, and its fun 😂

**Comment by pernielsentikaer** [comment]
You go play around, make sure not to make the image too big 😊

**Comment by stevedsimkins** [comment]
@pernielsentikaer Ok! I think it's ready 👀

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
