### PR TITLE
Pocket extension improvements

### PR DESCRIPTION
**Pull request by vimtor**
## Description

- Cache results for faster search
- Use native Pocket search to avoid rate-limits
- Add `Menu Bookmarks` command for quick access to the latest bookmarks
- Add `Create Bookmark` command for manual creation
- Add `Save Current Tab` command for creating bookmarks from URLs
- Rename `Random Bookmark`, `Latest Bookmark` and `Save Clipboard` commands
- Add confirmation modal on bookmark delete
- Add Pocket tags filter to `Search Bookmarks` command
- Add `Copy as Markdown URL` option in `Search Bookmarks`

## Screencast

 

https://user-images.githubusercontent.com/36263538/191830617-453f3363-954d-4a6e-afa2-e98ac06b8be6.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @vimtor 👋 

Thanks for your update 💪

I tried to make some new credentials but got stuck with the last `curl` call

CleanShot 2022-09-27 at 22 10 05@2x

First response don't give any output back, and the second says `Forbidden`, can you try to check the README?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by vimtor** [comment]
Hi @pernielsentikaer!

I haven't changed anything regarding the setup. Can you try it again?

**Comment by pernielsentikaer** [comment]
Let me try to set it up again, last time I was not able to do so 😊

**Comment by pernielsentikaer** [comment]
I followed all steps in the README again, and this time, I didn't get any reply from the last `authorize` call.

Raycast-PYblA29s@2x

Do you have an idea what might be wrong, I used `web` as the platform.

**Comment by vimtor** [comment]
I will review this PR next weekend @pernielsentikaer

**Pull request closed without merging**
