### PR TITLE
Adding Laravel Forge extension

### PR DESCRIPTION
**Pull request by aglipanci**
## Laravel Forge

This [Raycast](https://raycast.com) extension lets you quickly find and open your [Laravel Forge](https://forge.laravel.com) sites and servers.

## Type of change

- New extension

## Screencast

Screenshot 2022-01-04 at 21 20 25

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
FWIW I've been working on a more robust Forge extension here that I planned to submit a PR for next week after I work on a feature for accessing/updating environment variables.

https://github.com/KevinBatdorf/laravel-forge-raycast

**Comment by aglipanci** [comment]
@KevinBatdorf looks awesome! Mine is a very simpler version that I use daily for my work.

Do you want me to close my PR?

**Comment by KevinBatdorf** [comment]
> Do you want me to close my PR?

I don't know the answer. I could PR mine later today in it's current state if you find it's useful. Do you want to test the one I've been working on and see if you prefer it? I could also just give mine a different name

**Comment by unnamedd** [comment]
> > Do you want me to close my PR?
> 
> I don't know the answer. I could PR mine later today in it's current state if you find it's useful. Do you want to test the one I've been working on and see if you prefer it? I could also just give mine a different name

or maybe both of you could work on one of the extensions together and make it even better to everyone! 
what do you both think, @KevinBatdorf and @aglipanci?

**Comment by pernielsentikaer** [comment]
Also, there is support for "contributors" in package.json 😄

**Comment by aglipanci** [comment]
@unnamedd @pernielsentikaer to be honest as I mentioned I build this very simple version just for my personal needs (and it was inspired by the Alfred Workflow that I was used to), so I don't plan spending anymore time on this for the time being. If you think I should close this to leave space for the @KevinBatdorf extension, I would be more than happy to :)

**Comment by pernielsentikaer** [comment]
It won't make sense to have two extension for the same purpose.

I think the best decision for the users would be to keep the one that will be updated with new features(and bug fixes) and being active developed.

Maybe @KevinBatdorf could use some of this version's code / ideas and incorporate in his version (and then add you as “contributor”)

It could also be the other way around, but as you said, it sounds like you're happy with your version and are not planning to use more time.

Let me know what you both (@aglipanci @KevinBatdorf) think would be the best approach

**Comment by aglipanci** [comment]
@pernielsentikaer I am positive on updating the extension when necessary but I am not planning to add additional features like @KevinBatdorf has. I did test Kevin's extension and it looks very good but for me personally it doesn't work because I just need to open the site or the server and with that it takes a lot of steps.

Anyhow, I am closing this out and Kevin can move forward with his :)

**Comment by KevinBatdorf** [comment]
Hey all, yeah I'm curious how Raycast will handle situations like this. Anyway, it's not a competition, of course, and maybe both extensions would be useful even since they solve different problems.

@aglipanci PR is more like a "lite" version that will open a page in the browser, while my extension attempts to provide all of the day-to-day functionality so you don't need to open that page at all (unless you need to make an uncommon change).

There may be a case to having both extensions but of course ultimately that's up to Raycast.

I was also holding off on a PR as I identified a bug (potentially) in the List Item rendering, but the issue got lost on Slack over the holidays. https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1640566594305400?thread_ts=1640282139.293800&cid=C01A0R0NXGQ

Should I open an issue?

**Comment by pernielsentikaer** [comment]
Hi @KevinBatdorf 👋 

We have integrated support for “contributors” in package.json, which now will show contributors everywhere where the extension is visible, even in the contributors profile page.

This is a great community, and most of the time it's more a question about making the best extension to the community. Most of the time, there will be good chunks in both versions that could be merged into one of them.

In this case, it makes sense to add your extension since it's covering much more, and you still have a few things you want to add down the road.

If the extension already existed, you could have made a PR with the additions – and then it will be a judge by us and the original developer – we always try to focus on making the best and useful extensions for everyone.

Don't hesitate to write if you have any questions 😄

**Pull request closed without merging**
