### PR TITLE
[New Extension]: RayPass - Manage passwords through Raycast that just you and your laptop know.

### PR DESCRIPTION
**Pull request by paul-bokelman**
## Description

RayPass is a local password manager. Passwords are stored in documents in the ./raypass folder in the home directory. A user can create one or many documents, optionally encrypt them, then make as many password records as they please inside them. Users can create, delete, search, and switch between documents. A user can also create, edit, delete, or copy each individual field of a password record. Each password record follows this structure:

```typescript
export interface Record {
  id: string;
  name: string;
  username?: string;
  email?: string;
  password: string;
  url?: string;
  notes?: string;
}
```

## Screencast

https://user-images.githubusercontent.com/72945168/193752304-b2292fd1-c663-4ae6-baf5-3ef3f8c45998.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Did you see the PR from @GastroGeek in your fork? Might be worth checkout out too before we're merging too. Did you want to change the icon, or?

**Comment by paul-bokelman** [comment]
@pernielsentikaer just committed new icon and TOTP integration.

**Comment by GastroGeek** [comment]
Looks like there might be a space/extra newline in `CopyRecordTOTP.action.tsx` as a result of merging @paul-bokelman ? so just needs a `lint --fix` on your end 🙏

**Comment by paul-bokelman** [comment]
> Looks like there might be a space/extra newline in `CopyRecordTOTP.action.tsx` as a result of merging @paul-bokelman ? so just needs a `lint --fix` on your end 🙏

Link does not fix the issue and my editor is not telling me whats wrong.

**Comment by GastroGeek** [comment]
That was quick @paul-bokelman 👍 noice! looking forward to playing with this one! 🤓

**Comment by pernielsentikaer** [comment]
Just a quick question, why not have the documents in the [supportPath](https://developers.raycast.com/api-reference/environment#example) - I think that would make more sense?

**Comment by paul-bokelman** [comment]
> Just a quick question, why not have the documents in the [supportPath](https://developers.raycast.com/api-reference/environment#example) - I think that would make more sense?

I was not aware this existed. I'll migrate it over to that in a few days. Thanks for letting me know.

**Comment by GastroGeek** [comment]
@paul-bokelman if you would be so kind as to simply merge my PR against your original repo, it should include the required changes

from: `~/.raypass` to `environment.supportPath/documents`

🙏

**Comment by paul-bokelman** [comment]
> @paul-bokelman if you would be so kind as to simply merge my PR against your original repo, it should include the required changes
> 
> from: `~/.raypass` to `environment.supportPath/documents`
> 
> 🙏

Life saver

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

It seems like it's possible to get into an endless loop state, can you do something about that?

I attached a video of the error, let me know if you need anything else.

https://user-images.githubusercontent.com/38033107/194852975-8f5b269c-cfa3-42ad-9984-efa489fb6c6f.mp4

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by httpjamesm** [comment]
This is a really cool extension. I just have one concern with your [encryption function](https://github.com/raycast/extensions/pull/3115/files#diff-096bbe3ba829f25aa2a8b2b149855a573eb34c728bfccc1291c771578588f3ccR11). It appears you are using AES-256-CTR but without any authentication (integrity checks). Do you calculate an HMAC in another function?

**Comment by paul-bokelman** [comment]
> Hi 👋
> 
> It seems like it's possible to get into an endless loop state, can you do something about that?
> 
> I attached a video of the error, let me know if you need anything else.
> 
>  CleanShot.2022-10-10.at.13.07.23.mp4 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

I've had lots of work recently, I'll try and resolve this over the weekend. Thanks for letting me know.

**Comment by paul-bokelman** [comment]
> This is a really cool extension. I just have one concern with your [encryption function](https://github.com/raycast/extensions/pull/3115/files#diff-096bbe3ba829f25aa2a8b2b149855a573eb34c728bfccc1291c771578588f3ccR11). It appears you are using AES-256-CTR but without any authentication (integrity checks). Do you calculate an HMAC in another function?

I do not. How would you recommend I go about doing that?

**Comment by httpjamesm** [comment]
> > This is a really cool extension. I just have one concern with your [encryption function](https://github.com/raycast/extensions/pull/3115/files#diff-096bbe3ba829f25aa2a8b2b149855a573eb34c728bfccc1291c771578588f3ccR11). It appears you are using AES-256-CTR but without any authentication (integrity checks). Do you calculate an HMAC in another function?
> 
> 
> 
> I do not. How would you recommend I go about doing that?

Here's a good [gist](https://gist.github.com/mykiimike/eae214a32f81c144950e) that can help you. 

I recommend using a minimum of SHA-256 to create an HMAC hash of both the encrypted data and the secret and store it alongside the encrypted data. On each decrypt, the client should verify that the HMACs match. If they don't, refuse to decrypt and warn the user about potential tampering. 

The reason why these integrity checks are important is because encryption only changes plain text into ciphertext, but a motivated attacker can still change the ciphertext and modify the plain text without the user ever knowing. These integrity checks make it impossible for an attacker to do this without knowing the secret beforehand. 

Here's a [Wikipedia article](https://en.wikipedia.org/wiki/HMAC) on HMAC.

**Comment by pernielsentikaer** [comment]
Thanks for the help @httpjamesm 🔥 

I convert this to a draft until it's implemented, sounds like a good idea

**Comment by paul-bokelman** [comment]
Hey @httpjamesm does this [implementation](https://github.com/paul-bokelman/raypass/commit/843b0fd32b09c46ed7ef4993fd9ed538e7517ebf#diff-af3b7a6b56471e627bc335c3d7ce05fecbdfedde59e9308231f0cacd2d00087e) of an HMAC function satisfy the issue?

I know it's been over a year... hope you're still out there 🙃

**Comment by httpjamesm** [comment]
Your encryption function looks to be hashing the key only. You want to hash `key + cipher` together in an HMAC and store that alongside the encrypted data.

**Pull request closed without merging**
