### PR TITLE
Update harvest extension: major caching upgrade

### LINKED ISSUE #11706: [Harvest] Tasks do not appear on first load
### Extension

https://www.raycast.com/eluce2/harvest

### Description

When I first open the extension there are no Tasks listed. When I switch to a different client project and then back to the original one, the Tasks do appear. Tried uninstall/reinstall to no avail and resetting my account on the Harvest side.

This started happening maybe a month ago. Had worked fine until then.

Screenshot 2024-04-08 at 1 23 09 PM

### Steps To Reproduce

I'm not sure how to reproduce it.

### Current Behaviour

Client Tasks do not load when the extension first starts.

### Expected Behaviour

Tasks should load.

### LINKED ISSUE #11983: [Harvest] ... can't choose task
### Extension

https://www.raycast.com/eluce2/harvest

### Description

Repeatedly, my ability to choose a task disappears. When I delete and reinstall the extension everything works. After some time the option to choose a task disappears.

### Steps To Reproduce

macOS sonoma 14.4.1

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by eluce2**
## Description

Improved how the caching is handled by all API requests improve stability and reduce the number of times the extension would get rate-limited by Harvest.

Fixes #12600
Fixes #11983
Fixes #11706

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by eluce2** [comment]
This PR includes changes inspired by #12600, plus a few other things. I hope I can still give credit to @klmz for his PR which inspired these changes!

**Comment by eluce2** [comment]
Also, should fix #11983 and #11706

**Comment by klmz** [comment]
This is seems like a more robust solution than what I did. 👍  Happy to have helped!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
