### PR TITLE
New Extension: Kinopio

### PR DESCRIPTION
**Pull request by pketh**
## Description

Hi, this adds a new extension for https://kinopio.club, that lets users add text cards to their kinopio inbox

## Screencast

kinopio-inbox-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @pketh 👋 

I tested it and can't get it to save

image

Just getting
```
13:12:48.636 🚒 HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/extensions/kinopio-inbox/add-card.js:5890:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1672920767960,
    socket: 1672920767961,
    lookup: 1672920767997,
    connect: 1672920768110,
    secureConnect: 1672920768234,
    upload: 1672920768235,
    response: 1672920768611,
    end: 1672920768620,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 36,
      tcp: 113,
      tls: 124,
      request: 1,
      firstByte: 376,
      download: 9,
      total: 660
    }
  }
}
```

**Comment by pketh** [comment]
Hi @pernielsentikaer to help me debug, can you let me know whether you signed up for a kinopio.club account and entered the apikey when you first ran the extension? Or if you put in a random string as your apikey, I could add better error messaging around that case too. 

thx

**Comment by pketh** [comment]
hey @pernielsentikaer , 

I fixed this with server side changes, as well as adding better error logging/messaging. Can you update and try this again? Thanks!

**Comment by pketh** [comment]
Bumping this up because I haven’t heard anything in 2 weeks,

**Comment by pernielsentikaer** [comment]
Checking, was waiting for a `Request for Review` 😊

**Comment by pernielsentikaer** [comment]
Hi @pketh 👋 

Still not working out for me; getting this error:

```
07:30:26.570 🎑 { name: 'HELLO FROM RAYCAST' }
07:30:27.055 🐸 response https://api.kinopio.club/card/to-inbox 404 {
  status: 404,
  message: 'inbox space not found for user',
  user: {
  ```
 
image

**Comment by pketh** [comment]
That’s working as designed , your kinopio account needs an inbox space which you can create from Kinopio via new -> 
B81B00DD-7D73-437D-B0A0-3EA242470015


by default new accounts once they sign up do have inbox spaces (which I just confirmed myself by making a new test account ). That said the inbox is optional for kinopio users and can be removed like any other space , hence the error msg

**Comment by pketh** [comment]
In case that’s not the source of the error you’re seeing can you let me know if the user object in the error output you pasted above has keys or if it’s an empty object?

**Comment by pernielsentikaer** [comment]
I just send you an e-mail with the complete log 😊

**Comment by pketh** [comment]
Hey @pernielsentikaer , I just updated your account to add an Inbox space (I just renamed your `hello kinopio` default space). Can you try it again?

On my end, I'll investigate why the inbox space wasn't created by default for you

**Comment by pketh** [comment]
> Checking, was waiting for a `Request for Review` 😊

I can't figure out how to add this. Is it a label? It doesn't look like I'm able to add labels to issues in this repo

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pketh** [comment]
Thanks!

**Pull request merged**
