### PR TITLE
Add nowplaying-cli extension

### PR DESCRIPTION
**Pull request by yusufakdenizxd**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

Could you look into the [CI errors](https://github.com/raycast/extensions/actions/runs/9142819466/job/25138795931?pr=12448) here before I can have a look?

**Comment by yusufakdenizxd** [comment]
I am just trying to update pr with npx raycast api.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Could you use `runAppleScript` from `@raycast/utils` instead 🙂

**Comment by yusufakdenizxd** [comment]
> Could you use `runAppleScript` from `@raycast/utils` instead 🙂

Its crashed with `runAppleScript` from `@raycast/utils`

```Error: Command failed with exit code 1: osascript
0:72: execution error: sh: line 2: nowplaying-cli: command not found (127)

runAppleScript3:run-applescript.js:38:21

35:         timedOut,
36:         command: "osascript",
37:         options,
38:         parentError: new Error(),
39:     });
40: }
41: exports.runAppleScript = runAppleScript;

async Object.go_next_default:go-next.js:7640:5```

**Comment by yusufakdenizxd** [comment]
It worked thanks

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
