### PR TITLE
Migrate to Raycast useFetch

### PR DESCRIPTION
**Pull request by geekdada**
## Description

Try to solve #5002 by migrating the HTTP request client to Raycast `useFetch`.

## Screencast

N/A

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* When entering the commands, I see an infinite loader; could you look into this?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by geekdada** [comment]
Thanks a lot! I forgot it😀

**Comment by geekdada** [comment]
@pernielsentikaer I think `@raycast/utils` has a bug here.

```
// Initial State
{
  isLoading: true, // or `false` if `options.execute` is `false`
  data: undefined,
  error: undefined
}
```

`options.execute` is `false` at start, however `isLoading` is `true` from `useFetch`, thus you see the loading animation.

**Comment by pernielsentikaer** [comment]
If you update to `@raycast/utils` version 1.5.2 it should be resolved 😊

**Comment by geekdada** [comment]
@pernielsentikaer Yes indeed. It's ready for review.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
