### PR TITLE
Update recent-downloads extension

### PR DESCRIPTION
**Pull request by alcibiadesc**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

How is this compared with [Download Manager](https://www.raycast.com/thomas/downloads-manager) - sounds like they have the same purpose?

**Comment by alcibiadesc** [comment]
> Hi 👋
> 
> How is this compared with [Download Manager](https://www.raycast.com/thomas/downloads-manager) - sounds like they have the same purpose?

Hello @pernielsentikaer 

It is quite similar, the main difference is Grid with image preview instead of list  and some more direct shortcuts.

I am also looking at adding a document preview as with File Search and that the file search is location-agnostic, i.e. it shows all downloaded files.


image

**Comment by pernielsentikaer** [comment]
Hi @alcibiadesc 👋 

It sounds like some nice updates for sure but it doesn't make sense to have two identical extensions with the same purpose, I would suggest that we enhance the current one build by @thomaspaulmann instead

**Comment by alcibiadesc** [comment]
> Hi @alcibiadesc 👋
> 
> It sounds like some nice updates for sure but it doesn't make sense to have two identical ext

You are right, :) Thank you very much for your time and giving me an insight that I had not previously taken into account :)

**Comment by pernielsentikaer** [comment]
You could still enhance the current one with many of the features you had here if you'd like to, that would be helpful for a lot of users

**Comment by thomaspaulmann** [comment]
This is indeed nice. We could allow an option to show the detail view for the Downloads Manager. Feel free to contribute to it.

**Pull request closed without merging**
