### PR TITLE
feat: add lark applink

### PR DESCRIPTION
**Pull request by chyroc**
## Description

use lark/feishu app link open api to open lark/feishu client.

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by chyroc** [comment]
@mattisssa can you review this, thanks very much.

**Comment by mattisssa** [comment]
> @mattisssa can you review this, thanks very much.

Hey @chyroc! It's not necessary to mention us in the PRs; we have a queue for the reviews, every PR will be reviewed by the review team 😉

**Comment by chyroc** [comment]
I'm sorry, it's been a long time since I brought this up, not immediately after I initiated the PR. I feel that the review time of the pr I submitted recently is relatively long. Thanks for your work.

**Review by pernielsentikaer — APPROVED** [review]
Hi @chyroc 👋 

Thanks for your contribution, lets's get it merged! 🔥

**Pull request merged**
