### PR TITLE
Update pdfsearch extension

### PR DESCRIPTION
**Pull request by kevin-pek**
## Description

- Revamp old search logic to use the SearchKit API.
- Modified Swift scripts to use Raycast Swift extensions.
- Add support for searching plaintext and markdown files.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by xilopaint** [comment]
Hey Kevin, could you make the View Outline command work with the PDF file selected in Finder?

**Comment by kevin-pek** [comment]
> Hey Kevin, could you make the View Outline command work with the PDF file selected in Finder?

That seems like a great idea. I have edited the command to use the [getSelectedFinderItems](https://developers.raycast.com/api-reference/environment#getselectedfinderitems) method instead of the previously used applescript command. Another cool feature is that it now allows outlines of multiple files to be viewed at once.

**Comment by xilopaint** [comment]
Wow! Those are insane improvements! Thanks a lot @kevin-pek!

Btw, there's a CI error. Can you check it?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
