### PR TITLE
Added Kaalam Extension

### PR DESCRIPTION
**Pull request by heertheeswaran**
## Description
Added a new extension called Kaalam, which means Time. 

This shows the current time in available date formats.

## Type of change

- New extension

## Screencast

The extension has only one command which is Show Time

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @heertheeswaran 👋 

I have a question about this extension, what is the use case? I'm really trying to understand what it could be, but I'm not able to – can you maybe enlighten me?

**Comment by heertheeswaran** [comment]
Hi @pernielsentikaer ,

This extension can be used by designers and developers to copy the current time in any of the available formats. Which will give them an easy advantage.

**Comment by pernielsentikaer** [comment]
Hi @heertheeswaran 👋 

Thanks for the clarification 👍 , the code looks fine 🔥, I do have suggestions for you 🚚 :

- Add `PasteAction` so it's possible to paste directly
- When it's added, then you could add a preference to set the “default” action, let me know if you need example 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by heertheeswaran** [comment]
Hi @pernielsentikaer , 

Can you share me a example.

**Comment by pernielsentikaer** [comment]
Sure! Take a look at #593

fZtaX0OvkJb8Unga

**Comment by pernielsentikaer** [comment]
Hi @heertheeswaran 🔥 

Do you need any help?

**Comment by heertheeswaran** [comment]
@pernielsentikaer Can you publish this? I will add those as an update to the extension later

**Review by pernielsentikaer — APPROVED** [review]
Hi @heertheeswaran 👋 

Yes we can, the two suggestions would be a good idea in the next version 😄 

I'm going to accept it and then will my colleague do a final review before it's finally merged.

**Pull request merged**
