### PR TITLE
[UPDATE Obsidian Extension] Several Quality of Life improvements

### LINKED ISSUE #4216: [Obsidian] Automatically exclude files
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

The "exclude following folders" option should automatically exclude any files or folders included in the Obsidian "Excluded files" option and should also exclude the `.trash` folder. In addition any user-defined excludes would be combined with these default excludes rather than overwriting them. 

### Who will benefit from this feature?

_No response_

### Anything else?

_No response_

### LINKED ISSUE #4217: [Obsidian] Support starred files
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

There should be a command for viewing files and searches starred in Obsidian. Alternatively instead of creating a separate command the existing "Pinned Notes" command could be renamed and repurposed to work with starred files instead. This may reduce user confusion as the "Pinned Notes" feature could be confused with Obsidian's own "pinned tabs" functionality. In fact I originally assumed the "Pinned Notes" command was for viewing pinned tabs and thought it was broken until I realized how it was supposed to work.

### Who will benefit from this feature?

_No response_

### Anything else?

_No response_

### LINKED ISSUE #4399: [Obsidian] Create a blank note
### Extension

https://www.raycast.com/marcjulian/obsidian

### Description

It would be great to open a blank note with hotkey and be able to bypass the new note form. 

### Who will benefit from this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by marcjulianschwarz**
## Description

- Add `Silent Mode` preference for the `Append to Daily Note Command` which prevents the command from opening the daily note
- Unified several preferences to make them more consistent
- Automatically exclude files and folders from search that are excluded in Obsidian
- Add `Blank Note` preference to `Create Note` command which lets you create a blank note immediately
- Add `Create Note` action to `Search Note` command which lets you create a new note from the search results if it doesn't exist yet
- Remove `Pinned Notes` command
- Add `Starred Notes` command which lists all starred notes of a vault
- Update Raycast API to v1.47.0
- Rewrote parts of the codebase to improve maintainability

Closes https://github.com/marcjulianschwarz/obsidian-raycast/issues/43
Closes https://github.com/marcjulianschwarz/obsidian-raycast/issues/27
Closes #4216 
Closes #4399 
Closes https://github.com/marcjulianschwarz/obsidian-raycast/issues/38
Closes #4217 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

- I can't see any differences when toggling `Silent Mode`. Both modes open Obsidian. Did I do something wrong? Tested with `Version 1.1.9 (Installer 1.1.9)`

- Can't see the `Create Note` action in `Search Note`


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by marcjulianschwarz** [comment]
Hi @pernielsentikaer,

`Silent mode` is a bit weird as it is based on the Advanced URI plugin for Obsidian. This means it still needs to open Obsidian to be executed. However if you have Obsidian opened and you are working in a note and want to quickly add something to the daily note, then it wont open the daily note (which means the currently opened note will remain open and you can continue to work on it).
Sadly I think that currently there is no way to do it differently. It would close https://github.com/marcjulianschwarz/obsidian-raycast/issues/43. You can see a short demo in the linked issue comments.

The `Create Note` action is only visible when the search term is not found in your notes (see image below). 

Bildschirm­foto 2023-02-11 um 21 20 51

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Tested with success, let's go! 🧑‍🚒

**Comment by marcjulianschwarz** [comment]
Great, thank you for the quick response 🙏

**Pull request merged**
