### PR TITLE
[New Extension] Shortcut Manager

### PR DESCRIPTION
**Pull request by devloos**
## Description

- This extension is designed to handle all of your application's keyboard shortcuts. It will manage them for you so you don't have to.
- If there are keyboard shortcuts you need that aren't already supported, you can create them yourself using this extension.
- The extension provides an intuitive way to manage your hotkeys, so you can easily customize them to suit your needs.
- The extension can also help you identify if there are any duplicate hotkeys being used across your application, so you can avoid conflicts and ensure everything works as intended.

## Screencast

shortcut-manager-2
shortcut-manager-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @devloos 👋 

This sounds a bit like [Keyboard Shortcut Sequences](https://www.raycast.com/HelloImSteven/keyboard-shortcut-sequences), could you check that out? It's made by @SKaplanOfficial 😊

**Comment by devloos** [comment]
Hey @pernielsentikaer 🙌

It is similar, when I started working on this it wasn't on the market. I do feel like some of the features I provide in this extension could be added to @SKaplanOfficial 's extension.

For example, organizing shortcuts by application, displaying shortcut sequences in the list view, and instead of running a sequence of keystrokes could we run them at the same time?

I feel this could be useful since not all shortcuts are sequences.

Do you suggest I speak with @SKaplanOfficial?

**Comment by SKaplanOfficial** [comment]
@devloos I agree, the features can definitetly be merged together. You can make a PR with the changes, if you want, otherwise I'll work on it when I rotate back to this project in a few days. 🙂

**Comment by devloos** [comment]
Hey @SKaplanOfficial

Thanks for the speedy reply, yea I should be free ill get those done and pushed up.

**Pull request closed without merging**
