### PR TITLE
[New extension] Clipboard Bookmark

### PR DESCRIPTION
**Pull request by codingki**
## Description

Bookmark your clipboard

## Screencast

https://user-images.githubusercontent.com/39829726/218281802-934aab06-9cb5-41a6-be3d-bed52176d379.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @codingki 👋 

How is this different from Clipboard History with pinned functionality?

**Comment by codingki** [comment]
Hey @pernielsentikaer 👋

Yes this is similar with Clipboard history, The difference is this extension have numbering order on the `subtitle` that can be searched. From what I've been use in my workflow when I code is the numbering of the bookmark helps me paste faster in case I have multiple clipboard that I need in one context. This extension currently only support text.
ex: i have `foo (1)`, `bar (2)`, `baz (3)` in my clipboard bookmark 
What I need to do after open this extension is type the number to get what I want.

This is useful in my case, maybe others having the same needs as I was. So I decide to PR this😅

**Comment by pernielsentikaer** [comment]
Hi 👋 

You can also see numbers if you hold ⌘ for a half second in the native, doesn't that help you?

Raycast-y8ON9EGX@2x

**Comment by codingki** [comment]
TIL, thanks @pernielsentikaer 😅 closing this PR

**Pull request closed without merging**
