### PR TITLE
Update Productboard extension - Add `Notes` command + `chore`

### PR DESCRIPTION
**Pull request by xmok**
## Description

I wanted to add some more features as I've started using Productboard recently. However, this extension is old and so I wanted to work on modernizing some of the code before more features are added so to that effect:

1. added CHANGELOG
2. added updated metadata images in the metadata folder
3. added `useForm` in the `index` command
4. created a `useProductboard` hook that fetches and returns paginated data that we can use for future "GET"
5. I did NOT remove the existing use of `got` as we might need to keep it depending on how useFetch, POST and PUT requests are handled by Productboard API.
6. added ONE command `Notes` that will show Notes
7. updated the dependencies especially raycast api

I think we can move "Add Note" and turn it into a subcommand via Push within Notes but I think this needs to be discussed first.

## Screencast

https://github.com/raycast/extensions/assets/30526133/1c94f375-bd70-43f2-8409-594e5b33a215

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@honzatmn can you check this update?

**Comment by pernielsentikaer** [comment]
@honzatmn pinging you one last time

**Comment by honzatmn** [comment]
What a nice improvement with Notes listing! Thanks for your contribution @xmok! 👏

> I think we can move "Add Note" and turn it into a subcommand via Push within Notes but I think this needs to be discussed first.

This also sound like a good thing, it might speed up adding a note significantly.

**Comment by pernielsentikaer** [comment]
Awesome, thanks for the feedback 🔥

**Comment by xmok** [comment]
Hey so this update moved `Add Note` to be a subcommand via Push in `Notes` command.
I also updated ray deps.
Finally, got a new type of Error so I updated the ErrorResponse type to handle it.
No real functionality changes!

**Comment by mil3na** [comment]
Hi! Is this ready for review again?

**Comment by xmok** [comment]
Hi yes this is ready to go ✅.

**Comment by mil3na** [comment]
LGTM!

**Pull request merged**
