### PR TITLE
Add chatgpt-chat extention

### PR DESCRIPTION
**Pull request by erodactyl**
## Description

ChatGPT chat extension lets users have a persistent chat with context using OpenAI-s ChatGPT API.
The difference from the other extensions integrating ChatGPT is that none of the others allow having a persistent chat with multiple messages and context. 

## Screencast
https://user-images.githubusercontent.com/22914589/222972106-1779de92-d21d-4ced-82e5-8d91e12adb1e.mov

openai-chatgpt-1
openai-chatgpt-2
openai-chatgpt-3
openai-chatgpt-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by casiar** [comment]
Would love to see this in Raycast! Good work on the extension.

**Comment by DorukAkinci** [comment]
This looks like the best implementation so far. Do you think could we also implement the system/user/assistant roles respectively in the messages that we sent? Maybe I missed that part in the code, however it seems the official documentation suggests it. [ChatGPT API Introduction](https://platform.openai.com/docs/guides/chat/introduction). Also, I hope we can also see a way to change our max token limits, so we can set it to 4096 if we want. In any case, well done 🙌

```
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
```

**Comment by casiar** [comment]
> This looks like the best implementation so far. Do you think could we also implement the system/user/assistant roles respectively in the messages that we sent? Maybe I missed that part in the code, however it seems the official documentation suggests it. [ChatGPT API Introduction](https://platform.openai.com/docs/guides/chat/introduction). Also, I hope we can also see a way to change our max token limits, so we can set it to 4096 if we want. In any case, well done 🙌
> 
> ```
>   messages=[
>         {"role": "system", "content": "You are a helpful assistant."},
>         {"role": "user", "content": "Who won the world series in 2020?"},
>         {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
>         {"role": "user", "content": "Where was it played?"}
>     ]
> ```

What would also be nice is to implement some presets like https://github.com/raycast/extensions/tree/50d68ab4b7ea92db0b60acfc765e6e0d8ab764d0/extensions/chatgpt3-prompt/

Then everything would be in one panel

**Comment by erodactyl** [comment]
> 

Yes that's a great idea. I'll work on letting you send `system` role messages as that could be helpful in setting the context of the conversation. 

I am also working on saving a history of previous conversations (up to some number of days not to create too much unnecessary data). Essentially, you'd be able to go back to any conversation withing the last 10 days, read it, and pick it up right where you left off. Of course the 10 days part would be configurable.

I am hoping this base version will be merged before then as I'm probably going to finish that on the next weekend.

**Comment by casiar** [comment]
Still waiting for this to be implemented

**Comment by erodactyl** [comment]
Same here, and I have a similar suspicion. However, I still have hope that the open-source nature of the extensions will prevail and they'll let us create what we want to create.

Meanwhile I have run "npm run dev" and am daily driving the non-store version. Works great.

**Comment by casiar** [comment]
> Same here, and I have a similar suspicion. However, I still have hope that the open-source nature of the extensions will prevail and they'll let us create what we want to create.
> 
> Meanwhile I have run "npm run dev" and am daily driving the non-store version. Works great.

So do I :)

**Comment by erodactyl** [comment]
Hi @pernielsentikaer, I saw you mentioned this extension in another PR. I am wondering if you had a chance to test it. Please let me know if you have any feedback, I tried to follow the rules as closely as I could.

**Comment by pernielsentikaer** [comment]
Hi 👋 

What do you think about that we're adding #5253 as the main and take enhancements from this one into the other one (With you as contributor)

**Comment by erodactyl** [comment]
Hey @pernielsentikaer. 

The other version does seem to be more feature-rich for this use-case. While I noticed a few nitpicks which I don't like while browsing the other one, I have added a comment to the other PR to see what the creator thinks about them.

**Comment by erodactyl** [comment]
The comments were addressed, we can close this version 🥲

**Comment by pernielsentikaer** [comment]
We're still adding you as contributor on the other one, I think this is the right call

**Comment by erodactyl** [comment]
@pernielsentikaer let me know if I need to do anything to be added as a contributor.

**Pull request closed without merging**
