### PR TITLE
Add sesh extension

### PR DESCRIPTION
**Pull request by joshmedeski**
## Description

Add a new extension for [sesh](https://github.com/joshmedeski/sesh), a smart terminal session manager.

## Screencast

SCR-20240110-qzuk

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
How to install sesh? Seems like it's not ready to be used at all?

**Comment by joshmedeski** [comment]
I'm currently working on getting the CLI released to homebrew, but didn't know how long it would take for you guys to approve it here.

Want me to put this in draft mode? I can add instructions to the README as well.

**Comment by pernielsentikaer** [comment]
I think it might be best to draft until ready 🙂

**Comment by joshmedeski** [comment]
Okay @pernielsentikaer, it's ready!

You can run `brew install joshmedeski/sesh/sesh` to install the CLI, then you can connect your terminal to tmux and it will do it's thing!

It's mean to be a companion to the core workflow that happens in the terminal. I've done some thorough testing and it's doing a great job.

p.s. this is a v2.0 rewrite for my [t - tmux plugin](https://github.com/joshmedeski/t-smart-tmux-session-manager). So it's not a brand new project like it might appear :)

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for the update 🔥 

I now installed the brew command and opening the command gives me this (and I'm not sure what to do) I see a point where I need to do something with a terminal emulator, but not sure what I need from here?

sesh 2024-01-16 at 09 02 51

I'm not sure if it's because I don't normal use tmux(if I need that) but I think others might be confused too 🙂

**Comment by enrique-villarrealp** [comment]
> Thanks for the update 🔥
> 
> I now installed the brew command and opening the command gives me this (and I'm not sure what to do) I see a point where I need to do something with a terminal emulator, but not sure what I need from here?
> 
> sesh 2024-01-16 at 09 02 51
> 
> I'm not sure if it's because I don't normal use tmux(if I need that) but I think others might be confused too 🙂

Yep - This is reading tmux sessions (and I think @joshmedeski has plans to add more multiplexers too) - if you don't use tmux it makes sense `sesh list` would error here!

**Comment by joshmedeski** [comment]
@pernielsentikaer so this tool gets built up with a tool called zoxide (which is automatically installed when you brew install sesh).

[My video explaination](https://www.youtube.com/watch?v=l_TTxc0AcCw) goes into the technologies involved, and I plan on making a brand new video when the Raycast extension goes live!

But let me know if there needs to be more explanation or error handling on Raycast's side in order for you guys to approve the extension.

For now, try running `cd` commands in your terminal after [zoxide](https://github.com/ajeetdsouza/zoxide) is configured in your terminal and/or open a tmux session or two and you won't get the error anymore.

**Comment by pernielsentikaer** [comment]
I tried `tmux new -s documents` and it looks like it started, Raycast does however say the same, not sure how to get pass this place 🫠

Raycast17012024-kJGldrsP png@2x

**Comment by joshmedeski** [comment]
Can you type `which tmux` and share the result? I'm not sure how Raycast expects to find binaries but I have this set on the environment:

```ts
export const env = Object.assign({}, process.env, { PATH: "/usr/local/bin:/usr/bin:/opt/homebrew/bin" });
```

So if tmux isn't in one of those places I don't think Raycast can read it.

You can also run `zoxide add ~/Downloads` manually to create a zoxide entry.

**Comment by pernielsentikaer** [comment]
I get this path back `/opt/homebrew/bin/tmux`

After manually adding `zoxide add ~/Downloads` I'm able to see it, when I run the connect action, nothing happens (my terminal pops to the front but nothing else)

**Comment by joshmedeski** [comment]
Because this is a companion to the `sesh` workflow, tmux has to already be running for this extension to be useful. Those that use sesh have a workflow in the terminal already.

I will be making improvements to the Raycast extension but I was hoping to get this merged soon to get it in the hands of my users! Let me know what we need to do to get this shipped, thanks!

**Comment by pernielsentikaer** [comment]
Let's get it out for your users and we can see how it goes 🙂

**Comment by enrique-villarrealp** [comment]
Thank you @pernielsentikaer ! So far it's been working great for me! Granted, I was already using Josh's sesh tool (and its previous iterations) for a good while now!

**Comment by pernielsentikaer** [comment]
That's awesome to hear, thanks for letting me know @enrique-villarrealp

**Comment by joshmedeski** [comment]
Thank you @pernielsentikaer!

I'll be getting feedback from my community and continue to improve on the extension 😉

**Pull request merged**
