### PR TITLE
Adds extension: Rabbit r1 | Rabbit Hole Journal Extension

### PR DESCRIPTION
**Pull request by RobErskine**
## Description
This is a new extension for the [Rabbit r1](https://www.rabbit.tech/rabbit-os) to access my journal entries through Raycast; making your data more accessible outside of the Rabbit ecosystem.

This extension allows you to query all of the entries in your journal from the Rabbit r1. This includes notes, recordings, computer vision, image generation, web searches, ai chats, and photos from the camera.

## Screencast
https://github.com/raycast/extensions/assets/1895120/a6c6d9ea-ba87-40a8-a03c-9bb23a840a3c

## Screenshots
rabbit-hole-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

Sorry for the delay answering your PR. My concern here is about how useful would it be if the key needs to be refreshed every 24h. And, as I don't have access to Rabbit, I would need a screencast of empty states and error states, just to check if everything is okay.

Also, we would need, on your README, a disclaimer waiving Raycast from any involvement on the extension building and telling the user that they are responsible for the use of this extension.

**Comment by RobErskine** [comment]
Hi @mil3na! No worries in the delay in the PR.

I hear your concerns over how useful this would be as a long-term plugin. My hopes with this extension is to use this as a case study for why they should open up API keys as part of their ecosystem so users can get more use out of their Rabbit's. Hopefully the 24 hour token expiration won't be an issue for long.

I'm unsure how to get your a screencast of empty states and error states. Do you mean like if the user sets it up for the first time, with no data?

Here is what it looks like when you sign up for the first time:
Adds extension Rabbit r1  Rabbit Hole Journal Extension-2024-07-17-21 23 11@2x

Here is what it looks like if you have no entries in your journal:
Journal-2024-07-17-21 30 50@2x

There should be checks and conditions in ts that prevent other empty states from showing up.

I have added the following into the README:

>## Disclaimer
>
>This extension is a third-party contribution and is not officially affiliated with or endorsed by Raycast. The developers of this extension are solely responsible for its functionality and maintenance. Users of this extension do so at their own risk, and Raycast bears no responsibility for its use or any consequences thereof. By installing and using this extension, you acknowledge that you are responsible for your use of this extension and any actions taken through it.

**Review by mil3na — APPROVED** [review]
Sounds good to me. I hope this works as a good use case for an open API!

**Comment by RobErskine** [comment]
Missed this getting merged in! Very cool, thank you @mil3na. I've published a [topic on the official Rabbit r1 forums](https://community.rabbit.tech/t/raycast-rabbit-hole-extension/13011). Fingers crossed!

**Pull request merged**
