### PR TITLE
Add mail-manager extension

### PR DESCRIPTION
**Pull request by nickkadutskyi**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by nick-kadutskyi** [comment]
Please check the original pr for more details: https://github.com/raycast/extensions/pull/9803

**Comment by nick-kadutskyi** [comment]
I checked that extension and it looks like it's Apple Mail specific.

My overall plan was to have an extension to manage any mail clients (e.g. Outlook, Spark), and specifically move messages to and navigate to mailboxes. 

I used Postbox before and it had that feature inbuilt and I thought it would be great to have that in any other clients since even Apple Mail doesn't have those shortcuts or popup to quickly select a mailbox to move emails to.
Also, Fastmail has this feature in their web client.

But, let me know if you still think that it should be merged into https://www.raycast.com/yug2005/mail or you want to make that extension more general instead of apple mail specific.

**Comment by pernielsentikaer** [comment]
I'm a bit afraid that it would be hard to maintain so many email clients, don't you? Since none of them works the same.

What do you think @yug2005?

**Comment by pernielsentikaer** [comment]
@yug2005 are you around?

**Comment by pernielsentikaer** [comment]
It seems like @yug2005 is not around at the moment 🫠

Was your plan to add more mail clients and how would it work, a preference or multiple commnads @nick-kadutskyi

**Pull request closed without merging**
