### PR TITLE
Update linear extension

### PR DESCRIPTION
**Pull request by gtsiolis**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by gtsiolis** [comment]
This is still showing _Unknown notification_ in the Menu Bar, I'm probably missing something. :/

**Comment by thomaslombart** [comment]
Could you add a `CHANGELOG.md` entry and post a recording to better see what's happening? 🙂

**Comment by gtsiolis** [comment]
@thomaslombart Here's a screenshot to visualize the problem. The PR changes do not resolve the issue—hints are welcome, otherwise let's close this PR.

Screenshot 2024-04-02 at 13 34 28

**Comment by gtsiolis** [comment]
@thomaslombart No, it's not. It also shows up there as _Unknown notification_.

**Comment by thomaslombart** [comment]
Ah! I thought it wasn't the case. Are you sure it's the right notification type? Linear doesn't document that anywhere so you'll probably have to add a `console.log` somewhere to guess the type.

**Pull request closed without merging**
