### PR TITLE
Add shadcn-vue extension

### PR DESCRIPTION
**Pull request by selemondev**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution 🔥

How is this compared with [this](https://www.raycast.com/luisFilipePT/shadcn-ui) by @luisFilipePT and would it be possible to enhance that one, or?

**Comment by selemondev** [comment]
Hey there @pernielsentikaer, @luisFilipePT 's work on Shadcn UI RayCast Extension is amazing. 

1. How does is to compare to his? Shadcn UI has various ports such as Shadcn UI ( React Version ), Shadcn Vue ( Vue Version ), Shadcn Svelte ( Svelte Version ) and Shadcn Solid ( Solid Version ). @luisFilipePT 's Shadcn UI RayCast extension focuses only on the React port and not any another port. My RayCast extension ( Shadcn-Vue ) focuses only on the Vue port.

2. Would it be possible to enhance that one? There is a possibility. As mentioned earlier, @luisFilipePT's RayCast extension only focuses on React in regards to the components, commands and logo. Having separate extensions would be better so as to follow the pattern implemented by the creators of the Shadcn ports.

**Comment by pernielsentikaer** [comment]
Thank you for taking the time to explain. It sounds like the best option would be to have them as separate entities.

**Comment by pernielsentikaer** [comment]
Could you fix the linting issues [described here](https://github.com/raycast/extensions/actions/runs/9052091693/job/24869359085?pr=12301)

**Comment by selemondev** [comment]
✅ Done.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
One of the commands crashes right after opening it, can you look into that?

shadcn-vue 2024-05-21 at 08 53 01

**Comment by selemondev** [comment]
> One of the commands crashes right after opening it, can you look into that?
> 
> shadcn-vue 2024-05-21 at 08 53 01

Hey @pernielsentikaer , could you please review the changes and let me know if everything is OK 😁?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
