### PR TITLE
Update chatgpt-quick-actions extension

### PR DESCRIPTION
**Pull request by alanzchen**
## Description

Use ChatGPT anywhere on your Mac! Summarize, polish, or rewrite your selected text.

## Screencast

https://user-images.githubusercontent.com/2144783/232259860-dcf47f25-cd1b-4612-a430-fedf58fabe28.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by alanzchen** [comment]
Hey @pernielsentikaer, AFAIK, the other extension focus on conversation with ChatGPT, whereas this one focuses exclusively on let ChatGPT work on selected text (e.g., rewriting, expanding, polishing, translating). This allows frictionless integration of ChatGPT in virtually any workflow.

**Comment by pernielsentikaer** [comment]
Seems like what https://www.raycast.com/douo/openai-translator/commands does. Could you check that out?

**Comment by alanzchen** [comment]
@pernielsentikaer thanks for the pointer. Yeah, the functionality is similar. The name of the extension was confusing so I didn't look into it. If I were someone who is looking for what my extension is doing, I will have a really difficult time finding this `openai-translator`. Nevertheless, there are several differences -- for example, mine allows users to customize the prompt, thus making it general purpose instead of being constrained by the prompt specified in the extension.

If I were you, I would rather add this extension to the store for the sake of better discoverability. I would also understand if you decide not to merge -- since the functionality of these two extensions are indeed similar in nature.

On a related note, I was wondering if it would be possible to install an extension in Raycast by entering a GitHub Repository URL. This would allow small groups of friends to share their extensions without having to publish them on the store.

**Comment by pernielsentikaer** [comment]
One thing we could do is renaming the current extension, what do you think about that @douo

**Comment by douo** [comment]
> One thing we could do is renaming the current extension, what do you think about that @douo

Hi @pernielsentikaer, I agree with @alanzchen. This extension is basically a Raycast version of  yetone's [OpenAI Translator](https://github.com/yetone/openai-translator/). It mainly focuses on translation and aims to improve the usability of obtaining text to be translated. Therefore, renaming it  is not very appropriate.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* When you try to get selected it crashes, you might want to have try{}catch{} around it to ensure no crashes 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by alanzchen** [comment]
@pernielsentikaer can you take a look at the new commits? Thanks!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by alanzchen** [comment]
@pernielsentikaer Hi, I am trying to push an update from my main repository. But after running `npx @raycast/api@latest publish`, I am getting this error `extension path in fork: found more than one extension with name chatgpt-quick-actions`.

Any thoughts?

**Pull request merged**
