### PR TITLE
Add Transfer extension

### PR DESCRIPTION
**Pull request by kgrhartlage**
## Description

Uploads a single selected file to [transfer.sh](https://transfer.sh/) and copies its URL to the clipboard.

## Screencast

https://github.com/raycast/extensions/assets/42832087/a567e794-4ae4-43ca-ab1a-b2e265bf0e10

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by kgrhartlage** [comment]
transfer.sh is currently down, the issue is apparently [being adressed](https://github.com/dutchcoders/transfer.sh/issues/556#issuecomment-1553330061)

**Comment by kgrhartlage** [comment]
> We are still working with the provider to restore the service. Hopefully within the next 2-3 days, the service is restored. Thanks everyone for the patience.

https://github.com/dutchcoders/transfer.sh/issues/556#issuecomment-1575092958

**Comment by kgrhartlage** [comment]
> > We are still working with the provider to restore the service. Hopefully within the next 2-3 days, the service is restored. Thanks everyone for the patience.
> 
> [dutchcoders/transfer.sh#556 (comment)](https://github.com/dutchcoders/transfer.sh/issues/556#issuecomment-1575092958)

@pernielsentikaer the service is back online. I updated the screencast and the PR is now ready for review 🙏

**Comment by sxn** [comment]
hi @kgrhartlage – thanks for the PR! I tested the extension and works quite well. I do have a couple of suggestions however:
1. The command is named `Upload File`, so without looking at what it does, I expected it to open a file picker. Instead, I got an error message as there's no file selected 🤔 What about renaming the command to something like `Upload Selected File`? Or alternatively, update the extension to open a file picker when there's no selected file?
2. Once the file is uploaded, I went to the specified URL, saw my file, and then wanted to delete it. The website requires me to provide a deletion token though, but…I don't think I have one? Is it returned by the API? It'd be great to save it / present it to the user in that case…

**Pull request closed without merging**
