### PR TITLE
feat(Timers): add Timers extension

### PR DESCRIPTION
**Pull request by ThatNerdSquared**
## Description
This PR adds a Timers extension to Raycast, allowing the user to start, stop, and save custom countdown timers. I previously created #1114 to add this extension, but it was closed because of my excessive delay in merging requested changes. In this PR, I've made all requested changes and am ready for another review.

## Screencast
See metadata for screenshots; it's hard to take an effective screencast that doesn't end up being excessively long due to the nature of the extension so I'd recommend a test drive by setting a 1-5 minute timer.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Hi @ThatNerdSquared 
Great extension!!! I tried it out, but I seem to have run into a little problem.
When I Stop the countdown timer in `Manage Timers`, the process created by this countdown timer doesn't disappear.
Is it a problem with the way I'm using it?
SCR-20220511-jpn

**Comment by ThatNerdSquared** [comment]
Hi @koinzhang, does the timer still go off after you've deleted it? **If not**, then that is expected behaviour. The process should disappear after the set amount of time, but it should not ring if you've deleted the timer, because it checks if the corresponding data file for the timer still exists before firing off any sound effects. In future updates, I may attempt to save the PID somewhere and kill off the process on timer delete.

**Comment by koinzhang** [comment]
Hi @ThatNerdSquared.
Stop the timer and it doesn't ring. Then this extension is no problem for me.

**Comment by ThatNerdSquared** [comment]
Bumping this just in case @pernielsentikaer missed it :)

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ThatNerdSquared 👋 

I have now tested this extension and have some feedback for you 😄

- The loader newer stops if the list is empty; could you look into this?

- It lacks validation in the "Start Custom Timer" since it's possible to start a timer without anything added in the form.

- Could the list of timers be sorted by the next one that will ring?

- If adding a timer with the "Start Custom Timer" command and set "Save as preset" to true, then it's not added as preset in the "Manage Timers" command.

- Instead of using fs to read/write files, you could use [storage](https://developers.raycast.com/api-reference/storage) instead

- When renaming a timer, it starts with the current name as a placeholder. If you submit, then the name is removed - is this expected?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by ThatNerdSquared** [comment]
Thanks for the review @pernielsentikaer!

- Fixed bug with perpetual loader
- Added validation to "Start Custom Timer" command
- Sorted running timers by next to ring, sorted saved timer presets from shortest to longest
- Fixed bug where preset was not saved from "Start Custom Timer" command
- Fixed bug where submitting an empty Rename Timer form cleared the name of the timer — it now requires a new name to be inputted

Additional notes:
- I'm using `fs` because the external bash command that controls each timer needs to be able to easily view the file to check if the timer has been deleted or not.

Looking forward to any more feedback you may have 🥂

**Comment by pernielsentikaer** [comment]
Hi @ThatNerdSquared 👋 

Everything works as expected, awesome 🔥 

I only have one last question about this section title when no timers are added, could you maybe find a better wording?

CleanShot 2022-05-18 at 13 40 14@2x

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by ThatNerdSquared** [comment]
@pernielsentikaer I removed the Currently Running header altogether, I think it's pretty easy to see what's running without it anyway.

**Comment by pernielsentikaer** [comment]
I liked the section, what about changing the text instead of removing it to something like this `<List.Section title={timers != null ? "Currently Running" : "No Timers Running"}>`

**Pull request merged**
