### PR TITLE
More actions for Bear extension

### PR DESCRIPTION
**Pull request by lucaschultz**
## Description

Added some new actions to the extension:

- Open in standalone Bear window
- Move note to archive
- Move note to trash
- Embedded  images and files in preview will be converted to `file://path/to/file.txt` links to the locally stored files and open in Finder when clicked
- Show notes linked from the selected note and backlinks to the selected note
- Copy note text as markdown
  - Embedded files will be converted to `file://path/to/file.txt` links
  - Embedded images will be converted to markdown images embeds `` 
- Copy note text as HTML
  - Converted with [commonmark.js](https://github.com/commonmark/commonmark.js/), which is not fully compatible with bear markdown compatibility mode/polar. But bear will switch to commonmark when they ship their [new editor](https://bear.app/panda/) in Bear
  - Embedded files will be converted to `file://path/to/file.txt` links 
  - Embedded images will be converted to `img` tags

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @hmarr 

## Screencast

<https://user-images.githubusercontent.com/45899273/139209196-691b392c-c945-4356-b059-c7bc3773f87b.mp4>

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Ho @lucaschultz 👋 

Awesome improvement of the Bear extension, thanks a lot for the contribution! 💯 🥇 

The only thing I found is when opening the "Search Notes" I get this error in the console (but it seems like everything is working). Can you investigate this error?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by lucaschultz** [comment]
@pernielsentikaer Unfortunately I'm a bit of noob (as in CS student who has never written a single line of Typescript or React) so I haven't found an elegant way to solve the error. It has something to with the way I was wrapping the `List.Item` in my own `NoteItem` function and handling the key/id props. However, I hacked my way around it and it works now 🥳 

The extension also feels more responsive for some reason. Might be an API bug, I'll set up an minimal example project and investigate further.

I also merged my changes with the changes of @diokhan to handle encrypted notes more elegantly.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @lucaschultz 

Thanks for your contribution 💪  We're getting closer and closer!

- Something is not looking right in the title.

Ug10R40LfhY9dS5l

- I tried the "Open note" dropdown when adding a new note, almost every possibility opened Bear - both from active, hidden and closed.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by lucaschultz** [comment]
Okay the title was my bad, I tried prepending an SF-Symbol (lock) for encrypted notes in front of the title. Forgot that this only works when one has SF-Symbols installed 🤦‍♂️

Might craft a (simple) custom Bear icon to indicate a note is encrypted (and thus has reduced actions) tomorrow.

Regarding the opening of Bear: Using their x-callback URL scheme will (as far as I can tell) always bring Bear to the front. The dropdown only controls wether a _new main window_ is opened when none is available (e.g. after pressing <kbd>cmd</kbd> + <kbd>w</kbd> when having the main window open), a _new standalone note window_ is created or neither of these. But whatever Bear windows you do have open, they will come to the front.

I fully understand why this is confusing though. However I would like to keep the dropdown with the options. Should I try changing the wording?

**Comment by lucaschultz** [comment]
@pernielsentikaer Both points should be fixed now.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Awesome @lucaschultz 💪 

A few comments from the latest run:

- Both "Don't open note" and "In Main Window" does what I expect, "In New Window" makes Bear active (and adds the most in the left panel) - from here nothing is happening, it stays on the current note.

- I think we somehow need to address the secure notes, now that they don't stand out and the "Show Note Preview" is removed, then it feels like an error instead, I think having the "Show Note Preview" would make sense again.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by lucaschultz** [comment]
@pernielsentikaer good catch, i think these last commits addressed both points:

- _In New Window_ now opens the note, well, in a new window. Still confused why it didn't work before. But now it does!
- I actually liked the idea of having some indicator for a note being encrypted. So I added a lock 🔒 emoji to the title of encrypted notes. Alternatively I could add it to the accessory title, what do you think? Also, since _Show Note Links_ actually works for encrypted notes (the links are taken from database meta information not the text of the note) I reenabled it along withe the preview. Before I disabled it for privacy considerations (think: leaking information about the contents of the note when you can see which notes linked to it and which it links to). But 50% of that information is acvailable anyways (links to the encrypted note) so 🤷‍♂️

**Comment by PitNikola** [comment]
Nice additions! Using this extension myself 👍 
Looks good, gonna merge.

**Pull request merged**
