### PR TITLE
Update 1password extension

### PR DESCRIPTION
**Pull request by luizvergennes**
## Description

🎉 My Vaults Command
Lists user vaults, and lists items from the vault.
🩺 Solves #4744 

🎉 Account switcher
Users are now able to switch accounts.
🩺 Solves #12102 #4744 

🎉 Better Error handling
Now errors are treated better to understand user issues.
There is a smart component that indicates the user what the problem was and tips to fix it.
🩺 Solves #12106 #11826 

🐛 Fixed the duplicated auth prompt
Fixed the issue when trying to access passwords to require two authentications after the 10 minute cooldown.
🩺 Solves #12095 

🔧 Modified the auto renew command to be disabled by default
It now requires the user to enable it in the extension config.
🩺 Solves #12095 

🔧 Improved the auto renew command to renewal only after a manual sign-in.
🩺 Solves #12095 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the update @Luk4h 🔥 

If I install it for the first time, then I see this error and have to use my biometric twice? Do you have an idea about that?

Raycast06052024-LdwjZxHS png@2x

**Comment by Luk4h** [comment]
It has to do with the 1Password CLI auth method. Since the views always execute ```op account``` and ```op item list```. It is trying to execute both commands at the same time, that's why the first time asks twice for the auth.
Currently this one is the last issue open related to 1password. I am currently working for a fix. The issue is somewhat resolved when you have auto-renew authorization on.

**Comment by Luk4h** [comment]
> I am currently working for a fix. 

Found that using a context for the auth may solve the issue. Please stand by while I fix this.

**Comment by Luk4h** [comment]
@pernielsentikaer trying to find anything about not closing the raycast window if the 1password prompt opens, is it possible?

**Comment by Luk4h** [comment]
@pernielsentikaer I made a way so that just before requesting 1Password authentication to pop to the root of Raycast. After authentication use, you will need to search for the command again. This is not ideal, but sufficient for now.

I believe there is a bug with Raycast or React when interacting with the node exec function that causes the 1Password prompt to break it and never return the function as finished. This makes it hard to work for a more seamless workflow for getting the passwords.

**Comment by pernielsentikaer** [comment]
An extension unloads when it is no longer loaded, for example, when popping to the root. Even if you do not pop to the root and Raycast loses focus, there is a high likelihood it will be unloaded as well.

Maybe it's possible to run something like `await open("raycast://");`

**Comment by Luk4h** [comment]
https://github.com/raycast/extensions/assets/78048969/27da0198-fc84-4202-a5f1-a1d20ba5322b

> Maybe it's possible to run something like await open("raycast://");

Even with that, it does not matter. As you can see in the video. If the prompt is successful, it does not continue the code execution. 

Sadly when I was using the node runtime directly to test it worked just fine...  That's why my guess is something related to React or the Raycast itself not retrieving the return of this command. 

Maybe is it because the stdout of this command is null?

**Comment by Luk4h** [comment]
We are ready to go @pernielsentikaer! 🎉

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by kjeldahl** [comment]
@Luk4h I get this error: 
image
I did not get a chance to select any of the two accounts I am using. Only the 1Password version. I tried to reinstall the extension, but it still fails with the error above. On all commands for 1Password.

**Comment by Luk4h** [comment]
> @Luk4h I get this error: image I did not get a chance to select any of the two accounts I am using. Only the 1Password version. I tried to reinstall the extension, but it still fails with the error above. On all commands for 1Password.

Got the fix already, I will make the PR.

**Comment by Luk4h** [comment]
Refer to #12491

**Pull request merged**
