### PR TITLE
Add android-emulator extension

### PR DESCRIPTION
**Pull request by 3llomi**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by 3llomi** [comment]
Hi @pernielsentikaer ,

The 'Android' extension only allows you to show Android Projects and Android Emulators with the ability to boot an emulator.

The Extension that I've created is more specific to Android Emulator, where you can Shutdown, Boot, or Restart an Emulator.
in addition to simulating certain functionality like Fold/Unfold, setting a specific network speed to test your app on a specific bandwidth, simulating a Fingerprint touch, SMS messages, and more.

Not sure if we can merge this into 'Android' Extension or keep this as standalone, as it has a different purpose.

Let me know what you think.

**Comment by pernielsentikaer** [comment]
I think it would make sense to merge with the current extension in order to avoid confusing the users who will be using it. What do you think, @mibrahimdev?

**Comment by mibrahimdev** [comment]
@pernielsentikaer Actually, adding this feature to the 'Android' extensions was one of my to-dos. I agree with you that it would provide a more complete solution for the user if we merged it. However, the final decision is for @3llomi to make.

**Comment by 3llomi** [comment]
Alright, I guess I will just open a new PR and merge these into Android extension.

**Pull request closed without merging**
