### PR TITLE
Add Cookie String Parser extension

### PR DESCRIPTION
**Pull request by NicolasMontone**
## Description

This extension takes a cookie string and parse to understand improve cookie debugging, etc.

I was having a hard time debugging cookies for a project I'm working and the only tool I found is this one https://cookie-parser.michaelbonner.dev/. For me make sense to have this extension, and actually I'm using it hehe

## Screencast
Raycast 2024-02-25 at 16 53 52
cookie-string-parser-2
cookie-string-parser-5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by NicolasMontone** [comment]
The screenshot are outdated! I will update them today :)

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I just tested this with the string `Foo=test;Bar=hello;` and it seems to add an extra value to the list

cookie-string-parser 2024-02-25 at 08 02 31

- Would it make sense to just use an [extension argument](https://developers.raycast.com/information/lifecycle/arguments#example) instead and just show the `<List>` directly

Raycast 2024-02-25 at 08 05 00
 


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by NicolasMontone** [comment]
Thanks a lot for the feedback! I already apply the suggestions and do minor changes :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
