### PR TITLE
Add raypass extension

### PR DESCRIPTION
**Pull request by paul-bokelman**
## Description

RayPass is a local password manager. Passwords are stored locally on the users hard disk in "documents". A user can create one or many documents, optionally encrypt them, then make as many password records as they please inside them. Users can create, delete, search, and switch between documents. A user can also create, edit, delete, or copy each individual field of a password record. 

## Screencast

https://user-images.githubusercontent.com/72945168/193752304-b2292fd1-c663-4ae6-baf5-3ef3f8c45998.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by paul-bokelman** [comment]
Same as #3115 (used ray publish).

**Comment by pernielsentikaer** [comment]
You might need to restructure your code to get rid of it

```
function Command() {
 const token. = something();
  if (!something) { 
    return <Form>{…}</Form>
  } else { 
    return <List>{…}</List> 
  }
}
```

Our API engineers in #extensions in [Slack](https://www.raycast.com/community) can help with questions 🙂

**Comment by paul-bokelman** [comment]
Thanks, I'll be sure to get in touch with them and resolve the issue.

**Comment by paul-bokelman** [comment]
Hey @pernielsentikaer, I've implemented HMAC into my encryption functions and resolved the issue with the infinite loop. RayPass is ready for a review!

**Comment by pernielsentikaer** [comment]
I'll look into this in a moment, sorry for the waiting time

**Comment by pernielsentikaer** [comment]
When it shows the list of passwords, should we redact the password or remove it from the entries?

**Comment by paul-bokelman** [comment]
> ## Description
> RayPass is a local password manager. Passwords are stored locally on the users hard disk in "documents". A user can create one or many documents, optionally encrypt them, then make as many password records as they please inside them. Users can create, delete, search, and switch between documents. A user can also create, edit, delete, or copy each individual field of a password record.
> 
> ## Screencast
>  Screen.Recording.2022-10-03.at.11.43.38.PM.mov 
> ## Checklist
> * [x]  I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
> * [x]  I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
> * [x]  I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
> * [x]  I checked that files in the `assets` folder are used by the extension itself
> * [x]  I checked that assets used by the `README` are placed outside of the `metadata` folder

I'm not sure what you mean by this. Could you clarify?

**Pull request closed without merging**
