### PR TITLE
add Terminal

### PR DESCRIPTION
**Pull request by ron-myers**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* It looks like it's only working the first time (when the terminal is not open)

https://user-images.githubusercontent.com/38033107/201851170-8682412f-3bdc-4fca-a9f6-6f17381a8dfd.mp4

Do you have an idea what might cause this (and if it's possible to fix)




I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by ron-myers** [comment]
Thank you, @pernielsentikaer - I have replicated the issue, will get a fix in place and request a review.  

Appreciate you catching the issue in review.  Thanks again.  ✋

**Comment by ron-myers** [comment]
The issue was a timing issue with

```
  await runAppleScript(script);
  await popToRoot();
  await closeMainWindow();
```

switching it to 

```
  await popToRoot();
  await closeMainWindow();
  await runAppleScript(script);
```

solved the issue.  :) Thank you again @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
