### PR TITLE
Add: Dungeons & Dragons Extension

### PR DESCRIPTION
**Pull request by RobErskine**
### Dungeons & Dragons

Look up monsters, spells, rules, and mechanics, all while rolling advanced dice, and even generate random encounters for your party in a pinch. This extension utilizes [the DND5api API](https://dnd5api.co/) to pull and present all data related to D&D 5th edition. An API token is not required.

#### Commands
-  *Game Mechanics* - Lookup Conditions, Damage Types, and Magic Schools info.
-  *Monster Compendium* - Access details on 300+ monsters, including alignments and stats.
-  *Random Encounter* - Generate party encounters based on levels and location. _Requires Raycast AI_.
-  *Roll Dice* - Flip a coin or roll various dice types and custom rolls.
-  *Rules Lookup* - Access over 30 D&D rules categories.
-  *Spell Lookup* - View details on 300+ D&D spells by level and school of magic.

## Screencast

https://github.com/raycast/extensions/assets/1895120/884fc6b9-06f8-41e5-a0f0-367e49dc78ec

## Generic Screenshot

Raycast 2024-05-29 at 21 08 07

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
sdungeons-and-dragons-2024-05-29-18 57 55@2x
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Shows undefined in the action panel title here

dungeons-dragons 2024-06-11 at 11 45 02

- There is no data on the first load here and there is no indicator

dungeons-dragons 2024-06-11 at 11 46 10

- Second time you enters the command it works, if I use `Show Details` it briefly flashes `Error from API` before showing the right data

- This command seems to die, I entered both level 1, 17 and 20, all of them failed (also once said that it should be within 0-12?)

Raycast 2024-06-11 at 11 48 35

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Thanks for all the update, almost everything works as expected now 🔥 

I entered level 5 as the only thing in the command and it crashes, do you know why?

dungeons-dragons 2024-06-12 at 10 41 36

**Comment by RobErskine** [comment]
@pernielsentikaer Thanks for taking a look, I appreciate your feedback. I think I have everything addressed in this latest 2 commit!

- fixing roll dice action title to fix undefined label
Add Dungeons   Dragons Extension-2024-06-11-21 59 17@2x


- fixing race condition in loading the monster compendium and details (should show loading indication and fixed the no results on first run)
Add Dungeons   Dragons Extension-2024-06-11-21 59 48@2x

- updating monster condition types
- fixing random encounter AI response streaming. I was attempting to loop over Monsters that weren't returned from the API yet. I added in a check to return an empty string on the initial call, which fixes the undefined on reading the `map`!
  - adding tone to random encounter to improve the AI responses
  
Random encounter for level 1: 
Add Dungeons   Dragons Extension-2024-06-12-22 05 18@2x
Add Dungeons   Dragons Extension-2024-06-12-22 05 29@2x


Random encounter for level 5:
Add Dungeons   Dragons Extension-2024-06-12-22 07 33@2x

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
