### PR TITLE
GitLab: Optimize

### LINKED ISSUE #842: GitLab extension to fetch the repos proactively
# Extension – [GitLab](https://github.com/raycast/extensions/tree/main/extensions/gitlab)
Author: @tonka3000 

Currently, when I list my projects using the GitLab extension, the extension makes a request when I attempt to do that, which means I have to wait until the API responds, and it is usually slow. In my day-to-day usage, I really want to be able to use this extension to quickly jump to my repo, but sometimes it is even slower than actually going to GitLab UI and searching there.

**Describe the feature and the current behavior/state.**
I think the GitLab extension should fetch the repositories in the background, just like the GitHub extension does. I can search my GitHub repos very quickly, but not for GitLab.

**Who will benefit with this feature?**
All the users of GitLab extension, in my opinion.

### LINKED ISSUE #1070: GitLab My Open Issues gets error on details and images don't load
# Extension – [gitlab](https://github.com/raycast/extensions/tree/main/extensions/gitlab)

Author: @tonka3000 

## Description

I do a My Open Issues and any of them I click on gets a Could not get details error for all of my issues. For any issues that have images, it shows Loading... but they never load. Both issues are shown in the screenshot below:

Screen Shot 2022-03-10 at 10 10 21 AM

## Steps To Reproduce

1. My Open Issues
2. Show Details

## The current behavior
Gets error fetching details and images don't load

## The expected behavior
Able to get details and loads images

### Raycast version

Version: 1.30.1

### PR DESCRIPTION
**Pull request by tonka3000**
## Description

* Minimum Raycast version is 1.31

* Increase project cache invalid time to 7 days

  This speedup access to projects for `My Projects` and `My Starred Projects` over a longer period of time. Before it was 1 days, which was too short for some users.

  Closes #842

* Most commands now use the SWR cache to speedup operations

* Add Primary Action option to settings

  User can decide if they want to stay in Raycast when they press enter (`Open Project`) or open the Browser (`Open Browser`). `Open in Raycast` is the default.
  
  CleanShot 2022-03-28 at 21 16 07@2x

  Related #946

* Add pop to root setting

  Users can decide if they want to pop to root if they open an external application like the browser.

  CleanShot 2022-02-20 at 09 22 31

  Request by @jaklan

  Related #244

* Add more details for issues and MRs

  CleanShot 2022-03-30 at 22 54 22@2x

  CleanShot 2022-03-30 at 22 54 53@2x

* Add `My Recent Commits` root command

  Fast navigation through the latest commits from the logged in user.

  CleanShot 2022-03-30 at 22 56 16@2x

* Merge Request and Issue Details view can be directly open from the `My Recent Activities` command when there is a corresponding event

  CleanShot 2022-03-30 at 22 57 30@2x

* Convert relative markdown links to absolute ones

  Markdown relative links which starts `/` (i.e. `a text`) will now be converted to absolute ones when being in an issue or merge request.

  Closes #1070

* Filter `My Merge Request`, `My Todos`, `My Recent Commits`, `My Open Issues`, `My Reviews` per project

  Use CMD + P to filter per project.

  CleanShot 2022-03-14 at 17 37 06@2x

* Most commands do now show the CI Jobs status if available

  CleanShot 2022-03-30 at 22 58 48@2x

  CleanShot 2022-03-30 at 22 59 31@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by Loskir** [comment]
How about adding actions to the "My Recent Activities" command?

**Comment by tonka3000** [comment]
> How about adding actions to the "My Recent Activities" command?

No worry, this will come. First lets get #944 merged by the raycast team. After that I will merge it into my branch here. Then I can add this (and some other stuff).

**Comment by tonka3000** [comment]
Hey @mattisssa ,

I have the problem that the navigation stack breaks. I use an component which fetch data before showing the component with the content. In the following video this is a merge request, but this happens also with the issue impl.. It seems that that pressing ESC skip on navigation frame to much.

[This](https://github.com/tonka3000/extensions/blob/2d84f99ef4d403b872c02cea3e8348d19bb634de/extensions/gitlab/src/components/mr.tsx#L45) is the fetch component and [here](https://github.com/tonka3000/extensions/blob/2d84f99ef4d403b872c02cea3e8348d19bb634de/extensions/gitlab/src/components/event.tsx#L238) is the PushAction where I call the component. 

https://user-images.githubusercontent.com/3163807/154848347-064f2c1a-76ec-4e4b-a314-929baf90a8d8.mp4

Not quite sure if this is a bug or not? Maybe you can give me some hint? Maybe this can be done better instead of using components (my goal is to have a loading screen unitl I get the data and switch to the data based view afterwards).

**Comment by mattisssa** [comment]
Oookay, that looks weird. Does it happen without having `Open in Raycast` option? 
I'll take a look at the code tomorrow.

**Comment by tonka3000** [comment]
> I'll take a look at the code tomorrow.

@mattisssa Do you had a chance to check why this strange bug happens?

**Comment by mattisssa** [comment]
So first, to show loading just use the `<Detail isLoading />` instead of using List component.
Second, it seems like there is something off with our view replacement, in your case with replacing Detail and List once the fetch is done.

**Comment by Loskir** [comment]
How do you feel about refactoring the event parser from the "switch — assign" style to "if — return"?
It will look much cleaner, I hope.

**Comment by tonka3000** [comment]
> So first, to show loading just use the `<Detail isLoading />` instead of using List component. Second, it seems like there is something off with our view replacement, in your case with replacing Detail and List once the fetch is done.

Fixed the problem.

**Comment by tonka3000** [comment]
> How do you feel about refactoring the event parser from the "switch — assign" style to "if — return"? It will look much cleaner, I hope.

Not for now. Later. Wanna finish the more important stuff first.

**Comment by Loskir** [comment]
изображение
The icon for issues (exclamation.png) appears pixelated on my screen, can you confirm this?

I ran into this problem when adding pipeline icons. using 64x64 icons instead of bigger ones seem to help

**Comment by tonka3000** [comment]
@pernielsentikaer @mattisssa

**Comment by Loskir** [comment]
изображение

My Recent Commits → Open Pipeline doesn't work for me. Are you aware of this or do you need some help with debugging?

**Comment by tonka3000** [comment]
> My Recent Commits → Open Pipeline doesn't work for me. Are you aware of this or do you need some help with debugging?

Interesting. On my side it works fine. Do you have no stages in your pipeline?

**Comment by Loskir** [comment]
изображение
изображение
I have investigated this issue and found out that the reason is that my gitlab instance doesn't return the `iid` of the pipeline in api's response for the commit. [Should it](https://docs.gitlab.com/ee/api/commits.html#get-a-single-commit)?

**Comment by Loskir** [comment]
GitLab Enterprise Edition [14.3.0-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v14.3.0-ee)

**Comment by tonka3000** [comment]
Any change you can upgrade to at least 14.6? The problem is that the IID seems not be available until 14.6, which is required for the graphql call. Otherwise I need to use the REST API for pipelines which slow down the whole download.

**Comment by Loskir** [comment]
It's not a big problem for me personally, but rather a decision on which version we should support.
Unfortunately, there is not a big chance that we're getting our gitlab updated soon. And I'm afraid this might be common across different companies.
I've played around with that problem last week and came to the conclusion that the flow must either use REST completely or GraphQL. GraphQL doesn't seem like a good option because it doesn't have a convenient interface for getting a commit by its SHA. 
Are REST calls for pipelines _that_ slow? I've made a working prototype using only REST API calls and it seems fine. Might commit my changes to a different branch so you can see

**Comment by Loskir** [comment]
Here: https://github.com/Loskir/extensions/commit/9123c5f4801eb926e3c1d5a8a5cb892f3e81c88d

**Comment by tonka3000** [comment]
I've done the same impl., I fallback when there is no iid. The problem I need to solve is that the REST API does not give the stages in order.

**Comment by Loskir** [comment]
Now it works, cool. But there is a little empty state flickering

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @tonka3000 👋 

What a chunk, it's incredible to see extensions grow like this one 🔥 

I don't use GitLab myself, so it's nice that @Loskir is helping test it. Thanks!

- Tested a few commands (Epics, My Open Issues, My Projects), and all of them give an error toast when credentials are wrong, but the loader never stops.

Could you address this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by tonka3000** [comment]
@pernielsentikaer Should be fix now.

**Comment by Loskir** [comment]
Maybe render a [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) on error instead of (or along with?) showing a toast?

**Comment by pernielsentikaer** [comment]
What do you say about that @tonka3000? Is it something you want to look into before merging or in another PR?

**Comment by Loskir** [comment]
изображение

Also there is an issue with icons. Hi-res icons (512x512) appear pixelated for some reason, whereas the same icons scaled down to 64x64 look fine.
Can you confirm this?

**Comment by tonka3000** [comment]
> изображение
> 
> Also there is an issue with icons. Hi-res icons (512x512) appear pixelated for some reason, whereas the same icons scaled down to 64x64 look fine. Can you confirm this?

On my display it looks normal.

**Comment by pernielsentikaer** [comment]
I think we should get it merged and live and tackle images and EmptyView later if there is a problem 🔥

**Comment by tonka3000** [comment]
@Loskir You can add your changes (isLoading) and emptyView thing as a deticated PR now 😃

**Pull request merged**
