### PR TITLE
Ray.so: Add Command for Server-Side generated images

### PR DESCRIPTION
**Pull request by RSO**
## Description

Add a command to the ray.so extension that copies the ray.so-generated image based on the `getSelectedText()` API.

I also made an executive decision regarding the branding of ray.so, and decided that the brand style uses a lowercased `r` 😄 .

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @gt-codes 

## Screencast

Main flow:
https://user-images.githubusercontent.com/139663/150560036-8ba0a8a8-0fc1-455f-a05d-001b41491306.mp4

Preferences:
CleanShot 2022-01-21 at 17 07 22@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by RSO** [comment]
I'm going to close this PR for now, as it seems that we have a bug in the server-side code that is causing all subsequent requests to crash, I need to investigate this first.

**Comment by RSO** [comment]
I've improved the stability of the server-side function, and haven't seen a 500 error since, so I believe that this PR is now ready to be merged!

**Comment by fe9lix** [comment]
Waiting for feedback from @gt-codes here?

**Comment by pernielsentikaer** [comment]
Yes, but I think we should proceed

**Comment by RSO** [comment]
Yeah, as we're coming up on almost two weeks since the original PR I'd vote for merging as well. If @gt-codes comes back later with feedback I can address it then!

**Comment by gt-codes** [comment]
I love this addition ✨ @RSO Let's do it!

**Pull request merged**
