### PR TITLE
Add zipper-run extension

### PR DESCRIPTION
**Pull request by arielconti10**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Missing a loading indicator



- The push is not an ideal solution since if you hit escape once you’ll end in a blank window.

You can maybe do some conditional returns instead like:

```
function Command() {
 const token. = something();
  if (!something) { 
    return <Form>{…}</Form>
  } else { 
    return <List>{…}</List> 
  }
}
```

- Would it make sense to make a list view with either scripts returned  by an API OR let the user add them themselves, I can see that it might be a hard job remembering the name and file  


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by arielconti10** [comment]
Hi @pernielsentikaer 
Thanks for your review. I took in consideration your comments and made a bunch of changes in the code. 
It's ready for review again

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I think we're almost there. If you try to fetch something that's not working, it never stops loading. Could you look into that?

**Comment by arielconti10** [comment]
@pernielsentikaer I've added the error handling. You can re-review

**Comment by arielconti10** [comment]
hi @pernielsentikaer 
let me know if this is good or if you need something else

**Comment by pernielsentikaer** [comment]
There is a small [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) when I search for `readme` - do you have an idea on how to eliminate that?

**Comment by arielconti10** [comment]
@pernielsentikaer can you provide me with a more clear example of when this is happening so I can check?

**Comment by pernielsentikaer** [comment]
It might be hard to see but if you look right before data is returned it shows "No Results" - I'm not sure how easy it is to do something - I can also try if you don't have an idea 🙂

https://github.com/raycast/extensions/assets/38033107/5c872d12-1e0d-43a3-b12f-7b1e6ae34b0a

**Comment by arielconti10** [comment]
@pernielsentikaer is it possible to be some issue with the List component? 
I've tried with a static list like this and I see the same behavior 
image

**Comment by pernielsentikaer** [comment]
It seems like we have an error as you said, thanks for pointing it out - we'll address that in the next release and will not be a blocker now 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
No, everything should be fine now 🔥 

Thanks for your cooperation. It was a pleasure working with you 🙂

**Pull request merged**
