### PR TITLE
Update send-to-flomo extension

### PR DESCRIPTION
**Pull request by maidangzhu**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you mind adding a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry?

**Comment by pernielsentikaer** [comment]
@ahonn do you mind checking this?

**Comment by ahonn** [comment]
> @ahonn do you mind checking this?

LGTM, but it looks like the change log needs to be updated.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by maidangzhu** [comment]
Thanks guys! It's the first time I make an pr for raycast plugin, not quite farmilar with rules about updating changelogs. Let's continue make great plugins~~~

**Pull request merged**
