### PR TITLE
Update cleanshotx extension

### PR DESCRIPTION
**Pull request by Aayush9029**
## Description

I’ve decided to add instructions to the metadata. This will enforce the requirements of the app and provide a warning about the API toggle.

- Added documentation
- Added metadata images
- Updated dependencies

## Screencast
EnableAPI

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaslombart — COMMENTED** [review]
The supporting images in `README.md` should be put in a top-level folder called `media` as `metadata` is for screenshots in the Raycast store. Otherwise, looks good!

**Comment by Aayush9029** [comment]
I included the screenshot in the metadata deliberately to inform users about the app extension. The API needs to be enabled.


Granted, it does conflict with the consistency of metadata images in the store. **I would love to know your thoughts on this.**


_I'll move them to the media folder as requested and update the readme.md._

**Comment by thomaslombart** [comment]
You can reference these images in the `README.md` file, that's usually where people go when they want troubleshoot some issues or getting setup.

**Comment by Aayush9029** [comment]
I've moved the image from `metadata` to `media` as requested. 
I've modified the `README.md` as well.

**Review by thomaslombart — APPROVED** [review]

**Pull request merged**
