### PR TITLE
New Extension: OBS Studio Control

### PR DESCRIPTION
**Pull request by Yukaii**
## Description

Control OBS Studio via the WebSocket API. I implemented two commands in this release. I would probably include [more commands](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md) if I need them 😛  .

## Screencast

Metadata-15

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @Yukaii 👋 

Thanks for your contribution 💯 

It would be nice if we could handle this error gracefully, maybe a installation check out [n8n extension ](https://github.com/raycast/extensions/pull/2050) to see how it can be done 😄

**Review by pernielsentikaer — COMMENTED** [review]
Hi @Yukaii 👋 

Thanks for your contribution 💪 

I tested the extension out and I'm not able to get it to work, I checked [obs-websocket-js](https://www.npmjs.com/package/obs-websocket-js) - is `ws://` supposed to be there in the URL?

I tried to do everything as the README said but I'm not able to test it, does it work fine on your end? We can also test it together in [Slack](https://www.raycast.com/community).

**Comment by Yukaii** [comment]
@pernielsentikaer Yes, `ws://` should be included in the URL.

It works fine on my machine, I've sent you a message.

**Review by pernielsentikaer — APPROVED** [review]
Looks good to me; thanks for your cooperation 🔥

**Pull request merged**
