### PR TITLE
fix(Apple Notes) Error handling and prompts

### PR DESCRIPTION
**Pull request by StevenRCE0**
## Description

Solved #4801
Added error handling when Raycast doesn't have Accessibility permission. If that happens, the command will show a HUD about the problem and return normally. 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi  @StevenRCE0 👋 

Thanks for your contribution 🔥 

I tested this without any permissions and:

* New Note works without permissions all the time for me
* Search notes don't work and fail

Raycast-GpAwrevH@2x

**Comment by StevenRCE0** [comment]
> Hi @StevenRCE0 👋
> 
> Thanks for your contribution 🔥
> 
> I tested this without any permissions and:
> 
> * New Note works without permissions all the time for me
> * Search notes don't work and fail
> 
> Raycast-GpAwrevH@2x

It made sense. Actually I see [errors.tsx](https://github.com/raycast/extensions/blob/main/extensions/apple-notes/src/errors.tsx) is dealing with permission prompts already. I'll take advantage of it. 

As the issue(#101) mentioned in the file, it feels a bit weird to make this rough workaround.

**Comment by StevenRCE0** [comment]
I wasn't able to reproduce the script error in Search command, however, I've tried to catch that.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @StevenRCE0 👋 

I'm still getting this error

Raycast-u9hJeF5S@2x

```
12:08:04.263 
Error: Command failed with exit code 1: osascript -e set output to ""
tell application "Notes"
  repeat with theAccount in every account
    set theAccountName to the name of theAccount
    set output to output & "account: " & theAccountName & "
"
    repeat with theFolder in every folder in theAccount
      set theFolderName to the name of theFolder
      set output to output & "folder: " & theFolderName & "
"
      repeat with theNote in every note in theFolder
        set theNoteID to the id of theNote
        set theNoteName to the name of theNote
        set output to output & "id: " & theNoteID & "
"
        set output to output & "title: " & theNoteName & "
"
      end repeat
    end repeat
  end repeat
end tell
return output
40:667: execution error: Not authorised to send Apple events to Notes. (-1743)

tell application "Notes"
  repeat with theAccount in every account
    set theAccountName to the name of theAccount
    set output to output & "account: " & theAccountName & "
```

Do you have a clue about what's going on 😊

**Comment by StevenRCE0** [comment]
Yes, that's Automation permission.  yet another type of permission error to identify and to catch 😫

**Comment by StevenRCE0** [comment]
Last commit should do, a new permission error screen is added.

**Review by pernielsentikaer — APPROVED** [review]
Works as expected now 🔥

**Pull request merged**
