### PR TITLE
Add dev-project-launcher extension

### PR DESCRIPTION
**Pull request by niconunez96**
## Description

Adding new extension `Dev Porject Launcher` which basically helps you to easily open your projects with JetBrains IDE's or VSCode. This extension also let's you customize the IDE shortcuts and provides and easy navigation through directories

Note: This is the first version of this extension, the idea is to have a start point so I can add more features if the extension add some value to the community.

The command receives the base path (the path which will be used to display projects) by argument
Raycast 2023-04-25 at 18 40 19

### Navigate through your projects 🧭
dev-project-launcher 2023-04-25 at 18 32 17

### Customize your IDE shortcuts ⌨️
dev-project-launcher 2023-04-25 at 18 32 48

### Open your project/file with any IDE ⚡
dev-project-launcher 2023-04-25 at 18 33 33

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋 

I'm not really sure I get the purpose of this extension, what's the use case?

**Comment by niconunez96** [comment]
Hi! thanks for reviewing this really appreciate it 🙌. The main use case is to "Open any development project with vscode editor or jetbrain IDE"(for now that is the scope, in the future I want to let the users add their own favourite text editor/IDE to be able to open projects with it)
This is mainly to avoid the following repetitive workflow:
1. Open your text editor/IDE and then select the project that I want to work on
2. Open the terminal, cd into the project and then open it with the text editor/IDE

**Comment by pernielsentikaer** [comment]
Sounds a bit like [Projects extension](https://www.raycast.com/ajaypremshankar/projects), could you check that out - it might do most of what you want to

**Comment by pernielsentikaer** [comment]
I have been trying to figure out how to use this tool and how it can benefit users. Can you show me a screencast of how you'd use it?

**Pull request closed without merging**
