### PR TITLE
New extension: Slugify

### PR DESCRIPTION
**Pull request by unreadablename**
## Description

A quick way to slugify text

## Screencast

slugify-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by gebeto** [comment]
What about this one? Is it similar to your extension?

https://www.raycast.com/es183923/change-case

**Comment by unreadablename** [comment]
@gebeto not really
This extension is not about changing case. It's about generating url safe tokens which requires extra transformations

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* The extensions suffer from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

* You need a proper logo for your extension; you can use [Raycast icon generator](https://icon.ray.so/)

* Could you update metadata images after new icon

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by unreadablename** [comment]
Hi @pernielsentikaer,
Huge thanks for your review

I've fixed empty flickering issue and added logo (the most difficult issue to fix)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
