### PR TITLE
Add Just Focus extension

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

Control Just Focus via Raycast. Just Focus is a simple, clean Pomodoro timer to help you stay healthy and regain your focus, keep you even more productive!

**Tips:**

- Before using this extension, you need to install the Just Focus application ([Download Just Focus](https://getjustfocus.com))
- Please make sure Just Focus is located in the Applications folder (/Applications/JustFocus.app)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by danielsequeira** [comment]
Hi @koinzhang,

I noticed that there are already a Pomodoro timer extension in our store: https://www.raycast.com/jameslyons/session

Have you tried it? What is the difference between this one and the existing one?

**Comment by koinzhang** [comment]
Hi @danielsequeira.
> What is the difference between this one and the existing one?

Both of these extensions control other app and both require other apps to be installed.
The one you mentioned is controlling [Session](https://www.stayinsession.com), while I made this extension to control [Just Focus](https://getjustfocus.com).
> I noticed that there are already a Pomodoro timer extension in our store: [raycast.com/jameslyons/session](https://www.raycast.com/jameslyons/session)
> Have you tried it?

Maybe Session is a good app, but I don't want to use it just yet.

**Comment by danielsequeira** [comment]
> Hi @danielsequeira.
> 
> > What is the difference between this one and the existing one?
> 
> Both of these extensions control other app and both require other apps to be installed. The one you mentioned is controlling [Session](https://www.stayinsession.com), while I made this extension to control [Just Focus](https://getjustfocus.com).
> 
> > I noticed that there are already a Pomodoro timer extension in our store: [raycast.com/jameslyons/session](https://www.raycast.com/jameslyons/session)
> > Have you tried it?
> 
> Maybe Session is a good app, but I don't want to use it just yet.

Thanks for the explanation @koinzhang, I didn't realise it was another app, I will have a look.

**Comment by danielsequeira** [comment]
Btw could you add some screenshots of the extension?

**Review by danielsequeira — APPROVED** [review]

**Comment by koinzhang** [comment]
Hi @danielsequeira. I have added a screenshot. Please review.

**Review by danielsequeira — APPROVED** [review]

**Pull request merged**
