### PR TITLE
added kill-listening-process command to port-manager

### PR DESCRIPTION
**Pull request by mvolkmann**
## Description

The "Kill Listening Port" command simplifies the steps
to quickly kill the process that is listening on a given port.

This functionality is especially useful for web developers
that are testing an app by running a local HTTP server.
You may have many terminal windows open.
You attempt to start a server in one of them,
only to get an error because the port is in use.
Rather that toggling through all your terminal windows to
find the one that is using the port and killing it by pressing ctrl-c,
you can use this command and simply enter the port number.

All output from the "Kill Listening" command is in the form of a toast.
If an non-integer port value is entered,
the toast message will say "The port must be an integer."
If no process is listening on the port,
the toast message will say "No process is listening on port ...".
Otherwise the toast message will say "Process {pid} was killed."

## Screencast

screenshot-1
screenshot-2
screenshot-3
screenshot-4
screenshot-5

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mvolkmann** [comment]
@lucaschultz @Sheraff Have you had a chance to look at this pull request? I'm happy to change anything about it that you don't like.

**Comment by lucaschultz** [comment]
> > Have you had a chance to look at this pull request? I'm happy to change anything about it that you don't like.
> 
> 
> 
> @mvolkmann I'm not sure I understand what this enables that isn't already possible with the existing command. It can already kill processes, and we can already search by port, can't we?

Yes but I this makes killing the process which is using a specific Port much faster. 

@mvolkmann Would you mind doing 2 changes:

1. Use a more concise description of the command in the README. I don't think wen need to justify to users why this command exists by describing in which scenario it might be useful.
2. I appreciate you spending the time to create a new icon! However, would you mind using the extension icon for the command? This is common behavior for most extensions (at least as far as I know) which makes it easier which extension the command belongs to.

**Comment by lucaschultz** [comment]
@pernielsentikaer If you have no further change requests this is ready to be merged 🚀

**Comment by mvolkmann** [comment]
I just connected by GitHub account to my Raycast account.

**Pull request merged**
