### PR TITLE
Spotify: Add Generate Playlist command

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

Added a new feature where the AI can create a playlist for you. You can then add this playlist to Spotify or queue all the songs directly.

## Screencast

https://github.com/raycast/extensions/assets/16003285/8bb88a26-2da3-4a2c-9678-8720da293a3c

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by erics118** [comment]
Should there be some clarification that this is using the Raycast AI feature, rather than part of Spotify's [native](https://newsroom.spotify.com/2024-04-07/spotify-premium-users-can-now-turn-any-idea-into-a-personalized-playlist-with-ai-playlist-in-beta/) AI playlist generation (currently in beta for UK and australia)?

**Comment by andreaselia** [comment]
> Should there be some clarification that this is using the Raycast AI feature, rather than part of Spotify's [native](https://newsroom.spotify.com/2024-04-07/spotify-premium-users-can-now-turn-any-idea-into-a-personalized-playlist-with-ai-playlist-in-beta/) AI playlist generation (currently in beta for UK and australia)?

Yep, I agree.

**Comment by thomaslombart** [comment]
I doubt there'll be soon a Spotify API for this change as the API is quite incomplete regarding new features. I'm thinking we could just name it `Generate Playlist` and then, if an API drops in the future, we could add a command dropdown with two options:
1. Using Raycast AI
2. Using Spotify AI

What do you think?

**Comment by andreaselia** [comment]
I still think it should be made clear that it's not official Spotify functionality, but not too fussed either way.

**Pull request merged**
