### PR TITLE
Update battery-menubar extension

### PR DESCRIPTION
**Pull request by yarnaid**
## Description

Add battery cycles and health

## Screencast

SCR-20230930-nqqh-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the update @yarnaid 🔥 

@panrafal do you mind checking this update 🙂

**Review by panrafal — APPROVED** [review]
Looks great to me! 🏅

**Comment by pernielsentikaer** [comment]
One last thing, do you think we can make the new metadata image look like the other, otherwise, can we take some new?

**Comment by yarnaid** [comment]
I'll update images soon

**Comment by yarnaid** [comment]
> One last thing, do you think we can make the new metadata image look like the other, otherwise, can we take some new?

I've updated the images, check, please

**Comment by pernielsentikaer** [comment]
Awesome, thanks 🔥

**Pull request merged**
