### PR TITLE
Add LaLiga extension

### PR DESCRIPTION
**Pull request by anhthang**
## Description

All the information of LaLiga Santander, LaLiga SmartBank, and Primera División Femenina: schedules, results, standings, news, statistics, and much more

## Screencast

laliga-01
laliga-02
laliga-03

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @anhthang 👋 

Sorry for the long response time. Let's get it ready to be released soon 🔥 

I have a few comments for you to address:

- When filtering with the dropdown and going to the club profile, when going back, then it's back to the first item in the list. It seems to be the same for the other commands.

https://user-images.githubusercontent.com/38033107/164085970-77e6ddd3-b62d-42b4-ab8f-d456e792539a.mp4

- For Fixtures & Results, when using the ActionPanel "Load Previous Matchday" nothing happens.

Looking forward to testing it out again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 👋 

Thanks for your addresses. I have fixed the dropdown one. For fixtures & results, new data is added at the end of the list and the data still there so I dont add loading indicator when this action called

Please review it again

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @anhthang 👋 

Thanks for fixing the dropdown issue. It works as expected 🔥 

Ah, now I see, I didn't understand what it did, and nothing visual was changed! Let's address this. It could be as simple as adding a spinner and success toast when using the Action Panel.

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 

Thanks for your suggestion. I have fixed it.

**Comment by pernielsentikaer** [comment]
Hi @anhthang 👋 

We're close here too! The only thing would be to consider switching Open in Browser and Squad in club profile view 😄

What do you think? You decide, just let me know 😄 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 

I have switched 😄

**Review by pernielsentikaer — APPROVED** [review]
💣

**Pull request merged**
