### PR TITLE
Add google-advanced-search extension

### PR DESCRIPTION
**Pull request by developerlover**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by developerlover** [comment]
Hi @pernielsentikaer and thank you for your feedback,

I think I need some help; I can't reproduce the error. In the code, I only iterate through all the values of the form to build the URL:

```
function buildSearchUrl(values: SearchParams): string {
  const searchParams = new URLSearchParams();

  Object.keys(values).forEach((key) => {
    const value = values[key as keyof SearchParams];
    searchParams.append(key, value);
  });

  return `https://www.google.com/search?${searchParams.toString()}`;
}
```

My test:

https://github.com/raycast/extensions/assets/2411263/2f5d6c36-6f3f-42d6-823d-88d97b14eeac

Thank you!

**Comment by pernielsentikaer** [comment]
It seems like it was something in my end, it works as expected now

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by developerlover** [comment]
Thank you @pernielsentikaer!

Do you have any suggestion about the extension or the code? It is my first extension and mi first time using React + Typescript.

Thank you!

**Comment by pernielsentikaer** [comment]
It's a fairly simple extension and it works as expected; I wouldn't change the code for this 🙂

**Pull request merged**
