### PR TITLE
Add find-and-replace-filenames extension

### PR DESCRIPTION
**Pull request by RenegadeFox**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution 🔥 

Would it make sense to enhance the current store extension that already [renaming files](https://www.raycast.com/theo_daguier/renaming) by @theodaguier 

Sounds like a new command within that extension could do the trick 🙂

**Comment by pernielsentikaer** [comment]
Are you still around @rootr

**Comment by rootr** [comment]
Hey @pernielsentikaer, sorry for the delay I'm pretty new to open source contributing. I'll take a look and see if I can get it added as a command to the [renaming files](https://www.raycast.com/theo_daguier/renaming) by @theodaguier

**Comment by pernielsentikaer** [comment]
All good, let me know if you need anything 🙂

**Comment by RenegadeFox** [comment]
Added it to the [renaming files](https://www.raycast.com/theo_daguier/renaming) extension already in Raycast.

#12641

**Pull request closed without merging**
