### PR TITLE
Tunnelblick: Update Extension

### PR DESCRIPTION
**Pull request by vkhitrin**
## Description

Add a README and metadata screenshots.

Perform migrations for the latest APIs.

Updated `tunnelblick` command interface:
- Fix list icons
- Add a tag showcasing the connection status

Adding an action to disconnect all configurations

## Screencast

Adding metadata.

(Note: I tried to compress the images as much as possible; if quality/size is not up to par, please let me know).

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by vkhitrin** [comment]
This extension doesn't include `CHANGELOG.md`. Should one be created and updated with the date from the git commit and this PR?

**Comment by vkhitrin** [comment]
Including `CHANGELOG.md`.

**Comment by mil3na** [comment]
Hi! Thank you so much for spending time improving this extension! 
I'm not a VPN user, so I don't have a way to build a valid configuration in order to test this update.
Do you mind providing a video of the new functionalities in action?
Also, @SamuelNitsche do you have anything against merging this update?

**Comment by vkhitrin** [comment]
@mil3na, sorry for the delay.

The patch is mostly some visual tweaks:
- Add toast notifications to let users know that configuration is being fetched.
- Fix list icons to display the "Network" icon and color (if connected).
- Add a colored tag to show the connection status.

The only thing added in this patch is to allow users to disconnect all connections in a single action.

I am attaching a video. The video only obfuscates the connection names, but if this patch is merged, it will use the real connection names.


https://github.com/raycast/extensions/assets/32794653/b054f14f-ba12-4261-9044-77d7a1aa9a56

**Review by mil3na — APPROVED** [review]
LGTM!

**Pull request merged**
