### PR TITLE
New Extension: Date Getter

### PR DESCRIPTION
**Pull request by See2et**
## Description

It's Date Getter. You can get a formatted date in your clipboard, and set a format: YYYY-MM-DD.

Example results: 2022-11-28, 221128

## Screencast

It uses no-view mode. 
スクリーンショット 2022-11-28 20 21 07

~~I don't know why, but the icon image of my extension hasn't been updated on my laptop.~~
~~I think it will work in other environments.~~
Never mind it.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contributions, this should however already be possible to do with `Snippets` where you also have auto-expansion available

Raycast-9WauwXO6@2x

Raycast-rmYEXwEg@2x

**Comment by See2et** [comment]
Oh, I hadn't realized it.
I'll close this PR, Thanks!

**Comment by See2et** [comment]
@pernielsentikaer
In the case you gave me, We have to access Search Snippets and choose one in the results to input the date.
There are two steps to get the date, and I feel it is troublesome.
So I prefer to use Date Getter than that way because it is faster.
Then can I reopen this PR and can you allow my extension?

**Comment by pernielsentikaer** [comment]
Just a last question, don't you think it works quite well with a keyword?
Raycast-58q8GCiK@2x

Then you can do it like this:

https://user-images.githubusercontent.com/38033107/204754275-5edb87bb-97c4-4d62-b4f8-63c38c942eef.mp4

keyword can be anything, let me know what you think 😊

**Comment by See2et** [comment]
Oh, I hadn't known it's so powerful and useful!
Thanks and I'm sorry...

**Comment by pernielsentikaer** [comment]
You're so much welcome, and no need to be sorry at all 😊

**Pull request closed without merging**
