### PR TITLE
Add PostHog extension

### PR DESCRIPTION
**Pull request by daibhin**
## Description

An extension for [PostHog](https://posthog.com) - The single platform to analyze, test, observe, and deploy new features. With this extension you can now search for feature flags, cohorts, dashboards, persons & projects within Raycast. You can open each of them in your web browser.

## Screencast
Raycast 2023-07-14 at 09 56 58

posthog 2023-07-14 at 09 56 23

posthog

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by joethreepwood** [comment]
@pernielsentikaer - I work with David, who submitted this extension, at PostHog. I'm on the marketing side and saw on Raycast's site that you handle the community. If there's an opportunity to do any sort of launch co-promotion for this extension, feel free to reach out!

**Comment by mil3na** [comment]
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

Is there a way to provide us with a dummy user with data in order to test your extension? Currently, PostHog requires setting up everything in order to provide an API key. No worries if it would be too much, it would just help and make the process of adding this extension to our store faster.

**Comment by daibhin** [comment]
@mil3na hi 👋 Just checking internally to try and get that setup. Will double back with a solution tomorrow :)

**Comment by daibhin** [comment]
@mil3na just wondering if you got sorted with an account or if there is anything I can do to help with the review process?

**Comment by mil3na** [comment]
Hi @daibhin! I was expecting an answer from your side about an account with dummy user data. Please let me know if that is possible or not so I can continue the review process.

**Comment by daibhin** [comment]
My bad. Sorry for the confusion on this. I have a demo project you can use to test with. I'll need an email that I can add so you will be able to generate an API key as per https://github.com/raycast/extensions/pull/7503/files#diff-1f88dfb9e6e97c263dcb2af4445fbdbbbc431cc02a9357a189e22d57c94768e2

**Comment by mil3na** [comment]
feel free to send it to milena at raycast :)

**Comment by daibhin** [comment]
@mil3na perfect! Just sent

**Comment by mil3na** [comment]
Hi!

I took a look at the extension and I have a few comments:
- Going to the `Projects` view, selecting a project does nothing, while in all other views, selecting something will open the item on the web. Maybe that should be the default for everything?
- There are a few `Open ..` commands that just open a web page. I'm wondering about the value of them, as the user can just create a QuickLink. The other commands are similar, but at least they show some content before opening it on the web. 
- When putting the wrong Data Region on the settings, I only get an unauthorized error message. As this is a simple mistake, maybe the error message could be more specific and the user could figure out what's wrong faster.

And that's it. If you address those things, I guess we are ready to ship 🚀

**Comment by daibhin** [comment]
@mil3na thanks for the feedback!

- There is no default action on projects because there is no direct URL to which you can link in the web app.
- TIL about the QuickLink app. Removed those commands
- I made an error page in case any of the network requests fail. It would be really nice if there was an error component that I could have used instead because it took me a little while to figure out how to make it look good. I opted for an EmptyState over a Detail with markdown but neither felt perfect.

Screenshot 2023-07-27 at 17 07 13

**Comment by mil3na** [comment]
Hi! Thanks for addressing my comments. However, I don't see the error page in all commands. For instance:

CleanShot 2023-07-31 at 11 35 57@2x

Do you mind checking that? Empty screens are not the best for UX.

**Comment by daibhin** [comment]
Thanks for pointing that out @mil3na. Managed to cleanup some of the code too while fixing the issue :)

**Review by mil3na — APPROVED** [review]
Awesome! Looks great. Thanks for your effort :D 🚀

**Comment by daibhin** [comment]
Thanks for the approval @mil3na! I hadn't considered that the extension would go under my name. I just created a `posthog` organisation and [created a PR to transfer ownership](https://github.com/raycast/extensions/pull/7746) (not looking to make it private, just have the extension owned by the organisation). I couldn't find anything in the docs about this but let me know if there is a different procedure.

**Comment by mil3na** [comment]
Hi!
The author needs to be the username you have on Raycast. You can make Posthog the `owner`, but we only allow it for pre-approved orgs. Maybe @peduarte can help you here?

**Pull request merged**
