### PR TITLE
Updated timers menubars refresh rate

### PR DESCRIPTION
**Pull request by pernielsentikaer**
## Description

Now updating every ten seconds instead of every minute

### CODE REVIEW

**Comment by GastroGeek** [comment]
🥳 nice.

**Comment by marcjulianschwarz** [comment]
Looks good to me 👍. Don't know why it was set to 1m in the beginning.

**Review by ThatNerdSquared — APPROVED** [review]

**Comment by pernielsentikaer** [comment]
That's correct, in 1.42.0 it's possible to use 10s 😊

**Comment by ThatNerdSquared** [comment]
Thanks Per!

**Comment by marcjulianschwarz** [comment]
> Looks good to me as well.
> 
> > Looks good to me 👍. Don't know why it was set to 1m in the beginning.
> 
> @marcjulianschwarz it was originally 1m because any lower than that was not supported by the Raycast API, [as I wrote in the original issue for this feature](https://github.com/raycast/extensions/issues/2902#issuecomment-1251602448). I guess it's been updated to allow as low as 10s now? 🥳

Oh thats a nice change! Awesome 🔥

**Pull request merged**
