### PR TITLE
Update sips extension

### PR DESCRIPTION
**Pull request by patomos**
## Description

A simple fix: Flip Images Vertically was flipping the images horizontally. Most likely a copy/paste gone wrong. 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by SKaplanOfficial** [comment]
Good catch, thanks! Not sure if the permission changes on the executables were intentional, but the +x flag gets added programmatically so it still works fine.

Looks good to me. @pernielsentikaer ready for your review.

**Comment by patomos** [comment]
Changes in permissions were not intentional

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by patomos** [comment]
I created a new Raycast account: Patricio Moschcovich
@raycastFanboy

Let me tell you that I am infatuated with Raycast!

It gives me so much pleasure working with it. It makes forget how much I
dislike the mac

**Pull request merged**
