### PR TITLE
Add Pastebin extension

### PR DESCRIPTION
**Pull request by vimtor**
## Description

New extension to interact with https://pastebin.com/

## Screencast

https://user-images.githubusercontent.com/36263538/163889700-ef9c713e-2c77-41c1-a47a-4a352014656a.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by vimtor** [comment]
After some testing by myself I changed the toast title on copy so there is some feedback:

https://user-images.githubusercontent.com/36263538/164676320-8ac0ea01-855b-4efd-b17b-bf78453bd94a.mp4

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @vimtor 👋 

Thanks for another extension 🔥 

I have some feedback for you to address:

- When I paste it ends up like `Guest`. Now that I used credentials I would expect it to be added as me instead?
- When listing pastes, I have some suggestions you can look into:
CleanShot 2022-04-28 at 09 15 08@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pernielsentikaer** [comment]
Hi @vimtor 

Did you have time to look into this one yet? 😄

**Comment by vimtor** [comment]
Hi @pernielsentikaer!

I've improved a bit the icons depending on the publicity state. Sadly I don't have access to whether the paste is burn mode or uses a password.

Regarding the hits, syntax, expire... I wonder whether we should put the paste on a separate `<Detail />` screen using the `metadata` prop like GitHub extension and many others do.

I cannot reproduce the thing you mentioned where pastes end up owned by a Guest. Currently Pastebin's API is doing funky stuff so I might continue it tomorrow to check if I can reproduce it.

I'll keep you updated. If you can please give me feedback on using `<Detail />` or not that would be super helpful ❤️

**Comment by vimtor** [comment]
Fuck I think I did something wrong trying to fix the WhatsApp extension CHANGELOG that does not disappear @mattisssa 
Let me close this PR and open a new one with just the Pastebin extension code.

For context: https://github.com/raycast/extensions/pull/1704#discussion_r873213688

I would love if we can see it together with one Raycast member in my local because it is a huge pain when developing.

Thank you and sorry for tagging the whole team by accident 😅

**Comment by mattisssa** [comment]
>Context of the WhatsApp changeling problem (@mattisssa): https://github.com/raycast/extensions/pull/1704#discussion_r873213688
I would love if we can see it together with one Raycast member in my local because it is a huge pain when developing

Hey! I thought it's resolved 🙈 
Let's jump into DM so I can help you figure that out

**Pull request closed without merging**
