### PR TITLE
Add Sublime extension

### PR DESCRIPTION
**Pull request by phgn0**
## Description

Hello!

This PR adds a new `Sublime` extension which allows people to easily save text, links, or files to their [sublime.app](https://sublime.app) account, and search across their saved content using Raycast.

sublime-1

The supported commands are:

-   `Open Library`: Open your Sublime Library
-   `Save Text`: Save a text to Sublime
-   `Save Link`: Save a link to Sublime
-   `Save Image or File`: Save an image or file to Sublime
-   `Search`: Search your Sublime Library
-   `Search my Collections`: Search your Sublime Collections
-   `Related Cards`: Find Sublime Cards related to a link or text

You can create a free Sublime account for testing [here](http://sublime.app/join).

Please let me know if you have any questions!!

## Screencast

[Demo of test account creation, login, and command testing](https://app.usebubbles.com/svgWUXUyYUweaGESNme4Vo/sublime-raycast-demo)

Screenshot 2024-08-21 at 4 04 14 PM

## Checklist

-   [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
-   [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
-   [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
-   [x] I checked that files in the `assets` folder are used by the extension itself
-   [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Can you look into the other error @phgn0 - the org should now be allowed 🙂

**Comment by phgn0** [comment]
> Can you look into the other error @phgn0 - the org should now be allowed 🙂

Thank you!! I just fixed the lint, title case, and dependency checks!

**Comment by pernielsentikaer** [comment]
Thanks for the demo, it really helped in understanding the flow 🙂

Would it make sense to have a dropdown instead of multilevel lists here?

Raycast27082024-IzB0zdSv png@2x

**Comment by phgn0** [comment]
> Would it make sense to have a dropdown instead of multilevel lists here?

Do you mean having a `searchBarAccessory` dropdown like this?

Screenshot 2024-08-27 at 12 51 44 PM

The problem is that you can have A LOT of Sublime Collections and we wanted to have a command to browse through them. So the primary function of the  `Search My Collections` command really is to browse / search collections (the first list), rather than saved cards inside these collections (which can already be done with the other `Search` command).

For example here are some of my collections (there are 4 pages more): 

Screenshot 2024-08-27 at 12 51 10 PM

Does that make sense?

**Comment by pernielsentikaer** [comment]
Thanks for explaining, it makes sense. Let's go with your solution and see how it goes 🙂

**Review by pernielsentikaer — APPROVED** [review]

**Review by pernielsentikaer — APPROVED** [review]

**Review by pernielsentikaer — APPROVED** [review]

**Comment by phgn0** [comment]
@pernielsentikaer how long does it take for new extensions to be published in the store?

`Sublime` still doesn't turn up: https://www.raycast.com/search?q=sublime

**Comment by phgn0** [comment]
> @pernielsentikaer how long does it take for new extensions to be published in the store?
> 
> `Sublime` still doesn't turn up: https://www.raycast.com/search?q=sublime

Nevermind, it's live now. Thanks!!

**Pull request merged**
