### PR TITLE
Fixed Change Case overlapping shortcuts

### PR DESCRIPTION
**Pull request by PWrzesinski**
## Description

The Change Case extension used the key combinations cmd+r and cmd+shift+r for multiple different actions that were available at the same time in some scenarios, so some actions couldn't be invoked. This PR changes the key for the "Remove Pinned Case", "Clear Pinned Cases", "Remove Recent Case" and "Clear Recent Cases" from "r" to "q". The cmd+r shortcut will invoke only the "Refresh Content" action now, regardless of state.

Example scenario demonstrating incorrect behavior:

> The user has 3 different texts in 3 different files:
> 
>     new york
>     la spezia
>     buenos aires
> 
> The user wants to correct the case for each one to proper Capital Case, so they copy the first one, open Raycast, go to Change Case extension, choose the Capital Case, press enter and paste the result back to the first file.
> 
> Then they go to the second file, copy second text, go back to Raycast and want to hit cmd+k, cmd+r to refresh the result with new clipboard content, **however the Capital Case has moved to recently used cases, so now cmd+r instead of performing the "Refresh Content" action will trigger the "Remove Recent Case" action. The "Refresh Content" action is not available by any shortcut at this point.**

_Note: I've chosen the q key arbitrarily, if there is some convention I should use or there are differing opinions I'm happy to discuss in the comments._

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by PWrzesinski** [comment]
BTW by "they" I very much meant myself and this is super annoying 😬

**Comment by erics118** [comment]
I'd suggest using `ctrl(-(shift-)x`, or, `Keyboard.Shortcut.Common.Remove(All)`
https://developers.raycast.com/api-reference/keyboard#keyboard.shortcut.common

**Comment by erics118** [comment]
> I needed to pull the whole 10GB repository

Raycast offers its own way of managing a singular extension. see: https://developers.raycast.com/basics/contribute-to-an-extension

You can also do a sparse checkout (which is what I do), as I feel more comfortable with using git commands rather than a wrapper around git.

**Comment by pernielsentikaer** [comment]
Forking the extension is the way to go for sure 🔥

**Comment by pernielsentikaer** [comment]
Let me know when this is ready for another review 🙂

**Comment by PWrzesinski** [comment]
@erics118 @pernielsentikaer 

I've changed the keyboard shortcuts to use `Keyboard.Shortcut.Common`. During the development (the fork extension is great!) I've also noted that the popToRoot setting is inverted:

    if (preferences.popToRoot) {
        closeMainWindow();
      } else {
        popToRoot();
      }

I've fixed that as well - previously it would pop to root when the checkbox was unchecked:

change-case-pop-to-root

The PR is ready for another review - thanks for being patient with me!

**Comment by pernielsentikaer** [comment]
Thanks 👏 

@erics118 could you check

**Comment by erics118** [comment]
Looks good 👍

**Review by pernielsentikaer — APPROVED** [review]

**Comment by PWrzesinski** [comment]
> :tada: :tada: :tada:
> 
> We've rewarded your Raycast account with some credits. You will soon be able to exchange them for some swag.

Haha this being merged is reward enough, thanks!

**Pull request merged**
