### PR TITLE
[Dropbox] Optional BYOK + error typing + improve deps

### PR DESCRIPTION
**Pull request by xmok**
## Description

As mentioned in #14105 and #14274, the extension no longer allows you to log in via OAuth due to pending review. As a workaround, this PR brings support to BYOK (bring your own key) by creating your own App in Dropbox and entering a generated access token (instructions are in README). This authentication was removed in #4291 but optionally one can choose to use it.

Full CHANGELOG:
- The List now shows you the current path i.e. directory you are in
- Files now show their last modified
- If OAuth is not working, you can create your own Dropbox App and plug in your own Access Token in Preferences (remove the token to go back to OAuth) [see README for instructions]

## Screencast

https://github.com/user-attachments/assets/24c1fdb3-0fef-42f0-a40e-af1c03c4cf52

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the update @xmok 

@chyroc do you want to check this?

**Comment by pernielsentikaer** [comment]
Seems like it's working again for me

Raycast20092024-RmNHzXZy png@2x

**Comment by xmok** [comment]
dropbox-pending-review

Shows me above when I try to proceed. Perhaps it's working for users who authorized before the app was frozen?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
