### PR TITLE
Add markdown-to-rich-text extension

### PR DESCRIPTION
**Pull request by vegetablesB**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Looks similar to these two 
https://www.raycast.com/aravindballa/markdown-this
https://www.raycast.com/skyline-123/markdown-to-plain-text

**Comment by vegetablesB** [comment]
> Looks similar to these two https://www.raycast.com/aravindballa/markdown-this https://www.raycast.com/skyline-123/markdown-to-plain-text

The result is different.
For markdown text:
```markdown 
# Welcome to StackEdit!
[raycast](https://www.raycast.com/)
```
The result is:
image

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

As said before, this extension does something very similar to pre-existing ones. Maybe you could improve one of the existing ones with the content of your extension. I believe there is no need for multiple extensions to manipulate markdown.

**Comment by vegetablesB** [comment]
> Hi!
> 
> Thank you for your contribution! My name is Milena and I will be reviewing it today.
> 
> 
> 
> As said before, this extension does something very similar to pre-existing ones. Maybe you could improve one of the existing ones with the content of your extension. I believe there is no need for multiple extensions to manipulate markdown.

Sure, here's an updated response incorporating your reason for developing the extension:

---

Hi Milena,

Thank you for taking the time to review my PR.

I understand the concern about having multiple extensions that seem to serve similar purposes. However, I'd like to clarify that my "Markdown to Rich Text" extension offers distinct functionality compared to the existing "Markdown to HTML" and "Markdown to Plain Text" extensions. Here are the key differences:

1. **Output Format**:
    - **Markdown to HTML**: Converts Markdown to HTML code, which is useful for web development and content management systems.
    - **Markdown to Plain Text**: Strips Markdown formatting, providing plain text with no styling.
    - **Markdown to Rich Text**: Converts Markdown into styled text that retains formatting such as bold, italics, headings, and lists, which can be directly pasted into applications that support rich text, like word processors or email clients.

2. **Use Cases**:
    - Users who need clean, styled text for documents, presentations, or rich-text fields in applications will benefit from the "Markdown to Rich Text" extension.
    - This extension simplifies the workflow for users who need to quickly convert Markdown content into a format that preserves the visual style without requiring HTML or losing formatting.

3. **User Experience**:
    - The existing extensions address different user needs and contexts. The "Markdown to Rich Text" extension fills a gap by providing an intermediate solution that is neither plain text nor raw HTML but styled, formatted text.

The reason I developed this extension is that I couldn't find any existing extension that converted Markdown directly to Rich Text. I believe that having a dedicated "Markdown to Rich Text" extension will greatly enhance productivity for users with specific needs for formatted text. Consolidating this functionality into existing extensions might dilute their purpose and make them less focused.

Thank you for considering my perspective. I look forward to your feedback.

**Comment by vegetablesB** [comment]
> Hi!
> 
> Thank you for your contribution! My name is Milena and I will be reviewing it today.
> 
> 
> 
> As said before, this extension does something very similar to pre-existing ones. Maybe you could improve one of the existing ones with the content of your extension. I believe there is no need for multiple extensions to manipulate markdown.


Hi Milena,

Thank you for your feedback and for reviewing my PR.

I understand the concern about having multiple extensions that seem to handle Markdown in similar ways. However, my "Markdown to Rich Text" extension is different from the existing ones, and I’d like to explain how:

### Key Differences

1. **Output Format**:
    - **Markdown to HTML**: Converts Markdown into HTML code, useful for web development and content management.
    - **Markdown to Plain Text**: Strips Markdown formatting, providing plain text without any styling.
    - **Markdown to Rich Text**: Converts Markdown into styled text that retains formatting like bold, italics, headings, and lists. This can be directly pasted into applications that support rich text, such as word processors or email clients.

2. **Use Cases**:
    - **HTML**: Ideal for developers or those working with web content.
    - **Plain Text**: Suitable for those needing unformatted, clean text.
    - **Rich Text**: Perfect for users who need formatted text for documents, presentations, or emails, keeping the visual style without needing HTML or losing the formatting.

3. **User Experience**:
    - Each extension serves different needs. "Markdown to Rich Text" provides an option for users who want their Markdown content converted into a format that maintains styling and can be pasted directly into rich text fields.

### Reason for Development

I created this extension because I couldn't find any existing tool that converted Markdown directly to Rich Text. I believe it fills a gap by offering a straightforward way to maintain the visual formatting of Markdown content in a rich text format.

I hope this explanation clarifies the unique value of the "Markdown to Rich Text" extension. It aims to make life easier for users who need this specific functionality. I look forward to any further feedback you might have.

**Comment by mil3na** [comment]
Thank you for your explanation. I decided to give it a chance for seeing how different these extensions are, however, I'm confused about the usage.
Using the command directly pastes the content of my clipboard on my frontmost app. No preview, no option to chose if I want it on my clipboard or pasted. The action panel still says that the main action is "Open Command" and nothing else. 

In order to make it happen to the Store, I would need this extension to be more clear on what is doing and giving me the options you promised on the README. Let me know if you need any help.

**Comment by mil3na** [comment]
Thanks for the video. My last suggestion would be to rename the command to the actual action that it does: Convert Clipboard To Rich Text. That way, it is clear to the user that the input is the clipboard and it will be converted. Then, after the action is successful, the HUD will make clear where the output is. What do you think?

**Comment by vegetablesB** [comment]
> Convert Clipboard To Rich Text

Hi, 

Thanks for your feedback! I agree, your suggestion to rename the command to "Convert Clipboard To Rich Text" does make more sense.  It clearly conveys the function of the command.  

I've updated the `package.json` to reflect that change and also adjusted the `showHUD` message to be more informative. 

### Command name change
Command

### showHUD Message
Screenshot 2024-07-09 at 8 53 24 AM

**Review by mil3na — APPROVED** [review]
LGTM.

**Pull request merged**
