### PR TITLE
Add zNotch Extension

### PR DESCRIPTION
**Pull request by zkondor**
## Description

New extension `znotch` to manage macbook's notch visibility directly from `Raycast`. Allows explicitly to hide and show the notch, as well as toggle to an opposite state.

## Screencast

Since `macOS` doesn't provide any option to record laptop's screen's notch, the overall effect looks this way:

usage-demo

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by peduarte** [comment]
Not sure what's happened with this PR, but shows that every single file has changed. The review page wont even load. 

image

Could you have a look? Thanks!

**Comment by nhojb** [comment]
> Not sure what's happened with this PR, but shows that every single file has changed. The review page wont even load.

It's because @zkondor is attempting to merge directly into `main`. You need to:

- Stash your PR changes somewhere.
- Reset your fork to https://github.com/raycast/extensions
- Create a new branch for your PR
- Apply the changes to the new branch.
- Re-create the PR.

**Comment by grzegorzkrukowski** [comment]
I don't think that's the real problem @nhojb - we should make PR to the `main` branch - it's correct.

The big problem is that on the fork @zkondor removed everything - all extensions and every single file that was in the repository - instead of just adding his extensions.
You can see it by checking his fork content.

**Comment by grzegorzkrukowski** [comment]
I pushed the fix, but in case you need to do it in the future, here is how to do it easily:

```
//clone repository (it will connect to upstream automatically)
gh repo clone zkondor/raycast-extensions
//FINDER: copy extension folder before next steps
//fetch latest changes from our public repository
git fetch upstream
//reset fork to public repository state
git reset --hard upstream/main
// now you have the same state as our public repository, force push changes to fork as we overwrite history
git push origin main --force
// FINDER: re-add the extension
git add .
git commit -m "Add zNotch Extension"
```

**Comment by grzegorzkrukowski** [comment]
I tried to fix the problem, but somehow I was able to force push to it the reset, but I'm not allowed to add the extension back to the repository 🤯

**Pull request closed without merging**
