### PR TITLE
Add list-randomizer extension

### PR DESCRIPTION
**Pull request by quuu**
## Description

A persistent list that lives in storage that can be randomized via Durstenfeld's shuffle and then copied to clipboard.

This was born out of being tired of showing up meetings and standups that require wasteful popcorning/ forgetting who hasn't gone, or creating mini teams but not having a way to easily randomize the roster without going to some random website.

## Screencast

opening the extension, adding to the list, randomizing, and copying and pasting

https://github.com/raycast/extensions/assets/32676955/0ef78b66-a547-4f99-b63d-47368221a787

not shown in video:
- persistent list from the last time
- deleting the whole list and local file

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Is there a reason why you're using a file on the disk and not [LocalStorage](https://developers.raycast.com/api-reference/storage)

- Could you add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
I'm not completely sure about the use case actually, but it works as expected

**Comment by RenderCoder** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * Is there a reason why you're using a file on the disk and not [LocalStorage](https://developers.raycast.com/api-reference/storage)
> * Could you add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

An expansion question, if the developed plug-in needs to create an image cache locally, what is the better way? The method I used is to store it in the user's cache directory. Is this reasonable? @pernielsentikaer

**Comment by pernielsentikaer** [comment]
Images downloaded within the extension will already be cached by Raycast, so there shouldn't be any reason for further caching.

**Comment by quuu** [comment]
> * Is there a reason why you're using a file on the disk and not [LocalStorage](https://developers.raycast.com/api-reference/storage)
> * Could you add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

Apologies for the delayed response, I've been using this extension every day and forgot it wasn't merged/ available in the store :P

I did see the localStorage API but because the data is meant to be updated quickly/ read quickly, I opted to read sync from a file rather than do an async Localstorage read -- I followed similar methods for loading in initial state quickly from the todo-list Raycast extension -- https://github.com/raycast/extensions/blob/965d8e834648870b50494ee2d6ef0f18c7d33b27/extensions/todo-list/README.md !


> I'm not completely sure about the use case actually, but it works as expected

So far this has been useful in determining ordering for updates, ordering for team selections, and for deciding on many options (like food) :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
