### PR TITLE
Add Wrike Extension

### PR DESCRIPTION
**Pull request by suarez-agu**
## Description

Adds Wrike support to Raycast.
The extension currently allows for searching specific tasks by name
If no text is provided, it defaults to showing the last 100 tasks created by the author.

There are more items in the TODO.md

## Screencast

https://user-images.githubusercontent.com/3652655/161593239-c3206e96-7ec1-4b0d-a18e-d183087d8f3b.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by suarez-agu** [comment]
@pernielsentikaer @fe9lix Any news on this? Is there something I can improve?

**Comment by pernielsentikaer** [comment]
Hi @suarez-agu 👋 

Thanks for your contribution and sorry for the longer response time than usual! 

I tested the extension by following the points in the `README` but it stops quite fast with this:

CleanShot 2022-04-21 at 13 05 27@2x

```
13:06:04.054 search error /Users/pernielsentikaer/Documents/Raycast/tmp/wrike/src/wrike.tsx:22
    throw new Error("errorDescription" in json ? json.errorDescription : response.statusText);
          ^

Error: Access token is unknown or invalid
    at null.getRequest (/Users/pernielsentikaer/Documents/Raycast/tmp/wrike/src/wrike.tsx:22:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at null.getCurrentUser (/Users/pernielsentikaer/Documents/Raycast/tmp/wrike/src/wrike.tsx:33:19)
    at null.performSearch (/Users/pernielsentikaer/Documents/Raycast/tmp/wrike/src/search.tsx:151:23)
    at null.search2 (/Users/pernielsentikaer/Documents/Raycast/tmp/wrike/src/search.tsx:113:25)
```

I tried the process twice to be sure I didn't do anything wrong. Is there something missing in the `README`

Catch me in [Slack](https://raycastcommunity.slack.com/) if you want to debug it with me

**Comment by pernielsentikaer** [comment]
Debugged and gave feedback in [Slack](https://raycastcommunity.slack.com/) 21/4

**Comment by suarez-agu** [comment]
> Debugged and gave feedback in [Slack](https://raycastcommunity.slack.com/) 21/4

All items addressed. Thanks for the improvement ideas.

I also decided to remove the "initial" request as it was very specific to my workflow and not something that everyone will want.  Ill be making another action for "Latest modified tasks I follow"

**Comment by pernielsentikaer** [comment]
Hi @suarez-agu 👋 

Thanks for the update, I'll DM you in [Slack](https://raycastcommunity.slack.com/) to get a new test token 😄

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Thanks for your contribution!

I tested your extensions, and it works as expected now 🔥

**Pull request merged**
