### PR TITLE
Update Ploi extension (related to #12786)

### PR DESCRIPTION
**Pull request by xmok**
## Description

As per Issue #12786, this half-addresses the issue by paginating Servers. Sites are not paginated because the way the Sites components are currently structured, the Sites are in List Items on the top and the other List Items are Actions so native pagination might require some UI changes.

I've wrapped an API call in `usePromise` which allows us to natively paginate the Servers. There are some flickers and state changes happening but I am able to reproduce them in the current version installed from the Store as well so that will need further refactoring of the code and is out of scope for this PR.

## Screencast

Here is a "real" screencast using an actual Ploi instance that has 1 server.

https://github.com/raycast/extensions/assets/30526133/1dcf3890-3f66-4c82-b4d0-589f226ece86

Here is a "fake" screencast in which I mocked the server response locally in order to show more servers and pagination in action.

https://github.com/raycast/extensions/assets/30526133/074eed2e-0dff-4727-9de1-e8c9ebb82b71

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

<details><summary>Dev Notes</summary>

- We can't simply set the PLOI_PER_PAGE to a number greater than 50 as `50` is max and a larger number defaults to `15` (https://developers.ploi.io/27-getting-started/81-pagination)
- One way we could tackle the initial flickering and related is to replace existing API call w/ a `useFetch` or wrap in a `usePromise`. Instead of `useEffect`, we can utilize `onWillExecute` of the hooks to carry out the related LocalStorage actions.
</details>

### CODE REVIEW

**Comment by corentinbtmps** [comment]
Hey @xmok! Thanks for this PR.

After some testing it seems to work fine on (infinite) scrolling, the new servers are there and appear fine, but the order is a bit weird and the search doesn't retrieve the added/last results if that helps.

It's very close to something usable and functional, thanks again!

**Comment by xmok** [comment]
Awesome!

I'm going to convert this PR to a Draft so I can work on improving the issues you're mentioning.

Would it be possible for you to share a screencast of the current behavior so I can best understand how to tackle it?

**Comment by Cannonb4ll** [comment]
Nice work @xmok! Appreciated 💙

**Comment by xmok** [comment]
Thanks @Cannonb4ll! 🫡

@corentinbtmps after further testing, sort and Server Pagination seems to work ok for me. I can refactor the code to use hooks instead of API calls which would allow us to paginate other items as well but that would be beyond this PR.

I am re-opening this PR so we can get it merged and then I can work on improving sorting and related performance in the near future.

**Review by mil3na — APPROVED** [review]

**Comment by mil3na** [comment]
@corentinbtmps, If you are okay with these changes, I guess we can go forward and merge this.
@xmok I would be happy with future improvements :)

**Comment by corentinbtmps** [comment]
@xmok : Yes, It works more than fine on this version, this PR can be merged for sure @mil3na !

PS: Sorry for the short delay, my team and I are in the middle of a summer sprint 🤓

**Pull request merged**
