### PR TITLE
Add trim-clip extension

### PR DESCRIPTION
**Pull request by remorses**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution 🔥 

Would it make sense to add this to [YAFW extension](https://www.raycast.com/pablopunk/yafw) by @pablopunk

**Comment by remorses** [comment]
No, makes it more difficult to find in the store. An user doesn't need to know what ffmpeg is to trim a clip.

**Comment by pernielsentikaer** [comment]
I gave it another spin 🙂

- Can you handle this error gracefully?

trim-clip 2024-08-29 at 08 44 41

- Could we show a animated toast while it's working, it's not possible to see what's going on 🙂

**Comment by remorses** [comment]
The extension now shows a toast when there are no files selected and the loading spinner should show faster.

**Comment by pernielsentikaer** [comment]
That's much better 🔥 

I just tested it with a video and trimmed it, most of it is just black - the original video has content - do you have a clue why?

Uploading bug-auto-change-alias-Scene-001-Scene-001-Scene-001-trimmed-0-15.mp4…

**Pull request closed without merging**
