### PR TITLE
[Notion] Major(ish) refactoring (pt. 1)

### PR DESCRIPTION
**Pull request by bkeys818**
## Description

This PR will deal with refactoring the following:
- [x] The `DatabaseProperty` and `PageProperty` types.
- [x] Refactor `PagePropertyField.tsx` (63b62bddc88a7e0a2c647285283409ff1081c20b - needs testing)

### The `DatabaseProperty` and `PageProperty` types

I've been putting off dealing with this for a while, but it's long overdue. Notion's method of typing objects is a nightmare in typescript. I've implemented a few hacks over the years but never dealt with the larger issue. This PR should put that nightmare to rest.

I've written an unhealthy amount of Typescript over the last half-decade, but this might be the best. I've created a new type, `Standardized`, and a helper function, `standardize`. 

#### Here's how it works:

Currently, Notion's objects (page properties in this example) look like this.
```js
[{ type: "checkbox", checkbox: true }, { type: "url", url: "..." }]
```

That's fine until you want to get the value inside a loop. For example:
```ts
props.forEach(prop => {
  prop[prop.type] // No index signature with a parameter of type 'string' was found on type...
})
```

So here's the solution. The `Standardized` type and `standardize` function will take those Notion objects and convert them to the following format.
```js
[{ type: "checkbox", value: true }, { type: "url", value: "..." }]
```

The new key doesn't have to be `"value"`, it can be anything. Inside of `DatabaseProperty`, it's `"config"`.
Here's the best part: It's recursive.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by bkeys818** [comment]
@thomaslombart

Can you take a look at what I have so far? I want to get a second opinion before I continue.

**Comment by thomaslombart** [comment]
I'm not too familiar with the original issue. I don't see any problems with your implementation (I haven't tested the extension though). Are you looking for a second opinion on something specific?

**Comment by bkeys818** [comment]
@thomaslombart

Honestly, no really. I just want to allow everyone to put their 2 cents in.

**Comment by bkeys818** [comment]
Are there any standard practices for implementing unit testing for extensions?

**Comment by thomaslombart** [comment]
Not really as of now though it's something we'd like to do at some point.

**Comment by bkeys818** [comment]
@thomaslombart @thomaslombart

How realistic would it be for `ray lint` to run `npm test` if a test script exists in `package.json`?

Then tests would also be run when PRs are opened.

Is there a PR for this topic?

**Comment by thomaslombart** [comment]
It's feasible, but we don't have a testing framework for extensions yet, so there's no real point to it as of now.

**Comment by bkeys818** [comment]
@thomaslombart This PR is ready whenever you get the chance to look at it.

I'd like to have some people beta test it for a week, but I'm not sure how we'd do that.

**Comment by bkeys818** [comment]
@mathieudutour, Would you be able to look at this, or should I just wait for @thomaslombart to return from vacation?

**Comment by mathieudutour** [comment]
We are all at an offsite next week, Thomas will have a look the week after - sorry for the delay

**Comment by bkeys818** [comment]
@HenriChabrand @mathieudutour @metakirby5 @thomaslombart @erics118 @AlexIsMaking @Yakitrak @tleo19 @dariuszpaluch @zsidnam

This PR would really benefit from some beta testing, to insure nothing is broken. Would any of you be willing to run it locally for a week or so?

**Comment by zsidnam** [comment]
@bkeys818 I'm happy to be a beta tester, but would it make sense to hold off on that until the PR is approved in case changes are required that would invalidate testing?

**Comment by bkeys818** [comment]
@zsidnam

This PR only contains refactoring, so nothing should be functionally different. That being said, there are a lot of changes. Having beta tests would ensure that everything is working like normal.

I've done a decent amount of work on this extension, and @thomaslombart and I spoke about reworking the property components here: https://github.com/raycast/extensions/pull/13507#issuecomment-2267553982. As long as everything working as expected, I'm fairly confident this PR will be accepted.

**Comment by zsidnam** [comment]
> I've done a decent amount of work on this extension, and @thomaslombart and I spoke about reworking the property components here: https://github.com/raycast/extensions/pull/13507#issuecomment-2267553982. As long as everything working as expected, I'm fairly confident this PR will be accepted.

@bkeys818 sounds good; I'll install it today 👍 If there is anything specific you'd like tested, just let me know, else I'll smoke test and run through my normal workflows for the next week.

**Comment by zsidnam** [comment]
@bkeys818 I've been running this for the last week and haven't encountered any issues 👍 (I've primarily been creating new database pages and searching for existing pages -- both seem to be working fine!)

**Comment by bkeys818** [comment]
@thomaslombart Could you take a look at this PR when u get a chance?

**Comment by pernielsentikaer** [comment]
Hi @bkeys818 👋

I'll take over this PR. I'm giving it a spin until Monday and hopefully, we'll be able to merge it then 🙂

**Comment by bkeys818** [comment]
@pernielsentikaer Perfect! Thank you!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Let's keep an eye out for bugs in the next couple of days 🙂

**Pull request merged**
