### PR TITLE
Update Coffee extension with menu bar toggle command

### PR DESCRIPTION
**Pull request by stursby**
## Description

Adding a new menu bar icon to toggle the Coffee extension!

## Screencast

https://user-images.githubusercontent.com/527849/192435282-621e3ede-b9bd-4003-8f81-c84ff7926a0d.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by peduarte** [comment]
nice! would be cool to change the icon based on the state

**Comment by pernielsentikaer** [comment]
Would be awesome to move this away from AppleScript and just use something like `exec` instead since there is no real reason to use AppleScript for this.

I tried to make it work but there is some issues with AppleScript hanging when I tried. I did like this:

```
import { useState, useEffect } from "react";
import { MenuBarExtra, Icon } from "@raycast/api";
import { isCaffeinated } from "./utils";
import Caffeinate from "./caffeinate";
import Decaffeinate from "./decaffeinate";

export default function MenuCommand() {
  const [state, setState] = useState({ isLoading: true, caffeinated: false });
  useEffect(() => {
    (async () => {
      setState({ isLoading: false, caffeinated: await isCaffeinated() });
    })();
  }, []);

  return (
    <MenuBarExtra icon={state.caffeinated ? Icon.LightBulb : Icon.LightBulbOff} isLoading={state.isLoading}>
      <MenuBarExtra.Item title={`Your mac is ${state.caffeinated ? "caffeinated" : "decaffeinated"}`} />
      <MenuBarExtra.Item
        title={state.caffeinated ? "Decaffeinate" : "Caffeinate"}
        onAction={async () => {
          if (!state.caffeinated) {
            await Caffeinate("", false);
            setState({ ...state, caffeinated: true });
            return;
          }
          await Decaffeinate(false);
          setState({ ...state, caffeinated: false });
        }}
      />
    </MenuBarExtra>
  );
}
```

Maybe you can use some of above in your version - let me know what you all think

**Comment by stursby** [comment]
@pernielsentikaer Yea... I was just trying to not rewrite the whole app haha. So I piggybacked off the existing Coffee/AppleScript app 🤷‍♂️. 

Did you get your code snippet above to actaully work with switching the icon?!? (I couldn't get mine to work "in real time", ie: it would only change after clicking back on the icon)

**Comment by peduarte** [comment]
Oh yeah I think that's a re-rendering bug in Raycast, apparently it has been fixed but not released. cc @thomaspaulmann

**Comment by thomaspaulmann** [comment]
> Oh yeah I think that's a re-rendering bug in Raycast, apparently it has been fixed but not released. cc @thomaspaulmann

Yeah that issue should be fixed with our release this week. Great menu bar command!

**Comment by pernielsentikaer** [comment]
@stursby it was looking something like below, but we should rewrite the script completely to just use something like exec instead 😊

```
import { runAppleScript } from "run-applescript";

export async function isCaffeinated() {
  try {
    await runAppleScript(`do shell script "pgrep caffeinate"`);
    return true;
  } catch (_) {
    return false;
  }
}
```

**Comment by peduarte** [comment]
@stursby oh btw, if you wanna activate it with a single click — and now show the menu — take a look at my confetti extension code. i achieved that by rendering "null" and tapping into "useEffect" 

https://www.raycast.com/peduarte/1-click-confetti

**Comment by pernielsentikaer** [comment]
That would be more awesome 😊

**Comment by peduarte** [comment]
@stursby raycast 14 is released and I can confirm it fixes the re-rendering issue. updated one of my other extensions: https://github.com/raycast/extensions/pull/3050

**Review by pernielsentikaer — APPROVED** [review]

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Wrong PR 😊

**Pull request closed without merging**
