### PR TITLE
feat: add protect PDF command

### PR DESCRIPTION
**Pull request by MohamedK1**
## Description
Extending the command with Protect PDF Command

## Screencast
https://github.com/raycast/extensions/assets/41074872/26e99c77-525d-4324-853b-e82664e0a325

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Closing this as it seems to be a duplicated of #13222.

**Comment by MohamedK1** [comment]
> Closing this as it seems to be a duplicated of #13222.

@mil3na, It's not a duplicate they are doing opposite functionality, one to protect a normal PDF by adding to it a password and the other one is to open/unlock a PDF that's already have a password

**Comment by mil3na** [comment]
oh, sorry about that. Can you fix the conflicts on both, then?

**Comment by MohamedK1** [comment]
> oh, sorry about that. Can you fix the conflicts on both, then?

resolved for open PRs. They are mainly due to the changelog. I think after merging any of the opened PRs, these conflicts will be existing again.

**Comment by koinzhang** [comment]
Why can't these PRs be combined into one? What are the considerations for splitting into multiple PRs?

**Comment by koinzhang** [comment]
#13253 #13222 #13252 #13238 #13299 and this

**Comment by MohamedK1** [comment]
> Why can't these PRs be combined into one? What are the considerations for splitting into multiple PRs?


 For separation of concern that each separate command is in a seprate PR. It's better also for organisation.

**Comment by mil3na** [comment]
Hey @MohamedK1 ! Thanks for your contribution. Hopefully, merging these PRs will not cause a lot of conflicts, otherwise it will slow down the process of them being accepted.

I tested this PR and it did not work for me. I get the error below. Do you know what is going on or if iLovePDF has any limitations?

CleanShot 2024-07-04 at 10 35 47

**Comment by MohamedK1** [comment]
> Hey @MohamedK1 ! Thanks for your contribution. Hopefully, merging these PRs will not cause a lot of conflicts, otherwise it will slow down the process of them being accepted.
> 
> I tested this PR and it did not work for me. I get the error below. Do you know what is going on or if iLovePDF has any limitations?
> 
> CleanShot 2024-07-04 at 10 35 47

I checked again and it's working. You are getting 401 which is due to issue in authentication. Could you make sure that the public and private key are correct? or if u could send any failing pdf with you where I can try with it and see.

**Review by mil3na — APPROVED** [review]
Hey! You were correct, the keys were wrong. Probably I pasted twice or something. What bugs me is that the extension never told me to check the keys. Maybe an improvement for the future?

For now, this is working as expected and LGTM!

**Pull request merged**
