### PR TITLE
Add gauthenticator extension

### PR DESCRIPTION
**Pull request by wd**
## Description

This is a tow-factor code generate extension for raycast, it works just like the Google Authenticator or other Two-Factors Authenticators.

More details can be found in the [Readme](https://github.com/raycast/extensions/blob/d65a26d491a67839ef3dc1b98a541faf8de30c0e/extensions/gauthenticator/Readme.md). 

## Type of change

New extension

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by es183923** [comment]
There is already https://www.raycast.com/cjdenio/two-factor-authentication-code-generator that does the same thing.

**Comment by wd** [comment]
> There is already https://www.raycast.com/cjdenio/two-factor-authentication-code-generator that does the same thing, why do we need another one?

Yeah, I know that. I have explained in the [readme](https://github.com/raycast/extensions/blob/d65a26d491a67839ef3dc1b98a541faf8de30c0e/extensions/gauthenticator/Readme.md). This one is compatible with the one for Alfred and can be configured from a plain text file, so no need to add them one by one from the UI.

**Comment by guga4ka** [comment]
Is it make sense to do a pr to the 2fa current extension  https://www.raycast.com/cjdenio/two-factor-authentication-code-generator instead of a new one? Also, it already supports `otpauth` URL parsing with options: a number of digits, hashing algorithm (f.e. some of the services that are using authy as a 2fa backend is using 7 digits and 10 sec period). I guess additional command to parse a file might be much more useful than an additional extension. One more thing, storing initial seeds in plain text on the file system might be a bit insecure.

**Comment by wd** [comment]
@pernielsentikaer  I think it is ready for review. 
My initial thought to create this extension is to have the same experience when I use Alfred. After I finished, I thought maybe it also could help others, so I created this PR. It's ok if it can't get merged. Thank you.

**Comment by pernielsentikaer** [comment]
Hi @wd 👋 

Firstly, thanks for your contribution 💯 

Encouraging users to store their TOTP secrets in a plain text file might indeed not be the best idea – apps like 1Password do that in a safe and encrypted way.

One solution could be to add a one-time import function. If it’s about compatibility with Alfred, an import should solve that problem, since the file can be deleted or safely stored afterwards. Once it’s imported, you can enable users to manually add new entries and store them via the local storage API (which encrypts the data).

If that's the case, it would be even better to add that import feature to one of the existing authenticator extensions – what do you think about that and could that be a viable solution somehow?

**Comment by wd** [comment]
> If that's the case, it would be even better to add that import feature to one of the existing authenticator extensions – what do you think about that and could that be a viable solution somehow?

Yeah, as we have discussed in previous posts, that could be a solution if we don't like using the plain text file. 
I'll close this PR. And I'll create another PR for the existing auth extension if I move to use it.

**Pull request closed without merging**
