### PR TITLE
Add markdown-search extension

### PR DESCRIPTION
**Pull request by xiaokyo**
## Description
Search local's md‘s content and filename

- multiple path configration
- multiple exclude regexp

## Screencast
image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by xiaokyo** [comment]
> https://developers.raycast.com/information/best-practices#handle-errors

ok, I will impove that

**Comment by xiaokyo** [comment]
> Hi @xiaokyo ! Thank you so much for your contribution to Raycast! My name is Milena and I will be reviewing your extension today :)
> 
> Can you explain to me the use of it other than being a file search? Raycast already has it built in :) There are a few usability issues: there's no default path and I'm only asked to add paths after the first query. Moreover, when typing an invalid path, the error is thrown at the user's face. There are nice ways to do so: https://developers.raycast.com/information/best-practices#handle-errors
> 
> Also, if you want to document your code, please stick to English :)

My Engilsh is bad, Let me try to explain
It's can search markdown's file's content

like the markdown file ```readme.md```
```
# js how to control clipboard
```

on the This tool,  I can search the query of ```clipboard``` or ```js how to control``` , that Locate the file and open it

**Comment by xiaokyo** [comment]
> Hi @xiaokyo ! Thank you so much for your contribution to Raycast! My name is Milena and I will be reviewing your extension today :)
> 
> Can you explain to me the use of it other than being a file search? Raycast already has it built in :) There are a few usability issues: there's no default path and I'm only asked to add paths after the first query. Moreover, when typing an invalid path, the error is thrown at the user's face. There are nice ways to do so: https://developers.raycast.com/information/best-practices#handle-errors
> 
> Also, if you want to document your code, please stick to English :)

why raycast advanced's window capture that 1000x625, how to capture picture is 2000x1250

**Comment by mil3na** [comment]
Hi @xiaokyo!
I understand what your extension does and I believe it is a functionality that we already have natively:

CleanShot 2023-06-20 at 14 17 13@2x

I will be closing this for now, but feel free to contact me on [slack](https://www.raycast.com/community) if you have any questions.

Moreover, our extensions' content, including code, code comments, and README files should be in English. Please consider it in case of future contributions :)

Cheers!

**Comment by xiaokyo** [comment]
> 

ok

**Comment by xiaokyo** [comment]
> Hi @xiaokyo! I understand what your extension does and I believe it is a functionality that we already have natively:
> 
> CleanShot 2023-06-20 at 14 17 13@2x
> 
> I will be closing this for now, but feel free to contact me on [slack](https://www.raycast.com/community) if you have any questions.
> 
> Moreover, our extensions' content, including code, code comments, and README files should be in English. Please consider it in case of future contributions :)
> 
> Cheers!

it is very very much files
image

**Comment by mil3na** [comment]
No, it doesn't exclude paths other than your user/your entire computer, however, is much more a feature to be added to this extension than creating a new one. I can add this suggestion for you if you want!

**Comment by xiaokyo** [comment]
> No, it doesn't exclude paths other than your user/your entire computer, however, is much more a feature to be added to this extension than creating a new one. I can add this suggestion for you if you want!

thanks

**Pull request closed without merging**
