### PR TITLE
Add material-icons

### PR DESCRIPTION
**Pull request by creasty**
## Description

Add `Search Material Icons` command that let you search material icons and preview them within Raycast.

## Screencast

screenshot-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by creasty** [comment]
Well, this is annoying...

**Comment by Aayush9029** [comment]
@creasty It seems like we already have a similar extension for this https://github.com/raycast/extensions/pull/1176.  it'd be awesome if you could incorporate your amazing code there! Perhaps by submitting a PR 

Just a suggestion though! Feel free to ignore!

**Comment by pernielsentikaer** [comment]
Hi @creasty 👋 

I'm so sorry for the waiting time, we're working on bringing the queue down, and we're almost back from easter 😄 

What do you think about what @Aayush9029 said?

**Comment by creasty** [comment]
> What do you think about what @Aayush9029 said?

Mine is more optimized for Material Icons, intended to mimic functionality of https://fonts.google.com/icons.
Iconify doesn’t come with canonical names, so when you want to view `edit` icon in the other extension for instance, you have to type that name exactly, whereas in my extension you can get the same icon for other keywords like `pen` or `write`.

**Comment by fe9lix** [comment]
Cheers! I've just removed the rendundant LICENSE file.

**Pull request merged**
