### PR TITLE
Add spring-initializr extension

### PR DESCRIPTION
**Pull request by danvega**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by danvega** [comment]
@pernielsentikaer Do you want the screencast embedded into the readme?

**Comment by danvega** [comment]
I have added a screenshot and a video preview of the extension. I will also publish this

https://github.com/danvega/raycast-spring-initializr

**Comment by pernielsentikaer** [comment]
Thanks for the video 🙂

- Would it make sense to poptoRoot() after creating the file (and maybe even open the Downloads folder)

- Would it make sense to add a preference to let the user select another output directory?

**Comment by danvega** [comment]
Yes, I think both of those would be nice...I'm not sure how to make either of them happen though 🤦‍♂️

**Comment by pernielsentikaer** [comment]
Why are you not able to do that?

**Comment by danvega** [comment]
This is my first extension... Do you have any examples of how to do that?

**Comment by pernielsentikaer** [comment]
You can call popToRoot() after success, you can see [here](https://developers.raycast.com/api-reference/window-and-search-bar#poptoroot) how to

You can add a preferences as a `directory` type and get the value in the frontend: https://developers.raycast.com/api-reference/preferences#getpreferencevalues

**Comment by danvega** [comment]
@pernielsentikaer I have made those changes in my repo but I am having issues publishing this now 🤦‍♂️

```
❯ npm run build

> build
> ray build

info  -  entry points [src/spring-initializr.tsx]
info  -  compiled entry points
info  -  generated extension's TypeScript definitions
ready -  built extension successfully
❯ npm run publish

> publish
> npx @raycast/api@latest publish

(node:1574) ExperimentalWarning: CommonJS module /Users/vega/.nvm/versions/node/v23.2.0/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /Users/vega/.nvm/versions/node/v23.2.0/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ready  - validate package.json file
ready  - validate package-lock.json
ready  - validate other lock files
ready  - validate extension icons
ready  - run ESLint
ready  - run Prettier 3.3.3
ready  - getting fork
ready  - preparing clone
error  - checking for new contributions
failed running git Command failed: git merge-base --is-ancestor df7dd9d491d72e6a2ce38117062e7b4bad59b8a7 447a45f5dc30b581abb01b79c7c14bc132262f2d && echo "success"
```

**Comment by pernielsentikaer** [comment]
Could you try updating @raycast/api to version 1.87.3 to see if it changes anything?

**Comment by danvega** [comment]
@pernielsentikaer similar issue

```
error  - checking for new contributions
failed running git Command failed: git merge-base --is-ancestor df7dd9d491d72e6a2ce38117062e7b4bad59b8a7 447a45f5dc30b581abb01b79c7c14bc132262f2d && echo "success"
```

**Comment by mathieudutour** [comment]
can you try to run 

```
cd ~/.config/raycast/public-extensions-fork
git merge-base --is-ancestor df7dd9d491d72e6a2ce38117062e7b4bad59b8a7 447a45f5dc30b581abb01b79c7c14bc132262f2d
```
?

**Comment by danvega** [comment]
can we just delete the PR and try again? 

image

**Comment by pernielsentikaer** [comment]
Closing as requested

**Pull request closed without merging**
