### PR TITLE
Add node-release-notes extension

### PR DESCRIPTION
**Pull request by filipszczepanski**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

Did you see [this extension](https://www.raycast.com/andresmorelos/node-version-manager) before submitting this one, they seems like they're doing similar things 🙂

**Comment by filipszczepanski** [comment]
> Hi 👋
> 
> Thanks for your contribution 🔥
> 
> Did you see [this extension](https://www.raycast.com/andresmorelos/node-version-manager) before submitting this one, they seems like they're doing similar things 🙂

Hi 👋,
yes, I saw that, but this new extension helps to browse all the release notes of Node.js. 
Users don't need to install Node Version Manager (like nvm, brew, fnm, etc.). 😉

**Comment by filipszczepanski** [comment]
> Wouldn't it be better to update that extension instead, since it does show the same versions, or is that a wrong assumption?

This is not the same. My extension displays all Node.js versions, unlike the "Node Version Manager" extension.

The main purpose of the "Node Version Manager" extension is to manage Node installations. My extension, on the other hand, is designed for quickly accessing release notes and documentation, such as LTS, Latest, etc.

1. Would you like me to integrate the current code from my extension into the "Node Version Manager" extension, but include the node installation option (nvm, brew, etc.)?
2. Or should I rename my extension to "Node Releases"?

**Comment by pernielsentikaer** [comment]
What do you think would be best here @AndresMorelos

**Comment by pernielsentikaer** [comment]
Thanks for chipping in @AndresMorelos  - what do you think about that @filipszczepanski

**Comment by filipszczepanski** [comment]
OK. I rename the extension to `Node Release Notes`.
Should I open a new PR for that? @pernielsentikaer

**Comment by filipszczepanski** [comment]
@pernielsentikaer it's done ✅

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
