### PR TITLE
New extension: Bitrise

### PR DESCRIPTION
**Pull request by ofalvai**
## Description

This PR adds a new extension for [Bitrise](https://bitrise.io) in order to manage CI builds and workflows from Raycast. Bitrise has a public API ([Swagger doc](https://api-docs.bitrise.io/#/builds/build-list)) and the extension uses a Personal Access Token for authentication.

The initial Raycast commands are:

- List Builds: grouped by running/completed status, can be filtered to a single app.
- List Apps: all apps the user has access to, this navigates to the build list
- Start Build: Raycast form to trigger a new build. It fetches the available apps and workflows for the selected app.
- Search Step Library: lists all available steps with optional maintainer badges and actions for opening/copying various URLs.

#### About the existing Bitrise extension

I noticed there is an existing Raycast extension called `Bitrise Builds`. That extension is limited to a single command though (listing builds). I named my extension simply `Bitrise` because it already contains more commands and actions, and I plan to add even more functionality from the Bitrise API. Let me know if this is a bad idea, I'm not sure what is your policy for overlapping extensions.

## Screencast

https://user-images.githubusercontent.com/1694986/210204936-9bcb6d1d-a6c0-4ddb-96d6-378fabbcdf46.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Thanks for your contribution 💯 

Did you see #65 (https://www.raycast.com/ubuntudroid/bitrise) before making this? Looks like it has the same purpose and we should aim to update the current one instead of having two - what do you both thinks?

**Comment by ofalvai** [comment]
Hello @pernielsentikaer 👋 

Yes, I've seen the other extension (unfortunately only after starting the work on mine), and I included my thinking in the PR description:

> About the existing Bitrise extension
I noticed there is an existing Raycast extension called Bitrise Builds. That extension is limited to a single command though (listing builds). I named my extension simply Bitrise because it already contains more commands and actions, and I plan to add even more functionality from the Bitrise API. Let me know if this is a bad idea, I'm not sure what is your policy for overlapping extensions.

Do you think it would be better to merge the two extensions into one?

**Comment by pernielsentikaer** [comment]
What do you think @ubuntudroid 😊

**Comment by ubuntudroid** [comment]
@ofalvai congrats to making such a powerful extension. It in fact does so much more than mine. As you guys likely have more capacity to expand it than I and that it would be kind of an official expansion (considering you are working at Bitrise 😅 ) I would opt-for making a new one using the official bitrise namespace.

The only downside would be, that users currently using my extension would likely want to migrate to yours if only they knew about it. 🤔  If we merged @ofalvai's changes into my extension this obviously wouldn't be a problem. @pernielsentikaer is there a good way to let users of my extension know about the new extension once it is released?

**Comment by pernielsentikaer** [comment]
We can for sure fiddle around, so this extension thinks it's yours; this way everyone that haves yours installed will get this as an update instead 😊

So you're okay with this superseding yours and making you a contributor on this?

**Comment by ubuntudroid** [comment]
> We can for sure fiddle around, so this extension thinks it's yours; this way everyone that haves yours installed will get this as an update instead 😊

Sounds great! 😎 

> So you're okay with this superseding yours and making you a contributor on this?

For sure! I would even agree without me being marked as a contributor, as technically I didn't write a single line of code in that new extension. 😅

**Comment by ofalvai** [comment]
@ubuntudroid thank you for the kind words. I appreciate your offer to replace the `bitrise` namespace with this extension!

I added you as a contributor to this new extension as well as to the README to give credit where credit is due :)

@pernielsentikaer I updated my PR, replacing the old `bitrise` extension with the new code. I ensured it uses the same preference key (`apiKey`) as the old code. This is going to allow smooth migration of existing users, right? Is there anything else I need to keep in mind?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
