### PR TITLE
Add app-keeper-manager extension

### PR DESCRIPTION
**Pull request by onlysunjun**
## Description
This extention offers users the ability to manage currently running applications, with options to choose which apps to keep open and which to close during cleanup. It's especially suited for users looking to optimize their work environment and increase productivity. Users can set apps to “Always Keep,” ensuring they aren't closed during cleanup operations. The extension also provides an intuitive interface to add or remove apps from the preset keep list and features a one-click function to close non-kept apps.

## Screencast
iShot_2024-04-06_21 25 04

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Missing a loading indicator when you open the extension, it just shows nothing until results are there

Uploading Raycast08042024-cFJzFF03.png.mp4…

- What's the  difference between keep and always keep?

- maybe have the "Always keep" section in top OR just have it in the list as the rest of the elements, it's a bit confusing.

- What does the grey dot means? I tried to hover it but found no tooltip for it

Raycast08042024-c0At81tX png@2x

- Maybe add icons here

Raycast08042024-8TVhtZXl png@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

- Could you make so the PR is editable for maintainers 🙂

**Comment by onlysunjun** [comment]
- Adding a Loading Indicator
Implemented a loading indicator to indicate when data is being fetched.

- Difference between "keep" and "always keep"
"Always keep" is for software that users frequently need to keep open for an extended period without closing by default, reducing the need for repeated selections.
"Keep" is for software that needs to be retained and not closed for the current session, providing flexibility for ad-hoc situations.
- Placement of the "Always Keep" Section
Moved the "Always Keep" section to the bottom considering its relatively lower frequency of interaction.
- Meaning of the Grey Dot
Initially, there was a grey dot intended to indicate selection, but it was redundant with the corresponding tags, so it has been removed.

I'm a complete beginner with zero experience. If there are any inappropriate aspects, I'll further study and make necessary modifications.

**Comment by onlysunjun** [comment]
iShot_2024-04-10_17 16 48
iShot_2024-04-10_17 17 13

**Comment by onlysunjun** [comment]
a screen shot
screen_shot

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by onlysunjun** [comment]
> 🎉 🎉 🎉
> 
> Such a great contribution deserves a reward, but unfortunately we couldn't find your Raycast account based on your GitHub username (@onlysunjun). Please [link your GitHub account to your Raycast account](https://www.raycast.com/settings/account) to receive your credits and soon be able to exchange them for some swag.

My raycast account mail :only_zone@126.com
I try to connect with github, but got failed.
The sign in failed with the following message:
ActionController::InvalidAuthenticityToken

**Comment by onlysunjun** [comment]
> Hi 👋
> 
> Looks good to me, approved 🔥

Thanks for your patience.

**Pull request merged**
