### PR TITLE
Add raycaster extension

### PR DESCRIPTION
**Pull request by stevedylandev**
## Description

An extension that allows users on Farcaster to send posts from Raycast, with the ability to attach images with Pinata!

## Screencast

https://github.com/raycast/extensions/assets/73185218/731a8a18-702d-4fee-a013-07d2944438f7

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by stevedylandev** [comment]
Hey all! Really excited to see if we can get this thing published :) Some context and instructions for testing:

**What is Farcaster?**
[Farcaster](https://farcaster.xyz) is a sufficiently decentralized social network that uses a mix of blockchain and peer to peer infrastructure to create an open social graph. With this model clients can take many forms and send posts (aka "casts") to the network and sync messages.

**Why Raycaster?**
Raycast + Farcaster. There are a few other extensions out there that specialize in reading or searching posts on Farcaster, but this one is specializing in just sending posts to the network. It provides an effortless experience for sending casts; even uploading image attachments. 

**Steps for Testing**
- Contact me over DMs on the Raycast Slack (email steve@pinata.cloud) and I will provide credentials for a test account on Farcaster you can use to test the extension. 
- Once you have the account credentials you will want to install [Warpcast](https://warpcast.com) which is a primary mobile client. With the credentials you can sign in and continue the rest of the testing.
- First run the `Authorize Raycaster` command. This will open a QR code you can scan that will then open an approval screen in Warpcast. It will cost `10 warps` which is an in-app currency the account will already have a balance of. Once its approved the extension will let you know it has saved the credentials
  - **Why this command?** The Farcaster protocol works a bit differently than other more traditional authorizations. Writes must be done with generated keypairs that are approved in a primary client like Warpcast. I tried to make this experience as seamless as possible for users so if there's anyway we can keep it I would greatly appreciate it :) 
- After authorizing you can now run `Send Cast`. If you try to send an image as well then you will get a screen instructing you to add the Pinata credentials. You can at this point put the credentials provided in the Slack DM as well. 

I will make a video later tomorrow to help clarify these steps as well. Thank you for your time! :)

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

What's the difference between this and the similar extensions in the store:

* https://www.raycast.com/artivilla/farcaster by @artivilla 
* https://www.raycast.com/gregskril/searchcaster by @gskril

**Comment by stevedylandev** [comment]
Hey! 👋🏻 This extension specializes in posting to the network; the others are read only extensions

**Comment by stevedylandev** [comment]
@pernielsentikaer Made a few small optimizations that I missed earlier, let me know if you have any other questions! Like I said in the top comment I can send account credentials to test it :)

**Comment by stevedylandev** [comment]
Hey @pernielsentikaer ! Just wanted to ping you again to see if there's any feedback or something we can do to help push this forward :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by stevedylandev** [comment]
Awesome!! Thanks so much! :)

**Pull request merged**
