### PR TITLE
[Obsidian] Use new brand icon

### PR DESCRIPTION
**Pull request by ofalvai**
## Description

Obsidian has [new official icons and brand guidelines](https://obsidian.md/brand). This PR updates the extension icons.

## Screencast

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
Sweet! I do know that earlier in development (which I wasn't a part of) at some point there was a decision to use a non-official icon. I think this change is OK though, but want to point that out. There's a mention of that in the readme. Can you remove that?

There's also another PR open so the version numbers in the changelog would get out of order. I don't think we need version numbers at all though. @pernielsentikaer what do you think about just removing all the version numbers from the changelog?

**Comment by pernielsentikaer** [comment]
There is really no use to have the version tag, I would also just remove it from all entries in the `CHANGELOG`

@ofalvai do you mind checking the merge conflicts?

I don't see a reason not to use the official icon @KevinBatdorf 🔥

**Comment by pernielsentikaer** [comment]
@mikejongbloet do you have a Raycast handle?

**Comment by mikejongbloet** [comment]
Hey - looks like it is @mikejlj

**Pull request merged**
