### PR TITLE
add: redis extension

### PR DESCRIPTION
**Pull request by k8scat**
## Description

- Search Redis Commands and Documents
- Run Redis Command

## Screencast

redis-0

redis-1

redis-2

redis-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by k8scat** [comment]
@pernielsentikaer any comments?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for another contribution 💪

When using the `Run Command` it would be nice with some error handling like dying gracefully 😊

CleanShot 2022-10-06 at 05 41 18@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by k8scat** [comment]
> Hi 👋
> 
> Thanks for another contribution 💪
> 
> When using the `Run Command` it would be nice with some error handling like dying gracefully 😊
> 
> CleanShot 2022-10-06 at 05 41 18@2x
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

fixed

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
