### PR TITLE
Dedup codeowners

### PR DESCRIPTION
**Pull request by LitoMore**
See https://github.com/raycast/extensions/pull/11085#issuecomment-1976355134.

There are two same codeowners in the comment.

It seems the `scripts/generate-code-owners.js` needs to be fixed as well. I will keep an eye on this.

### CODE REVIEW

**Comment by mathieudutour** [comment]
The issue isn't the code owners file, it's https://github.com/raycast/extensions/blob/main/.github/raycast2github.json. There are probably some users that are incorrectly matched

**Comment by LitoMore** [comment]
@mathieudutour Thanks. I will take a look. In the meantime, I think we still need to dedup users in CODEOWNERS.

**Comment by mathieudutour** [comment]
No, it's auto-generated from the file I linked so no point in changing it manually (as mentioned at the top of the file)

**Comment by LitoMore** [comment]
Ah, I see. Closing. I will check that part.

**Comment by mathieudutour** [comment]
FYI this script https://github.com/raycast/extensions/blob/main/scripts/find-wrong-raycast-to-github-mapping.js can be used to find wrong mapping - then it's a tedious process to find the correct one 😓

**Pull request closed without merging**
