### PR TITLE
Add wise-accounts extension

### PR DESCRIPTION
**Pull request by robsel118**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

I don't really know that much about wise, but we should maybe consider merging it into the current [Wise](https://www.raycast.com/hugoliconv/wise-quotes) extension by @HugoLiconV instead and make it a Wise extension so we don't confuse the end users using it?

Does that make sense?

**Comment by robsel118** [comment]
> Hi 👋
> 
> Thanks for your contribution 🔥
> 
> I don't really know that much about wise, but we should maybe consider merging it into the current [Wise](https://www.raycast.com/hugoliconv/wise-quotes) extension by @HugoLiconV instead and make it a Wise extension so we don't confuse the end users using it?
> 
> Does that make sense?

Hi, I did a separate one because the features are not overlapping and his code was not usable for my extension. To me they serve different purpose which is why I made a different one. But lmk your what you think is best

**Comment by pernielsentikaer** [comment]
It would be nice to hear what @HugoLiconV thinks; it would be nice with one unified extension for Wise if possible - I guess most users would gain from all commands?

**Comment by HugoLiconV** [comment]
Hi guys! Honestly, I have no idea what's the best approach. As @robsel118 said, both extensions have different purposes:

**Current Wise Extension**
- Get quotes to see the exchange rate and fees Wise offers.
- Get the current rate between USD and a target currency

**Wise accounts extensions**
- Get profiles
- Get balances
- Get transactions

As you can see the features don't overlap but I don't mind merging the extensions. My only concern is not making any of the extensions harder to use.

**Comment by pernielsentikaer** [comment]
So let's keep them separated if that makes sense, thanks for the chip in @HugoLiconV 🙂

**Review by pernielsentikaer — APPROVED** [review]
✅ Approved

**Pull request merged**
