### PR TITLE
Add Unogs extension

### PR DESCRIPTION
**Pull request by mohitkyadav**
## Description

Add extension for [Unogs](https://unogs.com/)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mohitkyadav** [comment]
Readme also uses the same screenshots as in metadata

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @mohitkyadav 👋 

I followed the README and got the key. However, it does not work for me. I'm in our [Slack](https://raycastcommunity.slack.com/) if you would like us to debug it 😄 

CleanShot 2022-05-11 at 10 11 36@2x

I'm not sure I understand the first step with the title form. Could we also discuss this?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by mohitkyadav** [comment]
@pernielsentikaer thanks for the review I'll look into it.

**Comment by mohitkyadav** [comment]
@pernielsentikaer just updated the PR
- added more descriptive steps in README.md
- not using README.md screenshots from metadata
- updated form title and placeholder so that it's obvious

Please review

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @mohitkyadav 👋 

Thanks for the update. I managed to set it up accordingly 🔥 

Here are a few suggestions for you: 

- When you search for `Batman` and use the `Open in Browser` action, I always end up on a page that doesn't work: e.g., https://www.netflix.com/title/70079583

- Switch Open `Open in Browser` and `Show Details` so cmd+num opens the link.

- Added [ActionPanel](https://developers.raycast.com/api-reference/user-interface/actions#api-reference) icon in the first screen

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by mohitkyadav** [comment]
hey @pernielsentikaer 
- The link does not work because you are not logged into Netflix.
- I think the main purpose of this extension is to discover the region, language, and availability of the shows.
- added action panel icon

**Review by pernielsentikaer — APPROVED** [review]
Hi @mohitkyadav 👋 

Let's get the first version live 🔥 Thanks for your contribution 💯

**Pull request merged**
