### PR TITLE
feat(Autoscroll): add Autoscroll extension

### PR DESCRIPTION
**Pull request by ThatNerdSquared**
## Description

This PR adds an Autoscroll extension to Raycast, allowing users to set an automatic scroll in any direction at a speed of their choice (e.g. "scroll down every 3 seconds").

## Screencast

https://user-images.githubusercontent.com/72814106/171732057-f463a8c6-ca28-4027-9068-27f51ebd0cc1.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by ThatNerdSquared** [comment]
A quick bump for @pernielsentikaer 😄

**Comment by pernielsentikaer** [comment]
Hi @ThatNerdSquared 👋 

Thanks for your contribution 💪 

What is the purpose of this extension 🙂

**Comment by ThatNerdSquared** [comment]
@pernielsentikaer works great for using documents/webpages as teleprompters, or when you want to read something hands-free, etc. Figured I'd submit it since I already had it built and use it regularly, but if it doesn't fit the store feel free to close 🙂

**Comment by pernielsentikaer** [comment]
Hi @ThatNerdSquared 👋 

Yes, I'm not sure yet. I gave the extension a quick spin as a regular user and ended up with a hard reboot - the machine froze, and there was no way to stop it again.

I'm unsure if it's the best extension since it might have unexpected behaviors.

**Comment by ThatNerdSquared** [comment]
@pernielsentikaer fair enough, let me know if you have feedback to make the behaviour more user-friendly, or feel free to close the PR :)

**Comment by pernielsentikaer** [comment]
I think that for now that we have to close it, we're not there yet to provide good enough ways to communicate about this.

If had to reboot, we might run into others with the same provlem. I'll have it on my list for when we're having a better way to communicate this, sorry for the long response time

Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Pull request closed without merging**
