### PR TITLE
Add Logtail extension

### PR DESCRIPTION
**Pull request by Cavallando**
## Description

Hey Raycast team!

Loving Raycast and loving the development with the extension API.

This PR adds a new extension for connecting with Logtail API. Allows for querying using Live Tail Query Language, Saving Queries for later, adding custom log metadata, querying by message found in logs, selecting different application sources.

## Screencast

Screencast highlighting the core features

https://github.com/raycast/extensions/assets/27144805/cf21d629-fdf4-4e9b-8348-7bff8ecb1cc1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @Cavallando 👋 

* Is there a reason why the API key is not added to [Preferences](https://developers.raycast.com/api-reference/preferences) instead?

**Comment by Cavallando** [comment]
Hi @pernielsentikaer, thank you so much for getting back to me! No reason other than I completely missed that section of the API docs 🤦 thank you for the call out I should have some time to correct that today!

**Comment by Cavallando** [comment]
Hey @pernielsentikaer! Addressed the preferences issue you called out and also realized that I had the wrong character case for "Logtail" so I updated that as well, let me know if there are any other issues, happy to address!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
