### PR TITLE
New extension: Holopin

### PR DESCRIPTION
**Pull request by timoransky**
## Description

An extension to see and examine [Holopin](https://holopin.io/) badges and board.

## Screenshots

holopin-1
holopin-3
holopin-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* Don't change navigationTitle in the root, this is mainly used in push commands. You can use a title on the Grid for this (This is the same for both commands)

* It would be cool to show an error when the board doesn't exist, would that be possible?
image

* It would be good with an error toast when it's failing to get the badges, is that possible?
image



I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by timoransky** [comment]
@pernielsentikaer Thank you for your feedback!

I edited the navigationTitles for both commands. 
Regarding the errors, their API is not very robust and it returns the exact same response for the username without stickers and for the incorrect username. Because of that, I added error message on empty API response which says `You either don't have any stickers or the username is incorrect.`. I also added `pop();` afterwards so the user is not left on empty screen. 
Is this good solution or would you recommend something else?

**Comment by pernielsentikaer** [comment]
Hi @timoransky 👋 

I made a few improvements, can you check that I didn't break anything 😊

**Comment by timoransky** [comment]
Hi @pernielsentikaer 
Looks great, didn't realize `Action.OpenInBrowser` already has icon and title predefined. Thanks for help!

**Comment by pernielsentikaer** [comment]
> didn't realize `Action.OpenInBrowser` already has icon and title predefined. Thanks for help!
Not sure why I removed it, it's not an error but yes, it has default values 😊

Sorry for the linting :D

**Comment by timoransky** [comment]
No problem 😊

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
