### PR TITLE
fix: unable to open project has path include space

### PR DESCRIPTION
**Pull request by mingo023**
## Description
fixed: #1661 

## Screencast
https://user-images.githubusercontent.com/38607460/170040755-6cf185dc-3371-42d9-8bd4-71d22db85dff.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by macbookandrew** [comment]
Looks good to me!

**Comment by immint023** [comment]
Hi @pernielsentikaer 

Thank you for your feedback. I'll test on more cases like that.

**Comment by pernielsentikaer** [comment]
Thanks @immint023 - please have #1805 in mind, I'm fixing so deleted files are not in the list

**Comment by immint023** [comment]
> Thanks @immint023 - please have #1805 in mind, I'm fixing so deleted files are not in the list

Okay, I'll update my PR. Thank you!

**Comment by pernielsentikaer** [comment]
#1805 is now merged @immint023; you should be able to continue without any disruptions. Let me know if you need help with the conflicts.

**Comment by pernielsentikaer** [comment]
I'm not sure if we should add any further than this, I think it's okay as is, what do you think @immint023

**Comment by immint023** [comment]
> I'm not sure if we should add any further than this, I think it's okay as is, what do you think @immint023 

Hi @pernielsentikaer If it's okay now, I think we should merge it first. I'll continue with your problem in next PR

**Comment by pernielsentikaer** [comment]
I merged the conflicts, let's get it merged 🔥

**Comment by immint023** [comment]
> Hi @immint023 👋
> 
> It seems to be doing the job pretty good. I tried to open a weird file I had in my temp folder, however, it's not possible to open it (it works fine in code)
> 
> Filename is: `10000000_176925064760892_686739283674657444_n.mp4?_nc_cat=110&ccb=1-7&_nc_sid=985c63&efg=eyJybHIiOjUzNCwicmxhIjoxMzIyLCJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&_nc_ohc=dwdW4DuQo08AX8W9k8a&rl=534&vabr=297&_nc_ht=video.faar2-1.fna&oh=00_AT9YSigks6O`
> 
> Can you think of a way to make it possible, so, like vscode, it's possible to open files like this too?
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Hi @pernielsentikaer, I tried to reproduce the issue with the file name as you mentioned but it works fine on my side. Do you think we should investigate more for this case?

https://user-images.githubusercontent.com/38607460/170496187-d7552cc9-ae2e-47ec-9a1d-a368f560dda7.mov

**Comment by pernielsentikaer** [comment]
It's because we rolled back to a stable version  #1811 since there were too many errors with the new way to retrieve items - like things missing and it only showed 10 items in total

**Pull request merged**
