### PR TITLE
Add covert-color extension

### PR DESCRIPTION
**Pull request by YFAnt**
## Description

hsl, rgb, hexadecimal, convert to each other

## Screencast
image
image

image

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by erics118** [comment]
This seems pretty similar to https://www.raycast.com/lekoarts/polished

**Comment by erics118** [comment]
I'd suggest talking to the extension creator, and maybe to a Raycast team member to decide what to do. I personally think that this could probably be added as a new command in the polished extension.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
I think it makes sense to make it an individual extension at this point since I didn't find an easy match with the `Polished` extension

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
