### PR TITLE
Add merge-pdf extension

### PR DESCRIPTION
**Pull request by valentindebrabandere**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I entered `test.pdf` and it came out as `test.pdf.pdf` 🙂

- Maybe add a preference to set the default behavior and show (Default|Keep|Remove) in the dropdown?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by valentin-deB** [comment]
I have push a new version bases on your advices !

**Comment by pernielsentikaer** [comment]
I can't see the changes yet, did you push it to your branch?

**Comment by valentin-deB** [comment]
Yes is push to the main branch of the repo
https://github.com/valentin-deB/pdf-merger

**Comment by pernielsentikaer** [comment]
You need to push to the branch that you used to make this PR [valentin-deB:ext/merge-pdf](https://github.com/valentin-deB/raycast-extensions/tree/ext/merge-pdf)

**Comment by valentindebrabandere** [comment]
> You need to push to the branch that you used to make this PR [valentin-deB:ext/merge-pdf](https://github.com/valentin-deB/raycast-extensions/tree/ext/merge-pdf)

It's done ! Sorry it's my first contribution, I'm still struggling

**Comment by pernielsentikaer** [comment]
Seems like it's not here yet, you only merged main into your branch :)

**Comment by pernielsentikaer** [comment]
Are you still around @valentindebrabandere

**Comment by pernielsentikaer** [comment]
@valentindebrabandere do you need help with this? 🙂

**Pull request closed without merging**
