### PR TITLE
Fix/swift evolution keys

### PR DESCRIPTION
**Pull request by dehesa**
## Description

The following is a list of the changes applied to the [Swift Evolution](https://www.raycast.com/BProg/swift-evolution) extension by @BProg:
- Migrated to the new Raycast API version.
- Fix a typo in the `package.json`.
- Fix React warnings about list items without keys in `map` loop.
- Fix issue when the Swift version is not specified.
- Used _cached state_ to remember if you use simple or detail list last time a user opened the command.
- Add standard keyboard shortcuts to open in browser and copy proposal URL.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @dehesa 👋 

It works as expected and it's some nice enhancements, @BProg do you want to check it before merging?

**Comment by BProg** [comment]
Let me take a look

**Comment by BProg** [comment]
Works great 🚀  
however I found another place where there are duplicate items: 
```
13:52:08.885 Warning: Encountered two children with the same key, `https://github.com/apple/swift/pull/62652`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

I could fix this separately

**Comment by pernielsentikaer** [comment]
You can use make a suggestion in the code @BProg 🙂

**Comment by dehesa** [comment]
I am not sure whether you can directly push to this branch, but if you can feel free to do it. If not, you can do as @pernielsentikaer suggests and leave me some comments. I will then write them right away.

**Comment by BProg** [comment]
@dehesa following method needs an update

New implementation for `getImplementations` from the `domain.ts` file
```
function getImplementations(proposal: ProposalJson): { title: string; url: string }[] {
  const implementations = proposal.implementation ?? [];
  const initialValue: { title: string; url: string }[] = [];
  return implementations
    .reduce((accumulator, x) => {
      const mapped = {
        title: `${x.repository}#${x.id}`,
        url: `https://github.com/${x.account}/${x.repository}/${x.type}/${x.id}`,
      }
      // Ignore duplications
      if (accumulator.find(impl => impl.url == mapped.url)) {
        return accumulator
      }
      return accumulator.concat(mapped);
    }, initialValue)
}
```

**Comment by dehesa** [comment]
Done! We are done @pernielsentikaer !

By the way, @BProg, it would be amazing to add ⌘+P filter for the status of the proposals (i.e. accepted, returned, implemented, etc.) if you have some time. Bonus points if we can filter for Swift version implementations. Sadly, my TypeScript/React knowledge is not that great.

**Comment by BProg** [comment]
@dehesa The existing search is looking at status and swift version as well. It may not be very intuitive, I do like your suggestion, would look at it 👍🏽 

Existing search functionality:
Screenshot 2024-01-12 at 08 54 58
Screenshot 2024-01-12 at 08 54 48

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
