### PR TITLE
Add surge-controller extension

### PR DESCRIPTION
**Pull request by Jasonzj**
## Description

Control your [Surge](https://nssurge.com/) with Raycast. Support backends switch.

### Features
- [x] Outbound Mode
- [x] Policies
- [x] Events
- [x] Statistics
- [x] Requests
- [x] Capabilities
- [x] Modules
- [x] DNS
- [x] Devices
- [x] Profiles

## Screencast

https://user-images.githubusercontent.com/8412988/164994340-1ef7b084-6e6f-412b-8ecb-3afbfbc367f9.mov

Devices

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @Jasonzj 👋 

I'm not a surge user myself, but how is this compared with the extension [raycast-surge](https://www.raycast.com/ysj151215/raycast-surge)

Could it make sense only to have one and instead contribute to the other one?

**Comment by pernielsentikaer** [comment]
Thanks for the explanation @Jasonzj 🔥 

It could be cool to merge it into one instead of having two doing some of the same features somehow, and another approach (if all features is in yours) could be to make this the superseded version

What do you think @ysj151215 about this, could you give it a peek?

**Comment by ysj151215** [comment]
Thanks for mention. @pernielsentikaer 

It's not necessary for both Raycast & Surge users to have the same named extensions to choose. Furthermore, mine version of Raycast has not been updated for a long time. If @Jasonzj could make another better version, please push it and remove all my codes. I think it's good for all users! 🥳

**Comment by pernielsentikaer** [comment]
Hi @ysj151215 👋 

Thanks for the quick response, have you tried this extension out, or could you try it?

Could be cool to have some feedback 👨‍🎤

**Comment by Jasonzj** [comment]
I think it would be simpler to close this PR and recreate a PR that contributes to [raycast-surge](https://www.raycast.com/ysj151215/raycast-surge)
@pernielsentikaer Wdyt?

**Comment by pernielsentikaer** [comment]
It depens on what's easiest, but things can work actually. I just need to tackle a few things in the backend before we merge it 😄 

This is almost as it should be, right? And if this will superseed the other one?

**Comment by andreaselia** [comment]
Would the current users of the existing extension be automatically updated to this one with the removal of the existing one in favour for this one? @pernielsentikaer

**Comment by pernielsentikaer** [comment]
@andreaselia - Yes but we have to change a few entries in the backend before merging 🙂

**Pull request closed without merging**
