### PR TITLE
Adding Laravel Documentation

### PR DESCRIPTION
**Pull request by aglipanci**
## Description

This [Raycast](https://raycast.com) extension lets you quickly search [Laravel Documentation](https://laravel.com/docs) straight from Raycast.

## Type of change

- New extension

## Screencast

Screenshot 2022-01-04 at 21 33 18

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Is there a reason why #605 / #606 / #607 are trying to achieve the same and are created within one hour of each other? I'm confused here.

**Comment by aglipanci** [comment]
@pernielsentikaer No idea honestly. Not sure what's the right thing to do in this case.

**Comment by pernielsentikaer** [comment]
We should keep one of the three extensions and add the two other authors as contributors. It's quite uncommon (as in never happened before)  that three is contributing three extensions within three hours 😄

Can we use this PR to discuss best approach with all contributors (#606 / @Erth0 - #607 / @indykoning)

An initial question that I have been wondering about for some ting now: 
- Does any one of you know if it's allowed to tap inside Laravel's Algolia search

**Comment by indykoning** [comment]
They haven't explicitly stated wether it is allowed or disallowed.
However we do have the extensions for other popular spotlight replacements using the same method without issues:
Alfred: https://github.com/tillkruss/alfred-laravel-docs/blob/master/laravel.php#L35
Albert: https://github.com/rickwest/albert-laravel-docs/blob/master/__init__.py#L21

**Comment by pernielsentikaer** [comment]
That makes sense, thanks for the clarification. I tried to get in touch with him some time ago, but never received an answer on the topic 😄 

Could you three help find the best base and discuss the best approach from here, I'm having a hard time finding the best alone, I want you three to help me out 🔥

**Comment by Erth0** [comment]
I am happy with all them as they all do the exact same some nice features I would like which I have added are the icon when searching grouping of the actual main links from documentation now the rest I don’t have any issue.

**Comment by indykoning** [comment]
I think they all have something nice in them:
- I like the fact #605 includes the highligted result, but this makes the line too long imo
- I like that #606 has functions to get the title & subtitle
- I like that #607 shows the deepest level as title since this is most often most relevant

I think i'm gonna try and "merge" these things together a little this evening.
To solve:
> the highligted result, but this makes the line too long imo
i think i am going to show the hierarchy tree as subtitle if no "highlighted result" is available and otherwise show that highlighted result

**Comment by indykoning** [comment]
I've updated the PR and updated the screenshot as well with the same "scopes" search query so we can properly compare the two from an end-user perspective.

Am i missing anything that really should be in there?

**Comment by Erth0** [comment]
Looks good but how it looks without searching? 
Because in my PR by default I was showing the links from the documentation sidebar the exact same way it is there.
https://laravel.com/docs/8.x

**Comment by indykoning** [comment]
Currently this also fetches the results from Algolia, thus:

image

Since the menu items are subject to change with every version it may prove to be difficult to maintain previous and future versions of this list. (Though previous versions should stay the same)
I've got a couple ideas of how to handle this:
- Maintain this list for the latest version only and fall back to the Algolia search results on other versions
- Maintain a separate file with it's list per version
Or of course if the current results are fine, keep it as-is

**Comment by Erth0** [comment]
I totally agree with both points. 
I think that having the list per version might be a good idea it's not going to be very difficult to maintain the list for each new version as laravel does it's releases every 1 year now I think used to be every 6 months.

**Comment by pernielsentikaer** [comment]
So @Erth0 @indykoning and @aglipanci — which PR is the base?

**Comment by aglipanci** [comment]
@indykoning mentioned that was going to try and merge everything if I am not mistaken so I supposed we can use that as a base? I am open to help in any way.

**Comment by indykoning** [comment]
If we all agree to the functionality that is in there #607 should now be ready to merge 🎉 
The documentation sidebar menu items showing if nothing is typed has been added

**Comment by Erth0** [comment]
Looks good to me I think is ready for merge 🎉

**Comment by pernielsentikaer** [comment]
Closing in favor of #607

**Pull request closed without merging**
