### PR TITLE
Add 'SolusVM 1 Client' extension

### PR DESCRIPTION
**Pull request by xmok**
## Description

This is a Raycast extension for [SolusVM](https://solusvm.com/) 1 Client level accounts ([Documentation](https://docs.solusvm.com/v1/api/client/Functions.html)). With this extension you can Reboot, Boot, Shutdown Virtual Server + Fetch Virtual Server Status and Information.

## Screencast

https://github.com/raycast/extensions/assets/30526133/ff076e50-3b78-4d70-a3ae-b68feb71d1b6

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 🔥

If the wrong credentials are entered, then the extension crashes, could you handle that gracefully? It looks like a problem in multiple commands

Raycast 2023-12-01 at 07 59 03

**Comment by pernielsentikaer** [comment]
Do you only have one server, as most commands only perform actions on a single server?

**Comment by xmok** [comment]
While it is definitely possible to have multiple servers, as per [API > Client > Overview](https://docs.solusvm.com/v1/api/client/Client%2Boverview.html) and as I mentioned in the **NOTES** of **README.md**, the access is granted "per-VPS" in this version of SolusVM so one would need to have separate API Hash and API Key for each server/VPS. Hence, why most commands can only be performed on a single server.

Hope this clears it up.

**Comment by xmok** [comment]
Hey @pernielsentikaer is there anything else you'd like me to do or is this extension ready to roll?

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
