### PR TITLE
Add cosmic-bookmarks extension

### PR DESCRIPTION
**Pull request by kemiljk**
## Description

A simple extension that allows you to read and write content to your [Cosmic CMS](https://www.cosmicjs.com) Bucket. Designed for saving and viewing Bookmarks, but the code can be modified to do anything with reading/writing Cosmic content.

## Screencast

https://github.com/raycast/extensions/assets/26257029/1e5fabd3-6d11-4437-a961-318c9b0edd47

(Sorry about the quality, needed to get it below 100mb…)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Could you add some [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by kemiljk** [comment]
@pernielsentikaer I've updated to include the metadata image and also made some other improvements to the experience. My understanding of the `Clipboard()` method is that you can also fetch the current active selection without the it being in the clipboard itself (which would improve the Bookmark Saving UX as you can do it by just highlighting the URL – i.e. CMD+L (to highlight URL in browser, CMD+Shift+B (or whatever hotkey is set) to save. 

Is that the case? It doesn't appear to work for me so not sure if I'm misunderstanding the API. I got this from the first line in the docs: _Use the Clipboard APIs to work with text from your clipboard **and current selection.**_ but maybe I'm misreading the intent of **current selection** here.

**Comment by kemiljk** [comment]
> @pernielsentikaer I've updated to include the metadata image and also made some other improvements to the experience. My understanding of the `Clipboard()` method is that you can also fetch the current active selection without the it being in the clipboard itself (which would improve the Bookmark Saving UX as you can do it by just highlighting the URL – i.e. CMD+L (to highlight URL in browser, CMD+Shift+B (or whatever hotkey is set) to save.
> 
> Is that the case? It doesn't appear to work for me so not sure if I'm misunderstanding the API. I got this from the first line in the docs: _Use the Clipboard APIs to work with text from your clipboard **and current selection.**_ but maybe I'm misreading the intent of **current selection** here. `Clipboard.copy()` requires content to be passed (understandably) but I don't see an API for the current selection as an option here, again, might be me missing something here!

Okay, I see it was in the Environment section of the docs... might be good to have an obvious link between the Clipboard API and this because the language confused me, but I got there in the end! Now saves via the current selection instead, which is preferred.

**Review by kemiljk — COMMENTED** [review]
Think all the issues should now be resolved.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
