### PR TITLE
Add repology-search extension

### PR DESCRIPTION
**Pull request by sebdanielsson**
## Description

Add Repology Search extension. It let's you search packages on repology.org.

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The extension crashes when you search for `git`

repology-search 2023-11-14 at 05 34 41

- Show Details action is missing an icon

repology-search 2023-11-14 at 05 35 18

- The initial empty has a weird working since I didn't search yet

repology-search 2023-11-14 at 05 35 54 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by sebdanielsson** [comment]
@pernielsentikaer thanks for the review. These issues should be resolved now! :)

**Comment by pernielsentikaer** [comment]
If I search for `git` and delete the query again, then I'm stuck with the list, maybe we should clear it when query length is back to 2 again?

**Comment by sebdanielsson** [comment]
> If I search for `git` and delete the query again, then I'm stuck with the list, maybe we should clear it when query length is back to 2 again?

Good idea! Please try again. The results should be cleared now. :)

**Comment by pernielsentikaer** [comment]
Works much better! 🔥 

A few small things:

-  Maybe you can use `throttle` and skip the debounce completely. I'm not sure if that makes sense.

-  Is there a reason why it doesn't search from the first character?

**Comment by sebdanielsson** [comment]
Using throttling now!😃 Also added sorting to the repo filter. I added the minimum of two characters to not send unnecessary API calls because no package is shorter than two chars.

**Review by pernielsentikaer — APPROVED** [review]
Hi there! 👋 

Everything looks great to me. Approved! 🔥

Thank you for your cooperation 🚀

**Comment by sebdanielsson** [comment]
> Hi there! 👋
> 
> Everything looks great to me. Approved! 🔥
> 
> Thank you for your cooperation 🚀

Thank you for the guidance. Learned a lot!😃

**Pull request merged**
