### PR TITLE
[Raycast Wallpaper] Detailed Optimisation

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

- Some optimisation of details

## Screencast

raycast-wallpaper-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Hi @pernielsentikaer Maybe change it to 355 for a better display, equal width top and bottom. Can you submit a new Commit for updates?
image

**Comment by pernielsentikaer** [comment]
Was there a reason behind changing the cache key?

**Comment by koinzhang** [comment]
There was no update to the key, just the variable names.

Since the cache component was not fully migrated when it was previously migrated from LocalStorage to Cache, it was also fully migrated to Cache in this update so that it can be unified in the extension. This update has done a lot of code sorting work, only in clear code logic, reduce redundant code

The impact on users is minimal, just resetting the Exclude from Auto Switch data.

**Comment by koinzhang** [comment]
@pernielsentikaer Is there anything stopping this PR from being reviewed?

**Comment by pernielsentikaer** [comment]
I'm actually doing a final check now. Do you think it makes sense for `Next` in the `preview` view to go back to the first item when it reaches the end? Right now, it just programmatically stops.

**Comment by koinzhang** [comment]
Hi @pernielsentikaer I optimized the preview logic
1. You can now cycle the pictures
2. When exiting from the preview, the current selected image will be positioned

**Comment by koinzhang** [comment]
Optimize **Exclude From Auto Switch** shortcut keys to **Ctrl+X**

**Comment by pernielsentikaer** [comment]
That's just awesome, I like it a lot 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
