### PR TITLE
Add array-this extension

### PR DESCRIPTION
**Pull request by matheus-depaula**
## Description

An extension to format list of items into an array.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mil3na — COMMENTED** [review]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

Since this is a very specific extension with only one functionality, have you considered adding this as a command to another extension like these?
https://www.raycast.com/devutils/devutils/commands
https://www.raycast.com/mblode/cyberchef/commands

**Comment by matheus-depaula** [comment]
Hey Milena!

I want to add new commands at some point. I sent only this first feature since it's what meets my needs today.
Also, I use an extension called [Format JSON](https://www.raycast.com/destiner/json-format) and I kinda followed it's approach for UI related and stuff. This extension has features that exists in both you mentioned, but it's still standalone.

That's why I didn't considered it :)

**Comment by mil3na** [comment]
I understand, just want make sure if there is a justification for it to be a standalone instead of incrementing an existing extension. Do you plan to add more features to it? Like what?

**Comment by matheus-depaula** [comment]
To be honest I'm still figuring out. It's something I use in my daily work routine, so new demands always come.
In first instance, I was wondering about let it receive the input through upload, but I'm not sure if it's possible reading the docs... As I say, I'm still thinking on the next commands besides this one I mentioned.

**Comment by koinzhang** [comment]
https://www.raycast.com/koinzhang/text-shortcuts
Try this extension to customise your text processing tools

**Review by mil3na — APPROVED** [review]
It's okay. I think we can have it as-is in the Store.
LGTM.

**Pull request merged**
