### PR TITLE
Update speedcubing extension

### PR DESCRIPTION
**Pull request by Menchynskyi**
## Description

Added OLL algorithms command.

## Screencast

image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you want to be added as a contributor to the extension? If so, please add your Raycast handle in `package.json` in `contributors: []`

**Comment by Menchynskyi** [comment]
@pernielsentikaer
This is my second contribution to this extension, so I should already be listed 👍

**Comment by pernielsentikaer** [comment]
You're right, I'm blind 🧑‍🦯

**Review by samuelkraft — APPROVED** [review]
Loove this 🙌 
Thanks for contributing, looks good to me

**Pull request merged**
