### PR TITLE
update: search-mdn

### PR DESCRIPTION
**Pull request by k8scat**
## Description

- Support `Read Document` from GitHub
- Optimize locales with `List.Dropdown`
- Add extension categories
- Fix locale `zh-CN` to `zn-cn`
- Upgrade @raycast/api to 1.40.1
- Remove debug log

## Screencast

search-mdn 2022-10-03 at 06 03 44

search-mdn 2022-10-03 at 06 05 46

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by k8scat** [comment]
image

**Comment by pernielsentikaer** [comment]
Can you have a look @krzysztofzuraw 😊

**Comment by k8scat** [comment]
This PR has some other changes in progress

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
