### PR TITLE
Add gpt-snippets extension

### PR DESCRIPTION
**Pull request by olegkron**
## Description
Allows to create custom GPT snippets and run them on clipboard text.

gpt-snippets1
gpt-snippets2
gpt-snippets3
gpt-snippets4
gpt-snippets5
gpt-snippets6

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by olegkron** [comment]
Hi Raycast team. LMK if I need to fix TS errors or we can proceed with them. Thanks!

**Comment by MarshalX** [comment]
That’s cool! Can it be part of the ChatGPT extension? It also allows creating items with an initial prompt. These actions fit perfectly into the existing extension, in my opinion

The extension: https://www.raycast.com/abielzulio/chatgpt

**Comment by olegkron** [comment]
> That’s cool! Can it be part of the ChatGPT extension? It also allows creating items with an initial prompt. These actions fit perfectly into the existing extension, in my opinion
> 
> The extension: https://www.raycast.com/abielzulio/chatgpt

Hey! That could also work, as long as the custom action functionality is there. Are you the maintainer of the ChatGPT extension?

**Comment by MarshalX** [comment]
> Are you the maintainer of the ChatGPT extension?

I am not but I gonna summon @pernielsentikaer here

**Comment by pernielsentikaer** [comment]
@abielzulio @bxb100 what do you think? 

I think it's better to enhance the current instead of adding yet another extension 🙂

**Comment by bxb100** [comment]
Nice work @olegkron , I agree with @pernielsentikaer @MarshalX 

and the ChatGPT extension's "Summarize website" command can be incorporated into your idea

**Comment by bxb100** [comment]
@olegkron After some work, it works like this

SCR-20240523-qefs

and can use Hotkey to quickly ask in a separate command.

SCR-20240523-qgif

the code lives in https://github.com/bxb100/chatgpt, you may want to see it.

**Comment by olegkron** [comment]
@bxb100 Looks great! 
Is it on the way to the Raycast store?

**Comment by bxb100** [comment]
> @bxb100 Looks great! Is it on the way to the Raycast store?

No.. this repo currently meets my own need, it's slightly different from the store version, and the code is not tested, so you can pick some logic/code from it, and welcome @ me to code review

**Pull request closed without merging**
