### PR TITLE
Add SM.MS extension

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

SM.MS image hosting service to upload and share images.

**⚠️Warning:**
The size of uploaded images is limited to less than 5M.

**How to get API secret token?**

- Register an account on [SM.MS](https://sm.ms),
- After entering the home page, click on **User** in the upper right corner and select **Dashboard**,
- Click on the **API Token** in the left sidebar,
- Click on the blue **Generate Secret Token** button,
- Copy the generated _Secret Token_, back to this extension and fill in the **API secret token** form.

## Screencast

Metadata-1

Metadata-2

Metadata-3

Metadata-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @koinzhang 👋 

I have tried for a few days now to create a user, and no matter how much I change the password, make a new user, or try to log in, it's not possible. 

When creating a new user I get to this screen:
CleanShot 2022-05-31 at 12 57 29@2x

Do you have a token I can use to test, or can you create a user for me? I give up 😄

**Comment by pernielsentikaer** [comment]
Hi @koinzhang 👋 

I gave it a new spin and have some more feedback for you 😄 

**Upload Image**
- After uploading an image I think it should clear the text field?
- Maybe add the finder view so we don't need to drag the path, also done in other of your scripts and also here:
CleanShot 2022-06-01 at 15 25 24@2x

**Search Images**
- I was not able to delete it again?
CleanShot 2022-06-01 at 15 28 27@2x

**Delete Image**
- I was not able to delete hash
CleanShot 2022-06-01 at 15 30 38@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by koinzhang** [comment]
Hi @pernielsentikaer. Thanks for your review.
> After uploading an image I think it should clear the text field?

Good idea, I'll make the changes.

> Maybe add the finder view so we don't need to drag the path, also done in other of your scripts and also here:

This feature already exists, use the shortcut Shift+cmd+enter to bring up.

> I was not able to delete hash

I am also experiencing this problem now, I will investigate.

**Comment by pernielsentikaer** [comment]
Hi @koinzhang 👋 

Thanks for the corrections and the new key 💯 

When I try to upload anything else than an image I get this error with a success style, is that correct?
image

I'm still not able to delete images, also here is the success toast misplaced 😄 
CleanShot 2022-06-01 at 20 49 51@2x

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by koinzhang** [comment]
Hi @pernielsentikaer 

- I have fixed the Toast style error issue.

- Added a temporary history display for Upload Images and Delete Images

As for the bug you encountered where you couldn't delete images, I am now able to delete images normally, perhaps because of the API Token that prevented you from deleting images.

**Review by pernielsentikaer — APPROVED** [review]
Working a lot better now, thanks @koinzhang 🔥

**Pull request merged**
