### PR TITLE
[worktrees] Fix findRepos with fd v9

### PR DESCRIPTION
**Pull request by canac**
## Description

As of version 9, `fd` now hides `.git` directories by default ([release notes](https://github.com/sharkdp/fd/releases)). This fixes the `fd` command to still be able to find `.git` directories.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
In the latest version of the API (1.64.0) we changed the behavoir of `appPicker` a bit:

> Types generation: Fixed the type of a required appPicker preference (even if it is required, the app might be undefined because it is missing).

Could you look into this @canac

**Comment by canac** [comment]
@pernielsentikaer That makes sense. I was wondering why that check was failing.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by canac** [comment]
@pernielsentikaer Thanks for the assist with the config and formatting updates! 🙏

**Pull request merged**
