### PR TITLE
Add 8-divide extension

### PR DESCRIPTION
**Pull request by pakliem**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
In what use case would a user need this extension 🙂

**Comment by pakliem** [comment]
> In what use case would a user need this extension 🙂

Rounding up or down to reach a multiple of 8 after blocking out a design in certain workflows (:

https://github.com/user-attachments/assets/d33c2635-fa47-4e60-b132-96ab16138848

**Review by pernielsentikaer — COMMENTED** [review]
Could you add a few lines in the README about it, maybe? That would help others who are as confused as I was :)

**Comment by pakliem** [comment]
> Could you add a few lines in the README about it, maybe? That would help others who are as confused as I was :)

added one 🧢

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
