### PR TITLE
Add hide-desktop-icons extension

### PR DESCRIPTION
**Pull request by MatteoGauthier**
## Description

Small extensions to show, hide and toggle desktop icons quickly using this beautiful App !

## Screencast

https://github.com/raycast/extensions/assets/32040951/a65c677b-e4c4-4403-89d8-7042b9f0e952

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by erics118** [comment]
There already is an extension with the same features.
See
https://www.raycast.com/Haojen/toggle-desktop-visibility
https://github.com/raycast/extensions/tree/main/extensions/toggle-desktop-visibility

**Comment by pernielsentikaer** [comment]
Hi @MatteoGauthier 🔥 

Thanks for your contribution 🚀 

This feature is already included in [this extenson](https://www.raycast.com/Haojen/toggle-desktop-visibility) and will at some point be a part of Raycast too - we can make the current extension more findable if that makes sense?

**Comment by MatteoGauthier** [comment]
Hey @pernielsentikaer, I understand this will be more simple for users 👍 

Did you plan to add an option to toggle dekstop icons visibility in the menu bar ? (ref https://github.com/raycast/extensions/pull/9118#issuecomment-1796673478)

**Comment by pernielsentikaer** [comment]
I think it should be possible to add the requested feature in https://www.raycast.com/Haojen/toggle-desktop-visibility - the two extensions are quite the same as I see it.

**Pull request closed without merging**
