### PR TITLE
[Transmission] fix: handle error state

### PR DESCRIPTION
**Pull request by FezVrasta**
## Description

the dark-mode script can sometimes error with:

image

This PR handles this case.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by mathieudutour** [comment]
How do you feel about using a gray that works on both themes so you don't have to use a binary to get the current theme?

**Comment by FezVrasta** [comment]
I couldn't find something that looked good for both themes, open to suggestions though.

**Comment by FezVrasta** [comment]
I updated it to use that color, thanks.

**Review by mathieudutour — APPROVED** [review]
Thanks!

**Pull request merged**
