### PR TITLE
[Image Modification] Add Apply Image Filter command

### PR DESCRIPTION
**Pull request by SKaplanOfficial**
## Description

This update to the Image Modification extension adds one new command: Apply Image Filter. You can select from a variety of filters to apply to one or more selected images files. Many of the filters available via CIFilter are supported, except those that require additional parameters, and currently distortions and generators are not supported (but might be in the future). The image processing is accomplished via AppleScriptObjC.

## Screencast

[ImageFilters720.webm](https://user-images.githubusercontent.com/7865925/227040103-5aad67e8-3d70-4471-8451-5d9fdb2cf757.webm)

[YouTube Video](https://www.youtube.com/watch?v=dsHcL69OJ-g)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Something weird is going on when using the filters, I tried a few filters and every one of them is doing the same, check before and after:

### Before
raindrop-io 2023-03-22 at 14 10 08 2

### After
raindrop-io 2023-03-22 at 14 10 08

Can you look into this?

**Comment by SKaplanOfficial** [comment]
@pernielsentikaer Hmm, I'm not able to recreate this, or I'm misunderstanding. Are all of the filters applying the same effect? I'm not sure why that would be happening. Can you tell me which filters specifically you tested?

**Comment by pernielsentikaer** [comment]
Happens with all images, look like something with retina? See 3 images with filters and the reference image i used





### reference
reference

**Comment by SKaplanOfficial** [comment]
@pernielsentikaer Can you give it another try? I've changed the way the size of the output image is determined.

**Pull request merged**
