### PR TITLE
New extension: Mantine documentation

### PR DESCRIPTION
**Pull request by EmilMalanczak**
## Description

Documentation for [Mantine UI](https://mantine.dev/) inside Raycast, browse simplified documentation or open particular pages directly by the links to the pages

## Screencast
mantine-01
mantine-02
mantine-03
mantine-04
mantine-05

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @EmilMalanczak 👋 

Thanks for your contribution 🔥 

I think we could make the UX better by doing it with sections instead, a bit like this:



Do you think that could be a way and are you able to look into this?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by EmilMalanczak** [comment]
Thanks for your feedback @pernielsentikaer , I think that's a great idea 👏 . 
To clarify - that's a change for the first screen - `Core`, `Hooks` etc. to make it as Section list instead of current way?

**Comment by pernielsentikaer** [comment]
Yes, I would add a second command for changelog and reverse the order (to have the newest on top)

The rest would be one list with sections, so it's possible to search all content without pushing around 😄 

Let me know if you need help 🔥

**Comment by EmilMalanczak** [comment]
I've changed the code based on your review @pernielsentikaer, basically, 1st and 2nd steps now are connected and that's a definitely a good change

**Review by pernielsentikaer — APPROVED** [review]
Hi @EmilMalanczak 👋 

I think we're good to go here 🔥

**Comment by pernielsentikaer** [comment]
One more thing @EmilMalanczak, could we move the folder docs out from `assets` and to `src`

**Comment by EmilMalanczak** [comment]
Sure, I'll try to push that change today afternoon

**Comment by EmilMalanczak** [comment]
@pernielsentikaer how can I do that? I've got into a problem

currently the `__dirname` shows me `/Users/misit/.config/raycast/extensions/mantine-documentation` but after opening that I can see only these files:

image

At the moment I'm loading these files inside `useEffect` so that might be the issue but I'm aiming to load these files directly from GitHub so that approach is temporary anyway

**Review by pernielsentikaer — APPROVED** [review]
You're right, let's keep it as it 😄 Let's get it merged 🚀

**Comment by EmilMalanczak** [comment]
Thanks! 🔥

**Pull request merged**
