### PR TITLE
feat(deepcast): add missing features to the index command

### LINKED ISSUE #9070: [Deepcast] Copy to clipboard not working
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

The extension has stopped copying the translated string into the clipboard, even though the On Translation Action is set to Copy to Clipboard.

### Steps To Reproduce

1. Open Deepcast
2. Translate a string
3. Try to paste into other application or view clipboard in Raycast

### Current Behaviour

The translation isn't copied to the clipboard.

### Expected Behaviour

The translation should be copied to the clipboard when set to do that in the extension settings.

### LINKED ISSUE #9077: [Deepcast] Selected text as source doesn't seem to work
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

Hey,

Even if I choose `Selected` as the Preferred Source in the extension settings, selected text doesn't appear in Deepcast.
Please note that it's working well with other Raycast Extensions I use with this setting (WordReference, Quicklinks etc.).

Thanks a lot for the support!

### Steps To Reproduce

1. Select text
2. Trigger Deepcast using a hotkey

### Current Behaviour

No text appears in the extension.

### Expected Behaviour

Selected text shall appear in the extension.

### LINKED ISSUE #9136: [Deepcast] ...Transliterated translation for special characters
### Extension

https://www.raycast.com/mooxl/deepcast

### Description

I'm adding reminder for @erics118 about transliterated text for translation. As we spoke I would love to be able to copy Russian transliterated text, for example 
English: My name is Rihards
Russian: Меня зовут Рихардс
Transliterated Russian: Menya zovut rihards

### Who will benefit from this feature?

Everyone who is translating something to Russian language and using transliterated version for something, e.g. for URLs

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by erics118**
## Description

Fix #9077
Fix #9070
Fix #9136

for the `Translate` command:
- support using selected text
- added a shortcut to copy translation (#9070)
- added shortcut to paste translation to frontmost app
- added support for fallback text

for all commands:
- added option to transliterate (romanize) the translation (#9136)

## Screencast

todo

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you need with the CI errors @erics118 🙂

**Comment by erics118** [comment]
> Do you need with the CI errors @erics118 🙂

No, all good. I know the fix. I just kinda forgot about fixing the CI

**Comment by pernielsentikaer** [comment]
@mooxl do you mind checking this 🙂

**Comment by MonsterDeveloper** [comment]
Hi! Any ETA on this one? The critical part of `deepcast` isn't working.

**Review by pernielsentikaer — APPROVED** [review]
Let's merge it it 🔥

Thanks once again @erics118

**Comment by pernielsentikaer** [comment]
@MonsterDeveloper should be in now, run `Check for extension update` or wait a few hours 🙂

**Pull request merged**
