### PR TITLE
Add Lipsum extension

### PR DESCRIPTION
**Pull request by mhogeveen**
## Description

Add Lipsum extension which generates a specified amount of Lorem Ipsum text.

## Type of change

- New extension

## Screencast

screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @mhogeveen 👋 

Sorry for the long waiting time processing this.

Are you aware of there is already another generator doing almost what this is doing: https://www.raycast.com/AntonNiklasson/lorem-ipsum

I can see that yours differs because it's possible to select how much, but besides that it's almost identically, the approach could be opening a PR (or ask the contributor) to the existing extension if it could be added in the current, otherwise we end up with 2 identically extensions.

**Comment by mhogeveen** [comment]
Hi @pernielsentikaer ,

I was aware of the current version of the Lorem Ipsum extension, but because of the different functionality I decided to build my own version. I will try to contact the contributor of the current extension of open a PR to add the functionality myself.

**Comment by pernielsentikaer** [comment]
Hi @mhogeveen 👋 

Did you get in touch with @AntonNiklasson yet in order to add extra functionality to the current extension?

**Comment by mhogeveen** [comment]
Hi @pernielsentikaer,

I haven't gotten around to it yet, but it seems @AntonNiklasson has seen your message already.

@AntonNiklasson would you be willing to update you extension with the functionality that I implemented in this one?

**Comment by AntonNiklasson** [comment]
I'm sure we can figure something out to not have two extensions this similar. Could you explain just exactly what's missing from the one I built?

**Comment by mhogeveen** [comment]
@AntonNiklasson I added a couple of features:
- The ability to generate words
- Default is to generate 1 word, sentence or paragraph, but the user can type in a number and the generated content will be x words, sentences or paragraphs

These features add a bit more flexibility to extension.

afbeelding
afbeelding

**Comment by pernielsentikaer** [comment]
@AntonNiklasson are you still willing to help out with some improvements?

**Comment by AntonNiklasson** [comment]
Yes, I would like to spend some time here! I might be able to in the coming week or so.

**Comment by mattisssa** [comment]
Hey @mhogeveen! What is the status of this PR? It seems like it's been here for a long time unfinished.
Shall we probably close this one and once you're ready open another PR?

**Comment by mhogeveen** [comment]
@mattisssa I have leaved this PR open as a reminder for @AntonNiklasson to update the Lorem Ipsum extension. It doesn't seem likely that will happen, so I will close this PR.

**Comment by AntonNiklasson** [comment]
Sorry for getting back to this. I've been swamped both at work and in life.

**Comment by pernielsentikaer** [comment]
No rush or pressure @AntonNiklasson, do you still like to add some of the suggestions?

**Comment by AntonNiklasson** [comment]
Yes, it would be fun to get back to it.

**Pull request closed without merging**
