### PR TITLE
[Year In Progress] (Show|Hide) in Command Subtitle

### PR DESCRIPTION
**Pull request by akshykhade**
## Description

Added action "Show as Command" to dynamically modify progress bar on raycast command.

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
- Would it make sense to call it "(Show|Hide) in Command Subtitle" instead?
- Maybe change the red color for the selected to using a tag instead?

Raycast25042024-ksnG52E0 png@2x

- Could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

**Comment by akshykhade** [comment]
Hi @pernielsentikaer,
Thanks for review.

**Comment by pernielsentikaer** [comment]
I believe you need to set the year selected; if you enter the extension without setting it, the first time I open it, there are no selected items.

year-in-progress 2024-04-26 at 10 51 03

**Comment by helloteam-akshykhade** [comment]
RIght @pernielsentikaer.
Thanks

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
