### PR TITLE
Add oktasearch extension

### PR DESCRIPTION
**Pull request by zachmian**
## Description
This extension is intended to help Okta admins working in organizations to search through users and groups in Okta and instantly open the profile of selected item. 

## Screencast
oktasearch-1
oktasearch-2
oktasearch-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

At the moment, I do not have access to okta. Do you know if there is a way of getting a test user or can you provide a video of your extension working? I have no way to test otherwise.

**Comment by zachmian** [comment]
Hello @mil3na,
I think I can provide you with some video. Can I share it with you privately (with Raycast's Slack maybe?) or should I upload it here?

**Comment by mil3na** [comment]
Feel free to send it via slack or email milena@raycast.com 
whichever you prefer :) I understand that sharing here is not the best option.

**Review by mil3na — APPROVED** [review]
LGTM

**Pull request merged**
