### PR TITLE
Add youtube-subscriber-celebrator extension

### PR DESCRIPTION
**Pull request by imaNNeo**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @imaNNeo 👋 

Even though I like the idea, it might not be the best to publish.

When running confetti, it steals focus from the fields you're currently working in, which will be really annoying for the user.

I tested it by running `for i in {1..5}; do open raycast://confetti && sleep 2; done` in the terminal

**Comment by imaNNeo** [comment]
Hi there,
Yes, you're right, it distracts you if you get more than an amount per day,
This config (checking every minute and showing confetti every time the subscribers increase) works well for me because I just started my YouTube channel and have no more than 3 subscribers per day.
But I agree it can distract people who have famous YouTube channels

What if I add some configs for `checkInterval` and `thresholdCount`?
In this case, for example you can set it to check every one hour with the threshold of 20 subscribers

**Comment by pernielsentikaer** [comment]
That sounds like a plan. What about changing the name to "YouTube Subscriber Count" and adding the required preferences for the confetti and the threshold?

Then, initially, when people install it, they can select their preferences.

**Comment by imaNNeo** [comment]
Sounds good, I will close this PR and will create a new one with the better name
`YouTube Subscriber Count`

**Pull request closed without merging**
