### PR TITLE
[Apple Notes] Add new actions & Fix Bugs

### LINKED ISSUE #5469: [Apple Notes] Error trying to open an Apple Note
### Extension

https://raycast.com/tumtum/apple-notes

### Description

I can search my Apple Notes and the titles come up, but when I select one I get an error
Screen Shot 2023-03-20 at 10 52 23 AM

### Steps To Reproduce

Mac OS 10.15.7
Raycast version 1.44.0

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### LINKED ISSUE #5658: [Apple Notes] Action to create a deep link to open a specific note in Notes
### Extension

https://www.raycast.com/tumtum/apple-notes

### Description

I really appreciate this extension, and use it quite a bit to get to my notes. One thing that would make it even better would be an action to be able to create a deep link ~~similar to the one that can already be created to search for notes:~~

~~raycast://extensions/tumtum/apple-notes/index?fallbackText=Recipe~~

~~The link searches for all notes containing recipes. Nice!~~

~~Additionally, I would now want to be able to link to notes directly and open them. Therefore, an idea:~~

Could we create a new action in the note search results to immediately create a deep link to open the note in Notes?

~~raycast://extensions/tumtum/apple-notes/open?fallbackText=Best%20Chocolate%20Chip%20Cookie%20Recipe~~

notes://showNote?identifier=UUID

EDIT: Changed to Apple notes URL scheme. See comments below, for an explanation, why the Raycast URL scheme was suggested at first.

### Who will benefit from this feature?

All users who would want to link to notes from other applications (writing tools, task managers etc.).

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SKaplanOfficial**
## Description

This update to the Apple Notes extension adds four new actions: Copy Note URL, Copy Mobile Note URL, Delete Note, and Restore To Notes Folder. The two URL actions copy to the clipboard a `notes://` or `mobilenotes://` deeplink, respectively. This update also moves Recently Deleted notes to their own list section below other notes.

I've also fixed some bugs by adjusting the AppleScript to open notes and relying on the SQL database alone to query for notes instead of getting them via AppleScript.

## Issues Resolved
Resolves #5469
Resolves #5658 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you mind checking this @StevenRCE0 😊

**Comment by StevenRCE0** [comment]
> Do you mind checking this @StevenRCE0 😊

It works as expected, apart from a long existed issue: 

```
Error: database disk image is malformed
    at c.handleError (/Users/{user}/.config/raycast/extensions/apple-notes/index.js:2355:19)
    at a.step (/Users/{user}/.config/raycast/extensions/apple-notes/index.js:2082:31)
    at /Users/{user}/.config/raycast/extensions/apple-notes/index.js:4486:26
```


Typically it'll disappear after a while. I don't really have clues of what's going on.

**Comment by SKaplanOfficial** [comment]
@StevenRCE0 I can look into it and make a separate PR if I find a solution. I don't really know why that's happening either...

**Comment by StevenRCE0** [comment]
> I don't really know why that's happening either...

Okay...

I'm happy with this PR, maybe also assign keyboard shortcuts to these copy actions?

**Comment by StevenRCE0** [comment]
@pernielsentikaer I think it's ready to be merged 😊

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by neilpatel121** [comment]
I've identified the bug in the Notes extension. It seems to stem from a particular type of note. Specifically, any Apple note that is accompanied by a file attachment (not an image) appears to trigger the issue. Once I removed the file attachment from the problematic note, I was able to successfully operate the extension. This issue occurred while utilizing image effects.

**Pull request merged**
