### PR TITLE
Create `Youtube Downloader` extension

### PR DESCRIPTION
**Pull request by vimtor**
## Description

This extension attempts to download YouTube videos from Raycast. It has been attempted twice (#138 and #173), but many issues arose. I think I've solved them all, but before adding new features, I want to make sure my tricks comply with the Raycast team.

For it to work I had to do 2 things:
1. Require that the user install `ffmpeg` using `brew install ffmpeg`. Maybe this could be installed by the extension but I will need some guidance on how to properly do this.
2. Use [`patch-package`](https://www.npmjs.com/package/patch-package) to instruct [`fluent-ffmpeg`](https://www.npmjs.com/package/fluent-ffmpeg) to use the correct library. This happened because (don't ask me why) the package was requesting a `lib-cov` library instead of `lib` because the `FLUENTFFMPEG_COV` is set to `true` on build and development.

## Screencast

https://user-images.githubusercontent.com/36263538/228520241-08c854bb-706a-4775-ad18-b2bbe45dd7a6.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by sxn** [comment]
hey @vimtor – nice idea! Regarding your questions:

> Require that the user install `ffmpeg` using `brew install ffmpeg`. Maybe this could be installed by the extension but I will need some guidance on how to properly do this.

You could check if the user has ffmpeg, and if they don't:
1. if they have brew installed, show the user the command, and maybe offer to install it for them
2. if they don't have brew installed, point them to installation instructions for ffmpeg (go to http://www.ffmpeg.org/download.html etc)

Would that work? 🤔 

> Use [patch-package](https://www.npmjs.com/package/patch-package) to instruct [fluent-ffmpeg](https://www.npmjs.com/package/fluent-ffmpeg) to use the correct library. This happened because (don't ask me why) the package was requesting a lib-cov library instead of lib because the FLUENTFFMPEG_COV is set to true on build and development.

It sounds weird that `FLUENTFFMPEG_COV` would be set during build. Do you know who's setting it? Ideally we wouldn't need to patch the library 😬 if there's absolutely no way to go around it, we could live with it as long as the library version is pinned in `package.json`.

**Comment by vimtor** [comment]
hey @sxn (cool username btw)

To avoid complicating the extension code, I added the necessary documentation for installing `ffmpeg` and an appropriate error message if it is not installed.

Regarding `patch-package`, I'm not sure what is setting the environment variable; it could be something related to the operating system set by `ffmpeg`. I pinned the dependency as you suggested.

If you think it is ready we can publish the extension and see how to improve it in future versions :)

**Comment by sxn** [comment]
hey @vimtor – thanks for the change, and sorry I'm only getting back to this PR now 😅
Regarding the change – I actually meant you should show somewhere inside the extension, something like [what this extension does](https://github.com/raycast/extensions/blob/revert-masscode-paste-on-enter/extensions/displayplacer/src/components/not-installed.tsx#L4-L24). That way the extension would acknowledge some prerequisite is missing, and offer to help the user fix the issue. 😺

**Comment by vimtor** [comment]
Thanks for the feedback @sxn! I added the code you suggested and tried it to check it is working. `ffmpeg` is quite heavy so it takes up 2 minutes to complete the installation. I added some notes regarding that.

**Comment by 0xOsprey** [comment]
Looking forward to this one as I'm currently using a hacked together python script via https://github.com/ytdl-org/youtube-dl

**Comment by vimtor** [comment]
> This issue has been automatically closed due to inactivity.
> 
> Feel free to comment in the thread when you're ready to continue working on it 🙂
> 
> You can also catch us in [Slack](https://www.raycast.com/community) if you want to discuss this.

😢

**Comment by sxn** [comment]
hey @vimtor, very sorry that it took so long to get back 🥲 I finally managed to have a go and it works great! 🎉 :shipit:

**Pull request merged**
