### PR TITLE
Update openai-gpt extension

### PR DESCRIPTION
**Pull request by EvilMouth**
## Description

Add support for the basepath in the OpenAI configuration.

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @EvilMouth 👋 

Why would that be necessary? I'm not that much into this so maybe we can add something about it in the `README` so end users can get some more knowledge too 🙂

Also, could you provide a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry

**Comment by EvilMouth** [comment]
@pernielsentikaer 
yes, because some regions are unable to directly connect to the OpenAI API, with the base path configuration, we can proxy the requests through an intermediary server.

**Comment by pernielsentikaer** [comment]
Thanks for the explanation @EvilMouth - do you mind adding a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry too?

@simicvm do you mind checking this?

**Review by simicvm — APPROVED** [review]
Looks good and works ok. Tested with local Mistral model.

**Pull request merged**
