### PR TITLE
[New Extension] added Package Tracker extension

### PR DESCRIPTION
**Pull request by cojmeister**
## Description

Track your packages and parcels in raycast with the 17Track API

## Screencast
package-tracker-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋

Does this require an API Key from 17track or business.pkge.net

**Comment by cojmeister** [comment]
Just solved it!

**Comment by cojmeister** [comment]
@pernielsentikaer any more comments, or things to change in the code?

**Comment by pernielsentikaer** [comment]
README still says 17track - is it only business.pkge.net now?

**Comment by cojmeister** [comment]
> README still says 17track - is it only business.pkge.net now?

I'm sorry @pernielsentikaer , I've pushed to the wrong repo. corrected it now!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
