### PR TITLE
Fix NBA viewer starting season date for Standings view

### PR DESCRIPTION
**Pull request by degouville**
## Description

Summary of changes:

- Add a rule to set the year according to the start of the new NBA season, traditionally in October.

## Screencast

| Before | After |
| ------- | ------- |
|  |  |
|  |  |

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by degouville** [comment]
cc @michaelli1324 @AbhinavPalacharla  @djpowers @pernielsentikaer 

Good 2024 NBA season everyone !

**Review by djpowers — APPROVED** [review]
Makes sense to me

(Go Celtics! ☘️)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by degouville** [comment]
Thanks @pernielsentikaer 🚀

**Pull request merged**
