### PR TITLE
Add thesaurus extension

### PR DESCRIPTION
**Pull request by ABukSwienty**
## Description

The thesaurus extension is a simple web-scraper that allows users to lookup words on Merriam-Webster's thesaurus. Displays a list of synonyms and antonyms. Some basic copy/past functionality as well.

## Screencast

https://user-images.githubusercontent.com/88147569/224560641-53202d95-15f1-4bd9-ba20-ddba512d7bff.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaslombart — COMMENTED** [review]
Congrats on your extension! I've reviewed it and have some feedback to share:

- The extension uses web scrapping which doesn't seem to be compliant with the terms of the website that's used. Could you add the following warning to the `README.md` file: `Warning: This extension is not compliant with the Terms of Service of [service name]. Use at your own risk.` 
- The `command-icon.png` file doesn't seem to be used so you can remove it.
- The command icon isn't really visible in the root search. Maybe you can quickly design one using the [Icon Maker](https://icon.ray.so)?
- There are no shortcuts for opening a word in the browser. Could you add one so that keyword users have a way of performing the action? `⌘` + `O` is a common one for this type of action.
- Some tags are not really visible in dark mode in the detail metadata. Could you either find a color that works well in both modes? Otherwise, you can use the [`adjustContrast` prop](https://developers.raycast.com/api-reference/user-interface/colors#color.dynamic).

Let me know when the extension is ready to review again 💪

**Comment by ABukSwienty** [comment]
Hi @thomaslombart. I've amended the above. But I'm unsure of how to merge the changes from my repo into the branch. Please advice.

Cheers

**Comment by thomaslombart** [comment]
@ABukSwienty Answered your mail 😊

**Comment by ABukSwienty** [comment]
@thomaslombart thanks! I've pushed the changes :)

**Review by thomaslombart — APPROVED** [review]
Let's ship it! 🚢

**Pull request merged**
