### PR TITLE
[New Extension] Apple Mail

### PR DESCRIPTION
**Pull request by ikupenov**
## Description

Builds on top of https://github.com/raycast/extensions/pull/4080, props to @yug2005 for building the foundation. This PR fixes issues found in the original one and improves performance and UX.

- Go through any mailbox for any account
- See important mail quickly
- See recent unread messages
- Read messages in Raycast or open them in mail app
- Reply, reply all, forward or redirect messages
- Compose a new message
- For new messages, you can specify the following fields:
  - Choose the account from which to send the message
  - Choose the to, cc, and bcc recipients
  - Specify the subject and the content of the message
  - Select attachments for the message
- Quickly share selected items in the finder through a new message
- Mark messages as read or unread
- Move messages to junk or trash
- Delete messages from the trash
- Tell mail to check for new mail for all accounts

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by zisra** [comment]
Thank you so much for your hard work! Hope we can see this extension in the store soon 🚀

**Comment by pradeepb28** [comment]
@ikupenov can we able to read an entire thread? If not it would be great to be able to add that. Example: I select an email in inbox then I run a command where it reads the entire thread in Raycast UI

**Comment by ikupenov** [comment]
> 

You mean something like that?
CleanShot 2023-05-18 at 12 36 41@2x

**Comment by pradeepb28** [comment]
@ikupenov yeah

**Comment by zisra** [comment]
> Pleasure! You could import it manually and give it a spin in the meantime, testers are greatly appreciated 😄.
How would I do that?

**Comment by pradeepb28** [comment]
> > @ikupenov yeah
> 
> You probably figured it out by now, but yeah, it's possible to read an entire thread.

are you launching with that?

**Comment by ikupenov** [comment]
@zisra You can clone my fork https://github.com/ikupenov/raycast-extensions/tree/ext/mail then `cd` into `/extensions/mail` and run `npm i && npm build`. Then through Raycast, lookup **Import Extension** and select the mail extension folder.

**Comment by pernielsentikaer** [comment]
I'll try to see if I can figure out what it is today @ikupenov

**Comment by ikupenov** [comment]
It seems that the production build breaks one of the dependencies (Turndown's dependency to be exact - Domino - https://github.com/fgnass/domino/issues/146) due to the minifier. Turndown is currently used to transform the HTML into MD. It's possible to release this extension with just pain text mode until either of the following happens:
- Domino patches their code (probably unlikely in the near future as there's been an open issue since 2019)
- Bundler's minifying step is toned down (unlikely)
- Another **good** HTML to MD library comes through (not optimistic)
- Ability to use HTML instead of MD in Raycast (rooting for this one as it makes the perfect sense for this type of extensions)

**Comment by pernielsentikaer** [comment]
I have some objects with date either being `Invalid Date` or `null` 

```
11:48:47.823 {
  id: '25221',
  account: 'xxx',
  accountAddress: 'xxx',
  subject: 'Re: [raycast/extensions] [ Quantumcast ] - New command "Open Cloudflow Whitepaper" (PR #6972)',
  date: Invalid Date,
  read: true,
  numAttachments: 0,
  senderName: 'raycastbot',
  senderAddress: 'notifications@github.com'
}
```

```
11:48:47.819 {
  id: '25030',
  account: 'xxx',
  accountAddress: 'xxx',
  subject: 'Re: [raycast/extensions] Update typefully extension (PR #6577)',
  date: null,
  read: true,
  numAttachments: 0,
  senderName: 'raycastbot',
  senderAddress: 'notifications@github.com'
}
```

Maybe that gives a little clue since it should always be a `Date` object

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I think we're about to have the first version ready for the store and then we can iterate over it, do you mind adding some [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by yug2005** [comment]
Hey guys, sorry I haven't been able to work on raycast for a while but @ikupenov thanks for taking over the work! I tested out the extension briefly and it works great! Looking forward to seeing this go up in the store.

**Comment by pernielsentikaer** [comment]
Awesome, thanks for chirping in and all your hard work on this too 🔥

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by jesse-c** [comment]
Incredibly work!

**Pull request merged**
