### PR TITLE
Add cursor-project-manager extension

### PR DESCRIPTION
**Pull request by 5Gears0Chill**
## Description
This is a fork off the popular search in project manager and open with visual studio code extension. The goal is to alter this to open any project from the project manager in cursor. cursor is a fork off of the vscode repo rebuilt for AI coding assistant. [Cursor](https://cursor.com)

## Screencast

https://github.com/user-attachments/assets/9ee18125-c9dd-4cab-acc8-ef6875b40268

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Instead of having a fork of the extension it's better to enhance the current one by @MarkusLanger - we do the same for the main Visual Studio Code to ensure that we don't have to update them both since they can do the same

Does that make sense?

**Comment by 5Gears0Chill** [comment]
We can look at an enhancement, however the one created was built for visual studio code specifically, I believe it could lead to a confusing user experience to alter the existing one.

**Comment by MarkusLanger** [comment]
In my extension it is possible to open the project in Cursor. In the configuration it is possible to switch to Cursor.

**Comment by pernielsentikaer** [comment]
We could potentially improve the naming and descriptions to make them clearer. Having two identical problems will cause further complications.

**Pull request closed without merging**
