### PR TITLE
Microsoft Teams

### PR DESCRIPTION
**Pull request by svenwiegand**
## Description

First version of a new extension for Microsoft Teams users. This first version allows controlling meeting settings from Raycast using a brand new, unofficial API provided by the Microsoft Teams desktop client. Users can control these features during a meeting:

- Toggle microphone on/off
- Toggle camera on/off
- Toggle background blur on/off
- Leave call
- Raise hand
- Send reactions (like, love, applause, laugh, wow)

For future versions, I plan commands to adjust the Microsoft Teams status (if ever Microsoft will provide a useful API for this).

## Screencast

No screencast, but screenshots. See README.md for details.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by svenwiegand** [comment]
Any updates here @raycastbot ?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Could you handle errors gracefully so it doesn't crash?

image

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by svenwiegand** [comment]
Thanks for the hint @pernielsentikaer. Handling errors gracefully now.

**Comment by svenwiegand** [comment]
@pernielsentikaer I renamed my branch without thinking about the consequences. Please use follow-up PR #5718.

**Pull request closed without merging**
