### PR TITLE
Add extension json2ts-multi-converter

### PR DESCRIPTION
**Pull request by kyuuseiryuu**
## Description
 
Convert JSON data to Typescript code

## Screencast

https://user-images.githubusercontent.com/18333716/202422087-9605ee90-eb1a-42a5-b6a1-03450da84db6.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @kyuuseiryuu 👋 

Thanks for your contribution 🔥 

It might look like we already have something like that in the store, could you check [this out](https://www.raycast.com/gbarba/json2ts)

**Comment by kyuuseiryuu** [comment]
> Hi @kyuuseiryuu 👋
> 
> Thanks for your contribution 🔥
> 
> It might look like we already have something like that in the store, could you check [this out](https://www.raycast.com/gbarba/json2ts)
Thank you for reply.
Yes, I knew it, but it's not easy to use. So I want re-publish a new one.

**Comment by pernielsentikaer** [comment]
Instead of making another one with the same purpose, it could be an idea to hear if @gon250 is up for a revamp 😊

Added some JSON data to my clipboard but I was not able to get it to work, do you have some example data?

**Comment by kyuuseiryuu** [comment]
Yeah, it's the same purpose right. But they are entirely different project.
if extension support install from Github Repo, I think it's will really cool. 


---

### example JSON data
```json
{
  "code": 0,
  "result": {
    "name": "string",
    "continent": "string",
    "oldContinent": "string",
    "openTime": "2022-11-16T05:46:01.778Z",
    "officialId": "string",
    "isMerge": true,
    "districtMerges": [
      {
        "mergeDistrictId": 0,
        "mergeDistrictName": "string",
        "beDistrictId": "string",
        "beDistrictName": "string",
        "districtMergeDate": "2022-11-16T05:46:01.778Z"
      }
    ],
    "districtMergeDate": "2022-11-16T05:46:01.778Z",
    "nowDistrictId": "string",
    "nowDistrictName": "string",
    "isMergeStr": "string",
    "timeToLive": 0,
    "mergeQuantity": 0
  },
  "msg": "string"
}
```

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
The first time you open the extension after installation with the above JSON content in the clipboard it's not working as expected

https://user-images.githubusercontent.com/38033107/202122943-4f93df75-1f83-4aaf-87bf-303e748f545b.mp4

You could also use [preferences](https://developers.raycast.com/api-reference/preferences#api-reference) instead of the second command, did you think about doing that instead?

**Comment by kyuuseiryuu** [comment]
Thank you for review and feedback. "preferences" is awesome features. Thanks for your teams hard work.

**Comment by gon250** [comment]
I'm open to review what you are implementing and try to update the extension we already have to add more features and improve usability with your help and ideas 🤩

**Comment by gon250** [comment]
@kyuuseiryuu Let me know if you want :), also I dont see a recording at the description to see what have this extension to make it even more simple. thanks!

cc @pernielsentikaer

**Comment by kyuuseiryuu** [comment]
@gon250  Hi, in your extension, user operating flow is: 
1. copy JSON data
2. open extension
3. paste data
4. set TS code to clipboard

so, if user is copy the data to the clipboard already, why we should not read it automatically? so we can skip the step 3.

Mabe you hope user can re-edit the data in extensions, so you make a textarea field. But, someone who will use the extension he must be a developer right ? They must have better editor to do that. so I think we can remove the textarea field.

If we use form field, we have to use mouse or Tab key to move the cursor, it's can not over the operating flow quickly.

In this extension, user just *copy data* -> *open extension* -> *press Enter key done* without any mouse or Tab key operation.

Finally, some library may be has unfixed bug, so I think we should support multiple librarise to make users can chose.

**Comment by kyuuseiryuu** [comment]
@gon250 I updated the summary, will you merge this PR ?

**Pull request closed without merging**
