### PR TITLE
Add command to search history (and refactor the rest)

### PR DESCRIPTION
**Pull request by thomaspaulmann**
## Description

I added a new command to search Safari's browser history. This is convenient if you need to find a website that you opened before. I use this command heavily and finally was able to publish it. I took the courtesy to refactor the rest of the extension to make it easier to reuse code. @loris is aware of this change. 

There are a few outstanding things that could be improved:
- Convert more logic to hooks instead of async functions which make it easier to handle
- Add more convenience actions/commands to interact with Safari 

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @loris 

## Screencast

I'm hesitant to share my browser history :-)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
@loris please have a look

**Comment by loris** [comment]
@thomaspaulmann this is totally awesome, thanks a lot for the new history feature + the heavy code splitting 💯

only one feedback: could be great to make all command name/descriptions look similar, ie:

- Browse your Safari Tabs
- Browse your Safari Reading List
- Browse your Safari History

(instead of using "Search" or "List" etc)

**Comment by pernielsentikaer** [comment]
Seems like a single file was not correctly ran through Prettier

```❯ prettier --check .
Checking formatting...
[warn] src/components/AddToReadingListAction.tsx
[warn] Code style issues found in the above file(s). 
```

**Comment by thomaspaulmann** [comment]
> @thomaspaulmann this is totally awesome, thanks a lot for the new history feature + the heavy code splitting 💯
> 
> only one feedback: could be great to make all command name/descriptions look similar, ie:
> 
> * Browse your Safari Tabs
> * Browse your Safari Reading List
> * Browse your Safari History
> 
> (instead of using "Search" or "List" etc)

Good point, just synced the descriptions of the commands. I kept them a little bit different to make sure they don't read too boring. Also, I was thinking of renaming "Show Tabs" to "Search Tabs" and the same for reading list. I think it fits better the model. The problem is that renaming the commands could affect existing users habits, so I'm not sure if it's wise to go ahead.

**Comment by pernielsentikaer** [comment]
Hi @thomaspaulmann 👋

In my opinion it makes sense to renaming it now (I don't think it's too late) but I leave that up to you and @loris 

Your additions work as expected, good work 💪

**Comment by loris** [comment]
@thomaspaulmann @pernielsentikaer Yes it makes sense! But @thomaspaulmann is this on purpose that you renamed 2 of them to "Search", but left the 3rd one to "Browse your history"?

**Comment by thomaspaulmann** [comment]
Just updated the names and unified the descriptions. Let me know if there is something left that you would like to add.

**Comment by thomaspaulmann** [comment]
I also unified all copied actions across the search commands.

**Pull request merged**
