### PR TITLE
Add proxmox-virtual-environment extension

### PR DESCRIPTION
**Pull request by vkhitrin**
### Caveats

- This extension was tested on `PVE > 8.1` and may not work on earlier releases.

### About

Interact with [Proxmox Virtual Environment](https://www.proxmox.com/en/proxmox-virtual-environment/overview).
Manage `Nodes`, `Storage`, `Linux Containers (LXC)`, and `Nodes` present in a Proxmox instance.

## Screencast

https://github.com/raycast/extensions/assets/32794653/035227a4-5756-44d6-bad0-870f8adbabd0

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
What's the difference between this and [this extension](https://www.raycast.com/CzBiX/proxmox) by @CzBiX - could it be an idea to merge them?

**Comment by vkhitrin** [comment]
Hey @pernielsentikaer,

I was not aware that a Proxmox extension was already published in the store :(
The only difference is that this extension has additional commands to interact with more resources in a Proxmox cluster, and it is using a library instead of direct API calls.
Merging them sounds logical, but it is written differently compared to current @CzBiX's extension.

**Comment by pernielsentikaer** [comment]
Is any features from this missing, maybe @CzBiX could help with that too if he is available 🙂

**Comment by CzBiX** [comment]
Nice implementation. I also have plans to expand the functionality and show more details. I can make updates based on your code when I back from vacation.

**Comment by pernielsentikaer** [comment]
That sounds awesome @CzBiX - could that work for you @vkhitrin - then we'll close this PR and await the new PR

**Comment by pernielsentikaer** [comment]
Closing so @CzBiX can add it to the original extension - the features from this PR will be added @vkhitrin

**Pull request closed without merging**
