### PR TITLE
New extension: Easydict

### PR DESCRIPTION
**Pull request by tisfeng**
## Description

`Easydict` is an easy dictionary, for looking up words or translate text in an easy way, especially optimized for English and Chinese words. Use it out of the box,  support 23 translation languages with the help of Youdao, Baidu and Caiyun translation API.

For more details, please see [Easydict README](https://github.com/tisfeng/Raycast-Easydict) .

### Look up English word
log

###  Open and search word in third-party Eudic dictionary
log-exam-action

### Translate English text to Chinese
With

###  Look up Chinese phrase
增强

### Translate Chinese text to English
你是非常可爱

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tisfeng** [comment]
The first thing to say is, [Easydict](https://github.com/tisfeng/Raycast-Easydict) is inspired by [parrot-translate](https://github.com/raycast/extensions/tree/d0c2cfc46cf84b936518f81ed0f3c75132563987/extensions/parrot-translate/) and based on it. 

However, `Easydict` and `parrot-translate` are quite different in terms of product positioning, functional features and UI design. The core difference is that `Easydict` is aimed at concise and easy-to-use dictionary extension, translation is only an accompanying feature, while `parrot-translate` is a translation extension.

## Why Another Extension?



When I first met `parrot-translate`, I quickly became interested in this extension and hoped that it could have some more exciting new features, so I tried to submit some PRs and issues to it, such as

- Richer and more beautiful UI: https://github.com/raycast/extensions/pull/1677

- Support shortcut: https://github.com/raycast/extensions/issues/1683
- Support third-party dictionary Eudic: https://github.com/raycast/extensions/issues/1685 , https://github.com/raycast/extensions/pull/1708
- Feedback a bug: https://github.com/raycast/extensions/issues/1679

But, it is very regrettable that due to the large differences between me and the original developer on the product positioning of the extension, product design concepts, UI design, etc. https://github.com/raycast/extensions/pull/1677#issuecomment-1124838553, my suggestions have not been adopted or only partially adopted https://github.com/raycast/extensions/pull/1678, https://github.com/raycast/extensions/pull/1791, and there is a big gap between the adopted features and my original vision. I don't want to judge who is right and who is wrong here, because everyone has their own unique understanding of the product, and product is not only source code and features, but also product positioning, UI design and developers' personal preferences.

For the above reasons, I decided to implement an extension of my ideal dictionary https://github.com/raycast/extensions/pull/1708#issuecomment-1128360803, which is the origin of `Easydict`.

**Comment by tisfeng** [comment]
# What are the new features and improvements of Easydict?



Next, I will briefly describe the new features and improvements of `Easydict` from these four aspects:

### UI display changes:

- The new UI design distinguishes the meaning represented by the list elements with richer colored dots, and the corresponding dot icons add a friendly tooltip prompt.

- Add richer word query information: the form and tense display of word, and the types of exams that include the word.

- Redesigned action panel and preference page.



#### `Easydict` Look up a word

log的副本

#### `parrot-translate` Look up a word

iShot_2022-06-02_21.18.44



### New Features

- Support for displaying multiple translation results, currently supports Youdao, Baidu and Caiyun translation API.

- Support automatic query clipboard text, enabled by default.
- Add quick search query text online, supports Eudic, Youdao dictionary and Google translation.

#### `Easydict` Translate sentences

你是非常可爱的副本

#### `parrot-translate` Translate sentences 

iShot_2022-06-02_21.21.52



### Fixes && Improvements:

- Fixed the problem of querying the incorrect interpretation of some words https://github.com/raycast/extensions/issues/1679, For details, please see https://github.com/tisfeng/Raycast-Easydict#preferred-languages.
- Fixed a bug where the special character "(" "'" in the text could cause play sound to be interrupted.
- Improve the experience of using third-party dictionaries `Easydict`. Now it will automatically detect whether Eudic is installed to decide whether to display the action of opening in `Easydict`, and supports shortcut.
- For Chinese and English, the language judgment of input text is optimized to avoid wasting time when the input text language is the same as the first preferred language.
- Improve the Copying of the web result type in List.Item, the copied content has been modified to title join with subtitle.

#### `Easydict` Fixed https://github.com/raycast/extensions/issues/1679

heel

#### `parrot-translate`

iShot_2022-06-02_21.24.42

### Remove or Simplify Features:

- The complex input copy features `>` and `>>` has been removed, and this design implementation is not in line with the easy use concept of `Easydict`. Other ways may be considered in the future.
- Removed auto-paste function, which is often confusing and prone to misoperation.
- Removed the option to manually modify delayed translation time. First of all, this option is not necessary. Ordinary users do not need to manually modify this value. Adding a preference option will make it more difficult to understand. Secondly, this value is very important. If it is too small, it will frequently trigger translation API warnings. Too big will cause the translation time to become longer and affect the user experience.
- Simplified the copying operation of List.Item with long content, making the copied content more intuitive and friendly.

#### `Easydict` Copy Action

iShot_2022-06-02_21.37.40

#### `parrot-translate` Copy Action

iShot_2022-06-02_21.24.12

The above introduces some major optimizations and improvements of `Easydict` on the original project. 

For more details, please experience the `Easydict` extension in person and read [README](https://github.com/tisfeng/Raycast-Easydict).

**Comment by tisfeng** [comment]
Finally, when the extension is approved, I need someone to help modify the screenshot size under the metadata directory to meet the requirements of the guide. Those screenshots are only taken manually. I won't use figma to make unified screenshots. Thanks.

image

**Comment by pernielsentikaer** [comment]
Hi @tisfeng 👋 

Is this extension uses a different translation base? Or is it the same as Parrot Translate but just looks different? Is this a fork of Parrot Translate?

Regarding screenshots, I can help you out for sure 😄

**Comment by tisfeng** [comment]
Thank you first   @pernielsentikaer 

1. `Easydict` supports Youdao, Baidu and Caiyun translation API, `Parrot Translate` only supports Youdao. And I'm working for supporting more translations, such as [Tencent translation](https://cloud.tencent.com/document/product/551/15619), users can choose their preferred translation engine. More dictionary APIs will be added later.

2. Yes, `Easydict` first version was forked from parrot, and I have improved many UI displays, added more practical features, deleted some complex or inappropriate operations, made a lot of optimization && improvements on the original project.

image

**Comment by tisfeng** [comment]
Thank you for your advice  @pernielsentikaer, I have changed "Copy" to "Copy Text:".

Finally, thank you for helping me modify the screenshots.

image

**Comment by tisfeng** [comment]
@pernielsentikaer Oh,  I see what you mean, it's OK to change it to "Copy Text".  At first, I added the copy text because I was worried that this may won't make people understand the content of the copied text at first sight...

After thinking about it, I actually prefer to use this title, which is more concise and clear as an action title.  Thank you for your patient advice.

**Comment by pernielsentikaer** [comment]
Wouldn't it make sense to have most of the preferences required?

**Comment by tisfeng** [comment]
> Wouldn't it make sense to have most of the preferences required?

Well, I have changed the title of copy action to "Copy Text".  Do you have any other questions?

**Comment by tisfeng** [comment]
Hi @pernielsentikaer 

Yes, in order to make it easy to use, I set all preferences to unnecessary. Let me briefly explain why.

As for the language options, I set simplified Chinese and English by default, because this extension is mainly for Chinese users, many features are also specially optimized for Chinese and English, and the dictionary and translation API  Services are also  provided by several large Chinese companies. In short, the main purpose of this dictionary expansion is to make it convenient for Chinese users to query English words, or to query English words corresponding to Chinese phrases, or to translate Chinese and English sentences.

Second, for the same reason, I have provided some appIds and keys of the above translation services, which provide developers with a certain amount of free usage. If users apply by themselves, this may be a big challenge for non-developer users, and it is also inconsistent with the slogan "use out of the box" of the extension. For advanced users, I suggest that they apply for their own dedicated key, which I have explained [here](https://github.com/tisfeng/Raycast-Easydict#translation-services)  in detail.

**Comment by pernielsentikaer** [comment]
Hi @tisfeng 👋 

I added metadata images and missing dotfiles in order to validate, could you look into the [errors from the CI](https://github.com/raycast/extensions/pull/1872/commits/9f46eff7a62baa30a13f287c6c2c47f764017ab8)?

**Comment by tisfeng** [comment]
OK, I'll take a look right away.

**Comment by tisfeng** [comment]
Hi @pernielsentikaer , I have resolved all lint errors, could you have a look?

**Review by pernielsentikaer — APPROVED** [review]
Hi @tisfeng 👋 

Let's get it merged 🚀

**Pull request merged**
