### PR TITLE
Add extension for controlling Philips Hue lights

### PR DESCRIPTION
**Pull request by pindab0ter**
## Description

This extensions enables you to quickly and easily control your Philips Hue lights by controlling groups (rooms/zones/entertainment areas), individual lights, or by setting scenes.

There is a robust command for linking your Hue bridge.

There is support for setting the color for RGB lights, in- and decreasing color temperature for supported lights, setting and in-/ decreasing brightness, setting scenes and turning lights off/on.

## Screencast

https://user-images.githubusercontent.com/5128166/185599653-4c257fb2-fcdd-4976-b03d-1f8af808d5e1.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@thomaspaulmann - do you still have the Hue extension you started on, could be cool to share it to improve here if possible 🙂

**Comment by pindab0ter** [comment]
@pernielsentikaer I contacted @thomaspaulmann, and he allowed me to use his code. So the code in this project actually already [incorporates his work](https://github.com/pindab0ter/raycast-hue/commit/d9b38f227d587a631b8769cd7342cea57e3e865b).

**Comment by pernielsentikaer** [comment]
That's good to hear @pindab0ter 🙂 Would be a waste to miss that! 

The bridge connection works very well, I like how it works 🔥

When using one of the commands like `Set Space` when bridge is not connected it gives me the action `Link With Bridge` - would it be possible to push to that view instead so it's actually linking instead of popping to root?

Just after the connection is made, I experience some problems:

CleanShot 2022-08-25 at 13 50 40@2x

```
13:48:19.043 (node:91663) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
13:48:21.175 /Users/pernielsentikaer/Documents/Raycast/tmp/hue/node_modules/node-hue-api/dist/esm/api/http/HttpClientFetch.js:98
                throw new HttpError(res.status, res.url, res.headers.raw(), data);
                      ^

Error: HTTP error status: 503; "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n<html>\n<head>\n    <title>hue personal wireless lighting</title>\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"/index.css\">\n</head>\n<body>\n    <div class=\"philips-header\">\n      <img src=\"/philips-blue.png\" class=\"philips-logo\" alt=\"Philips\" />\n    </div>\n    <div class=\"header\">\n      <img class=\"header-logo\" src=\"/hue-logo.png\" alt=\"hue personal wireless lighting\" />\n\n      <img src=\"/hue-color-line.png\" class=\"colorline\" />\n\n    </div>\n    <div class=\"error\">Oops, there appears to be no lighting here</div>\n</body>\n</html>\n"
    at null.<anonymous> (/Users/pernielsentikaer/Documents/Raycast/tmp/hue/node_modules/node-hue-api/dist/esm/api/http/HttpClientFetch.js:98:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  _hueError: undefined
}
``` 

After some hours it was working as expected, do you know what might cause this?

I might have to wait a few hours to test more, I will be back! 🙂

**Comment by unnamedd** [comment]
> @pernielsentikaer I contacted @thomaspaulmann, and he allowed me to use his code. So the code in this project actually already [incorporates his work](https://github.com/pindab0ter/raycast-hue/commit/d9b38f227d587a631b8769cd7342cea57e3e865b)! :)

@pindab0ter that being said, don't you think would be nice to add his username as contributor?

**Comment by pindab0ter** [comment]
> The bridge connection works very well, I like how it works 🔥

Glad to hear!
 
> When using one of the commands like `Set Space` when bridge is not connected it gives me the action `Link With Bridge` - would it be possible to push to that view instead so it's actually linking instead of popping to root?

I've thought about that. It does increase the complexity quite a bit, but I think it should be doable. Do you reckon that's a better approach than keeping the 'Manage Hue Bridge' as a separate and isolated command?

> Just after the connection is made, I experience some problems:
>
> […]
>  
> After some hours it was working as expected, do you know what might cause this?

I've noticed the same problem as well and haven't been able to pin it down. It's a 503 which implies that it's an issue caused by the Hue Bridge rather than the extension.

It just needs to handle that exception and show a toast that it couldn't reach the Bridge.

I'm quite busy the coming days, so I don't know when I'll get around to fixing these issues, but thank you for bringing them to light!

**Comment by pindab0ter** [comment]
> @pindab0ter that being said, don't you think would be nice to add his username as contributor like was done [here](https://github.com/raycast/extensions/blob/47d5f3f161415b14a3a3d6491c8b11049c29aa4f/extensions/linear/package.json#L10-L13)?

I didn't know that you could do that in that way, so thank you for pointing that out! I've added him, immediately!

**Comment by thomaspaulmann** [comment]
Thanks for adding me as a contributor. I was wondering if we should the pairing view whenever there isn't one connected instead of having the user manually to go to the other command. This isn't blocking the PR, just wanted to note it.

**Comment by pernielsentikaer** [comment]
That's an excellent idea; we could skip one command. If you want to disconnect the bridge, there could be an action in the panel in all other commands.

**Comment by robertvanhoesel** [comment]
Excited for this extension!

If you don't mind I tried creating a better icon. The hue logo mark is terrible to read at a small size and color contrast isn't great. I tried to mimic the same gradient on top of a lightbulb using a slightly darker squircle. [Edit/View on Figma](https://www.figma.com/file/aVfOFP1h82JKXvxG5w3liE/Hue-Raycast-Icon?node-id=202%3A341)

Artboard

<details>
<summary>Before</summary>

Artboard


</details>

<details>
<summary>icon</summary>

command-icon


</details>

**Comment by thomaspaulmann** [comment]
@robertvanhoesel this is great! Love the collaboration here. Seems like everybody is excited about the extension :-) FYI we also support different icons for light/dark theme. I think your suggested icon works in both themes, just wanted to mention it, in case you thought about two different ones.

**Comment by robertvanhoesel** [comment]
> FYI we also support different icons for light/dark theme. 
Oh that's sick! I may revisit the design a bit in that case.

**Comment by pindab0ter** [comment]
> That's an excellent idea; we could skip one command. If you want to disconnect the bridge, there could be an action in the panel in all other commands.

I agree. That's just better from a UX point of view. I have a working solution locally that uses the existing logic and mixes them into the commands. There's some streamlining I need to do, so expect an update on that, soon™.

The only thing I'm not sure about is whether having the “Remove Hue Bridge” action on every single light/group/scene is the best approach. It feels like there should be a different place for that.

> Oh that's sick! I may revisit the design a bit in that case.

The icon already looks amazing, I look forward to the light/black theme versions.

However much I like the “Hue” letters/logo and the idea of using the official logo, I agree that it's just not legible. The only reason I went with it in the first place is that I saw the logo more like a logo than letters you should be able to read.

I look forward to the versions for the light/black theme and will definitely use them!

**Comment by robertvanhoesel** [comment]
Tweaked the icons a bit, adding more contrast and more of the original blue tones. Light definitely nicer like this.

image


<table>
<tr><th>Light</th><th>Dark</th></tr>
<tr>
	<td>
	
	</td>
	<td>
	</td>
	</tr>
	<tr>
      <td><a href="https://user-images.githubusercontent.com/6642554/187084335-8397158b-0c30-4077-a96f-613edb011641.png">command-icon-light.png</a></td>
      <td><a href="https://user-images.githubusercontent.com/6642554/187084333-31b89a83-7d13-44e0-9c40-4d7dc3d0224c.png">command-icon-dark.png</a></td>
      </tr>
</table>

**Comment by pindab0ter** [comment]
This is awesome, @robertvanhoesel. I just tried them locally, and they look so good!

What's your Raycast username? I'll add you as a contributor.

**Comment by robertvanhoesel** [comment]
@pindab0ter glad you like them, it's [@robert](https://www.raycast.com/robert)

**Comment by pindab0ter** [comment]
> That's an excellent idea; we could skip one command. If you want to disconnect the bridge, there could be an action in the panel in all other commands.

It was quite a bit of work, but in the end I think it was worth it.

The extension now takes you through the required steps when you launch any command while not having linked a Hue Bridge yet.

Even though I think I've covered it all, I would love it if other people could test it (and removing the Hue Bridge and re-adding it) to see if anything unexpected happens.

**Comment by robertvanhoesel** [comment]
Tested the extension and linking without encountering any problems. Only thing to add is that the text on the link screen is no longer correct;
> Press the button in the center and use the ‘Link With Bridge’ action to connect.
May want to change to
> Press the link button in the center of the bridge, and press enter

**Comment by pindab0ter** [comment]
> Only thing to add is that the text on the link screen is no longer correct;

Thank you for the feedback. I would like to put out as best an extension as I can, so this kind of feedback is appreciated!

**Comment by robertvanhoesel** [comment]
So one more idea, which I actually started fiddling with, is adding favorite scenes that would show first in the 'Set Scene' command (either first in each group or all the way at the start in a section called 'favorites' with the room name.

I know the scenes are sorted on how they are configured in the Hue App, but I already found that at my desk there are just a handful of scenes I really use. It's definitely a nice to have to maybe add in a next version and I don't mind helping out with that!

**Review by pernielsentikaer — APPROVED** [review]
Hi @pindab0ter 👋 

I think we should get this out and then we can iterate on it, I tested it again now and the new flow works better and I was able to use it right away, awesome!

When it's out we can do all the awesome things! 🔥

Thanks for all chirping in!

**Comment by pindab0ter** [comment]
> So one more idea, which I actually started fiddling with, is adding favorite scenes that would show first in the 'Set Scene' command (either first in each group or all the way at the start in a section called 'favorites' with the room name.
> 
> I know the scenes are sorted on how they are configured in the Hue App, but I already found that at my desk there are just a handful of scenes I really use. It's definitely a nice to have to maybe add in a next version and I don't mind helping out with that!

I agree this is a good idea! I don't have much time these weeks, so whatever you can do will be appreciated. Feel free to hit me up on Slack, too.

**Comment by tomclark** [comment]
Hi there,

Apologies for hijacking this thread; I wasn't sure where might be most appropriate.

I'm brand new to Raycast - I just discovered the tool today. I installed the Hue extension, but I don't have the option to manage the bridge. I only see four options: control lights, control groups, set scene, and turn off all lights. When I choose one of those, it takes me to a screen saying it's trying to discover the bridge, but doesn't ever find it. I've tried multiple times, making sure I'm definitely able to ping the bridge, and that I've pressed the button in good time, but nothing works.

There doesn't seem to be anyway of specifying the bridge IP (on some other applications I've needed to do that).

Is there something I'm missing? Thanks in advance for your help. Can someone point me in the right direction, please?

**Comment by thomaspaulmann** [comment]
Mmh that's unfortunate. You can ping it from your Mac?

**Comment by tomclark** [comment]
> Mmh that's unfortunate. You can ping it from your Mac?

Hey, thanks for your reply.

Yeah, I can ping it, and I have other apps on my Mac that work with the bridge - Alfred, for one.

As I said, I have in the past had to specify the IP address of the bridge for some apps; I wonder if I need to do that here, but I can't see a way of specifying an IP address. Is there any way I can do that? I'm very new to Raycast; is there somewhere in the code I could hardcode the bridge's address?

The extension does seem to find the bridge. When I choose one of the commands, it says it's trying to discover a Hue bridge on the network, and then it prompts me to connect with it by pressing the button on the bridge. I do that, then press enter, and it just times out. The next time I try and do it, it goes back to trying to detect the bridge. The bridge is downstairs, I'm upstairs, and it takes me ten-fifteen seconds to get between the two of them - but it's not nearly long enough for it to time out (and as I say, I've linked devices without issue before).

Frustrating. :-(

**Comment by tomclark** [comment]
Interestingly, if I turn off wifi on my Mac, and try one of the commands again, it says it can't find a bridge, which is different to when wifi is on, when it finds the bridge but doesn't seem to be able to connect to it after I push the button.

I found the files for the extension in ~/.config/raycast/extensions/1437e84a.../ but of course all the files are minified so I can't edit them. Is there any config file I could create that it'd pick up and respect?

**Pull request merged**
