### PR TITLE
[Hue] Hue API V2

### PR DESCRIPTION
**Pull request by pindab0ter**
## Description

This is nigh-on a complete rewrite of the extension. The changes, as noted in CHANGELOG.md:

* Groups and scenes are now shown as images to make it easier to find the right one
* Add rate limiting to improve behaviour when holding down a hotkey and to prevent rate limiting errors
* Add live updating of lights when they are changed by e.g. the Hue app or a physical switch
* Many improvements under the hood to improve performance, responsiveness and reliability
  * Use Hue API V2: ‘Connected Lighting Interface Protocol’ or CLIP
  * Connect with the Hue Bridge using TLS (HTTPS) and HTTP/2
  * Use a single persistent connection to send and receive data to and from Hue bridge
* Deprecation: It is no longer possible to set/adjust the color (temperature) of a group since this is not supported by
  the Hue API V2. It may be added in the future with a workaround. Please use scenes or individual lights instead.

I'm looking forward to your findings and feedback!

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pindab0ter** [comment]
@pernielsentikaer I think you might be interested in looking at this, too.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I tried this update but I was not able to set it up, I'm stuck in this view 

Raycast-2wn6VWJg@2x

In the console I see this output: 

Raycast-TniuyH17@2x

Do you have a clue about this one @pindab0ter, all previous versions connected just fine

**Comment by pernielsentikaer** [comment]
This is the full output @pindab0ter 

```
❯ npm run dev

> dev
> ray develop

info  -  entry points [src/controlLights.tsx src/controlGroups.tsx src/setScene.tsx src/turnOffAllLights.ts]
ready -  built extension successfully
16:02:25.511 Error: No Hue Bridge credentials found
    at src (/Users/pernielsentikaer/.config/raycast/extensions/hue/controlGroups.js:60867:21)
16:02:25.512 Discovering bridge using MeetHue's public API…
16:02:25.636 Discovered Hue Bridge using MeetHue's public API: 192.168.68.56
16:02:45.694 (node:76790) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
16:02:45.798 Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at TLSSocket._finishInit (node:_tls_wrap:952:8)
    at ssl.onhandshakedone (node:_tls_wrap:733:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
  ```

**Comment by pindab0ter** [comment]
Ah, right. I think this might be because that's an older model of Hue Bridge, or simply one that isn't up-to-date. Which is good, because you won't be the only one.

I'll look into how I can deal with this.

**Comment by pindab0ter** [comment]
I added support for Hue Bridges with self-signed certificates. The relevant code is documented with links to the relevant Philips Hue Developer documentation.

I also added a DNS shim. Since it's not allowed to set the TLS ServerName to an IP address, I set the ServerName to the server ID, which I then resolve with the shim. The shim only resolves this Bridge ID address. Any other DNS request is passed through to the regular lookup function.

**Comment by pernielsentikaer** [comment]
Thanks for all the fixes and hard work @pindab0ter 🔥

**Comment by pindab0ter** [comment]
> Thanks for all the fixes and hard work @pindab0ter 🔥

My pleasure!

Does that mean it works on your end, now?

**Comment by pernielsentikaer** [comment]
No, not yet, but just wanted to thank you 😊

**Comment by pindab0ter** [comment]
I appreciate that! ☺️ 

Could you provide me with details as to why it doesn't work yet?

**Comment by pindab0ter** [comment]
Bridges with self-signed certs are now supported and the loading issue is resolved.

**Comment by unnamedd** [comment]
@pindab0ter I'd like to ask you how complex is for you (in implementation) to give the option in the Preferences for the user to set by himself the bridge IP Address and also the API Key?

**Comment by pindab0ter** [comment]
> @pindab0ter I'd like to ask you how complex is for you (in implementation) to give the option in the Preferences for the user to set by himself the bridge IP Address and also the API Key?

I'll look into doing that soon. You should only have to set the bridge IP address, since everything else is just requested from the bridge on linking.

Could you tell me more about your scenario, so I know what problem I'm solving?

**Comment by unnamedd** [comment]
@pindab0ter basically my point is: my bridge is behind of a tv hack and I already have an API Key and also its IP Address and I'd like to just skip the linking part just to input the information needed myself.

**Comment by pindab0ter** [comment]
@unnamedd This will most likely make it into the next version.

**Comment by unnamedd** [comment]
> @unnamedd This will most likely make it into the next version.

Nice!

**Comment by pernielsentikaer** [comment]
Awesome work here @pindab0ter - this is SUCH a massive one! Good work 🚀

**Pull request merged**
