### PR TITLE
Update doccheck extension

### PR DESCRIPTION
**Pull request by justspacedog**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by justspacedog** [comment]
> Could you check the files once more, there are quite a lot german in them still

Ah - do you mean the comments in the code? I will have a look.

**Comment by pernielsentikaer** [comment]
doccheck-flexikon.tsx does have actions with German, comments are not that important 🙂

**Comment by justspacedog** [comment]
> doccheck-flexikon.tsx does have actions with German, comments are not that important 🙂

I have removed ALL GERMAN from the extension. However I noticed a bug: when I click a link and open another article from an article raycast will show the old German actions. But I don't have any German left in the source…

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
