### PR TITLE
Add Vaib Extension

### PR DESCRIPTION
**Pull request by Vaib215**
## Description

Fixed the issues as per review on previous PR

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Vaib215** [comment]
@pernielsentikaer

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you look into the [CI errors](https://github.com/raycast/extensions/actions/runs/7485009951/job/20372771249?pr=10092) and fix them 🙂

- Screenshots should be made [this way](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Vaib215** [comment]
I have resolved the CI errors and added some screenshots as per the docs

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by Vaib215** [comment]
> 🎉 🎉 🎉
> 
> Such a great contribution deserves a reward, but unfortunately we couldn't find your Raycast account based on your GitHub username (@Vaib215). Please [link your GitHub account to your Raycast account](https://www.raycast.com/settings/account) to receive your credits and soon be able to exchange them for some swag.

Haven't received any credits

**Pull request merged**
