### PR TITLE
Add ai-git-assistant extension

### PR DESCRIPTION
**Pull request by Popalay**
## Description

The primary function of this extension is to generate Git commit messages using Raycast's AI and to feed from the diff and status outputs of your repository.

## Screencast

ai-git-assistant-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @Popalay 👋 

I like the idea a lot - what about instead rely on getSelectedFinderItems (and taking the files current directory)?

**Comment by Popalay** [comment]
> Hi @Popalay 👋 
> 
> I like the idea a lot - what about instead rely on getSelectedFinderItems (and taking the files current directory)?

Hey @pernielsentikaer 

This is a good idea, but in this case the usage of the extension changes a bit. With your proposal, choosing the git repo folder is required each time to generate a commit message. I want to make this experience more smooth w/o any required step expect the initial configuration. Do you have something in mind to make it possible? Thanks!

**Comment by Popalay** [comment]
I think I can utilize the getSelectedDir method and if it returns something, presave the output for the next calls. In this case it will be possible to generate messages for the same repo w/o selecting the same repo twice. What do you think? @pernielsentikaer

**Comment by Popalay** [comment]
@pernielsentikaer Broke down my branch history by trying to push changes instead of using the publish command. Opened a new [PR](https://github.com/raycast/extensions/pull/11800). Please take a look.

**Pull request closed without merging**
