### PR TITLE
[Image Modification] Add WebP support + Path Finder support

### LINKED ISSUE #5584: [Image Modification] WebP Conversion
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

Is there any chance WebP can be a conversion option because it's the #1 format that is recommended for web in many instances.

### Who will benefit from this feature?

I can totally stop using web-based tools to do this conversion that slows me down immensely (since every image needs to be converted to WebP).

### Anything else?

_No response_

### LINKED ISSUE #5587: [Image Modification] Can you add support for Path Finder
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

When I use with an image in path finder it says image not found. Can you add an option to select or set an alternative file manager like path finder

### Who will benefit from this feature?

Anyone who use different file manager

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SKaplanOfficial**
## Description

This update to the Image Modification extension add supports for converting images to and from WebP format, as well as for executing SIPS commands (such as resize, rotate, etc.) on WebP files by utilizing a temporary PNG image. WebP conversion is made possible by embedding the [cwebp and dwebp binaries](https://developers.google.com/speed/webp/docs/precompiled) into the extension. The update also adds a preference for preferred file manager, currently supporting Finder and Path Finder.

### Issues Resolved
- Resolves #5584
- Resolves #5587 

## Screencast

[ImageMod720.webm](https://user-images.githubusercontent.com/7865925/228455088-5cd478e3-6991-4f2b-9d6b-15824c707384.webm)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hello 👋

I gave it a quick spin, works as expected, approved 🔥

**Comment by abass** [comment]
AMAZING!!!! Thank you 🤗🤗🤗🤗

**Comment by abass** [comment]
@SKaplanOfficial the WEBP conversion doesn't seem to be working most of the time. I'm simply using Cleanshot to take a PNG photo and then convert it and it just errors out:
CleanShot 2023-04-02 at 16 49 03@2x

Any idea what might be going wrong there?

**Comment by SKaplanOfficial** [comment]
@abass That's the result of a permissions issue with the version downloaded from the store — [my latest PR](https://github.com/raycast/extensions/pull/5715) contains a fix for it. In the meantime, you can use `find ~/.config/raycast/extensions/ -name "cwebp"` to locate the cwebp (and likewise dwebp) binary, which you can give execute permission with `chmod +x`. Sorry for the inconvenience!

**Comment by abass** [comment]
Hugely appreciate it! Thanks so much!

**Pull request merged**
