### PR TITLE
[scrcpy] minior change

### PR DESCRIPTION
**Pull request by bxb100**
## Description

- Added disable audio for scrcpy
- Improve configuration prompt
- Added default value for Apple Silicon scrcpy install path

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution 🔥 

@zcfan do you mind checking this?

**Comment by bxb100** [comment]
cc @pernielsentikaer what should I do?

**Comment by pernielsentikaer** [comment]
Pinging @zcfan one last time

**Comment by zcfan** [comment]
> Pinging @zcfan one last time

LGTM

Sorry for late reply, I don't check github everyday, feel free to make any improment.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
