### PR TITLE
Order snippets by last copied

### PR DESCRIPTION
**Pull request by mkitane**
## Description

- Order snippets by last used

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by antonreshetov** [comment]
@mkitane I think that first of all we should discuss new features before they are implemented.
@pernielsentikaer Is there any way that does not allow to merge PR without approval from the author of the extension

**Comment by pernielsentikaer** [comment]
@antonreshetov, in most cases, it makes sense to hear from the author, and that's also why you're being taggged; in some cases, they might get merged.

What do you think about this one? You can have your say at any time, but what PRs are for is new ideas and fixes. Most of them are enhancements and should only make everything more delicious 😄

**Comment by antonreshetov** [comment]
@pernielsentikaer I don't want the extension to lose the original idea of the author. I would like to be able to prevent the merge without my approval. Otherwise it's kind of chaos that everyone can just make changes that solve their problem.

**Comment by pernielsentikaer** [comment]
@antonreshetov that makes perfect sense, this will first be reviewed later today or tomorrow, so you have plenty of time to approve or ask about the solution. 

One way here could be to make a dropdown in preferences where it's possible to select sort type?

**Comment by antonreshetov** [comment]
@pernielsentikaer Enough time? This approach is not acceptable, you can not limit the author in terms of time to consider PR. This is open-source after all, not his work. 

Generally, I think you should look at a more mature approach for managing custom extensions, such as VS Code Extensions or NPM, where only the author can publish extensions, no matter where the source code is stored.

**Comment by pernielsentikaer** [comment]
Hi @antonreshetov 👋 

I'm sorry to hear that you feel this way; it's one of the strengths as I see it.

I'm not sure I follow what the problem is? Why wouldn't it be a good idea to enhance extensions to provide the best UI/UX at any time?

As I see it, there have been 3 PRs in total, two by you and another from @mkitane you approved.

Of course, we want the original Author to approve it, except if it's something critical - that's also why the bot tagged you.

**Comment by antonreshetov** [comment]
@pernielsentikaer I'm not talking about this particular PR, I'm talking about the approach in general. The fact that I saw a notification about this PR today and that I now have time to deal with it is good, but tomorrow I can skip it, because I have other things to do, and the PR will be accepted by you. So I started this conversation for the sole purpose of having the final approval of the PR acceptance, I may not approve any PR in general because it is my extension and I have a certain view on it

**Comment by pernielsentikaer** [comment]
Don’t worry, we will not merge it without your approval. Please let us know here about your decision when you have time to take a look, no rush 😄

**Comment by antonreshetov** [comment]
@pernielsentikaer I don't know why this makes you smile all the time, but thanks nonetheless for the opportunity to give me time to consider PR.

**Comment by pernielsentikaer** [comment]
I can see that my initial response to you makes it easy to interpret the wrong way, as it should have been written more clearly. It’s solely my mistake, and I do apologize for that.

Take your time. Ping me here or in DM at any time if you have any questions.

**Comment by mkitane** [comment]
After discussions with @antonreshetov , I added a preference option to be able to choose your sort order. The PR is ready.

**Comment by antonreshetov** [comment]
@mkitane awesome.
@pernielsentikaer I think we are could merge it.

**Comment by pernielsentikaer** [comment]
Works as expected, thanks - shouldn't `original` be the default value here, or?

**Comment by mkitane** [comment]
@pernielsentikaer i think last copied should be the default behavior as this is how most snippet apps behave. (The raycast snippet app does the same)

**Comment by pernielsentikaer** [comment]
What do you think here @antonreshetov 😄

**Comment by antonreshetov** [comment]
@pernielsentikaer As I wrote earlier, I think it's okay and we can merge it.

**Comment by pernielsentikaer** [comment]
Great, I just wanted to make sure that nothing wrong got committed here 🔥

**Pull request merged**
