### PR TITLE
ChatGPT: migrate openai V3 to V4

### PR DESCRIPTION
**Pull request by bxb100**
## Description

Old version stream data can't recognize truncated data

## Screencast

image

the answer is `Hello! How can I assist you today?` missing `How` `assist` data

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @bxb100 🔥 

I tested the extension from the store and couldn't reproduce it, can you help with a screencast so I can see the issue?

**Comment by bxb100** [comment]
https://github.com/raycast/extensions/assets/20685961/f203538d-471e-4395-8a20-ca7dfa67dce6

if the server response JSON not complete, you can see this error

```plain

16:29:13.594 {"object": "chat.completion.chunk", "model": "gpt-4", "choices":[],"created":0,"id":"","prompt_filter_results":[{"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"prompt_index":0}]}
16:29:13.599 {"object": "chat.completion.chunk", "model": "gpt-4", "choices":[{"index":0,"content_filter_offsets":{"check_offset":91,"start_offset":91,"end_offset":125},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":fal
16:29:13.600 se,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":null,"role":"assistant"}}],"created":1705220953,"id":"chatcmpl-8gq9hJqC0jeBxcxRak6OSQHuhbKer"}
16:29:13.600 {"object": "chat.completion.chunk", "model": "gpt-4", "choices":[{"index":0,"content_filter_offsets":{"check_offset":91,"start_offset":91,"end_offset":125},"cont
16:29:13.600 ent_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" How","role":null}}],"created":1705220953,"id":"chatcmpl-8gq9hJqC0jeBxcxRak6OSQHuhbKer"}
16:29:13.601 {"object": "chat.completion.chunk", "model": "gpt-4", "choices":[{"index":
16:29:13.601 0,"content_filter_offsets":{"check_offset":91,"start_offset":91,"end_offset":125},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}},"delta":{"content":" assist","role":null}}],"created":1705220953,"id":"chatcmpl-8gq9hJqC0jeBxcxRak6OSQHuhbKer"}
16:29:13.601 {"object": "chat.completion.chunk", "model": "gpt-4", "choices":[{"finish_reason":"stop","index":0,"content_filter_offsets":{"check_offset":91,"start_offset":91,"end_offset":125},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"sa
16:29:13.601 fe"}},"delta":{"content":null,"role":null}}],"created":1705220953,"id":"chatcmpl-8gq9hJqC0jeBxcxRak6OSQHuhbKer"}

```

**Comment by pernielsentikaer** [comment]
Which settings did you set for your model? I'm still not able to reproduce this 😕

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
