### PR TITLE
[ Quantumcast ] - Update extension with new command

### PR DESCRIPTION
**Pull request by ghost**
## Description

Added new command "Open Cloudflow Workpace" that allows to open specific Cloudflow workspace URLs in the default browser.

## Screencast

Raycast 2023-04-18 at 11 46 47

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jcgerhard** [comment]
Thanks in advance for your review! 🤗

**Review by jcgerhard — COMMENTED** [review]
Thank you very much! Changes approved!

**Review by jcgerhard — COMMENTED** [review]
Approved

**Review by jcgerhard — COMMENTED** [review]
Approved

**Review by jcgerhard — COMMENTED** [review]
Approved!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
