### PR TITLE
Update hetzner extension

### PR DESCRIPTION
**Pull request by alex-w0**
## Description

Allows the user to have different Hetzner projects

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you mind sharing a screencast of the new flow?

**Comment by alex-w0** [comment]
@pernielsentikaer I've updated the changelog and here you find a record of the new flow:

https://github.com/raycast/extensions/assets/25109632/1bff3865-ba80-4a53-9303-c0f2dee53273

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by alex-w0** [comment]
Looking forward to get this feature merged 🔥

**Pull request merged**
