### PR TITLE
Add time extension

### PR DESCRIPTION
**Pull request by devidw**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

What's the use case for this extension? It's really heavy while having it open with all the refreshes.

**Comment by pernielsentikaer** [comment]
You don't have the time in the menubar? 🙂

**Comment by pernielsentikaer** [comment]
I think we should indeed skip the milliseconds since it's hammering the CPU for all the redraws 🙂

**Comment by devidw** [comment]
Good with me @pernielsentikaer: https://github.com/raycast/extensions/pull/10659/commits/efe106e94fd5f6d0713817d29e7cff023b3acef0

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
