### PR TITLE
Improve Pokédex extension

### PR DESCRIPTION
**Pull request by anhthang**
## Description

Bug fix / improvement for my extension

898 Pokémon Species with all alternate forms including Regional forms (Alolan, Galarian), Mega Evolution, Gigantamax

- [x] 🔍 Pokédex
  - Search for a Pokémon by name or using its National Pokédex number.
    - Training
    - Breeding
    - Forms
  - Open in the Official Pokémon Website, Open in Bulbapedia.
  - Type icons in listing page
- [x] ⚙️ Preference
  - Pokémon details by prefered language. Supported: English (default), French, German, Italian, Japanese, Korean, Spanish.

- [x] Update deprecated API

## Screencast

https://user-images.githubusercontent.com/10458061/155260878-cbf485cd-01a5-450b-80e0-02b22a37e505.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by anhthang** [comment]
Hi @pernielsentikaer 👋

I did some updates for the extension. Please help me review this if you have time.

Thank you.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @anhthang 👋 

It turns out quite awesome, I like the possibility to change language 💪 

Some feedback for you to address:

- It seems like something is wrong with “Pikachu”, I get a lot of loading images when looking up details, is anything wrong?

YAkUOmdgyp4ONQxN

- When using backspace it makes a funny flicker with the full list and then showing the new search, can you look into this? 

https://user-images.githubusercontent.com/38033107/156259576-3f480f97-3f55-4a36-924e-c7a94395343a.mp4

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 👋 

I just pushed new commit that includes fix for the flicker issue. It also remove forms that unavailable in the official website (pokemon.com) as I don't think they will add it. If it was possible, they would have done it.

**Review by pernielsentikaer — APPROVED** [review]
Awesome @anhthang 🔥 

Both works as expected, let's get it ready for the Store - well done!! 💪

**Comment by anhthang** [comment]
Thank you so much @pernielsentikaer, you made it better a lot also.

**Comment by pernielsentikaer** [comment]
It was a pleasure working with you 🔥

**Pull request merged**
