### PR TITLE
Add helldivers2 extension

### PR DESCRIPTION
**Pull request by AlexStrNik**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by AlexStrNik** [comment]
@pernielsentikaer Hello! Could you review this one please?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You should maybe look into using [useCachedPromise](https://developers.raycast.com/utilities/react-hooks/usecachedpromise) with [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch) instead - that will give you a better experience

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by AlexStrNik** [comment]
@pernielsentikaer Hello! Thank you for feedback. I tried using built-in `use Fetch` but it have some problem, i need staggered loading in many places (e.g fetching status requires fetching current season) and it seems impossible to implement with default hook. So i written my own `use Fetch` that just do nothing if url is undefined. Regarding `useCachedPromise` i doubt if it actually needed, the info updates very frequently and showing cached information may worse user experience (i think so). But if you think that's really needed i will implement it, no problem

**Comment by pernielsentikaer** [comment]
One command is crashing for me, can you look into what's going on

helldivers2 2024-06-11 at 09 03 34

```
09:03:58.744 TypeError: Cannot read properties of undefined (reading 'setting')
    at Command (/Users/pernielsentikaer/.config/raycast/extensions/helldivers2/major-orders.js:13766:52)
    at Wl (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:5:21246)
    at Kl (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:3134)
    at ho (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:41965)
    at co (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:36991)
    at Ds (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:36922)
    at qr (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:36779)
    at vu (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:33275)
    at io (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:7:32231)
    at Lu (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.production.min.js:1:1694)
09:03:58.806 
TypeError: Cannot read properties of undefined (reading 'setting')

Command:major-orders.tsx:33:37

---
30: };
31: 
32: export default function Command() {
33:   const { isLoading, assignments } = useAssignments();
34: 
35:   return (
36:     <Detail
---

_r:index.js:11:2490
    at ray-navigation-stack
Io:index.js:11:2088
```

**Comment by AlexStrNik** [comment]
@pernielsentikaer fixed

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
