### PR TITLE
Add NHL Extension

### PR DESCRIPTION
**Pull request by RobErskine**
### NHL for Raycast

Access real-time NHL scores, standings, and comprehensive player statistics directly from Raycast.

Adds the NHL extension which adds the following commands:
| Command              | Description                                                    |
| -------------------- | -------------------------------------------------------------- |
| `Search NHL Players` | Find and explore stats for both current and former NHL players |
| `NHL Standings`      | View up-to-date league standings by conference and division    |
| `NHL Scores`         | Track live scores, upcoming games, and recent results          |

## Screencast

https://github.com/user-attachments/assets/6d5be327-6dc6-4990-8895-a8bf145879ca

_Sorry for the long video; got carried away 😅. This extension doesn't require an API key, so it should be easy to test_. 

If you have any questions or anything please let me know!

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
ensionsextensionsnhl-2024-11-20-22 17 51@2x
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Really nice extension 🔥

At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension

**Comment by RobErskine** [comment]
@pernielsentikaer got ya. I knew localization wasn't supported but wanted to take a stab at it. 

Can I leave the translations file in and hardcode the existing strings in English? Trying to find the path of least resistance to getting this approved 😅

It's a holiday in the states today so I won't be able to get to it till tomorrow but I appreciate you and the rest of the raycast team! 🙏🦃

**Comment by pernielsentikaer** [comment]
Sture, keep it in the code, but we can't change it at the moment 🙂

**Comment by RobErskine** [comment]
@pernielsentikaer I went ahead and removed the language preference and set the default language to `default` so it will only ever pull in the English values. 

If you'd like for me to go back and hardcode everything instead of pulling from the `src/utils/translations.ts` file, I can do that, but that's obviously a bigger change that will take me some time. 

Thanks again!

**Comment by pernielsentikaer** [comment]
One of the commands is now crashing, could you fix that?

nhl 2024-12-03 at 07 39 36

**Comment by RobErskine** [comment]
@pernielsentikaer ack sorry about that. I was pulling the language in one other spot that wasn't using that helper function. The latest commit resolves that issue. I've gone through and tested all the views and it looks good now.

**Comment by pernielsentikaer** [comment]
Much better, do you have an idea why there is initial flicker first time you open the scores command?

https://github.com/user-attachments/assets/00931137-067d-4030-ab66-c69943436f3e

**Comment by RobErskine** [comment]
I do not... but I will look into it more in the morning for me. So you mean the initial Error view your see the first time trying to call the command?

**Comment by pernielsentikaer** [comment]
Raycast04122024-UmT0J8nV png@2x

👆 This 🙂

**Comment by RobErskine** [comment]
@pernielsentikaer ah I think this was an unintentional consequence of your ["Update nhlScores.tsx" commit](https://github.com/raycast/extensions/pull/15459/commits/e67ecd9b66326a802a54bd41986da126bd4aacd8#diff-806150d3dac836d4b87f560ece2a13b99acd5f4392b61922bf3a4832b841f7b6L22). When `if (scoreboard.isLoading) return <List isLoading={true} />;` was removed it jumps to the next line `if (!scoreboard?.data) return <Unresponsive />;` which is why the error flashed while the data was still being fetched.

I have remedied this by updating my `if` statement to include `isLoading` to fix it:
```tsx
if (!scoreboard?.data && scoreboard.isLoading === false) return <Unresponsive />;
```

I believe it should be ready to go now!

**Comment by pernielsentikaer** [comment]
I don't get that error anymore, but I'm stuck here now (tested with a clean installation)

**Comment by pernielsentikaer** [comment]
Ooooups!

nhl 2024-12-05 at 15 51 42

**Comment by RobErskine** [comment]
@pernielsentikaer thanks for sharing. i didn't know about the clean install (clear local storage and cache) thing so I will make sure to add that to my testing workflow moving forward.

I updated the helper function to return an empty response if the nhlScores request is still loading. I also added a small bugfix for an edge case for properly returning the  Swedish "🇸🇪" flag. 

I tested all commands on a fresh install and all seems to be working now. Thanks for your help with this.

**Comment by pernielsentikaer** [comment]
Let's release the first version live 🔥

**Pull request merged**
