### PR TITLE
add aws-ecr extension

### PR DESCRIPTION
**Pull request by abelkuruvilla**
## Description

Added a new extension AWS ECR to update ECR Images

## Screencast
ecr-tag-change-2

Screen Shot 2022-10-01 at 8 22 58 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @abelkuruvilla 👋 

Thanks for the contribution 💪 

Would it make sense to add it to [this extension](https://www.raycast.com/Falcon/aws) instead so we keep only having one extension?

**Comment by abelkuruvilla** [comment]
@pernielsentikaer This extension works with aws cli, whereas the other one works with aws SDK. I wanted to use SDK, but it does not support the `query` param that cli has for describe-images. Do you still think its best to combine both ?

**Comment by pernielsentikaer** [comment]
Then it might be a good idea to split it, otherwise, it would be a weird UX.

Maybe one of @victor-falcon @Hodglim @JonathanWbn @gebeto @momme-rtf @duboiss @hexpl0it knows how to do what you're doing here in the SDK?

**Comment by JonathanWbn** [comment]
I also agree that this behaviour can be integrated with the existing `amazon-aws` extension. This could be a "List ECR Repositories" command with an action to add a tag.

Even if the SDK doesn't allow for the desired behaviour, I don't see a problem with mixing SDK + CLI operations in the same extension.

**Pull request closed without merging**
