### PR TITLE
added support for JS Object

### PR DESCRIPTION
**Pull request by lacherogwu**
## Description

I added support to parse JS objects to an extension that could only format JSON objects. 
It was a cool opportunity to improve the extension and make it more useful for people who work with JavaScript objects. 
I looked at the code and made the necessary changes to handle different data types. 

I'm happy I could contribute to a project that I find useful and that I think others will too!

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaslombart — CHANGES_REQUESTED** [review]
I have trouble understanding what's possible now that wasn't possible before. From what I understand, this PR adds support for JS objects so things like comments, dates, regex, function should be possible, right?

So, I tested it with the string below but got an `Invalid Input` error.

```
{name:"John Doe",age:30,city:"New York",email:"johndoe@example.com",phone:"+1234567890",address:{street:"123 Main St",suite:"Apt 4B",city:"New York",state:"NY",zip:"10001"},hobbies:["reading","hiking","cooking"],occupation:"Software Developer",getFullAddress(){return`${this.address.street}, ${this.address.suite}, ${this.address.city}, ${this.address.state} ${this.address.zip}`;},birthdate:new Date(1993,4,15),phoneRegex:/^\+\d{11}$/}
```

Am I misunderstanding something?

**Comment by lacherogwu** [comment]
> I have trouble understanding what's possible now that wasn't possible before. From what I understand, this PR adds support for JS objects so things like comments, dates, regex, function should be possible, right?
> 
> So, I tested it with the string below but got an `Invalid Input` error.
> 
> ```
> {name:"John Doe",age:30,city:"New York",email:"johndoe@example.com",phone:"+1234567890",address:{street:"123 Main St",suite:"Apt 4B",city:"New York",state:"NY",zip:"10001"},hobbies:["reading","hiking","cooking"],occupation:"Software Developer",getFullAddress(){return`${this.address.street}, ${this.address.suite}, ${this.address.city}, ${this.address.state} ${this.address.zip}`;},birthdate:new Date(1993,4,15),phoneRegex:/^\+\d{11}$/}
> ```
> 
> Am I misunderstanding something?

It seems that you may have misunderstood the purpose of this tool. Allow me to clarify - the primary goal of this tool is indeed to prettify JSON. However, JSON does not support types like Dates, regex, functions, and so on.

Here is an example of a valid JS Object
```
{
	name: 'John Doe',
	age: 30,
	city: 'New York',
	email: 'johndoe@example.com',
	phone: '+1234567890',
	address: { street: '123 Main St', suite: 'Apt 4B', city: 'New York', state: 'NY', zip: '10001' },
	hobbies: ['reading', 'hiking', 'cooking'],
	occupation: 'Software Developer'
}
```
That said, this feature can come in handy when you have a JavaScript object in a format like the one above. This format is not JSON, mainly because of the single quotes and the keys not being wrapped in double quotes. It's a common formatting you may find in your code editor.

The feature that this PR adds enables you to take an object in this format and format it into valid JSON. This can be useful when you need to copy an object from your code editor and paste it into an HTTP client or when you receive a response from an API but forget to stringify it.

So, the tool isn't meant to support Dates, regex, functions, etc. But it does make it easier to work with JavaScript objects that are not in valid JSON format.

**Comment by lacherogwu** [comment]
@thomaslombart

**Review by thomaslombart — COMMENTED** [review]
You need to rebase your work. An update has been pushed in between.

**Comment by lacherogwu** [comment]
@thomaslombart Done ✓

**Review by thomaslombart — APPROVED** [review]

**Pull request merged**
