### PR TITLE
Add Search Companies command to the hubspot extension

### PR DESCRIPTION
**Pull request by yuanminglee**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @yuanminglee 🔥 

@harisvsulaiman do you want to check this?

**Comment by pernielsentikaer** [comment]
Did you check it yet, @harisvsulaiman, I'm unsure what the 👍 means 🙂

**Comment by yuanminglee** [comment]
It's been awhile, any way to move this forward?

**Comment by harisvsulaiman** [comment]
@pernielsentikaer Looks good to me. Please merge

**Comment by harisvsulaiman** [comment]
Thank you for the contribution @yuanminglee

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
