### PR TITLE
add color rgb feature (homeassistant)

### PR DESCRIPTION
**Pull request by altrdev**
## Description

Add one command to Home Assistant extension:

- Rgb color to Light entity

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @tonka3000 

## Screencast

https://user-images.githubusercontent.com/22495387/151591121-4443952d-f35d-412f-9d06-ea8aa4f17f7d.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by tonka3000** [comment]
@altrdev awesome contribution, thanks.

@pernielsentikaer for me this PR is fine 👍

**Comment by altrdev** [comment]
> @altrdev awesome contribution, thanks.

Thanks for your amazing extension 🔝

**Review by pernielsentikaer — APPROVED** [review]
Awesome @altrdev 💪 

Thanks for your contribution 💯  aI'm going to accept it and then will my colleague do a final review before it's finally merged.

**Comment by pernielsentikaer** [comment]
Still accepted ;0)

**Comment by sxn** [comment]
🎉

**Pull request merged**
