### PR TITLE
Update battery-optimizer extension

### PR DESCRIPTION
**Pull request by VatsalSy**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by VatsalSy** [comment]
@Qetesh the checks that you included for bclm command line was throwing an error even if I could use bclm using terminal. This issue can be easily fixed if you allow users to provide a custom bclm executable. I have added this as a preference called Custom BCLM Executable Path. For example, using /opt/homebrew/bin/bclm works for me.

**Comment by pernielsentikaer** [comment]
Hi @VatsalSy   👋

Thanks for your contribution 🔥

@Qetesh do you want to check this before merge?

**Comment by VatsalSy** [comment]
@pernielsentikaer @Qetesh 
This is only my private copy of the repo which I keep up-to-date with the actual raycast repo: https://github.com/VatsalSy/raycast-extensions/pull/1

I think the action should be done on this thread for the extension to be available on raycast. Right?

Or, did I miss something? Sorry about the confusion.

**Comment by VatsalSy** [comment]
Ok. maybe. I see how this is done. Sorry this is my first contribution to a large open source project. 🫣

**Comment by Qetesh** [comment]
It’s my first contribution to a large open source project too. I don’t have permissions for the raycast/extensions PR, so I synced my changes to the VatsalSy:ext/battery-optimizer repo. I hope I didn’t make any mistakes.

This commit is great and serves as a good solution until the weird error is clearly identified.

Thanks for your contribution!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
