### PR TITLE
[New] [Browser Tabs] Search all open browser tabs

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

- Search all open browser tabs

## Screencast

browser-tabs-1

browser-tabs-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!

Thank you so much for your contribution! My name is Milena and I will be reviewing your PR today :)

First of all, I think the name of the extension is a bit misleading: Firefox is not supported so it's not all browsers. Have you considered adding it or changing the name of the extension to "multi-browser" instead?

There's an incoherence on your README, do you mind rephrasing that?

Cheers!

**Comment by koinzhang** [comment]
Hi @mil3na The extension was named Browser Tabs to align with two other extensions, [Browser Bookmarks](https://www.raycast.com/raycast/browser-bookmarks) and [Browser History](https://www.raycast.com/crisboarna/browser-history), so I didn't really want to change the extension name. However, I have updated the description of the extension to make it clearer.

Also, the README has been changed to make it more concise

**Comment by mil3na** [comment]
Fair enough. One last thing: do you mind doing a comment cleanup? There are a few that are not adding any value or are in a language other than English. After that, I think we should be good to merge.

**Comment by koinzhang** [comment]
Have cleaned up non-English comments and some useless logs

**Review by mil3na — APPROVED** [review]
I've removed a few more comments, I hope it is okay.
LGTM!
In the future, maybe improve how errors are handled. Just keep that in mind :)

**Pull request merged**
