### PR TITLE
Add clarify extension

### PR DESCRIPTION
**Pull request by akramarev**
## Description

This simple extension allows users to interact with Clarify CRM directly from your command bar. The extension uses oAuth2 and requires just a few clicks to connect to Clarify account (users can request access at https://www.getclarify.ai/).

Currently, just a few basic commands are available through the extension:
* Add a new Company/Person
* Open Companies/People list
* Search across all records

## Screencast

Please check the screenshots below in the /metadata directory.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mil3na — CHANGES_REQUESTED** [review]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

On your README, there's a description on what Clarify is, but not what extension does or how to get it working. Could you please change that?
Also, I was not able to get a key to try this extension. Is there anyway to get one that is not waiting on the regular line?

**Comment by akramarev** [comment]
Thank you for review, Milena! I just updated readme.md file with the requested information.

Regarding the account for validation, absolutely - the service supports Google authentication only at the moment, thus I need your _gmail address_ to invite you to one of the test workspaces. Please send it to me using the email available in my GitHub profile.

**Comment by akramarev** [comment]
Milena, I also sent an invite to the @raycast.com email that most probably you used two days ago in that form.

**Comment by mil3na** [comment]
Thank you so much for the invite! I will make sure to join and review the extension early next week :)

**Comment by ondrej** [comment]
Hi Milena, I work with Andrew at Clarify, it's nice to meet you. Is there any chance you might have a moment to review our extension? Thank you!

**Comment by mil3na** [comment]
I'll do it first thing tomorrow morning!

**Comment by mil3na** [comment]
Do you mind sending an invite to milena@raycast.com? I could not access the other email in order to login with it.

**Comment by akramarev** [comment]
Sure, I sent it just now.

**Comment by mil3na** [comment]
Hi!
I finally had the opportunity to try the extension. Thank you so much for the invite and your patience.

The Create Company/People commands are working as expected and so it is the oAuth. However, this is what I get when I try the Go To People command (and I get something similar for the Go To Company)

CleanShot 2024-07-29 at 16 36 27

All three searches are empty, no matter what I search for:

CleanShot 2024-07-29 at 16 38 48

Do you mind taking a look on what happened? Did I do anything wrong? I can confirm that the things I created are represented on your website.

**Comment by akramarev** [comment]
Thanks for the thorough review, Milena. Let me address both questions.

In Clarify, People and Companies are organized inside so-called lists. One of those lists, All People/All Companies, is special and always contains every Person and Company in our users' accounts. Others are custom, and our users can create as many as they'd like to organize their contacts and customers in ways that make the most sense to their business. What you're seeing after selecting Go to People/Go to Companies are all the lists available in your account. This is an intermediate step that lets our customers pick the list they'd like to open and then be navigated directly to it on our website.

clarify 2024-07-29 at 14 26 51

Regarding search results, it's a hiccup on our side - the test account where I invited you was excluded from our search index to validate something else. I apologize and am happy to update you that the records that you created and a few more that I added today are available for search on the website and in the extension. Please check the screenshot below.

clarify 2024-07-29 at 14 23 15

**Pull request merged**
