### PR TITLE
Submit new extension: Cryptgeon

### PR DESCRIPTION
**Pull request by cupcakearmy**
## Description

This PR submits a new extension.

The extensions is my own project, [Cryptgeon](https://github.com/cupcakearmy/cryptgeon). So lets say an "official" extension.
It helps with creating and sending encrypted notes and files with Cryptgeon. The tool itself is open source and uses 100% client side encryption.

I'd be happy to get feedback.  I read through the docs and recommendations about naming, ux, etc. but if I missed something I'm happy to align with Raycast "style"

Side note: there are a few ugly `@ts-ignore` in the imports, because I have not exported the types perfectly yet from the other project, but the code works.

## Screencast

https://github.com/user-attachments/assets/6e0a9e19-7825-4616-839c-6c576ae3c1ff

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- There is some strange flickering (I can briefly see the attached file) when opening `Create Note`. Can you look into this?

- You can submit the form without anything in it, useForm has validation

- Can we get rid of ts-ignores?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Do you call it Cryptgeon or cryptgeon? It's spelled both ways in the PR

**Comment by cupcakearmy** [comment]
> Do you call it Cryptgeon or cryptgeon? It's spelled both ways in the PR

lowercase :)

thanks for the review btw!
I'm fixing the ts-ignores, and then let you know 🚀

**Comment by cupcakearmy** [comment]
@pernielsentikaer It should be all fixed :)

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Could you correct the wording in the extension if you want it lowercase, it's also okay in package.json title field

**Comment by cupcakearmy** [comment]
@pernielsentikaer done :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
