### PR TITLE
New Extension: iWork

### PR DESCRIPTION
**Pull request by SKaplanOfficial**
## Description

This extension adds commands for controlling Apple's iWork applications (Pages, Numbers, and Keynote). This first version includes commands for creating, opening, and exporting documents, minimizing windows, and creating slideshows from selected files in Finder. Additional commands will be added in the future.

The current commands include:
- **For Pages:**
  - _Minimize Pages_
    - Minimizes all Pages windows
  - _New Pages Document_
    - Creates a new blank document
  - _New Pages Document From Template_
    - Creates a new document using the user-selected template
  - _New Pages Document From Clipboard_
    - Creates a new document from the text content of the clipboard
  - _Export Pages Document_
    - Exports the current document to the path specified as an argument, in the user-selected format
  - _Open Selection In Pages_
    - Opens the selected file(s) in Pages. Displays an error alert if the file cannot be opened with Pages. This can open Pages and Word documents, plain text files, and rich text files.

- **For Numbers:**
  - _Minimize Numbers_
    - Minimizes all Numbers windows
  - _New Numbers Spreadsheet_
    - Creates a new blank spreadsheet 
  - _New Numbers Spreadsheet From Template_
    - Creates a new spreadsheet using the user-selected template
  - _Export Numbers Spreadsheet_
    - Exports the current spreadsheet to the path specified as an argument, in the user-selected format
  - _Open Selection In Numbers_
    - Opens the selected file(s) in Numbers. Displays an error alert if the file cannot be opened with Numbers. This can open Numbers and Excel documents, CSVs, plain text files, and more.

- **For Keynote:**
  - _Minimize Keynote_
    - Minimizes all Keynote windows 
  - _New Keynote Slideshow_
    - Creates a new slideshow with the default theme
  - _New Keynote Slideshow With Theme_
    - Creates a new slideshow with the user-selected theme
  - _Start Keynote Slideshow_
    - Starts the current slideshow 
  - _Stop Keynote Slideshow_
    - Stops the current slideshow 
  - _Export Keynote Slideshow_
    - Exports the current slideshow to the path specified as an argument, in the user-specified format 
  - _New Keynote Slideshow From Selected Images_
    - Creates a new slideshow from the selected image files
  - _Open Selection In Keynote_
    - Opens the selected file(s) in Keynote. Displays an error alert if the file cannot be opened with Keynote. This can open Keynote and PowerPoint documents.

## Screencast
See the YouTube video below:
[YouTube demonstration video of iWork extension](https://www.youtube.com/embed/_5JGBFTuDqU)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪

I gave it a quick spin and can see you're using `view` commands, did you consider using `no-view` instead?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Review by pernielsentikaer — COMMENTED** [review]
How does the export function work? Can you share a screencast?

I tried it without any luck 😞

**Comment by SKaplanOfficial** [comment]
There was a small issue preventing the Keynote and Numbers export commands from working, but it is fixed now. You have to provide the full path to where you want to export to. Here's a screencast: [https://youtu.be/RCQ9oQU1_N8](https://youtu.be/RCQ9oQU1_N8)

**Comment by pernielsentikaer** [comment]
Hi @SKaplanOfficial 👋 

Did you forget to add the `exportDir` to `package.json` 😊?

**Review by pernielsentikaer — APPROVED** [review]
Let's get it out! 🔥

**Pull request merged**
