### PR TITLE
Renamed extension

### PR DESCRIPTION
**Pull request by pernielsentikaer**
## Description

Renamed the extension

### CODE REVIEW

**Comment by L3K0V** [comment]
@pernielsentikaer does this mean that it's working with 1Password 7 and 1Password 8?

**Comment by L3K0V** [comment]
Nevermind @pernielsentikaer I found it, I will just reference it here: https://github.com/raycast/extensions/pull/1518

**Comment by pernielsentikaer** [comment]
Yes it does, @L3K0V - it should autodetect the version that you have, if not, then you can set it in extension preference 😄

**Comment by L3K0V** [comment]
Yes! Unfortunately I have used 1Password 7 before, and it looks that I have some left overs and the auto detection load old entries even that 1Password 8 is not configured using opbookmarks :( Later today I will try to get it working properly

**Pull request merged**
