### PR TITLE
Add table-flip extension

### PR DESCRIPTION
**Pull request by robigan**
## Description

Just adds some table flip clipboard paste commands similar to those of Discord. Yes I'm aware snippets work, but who doesn't like typing /shrug or /tableflip?

## Screencast

image

image

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
It would actually work a lot better if you just add it as a snippet and set the keyword to `/tableflip`, then it will automatically expand 🙂

Making an extension for this might be a bit overkill 🙂

**Comment by robigan** [comment]
> It would actually work a lot better if you just add it as a snippet and set the keyword to `/tableflip`, then it will automatically expand 🙂
> 
> 
> 
> Making an extension for this might be a bit overkill 🙂

I was thinking the same about it being overkill but I thought hey worth a try. Maybe someone might want it.

Although I've had random bugs at times with how snippets work so I wanted a simple extension that just used the clipboard#paste api to simply paste.

**Comment by pernielsentikaer** [comment]
If it doesn't work as expected you might need to try tweak your expand settings, try tweak `Response Time`

Raycast19062024-snCE2DvB png@2x

**Comment by mil3na** [comment]
Hi!

Thanks for your contribution! However, as you said yourself, we already provide this functionality natively with snippets. We even have a section at ray.so dedicated to Unicode snippets: https://ray.so/snippets/unicode
I'm closing this PR, but feel free to contact me on our Slack community if you want to discuss it further (https://raycast.com/community). I also encourage you to submit a more substancial extension in the future!

Cheers!

**Pull request closed without merging**
