### PR TITLE
Add aws-profiles extension

### PR DESCRIPTION
**Pull request by frese**
## Description

AWS Profiles lists all your AWS profiles from $HOME/.aws/config and let you chose one to execute a predefined command/script. This allows you to eg. open a terminal authenticating using this profile or (the default) use granted.dev assumes command to open an AWS console with selected profile.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Would this make sense to have under the [AWS extension](https://www.raycast.com/Falcon/aws)?

**Comment by pernielsentikaer** [comment]
CC @JonathanWbn 😊

**Comment by frese** [comment]
Not sure about this - my extension is very different in nature - the AWS profiles is the key of the search here.
So far you can have only one "command" to execute on the searched profile, but it would be relatively easy to extend to multiple commands, but the profile would still be the key element. I guess my extension targets people with a lot of profiles.

**Comment by JonathanWbn** [comment]
@frese I love this idea! I could use that myself at my place of work. 🎉 

I **do** think this could work well as part of the existing Amazon AWS extension. I opened #5357 to show I think we could include it. Let me know what you think!

**Comment by pernielsentikaer** [comment]
Let's close this for now, we can always open it again

**Pull request closed without merging**
