### PR TITLE
Add gmail-assistant extension

### PR DESCRIPTION
**Pull request by parikshith078**
## Gmail Assistant for Raycast

This extension adds Gmail integration to Raycast, allowing users to send emails and check their inbox without leaving the Raycast interface.

### Usage

To use the extension, you need to authorize it to access your Gmail account. When you first use the extension, you will be prompted to log in to your Gmail account and grant the necessary permissions to the extension.

#### Send Email

To send an email, type "send email" in the Raycast search bar and select the "Send Email" command. You will be prompted to enter the recipient's email address, the subject of the email, and the body of the email.

#### Check Inbox

To check your inbox, type "check inbox" in the Raycast search bar and select the "Check Inbox" command. This command will show your latest emails in your Gmail inbox, including the sender and subject of each email. You can toggle additional details for each email, such as the body and attachments, and open the email in your browser.

## Screencast
2 check-inbox
4 send-email

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by parikshith078** [comment]
I have a question about adding OAuth client ID.  Where can I add my OAuth client ID while publishing the extension?

**Comment by pernielsentikaer** [comment]
Hi @parikshith078 👋 

Could you maybe add my e-mail as a tester? Check my GitHub profile to find my e-mail 🙂

Raycast-RFs6V61b@2x

**Comment by parikshith078** [comment]
Thanks for reviewing my pull request! I have added you as a tester, using the email address listed on your GitHub profile. Let me know if you have any further questions or concerns 😊

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

#### In Check Inbox command
- I would add the title at the top of the detail pane too, since then you have it toggled you can't really see the title 🙂

- You're missing icons in the action panel (It would be nice if all actions have)

- I would make "Open in Browser" the default action and have "Toggle Details" secondary with ⌘+⇧+D as `File Search`

#### Send Email command
- Add validation, you could use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) for this

- Show a animated toast when sending, since I was confused if it was working

#### Other things?
- Maybe make some new [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) with a bit higher contrast, also the first image doesn't add any contextual value 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Pull request closed without merging**
