### PR TITLE
[gif-search] Add GIF Details metadata page and Fix GIF preview height

### PR DESCRIPTION
**Pull request by josephschmitt**
## Description

Adds a new GIF Details page that displays metadata about the gif

image

Also sets gif previews to a fixed 200px height so that the layout doesn't jump around as much when browsing through images.

Also updates the use of the attribution images based on the system theme so that they're readable in both light and dark modes.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @josephschmitt 👋 

Another awesome update, it's turning out to be an even more killer extension, I love how you keep pushing the limit!

- You should consider at hotkey for the `View Details` item too 😄 

- Is it by purpose that the `Finer Gifs Club` don't have any details in the `Viev Details`

CEChAyMFMZoG5dEM

I really love the fixed size!

Looking forward to testing it out again 💪

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by josephschmitt** [comment]
> * Is it by purpose that the `Finer Gifs Club` don't have any details in the `Viev Details`

🤦 oops, my own search engine doesn't return that metadata. I'll remove, good catch!

**Comment by josephschmitt** [comment]
@pernielsentikaer updated!

**Review by pernielsentikaer — APPROVED** [review]
Hi @josephschmitt 👋 

Thanks for the update, much better 💪 

Let's proceed! 🚀

**Pull request merged**
