### PR TITLE
Add language-switcher extension

### PR DESCRIPTION
**Pull request by MishaIvasyutyn**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Are these two identical PRs? https://github.com/raycast/extensions/pull/13511
And [Input Source Switcher](https://www.raycast.com/danulqua/input-source-switcher) do these two extensions do the same thing?

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

I have the same questions as @koinzhang  :)

**Comment by MishaIvasyutyn** [comment]
Hi Milena,

Thank you for your message!

Let me clarify the difference! The Input Source Switcher and the Language Switcher extension are different. The Language Switcher is an upgraded version of the Input Source Switcher. It automatically recognizes the language layout and switches both the text and keyboard layout to the correct language. 

In contrast, the Input Source Switcher only enables you to manually select only  one language to switch from (e.g., from English to Ukrainian).With the Language Switcher, you don’t need to manually select the language each time you make a mistake; it works automatically.

**Comment by mil3na** [comment]
If it is an "upgrade" why not add your changes in there? We want to avoid extensions doing the same thing :)

**Comment by MishaIvasyutyn** [comment]
Sorry, maybe I didn’t express myself correctly. What I meant to say is that it’s a completely different extension in terms of the codebase. It uses many components that are not important for power efficiency. For example, I don’t need a form component because I have a small, simple script. Adding an extra form would overload my code and reduce efficiency, so I can’t contribute directly to it. Additionally, my extension also switches the keyboard layout for extra consistency. 

Before writing any message, please take some time to review the actual code and compare the two extensions. You will see that my extension is not a fork of the input-source-switcher. Therefore, I cannot simply merge my changes, as it has a completely different codebase

**Comment by mil3na** [comment]
Hi! It's not about code, but about functionality. Am I wrong to assume that both extensions provide very similar value to the user?

**Comment by MishaIvasyutyn** [comment]
Yes, you are wrong.  It’s like deciding whether to cook with your left hand or your right hand—sure, you can manage with one, but why make life harder when you can use both for more convenience? My extension takes the hassle out of choosing a language for correction by automatically recognizing and switching to the right one. On the other hand, Input Source Switcher is like flipping a switch—English to Ukrainian or vice versa—no fancy footwork.

So, if you type ‘ghbdsn’ hoping it magically turns into ‘привіт,’ but you’ve got it set to Ukrainian to English, it’s a no-go. My extension, though, has got your back in both languages, no switch-flipping needed! And also forgot to mention that it's automatically switching your keyboard layout for more convenience.

**Comment by mil3na** [comment]
I still believe that you can add this functionality to the existing extension. Both have the same goal. Would that be hard?

**Comment by MishaIvasyutyn** [comment]
What wouldn't you tell someone who created this extension and got merged in the store?)) https://github.com/raycast/extensions/tree/8d0bbc486cca33bb8f2a9281a65402225fae4c3e/extensions/punto/

**Comment by mil3na** [comment]
Yes, but I was not the one who reviewed that extension.
Closing this due to duplication. If you want to discuss it further, you can find me on our Slack community https://raycast.com/community
Cheers!

**Pull request closed without merging**
