### PR TITLE
[New Extension] Directus documentation search

### PR DESCRIPTION
**Pull request by bryantgillespie**
## Description

This simple little extension searches the Directus (https://docs.directus.io) documentation.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Remove `directus-logo-256.png` since it's not in use

* follow the [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) guide to make better metadata images

* There is a bug where it doesn't go back to the initial view

https://user-images.githubusercontent.com/38033107/218834658-7c470ace-4994-4935-ad5a-776a3f713198.mp4

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by bryantgillespie** [comment]
Thanks for the feedback. Will work on these changes. Didn't notice the bug you shared.

One question for you on this bit though...
> follow the [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) guide to make better metadata images

Specifically what's wrong with the existing images?

I couldn't get the the Raycast Screen Capture working as outlined in the guide so I just took the screenshots using Cleanshot and edited them to the listed size / aspect raio.

**Comment by pernielsentikaer** [comment]
Awesome @bryantgillespie 🔥 

I only said it because I saw the green development icon in the metadata images when using the built-in tool 😊 You don't need to make new images - out of curiosity, what error do you get?

**Comment by bryantgillespie** [comment]
> I only said it because I saw the green development icon in the metadata images when using the built-in tool 😊 You don't need to make new images - out of curiosity, what error do you get?

I wasn't getting any error - it just wasn't loading the image capture while using the hotkey. Uninstall and re-install seem to have fixed it. Could have been something with the Mac system permissions maybe? 

At any rate working now, images updated and bug fixed.

**Comment by pernielsentikaer** [comment]
Awesome work @bryantgillespie 🔥 

One last ting, can we move media/directus-docs-search.gif somewhere else so we not add 3MB++ extra in the repo, you can just link to it from another place 😊

**Comment by bryantgillespie** [comment]
Killing me here @pernielsentikaer  😆 
GIF removed from the repo, but adding one here.



Let me know if we need anything else.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Comment by bryantgillespie** [comment]
Awesome! Thanks @pernielsentikaer. Appreciate you 👏

**Pull request merged**
