### PR TITLE
New extension :  Open in Visual Studio Code

### PR DESCRIPTION
**Pull request by shubzkothekar**
## Description

Open current Finder directory, selected folder or file in Visual Studio Code.

## Screencast

[screencast.webm](https://user-images.githubusercontent.com/19603503/185805868-be8ffd4e-aa03-4272-bca6-7bd216c8ab47.webm)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
@shubzkothekar great first contribution! The functionality that you built in AppleScript is available in our API as well. I changed your code to use the API instead. This has the benefits that it's faster and easier to maintain. Plus, it supports multi-selection.

Please take a look and let me know if that works for you. Then we can merge it. Another alternative would be to add a new command to the [Visual Studio Code Recent Projects extension](https://www.raycast.com/thomas/visual-studio-code) and rename it. But not sure if we need to have that at this point.

**Comment by shubzkothekar** [comment]
Hey, @thomaspaulmann Thanks for your feedback and replacing AppleScript with Raycast's API. `getSelectedFinderItems` is not documented on the website, so I didn't know about its existence.

I am okay with the current implementation, except there is one functionality missing. If no finder item is selected, then this command should open the active finder window in Visual Studio Code. Do we have an API for getting the path of the current active finder window? If not, then can I use AppleScript to implement this missing functionality alongside the current updated code? What do you suggest?

**Comment by thomaspaulmann** [comment]
You can find the docs [here](https://developers.raycast.com/api-reference/environment#getselectedfinderitems). 

Oh, I missed that. We don't have an API for that but you can do that with AppleScript yes. Just not sure if you need it because I would assume you use the extension only with an active Finder window anyways?! I leave it up to you.

**Comment by thomaspaulmann** [comment]
Can you fix the linters, then we should be good to go.

**Comment by shubzkothekar** [comment]
Done

**Comment by thomaspaulmann** [comment]
Congrats to your first extension in the store 👏

**Pull request merged**
