### PR TITLE
[AWS] Revamp extension

### PR DESCRIPTION
**Pull request by JonathanWbn**
This is a general revamp of the Amazon AWS extension with the goal of making this extension more enjoyable to use and easy to contribute to.

### Simpler UI/UX
- new icons leveraging [Raycast's built-in icon set](https://developers.raycast.com/api-reference/user-interface/icons-and-images?q=icon#icon)
- simplified accessories (one well-formatted info per item)
- consistent list item actions
- improve copy throughout the extension

### Cleaner Codebase
- remove unused dependencies
- improve code readability
- use a similar code structure for each command
- simplify data fetching of SQS queue attributes

### Fixes
- avoid fetching data before the profile is initialized
- explicitly use region for fetching S3 bucket objects (@duboiss this _might_ fix [your issue](https://github.com/raycast/extensions/pull/3612#issuecomment-1330336103))

### Rebranding

I believe the AWS extension is a perfect use case for Raycast and I would love it if more people discovered it.

- new command icon using [Raycast's generator tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#extension-icon)
- updated screenshots
- new readme
- improved extension/command copy in `package.json`

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
That's a solid update 🔥 I don't have any credentials at the moment but would like if some of you could test it 😊

**Comment by robertkossendey** [comment]
Great Update, love it so far. Everything seems to be working on my side :)

**Comment by pernielsentikaer** [comment]
@victor-falcon do you mind checking this? 😊

**Comment by Hodglim** [comment]
Working great for me too, really nice update! 🔥

**Comment by JonathanWbn** [comment]
@pernielsentikaer I've been using this version at work for the past week and it is working well. Could we get this merged?

**Comment by pernielsentikaer** [comment]
Yes we can @JonathanWbn 🔥

**Pull request merged**
