### PR TITLE
[Bark] Command optimisation

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

- Command optimisation for faster message sending

## Screencast

bark-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
And we can't keep the old names and just update the titles)

I hate to break aliases, hotkeys and ranking for that purpose

**Comment by koinzhang** [comment]
So I can keep the name the same and change the title?
Is raycast using name as a command identifier?

**Comment by koinzhang** [comment]
I've changed the name of the command back, please continue to review it

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
