### PR TITLE
Update todo list extension

### PR DESCRIPTION
**Pull request by ridemountainpig**
## Description

- Added an action to set a tag for a todo item.
- Added a dropdown filter to filter todo items by tag.

Added these two features for issue #13464. Users can now add tags to their todo items and use a dropdown filter to filter the todo items, allowing them to manage multiple lists with tags.

## Screencast

https://github.com/user-attachments/assets/f5c92665-541e-449f-934c-da308745d44b

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I really like the idea, but I'm a bit afraid for the UX here. Maybe it would make more sense to change to a new view instead?

What do you think @maggie-j-liu

**Comment by ridemountainpig** [comment]
> Maybe it would make more sense to change to a new view instead?

I think putting all the tasks on a single page and filtering them with a dropdown menu is more convenient than splitting the tasks into separate views. Dividing the tasks into multiple views could complicate the user experience, and managing the to-do list across multiple pages may be inconvenient.

**Comment by ridemountainpig** [comment]
Hello @pernielsentikaer, do you have any new suggestions for this pull request?

**Comment by pernielsentikaer** [comment]
I was referring to the element `Added an action to set a tag for a todo item` - don't you think switching to a new form view is better? I'm just afraid that I might miss that the search bar changes

**Comment by ridemountainpig** [comment]
> I was referring to the element `Added an action to set a tag for a todo item` - don't you think switching to a new form view is better? I'm just afraid that I might miss that the search bar changes

@pernielsentikaer I have changed the edit tag into a form view. Please check. Thank you.

https://github.com/user-attachments/assets/ab0d2bba-091f-4e10-ad52-a5115321e40e

**Comment by pernielsentikaer** [comment]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
