### PR TITLE
Elgato: Add extension to toggle key lights

### PR DESCRIPTION
**Pull request by thomaspaulmann**
## Description

I converted my [script commands](https://github.com/raycast/script-commands/tree/master/commands#elgato) to control my Elgato Key Light to an extension. This has two benefits:
1. Folks can easily find and install it from the Store
2. Folks no longer need to figure out the IP of their lights, it works now automagically thanks to Bonjour discovery

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/12066405/145231321-000e5e9f-dc95-4294-b360-c6eb9d899a49.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Awaiting pushes from @thomaspaulmann

**Comment by thomaspaulmann** [comment]
> Awaiting pushes from @thomaspaulmann

The pressure is on 😅

**Comment by pernielsentikaer** [comment]
> > Awaiting pushes from @thomaspaulmann
> 
> The pressure is on 😅

No rush at all 😄 

image

**Comment by thomaspaulmann** [comment]
Fix pushed to show a HUD instead of a toast.

**Comment by mattisssa** [comment]
Hey @pernielsentikaer! How is it going with the PR? Looks like it is ready for review 🚀 
I don't have the Elgato key lights, the only I can check is that the errors shown properly for me 😄

**Comment by pernielsentikaer** [comment]
Hi @thomaspaulmann 🔥 

Much better 🚀 Let's get it merged 💯

**Pull request merged**
