### PR TITLE
Add swift-repl extension

### PR DESCRIPTION
**Pull request by nakajima**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Do I need something special to get this extension working?

swift-repl 2024-05-06 at 11 26 27

**Comment by nakajima** [comment]
@pernielsentikaer Hey sorry about that, I think I accidentally lost the `repl` argument when I was finagling typescript. Just pushed a fix.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You can hit enter without any query, that should maybe give a failure toast instead?

- If output is to long, then there is no way to see it, maybe include a detail view in the list?

- Is it possible to run "evil" code?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by nakajima** [comment]
> You can hit enter without any query, that should maybe give a failure toast instead?

Updated to just do nothing if the user hits enter without a query, I feel like a full blown error might be too much there? I don't feel incredibly strongly about this tho.

> If output is to long, then there is no way to see it, maybe include a detail view in the list?

Great call, added it and it's much nicer. 

> Is it possible to run "evil" code?

Yes.

I updated the screenshots but I'm not entirely sure how to add them to this PR since I don't see this branch when I pull this repo?

swift-repl-1
swift-repl-2

**Comment by pernielsentikaer** [comment]
You can simply just add the new images in your local branch https://github.com/nakajima/raycast-extensions/tree/ext/swift-repl

**Comment by pernielsentikaer** [comment]
Could we add a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) with rememberUserChoice so we let the user know that they shouldn't run code they dont trust, and then they can tick not to show it again?

**Comment by nakajima** [comment]
Ok, screenshots updated and I added the alert in https://github.com/raycast/extensions/pull/12104/commits/930ab78cbf62d4001621e90d5ee2562a403e4d62.

**Comment by nakajima** [comment]
@pernielsentikaer Anything you think needs to be done here?

**Comment by pernielsentikaer** [comment]
I added the possibility to clear search bar upon submit (as preference) - Could you check that I didn't break something 🙂

**Comment by nakajima** [comment]
> I added the possibility to clear search bar upon submit (as preference) - Could you check that I didn't break something 

LGTM!

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
