### PR TITLE
Add dolar-hoy extension

### PR DESCRIPTION
**Pull request by GustavoCarvallo01**
## Description

This extension is a utility for doing quickly conversions between USD and ARS. Has some basic features like: seeing the current value, get a historical value and doing value conversions. 

## Screencast

dolar-hoy-5
dolar-hoy-4
dolar-hoy-3
dolar-hoy-2
dolar-hoy-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The extensions crashes If I don't select a date, maybe check before continue - you can maybe use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) for that (which has nice validation) 🙂 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
It's not possible to pass validation if you first tries to submit without a date, could you look into this too?

https://github.com/raycast/extensions/assets/38033107/62befb41-9787-4595-b5dc-4c6d6d3ee8b2

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by GustavoCarvallo01** [comment]
> It's not possible to pass validation if you first tries to submit without a date, could you look into this too?
> 
>  Raycast11032024-jrnAOYyE.png.mp4 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Thanks for catching this, the problem was that the error message was not getting updated (you need a date and also the date should be in the past).

**Comment by GustavoCarvallo01** [comment]
Hi @pernielsentikaer 👋  
I just changed that but it seems I cannot ask for new review 🤔

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
