### PR TITLE
Add Disk utility extension with Create and Show Volumes command(s)

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- Adds "Create Volume" command to create APFS encrypted and case-sensitive volumes with extra features like symlinks etc.
- Adds "Show Volumes" command to get details for volumes and perform operations.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

Wouldn't it make sense to have a list command as well?

**Comment by jfkisafk** [comment]
> Wouldn't it make sense to have a list command as well?

Hello @mil3na, thanks for taking a look! The volumes are in plist format and I am trying to come up with a list command (with delete action). It might require more time and we can tackle the list command in future iterations, starting with "Create Volume" and "Quick Create Volume" for now. What do you think?

**Comment by jfkisafk** [comment]
> Wouldn't it make sense to have a list command as well?

Hello @mil3na, thanks for the feedback! I have added the Show Volumes command along with a Delete action, can you please take a look when you find some time?

**Comment by jfkisafk** [comment]
The PR is ready to be reviewed!

**Review by mil3na — APPROVED** [review]
Works like a charm! Good job!

**Pull request merged**
