### PR TITLE
New extension OpenJike

### PR DESCRIPTION
**Pull request by sxzz**
## Description

New extension OpenJike

The GUI version of [Jike CLI](https://github.com/open-jike/jike-cli). Submit and browse posts of OpenJike.

## Screencast

openjike-1
openjike-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by sxzz** [comment]
@danielsequeira Hi, what should I do for the next step?

**Comment by danielsequeira** [comment]
Hi @sxzz,

Nothing really, we just have a huge backlog of extensions to review atm, but I think we will get to your in the next few days.

Thanks for the patience 🙏

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @sxzz 👋 

Thanks for your contribution 💪 

At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

When this is corrected I'm ready to continue the review.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by sxzz** [comment]
@pernielsentikaer Thanks for your review. I see, but OpenJike is a platform like Twitter or [Weibo](https://weibo.com/). It is a Chinese website, so many words are Chinese. To avoid confusing users, it is best to keep the Chinese language.

**Comment by pernielsentikaer** [comment]
Hi @sxzz 👋 

I do fully understand why you want to do that, but it's not allowed in Raycast for now 😥. If you want to continue adding it to the store it has to be changed

**Pull request closed without merging**
