### PR TITLE
Update tinypng extension

### PR DESCRIPTION
**Pull request by j3lte**
## Description

- Make the `method` in `Resizing Images` a Dropdown instead of a Text Field
- Fix the resize method for `scale`, where width and height are not both required
- In case a user sets the `Destination Folder Path` to the same folder, but doesn't enable `Overwrite Original Image File`, add `.compressed` or `.resized` to the file name to avoid overwriting the original file
- Update dependencies

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by j3lte** [comment]
> Note: Getting an error when resizing, figuring that one out before setting it to ready to be reviewed...

**Comment by j3lte** [comment]
@kawamataryo the PR is ready for review now, had to also fix a bug in the scaling command 😄

**Comment by kawamataryo** [comment]
Great! Thank you!

**Review by pernielsentikaer — APPROVED** [review]
✅ Approved

**Pull request merged**
