### PR TITLE
Update torr-manager extension

### PR DESCRIPTION
**Pull request by danniuz**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by dannius** [comment]
Hi! just small improvements from feedback, torrents in Jackett parser might have Url Or Magnet links, so here i just added magnet links support.

Also marked Jacket Api Key as not required argument, since some public servers might not have key.

Thanks :)

**Comment by dannius** [comment]
Hi! just small improvements from feedback, torrents in Jackett parser might have Url Or Magnet links, so here i just added magnet links support.

Also marked Jacket Api Key as not required argument, since some public servers might not have key.

Thanks :)

**Comment by dannius** [comment]
Hi! just small improvements after feedback:
- torrents in Jackett parser might have Url Or Magnet links, so here i just added magnet links support.
- marked Jackett Api Key as not required argument, since some public servers might not have key.

Thanks :)

Ps, ready to merge if its ok after review

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
