### PR TITLE
initial commit - google-fonts extension for raycast

### PR DESCRIPTION
**Pull request by GastroGeek**
## Description

New Extension. Google Fonts allows you to search all Google Fonts (via image previews in a grid), select your desired variants and export the corrosponding HTML in either `@import` or `<link>` syntax

## Screencast

https://user-images.githubusercontent.com/16214942/180869469-4cfee797-a70d-49b9-bfbb-18209db58f40.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by GastroGeek** [comment]
Realise i've added a few commits since the initial one... it's mostly fixes for little bugs I've noticed whilst using it (and have now taken note of the 'draft' option for next time). Thanks and sorry for the spam 😅

**Comment by yug2005** [comment]
Hi I had a look at the code. You are storing the font information in `fonts.tsx` and the font images in the assets folder. Would new fonts added to google fonts show in the extension?

**Comment by yug2005** [comment]
Could you perhaps use background refresh to fetch the fonts every day? See [Scheduling Commands](https://developers.raycast.com/information/background-refresh#scheduling-commands).

**Comment by GastroGeek** [comment]
Sadly not. As per my previous comment - whilst that might take care of the 'definitions' portion of it, it won't provide an updated list of images to render for any new fonts/font-changes in those definitions... (since they are nothing to do with Google's APIs and come from another completely independent source that is not available via an API).

**Comment by yug2005** [comment]
Where did you fetch the font images from? I am assuming you used some script to download them in the first place so there is a pattern to the font image urls? Instead of downloading them, maybe you could directly use the url to display them.

**Comment by danielsequeira** [comment]
@GastroGeek I would love to review this PR, but I can't open the files tab, I keep getting the 🦄

**Comment by GastroGeek** [comment]
@danielsequeira hmm. unless there is some GitHub specific issue going on at the moment i can only assume its due to there being a large number of 'font preview' images included in the PR? (since there are rather a lot of Google Fonts available). Perhaps consider viewing locally?

**Comment by danielsequeira** [comment]
I had to check it locally indeed @GastroGeek. Could you please condense your Changelog in one entry since this is the first time the extension is published and also updated it with today's date?

**Pull request merged**
