### PR TITLE
[Music] Beta Version

### PR DESCRIPTION
**Pull request by rawnly**
## Description
The new music extensions is finally here. 
Sorry for having ignored some issues, I'm currently super busy with my main job and I'm neglecting my side projects... 

Anyway, I'd love to merge this as separate extension until it's fully stable. I've introduced new features and integrated the apple music api where possible. 

This extension finally introduces the menu bar item too. 

Before merging this as drop-in replacement of the Music extension I need to test this with different environments / locales. 

Also the extensions is missing a few old commands still. I hope that this can give others the opportunity to contribute and help me fixing some bugs too :)

## Screencast
music-1
music-2
music-3

music-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Rawnly** [comment]
Hey @pernielsentikaer can you have a look?

**Comment by pernielsentikaer** [comment]
Hi @Rawnly 👋 

That looks like a massive update 🚀 

Regarding the login procedure, is there no way to do this directly to Apple instead, users (like me) are always a bit uncomfortable with authenticating my Apple Music account on a third-party website.

We do have [oAuth](https://developers.raycast.com/api-reference/oauth) and also host a few proxies ourselves.

**Comment by Rawnly** [comment]
Hi @pernielsentikaer, unfortunately [apple doesn't provide any other way to login.][0]. 

But the whole server is available as [public repo][1].

There's no other way to achieve that since to perform the login the MusicKit JS library must be used in order to generate the authentication url :/ 

I also tried to do some reverse-engineering but the code is minified and compiled so as you know it's kinda hard to understand something. (Apple checks the origin of the jwt too to see if it has been generated by a trusted entity)

Useful links:
- [User Authentication][0]
- [website repo][1]
- [Generating Developer Tokens][2]

[0]: https://developer.apple.com/documentation/applemusicapi/user_authentication_for_musickit
[1]: https://github.com/Rawnly/raycast-music.app
[2]: https://developer.apple.com/documentation/applemusicapi/generating_developer_tokens

**Comment by Rawnly** [comment]
Hey @pernielsentikaer any feedback so far?

**Comment by Rawnly** [comment]
Any chance to get this merged?

**Comment by absir1949** [comment]
I like this extension!

**Comment by mathieudutour** [comment]
Hey 👋

We discussed this internally and we don't really want people to host proxies themselves.

So what we can do is:
- keep your marketing page on https://raycast-music.app if you'd like
- use the `OAuth` flow provided by the raycast API instead of using a custom `Login` command (even if Apple doesn't provide OAuth, the proxy could act as such)
- create a trimmed down version of the proxy (ideally based on https://github.com/mathieudutour/pkce-proxy with a page where you would load the MusicKit JS library) which we will host on our server

How does that sounds?

**Comment by rawnly** [comment]
Hey @mathieudutour, sounds good! I'll explore this solution further in the next weeks. Can I contact you on slack if needed?

**Comment by mathieudutour** [comment]
Absolutely 👍

**Comment by ishaanrathodd** [comment]
Hi! Exactly the extension i was looking for! But i don't see it available on the raycast store. When will it be launched on the store?

**Comment by rawnly** [comment]
> Hi! Exactly the extension i was looking for! But i don't see it available on the raycast store. When will it be launched on the store?

Hi i'm currently out for summer holidays.
Realistically i'll have some time to work on this after the summer. I'm full of work until then. In the meantime check out the current version [here](https://raycast-music.app)

**Comment by ishaanrathodd** [comment]
> > Hi! Exactly the extension i was looking for! But i don't see it available on the raycast store. When will it be launched on the store?
> 
> Hi @ishaanrathodd i'm currently out for summer holidays. Realistically i'll have some time to work on this after the summer. I'm full of work until then. In the meantime check out the current version [here](https://raycast-music.app)

Ah thats fine, take your time.

**Comment by octoxan** [comment]
This looks great! Awesome work! Any chance we can keep a command around to both dislike and skip a track in one command? Such a time saver.

**Comment by rawnly** [comment]
> This looks great! Awesome work! Any chance we can keep a command around to both dislike and skip a track in one command? Such a time saver.

absolutely

**Comment by brandonkboswell** [comment]
Any chance of this getting merged? I hate searching the Apple Music app and this looks like it will solve that.

**Comment by rawnly** [comment]
> Any chance of this getting merged? I hate searching the Apple Music app and this looks like it will solve that.

still wip, atm i have no time to work on this :( , the server should be fine I just need to update the extension in order to support OAuth from raycast

**Pull request closed without merging**
