### PR TITLE
Update youtube-music extension

### PR DESCRIPTION
**Pull request by gnosticdev**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for the contribution 🔥 

It sounds like a nice update, could we add [disabledByDefault](https://developers.raycast.com/information/manifest#command-properties) to the commands so it doesn't feel that crowded? We're doing similar in the Spotify extension 🙂

**Comment by gnosticdev** [comment]
I added to the new commands I added, if you want it for all of them just let me know . Thanks!

**Comment by pernielsentikaer** [comment]
@danieldbird could you check this 🙂

**Review by pernielsentikaer — APPROVED** [review]
Tested OK, let's merge ✅

**Pull request merged**
