### PR TITLE
NBA: Use cache

### PR DESCRIPTION
**Pull request by thomaspaulmann**
## Description

I make use of the new Cache APIs to speed up the commands. While I was there, I also did a few minor adjustments to actions and inverted the list-detail view option.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by AbhinavPalacharla** [comment]
Looks good, thanks for the early access to cache @thomaspaulmann  😁

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @thomaspaulmann 👋 

I get this error when using the command `View Upcoming Games`
CleanShot 2022-07-01 at 09 16 23@2x

Could you have a look?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by thomaspaulmann** [comment]
Looks like now that the season is over, some fields might be optional. I'll take a look!

**Comment by pernielsentikaer** [comment]
@thomaspaulmann when you have time, can you then give it a spin? I'm a bit unsure actually if it works as expected since I don't know how data look.

**Comment by pernielsentikaer** [comment]
@thomaspaulmann could you check this?

**Comment by thomaspaulmann** [comment]
@pernielsentikaer I took another stab at it. Can you check again? I also switched to our `@raycast/utils` that provides caching out of the box and cleaned up a few things while migrating.

**Review by pernielsentikaer — APPROVED** [review]
The only weird thing now is the match that keeps hanging, but it's also like that in the source where data is received from: http://cdn.espn.com/core/nba/schedule?dates=20220815

Let's get it merged 🔥

**Pull request merged**
