### PR TITLE
New Extension: 1-Click Confetti 🎉

### PR DESCRIPTION
**Pull request by peduarte**
## Description

A Confetti Menu Bar Extension to shoot confetti with a single click. Followed by a croud cheering.

## Screenshots

screenshot-1

screenshot-2

screenshot-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

---

TODO:
- [x] will add preferences to disable sound as a next PR (done in here!)

### CODE REVIEW

**Comment by peduarte** [comment]
Ah, failed. I'm out now but will fix when i'm back

**Comment by peduarte** [comment]
Ready

**Comment by peduarte** [comment]
added preferences to enable sound 
image

**Review by pernielsentikaer — APPROVED** [review]
Hi @peduarte 👋 

Thanks for the contribution 💯 

For now, I have removed the metadata images since we haven't tackled this part yet.

We're planning a new Figma template to support extensions that only have a menubar, but we're not yet ready with that; I'll try to keep you updated when we have a good solution for this 🙂

**Comment by peduarte** [comment]
@pernielsentikaer sgtm!

**Pull request merged**
