### PR TITLE
Update mute-microphone extension

### PR DESCRIPTION
**Pull request by alexcamlo**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @thewinger 

There is no HUD/toast when I enter a wrong number. Shouldn't it do that? (Just like when an error happens)

@quentin23soleil do you want to check this?

**Comment by thewinger** [comment]
> Thanks for your contribution @thewinger
> 
> There is no HUD/toast when I enter a wrong number. Shouldn't it do that? (Just like when an error happens)
> 
> @quentin23soleil do you want to check this?

You mean in the config or where? If you put a number below 0 or above 100 in the command, it shows a HUD with the error. Not sure how to do that in the configuration area.

**Comment by pernielsentikaer** [comment]
I'm not sure what happened 🙂

When using "hello" as input you'll get a HUD, when you enters 5 there is no input, Raycast just closes, could you add the HUD or toast there as confirmation?

**Comment by thewinger** [comment]
> I'm not sure what happened 🙂
> 
> When using "hello" as input you'll get a HUD, when you enters 5 there is no input, Raycast just closes, could you add the HUD or toast there as confirmation?

Ah! Yes! My bad.
I was looking at the number in my sketchybar plugin, so I didn't think about adding a confirmation message. 

Added!

**Comment by pernielsentikaer** [comment]
Sorry for the poor explanation; I'm not sure if I was half asleep when I wrote it 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by iamyeizi** [comment]
😬 @thewinger 

CleanShot 2024-10-15 at 11  17 28

"Audio input set to 0"? wouldn't it be better to trigger the main toast, I think?

**Comment by thewinger** [comment]
I don't really understand the issue of the second video.
Clicking on 'Set default level' from the menubar opens the settings window to change the level number. The command only triggers from Raycast window.

**Pull request merged**
