### PR TITLE
[1-Click-Confetti] Add confetti with sound command

### PR DESCRIPTION
**Pull request by velios**
## Description

Add raycast confetti command, so you can set hotkey to run confetti with sound. It's so inspirational. 
I want to make it more often with hotkey.

Also small refactoring to make the changes look appropriate.

### CODE REVIEW

**Comment by peduarte** [comment]
Can we just update the Changelog please? Thanks!

**Comment by velios** [comment]
@peduarte Changelog updated

**Comment by velios** [comment]
@peduarte What now needs to be done to ensure that the changes get into the main branch?

**Comment by peduarte** [comment]
@velios thanks for your contribution!

**Pull request merged**
