### PR TITLE
[Easydict v2.7.0] ✨ Use list tag accessory to show exam type

### PR DESCRIPTION
**Pull request by tisfeng**
### 💎 Improvement

- Improved the display of word exam collection level, use tag label display.

### 🐞 Fixes

- Fixed the problem that the input text was not displayed when querying from arguments.

It seems Raycast API bug, if not use setTimeout, the `searchText` will not be updated when value is from `Arguments`.  Maybe you guys need to verify this problem.

## Screencast

easydict-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
How can I test this error @tisfeng, can you give me a guide?

**Comment by tisfeng** [comment]
@pernielsentikaer If you have any other questions, please let me know.

**Comment by pernielsentikaer** [comment]
> It seems Raycast API bug, if not use setTimeout, the searchText will not be updated when value is from Arguments. Maybe you guys need to verify this problem.

Can you make me a repro guide on how to test this issue?

**Comment by tisfeng** [comment]
I've uploaded a bug test branch https://github.com/tisfeng/Raycast-Easydict/tree/easydict-bug-3917, you can run it directly and follow these steps to reproduce the bug I'm talking about

1. enter the query text using the `arguments` type, such as `log`, and enter.
2. At this point the extension has worked, but the `searchText` is not displayed, this is the bug.

As a comparison, you can follow the above steps, also on my PR branch https://github.com/raycast/extensions/pull/3917, because my PR branch uses a temporary fix, so it can show the `searchText` properly.

image

**Comment by pernielsentikaer** [comment]
checking this soon

**Comment by pernielsentikaer** [comment]
Hi @tisfeng 

Sorry for the long response time; I missed my notifications on this PR

The high amount of console logs exhausts the API's internal message buffer, and that's why it's not working. We're considering increasing this buffer, however, reducing logs or maybe adding a global flag for disabling them would work in development.

I tested it by removing all `console.logs` and replacing:

```
setTimeout(() => {
           updateInputTextAndQueryText(trimQueryText, false);
         }, 20);
```

with
```
updateInputTextAndQueryText(trimQueryText, false);
```

**Comment by tisfeng** [comment]
@pernielsentikaer Yes, you are right, the problem was indeed caused by the `console.log`, and after I disabled it, there was no more problem.

Finally, I hope you can increase the API message buffer, after all, many times the `console.log` is still very useful in a development environment.

**Comment by pernielsentikaer** [comment]
Actually in production we remove `console.logs` so it's not a problem there, it's more a problem when developing the extension and want the logs, can you add a flag in the code to fast toggle while debugging?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
