### PR TITLE
Update tower extension

### PR DESCRIPTION
**Pull request by sebduggan**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tdwesten** [comment]
Hi @sebduggan nice addition. Thanks!

**Comment by sebduggan** [comment]
It seemed a pretty good solution to the inability to use Warp as an alternate terminal for opening from within Tower...

Not sure why some existing icons have been modified in the PR - they weren't modified or included in my git commit!

**Comment by grzegorzkrukowski** [comment]
Sorry @sebduggan, but meanwhile testing some modifications on CI actions, I messed up your PR :(
Now that PR is closed I don't have permission to fix it anymore - do you mind either giving me permissions to fix it in your branch, or fix it on your end so we can re-open this PR?

This should bring back the changes on your branch:
`git cherry-pick b292a6eaf06bde1ad0d191a3be893f7aa106efc7`

Then you need to push it again, so I can reopen it. Sorry for inconvenience.

**Comment by sebduggan** [comment]
@grzegorzkrukowski Have added you as a collaborator on my branch, let me know if you need anything else

**Comment by sebduggan** [comment]
@grzegorzkrukowski That seems to have lost the new icon (maybe my comment above was misleading...)

icon-warp.png was new and added; the others in the original PR seemed to be randomly modified.

**Comment by grzegorzkrukowski** [comment]
> @grzegorzkrukowski That seems to have lost the new icon (maybe my comment above was misleading...)
> 
> icon-warp.png was new and added; the others in the original PR seemed to be randomly modified.

Yes sorry, I just fixed it

**Pull request merged**
