### PR TITLE
[Update Obsidian Extension] Add Daily Note command, restructure code

### PR DESCRIPTION
**Pull request by marcjulianschwarz**
## Description

Added `Daily Note` command which uses Obsidians "Advanced URI" and "Daily notes" plugins. Closing #612, [this issue](https://github.com/marcjulianschwarz/obsidian-raycast/issues/11) and probably [this one](https://github.com/marcjulianschwarz/obsidian-raycast/issues/12) too.
Added new shortcut `Append selected text` to `Search Note` command.
Restructured code for better extendability, makes contributions easier too.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by marcjulianschwarz** [comment]
I am trying to use the [Action component](https://developers.raycast.com/api-reference/user-interface/actions). Importing it will throw a typescript error, ignoring the error with `@ts-ignore` isn't allowed.

Any idea on how to import the component or create a custom action without it?

**Comment by pernielsentikaer** [comment]
Hi @marcjulianschwarz 👋 

Thanks for the update, I did a review and have some suggestions for you to look into 😄 

> I am trying to use the [Action component](https://developers.raycast.com/api-reference/user-interface/actions). Importing it will throw a typescript error, ignoring the error with @ts-ignore isn't allowed.

You should update `@raycast/api` in package.json to version ^1.31.0 - this is the [latest release](https://developers.raycast.com/changelog#1.31.0-2022-03-23) where alot have changed, also Action as you noticed 😄 

 OpenAction, CopyToClipboardAction, PasteAction, PushAction and ToastStyle are all deprecated and needs to be updated - you can use https://developers.raycast.com/ to look up the new methods, let me know if you need anything at all 💪 

When using the new `Daily Note` command, I just get this error:

mvgUT3pHQ821dunV

```
2022-03-30 23:16:18.792 F  Raycast[830:122f8d] [com.raycast.extensions.obsidian:dailyNoteCommand] The above error occurred in the <Command> component:

    at null.Command (/Users/pernielsentikaer/Documents/extensions/extensions/obsidian/src/dailyNoteCommand.tsx:8:19)
    at Ir (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:2460)
    at ray-navigation-stack
    at ci (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:2088)
    at ai (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:23:514)
    at ray-root
    at Go (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:2829)

React will try to recreate this component tree from scratch using the error boundary you provided, InternalErrorBoundary.
2022-03-30 23:16:18.793 F  Raycast[830:122f99] [com.raycast.extensions.obsidian:dailyNoteCommand] The above error occurred in the <Command> component:

    at null.Command (/Users/pernielsentikaer/Documents/extensions/extensions/obsidian/src/dailyNoteCommand.tsx:8:19)
    at Ir (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:2460)
    at ray-navigation-stack
    at ci (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:2088)
    at ai (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:23:514)
    at ray-root
    at Go (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:2829)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
2022-03-30 23:16:18.836 F  Raycast[830:122f99] [com.raycast.extensions.obsidian:dailyNoteCommand]
Error: ENOENT: no such file or directory, open '/Users/pernielsentikaer/Desktop/test/.obsidian/community-plugins.json'

Object.openSync:node:fs:585:3
Object.readFileSync:node:fs:453:35
<anonymous>:dailyNoteCommand.tsx:10:10
    at Array.filter (<anonymous>)
Command:dailyNoteCommand.tsx:8:19
renderWithHooks:react-reconciler.development.js:5637:22
mountIndeterminateComponent:react-reconciler.development.js:7757:17
beginWork:react-reconciler.development.js:8544:18
Object.invokeGuardedCallbackProd:react-reconciler.development.js:9535:14
invokeGuardedCallback:react-reconciler.development.js:9622:35
```

We now have support for [categories](https://developers.raycast.com/basics/prepare-an-extension-for-store#categories), [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) and [changelog](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) – do you have time for adding this too

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by marcjulianschwarz** [comment]
Hi @pernielsentikaer 

I updated all the code to work with the new  Raycast API.
The error you mentioned should be fixed too and I added a category, changelog and screenshots. 

One question concerning the screenshots. Should I add some images where you can see the actions? Like these two:

Search Note Actions 1
Search Note Actions 2

**Comment by fe9lix** [comment]
Hey @marcjulianschwarz – showing the actions might indeed be nice in the screenshots. Btw, there's another thing that should be addressed before the merge: please use title-case style in all action titles, e.g. "Copy note content" should be "Copy Note Content", also see the [store guidelines on this](https://developers.raycast.com/basics/prepare-an-extension-for-store#action-panel).

**Comment by marcjulianschwarz** [comment]
Hey @fe9lix and @pernielsentikaer,
Thanks for your input on the screenshots. 

I updated the actions to follow title-case style, will have to update the screenshots too.

With the newest commit I added a new preference for the `Append Selected Text to Note` action which allows you to specify a prefix for the appended text.
That way you can quickly update a list (e.g. with `-` as prefix to trigger markdown list items).

**Comment by pernielsentikaer** [comment]
Hi @marcjulianschwarz 👋 

If I don't select a text in the frontmost application and then use `Append selected text`, then it throws an error (and added undefined to note), could you look into dying gracefully instead?

s1zEDiObCtrgzLCC

I tested the rest of the extension without finding anything further. Awesome! 🔥

**Comment by marcjulianschwarz** [comment]
Hi @pernielsentikaer,

thank you very much for the review. Fixed the error and the undefined.

**Comment by mattisssa** [comment]
Hey! Thank you for the fix, I couldn't repro the case from above, so let's get it merged.

**Comment by marcjulianschwarz** [comment]
Thank you @mattisssa and @pernielsentikaer!

**Comment by marcjulianschwarz** [comment]
#612 can now be closed.

**Pull request merged**
