### PR TITLE
Update mac-app-store-search extension

### PR DESCRIPTION
**Pull request by j3lte**
## Description

- Add AppStore icons to the search results.
  - Suggestion: #12088 
- Add option to open the author page (for other results from the author)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
That looks like a really nice update, @say4n can you check it 🙂

**Comment by say4n** [comment]
Sure thing, I will probably not have any bandwidth till the weekend though!

**Comment by say4n** [comment]
Otherwise, it looks good to me!

**Comment by say4n** [comment]
LGTM! 🚀

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
