### PR TITLE
Things: Big update

### LINKED ISSUE #7297: [Things] Add action to copy markdown link
### Extension

https://www.raycast.com/loris/things

### Description

Add an Action to copy a markdown link to a given To-Do instead of just the URI. Ideally extend this to work for any object where "Copy URI" works.

### Who will benefit from this feature?

Anyone who frequently links to To-Dos from other apps (E.g. note apps).

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

A big update has been released for the Things extension. Here's what's new:

### New actions

You now have additional actions for your to-dos:
- Schedule
- Move to a project/area
- Edit the title or notes
- Add a tag
- Set a deadline
- Copy the URL as a formatted link
- Copy the title
- Copy the notes

But that's not all. There are also two new actions powered by AI to assist you in completing your to-dos:

- `Generate checklist with AI` to generate a checklist based on the to-do's title and notes
- `Make To-Do Actionable with AI` to make a to-do's title more actionable.

> Note: Some of these actions require an authentication token for security reasons. Please refer to the instructions in the README.md file to set it up.

### New command: Add New Project

You can now create new Things projects directly from Raycast. Similar to to-dos, you can add project notes, tags, schedule it, assign it to an area, set a deadline, and add some to-dos.

Need inspiration or a little boost to kickstart a project? Use the "Generate To-Dos with AI" action to let the AI fill out the to-dos for you.

### Menu bar improvements

The menu bar command also has its own set of imrpovements. Now you can perform more actions directly from the menu bar:

- Schedule a to-do
- Move a to-do to a project/area
- Complete any to-do

The menu bar also includes shortcuts to different lists in Things for quicker access (Today, Upcoming, Projects & Areas, Logbook, etc.). If you prefer a simple, clean list, note that you can disable this feature and keep only your to-do list for today visible.

### Other improvements

- Added support for drafts when creating to-dos
- Improved deadlines accessories
- Enabled markdown when adding a new to-do
- Improved date pickers to only show dates from now onwards
- Added icons to list accessories
- Added a new empty state
- Added a confirmation alert when deleting a to-do

Closes #7297.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by loris** [comment]
@thomaslombart Looks cool! LMK when this is testable. Is there anything new in terms of features? (I quickly checked the changes and it seemed mainly chore changes: switch to raycast utils lib, refactoring, etc)

**Comment by thomaslombart** [comment]
Hey @loris, thanks! It's now testable. It's mostly small improvements + revamping the codebase to use the latest Raycast features. Lots of things have been shipped since Raycast 1.28. 😄

I initially wanted to add support for more stuff such as projects, headings, checklists, but it seems the extension is quite limited by JXA, and there's little support/docs for that either (e.g., moving an item in Things using AppleScript doesn't work for example).

I tried to use the URL scheme as well (like update), but hit some roadblocks when calling that from the extension because somehow, Things were not able to recognize the to-do ID. Have you already given that a try? It'll surely be useful to add support for more features (even though it requires an authentication token).

**Comment by thomaslombart** [comment]
@loris Let me know when everything looks good to you.

**Comment by thomaslombart** [comment]
I'm putting this PR back to draft as I want to add many features to it using the URL scheme.

**Comment by thomaslombart** [comment]
@loris The PR is now ready. I ended up adding many improvements with the Things URL scheme. Let me know when you've tested it.

**Review by loris — APPROVED** [review]
@thomaslombart This is amazing! You have taken the extension to a whole new level. I've been playing with it since this morning and haven't found any bugs yet. I really appreciate the AI additions!

FYI, here is the backlog I had in mind for future versions (let me know if you also had ideas that did not make it in this release)

- [ ] Show Upcoming List: group by date
- [x] Create Form: add Project
- [ ] Add “Show Logbook” command
- [ ] Add “Show Trash” command
- [ ] Add “Show Areas” command
- [ ] Add “Show Projects” command
- [ ] Add “Log Completed” command
- [x] Add “When” Action
- [x] Add “Move” Action
- [ ] Add “Empty trash” command
- [ ] Add Detail View

**Comment by thomaslombart** [comment]
All right, let's release it then! I've tried to group the upcoming list by date but haven't found a reliable way of getting the dates with AppleScript unfortunately. There's something called `activationDate` on a to-do but this property isn't there for all to-dos even though it should be the case.

The `Show Areas` and `Show Projects` shouldn't be too hard to build since there's now the `getLists` function. Not sure about the other ones 😊

**Pull request merged**
