### PR TITLE
Add "Vue.js documentation" extension

### PR DESCRIPTION
**Pull request by johanmolen**
## Description

This extension is adding two commands. One for searching the Vue.js version 2 documentation and one for version 3.
Under the hood it uses the public Algolia search of Vue.js to find the best results possible.
This is my first experience with Raycast extensions and I have little experience with TypeScript and React. So any feedback is more than welcome! If you have any questions please let me know.

Thanks in advance. 

## Type of change
- New extension

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @johanmolen 👋 

Thanks for the contribution, we do have other documentation extensions, and you can maybe get some inspiration from them.

Like [this one](https://github.com/raycast/extensions/pull/607/files) which:

- Using Algolia lite (Just an observation)

- Having default values from a JSON file to speed up (Not required at all)

-  Having dropdown preference to set the version for the command (I'm not sure if it's the same with Vue and using a specific version)

- Having the Algolia keys in the source code instead, since they can't really be changed (Should not be user defined)

When opening the extensions I noticed [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by johanmolen** [comment]
@pernielsentikaer Thanks for the feedback 🙌. I will work on this soon.

**Comment by pernielsentikaer** [comment]
Awesome @johanmolen – I'm excited about what you're going to add 💪

**Comment by johanmolen** [comment]
@pernielsentikaer im closing this PR for now, sorry, because Im not sure when I have time to finish it. I hope this creates space for somebody else trying to create it in the meanwhile. Otherwise I will recreate the PR once I have time. Too busy with client work at the moment.

**Pull request closed without merging**
