### PR TITLE
Update pipedrive extension

### PR DESCRIPTION
**Pull request by wimsy**
## Description

Closing #4564

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by wimsy** [comment]
https://github.com/raycast/extensions/issues/4564

**Comment by pernielsentikaer** [comment]
Thanks for the fix @wimsy 🚀  Do you mind adding a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry too?

Do you mind checking this update @stephendolan 🔥

**Comment by wimsy** [comment]
> Thanks for the fix @wimsy 🚀 Do you mind adding a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry too?

CHANGELOG added

**Comment by pernielsentikaer** [comment]
Thanks, then we just need @stephendolan to check it 🙂

**Comment by wimsy** [comment]
hi @stephendolan do you mind taking a look at this one? I can attest that some Pipedrive users don't add organization to records and this is a very minor update to just keep the extension from erroring out in that case. Thanks!

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
