### PR TITLE
Update Surl extension

### PR DESCRIPTION
**Pull request by fujiyamaorange**
## Description
- Add preferences to the extension

## Screencast
- Add `Customize Expiration Date` action.
- User can select the expiration date in setting page.

スクリーンショット 2024-02-12 15 28 53

スクリーンショット 2024-02-12 15 29 41

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Does the history also remove the items after the expiration date?

**Comment by fujiyamaorange** [comment]
@pernielsentikaer 
> Does the history also remove the items after the expiration date?

Thank you for the review.
The answer is no. For now, user has to check the validity of url by yourself. 😅 

Is that necessary to remove the expired urls?

**Comment by pernielsentikaer** [comment]
No, but I guess it could be confusing if you have the list and none of the links is working - it could be a version 3 for sure 🙂

Let's just continue for now :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by fujiyamaorange** [comment]
@pernielsentikaer 
Thank you for the reviewing!

> it could be a version 3 for sure 🙂

Exactly! I will!

**Pull request merged**
