### PR TITLE
Add to-streamshare extension

### PR DESCRIPTION
**Pull request by 0PandaDEV**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by 0PandaDEV** [comment]
I would like to replace the current version of the extension called Streamshare Uploader with this extension here.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Then you would need to "move" the files from the old folder into the new (and change the content, does that make any sense)

**Comment by 0PandaDEV** [comment]
So I need to also delete the old extension?

**Comment by pernielsentikaer** [comment]
Fork the original extension, move files to the new folder 🙂

**Comment by 0PandaDEV** [comment]
> Fork the original extension, move files to the new folder 🙂

No, that does not work because I changed the identifier name so it gets detected as a new extension by the ray CLI.

**Comment by pernielsentikaer** [comment]
Can we start with a PR where we only move all files to the new directory instead? Our CI doesn't like multiple folders 🙂

**Comment by 0PandaDEV** [comment]
> Can we start with a PR where we only move all files to the new directory instead? Our CI doesn't like multiple folders 🙂

Yeah, sure, but I don't get what you mean by moving files.

**Comment by pernielsentikaer** [comment]
If you delete your local copy and fork the updated one from store, then it should be easier to make the modifications

**Comment by 0PandaDEV** [comment]
Yes, I tried that, but now I get this when I try to publish again.
image

**Pull request closed without merging**
