### PR TITLE
[Mozilla Firefox] Add nightly support as fallback

### PR DESCRIPTION
**Pull request by kud**
Support Firefox Nightly as fallback.

## Description

I only use Firefox Nightly as default browser. This extension crashed. It does not anymore. I did not want to break the previous behaviour so I only use Nightly as fallback and not as first profile. People using both release and nightly will be able to still use release as default.

## Screencast

Private.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
What if a user uses both, maybe a preference would be a good thing to add?

**Comment by kud** [comment]
Hahaha, I knew it! One at a time, @pernielsentikaer. We struggle to have multiple accounts/apps in Raycast in general, so yeah, let's say for now that the normal behaviour is to use classic Firefox. Some people, like me, only use Nightly, and it's my choice. Usually, when people use both, it's because they want to try a futuristic version of Firefox for testing. But they could also use classic Firefox for web development testing and use Nightly for regular business.

Oh well, I suggest accepting this PR in the short term to fix the issue because it's a blocker as it causes a crash. And in the future, we can add a feature to choose the version of Firefox people want to use in the settings of this extension.

Does that sound fair?

**Comment by pernielsentikaer** [comment]
Sure that works fine for me, @crisboarna can you also check this

**Comment by kud** [comment]
> Sure that works fine for me, @crisboarna can you also check this

Amazing. Thanks! At some point I could create a PR to be able to choose in the settings what browser you want to use. 😌 I note this in my todo list.

**Comment by kud** [comment]
Hellooooooooooooooooo 👋

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Could you add a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry @kud

**Comment by kud** [comment]
I can definitely do it yeah

**Comment by kud** [comment]
Taaaaaaaaadaaaaaa 🎉

**Pull request merged**
