### PR TITLE
Add Wi-Fi extension

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

Connect Wi-Fi via Raycast

## Screencast

Metadata-1

Metadata-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mattisssa — APPROVED** [review]
Hey! Thanks for the contribution, looks good.

I think it would be nice to add new API validation logic here for password:
CleanShot 2022-06-30 at 00 26 13@2x

Would be also nice to show a toast if I'm trying to connect to the already connected WIFI. Or instead of **Connect** action add action **Disconnect**. WDYT?

Is it somehow possible to don't ask password for known WIFIs and connect to them directly?

**Comment by mattisssa** [comment]
And for some reason I got duplicates for my WIFI connection:

CleanShot 2022-06-30 at 00 28 48@2x

**Comment by koinzhang** [comment]
Hi @mattisssa. Thanks for your review.
> I think it would be nice to add new API validation logic here for password:

I don't have time to make changes now, so if you're not in a hurry, you can wait for me to make changes before posting it (Probably I can make changes tonight.).
If you need to merge it now, I will update it in the next version

> Would be also nice to show a toast if I'm trying to connect to the already connected WIFI. Or instead of **Connect** action add action **Disconnect**. WDYT?
> 
> Is it somehow possible to don't ask password for known WIFIs and connect to them directly?

Because the npm library I'm using doesn't support disconnecting Wifi on macOS right now, only connecting.

> And for some reason I got duplicates for my WIFI connection:

I don't know if this is a bug or not, I haven't studied it in depth, but my guess is that if router's wifi has two bands, 2.4G and 5G, and you combine them both into one, this situation will occur.

**Comment by koinzhang** [comment]
> Is it somehow possible to don't ask password for known WIFIs and connect to them directly?

Does the known wifi refer to the ones previously connected using the system? Unfortunately it is not possible to get the password of these Wi-Fi for now. Because this extension scans Wi-Fi directly instead of getting Wi-Fi from the system.

However, if you have connected to Wi-Fi once with this extension, the extension will automatically remember the password and you don't need to enter the password when you connect next time.
If you want to forget the **Preferred** Wi-Fi or re-enter the password, just remove it and connect again.

**Comment by koinzhang** [comment]
Hi @mattisssa. I'm sorry to keep you waiting.
I have added a verification that the password is empty when the Connect Wi-Fi action is clicked.
Please keep reviewing.
截屏2022-06-30 22 18 39

**Pull request merged**
