### PR TITLE
Replace List Workflows with Project Search in Circle CI extension

### PR DESCRIPTION
**Pull request by kudrykv**
## Description

List your CircleCI projects, quickly navigate to them, and see the most recent pipelines and workflows.

The extension helps quickly navigate to the CI project page and project settings. Within Raycast, it shows current pipelines and allows navigation to them.

## Type of change

- Improvement for somebody else's extension. Extension author: @qeude 

## Screencast

https://user-images.githubusercontent.com/12697803/148687680-54c8af1b-9ee5-41eb-9a67-52fa4bcb1448.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Comment by mathieudutour** [comment]
There is already a CircleCI extension. How about extending it instead adding a new extension?

**Comment by kudrykv** [comment]
> There is already a CircleCI extension. How about extending it instead adding a new extension?

Okay. There'll be a bunch of changes to that extension then.

**Comment by kudrykv** [comment]
@mathieudutour, I need more input. The existing extension is limiting. Besides the API key, it requires the project name, so one can't check workflows for different projects quickly.

Should I consider rewriting it?

**Comment by mathieudutour** [comment]
TBH I haven't used CircleCI in a while. Maybe you can see with @qeude (Quentin Eude on Slack) to see you to move forward with the existing extension?

**Comment by kudrykv** [comment]
@mathieudutour @qeude, please take a look!

**Comment by qeude** [comment]
@kudrykv Just gave a quick look, is the "List Workflows" command still relevant since you can basically access the same informations through the "Project Seach" one ?

**Comment by kudrykv** [comment]
@qeude I've kept it as you've had your use-case when you built it.
If the new command fits your needs and you're good if I replace "List Workflows" with "Project Search", I'll do that

**Comment by qeude** [comment]
You should maybe confirm with @mathieudutour. But when using Raycast I pretty much like the idea of not having too much similar extensions, so imo we should just keep "Project Search" here. Maybe we could add an optional setting to allow users to add a default project (even by using quick action for that purpose).

**Comment by kudrykv** [comment]
@qeude, there is one extension with two commands inside — list workflows and project search.
Having two even similar commands is less of an issue because you can disable one if you don't need it.

**Comment by kudrykv** [comment]
After having a little discussion with @qeude in Slack, we've decided to reduce the extension to a single command. I'll make an update soon.

**Comment by pernielsentikaer** [comment]
Hi @kudrykv 💎 

Is this ready for a review?

**Comment by kudrykv** [comment]
Hi @pernielsentikaer!
Yes, it is ready.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @kudrykv 👋 

When entering a wrong API key, it seems like there is no gracefully fallback

hDL3eVNm6HeINeWS

Could you look into this? Adding a Toast and make sure the loading stops with an empty array as data instead.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pernielsentikaer** [comment]
Much better @kudrykv 💯 

I don’t have a Circle CI aacount, did you test that everything still works @qeude?

**Comment by qeude** [comment]
@pernielsentikaer Everything was working fine on my side 🚀

**Pull request merged**
