### PR TITLE
Apple Reminders: Improve non-AI Quick Reminder

### PR DESCRIPTION
**Pull request by phil1995**
## Description

Improves the "non-AI" part of the Quick Reminder feature for Apple Reminders:

* add a due date using natural language by leveraging chrono
* add the reminder to a list via `some note  #List-Name` (adding no list name still saves it to the default list)
* actually allow to add notes when the `dontUseAI` option is enabled

I think one might still want to update the description for the `dontUseAI` option but I was a bit unsure here what might be now a good description.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

- Could you fix the [CI errors](https://github.com/raycast/extensions/actions/runs/8606880679/job/23586223345?pr=11708) mentioned

- Could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by thomaslombart** [comment]
Hey @phil1995, thanks for the PR! I've made the code a bit simpler and added two improvements on top of yours:

- Projects will be matched regardless of the case.
- Support full-day dates.

Let me know if it works as expected for you.

**Comment by phil1995** [comment]
> Hey @phil1995, thanks for the PR! I've made the code a bit simpler and added two improvements on top of yours:
> 
> * Projects will be matched regardless of the case.
> * Support full-day dates (e.g `Buy groceries tomorrow` won't add any specific time in Apple Reminders)
> 
> Let me know if it works as expected for you.

Hi @thomaslombart,

thanks for the improvements! I really like the support for full-days. 
For me it works now even better than expected 🎉

**Comment by thomaslombart** [comment]
Awesome! Let's ship it 🚀

**Pull request merged**
