### PR TITLE
Update spotify-player extension

### PR DESCRIPTION
**Pull request by hobhouse**
## Description
This PR enhances the song liking functionality in two significant ways:

1. It provides clear user feedback when attempting to like an already liked song, improving the user experience.
2. It prevents the re-liking of songs that have already been added to the Liked Songs playlist, ensuring efficient music management.

The benefits of these enhancements are:

1. Improved user experience, particularly when using the command with a hotkey, resulting in better music management.
2. Preservation of the order and date added value in the Liked Songs playlist, maintaining the integrity of the user's music library.
## Screencast

image
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by hobhouse** [comment]
@peduarte Do you have any feedback?

**Comment by hobhouse** [comment]
HI @peduarte do you think this is a desirable feature or shall I close?

**Review by peduarte — APPROVED** [review]
This is great, thank you!

**Comment by peduarte** [comment]
Could you resolve the conflicts, then happy to merge. Sorry for the delay.

**Pull request merged**
