### PR TITLE
Add find-nearest-tailwind-color extension

### PR DESCRIPTION
**Pull request by michaelnabil230**
## Description

This Raycast extension allows you to quickly find the closest matching color in the Tailwind CSS color palette for any given input color. Whether you're designing a UI or working on a front-end project, this tool will help you ensure color consistency and streamline your workflow.

## Screencast

https://github.com/raycast/extensions/assets/46572405/af98146a-e58b-4353-b26a-145b5b9d7bd9

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @michaelnabil230 👋

Thanks for your contribution 🔥

There is already a few Tailwind extensions in the store, maybe it's better to add the feature to one of them?

* [Tailwind CSS](https://www.raycast.com/vimtor/tailwindcss) by @vimtor 
* [Tailwind CSS Colorpicker](https://www.raycast.com/magicjaqk/tw-colorpicker) by @magicjaqk

**Comment by michaelnabil230** [comment]
Hi @pernielsentikaer,

I wish that were the case, but in reality, this extension is different from the basic functions found in other extensions because it helps to find the nearest color to Tailwind, unlike other extensions that display the colors from the documentation only.

**Comment by pernielsentikaer** [comment]
The first one by @vimtor sounds like a good match, it's a collections of _utilities to work with Tailwind CSS_ which this could fit into, having too many Tailwind extensions might end up confusing users more than it gives

**Comment by vimtor** [comment]
I think this would be a great addition to the Tailwind CSS extension as @pernielsentikaer said!

Let me know @michaelnabil230 if you need any help.

**Comment by mil3na** [comment]
Hi! I will be closing this PR as it is a better fit as an addition to the extensions mentioned above.
Please, let us know here or via Slack (https://raycast.com/community) if you need any help contributing to them!

Cheers!

**Pull request closed without merging**
