### PR TITLE
Update snap-jot extension

### PR DESCRIPTION
**Pull request by longy2k**
## Description

I have added two new commands to SnapJot:
- `Daily Note` - This will allow you to view your daily note and append any new memo quickly.
- `Search Notes` - This will allow you to search for any notes (files) within the specified directory.

Thank you for allowing me to add my contribution to SnapJot!

Please let me know what you think :)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by k41531** [comment]
Thank you for your contribution to the SnapJot!!
I tried using it, and it was very convenient!
Thank you also for the refactoring.

However, I'd like to discuss the naming of the commands.
I understand that the original foundation of this was TimelineJournal, which likely influenced the choice of names like 'Search Timeline' or 'Today's Timeline'.
Given that this extension is designed not just for journaling but for a wide range of note-taking purposes, I wonder if using 'Note' instead of 'Journal' in the command names might be more fitting.
What do you think?

**Comment by longy2k** [comment]
Yes, that sounds great!

Do you mind renaming the commands?

I am not sure what is more fitting for SnapJot. Maybe `Search Notes`/`Today's Notes` or `Search Memos`/`Today's Memos`?

**Comment by longy2k** [comment]
I just noticed that I left a `console.log` in the code. I can push the changes soon. 

How about `Search Notes` and `Daily Note`?

**Comment by k41531** [comment]
Indeed, Daily Note sounds better!
That's fine.

**Comment by longy2k** [comment]
Awesome!

Let me know if these changes are good

**Comment by k41531** [comment]
All good, thanks!

**Review by pernielsentikaer — APPROVED** [review]
✅ Approved

**Pull request merged**
