### PR TITLE
feat: add massCode assistant

### PR DESCRIPTION
**Pull request by antonreshetov**
## Description
- Fetch snippets from [massCode](https://github.com/massCodeIO)
- Search
- Copy to clipboard

## Screencast

https://user-images.githubusercontent.com/17480987/163411946-ebfd7319-1993-4da7-9099-0e6a9e02647f.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @antonreshetov 👋 

Are you on [Slack](https://raycastcommunity.slack.com/)? If so, please give me a message there about this extension, if not, send me a DM in [Twitter](https://twitter.com/pertikaer) 😄

**Comment by antonreshetov** [comment]
@pernielsentikaer Your Twitter DM is closed.

**Comment by pernielsentikaer** [comment]
Sorry, could you try again @antonreshetov 😄

**Review by pernielsentikaer — APPROVED** [review]
Hi @antonreshetov 👋 

Thanks for your extension. It was a pleasure to help you out 🚀 

Already looking forward to the next version! 😄

**Pull request merged**
