### PR TITLE
[1password] cli support

### PR DESCRIPTION
**Pull request by khasbilegt**
## Description

This new version of the 1Password extension contains the following changes.

### 1Password 8

- Filter by categories
- `opbookmark` is removed
- Copying of item fields
- Create new items (TBD)

### 1Password 7

- Better caching
- Beautiful icons instead of emojis
- Cleaner code

## Screencast
1password-1

1password-2

1password-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Wow, this is huge 🔥 Catch you in [Slack](https://www.raycast.com/community)

**Comment by khasbilegt** [comment]
Awesome 🤩

**Comment by sjdonado** [comment]
What a PR man! 🔥

**Comment by dteare** [comment]
Wow, this looks incredible! 😍 Bravo! 👏🏻

**Comment by pernielsentikaer** [comment]
Do you want to change the metadata images @dteare? Could you DM me in [Slack](https://www.raycast.com/community)

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Only one comment @khasbilegt - is there a way to not include the 39MB binary into the extension? Can we download it from 1password somehow?

**Comment by sjdonado** [comment]
> Only one comment @khasbilegt - is there a way to not include the 39MB binary into the extension? Can we download it from 1password somehow?

It seems that isn't necessary at all, that binary is a fallback when calling the real cli binary

https://github.com/raycast/extensions/pull/4298/files#diff-1ecc85b48dc302a18fe54ffc7a7124e60508ef7b9397e82cda4844208d49d185R12

**Comment by khasbilegt** [comment]
@pernielsentikaer Yeah, this is the only solution I found at the moment. 1Password doesn't provide a static url where the binary can be downloaded from and also they distribute it in .pkg file. We can just remove binary, let the user setup the CLI and insert the path in 
extension preference.

**Comment by khasbilegt** [comment]
> > Only one comment @khasbilegt - is there a way to not include the 39MB binary into the extension? Can we download it from 1password somehow?
> 
> It seems that isn't necessary at all, that binary is a fallback when calling the real cli binary
> 
> https://github.com/raycast/extensions/pull/4298/files#diff-1ecc85b48dc302a18fe54ffc7a7124e60508ef7b9397e82cda4844208d49d185R12

If the CLI is already installed in `/usr/local/bin`, the hook extension uses that binary and will not copy the included one. That way user doesn't go through any setup unlike the current `opbookmarks`.

**Comment by khasbilegt** [comment]
@pernielsentikaer, seems I'd never learn to update the changelog 😂

**Comment by pernielsentikaer** [comment]
True @sjdonado - but it increases the size of the extension (repo) with +39MB - id like to avoid that 😊

**Comment by pernielsentikaer** [comment]
> We can just remove binary, let the user setup the CLI and insert the path in extension preference.

Can we link to [this page](https://developer.1password.com/docs/cli/get-started/), I guess it's the fastest way? What do you think @khasbilegt

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
