### PR TITLE
Add mac-app-store-search extension

### PR DESCRIPTION
**Pull request by say4n**
## Description

Adds an extension to search for apps on the Mac App Store.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by xilopaint** [comment]
Hey, you need to add metadata images for the Store.

**Comment by say4n** [comment]
Sure, let me go ahead and add some. 🚀

**Comment by say4n** [comment]
Done!

**Comment by say4n** [comment]
(fixed the linter nag on screenshot dimensions, should have probably run `npm run lint` before I pushed)

**Comment by say4n** [comment]
do you think it is worth updating the npm build script to also run the linter perhaps? something like:
```diff
-    "build": "ray build -e dist",
+    "build": "lint && ray build -e dist",
```

**Comment by xilopaint** [comment]
1) I recommend you use the Window Capture feature to take pretty screenshots in the appropriate size. You can set a hotkey in the Advanced tab of Raycast Settings. With the Window Capture feature, the screenshots will not show the icon for the develop mode.

2) The search bar placeholder is not properly capitalized ("mac app store" instead of "Mac App Store").

**Comment by xilopaint** [comment]
> do you think it is worth updating the npm build script to also run the linter perhaps? something like:
> 
> ```diff
> -    "build": "ray build -e dist",
> +    "build": "lint && ray build -e dist",
> ```

By Raycast standards, `lint`, `fix-lint`, and `build` are separate scripts. I wouldn't change that because other developers who may contribute to your extension in the future may be used to that standard.

**Comment by say4n** [comment]
> I recommend you use the Window Capture feature to take pretty screenshots in the appropriate size. You can set a hotkey in the Advanced tab of Raycast Settings. With the Window Capture feature, the screenshots will not show the icon for the develop mode.

ah neat, I totally didn't know that was a thing -- instead I was doing it all by hand

> The search bar placeholder is not properly capitalized ("mac app store" instead of "Mac App Store").

sure, let me fix that as well!

**Comment by say4n** [comment]
done, thanks Arthur!

**Comment by xilopaint** [comment]
Honestly, I'd suggest using the original App Store icon in the extension. If you prefer using your own icon, consider giving it rounded corners. You can use the Raycast Icon Maker for this: https://icon.ray.so/

**Comment by say4n** [comment]
cool, updated it -- didn't want to use one of those icons but whatever (the icon maker seems to break when i try to import in a custom svg icon), are we gtm here?

**Comment by xilopaint** [comment]
> didn't want to use one of those icons

Actually, you don't need to. I suggested you use the Icon Maker to change your icon to use rounded corners. Here's a version of your original icon with rounded corners if you prefer to use:

icon

As I mentioned, in your place, I would rather use the App Store original icon, but it's also okay to use your own icon.

**Comment by say4n** [comment]
i've updated the icon, let's move with the one that i have at present :)

**Comment by say4n** [comment]
just following up: are we gtm, or are is there an ask here?

**Comment by xilopaint** [comment]
In a couple of days @pernielsentikaer will review the PR.

**Comment by say4n** [comment]
Good catch @pernielsentikaer, thanks! I have fixed the API search params and addressed the other comments!

**Comment by xilopaint** [comment]
@say4n your metadata images show the previous icon version:

mac-app-store-search-0

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by say4n** [comment]
Thanks @pernielsentikaer, apologies for the tardiness!

**Comment by pernielsentikaer** [comment]
All good 🎉

Awesome to see it in the store 🔥

**Pull request merged**
