### PR TITLE
Update 'Toothpick' Extension

### PR DESCRIPTION
**Pull request by VladCuciureanu**
## Description

Observe and manage your bluetooth devices with a few keystrokes.
This extension provides a quick and easy way to connect/disconnect bluetooth devices, right from Raycast.
This is possible by making use of Apple's bluetooth frameworks via AppleScript.

## Screencast

Screenshot of the extension

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Hi @VladCuciureanu. Did you notice this extension [Toothpick](https://www.raycast.com/briankosw/toothpick) in the store?

**Comment by VladCuciureanu** [comment]
Well that is awkward...
No, I didn't notice it. It actually shows up when searching for 'Bluetooth' too, but I missed it somehow.

To be fair though, my extension has battery level meters for wireless earbuds (case, left earbud, right earbud):
bluetooth-2

As well (e.g. AirPods) and also icons for specific devices:
Screenshot 2022-08-22 at 09 19 50
I was actually working on icons for Sony, Samsung and Bose devices too...

Would be a shame to waste all the work I put into this but I don't wish @briankosw ill either. Is there a way to still make use of my extension without sidetracking Toothpick?

**Comment by pernielsentikaer** [comment]
Hi 👋 

Thanks for your contribution and your time spent creating this extension. As you already know, we have a similar extension, and it doesn't make much sense to have almost identical extensions in the store.

What about contributing your enhancements to the other extension? I'm sure that @briankosw and the users would enjoy the extension enhanced 🙂

**Comment by VladCuciureanu** [comment]
@pernielsentikaer Please tell me if any further modifications are needed. Otherwise, should be good to go.

**Comment by pernielsentikaer** [comment]
Can you check this out @briankosw

**Comment by VladCuciureanu** [comment]
@pernielsentikaer What is your policy on the owner of an extension not being contactable?

**Review by pernielsentikaer — COMMENTED** [review]
Hi @VladCuciureanu 👋 

I just gave it a quick spin and it seems like I lost battery status. Do you have a clue what might cause that?

CleanShot 2022-09-20 at 13 09 51@2x

**Comment by VladCuciureanu** [comment]
> Hi @VladCuciureanu 👋 
> 
> 
> 
> I just gave it a quick spin and it seems like I lost battery status. Do you have a clue what might cause that?
> 
> 
> 
> CleanShot 2022-09-20 at 13 09 51@2x
> 
> 

In certain circumstances the magic devices stop sending their battery data. Do you happen to have them plugged in by cable? That does it for me sometimes.

**Comment by pernielsentikaer** [comment]
No wired at the moment and the image is taken in the same second so both should be able to use the same data 🙂

**Comment by VladCuciureanu** [comment]
I have kind of a reverse situation going on here on my travel macbook.
<table>
<tr>
<tc>
Old
Screenshot 2022-09-20 at 21 27 48
</tc>
<tc>
New
Screenshot 2022-09-20 at 21 31 05
</tc>
</tr>
</table>

Sadly I'm not sure we can coax the APIs (that Apple gives us access to, at least) into giving us battery info in certain situations. For example, the old implementation that uses 'ioreg' doesn't seem to want to return AppleDeviceManagementHIDEventService class devices on my travel laptop (runs Monterey).

I suggest moving forward with my implementation though. The reasoning being that it doesn't depend on the device being an AppleDeviceManagementHIDEventService class device, which means that my implementation has potential support for non-apple devices, whereas the older implementation does not.

I know this does not fix the missing battery problem on your devices but this seems like a good compromise for now. I'll look some more into the missing battery problem next week, when I'm back from my vacation.

**Comment by VladCuciureanu** [comment]
Added a few more requested features in the meanwhile:
- Added 'Connect to' and 'Disconnect from' commands
- Added favorite devices functionality for quick connecting to specific devices
- Added option to close the window when successfully connecting to a device.

**Comment by VladCuciureanu** [comment]
> Still no percentage for me, it feels a bit like a tradeoff even though the rest of the commands is improved. Can I help debug this somehow? Seems to always work in the current version.
> 
> CleanShot 2022-10-06 at 13 57 33@2x

Could you check if it works now? Reimplemented previous method as a backup method for fetching device battery levels.

**Comment by VladCuciureanu** [comment]
Sorry but... Bump @pernielsentikaer

**Comment by pernielsentikaer** [comment]
Sorry for letting you wait @VladCuciureanu; I gave it another spin and now it at least shows on of the two percentages; however it's the wrong one it shows 🫣

CleanShot 2022-10-27 at 08 52 06@2x

**Comment by VladCuciureanu** [comment]
> Sorry for letting you wait @VladCuciureanu; I gave it another spin and now it at least shows on of the two percentages; however it's the wrong one it shows 🫣
> 
> 
> 
> CleanShot 2022-10-27 at 08 52 06@2x
> 
> 

No worries about the delay. I'll see what I can do ⚰️😵

**Comment by pernielsentikaer** [comment]
You got e-mail 😊

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
