### PR TITLE
Add Kinopoisk – Search Movies extension

### PR DESCRIPTION
**Pull request by mattisssa**
## Description

Kinopoisk - Easily open your favorite film or tv series on Kinopoisk.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/15333662/142599980-6a23b5c9-11a8-4eec-82b9-0e59e5784a69.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

## Notes

This extension requires API token, to test the extension you can use mine: `8ae44d3a-fd4c-4cb7-b919-f0e9e09f4c18`

Or you can get your own:

1. Visit the [Kinopoisk Api Unofficial website](https://kinopoiskapiunofficial.tech).
2. Sign up and verify the account by entering the confirmation number from the email message from Kinopoisk Api Unofficial.
3. Copy your API-KEY on the profile page e.g. `8ae44d3a-fd4c-4cb7-b919-f0e9e09f4c18` (see image below).
4. You're all ready to go, start searching.

API Key on Profile Page

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @mattisssa 👋 

Thanks for this movie search extension, a few comments:

- It would be awesome if the logo didn't have white background, can you make that?
- If the token is invalid, then it fails, this should be handled gracefully
eHCGk6jm8ppyCDD9

```
Error: type mismatch at params.message : Expected to decode String but found a dictionary instead.

index.js:4:1156

---
1: var Cw=Object.create;var Cu=Object.defineProperty;var Iw=Object.getOwnPropertyDescriptor;var Aw=Object.getOwnPropertyNames;var Nw=Object.getPrototypeOf,xw=Object.prototype.hasOwnProperty;var qp=t=>Cu(t,"__esModule",{value:!0});var at=(t,n)=>()=>(t&&(n=t(t=0)),n);var Pt=(t,n)=>()=>(n||t((n={exports:{}}).exports,n),n.exports),Lw=(t,n)=>{qp(t);for(var o in n)Cu(t,o,{get:n[o],enumerable:!0})},Dw=(t,n,o)=>{if(n&&typeof n=="object"||typeof n=="function")for(let a of Aw(n))!xw.call(t,a)&&a!=="default"&&Cu(t,a,{get:()=>n[a],enumerable:!(o=Iw(n,a))||o.enumerable});return t},Et=t=>Dw(qp(Cu(t!=null?Cw(Nw(t)):{},"default",t&&t.__esModule&&"default"in t?{get:()=>t.default,enumerable:!0}:{value:t,enumerable:!0})),t);var vs=Pt(nn=>{"use strict";Object.defineProperty(nn,"__esModule",{value:!0});nn.createJSONRPCErrorResponse=nn.JSONRPCErrorCode=nn.isJSONRPCResponse=nn.isJSONRPCRequest=nn.isJSONRPCID=nn.JSONRPC=void 0;nn.JSONRPC="2.0";nn.isJSONRPCID=function(t){return typeof t=="string"||typeof t=="number"||t===null};nn.isJSONRPCRequest=function(t){return t.jsonrpc===nn.JSONRPC&&t.method!==void 0&&t.result===void 0&&t.error===void 0};nn.isJSONRPCResponse=function(t){return t.jsonrpc===nn.JSONRPC&&t.id!==void 0&&(t.result!==void 0||t.error!==void 0)};var Mw;(function(t){t[t.ParseError=-32700]="ParseError",t[t.InvalidRequest=-32600]="InvalidRequest",t[t.MethodNotFound=-32601]="MethodNotFound",t[t.InvalidParams=-32602]="InvalidParams",t[t.InternalError=-32603]="InternalError"})(Mw=nn.JSONRPCErrorCode||(nn.JSONRPCErrorCode={}));nn.createJSONRPCErrorResponse=function(t,n,o,a){var s={code:n,message:o};return a&&(s.data=a),{jsonrpc:nn.JSONRPC,id:t,error:s}}});var Fc=Pt(Da=>{"use strict";Object.defineProperty(Da,"__esModule",{value:!0});Da.DefaultErrorCode=Da.createLogDeprecationWarning=void 0;D<…>
```

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by mattisssa** [comment]
hey @pernielsentikaer! Thanks for the feedback, will fix that sooner 😉

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @mattisssa 👋 

That was much better, much appreciated with this update! Only one thing left I saw, when starting the extension I get trippe flash/flicker of "No Results", can you look into this? 💪 

https://user-images.githubusercontent.com/38033107/142989288-8258b133-b94c-4ff8-a345-b1c9a0c084cd.mp4

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @mattisssa  👋 

No flicker detected, awesome! Last thing before we can merge this is that it looks like there never is a loading spinner present, so I'm not able to see if it's actually doing anything before showing the result. Can you look into this? 💪

**Comment by mattisssa** [comment]
Done.

lol, sorry for a lot of bothering requests, just cannot seat and make this perfect from the first time 🤯

**Review by pernielsentikaer — APPROVED** [review]
Awesome @mattisssa 🚀 

This should now be ready to get merged 💯 

Thanks for the correction, it turned out crisp!

**Pull request merged**
