### PR TITLE
[Slack Status] - Add option to pause notifications

### PR DESCRIPTION
**Pull request by luizeboli**
## Description

Resolves https://github.com/raycast/extensions/issues/7578
Continues https://github.com/raycast/extensions/pull/10782

This PRs adds the option to configure a preset which pauses notifications (activates do not disturb mode)

## Screencast

https://github.com/raycast/extensions/assets/13091635/7cded68f-9629-404e-9531-adf4f29f0949

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by luizeboli** [comment]
Hello team, I noticed that the PR https://github.com/raycast/extensions/pull/10782 got reverted for some reason. I would love to help debugging issues, but I couldn't find any

@thomaspaulmann are you experiencing issues with OAuth? could you pls share details on how to reproduce?

**Comment by pernielsentikaer** [comment]
Hi @luizeboli 👋 

I just came back from vacation and I'm ready to have a look at this, are you in our [Slack Community](https://www.raycast.com/community) or can you catch me in on 𝕏 so we can have a look

I think the issue is that if you already have setup the OAuth connection, then it crashing due to missing scope. We can maybe handle that gracefully and add a tooltip and an error screen if you're trying to use it.

```
Error: An API error occurred: missing_scope
    at tv (/Users/mann/.config/raycast-internal/extensions/6916ad50-03ad-4b88-b83a-d25c3393a417/setStatus.js:43:29336)
    at e.apiCall (/Users/mann/.config/raycast-internal/extensions/6916ad50-03ad-4b88-b83a-d25c3393a417/setStatus.js:45:6161)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/mann/.config/raycast-internal/extensions/6916ad50-03ad-4b88-b83a-d25c3393a417/setStatus.js:49:119317
```

**Comment by luizeboli** [comment]
hey @pernielsentikaer, I will reach out on your slack

this issue is weird, [this code block](https://github.com/raycast/extensions/pull/11597/files#diff-dec4d6b18a3f3a4758594f6dc74a88fa5ddc9d88838b0da1847fc6c585b92b0fR44-R68) exists exactly to avoid that.

I will do some tests and try to understand what's happening

**Comment by pernielsentikaer** [comment]
Right after the update was released we start seeing this error (same as above). I tested with a clean installation of the extension and there is works since scopes is set.

image

You can always catch me in our Slack if you need help debug

**Pull request closed without merging**
