### PR TITLE
New extension: Myanimelist Search

### PR DESCRIPTION
**Pull request by luknl**
## Description

Easily search and open animes on Myanimelist.
Search any anime by its title and hit enter to access its page on Myanimelist. 3 views available.

## Screencast

https://user-images.githubusercontent.com/9930144/193934102-9a486bc2-76e0-4b61-83d3-7c2f93774a45.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by luknl** [comment]
Hi, thanks for the feedback!
- Actually the API itself has a limit of 25 items per page, their limit param works only for values less then 25 (try [here](https://api.jikan.moe/v4/seasons/now?limit=50)). But I did made the 
- Added
- Yes it's not perfect right now but they are working on improving it very soon: https://github.com/jikan-me/jikan-rest/issues/189

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by luknl** [comment]
Thank you @pernielsentikaer!
Quick question : I see here that the height I specified on the image at the top of my readme (68px) is not taken into account. Any ideas how this could be easily fixed? If not, I'll just remove the image as it's taking too much place. Thank you!
image

**Comment by luknl** [comment]
Hi @pernielsentikaer, it seems it got [reverted back](https://github.com/raycast/extensions/commit/ea0929a1dbc0ebd910221b80a0456dab57915bb3) a few hours ago. Do you know why, and what is the new API release?

**Pull request merged**
