### PR TITLE
Add graphcalc extension

### PR DESCRIPTION
**Pull request by cluzier**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The extension suffers from [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) - could you look into a fix for this?

- I'm not sure it makes to have the history in this view? 

graphcalc 2024-05-27 at 10 29 00


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by cluzier** [comment]
Thanks for the feedback @pernielsentikaer I'll make these changes this week.

**Comment by cluzier** [comment]
Hi @pernielsentikaer I made the changes you suggested 🔥

Thank you for the suggestions, I removed the history from the graph view and fixed the empty state flicker you had mentioned.

Hoping it passes review this time! 🤞

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for the update, it works much better now 🔥

I'm not sure how users would use the extension. Would you normally go back and modify the equation a lot or is it more a set-it-and-forget-it thing? `push()` might not be the best choice 🙂

**Comment by luarmr** [comment]
Hey @pernielsentikaer @cluzier 

I saw the pr and I want to drop my 2 cents, I think they are 3  options here:

	1.	Remove the ESC completely, rendering without a push.
	2.	Remove the search before loading the page. (so it is only 1 ESC)
	3.	Do nothing and allow the user to refine the search.
	
Not sure what the style guide is for these scenarios. But I like the second one, since the history will show the last option first and is easy to collect it, so we probably want to add 


```
  const submit = (expression: string) => {
    updateHistory(expression);
    push(<Graph expression={expression} />);
    setExpression("");
  };
  ```

I saw another issue with sorting the history that can be fix with something like this.

``` 
useEffect(() => {
    const currentHistory = history || [];
    setRenderHistorySorted([...currentHistory].sort());
  }, [history]);
  ```
  
  The last annoying thing with this solution is that the history is not selected with the last option after ESC. Can be set as selectedItemId={"0"} and add an id on the ListItems,  Not sure it will be a flickering.

**Comment by cluzier** [comment]
@pernielsentikaer @luarmr was able to help solve the issue. The most recent change allows the user to enter an expression/equation right on the main raycast screen. This eliminates the issue of having to hit escape twice.

Raycast 2024-05-30 at 18 27 44

**Comment by pernielsentikaer** [comment]
It works pretty nice 🔥 

There is a short [Empty State Flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) when you  use it from the argument, do you think we can get rid of that?

**Comment by cluzier** [comment]
@pernielsentikaer I will work on a fix for the empty state flicker tonight. Thanks for the feedback.

**Comment by cluzier** [comment]
I ended up fixing the empty state flicker as mentioned @pernielsentikaer . It was a bit tricky but now displays a loading toast as well as "Loading..." at the top of the screen briefly instead of flickering empty state view while loading.

**Comment by pernielsentikaer** [comment]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
