### PR TITLE
bitfinex: Support lending rates chart

### PR DESCRIPTION
**Pull request by Yukaii**
## Description

- Draw Bitfinex lending rates with [asciichart](https://github.com/kroitor/asciichart) npm package

## Screencast

https://user-images.githubusercontent.com/4230968/179489549-93825bed-2d25-4363-8995-b50089edc8b6.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Yukaii** [comment]
@danielsequeira added, thanks!

**Comment by danielsequeira** [comment]
Sorry for the nitpicking @Yukaii, but for the sake of consistency could you do it with the same background you used before: https://www.raycast.com/Yukai/bitfinex

**Comment by danielsequeira** [comment]
Thanks @Yukaii, we really appreciate it 🙏 

However it seems that one of your screenshots is not in the correct size and therefore broke the last pipeline. Could you fix this?

Screenshot 2022-07-19 at 09 53 32

**Comment by Yukaii** [comment]
Oops, must capture metadata with 2k screen resolution.

**Review by danielsequeira — APPROVED** [review]

**Comment by Yukaii** [comment]
Thanks for the help! Almost forgot this one.

**Review by danielsequeira — APPROVED** [review]

**Pull request merged**
