### PR TITLE
Add catppuccin extension

### PR DESCRIPTION
**Pull request by dvhsh**
## Description

Catppuccin extension with commands used to browse color palettes, ports, userstyles, and quickly open documentation for https://github.com/catppuccin 

## Screencast

catppuccin-2
catppuccin-3
catppuccin-4
catppuccin-5
catppuccin-6
catppuccin-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- What about having a command like `Search Themes` instead and then use the Dropdown to change theme - then in preferences you can let the user choose grid size

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by dvhsh** [comment]
Thanks for the feedback, I've gone ahead and made the requested changes and then tested a new build

**Comment by pernielsentikaer** [comment]
Should we consider setting a default grid size and making the preference optional?

I'll leave that part up to you

**Comment by dvhsh** [comment]
> Should we consider setting a default grid size and making the preference optional?
> 
> I'll leave that part up to you

That was the intent originally, I've gone ahead and fixed this

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
