### PR TITLE
[New Extension] AirPods Noise Control

### PR DESCRIPTION
**Pull request by chrahe**
## Description

This is a simple extension that toggles between Noise Cancellation and Transparency on AirPods, as the Shortcut action "Set Noise Control" doesn't work on macOS and public AppleScript solutions don't work on macOS Ventura.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

I keep getting the above error.

Raycast-XAhzTvSZ@2x

Added the device as number 4 according to the README, also checked that it's called Control Center / Sound

Raycast-g1ptZ0Zc@2x

Do you have any clue?

**Comment by chrahe** [comment]
Hey, have you also checked the setting that the sound menu is visible in the menu bar itself while your airpods are connected? (not just control center)

**Comment by chrahe** [comment]
I could have the AppleScript target Control Center itself but that would make it much more visible (and take longer) when it's navigating the menus. Perhaps I can add it as a preference? What do you think the default should be in that case?

**Comment by pernielsentikaer** [comment]
I can't remember how to get the headphones icon to the menubar, do you remember that @chrahe

**Comment by chrahe** [comment]
I put instructions in the README but they were kind of hidden. I now added a fallback that will look inside the regular Control Center if the sound menu isn't a separate item in the menu bar. Could you check if that works on your device @pernielsentikaer ?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
