### PR TITLE
add: netease-music

### PR DESCRIPTION
**Pull request by chyroc**
## Description

Control the NeteaseMusic app with your keyboard

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by chyroc** [comment]
@pernielsentikaer thanks for your review, thanks ~

**Review by mattisssa — CHANGES_REQUESTED** [review]
Hey! I don't have the Netease music installed and when I perform any of the commands of the extension I don't see the HUD or error messages. Could you take a look at that before we publish the extension? 

Let me know if you need any help with debugging.

**Comment by mattisssa** [comment]
Ah, update: I got a bunch of errors but about 30 seconds after I performed the command! Not sure if it's possible with the library you're using but can we add some timeout limits for this?

**Comment by chyroc** [comment]
@mattisssa i add exec timeout for applescript(1 second), When you can't find the app (the app is not installed), it will remind you more quickly that there is some problem, instead of waiting，

thanks for your review, thanks very much.

**Review by mattisssa — CHANGES_REQUESTED** [review]
Hey! I still have the same behaviour in the case when I don't have the app.

As I can see in your commit there was only a version bump for the library

CleanShot 2022-04-19 at 09 57 05@2x

**Comment by chyroc** [comment]
sdk add timeout: https://github.com/chyroc/netease-music-controller/compare/v0.5.0...v0.6.0

**Comment by chyroc** [comment]
image

i un-install my app, and test this command with some log.

i see commmand timeout with 1 second

**Comment by mattisssa** [comment]
Yes, sorry, I didn't run `npm i` to update the dependencies.

**Pull request merged**
