### PR TITLE
Update speedtest extension

### PR DESCRIPTION
**Pull request by xilopaint**
## Description

- Updated command title.
- Improved overall appearance.
- Improved UX for the `Clear CLI Cache` action.

## Screencast

Screenshot 2024-06-12 at 07 28 54

Screenshot 2024-06-12 at 07 30 05

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tonka3000** [comment]
Keep the colors please. Looks like dead icons to the eyes.

**Comment by xilopaint** [comment]
> Keep the colors please. Looks like dead icons to the eyes.

@tonka3000 The problem I see in the previous implementation was not the colors but the lack of coherence among the distinct colors. It made the UI distracting without adding any visual information. Also, not all colors work well in the light theme because of the lack of contrast. What do you think about using a single blue color?

Screenshot 2024-06-12 at 15 52 12

**Comment by pernielsentikaer** [comment]
@tonka3000 any comments here?

**Comment by aliaksandrZh** [comment]
Colored icons are much better to me

**Comment by pernielsentikaer** [comment]
Agree, I like the colored ones better too. Are you up for that, @tonka3000 😊

**Comment by xilopaint** [comment]
@tonka3000 are you ok with the all-blue version or do you prefer using multiple colors? Tbh, I find super ugly the version with different colors, but you are the boss here. 😄

Here's the all blue version:

339095353-4ebbcaef-4d41-4141-ae3e-32807db22e22

Here's the layout before this PR:

Screenshot 2024-06-20 at 03 46 58

**Comment by tonka3000** [comment]
@xilopaint Add an preference to get both (no-color and color)? You can let the no color version. The default, so everyone can get the favorite version of it 😄

**Comment by xilopaint** [comment]
> @xilopaint Add an preference to get both (no-color and color)? You can let the no color version. The default, so everyone can get the favorite version of it 😄

@tonka3000 I'm not advocating for no color. I am asking if you prefer a single color or multiple colors as before. Personally, I prefer a single color (tried with blue), but I will make it whatever you want. This PR has other changes.

**Comment by tonka3000** [comment]
> > @xilopaint Add an preference to get both (no-color and color)? You can let the no color version. The default, so everyone can get the favorite version of it 😄
> 
> @tonka3000 I'm not advocating for no color. I am asking if you prefer a single color or multiple colors as before. Personally, I prefer a single color (tried with blue), but I will make it whatever you want. This PR has other changes.

Go with single color. I will add an optional color preference in a couple of month.

**Comment by xilopaint** [comment]
It's ready @pernielsentikaer.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
