### PR TITLE
Add numi-cli extension

### PR DESCRIPTION
**Pull request by viandwi24**
## Description

Query Numi from Raycast using numi-cli.  
so don't need to download the desktop version of Numi, just download numi-cli and then can directly use this extension.

## Screencast

https://github.com/raycast/extensions/assets/41994283/0c659f47-034a-4ce8-ad2a-66a397ddcce2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Ek2100** [comment]
I think raycast bot adedd the wrong labels...

**Review by Ek2100 — CHANGES_REQUESTED** [review]
This extension is I think identical to this:

https://www.raycast.com/andresmorelos/numi

Also you need a new extension icon

**Comment by viandwi24** [comment]
> This extension is almost identical to this:
> 
> https://www.raycast.com/andresmorelos/numi
> 
> Also you need a new extension icon

the extension uses the official icon, do I have to change the icon too?

**Comment by Ek2100** [comment]
> > This extension is almost identical to this:
> > https://www.raycast.com/andresmorelos/numi
> > Also you need a new extension icon
> 
> the extension uses the official icon, do I have to change the icon too?

I’m not sure about the exact rules regarding this, however you likely need a unique extension.

**Comment by thomaslombart** [comment]
Hey @viandwi24, this extension is indeed quite close to the [original one](https://www.raycast.com/andresmorelos/numi). I'd suggest that you contribute to it so we keep the store clean. you could for example add a preference that allows the user to switch between Numi Desktop or Numi CLI.

**Comment by viandwi24** [comment]
@thomaslombart that's great,  I'll try to add this feature into the existing extension if you allowed

**Comment by viandwi24** [comment]
have documentation about updating extension? or i can just fork this main branch, edit on extension folder and make pull request?

**Comment by thomaslombart** [comment]
Sure. Here's our guide about contributing to extensions: [Contribute to an extension](https://developers.raycast.com/basics/contribute-to-an-extension).

**Comment by viandwi24** [comment]
thanks, i contribute to this one https://github.com/raycast/extensions/pull/7412

**Pull request closed without merging**
