### PR TITLE
Add Releases command to github repository search

### PR DESCRIPTION
**Pull request by Yukaii**
## Description

Add view Releases command to GitHub Repository search extension.

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author:  @thomaspaulmann

## Screencast

https://user-images.githubusercontent.com/4230968/140635776-b5df323c-c319-4213-9fb1-f73bc62dc982.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by Yukaii** [comment]
The CI build failed because the existing icon not match the 512x512 size. (which might be created before the CI setup) Not sure if we want to update the icon in this PR.

**Comment by pernielsentikaer** [comment]
Hi @Yukaii 👋 

It would be nice if you could update the icon size accordingly, if you're unsure how, please let me know and I'll help you do it 😄

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Yukaii 👋 

Awesome addition added. I gave it a quick spin and it works very well - a few times I got this error (can't remember repo) - We need to address this and handle the error gracefully

GX9QT53tRMeXj445

*Erorrmessage from console*
```
2021-11-09 07:42:47.039 F  Raycast[58669:2b1bf4] [com.raycast.extensions.github-repository-search:index] Warning: Failed prop type: The prop `title` is marked as required in `ListItem`, but its value is `null`.
    at ml (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:67:27026)
    at null.ReleaseView (/Users/pernielsentikaer/Desktop/flyyf/extensions/extensions/github-repository-search/src/index.tsx:183:61)
    at Is (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:11902)
    at ray-navigation-stack
    at nm (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:11535)
    at ul (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:11640)
    at Ps (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:10756)
    at QO (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:9717)
    at ray-root
    at Ef (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:11060)
2021-11-09 07:42:47.051 F  Raycast[58669:2b1c54] [com.raycast.extensions.github-repository-search:index]
Error: Cannot create rendering values
(Missing property 'title' in ["kind": listViewItem, "assetURL": file:///Users/pernielsentikaer/.config/raycast/extensions/github-repository-search/assets/, "path": /navigationStack/body/sections/0/items/0, "id": 9xHTumF6N71ZK8r4L5a6X, "onSelect": _commandView_navigationStack_body_sections_0_items_0_onSelect, "nodeId": _commandView_navigationStack_body_sections_0_items_0, "subtitle": v0.16.0, "accessoryTitle": 8/19/2020 8:58:19 AM, "title": <null>]	nil)

(Missing property 'title' in ["kind": listViewItem, "assetURL": file:///Users/pernielsentikaer/.config/raycast/extensions/github-repository-search/assets/, "path": /navigationStack/body/sections/0/items/0, "id": 9xHTumF6N71ZK8r4L5a6X, "onSelect": _commandView_navigationStack_body_sections_0_items_0_onSelect, "nodeId": _commandView_navigationStack_body_sections_0_items_0, "subtitle": v0.16.0, "accessoryTitle": 8/19/2020 8:58:19 AM, "title": <null>]	nil)
index.js:4:1156

---
1: var Cw=Object.create;var Tu=Object.defineProperty;var Iw=Object.getOwnPropertyDescriptor;var Aw=Object.getOwnPropertyNames;var Nw=Object.getPrototypeOf,xw=Object.prototype.hasOwnProperty;var qp=t=>Tu(t,"__esModule",{value:!0});var st=(t,n)=>()=>(t&&(n=t(t=0)),n);var Pt=(t,n)=>()=>(n||t((n={exports:{}}).exports,n),n.exports),Lw=(t,n)=>{qp(t);for(var o in n)Tu(t,o,{get:n[o],enumerable:!0})},Dw=(t,n,o)=>{if(n&&typeof n=="object"||typeof n=="function")for(let a of Aw(n))!xw.call(t,a)&&a!=="default"&&Tu(t,a,{get:()=>n[a],enumerable:!(o=Iw(n,a))||o.enumerable});return t},Et=t=>Dw(qp(Tu(t!=null?Cw(Nw(t)):{},"default",t&&t.__esModule&&"default"in t?{get:()=>t.default,enumerable:!0}:{value:t,enumerable:!0})),t);var vs=Pt(Qr=>{"use strict";Object.defineProperty(Qr,"__esModule",{value:!0});Qr.createJSONRPCErrorResponse=Qr.JSONRPCErrorCode=Qr.isJSONRPCResponse=Qr.isJSONRPCRequest=Qr.isJSONRPCID=Qr.JSONRPC=void 0;Qr.JSONRPC="2.0";Qr.isJSONRPCID=f<…>
```

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by thomaspaulmann** [comment]
Let's also add an icon to the show release details action

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Awesome @Yukaii 🚀 

We're SO close 💯 

A thing I think we should address would be the way search works on "Browse Releases" - let me know if you need ideas - see an example from Laravel here:

https://user-images.githubusercontent.com/38033107/141061454-fc3e78fd-7270-4999-8550-e08ba6c7d9ad.mp4

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pernielsentikaer** [comment]
Awesome @Yukaii  - It makes ALOT more sense to swap it, now the search makes a lot more sense 💯 

One last thing that I think should be added is a shortcut for "Browse Releases" now that you have added shortcuts to everything else, when its added, then we're ready to merge 💣

**Comment by Yukaii** [comment]
@pernielsentikaer Thanks for the review, I've added shortcut <kbd>Cmd</kbd> + <kbd>r</kbd> to the command. Although it's conflict with the "Reload" command, since that command is development-only, I think it's okay to use the shortcut.

**Comment by pernielsentikaer** [comment]
Awesome addition @Yukaii! - Let's mark it as ready to get merged 💎

**Pull request merged**
