### PR TITLE
feat:(google-search): add option to disable descriptions, autocomplete

### PR DESCRIPTION
**Pull request by erics118**
## Description

Adds a preference setting to disable showing the description of the search suggestion.
I don't like it because it doesn't show any that the icon+title doesn't already give me.

btw, all other file changes are from formatting or the updated extension config files

## Screencast

Disabled (no subtitles):
CleanShot 2023-11-01 at 21 36 42

Enabled (exact same as before):
CleanShot 2023-11-01 at 21 36 15

New autocomplete:

https://github.com/raycast/extensions/assets/52634785/52a1284f-84bb-4b39-a309-677064b0926a

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@mblode do you mind checking this?

**Comment by erics118** [comment]
Added a new autocomplete method that may be buggy. Would be nice if some people could test it.

**Comment by erics118** [comment]
Ok, there's a bug where you can't change searchText when you have selected a link/navigation type result

**Comment by erics118** [comment]
oops i was trying to rename the branch, didn't know it would break the PR

**Comment by erics118** [comment]
Can this be marked as "Dont close"? I want to work on this in the future, and this PR still is relevant

**Pull request closed without merging**
