### PR TITLE
New extension: Supernova.io

### PR DESCRIPTION
**Pull request by JiriTrecak**
## Description

Supernova.io is a super fast-growing platform to help designers and developers manage their design system, design system data and documentation.

We have created a Raycast extension to make accessing design system data easy for all of our users. In general, the extension allows you to:

- Search user documentation site
- Search design system styles
- Search design system assets
- Search and action upon design system components

We have used lot of fancy things that your API allows to do and also worked around some limitations in creative ways. We have made the system as performant as possible. 

## Screencast

To help you understand this a little bit better, I made a video just for the purposes of review, enjoy!

https://www.youtube.com/watch?v=FJcyuqnzo0U&ab_channel=Supernova

## How to test yourself

You'll need API key to test app yourself. For that, I have prepared a test account with some data linked to it. The access is as follows:

- Sign in here: `https://cloud.supernova.io/`
- Username: `raycast-review` [at] `domain.com`
- Password: `IFuckingLoveRaycast`

Let us know what you think! I am available on Raycast Slack as `Jiri (Supernova.io)` should you have some questions - reach out if needed!

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @JiriTrecak 👋 

Thanks for your contribution 🔥 

I tested the extension and it looks really awesome, I have some feedback for you to address:

- Every item in the [ActionPanel](https://developers.raycast.com/api-reference/user-interface/actions#api-reference) should have an icon

image

- Actions in the action panel should also follow the Title Case naming convention

- I tried to log in with the provided credentials without luck, it keeps telling me `Wrong email or password` - I'll do another round when this is working 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by JiriTrecak** [comment]
I have added title case where appropriate (command titles) unless command specifically mentions dynamic name (ie. Download page.png) as that is a filename and naming will be consistent for all commands in the list. I have added icon to custom actions where missing. Thank you for pointing this out, I will be more diligent in reading the list next time :)

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @JiriTrecak 👋 

Thanks for the corrections, it works a lot better now 🔥 

When trying to use any of the actions from `Search Assets` I get the error, seems to happen for all of the items, do you have an idea what might go wrong?

CleanShot 2022-08-23 at 20 45 46@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by JiriTrecak** [comment]
@pernielsentikaer Yes, I have, my bad. For security reasons, I have removed Figma integration for the reviewer account and it is used to render the images. I have reconnected the Figma integration for the review so you can proceed :) I have also exposed the error in the error message popup.

CleanShot 2022-08-24 at 08 22 02@2x

**Review by pernielsentikaer — APPROVED** [review]
I think we're ready to have the first version shipped, good job @JiriTrecak 🔥

**Pull request merged**
