### PR TITLE
Add owledge-raycast extension

### PR DESCRIPTION
**Pull request by RomainPct**
## Description

An extension to connect directly to your cloud tools via Owledge.

## Screencast

Preview_1
Preview_2
Preview_3

https://github.com/raycast/extensions/assets/30570099/1b18c10e-0efe-44e5-9ba9-f839ef2e0d91

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by RomainPct** [comment]
Hey @raycastbot, always getting an error on the author but it's my exact username. Do you know how can I fix it?

**Comment by pernielsentikaer** [comment]
You need insert your Raycast handle (not your GitHub handle)

**Comment by RomainPct** [comment]
Thanks for your recommandations @pernielsentikaer, Owledge extension for Raycast have been updated

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by RomainPct** [comment]
> :tada: :tada: :tada:
> 
> Such a great contribution deserves a reward, but unfortunately we couldn't find your Raycast account based on your GitHub username (@RomainPct).
> Please [link your GitHub account to your Raycast account](https://www.raycast.com/settings/account) to receive your credits and soon be able to exchange them for some swag.

Hope Owledge in Raycast will help a lot if people navigating their cloud knwoledge 👍

My Github account has been linked to my Raycast account ✅

**Pull request merged**
