### PR TITLE
Add jetpack-commands extension

### PR DESCRIPTION
**Pull request by sejas**
## Description

In this PR I'm adding a new extension, Jetpack Commands which allows users to manage their Jetpack-connected WordPress sites from Raycast.

Users will need to authenticates with the [WordPress.com](https://wordpress.com) API to retrieve information about their sites.

This extension makes it easier to manage your sites, like adding posts, open the phpMyAdmin database, copying the ssh connection string and creating new sites.

This extension simplifies site management, making it easier to _add new posts_, _open the database in phpMyAdmin_, _copy SSH/SFTP connection string_, _upload media_ and _add new sites_. 

## Screencast

https://github.com/raycast/extensions/assets/779993/68ef7f30-c2ce-4a37-ad42-1163f754be84

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Is there a way to merge some of the commands? 46 commands is quite a lot 🙂 Extensions like https://www.raycast.com/Kang/toolbox does it this way

**Comment by danielbachhuber** [comment]
> Is there a way to merge some of the commands? 46 commands is quite a lot 🙂 Extensions like https://www.raycast.com/Kang/toolbox does it this way

@pernielsentikaer Can you share a bit more detail about what you're hoping to see?

Most of our commands are navigational commands to various points in the admin interface (e.g. "Add new post" takes you to the screen to add a new post). We have some action commands too (e.g. "Copy SSH connection string").

Our intent with our Raycast extension is to make most of these destinations and actions available from Raycast. With this model, we'd expect to add more commands, not less.

Maybe this isn't appropriate for Raycast, though? I'd love to hear your thoughts on how we might achieve our goal.

Thanks for the awesome product!

**Comment by sejas** [comment]
@pernielsentikaer,
We tested the Raycast extension with multiple users and received positive feedback about adding the Jetpack Commands at the root level, rather than being hidden behind a single global command.
I understand the concern about adding multiple commands at once. However, if the extension isn't useful for a given user, they will simply uninstall it, won't they?
We also didn't observe any performance issues from having these commands installed.

Thanks for taking the time of reviewing the extension. We are looking forward to receiving your feedback.

**Comment by pernielsentikaer** [comment]
No problems if it doesn't make sense 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥 Let's get the first version out so we can iterate on it 🙂

**Comment by sejas** [comment]
Awesome! Thank you for approving it, and updating the package.json and Readme!  ✨

**Pull request merged**
