### PR TITLE
Add claude extension

### PR DESCRIPTION
**Pull request by florisdobber**
## Description

This extension is heavily based on the `chatgpt` extension, and has all the same functionality, but instead interacts with `claude` by Anthropic.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by florisdobber** [comment]
I included screenshots in the `metadata` folder, that I also want to display in the `README`, so I fail the checkbox. If that is an issue please let me know how you would like me to resolve it.

**Comment by xilopaint** [comment]
> I included screenshots in the `metadata` folder, that I also want to display in the `README`, so I fail the checkbox. If that is an issue please let me know how you would like me to resolve it.

[From the docs](https://developers.raycast.com/basics/prepare-an-extension-for-store#provide-readme-if-additional-configuration-required):

> Supporting README media: Put all linked media files in a top-level media folder inside your extension directory. (This is different from assets that are required at runtime in your extension: they go inside the assets folder and will be bundled into your extension.)

**Comment by florisdobber** [comment]
> > I included screenshots in the `metadata` folder, that I also want to display in the `README`, so I fail the checkbox. If that is an issue please let me know how you would like me to resolve it.
> 
> [From the docs](https://developers.raycast.com/basics/prepare-an-extension-for-store#provide-readme-if-additional-configuration-required):
> 
> > Supporting README media: Put all linked media files in a top-level media folder inside your extension directory. (This is different from assets that are required at runtime in your extension: they go inside the assets folder and will be bundled into your extension.)

I was unclear, I meant to say that the screenshots in the `metadata` folder are to be shown in the extensions details screen, but I also used to them in my `README`. The only alternative I see is to duplicate the images in the `metadata` folder and use the duplicates in the `README`, but that felt unnecessarily complicated.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
