### PR TITLE
[Transmission] Fix remove and delete local data command

### PR DESCRIPTION
**Pull request by timmevandermeer**
## Description

The Transmission extension is useful, but I noticed that the command to remove a torrent and delete local data did not actually delete local data. This PR fixes that.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by FezVrasta — APPROVED** [review]

**Review by danpalmer — APPROVED** [review]
LGTM, thanks!

**Comment by pernielsentikaer** [comment]
Would it be okay it we updated Raycast API @FezVrasta

**Comment by timmevandermeer** [comment]
@FezVrasta any updates on the above?

**Comment by FezVrasta** [comment]
Sure, go ahead

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
