### PR TITLE
Add openinterpreter extension

### PR DESCRIPTION
**Pull request by Cobular**
## Description

Run Open Interpreter from the comfort of Raycast! The last Raycast command you'll ever need - do anything you can imagine on your computer!

Note on the last item on the checklist - can I use one of the product screenshots that need to be in metadata in my readme without duplication?

## Screencast

https://github.com/raycast/extensions/assets/22972550/06973f4b-7ef5-4a5a-a8c5-994d4fd8d0e8

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi! 

Thanks for your contribution! My name is Milena and I will be reviewing your extension today.
I noticed that it has been failing for a while. Have you run prettier before submitting?

**Comment by Cobular** [comment]
Ok great, got it fixed - pushing in now

**Comment by Cobular** [comment]
Update: I need to do some force pushes on my branch to clean out some garbage. Give me just a sec..

**Comment by Cobular** [comment]
I'm having issues getting the ray cli to actually let me publish again - give me a bit to figure out what's going on. Where is my Raycast repo that ray CLI actually uses stored on disk? I need to go in and unfuck the git repo

**Comment by Cobular** [comment]
@mil3na whoo finally - https://github.com/raycast/extensions/pull/8943 I've got it ready - apologies for the delay

**Pull request closed without merging**
