### PR TITLE
Add gitmoji-commit extension

### PR DESCRIPTION
**Pull request by zrr1999**
### Gitmoji Commit

[Gitmoji Commit](https://github.com/zrr1999/gitmoji-commit) is an emoji commit messages generator.

#### Features

- [x] Search gitmoji by name
- [x] Generate commit message by LLM following selected text
- [ ] History of generated commit messages
- [ ] Support custom emojis
- [ ] Integrate with git diff

#### Preferences

You can customize the following preferences:

- `Emoji Format`: Choose between `emoji` and `emoji code`.
- `Copy Format`: Choose between `emoji-type` and `emoji`.
- `Terminator`: Change the terminator of the commit type and message.
- `Action`: Choose between `Copy to Clipboard`, `Paste into Editor` and `Copy and Paste`.

#### Customize

You can fork this repo and change the `src/lib/types.ts` to add more gitmojis.

This PR is auto-generated by [create-pull-request][1]
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

[1]: https://github.com/peter-evans/create-pull-request

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
What's the difference between this and https://www.raycast.com/ricoberger/gitmoji

**Comment by zrr1999** [comment]
> What's the difference between this and https://www.raycast.com/ricoberger/gitmoji

Compared to [ricoberger/gitmoji](https://www.raycast.com/ricoberger/gitmoji), there are two main differences:
1. It can generate a commit message based on the user-selected content (or clipboard content).
2. It supports more setting options, mainly to facilitate the generation of a specified format for commit messages, such as `🐛 fix: ` instead of just `🐛`.

Export-1727783551464

image

**Comment by pernielsentikaer** [comment]
Would it be possible to enhance the current one by @ricoberger instead of having a similar extension?

**Comment by zrr1999** [comment]
> Would it be possible to enhance the current one by @ricoberger instead of having a similar extension?

The primary goal of this extension is to generate or format commit messages, rather than simply searching for gitmoji. I have modified the plugin name and improved the search page. Now, multiple generated commit messages will be displayed on the search page. I have submitted another [PR](https://github.com/raycast/extensions/pull/14784).

**Comment by zrr1999** [comment]
> So this PR should be closed, or?

yes

**Pull request closed without merging**
