### PR TITLE
Update claude extension

### PR DESCRIPTION
**Pull request by alejandrotercero**
## Description
Added support for the beta 8192 output for sonnet. 3.5 (added as an option on the extension preferences) 
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by alejandrot96** [comment]
About the constants, yeah we could do it that way but I think you can only use one beta header at a time with the api, in the end it depends on how Anthrophic implements the longer outputs when it's not in beta anymore or if they add other beta features.

**Comment by florisdobber** [comment]
I think the `useBetaFeatures` preference flag is overkill for this functionality. Removing the flag should simplify both the implementation and usage. Can you update the PR to reflect those changes? So the beta header is always used when Sonnet 3.5 is selected and keep the code for allowing users to select up to 8192 tokens for Sonnet 3.5. I'm indifferent about the constants, that's your call.

I'm assuming this will become part of the standard API soon, so I want to minimize the changes made. 

Besides that, thanks for the quick spot and implementation! 🚀 (I also follow @alexalbert__ now)

**Comment by alejandrot96** [comment]
Works for me! I'll make the changes later today

**Comment by florisdobber** [comment]
Hey, it seems like not all references to the `preference` flag have been removed. Until those are cleaned up I don't think we should merge this PR.

**Comment by alejandrot96** [comment]
Is this good now? 😅

**Review by mil3na — APPROVED** [review]
Sure! You should have pinged me earlier :)

**Pull request merged**
