### PR TITLE
Add Akkoma extension

### PR DESCRIPTION
**Pull request by sevi418**
## Description

Publish status from Raycast to [Akkoma](https://akkoma.social/) or [Pleroma](https://pleroma.social/), and view your bookmarked status

**Features**:
- Write status with markdown support.
- Publish simple status with text.
- Publish scheduled status with natural date format.
- Publish status with attachments (image, video, files); add alt text to the image when only one image is attached.
- Save draft status.
- View your bookmarked statuses.
- View your latest statuses.
- Open the latest published status that was published from Raycast through the actions.
### Mark status as sensitive 
Toggle the "Sensitive" checkbox to mark the attached image as sensitive, or add a content warning to the status.

### Write status with markdown
Toggle the "Markdown" checkbox to render markdown in the text file. Markdown shortcuts are also supported (e.g., pressing `⌘` + `B` will add `**bold**` around the selected text, `⌘` + `I` will make the selected text italic, etc.).

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋 

Is there a place I can test this or get a test account so I can test the setup process?

**Comment by Sevichecc** [comment]
> Hi 👋
> 
> Is there a place I can test this or get a test account so I can test the setup process?

Thanks for your interest! There is a test account available on [kongwoo.icu](https://kongwoo.icu). The login info is:
```
username: test
password: 12345678
```

Please note that this instance is not as stable as other instances, so it may occasionally return 503 errors.

And in the URL field, you can input 'kongwoo.icu': 

login

**Comment by pernielsentikaer** [comment]
Thanks for the test data 🔥

Do you mind that we're removing all the smileys in toasts? 😊

**Comment by Sevichecc** [comment]
> Do you mind that we're removing all the smileys in toasts? 😊
That’s ok, though a bit of a pity 🥺

**Pull request merged**
