### PR TITLE
Add backstage extension

### PR DESCRIPTION
**Pull request by yukukotani**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

I'm marking your PR as a draft as it is not passing the checks. As soon as you fix this, it will be reviewed :D

**Comment by yukukotani** [comment]
@mil3na Hi Milena, thank you for your review. Now it's passing all checks!

**Comment by mil3na** [comment]
Hey! I don't have access to a backstage instance. Do you know if there is a free way to access a dummy one or can you create a screencast of this extension's usage?

**Comment by yukukotani** [comment]
@mil3na You can check with the demo instance `https://demo.backstage.io`. It's a bit slow but works well with the extension.

**Comment by mil3na** [comment]
Hey! I tried with the demo instance and it seems to work. However, I don't really understand what the extension is doing. After selecting a component, most of the times it shows me nothing. Is that expected? I'm a bit concerned about the usability of this extension.
I'm also missing screenshots for the extension.

**Comment by yukukotani** [comment]
@mil3na What you see after selecting a component is *Links*, which is related to the component. You can see them in [the backstage page](https://demo.backstage.io/catalog/default/component/artist-lookup).

In general, most of the components have links, so that users would be happy about easier access via Raycast. The demo instance is not like that because it's just a demo.

**Comment by yukukotani** [comment]
> I'm also missing screenshots for the extension.

Should I append them?

**Comment by yukukotani** [comment]
In depth, our common usage of links are like:

- IaC codebase
- Infra log
- Sentry link
- Metrics dashboard

**Comment by mil3na** [comment]
Yes, please add screenshots following our guidelines: https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots

**Comment by yukukotani** [comment]
@mil3na Done!

**Comment by mil3na** [comment]
I see a few more commits, do you need more time?

**Comment by yukukotani** [comment]
@mil3na Sorry for the confusion! It's ready.

**Review by mil3na — APPROVED** [review]
LGTM

**Pull request merged**
