### PR TITLE
Add brandfetch extension

### PR DESCRIPTION
**Pull request by yonbergman**
## Description

A simple extension that let's you quickly search for brand logos on Brandfetch

## Screencast
brandfetch-3

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for the contribution 🔥 

Sorry for the long response time. Due to the Easter vacation, we have a slightly increased response time, but it should soon return to normal.

We already have #11248 in the queue, maybe some features from yours could enhance that one? Currently i'm waiting for the author to respond

**Comment by yonbergman** [comment]
> Hi 👋
> 
> Thanks for the contribution 🔥
> 
> Sorry for the long response time. Due to the Easter vacation, we have a slightly increased response time, but it should soon return to normal.
> 
> We already have #11248 in the queue, maybe some features from yours could enhance that one? Currently i'm waiting for the author to respond

Yeah, there's opportunity to add some of his stuff into mine I guess. (Because he's using the paid API)
How do you usually handle multiple similar extensions proposed at once?

**Comment by yonbergman** [comment]
> Perhaps it makes sense to keep them separate and then we just need to ensure clarity regarding the naming, so end users can easily select the appropriate option. Does that make sense?

Sure does naming this Brand Fetch (Free) make sense?

**Comment by pernielsentikaer** [comment]
Name doesn't have to be the name, could also be something like "Search Brands" and mention in description somehow

**Pull request closed without merging**
