### PR TITLE
Add an extension for searching Rust crates

### PR DESCRIPTION
**Pull request by belltoy**
## Description

Search Rust crates on [Crates.io](https://crates.io). And provide a convenient way to open crates' pages
on [crates.io](https://crates.io), [docs.rs](https://docs.rs) and its repository.

### Features

- Search Rust crates on crates.io
- Provide a convenient way to open crates docs, homepage, and repository
- Provide two style result views, with and without details

## Screencast

screenshot-1

screenshot-2

screenshot-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @belltoy 👋 

Have you seen this [extension](https://www.raycast.com/matt/cratecast)? It could be an idea to enhance that one 😊

**Comment by belltoy** [comment]
I just noticed that extension.

@mathieudutour Do you mind merging this extension to the [crates.io extension](https://www.raycast.com/matt/cratecast)?

**Comment by pernielsentikaer** [comment]
What do you think @gleich about this? Would it make sense to merge this?

**Comment by gleich** [comment]
Besides adding some icons I am not sure how this differs from mine. Is there anything special that your version does that mine doesn't @belltoy?

**Pull request closed without merging**
