### PR TITLE
Improve Todoist extension

### LINKED ISSUE #208: [Extension Feature Request] Todoist Create Task Menu Improvements
## Extension – [Todoist](https://github.com/raycast/extensions/tree/main/extensions/todoist)
**Author**: @thomaslombart 

## Describe the feature and the current behavior/state.
The Create Task menu stays as-is when a task is created. The form does clear, nor does it send you to a different page when it's submitted.

## Will this change the current api? How?
I suggest that once the task is created the project view for the task's selected project should open. There can also be a CMD-k menu option that doesn't open the project view and instead creates the task and clears the form.

## Who will benefit from this feature?
Anyone using the Todoist Raycast integration to add tasks.

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

Add further improvements to the Todoist extension:

- Add ability to go to project when a new task is created
- Add loading state to different toasts
- Add an error when a user doesn't provide a title when creating a task
- Clear form when creating a task
- Add labels in task creation
- Support overdue tasks in today and upcoming view
- Improve documentation to make it more readable

Closes #208 

## Type of change

- Bug fix / improvement for my extension

## Screenshots

CleanShot 2021-11-23 at 23 15 42@2x

CleanShot 2021-11-23 at 23 15 19@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
Very cool changes. This extension is getting better and better 👏

**Review by pernielsentikaer — COMMENTED** [review]
Hi @thomaslombart 👋 

I'm going to do the full review a bit later today, just having a quick comment for now 😄 

- It would be awesome if the three views Today Tasks, Upcoming Tasks and Search Projects had an error toast when token is wrong, just like “Create Task” have — is that possible?

**Comment by thomaslombart** [comment]
Hi @pernielsentikaer, I'm not sure I got what you mean. Did you mean showing an error toast when getting the tasks/projects fail due to the Todoist token being invalid or similar reason?

**Comment by pernielsentikaer** [comment]
@thomaslombart, correct! Sorry for not clarifying this good enough, that's my mistake 😄 
Zp87PHc1MUCKJloc

**Comment by thomaslombart** [comment]
@pernielsentikaer Ready to review 🙂

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @thomaslombart 👋 

Awesome addition, I tested it thoroughly and couldn't find anything not working, good job 👏
 
- Did you add the token error to the three views Today Tasks, Upcoming Tasks and Search Projects? If so, it looks like it's not working

https://user-images.githubusercontent.com/38033107/143671488-284c0194-e1f0-4965-ace7-ead7b8b43fb3.mp4


We're close to merging this update 🚀 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by thomaslombart** [comment]
@pernielsentikaer Oops forgot to do it! It should be good now.

**Review by pernielsentikaer — APPROVED** [review]
Hi @thomaslombart 🔥 

MUCH better 😄 I'm going to accept it now and then will my colleague do a last review before  merging it in 💪 

Thanks for an awesome update 🚀

**Pull request merged**
