### PR TITLE
Update jira-time-tracking extension

### PR DESCRIPTION
**Pull request by haydencbarnes**
## Description

Added preference options for Custom JQL Query and Default Project. Fixed a found type safety issue.

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by haydencbarnes** [comment]
Fix for https://github.com/raycast/extensions/issues/15640

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @haydencbarnes 🔥

@niallpaterson do you want to check this?

**Comment by haydencbarnes** [comment]
@pernielsentikaer I believe on a previous change I made to this extension @niallpaterson said that he no longer has access to a Jira instance so unable to really test this

**Comment by haydencbarnes** [comment]
@pernielsentikaer sure, please view: https://drive.google.com/file/d/1IJMkIbhlIjqpEcMC3qy8jubSfFrP5aRm/view?usp=sharing

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
