### PR TITLE
Reclaim - Make Smart Habit actions respect override setting / fail API errors silently / only strip planner emojis

### PR DESCRIPTION
**Pull request by clayton-knapp**
## Description

Update contributors list
Only strip planner emojis
Have smart habit actions respect unscheduleRestartedOverride setting
Fail useFetch API calls silently
Code improvements and cleanup

## Screencast

Screen Shot 2024-08-13 at 4 57 40 PM
Screen Shot 2024-08-13 at 4 57 45 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by gunrein** [comment]
Looks good to me!

**Comment by clayton-knapp** [comment]
@pernielsentikaer are you able to review?

**Comment by pernielsentikaer** [comment]
@ajohnson1200, did you also check this? I can see a lot more contributors added; is that intended?

**Comment by gunrein** [comment]
@pernielsentikaer - @ajohnson1200 isn't available but I'm also a contributor (previous to this PR; my username in the diff is due to the addition of a trailing comma) and approve of it. The additional contributors are folks from our team at Reclaim/Dropbox who will be contributing.

**Comment by pernielsentikaer** [comment]
Thanks for the explanation 🔥

Let's merge this Monday so we can take action if something goes wrong 🙂

**Pull request merged**
