### PR TITLE
update to support custom date format

### PR DESCRIPTION
**Pull request by randomradio**
## Description

update to support custom date format

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Seems like it doesn't work as expected, could you have a look?

https://user-images.githubusercontent.com/38033107/236118617-52261499-169c-4ec5-97dc-acb5e97953c9.mp4

**Review by randomradio — COMMENTED** [review]
soy, i made a mistake not including the changes in React template. will fix

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I'm missing some titles too, not sure what I'm looking at

Raycast-Atd7iUHO@2x

@yangxyo do you mind checking this too

**Comment by pernielsentikaer** [comment]
I'm still not 100% sure what the fields are for. If you look at this screenshot, shouldn't that work?

Raycast-fGNFqRII@2x

**Comment by pernielsentikaer** [comment]
Can you tell me how I use this extension @randomradio

**Pull request closed without merging**
