### PR TITLE
update file-manager extension

### PR DESCRIPTION
**Pull request by es183923**
## Description

- add image previews ('png', 'jpg', 'ico', 'webp', 'gif' only)
- get a video showcasing new functionality
- added preference to add a slash to end of directories
- better sorting (numbers go in order)
- more copy commands

## Type of change

- Bug fix / improvement for my extension

## Screencast

- todo

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by es183923** [comment]
I'd like some testing to be done for the symlinks and the images.

**Comment by aesign** [comment]
@es183923 I'm getting an error

Screenshot 2021-11-22 at 15 25 56@2x

That's probably related to google drive's file

**Comment by es183923** [comment]
@aesign could you provide an example file that has this error?

**Comment by fe9lix** [comment]
Hey @es183923 – what is the status of this PR?

**Comment by es183923** [comment]
The bug that was mentioned was always present since the first version, so I think it's okay for now.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @es183923 👋 

Awesome update 🔥 

I gave it a spin and found some things:

- Initial load takes ~21 seconds when loading ~ (MacBook Pro (13-inch, M1, 2020) 16 GB RAM)
- When entering a directory with a 6gb file, it crashes after a long time

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by es183923** [comment]
How many files/folders do you have in your home directory?

**Comment by pernielsentikaer** [comment]
Hi @es183923 

Is there something I can assist you with? We can take a Slack session if needed

**Comment by mattisssa** [comment]
Hey @es183923! I've resolved the conflicts you had. Let's get this PR merged, I haven't found any issues with the extension.
Wairing for your approval that I didn't miss anything while rebasing.

**Comment by es183923** [comment]
@mattisssa It looks fine. You can merge this now.

**Review by mathieudutour — CHANGES_REQUESTED** [review]

**Comment by aesign** [comment]
> @aesign could you provide an example file that has this error?

Hello @es183923 , sorry for writing only now. I fixed the issue myself, it was enough a line:
Screenshot 2022-01-26 at 12 33 45@2x

Here's an example .gdoc file so you can look into it for a better solution:
[Untitled.gdoc.zip](https://github.com/raycast/extensions/files/7941430/Untitled.gdoc.zip)

**Comment by mattisssa** [comment]
Hey @es183923! Could you please apply the proposed changes from above related to the preferences `name`?
Ping me once it's done so we can get the PR merged.

**Comment by mattisssa** [comment]
@es183923 Hey, you have some errors in your extension: 
CleanShot 2022-02-14 at 21 36 55@2x

**Comment by mattisssa** [comment]
Please, test out your extension properly, seems like it still has some errors:
CleanShot 2022-02-14 at 22 09 14@2x

**Pull request closed without merging**
