### PR TITLE
Add klack extension

### PR DESCRIPTION
**Pull request by henrikruscon**
## Description

An extension for [Klack](https://tryklack.com) that enables you to control it.
Toggle Klack, set your desired volume level, change to your preferred switch set.

## Screencast

https://github.com/raycast/extensions/assets/1430576/5299ab1c-9336-4beb-84c1-a243e4c368e5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by henrikruscon** [comment]
Apple being Apple just rejected Klack v1.4.1 that's been in review for more than 24h on the grounds of marketing screenshots (which haven't been changed since Klack v1.3 and has been approved multiple times).

This extension depends on a change in the Apple Script Commands API for Klack to be able to fully function. Was not expecting this as they are generally approving releases within hours nowadays. I know you have a 5 days approval but if for any reason there was gonna be a speedy approval, please hold off a little until it's resolved.

Sorry for the inconvenience. Will update with another comment as soon as it's resolved with Apple.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The extension crashes when you don't have the application installed, could you handle that gracefully? Maybe check how the extension [Eagle](https://www.raycast.com/Yukai/eagle) handles it 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by henrikruscon** [comment]
Thank you for the info, should be handled now.

**Comment by henrikruscon** [comment]
Oh and Apple has approved the update so ready when you are.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
