### PR TITLE
Add Microsoft Edge extension

### PR DESCRIPTION
**Pull request by KartikKumarSahoo**
## Description
Manage Microsoft Edge from Raycast. It can list all the open tabs, go to the selected, search from history, and open a new tab. 

Have extended an existing extension named "google-chrome", rather than creating a new one from scratch. I hope folks are okay with it. cc: @rgomezcasas, @thomaspaulmann, @bromanko, @HenriChabrand, @pernielsentikaer, @grzegorzkrukowski 

## Type of change
- New extension

## Screencast
https://user-images.githubusercontent.com/1303015/141615232-ccc38ccf-67e5-40d7-bba9-1f3905b081a6.mov

## Checklist
- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @KartikKumarSahoo 👋 

Found a quick showstopper that we need to address before going further 😄 

Errors should be handled gracefully, if you don't have Microsoft Edge installed, otherwise it just looks like this:

13gNYAEsMOOkvFk5

Pu9bB1pBbry4c2OS

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by KartikKumarSahoo** [comment]
Thanks, @pernielsentikaer for the quick review and nice findings. 😄 Will fix and raise a new review.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @KartikKumarSahoo 👋 

Much better! I noticed that sometimes does “Search Tab” only pops to root (without closing) main window — but it's not reproductive all the time — I can't find the pattern! 😢 

A thing I noticed is that ActionPanel.items are missing icons as [mentioned here](https://developers.raycast.com/basics/prepare-an-extension-for-store#action-panel)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by KartikKumarSahoo** [comment]
Thanks, @pernielsentikaer for the review again. I'll try reproducing that and fix the same and let you know. Please don't review until I mention you in a comment to review. Saying this because I might push things half done. So please wait for my comment to review the next time. Thanks for understanding and so sorry for troubling you. :)

**Comment by pernielsentikaer** [comment]
> Thanks, @pernielsentikaer for the review again. I'll try reproducing that and fix the same and let you know. Please don't review until I mention you in a comment to review. Saying this because I might push things half done. So please wait for my comment to review the next time. Thanks for understanding and so sorry for troubling you. :)

You're not troubling me at all, I'm just glad that I can help you out 😄 You could make the PR as a draft until you're ready, that would be the best way to ensure no one is doing anything 💯

**Comment by KartikKumarSahoo** [comment]
I have fixed all the bugs reported. Please have a look when you get time. @pernielsentikaer

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @KartikKumarSahoo 👋  I always have time for you 😄 

So much better, we're getting pretty close 🚀 

I found a strange behavior:
- When using “New Tab” command, 5/11 times it just pops to root while the rest of them also closes the window — rest of the commands closes the windows and pops to root

Can you reproduce this and look into it?

**Comment by KartikKumarSahoo** [comment]
Hi @pernielsentikaer, thanks a lot for your help and support. 🙏🏻 I could reproduce the problem and fix the same. Please take a look when you get time.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @KartikKumarSahoo 👋 

Thanks for adding another command 💯 

I tested it without having a collection and only getting the message “Microsoft Edge not installed” — after adding a few pages to collections it works as expected 👏  So we're really close now 💪

**Comment by KartikKumarSahoo** [comment]
Hi @pernielsentikaer 👋

  Thanks for checking all the cases and helping me shape the extension better. Fixed the above problem as well. Hope this time everything works. 🤞🏻

**Review by pernielsentikaer — APPROVED** [review]
Hi @KartikKumarSahoo 

Much better, awesome 💪 

I'm going to approve it now and then a colleague will do the last checking 💯  Again, thank you for a awesome extension 🥇

**Comment by KartikKumarSahoo** [comment]
Thanks a lot @pernielsentikaer. 🤝

**Comment by elcidowneador** [comment]
Hi @[KartikKumarSahoo](https://github.com/KartikKumarSahoo)

Could you add also compatibility with Edge Beta/Dev, please? Tried to rename app name to remove 'dev' but doesn't work.

**Pull request merged**
