### PR TITLE
[ChatGPT]: support Groq and Ollama

### PR DESCRIPTION
**Pull request by bxb100**
## Description

- break change: Remove `useApiEndpoint` `useAzure` and `azureEndpoint` from the settings; use `apiEndpoint` instead `azureEndpoint`, use `apiEndpoint` empty or not instead of originally enable checkbox
- support Ollama and Groq
- remove `onSelectionChange` due to [issue](https://github.com/raycast/extensions/issues/10844)

### effect: 
- using Azure OpenAI will be affected by this PR, they need to change the `apiEndpoint`
- can't use both OpenAI and `Azure OpenAI` by checkbox
- change `provider`, the original model setting may not be suitable, but it seems not a real edge case
- this extension chatGPT will not be "OpenAI" only, but akin to OpenAI

## Screencast

image

https://github.com/raycast/extensions/assets/20685961/7b9f24ae-62aa-42d3-9857-f7c606baa6bd

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Wouldn't that be odd, given that this is an OpenAI ChatGPT extension? Llama and Groq are not from OpenAI, correct?

**Comment by bxb100** [comment]
Ya, I admit it's a bad idea, and Groq/Llama isn't as useful as I expected.

**Comment by reneleonhardt** [comment]
Would it make sense to fork chatgpt into a separate extension instead to change it to allow working with local models through ollama?

**Comment by bxb100** [comment]
> Would it make sense to fork chatgpt into a separate extension instead to change it to allow working with local models through ollama?

The extension now can define the model name, which allows it to support Ollama in some way.

**Pull request closed without merging**
