### PR TITLE
[Update][Speedtest] Detailed view

### PR DESCRIPTION
**Pull request by aliaksandrZh**
## Description
 The issue https://github.com/raycast/extensions/issues/12423
 
- Add a detailed view.
 - Add an action to copy detailed view data.
 - Increase types coverage.
 - Refactor code to improve maintainability and scalability

## Screencast

[speedtest-detailed-view.webm](https://github.com/raycast/extensions/assets/108681764/9c26d097-d641-41bb-a00e-19c74768d276)

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution 🔥 

I don't think it makes sense to show the Detailed View action panel item before the test i done since it doesn't work before

**Review by tonka3000 — APPROVED** [review]

**Comment by pernielsentikaer** [comment]
@aliaksandrZh can we maybe make it possible to show the details view before it's done, it feels weird to have the button when nothing happens

**Comment by aliaksandrZh** [comment]
> @aliaksandrZh can we maybe make it possible to show the details view before it's done, it feels weird to have the button when nothing happens

Will check and let you know

**Comment by aliaksandrZh** [comment]
@pernielsentikaer Take a look please

It is how it looks like

https://github.com/raycast/extensions/assets/108681764/b27e5260-170f-42fb-a742-facc76790d99



The other option is hide the detailed view button until the test is done

**Comment by xilopaint** [comment]
You should use a capital "V" for the "Detailed View" action title.

**Comment by pernielsentikaer** [comment]
Is there a way to show prettier titles here? It looks a bit sad 🙂

speedtest 2024-06-06 at 09 05 55

**Comment by xilopaint** [comment]
I didn't install the extension to test, but what happens when we run the primary action (View Details)?

**Comment by pernielsentikaer** [comment]
https://github.com/raycast/extensions/assets/38033107/fc9063ab-2351-47c2-ba53-7065e5ba9ecb

**Comment by xilopaint** [comment]
Oh, in that case it seems that my suggestion was not appropriate. The primary action seems to hide the details and not show them. Am I correct?

**Comment by xilopaint** [comment]
Oh, it seems there's an issue. After displaying the details by running the "Show Details" action, the action title is still the same when it should change to "Hide Details". Am I correct?

**Comment by pernielsentikaer** [comment]
It could simply say `Toggle Details` instead 🙂

**Comment by pernielsentikaer** [comment]
But it would still be nice to have title/values formatted 🙂

**Comment by xilopaint** [comment]
> But it would still be nice to have title/values formatted 🙂

Agree.

**Comment by pernielsentikaer** [comment]
@aliaksandrZh are you up for that, otherwise let me know and I do it 🙂

**Comment by aliaksandrZh** [comment]
> @aliaksandrZh are you up for that, otherwise let me know and I do it 🙂

I can work on that tomorrow

**Comment by aliaksandrZh** [comment]
In the last commit:
* ISP section fills immediately. (Before: it was filled when test finished only)
* Added readable names for the details
* Added Icons for the sections title. Icons are the same as we see on the initial list view.
* The details items of the result section have the same order as items on the initial view.
image
@pernielsentikaer feel free to test and review

**Comment by xilopaint** [comment]
I don't see much coherence regarding the colors. I know this wasn't changed by this PR, but I would vote to use the default color for all the items on the list.

Also, I suggest using the following icons as replacements for the current ones:

1) `Icon.Globe` for Ping
2) `Icon.Livestream` for Streaming
3) `Icon.Link` for Result Link

**Comment by aliaksandrZh** [comment]
Sticking to the default color schema is more convenient for me. if no one mind we can update it

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
@aliaksandrZh what do you think about the icons @xilopaint mentions?

**Comment by aliaksandrZh** [comment]
I'm ok to update the icons. But what about colors?  @pernielsentikaer @xilopaint

**Comment by xilopaint** [comment]
Hey @aliaksandrZh, I will submit a PR with those improvements and some others.

**Pull request merged**
