### PR TITLE
feat: add icones

### PR DESCRIPTION
**Pull request by Fatpandac**
## Description

Search icons via Iconify and copy for SVG, Vue Components, React Components, and so on.

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @Fatpandac 👋 

Have you [seen this extension](https://www.raycast.com/destiner/iconify), it looks a bit like what you're building, maybe it's better to enhance the current one. Looking forward to hearing from you 🙂

**Comment by Fatpandac** [comment]
I don't want to merge it with others.
I'm so sorry. 🙏

**Comment by pernielsentikaer** [comment]
What is the difference between this and the other? It doesn't make a lot of sense to have two almost identical extensions in the store 🙂

**Comment by Fatpandac** [comment]
[This](https://www.raycast.com/destiner/iconify) extension can search the icon to check its availability. My extension is built for front-end dev, they can use it easy to create icon components for many different front-end frameworks. We just need to choose the icon and hit the enter button then the code is created and copied into the clipboard. The code is like the one below.

```vue
<template>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1em" height="1em" viewBox="0 0 24 24">
        <g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2">
            <path d="M11 7c4.418 0 8 .895 8 2s-3.582 2-8 2s-8-.895-8-2c0-.357.375-.693 1.033-.984"></path>
            <path d="M3 9v9.343c0 1.061.44 2.08 1.409 2.513C5.624 21.399 7.711 22 11 22c3.29 0 5.377-.601 6.591-1.144c.968-.433 1.409-1.452 1.409-2.513V9m0 1v0a3 3 0 0 1 3 3v0a3 3 0 0 1-3 3v0M7 3v4m4-5v2m4 0v3"></path>
        </g>
    </svg>
</template>

<script>
export default {
  name: 'AkarIconsCoffee'
}
</script>
```

**Comment by Fatpandac** [comment]
[This](https://www.raycast.com/destiner/iconify) extension can search the icon to check its availability. My extension is built for front-end dev, they can use it easy to create icon components for many different front-end frameworks. We just need to choose the icon and hit the enter button then the code is created and copied into the clipboard. The code is like the one below.

```vue
<template>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1em" height="1em" viewBox="0 0 24 24">
        <g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2">
            <path d="M11 7c4.418 0 8 .895 8 2s-3.582 2-8 2s-8-.895-8-2c0-.357.375-.693 1.033-.984"></path>
            <path d="M3 9v9.343c0 1.061.44 2.08 1.409 2.513C5.624 21.399 7.711 22 11 22c3.29 0 5.377-.601 6.591-1.144c.968-.433 1.409-1.452 1.409-2.513V9m0 1v0a3 3 0 0 1 3 3v0a3 3 0 0 1-3 3v0M7 3v4m4-5v2m4 0v3"></path>
        </g>
    </svg>
</template>

<script>
export default {
  name: 'AkarIconsCoffee'
}
</script>
```

**Comment by Fatpandac** [comment]
[This](https://www.raycast.com/destiner/iconify) extension can search the icon to check its availability. My extension is built for front-end dev, they can use it easy to create icon components for many different front-end frameworks. We just need to choose the icon and hit the enter button then the code is created and copied into the clipboard. The code is like the one below.

```vue
<template>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1em" height="1em" viewBox="0 0 24 24">
        <g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2">
            <path d="M11 7c4.418 0 8 .895 8 2s-3.582 2-8 2s-8-.895-8-2c0-.357.375-.693 1.033-.984"></path>
            <path d="M3 9v9.343c0 1.061.44 2.08 1.409 2.513C5.624 21.399 7.711 22 11 22c3.29 0 5.377-.601 6.591-1.144c.968-.433 1.409-1.452 1.409-2.513V9m0 1v0a3 3 0 0 1 3 3v0a3 3 0 0 1-3 3v0M7 3v4m4-5v2m4 0v3"></path>
        </g>
    </svg>
</template>

<script>
export default {
  name: 'AkarIconsCoffee'
}
</script>
```

**Pull request closed without merging**
