### PR TITLE
SABnzbd: Add job moving

### PR DESCRIPTION
**Pull request by jesse-c**
## Description

Jobs (slots) can be moved up and down. After either operation, the list of slots is refreshed. The position of a job is important as dictates the priority in being downloaded.

This isn't the greatest code, but alas.

I've added a set of arrow icons too. They're not all being used, yet.

## Type of change

- Bug fix / improvement for my extension

## Screencast

up

up-down

down

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @jesse-c 👋 

Just like the last time, I have no way to actually test how it works, but it looks like it does what I expect.

A single suggestion:
- It looks like you're importing node-fetch in many of the scripts where is not in use, if so, could you tidy it up by removing them?

**Comment by jesse-c** [comment]
@pernielsentikaer: 😅

I've removed `node-fetch` now.

**Comment by pernielsentikaer** [comment]
I'm going to mark this as accepted and my colleague will give it a final check tomorrow 😄

**Comment by jesse-c** [comment]
Thank you!

**Pull request merged**
