### PR TITLE
Update center extension

### PR DESCRIPTION
**Pull request by artivilla**
## Description

I noticed the current version was not working so I updated the api to V2 and made some other upgrades.
- removed param value passing if only a single param was passed to hooks
- added a non hook fetch method to append images to nft collections
- removed argument interfaces
- added viewing the token type as a subtitle

Few other add-ons I think would be nice are:
- opening the contract in etherscan
- copying smart contract address action
- optionally hide contracts/nfts that do not have media

## Screencast

Screenshot 2024-03-01 at 6 19 37 AM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by artivilla** [comment]
Still noticing a bug when you hit backspace, it clears the entry rather than going back: https://www.loom.com/share/779a990335a3498190c44070109cf5c7?sid=da650a26-2139-427f-a4ee-24e0e99a6675

This is likely not a regression but hard to test given the app in prod currently doesn't work for me. Can put in a follow in PR.

**Comment by pernielsentikaer** [comment]
@enesozturk could you have a look here?

**Review by enesozturk — APPROVED** [review]
Looks great! Thank you @artivilla! I'll just test locally and I think we'll be good to go 🚀

**Comment by enesozturk** [comment]
@artivilla seems like we have some issues in the following commands and API endpoints:

- `Search` - Searching any query failing, we might need to update the API endpoint or debug the response.
- `Asset Details` - Asset details doesn't render image. We might need to check if we are fetching image as expected.

**Comment by artivilla** [comment]
Oh interesting. Does the current published version work for you? The current version doesn't work for me. Will drop a loom video tomorrow.

**Comment by artivilla** [comment]
@enesozturk I recorded myself. let me know if this still does not work: https://www.loom.com/share/117790ff6ebb469296963ff7e8638d6c?sid=eed575c9-f7e1-4a2f-a8da-8a12d7c13a2b
note there is a bug but its not related to hitting the API.

**Comment by enesozturk** [comment]
@artivilla thanks for video record. 🙏 Took a glance and its helpful. I'll go another round here I think we could handle those issues shortly. I'll share my results later tomorrow. Lets goo

**Comment by pernielsentikaer** [comment]
Thanks for looking into this @enesozturk 🔥

**Comment by pernielsentikaer** [comment]
So what should we do with this PR, are you going to update this or make a new one first?

**Comment by artivilla** [comment]
Waiting on @enesozturk . If needs me to, I can update my changes accordingly.

**Comment by artivilla** [comment]
any updates?

**Comment by pernielsentikaer** [comment]
@enesozturk are you still around 🙂

**Comment by enesozturk** [comment]
Hey all, sorry wasn't able to handle this last week. I cannot promise but let me handle it through this week. 🤞 @pernielsentikaer @artivilla

**Comment by pernielsentikaer** [comment]
Are you still interested in fixing this @enesozturk

**Pull request closed without merging**
