### PR TITLE
New extension: Gather

### PR DESCRIPTION
**Pull request by yannglt**
## Description

Create a new extension for [Gather](https://www.gather.town).

This extension has one command (for the moment):
`Toggle Availability Status` > Toggle your availability status in Gather
`Toggle Camera` > Toggle your camera in Gather
`Toggle Microphone` > Toggle your microphone in Gather
`Toggle Away From Keyboard` > Toggle your camera, microphone and availability status in Gather

## Screencast
gather-raycast-01

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by yannglt** [comment]
Here's a screencast of the extension running (hi Specify team 👋):

https://user-images.githubusercontent.com/16894359/178008487-b74afa4f-657f-4e02-9a75-4f6530fbff75.mp4

**Comment by pernielsentikaer** [comment]
Hi @yannglt  👋 

Thanks for your contribution!

It works as expected for me; I added an installation check - could you please check it before merging?

**Comment by yannglt** [comment]
Works perfectly, thank you so much for your help Per  🙏
cleanshot-20220709-snzxBSHA@2x

**Comment by yannglt** [comment]
I added dedicated commands for camera, microphone and availability status to handle all use cases, based on your update on `utils.ts` (thank you again for this!)

**Review by pernielsentikaer — APPROVED** [review]
Let's get it in the store 🔥

**Pull request merged**
