### PR TITLE
Add git-co-authors extension

### PR DESCRIPTION
**Pull request by nickradford**
## Description

Simplify adding co-author attributions to git commits. Add your frequent collaborators, and copy the correct syntax to paste into your commit.

### Add a co-author
Screenshot 2023-05-10 at 4 25 49 PM

### Select a co-author
Screenshot 2023-05-10 at 4 26 03 PM

### Paste into your commits
Screenshot 2023-05-10 at 4 26 40 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* I would use a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert) before deleting

* `Add Author` missing validation, it's possible to submit without writing anything, you can use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) for that 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by nickradford** [comment]
Thanks for the review @pernielsentikaer, I'll try to make some time to make the changes requested this week!

**Comment by pernielsentikaer** [comment]
Hi @nickradford 👋 

I hope you don't mind I pushed some improvements, do you mind checking that I didn't break anything 🙂

**Comment by nickradford** [comment]
@pernielsentikaer Looks good to me! Just pushed up the lint fix. Thanks for improving the UX :D

**Pull request merged**
