### PR TITLE
Ext/rusbase

### PR DESCRIPTION
**Pull request by khlebobul**
## Description

Remove donation links in README.md

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @khlebobul

It looks like you're pushing the complete extension again, could you please only push changed files 🙂

**Comment by khlebobul** [comment]
HI @pernielsentikaer 

Honestly, I did the usual. I only see the changes in README.md

**Comment by pernielsentikaer** [comment]
If you check [here](https://github.com/raycast/extensions/pull/11231/files) you can see all files, how did you push them?

**Comment by khlebobul** [comment]
Yes, but the commits only include a change in a single file

**Comment by pernielsentikaer** [comment]
Delete your local branch in your repo and try again, otherwise DM me the file on Slack or twitter 🙂

**Pull request closed without merging**
