### PR TITLE
add: bootstrap-icons

### PR DESCRIPTION
**Pull request by chyroc**
## Description

search bootstrap icons

## Screencast
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by fe9lix — CHANGES_REQUESTED** [review]
Hey @chyroc – thanks for the contribution! Some comments:

- Could you remove the 1.6k icons from the assets? Everything is the assets folder gets bundled into extension and it looks like you anyway load the icons from the svg descriptions in the JSON file?
- With the dark theme active (Raycast Preferences > Appearance), the icons are hardly visible. Maybe dynamically color them based on the active `environment.theme` value?

**Comment by fe9lix** [comment]
Hey @chyroc – something seems off with the commit history and the added assets. To move forward with the PR, could you please: 

- Remove the 1.6k asset files
- Squash the commits

**Comment by chyroc** [comment]
ok

**Comment by pernielsentikaer** [comment]
I'm closing this due to inactivity; feel free to open it again or comment in the thread when you're ready to continue working on it 🙂

You can also catch me in [Slack](https://www.raycast.com/community) if you want to discuss 😄

**Pull request closed without merging**
