### PR TITLE
Add „Keyboard Layout Switcher“ extension

### PR DESCRIPTION
**Pull request by lucaschultz**
## Description

The extension allows **switching the keyboard layout**. It uses [keyboardSwitcher](https://github.com/Lutzifer/keyboardSwitcher) by [Wolfgang Lutz](https://github.com/Lutzifer) to *list* and *switch* available layouts and depends on the binary. 

The binary is build with Xcode using the the available source code in the [keyboardSwitcher repository](https://github.com/Lutzifer/keyboardSwitcher) and placed in the `src/assets` folder. That should be compliant with [the rules for binary dependencies](https://developers.raycast.com/basics/prepare-an-extension-for-store#binary-dependencies-and-additional-configuration) which I have read and (hopefully) understood. You can (of course) build the binary yourself and replace the one in this repository with the one you build.

Also – if possible – someone should probably go over the help text in `src/Help.tsx` to check wether the labels of buttons and sections are correct. I translated them from German and never checked on a Mac set to Englisch. That'd be super nice!

## Screencast

https://user-images.githubusercontent.com/45899273/155764947-b4d723b0-3800-4175-a675-455fee0036ab.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by fe9lix** [comment]
Hey @lucaschultz – could you run prettier on the code? (`npm run fix-lint`). The CI is currently failing...

**Review by fe9lix — CHANGES_REQUESTED** [review]
Hey @lucaschultz, thanks for the contribution! This looks useful and I'm gonna use it myself (currently using the menu item in MacOS to switch input sources to U.S. With Umlauts ;)). I'm going to replace the binary once we've done the review (simply because it's our current store policy). 

Could you please the sketch file in the assets folder? The assets folder gets bundled into the extension and should just contain runtime resource files.

Once this and the prettier errors are fixed, we can merge it!

**Comment by lucaschultz** [comment]
@fe9lix Done and done. Glad you like extension. There should be an extension for most menubar items. They're just so much more accessible in Raycast!

Ahhh yes the _U.S. With Umlauts_ layout, I know that one as well. But I gave up on ANSI Layouts a while ago, messes up my typing skills on ISO Layouts which are an (unfortunate) necessity in my day job 🥲

**Comment by fe9lix** [comment]
Thanks for the updates. I was just about to replace the binary with the one from homebrew, which is a universal binary, but it seems that getting the current keyboard layout and highlighting it in the list doesn't work then (activating seems to work, though). Haven't digged deeper...could you take a look? Ideally, we'd ship the universal binary...

**Comment by lucaschultz** [comment]
@fe9lix Sorry for taking some time. So I did some digging: I build the binary using Homebrew and manually. Here are the results (and the reason it doesn't work):

https://user-images.githubusercontent.com/45899273/157754253-d148f648-3ca5-4c78-9ea5-23f1de575637.mp4

The Home-brew version appears to have a bug returning an `Optional` string. I guess for some reason, it builds a different version than manually triggering the build from the repo. I see two possible solutions:

1. You build the universal binary manually like I did in the screencast. I you've got Xcode installed that's just: 
  ```
  git clone https://github.com/Lutzifer/keyboardSwitcher.git
  cd keyboardSwitcher
  xcodebuild -project keyboardSwitcher.xcodeproj ONLY_ACTIVE_ARCH=NO ARCHS='arm64 x86_64' build
  ```
2. I account for the bug in my code

I'd prefer the first option of course. But let me know what you decide.

**Comment by fe9lix** [comment]
Thanks for digging! Let's go with option 2 – I've built and replaced the binary.

**Review by fe9lix — APPROVED** [review]

**Pull request merged**
