### PR TITLE
Add nhl-schedule extension

### PR DESCRIPTION
**Pull request by rreichel3**
## Description

This is a new extension that adds the ability to view the current NHL schedule at a glance. 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by kciarnie** [comment]
Haha! Good work on your I actually wrote something like that for own personal extensions and was about to publish one. Nice work

**Comment by rreichel3** [comment]
> Haha! Good work on your I actually wrote something like that for own personal extensions and was about to publish one. Nice work
Thats awesome @kciarnie! If you have any UX suggestions from how you've built it, I'd be keen to see it

**Comment by kevin-c-meister** [comment]
Screenshot 2024-01-08 at 16 51 09
Screenshot 2024-01-08 at 16 50 51
Screenshot 2024-01-08 at 16 50 14

Just to give you an idea. If you want, I can contribute my changes to this extension. I would probably put a dropdown menu for the weekly schedule for the different teams and cache the user's choice. What'd you think?

**Comment by kciarnie** [comment]
Screenshot 2024-01-08 at 16 51 09
Screenshot 2024-01-08 at 16 50 51
Screenshot 2024-01-08 at 16 50 14


Just to give you an idea. If you want, I can contribute my changes to this extension. I would probably put a dropdown menu for the weekly schedule for the different teams and cache the user's choice. 

Another thing to is that I really liked the detail view with metadata to display the information. I was actually going to post this extension next and then literally checked to see in the repo if someone had already done it and bam, came across yours.

What'd you think?

**Comment by pernielsentikaer** [comment]
When I open `NHL Schedule` I get this error, could you look into this?

nhl-schedule 2024-01-10 at 12 23 05

**Comment by rreichel3** [comment]
@pernielsentikaer I've pushed a change that should fix that issue! 

@kciarnie I love how you used the metadata and other fields on the list views!  If its not too much work feel free to PR it here and we can get it all merged in! https://github.com/rreichel3/raycast-extensions/tree/ext/nhl-schedule

**Comment by kciarnie** [comment]
Yeah, I can definitely add to this extension later on tonight!

**Comment by pernielsentikaer** [comment]
If I'm clearing everything and open this command for the first time, then I get the same result now

nhl-schedule 2024-01-12 at 09 29 46

**Pull request closed without merging**
