### PR TITLE
Update klack extension

### PR DESCRIPTION
**Pull request by henrikruscon**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by henrikruscon** [comment]
Waiting for an Apple approval again for this one, should be approved later today.

**Comment by pernielsentikaer** [comment]
Just update the thread and I'll have a look 🙂

**Comment by henrikruscon** [comment]
Klack v1.6 has been approved, and I scheduled the release in 30 min from now. Thanks for holding it.

**Comment by henrikruscon** [comment]
Just to clarify, no need to hold the release anymore. Just in case this got lost in translation somehow. Not trying to rush you, sorry if it comes of that way!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
