### PR TITLE
Update send-to-flomo extension

### PR DESCRIPTION
**Pull request by asheryew**
## Description

Add newline character between content and tags.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaslombart** [comment]
Hey @thishym, could you include a description for your update? Also it looks like you haven't included your Raycast username in the contributors. Could you do it as well?

**Comment by thishym** [comment]
@thomaslombart Thank you for replying, this is my first PR so I apologize for any low-level mistake at first. 
I added the description, just add a newline character to make the result looks prettier.
My Raycast username was "joeyming" while pushing and changed it to "thishym" later. 
I wrote "thishym" in the contributors, which didn't pass the reviewer check. 
Is it ok to change Raycast username? Anything else should I do?
Thanks again.

**Comment by thishym** [comment]
Sorry, I find there was a typo in my Raycast username and corrected it just now.

**Comment by thomaslombart** [comment]
Could you add a screenshot and a recording as well? I can't really see what was wrong before, and what is your PR fixing?

**Comment by thishym** [comment]
OK, this photo shows the changes I made:
image

I think the error happens due to my raycast username changes. Right now, my raycast username is "thishym".
At first the username was "joeyiming". Even now I fork a raycast extension, the package.json will add this username to contributors. This is weird.
And then I changed it to "thiyhym"(with a typo), and this one didn't pass the reviewer check and bothered us.
Yesterday, I changed it to "thishym".

Sorry, I am not sure what I should make a recording of. The progress after running the extension publish command?

**Comment by thomaslombart** [comment]
I meant screenshots and recordings of the actual extension you're fixing. What was the bug and what is your PR fixing? 😊

**Comment by thishym** [comment]
ok, I made a recording, hope this is helpful. ❤️
code

**Review by thomaslombart — APPROVED** [review]

**Pull request merged**
