### PR TITLE
Update trello extension

### PR DESCRIPTION
**Pull request by Jimmy-b36**
## Description

Added ability to add a member when creating a Trello task. This means that when fetching a list of assigned items you will fetch ones you have assigned to yourself through Raycast instead of having to manually assign on Trello 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Could you add a changelog entry?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
@ChrisChinchilla do you mind checking this 🙂

**Comment by Jimmy-b36** [comment]
@pernielsentikaer does this look right to you?

**Comment by ChrisChinchilla** [comment]
The reordering of certain things outside of the feature addition was a bit confusing, but the functionality is great! Thanks :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
