### PR TITLE
Migrate extensions to 1.28.0

### PR DESCRIPTION
**Pull request by Destiner**
## Description

Migrating my extensions to 1.28.0 using migration tool. Also, unifying Prettier config. No functionality is changed.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by mathieudutour** [comment]
Hey! I'm curious what you thought of the migration tool? Anything we could improve?

**Comment by Destiner** [comment]
Hey! Thanks for the tool, it helped a lot. Overall it migrated most of the code flawlessly. I had a few incidents where it changed the opening tag of `ListItem` (`<ListItem>` -> `<List.Item>`) but not the closing one (`</ListItem>` didn't change).

**Comment by mathieudutour** [comment]
Oh right, I might have missed it. Thanks for the feedback!

**Comment by mathieudutour** [comment]
Thanks, I fixed the issue :)

**Pull request merged**
