### PR TITLE
Update xcode extension

### PR DESCRIPTION
**Pull request by qeude**
## Description

Changed the data source for the feature in this [PR](https://github.com/raycast/extensions/pull/7613) from a txt gist to a proper API.
Addition of macs as well.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the correction @qeude 🚀 

Do you mind checking @SvenTiigi 🔥

**Comment by SvenTiigi** [comment]
LGTM 👍
One little suggestion @qeude: 
Would it be possible to add a fallback in case of an error or unavailability of the `https://api.ipsw.me/v4/devices` HTTP endpoint to use the contents of the gist from the previous PR https://github.com/raycast/extensions/pull/7613

**Comment by qeude** [comment]
It would be possible, but I'm not sure we want to do so. 
Let's say that for some reason someone is using the extension with low connectivity. They could launch the command two times in a row, but have two different results which looks confusing to me. I think this is better for the UX to have a consistent and predictable result, even though it means that HTTP errors could happen at some point.
Adding to that, let's say that `https://api.ipsw.me/v4/devices` just shutdown and is not available anymore, the architecture of the extension with the service allows us to easily change the data source for this list so not a big deal to fix this.
WDYT @SvenTiigi?

**Comment by SvenTiigi** [comment]
Alright, sounds good 👍

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
