### PR TITLE
Improve Safari Extension

### PR DESCRIPTION
**Pull request by loris**
## Description

- [x] Reading List and Cloud Tabs: Add CopyToClipboardAction action
- [x] Reading List and Cloud Tabs: Open URLs in default browser
- [x] Reading List: Group items by unread/read sections
- [x] Cloud Tabs: Add "Close Tab" action for local device (using Apple Script)
- [ ] ~~Reading List: Add "Remove" action~~
- [x] Reading List: Add "Add to Reading List" command
- [x] Cloud Tabs: add fallback search action

## Type of change

- Bug fix / improvement for my extension

## Screenshots

image

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by loris** [comment]
Hi @pernielsentikaer, sorry took a bit longer to include everything I planned on this update.
Let me know if you have any feedbacks or things you want me to fix

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @loris 👋 

What an awesome extension update, much appreciated! 💪 

Only thing I spotted it that when opening an item from reading list, it opens in the default browser and not specific in Safari — can you look into this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Review by pernielsentikaer — APPROVED** [review]
Hi @loris 👋 

Thanks for the Slack conversation, I'm going to accept it as it is 😄 

Thanks for making the extension even better 💯

**Comment by itssimba** [comment]
Show tab crashes for me. It seems like its caused by the fact that it tries to find cloud tabs although I am not logged into iCloud.
```
Error: no such table: cloud_tabs

s.handleError:cloud-tabs.js:20:19921
---
[...]
---
s.prepare:cloud-tabs.js:20:19179
I1:cloud-tabs.js:35:530
L1:cloud-tabs.js:52:47
    at async Promise.all (index 1)
cloud-tabs.js:71:712
```

**Pull request merged**
