### PR TITLE
[1Password] Updates

### PR DESCRIPTION
**Pull request by pernielsentikaer**
## Description

- Increased maxBuffer since it caused problems
- Moved Reset Cache to commands instead, so regular users is not confused
- Updated Empty views

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Seems like if you have more than 2000 items in the vault you'll face this issue:
```
  itemsError: <ref *1> Error: spawnSync /usr/local/bin/op ENOBUFS
      at Object.spawnSync (node:internal/child_process:1110:20)
      at spawnSync (node:child_process:857:24)
      at execFileSync (node:child_process:900:15)
      at op (/Users/tmchow/.config/raycast/extensions/1password/item-list.js:10442:58)
      at /Users/tmchow/.config/raycast/extensions/1password/item-list.js:10457:21
      at commitHookEffectListMount (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:10831:30)
      at commitPassiveMountOnFiber (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react-reconciler.development.js:12115:13)
      at commitPassiveMountEffects_complete (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/react-reconciler/react<…>
```

Increasing the `maxBuffer` seems to fix this, but I'm unsure if we can somehow stream it instead.

**Comment by thomaspaulmann** [comment]
Great additions. As for the buffer, John found a way to stream the JSON but not sure if that would work here. I'm surprised that 2000 items break our limit but maybe it's ok for now?

**Comment by thomaspaulmann** [comment]
@mathieudutour thoughts on increasing the buffer when using `execFileSync`?

**Comment by mathieudutour** [comment]
we can increase the buffer yeah but it's not going to solve the scaling issue, just postpone it.

Streaming the response would be the right solution indeed

**Comment by pernielsentikaer** [comment]
Maybe you could also check this one @khasbilegt

**Review by khasbilegt — APPROVED** [review]

**Pull request merged**
