### PR TITLE
[Raindrop.io] Display additional item as subtitle on list

### PR DESCRIPTION
**Pull request by sh-cho**
## Description

I thought It'd be useful if I can check link(ex. `https://google.com/foo?bar=...`) or domain(ex. `google.com`) of bookmark in search list. Currently only title and tags are displayed.

So I added dropdown preference for additional item to show - [link, domain, none]

Additional item is displayed as subtitle.

Here are examples;

Screenshot 2024-01-25 at 12 07 03 AM

(additional 'link' as subtitle)

image

(preference)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by lardissone** [comment]
@sh-cho hey, thanks for your contribution! This is a great idea.

I would also include other options like: 

- `bookmark.type`: `link`, `article`, `image`, `video`, `document` or `audio`
- `bookmark.lastUpdate` or `bookmark.created`
- `bookmark.excerpt` or `bookmark.note` (or both)

**Comment by sh-cho** [comment]
@lardissone good idea 👍
I'll update on my free time.

**Comment by sh-cho** [comment]
image

@lardissone 
I updated a little bit :)
- Add more options for subtitle (excerpt / note)
- Add option for display date (last updated / created / none)
- Add Icon by bookmark type (link / article / image / video / document / audio)
- Add tooltip with link for title

**Comment by lardissone** [comment]
@sh-cho awesome! great work!

**Comment by sh-cho** [comment]
@pernielsentikaer gentle ping :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
