### PR TITLE
feat: add support for config sesh source

### PR DESCRIPTION
**Pull request by joshmedeski**
## Description

- Combine to one sessions state object
- Switch icon getter logic to switch case
- Add config section between tmux and zoxide in list items

## Screencast

sesh-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by joshmedeski** [comment]
@pernielsentikaer any chance this can get merged soon?

**Review by pernielsentikaer — APPROVED** [review]
Yes! I just returned back from vacation today 🙂

**Comment by joshmedeski** [comment]
@pernielsentikaer awesome, hope you had a good vacation! 🍹

**Comment by pernielsentikaer** [comment]
I had a nice easter vacation 🐰

**Pull request merged**
