### PR TITLE
Adding new extension - Twitter Video Downloader

### PR DESCRIPTION
**Pull request by kaanrkaraman**
## Description

Adding Twitter Video Downloader to the store. I'm going to include screenshots right after extension is released in the store, to avoid having the development sign on the bottom (the disk icon).

## Screencast

[Simple screen recording showing the extension while downloading a video](https://streamable.com/ckd2gr)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by kaanrkaraman** [comment]
Cannot reproduce the error causing lint checks to fail. Prettier cannot find any linting issues on my workspace. I'm not sure why it fails so I'm waiting for further reviews.

**Comment by kaanrkaraman** [comment]
No errors on my end, both ESLint and Prettier checks are passing on my computer. I don't know what is wrong with the failing action. I'm leaving my main branch open for edits, but I won't try to fix this anymore.

Code is stable and lint checks are passing on local.

**Comment by kaanrkaraman** [comment]
Stupid me! All previous checks failde because of a missing "r" in the Prettier config file. Worked three hours just to figure out this.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Shouldn't we use the new name (and logo) for X instead?
- Adding a .gitignore file with

```
# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules

# misc
.DS_Store
raycast-env.d.ts
```

- Add a [metadata image](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
