### PR TITLE
[Perplexity-API] Added new MoE models

### PR DESCRIPTION
**Pull request by maximilianzuern**
## Description
- Added Perplexity's new Sonar models `sonar-small-chat`, `sonar-medium-chat` and `sonar-small-online`, `sonar-medium-online`.
- Updated pricing for MoE (8x7B) models.

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by rochakagrawal** [comment]
Thanks - the extension works very well with the new model 

Feedback - Can you please give us a chat option so we can continue chatting after receiving a response? Similar to the way the Gemini and ChatGPT extensions work in Raycast.

Many thanks.

**Comment by maximilianzuern** [comment]
@rochakagrawal 
This is definitely on my list, but implementing this properly will take some time, as I have many other projects ongoing. Please feel free to open a PR if you have some spare time to implement this. 
I will turn your suggestion into an issue to track your suggestion and gather additional ideas.

**Comment by maximilianzuern** [comment]
Closed my issue because I noticed that you had already opened another issue on this topic.
#10759

**Pull request merged**
