### PR TITLE
Add color-studio-picker extension

### PR DESCRIPTION
**Pull request by javierarce**
## Description

This extension let users pick colors from the color palettes defined in https://color-studio.blog.

## Screencast

https://github.com/raycast/extensions/assets/4933/7d3cdfb7-ac8b-4f9b-80eb-0069c20f1bc5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
- The extension suffers from [Empty State Flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)
Could you look into first returning data when the view is loaded, also if you set an argument its doing some weird flicker, useMemo could maybe help with that

Let me know if you need any help

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by javierarce** [comment]
Thanks a lot, @pernielsentikaer! I've addressed your comments and the extension behaves much better now, so I think it's ready for a new review.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by javierarce** [comment]
Thanks, @pernielsentikaer! ✨

**Pull request merged**
