### PR TITLE
Add Sketch Extension

### PR DESCRIPTION
**Pull request by aesign**
## Description

View and open [Sketch](https://sketch.com) Workspace documents directly in Raycast.

## Type of change

- New extension

## Screenshot

CleanShot 2021-10-14 at 18 04 16@2x

## Checklist

- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Comment by aesign** [comment]
And, what kind of workspace did you have selected? The personal or shared one? If the latter, has it got an icon?

**Comment by PitNikola** [comment]
```
2021-10-15 21:30:45.633 F  Raycast[31003:efab8a] [com.raycast.extensions.sketch:searchDocuments] (node:75826) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
2021-10-15 21:30:45.928 Db Raycast[31003:efa880] [com.raycast.extensions.sketch:searchDocuments] ✓ logged in
2021-10-15 21:30:46.789 Db Raycast[31003:efa880] [com.raycast.extensions.sketch:searchDocuments] ✓ storing all workspace names and identifiers
2021-10-15 21:30:46.789 Db Raycast[31003:efa880] [com.raycast.extensions.sketch:searchDocuments] ✓ storing first workspace avaiable
2021-10-15 21:30:47.281 F  Raycast[31003:efa29d] [com.raycast.extensions.sketch:searchDocuments] The above error occurred in the <ShareListItem> component:

    at null.ShareListItem (/Users/pitnikola/dev/raycast/extensions/extensions/sketch/src/searchDocuments.tsx:191:23)
    at ray-list-section
    at da (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:46:31654)
    at ray-list
    at Zo (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:46:30982)
    at null.DocumentsList (/Users/pitnikola/dev/raycast/extensions/extensions/sketch/src/searchDocuments.tsx:33:29)
    at ray-navigation-stack
    at jc (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:6684)
    at aa (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:6789)
    at yp (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:5559)
    at ray-root
    at Go (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:5905)
    at Ds (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:6209)

React will try to recreate this component tree from scratch using the error boundary you provided, InternalErrorBoundary.
2021-10-15 21:30:47.281 F  Raycast[31003:efa29d] [com.raycast.extensions.sketch:searchDocuments] The above error occurred in the <ShareListItem> component:

    at null.ShareListItem (/Users/pitnikola/dev/raycast/extensions/extensions/sketch/src/searchDocuments.tsx:191:23)
    at ray-list-section
    at da (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:46:31654)
    at ray-list
    at Zo (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:46:30982)
    at null.DocumentsList (/Users/pitnikola/dev/raycast/extensions/extensions/sketch/src/searchDocuments.tsx:33:29)
    at ray-navigation-stack
    at jc (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:6684)
    at aa (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:6789)
    at yp (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:5559)
    at ray-root
    at Go (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:5905)
    at Ds (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:5:6209)

React will try to recreate this component tree from scratch using the error boundary you provided, InternalErrorBoundary.
2021-10-15 21:30:47.305 F  Raycast[31003:efa29d] [com.raycast.extensions.sketch:searchDocuments]
TypeError: Cannot read properties of null (reading 'small')

ShareListItem:searchDocuments.tsx:191:23

---
188:     }
189:   };
190:
191:   const share = props.share;
192:   const wp = props.workspaces;
193:
194:   return (
---

    at ray-list-section
da:index.js:46:31654
    at ray-list
Zo:index.js:46:30982
DocumentsList:searchDocuments.tsx:33:29
    at ray-navigation-stack
jc:index.js:5:6684
aa:index.js:5:6789
yp:index.js:5:5559
    at ray-root
Go:index.js:5:5905
Ds:index.js:5:6209
```

**Comment by PitNikola** [comment]
> And, what kind of workspace did you have selected? The personal or shared one? If the latter, has it got an icon?

I created few documents in "All Documents" and yes, they don't have icons:

CleanShot 2021-10-15 at 21 33 03@2x

**Comment by aesign** [comment]
Should be good to go now, thanks for helping!

**Comment by PitNikola** [comment]
Great, works now, thanks! Now one last small thing – considering that there is only one command in this extension, we recommend using more specific name for an extension to avoid generic names like "Sketch". How about "Sketch Documents"? See how other extensions in the store not just "VSCode" or "Vercel".

Once you add more commands that interact with Sketch, you can easily rename it.

**Comment by aesign** [comment]
Yep I sticked with Sketch because I’ve got an update ready (https://github.com/aesign/extensions/tree/feature/projects/extensions/sketch) that adds a “Projects” command as well. Do I still need to change the name?

**Pull request merged**
