### PR TITLE
feat: add ot extension

### PR DESCRIPTION
**Pull request by ireneisdoomed**
## Description

Adds a new extension to offer a quick entry point to the Open Targets ecosystem.

## Screencast
A screencast in gif format is available in the README.
There are also 3 pictures inside `metadata` to give an idea of the features.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* In the command `Browser Datasets` is it then possible to add a OpenInBrowser action to open the location?

* In the command `Browse Datasets` gives me this error in the console; could you have a look?

```
06:16:51.550 Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

- `Open...` commands should be a no-view command instead


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by ireneisdoomed** [comment]
Hi @pernielsentikaer!

Thank you so much for your comments. I've added an (optional) open-in browser button, which will be actionable for all our datasets except for the ones that are experimental.

The error that was being printed to the console is also fixed. Let me know if you have more comments!

Thanks again and congrats on the Wire article! It's great to see Raycast is getting a lot of buzz lately 🔥

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Can you host the demo.gif (and update reference in README) on your ownrepo, so we don't need to add 5MB with that too?

**Comment by ireneisdoomed** [comment]
@pernielsentikaer No problem, done!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Comment by ireneisdoomed** [comment]
Thank you so much for the review and your suggestions @pernielsentikaer!

**Pull request merged**
