### PR TITLE
Create `Single Focus` extension

### PR DESCRIPTION
**Pull request by vimtor**
## Description

https://user-images.githubusercontent.com/36263538/205444605-45600af1-75b3-41da-b519-ddda675f41dd.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by vimtor** [comment]
@pernielsentikaer fixed!

**Comment by pernielsentikaer** [comment]
One thing I still haven't figured it that might be annoying (since I don't have a solution right now) is how you'll be able to keep Raycast open when a HUD is spawned. 

Right now, it closes Raycast every time a HUD is shown 😞

**Comment by pernielsentikaer** [comment]
Sub issue which we also have to fix when we figure out what to do with the HUD is the empty row in the menubar

Raycast-8xoz2H0U@2x

**Comment by vimtor** [comment]
I'm okay with waiting until we can solve the HUD thing 😄

**Pull request closed without merging**
