### PR TITLE
[Gmail] Add label filter actions and dropdown

### PR DESCRIPTION
**Pull request by tonka3000**
## Description

- Add Labels support via actions

  CleanShot 2023-08-11 at 16 10 38@2x

- Add dropdown to `List Mails` command to allow filtering like on gmail.com

  CleanShot 2023-08-11 at 16 07 18@2x

  Sublabels are supported as well

  CleanShot 2023-08-11 at 16 11 17@2x

- `List Mails` have now an optional `Query` argument
- `List Mails` can store the current query as an quicklink for fast access

  CleanShot 2023-08-11 at 16 09 19@2x

- Add `List Archive` command
- Add `List Trash` command
- Add actions to select multiple mails (read, unread, delete)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by chambliss** [comment]
Wow thanks for adding this so quickly! 😄 

OK, so I checked these changes out to test them locally - looks great so far, although I did catch some buggy behavior with by-label filtering. I made a video for clarity, but essentially what's happening is first I open "List Archive," I scroll around to find some emails that also have one of the Newsletter sub-labels, then I filter by the DS/ML sublabel specifically, and there are no results returned, even though I was able to see it there in the base List Archive command.

https://github.com/raycast/extensions/assets/43484165/335ca71c-17fa-4297-a6e7-5d788101b0f7

**Comment by tonka3000** [comment]
Hey @chambliss ,

thanks for given the PR a try. That is strange, I can not really reproduce that on my side 🤔. The query itself is done via the Gmail API, so it seems to give no response for whatever reason.
I've added a Action `Copy Query to Clipboard`, with that you can get the full query. Copy the query and paste the content directly on gmail.com. Please let me know if you see the right data there.

btw: The searchbar text is now updated with the latest commit.

**Comment by pernielsentikaer** [comment]
@chambliss do you mind giving it another run?

We also applied for an official Raycast oAuth integration for the extension so that we can get rid of that step 🙂

**Comment by chambliss** [comment]
Oh, I figured it out 😄 The problem is with only some of my labels. Here are the labels that work as expected:
- Newsletters
- Newsletters/CA/Local
- Newsletters/People I Like
- etc,

The ones that don't work as expected:
- Newsletters/Tech - SWE
- Newsletters/Tech - DS/ML
- Newsletters/Tech - General

It's because gmail actually expects these to be passed with hyphens filled in for the spaces, e.g. "Newsletters/Tech---SWE". Even though spaces don't cause an issue with the "People I Like" label. 🤔 Maybe it's something to do with how they process spaces and special characters like "-" together.

"People I Like" - works fine:
image

"Tech - SWE" - doesn't work initially:
image

"Tech---SWE" working in gmail search bar:
image

"Tech---SWE" working in the extension:
image

**Comment by tonka3000** [comment]
@chambliss The `-` is used for the "not" operation, so it seems that there is a requirement to convert the input in the case.

**Comment by tonka3000** [comment]
@chambliss I pushed now a fix for dashed labels. Please try again.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
