### PR TITLE
Update library-genesis extension

### PR DESCRIPTION
**Pull request by j3lte**
## Description

- Removed [libgen](https://www.npmjs.com/package/libgen) dependency
  - The library is not maintained and had issues with old mirrors
- Removed `axios` because we can use `node-fetch` instead
- Updated all (dev) dependencies to latest version
- Added better code formatting and linting, cleaned up code
- Updated download controller, this is now cancellable
- Add Mirror List to the extension
  - This is a list of all mirrors that are currently available in the extension

This fixes the following issues:
- #9546  no results due to `libgen` dependency failing
- #8778 duplicate
- #8355 duplicate
- #8333 duplicate
- #8803 duplicate

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by yz3440** [comment]
First off, @j3lte thank you so much for taking care of the extension! I really appreciate it! 

I was thinking about fixing the mirror issue but I found that some mirrors have the "Library Genesis +" (eg. [this](https://libgen.gs/), as compared to [this](https://libgen.is/)) UI so the scraper I wrote would stop working. 

You seem like a much experienced TS developer than I was, so I'm curious to hear your thoughts.

**Comment by j3lte** [comment]
@yz3440 thanks!

Yes, there is a list of mirrors that is using a different UI. I'm planning on implementing that one tomorrow, I already moved some of the code for parsing a page around.

The beauty of the other mirrors is that it also has a JSON Api, so I think we only have to parse the initial page in cheerio and take it from there.

I'll update the PR further tomorrow to see if we can include the 'new UI' mirrors. We could also publish this version of the extension (so we can fix the list with open issues) and make a new PR for the mirrors

**Comment by yz3440** [comment]
Sounds great! Wow didn't know the JSON api existed! Is it documented somewhere? 
If you ended up making an update tmr, just ping me and I'll make sure to review it!

**Comment by j3lte** [comment]
@yz3440 I checked the other API, but it seems it uses a bit of a different structure, as they are using with editions for example. The new UIs are not really compatible with the current extension. I would argue that we publish this update, as it fixes a list of issues right now, and see if we can add the new UI mirrors a later moment.
This update contains 3 mirrors that are all working fine

**Comment by pernielsentikaer** [comment]
Sounds good to me, what do you think @yz3440

**Comment by yz3440** [comment]
Yeah sounds good to me too. Thank you so much for all the work. Sorry for the late reply!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
