### PR TITLE
Add tidyread---streamline-your-daily-reading extension

### PR DESCRIPTION
**Pull request by DophinL**
## Description
You can schedule your daily reading, and through a digest powered by AI(Support Raycast AI), we provide you with an efficient and tidy news reading experience.

## Screencast
tidyread---streamline-your-daily-reading-1
tidyread---streamline-your-daily-reading-2
tidyread---streamline-your-daily-reading-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by DophinL** [comment]
@pernielsentikaer 
The second plugin has finally been released, looking forward to the REVIEW. I tried to support Raycast AI, but since i don't have a pro account, i'm not sure if it performs well. Give it a try if it's convenient :P

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:



- `Save Source` is missing an icon in in the ActionPanel in `Add Source`

- Add `try{}catch{} around `launchCommand` in `Add Source` since it can be disabled

- `Daily Read` and some of the other commands suffers from [Empty State Flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

- When using Raycast to summarize I get this error, maybe v1 could be without Raycast AI?:
```
14:17:45.479 Error summarizing content with Raycast AI: Error: The data couldn’t be read because it isn’t in the correct format.
    at Rr (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:25:230)
    at Ye (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6249)
    at ht (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6374)
    at Immediate.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/server/index.js:24:6139)
    at process.processImmediate (node:internal/timers:478:21)
14:17:45.479 Failed to summarize: The data couldn’t be read because it isn’t in the correct format.
```

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by DophinL** [comment]
@pernielsentikaer  Thanks for your patience review! I'll try to fix it them

And is there a test pro account which I can test for the Raycast AI issue?

**Comment by DophinL** [comment]
> * launchCommand

Several of the issues you mentioned have been resolved, and Raycast AI support has been temporarily dropped. Please REVIEW it again and look forward to the release! @pernielsentikaer

**Comment by DophinL** [comment]
@pernielsentikaer Hi, I have Raycast AI Pro turned on and tried it without encountering problems. May I ask which mod you are using?

**Comment by pernielsentikaer** [comment]
I tested with 
```
[
    {
        "timeSpan": "1",
        "tags": [],
        "schedule": "everyday",
        "url": "https://newz.dk",
        "title": "Newz – Nyheder for rigtige nørder",
        "rssLink": "https://newz.dk/rss",
        "favicon": "https://newz.dk/templates/themes/newz.dk/images/newz.dk/newz-dk.icon.png"
    }
]
```

**Comment by DophinL** [comment]
> I tested with
> 
> ```
> [
>     {
>         "timeSpan": "1",
>         "tags": [],
>         "schedule": "everyday",
>         "url": "https://newz.dk",
>         "title": "Newz – Nyheder for rigtige nørder",
>         "rssLink": "https://newz.dk/rss",
>         "favicon": "https://newz.dk/templates/themes/newz.dk/images/newz.dk/newz-dk.icon.png"
>     }
> ]
> ```

I tried it, but only encountered the 429 rate limit issue, which can be mitigated by adjusting the api concurrency inside the preferences, but it doesn't affect the use, and still generates the digest properly.
image

If there are no other issues with the code anymore, is it possible to release it first? :P @pernielsentikaer

**Comment by DophinL** [comment]
Just prepared the Get Started documentation, looking forward to ship haha! @pernielsentikaer

**Comment by DophinL** [comment]
To fulfill my needs, I added a new feature: support for translating digest titles. Just configure the preferred language.

I tested all 3 supported providers and have solved all problems.

If you can, please help ship it, thanks! @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by DophinL** [comment]
@pernielsentikaer thx buddy!

**Pull request merged**
