### PR TITLE
Add mullvad-connection-manager extension

### PR DESCRIPTION
**Pull request by SebKranz**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Thanks for your contribution 🔥 

Would it make sense to build some of this into this [extension](https://www.raycast.com/0x46616c6b/mullvad) by @0x46616c6b if it's not already doing what yours are?

**Comment by SebKranz** [comment]
> Would it make sense to build some of this into this [extension](https://www.raycast.com/0x46616c6b/mullvad) by @0x46616c6b if it's not already doing what yours are?

Yes, it would be possible to move the "Connect", "Disconnect" and "Select Location" commands.
The "Connection Status" command could be omitted, since the version by @0x46616c6b already does this better.

**Comment by pernielsentikaer** [comment]
Awesome, that would make sense

**Comment by SebKranz** [comment]
Closing this in favour of https://github.com/raycast/extensions/pull/10251

**Pull request closed without merging**
