### PR TITLE
[Arc] New Commands for creating new notes and new easel

### PR DESCRIPTION
**Pull request by tleo19**
## Description

- Added `Open New Note` command to open a new Note in Arc.
- Added `Open New Easel` command to open a new Easel in Arc.

## Screencast

https://github.com/raycast/extensions/assets/65966422/108a4ef7-0999-450a-96bf-44e8ba844dd1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @tleo19 👋 

Thanks for another great update 🔥 

Do you have any idea why my Raycast opens the cmd+k menu when I open the easel command, but it doesn't for the note command?

https://github.com/raycast/extensions/assets/38033107/9c7fc4da-a760-4aa7-9ce5-c7c6d8f23d32

**Comment by tleo19** [comment]
> Hi @tleo19 👋 
> 
> 
> 
> Thanks for another great update 🔥 
> 
> 
> 
> Do you have any idea why my Raycast opens the cmd+k menu when I open the easel command, but it doesn't for the note command?
> 
> 
> 
> https://github.com/raycast/extensions/assets/38033107/9c7fc4da-a760-4aa7-9ce5-c7c6d8f23d32
> 
> 
> 
> Could you also check the CI errors I caused, I can help you out if you struggle 🙂

Hey @pernielsentikaer, thanks for your feedback looks I forgot to push my last commit where I fixed that issue. 

Thanks for catching that. 

And I will look at the CI error also

**Comment by tleo19** [comment]
Hey @pernielsentikaer the ci error is related to some `any` used with typescript. Should I use `@typescript-eslint/no-explicit-any`?

**Comment by pernielsentikaer** [comment]
Hi @tleo19 👋

What about something like this? Could you test that I didn't break anything?

**Comment by tleo19** [comment]
> Hi @tleo19 👋
> 
> What about something like this? Could you test that I didn't break anything?

Looks all good, when I ran lint and build script. Thanks

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
