### PR TITLE
Add raycast-google-palm extension

### PR DESCRIPTION
**Pull request by EvanZhouDev**
## Description
A extension for using the Google PaLM v2 API in Raycast!

Your question to Ask AI can either be: From the Argument Box, from Selected Text, or from the Form that will appear if you do not provide either. If you do use the Query Box, you can also select text to give it context.

i.e. You select "good" and type "Give an antonym," for Ask AI.

For the rest of the commands, you select text or provide text to the Argument Box to run the command with. If you provide both, the stuff in the Argument Box will take priority.

This extension is not too dissimilar to the `raycast-bard-ai` extension.

There are a few differences though:
- You will need to get a API Key from Google Makersuite
- Improved all of the additional commands so that they accept inputs from arguments (or the selected text)
- No Chat functionality yet

## Screencast
(Sorry for the blurriness, GitHub doesn't like large video files)

https://github.com/raycast/extensions/assets/62189478/4ba3bfd1-7236-48ec-912e-7004ff2755bc

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by Ssiswent** [comment]
I got it.
But this tool can't get pictures?
image

**Comment by EvanZhouDev** [comment]
If I remember correctly, it doesn't have access to the internet, so it must be hallucinating these in the first place...

Access to internet, Google Lens, and all that jazz is dedicated Google Bard functionality... unfortunately, Google is clamping down on it, or has already done so 😅

Trust me, my team, others from different Bard APIs, and I have spent a good amount of time trying to find a workaround for Bard, but it's useless fighting a battle where we take hours to contemplate and execute a move, while Google can spend a few minutes invalidating our workaround.

Sorry... I wish I could continue using and maintaining Bard too. It only works for some people sometimes, and I really have no idea why.

**Comment by Ssiswent** [comment]
Thank you very much for the contributions you have made to the community! This is already very cool!

**Pull request merged**
