### PR TITLE
add preferences to change-case extension

### PR DESCRIPTION
**Pull request by es183923**
## Description

adds preferences to customize which case transformations to be shown.

## Type of change

- Bug fix / improvement for my extension

## Screencast

Screen Shot 2021-12-29 at 6 38 51 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @es183923 👋 

Awesome update! 💪 

Can you look into what the linter is complaining about? It seems like name in the preferences can't have a space, could you correct this and try again?

```
Error: jsonschema: '/preferences/0/name' does not validate with https://raycast.com/schemas/extension.json#/properties/preferences/$ref/items/properties/name/pattern: does not match pattern '^[a-zA-Z0-9-._~]*$'
``` 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by es183923** [comment]
Okay, @pernielsentikaer I do need some help 😄  I can't figure out why the typescript check is throwing an error.

error: 
```
✅ No linter errors
✅ Validation complete
🧬 Building entry points [src/change-case.tsx]
🔎 Checking TypeScript
src/change-case.tsx(76,15): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'PreferencesType'.
  No index signature with a parameter of type 'string' was found on type 'PreferencesType'.
💥 Error: TypeScript check failed (exit status 2)
Error: 💥 Error: TypeScript check failed (exit status 2)
Error: Process completed with exit code 1.
```

**Comment by pernielsentikaer** [comment]
Hi @es183923 👋 

I wrote you in Slack, check if when you have time 😄

**Comment by pernielsentikaer** [comment]
Hi @es183923 👋 

Could you run prettier so we can get the linting error removed? 😄

**Review by pernielsentikaer — APPROVED** [review]
Hi @es183923 👋 

Thanks for the update, I'm going to accept it and then will my colleague do a final review before it's finally merged 🚀

**Pull request merged**
