### PR TITLE
Add what-the-commit extension

### PR DESCRIPTION
**Pull request by pranshu314**
## Description

This is a basic extension that calls the https://whatthecommit.com/index.txt endpoint to fetch a absurd and comical commit message. Then it displays the commit message and gives the user to copy and paste the generated message.

## Screencast

what-the-commit-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

We have an extension on the store that does the exact same: https://www.raycast.com/rokartur/commit-message-generator
Or am I missing something from your extension?

**Comment by pranshu314** [comment]
Hi,
Thank you for looking into the extension.
I did not discover the extension you mentioned when searching for it. Hence the same contribution. I would be more careful next time.
Sorry for the inconveniences caused

**Comment by pranshu314** [comment]
Though the extensions do the same thing, there is a subtle difference in that, the one mentioned has an array of commits, from which it selects a random one, while mine actually queries the whatthecommit.com endpoint to get the message.
Though I am not sure if both have the same commits list.

**Comment by mil3na** [comment]
Well, I would encourage you to make that change to that extension instead of making a new one, if you believe querying the website is a better way to do it. 
Closing due to duplication.

**Pull request closed without merging**
