### PR TITLE
Update vim-bro extension

### PR DESCRIPTION
**Pull request by zayadur**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by zayadur** [comment]
This was more of a common-sense update that I should've included with the copy to clipboard feature listed in the changelog item: 11-11. Should I add another item for this update?

**Comment by pernielsentikaer** [comment]
Feel free to add more to this one

**Comment by pernielsentikaer** [comment]
Let me know when everything is updated so I can review again

**Comment by zayadur** [comment]
> Let me know when everything is updated so I can review again

CHANGELOG updated. Ready for review.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
