### PR TITLE
feat: add dropbox

### PR DESCRIPTION
**Pull request by chyroc**
## Screencast

image

image

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by chyroc** [comment]
thanks!

**Comment by chyroc** [comment]
@mattisssa can you review this, thanks very much.

**Comment by chyroc** [comment]
fix handle wrong Dropbox Access Token

**Comment by chyroc** [comment]
「It feels a bit heavy. It loads the list, but when searching, it looks like it's doing another search, is filtering the content not enough?」

by default, this extension list all files with token.
when you input something, this extension search input query.

should i change it to two command? one list, and one search?

**Comment by chyroc** [comment]
Empty state fixed.

**Comment by chyroc** [comment]
@pernielsentikaer hi, i fix wrong token and empty state. please review this pr again. thanks very much.

**Comment by pernielsentikaer** [comment]
Hi @chyroc 👋 

Thanks for taking your time to look into corrections 🔥 

I'm not sure that I can see the need to add another search command? If this command lists all files, it's already possible to filter it out of the box.

Do I misunderstand something?

**Comment by chyroc** [comment]
@pernielsentikaer I'm sorry, this doesn't work. There are two reasons. 1. List will not load all files at once and will scroll to load. 2. List can only list one level of files and will not list sub-files.

**Comment by pernielsentikaer** [comment]
Hi @chyroc 👋 

Then I think it's OK to have it in the same command. Thanks for the clarification 😄 

I just tested the latest version, and now I get this.

CleanShot 2022-04-21 at 14 45 33@2x

Did you change anything that can cause this behavior?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by chyroc** [comment]
@pernielsentikaer i fix it.

**Review by pernielsentikaer — APPROVED** [review]
Hi @chyroc 👋 

Thanks for the correction 🔥 

Let's get the first version live and then you can work on improvements 💪

**Comment by chyroc** [comment]
thanks.

**Pull request merged**
