### PR TITLE
[ADB] Add ability to get current activity #10997

### PR DESCRIPTION
**Pull request by lidary-byte**
## Description

Add ability to get current activity

### CODE REVIEW

**Comment by quentin23soleil** [comment]
Hey! Great addition!

Maybe we want this to not be enabled by default?

**Comment by lidary-byte** [comment]
> Hey! Great addition!
> 
> Maybe we want this to not be enabled by default?

I'm sorry, I just saw it. Is it set to ```disabledByDefault: true``` ?

**Comment by quentin23soleil** [comment]
>I'm sorry, I just saw it. Is it set to disabledByDefault: true ?

Exactly yes :)

**Review by quentin23soleil — APPROVED** [review]

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
