### PR TITLE
Add Paste without Formatting extension

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

Paste text from the clipboard without formatting.

## Screencast

https://user-images.githubusercontent.com/36128970/159659152-4b65cc74-cd62-4ed8-bbbe-1db74c2f3859.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by FezVrasta** [comment]
Wondering how is this different from the default <kbd>⌥</kbd> <kbd>⌘</kbd> <kbd>⇪</kbd> <kbd>V</kbd> default shortcut of macOS?

**Comment by koinzhang** [comment]
I didn't know before that I could use this ⌥ ⌘ ⇪ V to paste unformatted text quickly 😅, they don't make a difference

**Comment by koinzhang** [comment]
> Wondering how is this different from the default ⌥ ⌘ ⇪ V shortcut of macOS?

@FezVrasta hi, Thanks for asking the question!
Sorry I didn't just do an exhaustive test, I found that the ⌥ ⌘ ⇪ V shortcut doesn't clear formatting when pasting text in word. I still haven't figured out what the ⌥ ⌘ ⇪ V shortcut does, it sometimes helps me clear text formatting in some applications, sometimes not.
I made this extension to automatically clear formatting when pasting text, for example, if you copy a bolded text in Word, it automatically clears the bold when you paste it.

**Comment by koinzhang** [comment]
> Wondering how is this different from the default ⌥ ⌘ ⇪ V shortcut of macOS?

After testing, the default system shortcut only works in some applications, for example, in word it can only clear some formatting (you can clear strikethrough, but not underline, bold and italic). 
This extension is used to clear all formatting: background color, bold, strikethrough, font color, etc.

**Comment by luis-amendola** [comment]
Can confirm ⌥ ⌘ ⇪ V  does not work in Microsoft Word. 

Also it's hit or miss in some scenarios like:

Wordpress editors and themes(Elementor)

Joomla stock WYSIG editor. 

Wix text editor. 

Tested on multiple browsers on latest Mac OS.

**Review by pernielsentikaer — APPROVED** [review]
Hi @koinzhang 👋 

Thanks for your contribution, approved 🚀

**Pull request merged**
