### PR TITLE
New Extension: Numi

### PR DESCRIPTION
**Pull request by AndresMorelos**
## Description

I'm adding an extension to query  [Numi App](https://numi.app/) from Raycast 

## Screencast

screenshot-03
screenshot-01

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @AndresMorelos 👋 

Thanks for your contribution 💯 

I have some feedback for you to address 😄 

- It would be awesome if the logo was bigger like the original one

- I miss an early indication that Numi is not open or hasn't enabled remote connections. Maybe it's possible to query the port when opening the extension to check?

- I miss some more information in the README about how to enable remote?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Are you still working on this @AndresMorelos

**Comment by pernielsentikaer** [comment]
Hi @AndresMorelos 👋 

Thanks for the update, really appreciate your time finishing this 🙂

I added some new features like checking if Numi is installed and added handling of closed Numi, could you give it a spin and give some feedback 🙂

**Comment by AndresMorelos** [comment]
@pernielsentikaer I added one missing bundleId `"com.dmitrynikolaev.numi"` this is the id of the app downloaded from numi.app, thank you for ur help

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
