### PR TITLE
Notion add simple page search

### PR DESCRIPTION
**Pull request by HenriChabrand**
## Description

Search Notion page and open them in Notion Application (if installed).
Quickly access the last 20 opened Notion pages.

## Type of change

- Bug fix / improvement for my extension

## Screencast

Screenshot 2021-11-19 at 14 54 23

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @HenriChabrand 👋 

Awesome, the search works perfectly now, MUCH better 💪 

When using the “Create Database Page” command, it fails, did you remove the slug?

Could you into this?

2E1KCXa1xdJNiylM

```
TypeError: Cannot read properties of undefined (reading 'value')

  const notion_workspace_slug = String(preferences.notion_workspace_slug.value)
                                                                         ^

CreateDatabaseForm:create-database-page.tsx:35:74

---
32: export default function CreateDatabaseForm(): JSX.Element {
33:   // Get preference values
34:   const notion_token = String(preferences.notion_token.value)
35:   const notion_workspace_slug = String(preferences.notion_workspace_slug.value)
36:   if (notion_token.length !== 50) {
37:     showToast(ToastStyle.Failure, 'Invalid token detected')
38:     throw new Error('Invalid token length detected')
---

renderWithHooks:react-reconciler.development.js:5636:22
mountIndeterminateComponent:react-reconciler.development.js:7756:17
beginWork:react-reconciler.development.js:8543:18
Object.invokeGuardedCallbackProd:react-reconciler.development.js:9534:14
invokeGuardedCallback:react-reconciler.development.js:9621:35
beginWork$1:react-reconciler.development.js:12459:11
performUnitOfWork:react-reconciler.development.js:11682:16
workLoopSync:react-reconciler.development.js:11636:9
renderRootSync:react-reconciler.development.js:11611:11
```

**Comment by HenriChabrand** [comment]
@pernielsentikaer Good catch – it should be good now 👌

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @HenriChabrand 👋 

Again, MUCH better, I'm doing a thorough everytime, so I'm sure that I'll catch every small glitch 😄 

If setting a wrong secret key I get this the first 4/5 time
ryswui0HVUVhGONC

````
2021-11-20 21:33:28.393 F  Raycast[86584:322ca9] [com.raycast.extensions.notion:create-database-page] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at null.rawDatabaseProperties (/Users/pernielsentikaer/Desktop/rc2/extensions/notion/src/notion.ts:132:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at null.fetchDatabaseProperties (/Users/pernielsentikaer/Desktop/rc2/extensions/notion/src/notion.ts:103:51)
    at null.fetchData (/Users/pernielsentikaer/Desktop/rc2/extensions/notion/src/create-database-page.tsx:100:43)
2021-11-20 21:33:28.443 F  Raycast[86584:3220fa] [com.raycast.extensions.notion:create-database-page]
Error: Failed to fetch database properties

    throw new Error('Failed to fetch database properties')
          ^

rawDatabaseProperties:notion.ts:163:11

---
160:   } catch (err) {
161:     console.error(err)
162:     showToast(ToastStyle.Failure, 'Failed to fetch database properties')
163:     throw new Error('Failed to fetch database properties')
164:   }
165: }
166:
---

processTicksAndRejections:task_queues:96:5
fetchDatabaseProperties:notion.ts:103:51
fetchData:create-database-page.tsx:100:43
```

After 4/5 times, I see the new “No Shared Content” - can you look into this?

**Comment by HenriChabrand** [comment]
@pernielsentikaer I've added a custom error when Token is invalid, both for create and search page command 👍

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @HenriChabrand 👋 

Thanks for the update 💯 

A few comments:
- If token is wrong length, it's dying instead of gracefully telling about it, can you do anything about this also?

DboA3mN3yelddTN6

- Just to be sure, is it correct that only “Create Database Page” shows the README - not that it's a problem, just wanted to be sure 😄 

We're pretty close to merge! 🚀

**Comment by HenriChabrand** [comment]
Re @pernielsentikaer 

So actually the Token length check was a copy/paste from another Extension – but it is now redundant with the `Invalid token` notification, so I removed it.

And yes I only return the read when there's no database shared for the `Create Database Page` command.
As for the `Search Page`, is a research return no pages `[]` – I have no ways to know if it is because the user is searching something that doesn't exist – or if he has forgotten to share pages, unfortunately.

**Review by pernielsentikaer — APPROVED** [review]
Hi @HenriChabrand 👋 

Thanks for the update and clarification 👍 I'm going to accept it and my colleague will do a final check before merging 🚀 

Thanks for the patience 😄

**Pull request merged**
