### PR TITLE
Update `ImprovMX` Extension (fix #12812, #12813, #12817) (dev QoL)

### LINKED ISSUE #12812: [ImprovMX] `Manage Domains and Aliases` loads infinitely on first run
### Extension

https://www.raycast.com/ImprovMX/improvmx

### Raycast Version

1.76.0

### macOS Version

13.0.1

### Description

NOTE: I am already working on fixing this issue within the next few days - no action needed from the author.

The first time you run the extension, the `Manage Domains and Aliases` command fetches domains then "flickers" and loads infinitely. This is fixed the next time you run the command but affects the UX.

### Steps To Reproduce

1. Install extension fresh from store
2. Run `Manage Domains and Aliases` command
3. Observe that screen flickers then loads

https://github.com/raycast/extensions/assets/30526133/6b19a21f-d312-4218-a23a-1b0545d6cabd

### Current Behaviour

screen flickers then is stuck loading

### Expected Behaviour

domains should show without having to re-run the command.

### PR DESCRIPTION
**Pull request by xmok**
## Description

<details><summary>PR Logic (can be skipped)</summary>
<p>
Initially, I just wanted to add a new subcommand `View Domain Logs` which is how I came across #12812. It was difficult to identify the cause of the issue but a combo of the useEffect and now deleted fetchAccont function is my guess. That is when I replaced some of the code with the new hooks mentioned in CHANGELOG. To keep it the code uniform, I decided to refactor as much as possible to make future enhancements easier.
</p>
</details>

## Code Explanation
Though I made a lot of changes, most of it is removal of duplicated code so the following is an explanation:

Previously:
A Command would `fetch` the API. Each command would have the same error handling code in the same try catch repeated verbatim in each call.

Now:
`useImprovMX` hook wraps `useFetch` and returns parsed data.
`useImprovMXPaginated` hook wraps `useFetch` and returns parsed data w/ pagination object.
`constants.ts` provides all the API related constants.

Under the hood, both hooks use `parseImprovMXResponse` to `parseResponse`. We pass this function T as type of data w/o Array and K as key of the data (comments have been added). The function `throws` Error and since default behaviour of `useFetch` is to `showFailureToast`, that covers error handing.

For more error handling, we use the returned error object from hook and show `ErrorComponent`.

For `no-view` commands and some I have opted to keep `node-fetch` as it makes the code easier to understand. However, like the hooks, we use `parseImprovMXResponse` to parse the response.

Finally, I decided to remove the `fetchAccont` function itself. This function would first get the LocalStorage data. If data was present, it would check if enough time has passed. If time has passed or there was no data in first place, it would fetch latest account data and store it. The problem with this is if I change my email and/or subscribe to different plan, if we use LocalStorage data and enough time has not passed, that data is stale. SO it's easier to fetch the latest data itself. However, if Team ImprovMX disagrees, we can restore that functionality.

## Screencast

https://github.com/raycast/extensions/assets/30526133/f90459ac-1aa7-4015-a9d0-bab78349877b

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@improvmx do you mind checking this PR 🙂

**Comment by pernielsentikaer** [comment]
https://github.com/improvmx / @cnicodeme one last ping 🙂

**Comment by cnicodeme** [comment]
Yes, sorry. The person who worked on this is no longer working with us so this lands on me but I haven't followed the development (nor the quality of the initial code) and I'm not specialized in neither Raycast nor this code.

I can review the changes in a pure pragmatic way (does it makes sense, does the call to our API can be improved, etc) but I can't review the features and if the change added/removed things.

Does that work?

**Comment by pernielsentikaer** [comment]
Sure, it works. You can use the guide at the bottom to check it out. Basically, we want to make sure nothing is broken after the update :) Whether the code could be 5% more optimized is not the main concern

**Comment by cnicodeme** [comment]
I finally had time to review the PR and it appears to be good and well structured.
Do you need me to do anything special?

**Comment by mil3na** [comment]
Other than approving it, we should be good to go!

**Comment by cnicodeme** [comment]
I don't have a way to approve this pull request.

**Comment by mil3na** [comment]
Oh, I'm so sorry, I din't realize that. I will be reviewing and approve this soon.

**Comment by cnicodeme** [comment]
No worries ;)

**Review by mil3na — APPROVED** [review]
LGTM!

**Pull request merged**
