### PR TITLE
Add raycast-jq extension

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
## Description

This adds the extension to query JSON files or clipboard content with [jq](https://jqlang.github.io/jq/).

## Screencast

<details><summary>Hidden due to large size</summary>

jq_cast_1
jq_cast_2
jq_cast_3

</details> 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
There is a crash when you open the extension and leave the file picker open for about 10 seconds. Could you look into that before I dive deeper?

raycast-jq 2024-11-18 at 13 27 06

**Comment by pernielsentikaer** [comment]
The issue with timeout should be fixed in the latest version of @raycast/utils (1.18.1) - could you try that?

**Comment by vladimir-kotikov** [comment]
> The issue with timeout should be fixed in the latest version of @raycast/utils (1.18.1) - could you try that?

Yep, it works now. Updated the code accordingly

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Would it be better to let the user install jq with brew (or link to the installation page) instead of just installing it, I don't think this way will work for intel machines, right?

**Comment by vladimir-kotikov** [comment]
I've actually initially implemented the logic to determine system arch and download the appropriate binary, but it seems it has been lost during my experiments, so I think I can reimplement it back so it works for any processor architectures.

As for the option to use system jq - that would be nice (and I was considering adding an option to choose between system and downloaded jq) but it appears that the extension not getting the system PATH variable so spawning system jq would require asking user to provide full path to it, which I feel is not very friendly (or guessing it, which is error-prone). 

Also, the current [documentation suggests](https://developers.raycast.com/basics/prepare-an-extension-for-store#binary-dependencies-and-additional-configuration) to

> avoid asking users to perform additional downloads and try to automate as much as possible from the extension

so I was trying to follow that.

What do you think?

**Comment by vladimir-kotikov** [comment]
Done!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
