### PR TITLE
Airtables - Added custom no-view, Corrected naming errors

### PR DESCRIPTION
**Pull request by pernielsentikaer**
## Description

Added custom no-view
Corrected naming errors

## Screencast

image

image

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Could you check this @marks

**Comment by marks** [comment]
Thanks @pernielsentikaer ! Looks good to me and appreciate your help. 

Im mobile and on vacation so I can't test it but recommend merging. 

Do you think the other lists should be updated to show the number of results similarly in the list header?

Thanks again!

**Comment by pernielsentikaer** [comment]
Thanks for the approval, I'll check the rest of the code and add some more corrections 😊

**Comment by marks** [comment]
Awesome. I wouldn't expect any other lists to have 0 results (though not a bad idea to have a fallback), I just assume it'd be desirable to have consistent headers

**Comment by pernielsentikaer** [comment]
It's also showing the [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) when you search doesn't find a match, should be a bit more consistent now 😊

**Comment by pernielsentikaer** [comment]
Let's update with this, if anything pops up I will be available to correct it 😊

seal-of-approval-thumbs-up-gif

**Pull request merged**
