### PR TITLE
Add bahnexperte extension

### PR DESCRIPTION
**Pull request by ghost**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by KrautByte** [comment]
In reference to https://github.com/raycast/extensions/pull/7925
Had no idea how to update that pull request as the publish script threw errors my way.

**Comment by pernielsentikaer** [comment]
Hi 👋 

The icon should be 512x512 px 🙂

**Comment by KrautByte** [comment]
Is there any way to run all of this checks locally? I got a machine with 64 gigs ram and a good ethernet connection. I don't want to waste 3 hours time to get that message...

**Comment by pernielsentikaer** [comment]
Three hours? It shouldn't take more than a few seconds to lint, you have scripts in `package.json` for that

Raycast-LV1aE59a@2x

**Pull request closed without merging**
