### PR TITLE
[#407] [2fa extension]: Add generation options, tokens sortiong

### PR DESCRIPTION
**Pull request by guga4ka**
## Description

Add options to the token generator, optional sorting for tokens
#407 

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @cjdenio 

## Screencast

options
sorting

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

FYI:  @bennetfabian

### CODE REVIEW

**Comment by bennetfabian** [comment]
Thanks for actually looking into it. Appreciate it!

**Review by bennetfabian — APPROVED** [review]

**Comment by guga4ka** [comment]
I've been thinking about adding [otpauth](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) parsing, but not sure if it is a good idea.

**Comment by bennetfabian** [comment]
Especially sites like GitHub or other developer tools focused on tech-savvy people often use the standardized URI scheme so it would seem like a good idea to me. URI parsing should be relatively easy to robustly implement either by writing custom RegExp or using a URI parsing library.

**Review by bennetfabian — APPROVED** [review]

**Comment by bennetfabian** [comment]
Can anyone merge?

**Comment by cjdenio** [comment]
One quick comment: should alphabetical sorting be an option? It seems reasonable enough to be the default.

**Comment by bennetfabian** [comment]
> One quick comment: should alphabetical sorting be an option? It seems reasonable enough to be the default.

To be honest, I thought that, too. Just didn't say anything because I didn't want to make you think I don't appreciate your work. @guga4ka 

Let's think about it from another perspective: could you imagine there may be people who prefer random sorting as a default? At least from my perspective, I couldn't relate to people who prefer random sorting. 😅
@cjdenio @guga4ka

**Comment by guga4ka** [comment]
@cjdenio quick question is the "remove" shortcut working for you? I have ISO keyboard (large return and short left shift) and I guess the right button should be "return" not an "enter".

Is it ok, to create one more pr to remove the sorting option and make sorting by default? Also, should I add a view to hast otpauth URL to create token?

**Comment by cjdenio** [comment]
Hmm, the ctrl+shift shortcut isn't working for me either (looks like a Raycast bug perhaps)

otpauth parsing sounds awesome; I think that it could be added in the same PR as removing the sorting option (if you're up to it)

Thanks!

**Pull request merged**
