### PR TITLE
Add "Quick Event" Extension

### PR DESCRIPTION
**Pull request by mblode**
## Description

This is a new extensions that adds "Quick Event" extensions

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/7183998/148848801-163f85f3-cc3e-41a6-b4e4-b98cc29e894a.mp4

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Review by fe9lix — COMMENTED** [review]
Hey @mblode, thanks for the contribution. General question: 

Have you considered using a forms-based UI here? (Updating other components after each input change in a textfield). The primary use of a list + search bar is listing and filtering items and less that of creating new items.

Btw, forms also provide a date component that supports NLPish capabilities, e.g. you can enter expressions such as "tomorrow at 5 pm" or "next monday" into the component.

**Comment by mblode** [comment]
@fe9lix I've reviewed some alternative designs using the Raycast UI components. I'm going to stick with the current implementation. I think it has the right balance of simplicity and efficiency for a quick command to create calendar events.

**Comment by fe9lix** [comment]
Hey @mblode, some comments on the current version:

- When I delete all characters from the search bar, the list is not reset properly and still keeps an item for the first character.
- Is there anything that could be shown by default in the list? It's not too nice to show "No results" and unfortunately this API doesn't yet allow customizing this default text
- Is there any error handling if the calendar doesn't exist or is not accessible?

**Comment by fe9lix** [comment]
Hey @mblode – any updates on this?

**Comment by mblode** [comment]
@fe9lix I'm so sorry I forgot to respond to your feedback!

- I've fixed the issue that now if you clear the text it will correctly show an empty result.
- I think it's fine to just show an empty results set when the user hasn't typed anything. This isn't meant to be a deep calendar integration and it's just a quick entry solution.
- Unfortunately the AppleScript calendar integration is fairly limited in error handling. If the calendar doesn't match then it simply doesn't create a calendar event.

Are you happy with these outcomes? Do you think it's ready to merge

**Comment by mblode** [comment]
@fe9lix I've fixed this up 👍  I'm really glad you found this bug!

**Review by fe9lix — APPROVED** [review]

**Pull request merged**
