### PR TITLE
Add raycast-link-lock extension

### PR DESCRIPTION
**Pull request by EvanZhouDev**
## Description

An extension, powered by `shrtco` that takes any link, and locks it behind a password. An example of a "locked" YouTube link is as follows: [shrtco.de/2CuGX6](https://shrtco.de/2CuGX6). The password is `12345` 😄.

Huge thanks to @Visual-Studio-Coder for discovering the amazing service, and look out for his upcoming [link shortener extension](https://github.com/raycast/extensions/pull/7897) that will also be powered by `shrtco`!

## Screencast

Here's what it looks like when you Lock a link.

raycast-link-lock-1

It copies the link to your clipboard, and the result itself is what I showed above with [shrtco.de/2CuGX6](https://shrtco.de/2CuGX6).

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @EvanZhouDev 🔥 

I cleaned the code to use useForm instead, could you test that I didn't break something 🙂

**Comment by EvanZhouDev** [comment]
@pernielsentikaer Can you take a look at the Raycast Arcade thing too? Forking and restarting PR doesn't work either :(

**Comment by pernielsentikaer** [comment]
I'll catch you in Slack 🙂

**Comment by EvanZhouDev** [comment]
All good!

**Pull request merged**
