### PR TITLE
[Speedtest] Update interface to include streaming quality - 12232

### PR DESCRIPTION
**Pull request by aliaksandrZh**
## Description
The issue - [12232](https://github.com/raycast/extensions/issues/12232)

- The interface has been updated to incorporate streaming quality.
- It now displays the available quality for both voice/video calls and streaming.
- Additionally, in the event of a poor internet connection, a corresponding icon will be displayed.

## Screencast
Изображение

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by tonka3000 — COMMENTED** [review]
Looks good to me. One thing confuse me.
Why are all files in the bandwidth folder prefix again with bandwidth? Seems like redundant to me. 

Btw: I can not the the runtime behavior for now

**Comment by aliaksandrZh** [comment]
> Looks good to me. One thing confuse me. Why are all files in the bandwidth folder prefix again with bandwidth? Seems like redundant to me.
> 
> Btw: I can not the the runtime behavior for now

Hi there. Thank you for the review.
It makes sense to drop duplicated words. Updated filenames.

Here they are some showcases:

Default Internet connection:

[Default internet connection](https://github.com/raycast/extensions/assets/108681764/b1d96ea9-2aa0-469b-8170-9f09d405b6a0)

Poor internet connection: 

[Poor internet connection](https://github.com/raycast/extensions/assets/108681764/5615730b-f31e-434a-b22d-29a99aa467fb)

**Review by tonka3000 — APPROVED** [review]
As already I can not test the runtime behavior now, maybe @pernielsentikaer can do that. Code is fine for me.

**Review by pernielsentikaer — APPROVED** [review]
I think everything looks good, let's merge it ✅

**Pull request merged**
