### PR TITLE
Add colorify extension

### PR DESCRIPTION
**Pull request by EvanZhouDev**
## Description
Introducing `colorify` for Raycast: Say goodbye to the days of manually crafting themes to match your wallpaper! With `colorify`, simply upload an image, tweak a few settings, and let the magic happen.

Key features:
-  Raycast AI-powered theme generator
-  Support for both light and dark themes
-  AI-generated theme titles for a personalized touch

## Screencast
colorify-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
I love the idea of this PR and tried it out. I get the following error:
```
07:21:20.594
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
07:22:27.210
Error: Worker terminated due to reaching memory limit: JS heap out of memory

NodeError:errors:399:5
[kOnExit]:worker:287:26
Worker.<computed>.onexit:worker:209:20
```
It works on some  images and not on others.  Here are some of the images I tried it with:
20131112_PIA17172
main_image_star-forming_region_carina_nircam_final-5mb

It works on the carina nebula (wich has 5mb) but not on the image of saturn.

Asking for a title has worked in some cases but not in all cases.

**Comment by EvanZhouDev** [comment]
It doesn’t work with images that are too large. Going to try to find a workaround but essentially you can just reduce image quality with something else and plug it in.

What do you mean by AI title not working, though? It has worked for me nearly every time?

**Comment by AaronDavidSchneider** [comment]
> It doesn’t work with images that are too large. Going to try to find a workaround, but essentially you can just reduce image quality with something else and plug it in.

I had the same thought, but it seems that the large image works (5mb) and the small one doesn't (0.5mb).

> What do you mean by AI title not working, though… It has worked for me nearly every time?

I can't reproduce it at the moment, but there were certain title that didn't work

**Comment by EvanZhouDev** [comment]
Well I’ll try to figure it out the image problem when I get back to my computer… it’s probably a resolution thing in the end.
What do you mean by “Doesn’t work” though for the title? Does it not give you a title, error out, or something else?

**Comment by AaronDavidSchneider** [comment]
> Well I’ll try to figure it out the image problem when I get back to my computer… it’s probably a resolution thing in the end. What do you mean by “Doesn’t work” though for the title? Does it not give you a title, error out, or something else?

I believe it doesn't give a title. But there is no direct error thrown. I think you could use a fallback title, when the AI command returns something weird.

**Comment by EvanZhouDev** [comment]
Okay, so I have implemented a system in which images are first resolution-reduced, then processed with `color-thief`, but it still doesn't work with the 9k Saturn image...

**Comment by AaronDavidSchneider** [comment]
Thats fair! Sorry, I only now realised it was 9K. Its black most of it and thus can be compressed to 0.5mb, which confused me.

Here is a warning that I now get:
```
14:38:46.424 (node:39491) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

The warning is a good idea, but maybe you could catch the exception? And print a proper toast?

**Comment by EvanZhouDev** [comment]
> Here is a warning that I now get:
> 
> ```
> 14:38:46.424 (node:39491) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> ```

That's from a library, can't necessarily fix it easily...

> The warning is a good idea, but maybe you could catch the exception? And print a proper toast?

It's hard to tell the difference between that exception and the rest of the exceptions (i.e. in AI, JSON.parse(), etc.), because you can't know when _exactly_ JS heap runs out of memory...

**Comment by EvanZhouDev** [comment]
On second thought I may as well wrap the whole thing inside a `try/catch`

**Comment by EvanZhouDev** [comment]
It doesn't work 😅. I think it's an error on the entire Raycast `node` process and not a JS thing...

**Comment by mil3na** [comment]
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

First of all, I love the idea and it will be so useful to me! Thanks again.
About the image size problem, maybe you could do some validation on the form and limit the image size? I think it's worth doing that if it's a known issue / unsupported feature.

Also, for the dark themes, codeblocks are not very color-friendly. Anything that can be done about that?

CleanShot 2023-07-14 at 15 06 53@2x

**Comment by EvanZhouDev** [comment]
Hello! Thank you so much for your kind words.

I will definitely try to get the size thing down, but the code blocks are a bit harder to fix. I am currently extracting colors with `colorthief`, and then using AI to improve contrast and build it into a theme. The codeblocks look bad because I am not editing the "Support Colors," but I fear that providing the AI with too much will just cause it to be confused. Do you have any ideas about how to fix that?

**Comment by mil3na** [comment]
I believe that the way to go is to match the support colors with the ones you get from AI. You don't need to generate those, but re-use the ones you got or maybe re-use them in another tone/contrast/brightness so it would match the theme. Give it a go, if it doesn't work, I don't think it's a blocker, as the user can edit the theme later.

**Comment by EvanZhouDev** [comment]
I'm just curious, how do you suggest I modify the colors? I just don't see a way to measure the "contrast" level of the colors...

**Comment by mil3na** [comment]
Yeah, I know you can do some mathematics and find different tones of the same color. But generating color based on pictures that also look good/visible is a very hard problem. My suggestion was to use the colors you already have.
Again, I don't think it's a blocker, just let me know if you want to solve this problem later.

**Comment by EvanZhouDev** [comment]
Yes, I will try to implement that some time in the future. I am currently working on another project, so I may get back to this later.
With the image size checking, even checking the size of really large photos drives JS heap out of memory, so there's really nothing I can do about it... I did implement the code though.

**Review by mil3na — APPROVED** [review]
I think it should be fine. We will see on the community if people are encountering errors with it and we can come back to this then. Thanks for your effort, I will be using this right now :)

**Pull request merged**
