### PR TITLE
[Visual Studio Code] Add Customizable Git Branch Color Option

### PR DESCRIPTION
**Pull request by VatsalSy**
## Description

inspired by https://github.com/raycast/extensions/issues/15693

🎨 Add customizable Git branch color option
•	Introduce a new setting in package.json for users to define a
custom hexadecimal color code for Git branch tags.
•	Update index.tsx to apply the user-defined color if valid,
defaulting to green otherwise.
•	Expose gitBranchColor in preferences.ts to integrate with
existing preferences.
•	Add isValidHexColor function in utils.ts to ensure color
codes are valid.
This enhancement allows users to personalize their Git branch
display, improving the visual experience.

## Screencast

How to edit color:
CleanShot 2024-12-04 at 22 59 58@2x

how it shows up: 
CleanShot 2024-12-04 at 22 49 11@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by VatsalSy** [comment]
@pernielsentikaer Any idea why pull_request action keeps failing.... :(

**Comment by VatsalSy** [comment]
thanks for the updates @pernielsentikaer

**Review by VatsalSy — COMMENTED** [review]
is there an easy way to fix the ``Prefer Title Case naming convention for action titles (e.g Copy to Clipboard)" warnings? 

I know these are only warnings... but would be satisfying if they are also all fixed..

**Comment by pernielsentikaer** [comment]
There is a way, but you'll need to add a comment above the warning to instruct the linter to ignore it

Could you also check that I didn't break something with my fixes?

**Comment by VatsalSy** [comment]
yes, I was just checking that.. and all looks fine. :) nice work. I think I am getting a hang of this. :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
