### PR TITLE
[Spotify-Player] Add the ability to dislike songs

### LINKED ISSUE #2449: [Spotify Player] Add "dislike" command
# Extension – [Spotify Player](https://github.com/raycast/extensions/tree/main/extensions/spotify-player)

Author: @mattisssa

**Describe the feature and the current behavior/state.**
Add a command to dislike a song (I often use it in the "Discover Weekly" playlist).

**Who will benefit from this feature?**
Everyone who loves to say to Spotify they don't like a song (better matching).

### PR DESCRIPTION
**Pull request by ghost**
## Description

Resolves #2449 

Dislike the current song by `dislike current song` command or click dislike item in the menu bar, and  HUD will pop up.
In fact, like/dislike song should be integrated into one item in the menu bar. When the song is already liked, show dislike item.

But the client ID does not support setting in preferences, `user-library-read` is illegal scope for current client ID. So I can't check whether the current song is saved.

By the way, I added the display of the track album cover in the menu bar. Maybe it looks better this way.

## Screencast

image
image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by dancannon — COMMENTED** [review]
Reviewed these changes and tested locally. All looks good on my end (and thanks for these changes!)

Regarding the client permissions I have talked with @mattisssa before and unfortunately Spotify are not responding to his/raycast's requests to update the client permissions.

That being said I think it would be good to split the changes to the menu bar icon into its own PR and it would be great if you could update the extensions changelog. Thanks!

**Comment by daikaiyu** [comment]
> Reviewed these changes and tested locally. All looks good on my end (and thanks for these changes!)
> 
> Regarding the client permissions I have talked with @mattisssa before and unfortunately Spotify are not responding to his/raycast's requests to update the client permissions.
> 
> That being said I think it would be good to split the changes to the menu bar icon into its own PR and it would be great if you could update the extensions changelog. Thanks!

Thank you for reviewing.

For menu bar icon, it is indeed a more personalized requirement, I have considered adding additional preferences to toggle on and off, but I did not do it.

Now I have removed the menu bar icon and updated the extensions changelog.

**Review by dancannon — APPROVED** [review]
Great, thanks again!

I don't have permission to merge but I am happy with these changes and hopefully somebody from Raycast can have a look soon.

**Comment by pernielsentikaer** [comment]
I tested this and it seems to do as expected, is there anything we need to address or is everything ready?

**Comment by daikaiyu** [comment]
> I tested this and it seems to do as expected, is there anything we need to address or is everything ready?

I think everything is ready.Maybe we can close the issue #2449 .

**Pull request merged**
