### PR TITLE
[search-npm] Update and add new features

### PR DESCRIPTION
**Pull request by mrmartineau**
## Description

This PR updates my search-npm extension in a few ways:
- updated to the latest `@raycast/api` package version and refactored based on any new APIs and deprecations
- added [pnpm](https://pnpm.io) as an option for default package manager. Now there are three: `yarn`, `npm` and `pnpm`, which meant the existing logic for choosing a default and alternate was not sufficient
- added new option for secondary package manager. This helps with the above point so users can explicitly choose the secondary/fallback package manager
- add link to [Skypack.dev](https://skypack.dev) for each package
- updated the default open action to include new Skypack.dev link
- added more information to the list item's `accessories`, now you can view the latest publish version, when the package was last published and the npms.io score for that package.
- also added screenshots (metadata) and categories info in `package.json`

## Screencast
2022-05-04 at 7 29 32 - Olive Halibut

https://user-images.githubusercontent.com/64883/166630703-962ac4de-5da5-40f6-8895-25aeb92bcfb6.mp4

### New preferences
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @mrmartineau 👋 

Thanks for the update, it looks and feels like a good one 💯 

I have some suggestions for you:

- Metadata images are not [following the guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots), if you need help let me know

- You should maybe consider adding an AbortController to cancel requests while typing, on your video I saw that it doesn't.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by mrmartineau** [comment]
@pernielsentikaer I have made the relevant changes now, please re-review

**Comment by pernielsentikaer** [comment]
I updated the AbortController. Take a look if you want to 😄 

Do you want to select the images needed, or should I remove a few? We’re only allowing 6 in total 😄 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by mrmartineau** [comment]
@pernielsentikaer I have removed a couple of images now, didn't see the docs about a max number

Thanks for the `AbortController` fix

**Review by pernielsentikaer — APPROVED** [review]
Hi @mrmartineau 👋 

You're so much welcome, AboertController also giving me troubles almost everytime 😄 

Awesome, thanks @mrmartineau 🔥

**Pull request merged**
