### PR TITLE
Add open-docker-dashboard extension

### PR DESCRIPTION
**Pull request by devsejong**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

Could it make sense to add this into the [Docker extension](https://www.raycast.com/priithaamer/docker) that @priithaamer made?

**Comment by priithaamer** [comment]
Hey @devsejong, @pernielsentikaer!

Looks like a good candidate for additional action there indeed. Feel free to submit a PR to Docker extension.

Ideally, the command would be available only if Docker Desktop is installed as there are many other ways to manage docker instance. Not sure if action availability based on some heuristics is possible though.

**Comment by pernielsentikaer** [comment]
We can have it disabled by default 🙂

**Comment by devsejong** [comment]
Sorry for the late comment due to I'm on vacation for a while.
I will send a PR to existing Docker extension soon.

**Comment by pernielsentikaer** [comment]
I'll close this 🙂

**Pull request closed without merging**
