### PR TITLE
Use built-in icons for AWS extension

### PR DESCRIPTION
**Pull request by JonathanWbn**
## Description

- introduce the usage of built-in icons instead of imported icons for the "Codepipelines" extension
- add an icon to list items of "Cloudformation Stacks"
- add fallback to creation date to list items of "Cloudformation Stacks"
- update "@raycast/api" dependency

### CodePipelines Before
Screenshot 2022-07-30 at 13 54 45
### CodePipelines After
Screenshot 2022-07-30 at 13 53 18
### CloudFormation Stacks Before
Screenshot 2022-07-30 at 13 57 19
### CloudFormation Stacks After
Screenshot 2022-07-30 at 13 58 05

### CODE REVIEW

**Review by gebeto — APPROVED** [review]
🔥

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @JonathanWbn 👋 

Thanks for the update, could you also add an entry in the changelog about this? 🔥

**Comment by pernielsentikaer** [comment]
Can you also check this @victor-falcon 🔥

**Comment by victor-falcon** [comment]
For me, it's ok :), good job 🎉

**Review by mattisssa — APPROVED** [review]

**Pull request merged**
