### PR TITLE
Add lemmy extension

### PR DESCRIPTION
**Pull request by httpjamesm**
## Description

Official description: Lemmy is a selfhosted social link aggregation and discussion platform. It is completely free and open, and not controlled by any company. This means that there is no advertising, tracking, or secret algorithms. Content is organized into communities, so it is easy to subscribe to topics that you are interested in, and ignore others. Voting is used to bring the most interesting items to the top.

This extension interfaces with Lemmy's API to create a "Lite" browsing client for timelines, search and notifications.

## Screencast

lemmy-1
lemmy-2
lemmy-3
lemmy-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by httpjamesm** [comment]
Hey, for the instance URL, did you prepend the protocol? It should be https://lemm.ee, not lemm.ee. This will help me identify the issue.

**Comment by mil3na** [comment]
Yes, I did :) Just copy-pasted from Chrome.

**Comment by mil3na** [comment]
Sorry, I just saw that there was a 's' missing. It works now. But still, it would be nice to have a error handler, as user input can always cause error.

**Comment by httpjamesm** [comment]
For sure. I will add more error handling

**Comment by httpjamesm** [comment]
@mil3na Are you available to test out this fix?

**Comment by mil3na** [comment]
Hey @httpjamesm! Sorry for the delay on answering you, I was off yesterday. I will continue the review during the day and hopefully we will be able to merge this 💪

**Review by mil3na — APPROVED** [review]
Well, it does look good to me! 
Any more changes you want to make or are you ready to publish?

**Comment by httpjamesm** [comment]
> Well, it does look good to me! 
> Any more changes you want to make or are you ready to publish?

I think I'm ready :)

**Pull request merged**
