### PR TITLE
Extension - [nextjs-docs] - Feature caching

### PR DESCRIPTION
**Pull request by PrasadChinwal**
Caching and Code Cleanup

## Description

Implemented caching for faster performance.
code cleanup.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @PrasadChinwal 👋 

I have tested this update and it works as expected, I have some feedback for you:

- I don't think the loading toasts add anything to the UX, it's now that fast that it's only visible for a few milliseconds before disappearing again.

- The `Home` button in the `Detail` view should not be used, Raycast default is to use the Escape key instead as you can [see explained here](https://developers.raycast.com/api-reference/user-interface/navigation#usenavigation)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by PrasadChinwal** [comment]
@pernielsentikaer Thanks for the review. I'll get back with the suggested changes.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @PrasadChinwal 👋 

Thanks for the update, it seems to work as expected, awesome 🔥  

There is still a funny toast when opening the command, now it's a failure toast without content.

https://user-images.githubusercontent.com/38033107/172061672-471773c0-aac2-46e9-95cb-833a706d07e4.mp4

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Could you look into this @PrasadChinwal, seems like there is some merge conflicts  🔥

**Pull request closed without merging**
