### PR TITLE
Add blitlink extension

### PR DESCRIPTION
**Pull request by RobertBolender**
## Description

I created this small extension to help me be the fastest at replying with just the right link, meme, or reaction GIF.

It stores everything in a local SQLite database, no external dependencies.

Link to rendered [README](https://github.com/RobertBolender/extensions/blob/ext/blitlink/extensions/blitlink/README.md)

## Screencast

image

image

image

blitlink-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @RobertBolender 👋 

Looks a bit link what Quicklinks and Snippets in Raycast already do, can you help me understand the usecase of this 🙂

**Comment by RobertBolender** [comment]
> Hi @RobertBolender 👋
> 
> Looks a bit link what Quicklinks and Snippets in Raycast already do, can you help me understand the usecase of this 🙂

@pernielsentikaer 

They are very similar, but this has a few added conveniences:

- For images/gifs, I render a preview within the Raycast window
- I have a shortcut for copying a link formatted with markdown, i.e. `[title](url)`

Something I had not considered until now was whether it would be possible for this to build on top of Quicklinks/Snippets. I'm just now seeing that `Action.CreateSnippet` and `Action.CreateQuicklink` exist. Would there be an appropriate API where I could search for Quicklinks within my extension? I'm not immediately seeing one.

I see a few ways forward, what do you think of these?

1. Close this PR, add an issue requesting these conveniences within the core Quicklinks command.
2. Rewrite this PR to build on top of Quicklinks primitives (if such an API is available)
3. Merge this PR as-is.

**Comment by RobertBolender** [comment]
@pernielsentikaer would you have any thoughts on these possible ways forward?

> A. Close this PR, add an issue requesting these conveniences within the core Quicklinks command.
> B. Rewrite this PR to build on top of Quicklinks primitives (if such an API is available)
> C. Merge this PR as-is.

**Comment by pernielsentikaer** [comment]
I think the first option makes the most sense, since this is more or less the same. Would that be okay if we try that? We can always open this again

**Pull request closed without merging**
