### PR TITLE
Add bazinga-tools extension

### PR DESCRIPTION
**Pull request by luin**
## Description

This extension adds a shortcut so users can access tools on https://bazinga.tools easier.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/635902/152481278-855c59f3-5e4b-4338-9304-e2b7bac5abb9.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @luin 👋 

Just a question, are you aware of that almost every feature in banzinga.tools already exists directly in Raycast with the extension https://www.raycast.com/Kang/toolbox

**Comment by luin** [comment]
hi @pernielsentikaer 

Thanks for the quick response! 👍

I just checked it out and IMO there are some differences:

1. In most use cases, it's necessary to deal with multi-line text or local files, and bazinga-tools supports that out of the box. Also, it provides syntax highlighting.
2. Bazinga-tools also provides tools that don't fit in https://www.raycast.com/Kang/toolbox, most of which require a more structural input instead of a simple string, e.g. the border radius tool accept 4 integers and the markdown generator needs 2D table data.

So I think it'd be useful to provide an extension to allow users to access bazinga tools quicker from Raycast.

**Comment by pernielsentikaer** [comment]
Hi @luin 👋 

Valid point, thanks for taking your time to clarify 😄 

The only thing I can come up with is the title and subtitle regarding the [naming convention](https://developers.raycast.com/basics/prepare-an-extension-for-store#extensions-and-commands-naming)

Do you have an idea to make it a bit more lightweight?

**Comment by luin** [comment]
@pernielsentikaer Thanks for the feedback! I should have read the guideline more carefully.

I updated the titles so the subtitle becomes the product name and the title becomes the action. Does this change make sense?

**Review by pernielsentikaer — APPROVED** [review]
Hi @luin 👋 

I think it does, let's await final review 🔥 Thanks a bunch for your contribution 💪

**Comment by sxn** [comment]
🎉

**Pull request merged**
