### PR TITLE
[Bitwarden] add ability to paste a password

### PR DESCRIPTION
**Pull request by pomdtr**
## Description

Add the ability to paste a password to the active app. Also add a pref similar to the built-in clipboard extension to set the default primary action.

## Type of change

- New extension
- Bug fix / improvement for my extension
- Bug fix / improvement for somebody else's extension. Extension author: @GH-handle
- Documentation update
- Other (Specify)

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @pomdtr 👋 

I sent you a correctly formatted `search.tsx` in Slack that you can push, the update is doing as expected 💯

**Review by pernielsentikaer — APPROVED** [review]
Hi @pomdtr 👋 

Thanks for the update, it works as expected every bit of it, well done 🔥

**Comment by sxn** [comment]
thanks @pomdtr, looks good!
I've encountered an issue when trying to lock my vault though:
image

**Comment by pomdtr** [comment]
Interesting, it looks like you use some custom bitwarden installation ? I was not aware of this behavior.
Can you create an issue ? It is not related to this Pull request.

> And one nitpick if I may: could you change the toast message to say It may take some time instead of It may takes some time? 😅
😧

**Pull request merged**
