### PR TITLE
Show crosshair cursor for better accuracy

### PR DESCRIPTION
**Pull request by thomaspaulmann**
## Description

This changes the cursor of the ruler to crosshair which makes it eaier to accurately measure.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@anwarulislam do you mind checking this 🙂

**Comment by anwarulislam** [comment]
> @anwarulislam do you mind checking this 🙂

Yeah, sure!
How do I checkout to this specific PR without pulling all the extensions? 
Any guidelines?

**Comment by pernielsentikaer** [comment]
Hi @anwarulislam 👋 

It's not that simple but you can use sparse checkout, in this case it might be easier to move the few lines to your local version manually 🙂

**Comment by pernielsentikaer** [comment]
Did you have time to check it out @anwarulislam

**Comment by pernielsentikaer** [comment]
@anwarulislam could we merge this?

**Comment by anwarulislam** [comment]
Yeah, sure. I have tested it already.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
