### PR TITLE
feat: add grafana extension

### PR DESCRIPTION
**Pull request by Lp-Francois**
## Description

Extension for [Grafana](https://grafana.com/products/cloud/), allowing to access quickly dashboards & manage annotations (CRUD).

The README is quite comprehensive to showcase the different capabilities of this extension.

## Type of change

- New extension

## Screencast

[Screenshots provided in the readme](https://github.com/AsterYujano/extensions/blob/main/extensions/grafana/README.md
)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

Thanks for the reading 🙏

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @AsterYujano 👋 

Could you record a screencast for me so I can see it in action? 🔥

**Comment by AsterYujano** [comment]
Hello @pernielsentikaer! 👋 

https://user-images.githubusercontent.com/32224751/144726494-287eb1e1-db06-440d-8450-fa183d6e3b8b.mp4

Sure, here it is :)

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Lp-Francois 👋 

Thanks for your contribution, it looks very nice 🔥 

- If credentials are wrong then I see a failure toast, could you stop the loader, so it just shows “No Results”

When above is corrected, then I think we're ready to merge 😄 💪

**Comment by Lp-Francois** [comment]
Hi @pernielsentikaer 

I pushed 2 commits, one for the dashboard search, the other one for the annotation search. In case of an error coming from a wrong URL or Wrong API key, it will empty the results (shows “No Results”) & stop the loading.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Lp-Francois 🔥 

Thanks for the update, that was much better! 💯 

One thing I didn't notice last time was that in many files like `src/components/annotation/annotationActions.tsx` there is a lot of unused imports, could you tidy the scripts 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by Lp-Francois** [comment]
Hi @pernielsentikaer,

I have removed all the unused packages in the latest commit👌

**Review by pernielsentikaer — APPROVED** [review]
Hi @Lp-Francois 👋 

Much better 💯 I'm going to accept it and my colleague will do a final review before merging it 💪 

Thanks for your contribution 😄

**Pull request merged**
