### PR TITLE
Add dice-roll extension

### PR DESCRIPTION
**Pull request by FrederikBanke**
## Description

An extension for rolling any sided dice. You can roll multiple dice, using different combinations of sides.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @FrederikBanke 👋 

Thanks for your contribution 🔥 

Would it make sense to enhance the [current one](https://www.raycast.com/troalexis/rollcast) instead made by @TroAlexis

**Comment by FrederikBanke** [comment]
> Hi @FrederikBanke 👋
> 
> Thanks for your contribution 🔥
> 
> Would it make sense to enhance the [current one](https://www.raycast.com/troalexis/rollcast) instead made by @TroAlexis

Absolutely, only reason I made this, was because it was marked as stalled at the time.

**Comment by TroAlexis** [comment]
> > Hi @FrederikBanke 👋
> > Thanks for your contribution 🔥
> > Would it make sense to enhance the [current one](https://www.raycast.com/troalexis/rollcast) instead made by @TroAlexis
> 
> Absolutely, only reason I made this, was because it was marked as stalled at the time.

It would be really awesome if you could pull up a dice-roller parser like [this one](https://github.com/BTMorton/dice_roller) to allow for even more versatility in rolls.

**Comment by pernielsentikaer** [comment]
What is the status here, can I do something to ease the process?

**Pull request closed without merging**
