### PR TITLE
Update easy-ocr extension

### PR DESCRIPTION
**Pull request by Rafo1994**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Rafo1994** [comment]
I forgot to update extension description after removing Google OCR

**Comment by pernielsentikaer** [comment]
It looks like you're pushing the extension as a new one, could you only push the new files? 🙂

**Comment by Rafo1994** [comment]
How should I exactly do that?  🙂

**Comment by pernielsentikaer** [comment]
It should be enough to delete `Rafo1994:ext/easy-ocr` and try to push it again 🙂

**Pull request closed without merging**
