### PR TITLE
fix(tailscale): fix account switcher command

### LINKED ISSUE #9916: [Tailscale] Switch Account fails with error
### Extension

http://www.raycast.com/tailscale/tailscale

### Description

The `Switch Account` command for the Tailscale extension fails with the error below. This used to work and started to fail recently. It looks like [this code change](https://github.com/tailscale/tailscale/commit/2dc0645368d036c9233909ecfa53df73fa070d3d#diff-c3cce201135f1c09b2c735ff073f345069422071b59a1a6911340f2320d92cccR56-R66) in `tailscale switch --list` cli command changed the output format which broke this extension.

#### Error:
```
Error: Missing required property "title" for List.Item


```

Safari-tailscale com — New Issue · raycastextensions-2023-12-29-06 06 01

### Steps To Reproduce

1. Raycast version v1.64.4
2. Tailscale version - 1.57.25 track: unstable (dev)
3. open raycast, type switch, select the tailscale `Switch Account` command, hit enter

### Current Behaviour

Fails with the error 

### Expected Behaviour

Should pop up the account switcher

### PR DESCRIPTION
**Pull request by clstokes**
## Description

Fixes the `Account Switch` command. The output from the underlying `tailscale switch --list` command changed - adding a header line and a new ID column.

The upstream change to the tailscale cli output is https://github.com/tailscale/tailscale/commit/2dc0645368d036c9233909ecfa53df73fa070d3d#diff-c3cce201135f1c09b2c735ff073f345069422071b59a1a6911340f2320d92cccR56-R66.

Fixes #9916.

## Screencast

Safari-tailscale com —  Tailscale  Switch Account fails with error · Issue #9916 · raycastextensions-2023-12-29-07 47 14

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by clstokes** [comment]
Well, shoot. 🤦‍♂️

I searched existing issues for this first, but did not search existing pull requests. I saw #9907 after opening this.

**Comment by pernielsentikaer** [comment]
I don't know if yours or @Yukaii has the best solution, the code is different - can you two agree on the best solution?

**Comment by Yukaii** [comment]
Looks like @clstokes's solution is simpler! I'm happy with it (as long as the extension is working)

**Comment by Yukaii** [comment]
I'm still getting `missing required title` error on this branch. For reference, my tailscale cli output (`./Tailscale switch --list`) is:

```
ID    Tailnet              Account
1234                       Yukaii
5678  hhhhhhh.org.github   Yukaii@github
asdf  xxxxxxxx.org.github  Yukaii@github*
```

While the first row is my personal GitHub account, and the other two are GitHub organization logins.

**Comment by clstokes** [comment]
Thanks for the additional testing @Yukaii. I’ll take a look at this later today.

**Comment by Yukaii** [comment]
It's now working for me 🎉

**Comment by samlinville** [comment]
Works for me, thanks @clstokes and @Yukaii

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
