### PR TITLE
Updating applescript for ventura 13 (Change scroll direction extension)

### PR DESCRIPTION
**Pull request by emilshr**
## Description

- The existing [Change scroll direction](https://www.raycast.com/gregoralbrecht/change-scroll-direction) extension became obsolete with the changes to System settings panel in MacOS Ventura.
- Added additional appleScript to be run on devices on `Ventura`.
- Added test cases for the function that fetches the OS version.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Does this still work in older versions of macOS, or does it only work in Ventura?

**Comment by pernielsentikaer** [comment]
That would be the best solution if possible 😊

**Comment by pernielsentikaer** [comment]
Shouldn't it be `os.release()`?

Raycast-X0BqNpXK@2x

**Comment by emilshr** [comment]
> Shouldn't it be `os.release()`?
> 
> Raycast-X0BqNpXK@2x

`.release()` gives the entire platform information. Something like [this](https://en.wikipedia.org/wiki/Uname#Examples). The example that is mentioned here.
`.version()` is giving just the kernel version.
I started by using `.release()` but checked the docs and found that `.version()` exists.

**Comment by pernielsentikaer** [comment]
For me, it's opposite, and I'm not sure why 

Raycast-AhHdCrKn@2x

**Comment by emilshr** [comment]
@pernielsentikaer 
I'm sorry about the confusion, you're right.
It should be `.release()` 😅 
I've updated the PR

**Comment by pernielsentikaer** [comment]
Is it as intended that I'm landing here as the only thing happening?

Raycast-tKBGxIiI@2x

**Comment by emilshr** [comment]
Hey @pernielsentikaer 
Sorry I was a bit caught up with work. Let me check this, that shouldn't be the case. I'll add a new comment once I debug.

**Comment by emilshr** [comment]
@pernielsentikaer This should be taking you to the `Scroll & Zoom` tab, toggle the `Natural scrolling` checkbox.
For you, is the execution stopping once the system settings panel comes up?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Comment by gregoralbrecht** [comment]
Oh I completely missed this, sorry! Thank you @emilshr and @pernielsentikaer ❤️

**Pull request merged**
