### PR TITLE
feat(cleanshotx): add open-settings and open-all-uploads command

### LINKED ISSUE #11257: [CleanShot X] New command: Open settings
### Extension

https://www.raycast.com/Aayush9029/cleanshotx

### Description

I'd like to open CleanShot preferences from Raycast

### Who will benefit from this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by erics118**
## Description

add open-settings command to open settings
add open-all-uploads command to open https://cleanshot.cloud in browser
updated misc extension files

Fix #11257

@Aayush9029, it would be great if you could make the icons for these commands too! Thanks :)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Could we consider making the new two commands `disabledByDefault` so we don't end up with too many commands? We done something similar in the Spotify Extension

**Comment by Aayush9029** [comment]
LGTM on the code. 

Feel free to explore icons :) busy atm

**Comment by pernielsentikaer** [comment]
@Aayush9029 did you use the icon generator or do you have a logo without anything on?

**Comment by Aayush9029** [comment]
> @Aayush9029 did you use the icon generator or do you have a logo without anything on?

Used Figma with SFSymbol icons and a blue gradient, nothing fancy.

unfortunately, don't have the old files with me atm.

**Review by pernielsentikaer — COMMENTED** [review]
Maybe we can revamp all icons since they also is a bit different today and then we can save the preset so it's easier to make new?

Something like: https://ray.so/YDwEehc

**Comment by erics118** [comment]
I was hoping to do that, but the Raycast icons and SF Symbols don't match up too nicely with the CleanShot icons. 

Of course, the actual cleanshot icons are available in the Assets.car file, but nowhere close to the 512x512 resolution (they're 48x48).

**Comment by pernielsentikaer** [comment]
Can you come up with something, @erics118, or should I see if I can solve it

**Comment by pernielsentikaer** [comment]
I think we have to redo all icons now that @Aayush9029 doesn't have the template :&

**Comment by erics118** [comment]
I've emailed the CleanShot team and they'll be remaking the icons

**Comment by pernielsentikaer** [comment]
Wow, you're the best @erics118 🔥

**Comment by erics118** [comment]
I've added the new icons created by the CleanShot team. This PR should be good to go now

**Comment by pernielsentikaer** [comment]
Awesome work @erics118 🔥

**Pull request merged**
