### PR TITLE
Update bear extension

### PR DESCRIPTION
**Pull request by bradenschiller**
## Description
Similar to the Apple notes Ai extension this options will allow users to generate a note directly into their bear app utilizing Ai. 

## Screencast
CleanShot 2024-04-30 at 12 17 24@2x
CleanShot 2024-04-30 at 12 18 30@2x
CleanShot 2024-04-30 at 12 19 18@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Thanks for the enhancement @bradenschiller 🔥

@hmarr can you check this?

**Review by pernielsentikaer — COMMENTED** [review]
I can't remember if we can use useSQL from [@raycast/utils](https://www.npmjs.com/package/@raycast/utils) instead of loading a custom wasm?

**Comment by pernielsentikaer** [comment]
Do you think it's possible @bradenschiller

**Comment by pernielsentikaer** [comment]
@bradenschiller are you still around?

**Comment by ramsaysewell** [comment]
There are merge conflicts on this branch that are stopping it from being merged. Is it still being worked on?

**Comment by pernielsentikaer** [comment]
Calling a last time @bradenschiller - do you want to get this merged 🙂

**Pull request closed without merging**
