### PR TITLE
Update raycast-bard-ai extension

### PR DESCRIPTION
**Pull request by xsbchen**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by EvanZhouDev** [comment]
Hello! I'm the original developer of `raycast-bard-ai`. Here's something that can help you out: https://github.com/EvanZhouDev/gemini-ai, if you are planning to use the "official API." However, keep in mind that this is _not the official API for Bard_. Rather, it is the official API for the _model that powers bard_, Gemini Pro. These are two (rather distinctly, I'd say) different things. For one, Bard takes the AI model and combines it with other things, like Google Lens, Extensions, and Google Search to make it able to process images, Google Workspace, and live information. Just using the model will not yield this result.

Feel free to continue development on this branch, though I will be working on a dedicated Gemini extension in the future—I'm quite busy with other work right now though, and I may decide to merge this as a quicker solution for people.

Thank you for developing and contributing!

**Comment by pernielsentikaer** [comment]
So what's the status @EvanZhouDev 

Are we merging this when you have accepted?

**Comment by EvanZhouDev** [comment]
@xsbchen I have a new extension specifically for Gemini now at #9954... feel free to help out there after it is merged. I know it is currently missing chat, but I will be adding that and refactoring the whole thing specifically for Gemini later (i.e. adding Streaming and Image support).

I still believe we should leave the Bard extension still strictly for Bard, but I understand you have worked much on this, and I appreciate your help :)

**Comment by ddlaws0n** [comment]
> I think that would make sense, does this extension still work as expected (think I saw some issues with it(?)) @EvanZhouDev

It does not unfortunately as of this morning— also if you search `bard` on Open Issues there are 3 tickets opened in the past two weeks.

**Comment by pernielsentikaer** [comment]
Does it work correctly for you @EvanZhouDev

**Comment by xsbchen** [comment]
> @xsbchen I have a new extension specifically for Gemini now at #9954... feel free to help out there after it is merged. I know it is currently missing chat, but I will be adding that and refactoring the whole thing specifically for Gemini later (i.e. adding Streaming and Image support).
> 
> 
> 
> I still believe we should leave the Bard extension still strictly for Bard, but I understand you have worked much on this, and I appreciate your help :)

No problem, thanks for your kind feedback

**Comment by pjburnhill** [comment]
Unfortunately Gemini and Makersuite are not available in Europe at the moment. It would be good to have Bard running, if possible. Thanks.

**Pull request closed without merging**
