### PR TITLE
Add format-code extension

### PR DESCRIPTION
**Pull request by raszi**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

We already have an extension for Prettier on our store: https://www.raycast.com/lin/prettier
Do you think your extension provides any value that the one in our store doesn't? Or that could not be added to them?

**Comment by mil3na** [comment]
I understand that your extension has more Languages/ Frameworks options, but still, you are only using Prettier. I see your point about Prettier being just a way of implementing things, but so far, that's the only way you are doing it.

We want to avoid having duplications in our store and I still believe that your extension would be better lived as an addition to the current extension :)

**Comment by raszi** [comment]
Okay, then let me play the devil's advocate for a minute.

1. I would do the changes to the existing Prettier extension as you suggested.
2. Imagine it gets merged.
3. Then I would need to add yet another format that Prettier does not support but there is a great formatter that does.
4. Then, I guess the logical next step is to pull that dependency in and implement the functionality.
5. And then we would need to change the name of the prettier extension to something else.

Could you please explain to me how that would work? How would the existing users get the new functionality without uninstalling and installing the newly named extension?

**Comment by mil3na** [comment]
Extension updates are automatic and transparent to the user. Including when the extension changes names. There are a couple of cautionary actions to be taken by the reviewer on our side, but nothing that should block the dev/author to change their extension name if needed.

**Pull request closed without merging**
