### PR TITLE
Update gif-search extension

### PR DESCRIPTION
**Pull request by j3lte**
## Description

- Fixing bug #9483 where Giphy does not download the highest quality GIF

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by j3lte** [comment]
Seems @josephschmitt is inactive, can we still pull this in @pernielsentikaer?

**Comment by scottaw66** [comment]
Bump

**Comment by scottaw66** [comment]
Btw, this is not the only extension where the author seems to have gone AWOL. I wonder if Raycast could consider an "in case of missing owner" strategy for obviously popular extensions?

**Comment by thomaslombart** [comment]
Hey @j3lte, thanks for the fix! Could you resolve the conflicts? Everything looks good to me otherwise.

**Comment by j3lte** [comment]
@thomaslombart the conflicts should be resolved now...

**Pull request merged**
