### PR TITLE
add launch agents extension

### PR DESCRIPTION
**Pull request by stevensd2m**
## Description

New extension that allows the management of launch agents:
- list all agents
- create new agent
- select agent
- remove agent
- unload agent
- load agent

## Screencast

Screens added to metadata

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- What does `Create Launch Agent` do? Nothing happens when I use that action

- Remove the `Back to Launch Agents List` and `Back to List` actions since it's not how Raycast normaly does it, we're just using escape

- `Remove` functionality should add a confirmAlert since it just deletes it and the user might not know what they are doing - you can also add `style={Action.Style.Destructive}` to the Action

- Add icons to all `<Actions />`

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by stevensd2m** [comment]
Thanks for the review!

> * What does `Create Launch Agent` do? Nothing happens when I use that action

It creates a new plist file but I did not add a refresh when it happens.

> * Remove the `Back to Launch Agents List` and `Back to List` actions since it's not how Raycast normaly does it, we're just using escape

Roger that!

> * `Remove` functionality should add a confirmAlert since it just deletes it and the user might not know what they are doing - you can also add `style={Action.Style.Destructive}` to the Action

Agreed. Adding.

> * Add icons to all `<Actions />``

Will do.

**Comment by stevensd2m** [comment]
@pernielsentikaer I think I tackled all of the concerns you mentioned 🙏

**Comment by pernielsentikaer** [comment]
Thanks for the corrections 🙂

Another round of feedback that I stumbled upon:

- Does it make sense to be able to make a new launch agent directly from Raycast?

- When I try to load a Launch Agent which is not valid it gives me an error but the message says it's loaded

launch-agents 2024-08-09 at 13 13 52

I modified the code a bit since there was [Empty State Flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) and added hotkeys too, could you check it out

```typescript
import {
  Action,
  ActionPanel,
  Alert,
  Color,
  confirmAlert,
  Detail,
  Icon,
  Keyboard,
  List,
  showToast,
  Toast,
  useNavigation,
} from "@raycast/api";
import { execSync } from "child_process";
import { useEffect, useState } from "react";

const getRecurrence = (filePath: string) => {
  const plistContent = execSync(`cat ${filePath}`).toString();
  const intervalMatch = plistContent.match(/<key>StartInterval<\/key>\s*<integer>(\d+)<\/integer>/);

  if (intervalMatch) {
    const seconds = parseInt(intervalMatch[1]);
    if (seconds >= 3600) {
      const hours = (seconds / 3600).toFixed(2);
      return `Recurs every ${hours} hour${hours === "1.00" ? "" : "s"}`;
    }
    if (seconds >= 60) {
      const minutes = (seconds / 60).toFixed(2);
      return `Recurs every ${minutes} minute${minutes === "1.00" ? "" : "s"}`;
    }
    return `Recurs every ${seconds} second${seconds === 1 ? "" : "s"}`;
  }

  const calendarIntervalMatch = [...plistContent.matchAll(/<key>Weekday<\/key>\s*<integer>(\d)<\/integer>/g)];
  if (calendarIntervalMatch.length > 0) {
    const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
    const daysOfWeek = calendarIntervalMatch.map((match) => dayNames[parseInt(match[1])]);
    return `Recurs on weekdays: ${daysOfWeek.join(", ")}`;
  }

  return "No recurrence information";
};

const isPListOK = (filePath: string) => {
  try {
    return execSync(`plutil -lint ${filePath}`).toString().includes("OK");
  } catch {
    return false;
  }
};

const getFileName = (filepath: string) => filepath.split("/").pop();

function LaunchAgentDetails({ selectedFile, refreshList }: { selectedFile: string; refreshList: () => void }) {
  const { pop } = useNavigation();
  const [isFileLoaded, setIsFileLoaded] = useState<boolean>(false);

  const fileName = getFileName(selectedFile);
  const isFileValid = isPListOK(selectedFile);
  const recurrence = getRecurrence(selectedFile);

  const markdown = `
# ${fileName}

## Details

| Property                | Value                           |
|-------------------------|---------------------------------|
| Valid                   | ${isFileValid ? "✅" : "❌"}     |
| Loaded                  | ${isFileLoaded ? "✅" : "❌"}    |  
| Recurrence              | ${recurrence}                   |
| File Path               | ${selectedFile}                 |
`;

  const updateIsFileLoaded = () => {
    try {
      const output = execSync(`launchctl list | grep $(basename ${selectedFile} .plist)`);
      setIsFileLoaded(output.toString().trim() !== "");
    } catch {
      setIsFileLoaded(false);
    }
  };

  const confirmDeleteFile = async () => {
    await confirmAlert({
      title: "Confirm Deletion",
      message: `Are you sure you want to delete ${selectedFile}? This action cannot be undone.`,
      icon: { source: Icon.Trash, tintColor: Color.Red },
      primaryAction: {
        title: "Delete",
        style: Alert.ActionStyle.Destructive,
        onAction: deleteFile,
      },
      dismissAction: {
        title: "Cancel",
        style: Alert.ActionStyle.Cancel,
      },
    });
  };

  const deleteFile = () => {
    try {
      execSync(`rm ${selectedFile}`);
      showToast(Toast.Style.Success, "File Deleted", `${selectedFile} has been deleted.`);
      refreshList();
      pop();
    } catch (error) {
      console.error("Error deleting file:", error);
      showToast(Toast.Style.Failure, "Error", "Failed to delete the file.");
    }
  };

  const loadOrUnloadFile = () => {
    try {
      const action = isFileLoaded ? "unload" : "load";
      execSync(`launchctl ${action} ${selectedFile}`);
      updateIsFileLoaded();
      showToast(
        isFileLoaded ? Toast.Style.Success : Toast.Style.Failure,
        isFileLoaded ? "Unloaded" : "Loaded",
        `${selectedFile} has been ${isFileLoaded ? "unloaded" : "loaded"}.`,
      );
    } catch (error) {
      console.error(`Error ${isFileLoaded ? "unloading" : "loading"} file:`, error);
      showToast(Toast.Style.Failure, "Error", `Failed to ${isFileLoaded ? "unload" : "load"} the file.`);
    }
  };

  useEffect(() => {
    updateIsFileLoaded();
  }, [selectedFile]);

  return (
    <Detail
      markdown={markdown}
      actions={
        <ActionPanel>
          <Action
            icon={isFileLoaded ? Icon.Stop : Icon.Play}
            title={isFileLoaded ? "Unload" : "Load"}
            onAction={loadOrUnloadFile}
          />
          <Action icon={Icon.Folder} title="Open" onAction={() => execSync(`code ${selectedFile}`)} />
          <Action
            title="Remove"
            icon={Icon.Trash}
            shortcut={Keyboard.Shortcut.Common.Remove}
            style={Action.Style.Destructive}
            onAction={confirmDeleteFile}
          />
        </ActionPanel>
      }
    />
  );
}

const EmptyView = () => (
  <List.EmptyView
    icon={Icon.Multiply}
    title="No PList Launch Agents found"
    actions={
      <ActionPanel title="Manage Launch Agents">
        <Action
          icon={{ source: Icon.Circle, tintColor: Color.Red }}
          title="Create Launch Agent"
          onAction={() => {
            const fileName = `com.raycast.${Math.random()}`;
            execSync(`touch ~/Library/LaunchAgents/${fileName}.plist`);
          }}
        />
      </ActionPanel>
    }
  />
);

export default function Command() {
  const [plistFiles, setPlistFiles] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);

  const loadPlistFiles = () => {
    try {
      const plistOutput = execSync("ls ~/Library/LaunchAgents/*.plist").toString();
      const files = plistOutput.split("\n").filter((file) => file.trim() !== "");
      setPlistFiles(files);
    } catch (error) {
      console.error("Error fetching plist files:", error);
    }
  };

  useEffect(() => {
    loadPlistFiles();
    setIsLoading(false);
  }, []);

  return (
    <List navigationTitle="Search Launch Agents" searchBarPlaceholder="Search your Launch Agent" isLoading={isLoading}>
      <EmptyView />
      {plistFiles.map((file, index) => (
        <List.Item
          key={index}
          title={getFileName(file) || ""}
          icon={{ source: Icon.Rocket, tintColor: Color.Yellow }}
          actions={
            <ActionPanel>
              <Action.Push
                icon={{ source: Icon.Mouse, tintColor: Color.Green }}
                title="View Details"
                target={<LaunchAgentDetails selectedFile={file} refreshList={loadPlistFiles} />}
              />
              <Action
                icon={{ source: Icon.NewDocument, tintColor: Color.Green }}
                title="Create Launch Agent"
                onAction={() => {
                  const fileName = `com.raycast.${Math.random()}`;
                  execSync(`touch ~/Library/LaunchAgents/${fileName}.plist`);
                  loadPlistFiles();
                }}
              />
            </ActionPanel>
          }
        />
      ))}
    </List>
  );
}
```

**Comment by stevensd2m** [comment]
Thanks again for the review and updates suggested! 🙏 

> Does it make sense to be able to make a new launch agent directly from Raycast?

Added.

> When I try to load a Launch Agent which is not valid it gives me an error but the message says it's loaded

It is because the useState is asynchronous. That is why I have to check if `isFileCurrentlyLoaded`. There were some alternatives but not with the same behaviour I wanted. I can try to address it in a later MR refactor I was planning on doing, extracting the Details component and so on.

**Comment by stevensd2m** [comment]
indeed @pernielsentikaer

**Comment by stevensd2m** [comment]
not sure if it was clear but it is ready for new review (possible the final one? 😛 ) @pernielsentikaer 😃

**Comment by pernielsentikaer** [comment]
I just had a day off yesterday but I'll do it today 🙂

**Comment by stevensd2m** [comment]
No worries @pernielsentikaer ! 😄  vacations are important!

**Comment by pernielsentikaer** [comment]
Let's get the first version live and see how it goes 🙂

**Pull request merged**
