### PR TITLE
Add quick-journal extension

### PR DESCRIPTION
**Pull request by robotdestroy**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by robotdestroy** [comment]
Pretty excited about this extension. It's called 'Quick Journal'. With it you can open Raycast and quickly type out a journal entry. These entries are saved as Markdown files in a Quick Journal folder in your Documents folder, but you can also customize the location to be anywhere on your drive. You can view these entries from within Raycast, or open them in your preferred viewer/editor.

**Comment by robotdestroy** [comment]
A short video demo of the functionality.

https://github.com/raycast/extensions/assets/1692917/4cfecdf5-8b52-4b5e-a46b-8b23ca069126

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

Have you seen [SnapJot](https://www.raycast.com/k41531/snap-jot), it might be pretty similar to what you're building there, we also a some other notes/journal extensions in the store which might be be similar too 🙂

**Comment by robotdestroy** [comment]
Is your policy not to permit similar extensions in the store? While I see the similarity to SnapJot, I think this extension is novel in the fact that it is focused on the singular intention of being a journal.

**Pull request closed without merging**
