### PR TITLE
Add papago-translate extension

### PR DESCRIPTION
**Pull request by Rita-Mordio**
## Description

language translation using Papago, is an extension for Raycast.
English, Korean, and Japanese are supported
I'm planning to increase the translation language types later

## Screencast

screen-1
screen-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Maybe add the option to remove an item from the history

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Rita-Mordio** [comment]
@pernielsentikaer 

Hi, it was all a new experience for me

Thank you for allowing me to experience this and I appreciate you for correcting my code

**Comment by Rita-Mordio** [comment]
@pernielsentikaer 

I checked that you modified the README file, please let me know if there is anything I need to do 🤔

**Comment by Rita-Mordio** [comment]
@pernielsentikaer 

If the credentials are incorrect, they are not added to the list. Please check 😀

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
