### PR TITLE
Add extension to Bamboo Search (Self Hosted)

### PR DESCRIPTION
**Pull request by axp-dev**
## Description
This [Raycast](https://raycast.com) extension lets you quickly find Bamboo (Self Hosted) projects, deploys and plans.

Features:
- Find projects by title.
- Find deploys by title.
- Find plans by title.

## Screencast
bamboo-self-hosted-1
bamboo-self-hosted-2
bamboo-self-hosted-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by axp-dev** [comment]
@pernielsentikaer PR will close soon. You can check it out?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @axp-dev 👋 

Did you use [our tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#how-to-use-it) to take the metadata images? The padding seems to be wrong, can you verify and maybe take some new if possible?

I can also help, let me know 😊

**Comment by axp-dev** [comment]
@pernielsentikaer I did not see that there are requirements for the background image. I'll fix it tomorrow

**Comment by axp-dev** [comment]
Hi @pernielsentikaer corrected your comments

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
