### PR TITLE
Update claude extension

### PR DESCRIPTION
**Pull request by gcordalis**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by FelixLisczyk** [comment]
Thank you for your PR! Could you please add ⁠`claude-3-5-haiku-latest` as another model option, similar to what was done in #15057?

https://docs.anthropic.com/en/docs/about-claude/models

**Comment by gcordalis** [comment]
@FelixLisczyk yep done - they hadn't published latest when I opened the PR

**Comment by FelixLisczyk** [comment]
Looks good to me! 👍

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
