### PR TITLE
Add universal-inbox extension

### PR DESCRIPTION
**Pull request by dax**
## Description

This is an extension to connect to [Universal Inbox](https://www.universal-inbox.com) and manage notifications from Raycast.
Universal Inbox is an application to centralize notifications from many different third parties (Github, Linear, Google Mail, Todoist for now) and handle them:
- delete the notification
- unsubscribe from the notification
- snooze the notification
- turn the notification into a (Todoist) task
- link with an existing (Todoist) task

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Add icons to all [Action Panel items](https://developers.raycast.com/basics/prepare-an-extension-for-store#action-panel)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Thanks for the corrections, could you look into the [CI error](https://github.com/raycast/extensions/actions/runs/7785221346/job/21227301818?pr=10492)

**Comment by dax** [comment]
> Thanks for the corrections, could you look into the [CI error](https://github.com/raycast/extensions/actions/runs/7785221346/job/21227301818?pr=10492)

Ooops, sorry 🙈 This is now fixed 👍

**Review by pernielsentikaer — APPROVED** [review]
✅ Approved, let's get the first version released 🙂

**Pull request merged**
