### PR TITLE
[New Extension] chatgpt3 prompts add

### PR DESCRIPTION
**Pull request by denizyoldas**
## Description

ChatGPT3 prompts

[awesome-chatgpt-prompts](https://github.com/f/awesome-chatgpt-prompts)

## Screencast

Screenshot 2023-02-04 at 11 49 36

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @denizyoldas 👋 

I changed a bit in the code and added new stuff. Do you mind rechecking it to ensure I didn't break something 😊

**Comment by denizyoldas** [comment]
Hello 

I'll check again, thanks for the update

**Comment by denizyoldas** [comment]
Hi @pernielsentikaer 😊

I have conducted a thorough inspection and no issues were observed. Kudos to you

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
