### PR TITLE
Add Vault Extension

### PR DESCRIPTION
**Pull request by ricoberger**
## Description

This PR adds an new extension for [Vault](https://www.vaultproject.io), which allows users to navigate through all the secrets of a KV2 engine and copy or show the values of all keys of the selected secret.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/18552168/139947842-6bf54f1e-1115-4383-9d97-f1757dc2135f.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ricoberger  👋 

Thanks for your contribution, I never tried Vault myself before today and it feels a bit overwhelming - since we now have support for README.md when installing the extension I think that you should make one explaining what Vault is and how to get started 

Should there be more of the error message? They all give me this

v7EpkdUy0VUp9kUU

I got a secret added and it seems to work fine 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by ricoberger** [comment]
Hi @pernielsentikaer, I added a readme file with a short description and some instructions for development / testing.

I also fixed the error message, which now includes the correct response from Vault.

Please let me know if other changes are required.

**Comment by es183923** [comment]
Suggestion: use icons to help show whether an item is a folder or an actual item.

**Comment by ricoberger** [comment]
> Suggestion: use icons to help show whether an item is a folder or an actual item.

Hi @es183923, nice idea. I added some icons for secret engine / path / secret / secret keys.

I'm not sure about which icons to use, so please feel free to make some suggestions.

**Comment by pernielsentikaer** [comment]
Wrong PR, lets get the icons added before closing :)

**Comment by pernielsentikaer** [comment]
hi @ricoberger 👋 

Yeah, it's a tough one, cobbyhole gives one error message

vyjyDuo5xdgq99dC

And identity and sys gives another 
OOIwsgnAkWqoUGp1

I guess it's pretty hard to make something that's also useful - I'm not sure if something could be improved or its the best we get

**Comment by ricoberger** [comment]
> hi @ricoberger 👋
> 
> Yeah, it's a tough one, cobbyhole gives one error message
> 
> vyjyDuo5xdgq99dC
> 
> And identity and sys gives another OOIwsgnAkWqoUGp1
> 
> I guess it's pretty hard to make something that's also useful - I'm not sure if something could be improved or its the best we get

@pernielsentikaer I slightly adjusted the error handling, but I think thats the best we can get out of it.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ricoberger 👋 

It's a lot better now, I don't think there is more to do about it. The last thing could be to remove console.* as they will never be seen - after this I think we're ready to merge it 😄

**Comment by ricoberger** [comment]
> Hi @ricoberger 👋
> 
> It's a lot better now, I don't think there is more to do about it. The last thing could be to remove console.* as they will never be seen - after this I think we're ready to merge it 😄

Hi @pernielsentikaer, thanks for the hint 🙂. The console.* statements are removed now.

**Comment by pernielsentikaer** [comment]
Awesome @ricoberger 💪 

Let's get it merged 💯 

Thanks for your contribution 🥇

**Pull request merged**
