### PR TITLE
New extension: Mochi

### PR DESCRIPTION
**Pull request by kawamataryo**
## Description

Quickly create [Mochi](https://mochi.cards/) cards

## Screencast

https://user-images.githubusercontent.com/11070996/213101113-0b51650c-c1b0-4ead-b893-1c96ebc462f4.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* When wrong credentials are entered, it always keeps the loading indicator. Could you stop that and return an empty array so we can use the [List? EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) for a custom error message?

https://user-images.githubusercontent.com/38033107/213373110-984359e6-400f-4055-9c19-0bce009a8c08.mp4

* Add validation so the user can't submit empty fields; you can use [useForm](https://developers.raycast.com/utilities/react-hooks/useform)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by kawamataryo** [comment]
Thank you for your review.
I'll fix your suggestion.

**Comment by kawamataryo** [comment]
@pernielsentikaer 

Hi, I have added an error message view. This view is displayed when an API Error occurs.

image

> Add validation so the user can't submit empty fields; you can use [useForm](https://developers.raycast.com/utilities/react-hooks/useform)

Sorry, I can't suggest the above. because this extension's form field is created dynamically. 
So I can't know the required field in advance.

**Review by pernielsentikaer — APPROVED** [review]

**Comment by pernielsentikaer** [comment]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
