### PR TITLE
Add Resmo Extension

### PR DESCRIPTION
**Pull request by ozgunarslantas**
## Description

This is a new extension that lists resources in your [Resmo](https://www.resmo.com) account. You can search within your resources, check their details, and go to the related resource page in the Resmo UI.

## Screencast

resmo-metadata0
resmo-metadata1
resmo-metadata2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @ozgunarslantas 👋 

Could you please tick this setting, I have a few suggestions I want to apply 😊

image

**Comment by ozgunarslantas** [comment]
Hi @pernielsentikaer 👋🏻 

I cannot seem to find the checkbox unfortunately, I'll tick it as soon as I find it.

**Comment by pernielsentikaer** [comment]
Strange, it should be somewhere around on this page, also after it's opened 😊

**Comment by pernielsentikaer** [comment]
@ozgunarslantas maybe some hints here https://github.blog/2016-09-07-improving-collaboration-with-forks/

**Comment by ozgunarslantas** [comment]
This is in an organizational repository, that's why the checkbox doesn't appear I guess. But I've been told that you are granted access to the repository now @pernielsentikaer , can you please check if you can do what you wanted to do?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

You can also change the assets if you want, but I added fallback images if the source somehow is not available.

Setting up the extension was easy, I didn't check the README or anything, well done 😊 

You could set the type = password for the API key, just to be sure

I tried to search but it seems like the items on the list are something else? not completely sure what I'm looking at 😊
https://user-images.githubusercontent.com/38033107/205063570-9ce3cbde-2143-4788-98f4-c2e3d5d3fbd4.mp4

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by ozgunarslantas** [comment]
@pernielsentikaer Hi again 👋🏻

We are using a weighted search algorithm that returns the elements with scores above a certain threshold. I guess in your case, searching for `r` or `t` have resulted in elements with scores below this threshold. You can populate your resources with sample data if you add the `Demo Data` from `Add Integration` page within `Settings`. However, this might still not guarantee having results for single letter search queries.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
