### PR TITLE
Add codesnipper extension

### PR DESCRIPTION
**Pull request by omit2c**
## Description

This extension can be used to copy code snippets from CodeSnipper. CodeSnipper is a macOS App (only M1 currently) to store and manage code snippets locally. With this extension you can copy snippets, view their code and their explanation. 

CodeSnipper isn't available on the AppStore right now, it is currently in beta: https://testflight.apple.com/join/VgduAP3J

You can also create new snippets with this extension.

Please be aware that it might take some time for the extension to show new snippets your created, as this relies on the private database of the app which gets updated automatically from time to time by some background jobs.

## Screencast

https://github.com/raycast/extensions/assets/67875249/4ee7c516-da12-46de-96d5-31d81d03a12d

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I tried joining TestFlight, but I don't feel secure by disabling this. Is that the only way to get it? I have joined a lot of TestFlight apps in the past and never saw that one.

Raycast-leV4ryxT@2x

**Comment by omit2c** [comment]
Hi @pernielsentikaer,

that is a strange alert, I have never seen this before. I created a new TestFlight group and a new build for you to join: https://testflight.apple.com/join/BUGzZQbC. Maybe this will work.

Kind regards,
Timo

**Comment by pernielsentikaer** [comment]
I still have the same error. That's so strange!

I just tested three other TestFlight applications, and none of them exhibit this issue. 🫠

**Comment by omit2c** [comment]
I will contact the Apple App Store Support and ask for advice. Maybe they have an answer. For now I will draft this pull request. Thanks for your time :)

**Pull request closed without merging**
