### PR TITLE
Add mindnode extension

### PR DESCRIPTION
**Pull request by natsustan**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Remove use-applescript since it's not used

- Take a [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension with the built-in tool

- Check the [CI errors](https://github.com/raycast/extensions/actions/runs/8200301753/job/22426809493?pr=11169)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by natsustan** [comment]
Hey, I have already fixed questions you told. 
Please check it again. Thank you.

**Comment by pernielsentikaer** [comment]
One last thing that would really make the UX a lot better would be to include an installation check like it's done in the [Eagle extension](https://www.raycast.com/Yukai/eagle)

**Comment by natsustan** [comment]
Hi, the newly publish is the installation check. Please check it.
Thanks for teaching me the basics of what a Raycast Extension should need.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
