### PR TITLE
Pocket extension

### PR DESCRIPTION
**Pull request by vimtor**
## Description

Extension of searching and managing [Pocket](https://getpocket.com/) bookmarks

## Screencast

https://user-images.githubusercontent.com/36263538/153724235-c230169d-4fae-4a71-916a-74b065f3ecd0.mp4

https://user-images.githubusercontent.com/36263538/153724246-aa4178bd-3564-467c-96d0-1d59c9fc1eb7.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by mattisssa** [comment]
Hey! @vimtor 
I see that you've implemented the OAuth in your extension.
1) I know that it can look easy to do the auth flow for end-users, but I am not sure it will be for non-developers users.
2) I'm also not sure that this is fully secure for end-users to do the manual OAuth
3) Small spoiler, but we are actually working on the OAuth flow API, I don't have specific dates but first version of it will be available in Q1. So, I would actually propose to wait until we do that and stick with another authorisation for now, like personal tokens.

What do you think?

**Comment by pernielsentikaer** [comment]
Hi @vimtor 👋 

Thanks for your contribution, I have some feedback for you 💯 

Even though we might need to wait for proper OAuth, I have some feedback you can address while waiting 😄 

When wrong credentials added, then I get unexpected responses:

- Search Bookmarks: I think it should show a failure toast telling something is wrong, right now it just shows “No Result”.

- Random Bookmarks: Dying pretty hard, as above, dying gracefully with toast instead

D1qCKhRQGIHsc00Y

When opening the extension and using the `Search Bookmarks`, it looks like it fetches all items, is there a reason to search on input instead of just filtering?

**Comment by vimtor** [comment]
Awesome! I will wait for OAuth to be implemented. I would also love to wait for the top right select (like the one used in GitHub "My Pull Requests") so users can filter bookmarks by archived, not archived and tags.

Meanwhile I will implement the things you mentioned @pernielsentikaer

**Comment by mattisssa** [comment]
Hey! We've just discussed this internally and realised that the OAuth API won't solve this case because Pocket doesn't support PKCE. And Pocket doesn't support personal tokens either, that's why you have to do a weird auth like this. 
Well, since there is no any alternatives at the moment, I'd say it's a tradeoff we can accept 😉

**Comment by vimtor** [comment]
I've improved the error handling and made Prettier happy

**Comment by vimtor** [comment]
Also, I made use of Raycast built-in search

**Comment by pernielsentikaer** [comment]
Awesome work @vimtor 💪 

One suggestion (for next version) could be to make a command, so it's possible to add bookmarks directly, is that possible?

Would it be something you want to look into in next version, or in this? :)

**Comment by vimtor** [comment]
> Awesome work @vimtor 💪 
> 
> 
> 
> One suggestion (for next version) could be to make a command, so it's possible to add bookmarks directly, is that possible?
> 
> 
> 
> Would it be something you want to look into in next version, or in this? :)

Since Pocket already has browser extensions I would prefer to wait for people asking this feature so we don't delay the release.

On this note, it will be cool if users could leave specific feedback on the extension website (e.g. https://www.raycast.com/vimtor/whatsapp). Here users could add and upvote other users suggestions.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @vimtor 👋 

I found a last thing before we're ready to proceed, can you look into this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Review by pernielsentikaer — APPROVED** [review]
Awesome @vimtor 💪 

Thanks for your contribution ⭐ 

It works very nice, I can't find anything else that I would like to have changed, let's await final review 😏

**Comment by sxn** [comment]
hi @vimtor! Thanks for the work!

One request: would you mind moving the `tutorial` folder from `assets` to a new `media` folder in the root of the extension? Everything in the `assets` folder gets bundled with the extension when users install it, and the `tutorial` is only necessary for the README (which isn't included with the extension). 😸

**Comment by sxn** [comment]
🎉

**Pull request merged**
