### PR TITLE
Added grid support, pinned items, and filtering items

### PR DESCRIPTION
**Pull request by yug2005**
## Description

Added some features to the Visual Studio Code Recent Projects extension that I think will be helpful to everyone. 

* You can filter by the type of the item (files, folders...)
* When showing all items, items are ordered only based on how recent they are, not their type
* Support for optional grid view
* You can choose to pin items 
* New icon for remote folders

## Screencast

visual-studio-code 2022-12-06 at 14 52 34

visual-studio-code 2022-12-06 at 14 53 33

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by yug2005** [comment]
Not sure what is wrong with PR Bot

**Comment by pernielsentikaer** [comment]
We had an error one day, and rerunning the job catches the old configuration; it should be better now @yug2005 🔥

**Comment by macbookandrew** [comment]
I love it!

One note: for some reason, the workspaces have a 1Password icon for me, rather than a VS Code icon:

Screenshot 2022-12-12 at 09 50 28

I have that file type set to open with VS Code, so I’m not quite sure what’s causing the mismatch.

@yug2005 what does a workspace entry look like for you?

**Comment by pernielsentikaer** [comment]
That's correct; it's a bug in the API somehow, even though we rely on Apple's API - I created a ticket internally to check this, but I don't think it should stall this since it's already broken now.

**Comment by pernielsentikaer** [comment]
@yug2005 do you think it makes sense to remove the entry from Recents if it's pinned?

Raycast-PBlm1bGq@2x

**Comment by yug2005** [comment]
> @yug2005 do you think it makes sense to remove the entry from Recents if it's pinned?

Yeah I think that makes sense. I will add that if you guys agree as well?

**Comment by macbookandrew** [comment]
Sounds good to me 👍🏻

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
