### PR TITLE
Update pdfsearch extension

### PR DESCRIPTION
**Pull request by kevin-pek**
## Description

- Resolve issue #10269 where deleting collections causes an error.
- Improve file picker validation logic.
- Edit package description.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @kevin-pek 👋 

It seems like your pushing everything again, could you try to only push the new changes?

**Comment by kevin-pek** [comment]
@pernielsentikaer understood, is there a way i can remove the past commits from the history of this pull request?

**Comment by pernielsentikaer** [comment]
If you're good with `git` you can do a interactive rebase, but I'm not.

 I would: 
  * Save the few files you changed
  * Delete your local version of the extension
  * Download pdfsearch from the store
  * Use the action Fork extension
  * Add your changes
  * Use the provided publish function from `package.json`

**Comment by kevin-pek** [comment]
Okay, I have rebased the branch.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by thomaslombart** [comment]
Hey @kevin-pek, note that you can use our Swift integration into TypeScript, which makes it easier for you to use Swift functions in your extension. You can see the documentation here: https://github.com/raycast/extensions-swift-tools. Let me know if you have any questions! 😊

**Comment by kevin-pek** [comment]
Hi @thomaslombart, was trying out the integration. My typescript language server can't seem to detect the functions I marked with @raycast in my Swift code. Will I have to import them from somewhere?

**Comment by thomaslombart** [comment]
Yes, you have to import the functions in TypeScript. Take a look at [this example](https://github.com/raycast/extensions-swift-sample) to see how it's been done.

**Pull request merged**
