### PR TITLE
Update Apple Notes extension

### PR DESCRIPTION
**Pull request by jordanamblin**
## Description

Capture selected text and create a new note in Apple Notes with a new `Quick Capture` command.

## Screencast

https://github.com/raycast/extensions/assets/3781309/d98f0e84-fef5-4995-b0c4-227386521af0

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by maximilianzuern** [comment]
Awesome idea!
How about including an optional [argument](https://developers.raycast.com/information/lifecycle/arguments) that allows users to define a title for the new note? This would make it easier for users to organize and locate their notes later on.

At the moment, I use a script command to achieve this, using an \<h1\> tag since Apple Notes uses HTML markup.

image

image


```
#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Quick Capture
# @raycast.mode silent

# Optional parameters:
# @raycast.icon ./images/notes.png
# @raycast.argument1 { "type": "text", "placeholder": "Title", "optional": true}
# @raycast.packageName Notes

on run argv
	set content to "
	<body>
	<h1> " & (item 1 of argv) & "</h1> 
	<p>" & (the clipboard as Unicode text) & "</p>
	</body>"
	tell application "Notes"
		activate
		set newNote to make new note at folder "Notes"
		set body of newNote to content
	end tell
end run
```

**Comment by thomaslombart** [comment]
@jordanamblin It looks good to me! Let me know if you want to work on Maximilian's suggestion 🙂

**Comment by thomaslombart** [comment]
@jordanamblin @maximilianzuern FYI, I added the text selection feature as part of the existing command to avoid having another command with similar features. I did not implement any HTML markup, so we can maybe ship these improvements as part of this PR?

**Comment by thomaslombart** [comment]
Closing due to the updates included in  #11596.

**Pull request closed without merging**
