### PR TITLE
Tailscale - expand description with more details

### PR DESCRIPTION
**Pull request by tommorris**
## Description

Improves the description to make it clearer to potential users what functionality it offers.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

(latter three are not applicable for such a small change)

### CODE REVIEW

**Comment by j3lte** [comment]
This is the most minimalist of 'updates'. Users typically search for it in the [Store](https://www.raycast.com/tailscale/tailscale) and will see the commands right away, so I'm not sure this is a real update...

**Comment by tommorris** [comment]
I submitted it precisely because I was confused by the mismatch between the description I read on the store page and the functionality offered.

I appreciate the effort and hard work that has gone into building the extension, and simply wished to make the store listing reflect the functionality offered to help others know whether to install it.

**Comment by pernielsentikaer** [comment]
You're right @j3lte. I think in this case, we'll merge it. However, you need to add a changelog entry, @tommorris

**Comment by tommorris** [comment]
Hoping that posting a comment will unstale this. I've updated the CHANGELOG as requested.

**Comment by j3lte** [comment]
> Hoping that posting a comment will unstale this. I've updated the CHANGELOG as requested.

@tommorris that doesn't show up here, have you pushed the changes? (`ray publish`)

**Comment by tommorris** [comment]
@j3lte I rebased and pushed the commit [0a44029f355241aca9db2c38da9e53c6f1d47c18](https://github.com/tommorris/raycast-extensions/commit/0a44029f355241aca9db2c38da9e53c6f1d47c18) to my fork. But because the PR has been closed as stale, GitHub won't pick up the change in the PR. And I can't reopen the PR.

If you reopen the issue, hopefully it should get picked up.

**Pull request closed without merging**
