### PR TITLE
Add new extension:WeChat and update some extension icons

### PR DESCRIPTION
**Pull request by RaffeYang**
## Description

A Raycast extension for WeChat to quickly search your contacts and chat.
cover
showcase

## Screencast

https://user-images.githubusercontent.com/7557357/206844029-5308a738-38e9-4a54-963e-13bb84e6f601.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
@raffeyang wow that's a lot of commits :-) Could we separate this into two PRs? One for the icons and one for the new extension?

**Comment by mathieudutour** [comment]
it might even be better to create a PR per icon change, some of them are different enough that the extension author might not agree with it

**Comment by thomaspaulmann** [comment]
Good point @mathieudutour. Let's split it further.

**Comment by raffeyang** [comment]
> @raffeyang wow that's a lot of commits :-) Could we separate this into two PRs? One for the icons and one for the new extension?

Yes,please

**Comment by pernielsentikaer** [comment]
I'll await that @raffeyang 😊

**Pull request closed without merging**
