### PR TITLE
Add addy extension

### PR DESCRIPTION
**Pull request by mormubis**
## Description
AnonAddy has been rebranded to Addy. This PR updates the company name and API endpoints to their new site.

Additionally, new icons have been added to it.

This PR refactors the old `anonaddy` extension and fixes the issue with the default domain when creating an alias.

## Screencast

Screenshot 2023-12-03 at 4 16 56 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by httpjamesm** [comment]
Looks good

**Comment by mormubis** [comment]
> Hi @mormubis 👋
> 
> It would be better to move the original extension instead of creating a new one, if you move it you'll also move all the extension users - does it make sense? (I don't think you can do it with Fork extension alone)

Hey @pernielsentikaer 

Thanks for the answer. That's what I tried but when I renamed the extension it automatically created a "new" extension.

Can you explain me a bit how to rename extensions?

**Comment by pernielsentikaer** [comment]
if @httpjamesm is okay with it, then you just replace your files in the folder, that was it's just an update 🙂

**Comment by mormubis** [comment]
Closing this PR in favor of https://github.com/raycast/extensions/pull/9621

**Pull request closed without merging**
