### PR TITLE
Add invitation-app extension

### PR DESCRIPTION
**Pull request by iplanwebsites**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I tried to copy H&M's suggestion, but the extension crashes. Can you handle that carefully?

invitation-app 2024-11-19 at 12 26 54

- When is the history showed? coulnd't see it

- You can add `style={Action.Style.Destructive}` to destructive commands

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Are you still working on this?

**Comment by iplanwebsites** [comment]
Similarly to the issue I had with the touchdesigner extension I figured I'd
wait to solve everything in the simpler extension first. Really hoping to
finish this one here as I believe it adds more value.

**Comment by pernielsentikaer** [comment]
It Seems like you have a lot of errors here, are you able to [check them](https://github.com/raycast/extensions/actions/runs/11914465343/job/33202450094?pr=15357)?

**Pull request closed without merging**
