### PR TITLE
Markdown Blog Manager 1.0

### PR DESCRIPTION
**Pull request by pyronaur**
## Description

Adding a Raycast extension to manage markdown file based blogs. 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pyronaur** [comment]
Whoa, thanks for reviewing, I've been using the extension for some time now and never ran into any of these issues. Glad to have someone else take a peek at it before it goes live 🙂

I'll have a look and get back to you with updates as soon as I can 👍

**Comment by pernielsentikaer** [comment]
Awesome 📿

It happens to me all the time when developing, sometimes the best thing to do is to uninstall and start fresh since we always code for happy flows 😊

I'm looking forward to testing this extension again 🔥

**Comment by pyronaur** [comment]
> You should consider using placeholders instead since it looks like this every time I enter the command

Done, I've switched the title to placeholder now

> Consider using useForm instead, for better handling of the forms (and validation) - it's also possible to make a new post without a title.

The documentation seemed a bit incomplete at first, which is why I didn't pay much attention to `useForm` at first. Switched to `useForm` now and......its soooo much easier to handle forms that way 🤯


> There is no folder path for public in the package.json file, shouldn't there be that?

Variable names throughout iterations got funky. Renamed, should be consistent now.


> How does Category work, couldn't figure that out in the README

I've renamed "Category" to "Subdirectory". I use sub-directories as categories, but not everyone might want to do that. They are mentioned in the readme, so hopefully renaming made that clearer, but if it doesn't - I'll welcome any feedback that you may have on how to clarify further.

> There is something funny going on when changing the title
> https://user-images.githubusercontent.com/38033107/197706487-587933eb-6970-42ec-bd87-507123ce5d87.mp4

That was really funky. Looks like the issue went away now that I'm using `useForm`.

**Comment by pernielsentikaer** [comment]
Do you think it could be an idea to auto-create the folders (draft/public) if they don't exist or at least handle the error telling the user to create the directories 😊

**Comment by pyronaur** [comment]
I really wish there was a "Raycast way" of handling that workflow. A lot can go wrong, like if I attempt to create a directory that doesn't exist, but the specified path was wrong by one character at the start of the string, that would create a long invalid path of directories.

But for now - I think you're right, some sort of error should be surfaced and the setting unset if the specified path is invalid.

**Comment by pernielsentikaer** [comment]
Then maybe just check if the path exist and an error telling that the user has to create it instead?

**Comment by pyronaur** [comment]
Sounds good 👍

**Comment by pyronaur** [comment]
Hi @pernielsentikaer,
I've wrapped both commands in a helper that checks if the paths are valid, and if they aren't - it'll show a somewhat user-friendly error message:
Raycast-1

It's not looking as pretty as I'd want it to be, but I guess that's a limitation in Raycast for now. Or is there a better way?

**Comment by pernielsentikaer** [comment]
Hi @pyronaur 👋 

It's much better now, could you look into this [linter error](https://github.com/raycast/extensions/actions/runs/3369152768/jobs/5588480068), maybe one of the old files still exists?

**Comment by pyronaur** [comment]
Oooh. I'm using rsync without `--delete` to sync my own repository with raycast extensions. I need to update my workflow 😅

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pyronaur** [comment]
🎉🎉🎉 
Thank you @pernielsentikaer for patiently walking through the code review with me. Truly appreciate it 👍

**Pull request merged**
