### PR TITLE
Add olympic-games extension

### PR DESCRIPTION
**Pull request by elonwoo**
## Description

an extension to show Paris 2024 Olympic Medal Table

## Screencast

olympic-games-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by elonwoo** [comment]
> ## Description
an extension to show Paris 2024 Olympic Medal Table

> ## Screencast
olympic-games-2

> ## Checklist
>  [*]  I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
>  [*]  I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
>  [*]  I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
>  [*]  I checked that files in the `assets` folder are used by the extension itself
>  [*]  I checked that assets used by the `README` are placed outside of the `metadata` folder

**Comment by koinzhang** [comment]
Hi @elonwoo @pernielsentikaer 
I have a question about this type of extension, is this a temporary extension? After the Paris Olympics, it doesn't seem to make much sense for this extension to be around.
Similar extensions are [FIFA World Cup Qatar 2022™](https://www.raycast.com/isma/world-cup)

**Comment by elonwoo** [comment]
> Hi @elonwoo @pernielsentikaer I have a question about this type of extension, is this a temporary extension? After the Paris Olympics, it doesn't seem to make much sense for this extension to be around. Similar extensions are [FIFA World Cup Qatar 2022™](https://www.raycast.com/isma/world-cup)

I will modify the extension later. I will add "Custom filtering" to query the medal tables of previous Olympic Games.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Sounds like a little nice extension 🔥

- For me it feels a bit weird with the `padStart` when showing the medals, what do you think?

- I would put ranking last (and maybe put total medals as tooltip for ranking?

- Would it be possible to use https://flagpedia.net/download/api as CDN for flags?

**Comment by elonwoo** [comment]
> Sounds like a little nice extension 🔥
> 
> I gave the extension a spin and got some feedback for you 🙂
> 


> * For me it feels a bit weird with the `padStart` when showing the medals, what do you think?

https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1722972856617799

I tried to discuss this issue in slack. Because Accessory cannot be left-aligned, I tried to add some extra spaces to make them as left-aligned as possible.


> * I would put ranking last (and maybe put total medals as tooltip for ranking?

It's OK.

> * Would it be possible to use https://flagpedia.net/download/api as CDN for flags?

I have tried to use the flag API to access the flag icon. But I encountered two problems.

Problem one: I think every time this extension is loaded, the extension will make dozens of requests, and each country's flag must request a flag icon. Although using the API will be more elegant, too many requests may cause trouble to users.

Problem two: In the Olympic Games, some teams cannot participate as countries or regions, but can only participate as regional Olympic committees. Their representative flags cannot be requested in the regular flag API. Of course, I can also use the flag API for most requests, and a few special teams use local images separately, but this will encounter another problem, the style of the flag image cannot be unified.

@pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by acpplife** [comment]
It feels pretty good after trying it, very convenient to use.❤️❤️

**Comment by Arrows78** [comment]
Working well, thanks for the app! 💪

**Pull request merged**
