### PR TITLE
[Google Maps Search] Travel mode fixes and improvements

### PR DESCRIPTION
**Pull request by klaussner**
## Description

This PR reverts a change from a [previous PR](https://github.com/raycast/extensions/pull/13885), where the travel mode values were changed, e.g., from `bicycling` to `b`. I'm not sure why this change was made, but the values that are currently used are not accepted by Google Maps. Therefore, the search defaults to the "Best travel modes" option instead of using the one selected in the extension.

I also renamed "Walk" to "Walking" in the travel mode dropdown to make it consistent with the other options and the Google Maps UI.

### CODE REVIEW

**Comment by chrismessina** [comment]
@klaussner thanks for jumping in with these improvements. 

I was inspired by CityMapper's action labels since Google Maps doesn't really have quick action buttons:

IMG_7CE16AAA737F-1

"Travel Home" and "Travel To" are fine, but that's where those labels came from.

LGTM.

**Comment by klaussner** [comment]
Thanks, @chrismessina. Just to clarify, I didn't revert the command names, but the internal travel mode values that are stored in the extension preferences and passed to Google Maps. 🙂

**Comment by chrismessina** [comment]
> Thanks, @chrismessina. Just to clarify, I didn't revert the command names, but the internal travel mode values that are stored in the extension preferences and passed to Google Maps. 🙂

Oh! I see that now. I misinterpreted the edits to README.

All good! :)

**Comment by ratoru** [comment]
Thank you @klaussner for catching the mistake! I somehow missed it when reviewing the last changes.
LGTM!

**Pull request merged**
