### PR TITLE
Add auto-work extension

### PR DESCRIPTION
**Pull request by weitanai**
## Screencast
summary

improve

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋 

Thanks for your contribution 🔥 

We do already have a lot of [GPT extensions](https://www.raycast.com/search?q=openai) in the store which also cover what this does (I think)

Could you check them out, it's also possible to enhance the current store versions

**Comment by weitanai** [comment]
what did I do
Provide a better product experience
Find the balance between the minimum key value and the cache hit rate

**Comment by pernielsentikaer** [comment]
You didn't do anything wrong, we're just trying to limit extension that does almost the same, there a few more that does nearly the same as this on [this list](https://www.raycast.com/search?q=chatgpt) too 🙂

**Comment by weitanai** [comment]
I hope that my project can help others, and I am also recommending my classmates to use the extension I developed, which is of great significance for me to continue to study computer science

**Comment by pernielsentikaer** [comment]
It would still be better to enhance one of the current ones, like the one @alanzchen made (https://www.raycast.com/alanzchen/chatgpt-quick-actions)

What do you think @alanzchen, could this be a good idea to add?

**Comment by alanzchen** [comment]
Yeah i'd well come any PR that improves the performance of the extension.

I'm not sure if I'm missing something, but it seems both extension is targeted towards one-off actions that are not likely to be repeated again in the future. So I'm not sure how caching would be useful.

**Comment by weitanai** [comment]
> Yeah i'd well come any PR that improves the performance of the extension.
> 
> I'm not sure if I'm missing something, but it seems both extension is targeted towards one-off actions that are not likely to be repeated again in the future. So I'm not sure how caching would be useful.

In my own use case
Sometimes: I have already summarized an article, but something happened temporarily, and this operation was interrupted, so I did not copy the good results. If there is no cache, I rewrite and summarize an article. Here, the waiting time is related to the repeated consumption of tokens.

**Comment by pernielsentikaer** [comment]
I guess a simple "History" command would do the same, right?

**Comment by weitanai** [comment]
> I guess a simple "History" command would do the same, right?

Yep，

Sometimes, Users don't want to search in the history, they want  straight forward   interaction

**Comment by pernielsentikaer** [comment]
Besides that one feature it doesn't look like there are any differences between them 😞 I would still say that it would be better to enhance the current if it makes sense instead of having two identical extensions since it will confuse the end user

**Pull request closed without merging**
