### PR TITLE
Emoji Grid

### PR DESCRIPTION
**Pull request by jokull**
## Description

Another twist on an emoji picker. This one has a setting for skin tones. It also includes an up to date database with things like 🫡.

This doesn't bring enough new features to replace the native emoji picker. However the newest emojis are not yet available in the modern picker so maybe someone finds this useful.

## Screencast

https://user-images.githubusercontent.com/701/173639460-461b2987-4ebd-47af-ad45-e1d050205cfa.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Hi @jokull.
> This one has a setting for skin tones.

The built-in Search Emoji also allows you to choose the skin color, just set it in Preferences - Advanced

> It also includes an up to date database with things like 🫡

For the lack of new emoji emoji, is the best way to suggest to the official to add new emoji instead of making an extension with such duplicate functions?

image

**Comment by jokull** [comment]
I agree, ideally Raycast just keeps the emoji database up to date. I suggested this on twitter, and @thomaspaulmann encouraged me to write an extension and submit it. This is after I suggested updating the emojis on Twitter mentioning the official Raycast account. I am happy to close this PR and/or put up a GitHub issue instead.

**Comment by koinzhang** [comment]
Hi @jokull. If it's @thomaspaulmann suggestion, I think this extension is fine, although maybe his suggestion implies that the official Search Emoji extension won't be updated with new emojis anymore.

**Comment by thomaspaulmann** [comment]
Just to clarify, we'll update the official extension with the new emojis. We just didn't get around to it yet. Given that we have already an [emoji search in the store](https://www.raycast.com/FezVrasta/emoji), would it make sense to contribute your changes to that one @jokull? Otherwise it might be hard for end users to know which extension they should install.

**Comment by jokull** [comment]
I'll close this for now. Sorry for the confusion.

**Pull request closed without merging**
