### PR TITLE
[Linear]: Make use of `autoFocus` prop in Sub Actions

### PR DESCRIPTION
**Pull request by peduarte**
## Description

This PR makes use of the new `autoFocus` prop on `Action` Items. [Docs here.](https://developers.raycast.com/api-reference/user-interface/actions#props)

## Screencast

Notice that in this demo, when I select "Set Status…", the current status item is auto focused ✨ 

https://user-images.githubusercontent.com/372831/201091483-62ae4292-3b54-40c2-85d4-66a5c3a7a7e1.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mathieudutour — COMMENTED** [review]
We are using npm on the CI. Could you remove the yarn.lock and update the package-lock instead?

**Comment by peduarte** [comment]
@mathieudutour yep, just noticed and removed.

**Comment by thomaspaulmann** [comment]
Very nice addition that makes it more intuitive to use the action panel submenus, ship it 👏

**Comment by peduarte** [comment]
🚀

**Review by mathieudutour — APPROVED** [review]
🎉

**Pull request merged**
