### PR TITLE
[Easydict] ✨ Add support for DeepL translation

### PR DESCRIPTION
**Pull request by tisfeng**
### ✨ New

- Added support for DeepL translation.
- Supported to sort translation results manually.

### 💎 Improvements

- Used some new icons to adapted to the new raycast API.

### 🐞 Fixes

- Fixed deleting input box text will cause repeated query selected text problem.
- Fixed the bug of "✨ New Version Released" flashing when rendering action button.

## Screencast

easydict-5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tisfeng** [comment]
I need help  @pernielsentikaer

What's this build error?   https://github.com/raycast/extensions/runs/7371802040?check_suite_focus=true#step:4:165 
```
Error:   {6 10}  error  Missing icon: /home/runner/work/extensions/extensions/extensions/easydict/assets/Eudic-icon.png
```
I confirm that this assets image exists, and it has not even been changed in this update.

**Comment by tisfeng** [comment]
I'm sorry, but I've found the cause of the problem. It's a case insensitive file name in Git, and although I changed the icon name and made the corresponding change in the code, Git ignored the icon file name change. This is really a terrible thing.

image
</br>
image

**Comment by tisfeng** [comment]
@danielsequeira Ok, thanks.

**Comment by danielsequeira** [comment]
@tisfeng I played around with your extension and I found some weird flickering while using it, specially on the bottom right corner of raycast where the "Copy Text" action changes to another action for a split moment (video below).
https://user-images.githubusercontent.com/12091319/179710404-13cbf572-03b0-461f-8037-682c17fdd092.mp4

Besides that I noticed that you don't offer a DeepL action in menu, like you do for the other translation services, what is the reason for that?
Screenshot 2022-07-19 at 10 57 00
 
One last suggestion would be to move the Feedback action to the action menu instead of being the primary action. It happens to me a couple of times pressing enter after inserting my word and opening the github issues page when that was not my intention.
easydict 2022-07-19 at 10 53 02

**Comment by tisfeng** [comment]
This should be a bug, I'll check this later.

**Comment by tisfeng** [comment]
@danielsequeira   For the problem you mentioned above, I have updated to solve it, please take a look.

1. fixed the bug of "✨ New Version Released" flashing when rendering action button.
2. added DeepL web translate action. (I just forgot...)
3. removed action list when input text is empty.

deepl

**Comment by danielsequeira** [comment]
@tisfeng thanks for the changes 🙂 

I have no idea how this happened, but when I first installed the extension and used it for the first time I saw new version action as the primary one. However after closing Raycast and trying it again, it doesn't show up anymore and Copy text is the primary action.
easydict 2022-07-20 at 16 02 32

**Comment by danielsequeira** [comment]
> @tisfeng thanks for the changes 🙂
> 
> I have no idea how this happened, but when I first installed the extension and used it for the first time I saw new version action as the primary one. However after closing Raycast and trying it again, it doesn't show up anymore and Copy text is the primary action. easydict 2022-07-20 at 16 02 32

I was just checking the code, I guess this is intended behaviour?

**Review by danielsequeira — APPROVED** [review]

**Pull request merged**
