### PR TITLE
Add valheim-wiki extension

### PR DESCRIPTION
**Pull request by Blackbird9223**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Looks like there is something wrong with the initial load of the extension, I'm just getting no results

valheim-wiki 2024-10-11 at 11 44 48

Use this action to test the error

Raycast 2024-10-11 at 11 45 22

**Comment by Blackbird9223** [comment]
> Looks like there is something wrong with the initial load of the extension, I'm just getting no results

Seemed liked the data were displayed before fully loaded, and on second attempt data were shown. 
Fixed it now.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by Blackbird9223** [comment]
Something missing for a merge?

**Comment by pernielsentikaer** [comment]
I'm not sure why our CI stopped in the middle. Sorry for the inconvenience 🫠

**Pull request merged**
