### PR TITLE
Add ingredients-lister extension

### PR DESCRIPTION
**Pull request by Visual-Studio-Coder**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @Visual-Studio-Coder 👋 

That's a neat idea! I removed some unused imports and corrected the name in an action panel item - could you check that I didn't break something 🙂

**Comment by Visual-Studio-Coder** [comment]
Yep it works! I'm just going to quickly add a youtube video option, but go ahead and publish without it because its going to take me some time to research it.

**Comment by Visual-Studio-Coder** [comment]
Also, do you think I could get onto "featured" of the raycast store?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
