### PR TITLE
Update bobcontrol extension

### PR DESCRIPTION
**Pull request by natsustan**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Looks likes a nice update @natsustan - could you check it @ViGeng

**Review by ViGeng — APPROVED** [review]
Thanks for the contribution!
It looks good to me.

**Comment by pernielsentikaer** [comment]
One last thing @natsustan, could you use [runAppleScript](https://developers.raycast.com/utilities/functions/runapplescript) from @raycast/utils instead?

**Comment by natsustan** [comment]
Well, after following your advice, I was happy to find that @raycast/utils would run AppleScript. so I tweaked and updated the code.

**Comment by pernielsentikaer** [comment]
Thanks 🔥 

We have tweaked it a bit to fit Raycast, thanks for doing it 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by natsustan** [comment]
What a day! I accidentally linked the Github Extension instead of my Github account. LOL.
I just linked it. It is my account https://www.raycast.com/thuggyduck

**Pull request merged**
