### PR TITLE
Update twitch extension

### PR DESCRIPTION
**Pull request by j3lte**
## Description

- Refactored the codebase for better maintainability (_major refactoring, moving files around and moving some parts to separate components_)
- Bumped dependencies
- Updated `useFollowedChannels` to return 100 channels instead of 20
  - This might need an upgrade soon to load more channels (currently it only returns the first 100)
- Added option to show times in 24-hour format

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Sheraff** [comment]
I'll try and take a detailed look next week. This looks like a nice and necessary cleanup, though some of the memoization needs a 2nd pass.

**Comment by pernielsentikaer** [comment]
Hi @j3lte 🚀 

Awesome, thanks for taking your time to enhance the extension

Thanks for taking a look @Sheraff 🔥

**Comment by j3lte** [comment]
@Sheraff have you had a look at the PR? The memoization should be fine, I'd like to know if it can be better. I do have noticed that the extension will regularly rerender the list, which could do with some better checking if something has really changed.

**Comment by Sheraff** [comment]
> @Sheraff have you had a look at the PR? The memoization should be fine, I'd like to know if it can be better. I do have noticed that the extension will regularly rerender the list, which could do with some better checking if something has really changed.

Wow you did well to ping me because I had completely forgotten. My job is basically reviewing PRs, i think I lost track of this notification (and usually at work people ping me when I forget them!).

**Comment by pernielsentikaer** [comment]
Thanks for the review @Sheraff, could you look at the comments @j3lte

**Pull request closed without merging**
