### PR TITLE
New extension: Google Photos

### PR DESCRIPTION
**Pull request by BalliAsghar**
## Description

Access, view and Download your Google Photos.

## Screencast

https://user-images.githubusercontent.com/14165223/212938224-a02aed44-b70f-450d-b1fc-12281734947d.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* If you select a type without content in the Dropdown, then it's not possible to go back before going out and in again - could it be persistent?

Raycast-9y77KkaH@2x

* Is there a way to approve the app? 

Raycast-rD466zGs@2x

* Metadata images are wrong 😊


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by BalliAsghar** [comment]
- **Dropdown** issue is fixed
- added new metadata images

I have submitted the app for verification, It should be verified soon.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @BalliAsghar 👋 

It seems like after this new update I get an exception, could you maybe handle it gracefully?

Raycast-rtjsv9D6@2x

```
Error: Unauthorized

refreshTokens:index.ts:66:10

---
63:   const response = await fetch("https://oauth2.googleapis.com/token", { method: "POST", body: params });
64:   if (!response.ok) {
65:     console.error("refresh tokens error:", await response.text());
66:     throw new Error(response.statusText);
67:   }
68:   const tokenResponse = (await response.json()) as OAuth.TokenResponse;
69:   tokenResponse.refresh_token = tokenResponse.refresh_token ?? refreshToken;
---

async authorize:google-photos.js:5622:23
google-photos.js:5674:15
```

Maybe it's because you're getting it verified?

**Comment by BalliAsghar** [comment]
I believe this is because I updated the Client Id. It should be fine if you sign out and then log back in. I had to change it for verification. btw still waiting for verification to complete.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Is it possible to show a `Grid.Section` so we can get a title of the "Album"

This is what I see when I enter the command:

Raycast-6x8Q14uO@2x

When I upload an image and recheck the Photos command it's now showing this:

Raycast-nzllmRvo@2x


Is this intended behavior? I find it very hard to navigate 🫤

**Comment by osamaaamer95** [comment]
@BalliAsghar did your verification go through? I am going to verify my extension that uses Google Calendar APIs and was wondering if you could help.

**Comment by BalliAsghar** [comment]
@osamaaamer95 Unfortunately, I wasn't able to complete the verification process. The verification required confirming the domain [raycast.com](http://raycast.com/) as it was specified in the redirect URL. However, in order to verify the domain through Google Search Console, we need to have ownership of the domain. which i obviously don't. I reached out to the support team at Google for assistance, but unfortunately, they were unable to provide any help. Therefore, it seems unlikely that we will be able to verify the extension. The only remaining option is to request users to provide their own client key.

**Comment by osamaaamer95** [comment]
@BalliAsghar domain verification is where I am stuck too. Are you using PKCE? The only identifier there is the `bundleId`, and I don't think Google will ask to verify `com.raycast`. In that case, hosting the privacy policy, terms of service, and app homepage on our own site will help solve the domain verification problem.

@pernielsentikaer perhaps the community can benefit from an official Raycast guide/post on how Google verification can be done for public extensions.

**Comment by osamaaamer95** [comment]
#7061 is another extension that uses Google OAuth. @austinwasson please let us know how your verification experience goes.

**Pull request closed without merging**
