### PR TITLE
[Amazon AWS] Improvements for CodePipeline and Secrets Manager commands

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- CodePipeline: Adds action to retry failed stage, stop ongoing execution and toggle stage transition
- Secrets Manager: Retrieves secret value in a new Detail navigation and adds extra metadata

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

* closes https://github.com/raycast/extensions/issues/12958
* closes https://github.com/raycast/extensions/issues/12966

### CODE REVIEW

**Review by JonathanWbn — APPROVED** [review]
good stuff 🚀

**Comment by jfkisafk** [comment]
Hey @pernielsentikaer please take a look when you find some time 🫶

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by jfkisafk** [comment]
Hey @pernielsentikaer can we merge these changes?

**Pull request merged**
