### PR TITLE
Update schoology extension

### PR DESCRIPTION
**Pull request by Visual-Studio-Coder**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Is it possible to make the graphs lines white in dark theme, or is that not possible?

**Comment by Visual-Studio-Coder** [comment]
It's hard to find the right combo of colors though. An option I have is to make the background white, which isn't that great. I'll try that...

**Comment by Visual-Studio-Coder** [comment]
Ok I used the environment.appearance thing this time. I'll just have to hope the graph looks good on the user's end though 🤞🏼

**Review by pernielsentikaer — APPROVED** [review]
✅ Approved

**Pull request merged**
