### PR TITLE
Microsoft Teams Meeting

### PR DESCRIPTION
**Pull request by svenwiegand**
## Description

Followup for #5475 

First version of a new extension for Microsoft Teams users. This allows controlling meeting settings from Raycast using a brand new, unofficial API provided by the Microsoft Teams desktop client. Users can control these features during a meeting:

- Toggle microphone on/off
- Toggle camera on/off
- Toggle background blur on/off
- Leave call
- Raise hand
- Send reactions (like, love, applause, laugh, wow)

## Screencast

No screencast, but screenshots. See README.md for details.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by fredlabosch79** [comment]
Hi, i am using the extension with my corporate Teams Account. I always get the error Message "cannot connect to Microsoft Teams" if I want to use the commands (Mute/Unmute etc) with Teams. 

Any Ideas how to fix that ?

Thank You !!

**Comment by svenwiegand** [comment]
@fredlabosch79 The only thing this extension is communicating with is your local Microsoft Teams client: So the local app must be started (it is not working with teams in the browser). One common issue is, that people copy the API token from the teams client with leading/trailing spaces – then the connection will fail.

**Comment by fredlabosch79** [comment]
> that people copy the API token from the teams client with leading/trailing spaces – then the connection will fail.

This was the problem! Now it works like a charm !! Thanks a lot

**Comment by svenwiegand** [comment]
@fredlabosch79 Happy to hear. Always wanted to publish a new version which fixes this, but never found the time …

**Pull request merged**
