### PR TITLE
Create Apple Books extension

### PR DESCRIPTION
**Pull request by vimtor**
## Description

A simple extension to search Apple Books.

## Screencast

https://user-images.githubusercontent.com/36263538/226165914-43a92480-1402-4662-95d6-32772bdb9732.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* The extension crashes when I search for `ee`

Raycast-vxWuWPxU@2x
  
* Could be nice with a custom EmptyView that says search instead of No Results initially 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by vimtor** [comment]
@pernielsentikaer done!

**Comment by pernielsentikaer** [comment]
I still get the same error with the search term `ee`

Raycast-nLN3oFVD@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by vimtor** [comment]
Hi @pernielsentikaer!

I don't know why is it failing to you. Also, the error you showed seems to be React related since it is complaining that no object is being passed to the component.

https://user-images.githubusercontent.com/36263538/232302428-4f0d438c-a12d-42ed-920a-789a11b1694e.mp4

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
