### PR TITLE
Update schoology extension

### PR DESCRIPTION
**Pull request by Visual-Studio-Coder**
## Checklist

- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Visual-Studio-Coder 👋

Thanks for taking your time updating the extension 🔥 

Instead of adding [schoology-3.png](https://github.com/raycast/extensions/pull/9970/files#diff-99d9fedb15e5ab5043f1b72c8a530ce26981b449668c379e4c50b14b44ea681b) which has no contextual value, could you then add new image of the grades since that's what you're enhancing 🙂

**Comment by Visual-Studio-Coder** [comment]
I just added that new assignments view image I was referring to

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
We'd like to have all metadata images in the same format, could you change the new to match the other?

**Comment by Visual-Studio-Coder** [comment]
Fixed!

**Comment by pernielsentikaer** [comment]
Could you use the same background too 🙂

**Comment by Visual-Studio-Coder** [comment]
Yes I completed it.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
