### PR TITLE
Add github-projects extension

### PR DESCRIPTION
**Pull request by skw**
## Description

This PR adds a raycast extension allows searching recently-updated and recently-visited GitHub projects. The project/view visits are saved in localStorage so that users can quickly access items they opened.

## Screencast

previewx

See the readme for more details: https://github.com/skw/raycast-github-projects

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @skw 👋 

Thanks for your contribution 💯 

@thomaslombart what do you think of this, would it benefit the GitHub extension?

**Comment by thomaslombart** [comment]
@pernielsentikaer It'd make more sense for it to be part of the GitHub extension since we already have stuff related to projects there.

**Comment by pernielsentikaer** [comment]
I agree 🙂

@skw would you be up for that, contributing to the GitHub extension?

**Comment by skw** [comment]
@pernielsentikaer Yes absolutely 👍

**Pull request closed without merging**
