### PR TITLE
Add custom-command-search extension

### PR DESCRIPTION
**Pull request by mrdear**
## Description
You can customize commonly used URLs or commands, and then use this plugin for quick access. This plugin can be very useful in situations where a platform provides multiple environments.

Then You can use the yaml path in the custom command file for multi device synchronization

## Screencast
Screenshots1
Screenshots2
Screenshots3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
This is what snippets and quicklinks in Raycast are there for, wouldn't it be a lot easier just to use them?

**Comment by mrdear** [comment]
> This is what snippets and quicklinks in Raycast are there for, wouldn't it be a lot easier just to use them?

Yes, Snapets and Quicklinks can solve the problem, but in some scenarios, they are not very convenient.
1. Our company's system generally has five environments, dev, test, pre, gray, and prod. A project platform has five addresses links. When configuring quicklinks, due to high repetition, the configuration is trivial and inconvenient.
2. It is not convenient to share. With this plugin, I can copy these configuration files to newly hired colleagues at once.

**Comment by mrdear** [comment]
``` yaml
- key: dds
  remark: 数据源配置平台
  values:
  - cmd: http://iddsconsole.stable.xxx.net/index.html
    remark: stable
  - cmd: http://iddsconsole-1-64.test.xxxxx.net/index.html#/ixxxxx/test/zdal/overview?_k=x3y7t3
    remark: sit
  - cmd: https://idds-pre.xxxxx.com/index.html
    remark: pre预发
  - cmd: https://idds-gray.xxxxx.com
    remark: 灰度
  - cmd: https://idds.xxxxx.com/index.html#/ixxxxx/prod/zdal/overview?_k=wcqa0b
    remark: prod
```

image

**Comment by pernielsentikaer** [comment]
It could work, but I'm not sure about the config file approach (and it seems a bit niche cased) 

You could create a free organization and make it a private extension instead, that way you can also update content that fits your need and just invite new members to the organization?

**Pull request closed without merging**
