### PR TITLE
Add qrcode extension

### PR DESCRIPTION
**Pull request by hcl-z**
## Description

A more complete function of the qrcode generator

## Screencast

qrcode-1
qrcode-2
qrcode-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Did you see this [one](https://www.raycast.com/Melvynx/qrcode-generator) before creating this, it seems very similar

**Comment by hcl-z** [comment]
> Did you see this [one](https://www.raycast.com/Melvynx/qrcode-generator) before creating this, it seems very similar

Yes, I used this plugin before, but it doesn't have a history function, and it's not easy to see the current qrcode link, so I made this

**Comment by LitoMore** [comment]
You can add the history feature to the existing extension with preference options. Make it switchable in case someone doesn't need it.

**Comment by hcl-z** [comment]
> You can add the history feature to the existing extension with preference options. Make it switchable in case someone doesn't need it.

The history feature is the main feature of my plugin, and if someone doesn't need it, they can use the qrcode plugin already available in the store

**Comment by hcl-z** [comment]
> This will become a mess. It is better not to submit highly similar extensions. If you want to use it personally, consider publishing it to your own organization.

Well, thank you for your time

**Pull request closed without merging**
