### PR TITLE
Add run_replicate extension

### PR DESCRIPTION
**Pull request by cbh123**
## Description
Adding a new replicate raycast extension that lets users run models, explore models, view predictions, and open their replicate dashboard.

There currently is a great replicate extension, but it only allows users to view predictions (https://github.com/KevinBatdorf/replicate-raycast).

## Screencast

https://user-images.githubusercontent.com/14149230/224436103-ad83c221-cac6-46b7-8536-60dfcae802c0.mp4

Here's a loom of me walking through it: https://www.loom.com/share/b3c53bdab54944899fa461632b0ce1c3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by zeke** [comment]
cc @KevinBatdorf. Maybe this is an opportunity to converge and collaborate.

**Comment by KevinBatdorf** [comment]
This is great @cbh123! I think from Raycast's perspective they would prefer to build on the existing extension and adding another command. Do you want to work on that a bit together? Maybe via a PR [here](https://github.com/KevinBatdorf/replicate-raycast)? Could break it into a few PRs as well. 

Have you explored getting the models list dynamically? That way it would be able to support any new models in the future without needing to update this extension. Could just use https://api.replicate.com/v1/collections/diffusion-models I think, and also add a mechanism to sort by previously run models.

**Comment by cbh123** [comment]
@KevinBatdorf thanks! You're right, I just changed up things so that it gets the model list dynamically. I was meaning to do that originally but decided to just get it done now. 

I'm going to also take a look at building on your extension rather than making this a new one, stay tuned

**Comment by KevinBatdorf** [comment]
@cbh123 I'm not with Replicate and not a part of the org. I built this as a community member and a fan. I have some feature ideas scheduled for early April actually. I'll see about making a PR to the new repo (just a small aside, copy/pasting instead of forking or asking me to transfer my repo feels a bit outside the spirit of open source imo).

@zeke do you want to create a Raycast account with a Replicate username and transfer the extensions ownership to Replicate? I think we can ask Raycast to take care of that (or it may even just be automated from the package.json file). So for example, it would show up on the author list here: https://www.raycast.com/KevinBatdorf

**Comment by cbh123** [comment]
I'm planning to create a PR! May be some miscommunication here but I'm not trying to copy and paste your code. When I run npm run publish it automatically creates a pull request to your repo, I think. It's just failing on that step because I'm not a member of an organization. I'll figure it out.

**Comment by KevinBatdorf** [comment]
I think it's using the GitHub api to PR from the [repo here](https://github.com/replicate/replicate-raycast) into the raycast extensions repo using your credentials. But if you don't have org access then it will fail. 

> I'm planning to create a PR! May be some miscommunication here but I'm not trying to copy and paste your code.

No need for that. I'll archive it later on. It makes more sense to have the repo under the Replicate namespace and on their org _if_ Replicate wants to maintain it. That's totally understandable.

**Comment by zeke** [comment]
> @zeke do you want to create a Raycast account with a Replicate username and transfer the extensions ownership to Replicate?

Hi. Raycast newcomer here. 👋🏼 

I think @bfirsh created a `replicate` organization for us, but it sounds like you're suggesting creating a user with the name `replicate` instead. Can orgs be owners or would we need to create an actual user?

**Comment by KevinBatdorf** [comment]
They just need a Raycast account, I believe. So it may need to be a user. @pernielsentikaer is that accurate? Or can a GitHub Org be an author?

**Comment by cbh123** [comment]
Ok so the latest is that I changed the owner to replicate and published under the replicate org, here: https://www.raycast.com/replicate/replicate. The code is all here: https://github.com/replicate/replicate-raycast/tree/main, and includes the contributions from @KevinBatdorf. 

But I'm confused now how to get this into a public extension anyone can download. When I run `npm run publish`, it publishes as an [organization extension](https://www.raycast.com/replicate/replicate), which seems to be private. But when I remove the owner, the `npm run publish` command asks for an owner. 

@pernielsentikaer could you help with this? TLDR we want this https://github.com/replicate/replicate-raycast/tree/main to be the public / official Raycast extension for replicate.

**Comment by cbh123** [comment]
Ok I figured it out. New extension is here: https://github.com/raycast/extensions/pull/5384

**Pull request closed without merging**
