### PR TITLE
Update papago-translate extension

### PR DESCRIPTION
**Pull request by jaeyeonling**
## Description

- Change the endpoint from Naver to Naver Cloud Platform
    - This should fix the following issue: #11219, #11332
- Exception handling for status code 404, 429
- Update README

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @jaeyeonling 🔥 

@Rita-Mordio could you have a look?

**Comment by pernielsentikaer** [comment]
Are you still around @Rita-Mordio

**Comment by dead-1ine** [comment]
@Rita-Mordio ping :)

**Comment by pernielsentikaer** [comment]
Sent @Rita-Mordio an e-mail

**Comment by pernielsentikaer** [comment]
Just to understand, will the extension still work for the users using it today? Is Naver and Naver Cloud the same?

**Comment by jaeyeonling** [comment]
Yes, the same service has been moved from Naver to Naver Cloud Platform.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
