### PR TITLE
GIF Search: Better results and codebase revamp

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

- The extension now uses GIPHY Pro and Tenor v2 to have better GIF results
- The codebase has largely been revamped to make it easier to maintain

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by j3lte** [comment]
@thomaslombart FYI, I still got a PR open for gif-search: #11794

**Comment by thomaslombart** [comment]
@j3lte Could you test out this PR and let me know if it fixes what you initially fixed? This PR is revamping the codebase to make it easier to understand and simpler to maintain while still adding some nice features like caching the results.

**Comment by pernielsentikaer** [comment]
Wow @thomaslombart, that's a serious rewrite! 

Do I need to do anything to get it working, I end up here as soon as I open the extension

gif-search 2024-04-22 at 13 58 37

```
FetchError: request to https://gif-search.raycast.com/api/giphy?limit=20&offset=20 failed, reason: connect ECONNREFUSED 127.0.0.1:9090
    at ClientRequest.<anonymous> (/Users/pernielsentikaer/.config/raycast/extensions/gif-search/search.js:23288:14)
    at ClientRequest.emit (node:events:526:35)
    at ClientRequest.emit (node:domain:488:12)
    at /Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:2:37408
    at Socket.<anonymous> (/Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:2:38379)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by thomaslombart** [comment]
I can't reproduce it… Could you post a recording to better see what happens? Is it the same if you switch to the Tenor provider?

**Comment by pernielsentikaer** [comment]
I'm not sure what happened; it seems to be working much better now. I ensured that I could open the URL, so I don't know what caused it.

The search works SO much better than previous, well done @thomaslombart

**Comment by samuelkraft** [comment]
Echoing this, great work @thomaslombart!

My only nit is regarding the empty states, on initial load we display a flickering empty state even for the services that automatically populates the list:
Sam 2024-04-23 at 8  47 25@2x

The empty state for when you get 0 hits on search is also the same generic one, instead of saying "No Results":
Sam 2024-04-23 at 8  54 24@2x

**Review by josephschmitt — APPROVED** [review]
This is a big change, nice work @thomaslombart! I haven't been able to review every line contributed, but directionally this looks good to me and as long as it's well-tested I'm comfortable with it getting merged.

**Pull request merged**
