### PR TITLE
Ruler: Improvements

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

- Added coordinates
- Replaced measurement by dragging
- Improved overlay styling

## Screencast

https://github.com/raycast/extensions/assets/16003285/48bacf27-75da-44a3-9f2a-ef05f4309fa2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by anwarulislam — APPROVED** [review]
LGTM 🚀

**Comment by thomaslombart** [comment]
Are you meeting the requirements described [here](https://github.com/raycast/extensions-swift-tools?tab=readme-ov-file#requirements)? What compilation errors do you get?

**Comment by pernielsentikaer** [comment]
@anwarulislam can you check once more, I updated the CLI version 🙂

**Review by anwarulislam — APPROVED** [review]
I have checked, it is working now!
LGTM 🚀

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
> Change the API version before merging to latest `1.75.1`

Nothing new has been added that affects this, so let's keep it as is

**Pull request merged**
