### PR TITLE
Update copyq-clipboard-manager extension

### PR DESCRIPTION
**Pull request by andrewcincotta**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Thanks for your new enhancement 🔥 

When I use the commands I get a lot of crashes, check this video out:

https://github.com/raycast/extensions/assets/38033107/3288e48e-8341-4e67-9a4c-a861b84baade

It also looks like there is some [empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
The new command crashes If `copyq` is not open, could you handle this gracefully (Maybe add a toast in both commands if possible)

copyq-clipboard-manager 2023-11-28 at 06 47 40

**Comment by pernielsentikaer** [comment]
I can't reproduce that error now, I guess we can continue 🚀

What about leaving the path not required and test against /opt/homebrew/bin/copyq and /usr/local/bin/copyq - if not found let the user add it in the preferences manually?

**Comment by andrewcincotta** [comment]
> I can't reproduce that error now, I guess we can continue 🚀
> 
> What about leaving the path not required and test against /opt/homebrew/bin/copyq and /usr/local/bin/copyq - if not found let the user add it in the preferences manually?

I'm honestly stuck on the error handling. I can't find a way to try/catch "copyq server not running" and "copyq not found". When I attempt this, my code cannot tell the difference between the two errors, and throws the same return value for each (which is why the updated error screen includes "path not found or server not running". If I could differentiate these two errors, I could check for the path better, and potentially have the extension start the copyq server if the path is found but it is not running.

If copyq is not found, it should return something like "command not found"
If copyq server is not running, it should return "ERROR: Cannot connect to server! Start CopyQ server first."

Could you assist me with this change?

**Comment by andrewcincotta** [comment]
@pernielsentikaer Are we good to publish this version?

**Pull request merged**
