### PR TITLE
don't cache moment data

### PR DESCRIPTION
**Pull request by SandyGifford**
## Description

Gets new data moment data when refreshing menu-bar

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by clayton-knapp** [comment]
LGTM!

**Comment by SandyGifford** [comment]
@pernielsentikaer @clayton-knapp all cleaned up - ready for eyes and merge

**Review by clayton-knapp — APPROVED** [review]
LGTM!

**Comment by pernielsentikaer** [comment]
Awesome, thanks 👏

**Pull request merged**
