### PR TITLE
Add 5devs extension

### PR DESCRIPTION
**Pull request by gustavo-fior**
## Description

This is an extension that generates fake Brazilian (shoutout Pedro and Bruno! :D) data for testing purposes.

## Screencast

https://github.com/user-attachments/assets/2d7021da-bf99-4191-9cb0-1ef78424d7f5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mil3na — CHANGES_REQUESTED** [review]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

I guess you forgot one more brazilian on your shoutout ;)
- So, your extension is not really generating, but getting data from a pre-built database that you submit with the extension. I think that should be clear to the user.
- Your README is empty, please provide context for this information
- The data on the extension, is it really fake? Some CEPs have comments with addresses, which concerns me.
- Do you have any license for the data you are submitting here?
- Please, although it is fine that the content generated is in Portuguese, the actions and prompts should be in English.

Please, take a look at my comments and let me know what you think.

**Comment by gustavo-fior** [comment]
Hi Milena! 

My bad, I truly forgot hahahah! I even follow you on X.

I will make the changes tonight!

I just have a few questions:

> So, your extension is not really generating, but getting data from a pre-built database that you submit with the extension. I think that should be clear to the user.

It depends, I have a few databases (e.g. Inscrições Estaduais, CEP, Names), but some of the data is generated from algorithms like CNPJs and CPFs. Maybe a better approach would be to say something like "Get fake and static data for your tests". What do you think?

> The data on the extension, is it really fake? Some CEPs have comments with addresses, which concerns me.

The CEPs database has real CEP numbers from famous places. This is because there's a lot of apps that fill all the other address fields with correct values after looking up the CEP in some external service like https://viacep.com.br. Would this be all right if the description was what I suggested earlier?

> Do you have any license for the data you are submitting here?

Not at all. Excluding the ones that are generated from algorithms, most of it was generated by AI and some were collected from other data generator websites.

Thanks for your fast response :)

**Comment by mil3na** [comment]
My concern with fake that that is not really fake is legal. It would be nice to have a description of where the data comes from and that you have authorization to use them if they are real (or not generated).
Also, I was wondering: why the name of the extension is 5devs and not something more descriptive?

**Comment by gustavo-fior** [comment]
Hey @mil3na, do you need anything else from my side? 

Thanks :)

**Comment by mil3na** [comment]
Sorry for the delay, I will be taking another look tomorrow!

**Comment by mil3na** [comment]
One more thing: Even though the data is in Portuguese, I'd recommend leaving the commands and actions in English. Do you mind changing that?
In the future, data presentation can be better as well, but it is good enough for a first version.

**Comment by gustavo-fior** [comment]
Just translated everything to English now! 

Please let me know if I forgot something.

**Comment by mil3na** [comment]
We have some linting erros preventing me to merge :)

**Comment by gustavo-fior** [comment]
Fixed :)

**Review by mil3na — APPROVED** [review]
LGTM!

**Comment by gustavo-fior** [comment]
Thanks for the patience @mil3na :)

Happy to have an extension published in one of my favorite apps of all time!

**Pull request merged**
