### PR TITLE
VSCode: Add extension commands

### PR DESCRIPTION
**Pull request by tonka3000**
## Description

Port of #4099

Add following commands

### Commands

Search and trigger commands directly from Raycast. This command requires that the `Raycast for VSCode` extension is installed in VSCode. If not the user will get an action to do so.
VSCode has some internal API limitations and therefore not all command aliases can be shown. If this is the case the command ID will be shown instead.

User can also store the VSCode command as quicklink (using URL schemas in the background) which makes it accessible from the root menu of raycast.

CleanShot 2022-12-30 at 12 56 01@2x

CleanShot 2022-12-30 at 12 56 57@2x

CleanShot 2022-12-30 at 12 57 45@2x

### Show Installed Extensions

Show locally installed extensions.

CleanShot 2022-12-30 at 13 00 02@2x

CleanShot 2022-12-30 at 13 00 42@2x

### Install Extensions

Install Extension in VSCode.

CleanShot 2022-12-30 at 13 01 29@2x

CleanShot 2022-12-30 at 13 01 44@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the update @tonka3000, that's really awesome 🔥 

@thomaspaulmann do you mind giving it a spin

**Comment by eduwass** [comment]
Hey @tonka3000 I was about to test this, any reason why you closed? Thanks!

**Comment by andrewminion-luminfire** [comment]
@tonka3000 thanks for your work on this and other extensions; I use the GitLab extension **dozens** of times every day.

I’m curious what announcements you refer to…I must’ve missed something

**Comment by eduwass** [comment]
+1 to what @andrewminion-luminfire just said, first of all, thanks, and we respect your choice... but what exactly happened?

**Comment by tonka3000** [comment]
@eduwass I opened the PR again so that this work can be used, feel free to test it.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
