### PR TITLE
Add duckduckgo-image-search extension

### PR DESCRIPTION
**Pull request by jag-k**
## Description

Search Images inside Raycast by DuckDuckGo Image!

## Screencast

duckduckgo-image-search-1
duckduckgo-image-search-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

This doesn't work for me, I just end up here:

duckduckgo-image-search 2024-11-12 at 09 21 06

```
Error: attempt finished
    at imageNextSearch (/Users/pernielsentikaer/.config/raycast/extensions/duckduckgo-image-search/search-image.js:21830:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async imageSearch (/Users/pernielsentikaer/.config/raycast/extensions/duckduckgo-image-search/search-image.js:21807:10)
    at async searchImage (/Users/pernielsentikaer/.config/raycast/extensions/duckduckgo-image-search/search-image.js:21896:12)
    at async /Users/pernielsentikaer/.config/raycast/extensions/duckduckgo-image-search/search-image.js:21983:38
```

Do you have any idea what might be wrong?

**Comment by jag-k** [comment]
Oh, yes... sometimes, DuckDuckGo might block re requests. Try to open ddg on your browser and search anything. After that, try to find images in extension.

Anyway, I need to raise connection attempts up to 5-10

**Comment by pernielsentikaer** [comment]
I'm still encountering the error. I've tried various searches but haven't been able to get it to work. I'm unsure if it's suitable for the store in its current state 🙁

**Comment by jag-k** [comment]
> I'm still encountering the error. I've tried various searches but haven't been able to get it to work. I'm unsure if it's suitable for the store in its current state 🙁

Sounds sad 😢 I'll try to update rate limit tomorrow ('cause I haven't Mac yet)

**Comment by jag-k** [comment]
@pernielsentikaer I think I fixed it.

Added more settings into Raycast Command Settings:
 - License
 - Locale
 - Retry count
 - Sleep time between retries

I think the error was caused by a locale (maybe DuckDuckGo "removes" locale `wt-wt`). Now the default locale is `en-us`.

**Comment by pernielsentikaer** [comment]
VPN and changed locale didn't do anything, the error happens the second I press a key
 
https://github.com/user-attachments/assets/f320ace0-0bb8-4a9f-9a96-f21017349f89

**Pull request closed without merging**
