### PR TITLE
Add raycast-translate-ge extension

### PR DESCRIPTION
**Pull request by giokaxo**
## Description

This extension translates words from Georgian to English and vice versa using translate.ge

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I would remove the redundant accessory

raycast-translate-ge 2023-06-09 at 05 55 19

- There are no [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by giokaxo** [comment]
Hello @pernielsentikaer 👋.

Thank you for your feedback. I've fixed all the comments, should be good now 🙏.

**Comment by pernielsentikaer** [comment]
I can't see the pushed changes, did you commit them yet @giokaxo

**Comment by pernielsentikaer** [comment]
You could do it manually from this [view](https://github.com/raycast/extensions/pull/6961/files)

You should also be able to do like this
1) Change files
2) run `git commit -am "New files"`
3) run `npx @raycast/api@latest publish`

**Comment by giokaxo** [comment]
I did it and still not luck.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
