### PR TITLE
[Github Gists] OAuth 2.0 support

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- Uses Raycast OAuth2.0 GitHub integration with `repo read:user gist` scopes.
- ⚠️Disables the personal access token preference. Users can delete their tokens after successful OAuth2.0 connection.
- Minor refactoring and updated dependencies.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

* closes https://github.com/raycast/extensions/issues/13402

### CODE REVIEW

**Comment by koinzhang** [comment]
Hi @jfkisafk Good job!

**Comment by jfkisafk** [comment]
Hello @koinzhang thanks! I forgot to make this PR open for review, now I have and you can review when you get time 🙌

**Review by mil3na — APPROVED** [review]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

Great addition to this extension. OAuth makes it even easier to use. @koinzhang Are you okay with the changes?

**Comment by koinzhang** [comment]
It's ok👍

**Pull request merged**
