### PR TITLE
Add count-numbers extension

### PR DESCRIPTION
**Pull request by XInTheDark**
## Description
Add the Count Numbers extension.

It has a simple and intuitive interface to count numbers - press Enter to increment the counter.
It is also customizable and supports having multiple counters, as well as changing the value, increment and modulo.

## Screencast
count-numbers-1
count-numbers-2
count-numbers-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for your contribution 🔥

Is there a specific reason why it can't count down again? 🙂

**Comment by XInTheDark** [comment]
Hi, technically counting down can be configured by setting increment = -1. But I can add a shortcut for it I suppose - what keyboard shortcut do you recommend?

**Comment by XInTheDark** [comment]
pushed changes

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by abdullahkhilji** [comment]
This no longer seems to work.

@XInTheDark

**Comment by pernielsentikaer** [comment]
Since this is about a public extension not built by us but maintained by our community, you should use the `Report Bug` action in Raycast action panel while having the extension selected in order to create an issue for it, so the author of the extension or someone else can help you out

**Pull request merged**
