### PR TITLE
[Update Extension] World Clock - Fix clock image not working

### PR DESCRIPTION
**Pull request by lucasmezencio**
## Description

After the [last update](https://github.com/raycast/extensions/pull/4086), the [World Clock](https://www.raycast.com/koinzhang/world-clock) extension stopped working due to a change on the original `datetime` object, making any `Date` operations to fail.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I'm still seeing a bunch of errors in a toast, could you give it a spin @koinzhang 

Raycast-kfoydhNt@2x

**Comment by koinzhang** [comment]
Hi @lucasmezencio. First of all, thank you for using World Clock.

> After the https://github.com/raycast/extensions/pull/4086, the [World Clock](https://www.raycast.com/koinzhang/world-clock) extension stopped working due to a change on the original datetime object, making any Date operations to fail.

You mentioned that the clock image of this extension is not working, but on my device this extension is working fine, can you describe in more detail the problem you are experiencing?

**Comment by lucasmezencio** [comment]
Hey @koinzhang! So, basically the issue happens when you change the format of the date. If you use the default date format it works perfectly. That's why it might be working on your end.

I, indeed, didn't explain what is the main issue in the PR description.

So, when the date format is different from the default, the date operations return an invalid date, hence, invalid (`NaN`) arithmetic operations.

**Comment by koinzhang** [comment]
Hi @lucasmezencio. I changed the time format according to your description, but on my device, always the clock image still updates properly.
I recorded a video and it seems to me that the extension is working properly in this video.

https://user-images.githubusercontent.com/36128970/236393377-c8f8ba8f-4239-429b-8759-000d451b276f.mp4

Have you tried to uninstall and reinstall the extension? Maybe the problem is caused by some LocalStorage data.

**Comment by lucasmezencio** [comment]
Hey, @koinzhang, sure thing, let me try to reinstall it.

**Comment by lucasmezencio** [comment]
Hey, @koinzhang, you're correct. Something was wrong on my end.

I'm sorry for wasting your time too @pernielsentikaer.

Closing this one.

**Comment by pernielsentikaer** [comment]
All good, glad it works now

**Pull request closed without merging**
