### PR TITLE
Update jira extension

### LINKED ISSUE #12674: [Jira] ... If I search the ticket number without the project prefix, it shows no result found
### Extension

https://www.raycast.com/raycast/jira

### Raycast Version

1.75.2

### macOS Version

Sonoma 14.4.1 (23E224)

### Description

[Jira] ... If I search the ticket number without the project prefix, it shows no result found

### Steps To Reproduce

Go to Jira search issues
search with ticket id number alone without the prefix

### Current Behaviour

If I search the ticket number without the project prefix, it shows no result found

### Expected Behaviour

It should show the relevant tickets even if just the number is provided

### PR DESCRIPTION
**Pull request by mikybars**
## Description

Fixes #12674 

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mikybars** [comment]
I've just added a little code that proves that the issue list is being searched locally and that the expected behavior can be achieved by tinkering with a [list item's keywords](https://developers.raycast.com/api-reference/user-interface/list#search-bar).
In order to test it, just run the `Open Issues` command, for example, and search by the numeric id instead of the full issue id.

**Comment by pernielsentikaer** [comment]
@jesperorb did you change your Raycast handle?

**Comment by mikybars** [comment]
Sorry if I didn't make myself clear in the first place but I this is not a fix yet but rather a workaround to show that the search within a list in Raycast may be broken. As per the official [docs](https://developers.raycast.com/api-reference/user-interface/list#search-bar):

> The search bar allows users to interact quickly with list items. By default, [List.Items](https://developers.raycast.com/api-reference/user-interface/list#list.item) are displayed if the user's input can be (**fuzzy**) matched to the item's title or keywords.

I assume that in the context of the Jira extension, the above feature will allow me to search for Jira issues that have the key `PROJ-123` just by typing `123` but that's not the case unless I add `123` to the list of keywords (as you can see in the changes).

So if someone from the team could check that this is expected behavior...

**Comment by mikybars** [comment]
Hey @thomaslombart. Did you have the time to review this?

**Comment by thomaslombart** [comment]
I can see there are some conflicts, and the PR is still a draft. Could you look into it and mark it as ready so I know when to test it?

**Pull request closed without merging**
