### PR TITLE
Add format-graphql extension

### PR DESCRIPTION
**Pull request by tngranados**
## Description

Formats GraphQL with provided indentation

## Screencast

format-graphql-01

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by sxn** [comment]
hey @tngranados, congrats on the extension 🎉 
Mind adding an `.eslintrc` file? That's why CI is currently failing 😉

**Comment by tngranados** [comment]
> hey @tngranados, congrats on the extension 🎉
> Mind adding an `.eslintrc` file? That's why CI is currently failing 😉

You are right, I missed those. Added now, thanks 👌

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @tngranados 👋 

Thanks for the extension and the updates. Much appreciated! 💪 

It's possible to break the extension and throw errors; can you look into catching the errors gracefully?

If I insert "hello" and submit, it looks like this:
jUdzOyYVbH7uR91U

Besides that, it works as expected! 💪  I tested some strings and couldn't find anything else 😄

I am looking forward to testing it out again!

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by tngranados** [comment]
Thanks for letting me know @pernielsentikaer, I've updated the extension with error handling.

**Comment by pernielsentikaer** [comment]
Hi @tngranados 👋 

Thanks for the update. It works a lot better now 🔥

**Pull request merged**
