### PR TITLE
Add SauceNAO Reverse Image Search extension

### PR DESCRIPTION
**Pull request by bgiesing**
## Description

Extension to reverse search images from your clipboard, a link, or Finder via [SauceNAO](https://saucenao.com/) which is often used for Art communities. 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you handle this error gracefully?

saucenao 2024-10-25 at 09 59 53

- Could you record a screencast so I can see the flow?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by bgiesing** [comment]
TBH I have no idea how to handle that, the entire extension was made with ChatGPT and I don’t know TypeScript.

As for the screencast, there’s no UI since it just launches a web link so not really sure what I could do there since it would just be a still image of the search box list

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
You should use a try catch around it, you can see [more here](https://developers.raycast.com/api-reference/environment#example-2)

**Comment by bgiesing** [comment]
Yeah I can’t figure it out, I tried for 4 hours working on a solution and every way I try to wrap it, it just breaks the extension entirely unable to do anything with that command. This is way above my skill level

**Comment by pernielsentikaer** [comment]
Could you check that I didn't broke something 🙂

**Comment by bgiesing** [comment]
Yep the changes seem to work, I also made a slight update to fix a README typo and updated the other commands to use the same `  const { apiKey } = getPreferenceValues<ExtensionPreferences>();` change you made in the Selected File command.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
