### PR TITLE
feat(brave): added search bookmarks

### PR DESCRIPTION
**Pull request by crisboarna**
## Description

- Added search bookmarks action
- Refactored code to use new useSQL hook

## Screencast
image
image
image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @ron-myers 👋 

Do you mind checking this?

**Comment by ron-myers** [comment]
Hey @pernielsentikaer 👋 - happy to; I am travelling today and tomorrow but will find some time to review/test.

**Comment by pernielsentikaer** [comment]
I can do it @ron-myers, I'll give it a quick spin 😊

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* `New Tab` and `Search Tabs` doesn't work; it shows that I have to install Brave even though I have it.
* Some actions are missing icons

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by crisboarna** [comment]
HI @pernielsentikaer,

Updated with requested changes.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
