### PR TITLE
Update PIA controls

### PR DESCRIPTION
**Pull request by Yakitrak**
## Description

- Updated commands to check for connectivity before showing HUD
- New command to see current status
- New command to search and connect to specific region

## Screencast
image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Yakitrak** [comment]
This might be a silly question I was wondering whats the best way to add images for the store page?

**Comment by pernielsentikaer** [comment]
Its not a silly question at all, you add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) 🙂

**Comment by Yakitrak** [comment]
> Its not a silly question at all, you add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) 🙂
> 
> Could you also add a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry

Updated changelog and images. Thank you for the guidance on adding images. I figured it had to be in the metadata folder but was struggling to get it the right size - the fact that you have a tool to take the perfect image and provide the backgrounds is absolutely amazing! Love Raycast more everyday!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Thanks for the lovely words @Yakitrak 🔥

**Pull request merged**
