### PR TITLE
Add simple-memo extension

### PR DESCRIPTION
**Pull request by mushroom528**
## Description

A lightweight, offline-first memo extension for Raycast that helps you capture and organize your thoughts quickly without any external dependencies. The fastest way to access and manage your memos on your Mac – just a keyboard shortcut away.

### Core Features

✍️ Create Memos: Quickly capture your thoughts with markdown support
🔄 Edit Memos: Seamlessly update your existing memos
🔍 Search Memos: Instantly find any memo with fast full-text search
💻 100% offline - all data stored locally

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

It looks a bit like https://www.raycast.com/k41531/snap-jot - could that work for you?

**Comment by mushroom528** [comment]
Thank you for reviewing my contribution! 👋

I've looked at Snap Jot, and while it serves similar purposes, my extension takes a fundamentally different approach:

1. Storage Architecture: Instead of file-based storage, my extension uses LocalStorage, providing a seamless in-app experience without file management overhead. This makes it ideal for users who prefer keeping their memos within Raycast's ecosystem.

2. Different Use Case: While Snap Jot excels at quick file-based note-taking, my extension focuses on providing an integrated memo management experience entirely within Raycast.

Additionally, I have plans to enhance the extension with more features in the future:
- Tag support for better memo organization and filtering
- Import/Export functionality for data backup and migration between devices

Would these architectural differences and future roadmap be significant enough to warrant a separate extension? I believe both extensions could serve different user preferences and workflows.

**Comment by mushroom528** [comment]
Thank you for testing the extension! 🙏

I apologize for any confusion - I should have been clearer in my previous message. The tag support is actually part of my future development plans, not a current feature. 🚀

The current version focuses on the core memo management functionality using LocalStorage. Here's what's currently implemented:
- Basic memo creation and management
- In-app storage system
- Seamless Raycast integration

Would you like me to proceed with the review of the current functionality? I'd be happy to clarify any other aspects of the extension. 💪

Looking forward to your feedback! ⚡️

**Comment by pernielsentikaer** [comment]
If it's not working at the moment and you want to add it later, we should remove it until then to avoid confusion.

**Comment by mushroom528** [comment]
I sincerely apologize for the oversight.

You're absolutely right - I accidentally left the tag feature in the code while it wasn't fully implemented yet. I've now removed it to avoid confusion and pushed a new version that reflects the current core functionality correctly.
Would you mind testing the updated version? 

Thank you for your patience and thorough review!

**Comment by pernielsentikaer** [comment]
Much better 🔥 

A few things:

- You could consider adding an action to “Delete All Memos” with a [[confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert)](https://developers.raycast.com/api-reference/feedback/alert#confirmalert)
- You can use [[showFailureToast](https://developers.raycast.com/utilities/functions/showfailuretoast#signature)](https://developers.raycast.com/utilities/functions/showfailuretoast#signature) for errors

**Comment by mushroom528** [comment]
I've implemented all the suggested improvements! 

Changes made:
- Added "Delete All Memos" action with confirmAlert for safety
- Updated error handling to use showFailureToast
- Improved date formatting with toLocaleString()

Would you mind reviewing the updated version? 

Thank you again for your helpful suggestions! 🙌

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
We actually have a similar extension in the store which actually does the job pretty good: https://www.raycast.com/biknandy/quick-notes

Did you see that one?

**Comment by mushroom528** [comment]
Thank you for pointing this out! You're right - I've looked at Quick Notes and it does provide similar functionality to my extension. Since it already serves the use case well, I think it makes more sense to avoid duplicating effort.

Would you recommend I close my PR and perhaps contribute to Quick Notes instead if I have ideas for improvements? 🤔

Thank you for your time and guidance throughout this review process! 🙏

**Pull request merged**
