### PR TITLE
Cloudflare: Add cache purge command, bugfix

### PR DESCRIPTION
**Pull request by niklaswa**
#### New Feature:
Added action for purging files from the cache at Cloudflare.
See https://api.cloudflare.com/#zone-purge-files-by-url & screencast

#### Bugfix:
And I also fixed getting the zones for specific accounts. Before every zone of every account were showing up multiple times (for every account), because the filtering in the zone method were broken.
Also an error were showing up because apparently a key is needed in a List view, which I also added. 

## Screencast

https://user-images.githubusercontent.com/7442307/155328208-0f6fc38b-213e-4771-9478-e478b476fc5d.mov

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by Destiner** [comment]
@niklaswa thanks for the update, looks good!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @niklaswa 👋 

Thanks for the update, it seems to do as expected, well done!

The linter is complaining about the contributors' property, you need to add your Raycast username (and not the one from GitHub) – So it's because https://www.raycast.com/niklaswa is not found – do you have an account, if not you can create one here: https://www.raycast.com/developers

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by niklaswa** [comment]
Hey @pernielsentikaer! 
I didn't know that you would need to create an account - I just did. :)

**Review by pernielsentikaer — APPROVED** [review]
Hi @niklaswa 👋 

Awesome 👏 

Again, thanks for your contribution, I'm going to approve it 💪

**Comment by sxn** [comment]
🎉

**Pull request merged**
