### PR TITLE
Add gfb extension

### PR DESCRIPTION
**Pull request by jamtur01**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Your extensions suffers from [Empty State Flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

- We have [Cache](https://developers.raycast.com/api-reference/cache) built in within Raycast, if you really want to save your own file then you should use [environment.supportPath](https://developers.raycast.com/api-reference/environment#example)

- Is there a way we can make so the user doesn't have to edit `json` files in order to configure it

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by jamtur01** [comment]
@pernielsentikaer  Oh neat!  Thanks.

1. Can fix that. 
2. I missed the built-in Cache - will replace my hack with that.
3. Can you recommend an extension that handles complex configuration? The issue is have is the user needs to go look up the specific IDs for the teams, leagues, etc. Do you know anyone who does a lookup in their preferences setup that I could take a look at.

**Comment by jamtur01** [comment]
@pernielsentikaer  Oh neat!  Thanks.

1. Can fix that. 
2. I missed the built-in Cache - will replace my hack with that.
3. Can you recommend an extension that handles complex configuration? The issue is have is the user needs to go look up the specific IDs for the teams, leagues, etc. Do you know anyone who does a lookup in their preferences setup that I could take a look at.

**Comment by jamtur01** [comment]
@pernielsentikaer  Oh neat!  Thanks.

1. Can fix that. 
2. I missed the built-in Cache - will replace my hack with that.
3. Can you recommend an extension that handles complex configuration? The issue is that the user needs to go look up the specific IDs for the teams, leagues, etc. Do you know anyone who does a lookup in their preferences setup that I could take a look at.

**Comment by jamtur01** [comment]
@pernielsentikaer  Oh neat!  Thanks.

1. Can fix that. 
2. I missed the built-in Cache - will replace my hack with that.
3. Can you recommend an extension that handles complex configuration? The issue is that the user needs to go look up the specific IDs for the teams, leagues, etc. Do you know anyone who does a lookup in their preferences setup that I could take a look at.

**Comment by pernielsentikaer** [comment]
Remember to use the  `isLoading` property in your <List> so the user can see that it's loading 🙂

Wouldn't it be possible to add an action inside the list to add it as "favourite" somehow?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Let me know when I can test this again 🙂

**Comment by jamtur01** [comment]
@pernielsentikaer, it should be good to take another look. Thanks.

**Review by pernielsentikaer — COMMENTED** [review]
I think the name confused me a lot, we already have [fotmob](https://www.raycast.com/iamlas/fotmob) in the store - did you check that one out?

**Comment by jamtur01** [comment]
@pernielsentikaer Ah okay. I searched for something but missed this entirely. It doesn't do what I want, but it's definitely prior art, so I am happy not to duplicate efforts and close this out.

**Comment by pernielsentikaer** [comment]
What about enhancing that one, thats also a possibility - I'm sure that would be okay for @sonla58

**Comment by jamtur01** [comment]
@pernielsentikaer Yes, I'm taking a look at that previous extension. Thanks.

**Pull request closed without merging**
