### PR TITLE
Add rayscan extension

### PR DESCRIPTION
**Pull request by Jds-23**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋

Thanks for your contribution 🔥 

How is this compared with all the other extensions like [DropsTab](https://www.raycast.com/nikolayqwerty/dropstab) by @Motion-Up - It feels like it's the same alley

**Comment by Jds-23** [comment]
> Hi 👋
> 
> Thanks for your contribution 🔥
> 
> How is this compared with all the other extensions like [DropsTab](https://www.raycast.com/nikolayqwerty/dropstab) by @Motion-Up - It feels like it's the same alley

Rayscan is a bit different in its use case—it's specifically designed for searching transactions across chains using a hash.

**Comment by Jds-23** [comment]
1. 0x2ba8d44ad09397d366bdcfc5c9bed20af024db0951219fa8058fbebe85ff1b39 
2. https://github.com/Jds-23/raycast-extensions/blob/ext/rayscan/extensions/rayscan/metadata/search.png already there

**Comment by pernielsentikaer** [comment]
1) Maybe implement [argument](https://developers.raycast.com/information/lifecycle/arguments) so it's faster, I was a bit confused about what to enter (maybe use a [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) and explain short what to expect)

2) The size of the metadata image is not right, if you use our tool on the built-in retina screen it should look like this (feel free to use them)

3) I'm getting this error while running the extension, do you think you can look into that?

```
08:54:09.230 (node:58974) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by Jds-23** [comment]
Which tool are you taking about here?

**Comment by Jds-23** [comment]
Haha, I was not able to reproduce it 😅. By the way, how do I use the 'built-in retina screen' that you mentioned?

**Comment by pernielsentikaer** [comment]
Did you see [this guide](https://developers.raycast.com/basics/prepare-an-extension-for-store#how-to-use-it) on how to set it up to take stunning images 🙂

**Pull request closed without merging**
