### PR TITLE
Update jetbrains extension

### PR DESCRIPTION
**Pull request by gdsmith**
## Description

More Jetbrains Toolbox V2 Updates

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @gdsmith 👋 

Thanks for the update 🔥 Could you look into the merge conflicts 🙂

**Comment by peppy** [comment]
Thanks for the quick fix! It looks to be working now, but the icon for rider seems missing on each project:

iTerm2 2023-08-23 at 10 54 40

**Comment by pernielsentikaer** [comment]
You might need to fork, like described here: https://developers.raycast.com/basics/contribute-to-an-extension

**Comment by peppy** [comment]
This was using a fork (the actual reported issue is fixed, so it's definitely working). Just reporting back that the icon still looks wrong.

**Comment by pernielsentikaer** [comment]
I was answering @gdsmith on that one 🙂 Thanks for testing it out, much appreciated 🔥

**Comment by gdsmith** [comment]
@peppy can you check to see if this change fixes the icon for you?

**Comment by pernielsentikaer** [comment]
Could you test it @peppy

**Comment by peppy** [comment]
It's on my list! Will report back within 12 hours.

**Comment by pernielsentikaer** [comment]
Awesome 👏

**Comment by peppy** [comment]
@gdsmith This is what I'm seeing now:

2023-09-08 00 24 40@2x

The icon definitely looks fixed in the main view, but I'm not sure about the dropdown.

**Comment by gdsmith** [comment]
@peppy can you try again, made some other changes based on #8057 and updated the icon handling again

**Comment by gdsmith** [comment]
@pernielsentikaer please check this for release again

**Comment by peppy** [comment]
I'm now seeing a new error message:

2023-09-08 03 33 42@2x

I double-checked back on 3fe1c5845d0e923a781c0bcd0649726a5995702b to make sure I didn't break something locally and that commit is still working as above.

**Comment by Inmovilizame** [comment]
First time here... how can I test a PR locally? I know how to fork to debug, but how to checkout this precise PR?

**Comment by gdsmith** [comment]
@peppy what is your shell scripts directory?

**Comment by LeslieLeung** [comment]
I am not quite familiar with this monorepo stuff, do I have to clone the whole repo? It's really huge(>1G).

**Comment by peppy** [comment]
> I am not quite familiar with this monorepo stuff, do I have to clone the whole repo? It's really huge(>1G).

That's what I had to do.

> @peppy what is your shell scripts directory?

I thought I had i set to default, but I'll double check in a few hours when I am at my other PC.

**Comment by Inmovilizame** [comment]
Tested locally, 

Same, working ok if ToolBox App settings I set the `Shell scripts location` to a full directory. If set to `~/bin` it fails

**Comment by gdsmith** [comment]
> Same, working ok if ToolBox App settings I set the `Shell scripts location` to a full directory. If set to `~/bin` it fails

@Inmovilizame can you just double check you are on the branch from my fork? Shell scripts supported tilde replacement before any changes were made here and I have tested that myself without issue. When you say it fails, how is it failing? Are you getting an error?

**Comment by Inmovilizame** [comment]
My bad... I was working on main branch 😅 Works well with `~/bin` in the ToolBox App 🥳 . 

Worth mentioning, seems like Fleet history is not being gathered 

Screenshot 2023-09-08 at 12 49 32

**Comment by gdsmith** [comment]
Yeah, Fleet is "special" and has a completely different way of storing projects that I'm not going near until they get nearer to releasing it (it's already changed at least twice). There's a tooltip on the "Projects Unavailable" – wondering if it may not be enough now

**Comment by Inmovilizame** [comment]
Just checked the tooltip... FMPOV fair enough. Any user of Fleet knows it's still under heavy development and should expect not to be fully integrated :) 

👍

**Comment by peppy** [comment]
This is my configuration:

2023-09-08 21 40 00@2x

2023-09-08 21 40 22@2x

**Comment by gdsmith** [comment]
@peppy what is configured in the extension for `Shell scripts location`?

**Comment by peppy** [comment]
Right, my bad! It was configured incorrectly there. After matching my install path, everything looks to finally be working correctly. Sorry for the confusion!

2023-09-08 23 49 08@2x

**Comment by gdsmith** [comment]
@pernielsentikaer okay think this is good for release 🚀

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
