### PR TITLE
Fixed some bugs for Canvascast extension

### PR DESCRIPTION
**Pull request by yug2005**
## Description

Updates : 

- Fixed a bug with loading the download urls of the module items
- Updated the icons to be higher resolution and svg format. 
- Fixed movement of pinned items. 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by YodaLightsabr** [comment]
This is incredible! I'll have a look later.

**Comment by YodaLightsabr** [comment]
Looks good!

**Comment by YodaLightsabr** [comment]
You've done a lot more work for this than I have recently, thank you so much!

**Comment by yug2005** [comment]
Yeah, for sure, I love to work on raycast stuff when I've got free time. Let me know if you wanna see any other features and I could look into them...

**Comment by yug2005** [comment]
Ready to merge?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
