### PR TITLE
Extension: Add World Holidays extension

### PR DESCRIPTION
**Pull request by jahirfiquitiva**
## Description

View upcoming holidays for many countries worldwide

Extension created as a companion for my project [World Holidays](https://world-holidays.info/)

Holidays data comes from the `holidays` python package. If your country holidays are not correct, please report the issue or contribute at the [`holidays` project](https://github.com/dr-prodigy/python-holidays).

## Screencast
world-holidays-1
world-holidays-2
world-holidays-3
world-holidays-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @jahirfiquitiva 👋 

How does this compare to [this extension](https://www.raycast.com/rodrigouroz/upcoming-holidays)? They looks quite similar actually

**Comment by jahirfiquitiva** [comment]
@pernielsentikaer 
- It shows data in a different format (does not limit to 5 results but shows all current year's holidays) and shows a random photo for the given country
- Data is more accurate (I tried the extension and it showed incorrect holidays for my country)

**Comment by pernielsentikaer** [comment]
The two extensions are so similar; almost only the data source is different. I'd suggest we hear the original author of #1864, @rodrigouroz, if data can be updated OR another endpoint can be used, or if it makes more sense that this is the extension.

It would confuse the users to have two same extensions to pick from

**Comment by jahirfiquitiva** [comment]
Btw, I've updated the command title and description as my app does not show the `upcoming` holidays, but the whole current year's list.

**Comment by rodrigouroz** [comment]
Hi, can you tell me what are the incorrect holidays? I checked for Colombia (based on the pictures) and I see the same holidays. 
Let me see where I'm getting the data from (I can't recall by heart)

**Comment by rodrigouroz** [comment]
I'm getting the data from two different sources. 
https://calendarific.com is the first option and if that fails for any reason there's a fallback to https://date.nager.at

**Comment by jahirfiquitiva** [comment]
@rodrigouroz 

From `date.nager.at` these are not holidays in Colombia
IMG_9773

And `calendarific` includes holidays that are actually workable, like: Secretaries' day, Teacher's day and others

**Comment by pernielsentikaer** [comment]
Another thing could also be to use the source that @jahirfiquitiva has instead of the current in this extension?

**Pull request closed without merging**
