### PR TITLE
Update memos extension

### PR DESCRIPTION
**Pull request by JakeLaoyu**
## Description

Fixes https://github.com/raycast/extensions/issues/12415

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by JakeLaoyu** [comment]
#12415

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by forrany** [comment]
JakeLaoyu
Hello developers, I think send Form is a great option and I'm sad to see it was removed in your PR. I usually don't even open the website and use send Form as an editor. I was very disappointed to see that the option was removed in the update. Would you consider adding it back? Thanks.

**Comment by JakeLaoyu** [comment]
@forrany Being implemented based on the new api

**Pull request merged**
