### PR TITLE
Add markdown-tools extension

### PR DESCRIPTION
**Pull request by uxkjaer**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Could you please look into the [CI errors](https://github.com/raycast/extensions/actions/runs/6529103741/job/17726263169) and let me know if you need any help resolving them?

**Comment by pernielsentikaer** [comment]
Is this ready for another review?

**Comment by uxkjaer** [comment]
yes it is, please go through it. All checks passing

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I would have this order of fields instead, hence capital letters

markdown-tools 2023-11-13 at 04 57 45

- Are you planning on bringing more to the extensions, you might need to change the name to Quick Markdown Table Generator or something like that 

- Add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Pull request closed without merging**
