### PR TITLE
Logseq extension

### PR DESCRIPTION
**Pull request by futantan**
## Description

Add a new extension for Logseq to add notes quickly.

## Screencast

https://user-images.githubusercontent.com/6268441/161554327-eb068107-cabd-4f68-9a58-ca40bbf8b03e.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by sxn** [comment]
hi @futantan - thanks for the extension! Works as intended when a correct path is specified. However, if I specify `/Users/sorin/N` (doesn't exist either as a folder or a file), trying to add a note crashes the extension 😢 
image

https://user-images.githubusercontent.com/1155589/162085199-2a3ded16-42c8-4358-89a8-7b16a02601ed.mov

**Comment by futantan** [comment]
CleanShot 2022-04-07 at 11 36 59
@sxn Thanks for your feedback! Added a hint to let user check the path.

**Comment by sxn** [comment]
🎉

**Comment by ituri** [comment]
@sxn What if my graph is stored in an iCloud folder? I tried entering `/Users/phil/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/zettelkasten` in the settings but this causes the plugin to fail.

**Comment by futantan** [comment]
> @sxn What if my graph is stored in an iCloud folder? I tried entering `/Users/phil/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/zettelkasten` in the settings but this causes the plugin to fail.

@ituri Try to use `/Users/phil/Library/Mobile Documents/iCloud~md~obsidian/Documents/zettelkasten` (remove the backslash)

**Comment by iampbernardo** [comment]
It remains in "Adding note" but neither throws an error nor performs any action.
I have tried changing the path but it is still in this mode for more than five minutes now. 

Happy to give you all the info you need for debugging.

image

**Comment by futantan** [comment]
@iampbernardo Did you configured the `:journals-directory` in file `/the-path-you-configured/logseq/config.edn`

**Comment by absir1949** [comment]
@futantan 感谢logseq扩展，已经用上啦，很棒，是否有计划在其中增加搜索功能，包括文件名搜索和全文搜索/块搜索呢？

**Comment by futantan** [comment]
@absir1949 So happy that you like it!
I'm willing to support these features if logseq provides those abilities for the extension to extend.
I also provided the ideas to the logseq team and looking forward to it!

**Comment by iampbernardo** [comment]
> @iampbernardo Did you configured the `:journals-directory` in file `/the-path-you-configured/logseq/config.edn`
Let me check that because I am not 100% sure I get your point here.

**Pull request merged**
