### PR TITLE
Add Regex REPL extension

### PR DESCRIPTION
**Pull request by hongkiulam**
## Description

Simple extension for testing regular expressions:
- The user can type in a regular expression and some text which they want to test.
- The extension will give instant feedback by underlining the matching section
- The extension will provide validation for the inputted regex

## Screencast

image
image
image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@hongkiulam 🔥

What about just having another command into the "current" extension instead?

**Comment by hongkiulam** [comment]
@pernielsentikaer fine with me :) however are you considering just dropping it in?

I feel work is needed to separate out the various concerns to ensure each command we have is clearly doing only one thing, instead of two commands which do a similar thing but in a different way

**Comment by pernielsentikaer** [comment]
What are the differences? It seems like it's doing the same but different for me.

**Comment by pernielsentikaer** [comment]
Hi @hongkiulam 👋 

Do you still want to finish this?

**Comment by hongkiulam** [comment]
Hey @pernielsentikaer, sorry for the lack of activity here.
Happy to finish it but still not sure how to fit it into the current extension... as you said they are same but different.

The existing extension allows the user to enter a test string and then proceed to test a pattern against it in the following step.
This PR allows the user to enter the pattern, modifiers and test string in a single form and receive a live result.

Packing them into the same extension seems odd to me and my preference would be to have separate extensions, but I'm sure that's not desirable on your end.

Lmk your thoughts, I'm also fine with closing this PR as I'm not too bothered whether this gets published or not

**Comment by pernielsentikaer** [comment]
I would like to have it in the store, we can go with a standalone extension. We just need to find another name(also for the folder) - can you think of anything?

**Comment by hongkiulam** [comment]
Apologies, completely forgot about this - stalebot reminded me xD Renamed to regex-repl

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
