### PR TITLE
feat(tailscale): add preferences for path and exec wrapper

### LINKED ISSUE #8273: [Tailscale] does not work with App Store installation out of the box
### Extension

https://www.raycast.com/tailscale/tailscale

### Description

The tailscale uses a hardcoded path to the tailscale executable `/Applications/Tailscale.app/Contents/MacOS/Tailscale`. But this varies depending on the installation method (tailscaled, dmg or App Store). I am not familiar with the inner workings of App Store installs or why my executable is nested in the `Tailscale.localized` folder.

I would suggest either using `tailscale` as executable like described [here](https://tailscale.com/kb/1080/cli/?tab=macos) as alias. Or add a config option to provide path to executable.

Just for reference the path for my App Store install is `/Applications/Tailscale.localized/Tailscale.app/Contents/MacOS/Tailscale`. 

### Steps To Reproduce

1. Install tailscale from App Store or only tailscaled 
2. try extension
3. will always fail because executable not found

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by erics118**
## Description

Add a preferences for setting the path to the tailscale CLI
also adds a wrapper function for calling the tailscale CLI to be more DRY

Closes #8273 

## Screencast

Nothing

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaslombart** [comment]
It seems you have the same CI error than [here](https://github.com/raycast/extensions/pull/8280#issuecomment-1713774815).

**Comment by erics118** [comment]
CI errors fixed.

**Comment by thomaslombart** [comment]
Code seems fine. I'm not using Tailscale so I'll let @samlinville, @rosszurowsk, oy @itsmingjie know if everything's good.

**Comment by thomaslombart** [comment]
I'm merging it since no one has responded to it.

**Pull request merged**
