### PR TITLE
Add finder-helpers extension

### PR DESCRIPTION
**Pull request by madebyankur**
## Description

This extension adds a set of helper actions for the finder in macOS. For now this consists of opening the context menu from raycast but will be adding more over time.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @madebyankur 👋 

Thanks for your contribution 🔥 

I just tested the extension and I can't get it to work, I end up getting this box

Raycast11042024-CAmy2bUM png@2x

and it crashes the extension

finder-helpers 2024-04-11 at 11 28 07

Do you have an idea why?

**Comment by madebyankur** [comment]
@pernielsentikaer sorry about the delay - got sidetracked with some other things. Not sure why you're seeing that - `AXShowMenu` should be available for Finder normally. Can you try running this in Script Editor:
```tell application "Finder"
	activate
	tell window 1
		set oldView to current view
		if oldView is icon view then set current view to list view
	end tell
end tell

tell application "System Events" to tell application process "Finder"
	set theSelection to value of attribute "AXFocusedUIElement"
	tell theSelection to perform action "AXShowMenu"
end tell

tell application "Finder"
	activate
	tell window 1
		if oldView is icon view then set current view to icon view
	end tell
end tell```

**Comment by pernielsentikaer** [comment]
I'm getting this error

Raycast19042024-8UH1BCDC png@2x

**Comment by pernielsentikaer** [comment]
Still getting an error, it runs for 20+ seconds and give me this error

Raycast22042024-NMyJhVCR png@2x

**Comment by madebyankur** [comment]
@pernielsentikaer I added some additional checks to make sure the finder is open.

Let me know if it's working now.

**Comment by pernielsentikaer** [comment]
I'm still getting random errors, it worked once but then I ended up in this error

finder-helpers 2024-04-29 at 22 05 22


It might be something in macOS that doesn't work as expected, do you have a clue about that?

**Pull request closed without merging**
