### PR TITLE
Color Picker: Fix color spaces differences

### PR DESCRIPTION
**Pull request by mathieudutour**
## Description

This makes sure that colors are picked without losing informations and displayed in the sRGB color space when formatted as hex

Fix https://github.com/raycast/extensions/issues/8534

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by otakustay** [comment]
https://github.com/raycast/extensions/pull/11021 is also a fix to this problem, please help to clarify the difference between us, so that I can close my PR if it is incorrectly implemented.

**Comment by mathieudutour** [comment]
Ah I didn't notice your PR sorry. I chose to use the P3 color space as the reference instead of the sRGB because it is larger (and so contains more information). So when transforming the color into another color space (like LCH), the color will be more "correct"

**Comment by otakustay** [comment]
Seems this is a better version, leave to @pernielsentikaer to determine, I'll close mine when this is merged

**Comment by pernielsentikaer** [comment]
Let's go with this one for the reasons mentioned by @mathieudutour. I also included a fix for a bug when setting a custom title in this one.

**Pull request merged**
