### PR TITLE
Add Sentry error reporting

### PR DESCRIPTION
**Pull request by SandyGifford**
## Description

Adds error reporting to Sentry (we needed a little more info than was available in `/extension-issues`)

Opened in favor of https://github.com/raycast/extensions/pull/14823 (moved to its own branch to free up `reclaim-ai:main`)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by clayton-knapp — APPROVED** [review]
LGTM!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Seems like we have the same conflicts here in main @SandyGifford

**Comment by SandyGifford** [comment]
@pernielsentikaer merge conflict cleared - ready to go!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
