### PR TITLE
Update pomodoro extension

### PR DESCRIPTION
**Pull request by MartinGonzalez**
## Description

This pull request adds slack support to update slack status when using pomodoro intervals.
2 new commands were added to not modify existing pomodoro commands.

## Screencast

https://github.com/raycast/extensions/assets/4130008/6467d10f-894f-45fb-9590-0161b5e928e5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for adding this. I think it's adding a lot of value, and I do think that you're right about having it as separate commands works.

Could you check this, @KELiON?

**Comment by MartinGonzalez** [comment]
@KELiON just pinging

**Review by KELiON — CHANGES_REQUESTED** [review]
Thanks for contribution! I like your idea and probably I'm going to use this integration, but I'd like to keep pomodoro features as simple as possible. Slack integration won't be used by all pomodoro users, some users would like to see similar integrations with other services, so it could add more complexity to the extension.

As an option, we can add this integration but make it optional. Can you please add [disabledByDefault](https://github.com/raycast/extensions/blob/1e557701ac0a5ab40004dd333d5dccd4725e81f9/docs/information/manifest.md?plain=1#L61) to new commands? This way everyone who want to use slack integration can enable these commands, but "default" pomodoro extension won't show them

**Comment by pernielsentikaer** [comment]
Thanks for the correction, let's merge it 🙂

**Pull request merged**
