### PR TITLE
Update github extension

### PR DESCRIPTION
**Pull request by xilopaint**
## Description

- Fixes icons for "Closed as not planned" and "Closed as completed" statuses in the `My Issues Menu Bar`.
- Fixes workflow icons for statuses other than "succeeded" in the `Unread Notifications` menu bar command.
- Changes the icon color of the `Unread Notifications` menu bar command for better visibility in the light menu bar.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by antonengelhardt** [comment]
Just checked it our very briefly. Nice work! Thanks a lot. @xilopaint

**Comment by antonengelhardt** [comment]
This is how it looks for me with Dark Mode on...

Screenshot-Arc-006354@2x

**Comment by antonengelhardt** [comment]
This is how it looks for me with Dark Mode on. 

Screenshot-Arc-006354@2x

**Comment by xilopaint** [comment]
> This is how it looks for me with Dark Mode on.

Are you sure you are testing my PR and not yours? This is how it looks to me in Dark Mode:

Screenshot 2024-03-25 at 08 17 10

**Comment by xilopaint** [comment]
> Yes, i am on commit [0640581](https://github.com/raycast/extensions/commit/0640581d1729a64bb8d4f631326b7e880e6f893d), running `npm run dev` and see two menu bar items. Both are having this issue.

If both menu bar items show black icons on dark mode so it's not an issue introduced by this PR. Anyway, I can't reproduce the issue. Could you test with different wallpapers? Do you have any issues with the `Notifications` command?

**Comment by xilopaint** [comment]
Have you tried to test it with different wallpapers? How does it look if you use some of the macOS built-in wallpapers?

**Comment by antonengelhardt** [comment]
Tried "Sonoma", "Monterey", "Ventura", "Sonoma Horizon" and all the same. I think it might be related to theme i am using (Overcast and Sky). But dont worry about it, not "related" to this PR.

**Comment by xilopaint** [comment]
What are Overcast and Sky?

**Comment by antonengelhardt** [comment]
Screenshot-Raycast-006369

**Comment by xilopaint** [comment]
I can't reproduce your issue with these themes. Anyway, it's not something related to this PR.

**Review by thomaslombart — APPROVED** [review]

**Pull request merged**
