### PR TITLE
Add hoarder-bookmark extension

### PR DESCRIPTION
**Pull request by foru17**
## Description

A user-friendly Raycast extension that seamlessly integrates with [Hoarder](https://github.com/hoarder-app/hoarder), bringing powerful bookmark management to your fingertips. Quickly save, search, and organize your bookmarks, texts, and images—all through Raycast's intuitive interface.

This extension leverages Hoarder's API to provide a streamlined experience for managing your digital collection, complete with AI-powered tagging and search capabilities.

## Screencast

hoarder-bookmark-1
hoarder-bookmark-2
hoarder-bookmark-3
hoarder-bookmark-5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

Did you see [this](https://www.raycast.com/kdurek/hoarder) extension before creating this one?

**Comment by foru17** [comment]
Hi! Yes, I reviewed the Hoarder extension before developing this one. While there's an existing extension that provides basic list functionality, I saw an opportunity to create a more comprehensive solution with proper documentation following Raycast's guidelines.

This new extension offers a complete Hoarder integration experience with full CRUD operations, tag management, and AI features, along with a more polished UI that closely follows Raycast's design principles. I've also documented everything thoroughly to help users get started easily.

I've reached out to the Hoarder project maintainer about this extension, and they've shown their support by starring the project, which I believe validates its value to the ecosystem.

Let me know if you'd like to know more about any specific aspects!

**Comment by pernielsentikaer** [comment]
It still sounds like an enhancement instead of another version of the same extension with more capabilities

@kdurek What do you think?

**Comment by kdurek** [comment]
Hey, yeah I waited for better enhancements to rest api from maintainer of hoarder, but this one does really good upgrades to my extension functionality so feel free to do whatever seems best for both extensions, including replacing my own :D

**Comment by pernielsentikaer** [comment]
So @kdurek, do I understand this correctly?

We're letting this completely overwrite yours, and then we'll move you to contributors instead (if you'd still like that) 😊

**Comment by kdurek** [comment]
That's what I wanted to propose, wanted to leave me in history of extension or something but didn't know it's possible :D Don't mind this replacing my extension, it seems really good upgrade!

**Comment by pernielsentikaer** [comment]
@foru17 so what we're going to do is that you move your code to overwrite the current (extensions/hoarder/)

Can we use the same preferences so the end user is not interrupted, is that possible?

**Comment by kdurek** [comment]
@foru17 Thank you for your kind attitude and words ❤️  Hope I will be able to help or contribute in future!

**Comment by pernielsentikaer** [comment]
You just add below to the package.json somewhere (I use to have it under `"author"`:

```
"contributors": [
  "kdurek"
],
```

**Comment by foru17** [comment]
I've published the changes using npx @raycast/api@latest publish which automatically created PR #15810. 

This PR moved the code to replace the original hoarder extension and made the preference fields compatible. 

Just want to confirm - is this the right process, or should I have done something differently?

**Comment by pernielsentikaer** [comment]
Closing in favor of https://github.com/raycast/extensions/pull/15820

**Pull request closed without merging**
