### PR TITLE
Add cht-sh extension

### PR DESCRIPTION
**Pull request by BrandenXia**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Is there a way to show the data on the initial load? First time I enter the command it just says `No Result` - if I search for anything and re-enter the command it has the list populated

cht-sh 2023-05-30 at 20 00 38

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by BrandenXia** [comment]
I change some part of the code, and now it should work properly. Can you review it again? Thank you.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

It works much better now 🔥

The extensions suffer from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
The empty state flicker is now gone, awesome!

I'm still a bit confused about how to use it, if I go to PHP I see this view

cht-sh 2023-06-07 at 08 46 17

If I use the action to Open Cheatsheet here I just see this

cht-sh 2023-06-07 at 08 46 41

Is something missing?

**Comment by pernielsentikaer** [comment]
I'm still not convinced that it adds a lot of value, the fist more than 20 items don't have any data, and it seems like the list is a mix of languages/software/commands - can you help me understand @BrandenXia

**Comment by BrandenXia** [comment]
> I'm still not convinced that it adds a lot of value, the fist more than 20 items don't have any data, and it seems like the list is a mix of languages/software/commands - can you help me understand @BrandenXia

Those cheatsheets are actually different categories. If you go to 7z, for example, and type in some keywords like `compress`, it will search for `compress` in this category and find some corresponding code example.
Screenshot 2023-06-13 at 2 45 09 PM

**Comment by pernielsentikaer** [comment]
How would I best find this in the extension? https://cht.sh/a2disconf

**Pull request closed without merging**
