### PR TITLE
Add wise-quotes extension

### PR DESCRIPTION
**Pull request by HugoLiconV**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- If you set `USD` as the target the extension crashes, could you fix this gracefully?

- Add a placeholder to the default target input in `package.json` 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by HugoLiconV** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * If you set `USD` as the target the extension crashes, could you fix this gracefully?
> * Add a placeholder to the default target input in `package.json`
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Hey @pernielsentikaer thanks for the review, here are the latest changes: 

* I added a better error message and some actions to correct the error
* I found out that while you're writing the target currency in the extension settings, you're getting some errors, that's because every time you write a character a request is made. I fixed this by also showing a better error message.
Let me know if this solves your comment. Thanks :slightly_smiling_face:

https://github.com/raycast/extensions/assets/22970186/c6e4ebab-f98a-428e-9de8-1ba36f15662b

image

**Comment by pernielsentikaer** [comment]
If you in this view just press enter, then it dies, could you handle this gracefully?

Raycast 2023-08-28 at 12 05 08

wise-quotes 2023-08-28 at 12 04 48

**Comment by HugoLiconV** [comment]
@pernielsentikaer Nice catch with that bug! Should be fixed now

image

**Comment by HugoLiconV** [comment]
Hey @pernielsentikaer 
Any update on this PR?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
