### PR TITLE
Improve ToolBox extension

### PR DESCRIPTION
**Pull request by kkange**
## Description

Add further improvements to the ToolBox extension:

- Added 25 scripts and Script classification has been subdivided
- Added option to set whether to close the extension tool after copying the result
- Improve script execution types.

## Type of change

- Bug fix / improvement for my extension

## Screencast
스크린샷 2021-12-07 21 16 59

more Screencast
https://imgur.com/a/rbbtst9

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @kkange 🔥 

Thanks for the update, the toolbox is growing! 😄 

I small comment about SQL formatter, for me the formatter is not as I would expect it:
- Shouldn't LIMIT be possible?
- Shouldn't the fields not all of them go to next row?

6lVqV1sbvXaKTER0

Could be that my knowledge is a bit outdated here 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by kkange** [comment]
> Hi @kkange 🔥
> 
> Thanks for the update, the toolbox is growing! 😄
> 
> I small comment about SQL formatter, for me the formatter is not as I would expect it:
> 
> * Shouldn't LIMIT be possible?
> * Shouldn't the fields not all of them go to next row?
> 
> 6lVqV1sbvXaKTER0
> 
> Could be that my knowledge is a bit outdated here 😄
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.


This was reflected through library changes.

Added an option to select an action after copying the result.

스크린샷 2021-12-13 19 25 54

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @kkange 👋 

It seems like it makes no difference whether I select none/back or exit in the preferences, the window always closes, can you look into this behaviour?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by kkange** [comment]
Hi @pernielsentikaer 

Thank you for the feedback.


The function that I intended is not whether Windows will be shut down or not.
If you copy the value, the window is always closed.
It's just that this setting supports the following actions.

- 'None' type doesn't move the window.
- 'Back' type goes back to ToolBox's function list.
- 'End' type ends ToolBox extension and returns to RayCast main window.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @kkange 

I think it's because it's called “Exit” in the preferences (Action after copy) – It's at least misleading me 😄 

- I can see that the SQL formatter don't recognize “OFFSET” which also is valid (at least in MySQL)

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by kkange** [comment]
Hi @pernielsentikaer 

 I don't know how to express it well. Please help me.
` I think it's because it's called “Exit” in the preferences (Action after copy) – It's at least misleading me`


You have to select sql language (sql, mysql, postgresql) to process what you pointed out in SQL formatter.
Currently, I am not planning to give options for each function.

**Comment by pernielsentikaer** [comment]
> I don't know how to express it well. Please help me. 

Could it be something like "Pop to root"

**Comment by pernielsentikaer** [comment]
Hi @kkange 👋 

Are you ready to proceed with this in order to be ready to merging it?

**Comment by pernielsentikaer** [comment]
Hi @kkange 👋 

I'm closing this due to inactivity, we can open anytime when you're ready to proceed 💯

**Comment by kkange** [comment]
> Hi @kkange 👋
> 
> I'm closing this due to inactivity, we can open anytime when you're ready to proceed 💯

Okay, I'm going to start again.

**Comment by kkange** [comment]
Hi @pernielsentikaer 

I'm ready. Can I open it again?

**Pull request merged**
