### PR TITLE
Add HTTP.cat extension for visual HTTP status codes with fancy cats 🐈‍⬛🐈

### PR DESCRIPTION
**Pull request by lucasmezencio**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Works as expected, maybe you could add a way to copy the image to the clipboard too? You can see how it's done in the [GIF extension](https://github.com/raycast/extensions/tree/main/extensions/gif-search) 🙂

**Comment by lucasmezencio** [comment]
> Works as expected, maybe you could add a way to copy the image to the clipboard too? You can see how it's done in the [GIF extension](https://github.com/raycast/extensions/tree/main/extensions/gif-search) 🙂

@pernielsentikaer that's an awesome idea! Will do!

**Comment by lucasmezencio** [comment]
@pernielsentikaer there you go! 😊

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
