### PR TITLE
Add Toggle Desktop visible extension

### PR DESCRIPTION
**Pull request by Haojen**
## Description

You can toggle the Desktop file and folder Show and Hidden. sometimes we don't want to see the Desktop have so many files or folders,
So the extension can help you, you can easily switch to Desktop visible.

For more detail see readme: https://github.com/Haojen/raycast-ToggleDesktopVisible

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by sxn** [comment]
Sure thing! 

image

**Comment by sxn** [comment]
hi @Haojen - any news? 😸

**Comment by Haojen** [comment]
> hi @Haojen - any news? 😸

For now, I'm trying to fix my another Raycast extension Parrot-translate, This extension I think will need more time to fix it. Also, my device is M1, OS same too, don't understand the error why happened

**Comment by Haojen** [comment]
> me again! 😸 since your busy, I took a bit of time to update the extension so that it uses `spawnSync` instead of `exec` & handles the case where the entry is missing (which was the case for me).
> 
> Hope that's fine! ❤️

❤️ Thank you help me to fix this bug, I am busy with my studies now. It is very kind of you to help me solve this problem. Later, I will merge it into my local code and test it again to make sure everything is OK

**Comment by Haojen** [comment]
I've tested it. It's all good. Thanks again for your help

**Pull request merged**
