### PR TITLE
Add wta-rankings extension

### PR DESCRIPTION
**Pull request by drillprop**
## Description

This extension is basically raycast version of these rankings presented on this site https://live-tennis.eu/en/wta-live-ranking.
As a big fan of tennis I found myself that I'm checking the website too often 😄  so I decided to create an extension, to make this easier. 

## Screencast

https://github.com/raycast/extensions/assets/51168865/ee0b4201-8937-4655-81ea-3b39041492db

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by drillprop** [comment]
Ok, I found that there is another extension that covers ATP and WTA rankings https://www.raycast.com/Zalgo_123/tennis-standings. 
That's bad timing from my side because when I started developing my extension there were no WTA rankings at that time. As far as I checked, WTA standings were added last week. In fact, even in README, there is no mention of the WTA(women's tennis association). 
image

I still think my extension is worth adding. The [current tennis standings](https://www.raycast.com/Zalgo_123/tennis-standings) extension has a lot of downsides: 

- they don't show "live" ranking. They only show published ranking, which is updated once a week(as far as I remember). That's a deal breaker for me because I want to know how points and positions will change after a certain player wins a match or tournament. I don't want to wait for the official update of the ranking. 
- they don't show any information about a player. Check these screenshots below: 
my extension: 
image
tennis standings: 
image

- there is no information about the current tournament, next points, max points, country rank etc. 
- there is no information about ranking change and points change
- It's a matter of preference, but IMO the tennis standings extension is much less readable. I think there is a redundant tennis icon on the left, which doesn't add any value, and there are no flags. I found the points icon also blurry and incomprehensible for me. 
-  There is no race ranking. For explanation - the players with the highest point totals in the WTA Race Ranking qualify for prestigious season-ending tournaments like the WTA Finals. It's very useful to track these by tennis fan. 
- In my extension, I added the action `Show player in ranking` which is handy when you want to search a player and check his ranking in context to other players. You can't do this in tennis rankings 
image 

Also, I can easily add the same rankings for ATP(live and race), because I have control over the API. I also planned to add official rankings. 

Let me know what you think. If you find this extension redundant, I'll understand your decision(although I'll be a little bit sad 😅 , because I spent some time on it).

**Comment by pernielsentikaer** [comment]
That's correct; it was recently updated with WTA by @xilopaint. What about enhancing the current extension? That would make sense, wouldn't it?

**Comment by drillprop** [comment]
@pernielsentikaer Yeah, that would make sense, I'll try to update the `tennis standings` extension today or in the following days.

**Comment by pernielsentikaer** [comment]
That sounds like a nice thing; it would definitely be awesome. Should we close this PR or mark as draft until?

**Comment by drillprop** [comment]
> That sounds like a nice thing; it would definitely be awesome. Should we close this PR or mark as draft until?

Yeah, sorry, I forgot to close it 👍🏻

**Pull request closed without merging**
