### PR TITLE
New extension: Menubar Weather

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

Show current weather on the menu bar. Weather information updated every 10 minutes.

> How to get the OpenWeather Api key?
>
> 1. Go to and login to [OpenWeather](https://openweathermap.org) official website, (if you don't have an account, create one).
>
> 2. Click your username in the upper right corner, and click **My API Keys** in the pop-up list to enter the API Keys page.
>
> 3. Copy the default key or create a new API Key, copy the key after you finish creating it.

## Screencast

SCR-20221121-rsg

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
This is cool! Looking forward to see a lot of rainy clouds for London in my menu bar :D

**Comment by kud** [comment]
@thomaspaulmann Hahah don't say that please. Just arrived in London to live here, hope I won't see this in my menu bar. :p

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I can't get this to work @koinzhang, see attached image.

I checked:
* API key (Made three different)
* Tried three cities

```
> dev
> ray develop

info  -  entry points [src/menubar-weather.tsx]
ready -  built extension successfully
13:55:08.704 
AxiosError: Request failed with status code 401

settle:settle.js:19:11

---
16:   if (!response.status || !validateStatus || validateStatus(response.status)) {
17:     resolve(response);
18:   } else {
19:     reject(new AxiosError(
20:       'Request failed with status code ' + response.status,
21:       [AxiosError.ERR_BAD_REQUEST, AxiosError.ERR_BAD_RESPONSE][Math.floor(response.status / 100) - 4],
22:       response.config,
---

IncomingMessage.handleStreamEnd:menubar-weather.js:12307:11
IncomingMessage.emit:node:events:525:35
endReadableNT:readable:1359:12
```

Raycast-xmvLtCLr@2x

Do you have a clue what might cause this @koinzhang 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by koinzhang** [comment]
Hi @pernielsentikaer. I have fixed the NAN error, please keep reviewing.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @koinzhang 

Do you think you can fix the last flicker, maybe use one of the hooks from @raycast/utils when caching the data between loads?

https://user-images.githubusercontent.com/38033107/203242472-f115c820-bf11-4eb2-b234-9091a64e2623.mp4

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by koinzhang** [comment]
Hi @pernielsentikaer. 
I have fixed the blinking bug, please keep reviewing.
Other updates:
1. Add new information
2. No longer networked to get weather when user-initiated commands are invoked (reduces the number of API calls)

**Comment by pernielsentikaer** [comment]
Hi @koinzhang 👋 

It works as expected now, you should actually be able to simplify the entire extension if you use [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch?q=usefetch) instead since it has all the logic already - but it's not something that we need to look into now 😊

**Comment by koinzhang** [comment]
I haven't used UseFetch yet, and I'm not familiar with him, so I didn't use it in the extension

**Comment by pernielsentikaer** [comment]
That's a valid point for sure, let's continue as is for now and I can show you one day soon 😊

**Review by pernielsentikaer — APPROVED** [review]

**Comment by ron-myers** [comment]
@pernielsentikaer - I am interested in this extension - the link above doesn't seem to work. Did `Published to the Raycast Store:` fail?

**Comment by pernielsentikaer** [comment]
It will soon be there again - just sorting out a few things

**Pull request merged**
