### PR TITLE
Update search-project-manager-projects.tsx

### PR DESCRIPTION
**Pull request by eduwass**
Add support for Cursor as editor 
http://cursor.sh

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by MarkusLanger** [comment]
Is it possible to use the Project Manager Extesion (https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) with the Cursor editor?

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @eduwass 🔥  Could you check the CI errors and add a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry?

@MarkusLanger everything possible in code should work the same in cursor 🙂

**Comment by eduwass** [comment]
Hi @pernielsentikaer, 

I'm not sure how to proceed with this PR. When I used the command `npx @raycast/api@latest publish`, it created a new PR instead of continuing the current one. My latest work can be found here: https://github.com/raycast/extensions/pull/9392 

We can close this PR and prioritize the new one. Alternatively, if you could provide some guidance, I can make edits to this PR. 

Please let me know. 

Apologies for any confusion!

**Comment by pernielsentikaer** [comment]
You should also be able to edit your files directly on GitHub in your branch, when you save there it reflects files here too

**Comment by eduwass** [comment]
Thanks @pernielsentikaer I'll take that into account for next time.

Closing this in favor of https://github.com/raycast/extensions/pull/9392

**Pull request closed without merging**
