### PR TITLE
Remove non used Todo type in the todo-list example

### PR DESCRIPTION
**Pull request by JuanVqz**
## Description

I followed the todo-list example and noticed that the Todo type was not used in the `CreateTodoAction.tsx` file. Therefore, I removed it because it could be confusing for some developers.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
  (But I got `zsh: command not found: ray`
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Where do you see that, here? https://developers.raycast.com/examples/todo-list

**Comment by JuanVqz** [comment]
> Where do you see that, here? https://developers.raycast.com/examples/todo-list

Hi @pernielsentikaer, I was following the todo-list example in the code itself. I didn't even check if there was a page, which is good to know :)

**Review by pernielsentikaer — APPROVED** [review]
Thanks for the correction 🙏

**Comment by JuanVqz** [comment]
> Thanks for the correction 🙏

Thanks for the great tooling you facilitate for my workflow

**Pull request merged**
