### PR TITLE
fix: handled spacing for each list item

### LINKED ISSUE #9719: [GitHub Stars] not displaying full number of star
### Extension

https://www.raycast.com/mrmartineau/search-github-stars

### Description

If the project has long description, the star number may not be properly displayed (some digits are hidden which makes the number totally meaningless)

### Steps To Reproduce

For example if you star https://github.com/EleutherAI/lm-evaluation-harness, you will reproduce it.

I am using a macbook pro 16inch, with the default resolution.

image

### Current Behaviour

Some digits of the star number are hidden

### Expected Behaviour

Show something like 3.2K/3200 which can be fully displayed

### PR DESCRIPTION
**Pull request by Princeyadav05**
## Description

Extension: [Github Stars](https://www.raycast.com/mrmartineau/search-github-stars)

This update addresses an issue where the display of stars was not rendering correctly for projects with lengthy descriptions.

Changes Implemented:
1. Implemented logic to handle larger numbers of stars, converting them to a more readable format (e.g., 320000 becomes 320.0K).
2. Added logic to calculate the remaining characters available for the description after accounting for the repository name and stars length

Fixes #9719 

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@mrmartineau do you want to check this? 🙂

**Comment by Princeyadav05** [comment]
@pernielsentikaer I was able to fix the issue using textSize. However, I'm getting a linting error.

"TS2339: Property 'textSize' does not exist on type 'Environment'"

image

I did check the environment object in raycast/api node modules but it doesn't have textSize property.

image


Can you guide me on what I'm missing here?

**Comment by pernielsentikaer** [comment]
Can you try to push it, so I can see it @Princeyadav05 🙂

**Comment by Princeyadav05** [comment]
@pernielsentikaer pushed. Please check.

**Comment by pernielsentikaer** [comment]
It's because the API version is WAY too old, try to run `npx @raycast/migration@latest .` to update to the newest version (which also changes the code)

**Comment by Princeyadav05** [comment]
@pernielsentikaer I've made all the changes. The build is working fine locally. However, the check "Extension /check" is failed due to the following reasons. 

"ESLint couldn't find the config "prettier" to extend from. Please check that the name of the config is correct.

The config "prettier" was referenced from the config file in "/Users/runner/work/extensions/extensions/extensions/github-stars/.eslintrc.json"."

**Comment by pernielsentikaer** [comment]
Now you should get a real error, I think it's the last one 😅

**Comment by Princeyadav05** [comment]
@pernielsentikaer fixed all.

image

image

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
