### PR TITLE
[Everhour] fix #14813 | add conditional verifying Task has time property

### LINKED ISSUE #14813: [Everhour Time Tracking] ... "Failed to fetch projects"
### Extension

https://www.raycast.com/farisaziz12/everhour

### Raycast Version

1.83.2

### macOS Version

15.0.1 (24A348)

### Description

Both "Recent Tasks" and "Active Projects" are not working.
I'm getting this error description "Failed to fetch projects Cannot read properties of undefined (reading 'total')"

### Steps To Reproduce

1. Open "Recent Tasks" and "Active Projects"
2. And immediately you'll see the error, as it can't connect to the data
Screenshot 2024-10-07 at 11 25 20

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by teisenhower**
## Description

Closes #14813. 

The issue discovered is there are times when tasks do not have the expected `time` property which would cause a `Cannot read properties of undefined (reading 'total')` error. This PR aims to resolve this issue by checking for the existence of the `time` property prior to it being needed. 

#### Before

https://github.com/user-attachments/assets/35b10199-c6b1-493d-b747-f0fe36ba6ef5

#### After
after - projects

after - tasks

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by xmok** [comment]
Seems to be working fine 🤔.
Would it be possible for you to share a `Before and After` screencast so it can act as a reference for the future?

**Comment by teisenhower** [comment]
> Seems to be working fine 🤔. Would it be possible for you to share a `Before and After` screencast so it can act as a reference for the future?

Absolutely! I've update the description with those examples. I just had to grey out the projects and tasks as I am not sure that I should openly share those.

**Comment by xmok** [comment]
Ah man I missed one thing!
Please change the date in CHANGELOG to be `{PR_MERGE_DATE}` so it is updated automatically.

**Comment by teisenhower** [comment]
@xmok No problem! I updated that! Thank you!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
