### PR TITLE
feat: better sentence case

### LINKED ISSUE #9691: [Change Case] ... Punctuation Removal and Text Merging in Sentence Case Conversion
### Extension

https://www.raycast.com/erics118/change-case

### Description

When using the Change Case extension to convert text to 'Sentence case,' I've encountered a significant issue where all punctuation in the original text is removed. This includes commas, colons, periods, ampersands, exclamation points, and dashes. Additionally, this leads to all the text merging into a single, continuous sentence, thereby altering the intended structure and meaning of the text.

**Example:**
Converting the text "The Quick, Brown Cat & Slow Dog Are Friends. They live happily." using the 'Sentence case' option results in "The quick brown cat slow dog are friends they live happily," where all punctuation is missing and the text becomes one long sentence.

This issue persists even when the latest version of the extension and Raycast is used.

### Steps To Reproduce

1. Select text with punctuation and multiple sentences (e.g., "The Quick, Brown Cat & Slow Dog Are Friends. They live happily.").
2. Run the Change Case command in Raycast.
3. Choose the 'Sentence case' option.
4. Observe that the output text lacks all punctuation and merges into a single sentence.

### Current Behaviour

The current output when converting to 'Sentence case' removes all punctuation from the original text and merges multiple sentences into one continuous sentence.

### Expected Behaviour

The expected behavior is for the text to change case to 'Sentence case' while retaining all original punctuation and sentence structure. The ideal output for the above example should be "The quick, brown cat & slow dog are friends. They live happily."

### PR DESCRIPTION
**Pull request by erics118**
## Description

Fixes #9691

Improves sentence case to keep punctuation.

Using the text: 
`this is a sentence. this is a sentence. this is a sentence.`
Before: 
`This is a sentence this is a sentence this is a sentence`
Now: 
`This is a sentence. This is a sentence. This is a sentence.`

## Screencast

no

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
HI @erics118 👋 

Do you mind resolving the conflicts?

**Review by pernielsentikaer — APPROVED** [review]
Approved ✅

**Comment by jahoseph** [comment]
There seems to be a small bug. 

Using the change case's sentence case transform on the following text: "This Is A Sentence. This Is A Sentence." 

Currently results in: "This Is A Sentence. This Is A Sentence.".

Whereas it should result in: "This is a sentence. This is a sentence."

**Comment by jahoseph** [comment]
Can you check that this is working as you expect? 

For me, using the change case's sentence case transform on the following text: "This Is A Sentence. This Is A Sentence."

Currently results in: "This Is A Sentence. This Is A Sentence.".

Whereas it should result in: "This is a sentence. This is a sentence."

**Pull request merged**
