### PR TITLE
feat(regenradar): add extension for german regenradar

### PR DESCRIPTION
**Pull request by NicolaiSchmid**
## Description
A new extension, displaying the German rain radar upon request. 

## Screencast
regenradar-1

regenradar-2

(This is the only screen, no further configuration)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪

The extension seems to be working as expected, I have some feedback for you:

At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

Can you come up with a better naming of extension and command?

Raycast will cache the image so you won't see a new one, could you add a parameter to the URL, maybe something that will update every 15 minutes using Date? Let me know if you need help here 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by NicolaiSchmid** [comment]
I'll fix the caching issue right away.
Regarding the i18n, I'm not sure if renaming it to an English command is actually preferred. This extension will only ever display the German rain radar. So having it scoped, using the German term, is a UX signifier to what the command is supposed to do. Additionally, I'm just reusing the name the DWD (German weather organization) is using itself. If it were a command regarding the “VW” car brand, you wouldn't start translating it to “people's car” (Volkswagen ⇾ people's car).
Let me know your thoughts

**Comment by NicolaiSchmid** [comment]
Any idea where the lint is failing?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
