### PR TITLE
Add extension: DEVONthink

### PR DESCRIPTION
**Pull request by kudrykv**
## Description

Create a new extension that allows searching through DEVONthink databases.

The extension uses DEVONthink search, meaning you can use the same search operator as in the app.

## Screencast

CleanShot 2022-08-12 at 08 20 18

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @kudrykv 👋 

Thanks for your contribution 🔥 

I can't get it to work, nothing happens when I'm searching 😞🫠

CleanShot 2022-08-12 at 07 56 22@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by GastroGeek** [comment]
@pernielsentikaer not to interject but noticed this PR has been sat for a while... so I tested it and it _does_ appear to work quite well? 

I assume you had a document in DEVONthink called 'clean code' set up during testing otherwise it would not return any results? Also try the 'partial match' of `~clea` and that should also return something (assuming you have a file named appropriately of course).

**Comment by pernielsentikaer** [comment]
@GastroGeek, thanks for taking a look too; we had some bugs in Ventura that we had to clear before it was possible to go further with this (it kept saying that Devonthink was not installed)

@kudrykv / @GastroGeek, is this intended? It looks like the matching is a bit off.

https://user-images.githubusercontent.com/38033107/188555787-141ccf9b-f37e-4e9b-a0df-5975f453ed68.mp4

**Comment by kudrykv** [comment]
@pernielsentikaer, yes, that is intended. I'm delegating the search to DEVON itself, and it does that.

To find notes, that start with `hel`, you need to search for `hel*`

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
