### PR TITLE
[Xcode] Add Swift Package

### PR DESCRIPTION
**Pull request by SvenTiigi**
## Description

Added `Add Swift Package` command to quickly add a Swift Package from a url to a Xcode project.

## Type of change

- Bug fix / improvement for my extension

## Screencast

https://user-images.githubusercontent.com/11733014/142758486-93582e19-a71e-42a3-8152-383c58f396da.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @SvenTiigi 👋 

What an extension! I'm not using Xcode (that much) but it feels like this can help a lot out there! 

- There is a unique “key” prop issue that we need to address

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `projects_command_default`. See https://reactjs.org/link/warning-keys for more information.
    at ks (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:68:27832)
    at null.projects_command_default (/Users/pernielsentikaer/Desktop/rc2/extensions/xcode/src/projects.command.ts:14:45)
    at ray-navigation-stack
    at nm (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:10558)
    at al (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:10663)
    at Is (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:9779)
    at QO (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:8740)
    at ray-root
    at Ef (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:10083)
```

Besides that I couldn't find anything, I'm going to give it another test when above is addressed.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by SvenTiigi** [comment]
Hi @pernielsentikaer

Thanks for the heads up to the "unique key prop" warning.
I'm also getting this warning in the console but couldn't find the exact reason why this is happening.
The List.Item `key` of each Xcode project is set to the `filePath` of the project and therefore the key should be unique.

https://github.com/raycast/extensions/blob/c46757271fed90d2a03cab47504675f1add3f132/extensions/xcode/src/user-interfaces/xcode-projects/xcode-project-list-item.user-interface.tsx#L15

I've also checked the file paths that are generated on my machine and found no duplicates.

Additionally, I have reduced the list to just two entries as seen in the screenshot and even in this scenario the "unique key prop" warning appears even tough the keys/filePaths are different 🤔

Screenshot

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `projects_command_default`. See https://reactjs.org/link/warning-keys for more information.
    at ks (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:68:27832)
    at null.projects_command_default (/Users/sventiigi/Developer/Javascript/extensions/extensions/xcode/src/projects.command.ts:14:45)
    at ray-navigation-stack
    at nm (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:10558)
    at al (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:10663)
    at Is (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:9779)
    at QO (/Applications/Raycast.app/Contents/Resources/RaycastCommands_RaycastCommands.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:24:8740)
    at ray-root
```

**Comment by SvenTiigi** [comment]
Hi @pernielsentikaer 

The https://github.com/raycast/extensions/pull/394/commits/4c4550ef7d281996a6543a50f7076728efd2507c commit fixes the `Each child in a list should have a unique "key" prop` warning 👌

It seems like the warning has occurred because the `OpenAction` and `ShowInFinderAction` were missing a `key` attribute.

```
<OpenAction
  key="open-with-xcode"
  title="Open with Xcode"
  target={xcodeProject.filePath}
/>
<ShowInFinderAction
  key="show-in-finder"
  path={xcodeProject.filePath}
/>
```

**Review by pernielsentikaer — COMMENTED** [review]
Hi @SvenTiigi 👋 

Thanks for the update, and sorry for not being clear what caused the error, I thought that I wrote it, but I can see that I didn't, for that I'm sorry.

It's a huge extension with a lot of commands and files, I can't test it myself, since I can't uninstall my xcode, but it seems like it should handle errors about missing xcode gracefully (and not just dying) — correct?

**Comment by SvenTiigi** [comment]
Hi @pernielsentikaer 

Yes thats correct all errors are handled gracefully via either a failure Toast or an HUD explaining the error as well as logging the error to the `console.error`. A general availability check if Xcode is installed is currently not implemented.

**Comment by unnamedd** [comment]
Hi @SvenTiigi, this error about the `key` isn't really clear and I got myself taking our my hair trying to figure out, however the solution is tricky to understand, but easy to fix:

```typescript
<List
  isLoading={!xcodeProjects}
  searchBarPlaceholder="Search for Xcode Projects or Swift Packages">
  {xcodeProjects?.map(project => (
    <xcodeProjectListItem // <- you current element, where you already have the key props being configured
      key={ project.filePath } // <- here is where you need to set you key as well
      xcodeProject={ project }
    />
  ))}
</List>
``` 

As you are creating an element called `xcodeProjectListItem` and using it inside a map, this is the place where you need to set the `key` props. Copy the code above, paste into your extension and you will see that error gone!

**Review by pernielsentikaer — APPROVED** [review]
Hi @SvenTiigi 👋 

I can confirm that the latest commit, 4c4550e, fixed the problem I encountered. I don't get any errors with the commands 💯 

I'm going to accept this, my college will do the last check later today 💪

**Comment by SvenTiigi** [comment]
> Hi @SvenTiigi, this error about the `key` isn't really clear and I got myself taking our my hair trying to figure out, however the solution is tricky to understand, but easy to fix:
> 
> ```ts
> <List
>   isLoading={!xcodeProjects}
>   searchBarPlaceholder="Search for Xcode Projects or Swift Packages">
>   {xcodeProjects?.map(project => (
>     <xcodeProjectListItem // <- you current element, where you already have the key props being configured
>       key={ project.filePath } // <- here is where you need to set you key as well
>       xcodeProject={ project }
>     />
>   ))}
> </List>
> ```
> 
> As you are creating an element called `xcodeProjectListItem` and using it inside a map, this is the place where you need to set the `key` props. Copy the code above, paste into your extension and you will see that error gone!

Thanks @unnamedd for the hint 🙏
Even tough this commit https://github.com/raycast/extensions/commit/4c4550ef7d281996a6543a50f7076728efd2507c  has fixed the key warning I will also try your solution in the next maintenance PR for the Xcode extension.

**Pull request merged**
