### PR TITLE
Add lunar-client-server-mappings extension

### PR DESCRIPTION
**Pull request by Tuchan**
## Description

This extension allow you to better visualise and search through [Lunar Client's Server Mappings](https://servermappings.lunarclientcdn.com/servers.json) directly in Raycast! It also allows you to join the server directly or copy the specific part of a json response, to only include the specified server data.

## Screencast
lunar-client-server-mappings-1
lunar-client-server-mappings-2
lunar-client-server-mappings-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Tuchan** [comment]
considering soundboard extension already has a [.gitignore with .DS_STORE](https://github.com/raycast/extensions/blob/main/extensions/soundboard/.gitignore) inside of it, can the changelog check be ignored?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

I don't know anything about Lunar, but could we handle if I don't have anything installed? (Like showing an List.EmptyView if it's not running?

**Comment by Tuchan** [comment]
You don't need anything installed since you access the data from lunar client's cdn.
https://github.com/Tuchan/raycast-extensions/blob/65cb1be14191d3e60c6ed4e714af8d32c7572c5f/extensions/lunar-client-server-mappings/src/view.tsx#L80-L88
After which it is getting cached for a day. You can obviously force reload the cache if you need to.

If for some reason you can't access the link, you will get an error.
image

The only thing that accesses Lunar Client in some way, is this:
https://github.com/Tuchan/raycast-extensions/blob/65cb1be14191d3e60c6ed4e714af8d32c7572c5f/extensions/lunar-client-server-mappings/src/view.tsx#L202-L206

Lunar automatically handles server connections, so the only thing you need to do is specify a deeplink. 
If you don't have it installed, it will just not work. I will add an error message if you try to select the `Join the Server` option but you don't have Lunar Client installed.

**Comment by pernielsentikaer** [comment]
Yesterday I just got some weird state where nothing was shown, today it works as expected 🙂

Can we move the preference about ToS to the README file instead

**Pull request closed without merging**
