### PR TITLE
New Extension: Force Quit App

### PR DESCRIPTION
**Pull request by dannymout**
## Description

New extension that allows the user to force quit any of the running apps on their system.

## Screencast
https://user-images.githubusercontent.com/17968389/187593935-12c7063a-015a-4549-ae2c-365805dbdd26.mov

## Checklist
- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by PineappleRind** [comment]
cool extension

**Comment by pernielsentikaer** [comment]
Hi @dannymout 👋 

Thanks for taking the time to contribute! 🔥 

Did you try out the other extensions (and built-in ways in Raycast to do this) before making this extension?

There is an extension called [Kill Process](https://www.raycast.com/rolandleth/kill-process) which might most of the day do the same but also lists processes.

CleanShot 2022-09-01 at 09 30 47@2x

It's also possible directly from root search

CleanShot 2022-09-01 at 09 25 54@2x

Or from `Switch Windows`

CleanShot 2022-09-01 at 09 25 39@2x

Let me know what you think 🙂

**Comment by pernielsentikaer** [comment]
I think that's a good reason @dannymout 🔥 Do you think you can add a file icon, as it's done with [this one](https://www.raycast.com/rolandleth/kill-process)?

That would make it even more nice 🔥

**Comment by dannymout** [comment]
Will try to get icons working shortly.

**Comment by pernielsentikaer** [comment]
awesome @dannymout

**Pull request closed without merging**
