### PR TITLE
[New extension] Bark

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

Send messages to [Bark](https://bark.day.app) via Raycast.

Bark
- Free, lightweight! Simply call the interface to send push notifications to your own iPhone.
- Depends on Apple APNs, timely, stable and reliable
- Does not consume device’s battery power. Based on system push service and push extension, APP itself does not need to run.
- Privacy and security. You can ensure that no one, including the author himself, can steal your privacy through some ways.
- Click for details on how to ensure [privacy and security](https://bark.day.app/#/en-us/privacy)

Get the Device Token of Bark
1. Search and download Bark in the App Store
2. Open the Bark app
3. Go to the Setting page and copy the Device Token

## Screencast

image

bark-1

bark-2

bark-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pindab0ter** [comment]
I've never heard of Bark. Is it this service? https://www.bark.com/

**Comment by koinzhang** [comment]
Hi @pindab0ter You can find information about Bark here https://bark.day.app

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Is there a way to check if the user has Bark and tell about it?

* Instead of using a HUD that closes Raycast you might want to use toast instead and clear the form upon success if possible   

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by koinzhang** [comment]
Hi @pernielsentikaer. Thanks for the review.

1. Bark is an iOS application, and I cannot and do not need to determine whether the user has installed it. If the user wants to use this extension, they must fill in the Device Token, which must be installed in Bark and copied from the application. Therefore, there is no need to determine whether the user has installed the Bark application on their phone. 
2. Thank you for your revision suggestions. I have submitted a commit to update the prompt method for the Send Message command.

Please keep reviewing.

**Comment by pernielsentikaer** [comment]
Hi @koinzhang 👋 

That make sense 🔥 

Does it make sense to clear the form after submitting, just asking since I'm not sure how the app work 😊

**Comment by koinzhang** [comment]
Hi @pernielsentikaer. Thanks for the review.

- Added a setting item: close the window automatically, so that the user can choose whether to close the main window after sending the message.
- Now after sending a message, if the main window is not automatically closed, the text box will be automatically emptied

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
