### PR TITLE
New extension: FrankerFaceZ

### PR DESCRIPTION
**Pull request by davidchalifoux**
## Description

This is a new extension which allows you to search the [FrankerFaceZ](https://www.frankerfacez.com/) emote library.
## Screencast
Screen Shot 2022-04-28 at 11 00 13 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @davidchalifoux 👋 

Thanks for your contribution 💪 

I have some feedback for you:

- Would it be possible to use our detail view, like it's done in [this extension](https://www.raycast.com/josephschmitt/gif-search) so it's possible to see the images?

It looks like you actually tried to [implement it](https://github.com/raycast/extensions/pull/1529/files#diff-d2c0750574c76bba175dbf083e98ce2c527a7ca694c09036463df82692b057e0R31-R33), let me know if you need help.

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by Aayush9029** [comment]
@davidchalifoux Amazing Work! I've made similar https://github.com/raycast/extensions/pull/600 but for BTTV!
We could try to merge both of these extensions in one and even add 7tv 😄 

What do you think?
>  Completely understandable if you'd rather have separate extensions for each providers! 💪🏼

**Comment by davidchalifoux** [comment]
> @davidchalifoux Amazing Work! I've made similar #600 but for BTTV! We could try to merge both of these extensions in one and even add 7tv 😄
> 
> What do you think?
> 
> > Completely understandable if you'd rather have separate extensions for each providers! 💪🏼

Thanks @Aayush9029 ! Your extension is actually what inspired me to make one for FrankerFaceZ!

I thought about your idea of having one extension for searching all of those services, and I would do that only if they were separate commands within the extension (ie "Search BTTV" and "Search FrankerFaceZ"). I took a look at the "GIF Search" extension which can search a few different GIF services, but I don't like needing to use the dropdown to change providers.

Here's how I would do it:

- Create a new extension called "Search Emotes"
- Create commands for each service and name them something like "Search BTTV" and "Search FrankerFaceZ"
- Use the detail view per @pernielsentikaer's suggestion

Let me know what ya think. @pernielsentikaer I'd love to hear your thoughts too if you have any opinion.

**Comment by Aayush9029** [comment]
@davidchalifoux Don't mind me, I love to throw out some ideas💡

I've been using emotes (extension) a lot lately, replacing GIFs during conversations 😆

Definitely, Looking forward to your extension!

**Comment by pernielsentikaer** [comment]
Hi @davidchalifoux 👋 

It would be awesome to have it as one, the only problem with that is that we might end up with a lot of extensions stalling with an older version of BTTV since we can't uninstall extensions from the users.

I think we're better with having them separated, even though it would be cool!

**Comment by davidchalifoux** [comment]
Added detail view per @pernielsentikaer.
Also cleaned everything up a bit.

Screen Shot 2022-05-03 at 12 19 48 AM

**Comment by pernielsentikaer** [comment]
Hi @davidchalifoux 👋 

Awesome update! Could it be an idea to add a [Paste](https://developers.raycast.com/api-reference/clipboard#paste) action too?

**Comment by davidchalifoux** [comment]
I added a paste action, but it doesn't seem to be working for me. It copies the content to the clipboard but never pastes it. Any ideas @pernielsentikaer?

**Comment by pernielsentikaer** [comment]
It should work since the action is right; I think we should merge it now 🎉 

Does it works from other extensions like the `Clipboard History`?

**Pull request merged**
