### PR TITLE
[Browser Tabs] Optimize function

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

- Reverse the order of the tabs and the most recently opened tab will be at the top.
- Add a new action to disable/enable browser.
- Add a new action to open tab in other browsers.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

Love the "open tab in another browser" action. I believe it is very useful. However, don't you think that enabling and disabling browsers would be better on the extension's settings? Right now, it is very hidden on the Action Command. Tab sorting would also be a great candidate for the preferences.

What do you think?

**Comment by koinzhang** [comment]
Hi @mil3na Thanks for the review and suggestion.
If I put it in the package.json preferences, I can't get all the user's browser apps dynamically, the data in the package.json is fixed.This **Setup Browser** Action is also made with reference to Browser Bookmarks.
image
Screenshot 2024-07-09 at 21 15 20

Tab sorting as a setting item is a good choice, I will add this feature

**Comment by koinzhang** [comment]
Hi @mil3na I have submitted a new commit: [New setting: Recent Tabs on Top](https://github.com/raycast/extensions/pull/13339/commits/c92573d5fcab710592eab8706ddae0d64e3e16e8), please keep it under review!

**Review by mil3na — APPROVED** [review]
LGTM!
Let me know if you are ready for merging this.

**Comment by koinzhang** [comment]
@mil3na It's ready to merge.

**Pull request merged**
