### PR TITLE
apple notes:add support for system date format handling

### PR DESCRIPTION
**Pull request by ron-myers**
## Description

- moved to moment and use system format string of "LLLL"
- updated default to be true for display folder
- added relative date display for dates in search results
- added alias for `create note`
- tested on two machines (may have additional edges)

Closes for #829

## Screencast

https://user-images.githubusercontent.com/10678906/153786040-766a796c-d112-4f10-9083-f67b804b9c9a.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by ron-myers** [comment]
Correction for #829

**Comment by pernielsentikaer** [comment]
Hi @ron-myers 👋 

Thanks for your contribution 💪

Just out of curiosity, why is `updated default to be true for display folder` changed?

@tumispro, do you have any feedback, could you test it out?

**Comment by ron-myers** [comment]
Thanks, @pernielsentikaer - the change is in support of the issue highlighted in #829 - when the folder is turned on, it is much more apparent the source, making the sort clearer.

**Comment by tumispro** [comment]
Nice! I agree it's better to display folders by default, I was actually thinking about changing it recently myself too.

Moment is definitely a better choice and I like the added relative date too. I do think it should be configurable in settings as well, and even be turned off by default perhaps, although that is debatable. For me personally it's not relevant info.

**Comment by ron-myers** [comment]
Hey @tumispro 👋.  I appreciate your feedback - adding a setting for the relative time is a good idea.  I will do that today.

My perspective is having it on by default similar to the folder, makes it more apparent why the notes are rendering in the order that they are.

**Comment by tumispro** [comment]
Alright, if you implement the setting I can agree with that :)

**Comment by tumispro** [comment]
I've just tested your PR and the moment integration gives a lot of invalid dates. Perhaps the format of the modified data coming from Apple Notes is different depending on localisation settings?

An example:

```
Wednesday, 6 June 2018 at 13:19:08
Moment<Invalid date>
```

**Comment by ron-myers** [comment]
Hrm, thank you for your testing @tumispro - handling different localization dates is the intention behind 'LLLL' format.    There may be more work to do here to make the parsing work in all cases.  On the devices I tested the dates parse correctly.  My localization settings are `Canada`(hey eh), Gregorian, non-24 clock.  I had another device on US, 24 clock and it parses successfully. What are your localization settings? I can add those to my testing.

When I run the store version of the plugin and add the display date in the results all of my dates were `null`, which is what I saw as causing #829 

If `LLLL` is not working for long date formats on Mac, maybe our best approach is to use a library with some natural language processing to handle any edges when invalid dates are found.  I could layer that in tonight.

**Comment by tumispro** [comment]
I took the liberty to look into the issue and found that the Sugar library seems to do a good job as well. I've make a commit to try and resolve the issue, as well as add a pref item for modification date. If you grant me access to your forked repo I can push it so you can perhaps test it on your machines too.

I set the default for modification date to default however for the following reasons:
- I think the mentioned issue (https://github.com/raycast/extensions/issues/829) is caused by the notes really being in the wrong order. I don't think showing the modification date will help with that.
- With a lot of notes the extension can be a bit slow to display results and therefor it uses caching. Usually the results won't change often after the notes are 'actually' refreshed and you won't see anything, but with the modification date next to them they do change a lot, causing the data to refresh after already being loaded more often.

I'm still open to debate about it though, so let me know what you think :)

**Comment by ron-myers** [comment]
Amazing - thank you [tumispro](https://github.com/tumispro) - I invited you as a collaborator.

**Comment by tumispro** [comment]
Awesome! I pushed my commit. Let me know how it works for you when you find some time :)

**Comment by ron-myers** [comment]
@tumispro - works great here on both of my machines.  Nice job!  Thanks for tag-teaming this with me.

**Comment by tumispro** [comment]
@pernielsentikaer I think it's ready for review then!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ron-myers 👋 

Awesome work, really 🔥 

When adding the setting for date, I get this error when I open the list:

```
TypeError: Date is not valid

Command:index.tsx:34:29

---
31: }
32: 
33: export default function Command() {
34:   const [state, setState] = useState<State>({
35:     notes: [],
36:     loading: true,
37:   });
---

    at ray-navigation-stack
bc:index.js:24:22698
eo:index.js:24:22803
jr:index.js:23:514
nA:index.js:1:5142
    at ray-root
Mi:index.js:24:2094
```

Catch me in [Slack](https://raycastcommunity.slack.com/) if we should debug it 😄

**Comment by tumispro** [comment]
That was a bit messy with commits, but I think we're there now. Thanks a lot both @ron-myers and @pernielsentikaer for helping out!

**Review by pernielsentikaer — APPROVED** [review]
Thanks both for the corporation here, it's exactly what the community is for ❤️ 

I tested all scenarios and had a debug session at Slack with @tumispro, thanks for your time 💪 

Accepted 🔥

**Pull request merged**
