### PR TITLE
Add surfed extension

### PR DESCRIPTION
**Pull request by hosy**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Thanks for your contribution, first of all, I'm not sure where to get the API key from, can you update the README with this information?

**Comment by hosy** [comment]
@pernielsentikaer thank you for your review. I have added more details and included a screenshot with the API-Key entry in the app settings.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I'm not sure what I'm missing, I only have below settings in the pane you shows

Raycast25072024-VYLUcO3c png@2x

I don't have a password on, but nothing is shown in the extension (even though there are a few things in the application)

**Comment by hosy** [comment]
@pernielsentikaer README > Configuration section should be better now. The API-Key is only available if `Use Password` is enabled. Otherwise, leave the API-Key setting blank.

**Comment by pernielsentikaer** [comment]
It seems like there is no -l option

```
22:45:58.879 Failed to fetch data: Error: Command failed: /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/MacOS/surfed-cli dac -j -a -l 50 
objc[10881]: Class _TtC6SQLite6Backup is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2668) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x10435d6c8). One of the two will be used. Which one is undefined.
objc[10881]: Class _TtC6SQLite10Connection is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee23e8) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x10435d7f8). One of the two will be used. Which one is undefined.
objc[10881]: Class _TtC6SQLite9Statement is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2510) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x10435d968). One of the two will be used. Which one is undefined.
objc[10881]: Class _TtC6SQLite13DateFunctions is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee25d0) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x10435ef78). One of the two will be used. Which one is undefined.
objc[10881]: Class _TtC6SQLite12TableBuilder is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2278) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x10435f328). One of the two will be used. Which one is undefined.
Error: Unknown option '-l'
Usage: surfed-cli [--collections] [--tags] [--all] [--json] [--password <password>] [--key <key>] <search> ...
  See 'surfed-cli --help' for more information.

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 64,
  killed: false,
  signal: null,
  cmd: '/Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/MacOS/surfed-cli dac -j -a -l 50 ',
  stdout: '',
  stderr: 'objc[10881]: Class _TtC6SQLite6Backup is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2668) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x10435d6c8). One of the two will be used. Which one is undefined.\n' +
    'objc[10881]: Class _TtC6SQLite10Connection is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee23e8) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x10435d7f8). One of the two will be used. Which one is undefined.\n' +
    'objc[10881]: Class _TtC6SQLite9Statement is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2510) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x10435d968). One of the two will be used. Which one is undefined.\n' +
    'objc[10881]: Class _TtC6SQLite13DateFunctions is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee25d0) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x10435ef78). One of the two will be used. Which one is undefined.\n' +
    'objc[10881]: Class _TtC6SQLite12TableBuilder is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2278) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x10435f328). One of the two will be used. Which one is undefined.\n' +
    "Error: Unknown option '-l'\n" +
    'Usage: surfed-cli [--collections] [--tags] [--all] [--json] [--password <password>] [--key <key>] <search> ...\n' +
    "  See 'surfed-cli --help' for more information.\n"
}
22:45:59.164 Failed to fetch data: Error: Command failed: /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/MacOS/surfed-cli dace -j -a -l 50 
objc[10882]: Class _TtC6SQLite6Backup is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2668) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x105ff96c8). One of the two will be used. Which one is undefined.
objc[10882]: Class _TtC6SQLite10Connection is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee23e8) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x105ff97f8). One of the two will be used. Which one is undefined.
objc[10882]: Class _TtC6SQLite9Statement is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2510) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x105ff9968). One of the two will be used. Which one is undefined.
objc[10882]: Class _TtC6SQLite13DateFunctions is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee25d0) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x105ffaf78). One of the two will be used. Which one is undefined.
objc[10882]: Class _TtC6SQLite12TableBuilder is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2278) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x105ffb328). One of the two will be used. Which one is undefined.
Error: Unknown option '-l'
Usage: surfed-cli [--collections] [--tags] [--all] [--json] [--password <password>] [--key <key>] <search> ...
  See 'surfed-cli --help' for more information.

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:488:12)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 64,
  killed: false,
  signal: null,
  cmd: '/Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/MacOS/surfed-cli dace -j -a -l 50 ',
  stdout: '',
  stderr: 'objc[10882]: Class _TtC6SQLite6Backup is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2668) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x105ff96c8). One of the two will be used. Which one is undefined.\n' +
    'objc[10882]: Class _TtC6SQLite10Connection is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee23e8) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x105ff97f8). One of the two will be used. Which one is undefined.\n' +
    'objc[10882]: Class _TtC6SQLite9Statement is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2510) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x105ff9968). One of the two will be used. Which one is undefined.\n' +
    'objc[10882]: Class _TtC6SQLite13DateFunctions is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee25d0) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x105ffaf78). One of the two will be used. Which one is undefined.\n' +
    'objc[10882]: Class _TtC6SQLite12TableBuilder is implemented in both /System/Library/PrivateFrameworks/LinkServices.framework/Versions/A/LinkServices (0x280ee2278) and /Applications/Surfed.app/Contents/MacOS/surfed-cli.app/Contents/Frameworks/SharedFramework.framework/Versions/A/SharedFramework (0x105ffb328). One of the two will be used. Which one is undefined.\n' +
    "Error: Unknown option '-l'\n" +
    'Usage: surfed-cli [--collections] [--tags] [--all] [--json] [--password <password>] [--key <key>] <search> ...\n' +
    "  See 'surfed-cli --help' for more information.\n"
```

I'm currently on macOS Sequoia, but I guess it should work there too?

**Comment by hosy** [comment]
Thanks a lot for your feedback. It looks like there is a problem with the CLI in the current version that requires an app update. I can add you to TestFlight to give you access to the upcoming version. Is it possible to approve an extension and release it later? Otherwise, I'll have to ship the new app update before the Raycast extension release.

**Comment by pernielsentikaer** [comment]
We can draft this PR until you're ready, but sure, feel free to add me to TestFlight 🙂 It's just per@r.......com 😂

**Comment by pernielsentikaer** [comment]
Thanks for the invite. I just tested it again with the version from TestFlight and it seems to retrieve data now, but I have two questions for you:

-  Is there a way to show the latest 50 items in the list when entering the extension?

-  If not, you should consider a [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) to explain what to do

**Comment by hosy** [comment]
Great to hear that it is now working. Have fun with Surfed! I have implemented a List.EmptyView for various scenarios.

**Comment by hosy** [comment]
I did not found any kind of tokens like [UISearchToken](https://developer.apple.com/documentation/uikit/uisearchtoken). It would be great to have an equivalent API for that in a future Raycast version.

**Comment by hosy** [comment]
@pernielsentikaer hi, any news from the code review?

**Review by pernielsentikaer — COMMENTED** [review]
I think it works fine like this, is the right version in AppStore yet?

**Comment by pernielsentikaer** [comment]
@hosy are you still around?

**Comment by hosy** [comment]
@pernielsentikaer the new app version is currently under review by Apple. I hope it will be approved within the next two days. I'll ping you as soon as it's approved. Thanks!

**Comment by hosy** [comment]
@pernielsentikaer I would like to release Surfed 3 today at 11 AM (GMT+2). Is it possible to merge the PR today?

**Comment by pernielsentikaer** [comment]
Should be fine, drop a ping here when it's ready 🙂

**Comment by hosy** [comment]
@pernielsentikaer yes, it is available now. Thank you!

**Comment by pernielsentikaer** [comment]
I have the 3.0 version from TestFlight and I'm getting this error when I search. Do you know what that might be?

```
10:55:09.726 Failed to fetch data: SyntaxError: Unexpected token 'S', "StorageMan"... is not valid JSON
    at JSON.parse (<anonymous>)
    at fetchURLs (/Users/pernielsentikaer/.config/raycast/extensions/surfed/index.js:69:31)
```

**Comment by hosy** [comment]
@pernielsentikaer Argh! There was a regression in the submitted build. Thanks for finding this bug. I have submitted a new build, version 3.0.1, for review.

**Comment by pernielsentikaer** [comment]
That's better in the TestFlight version. Has this version been released yet?

**Comment by hosy** [comment]
The version is now available in the App Store. Thank you for your support and quick response. Best regards!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
