### PR TITLE
Add unix-time-converter extension

### PR DESCRIPTION
**Pull request by rpandey1234**
## Description

The goal of this extension is to make it easier to translate between UNIX time and what that actually means in terms of a human date. Given an input, this command tries to smartly detect a UNIX (epoch) time or human time and convert it to the other. 

As a JavaScript/TypeScript developer, we often work with time in milliseconds, not seconds, so this extension also tries to detect the appropriate input unit.

## Screencast

https://github.com/user-attachments/assets/aadb23fd-fedb-4954-9ce2-d54ed8884904

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥

This should also be working directly in Raycast, could you try that?

Raycast 2024-12-12 at 14 07 16

**Comment by rpandey1234** [comment]
Nice @pernielsentikaer, I had no idea this was built into Raycast! (I saw another extension `Unix Timestamp` which I was trying to improve upon.)

The benefit of this extension is: 
- supporting milliseconds instead of only seconds
- the additional info shown with the screen real estate: relative time

Happy to close this out if this doesn't offer enough functionality. As a JS dev who works in milliseconds, I'd personally use this.

**Comment by pernielsentikaer** [comment]
It should also work the other way `1737802800 to date` - I guess another extension doing this might be a bit too much

**Comment by rpandey1234** [comment]
Thanks for the review, will close this out then.

**Pull request closed without merging**
