### PR TITLE
Update screenocr extension

### PR DESCRIPTION
**Pull request by anwarulislam**
## Description

Problem: Previously, selecting an area for text recognition left the original image in the clipboard

Solution: We’ve added a customizable option that allows users to choose whether to keep the image in the clipboard after performing text recognition.

How?

We have added a temporary image path for the selected image instead of capturing them in a clipboard when keepImage is false. And after we get the `imageRef` we delete the temp image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by anwarulislam** [comment]
> @anwarulislam Could you attach a screen recording of the feature?

Hi @neo773, I have updated the description.

**Comment by pernielsentikaer** [comment]
@neo773 can you check the reply

**Comment by neo773** [comment]
LGTM!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
