### PR TITLE
Add GIPHY GIF search extension

### PR DESCRIPTION
**Pull request by stigi**
## Description

> [!NOTE]
> The Giphy API Key is not approved for production yet (it's pending the extension having a presence on the Raycast Store). Classic catch 22...

This is my first Raycast extension 🥳
I wonder why there wasn't a GIPHY extension already when I searched for it 🤔

This a simple GIF search via GIPHY, that displays its results in Grid.

I've implemented 3 actions per result, to be inline with the [GIPHY attribution policy](https://developers.giphy.com/docs/sdk/#design-guidelines):
- A default (`⏎`) action that pastes the gif URL as provided from the API
- An action that opens the entry on GIPHYs website (`⌘⏎`) as required for attribution
- An optional action that opens the GIFs authors profile on GIPHYs website as required for attribution (didn't assign a shortcut to this one, as it's optional and should be rarely used anyway)

## Screencast

https://github.com/raycast/extensions/assets/13815/5bad2d66-894c-406e-826f-98810d2dbf94

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

## Meta

Original code under https://github.com/stigi/raycast-giphy

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

There is actually a GIPHY extension which is inside [GIF Search](https://www.raycast.com/josephschmitt/gif-search) - we should indeed add some keywords for it so it's easier to be found, I'll do that later today.

Could that extension work for you?

**Comment by pernielsentikaer** [comment]
You can now find the other extension by searching for giphy, tenor and other keywords 🙂

**Comment by stigi** [comment]
Hi @pernielsentikaer 👋

Thanks for updating the keywords and making it easier to find for others 🙌 

Makes perfect sense to call it "Gif Search" and support multiple providers! I was honestly wondering hard why there wasn't such an extension available yet.
shame-facepalm-gif-by-moodman

Well, it still gave me the oportunity to play with the extension API and build something that's close to the existing version already.

I'm going to close this PR now. On to the next one ⏭️ 
✌️

**Comment by pernielsentikaer** [comment]
The extension was made before the support for keywords, that's why there was none added 🙁

Thanks for taking your time to contribute 🔥

**Pull request closed without merging**
