### PR TITLE
Update spanish-tv-guide extension

### PR DESCRIPTION
**Pull request by doktor500**
## Description

Fixed issue with the size of icons
Bumped dependencies

## Screencast

Bug fixes, no new functionality added

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Why did you move the `metadata` to `docs`, it should still be in the `metadata` and referenced in the `README`

**Comment by doktor500** [comment]
@pernielsentikaer Sorry, I got misunderstood what was the right way to do it, it is fixed now 🙂. Thanks

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
No worries at all 🔥

**Pull request merged**
