### PR TITLE
Update index.tsx at extensions/tw-colorsearch

### PR DESCRIPTION
**Pull request by irsyadadl**
Add 950 to every color.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @irsyadadl 👋 

Seems like you removed all commas too, do you mind adding them back and add a changelog entry 🙂

**Comment by irsyadadl** [comment]
> Hi @irsyadadl 👋
> 
> Seems like you removed all commas too, do you mind adding them back and add a changelog entry 🙂

Okay, will add later.

**Comment by irsyadadl** [comment]
Hey @pernielsentikaer am I doing something wrong? This github action cannot be passed. I saw, it guide to upgrade prettier to 2.6.2 and I did. And not too.

**Comment by pernielsentikaer** [comment]
Should be better now, upgraded almost everything 🙂 @magicjaqk could you check?

**Comment by irsyadadl** [comment]
Thank you Perniel.

**Comment by magicjaqk** [comment]
@pernielsentikaer I'll try to take a look later today.

**Pull request closed without merging**
