### PR TITLE
Add url-parse extension

### PR DESCRIPTION
**Pull request by Johnson-LYS**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by YES-Lee** [comment]
During development I often need to manually process very long urls, usually parse them manually in the browser devtool, which is very inconvenient, so I wanted to develop a raycast extension to improve efficiency.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Something weird happens with `https://www.mktraefaeldning.dk/` - sometimes it's not in the list after adding (see below video)

https://github.com/raycast/extensions/assets/38033107/f403429b-429e-4d8d-926e-43752d97abaa

g a new item but returns when going out and in again.

- How is this data sorted?

- You can add `style={Action.Style.Destructive}` and `shortcut={Keyboard.Shortcut.Common.Remove}` to your `Clear History` action

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by YES-Lee** [comment]
Hi~

Thanks for testing, I have fixed the issue an made some improvements.

**Comment by pernielsentikaer** [comment]
It seems like `Paste URL` does not work as intended. Could you fix that one 🙂

**Comment by YES-Lee** [comment]
I tested it but didn't find any problem. I you need to input a URL to the search bar before hitting `Parse URL`. I removed the reading from clipboard function because it causing some weird cases.

**Comment by pernielsentikaer** [comment]
Hi @YES-Lee 👋 

I update the code a bit, could you check that I didn't break something 🙂

Maybe also look into a preference if primary action should be copy or paste?

**Comment by YES-Lee** [comment]
Hi @pernielsentikaer 👋

`﻿Copy` as the primary action works well. However, there's an exception when I need to parse a slice of a URL present in the history list. In this case, while `﻿Copy` remains a feasible option, `﻿Parse URL` should be the primary action.

So I add a function to check whether the inputed text is a URL-like text, if so set `Parse URL` as the primary action.

https://github.com/raycast/extensions/assets/19748456/80e89b08-01a6-46d0-bbe5-4b8b75e7b034

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
