### PR TITLE
[Music] General Improvements

### PR DESCRIPTION
**Pull request by rawnly**
## Description
Improved stability. Better error handling / reporting

## Screencast
Raycast 2022-07-26 at 03 46 48

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Rawnly** [comment]
I'm using the native screenshot method for assets. How can I improve the size?

**Comment by Rawnly** [comment]
@pernielsentikaer any suggestion on this?

**Comment by danielsequeira** [comment]
@Rawnly would you mind adding an entry to the changelog?

**Comment by Rawnly** [comment]
sure!

**Review by danielsequeira — APPROVED** [review]

**Pull request merged**
