### PR TITLE
Update spoiler-converter extension

### PR DESCRIPTION
**Pull request by Visual-Studio-Coder**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Visual-Studio-Coder** [comment]
Why did the raycast bot mention evanzhoudev? he isn't even a contributor?

**Comment by EvanZhouDev** [comment]
Strange. Probably a glitch?

**Comment by Visual-Studio-Coder** [comment]
For some reason, @EvanZhouDev is in CODEOWNERS for this file

**Comment by EvanZhouDev** [comment]
Have you duplicated any part of the extension from any of my extensions? It may be because of that... I didn't get pinged the original release, anyway...

**Comment by Visual-Studio-Coder** [comment]
I don't believe so, unless you made a spoiler-converter?

Or maybe I screwed up the source control and accidentally pushed to some other branch using the VSCode github thingy (because I have forked your extensions in the past)

**Comment by Visual-Studio-Coder** [comment]
@pernielsentikaer I'm okay with your changes to the changelog 👍

please merge it to the store.

also, could you please review my changes for the URL shortener as soon as you can? 🙏

tysm

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
