### PR TITLE
[stackoverflow] close #14738 by fetching 9999 sites + update deps + replace getSites `useEffect` w/ `usePromise`

### LINKED ISSUE #14738: [Search Stack Exchange Sites] Some sites cannot be searched
### Extension

https://www.raycast.com/reckoning-dev/stackoverflow

### Raycast Version

1.83.1

### macOS Version

_No response_

### Description

When trying to search a StackExchange site, some do not show up (such as [Biology StackExchange](https://biology.stackexchange.com/)):

Screenshot 2024-09-30 at 17 00 29

### Steps To Reproduce

1) open the "Search Question" command
2) press ⌘P to filter for a specific site
3) try to search for some sites, such as Biology StackExchange - some do not show up.

I believe the `pageSize` for the `sites` API call is not set high enough to grab all sites.

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by xmok**
## Description

closes #14738 by fetching `9999` sites (the API docs mentions this endpoint has "unbounded" page limit so this works great).`

NOTE: I have added a temp fix in `SoApi` to force early loading of the cache if it only has default 30 sites - we can remove this a few days after extension is merged.

## Screencast

Screencast shows Store version 1st then updated one:

https://github.com/user-attachments/assets/ed766c3a-7dc5-430e-bc73-f1b19acc6291

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I can't get this to work, for me is always ends here (waited 5 minutes)

stackoverflow 2024-10-08 at 14 59 51

**Comment by xmok** [comment]
Great catch @pernielsentikaer.
I was able to identify the issue as the `useEffect` in getDetails not **unmounting** and setting the *cancel* properly. Seems like a 50/50 chance.

I _think_ the reason was updated deps of React and Raycast but I replaced the `useEffect` with a `useFetch` and it's all working fine now 👍.

Screencast:

https://github.com/user-attachments/assets/9f3f1cf5-da57-4f1d-9df5-2088ea819eae

**Comment by sadanand-singh** [comment]
This looks great. Thanks @xmok

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
