### PR TITLE
Add Grid layout support for kaomoji extension

### PR DESCRIPTION
**Pull request by Yukaii**
## TODOs

- [x] Add `Frequently Used` feature, like built-in Search Emoji command
- [x] Kaomoji SVG not centered perfrectly...

## Description

- Add new preference `displayMode`
- Upgrade raycast/api to latest
- Upgrade asciilib to latest
- Group search results by category when no search input is provided

## Screencast

スクリーンショット 2023-01-27 午後1 23 54

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @Yukaii - do you mind adding a changeling entry

@allexks do you mind giving it a check?

**Comment by Yukaii** [comment]
HI @pernielsentikaer , did you mean "adding a Changlog"?

I track to the origin PR #746 and seems that allexks's GitHub handle has been changed to @yalishanda42

**Review by yalishanda42 — APPROVED** [review]

**Comment by yalishanda42** [comment]
@Yukaii  Thank you for keeping the extension fresh and up-to-date!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Pull request merged**
