### PR TITLE
Add Hubspot Extenstion

### PR DESCRIPTION
**Pull request by harisvsulaiman**
## Description
A Hubspot Extension to Search for Deals and Contacts.

## Screencast
hubspot 2022-12-06 at 23 15 07

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by harisvsulaiman** [comment]
@pernielsentikaer thank you for additional fixes

**Comment by pernielsentikaer** [comment]
There is a few problems with SVG in EmptyView, for now we'll use the PNG instead 😊

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
We might need better metadata images later on, I didn't know the right format

**Pull request merged**
