### PR TITLE
[Extension] Add Quit App extension

### PR DESCRIPTION
**Pull request by ahmetayrnc**
## Description

Add new extension: Quit App. The extension lists all open apps, then quits the chosen app.

## Screencast

screenshot_01

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Hi @ahmetayrnc 👋. Very good extension. But I have a small doubt.
First, did you know that the Raycast main window can search for apps and quit directly (shortcut: `⌃+⇧+Q`) and that the running app icon is identified by a small dot below it.

Second, your extension seems to recognize only the applications displayed on the dock bar (with a small dot icon), but not applications such as Magnet, Shottr, JB Toolbox, ClashX,  AlDente, KeyCastr, etc.

**Comment by ahmetayrnc** [comment]
Hello. I started using Raycast recently, before that I was an Alfred powerpack user. With Alfred quitting running apps is super convenient, you start writing quit and open apps get listed below and you choose one to quit. With Raycast, I could not find an equivalent workflow. This extension was a way for me to try to fill that gap. (But still does not compare to the ease of quit in Alfred)
This extension is for cleaning up the dock and the app switcher, that is why it selectively shows foreground apps. Additionally, this could be a personal preference, seeing a list of open apps and choosing one to kill feels easier than writing the name of the app I want to quit then using a shortcut to quit.
However, if this does not fill the requirements for being an extension feel free to close the PR. Have a great day!

**Comment by pernielsentikaer** [comment]
Hi @ahmetayrnc 👋 

This is also possible with the command `Switch Windows`; from this list, you can use `⌃+x`

Could you see if that does what you're trying to achieve?

CleanShot 2022-05-24 at 11 49 39@2x

**Comment by ahmetayrnc** [comment]
Thank you everyone for your suggestions. @pernielsentikaer your suggestion comes closest to what I want to achieve. I am closing this PR now. 

However, I recommend you check out how Alfred Powerpack does this, as I believe it is still more convenient compared to any of the options that Raycast provides. And right now there is no way to achieve the same using extensions or script commands with Raycast. I think it will be a nice quality of life feature to have in Raycast.

**Pull request closed without merging**
