### PR TITLE
Add teslamate extension

### PR DESCRIPTION
**Pull request by mSarheed**
## Description

Raycast Extension to retrieve data about Tesla vehicle from a TeslaMate instance.

## Screencast

teslamate-1
teslamate-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @mSarheed 🔥 

What is the difference between this extension and [this one](https://www.raycast.com/williamwelsh/tesla) by @WilliamWelsh

**Comment by mSarheed** [comment]
This extension is for the more 'diy' Tesla owners who's self-hosting an instance of [TeslaMate](https://github.com/teslamate-org/teslamate), where they're storing all their vehicle data.

The extension by @WilliamWelsh is dependent on the Tesla owner having a [Tessie](https://tessie.com/) account hooked up to their Tesla. 

I hope that makes sense @pernielsentikaer 😊

**Comment by pernielsentikaer** [comment]
It does @mSarheed, thanks for pointing it out 🔥

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
