### PR TITLE
feat: year progress add copy to clipboard

### PR DESCRIPTION
**Pull request by chenpx976**
## Description

year progress add copy to clipboard 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by anothertempore** [comment]
LGTM!

**Comment by chenpx976** [comment]
@pernielsentikaer 
You're right, I've modified the copied action placed in the action of x-in-progress

**Comment by pernielsentikaer** [comment]
Could you as the last thing add a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry? 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
