### PR TITLE
Add oklch-color-converter extension

### PR DESCRIPTION
**Pull request by strongeron**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Thanks for your contribution 🔥

We have many color extensions in the store. What makes this one special? Instead of creating a new extension, could we enhance an existing one?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Thanks for your contribution 🔥

We have many color extensions in the store. What makes this one special? Instead of creating a new extension, could we enhance an existing one?

**Comment by strongeron** [comment]
Hey @pernielsentikaer 

I’d like to contribute by adding more OKLCH and P3 gamut-related features based on our tool, [oklch.com](https://oklch.com/).

Currently, none of the existing color extensions support OKLCH/P3 conversions, Figma P3 exports, or color space detection. A key use case (which I believe will become increasingly popular) is enabling developers and designers to work with P3 colors seamlessly. This would provide essential P3 and wide-gamut support.

As more color tokens are being created with OKLCH and P3 formats, there’s a growing need for tools that can handle them better. A Raycast extension could simplify workflows and act as a bridge between different apps.

While extending an existing color extension is technically possible, adding such extensive functionality would require major changes, likely involving a complete overhaul of the current logic. This could place a significant burden on the original extension’s author, which might not be ideal.

By creating a separate extension, I’ll be able to expand its functionality further. I’m already planning features like handling multiple colors as input, adding a contrast checker, supporting advanced color export, and more. This would allow for continuous development and improvements without impacting existing tools.

Looking forward to hearing your thoughts!

**Comment by pernielsentikaer** [comment]
That makes sense, can you look into the errors from the [CI](https://github.com/raycast/extensions/actions/runs/12222232305/job/34092252082?pr=15747)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
