### PR TITLE
Update package.json for chatgpt-quick-actions with GPT-4o model

### PR DESCRIPTION
**Pull request by ashtukaturov**
## Description

Adding ChatGPT-Quick-Actions GPT-4o model

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jimmyn** [comment]
@alanzchen please check this PR, really needed 🙏

**Comment by jimmyn** [comment]
@alanzchen thanks for awesome extension! I have reinstalled it, but I still don't see GPT-4o model, do you know when it is going to be published? 

image

**Comment by ashtukaturov** [comment]
I've added to Summarize command only for now. Going to update all commands in the next PR.

**Comment by ashtukaturov** [comment]
new PR https://github.com/raycast/extensions/pull/12554

**Pull request merged**
