### PR TITLE
coinpaprika extension

### PR DESCRIPTION
**Pull request by gumbleliks**
## Description

add a extension that lets you easily check your favourite cryptocurrencies via the Coinpaprika API

## Screencast

image

Screenshot 2022-04-28 at 16 34 02

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @gumbleliks 👋 

Sorry for the long response time here; it's on me! 

I added checks to ensure that only mounted components are doing state updates. Could you please try it out to ensure that I didn't break anything 😄 

We could still look a bit more into caching the responses for a day to ensure the speed, but it's not something we need to add in this version.

Let me know what you think

**Comment by gumbleliks** [comment]
> Hi @gumbleliks 👋
> 
> Sorry for the long response time here; it's on me!
> 
> I added checks to ensure that only mounted components are doing state updates. Could you please try it out to ensure that I didn't break anything 😄
> 
> We could still look a bit more into caching the responses for a day to ensure the speed, but it's not something we need to add in this version.
> 
> Let me know what you think

Hey @pernielsentikaer 👋
Thanks for your changes, it is a much better approach and works like a charm.

Unfortunately the current API Version doesn’t provide a limit call but I want the implement something like this in the next update by my own. Then it should be possible to steer the request calls more on point and in a performance optimised way.

And I want to implement a favourite/bookmark Coin function to preload only a few coins.

**Comment by gumbleliks** [comment]
Hey @pernielsentikaer 👋
Thanks for your changes, it is a much better approach and works like a charm.

Unfortunately the current API Version doesn’t provide a limit call but I want the implement something like this in the next update by my own. Then it should be possible to steer the request calls more on point and in a performance optimised way.

And additionally I want to implement a favourite/bookmark Coin function to preload only a few coins.

**Review by pernielsentikaer — APPROVED** [review]
Let's get it merged @gumbleliks 🔥

**Pull request merged**
