### PR TITLE
New extension: Curator.bio

### PR DESCRIPTION
**Pull request by Yukaii**
## Description

Add the new extension for https://beta.curator.bio/

## Screencast

Metadata-1

Metadata-2

Metadata-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* For all three commands, could you ensure that the loader stops when wrong credentials is entered 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Yukaii** [comment]
Hi @pernielsentikaer, I've pushed one commit to show message when error occurred. I also have another problem. 

Since curator.bio lacks a public API, I used the Raycast Cache API and `tough-cookie` to preserve login sessions rather than keeping access tokens in preference storage. However the login status of a session cannot be reset by changing the email or password because the cookie is persistent between requests. The possible solutions might be:

1. Completely remove session caching. Each command sends login request every time.
2. Provide a way to clear the cache when changing preferences. But I'm not sure how to achieve this.

Have you got any suggestions?

**Comment by pernielsentikaer** [comment]
1) That would also be a shame since it will make it more responsive and snappy
2) I'm pretty sure we did something similar in [Liveblocks](https://www.raycast.com/andreaselia/liveblocks) - there we saved a hashed value of the password and compared it

**Comment by andreaselia** [comment]
Just for future reference in case someone ends up looking at this issue for something.

The Liveblocks extension is being updated to simply use the secret key, so if you're looking for the previous implementation mentioned in this issue, you'll need to check a historic version of the extension.

**Pull request merged**
