### PR TITLE
Machine Learning Libraries Documentation Search Extension

### PR DESCRIPTION
**Pull request by sadanand-singh**
## Description

A simple extension to search all major machine learning libraries directly from Raycast.

## Type of change

New extension

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @sadanand-singh 👋 

Just gave it a very quick spin and was wondering if this is the correct search behavior

https://user-images.githubusercontent.com/38033107/141375641-c3e26f43-3b01-4f0b-8bb4-bbbf842d002e.mp4

I stopped the test after finding this, so I will check it again when you're ready.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions 💪

**Comment by sadanand-singh** [comment]
> Hi @sadanand-singh 👋
> 
> Just gave it a very quick spin and was wondering if this is the correct search behavior
> 
>  QQe3GvHrlfEIFYm6.mp4 
> I stopped the test after finding this, so I will check it again when you're ready.
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions 💪

Thanks for catching this too much fuzziness! I have made some updates to the parameters to Fuse.js library that I am using for fuzzy matching. It i still going to be little dynamics for such random strings but now it should be little more robust.

I do not want to do too strict matching since when you search docs many a times you are generally not too sure about what you are searching for.

**Comment by pernielsentikaer** [comment]
Hi @sadanand-singh 👋 

I can confirm that the search is much better now, I'm not getting any irregularities this time.

I'll get back to you asap, I have to check with the team about the way data is received, we'll keep in touch soon 💯 😄

**Comment by pernielsentikaer** [comment]
Hi @sadanand-singh 👋 

I'm very sorry for the delay, I though that I already replied in the thread, but obviously I haven't.

My concern about getting the data is that it's based on a file from another repository and there is no license file at all. I suggest you to contact the mldocs author and talk to him about using the data.

**Comment by sadanand-singh** [comment]
I have updated the raw data path to now point to my personal repo https://github.com/sadanand-singh/mldocs-data. This repo automatically updates this crawled file everyday via a Github Action.

**Comment by pernielsentikaer** [comment]
Hi @sadanand-singh 👋 

I'm going to accept it, my colleague will do the last review before its getting merged 🔥

**Review by mattisssa — APPROVED** [review]
Thanks for the contribution! Let's bring it to the Store 👍

**Pull request merged**
