### PR TITLE
Update git-commands extension

### PR DESCRIPTION
**Pull request by manumorante**
## Description

✨ Add missed aliases

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your correction 🔥 

What does `Add prepare folder with scripts and notes for developers` cover? It seems like a lot of steps for something, and I don't think that everyone understands what they have to do

**Comment by manumorante** [comment]
> Hi 👋
> 
> Thanks for your correction 🔥
> 
> What does `Add prepare folder with scripts and notes for developers` cover? It seems like a lot of steps for something, and I don't think that everyone understands what they have to do

Hi @pernielsentikaer It's just something extra for the devs. I thought it might help to create similar extensions.

I understand that it is not necessary for the use of the extension.

You prefer that I remove it from the repo, right?

thanks!

**Comment by pernielsentikaer** [comment]
If possible I think that would be a good idea, I saw the README and was very confused 🙂

**Comment by manumorante** [comment]
> If possible I think that would be a good idea, I saw the README and was very confused 🙂

Thanks!. You're right @pernielsentikaer, it's confusing. This way it doesn't help much.

I have already deleted the `prepare` folder and updated the CHANGELOG.md

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
