### PR TITLE
Add apply-inline-code extension

### PR DESCRIPTION
**Pull request by aforian**
## Description

Apply inline code style in common applications and websites

## Screencast

apply-inline-code-1

apply-inline-code-2

apply-inline-code-execution

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Would it be possible to support other Chrome browsers like Arc, Vivaldi, Brave and so on too?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by aforian** [comment]
@pernielsentikaer Oh I didn't think about it. Maybe I can add a customize list to add support browser from installed applications by user. Do you think it's a good idea?

**Comment by aforian** [comment]
Thank you for your prompt feedback. I've made some changes:
1. Add the chromium-based browsers you mentioned before to support.
2. add preference `Custom Browser` for users to set their preferred browser.

Please have a look. Thank you!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
