### PR TITLE
Add Color Palette Extension

### PR DESCRIPTION
**Pull request by mapengyuan**
## Description
Your Global Color Palettes
Choose palette from built-in popular color palettes ; Preview the appearance, name and HSL value of each color;  Copy the color value (Hex or RGB or HSL) to your clipboard.

## ScreenShot
screenshot-01
Screenshot-02
screenshot-03
screenshot-04
screenshot-05
screenshot-06

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
It would maybe be nice if this extension could superseed #3162 by @douglas-pires and add the colors from that extension too; what do you both thinks?

**Comment by mapengyuan** [comment]
> 

Sorry, I didn't notice that there is already a similar extension.
I want to ask whether similar extensions are allowed to exist?
- if it's not allowed, I don't mind merging the two extensions, of course it depends on what @douglas-pires thinks.
- If allowed, I might prefer ColorPalette to be released as an independent extension, so that we can all continue to optimize according to our own ideas.
ColorPalette wants to support more functions in the future. Such as supporting users to add JSON files to make their own color palettes.

Looking forward to your reply.

**Comment by douglas-pires** [comment]
>if it's not allowed, I don't mind merging the two extensions, of course, it depends on what @douglas-pires thinks.

Hello folks, I don't mind merging them either. @mapengyuan, you did a great job putting together the pre-built palettes.

I also don't mind having two independent extensions, but that will depend on the strategy Raycast wants to take as a product per se.

**Comment by pernielsentikaer** [comment]
It's also more about not confusing the users that can see two almost identical extensions.

If @douglas-pires doesn't mind, yours can superseed the current one, then the current users of https://www.raycast.com/douglas-pires/palette-colors will just get an update with this instead

That would only require that you support the palette colors that's currently in that one

**Comment by mapengyuan** [comment]
> If @douglas-pires doesn't mind, yours can superseed the current one
This is my first PR on Github，and I just started learning TS and writing the extension of Raycast. I have a lot to learn.

The next thing I need to do is to organize the colors of the previous plugins into the JSON file as a separate category? 

And I want to confirm again, whether @douglas-pires  is willing to accept this, after all, you are the first developer to provide a similar plugin, and I fully accept you to do this.

**Comment by douglas-pires** [comment]
> It's also more about not confusing the users that can see two almost identical extensions.

I agree. Even though they have different approaches (dynamic vs static) they have a similar purpose: to provide colors.

> The next thing I need to do is to organize the colors of the previous plugins into the JSON file as a separate category?

Yes, you can use another `Grid.Dropdown.Section` component to create another section and list the options there. Something like:

```ts
        <Grid.Dropdown tooltip="Select Color Scheme Variant" storeValue onChange={(newValue) => setType(newValue)}>
          <Grid.Dropdown.Section title="Color Scheme Variants">
            <Grid.Dropdown.Item title="Mono" value={SchemeTypes.Mono} />
            <Grid.Dropdown.Item title="Contrast" value={SchemeTypes.Contrast} />
            <Grid.Dropdown.Item title="Tetrade" value={SchemeTypes.Tetrade} />
            <Grid.Dropdown.Item title="Analogic" value={SchemeTypes.Analogic} />
          </Grid.Dropdown.Section>
          <Grid.Dropdown.Section title="Design">
            // ... The list of colors here
          </Grid.Dropdown.Section>
        </Grid.Dropdown>
``` 

It shouldn't be too problematic to merge your approach with the current plugin. Let me know if you need help. Also, it's important to note that unfortunately, Raycast doesn't provide a localization feature, which means that the plugins and their texts must be translated into English (link to the [docs](https://developers.raycast.com/basics/prepare-an-extension-for-store#localization-language)),

**Comment by mapengyuan** [comment]
> If @douglas-pires doesn't mind, yours can superseed the current one, then the current users of https://www.raycast.com/douglas-pires/palette-colors will just get an update with this instead

Hello folks, I think I should have done the job, and change some features.
  - Combined palette-colors's four kinds palettes into one palette named "Color Scheme Variants", and put the palette into "Dynamic palettes".
  - Modifies the mechanism of regenerate palette: switching palette no longer triggers regenerate palette, only manually clicking "Regenerate Color" will trigger.Because I think that after the user generates a favorite color palette, they don't want to switch the color palette to trigger the refresh of the palette, so that they will not be able to find the previous color palette.

Screenshot-06


I also did the following：
- Documented the current merge in the README.md and CHANGELOG.md files, with thanks to @douglas-pires.
- Replace the previous Chinese content with English content, however, the colors in Traditional Chinese Color Palette use Chinese names that are so difficult to translate into English. In order to maintain the accuracy of the color names, the Chinese names are still used.

image

image


Is there anything else I need to do? @pernielsentikaer

**Comment by pernielsentikaer** [comment]
Hi @mapengyuan 👋 

Wow! That's awesome! I fixed the flicker when entering the extension. Do you mind checking it out so Ididn't break anything?

There are some Chinese in the extension, at the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by douglas-pires** [comment]
I'm loving the changes! Thank you for your work improving it, @mapengyuan! I'll test it today in the evening here.

**Comment by pernielsentikaer** [comment]
Did you have time to test it out yet @douglas-pires

**Comment by mapengyuan** [comment]
Hey guys, I made another Commit, fixing some bugs and adding a custom palette.
- Fixed the problem of automatic refresh when the dynamically generated swatch is loaded, ensuring that the refresh of the palette can only be triggered manually.
- A customizable built-in color palette has been added. Users who need to customize the color palette can easily customize it by modifying the Json file without modifying the code.

You can  test the extension by the latest commit @douglas-pires 😊

**Comment by pernielsentikaer** [comment]
Maybe we should move Custom_Palette to supportPath (write it if not exists) and do something like this instead: 

```
{paletteRef.current === "custom" && (
  <Action.Open
    title="Edit Custom Palette"
    target={`${environment.supportPath}/Plaette_Custom.json`}
  />
)}
```

If we keep it in assetsPath it will be deleted upon updating the extension 😉

Also hence there is a spelling error here: `Plaette_Custom`

**Comment by mapengyuan** [comment]
Thank you so much for your suggestion. After thinking about it, users should have a better way to add custom palettes, the current method I provide is not good enough. So I removed the Custom palette. After this busy time has passed, I'll try to come up with a better way to support custom.

**Comment by pernielsentikaer** [comment]
So we're ready to move on now @mapengyuan?

**Comment by mapengyuan** [comment]
> So we're ready to move on now @mapengyuan?

I have no problem 😊

**Comment by douglas-pires** [comment]
I'll test right now. Sorry for the late response everyone!

**Comment by pernielsentikaer** [comment]
Yes, replace the current extension folder is the thing to do, then its only an update 😊

**Comment by mapengyuan** [comment]
> Yes, replace the current extension folder is the thing to do, then its only an update 😊

Do you need me to do this? Complete the replacement and submit a new Commit

**Comment by mapengyuan** [comment]
> It needs to "replace" files in the other extension, this way it will just be seen as an update 😊

Done, but I don't know how to add @douglas-pires to the developer of the plugin😂

**Comment by pernielsentikaer** [comment]
I'm not sure what I broke, can you guys check it? 😊

**Comment by douglas-pires** [comment]
Thanks, @mapengyuan! :)

**Comment by pernielsentikaer** [comment]
Can we fix it so it's not flickering? It seems to be the elements that go temporary to `4`

#### Log
```
06:39:05.537 PaletteRef:  spectrum palette.length:  42
06:39:05.552 PaletteRef:  spectrum palette.length:  4
06:39:05.558 PaletteRef:  spectrum palette.length:  4
06:39:05.592 PaletteRef:  spectrum palette.length:  42
```

**Comment by pernielsentikaer** [comment]
Happens on all loads for me, I just added `console.log("PaletteRef: ", paletteRef.current, "palette.length: ", palette.length);` before the `return` 😊

**Comment by mapengyuan** [comment]
I reproduced this bug and I will try to fix it over the weekend

**Comment by pernielsentikaer** [comment]
Are you still working on this @mapengyuan

**Comment by mapengyuan** [comment]
> Are you still working on this @mapengyuan

I'm really sorry, there have been some changes in my job recently, and I have had to spend a lot of time on work. I may have to finish fixing this issue in May.😭

**Comment by pernielsentikaer** [comment]
All good, I converted it to a draft 😊

**Comment by pernielsentikaer** [comment]
Closing this for now. We can always open it again when you're ready 🙂

**Pull request closed without merging**
