### PR TITLE
Update warp extension

### PR DESCRIPTION
**Pull request by danulqua**
## Description

Improved "Open Directory" command:
- Marking directories as favorite
- Reordering of favorite directories
- Filtering directories by "All" and "Favorite"

## Screencast

screenshot

Update: favorites are being affected by filtering when you type in the search input. As a result, they won't be visible all the time and won't occupy excessive space when you are searching for a specific directory.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @danulqua 🔥 

@joetannenbaum / @theRubberDuckiee do you mind checking this?

**Review by theRubberDuckiee — APPROVED** [review]
This looks great! 

My only comments:

1. There was some confusion when testing this extension because I thought this would show me all directories I already have under "Favorites" in my MacOS finder window. Not a blocker, but consider making it more clear in the changelog, the screencast you took, or changing the word "favorite" to "starred".

2. This feature of the extension isn't super discoverable to me. Why only surface the option to favorite a directory when I'm opening it? This is expanding the scope of what you built a little - not a blocker but would be my recommendation to build something like what I outlined in the screenshots below.
Screenshot 2023-09-12 at 7 12 00 PM
Screenshot 2023-09-12 at 7 12 40 PM

**Comment by danulqua** [comment]
Hi @theRubberDuckiee,

1. I have fixed that ✅. In this case, it is better to refer to them as "pinned" directories. That is what I have done.
2. I would argue against that because marking entries as favorites or pinning them is a common thing in the Raycast ecosystem. The common shortcuts for these actions are ⌘⇧F and ⌘⇧P. I don't feel like implementing this one.

**Review by theRubberDuckiee — APPROVED** [review]
Looks good to me! Very excited about having this extra functionality :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
