### PR TITLE
Add Terraform Doc extension😎

### PR DESCRIPTION
**Pull request by shoppingjaws**
## Description

Extension to quickly search and access terraform resources.

## Screencast

terraform-doc 2023-12-17 at 20 06 48
terraform-doc 2023-12-17 at 20 06 57

terraform-doc 2023-12-17 at 20 07 02

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by nakamuloud** [comment]
Sorry, I had free time over the year-end and New Year holidays, so I added some minor corrections.
I won't do it anymore

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The default action says “Navigate to xxx”, what does that mean?

- Missing icons in the action panel

- The extension flickers with `Oops, it looks like the documentation doesn't exist` before it's loaded correctly.

https://github.com/raycast/extensions/assets/38033107/30051fb8-b613-41d7-a1dd-26926c2c9abd

- The loading indicator never stops loading in this view

https://github.com/raycast/extensions/assets/38033107/4a5d5365-d677-4c64-883d-6f2f36d58dd9

- The extension flickers with `404` when loading the last step

https://github.com/raycast/extensions/assets/38033107/1f25792c-9e11-4024-9acb-f0948f9c0453

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by shoppingjaws** [comment]
@pernielsentikaer Happy New Year! I fixed and added a few new features.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
