### PR TITLE
added defichain lottery extension

### PR DESCRIPTION
**Pull request by adrian-schnell**
## Description

An extension to see current and all-time stats for Defichain-lottery.com. Also have the possibility to manage a watchlist of own addresses to see bought tickets and possible wins.

## tutorial to test

use the `add tickets` command and add one of the following addresses:

- `df1q6fcwduxy0t6u0mmf5vyzqtrw4vdqjhe820xexs`
- `8VKs5jqADhwRTHVXsf8hhMmJm5r8FpWF7h`

after that use the `tickets` command

Undo added addresses with the `remove` command.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I moved your extension to the right folder and I can see that you're looking int the lining issues @adrian-schnell - let me know if you need anything

**Comment by adrian-schnell** [comment]
> I moved your extension to the right folder and I can see that you're looking int the lining issues @adrian-schnell - let me know if you need anything

@pernielsentikaer thanks for your help 🙏
seems like I fixed all issues.

let me know if you need details for testing or something else

**Comment by adrian-schnell** [comment]
@pernielsentikaer extension is ready to be reviewed

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for pleasing the linter @adrian-schnell 🚀 

I have some feedback for you:

* There is something wrong when you hit cancel when you try to remove an address

https://user-images.githubusercontent.com/38033107/201868109-a4a5487b-e664-400f-ba11-a301b7151ff6.mp4

* You could also use the [List.Dropdown](https://developers.raycast.com/api-reference/user-interface/list#list.dropdown) component here instead of filtering in the [ActionPanel](https://developers.raycast.com/api-reference/user-interface/actions#api-reference)

image

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by adrian-schnell** [comment]
@pernielsentikaer I sent you a message on slack.
I fixed the exception and added the dropdown, which is a cool feature.

As i wanted to use the keyboard shortcuts for primary / secondary action, I left the actions. hope it's no blocker for you?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
