### PR TITLE
Add mite extension

### PR DESCRIPTION
**Pull request by paoloricciuti**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

It seems like it crashing for me, value here is undefined, could you look into that?

mite 2024-01-26 at 07 35 27

**Comment by paoloricciuti** [comment]
> Hi 👋
> 
> It seems like it crashing for me, value here is undefined, could you look into that?
> 
> mite 2024-01-26 at 07 35 27

Sure will fix this asap

**Comment by paoloricciuti** [comment]
@pernielsentikaer sould be fixed now, thanks

**Comment by pernielsentikaer** [comment]
I'm getting an error when using it, I copied the values from my test setup

Raycast 2024-01-26 at 09 32 12

I sent you an e-mail with my credentials to your email

**Comment by paoloricciuti** [comment]
> I'm getting an error when using it, I copied the values from my test setup
> 
> Raycast 2024-01-26 at 09 32 12
> 
> I sent you an e-mail with my credentials to your email

As discussed in the mail i think what you are missing is saving your profile after allowing api access so you are unauthorized. I've added a better explanation in the command setup and in the README

**Comment by pernielsentikaer** [comment]
Seems like you we're right about the save button, thanks 👏 

Could you check the naming I corrected, is that okay? I'm trying the extension later today again to ensure the flow 🙂

**Comment by paoloricciuti** [comment]
> Seems like you we're right about the save button, thanks 👏
> 
> Could you check the naming I corrected, is that okay? I'm trying the extension later today again to ensure the flow 🙂

Just checked...i think it's perfect. Also if you actually use mite and have some feature request i'm eager for it. I've developed this based on how I use mite but maybe there are other unexplored uses.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
