### PR TITLE
CoinGecko extension - Show coin info in list detail

### PR DESCRIPTION
**Pull request by mike182uk**
## Description

This PR updates the CoinGecko extension to show coin info inside of a list detail view:
  - Combines the coin info and price history into the same view
      - Also includes the current price and an icon
  - Changes default behaviour (`enter`) to open coin info in list detail view
      - Secondary behaviour is to open in the browser (`cmd` + `enter`)

I feel this is a better experience than having to navigate to multiple views to get the coin information. I was also struggling with the default behaviour of opening in the browser - Opening the info in the list details view felt more natural.

@Destiner what do you think? I appreciate this a large change from how you had things originally.

## Screencast

https://user-images.githubusercontent.com/991592/158798188-6cfaa38c-cdff-41b6-b20a-18ec07b6d6e8.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @Destiner 👋 

Do you have any last feedback or do you think it's review ready?

**Comment by sxn** [comment]
hi @Destiner @mike182uk - what's the status here? Do we want to proceed with the current PR? 😸

**Comment by mike182uk** [comment]
I think we are still waiting on feedback from @Destiner regarding my last comment

**Comment by pernielsentikaer** [comment]
Let's wait until Monday, and then we will decide what to do.

**Comment by pernielsentikaer** [comment]
What about making the historical prices a setting that lets the user decide `(required: true)`, then the user can toggle it? 

It sounds like it will do the trick and make all happy here? Can you look into this @mike182uk so we can get it merged?

**Comment by pernielsentikaer** [comment]
Hi @mike182uk 👋 

Do you have time to look into above?

**Comment by mike182uk** [comment]
Hey @pernielsentikaer 

Thanks for taking a look at this and sorry for the delayed response.

Yep we could add an option where the user could specify how much historical price information they want to display on this view, the options could be: `None` (satisfying @Destiner's requirement), `7 Days` & `30 Days`?

Alternatively, I'm not sure what the usual process is when the original extension author isn't able to provide feedback, but I'am happy enough to drop this if we don't feel it adds any value to the extension, I don't want to be stepping on @destiner's toes or undoing the hard work they originally put into the extension

**Comment by pernielsentikaer** [comment]
Hi @mike182uk 👋 

Keep it simple - a dropdown with none,7,14,30(, all) and keep the [ActionPanel](https://developers.raycast.com/api-reference/user-interface/actions#api-reference) item, so it's still possible to get into that?

What do you think about that?

**Comment by pernielsentikaer** [comment]
I'm closing this due to inactivity; feel free to open it again when you're ready to continue working on it 🙂

**Pull request closed without merging**
