### PR TITLE
feat(hugging face): added hf actions

### PR DESCRIPTION
**Pull request by crisboarna**
## Description

Adding [Hugging Face](https://huggingface.co/) (AI/LLM/Big Data GitHub) actions for 
- model search
- model history
- model favorite
- dataset search
- dataset history
- dataset favorite

## Screencast

hugging-face-1
hugging-face-2
hugging-face-3
hugging-face-4
hugging-face-5
hugging-face-6
hugging-face-7
hugging-face-8
hugging-face-9

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by crisboarna** [comment]
Hi @pernielsentikaer ,

Could you please review / merge this new extension ?

**Comment by pernielsentikaer** [comment]
Hi @crisboarna 👋 

Would it make sense to enhance [this extension](https://www.raycast.com/ragnor/huggingcast) instead? I don't know much about it 🙂

**Comment by crisboarna** [comment]
Hi @pernielsentikaer ,

That extension is focused on a very specific feature of the platform that requires authentication for it's usage while this is aimed at providing global search features that I look at expanding at a later point. In similar vein how there is `Search npm Packages` and `NPM Registry Manager`, they reference the same platform, but provide vastly different features.

**Comment by pernielsentikaer** [comment]
Thank you for the explanation; that makes sense 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
