### PR TITLE
Add vat-calculator extension

### PR DESCRIPTION
**Pull request by Justiniscoding**
## Description

This extension is used for calculating the VAT(value added tax) of the number or equation inputted

## Screencast

https://github.com/raycast/extensions/assets/76059890/bcb86157-bb0c-447f-8f03-b28022861c32

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I would strip % from preferences if the user adds it

- You could add an argument for faster results directly from the root


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Justiniscoding** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * I would strip % from preferences if the user adds it
> * You could add an argument for faster results directly from the root
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

I've made the extension ignore `%`, but how do I make it work directly from root? I've made the command `no-view` in the `package.json` and also added an argument for the number or equation. In my code, instead of using a `useState` I set the number variable to `props.arguments.number`. When I try to run the extension, it gives me this error message:
```
TypeError: e.then is not a function

index.js:23:35657
    at new Promise (<anonymous>)
Fn:index.js:23:35635
iM:index.js:23:34680
```

**Comment by Justiniscoding** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * I would strip % from preferences if the user adds it
> * You could add an argument for faster results directly from the root
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Ok, done. The extension ignores the `%` symbol and I created another no-view command for quickly calculating the VAT and pasting or copying to clipboard(depending on the preferences)

**Comment by pernielsentikaer** [comment]
I would still add an argument to the other command to make it faster, don't you think that will make it even better?

**Comment by Justiniscoding** [comment]
> I would still add an argument to the other command to make it faster, don't you think that will make it even better?

So I add an argument to the other command and then have it show the two results like it normally did? How would I do that? Isn't it only `no-view` commands that accept arguments from root?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
