### PR TITLE
Add mamp-utility extension

### PR DESCRIPTION
**Pull request by SuoweiHu**
## Description

This extension helps MAMP user to navigate their database/filebase with ease.

## Video

https://github.com/raycast/extensions/assets/35317549/4a938dba-96d1-4029-ba67-5be00948e5ea

## Screenshot

mamp-utility-1

mamp-utility-2
mamp-utility-3
mamp-utility-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- In `Manage Database`, could you add a timeout, it keeps loading forever if you don't have a server running

- What about letting the user select the browser / editor of choise instead? We have a [appPicker](https://developers.raycast.com/api-reference/preferences#preferences)

- Could you look into the CI errors 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by SuoweiHu** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * In `Manage Database`, could you add a timeout, it keeps loading forever if you don't have a server running
> * What about letting the user select the browser / editor of choise instead? We have a [appPicker](https://developers.raycast.com/api-reference/preferences#preferences)
> * Could you look into the CI errors 🙂
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Thank you for checking out my extension @pernielsentikaer, those are all very good suggestions I have overlooked, I'll have them sorted in no time !

**Comment by SuoweiHu** [comment]
Hello @pernielsentikaer I've got all the feature you suggested onboard ! (・ω・)b
(And all CI error resolved 

https://github.com/raycast/extensions/assets/35317549/1d17297f-e8e5-43e3-9c5b-bd6c82c785d8

https://github.com/raycast/extensions/assets/35317549/eab12b8d-f4a2-4d99-a542-da883866e9ac

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by SuoweiHu** [comment]
Hello @pernielsentikaer, it seems the @raycastbot have not automatically merged the pull request for some reasons, could you help me take a second look ? 

Appreciated your time ʕ •ᴥ• ʔ

**Comment by SuoweiHu** [comment]
> Hello @pernielsentikaer, it seems the @raycastbot have not automatically merged the pull request for some reasons, could you help me take a second look ?
> 
> Appreciated your time ʕ •ᴥ• ʔ

Just have to have a bit more patient ! All resolved now !

**Pull request merged**
