### PR TITLE
Update keepassxc extension

### PR DESCRIPTION
**Pull request by pabroux**
## Description

- New feature/action "Paste TOTP" so as to be more productive;
- Respecting the KeePassXC shortcut logic as much as possible since `cmd + P` isn't an available custom shortcut anymore for extensions;
- <del>Giving a tempory solution for the "Copy Password" (why? when the password contains a backslash, that action fails due to AppleScript in the `protectedCopy` function);</del>
- Updating the README.md accordingly;
- Fixing the `protectedCopy` function to handle passwords with backslash.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Sulfyderz** [comment]
@zkytech , by the way I think `protectedCopy` is quite useless. The only case where I see it as interesting is when you are away of your computer and someone checks your Raycast copy history. Feel free to share your agenda about that function.

**Comment by zkytech** [comment]
**Shortcut in KeepassXC**:

- Copy Password: `CMD + C`

**About protectedCopy**: 

If you can see those password you have copied in the `Clipboard History` extension, I think it is unsafe. 

My suggestion is to remove backslash from your password. Backslash is too spetial and rare to use in password, it is not worth removing protectedCopy for this.

**Comment by Sulfyderz** [comment]
Hello @zkytech 

> **Shortcut in KeepassXC**:
> 
> * Copy Password: `CMD + C`

I tried to apply it but it doesn't work. Raycast doesn't allow that custom shortcut as well (anymore ?). The current one `CMD + P` doesn't work anymore. That's why I suggest `CMD + G`.

> **About protectedCopy**:
> 
> If you can see those password you have copied in the `Clipboard History` extension, I think it is unsafe.
> 
> My suggestion is to remove backslash from your password. Backslash is too spetial and rare to use in password, it is not worth removing protectedCopy for this.

I have just fixed `protectedCopy`. Now, it works with backslash 😉. I have also put it back for copy TOTP and copy Password.

Feel free to share your feedback !

**Review by zkytech — APPROVED** [review]
OK

**Comment by zkytech** [comment]
Thanks for your contribution! @Sulfyderz

**Comment by pernielsentikaer** [comment]
In 1.59.0 we just released `concealed` which you can find [here](https://developers.raycast.com/api-reference/user-interface/actions#props-1) - you should use that instead 🙂

Copy Password could also be cmd+shift+c or cmd+. as many things in Raycast use

**Comment by Sulfyderz** [comment]
Hello @pernielsentikaer,

> In 1.59.0 we just released `concealed` which you can find [here](https://developers.raycast.com/api-reference/user-interface/actions#props-1) - you should use that instead 🙂

Done. Feel free to share your feedback (@zkytech you too 😉).

⚠️ By the way, one of your CI fails because of `Clipboard.copy` saying `src/utils/keepassLoader.ts(140,37): error TS2554: Expected 1 arguments, but got 2..` According to your [doc](https://developers.raycast.com/api-reference/clipboard#clipboard.copyoptions), it can have two parameters. On my side, everything works. I have no error message.

> Copy Password could also be cmd+shift+c or cmd+. as many things in Raycast use

Thank you. I'd rather stay with `cmd+G` since it's less complex, especially if you have another daemon listener for scripts (e.g. [skhd](https://github.com/koekeishiya/skhd) with [yabai](https://github.com/koekeishiya/yabai)).

**Comment by zkytech** [comment]
> ⚠️ By the way, one of your CI/GitHub Action fails because of `Clipboard.copy` saying `src/utils/keepassLoader.ts(140,37): error TS2554: Expected 1 arguments, but got 2.`. According to your [doc](https://developers.raycast.com/api-reference/clipboard#clipboard.copy), it can have two parameters. On my side, everything works. I have no error message.


Upgrade the `raycast/api` in `package.json` to `1.59.0`.

**Comment by Sulfyderz** [comment]
> > ⚠️ By the way, one of your CI/GitHub Action fails because of `Clipboard.copy` saying `src/utils/keepassLoader.ts(140,37): error TS2554: Expected 1 arguments, but got 2.`. According to your [doc](https://developers.raycast.com/api-reference/clipboard#clipboard.copy), it can have two parameters. On my side, everything works. I have no error message.
> 
> Upgrade the `raycast/api` in `package.json` to `1.59.0`.

Thank you. My bad.

**Comment by zkytech** [comment]
Looks good to me. @pernielsentikaer

**Pull request merged**
