### PR TITLE
[Hue] Fixes and improvements

### LINKED ISSUE #4929: [Hue] Too many requests
### Extension

https://www.raycast.com/pindab0ter/hue

### Description

Even tho I managed to connect successfully after a while it throws this error, it usually work only the first time 

CleanShot 2023-02-23 at 11 34 31@2x

@pindab0ter 

### Steps To Reproduce

1. Open Raycast
2. Open one of the commands ( Control Groups, Lights, Set Scene ) 

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by pindab0ter**
## Description

Fix #4929, update dependencies and improve code quality.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Awesome update @pindab0ter 🔥 

I tested it and it works quite better than before 🔥

**Comment by pernielsentikaer** [comment]
Do you want tot test it @thomaspaulmann @robertvanhoesel

**Comment by pindab0ter** [comment]
> Awesome update @pindab0ter 🔥 
> 
> 
> 
> I tested it and it works quite better than before 🔥 

Glad to hear!

Can you or anyone give me pointers on how to best memoize/cache/reuse an [API instance](https://github.com/raycast/extensions/blob/3d66076dbab2adcfa0a52c5b39a69da3cd5969d7/extensions/hue/src/lib/getAuthenticatedApi.ts#L7)?

I'm not very well versed in React. Apparently `useMemo` is not an option in this context and storing the reference in a local variable does nothing since the variable doesn't live on.

**Comment by thomaslombart** [comment]
Hey @pindab0ter, we have a few extensions that do that, like Linear. We have a function called [withLinearClient.tsx](https://github.com/raycast/extensions/blob/main/extensions/linear/src/helpers/withLinearClient.tsx) which takes care of initializing a client. It's then possible to share it using a variable that you get through the `getLinearClient` call. We also have another function called [View.tsx](https://github.com/raycast/extensions/blob/main/extensions/linear/src/components/View.tsx) that uses `withLinearClient` and is then used to wrap any commands using the Linear client. You can probably follow a similar approach here. Let me know if you have any further questions.

**Comment by pindab0ter** [comment]
Hi @thomaslombart, thanks for pointing me to those resources. I gave it a good shake, however I got stuck with the following problem:

* Whether I can connect to the API depends on the credentials being present, which is determined by whether the Hue Bridge is set up, which is when the state machine reaches the `connected` state.
* There are three `useCachedPromise`s to "stale while revalidate" the lights, groups and scenes. Those can't be instantiated until there is a valid API reference to define them with (the `useCachedPromise` need to know what to do while it returns the cached data).
* It's not possible to wait to invoke the `useHue` hook until I have that reference, since that results in a `Error: Rendered more hooks than during the previous render.`.

The only way I see right now to solve this is to drop the "stale while revalidate" `useCachedPromise` and just show a loading Detail view until a connection is established. That takes about 0.5 - 1 second though, and that's something I want to avoid.

My question is: How do I combine a `useCachedPromise` with an API reference that doesn't exist (is `null` or `undefined`) the moment that the `useCachedPromise` is defined? Or do I not use `useCachedPromise` but some other caching mechanism?

**Comment by pindab0ter** [comment]
I ended up connecting twice: 
* Once in the state machine to verify that we're successfully connected to a Hue Bridge
* Once for the rest of the extension, which is now reused throughout, meaning that every command usage no longer results in a new connection being established.

This could theoretically be less robust, since the connection could be lost in between establishing and the invocation of a command. However, I don't think this would happen often enough and is easily remedied by starting the command again.

**Comment by pindab0ter** [comment]
In rewriting large parts of the extension, I found out the solution to my problem: `useCachedPromise` supports an `execute` configuration option that I set to whether the connection is defined or not.

That way, the hook isn't executed until the connection is set up. Perfect!

That won't make it into this PR, however. This works as it is. It's good to go on my end.

**Review by thomaslombart — COMMENTED** [review]
Looks good to go on my end. @thomaspaulmann do you want to review and test it?

**Review by thomaslombart — APPROVED** [review]

**Review by thomaspaulmann — COMMENTED** [review]
CleanShot 2023-04-06 at 2 26 30

I triet to authenticate and got the above failure toast. Pressing continue worked but the list of lights was empty. Exiting the command and re-entering then showed the lights. Can we fix this?

Instead of passing around the `apiPromise` everywhere, it might be cleaner to create some sort of client that gets the promise injected once, resolves it and then uses the resolved one. This way your code stays a bit cleaner. But up to you.

**Comment by thomaspaulmann** [comment]
Given that this was merged, you can do a fix in another PR ;-)

**Comment by pindab0ter** [comment]
> CleanShot 2023-04-06 at 2 26 30
> 
> I triet to authenticate and got the above failure toast. Pressing continue worked but the list of lights was empty. Exiting the command and re-entering then showed the lights. Can we fix this?
> 
> Instead of passing around the `apiPromise` everywhere, it might be cleaner to create some sort of client that gets the promise injected once, resolves it and then uses the resolved one. This way your code stays a bit cleaner. But up to you.

Thanks for the suggestion! Always happy to learn more about how to improve!

I'm basically completely rewriting the entire extension. One of the things I've done is use one single 'Hue Client' that I reuse everywhere, like you suggested.

I'll detail everything I've done in a new PR. If you're curious, check out https://github.com/pindab0ter/raycast-extensions/tree/feature/hue-v2-api.

**Pull request merged**
