### PR TITLE
Adding a new extension: Now

### PR DESCRIPTION
**Pull request by lukasoppermann**
## Description
This adds a new extension with the goal to have a simple way of getting your current time converted to other locations

**Why?**
May of us work remote, so when scheduling meetings you often need to arrange a time that fits for multiple time zones. 
This can be hard to remember and require a lot of checking on websites. With this extension it gets very easy, especially when you favorite the cities you colleagues come from.

**Commands**
Only one command exists. It reacts the users input, there are 4 possibilities:
- No input: Favorites (if any) are shown and your current time is converted
- Time input (e.g. 12pm or 13:21): The time is converted and shown for your favorites
- City name (e.g. London): A search results list shows matching cities and your current time converted for their time zone
- City name & time (e.g. 5pm Tokyo): The provided time will be converted for the time zones in the results list

**Actions**
- Return: The default action copies the time to the clipboard to conveniently paste it into an email, slack, etc.
- In the results list the secondary action, (cmd + return) adds the item to the favorites (or removes if already favorite)
- In the favorite list, the secondary action removes the item from the favorites
- In the favorites list, users can move an item up or down on the favorites list

**Settings**
The only setting allows users to decide if time should be shown in a 12 or 24 hour notation.

## Screenshots

now-1
now-2
now-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hmm, I seem to have messed up title case. I will check what the correct "title case" is and update asap.

**Comment by koinzhang** [comment]
Hi @lukasoppermann. Did you know that Raycast has this built-in time conversion feature?
image
In addition, [World Clock](https://www.raycast.com/koinzhang/world-clock) is a useful extension to know the time of remote colleagues

**Comment by lukasoppermann** [comment]
No, I hadn't found this. Can you favorite things there as well? World clock is very complex form me. Not so great for quick conversions. 

Can the internal feature Favoriten locations or convert multiple ones?

**Comment by pernielsentikaer** [comment]
Hi @lukasoppermann 👋 

Thanks for your contribution 🙂

As @koinzhang mentions it seems quite similar to what [World Clock](https://www.raycast.com/koinzhang/world-clock) offer, could you check that out?

**Comment by lukasoppermann** [comment]
Hey, World Clock is actually not quite the same, you can't really search for cities that well and it has a very complex interface. However the built in functionality comes really close. Only the favouriting is missing and it does not find small cities. But that is enough for me I guess.

**Comment by robertvanhoesel** [comment]
@koinzhang since when is this feature there? I started working on a very similar extension as @lukasoppermann (exact same implementation) because I never triggered it.

I expect it to trigger when I type things like:
```
15 gmt // 15:00 gmt works
5 CEST // 5am CEST works
```

Is that calculator trigger open source? Having it native vs first having to search for an extension that helps you is a big plus.

**Pull request closed without merging**
