### PR TITLE
Update shortcuts-search extension

### PR DESCRIPTION
**Pull request by solomkinmv**
## Description

Added new command "Show shortcuts for the frontmost web page". Fetches shortcuts for current active browser page.

Note: it doesn't support Firefox.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋

Can you give me an example of such a webpage where this works?

**Comment by th0rgall** [comment]
@pernielsentikaer https://fastmail.com/ is the only example currently, see https://github.com/solomkinmv/hotkys/blob/72fce2a27582eb9488ba817a456d3ac13005061a/shortcuts-disco-site/shortcuts-data/fastmail.json#L4 and this search: https://github.com/search?q=repo%3Asolomkinmv%2Fhotkys+hostname+path%3A%2F%5Eshortcuts-disco-site%5C%2Fshortcuts-data%5C%2F%2F&type=code

I've been contributing some desktop shortcuts to this dataset already, and also want to add web shortcuts for Figma, Slack, Whimsical, Notion, Penpot, Tally.so, ... in the near future.

**Comment by pernielsentikaer** [comment]
Could it be an idea to update the README (and changelog in this case) to let users know its only for fastmail right now?

**Comment by solomkinmv** [comment]
The database is more dynamic than the extension, so I’d prefer to omit listing the exact web apps. However, I can explain how it works in the README.

Moreover, I can add a command to display the list of supported web apps. What do you think?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
