### PR TITLE
Add webflow-extended extension

### PR DESCRIPTION
**Pull request by itslucasramalho**
## Description

Webflow has updated their API and now requires Data API to be used moving forward. This extension allows anyone with a Webflow account to have quick access to useful features like opening a project in Webflow Designer, publishing CMS Items, opening a specific CMS template page.

## Screencast

https://github.com/raycast/extensions/assets/40926970/6a6889a1-a79e-4eed-a88a-e46a5b01f4fe

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

Instead of creating a new one it would be better to [enhance the current one](https://www.raycast.com/peeks/webflow-sites) by @vurhd in the store so all users with that extension gets the update, what do tou think about that?

**Comment by randomgx** [comment]
@pernielsentikaer Honestly I’m not sure, since we didn’t build the current one it feels weird to just say ours should replace it. Functionality wise, the two extensions are way different, so maybe updating the existing one might change the idea of what the original creator was trying to achieve. Whatever you all think is best works for us!

**Comment by pernielsentikaer** [comment]
I didn't compare the two since I don't know anything about it - maybe features from this could be implemented in the current extension but I'm not sure it makes sense.

@vurhd what do you think?

**Comment by pernielsentikaer** [comment]
@vurhd are you around?

**Pull request closed without merging**
