### PR TITLE
[Pomodoro] Update to be able to show / hide menu bar icon

### PR DESCRIPTION
**Pull request by adamsiwiec**
## Description

Added the ability to hide the app from the menu bar. The corollary: also added the able to show the menu bar once it is hidden.

## Screencast

image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by adamsiwiec** [comment]
Hmm looks like the check got flagged for style, yet I ran `ray fix-lint` with no issues. Any advice?

**Comment by adamsiwiec** [comment]
Ahhh, I guess some small indentation slipped through. Fixed now!

**Comment by pernielsentikaer** [comment]
Do you mind taking this @KELiON

**Comment by adamsiwiec** [comment]
@pernielsentikaer @KELiON any update on looking at this?

**Review by KELiON — APPROVED** [review]
lgtm!

**Comment by pernielsentikaer** [comment]
Hi @adamsiwiec 👋 

Do you mind fixing the conflicts before we can merge 😊

**Pull request closed without merging**
