### PR TITLE
Update Search-Hookmark

### PR DESCRIPTION
**Pull request by QIanGua**
## Description

I add three commen commands: 
- Copy Hookmark Link
- Hook to Copied Link. 
- Show Hooked Links

An Action.Push panel is also created for hooked bookmarks. 

## Screencast
Commands

Hooked Bookmarks

## Checklist

- [ x ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ x ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ x ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ x ] I checked that files in the `assets` folder are used by the extension itself
- [ x ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

It seems like you pushed the complete extension so I'm not able to see the new changes, could you only push new changes?

**Comment by QIanGua** [comment]
@pernielsentikaer I'm trying to figure out how to only push new changes. It would be great if you can give me some tips 🫡

**Comment by pernielsentikaer** [comment]
It should be farily simple
1) Backup the extension
2) Uninstall the local extension from `Manage Extensions`
3) Get the store version of the extension
4) Fork the extension
5) Move files back 
6) run `git commit -am "message"` in the folder 
7) run `npx @raycast/api@latest publish`

**Comment by QIanGua** [comment]
In step 4, I can't find the fork option in action panel. Perhaps I missed some relevant steps in the initial repo.🤣

**Comment by QIanGua** [comment]
Hi @pernielsentikaer.  When I ran `npx @raycast/api@latest publish` I got the report
```
ready -  validate git repository
error -  getting fork
fork extensions repo: Error Body: {"message":"There are merge conflicts","documentation_url":"https://docs.github.com/rest/branches/branches#sync-a-fork-branch-with-the-upstream-repository"}
```

**Pull request closed without merging**
