### PR TITLE
Update chatgpt extension

### PR DESCRIPTION
**Pull request by bxb100**
## Description

support GPT vision input

## Screencast

SCR-20240514-rqta

SCR-20240514-rqxf
SCR-20240514-rrap

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by ericwienerdd** [comment]
Thank you for making this!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by MarshalX** [comment]
@bxb100, that’s great, thank you! I am wondering if it is possible to support adding attachments from the clipboard. Also, I’ve noticed that the ‘Required’ error next to the ‘Question’ text area doesn’t go away until I switch focus (for example, by using Tab). Could it be fixed?

to reproduce:
1. open full-text input
2. attack image
3. write question
4. i can't submit form 

image

**Comment by bxb100** [comment]
@MarshalX nice catch! Could you create an issue? You and I can track that issue. 

> I am wondering if it is possible to support adding attachments from the clipboard.

Yes, the Raycast clipboard API can copy media, but it seems to have some edge cases, so I will add this in the next PR.

**Pull request merged**
