### PR TITLE
add deepl translator

### PR DESCRIPTION
**Pull request by sugayutokyo**
## Description
I have created a deepl translator.

## Type of change
New extension

## Screencast
deepl_translator

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @sugayutokyo 👋 

Sorry for the late reply 😢 

It seems like an awesome extension, here is some feedback to address:

- Do you have a key I can test with somehow? Catch me in Slack if you are there 😄 

- Would be awesome if it was one command where dropdown with languages was possible (and set with default values in preferences)

- When wrong credentials are entered, there is a flicker, could you look into this?

Looking forward to testing it out again 😄 🔥 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by sugayutokyo** [comment]
Hi @pernielsentikaer 🤚

Thanks for the reply😆

> Do you have a key I can test with somehow? Catch me in Slack if you are there 😄

I'm sorry. I don't have a key. If you need a key, please get it by registering for deepl api free below!🙏
https://www.deepl.com/pro?cta=menu-login-signup

I have a question:

> When wrong credentials are entered, there is a flicker, could you look into this?

I couldn't figure this out, so a capture would be helpful.😎

Please confirm!

**Review by pernielsentikaer — COMMENTED** [review]
Hi @sugayutokyo 👋 

I just found out that we already have support for DeepL, could you try to look at https://www.raycast.com/mooxl/deepcast – could be covering the same as yours?

The reason why I didn't find this extension earlier is that the name of the extension seems to be wrong 😕

**Comment by sugayutokyo** [comment]
> Would be awesome if it was one command where dropdown with languages was possible (and set with default values in preferences)

I've added the feature above! Please confirm!

language_select_1
language_select_2

**Comment by pernielsentikaer** [comment]
Hi @sugayutokyo 👋 

It doesn't make much sense to have two extensions using the same service, what we could do was to take a chat with the author of the deepcast extension about collaborating to make the extensions even better.

I think your additions will fit nice in! 🔥 

If we're doing it that way, you get listed as contributor, which is fully supported everywhere the extensions appears

**Comment by sugayutokyo** [comment]
Hi @pernielsentikaer 🤚

OK! I'll try to get in touch with deepcast developer!

**Comment by pernielsentikaer** [comment]
I think it's @mooxl that is the original author 😄

**Comment by pernielsentikaer** [comment]
Just out of curiosity, @mooxl, why is it called deepcast? — Guess I'm just not that fast 😄

**Comment by mooxl** [comment]
I thought it would be cool if the name of the Raycast extension for the DeepL API reflected both technologies -> Deepcast:)
But wouldn't mind if the name was changed to DeepL.

**Comment by pernielsentikaer** [comment]
Ah, that really confused me when searching, I knew I tested it long time ago but couldn't find it 😄

**Comment by sugayutokyo** [comment]
@mooxl 
Thanks for the reply!

@pernielsentikaer
Since he seems to be short on time, is it difficult to release this as a new extension? I can't wait to get this extension working for me.

**Comment by mooxl** [comment]
Had a bit of time today and hopefully implemented your feature request as you imagined it: https://github.com/raycast/extensions/pull/947 @sugayutokyo @pernielsentikaer

**Comment by sxn** [comment]
Hi @sugayutokyo! 

Since @mooxl implemented the features this extension adds (and then some) in #947, I'm going to close this PR. Please ping me if you believe this does something that [Deepcast](https://www.raycast.com/mooxl/deepcast) does not do, or cannot do, and we'll reopen it. 😉

**Pull request closed without merging**
