### PR TITLE
Add extension - Choose a License

### PR DESCRIPTION
**Pull request by sandypockets**
## Description

Lets the user view, copy and paste licenses (as Markdown) from [choosealicense.com](https://choosealicense.com/) for their open source software projects. 

## Screencast
Submitting some screenshots in lieu of a video

<details>
<summary>View screenshots</summary>

image

image

image

image

image

</details>

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by sandypockets** [comment]
Hey gang! 

First time submitting this PR the checks failed, saying the images sizes (in the `metadata` directory) were not correct, and that they needed to be 2000x1250. 

Then I resized the images in Photoshop to exactly 2000x1250. Now when I submit again, it shows the sizes are off again slightly. 

Screen Shot 2022-04-13 at 11 27 21 PM

Is this something on my end, or is there a reason that the image size check is so exact? Even if it is sizing down to 1998x1249, the aspect ratio is still the same. Curious to learn a bit more!

**Comment by Aayush9029** [comment]
👋🏼  Hi! @sandypockets would you mind seeing if this works?
 https://user-images.githubusercontent.com/43297314/163308371-5352cebf-3868-48a7-b2ef-44dda5d72ce1.png

When I downloaded your Metadata image it was `1998 x 1249`, it could be a bug in Raycast's CI perhaps or photoshop 🤔 

Lmk if this works 😄 if not we'll have to ping **THE Raycast devs**!

**Comment by sandypockets** [comment]
Hi @Aayush9029 thanks for having a look at that! I resized those two offending images again and that time it worked. Looks like they got resized somewhere between Photoshop and my IDE. All is well now though, thank you. 

As for your icon, I'd be happy to use it, as the shape is more in line with Raycast's examples, so I think it would provide the user with a cleaner experience. That said, I did find the bottom right corner a bit too dark. What do you think about reducing that shadow/gradient a little bit?

**Comment by Aayush9029** [comment]
@sandypockets  [Here ya go!](https://user-images.githubusercontent.com/43297314/163621873-6d1b6ae3-ba57-4aad-92c1-e1572c7f75b6.png) 🥳

**Comment by sandypockets** [comment]
@Aayush9029 Done! Added you as a contributor too. Thanks!

**Review by pernielsentikaer — APPROVED** [review]
Hi @sandypockets 👋 

Thanks for your contribution 💯

**Pull request merged**
