### PR TITLE
[Brew] Adds more terminal options and minor refactoring

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- Added new terminal options for Alacritty, kitty, WezTerm and Hyper.
- Used app icons for actions to run commands in terminals.
- Apply Destructive style to Uninstall actions.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

* closes https://github.com/raycast/extensions/issues/13701

### CODE REVIEW

**Comment by Aayush9029** [comment]
LGTM

**Comment by jfkisafk** [comment]
> The only thing that worries me is hardcoded path

Thanks @Aayush9029! Yeah, I think most of these apps will be in Applications folder. And in the worst/rare case scenario, if the app icon is not found the image will not be rendered (it will **not** cause the command to crash).

**Review by nhojb — APPROVED** [review]
Looks good. Thanks for the contribution 👏 

I don't think the hardcoded app paths are a big problem since we don't check whether the terminal is installed anyway 😞

A future improvement (not necessary for this PR), would be to check at runtime if the selected terminal app is installed, and if not fallback to Terminal.app for the actions.

**Comment by jfkisafk** [comment]
> A future improvement (not necessary for this PR), would be to check at runtime if the selected terminal app is installed, and if not fallback to Terminal.app for the actions.

Good suggestion @nhojb! I added it to this PR itself. Please take a look when you have some time.

**Pull request merged**
