### PR TITLE
Enable date time selection on Create Task flow on Todoist Extension

### PR DESCRIPTION
**Pull request by sgnilreutr**
## Description

Added an option to the create-task component to allow for a switch between regular date and date with time.
User can now specify a due date with time via the creation of a task. 

## Screencast

https://github.com/raycast/extensions/assets/41041655/cd7a9585-41d5-4a75-ad1f-b4064c3de1d8

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Code style issues found, could you look at the CI errors and correct them?

- Provide a CHANGELOG entry

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by sgnilreutr** [comment]
@pernielsentikaer Sure! How do I best go about that? Since the PR is on the repo, and I don't want to clone this whole repo.

**Comment by pernielsentikaer** [comment]
If you push to your local branch again, it should update the PR 🙂

**Comment by sgnilreutr** [comment]
Never mind, ❯ npx @raycast/api@latest publish works to push as well.

**Comment by casassg** [comment]
curious, why not instead of having a checkbox why not have a separate field for time which can be set or left unset. Seems more in line w the todoist interface (where you specify time as an option later)

**Comment by sgnilreutr** [comment]
That's a good point you are raising there.
I didn't want to alter the current code to much, since I am not sure I had grasped the full scope of it all.

Which field would you use to do this?
https://developers.raycast.com/api-reference/user-interface/form#form

I don't think adding much additional code, if that is the case, to follow the flow of Todoist is the way forward for maintainability. I am curious what you'd suggest here.

**Comment by casassg** [comment]
{Form.DatePicker.Type.DateTime} would work fine. DateTime allows for date to be empty (we would just need to process it to ensure we remove it time is not set). 

From https://developers.raycast.com/api-reference/user-interface/form#form.datepicker it seems picker already shows time input (Now) and date input (Today) in the image.

**Comment by sgnilreutr** [comment]
@casassg Thanks for your reply.
As far as I know the dateTime will generate a full datetimestamp, so when no time is specified it will render it as noon (12PM). If my knowledge is correct, I am uncertain how to derive the fact if the user has actually no intention of setting a time, so keeping the default - or actually intending to set it to 12:00 PM.

**Comment by sgnilreutr** [comment]
@pernielsentikaer Is it possible to merge this request and do another pass on this another time? I'd like to use this function on a daily basis.

**Comment by thomaslombart** [comment]
@sgnilreutr We added a feature internally that will allow you to know if a date is a full day date or a date with time. I'd recommend to wait a bit longer to make use of it for this feature, it'll simplify the UX.

**Comment by thomaslombart** [comment]
@sgnilreutr Raycast 1.58 is out. You can use the feature now. Feel free to update the PR 😊

**Comment by thomaslombart** [comment]
@sgnilreutr Do you plan on finishing up the PR? I can take care of it if you want.

**Comment by thomaslombart** [comment]
All right. For your information, there's another issue with dates on the extension: https://github.com/raycast/extensions/issues/8354. It'd be great to fix that one as part of this PR.

**Comment by kud** [comment]
I think it would be beneficial to update the title of this pull request to make it more descriptive.

**Comment by thomaslombart** [comment]
Closing because the fix was part of adding duration support #8474.

**Pull request closed without merging**
