### PR TITLE
New Extension: Shortcut

### PR DESCRIPTION
**Pull request by Yukaii**
## TODOs

- [x] Story details
- [x] Display story list item color by type
- Story Actions
    - [x] Set estimate
    - [x] Set owner
    - ~~Set epic~~
    - [x] Delete story
- [x] Teams
- [x] workflow & workflow state
- [x] Create Story (Form like Linear extension)
- [x] Screenshots
- [x] Check console warnings
- [x] sort iteration in StoryForm

## Description

Raycast extension for [Shortcut](https://shortcut.com/)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Yukaii 👋 

Thanks for your contribution 💪

I tested your extension and have a few things that we need to address:

- When wrong credentials are added I see an error toast but the loading newer stops, could you stop it and return an empty array (Maybe combined with a custom [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview))

- When adding a new story it would be cool to use [validation](https://developers.raycast.com/api-reference/user-interface/form#validation)

- When adding a new story it just pops to root without an indication, maybe a simple toast would help

Besides that I didn't find anything else, I'm giving it a new spin later today, awesome 🔥 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Yukaii** [comment]
Hi @pernielsentikaer, I've pushed fixes for 1 and 3. For the validation, I did implement one:

https://github.com/Yukaii/extensions/blob/d43400cf4ced609e75827297a7b09412dd972fac/extensions/shortcut/src/components/StoryForm.tsx#L80

But on shortcut.com, only the story name is required, so I only validate the story name for now.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Yukaii 👋 

Thanks for the updates, it's some nice additions you added!

Regarding the validation of title and description, do you think it's possible to validate before it's even submitting the form?

CleanShot 2022-08-11 at 12 13 24@2x

Here it's still possible to submit the form, could be awesome if it just did this (Which also saves a network call):

CleanShot 2022-08-11 at 12 15 28@2x

When successfully adding a story you'll get the message with "Story #16 was created" - maybe you could add a primary action for the toast to open the link directly?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
