### PR TITLE
[minecraft-color-codes] allow customising color code prefixes

### PR DESCRIPTION
**Pull request by lafkpages**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I don't know much about this extension, but would you ever really need to switch between the two of them that often? It could be a dropdown in preferences where you set the default action instead. Does that make sense?

**Comment by lafkpages** [comment]
> would you ever really need to switch between the two of them that often?

Well, I guess if you always play Minecraft on the same server you wouldn't really need to switch between prefixes that often. However, I think that being allowed to toggle them easily could come in handy for several users, so unless you strongly think it should be removed, I'd leave it.

Another question I did have was how I should store the currently used prefix. I thought of using `LocalStorage`, but it seemed quite excessive to have to create an encrypted storage area just to store a single character. I also thought of having a preference that I could modify every time the user toggled between primary and secondary prefix, however I don't think it's possible to modify preference values programmatically. So I ended up using a 1-byte cache, but that also seems excessive. So what would be the ideal way to store the toggled prefix?

**Comment by pernielsentikaer** [comment]
You can maybe use `useCachedState` from `@raycast/utils`, I guess that would also work? In the end it's not really changing that much

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I would move copy actions to the top so it's the default actions for enter and cmd+enter 🙂

image

Can we do that?

**Comment by lafkpages** [comment]
Done

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
