### PR TITLE
Update notion extension

### PR DESCRIPTION
**Pull request by vinifigueiroa**
## Description

Addressing issue #11222 

- I updated the `queryDatabase()` function to show the 100 most recently edited pages instead of just 20. 

_I don't think we have to pull the entire database using cursors because some of them can have thousands of lines, but 100 seems like a good number it's the maximum size of a single page result from a query._

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by vinifigueiroa** [comment]
Addressing this issue #11222

**Comment by thomaslombart** [comment]
Hey @vinifigueiroa, thanks for your contribution! However, bumping the function to get 100 items instead of 20 will probably have an impact on performance. Did you notice any impacts?

**Comment by vinifigueiroa** [comment]
HI @thomaslombart, thanks for your reply. I haven't noticed any performance impact. We're still querying the database one time only but with more results. I recorded a video for you. Let me know what you think and if you want me to run any specific tests.

https://www.loom.com/share/889b2be6286c4ec6a61d86b57a849a7c?sid=6ec3340d-82d5-444c-a6d7-2a4779ecce57

**Comment by thomaslombart** [comment]
`queryDatabase` is also used in `DatabaseList.tsx` (when using the `Navigate to Database` action). I'd be surprised if this wouldn't impact the performance there. Isn't it possible to use typeahead search instead?

**Pull request closed without merging**
