### PR TITLE
Added Raylinks extension

### PR DESCRIPTION
**Pull request by GLaDO8**
## Description

Raylinks is a simple tool which let's users add their most frequently accessed links to raycast, and quickly copy them to their clipboard when needed. 

The extension let's users add all their links, browse them and quickly copy them to clipboard. 

### Some usecases
1. For when you're applying for jobs and frequently need access to your social links like LinkedIn, Twitter, your hosted resume or your personal website.
2. As a marketing person who needs access to company website, personal email or the current campaign link. 

## Screencast

Screencast link -> https://cln.sh/7I5qj8

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by fe9lix** [comment]
Hey @GLaDO8 – are you aware that Raycast has a built-in feature called Quicklinks? Check out the "Create Quicklink" command...

**Comment by GLaDO8** [comment]
I'm aware of the quick links feature. @fe9lix 

Raylinks provides a couple of things on top of that. 

1. A command to see all fast access links in one place

2. Two click access to copy links to clipboard. 

First is not possible and second takes a complex shortcut with quick links. 

The support this extension received in the slack community backs my claim.

**Comment by GLaDO8** [comment]
@fe9lix @pernielsentikaer any updates on this?

**Comment by koinzhang** [comment]
Hi @GLaDO8, Raycast has browser bookmark extension, and your extension functions more like **Search Browser Bookmark** than **Quicklinks**.

So can you tell us how your extension works better than the bookmark extension?

Disadvantages of the bookmark extension.
- Inability to add links via Raycast, a feature that is not available now

So can you tell us how your extension works better than the bookmark extension?

Metadata-2

It would be nice if you could add a screenshot of the extension in the metadata, so we can see the UI of the extension visually.
If you're not good at making meatdata, I can provide an extension that can take screenshots for you (but it's still under review, I'll provide the source code if you need it)

**Comment by pernielsentikaer** [comment]
Hi @GLaDO8 👋 

Did you see my comment in [Slack](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1649179900190699) regarding this?

**Pull request closed without merging**
