### PR TITLE
Add Append Text To page feature to Notion Extension

### PR DESCRIPTION
**Pull request by brian-xu-vlt**
## Description

Notion is the perfect app for journaling, but it lakes a true Logseq style feature to journal all day long without losing focus on the task at hand.
This PR adds this to the Notion Extension, so it's easy to dump any random thought or idea without loosing the focus.

It allows to add content to a journal page: 
- appending at the top or bottom of the existing content
- using timestamp separator
- it saves the last entry settings so it's easy to keep adding content with the same fashion

## Screencast

https://github.com/raycast/extensions/assets/47712216/f6c3769d-f285-4739-ad78-da81cc7c9cb7

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by brian-xu-vlt** [comment]
First contribution to Raycast Extension here, feel free to provide strong feedbacks for improvements, I will try my best to improve any aspect :)

**Comment by thomaslombart** [comment]
Hey @brian-xu-vlt, thanks for the pull request! The command seems tailored to your use case. The idea behind official extensions like Notion is to provide a set of generic commands that everyone can use. It appears that your command allows adding quick entries to pages (which is. great idea!) so I'd suggest renaming everything that's journal-related to something more generic, like `Add Page Entry` or `Add Text to Page`, or something similar (not sure about the names I chose).

**Comment by brian-xu-vlt** [comment]
> Hey @brian-xu-vlt, thanks for the pull request! The command seems tailored to your use case. The idea behind official extensions like Notion is to provide a set of generic commands that everyone can use. It appears that your command allows adding quick entries to pages (which is. great idea!) so I'd suggest renaming everything that's journal-related to something more generic, like `Add Page Entry` or `Add Text to Page`, or something similar (not sure about the names I chose).

Indeed it's quite better this way: it's not a more general feature which also fit my own need, and hopefully the need of people using sequential logging method too.

**Comment by thomaslombart** [comment]
@brian-xu-vlt Thanks for the updates! I've simplified the code a bit and added a `Text` argument to the command to make it faster to capture something. Let me know if everything looks good to you.

**Comment by brian-xu-vlt** [comment]
> @brian-xu-vlt Thanks for the updates! I've simplified the code a bit and added a `Text` argument to the command to make it faster to capture something. Let me know if everything looks good to you.

Great improvements! Thanks a lot :)

**Pull request merged**
