### PR TITLE
Update react-native-directory extension

### PR DESCRIPTION
**Pull request by shubh73**
## Description

This PR introduces improvements, the addition of an expo installation copy action, a compatibility tag for the old architecture, updated colors for better visibility of tags, and a reorganization of the library detail view to prioritize compatibility and platform information.

## Screencast

react-native-directory-6

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by shubh73** [comment]
@pernielsentikaer 

The Tag within TagList is rendered inconsistently. In some instances, the text is visible, while in others, it fails to appear.

I've attached screen recordings demonstrating this behavior. Let me know if you need any clarification or additional details to address this.

https://github.com/user-attachments/assets/2c10949b-96d7-43d7-94c0-e0309b8f3ef2

https://github.com/user-attachments/assets/cc4baf74-d24c-4d2e-9f9d-1a1bb7520fc2

**Comment by pernielsentikaer** [comment]
I'll check the Flickr and get back to you asap 🙂

**Comment by shubh73** [comment]
@pernielsentikaer any updates on this?

**Comment by pernielsentikaer** [comment]
I think we should update this. It's in our backlog to address as soon as possible, but there are no resources available at the moment.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
