### PR TITLE
Add HazeOver extension

### PR DESCRIPTION
**Pull request by ratoru**
## Description

New commands that let you control [HazeOver](https://hazeover.com/), an app that blurs out applications in the background. Specifically, you can toggle dimming on and off and set the dimming intensity directly.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/44789473/144024680-f1c59191-13ed-4df9-a7c0-cdc73cfb4005.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by mattisssa — CHANGES_REQUESTED** [review]
Hey! Thanks for the contribution, it was quick! 😄 

Everything looks good, but I've found the case that if I don't have the app installed I got the "dead" screen.

Once I trigger "Toggle Diming" I got the error:
```Error: Command failed with exit code 1: osascript -e tell application "HazeOver" to set enabled to not enabled
50:57: execution error: The variable enabled is not defined. (-2753)

		error = new Error(message);
		        ^

Error: Command failed with exit code 1: osascript -e tell application "HazeOver" to set enabled to not enabled
50:57: execution error: The variable enabled is not defined. (-2753)
makeError:error.js:60:11

---
57: 		error.originalMessage = error.message;
58: 		error.message = message;
59: 	} else {
60: 		error = new Error(message);
61: 	}
62: 
63: 	error.shortMessage = shortMessage;
---

handlePromise:index.js:118:26
processTicksAndRejections:task_queues:96:5
runAppleScript:index.js:9:19
runAppleScriptSilently:utils.ts:17:3
Object.toggleDimming_default:toggleDimming.ts:4:3
async MessagePort.<anonymous>:index.js:1:1662
```

CleanShot 2021-11-30 at 14 23 11@2x
`

And the same for all other commands. Can you please take a look at that?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ratoru 👋 

Thank you for an awesome extension for controlling HazeOver 🔥 

I couldn't find anything wrong, only one NIT:

- Add shouldPop to the JSDoc

I'm going to accept it in one hour, if you can change it before this time it would be awesome 😄

**Comment by ratoru** [comment]
Hi! Thank you for the quick feedback. I'll take a look at both!

**Comment by pernielsentikaer** [comment]
> Hi! Thank you for the quick feedback. I'll take a look at both!
> 
> * [x]  Added shouldPop to the JSDoc
> * [ ]  No HazeOver error handling
> 
> Since 3 of the 4 commands are non-view commands, I have an implementation that ignores all AppleScript errors instead of causing the "dead" screen. Is that preferred? If so, I can commit that.

You could maybe add a HUD showing the error?

**Comment by ratoru** [comment]
That works great! Thanks for the tip, Per. It should be fixed now.

**Comment by mattisssa** [comment]
Hey @ratoru! Thanks for the changes, looks like now I have proper behaviour. But actually, I don't think a HUD is the right thing to use to show this kind of errors, I would recommend updating it again and using `Toast.Failure` style instead 😉

**Review by mattisssa — CHANGES_REQUESTED** [review]
As I mentioned in comments, please update the error showing, Requeset me to re-review the PR once you're ready 👍

**Comment by ratoru** [comment]
Okay, there should be a Toast error for increment and decrement now. Setting the value directly does not cause an error with the AppleScript, so I can't show an error message.

The HUD gives a slight performance improvement since I can close the main window before running the AppleScript. I feel like that's worth having a suboptimal error message for (i.e. HUD) since this error should be quite rare.

**Review by mattisssa — APPROVED** [review]
Thank you for all these changes! Now it looks much better 👍

**Pull request merged**
