### PR TITLE
Add `FBI` extension (view art crimes and wanted persons)

### PR DESCRIPTION
**Pull request by xmok**
## Description

This is a simple extension I created in May. By default, the extension disables "Wanted Persons" as the data might be unpalatable to some people. If the command is enabled, markdown is hidden (can be changed in Preferences) which hides images - all this has been done keeping in mind user sensibilities.

## Screencast

https://github.com/user-attachments/assets/7efe9424-71ad-4c6d-9f5b-295ee9430aca

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I'm not sure the List.Section does anything useful here since, when you use pagination, it still shows 40 of xxx. However, besides that, I like it.

**Comment by xmok** [comment]
I intended it to give a user an idea of how many items are in total or in a query e.g. check out the following screenshot where I've searched "fruit" in `Art Crimes` which shows how many items of the total meet the criteria.

Screenshot 2024-10-14 at 3 44 49 PM

But if it doesn't make sense, removing the Section is trivial.

**Comment by pernielsentikaer** [comment]
Let's just keep it as is 🙂

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
