### PR TITLE
[parrot-translate] feat: support to open in Eudic and search the queried text

### PR DESCRIPTION
**Pull request by tisfeng**
## Description

- feat: support to open in Eudic and search the queried text
- feat: add shortcut keys to open in Eudic and play the pronunciation of the queried text
## Screencast

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tisfeng** [comment]
Implement features described by issues:  #1685 #1683

**Comment by Haojen** [comment]
@tisfeng 👋
I'm currently adding the ability to display long text translations to Raycast, and I've also refactored a lot of code in the process.
My thoughts on the feature you submitted are as follows.
1. Similar dictionaries are not very commonly used requirements. I may consider that not only Continental may also have other dictionaries added later, and I will add a function option here for this time because this shortcut menu is used for translation. Turning into a jump might go against his core functionality and take up more list items.
2. There are shortcut keys, maybe there is something wrong, I will fix it in the later version.

**Comment by tisfeng** [comment]
> will maybe add a function option in setting, let user to choice enable. 

This might be a good idea, since [parrot translate] seems to be more about translation than dictionary lookup and word management, and offering it in an optional way is in line with its current positioning.

Since I'm used to using Eudic on a daily basis, I prefer it when it comes to word queries or sentence translations. [parrot-Translate] is a great extension and I like it, so I'd like it to work with Eudic as well, which is a strong personal preference. I was looking forward to this feature so much that I developed it myself, and it has been working well in practice lately, so I wanted to open it up for partners who may have the same interests and preferences as me.

It would be nice if you could incorporate this feature into [parrot Translate] in a appropriate way that would benefit more enthusiasts. Thank you

**Comment by tisfeng** [comment]
Inspired by your project, I may later develop an extension specifically for Eudic, which can be used to query, mark, add or delete words, open queries in Eudic and so on. But I don't have enough free time right now, and I'm not familiar with TypeScript, so that's probably a plan for a long time.

**Comment by Haojen** [comment]
> > will maybe add a function option in setting, let user to choice enable.
> 
> This might be a good idea, since [parrot translate] seems to be more about translation than dictionary lookup and word management, and offering it in an optional way is in line with its current positioning.
> 
> Since I'm used to using Eudic on a daily basis, I prefer it when it comes to word queries or sentence translations. [parrot-Translate] is a great extension and I like it, so I'd like it to work with Eudic as well, which is a strong personal preference. I was looking forward to this feature so much that I developed it myself, and it has been working well in practice lately, so I wanted to open it up for partners who may have the same interests and preferences as me.
> 
> It would be nice if you could incorporate this feature into [parrot Translate] in a appropriate way that would benefit more enthusiasts. Thank you

I also need like Eudic too, but as my say Parrot more like a Translator, I will add Eudic or another third-party dictionary, but I need more think Integration of products and requirements best way

**Comment by pernielsentikaer** [comment]
What's the status here, what do you think @Haojen

**Comment by Haojen** [comment]
> What's the status here, what do you think @Haojen

You can close this PR now.  thanks

**Comment by tisfeng** [comment]
ok, I close this PR.

**Comment by Haojen** [comment]
@tisfeng I updated a new version and changed a lot, including UI adjustments and supporting EuDic. https://github.com/raycast/extensions/pull/1791

**Comment by tisfeng** [comment]
> @tisfeng I updated a new version and changed a lot, including UI adjustments and supporting EuDic. #1791

ok, I will see it

**Comment by tisfeng** [comment]
> 2. The shortcut key function was originally there. If there is any problem, I will fix it in the later version. It should be launched with the version of this function I am working on.

hi,

**Comment by Haojen** [comment]
> > 2. The shortcut key function was originally there. If there is any problem, I will fix it in the later version. It should be launched with the version of this function I am working on.
> 
> @Haojen Hi, I saw the new version you released. Is it the shortcut key that originally supports playing voice? or did I miss anything?
> 
> image

Try command +  1, 2, 3 etc. Raycast default shortcuts, we don't need custom a new

**Comment by tisfeng** [comment]
OK, I see.

**Pull request closed without merging**
