### PR TITLE
feat(toggle-desktop-visibility): support sonoma and add more commands

### LINKED ISSUE #8599: [Toggle Desktop Visibility] better show/hide icons (and widgets) on sonoma
### Extension

https://www.raycast.com/Haojen/toggle-desktop-visibility

### Description

In macOS Sonoma, it seems that you can show/hide desktop icons in Settings, so there will be no need for the kinda clunky way that icons are currently hid/shown, requiring a `killall Finder`

perhaps also add more commands to individually control each preference, for showing/hiding in stage manager as well.

### Who will benefit from this feature?

everyone on sonoma

### Anything else?

images:

CleanShot 2023-09-27 at 18 25 56

<br/>

CleanShot 2023-09-27 at 18 30 34

I can PR this after I upgrade to sonoma.

### PR DESCRIPTION
**Pull request by erics118**
## Description

- sonoma now uses a better method of showing/hiding icons
- added support for widgets
- add dedicated show and hide commands for icons (disabled by default)
- add dedicated show and hide commands for widgets (disabled by default)

Fixes #8599

## Screencast

Sonoma:

https://github.com/raycast/extensions/assets/52634785/2fd1db72-1b67-4f58-b7e0-14cc4cc7bb98

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by erics118** [comment]
I can't test this on Montereoy bc I don't have another computer to use.

**Comment by pernielsentikaer** [comment]
@Haojen do you mind checking this?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by pernielsentikaer — COMMENTED** [review]
IF something pops up we can always look into it for this one

**Pull request merged**
