### PR TITLE
[GitHub] Show Issue/PR number in Notification

### LINKED ISSUE #7068: [GitHub] Show Issue/PR number in Notifications action
### Extension

https://www.raycast.com/raycast/github

### Description

Currently in `Notifications` action, Issue/PR numbers are not shown unlike `Search Pull Requests` or `Search Issues`. I believe it would be useful if the Issue/PR numbers are shown in `Notifications` too!

##### In `Search Pull Request`
image

##### In `Notification`
image

### Who will benefit from this feature?

Users who want to work with the Issue/PR numbers. Specifically (in my case), `gh pr checkout` uses the number of the PR the user want to work with. Although the link can be used as an argument, it would be really nice if I could start working just by quickly glancing at the title and number of the PR!

### Anything else?

- [Documentation of `gh pr checkout`](https://cli.github.com/manual/gh_pr_checkout)

### PR DESCRIPTION
**Pull request by loxygenK**
## Description

This PR newly shows Issue/PR number (#...) in `Notifications` command in GitHub extension.

Closes #7068.

- I initially planned to add the issue/PR number to `accessories` props of `List.Item` as written in the issue, but I realized it shows the number at the right of the list item, which differs from other commands like `Search Issues`. So instead I added the number to the subtitle.
- This PR also includes generated GraphQL scheme updates.

## Screencast

Elements underlined with purple lines are those added in this PR:

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaslombart — COMMENTED** [review]
Thanks a lot for this PR 💪
I've added just two comments to make the code a bit less verbose.

**Comment by loxygenK** [comment]
Thanks for the review! I applied suggested changes.

**Review by thomaslombart — APPROVED** [review]
🚀

**Comment by loxygenK** [comment]
Thanks for the your code review & support! 🚀🚀

**Pull request merged**
