### PR TITLE
Add safari-tab-copy extension

### PR DESCRIPTION
**Pull request by rknightuk**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by erics118** [comment]
I think the Safari extension: https://www.raycast.com/loris/safari already has something similar, where you can copy a single tab's title, url, and as markdown

**Comment by rknightuk** [comment]
You're right it does but it only does it for a single tab and also doesn't have the other formatting options like this one has.

**Comment by pernielsentikaer** [comment]
Thanks for the contribution 🔥 

Wouldn't it make sense to enhance the safari extension by @loris with this?

**Comment by rknightuk** [comment]
I'd certainly be open to that if this is something @loris wanted to include

**Comment by pernielsentikaer** [comment]
Wrote a message to @loris in our community; let's give him a few days to respond

**Comment by pernielsentikaer** [comment]
Sounds like a good plan, will you open a new PR to that or do it in this?

**Pull request closed without merging**
