### PR TITLE
Notion – Add Database and Page Preview

### PR DESCRIPTION
**Pull request by HenriChabrand**
## Description

Allows users to:
- Preview pages (markdown)
- Preview database items

## Type of change

- Bug fix / improvement for my extension

## Screencast

Screenshot 2021-11-29 at 17 49 46
Screenshot 2021-11-29 at 17 50 00

Here is a quick demo:
https://www.loom.com/share/ff52693a98e643b4a94bf9282401f00b

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @HenriChabrand 👋 You're on 🔥 with all the awesome improvements 🚀 

- I tested it and it seems to work as expected, one question, should checkboxes be supported, if so, there might be a bug and if not, maybe its possible to keep the linebreaks somehow?

FPRdrUq4YaYRUibp

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pernielsentikaer** [comment]
And as always, catch me in Slack if needed 😄

**Comment by pernielsentikaer** [comment]
Hi @HenriChabrand 👋 

I still see the same as above image, are you use its added the right place?

I can't look myself since the history since my last comment are gone, did you merge a special way? 😄

**Comment by HenriChabrand** [comment]
So weird @pernielsentikaer 🤔

I just fetched and merged the upstream from Raycast repo before uploading my changes:
Screenshot 2021-12-01 at 08 45 29

I've no idea why my changes haven't been taken into account.

Anyway, here's the fix and the outcome:
Screenshot 2021-11-30 at 14 35 14

**⚠️ Disclaimer :**
For now, the page preview only display simple/linear page with basic blocks.
It doesn't take into account callout, page or people link – as well as complex column structure and indentation.

**Review by pernielsentikaer — APPROVED** [review]
Hi @HenriChabrand 🔥 

You're literally on fire!!! Thanks for another awesome update 💯

**Pull request merged**
