### PR TITLE
New Extension: Geist UI Components

### PR DESCRIPTION
**Pull request by Rahuls-Coding**
## Description

This extension can help you quickly access the Geist UI component documentation. There are multiple commands for this extension. In each command there are a links to components in Geist UI. For example, in the General command, you'll find general components, such as Text component, Button component, etc. 

## Screencast

https://user-images.githubusercontent.com/93681641/182150979-3d6b9390-caa1-4ee8-98e4-e35ac3b3f99f.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪

It works as expected, but I think it could be cool just to have one command instead and separate with sections instead, something like this:

CleanShot 2022-08-09 at 10 03 03@2x

That would make it much easier to filter and find the right data faster, what do you think about that?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Rahuls-Coding** [comment]
Sure thing, that sounds good to me! Thanks for reaching out!

**Comment by pernielsentikaer** [comment]
Do you need any help with this @Rahuls-Coding

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
