### PR TITLE
New Extension: Archiver, a missing archive tool in the Raycast Store

### PR DESCRIPTION
**Pull request by 404J**
## Description

An archive tool for compressing or extracting, supporting multiple formats.

## Screencast

archiver-1
archiver-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* At the moment, this won't work when you have this setting enabled since the command will be unloaded when picking from `Finder` - we're working on a new File/Folder picker component that will do the trick.

CleanShot 2022-10-12 at 13 43 08@2x


I think the new component will be added within a month (hopefully) - maybe we should convert it to a draft until it's ready?

**Comment by 404J** [comment]
@pernielsentikaer Thinks for your test! I will use this component as soon as it is released. BTW, it will support multiple choice, right?

**Comment by pernielsentikaer** [comment]
Yes it will 😊

**Comment by 404J** [comment]
@pernielsentikaer you may want to check this PR~ I have used the new File/Folder picker component.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
