### PR TITLE
Update lucide-icons extension

### LINKED ISSUE #8191: [Lucide Icons Search] Doesn't have same results as site
### Extension

https://www.raycast.com/basil/lucide-icons

### Description

The search doesn't have the same results as the website, this can make it harder, and annoying, to search from the extension. The extension requires it to be more specific

Example:

vengeance2023-09-01 at 08 09 39

vengeance2023-09-01 at 08 09 49

### Steps To Reproduce

1. Search "group" on both the site and extension
2. See the results are different

### Current Behaviour

Website results do not match extension results

### Expected Behaviour

Extension results match website results

### PR DESCRIPTION
**Pull request by WilliamWelsh**
## Description

- Updated to include the latest icons and icon changes
- The search results now match the search results on Lucide's website due to the changes below (fixes #8191)
- Prebuild script now includes saving the JSON metadata associated with each icon
- The grid now uses the `tags` and `categories` from the associated JSON metadata as keywords

## Screencast
lucide-icons-1
vengeance2023-09-10 at 14 52 29@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Is there a way to make that happen, could we pull the data from somewhere to supportPath instead?

**Comment by WilliamWelsh** [comment]
Maybe unpkg

**Comment by pernielsentikaer** [comment]
That could maybe work, is that possible?

**Comment by WilliamWelsh** [comment]
I guess every time they run it I could have it check for updates

**Comment by pernielsentikaer** [comment]
Raycast caches all files automatically. So, I suppose you could follow what @gBasil said and only check if it has been more than 24 hours since the last check.

**Comment by pernielsentikaer** [comment]
Looks like extensions like other extensions downloading them from the web

* https://www.raycast.com/zavbala/tabler
* https://www.raycast.com/praveenjuge/mynaui-icons

**Pull request closed without merging**
