### PR TITLE
[New Extension] - Brave Search

### PR DESCRIPTION
**Pull request by VishwasShashidhar**
## Description

Brave Search provides the ability for users to search with brave search with auto-suggestions

## Screencast

https://user-images.githubusercontent.com/5968790/209971691-54819661-76df-4382-8f95-ac147eaf938d.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by ron-myers** [comment]
Hey @VishwasShashidhar  👋  If you are open to it, it would be cool to see this in the [Brave extension](https://www.raycast.com/ron-myers/brave).

Feel free to DM me if you would like to discuss this. 😃

**Comment by VishwasShashidhar** [comment]
> Hey @VishwasShashidhar 👋 If you are open to it, it would be cool to see this in the [Brave extension](https://www.raycast.com/ron-myers/brave).
> 
> Feel free to DM me if you would like to discuss this. 😃

Hey @ron-myers, thanks for the suggestion 🙂. I thought about it initially, but, since Brave Search is an independent service (independent of the Brave Browser), I created a separate extension for it.

However, I don't know what is the best practise in this case with Raycast, so, I'm open to whatever the community suggests 🙂

**Comment by pernielsentikaer** [comment]
This seems to be the same as #3966, which is already in the queue 😊 This might have something that the other doesn't have so it might make sense to take the best from the both

**Comment by VishwasShashidhar** [comment]
@pernielsentikaer Sure, works for me as long as we have all the features 🙂

**Comment by VishwasShashidhar** [comment]
@pernielsentikaer Is there anything else required to merge this PR? Please let me know.

Also, I see that you've added @Spl0itable as a contributor in `package.json`, however, CI is failing since that doesn't seem to be their raycast username.

**Comment by Spl0itable** [comment]
My raycast username is @0xChain thanks.

**Comment by VishwasShashidhar** [comment]
> My raycast username is @0xChain thanks.

Thanks @Spl0itable, updated.

**Comment by pernielsentikaer** [comment]
Hi @VishwasShashidhar 👋 

Could you remove .vscode/settings.json from your PR? 😊

**Comment by VishwasShashidhar** [comment]
> Hi @VishwasShashidhar 👋
> 
> Could you remove .vscode/settings.json from your PR? 😊

Done @pernielsentikaer 🙂

**Comment by pernielsentikaer** [comment]
Thanks 🎉

**Pull request merged**
