### PR TITLE
New Extension: Ethereum Gas Tracker

### PR DESCRIPTION
**Pull request by vinch**
## Description

A new extension to track the current gas price of Ethereum in the Menu Bar.

## Screenshots

screenshot-1
screenshot-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by peduarte — COMMENTED** [review]
icon idea 
gas-icon

**Comment by vinch** [comment]
> LGTM. one thing i'd do is re-take the first screenshot with the updated icon. Needs approval by @pernielsentikaer

Indeed I completely forgot about that one, thanks!

**Review by pernielsentikaer — APPROVED** [review]
Hi @vinch 👋 

Thanks for the contribution 💯 

For now, I have removed the metadata images since we haven't tackled this part yet.

We're planning a new Figma template to support extensions that only have a menubar, but we're not yet ready with that; I'll try to keep you updated when we have a good solution for this 🙂

**Comment by vinch** [comment]
OK, thanks @pernielsentikaer 👍

**Pull request merged**
