### PR TITLE
Add mastodon extension

### PR DESCRIPTION
**Pull request by BasixKOR**
## Description
This PR adds a Mastodon extension in hopes of becoming what the Twitter extension brought to Raycast.

## Screencast
스크린샷 2023-02-27 오전 5 12 00

스크린샷 2023-02-27 오전 5 12 13

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
What do you think about this view for the command `Home`

Raycast-FQ20uo0R@2x

I can share source so you don't have to do it manually 😊 

The same view has empty state flicker, when checking the `isLoading` property on the list, i shows:

```
12:09:03.459 true
12:09:03.461 true
12:09:03.462 true
12:09:03.506 false
12:09:03.507 true
12:09:04.483 false
```

It should only go from true -> false 😊

**Comment by pernielsentikaer** [comment]
This is from the `home` command:
```
import { List } from "@raycast/api";
import { usePromise } from "@raycast/utils";
import { useMasto } from "./hooks/masto";
import StatusItem from "./components/StatusItem";
import { mastodon } from "masto";

export default function Home() {
  const masto = useMasto();
  const { data, isLoading, revalidate } = usePromise(
    async (masto?: mastodon.Client) => {
      if (!masto) return;
      return await masto?.v1.timelines.listHome();
    },
    [masto]
  );

  console.log(!masto || isLoading, !masto, isLoading);

  return (
    <List isLoading={!masto || isLoading} isShowingDetail>
      {data?.map((status) => (
        <StatusItem key={status.id} status={status} revalidate={revalidate} />
      ))}
    </List>
  );
}
```

**Comment by BasixKOR** [comment]
I don't see how the code you provided is different from the source code now other than console.log. However, I've moved the avatar to the left and something I'd like to know is how to render the custom emojis in the Detail component as if it was a glyph.

And the flicker seems to be caused by usePromise returning `isLoading: false` when masto is not loaded (yet). Because there is no straightforward way to handle the dependencies of the usePromise yet, I'll just check if the data is empty instead.

**Comment by pernielsentikaer** [comment]
I shared the wrong file
```
import { Action, ActionPanel, Icon, LaunchType, List, confirmAlert, launchCommand, showToast } from "@raycast/api";
import { mastodon } from "masto";
import { stripHtml } from "string-strip-html";
import { useMasto, useMe } from "../hooks/masto";
import dedent from "dedent";
import FavoriteAction from "./status/FavoriteAction";
import ReblogAction from "./status/ReblogAction";
import { getIconForVisibility, getNameForVisibility, isVisiblityPrivate } from "../utils/visiblity";
import BookmarkAction from "./status/BookmarkAction";

interface Props {
  status: mastodon.v1.Status;
  revalidate?: () => Promise<unknown>;
}

export default function StatusItem({ status: originalStatus, revalidate }: Props) {
  const masto = useMasto();
  const { data: me } = useMe(masto);
  const status = originalStatus.reblog ?? originalStatus;
  const content = status.spoilerText || status.text || stripHtml(status.content).result;

  return (
    <List.Item
      title={content}
      icon={status.account.avatar}
      accessories={[isVisiblityPrivate(status.visibility) && { icon: getIconForVisibility(status.visibility) }].filter(
        Boolean
      )}
      detail={
        <List.Item.Detail
          markdown={dedent`
            ## ${status.account.displayName.replace(":verified_coffee:", "![](verified2.png)")} \`${
            status.account.acct
          }\`

            ${content}

            ${status.mediaAttachments.map((media) => {
              switch (media.type) {
                case "image":
                case "gifv":
                  return `![${media.description ?? ""}](${media.previewUrl})`;
                default:
                  return "";
              }
            })}

            ${status.card ? `[${status.card.title}](${status.card.url})` : ""}
          `}
          metadata={
            <List.Item.Detail.Metadata>
              <List.Item.Detail.Metadata.Label title="Reblogs" text={String(status.reblogsCount)} icon={Icon.Repeat} />
              <List.Item.Detail.Metadata.Label
                title="Favorites"
                text={String(status.favouritesCount)}
                icon={Icon.Star}
              />
              <List.Item.Detail.Metadata.Label title="Replies" text={String(status.repliesCount)} icon={Icon.Reply} />
              <List.Item.Detail.Metadata.Separator />
              <List.Item.Detail.Metadata.Label
                title="Visibility"
                text={getNameForVisibility(status.visibility)}
                icon={getIconForVisibility(status.visibility)}
              />
              {status.application?.website && [
                <List.Item.Detail.Metadata.Separator />,
                <List.Item.Detail.Metadata.Link
                  title="Application"
                  text={status.application.name}
                  target={status.application.website}
                />,
              ]}
              {originalStatus.reblog && [
                <List.Item.Detail.Metadata.Separator />,
                <List.Item.Detail.Metadata.Label
                  title="Reblogged by"
                  text={originalStatus.account.displayName}
                  icon={originalStatus.account.avatar}
                />,
              ]}
            </List.Item.Detail.Metadata>
          }
        />
      }
      actions={
        <ActionPanel>
          {status.url && <Action.OpenInBrowser url={status.url} />}
          <Action
            title="Reply"
            icon={Icon.Reply}
            onAction={async () => {
              launchCommand({ name: "post", type: LaunchType.UserInitiated, context: { replyTo: status } });
            }}
          />
          <ReblogAction id={status.id} reblogged={status.reblogged ?? false} masto={masto} />
          <FavoriteAction id={status.id} favorited={status.favourited ?? false} masto={masto} />
          <BookmarkAction id={status.id} bookmarked={status.bookmarked ?? false} masto={masto} />
          {status.account.id === me?.id && (
            <ActionPanel.Section title="Manage my status">
              <Action
                title="Delete"
                icon={Icon.MinusCircle}
                style={Action.Style.Destructive}
                shortcut={{ modifiers: ["cmd"], key: "backspace" }}
                onAction={async () => {
                  if (!(await confirmAlert({ title: "Are you sure?" }))) return;
                  await masto?.v1.statuses.remove(status.id);
                  await revalidate?.();
                  showToast({ title: "Successfully deleted!" });
                }}
              />
              <Action
                title="Edit"
                icon={Icon.Pencil}
                shortcut={{ modifiers: ["cmd"], key: "e" }}
                onAction={async () => {
                  const source = await masto?.v1.statuses.fetchSource(status.id);
                  launchCommand({
                    name: "post",
                    type: LaunchType.UserInitiated,
                    context: {
                      action: "edit",
                      status: {
                        ...status,
                        text: source?.text,
                        spoilerText: source?.spoilerText,
                      },
                    },
                  });
                }}
              />
            </ActionPanel.Section>
          )}
        </ActionPanel>
      }
    />
  );
}
```

verified2

**Comment by fmerian** [comment]
oh no :/

any update on this? @BasixKOR @pernielsentikaer

**Comment by BasixKOR** [comment]
Oh, I think I forgot to push the changes to the PR...

**Comment by BasixKOR** [comment]
The mentioned problems should be fixed by the last commit.

**Comment by pernielsentikaer** [comment]
Did you see my shared code? Don't you want to add that?

**Comment by pernielsentikaer** [comment]
Seems like the loading state is a bit wrong here, could you look into having loading = true from the start?

https://user-images.githubusercontent.com/38033107/231948980-4bd75470-d6eb-45c3-ae73-fe8e0cec2195.mp4

**Comment by pernielsentikaer** [comment]
@BasixKOR has been working on #5001 for some time and it seems like it’s almost ready.

Now we also have #6117 and #6156 in the queue, we need to decide what to do with all three, are you up for selecting the best version and going with that and improving with the feature respectably from the other PRs?

**Comment by BasixKOR** [comment]
I've left comments on the two PRs you've mentioned. It seems like #6156 has a better implementation on how it approaches OAuth (I assumed PKCEClient was unavailable on Mastodon, but it seems like it can work), but this PR has some features missing on the @SevicheCC's implementation.

I think the feature parity is somewhat similar, so I think I'd prefer to help @SevicheCC to implement some of the features since this PR's codebase became a bit of a mess due to handling masto.js with `usePromise` (which caused all sorts of incorrect loading status you've mentioned).

**Comment by pernielsentikaer** [comment]
So we're closing this in favor of #6156, or?

**Comment by BasixKOR** [comment]
Closing as superseded by #6156.

**Pull request closed without merging**
