### PR TITLE
Add kepa extension

### PR DESCRIPTION
**Pull request by Piarre**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Piarre** [comment]
Im using bun sorry

**Comment by koinzhang** [comment]
Do these two extensions do the same thing?
https://www.raycast.com/dimagrossman/ssh-manager

**Comment by Piarre** [comment]
Ho, yes it does mb

**Comment by Piarre** [comment]
With mine I can't create a connection, for the moment I can only create ssh connection but I will soon implement this api https://github.com/kepa01/api

**Comment by pernielsentikaer** [comment]
If they do the same I don't t hink we should add another extension with the same purpose, if the current one that @koinzhang mentions missing something it's much better to the enhance that one instead

**Pull request closed without merging**
