### PR TITLE
Update vmware-vcenter extension

### PR DESCRIPTION
**Pull request by MassimilianoPasquini97**
## Description

- [BREAKING] Moved vCenter configuration from extension preferences to LocalStorage. Is required to reconfigure vCenter Server.
- Manage multiple vCenter Servers.
- List object of all configured vCenter Servers with 'All'.
- Added 'Refresh' Action for update information. On 'Virtual Machines' Command it refresh information of selected vm.
- Added 'Open Rdp' Action for open an rdp connection using Microsoft Remote Desktop App.
- Added 'Certificate Validation Enabled' on preferences, disabled by default. If enabled it verify certificate is valid.
- Implemented cache system for improve performance.
- Updated VmGuestOS.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Why do you want to move to a form, is that because of validation? 

- I would use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) instead and make the validation with that instead of disabling the action, `useForm` handles state, validation and errors too 🙂

**Comment by MassimilianoPasquini97** [comment]
Thanks @pernielsentikaer for your advice on useForm, with that I have removed all boilerplate code used for handles state, validation and errors. 🙏🏻

Is there a way for pushing latest [commit](https://github.com/MassimilianoPasquini97/raycast_vmware_vcenter/commit/d132bb551c13744e0fd439ea8ab822eb758cca48) on this pr without opening a new one?

**Comment by pernielsentikaer** [comment]
You just need to push to your branch `MassimilianoPasquini97:ext/vmware-vcenter` and it should be fine 🙂

If you used the publish command, then you can use it again :)

**Review by pernielsentikaer — APPROVED** [review]
✅ Approved

**Pull request merged**
