### PR TITLE
YouTube: Add IINA and VLC support

### PR DESCRIPTION
**Pull request by tonka3000**
## Description

Add Open with support for

- ~~VLC~~
- IINA

Also add Copy Video URL action to videos.

## Type of change

- Bug fix / improvement for my extension

## Screencast

CleanShot 2021-11-16 at 12 58 25@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by theofficialgrand1** [comment]
Poggers

**Comment by pernielsentikaer** [comment]
Hi @tonka3000 👋 

It would be an awesome update, however, I'm struggling a bit getting it to work 😢 

When opening a few videos in VLC just give me this
1U3aVRu4SX2lSnoh

**Comment by tonka3000** [comment]
@pernielsentikaer did you try another video as well? It seems that not every video from YouTube is playable in VLC (but this is not probable from the extension). Also make sure to have the newest version of VLC.

**Comment by pernielsentikaer** [comment]
@tonka3000 VLC has been working on 0/8 videos, IINA 8/8 (the same videos).

Do you have any videos that should work, I can check?

Tested with:
- VLC Version 3.0.16 Vetinari (Apple Silicon)
- IIMA Version 1.2.0 Build 129

**Comment by tonka3000** [comment]
@pernielsentikaer https://youtube.com/watch?v=rt-2cxAiPJk works on VLC on my machine.

I have the same VLC version, but the intel one. Maybe an M1 issue. Try out if opening just the url manually in VLC would work.

**Comment by pernielsentikaer** [comment]
@tonka3000 yeah- that one works fine - I can't open this one: https://youtube.com/watch?v=LRP8d7hhpoQ - can you?

**Comment by tonka3000** [comment]
@pernielsentikaer no, this wont work. Seems to be a VLC problem.

**Comment by pernielsentikaer** [comment]
@tonka3000 It's a strange one indeed, for me, it's failing almost everything with VLC and works with everything in IINA. In IINA it buffering all the time even though I have 200/200 — it should be possible to run without lag. 

When taking the URL from the error log in VLC and trying it in a browser, I get this response:

```
Access to r3---sn-nuv45-55gl.googlevideo.com was denied
You don't have authorisation to view this page.
HTTP ERROR 403
```

I'm not sure what to suggest right now actually, I'll try from two other locations (and machines) tomorrow and check how it goes, I'll get back to you 😄

**Comment by theofficialgrand1** [comment]
Do people actually still use VLC.....?

**Comment by pernielsentikaer** [comment]
Didn't have more success with VLC from other machine or network, IINA was still working in 99% of the cases, but lagged.

Did you try the addition @theofficialgrand1 ?

**Comment by tonka3000** [comment]
I can remove VLC for now, should be no big deal.

**Comment by pernielsentikaer** [comment]
> I can remove VLC for now, should be no big deal.

Until better support it makes sense to remove it and then we'll keep an eye on it 😊

**Comment by tonka3000** [comment]
@pernielsentikaer VLC support is removed now.

CleanShot 2021-11-16 at 12 58 25@2x

**Comment by pernielsentikaer** [comment]
Hi @tonka3000 👋 

Tried 5 random songs with the “Open with IINA” and 5/5 is lagging every 3 second — tried from different fiber connections in three different ISPs and speed (Mbit):

- 100/100 
- 200/200
- 500/500

No matter what connections I used, I had a lag every 3 seconds. Do you have the same behavior?

Searched for different genres and years:

- Darude - Sandsotrm
- Pentatonix - Halleluja
- Tony Braxton - Un-break my heart
- Toybox - Tarzan
- psy - gangnam style

**Comment by tonka3000** [comment]
But that is an IINA upstream problem. Not Fixable from the extension side.

**Comment by grandwastaken** [comment]
I think that this addition would be added in the future when IINA fixes their bugs. So letting it be added now is fine.

**Comment by pernielsentikaer** [comment]
Let's add it and of course, IINA uses Raycast themselves and fix it soon 😄

**Pull request merged**
