### PR TITLE
[Spotify-Controls] Add step setting for volume commands

### PR DESCRIPTION
**Pull request by amureki**
## Description

Added a configuration to change step for volume controls instead of having it fixed to 10%.

## Screencast

CleanShot 2023-02-07 at 14 50 56

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @amureki 👋 

I made a few improvements to ensure the input can be used, do you mind giving it a go 😊

**Comment by amureki** [comment]
> Hi @amureki 👋
> 
> I made a few improvements to ensure the input can be used, do you mind giving it a go 😊

Oh, sure, thank you for great additions!

**Comment by pernielsentikaer** [comment]
Can't figure out if it would be good to show a HUD when performing the actions? 

Raycast-CvSBvfcJ@2x

**Comment by amureki** [comment]
>Can't figure out if it would be good to show a HUD when performing the actions?

Interesting idea. 
I, personally, do not need a visual confirmation, as I instantly hear the difference with my setup. 
But can't speak for the others. However, I think this might go beyond the scope of this PR and can be introduced for more commands that were not touched here (like setting volume to certain level, changing the track etc.).

**Review by pernielsentikaer — APPROVED** [review]

**Comment by amureki** [comment]
Awesome, thank you @pernielsentikaer for finishing this up! ✨

**Pull request merged**
