### PR TITLE
Update Bitwarden master password input to hide password

### PR DESCRIPTION
**Pull request by AmayruN5**
## Description

Update Bitwarden master password input to hide password

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @pomdtr 

### Current behaviour
image

### Updated behaviour
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Comment by mattisssa** [comment]
Small spoiler, we will introduce specific password field very soon, so this feature could probably be not very actual 😉

**Comment by pomdtr** [comment]
Thanks for the contribution @AmayruN5 !
I think we should wait for the native password field type mentionned by @mattisssa, what do you think ?

**Comment by AmayruN5** [comment]
@pomdtr Yes, we can wait for the native one.

I just was frustrated with seeing my master password every time I need to unlock the vault. And couldn't wait for native password input, so I modified the extension.
At least it could be a temporary solution for hiding a password. If somebody needs it.

**Comment by pernielsentikaer** [comment]
Hi @AmayruN5 👋 

Why wait? It should be easy to incorporate the new type when it's released 💯 

I did a quick review, and it seems like it's actually sending the password as stars instead of the right password 😵‍💫 Did you test it yourself, could be that I'm mistaken.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by AmayruN5** [comment]
@pernielsentikaer  Hello, thanks for your review.
Yes, I haven't copied the part related to sending a correct password value from my local version of the extension.

I closed PR because I realized an unexpected behavior of my solution. It can not handle a case when user deletes characters at some part of password (not from the end). Which may cause sending an incorrect password. 
So I think it's better not to make any changes now and wait for the native password field.

**Comment by pernielsentikaer** [comment]
I'll let it be up to you @AmayruN5 – if you can't solve it without using massive amount of time, it could be better closing and wait as stated 😄

**Comment by pernielsentikaer** [comment]
There is now support for password in Form 😄

**Pull request closed without merging**
