### PR TITLE
Add devtools extension

### PR DESCRIPTION
**Pull request by frouo**
## Description

Add a collection of dev tools (commands) for everyday tasks. For now the only command I add is "Format JSON" that formats JSON from clipboard.

## Type of change

- New extension

## Screencast

https://user-images.githubusercontent.com/2499356/145694923-a769acb3-d6c8-4293-938d-101ef7b5ec4e.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @frouo 🔥 

Thanks for your contribution 💪 

Are you aware of that there is multiple extension that formats JSON and a toolbox?

* https://www.raycast.com/destiner/json-format
* https://www.raycast.com/Kang/toolbox  

It could be an idea to contact the author and help contribute to the already existing extension instead of making another one, let me know if you have any concerns regarding this

**Comment by frouo** [comment]
Hello @pernielsentikaer, thank you for reviewing.

Oh I did not see `toolbox`, sorry. And `json-format` did not yet exist when I first used Raycast (3 days ago) 😅.

I installed these extensions:
- `toolbox` is 1 command that lists features, it is not a collection of commands. So if I need to access a feature, I must first open the application. I personally prefer having commands right away just by pressing `Command + Space` (as in `Window Management` extension for example). So I think that toolbox / devtools concept is different. Besides, maybe I should rename this extension `devcommands`?
- `json-format`. Yes I can contact the author and contribute to make json-format meets my needs (as it is, this extension copies the result to the clipboard when I just would like to see the result).

What is best then:

Should I close the PR? Start contacting authors (including those listed in the `README.md`) to know what they think about the idea of merging their extension in a bigger one? Or ask the community (slack)?

**Comment by Destiner** [comment]
Hey there. Just stumbled upon this PR. I'm the author of `json-format` extension. Let me know if you want to collaborate!

**Comment by pernielsentikaer** [comment]
> * `toolbox` is 1 command that lists features, it is not a collection of commands. So if I need to access a feature, I must first open the application. I personally prefer having commands right away just by pressing `Command + Space` (as in `Window Management` extension for example). So I think that toolbox / devtools concept is different. Besides, maybe I should rename this extension `devcommands`?

You could bind the extension to a hotkey, then it's also starting in the “root” with all available commands like you want to

> Should I close the PR? Start contacting authors (including those listed in the `README.md`) to know what they think about the idea of merging their extension in a bigger one? Or ask the community (slack)?

It should be fine to tag them in this thread, they are both on GitHub (as you saw with @Destiner) — It would be preferable to close the PR and add it to the existing extensions due to similarities in them

We're planned on adding support for “contributors” in package.json, so co-authors also get credit, but I can't give you a date for that yet 😄

**Comment by frouo** [comment]
cc @DanielSinclair @AntonNiklasson @jmaeso @fe9lix

**Comment by fe9lix** [comment]
@Destiner @pernielsentikaer fyi: we do have support for the `contributors` now

**Comment by jmaeso** [comment]
Hey, not sure why I got tagged to the thread. My assumption is that I did (probably?) the smallest extension ever 😂 so it could be a great easy addition to a bigger toolbox.
I did the `uuid` extension to be able to have a new `uuid` in my clipboard by tapping `cmd + Space` -> `uuid` -> `Enter`, so please, whatever work is done with the toolbox, I would prefer not make this use-case longer in steps.
Feel free to include any `uuid` functionality wherever you desire, I don't deserve much merit on the code I submitted. I think it was literally a 3 lines feature.

**Pull request closed without merging**
