### PR TITLE
Add Video/GIF Modification extension

### PR DESCRIPTION
**Pull request by tonypinkevych**
### Motivation

I got tired of moving between different apps when I need something small like converting or optimizing a video. That's why I started using the `ffmpeg` cli. But it doesn't really fit because I have to memorize all the tricky parts of their cli. So I decided to create a simple wrapper around it.

### What it does

The extension allows you to optimize, convert and resize video and gif files using `ffmpeg` and `ffprobe`. At the moment the extension only works with a selection in the Finder.

### How it works

On first run, the extension will download the `ffmpeg` and `ffprobe` binaries from [https://www.osxexperts.net](https://www.osxexperts.net). I have not found any other public hosting of binaries for Intel and Silicon chips. So I am open to recommendations for security improvements.

The fetching mechanism can be checked at [binary.ts](https://github.com/raycast/extensions/blob/64c8e93aa205bd2aec1252cf48ae85d087ac6756/extensions/video-gif-modification/src/objects/binary.ts#L56) file. The endpoints and sha256 hashes at [ffmpeg.ts](https://github.com/raycast/extensions/blob/64c8e93aa205bd2aec1252cf48ae85d087ac6756/extensions/video-gif-modification/src/objects/ffmpeg.ts#L25) and [ffprobe.ts](https://github.com/raycast/extensions/blob/64c8e93aa205bd2aec1252cf48ae85d087ac6756/extensions/video-gif-modification/src/objects/ffprobe.ts#L22) respectively.

The binaries will then be stored in `environment.supportPath` and used from there.

## Screencast

https://github.com/raycast/extensions/assets/13913581/ede54906-6935-47dc-9d2c-a7b21193ba76

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tonypinkevych** [comment]
Just found this extension: https://github.com/raycast/extensions/pull/11894 by @pablopunk.
Looks like we came up with the same idea at the same time 😁

I'm not sure raycast needs two extensions in the store with the same functionality. As I see the only difference is the entry point and UX. You can close my PR @pernielsentikaer if you see fit, because `yafw` is already published in the store.

**Comment by pablopunk** [comment]
@tonypinkevych Mine only focuses on compressing videos. If you'd like, you could make a PR to add more commands and I'll happily review it 🙌🏻. Also, I'm not installing `ffmpeg` automatically, that could be added too. Latest code is [here](https://github.com/raycast/extensions/pull/12099)

**Comment by pernielsentikaer** [comment]
I don't know `www.osxexperts.net`, it sounds a bit dangerous just to trust the files from that page, or?

I agree, merging it into the current would be nice

**Comment by tonypinkevych** [comment]
@pernielsentikaer This site comes highly recommended on reddit, so I don't know. We can keep the local version of ffmpeg installed by homebrew. But that would reduce the number of potential users because of the external dependency.

I'll do another PR to extend `yafw` behavior in a few days. I will close this PR as soon as the new one is ready.

**Comment by tonypinkevych** [comment]
All code moved to https://github.com/raycast/extensions/pull/12147

**Pull request closed without merging**
