### PR TITLE
Add bibigpt-summarize-audiovideo-with-ai extension

### PR DESCRIPTION
**Pull request by hiskyline-123**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Since this require a token that I don't have, could you then make a screencast of the extension 🙂

- At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension. If the locale might affect functionality (e.g. using the correct unit of measurement), please use the preferences API.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by hiskyline-123** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * Since this require a token that I don't have, could you then make a screencast of the extension 🙂
> * At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension. If the locale might affect functionality (e.g. using the correct unit of measurement), please use the preferences API.
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Thanks for your feedback! Here are my responses:

Great! I've added two screenshots - one showing the loading process and the other displaying the successful summary in English.

I've now included localization configuration, and I've changed the default language for the extension's prompts to English.

I'm looking forward to your retest. Feel free to reach out if you have any more questions or need further assistance. 🔥

CleanShot 2024-02-06 at 20 43 00@2x
CleanShot 2024-02-06 at 20 43 18@2x

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by hiskyline-123** [comment]
> Hi 👋
> 
> Looks good to me, approved 🔥

Hi pernielsentikaer,

Thank you for your review and code corrections!

I would like to extend a sincere invitation for you to try out BibiGPT. You can sign up directly through GitHub and receive a 60-minute free trial. Additionally, by using the invitation link https://bibigpt.co/r/hiskyline, you can add an extra 60 minutes to your total summary time.

Best regards

**Review by Zhjngu — COMMENTED** [review]
Fgjjjj

**Pull request merged**
