### PR TITLE
feat(change-case): support quicklinks

### PR DESCRIPTION
**Pull request by erics118**
## Description

- remove execa dependency
- support quicklinks

## Screencast

(first one shows clipboard, second one shows selected text)
https://github.com/raycast/extensions/assets/52634785/607f9edf-3cbc-448e-ae97-f49df464c1cb

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by erics118** [comment]
Not sure why CI is failing

**Comment by pernielsentikaer** [comment]
I'll get an expert to help me here @erics118 🙂

**Comment by thomaslombart** [comment]
Hey @erics118, the CI is failing at the linting step. It seems it’s linked to the PR [upgrading TypeScript to 5.2](https://stackoverflow.com/questions/76996326/parsing-error-deprecationerror-originalkeywordkind-has-been-deprecated-since). I'm not entirely sure what's happening under the hood. In the meantime, you can downgrade it to TS 5.1.6 or 4.7.4 (as it was before).

**Comment by thomaslombart** [comment]
You need to run `npm lint --fix`

**Comment by thomaslombart** [comment]
Could you post a recording of your changes?

**Comment by erics118** [comment]
I added a video to the original post.

**Pull request merged**
