### PR TITLE
feat: ✨ Added Better Commit extension

### PR DESCRIPTION
**Pull request by BrieucCaillot**
## Description

Be able to create better commits with :prefix & gitmojis.

## Screencast

better-commit-prefixes
better-commit-gitmojis

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi there! 👋 

Thank you for your contribution. 🔥 

What is the difference between this and https://www.raycast.com/niemtec/conventional-commits made by @niemtec?

**Comment by niemtec** [comment]
I'd very much welcome some of these improvements if you'd like to contribute to my extension 😊

**Comment by BrieucCaillot** [comment]
The main difference is that Better Commit will append the emoji after the prefix : ex: feat: 🔥
Conventional Commits only allows to add prefixes, not emojis : ex: feat:

**Comment by pernielsentikaer** [comment]
Would it indeed be better for the end user to have only one extension? Otherwise, they end up being confused, as I am. 🙂

Would that be something you, @BrieucCaillot, would like to contribute to the current extension?

**Comment by whitespacecode** [comment]
> Would it indeed be better for the end user to have only one extension? Otherwise, they end up being confused, as I am. 🙂
> 
> Would that be something you, @BrieucCaillot, would like to contribute to the current extension?

There is already a extension for this https://www.raycast.com/krzysztofzuraw/conventional-comments
Maybe the easy list @niemtec created could be a new command ?

**Comment by pernielsentikaer** [comment]
I didn't even remember that one. Thanks for mentioning @whitespacecode. It makes sense to only have one extension. We can always enhance the current to make a better user experience

**Comment by whitespacecode** [comment]
I like the older one because it gives you the possibility to add a title and description. Only downside is that when submitting the form you get something like this: 
image
It should be `fix: This is a test `

**Pull request closed without merging**
