### PR TITLE
Add ratio-calculator extension

### PR DESCRIPTION
**Pull request by Justiniscoding**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mil3na — APPROVED** [review]
Hi!

Thanks for your contribution! My name is Milena and I will be reviewing your extension submission today.

It looks good to me! Thanks again for your contribution :)

**Comment by terryupton** [comment]
This is great. Thanks @Justiniscoding 👍🏻🎉

**Comment by terryupton** [comment]
@Justiniscoding  would it be possible to make this work with spaces ( ) as well or instead of colons (:) and no equals as it is much quicker? This is how it worked when I used in on Alfred.
For example:

800 500 8 x
_Would be 5_

8 5 800 x
_Would be 500_

So wherever the X is entered the value is calculated.
Thankyou.

**Comment by Justiniscoding** [comment]
> @Justiniscoding  would it be possible to make this work with spaces ( ) as well or instead of colons (:) and no equals as it is much quicker? This is how it worked when I used in on Alfred.
> 
> For example:
> 
> 
> 
> 800 500 8 x
> 
> _Would be 5_
> 
> 
> 
> 8 5 800 x
> 
> _Would be 500_
> 
> 
> 
> So wherever the X is entered the value is calculated.
> 
> Thankyou. 
> 
> 

Sure, working in the update now

**Comment by terryupton** [comment]
Any update on this @Justiniscoding ?
Thanks.

**Comment by terryupton** [comment]
Any update on this @Justiniscoding ?
Thanks.

**Pull request merged**
