### PR TITLE
Add SABnzbd extension

### PR DESCRIPTION
**Pull request by jesse-c**
## Description

[SABnzbd](https://sabnzbd.org) is a binary newsreader. 

There's a few simple commands at the moment but covers a few of the core things you'd want to do.

## Type of change

- New extension

## Screencast

raycast-sabnzbd-screencast

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Since I never tried it before it takes a lot of time setting it up and getting it to work and with every step something new happens and I'm not sure what I'm doing 😄

**Comment by jesse-c** [comment]
@pernielsentikaer: I've added a screencast. Please excuse the poor quality. 🤷🏼‍♂️

**Comment by PitNikola** [comment]
No idea what's happening there, but UX seems fine 😅

**Comment by PitNikola** [comment]
Small improvement suggestion for the future – expand a little bit in the description on what SABnzbd is so that users who have no clue what SABnzbd is could get some idea what it's for.

**Comment by jesse-c** [comment]
Thank you for the review and acceptance!

> No idea what's happening there, but UX seems fine 😅

Hopefully someone in the community can try it to verify it for them 😆 I'm happily using it day-to-day now though.

> Small improvement suggestion for the future – expand a little bit in the description on what SABnzbd is so that users who have no clue what SABnzbd is could get some idea what it's for.

Oh yes, good idea!

**Pull request merged**
