### PR TITLE
New Extension: Google Tasks

### PR DESCRIPTION
**Pull request by elliotdes**
## Description

An extension for viewing and interacting with Google Tasks.

## Screencast
google-tasks-1
google-tasks-2
google-tasks-3
google-tasks-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪

I tested your contribution and I have some feedback for you to address:

- The `Create Task` command doesn't seem to work at all, it just pops to root.
- When using `Create Task` from within `View Lists` could use some validation, it's possible to add a task without any information - check [useForm](https://developers.raycast.com/utilities/react-hooks/useform) out
- Maybe find a better wording for this action

CleanShot 2022-09-27 at 11 44 16@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by elliotdes** [comment]
@pernielsentikaer I have removed the `Create Task` action (the example [To Do](https://developers.raycast.com/examples/todo-list) does not have one) and I have implemented some validation on the create form.

**Comment by pernielsentikaer** [comment]
Could you check this @elliotdes if you're okay with the corrections?

**Comment by elliotdes** [comment]
@pernielsentikaer the changes look good to the icons! However I search the tasks within a list anymore? The search of lists still works. Let me know if it is the same on your end

**Comment by pernielsentikaer** [comment]
I don't have a problem with searching the list, is this the right view?

https://user-images.githubusercontent.com/38033107/207694204-27f536ea-8fb1-408e-8820-348c8c7f5775.mp4

**Comment by elliotdes** [comment]
@pernielsentikaer yeah thats the one! Must be an issue on my end. In that case, I am happy with the changes! Ready to merge when you are 😄

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
