### PR TITLE
New extension: Meme generator

### PR DESCRIPTION
**Pull request by timoransky**
## Description

Extension that uses Imgflip API to generate memes from most favorite templates.

## Screencast

https://user-images.githubusercontent.com/15653065/193561575-92be114f-55b6-43d8-95db-5bb64fa8277b.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by techvlad — APPROVED** [review]
I like it 🔥

**Comment by juhamust** [comment]
Is it possible to show the selected template _while_ filling in the values? Would help with usage / no need to remember where those texts are shown again 🤔

**Comment by timoransky** [comment]
Sadly the information about text boxes positions does not come in API response, so I would have to generate image on every text input change to get the preview. It is doable, but would definitely increase the number of API calls. 
Also I'm not sure how would I display form and preview image in the same view in Raycast. It might slow down the whole process, toggling back and forth between two views... But if you have any idea let me know and I can try 😊

**Comment by timoransky** [comment]
@pernielsentikaer Hi! 
Thanks for your feedback. I just tried to generate meme using the same codebase and its working fine for me. 😁 
Can you can please check if there are some filled values in extension preferences? They should be empty to use the shared user. Also I checked with Imgflip and requests to the API may be rate-limited if there is a lot of requests.
image

**Comment by pernielsentikaer** [comment]
Should be fixed now, you can see what I changed @timoransky 🔥

**Comment by timoransky** [comment]
@pernielsentikaer thanks for the fix! 👍

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
