### PR TITLE
Updating RescueTime with more commands to extend functionality

### PR DESCRIPTION
**Pull request by RobErskine**
## Description
Took some time while resting on the couch after the holiday to attempt to get more out of the tools I use every day, most notably Raycast and [RescueTime](https://www.rescuetime.com/). Instead of creating a net-new extension, I'm hoping to leverage the work that @tuortheblessed, has done, so the existing 170+ users can benefit from this update as well.

This PR takes the existing RescueTime extension and super-charges it to get way more out of the service. My favorite is the RescueTime today command, where you can see all of your stats at a glance. I pinned mine to my favorites so my Productivity Pulse is always top of mind.

Pinned RescueTime today command

- Added: RescueTime Today Command: Ability to see Pulse, Total Time, Productivity and Category breakdowns
- Added: FocusTime Feed Command: Adds in a List component to pull your latest Focus sessions feed
- Added: Alerts Feed Command: Adds in a List component to pull your latest Alerts/Goals from RescueTime
- Added: Daily Highlights Feed Command: Adds in a list component to pull yur latest Highlights from RescueTime
- Added: Log Highlight Command: Log a highlight directly from Raycast
- Added: Log Offline time Command: Log offline work time from Raycast
- Added: Default Offline Time preference
- Fixed: Introduced defaultFocusTime preference which was hardcoded before

## Screencast

Here is a video demo using all of the new features outlined above: https://share.roberskine.com/CgKY8rTK

Here are screenshots submitted in the extensions metadata as well

RescueTime Today
RescueTime today

RescueTime Alerts/Goals List
RescueTime Alerts and Goals

Logging Highlights
Log your own highlights

Log offline time
Log offline time

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
Build passing
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by RobErskine** [comment]
Sorry for all the linting and typescript fixes 😅. Please let me know if there is anything else I can update and I will jump right on it!

**Comment by tuortheblessed** [comment]
Looks great! Thanks for fleshing this out!

**Comment by pernielsentikaer** [comment]
Hi @RobErskine 👋 

Could you give my changes a quick spin that I didn't break something 🙂

**Comment by RobErskine** [comment]
Hi there @pernielsentikaer 👋🏼 Thanks for taking a look making the updates you did. The action labels and everything is more consistent now, which is great. I pulled them all down and the extension still works great.

However the Extensions/Check is failing again after updating `got` to `^13.0.0` (the extension still works tho). Moving down to `12` solves this issue, but don't know if that is the best solution?

>src/alertsFeed.tsx(4,17): error TS2307: Cannot find module 'got' or its corresponding type declarations.
src/dailyHighlights.tsx(4,17): error TS2307: Cannot find module 'got' or its corresponding type declarations.
src/endFocusTime.ts(2,17): error TS2307: Cannot find module 'got' or its corresponding type declarations.
src/focusTimeFeed.tsx(4,17): error TS2307: Cannot find module 'got' or its corresponding type declarations.
src/logDailyHighlight.tsx(4,17): error TS2307: Cannot find module 'got' or its corresponding type declarations.
src/logOfflineTime.tsx(4,17): error TS2307: Cannot find module 'got' or its corresponding type declarations.
src/rescueTimeToday.tsx(3,17): error TS2307: Cannot find module 'got' or its corresponding type declarations.
src/startFocusTime.ts(2,17): error TS2307: Cannot find module 'got' or its corresponding type declarations.
TypeScript check failed (exit status 2)
Error: TypeScript check failed (exit status 2)
Error: Process completed with exit code 1.

**Comment by pernielsentikaer** [comment]
Let's merge it and see how it goes 🔥 

Thanks once again for the update @RobErskine

**Comment by RobErskine** [comment]
@pernielsentikaer Awesome! I installed my local version, installed this from the store, dropped my key in, and all appears to be working flawlessly. Thanks for the help!

**Pull request merged**
