### PR TITLE
Added Solsearch extension

### PR DESCRIPTION
**Pull request by aquare11e**
## Description

Helps to search in one of available Solana explorers.
Verify that input (by keyboard or from clipboard) is transaction, address or block, and open in browser corresponding explorer (from preferences).

## Screencast
[Placed here](https://github.com/aquare11e/raycast-extensions/tree/solsearch/extensions/solsearch/media)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

How is this compared to the one we already have in [the store](https://www.raycast.com/darklong/solana-explorer)?

**Comment by aquare11e** [comment]
> Hi 👋
> 
> How is this compared to the one we already have in [the store](https://www.raycast.com/darklong/solana-explorer)?

Hello.

Thank you for the reply.

Yes, I saw this one, but my own allows to switch explorers, has better parsing for input, and has search history.

**Comment by pernielsentikaer** [comment]
Are you up for an enhancement of the current one if the author of the other one is ok with that?

**Comment by aquare11e** [comment]
> Are you up for an enhancement of the current one if the author of the other one is ok with that?

I will think about it, but probably author has abandoned his/her extension.
And also it takes double time for me. I already spend a week to develop, well-test, and prepare documentation for this one :)

**Comment by aquare11e** [comment]
So I had a free time to examine Solana Explorer solution.
Probably it is completely different extension and I will not able to merge my own with that one (in reasonable time).

It is up to you - if you will insist on it, I just close this merge request.

**Comment by pernielsentikaer** [comment]
There is also this in the queue which is older #3371 - maybe we can combine the best from the three?

**Pull request closed without merging**
