### PR TITLE
Update google gemini extension

### PR DESCRIPTION
**Pull request by ridemountainpig**
## Description
Add translate selected text command to any language for issue #13889.

## Screencast

https://github.com/user-attachments/assets/835322e4-8578-49d4-86ba-6879c498da62

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Looks like a good update @ridemountainpig, @EvanZhouDev can you check this?

**Comment by EvanZhouDev** [comment]
The feature itself looks good, I'm noticing that when loading, the "Response Finished" signs up multiple times, though? I cannot seem to replicate this on my side with prior commands. I don't see any issues with the code, but can you please try to reproduce?

**Comment by ridemountainpig** [comment]
Sorry for the late reply. 

I have tried to reproduce the issue, but it seems the "Response Finished" sign appears multiple times. I have also tried other commands, and this situation still occurs.

https://github.com/user-attachments/assets/cde8f5e1-4ef2-465c-bf96-02beb30ad11a


https://github.com/user-attachments/assets/7a32bdb7-f293-41b2-99f2-5d2b4c8e837e

**Comment by ridemountainpig** [comment]
> Is this something we need to address in this PR?

I think not.

**Comment by pernielsentikaer** [comment]
Let's continue and see what happens 🙂

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
