### PR TITLE
Add fetch-youtube-transcript extension

### PR DESCRIPTION
**Pull request by apoorv12**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Make the command `no-view` instead and add an argument for even faster usage


- I didn't change settings but I got this error, could you look into that? I would say it's a good idea if it works out of the box 🙂


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by apoorv12** [comment]
As per your request, I have implemented the following changes:
* **Mode:** Enabled the “no-view” mode and added an argument.
* **YouTube Link Addition:** Simplified the process of adding a YouTube link. Users can now simply paste the URL or share link.
* **Metadata Image Changes:** Adjusted the images in the metadata accordingly.
* **Default Transcript Download Folder:** Set the default download folder for transcripts to the “Downloads” folder.

**Comment by apoorv12** [comment]
I have made the changes but Unable to run `npm run publish`. It showing the following error:
failed running git Command failed: git merge-base --is-ancestor 5e1d306748bf4831fed7a107d4fe0427532fd0e7 f68536cdc99c7abdb885f2089f03d5f3209acea3 && echo "success"

**Comment by pernielsentikaer** [comment]
Did you get your fixes in?

**Comment by apoorv12** [comment]
Hi,
I have made update in package.json by adding contributors and version number. I haven’t found any error in fetch-youtube-transcript.tsx at my end still made changes related to Preferences.

**Comment by pernielsentikaer** [comment]
Anything you want me to add?

**Comment by apoorv12** [comment]
No Sir

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by apoorv12** [comment]
Sir,
Thank you so much for your kind words. I’ve just logged in to my Raycast account using my GitHub account. I’ve also added my GitHub ID to my Raycast profile. I hope it’s connected now.

My Raycast account email ID is: ***@***.***

Regards,
Apoorv Khandelwal

**Pull request merged**
