### PR TITLE
[GitHub] Various search usability improvements

### PR DESCRIPTION
**Pull request by peppy**
I have been using raycast as a primary means of searching github more recently, and made some improvements to improve productivity when doing so. I believe these can be useful to other users apart from me.

### Add "search discussions" command (92cad57f13a8a43226b74eee8bf9972f6e9cdd76)

This was one missing command. Until now we only had "My Discussions" which didn't allow searching globally.

https://github.com/raycast/extensions/assets/191335/83248ad4-7092-4a72-bdcd-dff95540224c

I'd probably also suggest renaming "Open issues" to "My issues" to match the other commands that are `author:@me` filtered.

### Add dropdown to choose target repositories when searching issues, PRs and discussions (e80bfd5e01842094f5e5da0b6c79634db9a365c8)

There was already a dropdown component allowing to choose <global|user|org> scope when searching repositories. I have added this dropdown to issue, pull request and discussion search commands.

https://github.com/raycast/extensions/assets/191335/7b54f5cf-19d2-4176-8fb0-87b2061c9a55

### Add customisation of result count (8668c35e48aa64bed9e019143607ba903616d607)

The default result count was 50, which can be quite low (server-side). I've been using 6-10 for my own purposes, which provides magnitudes faster responses from github.

https://github.com/raycast/extensions/assets/191335/50c2d07e-7094-401e-bc15-cf9ee77b2486

Note the loading time difference in the video between 50 and 5 results.

### Add default search term text (b5f017db360756615b9320693ae32fde97254af3)

This is a bit of an advanced use case, but I generally have some default criteria which I want to be pre-populated in the search box. If I don't need them, removing is just one `opt`-`delete` away. This can, for instance, allow for a default sort to be added, or any other supported github search criteria.

https://github.com/raycast/extensions/assets/191335/6a250de7-fded-47d9-981e-6fc9e50702de

Closes https://github.com/raycast/extensions/issues/8052.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaslombart — COMMENTED** [review]
Could you take a look at the CI errors? Otherwise, looks good to me 🚀

**Comment by peppy** [comment]
Thanks for reviewing the changes.

> Error:   19:4  error  Invalid contributor "peppy". Error: Not found (RequestID: 69961326-6336-44d4-8e04-449a5e6f6077)

I'm not too sure about this one, am I not supposed to add myself here? 😅

**Comment by thomaslombart** [comment]
@peppy Is `peppy` your actual Raycast account? It seems not according to this page: https://www.raycast.com/peppy.

**Comment by peppy** [comment]
Aha, I guess it's `ppy` https://www.raycast.com/ppy, thanks!

**Comment by thomaslombart** [comment]
Merged, thanks for the contribution! 🔥

**Comment by peppy** [comment]
> @peppy : Can you see if for the workflows you can only see yours, not the cloned ones?

I'm not too clear what you mean, could you explain a bit more?

**Pull request merged**
