### PR TITLE
Add easy-ocr extension

### PR DESCRIPTION
**Pull request by Rafo1994**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I would recommend sticking with Tesseract. Adding Google Vision can be challenging for most Raycast users. Would you be disappointed if we removed it?

**Comment by Rafo1994** [comment]
Not at all, that was just my idea of adding multiple options for users. Do you want me to refactor it and add commit when done?

**Comment by pernielsentikaer** [comment]
If you don't mind I think that would be better 🔥

**Comment by pernielsentikaer** [comment]
Is this ready for another review?

**Comment by Rafo1994** [comment]
Yes it is, I removed Google cloud vision ocr option

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
