### PR TITLE
Add Fast Chat Extension

### PR DESCRIPTION
**Pull request by TimonPeng**
## Description

A Raycast extension enables faster chatting with a target phone number in IM apps like WhatsApp and Telegram, eliminating the need to add contacts beforehand.

## Screencast

https://github.com/raycast/extensions/assets/8691151/6732c49b-2efe-409a-8970-d6c4a8fc59a5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @TimonPeng 👋 

This feels a bit like [Texts extension](https://www.raycast.com/zavbala/texts) from @zavbala - correct me if wrong 🙂

**Comment by TimonPeng** [comment]
> Hi @TimonPeng 👋
> 
> This feels a bit like [Texts extension](https://www.raycast.com/zavbala/texts) from @zavbala - correct me if wrong 🙂

Hi @pernielsentikaer 👋

After experiencing the Texts extension, I believe my submitted extension differs from Texts in several aspects:

1. My extension directly calls based on bundle ID and URL scheme (Texts redirects to a browser first, whereas mine directly opens the corresponding app).
2. Texts do not preprocess or format input parameters for WhatsApp.
3. Texts supports Telegram via username, not phone number (in fact, using a username makes it convenient to converse directly in Telegram).
4. Browser-based calls only invoke apps that handle URL schemes. This means when multiple release versions are installed, additional steps may be needed to make it work.
5. My extension focuses solely on `conversations with phone numbers` and it can easily support multiple release versions through set preferences. Chatting with phone numbers in IM Apps usually requires adding contacts first, so this is where my extension optimizes the workflow.

Therefore, I believe the two extensions fundamentally perform different tasks, hence I cannot directly contribute to the Texts extension either.

**Comment by pernielsentikaer** [comment]
Thanks for the clarification, I'll give it another whirl 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
