### PR TITLE
New Extension: Search iMessages & find 2FA codes

### PR DESCRIPTION
**Pull request by BalliAsghar**
## Description

Find 2FA Codes In your recent IMessage

## Screencast
IMessages-Find-2FA-Codes - 2
IMessages-Find-2FA-Codes - 3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Should we look into getting this out @BalliAsghar

**Comment by BalliAsghar** [comment]
> Should we look into getting this out @BalliAsghar

@pernielsentikaer I tried merging #1847 into this single extension with this one, but it did not work properly, so I would say let's get this out on its own.

**Comment by BalliAsghar** [comment]
> Hi @BalliAsghar 👋
> 
> Thanks for waiting patiently, we recently released `@raycast/utils` here we added a [useSQL](https://developers.raycast.com/utilities/react-hooks/usesql) hook, could you try to use that in the extension?

I've incorporated the useSQL hook into the extension. I've also added new features:
1: open message in markdown preview
2: search messages
3: copy the 2FA code to the clipboard if available in the message

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Actually, we just merged [another extension doing this](https://www.raycast.com/yuercl/imessage-2fa) a dew days ago since you didn't reply back, do you think yours have some features which are not in the other one?

**Comment by BalliAsghar** [comment]
> Actually, we just merged [another extension doing this](https://www.raycast.com/yuercl/imessage-2fa) a dew days ago since you didn't reply back, do you think yours have some features which are not in the other one?

That extension is only good for finding 2fa code, but in my extension, you can view all messages, search messages, and copy 2fa code if found in the message

**Comment by pernielsentikaer** [comment]
With that extension, you can search messages and 2FA, so I think they are pretty much the same unless I'm missing something.

**Comment by BalliAsghar** [comment]
> With that extension, you can search messages and 2FA, so I think they are pretty much the same unless I'm missing something.

I looked again into the extension, you are right there is not much difference.

**Pull request closed without merging**
