### PR TITLE
feat: add buildspace-os extension

### PR DESCRIPTION
**Pull request by TheLDB**
## Description
Adds a new extension, `buildspace-os`, which is a lightweight, easily accessible version of the [buildspace os](https://buildspace.so/os)

## Screencast
Screenshot 2023-04-08 at 14 32 00

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by TheLDB** [comment]
heres an updated screenshot btw

Screenshot 2023-04-08 at 17 35 07

**Comment by CobreDev** [comment]
sheesh that's a pretty lit extension

**Comment by michaelburkhardt** [comment]
lgtm 🔥

**Comment by TheLDB** [comment]
ok so update for anyone reviewing:

- data now pulls from an api (also open sourced [here](https://github.com/TheLDB/buildspace-os-raycast-api)
- data is cached for 5 minutes so it doesnt make a million requests to my server
- its swag imo so you should merge

**Comment by TheLDB** [comment]
ok *now* i think im happy w/ where this is at lol

**Comment by TheLDB** [comment]
heres a full screen recording of the functionallity
https://user-images.githubusercontent.com/29960599/230760247-b7f7f4d8-7b9c-4731-a75a-4d8e50ca1b18.mp4

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

I'm not really sure what this does, can you try to explain it to me - checked the `README` but it doesn't really say anything 😊

**Comment by TheLDB** [comment]
yeah for sure @pernielsentikaer 

I've gone ahead and updated the README w/ some more docs, so I'll send what I wrote there, in here:
# buildspace os for raycast

## what is buildspace?

[buildspace](https://buildspace.so) is a global home for builders, and the host of nights and weekends, a 6 week competition for builders to compete and grind, for a shot at $100,000

## what is this extension?

buildspace has a home/extension, found at [buildspace.so/home](https://buildspace.so/home), however if you don't use a supported browser for their extension, or just dont want to use your browser in general, this can be annoying to find.

this extension brings all of the cool features of buildspace os right into your menu bar

## how do you get events?

events are pulled from the [open source api](https://github.com/TheLDB/https://github.com/TheLDB/buildspace-os-raycast-api) i wrote, since events can change overnight, its important that the extension doesn't have to go through a long wait for review just to update a title or link

**Pull request closed without merging**
