### PR TITLE
Linear: Add due date action

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

- Add a new action to set due dates on issues
- Add due date accessory on issue list items

## Screencast

linear 2023-01-19 at 10 25 48

CleanShot 2023-01-19 at 10 33 57@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaspaulmann — APPROVED** [review]
Wonderful addition! Ship it. Just another idea while thinking about due dates, we could show overdue issues as part of the menu bar item as well. So it becomes more than just unread notifications.

**Comment by thomaslombart** [comment]
Indeed. That could be part of another section in the menu bar where you could see the related issues and maybe reschedule them 😊

**Comment by thomaslombart** [comment]
@thomaspaulmann

**Comment by jannesblobel** [comment]
Hej @thomaslombart ,
I have seen this PR, and it could be that you can help me. I am trying to create a new event for my own issues, which includes the data. 
CleanShot 2023-02-17 at 23 14 08@2x

In the settings, this field creates a new event, but I don't know if I can use your data function also in this field. 
CleanShot 2023-02-17 at 23 16 24@2x


I appreciate any help you can provide.  :)

**Comment by thomaspaulmann** [comment]
Hey @jannesblobel, this would be a wonderful addition. Unfortunately we can only do text as arguments right now. Therefore you couldn't do the date unless you fallback to some NLP text to date conversion but I'm not sure if that is convenient. We have plans to support different argument types, including dates. Unfortunately that will take a bit longer to implement/support.

**Pull request merged**
