### PR TITLE
Add base64-image-converter extension

### PR DESCRIPTION
**Pull request by VitorLostada**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mil3na — COMMENTED** [review]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

We already have a Base64 encoder/decoder. Do you think it would make sense to add your extension as a command for this? https://www.raycast.com/DanielSinclair/base64
And if not that one, maybe the `SVG64 - Convert SVGs to Base64 Strings`  https://www.raycast.com/EvanZhouDev/raycast-svg64

What do you think?

**Comment by vitorLostadaC** [comment]
> Hi! Thank you for your contribution! My name is Milena and I will be reviewing it today.
> 
> We already have a Base64 encoder/decoder. Do you think it would make sense to add your extension as a command for this? https://www.raycast.com/DanielSinclair/base64 And if not that one, maybe the `SVG64 - Convert SVGs to Base64 Strings` https://www.raycast.com/EvanZhouDev/raycast-svg64
> 
> What do you think?

I can add here https://www.raycast.com/DanielSinclair/base64; it's better to keep all tools on the same package. Other question, I can change the current UI of base64 to be more similar with my extension. 

I was thinking of separating the current extension behavior into two commands: one for decoding and another for encoding. I believe this could improve the UX. What do you think?

**Comment by mil3na** [comment]
I'd say go for it! And we can discuss further the changes when you submit another PR. And then we can get the opinion of the author as well :)

**Comment by vitorLostadaC** [comment]
Apologies for the absence; I had a lot of work to catch up on. However, I’m now ready to continue working on the extension. I spoke with the team on the other PR, and I believe it would be better to create a separate extension specifically for images. Could you please reopen this PR so we can proceed with publishing the extension?

What do you think

**Comment by mil3na** [comment]
Who you talked to? Do you mind sending me a link?

**Comment by mil3na** [comment]
@pernielsentikaer do you mind checking this?

**Comment by vitorLostadaC** [comment]
Hello @pernielsentikaer, would it be a good idea to reopen this PR so we don’t lose track of it? 😁

**Pull request closed without merging**
