### PR TITLE
Update cratecast extension

### PR DESCRIPTION
**Pull request by BalliAsghar**
## Description

- Updated the @raycast/api to the latest version.
- Removed deprecated @raycast/api methods to ensure a clean and up-to-date codebase.
- Rewrote the index.tsx file to use the latest @raycast/api methods, improving performance and code readability.
- Changed the command name from "crates.io Search" to "Search crates".
- Added descriptions and icons to the list of crates, providing additional context and visual cues for improved crate identification.
- Improved the formatting of downloads, making them more readable.
- Added Sceenshot

## Screencast
Metadata

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you mind checking this @gleich

**Comment by gleich** [comment]
looked over the code and looks good to me! also ran ti locally and it seems like all the core features are still working. as long as this is inline with the new API standards, it looks good to me!

**Comment by BalliAsghar** [comment]
@pernielsentikaer please approve!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
