### PR TITLE
Add Bing Wallpaper extension

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

Get and set Bing wallpapers within 15 days.

**Commands**

- **Bing Wallpaper**: Get and set Bing wallpapers within 15 days

**Actions**

- Set Desktop Wallpaper(↩︎): Set the current picture as desktop wallpaper
- Download Picture(⌘↩︎): Download Bing Pictures, directory is `/Users/xxxx/Downloads`
- Set Random Wallpaper(⌘R): Set random picture as desktop wallpaper
- Search Picture(⇧⌘S): Search current picture with bing
- Clear Wallpaper Cache(⇧⌘⌫): Clear picture cache created when the “**Set Desktop Wallpaper**” action is used

**Preferences**

- *Apply Wallpaper To*
  - Current Desktop
  - Every Desktop
- *Download Size*
  - Original: Raw
  - Full: 4K (3840×2160)
  - Regular: 2K (2560x1440)
  - Small: 1K (1920x1080)

## Screencast

https://user-images.githubusercontent.com/36128970/161362961-d9bc91ee-0f3b-428e-bb1c-55d304a02ba5.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @koinzhang 👋 

I have some feedback for you on this extension:

- I have selected `Apply Wallpaper To Every Desktop`, however, it looks like it's only changed in the first one? 

CleanShot 2022-04-20 at 14 06 18@2x

- It feels a bit weird that there is no default value in "downloadDirectory" in the preferences now that it's mandatory, even the code says it should be possible to leave blank `isEmpty(directoryPreference)`

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by koinzhang** [comment]
Hi @pernielsentikaer 👋. Thank for your review.I will attach the latest changes below.

> * I have selected `Apply Wallpaper To Every Desktop`, however, it looks like it's only changed in the first one?

1.This option is somewhat ambiguous. It applies to desktops in an extended monitor, not to other desktops in a monitor. 
So I changed the text and added the hint: "Valid only when you are using an extended monitor."

> * It feels a bit weird that there is no default value in "downloadDirectory" in the preferences now that it's mandatory, even the code says it should be possible to leave blank `isEmpty(directoryPreference)` 

2.Here I want the user to fill in the Download Directory when entering the extension, so that when the user checks the Auto Download, it doesn't download to an unexpected directory.
Latest changes: Added placeholder and default values to guide users.

**Comment by pernielsentikaer** [comment]
Hi @koinzhang 👋 

Thanks for the corrections 🔥 

One thing I don't get is the one with the `Download Directory, in the first test I just wrote `Downloads` and nothing more.

What about setting the default to ~/Downloads and use a library like [expand-tilde](https://www.npmjs.com/package/expand-tilde) to resolve the right path?

**Comment by koinzhang** [comment]
Hi @pernielsentikaer 👋. Thank for your review.I attach the latest changes below.

- Update the default download path to `~/Downloads`
- The download directory supports the form `/Users/Username/Downloads` and `~/Downloads`. However, it is not supported to enter only `Downloads`.

**Review by pernielsentikaer — APPROVED** [review]
Hi @koinzhang 👋 

Thanks for the latest update!

**Pull request merged**
