### PR TITLE
Add git-buddy extension

### PR DESCRIPTION
**Pull request by gianfrancopiana**
## Description

Hey Raycast team! This is my first extension submission, and I'm happy to share Git Buddy with you all.

Git Buddy is an opinionated, AI-powered Git assistant designed to simplify your Git workflow. It uses Raycast AI to help with common tasks like writing commit messages, creating PR descriptions, and managing branches.

### Commands

1. **AI-Powered Commit Messages**: Generate concise and clear commit messages for your current branch using AI.

2. **AI-Assisted PR Descriptions**: Create detailed pull request descriptions for your current branch with the help of AI.

3. **Branch Management**:
   - List all branches (local and remote) in your repository
   - Easily checkout to a selected branch
   - Generate PR descriptions for any selected branch
   - Quick copy of branch names to clipboard
   - Prune and delete untracked branches

4. **Configurable**: Set your repository path, target branch, and preferred AI model for content generation.

### Why Git Buddy?

I built this for myself and have been using it daily for while now. But I think it's time to make it available for everyone. Looking forward to your feedback!

## Screencast

https://github.com/raycast/extensions/assets/52470719/ad30dfc2-9e05-438c-b569-58107b7fe049

https://github.com/raycast/extensions/assets/52470719/ab04eba2-bbbb-45f9-bf11-a36fc1f257d4

git-buddy-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

There is already an extension similar to this [in the queue](https://github.com/raycast/extensions/pull/12983). Could it make sense to join forces to create one?

**Comment by gianfrancopiana** [comment]
> Hi 👋
> 
> Thanks for your contribution 🔥
> 
> There is already an extension similar to this [in the queue](https://github.com/raycast/extensions/pull/12983). Could it make sense to join forces to create one?

Thanks for the feedback and collaboration offer! I appreciate the thoughtfulness.

While the extensions might look similar at first glance, Git Buddy offers some unique features:

- Multi-repo support: Unlike the other extension, Git Buddy isn't limited to a single directory, offering flexibility that I'm sure many developers would need
- AI-powered commit messages and PR descriptions
- Streamlined branch management

I've put a lot of thought into keeping Git Buddy efficient and focused. Adding commit viewing would be a big change that could weaken its main purpose. Users might want this feature (and I'm open to feedback), but if I add it, I'd do it very differently from the other extension.

I'd love for the Raycast community to try Git Buddy and share their thoughts. User feedback is crucial for future improvements.

Please let me know if you have any questions. I'm always open to suggestions and discussion. 

Thanks for considering!

**Comment by mil3na** [comment]
Hi! 

The extension mentioned by Per was not merged yet, but have you taken a look at it? I understand that you put a lot of effort on your extension but the other was submitted first and seems like you both have the same goal. I believe you guys can work together to make this extension one and great. What do you think?

**Comment by gianfrancopiana** [comment]
> Hi!
> 
> The extension mentioned by Per was not merged yet, but have you taken a look at it? I understand that you put a lot of effort on your extension but the other was submitted first and seems like you both have the same goal. I believe you guys can work together to make this extension one and great. What do you think?

Hi Milena!

I appreciate your suggestion, and I have indeed looked at the code of the other extension. But I believe keeping these projects separate is best. Here's why:

1. My extension works with any repo, anywhere on your computer. No folder constraints.
2. It goes beyond commit listing, offering AI-powered features and streamlined management. There's virtually no overlap in functionality.
3. It's an opinionated project with a specific vision for enhancing Git workflows.

While both are Git-related, they serve different purposes. I think diversity in the Raycast ecosystem can benefit users with different needs.

If users express interest in commit listing, it would be a minor addition to this more feature-rich extension. Combining projects over a single, small feature doesn't seem beneficial, especially given the substantial differences in our approaches.

As the sole maintainer, I would be super committed to this project and could ensure quick iterations and consistent vision. This focus would allow me to be highly responsive to user feedback once published. Any specific features you think could enhance it further?

**Comment by mil3na** [comment]
@pernielsentikaer what do you think?

**Comment by pernielsentikaer** [comment]
If the other one is closed, I think we can proceed with this one. Maybe even adding some of the features from the other one could be an idea?

**Comment by pernielsentikaer** [comment]
What do you think of this one, @koinzhang? I remember you tested the other PR in the queue with the same name 🙂

**Comment by koinzhang** [comment]
I don't have Raycast AI and some of these commands can't be tested, so I can't make an evaluation

**Comment by gianfrancopiana** [comment]
@pernielsentikaer @koinzhang Please let me know if there's any way I can help.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Is there a way to show an error if something went wrong? I had a `modified` file that prevented it from switching, but the success toast was still present

- Maybe we should add the path in a `<List.Section />` so the user can see which path it's using

git-buddy 2024-08-12 at 15 19 37

- Shouldn't `Write PR Description` use the same branch as selected in `List Branches`, `Write Commit Message` didn't ask me about branch

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by gianfrancopiana** [comment]
Hey @pernielsentikaer, really appreciate your feedback. These are great suggestions.

- I've improved error handling to show errors in your scenario. Also took this an opportunity to make the code more modular and maintainable.

- Now all commands have a `Repository` label. I ended up using the folder name instead of the full path. I found it was more readable:
image
image
image

- `Write PR Description` compares the diff to the default **base** branch - which I've renamed for clarity:
Raycast 2024-08-15 at 22 41 07
You can write a PR using a different base branch by going into `List Branches`, choosing the base branch from the list, and selecting `Write PR Description → This Branch`:
image

Please let me know if this last point makes sense.

Thanks!

**Comment by pernielsentikaer** [comment]
Let's get the first version live to see how it goes 🙂

**Pull request merged**
