### PR TITLE
New extension: replicate.com

### PR DESCRIPTION
**Pull request by KevinBatdorf**
## Description

This adds a block to interact with the [replicate.com api](https://replicate.com/docs/reference/http). It only adds viewing and searching your own collections, and does not cover submitting prompts, etc. There's room to add those features later, but I feel like this isn't the best tool for that as prompts are somewhat dynamic.

## Screencast

https://twitter.com/kevinbatdorf/status/1571314960944271360

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @KevinBatdorf 

Thanks for your contribution 🔥 

After inserting the key I just get this screen (didn't have the time to search for anything) 

image

Could you look into this issue?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by KevinBatdorf** [comment]
Thanks @pernielsentikaer - I've added a view for when the account has no predictions. I think this change solves it now. Ready for a check when you are!

**Comment by pernielsentikaer** [comment]
Hi @KevinBatdorf 👋 

I gave it another spin; first problem solved 👏 but now I don't get any predictions after running them 🫤

CleanShot 2022-09-21 at 07 19 22@2x

**Comment by KevinBatdorf** [comment]
Looks like that model returns a string whereas the others send arrays. Thanks for trying that one! I've updated it to support both now.

Ready to check again when you have time thanks

**Pull request merged**
