### PR TITLE
[Bitwarden] Vault caching

### PR DESCRIPTION
**Pull request by jomifepe**
## Description

Issue #4351

This implementation is inspired by [Alfred's bitwarden workflow](https://github.com/blacs30/bitwarden-alfred-workflow), and you can see some of the caching code [here](https://github.com/blacs30/bitwarden-alfred-workflow/blob/master/src/cache.go).

### What was done
- [X] Implemented caching mechanism (explained below on `How does it work?`)
- [X] Adapted every action (e.g. copy password) to work with caching
- [X] Added new preference option to toggle Search Vault caching on/off (screenshot below)
- [X] Implemented unit tests for the most important caching & encryption code

### How does it work?

1. The vault is loaded from CLI.
2. Items are cleared of any secrets, replacing them with a placeholder value.
3. Once cleared, the items are encrypted, for an extra layer of security:
   i. The `client_secret` is used as the cipher key, that way it's unique to the user.
   ii. The `aes-256-cbc` algorithm is used.
5. The items are saved to the cache (locally) using [Raycast's Cache API](https://developers.raycast.com/api-reference/cache).
6. When the user launches the Search Vault command again, the items are retrieved from the cache, decrypted, and presented to the user still with the placeholder values. These placeholder values are not visible because they are accessed via actions such as copying a password.
7. When the user tries to access a value that may be a placeholder (e.g. copying a password), one of two thing can happen depending on the timing:
   i. The value is not a placeholder anymore because the user took time to perform the action, and in the meantime, the real values were loaded in the background, and the list was completely replaced.
   ii. The value is a placeholder, and once the user performs the action, a loading toast is displayed, and it will wait until the real values are loaded in the background to retrieve the value.

### Is this safe?
Yes, secrets are never cached, vault items are cleared of any password, secret notes, and other sensitive values, before being cached. As mentioned above, the already clean cache is also encrypted.

<details>
<summary>1. Login</summary>
<br/>
<table>
<tr>
<td>
Before (with sensitive data)
</td>
<td>
After
</td>
</tr>
<tr>
<td>
<pre lang="json">
{
  "collectionIds": [
    "b527c993-2936-45bc-8d30-afe8016cb3d7"
  ],
  "creationDate": "2023-03-02T23:55:38.490Z",
  "deletedDate": null,
  "favorite": false,
  "fields": [
    {
      "linkedId": null,
      "name": "Test Hidden Field",
      "type": 1,
      "value": "test"
    },
    {
      "linkedId": null,
      "name": "Test Test Field",
      "type": 0,
      "value": "test"
    },
    {
      "linkedId": null,
      "name": "Test Boolean Field",
      "type": 2,
      "value": "true"
    },
    {
      "linkedId": 100,
      "name": "Test Linked Field",
      "type": 3,
      "value": null
    }
  ],
  "folderId": "aae05628-f822-4537-a996-afe8016cf794",
  "id": "cfdd15d7-9f25-41c1-b216-afb9018a4f97",
  "login": {
    "password": "mypassword123",
    "passwordRevisionDate": "2023-04-07T01:08:33.510Z",
    "totp": null,
    "uris": [
      {
        "match": 1,
        "uri": "http://amazon.com/"
      }
    ],
    "username": "test@amazon.com"
  },
  "name": "Amazon",
  "notes": "These are notes",
  "object": "item",
  "organizationId": "1a148ca5-7b5f-44eb-af1f-afe8016cb3d1",
  "passwordHistory": [
    {
      "lastUsedDate": "2023-04-07T01:08:33.510Z",
      "password": "test"
    }
  ],
  "reprompt": 0,
  "revisionDate": "2023-04-18T22:09:08.006Z",
  "type": 1
}
</pre>
</td>
<td>
<pre lang="json">
{
  "collectionIds": [
    "b527c993-2936-45bc-8d30-afe8016cb3d7"
  ],
  "creationDate": "2023-03-02T23:55:38.490Z",
  "deletedDate": null,
  "favorite": false,
  "fields": [
    {
      "linkedId": null,
      "name": "Test Hidden Field",
      "type": 1,
      "value": "HIDDEN-VALUE"
    },
    {
      "linkedId": null,
      "name": "Test Test Field",
      "type": 0,
      "value": "HIDDEN-VALUE"
    },
    {
      "linkedId": null,
      "name": "Test Boolean Field",
      "type": 2,
      "value": "HIDDEN-VALUE"
    },
    {
      "linkedId": 100,
      "name": "Test Linked Field",
      "type": 3,
      "value": "HIDDEN-VALUE"
    }
  ],
  "folderId": "aae05628-f822-4537-a996-afe8016cf794",
  "id": "cfdd15d7-9f25-41c1-b216-afb9018a4f97",
  "login": {
    "password": "HIDDEN-VALUE",
    "passwordRevisionDate": "HIDDEN-VALUE",
    "totp": "HIDDEN-VALUE",
    "uris": [
      {
        "match": 1,
        "uri": "http://amazon.com/"
      }
    ],
    "username": "test@amazon.com"
  },
  "name": "Amazon",
  "notes": "HIDDEN-VALUE",
  "object": "item",
  "organizationId": "1a148ca5-7b5f-44eb-af1f-afe8016cb3d1",
  "passwordHistory": [
    {
      "lastUsedDate": "HIDDEN-VALUE",
      "password": "HIDDEN-VALUE"
    }
  ],
  "reprompt": 0,
  "revisionDate": "2023-04-18T22:09:08.006Z",
  "type": 1
}
</pre>
</td>
</tr>
</table>
</details>

<details>
<summary>2. Card</summary>
<br/>
<table>
<tr>
<td>
Before (with sensitive data)
</td>
<td>
After
</td>
</tr>
<tr>
<td>
<pre lang="json">
{
  "card": {
    "brand": "Visa",
    "cardholderName": "This is my name",
    "code": "444",
    "expMonth": "12",
    "expYear": "2050",
    "number": "4188190023452726"
  },
  "collectionIds": [
    "b527c993-2936-45bc-8d30-afe8016cb3d7"
  ],
  "creationDate": "2023-03-02T23:56:15.453Z",
  "deletedDate": null,
  "favorite": false,
  "folderId": null,
  "id": "bdf2836c-867b-4ceb-ae41-afb9018a7ae5",
  "name": "My Credit Card",
  "notes": "These are notes",
  "object": "item",
  "organizationId": "1a148ca5-7b5f-44eb-af1f-afe8016cb3d1",
  "reprompt": 0,
  "revisionDate": "2023-04-18T22:08:31.380Z",
  "type": 3
}
</pre>
</td>
<td>
<pre lang="json">
{
  "card": {
    "brand": "HIDDEN-VALUE",
    "cardholderName": "HIDDEN-VALUE",
    "code": "HIDDEN-VALUE",
    "expMonth": "HIDDEN-VALUE",
    "expYear": "HIDDEN-VALUE",
    "number": "HIDDEN-VALUE"
  },
  "collectionIds": [
    "b527c993-2936-45bc-8d30-afe8016cb3d7"
  ],
  "creationDate": "2023-03-02T23:56:15.453Z",
  "deletedDate": null,
  "favorite": false,
  "folderId": null,
  "id": "bdf2836c-867b-4ceb-ae41-afb9018a7ae5",
  "name": "My Credit Card",
  "notes": "HIDDEN-VALUE",
  "object": "item",
  "organizationId": "1a148ca5-7b5f-44eb-af1f-afe8016cb3d1",
  "reprompt": 0,
  "revisionDate": "2023-04-18T22:08:31.380Z",
  "type": 3
}
</pre>
</td>
</tr>
</table>
</details>

<details>
<summary>3. Identity</summary>
<br/>
<table>
<tr>
<td>
Before (with sensitive data)
</td>
<td>
After
</td>
</tr>
<tr>
<td>
<pre lang="json">
{
  "collectionIds": [
    "b527c993-2936-45bc-8d30-afe8016cb3d7"
  ],
  "creationDate": "2023-03-02T23:57:47.986Z",
  "deletedDate": null,
  "favorite": false,
  "folderId": "aae05628-f822-4537-a996-afe8016cf794",
  "id": "377fa415-9ee6-45a3-bab8-afb9018ae758",
  "identity": {
    "address1": "My Address",
    "address2": "Test Street",
    "address3": "N14",
    "city": "My Town",
    "company": "Test",
    "country": "Nigeria",
    "email": "test@email.com",
    "firstName": "This",
    "lastName": "Name",
    "licenseNumber": "192918381",
    "middleName": "My",
    "passportNumber": "182929813919",
    "phone": "918882918",
    "postalCode": "19202912",
    "ssn": "24523419",
    "state": "My County",
    "title": "Mr",
    "username": "thismyname"
  },
  "name": "Home Address",
  "notes": "These are notes",
  "object": "item",
  "organizationId": "1a148ca5-7b5f-44eb-af1f-afe8016cb3d1",
  "reprompt": 0,
  "revisionDate": "2023-04-18T22:09:22.110Z",
  "type": 4
}
</pre>
</td>
<td>
<pre lang="json">
{
  "collectionIds": [
    "b527c993-2936-45bc-8d30-afe8016cb3d7"
  ],
  "creationDate": "2023-03-02T23:57:47.986Z",
  "deletedDate": null,
  "favorite": false,
  "folderId": "aae05628-f822-4537-a996-afe8016cf794",
  "id": "377fa415-9ee6-45a3-bab8-afb9018ae758",
  "identity": {
    "address1": "HIDDEN-VALUE",
    "address2": "HIDDEN-VALUE",
    "address3": "HIDDEN-VALUE",
    "city": "HIDDEN-VALUE",
    "company": "HIDDEN-VALUE",
    "country": "HIDDEN-VALUE",
    "email": "HIDDEN-VALUE",
    "firstName": "HIDDEN-VALUE",
    "lastName": "HIDDEN-VALUE",
    "licenseNumber": "HIDDEN-VALUE",
    "middleName": "HIDDEN-VALUE",
    "passportNumber": "HIDDEN-VALUE",
    "phone": "HIDDEN-VALUE",
    "postalCode": "HIDDEN-VALUE",
    "ssn": "HIDDEN-VALUE",
    "state": "HIDDEN-VALUE",
    "title": "HIDDEN-VALUE",
    "username": "HIDDEN-VALUE"
  },
  "name": "Home Address",
  "notes": "HIDDEN-VALUE",
  "object": "item",
  "organizationId": "1a148ca5-7b5f-44eb-af1f-afe8016cb3d1",
  "reprompt": 0,
  "revisionDate": "2023-04-18T22:09:22.110Z",
  "type": 4
}
</pre>
</td>
</tr>
</table>
</details>

<details>
<summary>4. Secure Note</summary>
<br/>
<table>
<tr>
<td>
Before (with sensitive data)
</td>
<td>
After
</td>
</tr>
<tr>
<td>
<pre lang="json">
{
  "collectionIds": [
    "b527c993-2936-45bc-8d30-afe8016cb3d7"
  ],
  "creationDate": "2023-04-07T01:06:36.280Z",
  "deletedDate": null,
  "favorite": false,
  "folderId": "aae05628-f822-4537-a996-afe8016cf794",
  "id": "f560a80f-a9a1-4433-95a1-afdd00124b51",
  "name": "My Secret Note",
  "notes": "This is very secret asdasd",
  "object": "item",
  "organizationId": "1a148ca5-7b5f-44eb-af1f-afe8016cb3d1",
  "reprompt": 0,
  "revisionDate": "2023-04-18T22:09:27.793Z",
  "secureNote": {
    "type": 0
  },
  "type": 2
}
</pre>
</td>
<td>
<pre lang="json">
{
  "collectionIds": [
    "b527c993-2936-45bc-8d30-afe8016cb3d7"
  ],
  "creationDate": "2023-04-07T01:06:36.280Z",
  "deletedDate": null,
  "favorite": false,
  "folderId": "aae05628-f822-4537-a996-afe8016cf794",
  "id": "f560a80f-a9a1-4433-95a1-afdd00124b51",
  "name": "My Secret Note",
  "notes": "HIDDEN-VALUE",
  "object": "item",
  "organizationId": "1a148ca5-7b5f-44eb-af1f-afe8016cb3d1",
  "reprompt": 0,
  "revisionDate": "2023-04-18T22:09:27.793Z",
  "secureNote": {
    "type": 0
  },
  "type": 2
}
</pre>
</td>
</tr>
</table>
</details>

### Performance improvement demonstration

| 🐌  Without caching | 🏎️  With Caching |
| ---- | ---- |
|  <video src="https://user-images.githubusercontent.com/7235666/230514581-e8079327-ae8e-456b-8454-d4bff4b723a9.mp4"> | <video src="https://user-images.githubusercontent.com/7235666/230514702-ab2ec591-731c-40ea-9afa-12abc0986c69.mp4"> |

### New preference option

Screenshot 2023-04-24 at 18 09 00

### Small update to the unlock screen
Now you're informed of your timeout setting and where to change it

Screenshot 2023-04-07 at 00 13 35

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by bxb100** [comment]
Hi, @jomifepe, Thanks for your hard work

I'm just curious when the cache can refresh, have a button to deal, or fixed interval time to evict?

**Comment by jomifepe** [comment]
> Hi, @jomifepe, Thanks for your hard work
> 
> I'm just curious when the cache can refresh, have a button to deal, or fixed interval time to evict?

Hey, the cache is updated every time you open the vault, it's just used to eliminate the delay between opening the command and waiting for the items to load, so I won't really have much of a chance to get stale. If you wish to "make sure" your vault is updated, using the `Sync Vault` action will do it.

**Comment by bxb100** [comment]
Oh, I see, Thanks

**Comment by jomifepe** [comment]
@daniel-stoneuk @pomdtr @andreaselia @eth-p 

Do you mind taking a look at this one? 🙏

**Comment by pernielsentikaer** [comment]
Seems to be working all fine for me 👍  (but would also love to have other to test it out)

**Comment by bxb100** [comment]
@jomifepe When I input the wrong password it displays this:

image

```log
Error: Command failed with exit code 1: /opt/homebrew/bin/bw unlock dsds --raw
Invalid master password.

makeError:error.js:59:10

---
56: 		error.originalMessage = error.message;
57: 		error.message = message;
58: 	} else {
59: 		error = new Error(message);
60: 	}
61:
62: 	error.shortMessage = shortMessage;
---

handlePromise:search.js:1847:29
```

**Comment by pernielsentikaer** [comment]
Nice catch 🔥

**Comment by pernielsentikaer** [comment]
Anyone else wanna test before merging and are we ready @jomifepe

**Comment by jomifepe** [comment]
> Anyone else wanna test before merging and are we ready @jomifepe

I’m fine with merging it since multiple people have already tested it 🙂

**Comment by pernielsentikaer** [comment]
Could you maybe have a check @pomdtr 😊

**Comment by jomifepe** [comment]
Here's a video manually testing most features of the Search Vault command

https://user-images.githubusercontent.com/7235666/235540878-a1d7c06f-655a-4956-a7f3-31907f81de16.mp4

**Comment by pernielsentikaer** [comment]
Thanks for the video, that's a serious test 🔥 

I think we should merge it, agree @jomifepe ?

**Comment by jomifepe** [comment]
> Thanks for the video, that's a serious test 🔥 
> 
> I think we should merge it, agree @jomifepe ?

Sounds good to me!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by brandom** [comment]
I'm not sure if this is connected to this PR, but yesterday I started having an issue where the vault would lock right after unlocking. I solved it by uninstalling and reinstalling the extension.

**Pull request merged**
