### PR TITLE
[iTerm] Update iterm extension (Added python API support)

### PR DESCRIPTION
**Pull request by flops**
## Description
Added Python API support:
https://github.com/raycast/extensions/issues/10300

Added commands with profiles selection:
https://github.com/raycast/extensions/issues/9491

- New iTerm Window (Profile)
- New iTerm Tab (Profile)
- Split iTerm Horizontally (Profile)
- Split iTerm Vertically (Profile)
- Edit in iTerm (Profile)
- Open iTerm Here (Profile)

Fixed environment variables leaking  bug
https://github.com/raycast/extensions/issues/10078 

Total extension rewrite
Added better idle screens and error screens.

## Screencast

https://github.com/raycast/extensions/assets/433333/ce355379-c834-4f78-8f54-e5ef8901b447

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for the update 🔥 

@ron-myers do you want to check this?

**Comment by flops** [comment]
Hi
@pernielsentikaer is there any movement with this PR?

**Comment by pernielsentikaer** [comment]
There is, I spoke with @ron-myers that will check it 🙂

**Comment by pernielsentikaer** [comment]
Pinged @ron-myers again 🙂

**Comment by pernielsentikaer** [comment]
@ron-myers I could use some help testing this

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
@flops can you help me resolve the conflicts so we can merge it 🙂

**Comment by flops** [comment]
Sure, I'll try to merge updates today.

**Comment by grzegorzkrukowski** [comment]
There are some conflicts in this branch @pernielsentikaer

**Comment by pernielsentikaer** [comment]
Can you fix the issues @flops

**Pull request closed without merging**
