### PR TITLE
update: go-package-search

### PR DESCRIPTION
**Pull request by k8scat**
## Description

- Upgrade @raycast/api to 1.40.1
- Support Copy Package Path and Download Command
- Fix List.Item with the same key
- Update List.Item Accessories

## Screencast

go-package-search 2022-10-01 at 09 46 30

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by bstncartwright — APPROVED** [review]
Thanks so much for fixing this up and adding this new functionality @k8scat ! Great work, you rock!

**Comment by pernielsentikaer** [comment]
Would it make sense to add `https://` to `Copy Package Path` - just asking because I don't know the purpose 😊

**Comment by k8scat** [comment]
image

Package path does not have the protocol prefix, for example, https://pkg.go.dev/github.com/fsouza/go-dockerclient

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Makes sense, thanks for clarifying 😊

Looks good to me, approved 🔥

**Pull request merged**
