### PR TITLE
Add iconia extension

### PR DESCRIPTION
**Pull request by eevaery**
## Description

It is an extension that gives iconify a search icon that can boost productivity for developers and designers on the platform accordingly!

## Screencast

iconia-1
iconia-2
iconia-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

Thanks for your contribution, how is this compared with [this extension](https://www.raycast.com/destiner/iconify) by @Destiner

**Comment by yveeven** [comment]
> Hi 👋
> 
> Thanks for your contribution, how is this compared with [this extension](https://www.raycast.com/destiner/iconify) by @Destiner



> Hi 👋
> 
> Thanks for your contribution, how is this compared with [this extension](https://www.raycast.com/destiner/iconify) by @Destiner

More advantages:
1. display in Grid, more visible content, more reasonable.
2. Not sure about the data source of Iconify, but its response speed is not ideal, while this extension is based on the official API, with stable and fast response.
3. category is also completely based on Iconify, more convenient
4. have more in line with the needs of the use of rich Actions, the default [Open Icones, Open Iconify], selected Icon [Copy Icon String, Copy SVG, Copy URL, Open Icon in Icones].
5. Have dynamically updated totals, based on search results, category, all
6. more reasonable visual effects in general
7. We will consider to add the ability of AI to generate Icon.

I think it will be the first choice for people who need to search for icons.

**Comment by yveeven** [comment]
> > Hi 👋
> > Thanks for your contribution, how is this compared with [this extension](https://www.raycast.com/destiner/iconify) by @Destiner
> 
> More advantages:
> 
> 1. display in Grid, more visible content, more reasonable.
> 2. not sure the data source of the extension being compared, but its response speed is very unsatisfactory, while this extension is based on the official API, has a stable and fast response
> 3. category is also completely based on Iconify, more convenient
> 4. have more in line with the needs of the use of rich Actions, the default [Open Icones, Open Iconify], selected Icon [Copy Icon String, Copy SVG, Copy URL, Open Icon in Icones].
> 5. Have dynamically updated totals, based on search results, category, all
> 6. more reasonable visual effects in general
> 7. will consider to add the ability of AI to generate Icon.
> 8. Possibly consider local or cloud-based personal icon storage based on Raycast storage capabilities
> 
> I think it will be the first choice for people who need to search for icons.

**Comment by pernielsentikaer** [comment]
Are you still around @Destiner?

**Comment by yveeven** [comment]
> Are you still around @Destiner?

I noticed that the latest update to iconify was 7 months ago, and the author's update to it was 1 year ago!

**Comment by yveeven** [comment]
Are you still around @pernielsentikaer

**Comment by pernielsentikaer** [comment]
I am, still trying to get in touch with @Destiner 🙂

**Comment by yveeven** [comment]
@pernielsentikaer hello, Is there any further news as it is about to become obsolete

**Comment by yveeven** [comment]
not out of date

**Comment by yveeven** [comment]
hello?

**Comment by pernielsentikaer** [comment]
Sorry for the long response time, we have been on Christmas and New Year vacation and we're ready to dive in again 🙂

We have discussed this internally and since it uses the same library it would make sense to let this supersede the old one - what you have to do it to move the extension on top of the other so it "updates" the other one - does that make sense?

You might need to keep the original name in package.json but the rest should be fine

Let me know if you want us to help with that 🙂

**Comment by yveeven** [comment]
> Sorry for the long response time, we have been on Christmas and New Year vacation and we're ready to dive in again 🙂
> 
> We have discussed this internally and since it uses the same library it would make sense to let this supersede the old one - what you have to do it to move the extension on top of the other so it "updates" the other one - does that make sense?
> 
> You might need to keep the original name in package.json but the rest should be fine
> 
> Let me know if you want us to help with that 🙂

Understood, envious of your vacation and happy new year 🎉
I understand that you mean that I need to just use the name of the original extension, if so I will update it and resubmit it!

**Comment by pernielsentikaer** [comment]
Rebase this PR into the `iconify` folder instead and change the name of your extension to match the current 🙂

**Comment by yveeven** [comment]
I'm getting this error when trying to republish, can you help me, please?
CleanShot 2024-01-10 at 22 42 36@2x

**Comment by pernielsentikaer** [comment]
Are you on our [Slack community](http://raycast.com/community) - we have a channel called #extensions for help 🙂

**Comment by yveeven** [comment]
I have updated and re-posted it here https://github.com/raycast/extensions/pull/10316

**Pull request closed without merging**
