### PR TITLE
feat: update metadata images

### PR DESCRIPTION
**Pull request by Motion-Up**
## Description

# DropsTab Dropstab Crypto Toolbox

##### Get crypto coin data and navigate to official sites or X. Instantly view your wallets via blockchain explorers.

Bug Fixes:

Updated images located in the metadata folder to comply with Raycast documentation guidelines. All images have been organized and optimized for better performance and consistency.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

**Comment by Motion-Up** [comment]
> Could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

Done.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by Motion-Up** [comment]
@pernielsentikaer  I would like to link my profile on Raycast ([https://www.raycast.com/ignat_danilov](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)) to the Dropstab extension so that it is displayed on my profile. Could you please provide the steps or guidance on how to achieve this?

**Pull request merged**
