### PR TITLE
Add veganify extension

### PR DESCRIPTION
**Pull request by philipbrembeck**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Can we improve this? It feels cluttered that the search text in the `List.Item` is so behinf

**Comment by philipbrembeck** [comment]
@pernielsentikaer What exactly do you mean? 

I would love to improve the extension further and also I'm still on the screenshots etc., but currently don't have lots of time at hand.

**Comment by pernielsentikaer** [comment]
I think it would be better to remove the custom debounce and just use `throttle` directly on the `<List />` instead, could you try that?

**Comment by philipbrembeck** [comment]
@pernielsentikaer Yes, for sure, wild that today evening :)

**Comment by philipbrembeck** [comment]
@pernielsentikaer I had an issue with my git setup, maybe you can check my new PR: https://github.com/raycast/extensions/pull/14791

**Pull request closed without merging**
