### PR TITLE
Add masked-link-generator extension

### PR DESCRIPTION
**Pull request by Visual-Studio-Coder**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Visual-Studio-Coder** [comment]
Well it's kinda tedious for me to always type []() to make a masked link and I wanted to make this experience faster

**Comment by Visual-Studio-Coder** [comment]
I actually use it a lot now that I made it

**Comment by pernielsentikaer** [comment]
What's the difference, is it markdown? I tried it but can't see what it does 🙂

**Comment by Visual-Studio-Coder** [comment]
Its markdown

**Comment by Visual-Studio-Coder** [comment]
If you use it in discord, it defaults to not rendering the embed, which is also a good thing

**Comment by pernielsentikaer** [comment]
Where can I see the difference between [hello](<https://youtube.com>) and [hello](https://youtube.com) - here I don't see anything changed 🙂

**Comment by Visual-Studio-Coder** [comment]
In discord, I can prevent the embed from showing up by wrapping the url in <https://url.com>

**Pull request merged**
