### PR TITLE
[Update Obsidian Extension] Tag Filter, Markdown Controls for Edit Note, Templates for Append Action & More

### PR DESCRIPTION
**Pull request by marcjulianschwarz**
## Description

- Add tag filter to filter results in `Search Note` and `Pinned Notes` command by tags (YAML frontmatter and inline)
- Add `Random Note` command which opens a random note in Quick Look (all actions available)
- `Edit Note` action now supports markdown controls (e.g. `cmd + b` for bold and `cmd + i` for italic)
- `Append to Note` and `Append Selected Text to Note` actions now support all templates
- Add template preference for both `Append to Note` and `Append Selected Text to Note` actions
- Use `{content}` for `Append Selected Text to Note` action
- Add templates `{selected}`, `{selectedText}` for selected Text
- Add templates `{\n}`, `{newline}`, `{nl}` for new line
- Add shorter template `{clip}` for clipboard
- Add `Default Content` and `Fill Form with Default Values` settings for `Create Note` command
- Add `Show in Finder` action for all vault selection lists
- Minor fixes

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by marcjulianschwarz** [comment]
Wonder why it failed building. 

It built just fine on my local copy using `npm run build`.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪

With Random Note I get an empty list
CleanShot 2022-07-12 at 06 24 10@2x

I have a few notes as you can see here
CleanShot 2022-07-12 at 06 25 06@2x

Is this a bug you can look into?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by marcjulianschwarz** [comment]
Hi @pernielsentikaer,

thanks for pointing this out.
Should be fixed now.

**Comment by pernielsentikaer** [comment]
Hi @marcjulianschwarz 👋 

It seems to work much better now; there is only one thing that I stumbled upon while testing `Random Note`

Navigation titles should not be [changed in the root commands](https://developers.raycast.com/basics/prepare-an-extension-for-store#navigation-title) only when you push to a new view

Do you have a solution on how you can do this?

**Review by pernielsentikaer — COMMENTED** [review]
I think that we for `Random Note` should also not set the title, maybe better add #header in the markdown instead, is this possible?

**Comment by marcjulianschwarz** [comment]
Removed the navigation title changes for command when they are used with only one vault. For multiple vaults the changes will happen in a child view after a vault has been selected.

And removed the `{selectedText}` template as there were issues with the `getSelectedText` function not throwing an error but waiting, not resolving the promise.
Will investigate into this issue more for the next release.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
