### PR TITLE
Update Bluesky Extension

### PR DESCRIPTION
**Pull request by dkapila**
## Description

- The extension now requires a Bluesky App Password to be used.
- Unread Notifications command is renamed to Menu Bar Notifications.
- Menu Bar Notifications show not just the count, but the full messages of the recent 10 notifications.
- View and manage your Muted/Blocked Accounts.
- Mute or Block any user from the timeline from the Action Panel.
- Search for all posts in Bluesky.
- Improved search filters when viewing liked feed or an account feed.
- Raycast window closes automatically after a post is published (with a success HUD notification).

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by dkapila** [comment]
Some screenshots for the new features:
 
- Mute and block users from a timeline/feed:
CleanShot 2023-05-29 at 04 53 30@2x

- See/manage your mute and blocked users:
CleanShot 2023-05-29 at 04 54 15@2x

- Search for all posts in Bluesky from the Timeline:
CleanShot 2023-05-29 at 04 54 54@2x

- Menu bar now shows the notifications:
CleanShot 2023-05-29 at 04 57 09@2x

- Error if user uses Bluesky account password, instead of the generated App Password:
CleanShot 2023-05-29 at 04 57 52@2x

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:




* Some of the commands action panel items are not following the [naming convention](https://developers.raycast.com/basics/prepare-an-extension-for-store#action-panel), like below where it all lowercased - could you correct this in the extension?

bluesky 2023-05-30 at 13 54 25

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by dkapila** [comment]
Thanks for the feedback, will address it :)

**Comment by dkapila** [comment]
@pernielsentikaer Sorry for the delays - I have updated the commands in the action panel to follow the naming convention.

**Pull request merged**
