### PR TITLE
Add input-source-switcher extension

### PR DESCRIPTION
**Pull request by danulqua**
## Description

People with more than one input source often forget to switch between them and start typing in one language, but with a different input source in mind.

This extension switches the input source for the provided text from one language to another.

## Screencast

https://share.cleanshot.com/vvRSgSMj

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

It looks a bit like [this extension](https://www.raycast.com/lucaschultz/input-switcher) does kinda the same, could you check that out?

**Comment by danulqua** [comment]
@pernielsentikaer Hello, thank you for reviewing my extension!

Yes, before implementing it, I was looking for similar ones, including the **Keyboard Layout Switcher**. It simply toggles between input sources that the user has added in macOS.

But my extension transforms the provided text from one input source to another, as if you were typing using the same keyboard keys, so it's different and solves a real problem.

**Comment by danulqua** [comment]
So, any feedback?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

Thanks for the explanation 🙂

- I think I would use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) instead, this way you'll get better handling of errors and states

- I would add an action to toggle the language in the form

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
