### PR TITLE
Update gif-search extension to add option to hide filename.

### PR DESCRIPTION
**Pull request by seanparkross**
## Description

Following on from [this](https://github.com/raycast/extensions/issues/14413), added a feature to obfuscate the filename so it doesn't ruin the joke when sharing a gif. 

When pasting a gif into an app like Slack (which is where 99.99999% of all the gifs I need go) It displays the long text filename above the image. This kind of kills the joke in most cases. 

EG: 
> User 1: 
> {{Obvious statement}}
> 
> User 2: 
> funny-reaction-gif-to-an-obvious-statement.gif
> {{actual-hilarious-gif}}

This is devastating to comedy. 

## Screencast

[Screencast hereeeee](https://cirrus-prm.s3.amazonaws.com/Screen-Recording-2024-10-31-at-17.11.30.mp4)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by ridemountainpig — APPROVED** [review]
LGTM 👍

**Comment by seanparkross** [comment]
Updated PR description with Screencast. 👍

**Comment by seanparkross** [comment]
I could probably just call it "Hide filename" instead of "Obfuscate" 🤓 
Yes?

**Comment by seanparkross** [comment]
Changed to "Hide filename" not "Obfuscate filename" so we don't sound so pretentious. 🎉 

Can we get a merge please 🙏

**Review by samuelkraft — APPROVED** [review]
Looks good to me 👍

**Comment by seanparkross** [comment]
Profile updated!!

**Pull request merged**
