### PR TITLE
[Update Extension] Orion - add ability to search tabs

### LINKED ISSUE #4770: [Orion] Open tabs only search
### Extension

https://www.raycast.com/plonq/orion

### Description

Today, the history search works very well, but there's no way to scope it to only open tabs. A way to quickly search and switch tabs would be amazing.

### Who will benefit from this feature?

Orion users with lots of tabs open

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Plonq**
## Description

Adds the ability to search your Orion tabs, activate them, close them, etc.

Since Orion only exposes the tab URL and title (via automation scripting), there are some quirks if you have duplicate tabs open - only the first one will show up, as there's no way to differentiate them. Maybe this will change in the future.

Thanks to Safari extension - I adapted a bunch of code from there XD

Closes #4770

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Plonq 👋 

This doesn't work for me; I'm just getting this:

```
11:19:18.994 Inspection is enabled by default for process or parent application with deprecated 'com.apple.webinspector.allow' entitlement. Use `inspectable` API to enable inspection instead.
```

image

Can you look into this?

**Comment by Plonq** [comment]
Hi @pernielsentikaer, thanks for testing this.

I'm not sure what's happening there. I did a search for the error, and it seems to relate to devtools/webinspector. Is there anything about your setup that involves that? Maybe remote inspection enabled or something? Any other information you can provide?

I'm struggling to think of how this would relate to AppleScript/JXA.

**Comment by pernielsentikaer** [comment]
I checked once more, and all commands work, EXCEPT `Search Tabs`, which still gives me the same error as above. I have a standard Orion version 😞

**Comment by pernielsentikaer** [comment]
Actually, yes, I do @Plonq 😕 

Raycast-GLuP0I4f@2x

**Comment by Plonq** [comment]
> Actually, yes, I do @Plonq 😕

Interesting. Can you check that Raycast has appropriate automation permissions? System Settings > Privacy and Security > Automation.

image

**Comment by pernielsentikaer** [comment]
Hi @Plonq 👋 

Confirmed that both Safari and Arc is on the list 😢

**Comment by pernielsentikaer** [comment]
Yes, they're both on the Raycast list, sorry for the confusion 😊

**Comment by Plonq** [comment]
> Yes, they're both on the Raycast list, sorry for the confusion 😊

@pernielsentikaer Sorry I think there's still confusion here. Raycast needs to be on the Privacy & Security > Automation list, in MacOS System Settings. I.e., you need to give Raycast permission to use automation features of the OS, which includes AppleScript/JSA.
The browsers don't need to be on any list.

**Comment by pernielsentikaer** [comment]
I found out it's related to language, after switching the system language to English again, it works as expected - do you have a clue what we could change?

**Comment by Plonq** [comment]
> I found out it's related to language, after switching the system language to English again, it works as expected - do you have a clue what we could change?

Hmm. This is the first time I've used AppleScript/JXA, so I don't know much about it. But the only thing I can think of that would be affected by language is the name of the app - "Orion", due to this code:

```javascript
const orion = Application("Orion");
```

But I am assuming that the names of apps aren't translated (right?).

**Comment by pernielsentikaer** [comment]
Let's deal with that in another PR/issue if people is having the issue 😊

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Review by pernielsentikaer — APPROVED** [review]
Hello 👋

I gave it a quick spin, works as expected, and approved 🔥

**Pull request merged**
