### PR TITLE
feat: allow the user to select where to download the documents

### PR DESCRIPTION
**Pull request by MohamedK1**
## Description
Previously, all converted and downloaded documents are saved in the same directory as its original source. Now, adding the flexibility for the user to choose if they would like to select some specific name or directory.

## Screencast

https://github.com/raycast/extensions/assets/41074872/c43995ea-510a-4284-b7d6-3f3a34a8c6d4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution, do you want to add this for the new merge PDF command before merging?

**Comment by MohamedK1** [comment]
> Thanks for your contribution, do you want to add this for the new merge PDF command before merging?

Yep, I will do so

**Comment by MohamedK1** [comment]
@pernielsentikaer Done ✅  Updated it with changes for merge command too.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
