### PR TITLE
Add the-matrix-of-destiny extension

### PR DESCRIPTION
**Pull request by ordinz**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by ordinz — COMMENTED** [review]
Hey thanks for the review!  Great idea, but actually no, the name wouldn't be your own name.

**Comment by pernielsentikaer** [comment]
Could you improve the README a bit? I'm so confused about this what name I should type if not my own?

**Comment by pernielsentikaer** [comment]
Are you still here @ordinz 🙂

**Comment by ordinz** [comment]
> Are you still here @ordinz 🙂

mic check, is this thing still on?  Yup -- thanks!  Re-re-requesting now.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
