### PR TITLE
Update 1password extension

### PR DESCRIPTION
**Pull request by luizvergennes**
## Description

Fixes the infinite loading when trying to switch accounts.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Luk4h** [comment]
@kjeldahl Are you able to test this PR?

**Comment by kjeldahl** [comment]
> @kjeldahl Are you able to test this PR?

I am not sure how to do it. I found a way to fork the extension but how do I change it to your fork / pull request?

**Comment by kjeldahl** [comment]
> I am not sure how to do it. I found a way to fork the extension but how do I change it to your fork / pull request?

@Luk4h I just ended up forking it and copying your changes in by hand :-) It works just fine. 🎆 

One thing you could add is clearing the entries right away after switching account, as the old entries are show for about ~3 seconds while the new ones are loading.

Thanks a lot for the good work 👍

**Comment by Luk4h** [comment]
> @Luk4h I just ended up forking it and copying your changes in by hand :-) It works just fine. 🎆

Sorry got into how to do it as well...
The command is:
```bash
git clone -n --depth=1 --filter=tree:0 \
  -b ext/1password git@github.com:Luk4h/raycast-extensions.git
cd raycast-extensions
git sparse-checkout set --no-cone extensions/1password
git checkout
```

This should clone my fork and you can install and run in dev.

About the 3s Cache I thought about clearing it as well. I just pushed a fix to it, do you mind trying it?

**Comment by daninfpj** [comment]
I tested this branch for the issue mentioned in https://github.com/raycast/extensions/pull/12492#issuecomment-2125205104.

Still have the same problem.

> Command failed: /usr/local/bin/op signin --account xxx
[ERROR] 2024/05/22 10:46:56 found no accounts for filter "xxx"

The problem is `account.account_uuid` is `undefined` when setting the `Form.Dropdown.Item` value.

The command `op account list --format=json` returns something like this:

```
[
  {
    "url": "my.1password.com",
    "email": "email@mail.com",
    "user_uuid": "UUID"
  }
]
```

There is no `account_uuid` there and that seems consistent with the [1Password CLI Docs](https://developer.1password.com/docs/cli/use-multiple-accounts/#find-an-account-sign-in-address-or-id).

If I use either `url` or `user_uuid` for the value, signing in works.

**Comment by daninfpj** [comment]
> I tested this branch for the issue mentioned in [#12492 (comment)](https://github.com/raycast/extensions/pull/12492#issuecomment-2125205104).
> 
> Still have the same problem.
> 
> > Command failed: /usr/local/bin/op signin --account xxx
> > [ERROR] 2024/05/22 10:46:56 found no accounts for filter "xxx"
> 
> The problem is `account.account_uuid` is `undefined` when setting the `Form.Dropdown.Item` value.
> 
> The command `op account list --format=json` returns something like this:
> 
> ```
> [
>   {
>     "url": "my.1password.com",
>     "email": "email@mail.com",
>     "user_uuid": "UUID"
>   }
> ]
> ```
> 
> There is no `account_uuid` there and that seems consistent with the [1Password CLI Docs](https://developer.1password.com/docs/cli/use-multiple-accounts/#find-an-account-sign-in-address-or-id).
> 
> If I use either `url` or `user_uuid` for the value, signing in works.

Never mind, the problem was I was using an older version of the 1Password CLI (2.0.0). With v2.29.0 everything works! Thank you!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
