### PR TITLE
Update spanish-tv-guide extension

### PR DESCRIPTION
**Pull request by doktor500**
## Description

Calculate if a program is live in raycast extension to display the right live program as the data is cached now at origin

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
I just tested it and nothing happens for me, waited 5+ minutes

spanish-tv-guide 2024-12-11 at 12 42 38

Is something acting up?

**Comment by doktor500** [comment]
Hi @pernielsentikaer This is happening because https://www.movistarplus.es/programacion-tv is currently down

image

The API the raycast extension is using is scrapping this website and returning the necessary data in JSON format for the extension to work

**Comment by doktor500** [comment]
I'll consider dealing with this scenario in a more graceful way and display an error to the user, but that would be in another PR ;-)

**Comment by pernielsentikaer** [comment]
Let's merge it in and hope it's soon up again

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
