### PR TITLE
Add move-windows extension

### PR DESCRIPTION
**Pull request by albertxwz**
## Description
- The extension enables raycast to move the focused window to previous/next desktop on macos sequoia
- Basically simulate the "click and hold the window" and invoke "control+ arrow keys" to switch spaces by Applescripts.
- The switch of spaces by shortcuts should be enabled in keyboard settings first.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by albertxwz** [comment]
> Hi 👋
> 
> It seems to move the window correctly, but I get an error. Do you know what this might be about?
> 
> Raycast 2024-11-21 at 10 27 31
> 
> Should we make it work solely on Sequoia, or does it support every version compatible with Raycast?

Thank you for your review.

Could you please provide more information about the version of your system and raycast?

Thanks.

**Comment by albertxwz** [comment]
> > Hi 👋
> > It seems to move the window correctly, but I get an error. Do you know what this might be about?
> > Raycast 2024-11-21 at 10 27 31
> > Should we make it work solely on Sequoia, or does it support every version compatible with Raycast?
> 
> Thank you for your review.
> 
> Could you please provide more information about the version of your system and raycast?
> 
> By the way, does it happens for specific windows or for all windows on your system.
> 
> Thanks.

I found out why this error occurs. I think it is because it might select the raycast command bar and try to move the command bar to previous/next desktop if you perform the actions using command bar directly.

The simplest workaround is to set shortcuts for the two actions. Then you will not have the errors anymore.

Sadly, Apple's API does not allow developers to switch desktops(spaces). The only way, I think, is to simulate the actions we actually do using the mouse and keys.

**Comment by pernielsentikaer** [comment]
Hi @albertxwz 

We have a fix for this in Raycast which handle all situations better, do you mind waiting for that? It should be out with next release

**Comment by albertxwz** [comment]
> Hi @albertxwz
> 
> We have a fix for this in Raycast which handle all situations better, do you mind waiting for that? It should be out with next release

Look forward to the update. will close the pr.

**Comment by jaykobo** [comment]
According to the changelog, the fix has unfortunately only been implemented for Sequoia. The error still exists for me (on ventura). See #14451

**Comment by pernielsentikaer** [comment]
It should work out of the box for Ventura, only Sequoia is affected

**Pull request closed without merging**
