### PR TITLE
Update cobalt extension

### LINKED ISSUE #14044: [Cobalt] Deprecated API
### Extension

https://www.raycast.com/aelew/cobalt

### Raycast Version

1.81.0

### macOS Version

14.5 (23F79)

### Description

Error Message when trying to download any YouTube video:
```
An unexpected error occurred
this api domain is deprecated. use the https:// cobalt.tools/ web app, host your own api instance, or update the main cobalt api domain you use.
```

### Steps To Reproduce

1. Install the extension via the Raycast Store
2. Copy and paste any YouTube link (Optional: Set mode to Audio)
3. Start download

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by aelew**
## Description

- Updated dependencies
- Updated default API instance URL to `api.cobalt.tools`
- Fixed file names not being parsed properly sometimes
- Added `144p` and `240p` video quality options
- Added `Twitter: Convert GIFs to .gif` preference
- Added `TikTok: Prefer H.265/HEVC Videos` preference
- Removed `Vimeo Download Type` preference (no longer supported)
- Removed `Remove TikTok and Douyin Watermarks` preference (no longer supported)

Closes #14044

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by offbrands-studio** [comment]
Is this merge live? On the update extension plugin command it states Cobalt is Updated but this same issue arises with https://x.com videos whenever you try to use the extension. Downloading videos from X (formally, Twitter) on the https://cobalt.tools site works fine. 

Updated Raycast and all Extensions to clarify.

**Comment by aelew** [comment]
> Is this merge live? On the update extension plugin command it states Cobalt is Updated but this same issue arises with https://x.com videos whenever you try to use the extension. Downloading videos from X (formally, Twitter) on the https://cobalt.tools site works fine.
> 
> Updated Raycast and all Extensions to clarify.

The update should be live. Could you clarify the issue you're referring to? I've downloaded multiple videos from X without problems.

**Comment by offbrands-studio** [comment]
Apologies for not clarifying, thank you for the fast response. 

I just tried again to download a couple different videos from X using the cobalt.tools extension and this pops up from the notification section

`An unexpected error occurred this api domain is deprecated. use the https:// cobalt.tools/ web app, host your own api instance, or update the main cobalt api domain you use.`

When I run "Check For Extension Updates" from the command prompt I get : 
You're up to date! Raycast v1.81.2 is the newest version.  

When I run " Check for Extensions Update" from the command prompt I get : 
You are up to date!

In the Raycast Settings for Cobalt it says the extension API URL is : 
API Instance URL https://co.wuk.sh

I restarted both my computer and raycast a couple times before and after this comment to make sure it's not just me not doing the basic steps. Still getting the issue. Let me know if theres any other information I can pass along.

**Comment by aelew** [comment]
> > > Is this merge live? On the update extension plugin command it states Cobalt is Updated but this same issue arises with https://x.com videos whenever you try to use the extension. Downloading videos from X (formally, Twitter) on the https://cobalt.tools site works fine.
> > > Updated Raycast and all Extensions to clarify.
> > 
> > 
> > The update should be live. Could you clarify the issue you're referring to? I've downloaded multiple videos from X without problems.
> 
> Apologies for not clarifying, thank you for the fast response.
> 
> I just tried again to download a couple different videos from X using the cobalt.tools extension and this pops up from the notification section
> 
> `An unexpected error occurred this api domain is deprecated. use the https:// cobalt.tools/ web app, host your own api instance, or update the main cobalt api domain you use.`
> 
> When I run "Check For Extension Updates" from the command prompt I get : You're up to date! Raycast v1.81.2 is the newest version.
> 
> When I run " Check for Extensions Update" from the command prompt I get : You are up to date!
> 
> In the Raycast Settings for Cobalt it says the extension API URL is : API Instance URL https://co.wuk.sh
> 
> I restarted both my computer and raycast a couple times before and after this comment to make sure it's not just me not doing the basic steps. Still getting the issue. Let me know if theres any other information I can pass along.

Try manually updating the API instance URL in your extension settings to https://api.cobalt.tools

**Comment by offbrands-studio** [comment]
> > > > Is this merge live? On the update extension plugin command it states Cobalt is Updated but this same issue arises with https://x.com videos whenever you try to use the extension. Downloading videos from X (formally, Twitter) on the https://cobalt.tools site works fine.
> > > > Updated Raycast and all Extensions to clarify.
> > > 
> > > 
> > > The update should be live. Could you clarify the issue you're referring to? I've downloaded multiple videos from X without problems.
> > 
> > 
> > Apologies for not clarifying, thank you for the fast response.
> > I just tried again to download a couple different videos from X using the cobalt.tools extension and this pops up from the notification section
> > `An unexpected error occurred this api domain is deprecated. use the https:// cobalt.tools/ web app, host your own api instance, or update the main cobalt api domain you use.`
> > When I run "Check For Extension Updates" from the command prompt I get : You're up to date! Raycast v1.81.2 is the newest version.
> > When I run " Check for Extensions Update" from the command prompt I get : You are up to date!
> > In the Raycast Settings for Cobalt it says the extension API URL is : API Instance URL https://co.wuk.sh
> > I restarted both my computer and raycast a couple times before and after this comment to make sure it's not just me not doing the basic steps. Still getting the issue. Let me know if theres any other information I can pass along.
> 
> Try manually updating the API instance URL in your extension settings to https://api.cobalt.tools

Yup that fixed it for me! Thank you.

**Pull request merged**
