### PR TITLE
Update toggle-menu-bar extension

### PR DESCRIPTION
**Pull request by iamyeizi**
## Description

Troubleshooting added in readme.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by iamyeizi** [comment]
👋🏽 I think that is it

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by 48sudoku** [comment]
Hi @iamyeizi that's almost what I needed !! 
Can you also add a toggle for "Always" <-> "Never"? Thanks a lot

**Comment by iamyeizi** [comment]
Hi @48sudoku! for the moment → https://github.com/raycast/extensions/pull/6386#issuecomment-1718205923

I'll see if macos's settings allows me to do that or if I need to make a backend for that, when I have time 😁

**Comment by itsfatal** [comment]
Hey @iamyeizi what about and option to toggle between in full screen <-> Never? This is something I toggle frequently when watching a movie, or doing productivity work in a full screen app.

**Pull request merged**
