### PR TITLE
fix: NativeBase logo's aspect ratio, README media folder 

### PR DESCRIPTION
**Pull request by ShubhamVerma1811**
## Description

- Looks like for some reason in #967 the media folder was deleted and the README files were moved to a metadata folder. Added back the media folder with assets required in the README
- Fix the aspect ratio of the logo.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

### CODE REVIEW

**Review by mattisssa — CHANGES_REQUESTED** [review]
Hey! I've moved the files to keep them in a proper place so we can use them for screenshots.
Please check [our guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store#adding-screenshots) about it.

I think what can be done here is to change the path in the README.md file so you can use the screenshots in to be shown in the Store and in the readme file at the same time.

**Comment by ShubhamVerma1811** [comment]
Ah, Apologies.
The PR checklist also mentions about the `media` folder for README.

Will update the files with proper guidelines.

**Comment by mattisssa** [comment]
Thank you very much!

**Comment by mattisssa** [comment]
Sorry for popping this up again, but seems like something is still wrong with your screenshots. It hasn't passed the CI checks for sizes. 
The requirement for screenshots is having `2000 x 1250` dimensions, but yours has `1724 × 1172`.

Please update the dimensions when you have time, it's not urgent since we proceeded screenshots to the Store and for the Readme file everything works as well. @ShubhamVerma1811

**Pull request merged**
