### PR TITLE
Update tmux-sessioner extension

### PR DESCRIPTION
**Pull request by louishuyng**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by louishuyng** [comment]
Hi @pernielsentikaer please help to review this PR for fixing this issue here https://github.com/raycast/extensions/issues/7166#issuecomment-1597852850

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Is it correct that you deleted two files?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by louishuyng** [comment]
@pernielsentikaer these two files are redundant. I moved it inside the `src/utils` folder but forget to remove that in the previous release

image

**Comment by pernielsentikaer** [comment]
Thanks for the explanation 🙂

Approved 🚀

**Pull request merged**
