### PR TITLE
Add new PHP Monitor extension

### PR DESCRIPTION
**Pull request by nicoverbruggen**
## Description

This PR adds [PHP Monitor](https://github.com/nicoverbruggen/phpmon) (also known as *phpmon*) extension.

I created the extension [here](https://github.com/nicoverbruggen/phpmon-raycast-extension) first, and I copied over the relevant files and committed these changes here. If I missed anything, let me know. This is a very basic extension, since the it only really performs two tasks:

* Directly invoke `phpmon://` protocol commands, which will be interpreted by PHP Monitor if it is installed on the user's Mac. (PHP Monitor 5 or newer is required, which released yesterday.)
* Check which versions of PHP are installed, so that the user can tell PHP Monitor to switch to that version. To find out if a version is installed, the formulae folder locations are checked, after determining where Homebrew was installed. The communication with PHP Monitor also happens via the `phpmon://` protocol.

I did not add any additional checks because I suspect only users of PHP Monitor will install this particular extension, and they should have PHP Monitor installed and all its prerequisites installed.

## Type of change

- New extension

## Screencast

https://youtu.be/eq3gDWhfo1c (apologies for the low quality audio!)

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by nicoverbruggen** [comment]
Oops, I see I apparently made a mistake and this doesn't pass linting. Fixing this...

**Comment by pernielsentikaer** [comment]
Hi @nicoverbruggen 👋 

Thanks for your contribution, quite a coincidence, I just installed phpmon earlier today 💪 

 I'll give it a spin asap 🔥

**Comment by pernielsentikaer** [comment]
Hi @nicoverbruggen 👋 

Sorry for the late reply, it's not okay! Since I had it started last time, I now have problems starting it up (so not related directly to the extension)

When starting it i get alot of popups:
- PHP is not correctly installed
- PHP is not correctly installed
- Your Valet version could not be read (`valet --version` failed)
- Cannot determine services status
- Brew has not been added to sudoers.d
- Valet has not been added to sudoers.d

And here is the output of above commands:
O6Nn988kS7OD8tlN

Do you have any clue? Feel free to find me in [Slack](https://raycastcommunity.slack.com/) or another media 😄

**Comment by nicoverbruggen** [comment]
Hey @pernielsentikaer, what version of phpmon are you on? I pushed a bugfix update some time ago.

Could you try running `brew upgrade phpmon && valet trust` (no `sudo` needed I think, for `valet trust`) and let me know if that works?

**Comment by pernielsentikaer** [comment]
Hi @nicoverbruggen 

It was indeed an older version, but still, after update I get the exact same “errors” when launching

daAnq1AX1yPa14PD

So still no luck, I'm not sure what's causing it this time

**Comment by nicoverbruggen** [comment]
Hmm, it's strange that `valet`'s telling you `trust` is not defined, could you try reinstalling Valet? 

```
composer global update
valet install
valet use php@8.1
```

and try starting PHP Monitor again. That hopefully helps. 

Basically, if you ran `valet trust`, you should be able to run `valet` commands without sudo, which is required for the app to work. Since it seems like it's asking for your password, that's probably what's not working with your particular setup. 

I'm concerned that you're getting other PHP errors as well, though... but let's first see if this works. :)

**Comment by pernielsentikaer** [comment]
All above commands ran perfectly without problems – but still it's not quite happy

https://user-images.githubusercontent.com/38033107/153393081-9dee985f-e8dc-47de-909b-6b7a5d1aff48.mp4

I think I have to figure it out in my end, or reinstall some more 😄

**Comment by nicoverbruggen** [comment]
Are you on M1 hardware with another Homebrew installation in `/opt/homebrew` by any chance, and running x86 (Rosetta) Homebrew instead? It's a wild guess, but that could cause this issue.

Either way, PHP Monitor internally runs `/bin/sh` with a bunch of parameters, like this:

```
/bin/sh --login --noprofile -norc -c "valet --version"
/bin/sh --login --noprofile -norc -c "which php"
```

That might help us find out what's going on.

**Comment by pernielsentikaer** [comment]
I think your're right about them all
I got the new M1 pretty fast and there was no version of brew for M1 at that time.

Output of the commands are:
```
❯ /bin/sh --login --noprofile -norc -c "valet --version"
Laravel Valet 2.18.9
❯ /bin/sh --login --noprofile -norc -c "which php"
/usr/local/bin/php
```

I think there is a migration way to move to the "right" version also, could be an idea?

**Comment by pernielsentikaer** [comment]
It makes SO much sense - I'm almost done migrating to the "right" version 😄 

I think I only have one error left and its this one:

_Your Valet version could not be read (`valet --version` failed)_

I tried the trust commands without luck it seems, do you have an idea?

```
❯ sudo valet trust
Sudoers entries have been added for Brew and Valet.
```

**Comment by nicoverbruggen** [comment]
The following should work:

```
/bin/sh --login --noprofile -norc -c "/opt/homebrew/bin/valet --version"
```

and if it doesn't you may want to symlink Valet (the symlink is likely missing due to having run Valet prior to your native Homebrew migration), like so:

```
ln -s /Users/$(whoami)/.composer/vendor/bin/valet /opt/homebrew/bin/valet
```

That should fix the outstanding error message!

**Comment by nicoverbruggen** [comment]
Okay, thank you very much. I will look into these changes and let you know when it's done!

**Comment by nicoverbruggen** [comment]
Hey @pernielsentikaer, I've made some changes! Here's what I changed:

* All actions are now separate commands
* The active PHP version is now indicated as such

One thing of note:

> When switching PHP versions, you could then show a HUD, so the user know's what's happening

would not be possible since I don't broadcast or know when the switch has completed, so this is not included. 
Hope that's okay. Let me know if I need to make any additional changes :)

**Comment by pernielsentikaer** [comment]
Hi @nicoverbruggen 👋 

Thanks for the update 💪 I don't feel any slowness at all, but it's quite nice that it's possible to setup hotkeys and aliases for the commands 💯 

Subtitles for the commands should be “PHP Monitor” on all commands, when it's done, then we're ready to proceed to final review 🛩️

**Comment by nicoverbruggen** [comment]
@pernielsentikaer Okay, I've changed the subtitle for every command!

**Review by pernielsentikaer — APPROVED** [review]
Hi @nicoverbruggen 👏 

Thanks for your contribution, let's send it to final review 💪

**Review by mathieudutour — APPROVED** [review]

**Pull request merged**
