### PR TITLE
Update MLB Scores Extension

### PR DESCRIPTION
**Pull request by RobErskine**
## Description

With the MLB playoffs looming, I have been using the MLB Scores extension more and more. This PR adds in the following:

###  [Updated MLB scores] - 2024-09-23 
- Added Box Score summary
- Added inning indicator to games list
- Added latest play to  games list, as well as game detail
- Added "View on MLB" action

## Screenshots
ss1
ss2
ss3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
extensionsmlb-scores-2024-09-23-21 58 38@2x

- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jso8910** [comment]
Thanks so much for this commit. It feels great to know that someone still uses this extension I made in a few days a few years ago.

Do you know if Raycast has added some more component support since I last worked on this? I wonder if I could add a strike zone rendering. If you go to jso8910/mlb-nextjs in components/strike_zone.tsx I have react jsx that shows the strike zone. If there's more support for more advanced components with specific locations (or some drawing component), I could adapt that.

Additionally, having not used the component in a while, does it update automatically? Or do you need to exit the component and re-enter it every time you want it to update. I think that adding an updating feature could be useful.

**Comment by pernielsentikaer** [comment]
I would probably use [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch) which takes are of the caching

**Comment by RobErskine** [comment]
@jso8910 thanks for getting back to this so quick! i'm down to jam on additional features together if you're open to it.

To answer your questions:
- Component support: If it can be done in Markdown, it can probably be done in a Raycast component. I think it would be really cool to visualize the strike zone, but I don't know how feasible it is outside of rendering a dynamic SVG, which is totally possible, albeit a bunch of work.
- Updating automatically: Yeah the data is only fetched at time of use. We'd need to add a `setInterval()` or something to fetch data every 60s or something. As a self-proclaimed power user of this extension I think that would be a nice-to-have, but not a requirement.
- As part of this PR, I can make an update to sort the games. I can take a stab at that after work.

**Comment by jso8910** [comment]
@RobErskine hold up on doing that (because I did it this afternoon my time). Just spent a few hours working on it (and discovered I'm terrible at Typescript) and I managed to get auto refreshing and sorting working. I used `useFetch`, a `setInterval`, and a zustand store (to get the state to the `Action.push` component) to update the games every 15 seconds (which increases to every 10 minutes if there are no live games). I also fixed a couple bugs (inning indicator showing up in pre-game since the comparison was only `abstractGameCode === "F"`, as well as avg and era in the box score not working—not your fault, I blame the online interface generator I used 2 years ago for thinking that there were an ERA and AVG field, either that or it changed in the last 2 years which is also possible).

For a strike zone, perhaps we can create a grid? Just like a 3x3 grid (plus a few areas for pitches outside the zone) with the ball in it? That's not ideal, though, so it might just be better to create a list of pitches and nothing else.

Just opened a pull request in your repo https://github.com/RobErskine/raycast-extensions/pull/1.

**Comment by RobErskine** [comment]
@jso8910 Thanks for your help on making those updates today. I merged in your PR and cleaned a few things up a little bit (typos, linting, etc) as well as added a "Open in MLB" action for the Game Detail. If you have any questions or concerns let me know, but I think this is good to go!

**Comment by jso8910** [comment]
It looks like I forgot to commit `store.ts`. But you did a good job recreating it, thanks.

I think that for pitches, we should use the `Detail.Metadata` prop (because it will put the pitches off to the side so they can be seen while scrolling the box score, and it can be hidden). 

Just hardcoding the values, I made this mockup to show how we can do it. We would want to add an icon or some other UI element to make it look better but this UI works.

image

Here's the code used for it:
```ts
    return <Detail markdown={md_string} metadata={
        <Detail.Metadata>
            <Detail.Metadata.Label title="" text="3. Swinging Strike" />
            <Detail.Metadata.Separator />
            <Detail.Metadata.Label title="" text="2. Ball" />
            <Detail.Metadata.Separator />
            <Detail.Metadata.Label title="" text="1. Ball" />
        </Detail.Metadata>
    }/>;
```

**Comment by pernielsentikaer** [comment]
Can you help here @RobErskine

**Comment by RobErskine** [comment]
@jso8910 small update from me. I've optimized the markdown table a bit for the box scores for both batters and hitters that conjoins a few of the columns. It's a balancing act of readability/usability and getting it to look nice with the real estate we have.

Batting:
game tsx — mlb-scores-2024-09-25-21 43 27@2x

Pitching:
game tsx — mlb-scores-2024-09-25-21 43 45@2x

Next step for me is to loop through the active pitches and update the Metadata on the right there. I don't have it in me tonight but will tackle it tomorrow. You can check out the [latest up on my branch here](https://github.com/raycast/extensions/pull/14635/commits/8053b4d788486839ea225c209d4364577a268139).

**Comment by RobErskine** [comment]
@jso8910 alright, I think I got it.

I moved the game details to the right sidebar/metadata as well to save room. I added in the active pitch sequence to metadata as well. It's pretty cool to see it refresh and see the latest pitch result in `In play, run(s)`.

I also merged the R and RBI of 

Here are some screenshots of what this looks like.

image

image

I think this should be good for formal review unless you have issues?

Thanks - Rob

**Comment by jso8910** [comment]
@RobErskine I think this looks good. Can't think of any other features I want to add at the moment so should be good for review. 

Though you should merge my PR (https://github.com/RobErskine/raycast-extensions/pull/2) because I'm not confident that it is refreshing properly without it. Unless you noticed the issue and fixed it independently, but, testing the extension, that doesn't seem to be the case.

**Comment by RobErskine** [comment]
@jso8910 thanks for the ping on that PR; I totally missed it. I resolved the conflicts introduced with my new features tonight and got that merged in.

Here is a video of this working in action.

https://github.com/user-attachments/assets/c9a42dbb-ae50-4f7c-83ea-600ded849927
You can see it update automatically at 18s, 33s, 48s, etc.

I think this is good for Raycast's review, @pernielsentikaer!

Thanks and let me know if you have any questions.

**Comment by pernielsentikaer** [comment]
One last thing @RobErskine—do you mind using the same background for all metadata images 🙂

**Comment by RobErskine** [comment]
@pernielsentikaer Sure thing! I was cursed by the `Auto Switch Raycast Wallpaper` command. I have gone ahead and made sure that all metadata images are using the same background. If there are no other concerns I think this is good to roll out, just in time for the post-season!

---

Today is technically the last day of the regular season as the last few teams are playing makeup games. Due to this the original MLB Scores command screenshot (ss1.png) isn't that impressive since there are only two games listed. 

Perhaps during the post-season (which starts tomorrow) or maybe early in the 2025 season, we can update the screenshot so it is more representative of a typical Spring or Summer day that is packed with baseball.

**Comment by pernielsentikaer** [comment]
Could make sense :)

**Pull request merged**
