### PR TITLE
Add codegeex extension

### PR DESCRIPTION
**Pull request by MBearo**
## Description
[CodeGeex](https://github.com/THUDM/CodeGeeX) with raycast, generate code and translate code.

## Screencast
image

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by casiar** [comment]
This would be perfect!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Could you add some [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) 😊

**Comment by MBearo** [comment]
> Hi 👋
> 
> Could you add some [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) 😊

done

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
