### PR TITLE
Add polar extension

### PR DESCRIPTION
**Pull request by emilwidlund**
## Description

Implements `View Recent Orders` and `View Subscriptoins` commands for displaying orders and subscriptions on Polar.

## Screencast

polar 2024-12-10 at 21 48 57

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension in the `metadata` folder 🙂

**Comment by emilwidlund** [comment]
@pernielsentikaer Sure! Will do that right away!

**Comment by emilwidlund** [comment]
@pernielsentikaer I'm running into issues when trying to pull contributors before publishing. Any advice on how to proceed?
Screenshot 2024-12-20 at 11 29 40

**Comment by emilwidlund** [comment]
@pernielsentikaer Screenshots added ✅

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
