### PR TITLE
[GitHub]  Add an option to omit team review requests from query results

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- Add an option to omit team review requests from query results in PRs
- Updated dependencies and removed high-security vulnerabilities

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

* closes https://github.com/raycast/extensions/pull/12775 (duplicate)

### CODE REVIEW

**Comment by jfkisafk** [comment]
@thomaslombart can you please take a look? This is a duplicate of https://github.com/raycast/extensions/pull/12775 with some dependency update additions.

**Comment by LitoMore** [comment]
@jfkisafk This is fine. The people behind only need to deal with conflicts before merging.

It's super easy to resolve the `package-lock.json` file. Just run `npm install` again.

**Comment by jfkisafk** [comment]
For sure @LitoMore, this PR is updating all the dependencies to the latest! Given the rest of the changes are not heavy-handed like other open PRs for this extension, I think other PRs can resolve merge conflicts if necessary.

**Comment by LitoMore** [comment]
@jfkisafk Don't worry. GitHub will show a mandatory warning message if there are any conflicts. Users must solve the conflict before merging.

**Review by thomaslombart — APPROVED** [review]
🚀

**Pull request merged**
