### PR TITLE
Add YouTube Integration

### PR DESCRIPTION
**Pull request by tonka3000**
## Description

Add YouTube.

Command:

- Search Videos
- Search Channels

Support also sub-navigation between channels and videos.

Channel icons use circle mask, but the video thumbnails not, because they are rectangular.
 
> Info: Most personal commands can not be implemented without support for OAuth 2.0 in raycast directly, which is require in the YouTube API for every request which has private access (so playlist, recommended videos and so on).

## Type of change

- New extension

## Screencast

CleanShot 2021-10-31 at 17 21 47@2x

CleanShot 2021-10-31 at 17 17 51@2x

CleanShot 2021-10-31 at 20 12 26@2x

CleanShot 2021-10-31 at 20 13 01@2x

CleanShot 2021-10-31 at 20 13 52@2x

CleanShot 2021-10-31 at 20 14 09@2x

CleanShot 2021-10-31 at 20 14 22@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @tonka3000 👋 

Awesome addition to the extension report! Tested every aspect of it and it works as intended, good job 💪   Didn't have the Youtube API-enabled key, but I figured it out pretty fast.

A few suggestions that I personally would like to see:

- Some users may not know how to get the key, could something be added to ease this? Maybe a better description?
- Is it possible to add some kind of "sort by views", "name/default" preference?
- I'm not sure that I like the "No Result" - maybe it could show a list item somehow, did you have any considerations about this?

Again, looking forward to this 💯

**Comment by tonka3000** [comment]
> Some users may not know how to get the key, could something be added to ease this? Maybe a better description?

Did you check the `README.md` file, there should be all you need to get the key.

> Is it possible to add some kind of "sort by views", "name/default" preference?

Need to check if this is possible in all cases in the API (that it can sort by ...).

> I'm not sure that I like the "No Result" - maybe it could show a list item somehow, did you have any considerations about this?

Was my first try, but I would need OAuth to show the recommended videos (same as on youtube.com). So I don't have a good enough content for the list right now. Maybe I can get the trends, but this would waste the count of possible API calls per day.

Any ideas what I should show?

**Comment by pernielsentikaer** [comment]
> Did you check the `README.md` file, there should be all you need to get the key.

Frankly, I didn't, mostly because the end-user installing it from the store will never see the readme (at least not for now) - I don't have the perfect answer but it could maybe be a screen like this?

FeVcQOoRgXGTXEeQ

> Need to check if this is possible in all cases in the API (that it can sort by ...).

> EDIT: Should be possible to do

Awesome!

> Any ideas what I should show?

Let's discuss that over Slack (as we're doing right now) 😄

**Comment by PitNikola** [comment]
> Frankly, I didn't, mostly because the end-user installing it from the store will never see the readme (at least not for now) - I don't have the perfect answer but it could maybe be a screen like this?

We are adding a button that would show up in preferences and onboarding screen if `README` is provided. This might be shipped this week so keeping instructions in README is ok.

**Comment by tonka3000** [comment]
@PitNikola You read my mind 😄  => #277

**Review by pernielsentikaer — APPROVED** [review]
Hi @tonka3000 👋 

Thanks for your awesome contribution! We are suuuper happy that you chose Raycast extensions repo for it.

**Pull request merged**
