### PR TITLE
Add zen-browser extension

### PR DESCRIPTION
**Pull request by Keyruu**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Could you make new metadata images 🙂

**Comment by Keyruu** [comment]
Done.

**Comment by pernielsentikaer** [comment]
- Could you use the tool described [here](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension instead

**Comment by Keyruu** [comment]
Is it fine now?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Much better 🔥

**Comment by pernielsentikaer** [comment]
Do you by any change hold option key down? Try to release it faster 🙂

**Pull request merged**
