### PR TITLE
GitHub: Add typeahead search for repositories

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

Closes https://github.com/raycast/extensions/issues/5181
Closes https://github.com/raycast/extensions/issues/6519

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by yangwao** [comment]
Does it close this one too?
- #6432

**Comment by thomaslombart** [comment]
@yangwao The issue you linked is already closed.

**Comment by yangwao** [comment]
> @yangwao The issue you linked is already closed.

Ah got it.

GH has claimed that issue is on Raycast side, so looking forward to the release

**Comment by yangwao** [comment]
Sending activity.

**Comment by yangwao** [comment]
Hello @thomaslombart any update?

**Comment by pernielsentikaer** [comment]
Hi @yangwao 👋 

Sorry for the late reply, @thomaslombart has been on vacation and I didn't catch this because of the draft state, thomas will reply as soon as he is back 🙂

**Comment by thomaslombart** [comment]
Hey @yangwao, this PR is still in draft because we have inconsistencies with how dropdowns behave when used within the API as opposed to natively. Improving this may require directly enhancing the dropdown, which takes more time. Thanks for your patience.

**Comment by yangwao** [comment]
Activity 😌

**Comment by yangwao** [comment]
> which takes more time.

hey @thomaslombart any updates on this? :)

**Comment by thomaslombart** [comment]
Hey @yangwao, no updates as I'm onto other projects at the moment. Feel free to continue my work by opening another PR with my changes if that's important to you.

**Comment by thomaslombart** [comment]
Will get back to it at some point.

**Pull request closed without merging**
