### PR TITLE
Misc updates to CoinGecko extension calculate command

### PR DESCRIPTION
**Pull request by mike182uk**
## Description

A couple of miscellaneous updates to the `CoinGecko` extension `calculate` command:

- Refactored the calculate functionality due to rate limit changes on CoinGecko API making extension unusable
  - Uses similar logic for retrieving / searching coin data as existing `search` command
- Added in error message when retrieving coin data for calculate command fails due to rate limiting
- Tweaked the calculate actions copy
- Upgrade the extension dependencies
  - Removed redundant `rss-parser` dependency

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @mike182uk 👋 

Thanks for your contribution 🔥 

@Destiner do you mind checking this?

**Comment by mike182uk** [comment]
@pernielsentikaer Any reason this can't be merged?

**Comment by pernielsentikaer** [comment]
We have to get approval from the original author before it can be merged.

In this case, I'm going to open it again and check it once more

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by mike182uk** [comment]
@pernielsentikaer Out of interest, what happens in the case the original author is non responsive? (not just in this case, but in general with any raycast extension)

**Pull request merged**
