### PR TITLE
Fix VS Code recent projects extension

### PR DESCRIPTION
**Pull request by mskelton**
## Description

VS Code moved the storage of recent projects out of the storage JSON file into a sqlite DB causing the extension to stop working.  I used the same approach in this using sql.js and the WASM file as used by other extensions in this repo.

Due to the async nature of sql.js, this did require some changes to add in loading/error states while the data is loading.  I also tried to separate out the logic a bit to make it more clear and concise.

Here is the link to the VS Code PR: https://github.com/microsoft/vscode/pull/139632

## Type of change

- Bug fix

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @mskelton 👋 

Thanks for your improvement 💯

When opening the extension I just get `No Results` regardless I have items in `File > Open Recent` - can you look into this?

@thomaspaulmann do you have any feedback?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by mskelton** [comment]
@pernielsentikaer What version of VS Code are you running?

**Comment by thomaspaulmann** [comment]
> @pernielsentikaer What version of VS Code are you running?

Hey @mskelton thanks for this fix/addition. I wasn’t aware that VS Code changed the storage. I think it would be a good idea to support the old way as well for a period of time to guarantee a smooth transition. 

It shouldn’t be too hard to have a switch to get the data from the different locations. Probably check first if the JSON file exists and if not use your solution? WDYT? Happy to help to get this out soon so that it doesn’t block others with the new version of VS Code.

**Comment by pernielsentikaer** [comment]
> @pernielsentikaer What version of VS Code are you running?

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.4.0

**Comment by mskelton** [comment]
@thomaspaulmann @pernielsentikaer I've updated this PR to support older VS Code versions.  Thanks for the feedback.  Given that I don't have them installed, would one of you mind testing this works for you in an older VS Code version?

**Pull request merged**
