### PR TITLE
[DevDocs] Add import documentations feature and improve icons

### LINKED ISSUE #14101: [DevDocs]: Support for syncing enabled or disabled document sets
### Extension

https://www.raycast.com/djpowers/devdocs

### Description

DevDocs supports over 600 documentation sets, which can be overwhelming when searching. To address this, DevDocs allows users to control which documentation sets are enabled or disabled.

CleanShot 2024-08-20 at 11 39 57@2x

However, because of this fabulous Raycast extension, search entry points often happen from the extension, rather than the DevDocs interface. Unfortunately, this means that disabled documentation sets are still displayed in the search results.
CleanShot 2024-08-20 at 11  44 24@2x

It would be ideal if the Raycast extension could only show the enabled documentation sets, or at least sort them into two lexical groups: enabled and disabled.

### Who will benefit from this feature?

Almost everyone who uses DevDocs regularly would benefit from seeing less noise.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by djpowers**
## Description

This adds a new "Import Documentation Settings" command, which is designed to use the output from https://devdocs.io/settings. Instead of one large list, the imported "preferred" sets will be grouped at the top. This closes #14101.

In this version, the preferred documentations can be managed by re-importing a new JSON file, or clearing local storage to reset back to the default documentation sets. A future pull request could add the ability to add/remove preferred documentations, which could then potentially be exported for use with the web app.

It should handle bad file formats (non-JSON, no "docs" key), missing files, and if the doc strings are not valid (ignoring any strings that don't correspond to a documentation slug).

Additionally, this updates the icon stretching favicon strategy. Instead of fetching favicons, which are typically lo-res and outdated, this pulls from the DevDocs GitHub repo, which already stores a logo for each project. While this depends on GitHub being available to retrieve icons, I think the upgrade in quality is worth it. (For example, JavaScript, HTML, CSS, etc. use the "MDN" logo, which doesn't help distinguish the documentation at a glance.) A fallback Raycast item is used as a fallback.

## Screencast

https://github.com/user-attachments/assets/b37fb129-ad18-4f12-9f2e-dfafe639b155

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Can we handle this error gracefully? Used a mp4 file 🙂

devdocs 2024-09-30 at 11 34 01

**Comment by djpowers** [comment]
@pernielsentikaer thanks for the catch! I think the order of the validation logic had been changed such that the contents of the file were being checked before the filetype checks, resulting in the error. I just pushed an update to fix this.

**Comment by pernielsentikaer** [comment]
MUCH better 🔥

**Comment by djpowers** [comment]
Any other changes @pernielsentikaer, or should this be all set to merge?

**Comment by pernielsentikaer** [comment]
That should be all, let's merge it 🙂

**Pull request merged**
