### PR TITLE
[Imgur] Album and environment files

### PR DESCRIPTION
**Pull request by caumeira**
## Description

Add some features to imgur extension:
- Support multiple images to create a album
- Use environment finder selected files

## Screencast

https://user-images.githubusercontent.com/37943747/228082616-e6ca1da7-0872-4238-a642-fbb08285a247.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Can you check this @BalliAsghar 🔥

**Comment by BalliAsghar** [comment]
@pernielsentikaer LGTM!, @caumeira Thanks!

**Comment by caumeira** [comment]
> @pernielsentikaer LGTM!, @caumeira Thanks!

I will use mime-types to filter only allowed content acepted by imgur api, what you guys think?
@pernielsentikaer @BalliAsghar

**Comment by BalliAsghar** [comment]
> > @pernielsentikaer LGTM!, @caumeira Thanks!
> 
> I will use mime-types to filter only allowed content acepted by imgur api, what you guys think? @pernielsentikaer @BalliAsghar

it's a good approach, It adds an extra layer of validation and can prevent potential errors or security vulnerabilities.

**Comment by caumeira** [comment]
Done ✅
@BalliAsghar @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
