### PR TITLE
Add crisp extension

### PR DESCRIPTION
**Pull request by remorses**
## Description

[Crisp](https://crisp.chat/en/) is a support chat app

Control Crisp chat support app inside Raycast. This extension works by installing a Crisp plugin for 19$ a month: https://app.crisp.chat/initiate/plugin/f5ca7711-02b2-4f5b-bc39-216554c642b7/

## Screencast

Screenshot 2024-06-18 at 16 15 26

https://github.com/raycast/extensions/assets/31321188/298ff688-e582-409f-abd6-379639546f4d

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by remorses** [comment]
Ready for review

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Did you try [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch) from `@raycast/utils`, this should work more or less the same way as SWR - but you can keep SWR 🙂

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension



I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by remorses** [comment]
1. I am using swr because it has conditional fetching, so i can fetch only after the session has been created. I am also more familiar with its API
2. I added the screenshot, thank you

If you want to test the extension also installing the Crisp plugin i made it momentairly free :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
