### PR TITLE
[coffee] Add feature to schedule caffeination

### PR DESCRIPTION
**Pull request by adbcodes**
## Description
This PR adds a new command to the Coffee extension in Raycast called "Schedule Caffeination". This command will allow users to add schedules for caffeination, specific to each day of the week using natural language. Additional features to pause, resume and delete a schedule is also added

Contributes to #13705

## Screencast

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution 🔥 

Could you resolve the conflicts here @adbcodes so I can give it a go 🙂

**Comment by adbcodes** [comment]
@pernielsentikaer Donee! 😄

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Should we consider popping to root after setting it, I was really confused 🙂
- Im not sure that `Pause` is a destructive action
- Missing a color or tag if it’s currently paused or active
- Only show `Pause` or `Resume` based on the state

image


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by adbcodes** [comment]
Hello @pernielsentikaer 👋
Fixed the changes requested [here](https://github.com/raycast/extensions/pull/14171#pullrequestreview-2259887978)

And regarding the below point, I change the search text to an empty string after setting the schedule, I thought this would be better than popping to root. Let me know if it is okay 😄 
> Should we consider popping to root after setting it, I was really confused 🙂

Looking forward to your review!

**Comment by adbcodes** [comment]
@mooxl @bibixx @GastroGeek @pernielsentikaer @xilopaint @ridemountainpig

**Comment by pernielsentikaer** [comment]
I'll have a look with a fresh install now 🙂

**Comment by pernielsentikaer** [comment]
I gave it a spin and have some initial feedback 🙂

- When pausing I think a `Toast` would be better since `HUD` closes the window

- When resuming the paused command it changes to `Running` instead of Schedule, I guess that's an error (I'm not within the time)

- For delete action it would be better to use `Keyboard.Shortcut.Common.Remove` from `@raycast/api`

**Comment by adbcodes** [comment]
Hello @pernielsentikaer 😄
Thank you for the feedback. I have made the changes suggested

**Comment by pernielsentikaer** [comment]
- Instead of using HUD's it would still be better to use toasts

- What if I adds a new schedule for today for a timeframe that's already within the range it still shows "Scheduled", should it do that? I would expect "Running"

**Comment by adbcodes** [comment]
Fixed the second suggestion here in [this commit](https://github.com/raycast/extensions/pull/14171/commits/8543337b9a8651434b5bc1b383dc423c24b5bfc8) 

For the first comment I was not able to find any HUDs, if it is the one that pops up when a schedule starts running then I fixed that in the same commit as above. Other than that I don't see any HUDs 🤔

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
You can reference image from `metadata` folder in `README` - if you add a new [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)  please make sure to use the same background or let me know if you need help

**Comment by adbcodes** [comment]
The window capture feature is so cool, makes life so easy, thank you for the suggestion 💡 
Also thanks for adding the `{PR_MERGE_DATE}` label, I somehow missed that :D

**Pull request merged**
