### PR TITLE
Add gif-search extension

### PR DESCRIPTION
**Pull request by josephschmitt**
## Description

This extension allows users to search for animated GIFs via [giphy.com](giphy.com) or [tenor.com](tenor.com). It requires the user to get a (free) API token for each service they intend on using. Once that's set, they can view the top 10 trending gifs, or search for specific ones.

I really, REALLY wanted to have an embedded full-size GIF preview to be a part of this extension. However, Raycast's `<Detail>` component's markdown renderer only displays the first frame.

I [tried implementing a custom GIF decoder and renderer](https://github.com/josephschmitt/raycast-gif-search#about-this-extension) in react, with some amount of success. It mostly works well, but when it's first loading the frames the `img` tag loader pops in briefly between frames. Once they're all in memory it plays smoothly. There's also a weird issue I haven't been able to track down where sometimes when trying to exit the `<Detail>` view, it'll fail, and then when trying to exit again, I'll get a stack trace from the Raycast extension host saying it was unable to pop off the navigation stack. 

Because of this I've decided to hide it behind a setting (disabled by default) in order to be able to submit this extension to the store. With the preview disabled, all this extension will allow you to do is get a list of gifs, and either open it in your browser, or copy it to your clipboard. Still useful, but not as awesome as if the inline gif renderer worked.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

### CODE REVIEW

**Comment by josephschmitt** [comment]
Hmm, the build is complaining about not finding my username, but as far as I can see it's set correctly: https://www.raycast.com/josephschmitt

**Review by fe9lix — CHANGES_REQUESTED** [review]
Hey @josephschmitt, thanks for your contribution! 
I appreciate your workaround for the current limitation with detail views not rendering animated gifs. Here's what I would suggest:

How about removing the custom rendering incl. the checkbox and only supporting the search through the APIs? That already adds value, so the extension makes sense even without the detail view rendering. (I wouldn't want to expose a buggy feature to end users...)
Here's the good news: we've worked on an internal animated gifs rendering for detail views already and it's likely to be released in one of the upcoming releases. At that point, you could then update your extension and add this feature to detail views.

**Comment by fe9lix** [comment]
@josephschmitt Btw, the CI complains about prettier errors . You can fix them by running `npm run fix-lint`.

**Comment by fe9lix** [comment]
Some other things I noticed:

- The MIT license file can be removed since the entire repo is already MIT licensed
- Could you remove the media source files? Files that are shown in the README should go into the top-level media folder, without any psd or ai source files. (While files that you need at runtime go into the assets folder and get bundled into the extension.)

**Comment by josephschmitt** [comment]
@fe9lix I've removed the license, fixed the lint (my local VS Code seems to constantly fight your linter for some reason), and updated the `media` folder.

So the custom renderer actually works pretty well now. I feel like it could be useful still, and just off by default (and maybe marked "Experimental" instead of "Unstable"). wdyt?

**Comment by fe9lix** [comment]
Hey @josephschmitt, I've given it another try and when turning on the experimental feature, I'm running into a couple of issues:

- The initial loading causes heavy flickering, which looks buggy
- It consumes a ton of memory
- Sometimes ESC doesn't work to pop back

Overall, I wouldn't want to expose this particular feature to end users since it feels buggy and unstable. The search looks good to me, so we could still release it without the gif playback workaround, and you could publish an update later once we support native playback. Btw, if you still want to use the experimental feature personally, nothing stops you from running the extension locally.

When I tested the extension, I also ran into warnings with duplicate keys in the list (each list item should have a stable identity with the `key` property) – could you address this?

**Comment by josephschmitt** [comment]
@fe9lix wait nevermind, think I figured it out. I was setting the key on the wrapping `GifResult` component as well as the `List.Item` inside it. Fixed now.

**Comment by fe9lix** [comment]
Thanks for the updates!

**Comment by fe9lix** [comment]
@josephschmitt One more nit: The command subtitle property shouldn't really be used for longer descriptions, also see the [store guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store) on this. I'd suggest to either remove it in your case or add something short and title-cased such as "GIF Search"

**Comment by josephschmitt** [comment]
@fe9lix you mean this? 
image

How short should it be?

**Review by fe9lix — APPROVED** [review]

**Pull request merged**
