### PR TITLE
add hide-application

### PR DESCRIPTION
**Pull request by that70schris**
## Description

New extension for a global `Hide Application` command

macOS uses a dynamic menu command title for Hide, ex: `Hide Slack`.  this makes it impossible to remap the assigned keyboard shortcut `command + h`.  This extension just provides a single `Hide Application` command which can be assigned any shortcut in Raycast.

I ultimately think this should live in the built-in "System" commands.  But creating this to start with so I can move on from Alfred ;)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by that70schris** [comment]
just looking for an icon

**Comment by koinzhang** [comment]
It is possible to hide the current application using the shortcut CMD+H, is it worth creating another extension to do this?

**Comment by that70schris** [comment]
@koinzhang I really benefit from being able to remap this shortcut in my setup.  I used to do this with an Alfred workflow.  Creating an extension in Raycast is the only reliable and snappy way I've found to do this.  Ideally this would be a built-in System command rather than a separate extension

**Comment by koinzhang** [comment]
Perhaps creating a Script Command would be a better option?
The following code creates a Script Command in Raycast to hide the frontmost application.

```
#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Hide App
# @raycast.mode compact

# Optional parameters:
# @raycast.icon 🙈
# @raycast.packageName System

# Documentation:
# @raycast.author koinzhang
# @raycast.authorURL https://raycast.com/koinzhang

tell application "System Events"
	tell (first process whose frontmost is true)
		set appName to displayed name
	end tell
end tell

tell application "System Events"
	set visible of application process appName to false
end tell
```

**Comment by that70schris** [comment]
ah nice! thanks @koinzhang I had tried that before, but couldn't get the code right, this works perfectly and I agree is a better place than a complete extension

**Comment by that70schris** [comment]
thanks again @koinzhang, provided the script for the community here: https://github.com/raycast/script-commands/pull/956

**Pull request closed without merging**
