### PR TITLE
Add xcrun extension

### PR DESCRIPTION
**Pull request by 3llomi**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

How is tihs compared to @SvenTiigi's [xcode extension](https://www.raycast.com/SvenTiigi/xcode)? Seems like there are some overlaps, but I'm not the target audience 🙂

**Comment by 3llomi** [comment]
Hi @pernielsentikaer ,

My extension was built to execute commands for the IOS Simulator itself using 'xcrun' which gives you full control over the simulator like renaming a simulator, getting app container, pushing notification, launching app, uninstalling app, etc...

I can see that the other extension provides functionalities that are Xcode-related like showing recent projects, creating new projects, etc..

**Comment by SvenTiigi** [comment]
Hi @3llomi,

The functions you are describing are available via the "Search Recent Builds" command of the [Xcode Raycast extension](https://www.raycast.com/SvenTiigi/xcode) where you can launch an app, uninstall it and also get all relevant directories as well as resetting permissions for example push notifications, location services, etc...

The "Manage Simulators" command contains additional functionality which internally are making use of `xcrun`. 

Renmaing a simulator is currently not implemented so this would be a good PR to the Xcode extension 👍

**Comment by 3llomi** [comment]
Hi @SvenTiigi ,

Great job with the 'Search Recent Builds' command, I didn't notice it, even though I had your extension installed. probably because of the naming 😅

I can see that your extension has the most features except for the following:

1. Restart Simulator
I use this A LOT especially when the Simulator gets stuck for some reason.

2. Push Notifications using a Payload
3. Trigger iCloud Sync

4. Get app container path
I can see that your extension already have that, but it doesn't have the 'groups' directory which is a shared directory between app targets. Not sure if i'm missing something.

Let me know if you're interested in these so I can open a PR and close this.

**Comment by SvenTiigi** [comment]
@3llomi yes of course! Please feel free to open up a PR ✌️

**Pull request closed without merging**
