### PR TITLE
[Extension] kubectl logs and describe

### PR DESCRIPTION
**Pull request by m-wrzr**
## Description

Adds functionality to search trough kubernetes resources and get their logs or yaml description.

## Screencast

- Will be provided when PR is finished

List View
kubectl describe
kubectl logs

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by m-wrzr** [comment]
Hey, I have two things that I would like to add to the PR. Maybe you can help me with this:

1. Display text without the markdown rendering in _Detail_ (i would like to display logs as they appear in the terminal)
2. Automatically scroll to the bottom in a _Detail_ view

**Comment by danielsequeira** [comment]
@m-wrzr do you still need help with your extension? And are you still interested in finalising it?

**Comment by m-wrzr** [comment]
Yes, but from what i read in the docs it doesn't seem possible to do the UI this way?

I want to either show logs/describe outputs in a raycast terminal view (the way it is shown in script commands - without launching an external terminal application) or in some sort of detail view to achieve the same as described in points 1/2 above.

I didn't find any view components other than what is described in https://developers.raycast.com/api-reference/user-interface so that's why I asked for help here.

**Comment by danielsequeira** [comment]
@m-wrzr for that I think the best option in Raycast is to use the Detail component: https://developers.raycast.com/api-reference/user-interface/detail which renders markdown and in that case you could so something like **```shell**

**Comment by danielsequeira** [comment]
@m-wrzr ping here, do you still intend to continue the work for this PR?

**Pull request closed without merging**
