### PR TITLE
Add hubspot-portal-launcher extension

### PR DESCRIPTION
**Pull request by chrisoklepke**
## Description

A simple Raycast extension that allows you to quickly launch and navigate to different objects in your HubSpot portals. This extension is perfect for people who are working on and/or maintaining multiple portals/environments like HubSpot Partner employees and developers. 

It's different from the other HubSpot extension already on the store. The [HubSpot Raycast Extension](https://www.raycast.com/harisvsulaiman/hubspot) by [Haris Sulaiman](https://github.com/harisvsulaiman) is ideal if someone only works with one portal only. It allows to interact with records like contacts, companies etc. directly, whereas this one "only" launches the respective portal into a specific object overview. 

I've used the Todo List Template provided by Raycast. I'm not a developer by trade but I using and improving this extension for a while myself and I would like an easy way to share this with the rest of the HubSpot Solution Provider Community. 

## Screencast

[HubSpot Portal Launcher Demo - Watch Video](https://www.loom.com/share/7c535f87869f4be9a95875231365325f)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @chrisoklepke 👋 

Could you check that I didn't break anything before we proceed? 🙂

**Comment by chrisoklepke** [comment]
Hey @pernielsentikaer 🤘 

Thank you for taking the time to review this extension. It all LGTM!

The destructive styles where on my radar before but I wasn't able to get them to work properly. Thank you helping out here 🙏 

Is there something else you need me to do? 

Cheers, 
Chriso

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by chrisoklepke** [comment]
Thank you, mate! I'm happy this went so smoothly 🚢

**Pull request merged**
