### PR TITLE
Add Premier League extension

### PR DESCRIPTION
**Pull request by anhthang**
## Description

View the latest Premier League tables, form guides and season archives in Raycast.

## Screencast

epl-01
epl-02
epl-03
epl-04

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by anhthang** [comment]
```raycast-premier-league on  main via 🤖 v17.8.0
❯ npm run build

> build
> ray build -e dist

info  - entry points [src/table.tsx]
info  - checked TypeScript
ready - built extension successfully```

Built successfully but I don't know why it failed

**Comment by pernielsentikaer** [comment]
Hi @anhthang 👋 

Thanks for your contribution 🔥

It seems like you're missing the file `.eslintrc.json`

**Comment by anhthang** [comment]
Hi @pernielsentikaer 

Thanks for address it. I wonder how I can miss that file when copying from my repository. It's green now :D

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @anhthang 👋 

Thanks for your contribution 🔥 

I left some feedback for you to address: 

- It seems like all commands suffer from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

- Seems like a few clubs are missing a logo, you could provide a fallback image.

- If searching for "Kasper" in "Players", then no match is found, but if checking "Leicester city" here is there.

Looking forward to testing it out again 💪 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 

Thanks for your addresses. 

Regarding to the issue that club logo is missing, the url still showing image when I opened in browser. But I'm not sure why it's showing blank. I remember I tried with fallback image already but it's not rendered. Do you have any suggestions?

**Comment by anhthang** [comment]
Hi @pernielsentikaer 👋 

Can you please review this also?

**Comment by pernielsentikaer** [comment]
Hi @anhthang 👋 

Seems like this extension also suffers from the dropdown change on the action, tested it both in `clubs` and `Fixtures`

Could you look into this in this one too?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 👋 

Yes, you're right. It's fixed. Please check again.

**Comment by pernielsentikaer** [comment]
Hi @anhthang 👋 

Awesome with the corrections, we're almost there! 🚀 🔥 

I have some fresh feedback for you, went through all commands and spotted a few things:

- Player
   - Is there a reason for not showing all players in the list initially?
   - Add keyword with player type
   - Remove undefined values if possible?
   
CleanShot 2022-04-20 at 10 12 56@2x


- Clubs
   - Switch Squad and Open in Browser
   - When searching for a player in squad list, it searches in all clubs
   - Multiple `List.EmptyView` children have been passed to `List`. Only the last one will be shown.
 
- Results
   - Load more crashes the system
     
CleanShot 2022-04-20 at 10 19 55@2x

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pernielsentikaer** [comment]
Please note that we have a 🐛 when you search and the dropdown disappears it selects the text, we're working on it 😄

**Comment by anhthang** [comment]
Hi @pernielsentikaer 

Please see my comments below:
1. Player
- There is a thousand players, so it will be very long list and take long time to get it. And I want it same as the flow in the official website 

For the others, I will find and fix it soon

**Comment by pernielsentikaer** [comment]
Hi @anhthang 👋 

That makes sense. Maybe it should only be there when not searching?

CleanShot 2022-04-20 at 11 01 44@2x

At the moment, you're using the best way. Others do it too, [like this one](https://github.com/raycast/extensions/blob/070c194ad8e012da2e677a9c1f1f88f6111bab8a/extensions/readwise/src/components/Actions.tsx#L9-L31) 

I am looking forward to testing out the extension again.

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 👋 

It's fixed. Please review again.

**Comment by pernielsentikaer** [comment]
Hi @anhthang 👋 

MUCH better! 🔥 

The only thing I can see that could be improved now is when you search for a player some fun things happening:

- I guess there is no need to show a `Next Page` while searching, is there?

CleanShot 2022-04-20 at 14 54 27@2x
 
- I'm not sure if it's just here, but if I search for `Defender` in the player command, nothing happens

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 👋 

- Next Page issue is fixed.
- When searching in player command, it's searching for player name from API, so you will not see anything from results. It's expected. But in a club page, you can search by position to filter

The fixes is pushed, please review again.

**Review by pernielsentikaer — APPROVED** [review]
Awesome @anhthang 🔥 

Thanks for all the corrections, we're ready to release first version 🚀

**Pull request merged**
