### PR TITLE
feat(Timers): cleanup, support API changes, persistent timers, stopwatches

### LINKED ISSUE #2724: [Timers] ...
# Extension – [Timers](https://github.com/raycast/extensions/tree/6ead481b289b6072171326c1e5a8917c1e6cda3c/extensions/timers/)
Author:

Current: the timer finishes and the alarm sounds once. This is often sufficient, except when I'm deeply focused. In that state, the sound doesn't even register and I might as well not have even set a timer. 

Desired: When a timer is started, I can optionally select for it to have an alarm that persists until I dismiss the alarm.

### LINKED ISSUE #2902: [Timers] Menu bar command with nearest timer
# Extension – [Timers](https://github.com/raycast/extensions/tree/6ead481b289b6072171326c1e5a8917c1e6cda3c/extensions/timers/)
Author: @ThatNerdSquared

**Describe the feature and the current behavior/state.**

When any timer is set, it would be great if the nearest timer would show as `Menu Bar Command` 🔥

**Who will benefit from this feature?**

I certainly do, but I think that everyone who uses this extension.

**Any Other info.**

### PR DESCRIPTION
**Pull request by ThatNerdSquared**
## Description

This PR adds a few updates to the Timers extension:
- MenuBarExtra support (thanks @marcjulianschwarz) [closes #2902]
- Inline Argument support for the Start Custom Timer command
- Stopwatch support (start and stop multiple stopwatches, with renaming and viewing functionality similar to the timers)
- Persistent timer support (ring the timer alert sound until dismissed, when a timer finishes) [closes #2724]
- Support new Raycast form validation
- Add hooks for state management functions
- Create formatUtils file for various date and time formatters

## Screencast
The nature of this extension makes screen recordings a bit difficult, but here are some screenshots that help showcase the changes:

Screen Shot 2022-09-10 at 13 42 55
Screen Shot 2022-09-19 at 15 08 24
Screen Shot 2022-09-10 at 13 46 43

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by ungarmichael** [comment]
Is it also possible to copy the time to the clipboard?

**Comment by ThatNerdSquared** [comment]
Not yet ;) I can add it if you would like - or feel free to PR into [ThatNerdSquared/timers-for-raycast](https://github.com/ThatNerdSquared/timers-for-raycast) and I will add it here ASAP.

**Comment by pernielsentikaer** [comment]
I converted this into a draft until you're ready 🙂

**Comment by ThatNerdSquared** [comment]
Thanks @pernielsentikaer - it's ready for review now. Sorry for the delay 😅

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by ThatNerdSquared** [comment]
Thanks @pernielsentikaer!

**Pull request merged**
