### PR TITLE
Update json-format extension

### PR DESCRIPTION
**Pull request by AlexIsMaking**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by devloos** [comment]
Hey 🎉, @AlexIsMaking looks good thank you for contributing. I am trying to figure out what value this provides. I might be missing something but I see no difference than just running format command instead.

**Comment by AlexIsMaking** [comment]
Hey @devloos thanks for checking this out! At the moment, if you try to format stringified JSON like:

```
"{\n  \"product\": \"Live JSON generator\",\n  \"version\": 3.1,\n  \"releaseDate\": \"2014-06-25T00:00:00.000Z\",\n  \"demo\": true,\n  \"person\": {\n    \"id\": 12345,\n    \"name\": \"John Doe\",\n    \"phones\": {\n      \"home\": \"800-123-4567\",\n      \"mobile\": \"877-123-1234\"\n    },\n    \"email\": [\n      \"jd@example.com\",\n      \"jd@example.org\"\n    ],\n    \"dateOfBirth\": \"1980-01-02T00:00:00.000Z\",\n    \"registered\": true,\n    \"emergencyContacts\": [\n      {\n        \"name\": \"Jane Doe\",\n        \"phone\": \"888-555-1212\",\n        \"relationship\": \"spouse\"\n      },\n      {\n        \"name\": \"Justin Doe\",\n        \"phone\": \"877-123-1212\",\n        \"relationship\": \"parent\"\n      }\n    ]\n  }\n}"
```

then the format command won't work. This gives the user the option to parse stringified JSON and then format it, if they need to.

**Comment by devloos** [comment]
Hey @AlexIsMaking, I see thanks for the clarification. Maybe it would play nicer if we didn't make another command and used your existing logic and make it work with `formatJS`. That way users don't have another command to think about.

This could be accomplished by using your `parse` function in formatJS then check if successful give `formatJS` a stringified json else give trimmed text.

let me know if it works I did not test

**Comment by mil3na** [comment]
Hi @AlexIsMaking ! Thank you for your contribution and thanks @devloos for checking it out!
I'm just a bit confused: I don't see a new command being added, just a parser, which is exactly what this change is about. Seems to be transparent for the user. Am I wrong? @AlexIsMaking do you need any help? @devloos please tell us if you are ok if those changes are transparent to the user :)

**Comment by mil3na** [comment]
It would be nice to update the CHANGELOG ;)

**Comment by devloos** [comment]
Hey, @AlexIsMaking and @mil3na I fumbled my wording what I meant to say was instead of adding a new action toss it all under the same action. It could be cleaner since the end goal of both actions is to format the JSON given. It's not confusing to the user just removes friction points.

**Comment by AlexIsMaking** [comment]
@devloos no worries, nice idea. I've just updated the commit to add the parsing functionality to the existing actions and commands so it's integrated seamlessly now.

**Review by mil3na — APPROVED** [review]
It looks good to me! 
If @devloos is also ok with it, we can merge it :)

**Comment by AlexIsMaking** [comment]
Best,

Alex

**Comment by devloos** [comment]
Looks good!

**Pull request merged**
