### PR TITLE
Add paste-from-apple-books extension

### PR DESCRIPTION
**Pull request by winann**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- This should be a [no-view command](https://developers.raycast.com/information/lifecycle) instead

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by winann** [comment]
I'm update extension's mode to `no-view`, and also change extension's title  to use Title Cased.
When I run `npm run publish`, there are some error: ‘open PR: Error’.
What I want to know is: is it possible to continue the review？

Here is outputs:

> publish
> npx @raycast/api@latest publish

ready -  validate git repository
ready -  getting fork
ready -  preparing clone
ready -  checking for new contributions
ready -  preparing extension
ready -  pushing extension
error -  submitting extension
open PR: Error:

**Comment by pernielsentikaer** [comment]
Do you have anything missing in the PR now? If so, can you show me a screenshot of the error so I can figure out what's going on 🙂

**Comment by winann** [comment]
Nothing is missing in this PR. Please continue to review my extension. thx

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
