### PR TITLE
New extension: Session

### PR DESCRIPTION
**Pull request by jamesjlyons**
## Description

Allows user to control Session app timers, similar to previously submitted script commands.

## Screencast

[Screencast uploaded here](https://share.cleanshot.com/axzDbZ)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jamesjlyons** [comment]
Whoops, wrong icon size. I'll get that fixed.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @jamesjlyons  👋 

Thanks for your contribution 🔥 

I tested it out and it works as expected, I have a question:

Is it possible to show a HUD (on success and failure OR just a confirmation)? That would be awesome, I'm not sure if it's possible to check whether session is installed or not?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by jamesjlyons** [comment]
@pernielsentikaer Just added HUD messages for confirmations! Not entirely sure how to check if session is installed or not yet, but I'm still looking into it. As far as I know that would be the only way to know if there was any kind of error.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @jamesjlyons 👋 

I hope it's okay that I added the installation check and corrected the screenshot, could you give it a quick spin before merging 😄

**Comment by jamesjlyons** [comment]
@pernielsentikaer Oh perfect! Thank you for the help, very much appreciated. Gave it a spin and everything seems to be working on my end, the installation check works great.

**Pull request merged**
