### PR TITLE
[Bitwarden] Fix desync between password and generator options

### PR DESCRIPTION
**Pull request by jomifepe**
## Description

The first iteration of the password generation has a bug. When you changed the options, it generated a new password, and if you didn't wait for it to finish, and changed another option, it would ignore it and the result would be incorrect. In this PR, the previous action is aborted when you trigger a new one, using an `AbortController`.

<details>
  <summary>🎥 Demonstration</summary>
  
https://user-images.githubusercontent.com/7235666/162644727-039282bd-0be1-4747-9393-929e56dc7149.mp4
</details>

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pomdtr** [comment]
Please add yourself to the contributors array !

**Comment by jomifepe** [comment]
> Edit: I'm not good with names 😬
> 
> Thank for your contribution, it looks good to me !

Thank you 🙂 Waiting for merge

**Comment by pernielsentikaer** [comment]
Hi @jomifepe 👋 

Another PR regarding Bitwarden was merged earlier today which led to a merge conflict in this extension - It looks very small, do you have time to resolve it?

**Comment by jomifepe** [comment]
> Hi @jomifepe 👋
> 
> Another PR regarding Bitwarden was merged earlier today which led to a merge conflict in this extension - It looks very small, do you have time to resolve it?

Hey @pernielsentikaer. Of course, it's done 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi @jomifepe 👋 

Thanks for your contribution. I tested it OK. Let's get it merged!

**Pull request merged**
