### PR TITLE
Initial commit for .New Shortcuts extension

### PR DESCRIPTION
**Pull request by chrismessina**
## Description

This extension provides quick access to [all the shortcuts](https://whats.new/shortcuts) publicly listed in the Whats.New registry, managed by Google.

## Screenshots

new-shortcuts-2

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npx ray build -e dist` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
[dot-new](https://www.raycast.com/natterstefan/dot-new) already available in the store

**Comment by chrismessina** [comment]
> [dot-new](https://www.raycast.com/natterstefan/dot-new) already available in the store

Oh no! You're totally right. 

I'll need to make a PR for that extension. 🫣

**Comment by pernielsentikaer** [comment]
It would indeed be best to only have one of the same in the store, could some of your features enhance the other one from @natterstefan

**Comment by chrismessina** [comment]
> It would indeed be best to only have one of the same in the store, could some of your features enhance the other one from @natterstefan

Ok — I'll work on that later this week. Moving this PR to a draft for now.

**Comment by natterstefan** [comment]
Hi 👋,

thanks for the mention and your work @chrismessina. I'm happy to review and implement new ideas and improvements to the existing extension.

**Comment by chrismessina** [comment]
> Hi 👋,
> 
> thanks for the mention and your work @chrismessina. I'm happy to review and implement new ideas and improvements to the existing extension.

Super. A couple comments/clarifying questions:

- I was super impressed to discover how you populated your extension by scraping the table on [whats.new](https://whats.new). Like a n00b, I manually extracted the data and then built an Airtable so I could have more control over the data, including handling duplicate entries (i.e. handling shortcut synonyms like [building.new](https://building.new/), [floorplan.new](https://floorplan.new/), and [interiorspace.new](https://interiorspace.new/)). It appears that your extension doesn't handle these cases:

2024-08-26 (15 06 40) Arc
 
2024-08-26 (15 06 03) Arc

- I also added a few custom shortcuts that aren't strictly using the .new TLD (e.g. [New Claude Project](https://claude.ai/projects/create)).
- I added categories to make it easier to filter the shortcuts and that seems easy enough to add to your extension, though the data model would need to change.
- Going forward, what do you think is the best strategy for 1) maintaining the list of shortcuts (e.g. using your scraping method) and 2) allowing managing shortcuts (favoriting, hiding, adding new additions)?
- How might we align the data model, since mine includes a Category attribute?

FYI, I previously created an Alfred Workflow called "[Cloud New Documents](https://github.com/chrismessina/alfred-new-cloud-documents)" built around these TLD shortcuts, but my goal this time is to create an extension that parallels some of the functions of the [Easy New File](https://www.raycast.com/koinzhang/easy-new-file) extension but for the cloud docs.

**Comment by natterstefan** [comment]
> Bumping; hoping to work on this this week!

Hi @chrismessina. I'm sorry I got caught up in work. I will get back to you within the next few days. Thanks for everything you've invested so far in preparing and coming up with ideas on how to proceed!

**Comment by natterstefan** [comment]
Hi @chrismessina,

thanks for your kind words. I am also impressed with how you added new features, including categories, aliases, and other services outside of .new's scope to the extension. That makes the extension even more useful.

I am still thinking about how to brainstorm and find a way to harmonize the two approaches and ideas into one together.

What about scheduling a call to share ideas, or do you want to exchange thoughts/plans here in the PR asynchronously?

Btw, sorry again for the delay.

**Comment by natterstefan** [comment]
👋🏻👋🏻

**Pull request closed without merging**
