### PR TITLE
Add Confluence extension

### PR DESCRIPTION
**Pull request by atlas-tbrown**
## Description

Atlassian's Confluence Extension.
- Add `Search` allowing you to search all pages/blogs
- Add `Popular` command to view a list of what's trending
- Add `People` command to search for people
- Add `Go` command to quickly jump to useful places in Confluence
- Add `Recent` command for super snappy access to pages you've viewed 
- Add `Create Page`, `Create Blog`
- Add `Switch Site` command to allow to change connected Confluence site 

We plan to continue developing this adding more features over time!

Note: This is built by a group of Atlassian employees but is not officially endorsed by Atlassian.

## Screencast
confluence-4
confluence-3
confluence-2
confluence-1

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
This is a massive extension @atlas-tbrown 🔥 , @daviddkkim what about letting this superseed yours, would that make sense, or are these two different things?

**Comment by philatlassian** [comment]
Hi @pernielsentikaer - us Atlassian staff are keen to get this released - is there an agreeable limit to how long we wait for a response from @daviddkkim before we can push it forward?

Thanks!

**Comment by daviddkkim** [comment]
Hi @philatlassian, sorry for the wait  
I'm happy for this to take over as it makes sense. Am wondering if there's a way to leave an archival artifact that I jump-started having a confluence plugin for raycast ecosystem though

**Comment by pernielsentikaer** [comment]
That makes sense to add in the README for sure 😊

**Comment by pernielsentikaer** [comment]
@atlas-tbrown do you mind adding this on top of the current extension `confluence-search` - this way it will be an update to the users instead 😊

**Comment by daviddkkim** [comment]
Good w/ yall taking over! Awesome work!

**Comment by atlas-tbrown** [comment]
@pernielsentikaer We'd prefer keeping this separate but did at the shoutout to David in the readme now. Let us know if there's anything else we can address.

@daviddkkim Thank you for your understanding!

**Comment by pernielsentikaer** [comment]
You still need to move it so it's going to replace all @daviddkkim's extension, we don't want to have two extensions 😊

Let me know if you need help 😊

**Comment by yufeikang** [comment]
Hi:

https://github.com/atlas-tbrown/raycast-extensions/pull/2

@atlas-tbrown @pernielsentikaer  I have merged the features of [Confluence Search] extension into this new extension of yours.

**Comment by pernielsentikaer** [comment]
You still need to move it to the `confluence-search` folder 😊

**Comment by yufeikang** [comment]
> You still need to move it to the `confluence-search` folder 😊

Already removed.

**Comment by yufeikang** [comment]
> Where did you move it? Did you push the changes?
> 
> Raycast-ehGv6LvQ@2x

I understand that I can only initiate a pull request to @atlas-tbrown's repo. It will only appear in this pull request after @atlas-tbrown merges it. My pull request ：https://github.com/atlas-tbrown/raycast-extensions/pull/2

**Pull request closed without merging**
