### PR TITLE
New extension: Obsidian Bookmarks

### PR DESCRIPTION
**Pull request by dru89**
## Description

This change adds a new extension for managing your bookmarks with Obsidian. You can save new bookmarks and search your existing bookmarks.

The extension will try to automatically grab the frontmost link from whatever browser you're using (currently supports Chrome and Safari) and then prefill the form with that data for you.

## Screencast

The screencast is hosted on Google Drive, because it's a bit too large for GitHub:
https://drive.google.com/file/d/1IedVMXboC1zx0QY0buVBsqZ55tyeI7kl/view?usp=sharing

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

*Aside:* In the checklist above, should that read that assets used by `README` are placed **inside** the `metadata` folder? As per the instructions on [Provide README if Additional Configuration Required](https://developers.raycast.com/basics/prepare-an-extension-for-store#provide-readme-if-additional-configuration-required)?

> Supporting README media: Put all linked media files in a top-level metadata folder inside your extension directory. (This is different from assets that are required at runtime in your extension: they go inside the assets folder and will be bundled into your extension.)

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Dru89 👋 

I tested your extension and it works as expected, I have some feedback and suggestions for you:

- Maybe add so it's possible in Raycast preferences to give a list of tags that can be used, until the first tag is added in Obsidian it's not possible to use tags.

- Metadata images should be named something like: screenshot1.png, screenshot2.png, screenshot3.png 

- The text `Open Obsidian` confused me while saving a link, had to open the [ActionPanel](https://developers.raycast.com/api-reference/user-interface/actions#api-reference) to get more information and it still feels a bit weird:

image

Maybe it's better to have "Save and Close", "Save and Open in Obsidian", "Save and Copy Link", "Save and Copy Link Markdown" instead?

- If possible, if the path is wrong it could be awesome with an error toast telling about something is wrong.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by Dru89** [comment]
Ok @pernielsentikaer, I've updated with all of the feedback you requested! Each change is in a separate commit if that makes it a little easier to peruse. The "Check to see if Vault exists" one was a bit more complex than I'd originally anticipated since there's a lot of potential ways it could be broken, but otherwise I think all the changes are pretty straightforward.

Gonna reassign this to you now that I've done all those updates. 😄 

Also, I noticed earlier today that this is spiritually similar to @viticci's [Clip Webpage Shortcut](https://club.macstories.net/posts/shortcuts-essentials) Shortcut that he published in Club MacStories. I like the idea of the Shortcut and wanted to keep them compatible with each other, so I updated the names of the keys in the YAML frontmatter that gets written to Obsidian as one final change.

Screenshot of the output from Federico's Shortcut:
Clip Webpage Shortcut

**Review by pernielsentikaer — APPROVED** [review]
Hi @Dru89 👋 

Let's get it merged 🔥

**Comment by Dru89** [comment]
Excellent! Is there anything I need to do to proceed (since I don’t have write permissions)? Otherwise, I’m ready for it to be merged. 👍

**Pull request merged**
