### PR TITLE
Add ohmyzsh-plugins-docs extension

### PR DESCRIPTION
**Pull request by lazarjov**
## Description

Add new extension: Oh My Zsh Plugins Documentation

A [Raycast](https://raycast.com/) extension that lets you browse through plugins documentation for [Oh My Zsh](https://ohmyz.sh/) hosted within the [plugins folder](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins) in this [Oh My Zsh GitHub repository](https://github.com/ohmyzsh/ohmyzsh/).

## Screenshots
oh-my-zsh-plugins-docs-1
oh-my-zsh-plugins-docs-2
oh-my-zsh-plugins-docs-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @lazarjov 👋 

Thanks for your contribution, did you see [this extension](https://www.raycast.com/k8scat/ohmyzsh-plugins) before making yours?

**Comment by lazarjov** [comment]
Hi @pernielsentikaer,

Thanks for getting back to me.

Yes, I saw that extension and I also saw [another one](https://www.raycast.com/yufeikang/oh-my-zsh-git-alias). I decided to submit mine as it takes a different approach from [_Oh My Zsh Plugins_](https://www.raycast.com/k8scat/ohmyzsh-plugins), and in my implementation [_Oh My Zsh Git Alias_](https://www.raycast.com/yufeikang/oh-my-zsh-git-alias) is already included.

I hope it makes sense to add another version of this extension and let users decide.

Thanks,
Lazar

**Comment by pernielsentikaer** [comment]
I'm still a bit confused what's different here 😞

Comparing the current in the store with this one kind of looks almost the same.

Raycast-BWooK6aB@2x

**Comment by lazarjov** [comment]
Hey @pernielsentikaer,

I understand. In that case, let me make a PR with my changes onto the existing extension. The tables which list aliases/functions are not rendered nicely at the moment (for example, see details of the git plugin in the current extension).

Thanks,
Lazar

**Pull request closed without merging**
