### PR TITLE
Add convert-typescript-to-javascript extension

### PR DESCRIPTION
**Pull request by bengry**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

Your commands are a bit confusing. It would be interesting to describe on your README what each one does, and what each one expects. Also, not having anything selected gives me these errors, which are not expected to be so explicit to the user's face. Let me know if I can help you with anything!

CleanShot 2023-06-28 at 14 25 02@2x
CleanShot 2023-06-28 at 14 25 14@2x

**Comment by bengry** [comment]
> Your commands are a bit confusing. It would be interesting to describe on your README what each one does, and what each one expects.

I removed the README file as it didn't give any additional info. If that's required please let me know.
The commands themselves are described in the `package.json`

> Also, not having anything selected gives me these errors, which are not expected to be so explicit to the user's face. Let me know if I can help you with anything!

I've fixed both of these issues. Please let me know if there's anything else.

**Comment by mil3na** [comment]
Hi! Reviewing your changes:

When my clipboard is empty, I get the following error:

https://github.com/raycast/extensions/assets/611002/7dd1314f-d2e8-40e5-9cd7-bf286b6f4804

I think it also doesn't have a target.

I still find your commands a bit confusing. One gets the clipboard, transform it to JS, and pastes it. The other copies the selection, transform it to JS and keeps it on the clipboard. I think this simple detailed explanation would be useful to have on the README, so it sets expectations for the users.

**Comment by bengry** [comment]
> When my clipboard is empty, I get the following error:

Any idea where this errors in Raycast? I'm calling `Clipboard.read()` and also `.catch()`-ing it.
Simulating an empty clipboard is a bit tricky.

> I think it also doesn't have a target.

WDYM? If there's no target can I know that from Raycast's API? I didn't find any mention of this in the docs.

> I still find your commands a bit confusing. One gets the clipboard, transform it to JS, and pastes it. The other copies the selection, transform it to JS and keeps it on the clipboard. I think this simple detailed explanation would be useful to have on the README, so it sets expectations for the users.

Not exactly - 
**Paste as JavaScript** - gets the clipboard content, transforms it to JavaScript, and pastes it.
**Copy as JavaScript** - gets the _selected text_, transforms it to JavaScript, and keeps it in the clipboard.

**Comment by mil3na** [comment]
When I say it has no target, I mean that there was no text input that could be focused to paste the content. To clear your clipboard you can just `pbcopy < /dev/null ` on your terminal.

I don't see a difference between `selected text` and `selection`. Do you mind adding the description to a README file? It doesn't need to have much more.

**Comment by bengry** [comment]
> When I say it has no target, I mean that there was no text input that could be focused to paste the content. To clear your clipboard you can just `pbcopy < /dev/null ` on your terminal.

Good to know. I just tried this and with the latest version I get a HUD with "No text found in clipboard".

> I don't see a difference between `selected text` and `selection`. Do you mind adding the description to a README file? It doesn't need to have much more.

No problem, I'll add it. Just trying to make all the required changes in one revision.

**Comment by bengry** [comment]
@mil3na I just pushed out changes to the names of the commands, as well as added a README.

Can you please check it again and let me know if there's anything else you find that needs fixing? Thanks!

**Comment by mil3na** [comment]
Hey @bengry ! I just downloaded your updates and I got this error when using the copy command:

CleanShot 2023-07-03 at 13 02 22@2x

I had this first piece of code selected: https://snyk.io/advisor/npm-package/typescript/example
This example also triggers the HUD message I told you before.

**Comment by bengry** [comment]
> Hey @bengry ! I just downloaded your updates and I got this error when using the copy command:
> I had this first piece of code selected: [snyk.io/advisor/npm-package/typescript/example](https://snyk.io/advisor/npm-package/typescript/example) This example also triggers the HUD message I told you before.

Good catch! I added better error handling and pushed a new revision.

Thanks

**Review by mil3na — APPROVED** [review]
Looks good to me! Thanks for your effort :)

**Pull request merged**
