### PR TITLE
[Keyboard brightness] Improve user feedback and error handling

### PR DESCRIPTION
**Pull request by DannySeidel**
## Description

- Remove adjust-brightness command as it is replaced by increase-brightness and decrease-brightness commands
- Improve user feedback and error handling by showing the new brightness value when adjusted
- Force displayed brightness to be whole percentage values

## Screencast

keyboard-brightness-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by neo773** [comment]
On second thoughts could you change the screenshot to this?
Raycast 2024-04-12 at 13 48 54

**Comment by pernielsentikaer** [comment]
There is actually no reason to add a screenshot anymore since it's only no-view commands. You can still have an image in the README if you'd like.

This is taken from the manual:
> Select the most informative commands to showcase what your extension does – focus on giving the user as much detail as possible

**Comment by DannySeidel** [comment]
Hey @neo773,

sure I change it if you want. Or do you prefer to don't have a screenshot as @pernielsentikaer suggested?

**Comment by neo773** [comment]
@DannySeidel 
Let's keep it, store preview looks weird with no screenshot in my opinion.

**Comment by DannySeidel** [comment]
I agree no screenshot looks weird 👍🏻
I updated the screenshot

**Comment by neo773** [comment]
@DannySeidel 
Thank you for your contribution I appreciate it!

Can we get this merged now? @pernielsentikaer

**Comment by pernielsentikaer** [comment]
@DannySeidel do you want to have your Raycast handle added to the package.json?

**Comment by DannySeidel** [comment]
Sorry forgot that, I will add it

**Comment by DannySeidel** [comment]
Done! @pernielsentikaer thanks for reminding me 🙏🏻

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
