### PR TITLE
Add search-shopify-liquid-documentation extension

### PR DESCRIPTION
**Pull request by maximedaraize**
## Description

Search Shopify's Liquid Documentation Directly Raycast.

The four main categories of the liquid documentation include:
- Basic
- Operators
- Filters
- Objects

Here is the [Shopify's liquid doc](https://shopify.dev/docs/api/liquid/basics) as refernce.
## Screencast
display the list of Shopify's liquid documentation

display filtering the list when typing

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

How is this compared with [this extension ](https://www.raycast.com/sandypockets/shopify-developer-changelog) by @sandypockets?

**Comment by maximedaraize** [comment]
> Hi 👋
> 
> How is this compared with [this extension ](https://www.raycast.com/sandypockets/shopify-developer-changelog) by @sandypockets?

Hi @pernielsentikaer 👋🏻 

@sandypockets [extension ](https://www.raycast.com/sandypockets/shopify-developer-changelog)reference the Shopify's changelog (newest api's, releases, etc). _I have it installed, pretty good way to know about latest changes_ 😉

The extension I am submitting reference the pages of the [official liquid documentation of Shopify](https://shopify.dev/docs/api/liquid/basics). It gives you a quick access to go to the docs directly from Raycast.

Both extension are related to Shopify, but do not provide the same information. I hope this clarify the difference between both.

**Comment by pernielsentikaer** [comment]
Would it make sense to merge them into one Shopify extension instead of having two?

**Comment by maximedaraize** [comment]
> Would it make sense to merge them into one Shopify extension instead of having two?

I like the idea of having different extension with different purposes. Also, what I appreciate about having separate extensions is being responsible for its maintenance. 

If I understand correctly, by forking an existing extension and contributing to it, the original author would need to accept the changes and any future changes related to bug fixes and/or new add-on? 

But if we were to merge them into one, I should follow this [Contribute to an Extension](https://developers.raycast.com/basics/contribute-to-an-extension) guide?

**Comment by maximedaraize** [comment]
Hi @pernielsentikaer please let know what should be the next step. I would highly appreciate your feedbacks. 

Thank you

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
