### PR TITLE
Audio device extension tweaks

### PR DESCRIPTION
**Pull request by mike182uk**
## Description

Just a couple of tweaks to the `audio-device` extension:

- Made it so the `Set Output Device to Favourite` command shows a subtitle like all of the other commands and make it a `no-view` command seeming though it doesn't need a UI
- Added an extra action to the lists that lets you copy the name of the device - This is useful for setting the preference for your favourite output device (as this requires the exact name of the device)
- Update a couple of the strings throughout the extension to make them consistent with each other
- Minor refactoring to clean up some stuff

## Screencast

Screenshot 2022-03-10 at 20 50 59
Screenshot 2022-03-10 at 20 58 59

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

### CODE REVIEW

**Comment by mike182uk** [comment]
Hm, it looks like the linter has never been used on this extension. I can run it and fix the issues but its likely to bulk out the PR?

**Review by FezVrasta — APPROVED** [review]

**Comment by mathieudutour** [comment]
Hum weird - but yes, can you run the linter please?

**Comment by mike182uk** [comment]
@mathieudutour Thats fixed up now 👍

**Review by mathieudutour — APPROVED** [review]
Looks good :+1:

**Pull request merged**
