### PR TITLE
Update promptify extension

### PR DESCRIPTION
**Pull request by Ph-lo**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

We already have a lot of [openAI](https://www.raycast.com/search?q=openAI)/[ChatGPT](https://www.raycast.com/search?q=chatgpt) extensions, did you try them out before making this? Looks like it's something we already supports 😊

**Comment by Ph-lo** [comment]
Hi 👋,

I bet you do! I did not find one that allowed access to different models of openAI from the same panel so I made one. Did not particularly want to publish it on the store as I only wanted a more efficient extension for myself.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pernielsentikaer** [comment]
I think that should be doable in [ChatGPT](https://www.raycast.com/abielzulio/chatgpt) by @abielzulio

**Comment by Ph-lo** [comment]
Sweet ! I’ll make sure to check it out cheers ! Also gonna check out the AI boosted Raycast, love your tools guys !

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
