### PR TITLE
Publishing Greip to Raycast store.

### PR DESCRIPTION
**Pull request by gre-dev**
## Description

Greip helps you get the full information about your IP Address, your country or even detecting bad-words in a specific text.

## Screencast

greip-1
greip-2
greip-3
greip-4
greip-5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @gre-dev 👋 

I made some improvements, do you mind checking them out that I didn't break something 😊

**Comment by gre-dev** [comment]
> Thanks for the check @gre-dev; I forgot to add the dependency - should be better now 🧑‍🚒

Works well now, thanks.
You can merge it ✨

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by gre-dev — COMMENTED** [review]
Reviewed.

**Pull request merged**
