### PR TITLE
[New Extension] MDN Docs

### PR DESCRIPTION
**Pull request by bobbymannino**
## Description

Search the MDN docs from your keyboard. Next feature is saving recent searches, more to come after too!

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
How is this different than [this one](https://www.raycast.com/krzysztofzuraw/search-mdn)?

**Comment by bobbymannino** [comment]
Same as but quicker speeds

**Comment by pernielsentikaer** [comment]
Would be more nice to enhance the current version, what do you think here @krzysztofzuraw

**Comment by krzysztofzuraw** [comment]
Yes - it will be awesome 🎉

**Comment by bobbymannino** [comment]
not sure how to contribute to an existing one, I have looked on your docs but there's no option to 'fork'

**Comment by pernielsentikaer** [comment]
There are two options as I see it:

1.  This supersedes the current and brings features that are not included in this
2. Change the current version directly from this repo instead

What do you both think?

**Comment by krzysztofzuraw** [comment]
I'm open for both but it seems like 2) don't require any work from end users and avoid confusion with two extensions doing the same.

**Comment by pernielsentikaer** [comment]
2) would just be an update that all users that have the current version installed get without any interference 😊

**Pull request closed without merging**
