### PR TITLE
feat: add Azure OpenAI Chat

### PR DESCRIPTION
**Pull request by Fatpandac**
## Description

An OpenAI client that supports OpenAI and **Azure OpenAI** and offers additional, powerful functionalities. 

## Screencast

image

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by sxn** [comment]
hey @Fatpandac, thanks for the PR! There are already a couple of OpenAI extensions in the store:
- https://www.raycast.com/simicvm/openai-gpt
- https://www.raycast.com/douo/openai-translator
- https://www.raycast.com/josephschmitt/ai-gen
- https://www.raycast.com/abielzulio/chatgpt
- …etc

This looks like the only extension offering Azure AI integration. What do you think about focusing on making this an Azure AI-specific extension? Also, if this PR includes OpenAI integrations with superior features compared to other extensions, perhaps you might consider enriching those other extensions with your improvements?

**Comment by Fatpandac** [comment]
@sxn OK, I'll change it soon.

**Comment by sxn** [comment]
hi @Fatpandac – thanks for the changes :D generally it looks good. I don't have access to an Azure Open AI deployment, so most of what I've been able to test is how the extension works with wrong credentials, and whether whatever errors occur are being handled:
- `endpoint` is expected to be a URL, but if it's not, the extension crashes
- passing a wrong `endpoint` (e.g. `https://google.com`) also crashes the extension
- setting `endpoint` to `https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/completions?api-version=2023-05-1` also crashes the extension
- setting `endpoint` to `https://test.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/completions?api-version=2023-05-1` doesn't crash the extension, but appears to load infinitely 😅

Mind improving the error handling to address cases where the request fails (for whatever reason)?

https://github.com/raycast/extensions/assets/1155589/7612b138-4015-4334-9f88-7e00593593b5

https://github.com/raycast/extensions/assets/1155589/7b233615-42ae-4b60-a302-9ef775c5e722

https://github.com/raycast/extensions/assets/1155589/368b4174-be8e-4745-83b5-32a1ed67bd49

https://github.com/raycast/extensions/assets/1155589/1d15b3f4-c696-41d3-a5aa-3a0db2766e75

**Comment by Jackiexiao** [comment]
looks like we already support azure api in chatgpt extension
image

**Comment by Fatpandac** [comment]
Thank you for your comment. I will close this PR. @Jackiexiao

**Pull request closed without merging**
