### PR TITLE
Added optional grid view to the YouTube extension

### PR DESCRIPTION
**Pull request by yug2005**
## Description

* Added optional grid view for the extension. 
* Also addressed title bugs by decoding the HTML video and channel titles.
* For example, titles contained `&amp;` in place of just `&`. 

## Screencast

Metadata
Metadata-2
Metadata-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Can you give it a whirl @tonka3000 😄

**Comment by tonka3000** [comment]
@yug2005 Really like the chance 👏. Code is great. The only thing which seems now to be added is empty state flickering when searching for videos (Only happens in `Search Videos`).

https://user-images.githubusercontent.com/3163807/174538644-c2c43a85-6a89-45ac-9175-4cb1c0e8fe1c.mp4

Can you check this please?

**Comment by pernielsentikaer** [comment]
Thanks for the fix @yug2005, can you verify @tonka3000

**Comment by tonka3000** [comment]
@pernielsentikaer Works now.

**Comment by pernielsentikaer** [comment]
Thanks for the correction, could you @yug2005 ad a few screenshots if possible, if not, just tell me 😄

**Comment by yug2005** [comment]
@pernielsentikaer I have added a few screenshots to the README.md. However, currently there is a bug with this PR. When the view switches from List to Grid, the search bar text is cleared. When this happens the view flips back to the recently searched list. To account for this, I added a guard with the following code : 

```
searchText={searchText}
onSearchTextChange={(search: string) => {
    if (layout === "list" || search) appendRecentSearches(search);
}}
```

However, there are now two issues with the search bar. 

* When the search bar text becomes empty after a search, the view does not go back to the recently searched list. 
* When the user types really fast, and `searchText` has not updated, the search bar text reverts back to previous state. 

https://user-images.githubusercontent.com/77864399/174620032-f904e9e1-0148-4c04-8652-fc699819c05f.mov

**Comment by yug2005** [comment]
Hey guys, instead of recently search list, I have added a recent videos and channels section. Also you can pin videos and channels. Also added the option to hide/show recent videos/channels. Check it out!

**Comment by yug2005** [comment]
Metadata-4
Metadata-5
Metadata-6

**Comment by yug2005** [comment]
@pernielsentikaer @tonka3000

**Review by tonka3000 — COMMENTED** [review]
- This title size preference is not respected when showing the list of videos of a channel (`Search Channel` -> Open a Channel -> Trigger `Show Recent Channel Videos`)

**Comment by yug2005** [comment]
@tonka3000 @pernielsentikaer ready to merge?

**Comment by tonka3000** [comment]
@yug2005 Works nice. I found little thing. When I remove a pinned channel, the does not refresh (only toast message). Would be great when the refresh would happen after unpinning

**Comment by yug2005** [comment]
Hello, I haven't been able to reproduce the error. When does it not work for you?

https://user-images.githubusercontent.com/77864399/177047300-ee54222f-493c-49f8-a250-115c7eef924a.mov

**Review by tonka3000 — APPROVED** [review]
@yug2005 I tried it again and now it works. Not quite sure how to produce it. But now it works fine 👍

**Pull request merged**
