### PR TITLE
feat(google-chrome-profiles): support quicklinks

### LINKED ISSUE #7683: [Google Chrome Profiles] Add quick link for each profile
### Extension

https://github.com/raycast/extensions/tree/main/extensions/google-chrome-profiles

### Description

As a Raycast user I want to get quick access of each Chrome profile such as [work - personal ....]

### Who will benefit from this feature?

Any one using multi profiles

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by erics118**
## Description

support creating quicklinks to opena a selected profile

also update deps and config files

Fixes #7683

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @erics118 👋 

Could you look into the CI errors reported?

@frouo could you review this?

**Comment by frouo** [comment]
I am currently reviewing

**Comment by frouo** [comment]
@erics118 could you please give me the ability push on your repo? I would like to push these changes if it's ok for you:

_If it's easier, you can apply theses changes and push them, no problem for me._

image

**Comment by pernielsentikaer** [comment]
Did you resolve the errors you had in the editor @frouo?

@erics118 could you check this

**Comment by erics118** [comment]
@pernielsentikaer Could you take a look at the API errors? I have no clue why they are there

**Comment by frouo** [comment]
LGTM
Thank you @erics118

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
