### PR TITLE
Support Luxon formatting tokens in templates (yyyy, MM, dd)

### PR DESCRIPTION
**Pull request by FServais**
## Description

Related to issue https://github.com/raycast/extensions/issues/10426.

This PR adds the support of date and time formats as defined by [Luxon](https://moment.github.io/luxon/#/formatting?id=table-of-tokens).

As such, this change refactos the way templating is done:
- Replace `replaceAll` functions by `.replace(regex, matchFun)`.
- `regex` will check all text within `{` and `}`.
- The match function will return the same return values for keywords already supported (`day`, `year`, `timestamp`,...).
- If `regex` matches format from Luxon (`dd`, `MM`,...), it will defer the call to `dateTime.toFormat(key);`.
 
## Screencast

Screenshot 2024-01-29 at 23 56 39

Screenshot 2024-01-29 at 23 57 05

Screenshot 2024-01-30 at 16 03 56

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
I think they all need to run after `{content}` is processed so that one needs to be broken out. 

Was it not possible to just add another replaceAll with a regex after content (or at the end) that just runs format? Maybe like: 


```js
  return preprocessed
    .replaceAll("{content}", content)
    .replaceAll(/{(.*?)}/g, (_, c) => dateTime.toFormat(c))
    // rest
```

**Comment by FServais** [comment]
Oh sure, I didn't get `{content}` could be broken out. I'll add it.

Regarding `replaceAll`, I am unsure about `replace` vs `replaceAll` while using a regex. From what I got, they are similar in this case.

Regarding all the different `case`, I wanted to have a safeguard before hitting `dateTime.toFormat(c)`, as to be able to control what we give to `luxon`, and also such that anything not matching will be kept. For instance, I think using `{mytasks}` should be left intact and not sent to `toFormat`.

With those reasons, I thought we could refacto altogether to not to keep a mix of `.replaceAll({...})` and `case`, might as well all put in the `switch` for coherence.

Let me know what you think, I can adapt this of course.

**Comment by KevinBatdorf** [comment]
Just might be easier to maintain if it's a one liner. Could put it at the end I guess? What happens if it captures an unsupported value like {foo}? Does it throw or just move on?

But outside of {content}, what you have now is fine too. I'm not sure those values ever change anyway. It's your call.

**Comment by FServais** [comment]
> What happens if it captures an unsupported value like {foo}? Does it throw or just move on?

From the few tests, it parses it in unexpected ways, but does not throw an error. My thought of the expectation was that if a user wants to uses any text in `{...}` that is not defined in the documentation (extension + luxon), then it should not be parsed. 

I agree with maintaining, although I anticipate that should be really rare. 

I'll keep that switch as it is for this commit, but let me know if you still think the use case above is not relevant. 👍

**Comment by KevinBatdorf** [comment]
> My thought of the expectation was that if a user wants to uses any text in {...} that is not defined in the documentation (extension + luxon), then it should not be parsed.

Yeah if it encountered {foo} I was assuming it would just ignore it. I guess it breaks it apart and matches characters within it. 

> I'll keep that switch as it is for this commit

Sounds good.

**Comment by pernielsentikaer** [comment]
Is this ready for review before shipping, or do we still await something?

**Review by pernielsentikaer — APPROVED** [review]
🟢 Approved

**Comment by j-peeters** [comment]
Thanks for implementing my request @FServais and to the others for their critical eye!

**Pull request merged**
