### PR TITLE
Update mute-microphone extension

### PR DESCRIPTION
**Pull request by iamyeizi**
#### Feature (issue #8832, commit 198de72)
- I have added a new preference in the Menu Bar command section to respond to the issue and have tried to keep the two options so that the user has a choice.
- I have also added a background refresh interval in case Raycast is shutdown for some reason and an item to open the command settings from the menu bar icon (Settings...).

---
#### Refactor (issue #9750, #9808, commit 0875e3a)
If you agree, you can accept this refactoring to fix the main function of the extension or try to fix the swift code, I haven't touched that language enough to fix it.
- Switched to AppleScript.

---

## Screencast

https://github.com/raycast/extensions/assets/37552350/764be745-ab65-41c8-a557-19635cbcb889

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution 🔥 

@quentin23soleil do you want to check this?

**Comment by pernielsentikaer** [comment]
Pinging a last time @quentin23soleil 🙂

**Comment by quentin23soleil** [comment]
I'm happy with the changes 🙂

**Comment by pernielsentikaer** [comment]
Awesome, thanks 🤗

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by iamyeizi** [comment]
The swift code sets the microphone volume to 0.0 but still could recognise the sound, with what I know of swift I have not been able to solve it, any problem will apply a revert and try to solve it.

**Pull request merged**
