### PR TITLE
Rename AT Protocol Lexicon Search to AT Protocol Utilities

### PR DESCRIPTION
**Pull request by futurGH**
## Description

Renamed the AT Protocol Lexicon Search extension to AT Protocol Utilities and added a new "Resolve Handle/DID" command that resolves AT Protocol user handles to and from [Decentralized Identifiers](https://www.w3.org/TR/did-core/).

## Screencast

https://github.com/user-attachments/assets/016595cd-bdea-4a1b-8a7a-049670f35b28

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by futurGH** [comment]
Hey @pernielsentikaer, just checking if there's anything I need to do to get this merged?

**Comment by pernielsentikaer** [comment]
I'll check this now 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by grzegorzkrukowski** [comment]
We had to force-push to your main branch to fix the problem of random files being removed.

**Pull request merged**
