### PR TITLE
Add url-unshortener extension

### PR DESCRIPTION
**Pull request by sebdanielsson**
## Description

[See readme.](https://github.com/raycast/extensions/blob/ea932a2334f9fabb0792116e1f046a987491f71e/extensions/url-unshortener/README.md)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Maybe it could be cool to use `accessories` to set the redirect type, something like this

url-unshortener 2023-11-28 at 08 37 56

- Maybe try to add `throttle` to the `list` to ensure it doesn't search on every keystroke

- Fetching favicons is most of the time showing a globe, do you know why?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by sebdanielsson** [comment]
@pernielsentikaer awesome idea about the accessories. Cleaned up the UI a bit, hope you like it. I also added throttle to the list.

Not sure why you see the globe so often, it's only supposed to show up if there is no favicon for that domain. Do you have some example links I can look into?

**Comment by sebdanielsson** [comment]
Just found some bugs. I'll get back when I've fixed them.

**Comment by sebdanielsson** [comment]
Nice addition of colors btw!🤩

Short summary of the latest changes:

- Updated fetchFavicons to fetch favicons when typing in a URL manually in the search bar.
- Stricter URL validation
- If text selection or clipboard doesn't match a valid url (dr.dk), try to add https:// before it and retry in the same order.
- Improved error handling for queries that are a valid url but can't resolve. For example: dr.dkk

**Comment by pernielsentikaer** [comment]
Do you know why https://raycast.com doesn't end up with a 200?

url-unshortener 2023-11-29 at 10 24 45

Doing the same from a terminal seems to catch it
```
❯ wget https://raycast.com 2>&1 | grep Location:
Location: https://www.raycast.com/ [following]
```

Seems like favicon is found for the first element but not for the second, is that because of looking up with www too and it fails?

url-unshortener 2023-11-29 at 10 25 57

url-unshortener 2023-11-29 at 10 28 08

However, if I select bt.dk from a input field it seems to work better

url-unshortener 2023-11-29 at 10 28 51

**Comment by sebdanielsson** [comment]
@pernielsentikaer I will look up why the favicon doesn't work consistently.

I just ran `curl` on `https://raycast.com` and received a `308` response, so it appears that is how Vercel has configured their proxy.

```sh
curl -I https://raycast.com
HTTP/2 308
cache-control: public, max-age=0, must-revalidate
content-type: text/plain
date: Wed, 29 Nov 2023 15:06:57 GMT
location: https://www.raycast.com/
refresh: 0;url=https://www.raycast.com/
server: Vercel
strict-transport-security: max-age=63072000
x-vercel-id: arn1::6dr8m-1701270417089-401484437296
```

**Comment by sebdanielsson** [comment]
Okay, so here is some of the changes made:

* Handle all types of 3xx redirects
* Rework favicon fetching to fix missing favicons
* Favicon is now using the same data structure as the redirectionSteps
* Show icons in accessory for more http status codes
* Show error messages in a list item instead of a toast for improved visibility

**Comment by pernielsentikaer** [comment]
Wow what a nice update again 🔥 It works much better! Would it be possible to support bt.dk without https:// in interactive view, or doesn't that make sense?

**Comment by pernielsentikaer** [comment]
Could you give it another spin to check that I didn't break anything

**Comment by sebdanielsson** [comment]
Thanks! It's working great on my end. One question since I'm still learning. What is props.fallback for?

**Comment by pernielsentikaer** [comment]
It's when you add the command as a fallback command, check this video 🙂

https://github.com/raycast/extensions/assets/38033107/2debba09-c696-43e5-a8ee-3f73dfa99665

Do you think we have anything outstanding still?

**Comment by sebdanielsson** [comment]
Got it! No I'm happy with it if you are😃

**Pull request merged**
