### PR TITLE
feat: optimize the display of translation result interface

### PR DESCRIPTION
**Pull request by tisfeng**
## Description

1. optimize the display of translation result interface
2. reduce translation delay interval, from 900 to 400

### before
image

### now
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tisfeng** [comment]
Because the translation result display interface is optimized, the screenshot under metadata also needs to be updated, but I can't make the cover screenshot according to the guide. Can anyone help?

image

**Comment by pernielsentikaer** [comment]
I can help you out @tisfeng when @Haojen has approved it 😄

**Comment by tisfeng** [comment]
> 

thanks !

**Comment by Haojen** [comment]
@tisfeng Thank you PR, but reducing the delay timer is not a good idea, this delay timer 900 is this API Limit,  about this issue I have a better fix the resolution, I think today I can submit a PR.  and about this circle dot look like better but I think the red and yellow color is Warning color,  thank you UI idea, I'll make some improvements based on your ideas and post them. @pernielsentikaer

**Comment by Haojen** [comment]
> > @tisfeng Thank you PR, but reducing the delay timer is not a good idea, this delay timer 900 is this API Limit, about this issue I have a better fix the resolution, I think today I can submit a PR. and about this circle dot look like better but I think the red and yellow color is Warning color, thank you UI idea, I'll make some improvements based on your ideas and post them. @pernielsentikaer
> 
> Ok, it's best if you have a better solution. I made some simple tests to reduce the time delay to 400, It seems that there is no problem, so I submitted it, that I didn't consider it carefully. Thank you for reviewing the code.

And your UI looks better, but I next version maybe adds a new feature, the feature maybe will with this UI conflict, so I need more time to adjust both, not only change the color.

**Comment by pernielsentikaer** [comment]
Closing in favor of #1678

**Comment by tisfeng** [comment]
> > > @tisfeng Thank you PR, but reducing the delay timer is not a good idea, this delay timer 900 is this API Limit, about this issue I have a better fix the resolution, I think today I can submit a PR. and about this circle dot look like better but I think the red and yellow color is Warning color, thank you UI idea, I'll make some improvements based on your ideas and post them. @pernielsentikaer
> > 
> > 
> > Ok, it's best if you have a better solution. I made some simple tests to reduce the time delay to 400, It seems that there is no problem, so I submitted it, that I didn't consider it carefully. Thank you for reviewing the code.
> 
> And your UI looks better, but I next version maybe adds a new feature, the feature maybe will with this UI conflict, so I need more time to adjust both, not only change the color.

That sounds good, I'm looking forward to the new UI.

**Pull request closed without merging**
