### PR TITLE
New Extension: Websocket Debugging

### PR DESCRIPTION
**Pull request by RhysLees**
## Description

Allows you to debug web sockets (currently Pusher) inside Raycast.

The connection will stay alive as long as the command is open or until Raycast Pops to root search.

You can change between channels and listen to all events on that channel
You can also copy the data from the received web socket to clipboard

The logged events are not stored, only the selected channel so exiting the extension command will clear the logged events.

## Screencast

https://user-images.githubusercontent.com/43909932/211420391-98f524e6-214e-4f60-99f3-f1ff74f6ba78.mov

websocket-debugging-1
websocket-debugging-2
websocket-debugging-3
websocket-debugging-4
websocket-debugging-5
websocket-debugging-6

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* There is no validation of the `Create Event` form; maybe you should look at [useForm](https://developers.raycast.com/utilities/react-hooks/useform?q=useForm)

* After sending the first event, I cannot click on `Create Event` again; nothing happens.

* When loading the extension with fake preferences, I still get a success toast, is that as expected?

Raycast-aDHvJ7RV@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by RhysLees** [comment]
@pernielsentikaer In regards to 
>There is no validation of the Create Event form; maybe you should look at [useForm](https://developers.raycast.com/utilities/react-hooks/useform?q=useForm)

I have updated both forms to use `useForm`

> After sending the first event, I cannot click on Create Event again; nothing happens.

This would be due to the connection failing as the keys you entered are fake. After research there is not really a way to handle this well and there are no api endpoints to 'validate' the keys.

> When loading the extension with fake preferences, I still get a success toast, is that as expected?

This again relates to the above mentioned. there is not a way to check the keys so pusher throws an error. tried to catch this but the error is never caught.

**Comment by pernielsentikaer** [comment]
Checking again today @RhysLees, the notification got lost 😊

**Comment by RhysLees** [comment]
> Checking again today @RhysLees, the notification got lost 😊

No worries 😄

**Comment by RhysLees** [comment]
@pernielsentikaer Any updates?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Comment by RhysLees** [comment]
> Hi 👋
> 
> Looks good to me, approved 🔥
> 

Thank you !!!!

**Pull request merged**
