### PR TITLE
GitLab: add create mr action for issues

### PR DESCRIPTION
**Pull request by khasbilegt**
## Description

This change adds an **Create MR** action in the issue list that creates a new branch first, then, a merge request to the default branch of the project. If there's already a branch with same name exists, it will show a toast. In order to make the newly created merge request visible in the **My Merge Requests** list, the user is added as an assignee.

Works just like the _create merge request_ button on **GitLab**.

image

## Type of change

- Bug fix / improvement for somebody else's extension

## Screencast

image

image

## Checklist

- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I read the [extension guidelines](https://developers.raycast.com/information/review-process#guidelines)
- [ ] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by tonka3000** [comment]
Hi @khasbilegt ,

thanks for the PR. The action works great, like the idea 👏 . There are some thing which are different to the GitLab website feature which would be more familiar for GitLab users which already use the website version.

1. In my case, the MR title will be `Draft: Resolve: <title>`.  I would add `Draft: ` as a prefix, because it is an empty branch.
2. The description text should be `Closes #1234`, so that the MR is connected to the issue (same as in the website version)
3. This point is optional and maybe something for another PR later
    GitLab have this nice dialog where you can adjust the branch name and the source branch, which should be doable in Raycast via PushAction and a form. I've already impl. that when you display the branches of a project where you can create a [merge request via an action](https://github.com/raycast/extensions/blob/d4f55bcde0e6c1fbdb34d8852d27c99c4c62595d/extensions/gitlab/src/components/branch_actions.tsx#L10). What do you think about that?
    CleanShot 2021-10-19 at 19 56 20@2x


## GitLab website version
CleanShot 2021-10-19 at 19 51 00@2x

## Your action
CleanShot 2021-10-19 at 19 54 42@2x

**Comment by tonka3000** [comment]
> Just now I realized that I could add a code that creates a separate form component that lets the user modify the branch name (also will have a default branch name) and create the branch, MR at the submission. Is this how you wanna achieve the flow like GitLab website dialog?

Yes, exactly this flow would be nice. I personally often don't use the default branch name. So I would be nice when it would fill-out the form with defaults and the user can adjust it.

Can you also rename the action to `Create Merge Request`, just to be consistent with the other actions.
CleanShot 2021-10-20 at 08 39 03@2x

Thanks in advance

**Comment by khasbilegt** [comment]
@tonka3000, now it should be good.

**Comment by tonka3000** [comment]
@khasbilegt looks great.

@PitNikola ready to merge from my side

**Pull request merged**
