### PR TITLE
Add music-timer extension

### PR DESCRIPTION
**Pull request by JulienLacr0ix**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @JulienLacr0ix 🔥 

Could you look into the CI errors? Let me know if you need help with it 🙂

**Comment by JulienLacr0ix** [comment]
> Hi @JulienLacr0ix 🔥
> 
> Could you look into the CI errors? Let me know if you need help with it 🙂

I gonna check that! Thx!

**Comment by pernielsentikaer** [comment]
Awesome, let me know if you need any help resolving them

**Comment by JulienLacr0ix** [comment]
> Awesome, let me know if you need any help resolving them

To relaunch the CI, Can I do this command `npm run publish`? Will it keep this PR?

**Comment by pernielsentikaer** [comment]
> > Awesome, let me know if you need any help resolving them
> 
> To relaunch the CI, Can I do this command `npm run publish`? Will it keep this PR?

It should, yes 🙂

**Comment by JulienLacr0ix** [comment]
Here we go! 😊

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- You should maybe add a check when Music Timer is not installed, you can check how extensions like [Eagle](https://www.raycast.com/Yukai/eagle) are checking for it

music-timer 2023-08-02 at 15 40 07

- You should be able to use `npx @raycast/api@latest pull-contributions` to get the latest update 🙂

- Add [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by JulienLacr0ix** [comment]
I think we are good @pernielsentikaer 😊

**Comment by JulienLacr0ix** [comment]
Did I miss something or we can merge this PR @pernielsentikaer?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
