### PR TITLE
Update iconify extension

### PR DESCRIPTION
**Pull request by eevaery**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Pinging you one last time @Destiner :)

**Review by yveeven — COMMENTED** [review]
ok

**Comment by pernielsentikaer** [comment]
I reviewed the extension based on your informations regarding the missing `<Grid>` view, and I had a local version of the extension installed. I checked the store version and it has a fine `<Grid>` view. This was the main reason for a change for me.

iconify 2024-02-01 at 09 46 54

I checked the speed too, and it's loading pretty quickly here. Also, remember that things are cached, so loading it again should be pretty fast.

Based on the above, I don't see a reason to supersede, but you're still free to enhance the current. The author will, however, remain Destiner, and you'll be a contributor.

Feel free to DM in our Slack community or on Twitter to discuss further.

**Comment by yveeven** [comment]
Then I have no problem to close this merge, the view may be that I didn't notice the latest changes, the speed may be due to geography

**Comment by pernielsentikaer** [comment]
Closing as requested - let's monitor what's happening

**Pull request closed without merging**
