### PR TITLE
[Search npm Packages] Add shortcut to "npm Package Page" open in browser action

### PR DESCRIPTION
**Pull request by jomifepe**
## Description

Since the "open npm Package Page" is not the main action, I believe it should at least have a shortcut for quicker access. 

What do you think? 

## Screencast

Screenshot 2023-08-19 at 14 46 24

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by luisFilipePT — COMMENTED** [review]
Nice 😀, I think it makes sense, just a few notes

- I would rename the action to `Open Npm Package Page` so that it follows the convention of the other options that have the same action, open some page

- Don't forget to update the `changelog`

- It would also be cool to update the image of that menu displayed in the store to show the shortcut and be more up to date

- Maybe move that action above the `Open Changelog` for 2 reasons:
-- It seems to be to have a higher importance
-- That way all actions with shortcuts stay together so visually I think it looks better 

☝🏼 just my opinion let me know what you think

cc: @mrmartineau

**Comment by jomifepe** [comment]
> Nice 😀, I think it makes sense, just a few notes
> 
> * I would rename the action to `Open Npm Package Page` so that it follows the convention of the other options that have the same action, open some page
> * Don't forget to update the `changelog`
> * It would also be cool to update the image of that menu displayed in the store to show the shortcut and be more up to date
> * Maybe move that action above the `Open Changelog` for 2 reasons:
>   -- It seems to be to have a higher importance
>   -- That way all actions with shortcuts stay together so visually I think it looks better
> 
> ☝🏼 just my opinion let me know what you think
> 
> cc: @mrmartineau

Fine for me, updated. The latter should be done by someone else, just for consistency, as my raycast & wallpaper will produce a different-looking screenshot.

**Review by luisFilipePT — APPROVED** [review]
Good Job 🏅, looks good

I would still prefer to have the screenshots updated but it's a no blocker 😅 (even if with a different wallpaper / theme)

**Comment by pernielsentikaer** [comment]
Hi @jomifepe 👋 

You can use the [metadata image tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) to make new images, this way all references to development is hidden and the images looks so much better 🙂

Do you mind checking this PR too @mrmartineau

**Comment by jomifepe** [comment]
I updated the image to look similar to the other ones.

@mrmartineau did you have a chance to take a look? Should be quick, only a few changes 🙂

**Review by mrmartineau — APPROVED** [review]
Looks good to me. Thanks for the update

**Comment by pernielsentikaer** [comment]
Hi again 👋

I just updated all the metadata images with Rayfie and making them look like each other 🙂

**Pull request merged**
