### PR TITLE
[Zotero] Update Zotero extension to use local sqlite database

### PR DESCRIPTION
**Pull request by sadanand-singh**
## Description

This update simplifies the Zotero extension so that search is performed based on the local sqlite database, instead of the web API. This enables use of this extension with minimal setup and even behind proxies.

## Screencast
menu

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by sadanand-singh** [comment]
Any updates from the raycast team? Can someone please help me merge this? @pernielsentikaer I think you had reviewed the PR related to this extension last time.

**Comment by pernielsentikaer** [comment]
Hi @sadanand-singh 👋 

Sorry for the long response on this one 💯 

Could you rename the folder images to media instead (and update the README)

- I'll give it a spin later today 💪

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @sadanand-singh 👋 

I just gave it a quick spin, it seems like I can't figure out what's going wrong in the test? Nothing shows up in the SQLite database or in the extension? Maybe I'm doing something wrong 😄 

CleanShot 2022-05-16 at 14 45 49@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pernielsentikaer** [comment]
It seems to be working as expected now. In the next version, it could be cool with a custom [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) that shows both type to search before searching and no results after 😄

**Pull request merged**
