### PR TITLE
Update quit-applications extension

### PR DESCRIPTION
**Pull request by codesjedi**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Works as expected for me 🔥 Maybe we should consider a preference to poptoroot/clear search bar after quit? What do you think @codesjedi 

@mackopes do you want to give it a go too?

**Comment by codesjedi** [comment]
Hey @pernielsentikaer, thanks for the suggestion. I've added it and updated the changelog.md file accordingly. 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by codesjedi** [comment]
Nice! 👩🏼‍🚒

**Pull request merged**
