### PR TITLE
Update imessage-2fa extension

### PR DESCRIPTION
**Pull request by navtoj**
## Description

Add option to ignore messages that have been read

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @navtoj 🔥 Do you mind adding a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry too?

@yuercl do you mind checking this

**Comment by navtoj** [comment]
> Thanks for your contribution @navtoj 🔥 Do you mind adding a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry too?
> 
> @yuercl do you mind checking this

@pernielsentikaer I've added the update entry in the changelog

**Comment by navtoj** [comment]
@pernielsentikaer @yuercl Can this be merged?

**Review by yuercl — APPROVED** [review]
Thanks for you commit

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
