### PR TITLE
Simple youdao translate v1

### PR DESCRIPTION
**Pull request by xeric**
## Description

A new extension for simple youdao translation which has more quicker interaction of usage.

## Screencast
[See in README.md](https://github.com/raycast/extensions/blob/f731f8a5a467812748cbb75896c8abc79766665e/extensions/simple-youdao/README.md)

## Checklist

- [ √] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ √] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ √] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by xeric** [comment]
Do not understand the error in CLI:

🕐 wait  - run ESLint
💥 error - run ESLint
sh: 1: eslint: not found
Error: sh: 1: eslint: not found
Error: Process completed with exit code 1.

Did not make any change in eslint check or cli tool.

**Comment by xeric** [comment]
Could anyone provide some help why I always get 'eslint not found' error?
I tried to check eslint in local, compared the eslint files content with other repo, all of them are fine, but still get in build:

🕐 wait  - validate extension icons
✅ ready - validate extension icons
🕐 wait  - run ESLint
💥 error - run ESLint
sh: 1: eslint: not found
Error: sh: 1: eslint: not found
Error: Process completed with exit code 1.

**Comment by pernielsentikaer** [comment]
Hi @xeric 👋 

Seems like it could be an idea to team up with @tiancheng92, he is the original author of #112

It could be cool to only have one extension doing the same, since it would confuse the users a lot why there are two of the same.

Could we look into a solution where we can take the best of the both and keeping only one? 

(We do also have support for “contributors” in package.json, which is shown all the way around (also in the contributors store page, so everyone is mentioned for the work)

**Comment by xeric** [comment]
@pernielsentikaer yes, totally agree if we can provide one solution supports multiple requirements based on configuration maybe, but not sure how to setup collaboration with that author.

**Comment by xeric** [comment]
@pernielsentikaer after tried to connect with author of another youdao translator extension and got no response, @PitNikola suggested to continue submit this extension as a standalone one.
https://github.com/raycast/extensions/pull/112#issuecomment-1072692449
Thanks.

**Comment by pernielsentikaer** [comment]
Hi @xeric 👋 

Let's proceed, do you have a key/secret I can borrow for a short amount of time while testing? You can find me in [Slack](https://raycastcommunity.slack.com/) or e-mail me (see my GitHub profile)

Looking forward to testing it out! 🔥

**Review by pernielsentikaer — COMMENTED** [review]
Hi @xeric 👋 

I'm finally able to test your extension again, and thanks for providing me with the keys! 🔥 

I have question for you:

- The `Read It`button, is it supposed to read the input text (it's what it does right now), shouldn't it read the translated text?

CleanShot 2022-04-21 at 11 55 54@2x

**Comment by pernielsentikaer** [comment]
Hi @xeric 👋 

I'm closing this due to inactivity. Feel free to open it again when you're ready to continue working on it 😄

**Comment by xeric** [comment]
Hi @pernielsentikaer 
I've added a new function to speak both original search text and translated content and changed to use official speech synthesis service to provide better pronunciation.

**Comment by pernielsentikaer** [comment]
Sure @xeric 🔥

**Review by pernielsentikaer — APPROVED** [review]
Let's get the first version live @xeric 🔥 Thanks for completing this 😄

**Pull request merged**
