### PR TITLE
Add dirdock extension

### PR DESCRIPTION
**Pull request by yuxbao**
## Description

**DirDock** is your go-to Raycast extension for organizing and accessing your **most frequently used directories**. With powerful features like custom tags, dynamic color previews, and seamless search, DirDock simplifies directory management on macOS.You can get your most commonly used Folders more quickly than just using Raycast,beacuse you may forget the Folder Names(if there are too many folders).

## 🛠 Features

- **Quick Access**: Instantly open your favorite directories with a single command.
- **Manage Directories**: Add, edit, or remove directories effortlessly.
- **Custom Tags**:
  - Assign colorful tags to organize directories visually.
  - Filter directories based on tags for faster access.
  - Display tag names in their assigned colors across all views.
- **Search Capabilities**:
  - Search directories by name or their assigned tags.
- **Color Previews**:
  - Preview tag names dynamically in their assigned colors when creating or editing tags.
- **Clipboard Integration**: Copy directory paths to your clipboard with one click.
- **Lightweight & Fast**: Optimized for minimal impact on system performance.
- **Batch Actions**: Remove all directories at once with a single command.

### **1. Open DirDock**

- Open Raycast and search for `Open DirDock`.
- View all your saved directories, filter them by tags, or open them directly.

---

### **2. Add Directory**

- Open Raycast and search for `Add Directory`.
- Enter the directory path and assign optional tags for organization.

---

### **3. Remove Directory**

- Open Raycast and search for `Remove Directory`.
- Select a specific directory to remove or choose the "Clear All" option to delete all directories.

---

### **4. Add Tag**

- Open Raycast and search for `Add Tag`.
- Enter the tag name and select a color to visually distinguish it.

---

### **5. Manage Tags**

- Open Raycast and search for `Manage Tags`.
- Edit existing tags, delete unwanted tags, or view all available tags.

## Screencast

dirdock-1
dirdock-2
dirdock-3
dirdock-4
dirdock-4
dirdock-5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Abalone27** [comment]
Please Merge @raycastbot

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contributiuon 🔥

It sounds like something that's already possible with the built-in Quicklinks? 

Also a bit like:
* https://www.raycast.com/koinzhang/quick-access
* https://www.raycast.com/HelloImSteven/pins

Did you see them?

**Comment by EthanBao27** [comment]
> Hi 👋
> 
> Thanks for your contributiuon 🔥
> 
> It sounds like something that's already possible with the built-in Quicklinks?
> 
> Also a bit like:
> 
> * https://www.raycast.com/koinzhang/quick-access
> * https://www.raycast.com/HelloImSteven/pins
> 
> Did you see them?

Hello, first of all, I find that the built-in functions of Raycast sometimes fail to locate the folders I need. The DirDock plugin, however, allows me to quickly re-index folders based on my custom color-coded tags and supports multi-tag filtering searches. I can assign shortcuts, like Command+1, to swiftly locate folders according to my tag categorization. The Quick-Access and Pins features you mentioned lack this multi-tag search capability.

**Comment by pernielsentikaer** [comment]
We have an [extension guideline](https://manual.raycast.com/extensions) which is made to encourage users to enhance rather than creating very similar tools - I'm sure @SKaplanOfficial is up for talking about enhancements

Are you up for enhancing?

**Pull request closed without merging**
