### PR TITLE
Update Tailwind plugin to include Tailwind 3 docs

### PR DESCRIPTION
**Pull request by jordobaron**
## Description

Add Tailwind 3 docs to Tailwind extension

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @vimtor

## Screencast
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @codedbyjordan 👋 

A have a question for @vimtor and you, could it be an idea to do like #625 and others, where it's possible to set version in settings, or does that not make any sense?

**Comment by codedbyjordan** [comment]
> Hi @codedbyjordan 👋
> 
> A have a question for @vimtor and you, could it be an idea to do like #625 and others, where it's possible to set version in settings, or does that not make any sense?

Hey @pernielsentikaer :) 

I feel like for this extension this wouldn't be necessary, as Tailwind adds classes every version and doesn't change ones from previous versions.

**Comment by vimtor** [comment]
I agree with @codedbyjordan most endpoints are the same and most people are going to migrate to Tailwind CSS since it is really easy to migrate

**Review by pernielsentikaer — APPROVED** [review]
Thanks for the clarification, it makes perfectly sense 💪

**Review by mathieudutour — APPROVED** [review]

**Pull request merged**
