### PR TITLE
Add time-teller extension

### PR DESCRIPTION
**Pull request by ickas**
## Description

The Time Teller extension uses AI to transcribe human-friendly language into a start and end date and then converts the time frame into different units such as milliseconds, seconds, minutes, hours, and days.

## Screencast

time-teller-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by ickas** [comment]
@pernielsentikaer yup. I added a `setTimeout` for 1.5 seconds to avoid rate limits on the AI API, but I can think of another way to do it.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
What about setting the timeout to `800` instead and using `isLoading={}` on the list so the user knows it's processing?

**Comment by pernielsentikaer** [comment]
Should we consider doing something like this (Since Raycast can handle the AI error now)

```ts
import { useEffect, useState } from "react";
import { Action, ActionPanel, List, AI, environment, popToRoot, Icon } from "@raycast/api";
import { getFavicon, showFailureToast } from "@raycast/utils";
import { setTimeout } from "timers/promises";

interface Timeframe {
  startDate: string | undefined;
  endDate: string | undefined;
}

export default function Command() {
  const [searchText, setSearchText] = useState("");
  const [timeframe, setTimeframe] = useState<Timeframe>({ startDate: undefined, endDate: undefined });
  const [isLoading, setIsLoading] = useState(false);

  /**
   * Fetches and processes date information from the AI based on the current input text.
   *
   * This effect is triggered whenever the search text changes. It waits for 1.5 seconds before
   * querying the AI to avoid being rate limited. The AI's response is expected to be in the
   * format "startDate: YYYY-MM-DDTHH:MM:SSZ, endDate: YYYY-MM-DDTHH:MM:SSZ".
   *
   * The response is then parsed into a timeframe object, which is used to update the component's state.
   */
  useEffect(() => {
    /**
     * Checks if the input text is not empty before proceeding with the data fetching process.
     * This condition ensures that unnecessary requests are not sent to the AI when the input text is empty.
     */
    if (searchText !== "") {
      const fetchData = async () => {
        setIsLoading(true);
        await setTimeout(800);

        const aiPrompt = `translate the date and give only a direct answer with the current date and the date in the text, or between the two dates in the text, format in ISO 8601 and give a string with start and end dates like "startDate: 2024-10-05T13:00:00Z, endDate: 2024-10-06T22:00:00Z": ${searchText}`;

        try {
          const answer = await AI.ask(aiPrompt, {});
          const dates = answer.split(", ");
          const dateObject = dates.reduce((acc: Timeframe, date) => {
            const [key, value] = date.split(": ");
            acc[key as keyof Timeframe] = value;
            return acc;
          }, {} as Timeframe);

          setTimeframe(dateObject);
        } catch (err: unknown) {
          if (err instanceof Error) {
            if (err.message === "Process cancelled") {
              popToRoot();
            } else {
              showFailureToast(err);
            }
          }
        }

        setIsLoading(false);
      };
      fetchData();
    }
  }, [searchText]);

  function calculateTimeframes(startDate: Date, endDate: Date) {
    // Convert the input dates to date objects if they are not already
    const start = new Date(startDate);
    const end = new Date(endDate);

    // Calculate the difference in milliseconds, seconds, minutes, hours, and days
    const diffInMilliseconds = end.getTime() - start.getTime();
    const diffInSeconds = diffInMilliseconds / 1000;
    const diffInMinutes = diffInSeconds / 60;
    const diffInHours = diffInMinutes / 60;
    const diffInDays = diffInHours / 24;

    // Return a object with the timeframes
    return {
      milliseconds: diffInMilliseconds,
      seconds: diffInSeconds,
      minutes: diffInMinutes,
      hours: diffInHours,
      days: diffInDays,
    };
  }

  const timeframes =
    timeframe.startDate && timeframe.endDate
      ? calculateTimeframes(new Date(timeframe.startDate), new Date(timeframe.endDate))
      : calculateTimeframes(new Date(), new Date());

  return (
    <List
      filtering={false}
      onSearchTextChange={setSearchText}
      searchBarPlaceholder="Write a date or a time period"
      throttle={true}
      isLoading={isLoading}
    >
      <List.EmptyView icon={Icon.Clock} title="Waiting for input" description="Type a period or a specific query" />
      {timeframe.startDate !== undefined && (
        <>
          <List.Item
            title={timeframe.startDate ?? "No start date detected"}
            accessories={[{ text: "ISO 8601" }]}
            actions={
              <ActionPanel>
                <Action.CopyToClipboard title="Copy" content={timeframe.startDate ?? ""} />
              </ActionPanel>
            }
          />
          <List.Item
            title={timeframe.endDate ?? "No end date detected"}
            accessories={[{ text: "ISO 8601" }]}
            actions={
              <ActionPanel>
                <Action.CopyToClipboard title="Copy" content={timeframe.endDate ?? ""} />
              </ActionPanel>
            }
          />
          <List.Item
            title={timeframes.milliseconds.toString()}
            accessories={[{ text: "Milliseconds" }]}
            actions={
              <ActionPanel>
                <Action.CopyToClipboard title="Copy" content={timeframes.milliseconds.toString()} />
              </ActionPanel>
            }
          />
          <List.Item
            title={timeframes.seconds.toString()}
            accessories={[{ text: "Seconds" }]}
            actions={
              <ActionPanel>
                <Action.CopyToClipboard title="Copy" content={timeframes.seconds.toString()} />
              </ActionPanel>
            }
          />
          <List.Item
            title={timeframes.minutes.toString()}
            accessories={[{ text: "Minutes" }]}
            actions={
              <ActionPanel>
                <Action.CopyToClipboard title="Copy" content={timeframes.minutes.toString()} />
              </ActionPanel>
            }
          />
          <List.Item
            title={timeframes.hours.toString()}
            accessories={[{ text: "Hours" }]}
            actions={
              <ActionPanel>
                <Action.CopyToClipboard title="Copy" content={timeframes.hours.toString()} />
              </ActionPanel>
            }
          />
          <List.Item
            title={timeframes.days.toString()}
            accessories={[{ text: "Days" }]}
            actions={
              <ActionPanel>
                <Action.CopyToClipboard title="Copy" content={timeframes.days.toString()} />
              </ActionPanel>
            }
          />
        </>
      )}
    </List>
  );
}
```

Which gives us this view:

https://github.com/user-attachments/assets/6f719bb5-2744-45ce-8422-f48e7badbf4a

**Comment by ickas** [comment]
@pernielsentikaer that is a really nice tip, it's a much better UX 👌

**Comment by pernielsentikaer** [comment]
I'm still wondering if it's possible to achieve this without the use of AI. Maybe there is a package that can help guess dates?

**Comment by ickas** [comment]
@pernielsentikaer, it was my first move, but I don't find anything so accurate (obviously!). There are many packages that translate specific dates into relative dates and some that detect words, but I haven't found a really human-friendly solution.

The other way is to write a lot of *ifs* to try to achieve the same result, but the code won't be pretty 😅

**Pull request merged**
