### PR TITLE
Messages 2FA Codes: Added polling + general cleanup

### PR DESCRIPTION
**Pull request by thomaspaulmann**
## Description

The main purpose of this PR is to add polling of new 2FA codes. So you can open the command and the code might be a bit delayed. This way it shows up and you don't need to re-open the command.

While I was there, I cleaned up the extension a bit:
- Refactored for easier contribution
- Changed `iMessage` to `Messages` to match official name
- Added keyboard shortcuts to actions
- Cleaned up the UI

## Screencast

imessage-2fa 2023-01-16 at 17 55 51

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
@yuercl given that this extension is about 2FA codes, I was wondering to remove the search type dropdown. I assume just the `code` type should be enough? If we want to keep a search for messages, I would rather build a separate command that is optimized for this. WDYT?

**Review by yuercl — APPROVED** [review]
new hook 'useInterval' support

**Comment by thomaspaulmann** [comment]
@yuercl what do you think of removing the filter dropdown as described above?

**Comment by yuercl** [comment]
@thomaspaulmann Perhaps this scenario is more general, most of the time it is to search for all information, and a few times it is to extract the code, or in other words, extracting the code is just a shortcut.  so I agree with your suggestion about "remove filter dropdown menu". This will make the extension more concise.

**Pull request merged**
