### PR TITLE
New Extensions: ChatGPT

### PR DESCRIPTION
**Pull request by abielzulio**
## Description

A quick way to interact with the OpenAI's ChatGPT using [unofficial API](https://github.com/transitive-bullshit/chatgpt-api) with three commands available:
1. "Ask": A direct way to start a conversation with ChatGPT by asking a question
2. "Saved Answer": A collection of the user's saved question and its answer
3. "History": A collection of all the user's questions plus the answers

## Screencast

https://user-images.githubusercontent.com/7030944/206860420-35f55ce1-f11a-4aea-9510-5cf96af5e956.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by peduarte** [comment]
Closing due to OpenAI Limitations 😭

**Comment by ShubhamVerma1811** [comment]
so close yet so far 😭

**Comment by melalj** [comment]
Any updates since OpenAI is now supporting the ChatGPT API?

**Comment by abielzulio** [comment]
> Any updates since OpenAI is now supporting the ChatGPT API?

My new extension is already updated using the new ChatGPT API. You can check out my repository if you want to try (on `dev` env). I'll create a new PR once it's polished.

**Pull request closed without merging**
