### PR TITLE
Add azure-devops extension

### PR DESCRIPTION
**Pull request by yemilgr**
## Description

This extension add support to azure devops work items and navigate into them easily.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
This seems similar to [this extension](https://www.raycast.com/willem_van_lent/ado-search), could you check that one out?

**Comment by yemilgr** [comment]
> This seems similar to [this extension](https://www.raycast.com/willem_van_lent/ado-search), could you check that one out?

Yes indeed it is, I didn't knew it exists :( 
Anyway my extension add also projects and work items listing besides repositories and pull requests

**Comment by willemvanlent** [comment]
Seems like a great enhancement to my extension!

**Comment by yemilgr** [comment]
Ohhh I'm afraid I don't have the time to do so. Anyway @willemvanlent if you want to take any piece of feature of my PR. feel free. You're more than welcome.
thanks

**Comment by pernielsentikaer** [comment]
Sounds like we have a plan, I'm closing this so we can move it to the other extension 🙂

**Pull request closed without merging**
