### PR TITLE
Add Productlane extension

### PR DESCRIPTION
**Pull request by scopsy**
## Description

Created a new [Productlane](https://productlane.io/) extension to easily submit feedback to productlane.

## Screencast

CleanShot 2023-02-28 at 14 45 27

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by RaphaelFleckenstein** [comment]
Hey @raycastbot, any updates on releasing the extension?

**Comment by merlindru** [comment]
We'd love to see this go live 😄

**Comment by pernielsentikaer** [comment]
Hi @scopsy 👋 

It seems like you have a conflict in your `package-lock.json` you need to resolve

**Comment by pernielsentikaer** [comment]
Hi @scopsy 👋 

It seems like you have added a `package-lock.json` in the root of extension, could you please remove that from the PR 😊

**Comment by scopsy** [comment]
@RaphaelFleckenstein my bad, done!

**Comment by pernielsentikaer** [comment]
Hi @scopsy 👋 

There was a bug in the copy function, it was using `insight.id` instead of `insight.result.id`

I also added some validation and added e-mail to preferences.

Do you mind checking it so I didn't break anything 😊

**Comment by scopsy** [comment]
@pernielsentikaer just played with it and it looks great! Working as expected

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
