### PR TITLE
Add phosphor-icons extension

### PR DESCRIPTION
**Pull request by marinsokol**
## Description

Extension with 1 command to seach for phosphor icon. Allowing you to copy icon in format you need: icon name, HTML element, React or Vue component.

This extension idea is reported in [https://github.com/tonka3000/raycast-extension-ideas/issues/8](https://github.com/tonka3000/raycast-extension-ideas/issues/8)

## Screencast

phosphor-icons-1
phosphor-icons-2
phosphor-icons-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
We already have #10416 in the queue by @SKaplanOfficial but maybe we can unite the two of them - what do you two think?

**Comment by marinsokol** [comment]
> We already have #10416 in the queue by @SKaplanOfficial but maybe we can unite the two of them - what do you two think?

I would agree. How would you propose to unite it?
Extensions are similar. Looking at mentioned PR, i would make couple of updates:
1. load icons from url, like i did. So we don't have 5k assets for icons
2. Reduce icons size a bit, so icons are not border to border
3. Combine existing and mine action panel, so user can copy icon as SVG or component

**Comment by pernielsentikaer** [comment]
Sounds like a plan, what do you think @SKaplanOfficial

**Comment by pernielsentikaer** [comment]
Is there anything from #10416 you want to add before merging @marinsokol

**Comment by marinsokol** [comment]
@pernielsentikaer I would like add grid view option and option to copy svg in action panel

**Comment by pernielsentikaer** [comment]
That makes sense, I'll await that :)

**Comment by marinsokol** [comment]
@pernielsentikaer I updated this PR. You can take a look :)

**Comment by pernielsentikaer** [comment]
The only remaining thing is the extension logo, which doesn't work that well with dark appearance. Do you think you can come up with a better one?

Raycast26022024-qzCmNfk0 png@2x

**Comment by marinsokol** [comment]
forgot to update that. It is fixed now

**Review by pernielsentikaer — COMMENTED** [review]
Could you use the same background for the metadata images? 🙂

**Comment by marinsokol** [comment]
you are goood 🙂... metadata images are updated

**Comment by pernielsentikaer** [comment]
Much better 👏

**Pull request merged**
