### PR TITLE
Add safari-window-manager extension

### PR DESCRIPTION
**Pull request by Fnux8890**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Wouldn't it make more sense to include this in the [Safari extension](https://www.raycast.com/loris/safari) we already have in the store by @loris 🙂

**Comment by Fnux8890** [comment]
@pernielsentikaer oh for sure. This is my first time trying to develop something and added it so I wasn't sure if I could just add to other projects or how it works 😬

if your on it I can try other wise let me know

**Comment by pernielsentikaer** [comment]
You can use the action `Fork Extension` after you have it intalled locally, then you can do your changes and run

git commit, git push and npm run publish

**Comment by Fnux8890** [comment]
Awesome thanks🤩 
Ill look into it 👍

**Pull request closed without merging**
