### PR TITLE
Add DevGadgets

### PR DESCRIPTION
**Pull request by okuramasafumi**
## Description

This Pull Request adds a new extension called `DevDadgets`.

## Screencast

devgadgets-1
devgadgets-2
devgadgets-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x]  I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @okuramasafumi 👋 

Thanks for your contribution 🔥 

I think all of the features are already in the [Toolbox](https://www.raycast.com/Kang/toolbox) extension, could you check that out and see if it's covering your needs?

We might need to add a few more keywords on the Toolbox extension depends on what you searched for

**Comment by okuramasafumi** [comment]
Oh I didn't find Toolbox extension.
My motivation was to reimplement tools like https://devutils.com/ with Raycast. I'll add more features that Toolbox doesn't have.

**Comment by okuramasafumi** [comment]
Hi, I added a new `Date` command that adds and subtracts given number to specified date (or today if not specified).
Are there any existing extension that has this feature?

**Comment by pernielsentikaer** [comment]
Almost all in here is already added in the toolbox extension, manipulating time and date is build-in inside Raycast
Raycast-oylhcInq@2x

**Pull request closed without merging**
