### PR TITLE
Update http extension

### PR DESCRIPTION
**Pull request by negasus**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution. Have you seen [this extension](https://www.raycast.com/jonathangiardino/curl), which appears similar yet possesses a lot of features? Maybe enhancing that one would be preferable, so we avoid having two similar extensions.

**Comment by negasus** [comment]
This extension has slightly different goals. Calling predefined requests with substitution of variables from the profile. I also plan to add the ability to save queries in collections.

But if you want to reject this PR, I understand you.

**Comment by pernielsentikaer** [comment]
I agree it's not 100% the same, but it would be something that would fit right into the other extension, what do you think @jonathangiardino - wouldn't it make sense to enhance instead of adding a new one?

**Comment by jonathangiardino** [comment]
Haven't sen what the other extension does to be honest, but if there's something that can be added to cURL and can be an enhancement for all the users, I am all for it! @pernielsentikaer

**Comment by pernielsentikaer** [comment]
I think it would fit right in, what I understand is that it will be possible to make profiles and have variables - but I'm not sure how easy it will be to merge, what do you think @negasus

**Comment by negasus** [comment]
I'm afraid that this will require quite a lot of modification of the cURL extension. I think it would be better if the author decides for himself whether this functionality should be added.

I suppose, this PR can be closed?

**Comment by jonathangiardino** [comment]
> I'm afraid that this will require quite a lot of modification of the cURL extension. I think it would be better if the author decides for himself whether this functionality should be added.
> 
> I suppose, this PR can be closed?

@negasus unfortunately I do not have time for this implementation at the moment, but since it's all open source, feel free to add features if you want and open a PR, @pernielsentikaer also contributed to it before.

**Comment by pernielsentikaer** [comment]
Closing for now, let's get some of the features implemented in the current extension when there is time for it

**Pull request closed without merging**
