### PR TITLE
[Whois] Added IP2Location.io as failover for WHOIS data

### PR DESCRIPTION
**Pull request by ip2location-com**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by j3lte** [comment]
This code is not going to work. `useFetch` is a hook, you can't return another hook conditionally. Furthermore, the `try... catch` won't be caught, because useFetch uses the `onError` method to catch for errors.

This would only work if you would place the `useFetch` after the first one and execute it when the first one errors which would set some outside state.

Is this code tested?

**Comment by pernielsentikaer** [comment]
I agree with @j3lte. This is not the right approach to take as it doesn’t work

**Comment by j3lte** [comment]
@pernielsentikaer I think we can just close this PR. I checked the activity of this Github account, it's just spamming its own service everywhere. 

Screenshot 2024-08-21 at 19 00 33

**Comment by pernielsentikaer** [comment]
Let's do that @j3lte, that's a really good point

Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Pull request closed without merging**
