### PR TITLE
[Luna Search] Add menu-bar command for quick access, move to hooks for retrieving data, fix pagination issue, add min-search size

### PR DESCRIPTION
**Pull request by relevantsam**
## Description
* Added a new menu bar command that allows the user to quickly access the last 5 recent games they've visited through the extension. These are kept for up to 1 week (if the cache lives that long). Additionally, show the top 5 trending games in the list. Clicking a game opens the game in the most Luna-appropriate browser installed.
* Fixed an issue that would cause trending games to show in an empty state. It's related to something under the hood in useFetch that doesn't quite work with what I've done here - but I side-stepped it by ignoring the results from fetch in the appropriate places.
* Fixed an issue where irrelevant previous results would flash between an empty state and search results. Instead, only keep results when the search is forking off of the same search root.
* Limit searches to only run when only 3+ characters are entered, since anything below this is low quality traffic to the server with low accuracy of results.

---

* Noticed that I managed to introduce a nice bug with my pagination changes where a race could occur and an off-by-1 error would hit the user. Sorted!
* Dug into useFetch and found a nice react-y way to do what I was previously doing with Singletons etc. Hooks are so back. Also meant I could cut axios, so that's neat.
* Then "Services" didn't make sense anymore so moved to "models" 
* The new hooks let me break down the base component to be much simpler. Less gnarly logic differentiating viewing trending from viewing search results! woo.

## Screencast

Screenshot 2024-08-26 at 4 15 45 PM

## Checklist

- [✅] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [✅] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [✅] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [✅] I checked that files in the `assets` folder are used by the extension itself
- [✅] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by relevantsam** [comment]
[@pernielsentikaer] back on https://github.com/raycast/extensions/pull/14006 you pointed out I could use useFetch. Had a fun time reworking things and I feel much more satisfied with the layout of the code now! Thanks!

**Comment by pernielsentikaer** [comment]
Thanks really awesome, glad you liked the way it worked 🙂

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- When you search for e.g. `Lego` and delete the search query it still shows the list of games

- Is it by purpose that you'll need to search for 3 chars before it searches?

- I couldn't get the pagination to work, do you know something I can search for?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by relevantsam** [comment]
Thanks Per! Replies in-line.

>     * When you search for e.g. `Lego` and delete the search query it still shows the list of games

Addressed, thanks for finding! Good 🐛.

>     * Is it by purpose that you'll need to search for 3 chars before it searches?

Yes - I should've implemented this at first. The 1-2 character searches are low precision and not very useful traffic. I added customer messaging for this case to help.

>     * I couldn't get the pagination to work, do you know something I can search for?

Any grid that has >15 games uses it! Trending games, for example. It is hard to notice, because it is using the in-memory set of games so the pagination is extremely fast. I only added it because I want to let Raycast's memory controls manage if I load too many images into view for example. The previous bug happened when you went from a paginated view to a non-paginated (if I remember correctly..). So, maybe trending to "Valhalla"? 

> I'm looking forward to testing this extension again 🔥

Thanks for the hard work!

**Comment by pernielsentikaer** [comment]
MUCH better 🔥

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
