### PR TITLE
feat: add extract url from text

### PR DESCRIPTION
**Pull request by iloveitaly**
## Description
Extract urls from messy input text. I've tested this in a couple scenarios, but it probably needs some tweaking based on user feedback.

## Screencast
NA

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you mind checking this @pomdtr

**Comment by pernielsentikaer** [comment]
@iloveitaly could you also add a changelog entry

**Comment by iloveitaly** [comment]
added changelog

**Comment by iloveitaly** [comment]
@pernielsentikaer bump!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Thanks for the bump @iloveitaly

**Pull request merged**
