### PR TITLE
feat(Timers): add custom notification system using Swift app bundle

### PR DESCRIPTION
**Pull request by ThatNerdSquared**
## Description

- Add a custom notification system using a Swift app bundle to call into the system `User Notifications` framework
- Advantages of custom notification system:
    - Avoids silent permission errors when using `osascript`
    - Banner notification icon matches extension icon
    - Adds actions to banner notification for dismissing the timer or opening up "Manage Timers" command

## Screencast

Screenshot 2024-05-23 at 23 17 16

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by ThatNerdSquared** [comment]
@pernielsentikaer — for this feature to work properly, I need to include the compiled Swift app bundle somehow on the user's machine. What's the best way to go about this?

- keep a compiled bundle in `assets/`? Seems like that would take up a lot of space in the repo.
- download it on extension install from some hosted location (e.g., GitHub Releases)?
- some other method?

Also, I don't have a dev license to sign the bundle with. Not sure if that's an issue or not.

**Comment by pernielsentikaer** [comment]
You can check how extensions like [keyboard-cleaner](https://github.com/raycast/extensions/pull/12449) or [color picker](https://www.raycast.com/thomas/color-picker) does it, it will auto compile it 🙂

**Comment by ThatNerdSquared** [comment]
I've tried using the Swift for Raycast method, which is what those extensions do, but unfortunately it doesn't work for this use case. The API I'm using needs to be run from an app bundle, which doesn't happen using that method (i asked about it [here](https://raycastcommunity.slack.com/archives/C02HEMAF2SJ/p1715069030390119?thread_ts=1714605923.296799&cid=C02HEMAF2SJ) on the Raycast Slack).

**Comment by pernielsentikaer** [comment]
You should be able to use the "old" method, like it's [done here](https://github.com/raycast/extensions/tree/36a96ef5bebbbcea270809a664fc2e2e2ca56359/extensions/ruler)

**Comment by ThatNerdSquared** [comment]
Oh, this is interesting. How does this work, exactly? Is there documentation about it somewhere? I'm not sure if I understand the extension structure here.

**Comment by pernielsentikaer** [comment]
I'm not sure we have that much documentation of this way, you can see how it's triggered in package.json - first version of Color Picker also used this method afaik

**Comment by ThatNerdSquared** [comment]
Alright, that makes sense. Do you know what this binary file is in the `assets/` for that extension?

Screenshot 2024-05-24 at 00 19 51

**Comment by pernielsentikaer** [comment]
That's the one that was build with the `build-swift` npm run script in package.json

**Comment by ThatNerdSquared** [comment]
Unfortunately, this method does not work either. The executable is compiled but since it is not in an app bundle the API fails to work (i get a `NSInternalInconsistencyException` with reason `bundleProxyForCurrentProcess is nil`).

**Comment by pernielsentikaer** [comment]
I asked internally and got this reply, not sure if it works at all
> This might work, though I haven't used it for a long time and I'm not sure you can set the icon: https://github.com/julienXX/terminal-notifier

**Comment by ThatNerdSquared** [comment]
@pernielsentikaer I've looked at that, unfortunately it does not solve the problem as it is also distributed as an app bundle (and at that point I might as well just use the one I've written, which has more functionality).

In general, other methods of sending notifications to the user have one or more of the following problems:
1) They require an app bundle (same as my solution) or use Applescript
2) They use the deprecated `NSUserNotification` API rather than the newer `UserNotifications` framework
3) They use private methods not exposed as public APIs by Apple
4) They are missing functionality (no custom icon, no custom actions, etc)

This is because many things like the custom icon, custom actions, etc are only available through system APIs (not through Applescript, etc). Additionally the `UserNotifications` framework only works from within an app bundle.

I do not want to continue using Applescript (it has very unstable permissions, as shown [here](https://github.com/raycast/extensions/issues/11500) and [here](https://github.com/raycast/extensions/issues/11897)), and I do not want to use the deprecated API or private methods as Apple may block their usage at any time. So I think my current solution is probably the best one.

Possibly I can use a method similar to the Ruler extension, by including only the Swift file and app bundle? Then we will not have to add all the xcode files as well. But I think that's the best we can do.

**Comment by ThatNerdSquared** [comment]
As I haven't found a better way to do this, I've copied in the app bundle to the `assets/` folder. Should be ready for review.

The app bundle is still not signed - is this an issue? If so, would it be possible for someone from the Raycast team to build/sign it? Or for this to be set up as a CI job somehow?

**Comment by ThatNerdSquared** [comment]
Hi @pernielsentikaer, any news regarding this? Would be great if we could get it shipped :)

**Comment by pernielsentikaer** [comment]
Sorry for the delayed response.

I had to check what options were available. Unfortunately, we can’t support that at the moment, but we are working on a notification API which should give options for doing as you want. However, there is no ETA yet 🫠

**Comment by ThatNerdSquared** [comment]
If I get the app bundle signed, would it be acceptable? Or is the additional app bundle itself the dealbreaker?

**Comment by pernielsentikaer** [comment]
It's not possible at the moment but we're going to revamp toast/hud/notification where something like this will be possible - sorry it's not as simple as it could be

**Comment by ThatNerdSquared** [comment]
I see there are [other extensions](https://github.com/raycast/extensions/tree/6c8a2b516913f96205d17a7d269a5a3d1f5448eb/extensions/pins/assets/scripts/PinsLocationManager.app/Contents) that tap into system APIs via an app bundle - it is quite unfortunate that the same cannot be done for notifications.

In any case - thank you for your time reviewing this. If there are no other solutions for the time being, feel free to close the PR.

**Comment by pernielsentikaer** [comment]
We would like to support this out of the box with the revamp that we're going to add - I also tried to build this myself and I was not able to get it to work, not sure if it's something with the signing 🫠

**Comment by ThatNerdSquared** [comment]
> I also tried to build this myself and I was not able to get it to work

What error did you run into? Maybe we can debug it. I can also try getting it signed if that helps.

> We would like to support this out of the box

That would be great :) It would still be nice to push a solution to the users in the meantime though.

If it's not worth the trouble of debugging the build, feel free to close the PR - I'd understand if the team feels this is out of scope for the time being.

**Comment by pernielsentikaer** [comment]
For now, I'm closing it, but I will keep you in the loop about this feature internally

**Pull request closed without merging**
