### PR TITLE
update-extension/large-type: add new action panel option to close window.

### PR DESCRIPTION
**Pull request by gon250**
## Description

Add a new action panel option to close window.

## Type of change

- Bug fix / improvement for my extension

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @gon250 👋 

Thanks for the update, a suggestion could be that you should use [popToRoot](https://developers.raycast.com/api-reference/user-interface/window-and-search-bar#poptoroot) when closing the window right away, what do you think about that? 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by gon250** [comment]
> 

@pernielsentikaer good point! :) I didnt know about it. I've made the change and now its working in a way I think makes more sense. Let me know if there is anything else

**Review by pernielsentikaer — APPROVED** [review]
Awesome @gon250 💪 Much better 🔥 

I'm going to accept it and then will my colleague do a final review before it's finally merged 🚀

**Review by mathieudutour — APPROVED** [review]
Looks good :+1:

**Pull request merged**
