### PR TITLE
[vercel] Use the team id for selectedTeam state, fix persistency of team id

### LINKED ISSUE #4528: [Vercel] Not saving selected team between renders
### Extension

https://www.raycast.com/vercel/vercast

### Description

The selected team in the filter does not save. Each time I open the search deployments view, it defaults to my personal account, no matter how many times I switch to my company's team account.

### Steps To Reproduce

_No response_

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### LINKED ISSUE #5575: [vercel] Deployments urls should use team slug instead of team name
### Extension

https://www.raycast.com/vercel/vercast

### Description

Deployments urls should use team id instead of team name

You don't notice this if you have team id same as team name, this is the reason this issue wasn't noticed before

### Steps To Reproduce

_No response_

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by remorses**
## Description

Fix #5575
Fix #4528 

The persistency problem was because of the missing `value` in the team select

I replaced the selected team state with a string instead of the team object, this way the deployment list doesn't have to wait for the `teams` api request to start loading the correct list.

I also changed the local storage key to prevent issues with previous installations

## Screencast

https://user-images.githubusercontent.com/31321188/227745245-bcf73dc6-283a-461e-8a3b-a105f20f6b4a.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the update @remorses 🔥 Do you mind adding a `CHANGELOG` entry too?

@MaxLeiter @gleich do you mind checking this?

**Comment by remorses** [comment]
I added the CHANGELOG entry, it's ready for review

**Comment by pernielsentikaer** [comment]
Ping @MaxLeiter @gleich 😊

**Review by MaxLeiter — APPROVED** [review]
LGTM. Thank you!

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
