### PR TITLE
Add Port Manager Extension

### PR DESCRIPTION
**Pull request by lucaschultz**
## Description

The Port manager extension lists open ports and allows to [kill](https://ss64.com/osx/kill.html) the processes which open them. It allows killing either with the default **SIGTERM** signal or **SIGKILL**, which can't be ignored by the process.

It also offers the ability to copy information about the process (PID, Name, Parent PID, User name, User UID) or a `kill` command to paste in a terminal.

## Screencast

https://user-images.githubusercontent.com/45899273/154150489-837d45eb-31a0-4ae8-b6be-b7a05ac515d2.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @lucaschultz 👋 

I think I would call the command “Kill Port” instead, and remove the subtitle completely, what do you think about that?

Besides that, awesome work 🔥

**Comment by lucaschultz** [comment]
Hi @pernielsentikaer,

nice suggestions. I'll makes the changes later today.

**Comment by pernielsentikaer** [comment]
Awesome, looking forward for the next push 💪

**Comment by lucaschultz** [comment]
@pernielsentikaer Done 💪

**Review by pernielsentikaer — APPROVED** [review]
Hi @lucaschultz 👋 

Awesome 🔥 It's turned out very nice – good job 💪 

I'm going to accept it, lets proceed to final stage 😄

**Comment by lucaschultz** [comment]
@pernielsentikaer, awesome! The very first piece of Software published under my own name 🎉

**Comment by pernielsentikaer** [comment]
It's solid work @lucaschultz 💪 I'm quite sure it's not going to be your last 😄

**Review by mathieudutour — APPROVED** [review]
:100:

**Pull request merged**
