### PR TITLE
Add Flyio Extension!

### PR DESCRIPTION
**Pull request by nagauta**
## Description

Add extension to explore apps managed in [Fly.io](https://fly.io/)

## Screencast

fly-io-1
fly-io-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I'm missing something when I have a wrong key inputted, there is no loader or anything telling me about errors

fly-io 2023-10-05 at 12 41 25


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by nagauta** [comment]
Hi,@pernielsentikaer 
I updated accordinct to your review.
please check it again

**Comment by pernielsentikaer** [comment]
Hi @nagauta 👋 

I was a bit confused, I entered the token and just saw No Result, tried to search, the same result (didn't even see a loading indicator)

 Is it possible to show different EmptyViews?
  - If no apps are installed = “install apps”
  - If query is empty = “Type to search”
  - if no match = No Results

**Comment by nagauta** [comment]
oh

**Comment by pernielsentikaer** [comment]
Are you planning to work on this @nagauta, or should we temporarily close it until you're ready again? 🙂

**Comment by nagauta** [comment]
I'm not sure when I can try this
So it's good to temporarily close thanks

**Pull request closed without merging**
