### PR TITLE
feat(google-chrome): added search bookmarks, refactored to useSQL hook, code cleanup

### PR DESCRIPTION
**Pull request by crisboarna**
## Description

- Added search bookmarks action
- Refactored code to use new useSQL hook

## Screencast
image
image
image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @crisboarna 👋 

Thanks for the update 🔥 

 @rgomezcasas do you mind checking this?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by rgomezcasas — COMMENTED** [review]
Looks perfect!! 🙌

**Comment by ryan-efendy** [comment]
@crisboarna @rgomezcasas I'm using [Chrome Beta](https://www.google.com/chrome/beta/) instead of the regular/stable version, and I'm getting this error when invoking the new tab command. Is there a way to configure the path?

image

**Comment by bromanko** [comment]
I added config for the path in #4071. The extension was heavily refactored and I have had a chance to fix the merge conflicts yet.

**Pull request merged**
