### PR TITLE
Add open-folder-in-application extension

### PR DESCRIPTION
**Pull request by thecarlo**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Thanks for your contribution 🔥 

This extension seems to be pretty similar to [Folder Search](https://www.raycast.com/GastroGeek/folder-search), could you check that out?

**Comment by thecarlo** [comment]
> Hi 👋
> 
> Thanks for your contribution 🔥
> 
> This extension seems to be pretty similar to [Folder Search](https://www.raycast.com/GastroGeek/folder-search), could you check that out?

At first glance, the extensions seem somewhat similar.

However, with Folder search, when you hit enter, it opens the folder by default. To open in application, you have to:

- Open the extension
- Search for a folder
- Open Folder Actions
- Select the application
- Then open the folder in the app

With My extension, it immediately opens with the application selector once you select a folder. Hence the name "Open Folder in Application".

I believe there is value in being able to open a folder in an application quickly. Else what is the point of Raycast. If there's so many steps involved one might as well just launch your app from the terminal or use Alfred.

**Comment by thecarlo** [comment]
@pernielsentikaer ☝️

**Comment by mil3na** [comment]
Hi! Thanks for your effort making this extension!
I believe that the following extensions:
https://www.raycast.com/timothy_boye/open-folders
https://www.raycast.com/GastroGeek/folder-search
The missing feature that you are adding here would fit perfectly in one of them. I would suggest creating another PR adding it to one of these. Let me know if you have any concerns and want to discuss this further.

**Pull request closed without merging**
