### PR TITLE
Add pdfsearch extension

### PR DESCRIPTION
**Pull request by kevin-pek**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Maybe remove the `Search Collection` command, if you have a lot of collections it will be pretty hard to remember the names of collectins?

- Tried to make a few collections but was not able to get it to search. Do you have some test files I can use in order to test it?

- Missing [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by kevin-pek** [comment]
Hi, thank you for reviewing my extension!

I realise that my extension requires Git LFS as in its current implementation, as I am bundling a CoreML within the assets directory. I believe this caused the second issue that you highlighted about being unable to search. I have tried to push the bundled files into the assets folder, but it seems that I am unable to do so.

Screenshot 2024-01-14 at 10 21 08 PM

Is there a way I can work around this, or will I have to make changes to the app?

**Comment by pernielsentikaer** [comment]
When dealing with binaries we need to be a [bit more strict](https://developers.raycast.com/basics/prepare-an-extension-for-store#binary-dependencies-and-additional-configuration) - not actually sure why you see that error though.

How big is your binary, and is it possible that we can compile it ourself somehow?

**Comment by kevin-pek** [comment]
The model that the binaries in my extension depend on size is around 130MB. I downloaded the mlpackage file from https://huggingface.co/jinaai/jina-embeddings-v2-small-en/tree/main/coreml and compiled it using `xcrun coremlcompiler compile` before adding it as a dependency to the project's `Package.swift` file. I read the page that you linked to, is this file size considered too large for an extension?

**Comment by kevin-pek** [comment]
I have solved the issue in my previous comments by removing the dependency on the model. Have also removed the `Search Collection` command and added more metadata images as requested. The extension should now work fine!

**Comment by pernielsentikaer** [comment]
It looks a lot better 👏

Does it work for intel machines too, looks like the build is only for `arm64`

**Comment by kevin-pek** [comment]
I only included arm64 because I don't have access to an intel based machine to test this extension on, was afraid something might break. 😅

I can include it in the build, but is there a way the intel build can be tested?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
