### PR TITLE
F1: Add session times to Race Schedule

### PR DESCRIPTION
**Pull request by sxn**
## Description

- Uses `List.Item.Detail` to display session times for upcoming races
- Updates `Open in Browser` action for upcoming races so that it tries to open the season-specific Wikipedia URL (e.g. https://en.wikipedia.org/wiki/2022_Bahrain_Grand_Prix) instead of the generic one (e.g. https://en.wikipedia.org/wiki/Bahrain_International_Circuit)
- Adds `CHANGELOG.md` and screenshots

## Screencast

https://user-images.githubusercontent.com/1155589/159174202-9a45ade3-b5ab-4e0d-8909-6d4b2d75a324.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by csigritz** [comment]
❤️

**Comment by csigritz** [comment]
Great!!!

**Comment by sxn** [comment]
found a couple of issues I want to look into later this evening:

- some races (anything farther back than 2005) don't seem to have dates, so the extrnsion shows `Invalid Date` in that case 😬 
- will need to rethink the logic for when to allow a `List.Item.Detail` to be displayed. Currently if you open the detail view for the next race and then navigate to the previous race, the detail view stays open despite the fact that it's empty 😅 

Better not merge this until those issues are resolved.

**Comment by sxn** [comment]
Alright, I've fixed the detail view issue & the date issue - but in the process I've also ended up refactoring the whole extension 🥲 

https://user-images.githubusercontent.com/1155589/159353893-5a16f250-6aa4-4a24-bef0-5995a7985a70.mov

**Comment by anhthang** [comment]
I think we should change the extension name in package.json too, since a lot of features was added

**Comment by sxn** [comment]
@anhthang IIRC the extension was _initially_ named F1 but then @csigritz updated it to what it is now.

what would you change the name to? 🤔

**Comment by csigritz** [comment]
The title of the extension was `F1 Standings` when I committed the first version. Because at that time only current Formula 1 Standings for Drivers and Constructors have been displayed. Now also Race Schedule and lot more stuff by @sxn has been added. The title in package.json has then been updated to `Formula-1` by myself.
I did **not** change the package name because I thought this may eventually make problems when updating the extension to users. If this is not the case: of course we should rename it from `f1-standings` to `formula-1`.

I'm sure @sxn can answer if changing the package can cause problems.

**Review by csigritz — APPROVED** [review]

**Comment by sxn** [comment]
while extensions (folder, name in `package.json`) _can_ be named, it's a but more of a hassle, so maybe let's do that w/ a separate update 😬 I'll merge this PR for now, pretty sure there'll be more things to be added to the extension 😶

**Comment by sxn** [comment]
@anhthang @qeude good point! I've addressed it [here](https://github.com/raycast/extensions/pull/1217) 😸

**Comment by csigritz** [comment]
Yep. They both are right.

**Pull request merged**
