### PR TITLE
New Extension: Pins

### PR DESCRIPTION
**Pull request by SKaplanOfficial**
## Description

This extension adds a pin management system and an associated menu bar extra that displays the user's current pins. Pins can be anything with a URL or path, so users can pin websites, files, folders, apps, and more (e.g. the URL to a specific note).

The current commands include:
1. Show Pins - Initiates the menu bar extra
2. View Pins - Lists all pins, allows you to edit existing or rearrange existing pins
3. View Pin Groups - Lists all groups, allows you to edit existing groups
4. New Pin - Creates a new pin with a given name, URL/path, icon, and group assignment
5. New Pin Group - Creates a new group with a given name and icon
6. Copy Pin Data - Copies a JSON representation of your pins and groups to the clipboard
7. Import Pin Data - Imports a JSON string containing pins and groups

## Screencast

An example of pins and groups in the Pins menu

See the YouTube video here:
[https://youtu.be/rb-_R8wXnyY](https://youtu.be/rb-_R8wXnyY)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Ek2100** [comment]
This looks so cool lmao. Tell me when its approved so I can download

**Comment by pernielsentikaer** [comment]
Is this ready to be published 😊

**Comment by SKaplanOfficial** [comment]
@pernielsentikaer Yes, it is 😄

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
