### PR TITLE
Add imageoptim extension

### PR DESCRIPTION
**Pull request by marckohlbrugge**
## Description

Compresses images with [ImageOptim](https://imageoptim.com/mac). It's a free, open-source app that compresses your images on device. So unlike other extensions, there's no need for an API key, your images never leave your computer, and it's 100% free to use.

## Screenshot

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- The extension crashes if you don't have finder active, could you handle this gracefully?

Raycast 2024-09-22 at 20 47 16


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by marckohlbrugge** [comment]
@pernielsentikaer Thanks for the heads up. I've fixed the issue. It now shows a toast instead.

CleanShot 2024-09-22 at 21 32 14@2x

**Comment by pernielsentikaer** [comment]
Should we add a list of accepted file types and show an error instead? That would be pretty cool. Are you up for that?

**Comment by marckohlbrugge** [comment]
Unfortunately I wasn't able to find an exhaustive list of supported files.

However, the good news is that ImageOptim handles unsupported file types gracefully (i.e. just skips them).

So I think it's better NOT to build in any allow list. This way the extension is future proof and we don't risk accidentally disallowing certain file types that are actually supported. (now or in the future).

What do you think?

**Comment by pernielsentikaer** [comment]
Let's do that 🙂

**Pull request merged**
