### PR TITLE
[CSS Tricks] use wp-json search API for now (close #14614)

### LINKED ISSUE #14614: [CSS Tricks] Delete this Extension
### Extension

https://www.raycast.com/j3lte/css-tricks

### Raycast Version

-

### macOS Version

-

### Description

I'm the author of this extension. [CSS Tricks](https://css-tricks.com/) has deprecated their Search API, so this extension has become useless and obsolete. Please remove the extension from the Store.

### Steps To Reproduce

- Open Extension
- Search will result in an error. I have traced it back to the website undergoing changes.

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by xmok**
## Description

As mentioned in #14614 the site seems to no longer have the Jetpack search so I have replaced the endpoint with the WordPress REST API search endpoint - this API is usually enabled in most WordPress installations unless explicitly disabled. The drawback of this endpoint is we no longer have dates as they are not returned but otherwise this is a nice workaround and will mean we don't need to remove the extension from the store 😀.

@j3lte what do you think?

## Screencast

https://github.com/user-attachments/assets/c4156759-d0ff-4352-b378-3e70edd83d39

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by j3lte** [comment]
@xmok awesome update, thanks! Doesn't matter that we don't have the date, we can probably do something with the detail view that tries to download the HTML. I was about to retire this extension because search was broken, you fixed it 😄 👍

**Comment by xmok** [comment]
Awesome! One approach we can use is to have a `List.Dropdown` and ask user to specify "post" or "page" for searching - in that case we can use the /posts and /pages endpoints which expose more data such as *date*, *content*, *status* but of course the drawback is we can only get posts or pages at a time rather than both together.

Showing in a separate Detail View is a great idea tho and might be clean 👀.

**Comment by pernielsentikaer** [comment]
Is this ready, or not quite yet?

**Comment by xmok** [comment]
It's ready from my side as `Detail` view can be added in future PR. Up to @j3lte for final decision.

**Comment by j3lte** [comment]
@xmok I'm OK with you adding a Detail view 👍

**Comment by pernielsentikaer** [comment]
Should we merge now, or would you prefer to implement it first?

**Comment by xmok** [comment]
Came up with this quick detail view:

https://github.com/user-attachments/assets/d3dbbb6e-b8b4-4f74-94d2-284ae61804fc

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
