### PR TITLE
Add project-companion extension

### PR DESCRIPTION
**Pull request by maximedaraize**
## Description

This extension help you manage your projects by allowing to:

- List all your projects with their details.
- Add quick link to your prefer link (roadmap, design, website, etc).
- Tag your projects status (backlog, in progress, completed, etc).
- Search and Filter by project name or status.

## Screencast

https://github.com/raycast/extensions/assets/37809938/2d80b22f-aab5-472b-9cc1-0ef907ceddc2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- How do you use it? I can't see the example video where you maybe explained it?

- When deleting a Project it should maybe show a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert?q=confirmAlert)

- The `Delete Project` action should have the `style={Action.Style.Destructive}` 🙂

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by maximedaraize** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * How do you use it? I can't see the example video where you maybe explained it?
> * When deleting a Project it should maybe show a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert?q=confirmAlert)
> * The `Delete Project` action should have the `style={Action.Style.Destructive}` 🙂
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.




Thank you for the feedbacks! I am sorry you are not able to see the video (i'll try to upload it again.)

### How to use it?
The Project Companion Raycast Extension allows you to manage your projects directly from Raycast.
Use it to store project information like name, description, status, and links.

You can update or delete created project, and search by project name or status.
The description field allows you to add more details about your project and support Markdwon syntax.

This is ideal for developers, designers, and project managers who want to keep track of their projects in one place.


I am a frontend dev in a agency and for me the extension is useful because i can quickly
- update the projects status I am working on.
- Add quick note on the project during client meeting
- Have a quick link access to either link i need (website, jira, backend, etc)
- Also by working with shopify theme, having the ability to access easily theme and store backend with the favorite link feature is really fun.

Hope this explain how i use this extension a little better.

*I have update the Readme with those information and the Changelog file with the fixes you asked 👍🏻.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
The video worked as expected this time 🙂

I have now tested your extension again, and I have some feedback ready for you:

- It's possible to add a new Project without entering anything at all, maybe you can add some validation with [useForm](https://developers.raycast.com/utilities/react-hooks/useform)

- Change Delete Projects hotkey to `^+X` as Raycast does it

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by maximedaraize** [comment]
> * hotkey



> The video worked as expected this time 🙂
> 
> I have now tested your extension again, and I have some feedback ready for you:
> 
> * It's possible to add a new Project without entering anything at all, maybe you can add some validation with [useForm](https://developers.raycast.com/utilities/react-hooks/useform)
> * Change Delete Projects hotkey to `^+X` as Raycast does it
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Thanks again @pernielsentikaer for the feedbacks. 

Both have been corrected ✅.
I have added validation on the project title only, so user who do not have all the information can still create a project. They will be able to edit the rest later if they need to.

The validation was applied on the create and edit forms.

Let me know if you have other questions 🙏🏻

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
