### PR TITLE
[Linkwarden] fix #13613 (API uses Bearer Auth)

### LINKED ISSUE #13613: [Linkwarden] ...
### Extension

https://www.raycast.com/leodbrs/linkwarden

### Raycast Version

1.79.1

### macOS Version

14.5

### Description

Maybe I'm a bit slow today, but i cant log into the raycast extension w. my Linkwarden credentials. I've created an API key in LW and am giving the extension my https:// url - yet I keep getting the "unauthorized" message. Can you point me in the right direction? Or did LW's latest update broke compatibility? 

### Steps To Reproduce

cant login to LW in the extension

### Current Behaviour

"failed to fetch latest data: unauthorized" 

### Expected Behaviour

Loggin in correctly

### PR DESCRIPTION
**Pull request by xmok**
## Description

- close #13613 by changing the auth method to `Bearer`
- very minor refactor of utilizing `mapResult` and `initialData` of `useFetch`

## Screencast

The screencast shows first store and then updated version:

https://github.com/user-attachments/assets/d5ad3d4c-7d59-41cd-92a3-d85505e04ad0

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
It looks like a really good fix, @leodbrs. Can you also check this?

Is there a reason why the API key is not working anymore?

**Comment by xmok** [comment]
Hi.
I'm not sure how it was in the past but I installed Linkwarden on my server yesterday which is when I tried out the API and the Raycast Extension. Looking into the code I saw Linkwarden uses `getToken` from `next-auth/jwt` and as per documentation at https://next-auth.js.org/v3/configuration/options#jwt-helper, we can read the token using `Bearer` so I modified accordingly. Going through some of the issues e.g. https://github.com/linkwarden/linkwarden/issues/600 this seems correct.
Hope this helps.

**Comment by pernielsentikaer** [comment]
Can you verify @leodbrs

**Comment by leodbrs** [comment]
Hello,

thanks @xmok for the update 😀

Everything is okay for me @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
