### PR TITLE
[Zotero Extension] FIX: make all icons at 512x512 resolution

### PR DESCRIPTION
**Pull request by sadanand-singh**
## Description

Update all icons to 512x512 resolution

## Type of change

- Other (Specify) - Update icons to 512x512 size

## Screencast

No Changes

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @sadanand-singh 👋 

Thanks for the updated logo 💪 

Actually, it's only the icon specified in package.json that needs to be in 512x512px, it would be better to resize doc/paper.png down again in order to save space (and while you're doing that, could you check that your doc/paper images

Could you provide a test account like last time so I'm able to give it a quick spin again? Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) with the details

**Comment by sadanand-singh** [comment]
> Hi @sadanand-singh 👋
> 
> Thanks for the updated logo 💪
> 
> Actually, it's only the icon specified in package.json that needs to be in 512x512px, it would be better to resize doc/paper.png down again in order to save space (and while you're doing that, could you check that your doc/paper images
> 
> Could you provide a test account like last time so I'm able to give it a quick spin again? Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) with the details

Icons have been fixed. For the test account, please use following credentials:

API key: `hGWA50TsfvKh2LUlG9UDD9Rp`
user_id: `8739349 `

Please let me know once done, I will remove this account.

**Review by pernielsentikaer — COMMENTED** [review]
Hi @sadanand-singh 👋 

I just gave it a quick test run and I only have a single question 

- zoteroApi.ts in the parseResponse function

Dates are not in the same format, is that normal? It's causing the formatting with .getFullYear() to be showing wrongfully output

Actual format:
FQUwQm8MdaSCSt5q
Outputs:
ljZ8AyC07VJf9XtL

**Comment by sadanand-singh** [comment]
> Hi @sadanand-singh 👋
> 
> I just gave it a quick test run and I only have a single question
> 
> * zoteroApi.ts in the parseResponse function
> 
> Dates are not in the same format, is that normal? It's causing the formatting with .getFullYear() to be showing wrongfully output
> 
> Actual format: FQUwQm8MdaSCSt5q Outputs: ljZ8AyC07VJf9XtL

Yes, I have tried to look into it in the past. However, zotero parsing is not great. its dates in all random formats and hence I just could not do anything. Probably we would need more detailed code to try to infer all different date formats output by zotero. For  the time being I decided to leave as it is.

**Comment by pernielsentikaer** [comment]
> Yes, I have tried to look into it in the past. However, zotero parsing is not great. its dates in all random formats and hence I just could not do anything. Probably we would need more detailed code to try to infer all different date formats output by zotero. For the time being I decided to leave as it is.

A simple way to suppress as a temporary solution would maybe be like ```!isNaN(date.getFullYear()) ? date.getFullYear():''``` in the accessoryTitle - It would be better than showing NaN

**Comment by pernielsentikaer** [comment]
Awesome @sadanand-singh 💪 

The last thing that we could change is package.json line 13 where the word "Zotero" is redundant since it's in the subtitle and logo - Besides that I think I'm happy and ready to go :)

You may delete the access again 😄

**Pull request merged**
