### PR TITLE
Add call extension

### PR DESCRIPTION
**Pull request by mikejhan4455**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

Given that `FaceTime` is the default phone app on MacOS, do you think your extension has any practical difference from this `FaceTime` extension? https://www.raycast.com/ron-myers/facetime

**Comment by mikejhan4455** [comment]
Hi! Thank you for your reply!

I checked the `Facetime` extension you mentioned and found that it uses `facetime://` to initiate a Facetime call (https://github.com/raycast/extensions/blob/34c65c7f190ad172e46c75384600aa938f932e98/extensions/facetime/src/call.tsx#L20C9-L20C9).

Since I rarely use Facetime, most of the time I prefer to make phone calls from my Mac, which is different from the behavior of the extension. Instead, I use `tel://` to initiate a phone call.

**Comment by pernielsentikaer** [comment]
I was making the same extension at the moment, here is what I had, feel free to use some of it 🙂 I added both `fallbackText`, `arguments` and `getSelectedText`

```
import { LaunchProps, getSelectedText, open, showHUD } from "@raycast/api";

export default async function Command(props: LaunchProps<{ arguments: Arguments.QuickDial }>) {
  const { fallbackText } = props;
  const { number } = props.arguments;

  let dialNumber = fallbackText || number;
  if (dialNumber === "") {
    try {
      const selectedText = await getSelectedText();
      if (selectedText !== "") {
        dialNumber = selectedText;
      }
    } catch (error) {
      console.error(error);
    }
  }

  dialNumber = dialNumber.replace(/\s/g, "");

  try {
    await open(`tel://${dialNumber.trim()}`);
    await showHUD(`Opening facetime calling ${dialNumber}...`);
  } catch (error) {
    console.error(error);
    if (error instanceof Error) {
      await showHUD(error.message);
    }
  }
}
```

**Comment by mikejhan4455** [comment]
Hi, I'm sorry.
I encountered a merge problem and faced some issues.

When I run `npm run publish`, I encountered a checkout problem.

image

I chose to solve it in the wrong way by deleting the forked repository.
Now I'm going to restore the repository first.

**Comment by mil3na** [comment]
Hi! Are you planning on doing any change to your extension based on Per's comment or should I continue to review as-is? If there are changes to be made, please mark it as a draft and ping us when you are ready :)

**Comment by mikejhan4455** [comment]
I'll try to fix the publish problem in days, and modify the code based on Per's suggestion.

**Comment by mikejhan4455** [comment]
> Hi, I'm sorry. I encountered a merge problem and faced some issues.
> 
> When I run `npm run publish`, I encountered a checkout problem.
> 
> image
> I chose to solve it in the wrong way by deleting the forked repository. Now I'm going to restore the repository first.


I'm still experiencing this error and don't know how to fix it.
Can someone please give me some advice? Thank you.

**Comment by mil3na** [comment]
Hi! According to the error, you might have uncommmited changes. Have you tried running `git checkout main` by itself and see if there's more detail to the error?

**Comment by mikejhan4455** [comment]
> Hi! According to the error, you might have uncommmited changes. Have you tried running `git checkout main` by itself and see if there's more detail to the error?

I’ve seen both my extension repo and my forked repo of ’raycast/extensions’ and found no uncommitted  changes on every branches.
And ‘git checkout main’ runs success fully.

**Comment by pernielsentikaer** [comment]
@mikejhan4455 If you have all the code you could branch out from raycast:main in a new branch and open a new PR instead 🙂

**Pull request closed without merging**
