### PR TITLE
New Extension: PurpleAir

### PR DESCRIPTION
**Pull request by omarshahine**
## Description

This is a new extension that lets you view data for a [PurpleAir](http://purpleair.com) Air Quality Monitor which you can read about [on my SubStack](https://www.omarknows.com/p/purpleair-air-quality-monitor)

## Screencast

purpleair-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Could you remove the .gitignore in the root of the PR 😊

**Comment by omarshahine** [comment]
> Hi 👋
> 
> Could you remove the .gitignore in the root of the PR 😊

Done

**Comment by pernielsentikaer** [comment]
When having a wrong API key, it dies. Could you maybe look into this and return an empty array so we can show a no results or error screen?

Raycast-vTEukCrM@2x

**Comment by omarshahine** [comment]
Will take a look and figure out a graceful way to address that. Sorry for not catching.

**Comment by omarshahine** [comment]
> When having a wrong API key, it dies. Could you maybe look into this and return an empty array so we can show a no results or error screen?
> 
> Raycast-vTEukCrM@2x

Ok, added some error handling. If you need an API key to test with let me know and you can use mine.

**Comment by pernielsentikaer** [comment]
Hi @omarshahine 👋 

I updated the extension a bit. Could you look into the corrections and test if it works as expected? I'd like to try a key. Are you in [Slack](https://www.raycast.com/community)

**Comment by pernielsentikaer** [comment]
Let merge it 🔥

**Pull request merged**
