### PR TITLE
[Update Obsidian Extension] Pinned notes command, new actions, new preferences

### PR DESCRIPTION
**Pull request by marcjulianschwarz**
## Description
- Add `Pinned Notes` command which shows a list of pinned notes for every vault. You can pin and unpin notes with the `Pin Note` and `Unpin Note` actions (both available in `Search Note` and `Pinned Notes` command).
- Add option to display detail views for `Search Note` and `Pinned Notes` command.
- Add option to hide LaTeX in Quick Look and detail view
- Add customizable folder actions for `Create Note` command (quickly create a note in a folder)
- Add option to open note on creation for `Create Note` command
- Add option to specify default name for notes without name for `Create Note` command
- Commands with only one vault will now trigger directly without prior selection
- Minor other fixes (e.g. store images, restructuring project structure, etc.)

Closing issues #1443 and [this one](https://github.com/marcjulianschwarz/obsidian-raycast/issues/14).

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @marcjulianschwarz 👋 

I just tested your extension and it works as expected, awesome! 🔥 

Could you look into two things:

- Check and correct the [linting errors](https://github.com/raycast/extensions/runs/6256397863?check_suite_focus=true).
- Instead of having both a `Pin` and `Unpin`, why not just have a dynamic Action instead only showing what's possible?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by marcjulianschwarz** [comment]
Hi @pernielsentikaer,

thank you for the quick review!
Corrected the linting errors and implemented your suggestion. Thanks for the idea with having a dynamic action instead, it works great like this.

**Comment by pernielsentikaer** [comment]
Hi @marcjulianschwarz 👋 

Awesome, it works so much better now 🔥 

One last thing that could make the UX a bit better is to add [something like this](https://developers.raycast.com/api-reference/user-interface/list#list.item.accessory):

CleanShot 2022-05-03 at 05 47 14@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by marcjulianschwarz** [comment]
Hi @pernielsentikaer,

thank you for this great suggestion! It is now implemented.

**Review by pernielsentikaer — APPROVED** [review]
Hi @marcjulianschwarz 👋 

Thanks for your contribution. I tested it, and it works as expected 🔥

**Comment by marcjulianschwarz** [comment]
Hi @pernielsentikaer,
thank you very much for the review!

**Pull request merged**
