### PR TITLE
Add typeid-generator extension

### PR DESCRIPTION
**Pull request by jwalton9**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

I think this is already a part of https://www.raycast.com/jmaeso/uuid-generator, can you check that one out?

**Comment by jwalton9** [comment]
> Hi 👋
> 
> I think this is already a part of https://www.raycast.com/jmaeso/uuid-generator, can you check that one out?

Hey, The generator part definitely is, but this extension also add's the ability to convert between typeid and uuid. Which `uuid-generator` does not. I'm not sure that fits within that extension. But let me know if you think I should propose these additional features there instead

**Comment by pernielsentikaer** [comment]
What do you think @jmaeso 🙂

**Comment by jmaeso** [comment]
Hi 👋 !

For uuid generator extension, I already manifested in the past that the main goal should be to keep the uuid generation as simple as posible within minimal keystrokes required. Extra functionalities could be added there.
This being said, TIL about typeid, and not sure how that's related to uuids. 

Is that usecase really frequent and I just don't know it? Then might have a fit to my extension
Is that usecase rare and specific for very few people? Then might be better to isolate it

Since I can't decide if I miss some knowledge vs that knowledge being "rare" I can't take a decision.

Hope my 5 cents are helpful

**Comment by jmaeso** [comment]
Note: I see now this typeID <--> uuid conversion is based on UUIDv7 not any UUID version
Note2: A good explanation on the topic: https://github.com/jetify-com/typeid
Note3: FYI The icon used on this extension is a company logo (jetify) and not mentioned anywhere, not sure if that's important or not

**Comment by pernielsentikaer** [comment]
Could you answer here @jwalton9

**Pull request closed without merging**
