### PR TITLE
Add LinkedIn extension

### PR DESCRIPTION
**Pull request by HenriChabrand**
## Description

Add LinkedIn extension, allowing user to searh people and company from Raycast.

## Type of change

- New extension

## Screencast

Screenshot 2021-10-28 at 17 13 02
Screenshot 2021-10-28 at 17 13 31

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by HenriChabrand** [comment]
Hello @fe9lix 👋

I've made the change requested – I've removed the need for a user to copy/past its LinkedIn cookie.
Instead, I'll get it directly from his Keychain store (✨).

Works fine on my side, but I think I granted the Keychain access while developing it.
So I'm not sure what will be the expérience from a new user point of view after installing the extension.

If you can record a quick Loom while installing and launching it for the first time – that would help me improve the experience.

Thank you 🙌

**Comment by PitNikola** [comment]
Hey @HenriChabrand. I've just tried running it with keychain access, but unless you press "Always Allow", the pop ups will appear again and again. Unfortunately pressing "Always Allow" is quite dangerous practice because permission will be set for a particular process (in this case `security` process) making it possible for other extensions and even apps to access it as well without any prompts. You can confirm it by running this command in terminal:
```
security find-generic-password -s "Chrome Safe Storage" -a "Chrome" -w
```

Also, for what it's worth, even after pressing "Always Allow", the extension still doesn't work for me:
CleanShot 2021-11-02 at 19 32 50@2x

Does LinkedIn have normal API with some sort of API token authorization?

**Comment by HenriChabrand** [comment]
Hello @PitNikola 👋

Have you tried to make a search? If there is nothing input, no search is made.
And are you log in to LinkedIn with Chrome? 

As for the security part, I didn't know it was giving such broad access (!)
Maybe there is a way to only access cookies from the directory **once and store it within Raycast**.
So a user would only have to accept access once (until the cookie is revoked by LinkedIn, which for now in my case never happened for the past week)

But, as we are losing Raycast focus when the access request is prompted – I don't know if Raycast keeps the process in the background?
WDYT? 

As for your final question, I'm using LinkedIn unofficial API, which requires getting from the cookie `JSESSIONID` and `li_at` values.
So a user could simply copy-paste the whole cookie (like for the [Notion Search Extension](https://github.com/raycast/extensions/tree/main/extensions/search-notion) – but @fe9lix wasn't aligned with this experience for some obvious reason – hence this alternative.

**Comment by HenriChabrand** [comment]
Hello @PitNikola 👋

I manage to put in place the flow explained above 👆

User will only have to give access to the `Chrome Sage Storage` once – and then the Extension will work properly.

For example, running `security find-generic-password -s "Chrome Safe Storage" -a "Chrome" -w` will require the user to input his password again.

Here is the detailed flow:
[Raycast LinkedIn Extension Setup](https://www.loom.com/share/a030739921f24e678e3727869d8233e2)

**Comment by PitNikola** [comment]
@HenriChabrand, as we discussed in Slack, there are security concerns with letting this extension requesting keychain access to Chrome Web Storage, as well as UX issues for users who are not using Chrome Browser. Closing this PR for now, but feel free to publish it in your own repo, maybe some folks would find it useful. Thanks for your understanding!

**Pull request closed without merging**
