### PR TITLE
add iMessage 2fa code extract shortcut extension

### PR DESCRIPTION
**Pull request by yuercl**
## Description

iMessage Two Factor Authentication Code

## Screencast

preview

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tisfeng** [comment]
Good extension! I tried it, but it didn't seem to work,  cannot get the messages on M1 mac, did I miss anything?

image

**Comment by pernielsentikaer** [comment]
Hi 👋 

Thanks for the contribution 🔥 

We do also have #1954 in the queue which looks more or less like the same thing?

**Comment by yuercl** [comment]
> Good extension! I tried it, but it didn't seem to work, cannot get the messages on M1 mac, did I miss anything?
> 
> image

This tool can search within last 24 hours ago messages which may contain two factor auth code possibly.

**Comment by tisfeng** [comment]
@yuercl  I know, and I confirm that I have received SMS messages on my Mac within 24 hours.  I checked using the console log, it seems that it can't read the SMS.

I don't know much about the development environment of Apple desktop, but I am curious as to how the program reads the user's text messages without the user's knowledge and authorization to do so. This is inconsistent with what I understand to be Apple's system privacy policy.

My device: Apple M1 Pro, OS: 13.0 Beta(22A5373b)

image

**Comment by tisfeng** [comment]
Ok, I just pulled your latest code and it works as expected now. 🎉

**Comment by pernielsentikaer** [comment]
Could it be nice with a preference to select how long timespan you'll see 2FA codes, or is that irrelevant?

**Comment by tisfeng** [comment]
I used it and feel good.  I have a suggestion, could you add an action `Copy  to Clipboard` on the main page if the 2fa code is detected? so that the user can easily copy it to the clipboard after receiving the code, instead of going to the sub-page and then get it.

Also, it would be better to display the SMS details with [Detail](https://developers.raycast.com/api-reference/user-interface/detail) components, currently one line list  may not be able to display the full SMS content.

iShot_2022-10-13_17 53 30

**Comment by yuercl** [comment]
preview_2facode
submit a new version @tisfeng

**Comment by tisfeng** [comment]
Great, this extension will help many users who are used to receiving 2FA code on Mac, I'm looking forward to seeing it in the store!

**Comment by yuercl** [comment]
> Could it be nice with a preference to select how long timespan you'll see 2FA codes, or is that irrelevant?

- latest code has support preference search time gap.
- add new filter for search 2fa code or not.
- quick link to copy 2fa code in main list.
- improve ui that displays entire message content to list detail component.
@pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
