### PR TITLE
feat(visual-studio-code): add actions to remove entries

### PR DESCRIPTION
**Pull request by tmwrnr**
## Description

- add an action to remove a recent project entry
- add an action to remove all recent project entries, the user will be prompted for confirmation
- remove unused dependency `sql.js`

I used the `sqlite3` CLI directly, similar to the `useSql` hook, without using an npm package. Will this cause any problems?

## Screencast

SCR-20231206-qtyr

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi👋

Maybe we should add a toast that says it requires a restart of the client? It seems to be the case. I guess we can't do anything about that, right?

**Comment by tmwrnr** [comment]
Hi @pernielsentikaer  👋

> Maybe we should add a toast that says it requires a restart of the client?

Which client are you referring to? 😅

I had no problem removing entries and didn't require a restart from anything

**Comment by pernielsentikaer** [comment]
I was testing this in `Cursor` - here I had to restart before it happened

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
