### PR TITLE
Update antd-open-browser

### PR DESCRIPTION
**Pull request by crazyair**
## Description

1. change `https://ant-design.antgroup.com` to `https://ant.design`
2. edit `data.json`, sync component

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by crazyair** [comment]
Why does the image display abnormally?


image

The following figure is the original image


image

**Comment by pernielsentikaer** [comment]
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

Regarding the images, Raycast does support some SVGs but not all properties, that might be why 🙂

**Comment by crazyair** [comment]
How to set `dark` or `light` with  `List.Item.Detail` props `markdown`

**Comment by crazyair** [comment]
Added Chinese and English double characters


image

**Comment by crazyair** [comment]
> Regarding the images, Raycast does support some SVGs but not all properties, that might be why 🙂

Because SVG use `font-family="PingFangSC-Regular, PingFang SC"`

**Comment by crazyair** [comment]
image

Please open

**Comment by pernielsentikaer** [comment]
It seems like you deleted the repository in your end so I can reopen it
Raycast-S98g7G78@2x

You need to have only English in the list 😞

**Comment by crazyair** [comment]
> It seems like you deleted the repository in your end so I can reopen it Raycast-S98g7G78@2x
> 
> You need to have only English in the list 😞

Create a new https://github.com/raycast/extensions/pull/8747

**Comment by crazyair** [comment]
> You need to have only English in the list

Delete Chinese now, or wait until automatic language matching is supported in the future before making changes?

**Pull request closed without merging**
