### PR TITLE
feat: create pull request

### PR DESCRIPTION
**Pull request by dengshenkk**
## Screencast

image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @dengshenkk 👋 

What is this, seems to be something unfinished?

**Comment by dengshenkk** [comment]
> 你好@dengshenkk 👋
> 
> 这是什么，似乎还有什么未完待续的事情。

it's done

**Comment by pernielsentikaer** [comment]
Looks like it's something similar to [Bing Wallpapers](https://www.raycast.com/koinzhang/bing-wallpaper) in the store, or?

**Comment by dengshenkk** [comment]
ok, I didn't know there was an identical extension. close it

**Pull request closed without merging**
