### PR TITLE
Splitwise oauth

### PR DESCRIPTION
**Pull request by danpalmer**
## Description

Re-work of #10005 based on the updated codebase. Moves Splitwise to OAuth rather than manual API key configuration.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by danpalmer** [comment]
Note for the Raycast team, this is not currently using a Raycast hosted PKCE proxy, it's using one I'm hosting that is a fork of the one from @mathieudutour. I'll start a discussion on Slack, but it would be great to solve PKCE proxying once and for all and make this self-service for the rest of the community.

**Comment by mathieudutour** [comment]
I made a self-hosted proxy which you can access here: https://oauth.raycast.com/encrypt-form
We haven't communicated about it because we still have to polish it a bit (the functionality isn't going to change so you can still use it)

**Comment by maximilianzuern** [comment]
@danpalmer 
Thank you for your contribution 🎉 
LGTM!

**Comment by danpalmer** [comment]
@pernielsentikaer id rather get a self service version up and running to end all the back and forth if that's possible. I happy to switch to a Raycast hosted version of that, but the constant back and forth of getting new instances spun up is a bit of a damper on development so it would be great to solve this in a more permanent way.

**Comment by danpalmer** [comment]
Great, thanks for this, I'll get this updated soon.

**Pull request closed without merging**
