### PR TITLE
Color picker swift macros

### PR DESCRIPTION
**Pull request by thomaslombart**
## Description

Upgrade to the latest version of Swift Macros

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaspaulmann** [comment]
Thanks @thomaslombart this is soooo much nicer now!!!

**Comment by otakustay** [comment]
Sorry but I still get a swift compile error after pull the latest code:

```
npm run build

> build
> ray build -e dist

info  -  entry points [src/pick-color.ts src/menu-bar.tsx src/organize-colors.tsx]
error -  compiling swift package
build failed (src/pick-color.ts:5:26 import { pickColor } from "swift:../swift/color-picker";): failed to compile swift:
exit status 1

If this is unexpected, try to delete the extensions/extensions/color-picker/swift/color-picker/.raycast-swift-build folder and run this command again
```

Doesn't know the detailed error reason, and the `.raycast-swift-build` folder doesn't exist, do I need some preconfiguration in my macOS?

**Comment by thomaspaulmann** [comment]
> Sorry but I still get a swift compile error after pull the latest code:
> 
> ```
> npm run build
> 
> > build
> > ray build -e dist
> 
> info  -  entry points [src/pick-color.ts src/menu-bar.tsx src/organize-colors.tsx]
> error -  compiling swift package
> build failed (src/pick-color.ts:5:26 import { pickColor } from "swift:../swift/color-picker";): failed to compile swift:
> exit status 1
> 
> If this is unexpected, try to delete the extensions/extensions/color-picker/swift/color-picker/.raycast-swift-build folder and run this command again
> ```
> 
> Doesn't know the detailed error reason, and the `.raycast-swift-build` folder doesn't exist, do I need some preconfiguration in my macOS?

Do you have the [Swift toolchain](https://github.com/raycast/extensions-swift-tools?tab=readme-ov-file#requirements) 
installed?

**Comment by otakustay** [comment]
> Do you have the [Swift toolchain](https://github.com/raycast/extensions-swift-tools?tab=readme-ov-file#requirements) installed?

Yes, I just have swift toolchain installed, and I have `swift` command in my terminal:

```
Welcome to Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5).
Type :help for assistance.
```

The error remains exactly the same, wondering if I still lack some system components, or I have incorrect XCode version.

image

image

**Comment by thomaspaulmann** [comment]
> > Do you have the [Swift toolchain](https://github.com/raycast/extensions-swift-tools?tab=readme-ov-file#requirements) installed?
> 
> Yes, I just have swift toolchain installed, and I have `swift` command in my terminal:
> 
> ```
> Welcome to Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5).
> Type :help for assistance.
> ```
> 
> The error remains exactly the same, wondering if I still lack some system components, or I have incorrect XCode version.
> 
> image image

We resolved this internally. Check out [this](https://github.com/nodejs/node-gyp/issues/569) and you should be good to go. Sorry for the hassle. Next release of the API will automatically suggest the fix during build times.

**Pull request merged**
