### PR TITLE
Add TickTick extension.

### PR DESCRIPTION
**Pull request by viduycheung**
## Description

Add TickTick extension.

## Type of change

- New extension

## Screencast

CleanShot 2021-11-24 at 10 36 45@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @viduycheung 👋 

What a banger for the first contribution 💪 Everything works and errors is gracefully handled, well done 🥇 

A few comments:
- It would be cool if the results from the search also was grouped by date like the command.
- Add “Next 7 Days” command
- Add a “Create Task” command — not sure if it's even possible

Not all of above have to be in this PR if you just want it shipped, but would add a lot of value.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by viduycheung** [comment]
Hi @pernielsentikaer, thank you for your review.
I add the new "Next 7 Days Tasks"  command as you suggest.
For other suggestions, due to the TickTick app apple script support limit, I can't implement it right now, maybe develop in the future.

> Hi @viduycheung 👋
> 
> What a banger for the first contribution 💪 Everything works and errors is gracefully handled, well done 🥇
> 
> A few comments:
> 
> * It would be cool if the results from the search also was grouped by date like the command.
> * Add “Next 7 Days” command
> * Add a “Create Task” command — not sure if it's even possible
> 
> Not all of above have to be in this PR if you just want it shipped, but would add a lot of value.
> 
> Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

Hi @pernielsentikaer, thank you for your review.
I add the new "Next 7 Days Tasks"  command as you suggest.
For other suggestions, due to the TickTick app apple script support limit, I can't implement it right now, maybe develop in the future.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @viduycheung 👋 

Thanks for the update, that's an excellent update! 💪 

Comments:
- In both command, do you have access to the category they are in, so it looks like when searching
PaADJKDaraREUgOT

- Could you add a space between the emoji and the text easy, or is it just as good as it gets?
zGGdjGRgqPewvIkR

We're pretty close to merging 🥇

**Comment by viduycheung** [comment]
> Hi @viduycheung 👋
> 
> Thanks for the update, that's an excellent update! 💪
> 
> Comments:
> 
> * In both command, do you have access to the category they are in, so it looks like when searching
>   PaADJKDaraREUgOT
> * Could you add a space between the emoji and the text easy, or is it just as good as it gets?
>   zGGdjGRgqPewvIkR
> 
> We're pretty close to merging 🥇

All issue has been fixed ✌️

**Review by pernielsentikaer — APPROVED** [review]
Hi @viduycheung 👋 

Awesome update, it works as expected 🚀 

- I'm going to accept it and then my colleague will do a final review before merging 💯

**Comment by Gomeyy** [comment]
Hello, @viduycheung I've been using your extension and was wondering if it was possible to pull a filtered list of tasks? I was unable to find any documentation on the apple script support.
Thank you

**Comment by viduycheung** [comment]
> Hello, @viduycheung I've been using your extension and was wondering if it was possible to pull a filtered list of tasks? I was unable to find any documentation on the apple script support. Thank you

Hi, this extension future limit by TickTick macOS App Applescript support right now 🙈, maybe implement in the future~

**Pull request merged**
