### PR TITLE
Add installed-extensions extension

### PR DESCRIPTION
**Pull request by pernielsentikaer**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mil3na — CHANGES_REQUESTED** [review]
Hey Per! 

I'm reviewing your extension here. I have a few notes:

- When I first load it and don't have jq installed, after the error happens and the note on the bottom disappears, I cannot see why it doesn't work. Do you think it would be worth putting a note on the empty state like "it's empty or you don't have jq installed"?
- Would it be possible to open the settings when selecting an extension?
- Maybe for a future update: sorting!

Other than that, it looks good to me!

**Comment by pernielsentikaer** [comment]
> Do you think it would be worth putting a note on the empty state like "it's empty or you don't have jq installed"?

Good idea! I'll implement that!

> Would it be possible to open the settings when selecting an extension?

That's not possible (yet) in the API, but would indeed be cool, it would make sense if it opened extensions preferences for sure 🙂

> Maybe for a future update: sorting!

What kind of sorting do you want to have?

**Comment by mil3na** [comment]
Sorting alphabetically and by installed/update date would be a nice start!
By usage would be awesome, but not sure if it is possible.

**Comment by pernielsentikaer** [comment]
This version only sorts alphabetically, I have now added an empty view 🙂

**Review by mil3na — APPROVED** [review]
LGTM!

**Pull request merged**
