### PR TITLE
Update gpt

### PR DESCRIPTION
**Pull request by simicvm**
## Description

- Change name from `OpenAI GPT3` to `OpenAI GPT`
- Add support for `gpt-4` model
- Remove support for `code-cushman-001` and `code-davinci-002` models
- Update README.md

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by simicvm** [comment]
I changed the name of the extension (including the name of the extension folder). Will that be reflected on the Reycast store automatically?

**Review by pernielsentikaer — APPROVED** [review]

**Comment by kmahyyg** [comment]
A little feature request, can it support Azure OpenAI API endpoint?

**Comment by AbhishekTripathi** [comment]
The old extension is quite good as it gives control on creation of models and integrates with Azure.

**Comment by simicvm** [comment]
> Can you add support for gpt-4-1106-preview, the latest GPT-4 turbo model?

sure, I'll update it today or tomorrow.

**Comment by simicvm** [comment]
PR with new models here: https://github.com/raycast/extensions/pull/9271

**Pull request merged**
