### PR TITLE
Update jira-search extension

### PR DESCRIPTION
**Pull request by QuanDev2**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by svenwiegand** [comment]
@QuanDev2 please add a description to the PR describing the intention of the change. 

At least the prettier check fails.

**Comment by pernielsentikaer** [comment]
Could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

**Comment by QuanDev2** [comment]
Yeah sorry, the feature wasn't fully implemented yet. I thought I could publish a test version for my friends to test it. I didn't mean to publish the prod version yet.
That being said, I wanted to fork this extension, change its functionalities and call it something else (A different extension, based on this one). How do I do it? When I forked it, it only let me to improve this same extension. Thanks.

**Comment by QuanDev2** [comment]
> Could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

I'll close the PR 'cause it's not Prod ready, but could you please answer my question above? Thanks.

**Comment by pernielsentikaer** [comment]
If you change the name in the package.json, it will be installed as another "instance." You can also create a free organization and publish it for your friends 😊

**Comment by QuanDev2** [comment]
> If you change the name in the package.json, it will be installed as another "instance." You can also create a free organization and publish it for your friends 😊

Got it. Thank you. Have a nice day.

**Pull request closed without merging**
