### PR TITLE
Add indeed-key extension

### PR DESCRIPTION
**Pull request by iam43x**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

You extension is missing a description and a README file. Do you mind adding those in order to understand how your extension works, what it does and if it needs any setting to get it workin?

**Comment by mil3na** [comment]
Hey! Thanks for adding the README! However, I'm still missing how it is different from other OTP generators we already have on the store, like https://www.raycast.com/lachero/one-time-password

**Comment by iam43x** [comment]
> Hey! Thanks for adding the README! However, I'm still missing how it is different from other OTP generators we already have on the store, like https://www.raycast.com/lachero/one-time-password

this is an extension implementation of this ios application https://apps.apple.com/ru/app/indeed-key/id1541323258

`one-time-password` does not allow you to do what is required in indeed 


this is a more specific implementation

**Comment by mil3na** [comment]
Are you the developer of this iOS app? I don't see a service being used. 
What makes it different? What does it do that the other OTPs on our store don't? Can't this functionality be merged?

**Comment by iam43x** [comment]
> Are you the developer of this iOS app? I don't see a service being used. What makes it different? What does it do that the other OTPs on our store don't? Can't this functionality be merged?

no, I’m not an iOS developer) this is a specific implementation for working with the indeed service in this implementation there are other qr and another method of obtaining the secret, it is more complex, any features can be merged into 1 extesion but I’m not sure that we would like to see this in the raycast store

---

https://indeed-company.ru/ this provider otp

**Comment by iam43x** [comment]
https://www.raycast.com/lachero/one-time-password

> To migrate Google Authenticator, follow these steps:
> Export your accounts from the “Authenticator” app by Google
> Scan the QR code

this is the extension description >> `google` provider
and indeed-key >> `indeed` provicer

I think these are two different extensions with different fates

**Comment by mil3na** [comment]
I'm curious on how this interacts with the service without making any service call. Can you calculate an indeed key without having indeed on your computer or calling an API? I need a bit more context and, if possible, a test QR.

**Comment by iam43x** [comment]
> I'm curious on how this interacts with the service without making any service call. Can you calculate an indeed key without having indeed on your computer or calling an API? I need a bit more context and, if possible, a test QR.

qr contains [passphrase, init vector, period and how digits otp count] , deviceID = masterkey for derive secret key

1. passprase + iv + masterkey >> derving secretKey
2. secretkey + period + time + algorithm(hmac512 hashing) >> otp = hash(time, secretKey) / digits 

qr for testing i can`t shared because it`s private information)) its realy work :D

the entire workflow without other APIs and guaranteed by a crypto algorithm :)

**Comment by mil3na** [comment]
My concern is that this algorithm seems to be public, which is a security flaw by itself. 
Do you have any readings on how it is secure and how many people use this service?

**Comment by iam43x** [comment]
> My concern is that this algorithm seems to be public, which is a security flaw by itself. Do you have any readings on how it is secure and how many people use this service?

https://en.wikipedia.org/wiki/Time-based_one-time_password the whole world)) my implementation differs only in that the secret is obtained in 2 steps and not in one - which is safer))

**Comment by mil3na** [comment]
So you are generating the OTP yourself, is not part of a service?

**Comment by iam43x** [comment]
> So you are generating the OTP yourself, is not part of a service?

yes! but in addition to generation, the extension also decrypts (prepares) the secret for generation

**Comment by mil3na** [comment]
I still think, if it is not a service but just a way to encrypt/decrypt OTPS, it fits well on the existing extensions. I encourage you to add your changes on one of them.

**Comment by iam43x** [comment]
> I still think, if it is not a service but just a way to encrypt/decrypt OTPS, it fits well on the existing extensions. I encourage you to add your changes on one of them.

okay, extension will remain in private store :C

**Comment by mil3na** [comment]
PR closed. Please contact us on Slack if you would like to discuss it further. https://raycast.com/community

**Pull request closed without merging**
