### PR TITLE
Update app-icon-generator extension

### PR DESCRIPTION
**Pull request by hunter-ji**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by hunter-ji** [comment]
I've just submitted a update for the App Icon Generator plugin. Added a bunch of new platforms. Pretty excited about it!

Quick heads up though – I'm a bit worried I might have messed up something with Git, especially around the contributors info. 
If you spot anything weird with the Git history or contributor credits, could you let me know? I want to make sure everyone's work is properly recognized.
Specifically, if you see any of these issues, please give me a shout:
* Missing or wrong contributor info
* Anything funky in the Git commit history

**Comment by pernielsentikaer** [comment]
Are you still around @hunter-ji

**Comment by hunter-ji** [comment]
Yes, I've been a bit busy lately, sorry. I'm planning on taking care of it today or tomorrow.

**Comment by pernielsentikaer** [comment]
All good, just wanted to make sure 🙂

**Comment by hunter-ji** [comment]
Thank you for your suggestions and waiting. 😊
I have kept the previous platform name in the latest version and added a statement that the platform name will be updated in a transitional manner in the next version.

**Comment by hunter-ji** [comment]
Of course! Welcome! 
But what I don't understand is why you want to change the platform name? You told me before that it will cause user configuration to be lost.

**Comment by pernielsentikaer** [comment]
I only changed labels, not the values afaik - if you keep the original values then it should be just fine 🙂

**Comment by pernielsentikaer** [comment]
Anytime, champ. I really like the extension and know it has huge potential, so of course I want to make it the best possible

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by hunter-ji** [comment]
Thank you! This is another interesting submission. Also, I am planning to make a new plugin!

**Pull request merged**
