### PR TITLE
[Figma] Add action to open pages of files

### PR DESCRIPTION
**Pull request by thomaspaulmann**
## Description

I've added an action that opens a submenu with all pages of a file. This is handy if you have project files in Figma that have multiple pages and you want to launch a specific page. The pages are cached similarly to the files, so it makes it fast to use.

- Add action to open pages of a file.
- Fix race condition when visited files are returned first. This causes flickering of the list.
- Do some extracting of components and hooks to make the code easier to read.
- Deduplicate visited files so that they only show up once in the list.
- Formatted the code with prettier (sorry, this causes quite some Git blames 😬).

_Note: Right now we don't have a loading indicator in the Action Panel submenu. Right now, folks see the "No results" first and then it updates to the pages when the network/cache is finished. This is something that we'll improve. If the pages are cached, it isn't really an issue._

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @michaelwschultz 

## Screencast

https://user-images.githubusercontent.com/12066405/142264063-70a77529-8d20-46c8-9907-493047898926.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @thomaspaulmann 👋 

Thanks for the addition, it's quite handy — I'm already using it 😄

I saw the “No results” in the ActionPanel, but again, it's only while loading (and only if not cached). You have to be quite fast with shortcuts in order to see it, and it's still adding the items even though the ActionPanel is open, so It's not that big deal for now.

Let's see if we need to change anything when the loading indicator will be available through the API, but for now, I don't think it breaks the UX. 

@michaelwschultz could you try it out and see if you have any feedback?

**Comment by michaelwschultz** [comment]
Looks great to me! Thanks @thomaspaulmann, what a cool feature. I've been trying to think of more ways to make this extension more useful. Glad others are doing the same. :shipit:

**Comment by thomaspaulmann** [comment]
> Looks great to me! Thanks @thomaspaulmann, what a cool feature. I've been trying to think of more ways to make this extension more useful. Glad others are doing the same. :shipit: 

I'm glad you like it. I found myself often jumping to specific pages and wanted to make it faster. 

Maybe we could add other commands to create new Figma files/jams. Not super often used commands but could be handy.

**Review by pernielsentikaer — APPROVED** [review]
Let's get this gem 💎  shipped 🚢  then 💪 😄

**Pull request merged**
