### PR TITLE
Add BetterTouchTool extension

### PR DESCRIPTION
**Pull request by dnnsmnstrr**
## Description
This extension allows running actions in [BetterTouchTool](https://folivora.ai/) via the [Scripting Interface](https://docs.folivora.ai/docs/1101_scripting_btt.html). There are currently two commands, one for running predefined actions and the other for running so-called [named triggers](https://docs.folivora.ai/docs/1002_named_triggers.html). These act as reusable functions, much like script commands in Raycast, but they can be assigned to any kind of shortcut or gesture, which makes them incredibly powerful. The command lists all available named triggers by using a new scripting API, [created upon request to support this use case](https://community.folivora.ai/t/get-a-list-of-available-named-triggers/30390/3?u=dnnsmnstrr), so it can currently only be tested with the latest alpha-build of the application.

## Screencast

Searching for and running an action (in this case to open the clipboard-manager bundled with BTT)

https://user-images.githubusercontent.com/3686989/219920786-2467cdd5-6a4d-4119-b68f-095f4d275012.mov  

Here I created an example trigger that call the `Show HUD Overlay` action with a custom text:

https://user-images.githubusercontent.com/3686989/219922528-7c8dff84-228b-4d97-a671-1fc886bd4f84.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by dnnsmnstrr** [comment]
Update: a stable version [has been released](https://updates.folivora.ai/bettertouchtool_release_notes.html), so this extension can be used/tested with the regular version of BTT,  starting at v4.034

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have one piece of feedback ready for you:

* Icons for Action Panel Items since the copy action has icon, then you should add icons for the other actions 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by dnnsmnstrr** [comment]
I think I messed something up badly with my commit, might have to retry with a new pull request...

**Comment by pernielsentikaer** [comment]
It seems like 😊 Could you make a new PR with the changes?

**Pull request closed without merging**
