### PR TITLE
Add inspire-search extension

### PR DESCRIPTION
**Pull request by errepuntopenco**
## Description

Add extension to search inspirehep.net. 
For more info, see README.md.

### CODE REVIEW

**Comment by mil3na** [comment]
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

One thing that I think would improve the UI of your extension would be to add the options you have on the list view to the detail view. I would be more inclined to want to copy the BibTeX for the article after reading its abstract, for instance. Does it make sense?

**Comment by mil3na** [comment]
Thanks, Riccardo! Ping me when you're done. I can re-open the PR in case it gets stalled.

**Comment by errepuntopenco** [comment]
@mil3na Just a quick ping to let you know thatI have added actions to the Detail View as you suggested.

**Review by mil3na — APPROVED** [review]
Thanks! LGTM! 🚀

**Comment by errepuntopenco** [comment]
Awesome, thanks!Quick question: I noticed that I forgot to push also the updated readme. Do I need to submit another pull request for that or is there an easier way to update it?On Jul 24, 2023, at 1:19 PM, Milena Araujo ***@***.***> wrote:﻿
@mil3na approved this pull request.

Thanks! LGTM! 🚀

**Comment by mil3na** [comment]
If it's something quick you can send me and I can commit it directly, to make things easier. But, for any changes, I would recommend making another PR

**Comment by errepuntopenco** [comment]
Thanks, I appreciate it!The new README is attached.On Jul 24, 2023, at 1:52 PM, Milena Araujo ***@***.***> wrote:﻿
If it's something quick you can send me and I can commit it directly, to make things easier. But, for any changes, I would recommend making another PR

**Comment by mil3na** [comment]
You cannot send files via Github like you send in an email.

**Comment by errepuntopenco** [comment]
Apologies. No worries, I will submit another pull request.On Jul 24, 2023, at 2:19 PM, Milena Araujo ***@***.***> wrote:﻿
You cannot send files via Github like you send in an email.

**Pull request merged**
