### PR TITLE
GitHub: Fixes notification icons

### PR DESCRIPTION
**Pull request by xilopaint**
## Description

- Fixes icons for issues and pull requests in `Notifications` and `Unread Notifications` commands.
- Standardizes the color for all the accessories in `My Pull Requests`.
- Fixes an issue where the pull request icon color for the `My Pull Requests Menu Bar` was not adjusted for dark mode.
- Updates icons for `Open My Pull Requests` and `Open My Issues` menu items in the `My Pull Requests Menu Bar` and `My Issues Menu Bar` commands.

## Screenshot

Screenshot 2024-04-05 at 08 32 32

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaslombart — COMMENTED** [review]
Thanks for the PR! This would involve making many calls to the GitHub API and could potentially impact performance, though. Is it possible to use something from the [`Notification` object](https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#about-github-notifications) instead, like `state_change`?

**Comment by xilopaint** [comment]
> Thanks for the PR! This would involve making many calls to the GitHub API and could potentially impact performance, though. Is it possible to use something from the [`Notification` object](https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#about-github-notifications) instead, like `state_change`?

Hey @thomaslombart, I tried to use this, but for some reason I'm not sure, I was unable to get the `state_change` reason in my tests. I got `author`, `mention`, `subscribed` as reasons, but never `state_change`. Could you help me here? I didn't notice any relevant performance impact from this pull request, but feel free to make any changes.

**Comment by thomaslombart** [comment]
Oh, I thought that `state_change` was actually a property but it's a value so we can't use it 🤦‍♂️

I don't think the performance change will be noticeable, but I'm more worried about a [potential rate-limiting](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28) since requests will be made for every notification list item. It's a shame GitHub doesn't have any GraphQL API for that.

**Comment by xilopaint** [comment]
> I don't think the performance change will be noticeable, but I'm more worried about a [potential rate-limiting](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28) since requests will be made for every notification list item. It's a shame GitHub doesn't have any GraphQL API for that.

Honestly, I find it unlikely that we will face rate limits. While working on this PR, I refreshed the menu bar icon many times, well beyond normal use, without facing any limits. The same with the `Notifications` command. But we can only be sure if we merge the PR and test the implementation with users.

**Review by thomaslombart — APPROVED** [review]
Yeah, let's see what happens.

**Pull request merged**
