### PR TITLE
Add linak-desk-controller extension

### PR DESCRIPTION
**Pull request by samuelkraft**
## Description

This extension allows you to control your standing desk manufactured by Linak via Raycast. 

## Screencast

https://github.com/raycast/extensions/assets/2223418/6fb8a393-4f82-4320-a874-cb29ba58efec

One of the most boring screencasts to watch, the desk takes a few seconds to change height so the toast is shown during that progress.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Can you handle errors gracefully so the extension doesn't crash

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Hi @samuelkraft 🔥 

I updated the code a bit, `launchCommand` will throw an error is the command it launches it disabled, so I added try catch, can you make sure I didn't break it 🙂

**Comment by samuelkraft** [comment]
> Hi @samuelkraft 🔥
> 
> I updated the code a bit, `launchCommand` will throw an error is the command it launches it disabled, so I added try catch, can you make sure I didn't break it 🙂

Tested and works great! Thanks @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
