### PR TITLE
New extension: Eagle

### PR DESCRIPTION
**Pull request by Yukaii**
## Description

Add [Eagle](https://eagle.cool/) app raycast extension.

### Show Application Info

Metadata-1

### Search item command

https://user-images.githubusercontent.com/4230968/164730646-44c62f41-42e9-4358-b652-34d2147a3b87.mp4

### Navigate Folder command

https://user-images.githubusercontent.com/4230968/164730622-17cb3cd3-8606-4e53-bbd2-7bb10176e897.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Yukaii** [comment]
> I can't figure out what the command "Application Info" does, can you clarify what it's used for?

@pernielsentikaer It shows the Eagle version and the build version [based on this API](https://api.eagle.cool/application/info). It only shows the info as a table and I'm sure people won't use this regularly. Maybe I should move it under the `ActionPanel` action? Or simply remove it.

**Comment by Yukaii** [comment]
I'm not sure why the GitHub action workflow failed with this message 😓 :

```
Error:   7:12  error  Invalid author "Yukai". HTTP client: Get "https://www.raycast.com/api/v1/users/Yukai": net/http: TLS handshake timeout
```

**Comment by pernielsentikaer** [comment]
> > I can't figure out what the command "Application Info" does, can you clarify what it's used for?
> 
> @pernielsentikaer It shows the Eagle version and the build version [based on this API](https://api.eagle.cool/application/info). It only shows the info as a table and I'm sure people won't use this regularly. Maybe I should move it under the `ActionPanel` action? Or simply remove it.

I'm not sure it makes any sense to have it at all. If you decide to keep it, I think the action in the Action Panel would be a better way.

**Comment by Yukaii** [comment]
Hi @pernielsentikaer, I decided to remove it for now 😸

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Yukaii 👋 

I still miss one thing, if Eagle is closed, I would then like to see a Toast or HUD saying that you'll need to have Eagle open to using this extension. Is that something you can do?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Review by pernielsentikaer — APPROVED** [review]
Awesome @Yukaii 👋 

Let's get it merged 🔥

**Pull request merged**
