### PR TITLE
Added initial version of extension "flypy-code-query"

### PR DESCRIPTION
**Pull request by absir1949**
## Description

Double-Pin is an input method based on Pinyin input method, which can be regarded as an improvement of Full Pinyin. By mapping each sound or rhyme containing multiple letters in Hanyu Pinyin to a certain key, each sound can be typed with two keys, which greatly improves the input speed of Pinyin input method.

flypy(Xiaohe Double-Pin) is a Chinese character input method. It is characterized by a phonetic and morphological scheme; each single character code is divided into four codes, the first two codes are for double spelling and the last two codes are for double form. flypy(Xiaohe Double-Pin) can be used only in the Double-Pin scheme, using the shape as a secondary code, and hooking up the single character code in the Pinyin input method, using it to assist you in quickly finding the single character you want to input.

This is an extension for quickly looking up the flypy(Xiaohe Double-Pin) code of Chinese characters.

## Screencast
screenshot
screenshot

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by absir1949** [comment]
😭can you help me ? i dont know how to fixed it....

**Comment by koinzhang** [comment]
Hi @absir1949 

Although I don't know the reason why your project build failed.
But the easiest fix is for you to recreate a new extension of the same name, then copy the source file in `/src` over and replace the code in this PR with the new extension code.

If you have any questions feel free to contact me in [slack](https://raycastcommunity.slack.com/archives/D035N2D6H19)

**Comment by pernielsentikaer** [comment]
Hi @absir1949 👋 

I fixed your empty state flicker and added some actions, I hope it's okay 😄 

Can you test it out and let me know if you're okay with the changes 💪

**Comment by absir1949** [comment]
@pernielsentikaer  😄 thank you for the review and optimize,i has checked  it.

now it is okay.

**Comment by pernielsentikaer** [comment]
Hi @absir1949 👋 

I updated the screenshots since they was not in the right format, do you have a wish for the screenshot text (send me two texts) or is it okay as I did them?

**Comment by absir1949** [comment]
@pernielsentikaer ok
the eg:

text:小鹤音形
text:小鹤双拼

**Comment by pernielsentikaer** [comment]
Last this @absir1949 - can you add a better description, I don't think that the end-user will understand what this is for 😄

**Comment by absir1949** [comment]
> Last this @absir1949 - can you add a better description, I don't think that the end-user will understand what this is for 😄

oh..i update the description in this issue. Do you think it makes sense now?

**Comment by pernielsentikaer** [comment]
I was actually thinking about [this one](https://github.com/raycast/extensions/pull/1631/files#diff-1f10f2365b9f4dfe532d06fe08728969e8fa6afc902cafe6faae342e64bc02f3R6), sorry for not being clear enough

**Comment by absir1949** [comment]
> I was actually thinking about [this one](https://github.com/raycast/extensions/pull/1631/files#diff-1f10f2365b9f4dfe532d06fe08728969e8fa6afc902cafe6faae342e64bc02f3R6), sorry for not being clear enough

OK，i update the des.now i think it is clear

**Pull request merged**
