### PR TITLE
Support inline Markdown for text properties

### PR DESCRIPTION
**Pull request by bkeys818**
## Description

Add a preference that enables the use of inline Markdown on text properties when creating a new database page.

## Screencast

https://github.com/raycast/extensions/assets/65252963/ba9504ce-8505-4d52-be06-221ccea2c3cb

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by bkeys818** [comment]
@thomaslombart, The only reason I didn't make it the default functionality is because I didn't want people who use `*` or `_` or something in page titles to be thrown off by the functionality change. If you think it's ok, I'd be more than willing to move the preference!

**Comment by thomaslombart** [comment]
I'd say that if people write Markdown in the text field, that would be expected on Notion's end. What do you think?

**Comment by bkeys818** [comment]
I agree. I'll get it changed!

**Review by thomaslombart — APPROVED** [review]

**Comment by bkeys818** [comment]
@thomaslombart Could you merge this when you get the chance?

**Pull request merged**
