### PR TITLE
[Color Casket] Now with Color Picker!

### PR DESCRIPTION
**Pull request by slavarazum**
## Description

Update [Color Casket](https://www.raycast.com/slava.razum/color-casket) extension with most requested **Color Picker** feature.

- color picker tool
- new `Pick Color` command
- ability to setup preferred color format

## Screencast

screenshot-1

screenshot-2

screenshot-3

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi @slavarazum 👋 

Thanks for the update, it looks good to me 🚀

**Comment by slavarazum** [comment]
@pernielsentikaer Thanks for the feedback and quick review 🤝

**Comment by BigBenITA** [comment]
maybe it's only a personal issues, but the picker don't show anything. Search che extension, select pick color and that's it. Maybe some problem with M1 version or Raycast?

**Comment by slavarazum** [comment]
@BigBenITA Tested on M1, everything works fine. You can create an issue with details.

**Comment by BigBenITA** [comment]
> 
 I've made a little video about my issues

[https://imgur.com/a/efBuKhC](url)

**Comment by slavarazum** [comment]
@BigBenITA Have you tried to reinstall extension?

Or maybe there is an issue with Apple Script.

To check it:

1. Try to open native application **Script Editor**
2. Paste `choose color` to the new document
3. Run script with "Play" button at the tool panel

Color picker should appear.

**Comment by BigBenITA** [comment]
> 2\. choose color

yes, via Apple Script it shows the color picker

**Pull request merged**
