### PR TITLE
✨ version 1 of the fathom analytics extension

### PR DESCRIPTION
**Pull request by DanielFerguson**
## Description

Added the [Fathom Analytics](https://usefathom.com) Raycast extension.

Quickly interact with your Fathom Analytics account straight from your desktop. Quick open to a site dashboard, create a site and retrieve a site code to install on your new project, delete a site and open to your main dashboard; all with the power and efficiency you've come to love from Raycast.

## Screencast

[Fathom Analytics Raycast Demo Video](https://www.youtube.com/watch?v=MWIztNmsCR4)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by DanielFerguson** [comment]
Aahhhh... I accidentally pushed changed for my typefully plugin into this merge request as well. 🤦‍♂️ Doh!

I'm sorry about that. It looks like things are building, is that alright? Let me know if you'd like me to do anything here. Apologies, rookie move on my part.

**Comment by DanielFerguson** [comment]
If it helps at all...

## Description

(For commit: 92b87c3)

- Added the ability to view recently scheduled drafts; tweets that are scheduled, but not yet posted, and
- Added the ability to view recently posted scheduled drafts

## Screencast

Recently posted drafts
Scheduled drafts

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

**Comment by danielsequeira** [comment]
Hi @DanielFerguson 👋 

Thank you so much for your PR. Would it be possible for you to remove the typefully changes from this one and create a new PR with them? Each PR should only contain changes regarding one extension.

**Comment by DanielFerguson** [comment]
Absolutely, @danielsequeira!

**Pull request closed without merging**
