### PR TITLE
Update dolar-cripto-ar extension

### PR DESCRIPTION
**Pull request by koaladlt**
## Description

Fixed Abort Controller Handling: Previously, users were seeing an error message indicating that fetch requests were being aborted. This was due to premature aborts caused by the Abort Controller logic. The issue has now been resolved by refining the abort controller handling and state management.

Improved Error Handling: Implemented a more robust error handling mechanism to ensure that only genuine errors are reported to the user, avoiding false alarms and improving the overall user experience.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mil3na — COMMENTED** [review]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

It looks good on my side. However, I see a lot of `console.logs`. Are they necessary or can you remove them?

**Comment by koaladlt** [comment]
> Hi! Thank you for your contribution! My name is Milena and I will be reviewing it today.
> 
> It looks good on my side. However, I see a lot of `console.logs`. Are they necessary or can you remove them?

Hey @mil3na, you're right, missed that! I just removed them all. Thanks for your feedback

**Comment by mil3na** [comment]
Hi! Did you forget to push your changes?

**Comment by koaladlt** [comment]
@mil3na Ups! now it's done

**Review by mil3na — APPROVED** [review]
LGTM!

**Pull request merged**
