### PR TITLE
Update tidyread---streamline-your-daily-reading extension

### PR DESCRIPTION
**Pull request by DophinL**
## Description

- add search rss page
- add generate digest in background
- add redirect route to improve onboarding experience
- improve gen digest panel
- add some feedback iamges in degest
- fix default maxItemsPerFeed 10 => 5

## Screencast

image

CleanShot 2024-02-02 at 12 52 52@2x

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by DophinL** [comment]
It's done, Most of the code come from svg, so don't worry about it! @pernielsentikaer 🙏

**Comment by DophinL** [comment]
No more commits now🫠

**Comment by DophinL** [comment]
No more commits now🫠

**Comment by DophinL** [comment]
Here is a bug in search list when scroll fast, let me fix in 1 hour.

**Comment by DophinL** [comment]
It's done, Most of the code come from svg, so don't worry about it! @pernielsentikaer 🙏

**Comment by DophinL** [comment]
It's done, Most of the code come from svg, so don't worry about it! @pernielsentikaer  🙏
With this change, users can add RSS more easily

**Comment by DophinL** [comment]
Add generate digest in background, cause sometimes long task(generate digest) in user interface will cause Raycast back to root

**Comment by DophinL** [comment]
No more commits, if you are ok for that, looking forward to release 🥰 @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Approved ✅

**Pull request merged**
