### PR TITLE
Add phone-call extension

### PR DESCRIPTION
**Pull request by karbassi**
## Description

Make a phone call with default telephone app. The default is usually FaceTime.

Code is based on [Ron Myers' Facetime extension](https://www.raycast.com/ron-myers/facetime).

## Screencast

phone-call-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
We already had this in the [queue](https://github.com/raycast/extensions/pull/7250) some time ago where it stalled, it was pretty close to done, maybe we could use that?

I don't think there should be too many rules about the number and formatting, it needs to work all over the globe 🙂

**Comment by karbassi** [comment]
> We already had this in the [queue](https://github.com/raycast/extensions/pull/7250) some time ago where it stalled, it was pretty close to done, maybe we could use that?

Thanks for sharing that. The PR had it's source file deleted. This PR is working. Could we use this moving forward?

> 
> I don't think there should be too many rules about the number and formatting, it needs to work all over the globe 🙂

I could remove the US-centric checks. Let me know if the team wants me to do that.

**Comment by pernielsentikaer** [comment]
Sure, I still think it has some great features that I also implemented - this way you can use it with selected text and arguments and fallback

```
import { LaunchProps, getSelectedText, open, showHUD } from "@raycast/api";

export default async function Command(props: LaunchProps<{ arguments: Arguments.QuickDial }>) {
  const { fallbackText } = props;
  const { number } = props.arguments;

  let dialNumber = fallbackText || number;
  if (dialNumber === "") {
    try {
      const selectedText = await getSelectedText();
      if (selectedText !== "") {
        dialNumber = selectedText;
      }
    } catch (error) {
      console.error(error);
    }
  }

  dialNumber = dialNumber.replace(/\s/g, "");

  try {
    await open(`tel://${dialNumber.trim()}`);
    await showHUD(`Opening facetime calling ${dialNumber}...`);
  } catch (error) {
    console.error(error);
    if (error instanceof Error) {
      await showHUD(error.message);
    }
  }
}
```
What do you think about that?

Yeah, I think we should move the US-centric checks since I it would trigger some scenarios in e.g. Denmark 🙂

**Review by pernielsentikaer — APPROVED** [review]
Awesome @karbassi 🔥 Let's get it in the store

**Pull request merged**
