### PR TITLE
[Authy Extension] (fix): speedup extension loading

### PR DESCRIPTION
**Pull request by guga4ka**
## Description

Refactor code to speedup  extension loading

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by guga4ka** [comment]
@gdsmith could you pls take a quick look, just to be up to date with changes

In top of this MR i want to add a few more, to support DeepLinks and export data to be safe from Authy API shutdown/changes

**Review by gdsmith — COMMENTED** [review]
Looks good, just one small suggestion

**Review by gdsmith — APPROVED** [review]

**Review by mil3na — APPROVED** [review]
LGTM

**Comment by exarus** [comment]
The device does not meet the minimum intergity ...

**Comment by guga4ka** [comment]
@exarus unfortunately, seems like Authy Extension is going to die. 

Here is a message witch any active user will receive with this update 

---
### Authy data breach
 Several days ago, Twilio has detected that threat actors were able to identify data associated with Authy accounts, 
 including phone numbers, due to an unauthenticated endpoint. Twilio has taken action to secure this endpoint and no 
 longer allow unauthenticated requests.
 More details are available [here](https://www.twilio.com/en-us/changelog/Security_Alert_Authy_App_Android_iOS)
 ### Extension current state 
 Due to changes in the Authy API, new installation onboarding is currently impossible. 
 I recommend exporting your extension data to enable migration to other 2FA apps.
 
 ----
 
I've tried to explore a changes at android version, but I don't have enough skills to find what did they changed at onboarding process. I even can't login to my account on mobile device. So, currently i'm thinking on next steps (thx to my paranoia i have a backup of Authy data and can move to another 2FA app like 2FAS or even put all eggs to one place and move OTPs to bitwarder)
 
Regarding Raycast integration here is a nice extension https://www.raycast.com/lachero/one-time-password i might contribute to it to support 2FAS export format, or just write a private 2FAS extension to own use. 

Might @gdsmith will find a way to communicate with Authy API, but after their latest moves i didn't trust Twillio any more

**Comment by exarus** [comment]
LoL. Migration is not possible from mobile app, so I seem to be done :D

**Comment by guga4ka** [comment]
@exarus i might help you here. In case you still have access to your mobile app, you can intercept traffic between app and authy servers via https://mitmproxy.org/ or something similar get responses, decrypt seed and migrate.

**Comment by LiranBri** [comment]
any alternative?

**Pull request merged**
