### PR TITLE
Update wireguard-manager extension

### PR DESCRIPTION
**Pull request by lostfutures**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by sxn** [comment]
hi @morbae – thanks fort he PR! Are you aware of the [Wireguard](https://www.raycast.com/sbugzhu/wireguard) extension that's currently available in the store? They both seem to work _very_ similarly. 🤔

**Comment by morbae** [comment]
I am aware of that, it is in fact the reason I wrote this extension, because it's taking 3-5 seconds to display the connection list for a reason I could not figure out, while my extension is displaying the list instantly on top of tracking recent and available connections. 
I just wanted to share the extension I'm using myself now, feel free to merge or not.

**Comment by pernielsentikaer** [comment]
Hi @morbae 👋 

There are two solutions that could work

* If this is a better extension, we could ask @sbugzu about letting this superseed the current
* Move your enhancements into the current and be added a contributor

It will be confusing for the end user having two extension with the same purpose 😊

**Comment by sbugzu** [comment]
> I am aware of that, it is in fact the reason I wrote this extension, because it's taking 3-5 seconds to display the connection list for a reason I could not figure out, while my extension is displaying the list instantly on top of tracking recent and available connections. I just wanted to share the extension I'm using myself now, feel free to merge or not.

Thanks for your feedback, I suspect it's a problem with getting the state through the loop, it's not obvious because my list is small, I'll try to solve it first.
If that doesn't solve we'll consider @pernielsentikaer 's suggestion

**Comment by pernielsentikaer** [comment]
This PR could also superseed if it has more features

**Comment by pernielsentikaer** [comment]
So we close this one and go with #5936?

**Comment by morbae** [comment]
I didnt have time to check #5936 but others seem to have checked and confirmed that it's equally fast ( assuming they tested it with more than 100+ connections ). so i'd say go ahead with #5936

**Comment by pernielsentikaer** [comment]
We could surely wait until you have time if you want to give it a spin?

**Comment by morbae** [comment]
just checked & can confirm the slow rendering of the list has been fixed. wish they added my nation flag code display as well but that's just eye candy.

**Comment by pernielsentikaer** [comment]
That would be a nice addition, if it's not implemented straight away I think we should add that soon in another PR CC: @sbugzu

**Comment by pernielsentikaer** [comment]
Closing this in favor of #5936

**Comment by sbugzu** [comment]
> That would be a nice addition, if it's not implemented straight away I think we should add that soon in another PR CC: @sbugzu

The https://github.com/raycast/extensions/pull/5936 PR already include this feature ;)

**Pull request closed without merging**
