### PR TITLE
Make Sesh Prettier

### PR DESCRIPTION
**Pull request by joshmedeski**
## Description

Makes sesh much prettier using the json formatted output from the sesh CLI!

## Screencast

ray01

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
You can take the [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) with out built-in tool instead, this will add some nice effects and transparency

**Comment by joshmedeski** [comment]
Very cool, I used that screenshot feature and added an additional screenshot!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by joshmedeski** [comment]
Thank you @pernielsentikaer! 🎉

**Pull request merged**
