### PR TITLE
New Extension: ESV Bible

### PR DESCRIPTION
**Pull request by cpenned**
## Description

The extension searches and looks up Bible verses from the English Standard Version using the ESV API. It contains includes two commands:

1) Lookup Verse: type a reference and see returned results
2) Search Bible: type a query and see a list of matching verses

## Screencast

[YouTube Link to Screencast](https://youtu.be/0qZ-nSUkwqU)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Would it be possible to ask for an application token instead so it's just using that one (so the end user doesn't have to get a token)

* Is it possible to show a failure toast if the wrong credentials are used?

* You could add the compliance to `README.md`

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by cpenned** [comment]
Thanks for the quick review, Peter! 

In response:

1. Unfortunately, the way they've set up the API, there are a few limitations on the key, the most relevant is one of scale. "You may only perform 5,000 queries per day, with no more than 1,000 requests in an hour and no more than 60 requests per minute. If you exceed these limits, your application will be throttled." With that limit, it wouldn't take many users to hit throttle limit. They also make a fairly big point about each key being for personal use only. More at https://api.esv.org/. Let me know if I'm misreading that?
2. Yes, you should get a toast failure message if you don't have a key or if it isn't correct. (see attached screenshot)
forbidden api message
3. Yes, added compliance to the README along with more details on how to get the key and instructions on customizing the extension.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for the update 🔥 

For the two commands I suggest you to have a look at [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview)

Instead of have it look like this

Raycast-2Pb90WSj@2x

It could look like this (which also supports custom image in ~128x128)

image

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
