### PR TITLE
New extension: Giphy

### PR DESCRIPTION
**Pull request by sadeqi-ah**
## Description

Create a new extension for Giphy.
A Raycast extension that lets you communicate with Giphy's API.
With this extension, you can search for Giphy's GIFs.

This extension has 3 commands:

`Search` -> Search GIF file on Giphy.
`Clear History` > Delete all the items from your history.
`Clear Favorites` -> Delete all the items from your favorites.

## Screencast

Giphy-01
Giphy-02
Giphy-03

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @sadeqi-ah 👋 

Thanks for taking your time to contribute 💪 Did you see that we have [GIF](https://www.raycast.com/josephschmitt/gif-search) in the `Store`

CleanShot 2022-07-10 at 05 56 20@2x

**Comment by sadeqi-ah** [comment]
> Hi @sadeqi-ah 👋
> 
> Thanks for taking your time to contribute 💪 Did you see that we have [GIF](https://www.raycast.com/josephschmitt/gif-search) in the `Store`
> 
> CleanShot 2022-07-10 at 05 56 20@2x

Hi @pernielsentikaer,
`Giphy` extension is only for [Giphy](https://giphy.com/). Unlike the extension in the store, this extension has pagination, and users can see **all their search results**. I think it is more practical.

**Comment by andreaselia** [comment]
Maybe it could be worth contributing the features you'd like to see in the existing extension rather than making a separate extension for it? 😁

**Comment by sadeqi-ah** [comment]
> Maybe it could be worth contributing the features you'd like to see in the existing extension rather than making a separate extension for it? 😁

Yes, you are right. Sure.

**Comment by pernielsentikaer** [comment]
Maybe we could hear @josephschmitt (who is the author of GIF) thinks 🙂

**Pull request closed without merging**
