### PR TITLE
[Google Drive] Use SQLite for indexing files cache

### PR DESCRIPTION
**Pull request by vishaltelangre**
## Description

Moves in-memory indexing + searching logic to SQLite to fix the following issue happening for users having Google Drive with a large number of files (1k+) (see https://github.com/raycast/extensions/issues/1523).

```
Error: Worker terminated due to reaching memory limit: JS heap out of memory
```

Besides,
- Code reorganization (from a single file into multiple files for better maintainability)
- Retains old fuzzy search logic while querying for the files from SQLite
- Implements cache invalidation logic
- The index gets rebuilt if it is older than 7 days
- Adds `Reindex Files Cache` action in the action panel to forcefully rebuild the cache on-demand (see the updated screenshot)
- Adds logic to automatically purge the temporary file previews in the `/tmp` directory to free up the disk space if it grows to more than 50 previews.
- Adds `Clear File Previews Cache` action in the action panel to clear the previews of the files generated in the `/tmp` directory.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by vishaltelangre** [comment]
@pernielsentikaer Can you please test + review? Cc @daniel-stoneuk

**Comment by vishaltelangre** [comment]
> For some reason, it's not loading for me at all, I simply get a blank, like so:

Hi @browneye1826, thanks for the report.

It is crashing for you because these fixes are not live yet. :) You are using it from the Raycast Store which will be updated automatically once this PR gets merged in. If you want to test these changes (before they go live), you will have to clone [my fork](https://github.com/vishaltelangre/raycast-extensions/tree/google-drive-sqlite) and run `git checkout google-drive-sqlite; cd extensions/google-drive; npm install && npm run dev` from that cloned repository. Once you do that, it will be available in Raycast (with these changes) and will look like this -

image

See https://developers.raycast.com/basics/contribute-to-an-extension.

If you don't understand these steps, that's fine as well. You'll just have to wait for this PR to get merged in until then. :)

**Review by pernielsentikaer — APPROVED** [review]
Thanks for the update @vishaltelangre, let's see how it goes 😄

**Comment by browneye1826** [comment]
Thank you so much @vishaltelangre! You are the best.

**Pull request merged**
