### PR TITLE
[Amazon AWS] Reduce throttling with typeahead commands sqs, secrets, logs

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- No unnecessary pagination with typeahead for SQS, Secrets and Logs commands. Pagination with typeahead is redundant.
- Added frecency sorting for SQS, Secrets and Logs command results.
- SQS: Reduced max items per search to 25 to reduce throttling, added mutation after sending message and purging.
- Secrets: Removed pre-loading resource policy and instead provided an ad-hoc action. This reduces throttling.
- Pipelines: Changed icons and improved mutation logic.

## Screencast

Refactoring to reduce throttles, can't really be captured with a screenshot.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

* closes https://github.com/raycast/extensions/issues/13296

### CODE REVIEW

**Comment by jfkisafk** [comment]
Hey @b0lle / @srikirank if you find some time please take a look.

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

It would be lovely if one of the authors/contributors with AWS access helped reviewing this. I will get back to this if we get no response.

**Comment by jfkisafk** [comment]
Appreciate it @mil3na 🫡 . Hey @b0lle , can you pull these changes and test it out since you were seeing throttling with Secrets Manager before? You can use [this guide](https://developers.raycast.com/basics/review-pullrequest).

**Comment by b0lle** [comment]
I will it this afternoon

**Comment by b0lle** [comment]
This worked like a charm. I also like the details metadata view :) 👍

**Review by b0lle — APPROVED** [review]

**Review by srikirank — APPROVED** [review]

**Comment by jfkisafk** [comment]
Hello @mil3na , we have the required approvals from contributors now. I'd greatly appreciate if you can take a look when you find some time

**Review by mil3na — APPROVED** [review]
LGTM!

**Pull request merged**
