### PR TITLE
[1password]: Display cached Items while refreshing

### PR DESCRIPTION
**Pull request by luizvergennes**
## Description

Refactored the current "My Passwords" command to use Raycast's useCachedPromise hook, to work with optimistic updates. With this there are going to be way less waiting time for fetching passwords. Also I removed the cache timeout, since the updates are fetched on "background" every time the user uses the command, bringing newly added passwords, instead of waiting 10 minutes each time.

Also added a new command that is able to auto renewal the CLI authorization by itself. According to 1Password CLI documentation, every request refreshes the 10 minute cooldown time for a new manual authorization. This command simply runs each 9 minutes getting the account info. For now I left it as a new command for it to be simple and the user understand what it does, but if it is preferred I could add to the main command with no problems.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Luk4h** [comment]
Currently working on a command that renews the Authorization each 9 minutes to avoid the unlock screen everytime I need to use a password...

**Comment by Luk4h** [comment]
Also there is a hard limit for the auto renewal of 12 hours, according to the [documentation](https://arc.net/l/quote/msmegmbi).

**Comment by Luk4h** [comment]
Last added commits, fix the issue where even if the items are loaded from cache you are not able to use it's actions. I also replaced the useCachedPromise with useExec that is focused in executing cli commands (pretty nice Raycast gj). This improved a lot of the performance.

**Comment by pernielsentikaer** [comment]
Thanks for the update @Luk4h 🔥 

@khasbilegt do you want to check this?

**Comment by Luk4h** [comment]
@pernielsentikaer This now should solve a lot of the issues regarding the extension. After getting this one merged I plan on working on issue #4744. Which has been long over due. Should be a simple fix, but I would like to put it in another PR since this one is getting WAY bigger than I expected. I have been using the this local version on my workflow and it has been working  seamlessly.

**Comment by pernielsentikaer** [comment]
Thanks for taking a stab - I tested it ok but would still like if @khasbilegt could check too

**Comment by khasbilegt** [comment]
Looks good to me, awesome work @Luk4h 👍🏻

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
