### PR TITLE
Add new Abstract API extension

### PR DESCRIPTION
**Pull request by andreaselia**
## Description

Abstract API is a platform that provides multiple API endpoints for different services. This extension starts off with the following commands:

- IP Geolocation
- Holidays
- Exchange Rates
- Company Enrichment
- Timezone
- Avatars
- Screenshot
- Scrape

## Screencast

https://user-images.githubusercontent.com/5033092/173051615-185e8cdb-7c0b-4471-99d6-b91ad72b6f44.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @andreaselia 👋 

Thanks for your contribution 💯 

I have some feedback and comments for you to look into:

- Should all the API keys be required? What if I just need one of them? 

- Do you think it's possible to format the input, but I guess it depends on purpose maybe?

- Maybe add so it's possible to copy/paste output?

- I can see a toast when using `Avatars`, I miss a description/form element saying that I need to hover the toast for actions. Also, both options fails for me - open in browser gives me `{"error":{"message":"Invalid API key provided.","code":"unauthorized","details":null}}` and download just gives an error toast

CleanShot 2022-06-13 at 10 44 39@2x

- In Holidays, shouldn't there be more data than this? Seems to do the same as Timezone?

CleanShot 2022-06-13 at 10 49 30@2x
 
- Seems like it's the same with `Scrape` - I miss a way to figure out what to do after generating 😄 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @andreaselia 🔥 

I gave it a new spin and it really starts looking good 💪 

> > In Holidays, shouldn't there be more data than this? Seems to do the same as Timezone?
> 
> I forgot to implement this, it was a copy of timezone. This has now been implemented.

I'm not sure how to use this? Tried multiple countries and multiple days without luck, what should it do?

CleanShot 2022-06-14 at 07 56 57@2x

- Could company enrichment also be formatted prettier?

As for the scrape command, I still think it's a bit clunky actually, is there a way to make \n break lines? I'm not sure the output here gives any sense as it but maybe I don't get the right use case 😄

**Comment by andreaselia** [comment]
>I'm not sure how to use this? Tried multiple countries and multiple days without luck, what should it do?

You need to enter the country code for this, e.g. US.

>Could company enrichment also be formatted prettier?

Just about to commit this in a few minutes.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @andreaselia 👋 

Thanks for the updates, I have a few things that would make the UX better:

### Avatar, Screenshot, Holidays
- Instead of using the toast, could we do something like this?

image

### Get IP Geolocation Info for Any IP, Get Exchange Rates for Any Currency
- Would be awesome if this was structured like `Get Company Enrichment Data`

image

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by andreaselia** [comment]
@pernielsentikaer changes made bud.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
