### PR TITLE
Update simple-icons extension

### PR DESCRIPTION
**Pull request by LitoMore**
## Description

- Add support for configuring the default action on detail view
- Update screenshot of detail view
- ~~Add screenshots of dark mode~~
- Bump all dependencies to latest version

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for the update 🔥 

Could you use the same background on all metadata images 🙂

**Comment by LitoMore** [comment]
@pernielsentikaer I intentionally used the macOS Sonoma dark mode background wallpaper.

This is more in line with the actual scenario.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
But they don't use the same, also all images should be in either dark og light mode - please don't mix them 🙂

Raycast09042024-II60n1tt png@2x

**Comment by LitoMore** [comment]
np. I just removed those dark mode screenshots.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
