### PR TITLE
[New Extension] X In Progress

### PR DESCRIPTION
**Pull request by anothertempore**
## Description

This PR adds a new extension with 2 commands, allowing to display year/quarter/month/week/day in progress in both command and Menu Bar. Also allowing to add your own progress, and manage your progress.

## Screencast

year-in-progress-6
year-in-progress-2
year-in-progress-3
year-in-progress-4
year-in-progress-5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 This might superseed [Year in Progress](https://www.raycast.com/thomas/year-in-progress), so it would also be nice to have the subtitle as it has - are you up for that? That way we need to move the code to the current Year in progress so it's going to be an update instead 😊

I have now tested your extension, and I have some feedback ready for you:

- When deleting a progress it would be nice to have a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert)
- You could add move up/down in the list, so it's possible to decide the order
- You can use [LaunchCommand](https://developers.raycast.com/api-reference/utilities#launchcommand) to update the menubar when you update the list in the other command
- I tried to make a new progress, but I got an error

image

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by anothertempore** [comment]
Hi @pernielsentikaer 

Thanks for your reply and suggestions! Let me fix the issues first, then move the code to Year In Progress :)

**Comment by anothertempore** [comment]
Oh I'm working on it, will push again these days!

**Comment by anothertempore** [comment]
Hi @pernielsentikaer 

> You could add move up/down in the list, so it's possible to decide the order

According to this one, I would like to clarify with you that do you mean add "Move Up" / "Move Down" options for each progress when pressing cmd + K?

Like this:
image

---

If so, I have another idea which is to add a "Pinned Progress" section to let user set which progresses to be pinned. What do you think?
image

**Comment by pernielsentikaer** [comment]
Both things is fine with me, what do you want the most? 😊

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for merging 🔥

- Can you look into why they're not showing the same result?

Raycast-wAdDWLV4@2x

- If I add a date in the future it looks a bit funny, can we do something about that?

Raycast-2z4uyCPq@2x

**Comment by anothertempore** [comment]
Hi @pernielsentikaer 

I fixed issues again! This time I did a regression test, hopefully everything is good 🙏  Sorry for the inconvenience!

**Comment by pernielsentikaer** [comment]
Thanks for the fixes, I gave it another spin and had some fresh feedback 😊

I don't think this should be prefilled, placeholders would be more sufficient

Raycast-CBWsJpa1@2x

I added progress in 2024, it's ending in 2023?

Raycast-wPgaQYxV@2x

Raycast-Tsny1kZY@2x

I didn't enable the menubar but when I opened the "New Progress" it's enabling the menubar just by entering it, does that happen for you too?

**Comment by anothertempore** [comment]
Hi @pernielsentikaer, sorry for the late. I fixed all issues that you mentioned above :pray:

**Comment by sxn** [comment]
thanks for the changes @anothertempore, the extension looks good! 🎉
I found myself wanting to have a shortcut for instinctively pressing `cmd+n` to add a new item, but it didn't work – might be neat to add that? 😺
Apart from that, the screenshots are now outdated, so once you update that I'd say we can merge the extension 🙀

**Comment by anothertempore** [comment]
@sxn Thanks for your suggestion! The shortcut is added, and screenshot is updated.

**Pull request merged**
