### PR TITLE
New Extension: Roll D20

### PR DESCRIPTION
**Pull request by kaylasween**
## Description

It's a really simple extension to "roll a d20" by randomly generating a number between 1 and 20.

## Screencast

https://user-images.githubusercontent.com/5904775/199825306-96a96339-42d9-4c6f-ac37-cc50a2d49639.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by kaylasween** [comment]
Fixing the icon now. 😊

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @kaylasween 👋 

Thanks for your contribution 🔥 

I tested your extension and it works as expected 🙂

One thing that came into my mind while checking it out was, that maybe you should consider making it a no-view command and use a `showHUD` to show the results instead - wouldn't that make sense?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Hi @kaylasween 👋 

Do you still want to finish this?

**Comment by kaylasween** [comment]
Hey @pernielsentikaer, sorry for the _very long_ delay! Yes, I'll change this to use `showHUD` soon!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
