### PR TITLE
Update github extension

### PR DESCRIPTION
**Pull request by xilopaint**
## Description

- Enhanced the display of repository stars in the `Search Repositories` command by prefixing the number with a star symbol (★).

## Screenshot

Screenshot 2024-07-21 at 02 29 48

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by jfkisafk — APPROVED** [review]

**Review by thomaslombart — COMMENTED** [review]
Thanks for the PR! What about making that an accessory so that we can use the proper star icon? Then maybe the subtitle could be the repo's description?

**Comment by xilopaint** [comment]
> Thanks for the PR! What about making that an accessory so that we can use the proper star icon? Then maybe the subtitle could be the repo's description?

@thomaslombart a problem with this approach is that we already use a star icon as an accessory for starred repositories:

Screenshot 2024-07-22 at 12 25 01

**Review by thomaslombart — APPROVED** [review]
Looks good! Could you fix the conflict?

**Comment by pernielsentikaer** [comment]
Done @thomaslombart

**Pull request merged**
