### PR TITLE
Add bahnexperte extension

### PR DESCRIPTION
**Pull request by ghost**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Could you look at the CI errors?

- The icon doesn't work well with a dark appearance, you can add a [light version](https://developers.raycast.com/information/manifest#command-properties) in `package.json`

- When opening the command I just get this view

bahnexperte 2023-08-17 at 09 35 41


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by KrautByte** [comment]
Hi, 
the empty dialogue is supposed to be there.
If you search for an item, e.g. Berlin you will find a list of stations.
As for the icons, I will fix that when I find some spare time.

**Comment by pernielsentikaer** [comment]
You can use `execute` on `useFetch` to stop the initial load, check the new code I pushed 🙂

**Comment by KrautByte** [comment]
Wow thanks, didn't knew about that option :)

**Comment by pernielsentikaer** [comment]
- add your real Raycast handle to `package.json`

- Correct the extension icon 🙂

**Pull request closed without merging**
