### PR TITLE
Add Sourcegraph extension

### PR DESCRIPTION
**Pull request by bobheadxi**
## Description

Adds a Raycast extension for [searching code](https://about.sourcegraph.com/code-search) on [Sourcegraph Cloud](https://sourcegraph.com/search) and [Sourcegraph instances](https://docs.sourcegraph.com/admin/install).

image

## Type of change

- New extension

## Screencast

<a href="https://www.loom.com/share/36a85a31580e40ae91f262421ad09fde">
    <p>raycast-sourcegraph store submission</p>
    
  </a>

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Comment by bobheadxi** [comment]
I can't reproduce the [linter error being reported](https://github.com/raycast/extensions/runs/4863913867?check_suite_focus=true#step:3:184) on [my own CI](https://github.com/bobheadxi/raycast-sourcegraph/runs/4863896112?check_suite_focus=true#step:5:12) 😢

**Review by pernielsentikaer — COMMENTED** [review]
Hi @bobheadxi 👋 

Thanks for your contribution, it looks pretty good, but I have some troubles setting it up. Are you on Slack (in the extensions channel)?

**Comment by bobheadxi** [comment]
@pernielsentikaer yes! I just DM'd you

**Review by pernielsentikaer — APPROVED** [review]
Hi @bobheadxi 👋 

Thanks for the conversation about the extension 💯 

I'm going to accept it and then will my colleague do a final review before it's finally merged.

**Review by mattisssa — APPROVED** [review]
Hey, thanks for the contribution! 
A sourcegraph extension built by a sourcegraph engineer ❤️ 
That's really cool to see companies adding extensions for their products! 🚀

**Pull request merged**
