### PR TITLE
[New Extension] PromptLab

### PR DESCRIPTION
**Pull request by SKaplanOfficial**
## Description

This is an extension for creating and sharing contextually-aware AI commands that utilize placeholders, action scripts, and more. PromptLab uses Raycast AI by default but can be configured to use other model endpoints. 

## Commands

- New PromptLab Command
    - Create a custom PromptLab command accessible via 'My PromptLab Commands'
- My PromptLab Commands
    - Search and run custom PromptLab commands that you've installed or created
- PromptLab Command Store
    - Explore and search commands uploaded to the store by other PromptLab users
- Summarize Selected Files
    - Summarize the contents of selected text files, PDFs, images, audio files, and more.
- PromptLab Chat
    - Start a back-and-forth conversation with AI with selected files provided as context.       
- Import PromptLab Commands
    - Add custom commands from a JSON string.

## Screencast

This is the original video demonstrating iteractions with selected files. See comments below for updated demos.
https://user-images.githubusercontent.com/7865925/226258561-ce64767e-f6cc-4688-a2aa-041c15678644.mp4

[YouTube Video](https://www.youtube.com/watch?v=SiwY9RPW3p8)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Converting to draft for now so we don't end up merging it

**Comment by SKaplanOfficial** [comment]
Update demonstration: [https://www.youtube.com/watch?v=vpY2OxIpDvo](https://www.youtube.com/watch?v=vpY2OxIpDvo)

**Comment by SKaplanOfficial** [comment]
@pernielsentikaer This is ready for review whenever you get a chance 🙂

**Comment by pernielsentikaer** [comment]
Awesome @SKaplanOfficial 🔥

**Comment by pernielsentikaer** [comment]
Let's give it live so we can iterate on it 🙂

**Comment by Ein-Tim** [comment]
FYI: The extension isn't working, this is the error I get when using it with the OpenAI endpoint: TypeError: 

Cannot read properties of undefined (reading 'startsWith')

search-commands.tsx:42:98
    at Array.filter (<anonymous>)
search-commands.js:740:16878

Bildschirmfoto 2023-06-22 um 12 19 39

This was also reported to @SKaplanOfficial in https://github.com/SKaplanOfficial/Raycast-PromptLab/issues/14

**Comment by SKaplanOfficial** [comment]
@Ein-Tim I think there are three different bugs between the two in issue #14 and this one. I'll work on fixing them today.

**Pull request merged**
