### PR TITLE
Update audio-device extension

### PR DESCRIPTION
**Pull request by arthur-fontaine**
## Description

It adds an action to hide device and show the hidden devices.

Capture d’écran 2024-05-06 à 03 20 28
Capture d’écran 2024-05-06 à 03 20 37

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution @arthur-fontaine 🔥 

Is there a way to re-hide the hidden devices after showing them again, maybe it could be a toggle function instead?

@benvp could you check this?

**Comment by arthur-fontaine** [comment]
> Thanks for your contribution @arthur-fontaine 🔥 
> 
> Is there a way to re-hide the hidden devices after showing them again, maybe it could be a toggle function instead?
> 
> @benvp could you check this?

Yes it is 100% doable and easy. I can do this this evening or tomorrow.

Btw, do you have an idea about the icon to use? There is a duplicate between "Show hidden" and "Hide this device"

**Comment by pernielsentikaer** [comment]
What about `Eye` and `EyeDisabled`

**Comment by arthur-fontaine** [comment]
Yes that's what it is currently, but there are two new actions:
- show/hide device
- show/hide hidden devices

For the first one, I used `Eye` for "Show device" and `EyeDisabled` for "Hide device".

But for the second one, if we show the same icons, it may be disturbing for the user, no?

**Comment by pernielsentikaer** [comment]
What about adding a `<ActionPanel.Section>`, that might help with the confusion, you can even set a title to make it even more clear, something like this

audio-device 2024-05-14 at 08 35 18

**Comment by pernielsentikaer** [comment]
@arthur-fontaine are you still around?

**Comment by arthur-fontaine** [comment]
Yes sorry I didn't see your last reply. I will make the changes in the next days

**Comment by arthur-fontaine** [comment]
It should be ok now! Let me know if you see something to change.

**Comment by pernielsentikaer** [comment]
I accidentally tried to hide all my devices. Maybe we should add the action to show hidden devices in the list (or a List.EmptyView) since I can't get them back 😂

audio-device 2024-05-29 at 11 38 57

**Comment by arthur-fontaine** [comment]
Like this? (if there is no device, hidden or not, it does not change from before, it should show "No Results")

Capture d’écran 2024-06-04 à 20 49 59

**Comment by pernielsentikaer** [comment]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
