### PR TITLE
Update raycast-arcade extension

### PR DESCRIPTION
**Pull request by EvanZhouDev**
## Description

✨ It's update time! Get ready for new features, new games, fixes, and more!

### Game Search

Don't want to have all of the games cluttering your Raycast? Introducing Game Search, a centralized place to access all your games. Read a bit about the game, see highlights, and more!

Games are still available as commands, so you can pick and choose by disabiling them in Raycast Settings.

### New Games

- 🔢 **2048**: The number merging game you just can't miss! The beautiful design is nearly identical to the original, and you're sure to have a blast with this one.

- 🐍 **Snake**: Have fun navigating your snake through a board to grab apples! Try not to hit the walls or your own tail, though!

### New Features

- 🎨 **Game Icons**: Each game now has its unique icon... huge thank-you to Krishna AR on Slack for designing the original icons!
- 🟩 **Wordle**: Grab your dictionary, because Wordle just got better. By an Unlimited amount! Play Wordle infinitely in the new mode, and check statistics on both modes with the new Statistics tab!

## Screencast

raycast-arcade-4
raycast-arcade-5
raycast-arcade-6

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by EvanZhouDev** [comment]
Not too sure how to resolve this merge conflict 😅

It says that its too complicated to resolve in web editor. What should I do?

**Comment by pernielsentikaer** [comment]
Hi @EvanZhouDev 🔥 

You're on fire! Looks like you have a lot of merge conflicts, could you resolve it?

Maybe it would be a cool idea to only have it in one command, or at least diable all commands in the root, does that make sense?

**Comment by EvanZhouDev** [comment]
@pernielsentikaer I’m not too sure how to resolve the merge conflicts! It doesn’t let me do it in the web editor.

Also, having it in “one command” what the new Search is for. You can choose to have it all in one command, or have it split. The user has to control it in their own Raycast settings.

**Comment by EvanZhouDev** [comment]
Can you help me understand how to resolve these conflicts? And how to avoid them in the first place?

**Comment by pernielsentikaer** [comment]
Did you use the `publish` command when you pushed? Maybe running `npx @raycast/api@latest pull-contributions` before publish would do it.

If it goes all wrong, get your extension from the store and fork it, move your new code over in that folder 🙂

**Comment by EvanZhouDev** [comment]
@pernielsentikaer running `npx @raycast/api@latest pull-contributions` does nothing...

Can you elaborate a bit more on your second solution?

**Comment by pernielsentikaer** [comment]
Remove the old extension with `Manage Extensions` and then download it from the Store and use this command

Raycast 2023-08-14 at 18 21 58

**Comment by EvanZhouDev** [comment]
@pernielsentikaer I tried it, and it doesn't work. Still getting the same issue. Any ideas?

**Comment by pernielsentikaer** [comment]
And you forked it? Let's close this PR and try to publish again 🙂

**Pull request closed without merging**
