### PR TITLE
Update sip extension

### PR DESCRIPTION
**Pull request by ruiaureliano**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by omar-salama** [comment]
You have to add to the CHANGELOG.md a description of the changes you made.

**Comment by jamesjlyons** [comment]
@ruiaureliano Thanks for opening this! Thanks for all your work on Sip too 🫡

I see it was closed though, do you want me to go ahead and add the updated icon?

**Comment by ruiaureliano** [comment]
@jamesjlyons yes please 😃

**Comment by jamesjlyons** [comment]
@ruiaureliano Finally got around to this, have [a new PR open](https://github.com/raycast/extensions/pull/13255) for it 😃

**Pull request closed without merging**
