### PR TITLE
Update iata-code-decoder to v1.2.0

### PR DESCRIPTION
**Pull request by timrogers**
## Features

* Add support for viewing an airline's conditions of carriage in the "Decode IATA Airline Code" command
* Load data from Render rather than Heroku, to keep the extension going once Heroku drops their free tier
* Improve performance and avoid memory issues in the "Decode IATA Airport Code" command

## Dependency updates

* Bump node-fetch from 3.2.3 to 3.2.6 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/15
* Bump prettier from 2.6.0 to 2.6.2 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/16
* Bump typescript from 4.6.2 to 4.7.3 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/17
* Bump @typescript-eslint/eslint-plugin from 5.15.0 to 5.28.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/18
* Bump @types/react from 17.0.41 to 18.0.12 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/19
* Bump @typescript-eslint/parser from 5.27.1 to 5.32.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/86
* Bump @types/node from 17.0.42 to 18.6.3 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/84
* Bump @raycast/api from 1.36.0 to 1.38.2 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/74
* Bump prettier from 2.6.2 to 2.7.1 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/29
* Bump @types/react from 18.0.12 to 18.0.15 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/52
* Bump eslint from 8.17.0 to 8.21.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/89
* Bump typescript from 4.7.3 to 4.7.4 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/88
* Bump node-fetch from 3.2.6 to 3.2.10 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/87
* Bump react-devtools from 4.24.7 to 4.25.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/91
* Bump @raycast/api from 1.38.2 to 1.38.3 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/95
* Bump @types/react from 18.0.15 to 18.0.17 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/100
* Bump @types/node from 18.6.3 to 18.7.3 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/109
* Bump @typescript-eslint/eslint-plugin from 5.28.0 to 5.33.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/101
* Bump eslint from 8.21.0 to 8.22.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/110
* Bump @typescript-eslint/parser from 5.32.0 to 5.33.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/111
* Bump @types/node from 18.7.3 to 18.7.5 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/113
* Bump @typescript-eslint/parser from 5.33.0 to 5.33.1 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/114
* Bump @typescript-eslint/eslint-plugin from 5.33.0 to 5.33.1 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/115
* Bump @typescript-eslint/eslint-plugin from 5.33.1 to 5.34.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/128
* Bump @types/node from 18.7.5 to 18.7.11 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/127
* Bump @typescript-eslint/parser from 5.33.1 to 5.34.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/126
* Bump @typescript-eslint/parser from 5.34.0 to 5.36.1 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/144
* Bump @types/node from 18.7.11 to 18.7.14 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/141
* Bump typescript from 4.7.4 to 4.8.2 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/135
* Bump @raycast/api from 1.38.3 to 1.39.2 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/148
* Bump @types/node from 18.7.14 to 18.7.23 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/171
* Bump @typescript-eslint/eslint-plugin from 5.34.0 to 5.38.1 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/170
* Bump eslint from 8.22.0 to 8.24.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/167
* Bump @typescript-eslint/parser from 5.36.1 to 5.38.1 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/169
* Bump @types/react from 18.0.17 to 18.0.21 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/166
* Bump react-devtools from 4.25.0 to 4.26.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/172
* Bump @raycast/api from 1.39.2 to 1.40.1 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/174
* Bump typescript from 4.8.2 to 4.8.4 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/173
* Bump @typescript-eslint/eslint-plugin from 5.38.1 to 5.43.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/212
* Bump @raycast/api from 1.40.1 to 1.43.2 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/210
* Bump eslint from 8.24.0 to 8.27.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/208
* Bump @types/node from 18.7.23 to 18.11.9 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/205
* Bump @typescript-eslint/parser from 5.38.1 to 5.43.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/211
* Bump typescript from 4.8.4 to 4.9.3 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/215
* Bump node-fetch from 3.2.10 to 3.3.0 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/214
* Bump @types/react from 18.0.21 to 18.0.25 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/216
* Bump react-devtools from 4.26.0 to 4.26.1 by @dependabot in https://github.com/timrogers/raycast-iata-code-decoder/pull/213

**Full Changelog**: https://github.com/timrogers/raycast-iata-code-decoder/compare/v1.1.0...v1.2.0

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension and I have some feedback ready for you:

* Seems like `Decode Airport Code` crashes when searching for `a`, do you have a clue what we can do (there might be too much data)
* Is the commands data saved between openings? You could look into using Raycasts [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by timrogers** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension and I have some feedback ready for you:
> 
> * Seems like `Decode Airport Code` crashes when searching for `a`, do you have a clue what we can do (there might be too much data)

I'm not able to reproduce that. Would you like me to try limiting the data to a fixed number of results to see if that helps?

> * Is the commands data saved between openings? You could look into using Raycasts [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch)

No, it isn't. I implemented the data loading before those helpers existed. It also does a live search for each query, so I'm not sure how well a cache will work.

> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Are you open to accepting this PR without those fixes - especially the second one? I'm very aware that this extension will break once Heroku drop their free plan.

**Comment by pernielsentikaer** [comment]
I actually forgot to upload the screencast I made, but I'm not sure it gives anything useful. 

https://user-images.githubusercontent.com/38033107/202427932-e833111b-7375-487c-b04a-226d3926e723.mp4

**Comment by timrogers** [comment]
> Does it full the full list initially in this call?

Thanks for that! It helped to pinpoint the issue which was indeed that the first call returns the full list. I've fixed that in the API that serves the extension - and made some other performance tweaks too.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
