### PR TITLE
add Warp terminal to shell and ssh-manager

### PR DESCRIPTION
**Pull request by AaronDavidSchneider**
## Description

This PR brings support for the [Warp](https://www.warp.dev/) terminal to the `shell` and `ssh-manager` extension, following the request from here: https://github.com/raycast/extensions/issues/3165

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by AaronDavidSchneider** [comment]
Could you please comment on the applescript @dannyneira?

**Comment by matt08** [comment]
Great job @AaronDavidSchneider - looks good 👍
Waiting for merge/publish @pernielsentikaer

**Comment by matt08** [comment]
What is the status? CC: @KELiON

**Review by KELiON — APPROVED** [review]
Looks good, let's add some Warp support 🚀

**Comment by pernielsentikaer** [comment]
Hi @AaronDavidSchneider 👋 

Could you update the CHANGELOG in the two extensions and resolve the merge conflict?

**Comment by dannyneira** [comment]
Hi, @AaronDavidSchneider Thanks for this! I'm Danny, a Support Engineer at Warp, @elviskahoro and I use Raycast on a daily basis love it!

Was wondering if is there anything the Warp team would need to do on their end to add support for using Warp as the default terminal for the Shell / SSH Connection Manager. 

CleanShot 2022-11-23 at 10 24 19

Thanks for all that you're doing keep up the great work!

**Comment by AaronDavidSchneider** [comment]
Hi @dannyneira, once @pernielsentikaer merged this PR, you can select warp as default. If you want to try it out before it is merged you can go ahead and install this branch as a custom extension. You can find manuals in the docs of this repository.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
