### PR TITLE
Add Amazon Search extension

### PR DESCRIPTION
**Pull request by xilopaint**
## Description

A straightforward extension that integrates Amazon's search functionality into Raycast, providing autosuggestions across various Amazon marketplaces.

## Screenshot

amazon-search-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by xilopaint** [comment]
@pernielsentikaer

> * Maybe add a custom view (Maybe a List.EmptyView) when nothing is searched for

Could you mention another extension where I can see how List.EmptyView was implemented?

> * Is it possible to add images to the list items

No. The autocomplete results don't represent specific products but search terms for the Amazon Store.

> * Just tried to search in Sweden, seems like all links are broken

It started working for me after I clicked on a banner (cookies, I believe).

**Comment by pernielsentikaer** [comment]
An example could be something like this extension: https://www.raycast.com/koinzhang/google-maven-repository

Just to have a better UI/UX initially 🙂

**Comment by xilopaint** [comment]
> An example could be something like this extension: https://www.raycast.com/koinzhang/google-maven-repository
> 
> Just to have a better UI/UX initially 🙂

Do you recommend me to use the Amazon icon in the `List.EmptyView`? Also, is there a standard image size that I should use? (512px looks too big in this case)

**Comment by xilopaint** [comment]
@pernielsentikaer I added a `List.EmptyView` with a 128px logo image. Please tell me what you think.

**Pull request merged**
