### PR TITLE
[Xcode] Add "Show Recent Builds in Menu Bar" command

### PR DESCRIPTION
**Pull request by SvenTiigi**
### Show Recent Builds in Menu Bar

Added a new "Show Recent Builds in Menu Bar" menu bar command which shows the recent app builds for each simulator.

Bildschirm­foto 2022-11-29 um 18 52 45

### Improved Search Recent Builds

- Improved `XcodeSimulatorApplicationService` to find application builds twice as fast.
- The layout has been reverted to a simple list instead of a detail view for a better readability.
- Added permissions actions and grouped actions into sections.

Metadata

`Directories & Files` section.

Metadata-2

`Action` section.

Metadata-3

`Permissions` section.

Metadata-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @SvenTiigi 👋 

I tried the new command but I just get `No recent build` in the menubar - I tried a few build and restarted a few times, same result - do you have an idea why?

image

Raycast-B3tndq1G@2x

**Comment by pernielsentikaer** [comment]
Ah, duh, it's getting late here - missed that part :D

**Comment by SvenTiigi** [comment]
No problem 😃✌️

**Comment by pernielsentikaer** [comment]
Just tried, still not able to get it working (also tried to stop/start and restart Xcode) - do I need to do more? 😊

Raycast-CmK2TgRx@2x

**Comment by SvenTiigi** [comment]
Generally there is no additional action needed.
But it takes a little bit of time to find all simulator builds approximately 2-4 seconds as there is no direct way of retrieving all applications and the Xcode extension is performing a parallel file search to find all of them.

So it could be the case that the menu bar app gets unloaded if the menu bar itself is closed before the operation finished. Alternatively, you could open the "Search Recent Builds" command and check if the build is showing up in the list as this component is using the same logic as the menu bar app.

I have also performed a short test on my side by clearing all simulator applications and running a new build with a newly created Xcode project which showed up in the menu bar.

https://user-images.githubusercontent.com/11733014/204656876-059efdd3-966b-4071-9a07-e4c8447adc38.mov

**Comment by pernielsentikaer** [comment]
I might have used a strange naming pattern, just tried again and it works as expected 🔥

**Comment by pernielsentikaer** [comment]
Raycast-q4EExFft@2x

**Review by pernielsentikaer — APPROVED** [review]
Looks good to me, approved 🔥

**Comment by SvenTiigi** [comment]
Looks good 👍 
Would you mind to share the naming pattern you have used which caused the problem?
Maybe this a small bug in the Xcode extension which caused this issue that could potentially be fixed 🤔

**Pull request merged**
