### PR TITLE
reclaim-ai: minor update to filters

### PR DESCRIPTION
**Pull request by maximilianzuern**
## Description

Some minor changes:

- Changed task filter to "Archived" only 
- Reordered task statuses to ["IN_PROGRESS", "SCHEDULED", "NEW", "COMPLETE", "CANCELLED", "ARCHIVED"] to move unscheduled ("NEW") tasks down the list below "IN_PROGRESS" and "SCHEDULED" tasks.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I corrected the bot so @lightbody will be pinged next time correctly, what about you @ajohnson1200, do you have a Raycast handle too?

Could you check this?

**Comment by ajohnson1200** [comment]
yeah, my raycast handle is aaron_johnson. Thank you!

**Comment by pernielsentikaer** [comment]
Is this okay to merge @ajohnson1200 @lightbody

**Comment by ajohnson1200** [comment]
yep, LGTM!

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
