### PR TITLE
Add overseerr extension

### PR DESCRIPTION
**Pull request by iamhenry**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by iamhenry** [comment]
i'm not a dev so it's unclear to me if there's anything i need to fix in order for this to get approved. please advise 😊

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

It looks like you're using axios but it's not added in the package.json - you can always check the [CI errors](https://github.com/raycast/extensions/actions/runs/7836863081/job/21385358888?pr=10658) here

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by iamhenry** [comment]
@pernielsentikaer super noob question... but how do i request a new review?

**Comment by pernielsentikaer** [comment]
You can [see here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#re-requesting-a-review) how to request it 🙂

**Comment by iamhenry** [comment]
so i added axios to my json package in my main branch + requested a new review

**Review by pernielsentikaer — COMMENTED** [review]
I just checked what overseerr is and it seems to be related to requesting copyrighted materials to download, is that correct?

**Comment by iamhenry** [comment]
it can be used to request any type of media that is not copyrighted

it uses sonarr and radarr. there's a raycast extention for sonarr so it can be used in combination with that
https://www.raycast.com/Aayush9029/sonarr

it's also an alternative to Jellyfin
https://www.raycast.com/d2a/jellyfin

**Comment by iamhenry** [comment]
@pernielsentikaer just checking in for an update, thx 😊

**Comment by pernielsentikaer** [comment]
We're still checking it internally. As soon as I have something new, I'll update the thread. I should have some answers later today 🙂

**Comment by pernielsentikaer** [comment]
Hi @iamhenry 👋 

Could you look into the [CI errors](https://github.com/raycast/extensions/actions/runs/7912053849/job/21597165794?pr=10658) 🙂

**Comment by iamhenry** [comment]
i'll take a look and fix them, thank you

**Pull request closed without merging**
