### PR TITLE
[Premier League] Standings show points for teams with long names

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- Fixed standings to show points for teams with long names. Teams with names greater than 20 characters use short names.
- Updated the dependencies and removed critical security vulnerabilities, plus unnecessary dependencie

## Screencast

Screenshot 2024-12-01 at 3 01 53 PM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

* closes https://github.com/raycast/extensions/issues/15631

### CODE REVIEW

**Comment by anhthang** [comment]
Hi @jfkisafk,

Thanks for fixing the issues. I have just face this last night also.
IMO, we can always use shortName to have consistent data for tables. it's also same as what EPL website using in the homepage

image

I also have some small fixes from the main repo here (https://github.com/anhthang/raycast-premier-league/commits/main/) but haven't created PR yet. Can you sync to this to keep the extension is updated?

**Comment by anhthang** [comment]
One more thing, I think it's better if we keep using eslint flat config (v9), but not sure what version is preferred by raycast team

**Comment by jfkisafk** [comment]
> One more thing, I think it's better if we keep using eslint flat config (v9), but not sure what version is preferred by raycast team

Yeah while using v9 and trying to extend raycast config, it was creating a lot of resolve conflicts with peer dependency. I think most packages extending `@raycast` eslint config are using eslint@8 atm, so we can stick to that.

**Comment by pernielsentikaer** [comment]
Can you ping me when it's ready to be merged?

**Comment by jfkisafk** [comment]
Hi @pernielsentikaer this PR is ready to be merged

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
