### PR TITLE
Publish Salesforce Search extension

### PR DESCRIPTION
**Pull request by svenwiegand**
## Description

This extension provides a quick search for Salesforce records (Accounts, Contacts, Opportunities) and Dashboards and Reports. Further on it is customizable to also search other (custom) objects.

See `README` for full details

## Screencast

I've committed screenshots. A screencast isn't possible, as the data visible would be sensitive.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder → The docs state the exact opposite:

   > Supporting README media: Put all linked media files in a top-level metadata folder inside your extension directory.

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
H @svenwiegand 👋 

Can you [check the errors](https://github.com/raycast/extensions/actions/runs/3229457025/jobs/5286782376) from the linter and correct them 😊

**Comment by svenwiegand** [comment]
Hi @pernielsentikaer, I've run the prettifyer (did I mention, that I hate semicolons?) and separated the images used in the `README.md` into two folders:

-  `metadata` folder: Only images which should also be used as preview for the store. 
- `img` folder: Images which are _only_ used for the documentation in the `README.md`.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi again @svenwiegand 👋 

Thanks for `uglifying` the code 😊

If wrong credentials are entered it dies, could you make it die gracefully?

image
image

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by svenwiegand** [comment]
@pernielsentikaer : What would be the best way to report an error to the user in an early stage (like when reading the preferences)? Should I use a toast?

**Comment by svenwiegand** [comment]
@pernielsentikaer I've added a bunch of error checking.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

Let's get it out to collect some feedback 😊

**Pull request merged**
