### PR TITLE
Add cloudflare-warp extension

### PR DESCRIPTION
**Pull request by anandubajith**
## Description
Adds Cloudflare WARP extension which can connect, disconnect and switch between available virtual networks (for ZeroTrust WARP)

## Screencast

https://github.com/raycast/extensions/assets/3852827/3e9566f5-1357-46fb-b399-e62f0c990a6f

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @anandubajith 🔥 

Could you look into the CI error, do you need help?

**Comment by anandubajith** [comment]
@pernielsentikaer 
Yes please, 
I'm unable to find the source of the following CI issue

image

**Comment by anandubajith** [comment]
@pernielsentikaer PR is ready for review

**Comment by pernielsentikaer** [comment]
Checking again, sorry I didn't catch the notification 😞

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Could you add an [metadata image](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) from inside the list command - don't of the root with the commands - after that, we're good to go 🙂

**Comment by anandubajith** [comment]
> Could you add an [metadata image](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) from inside the list command - don't of the root with the commands - after that, we're good to go 🙂

Done, have added two images

**Pull request merged**
