### PR TITLE
[Toolbox] Add Command to convert unix timestamp to date 

### PR DESCRIPTION
**Pull request by SscSPs**
This is useful when you need to quickly check a timestamp

## Description

Add a new command in toolbox to that converts unix timestamp to human readable date

## Screencast

Screenshot 2023-12-13 at 12 58 55 AM

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
This is also something that you can find directly in Raycast by doing `1602409302 to date`  - does it work for you?

**Comment by SscSPs** [comment]
@pernielsentikaer it does help, thanks for pointing it out!

But it wasn't very obvious because when I saw the "Date to timestamp" command in the toolbox, i was confused as to why this wasn't available since I couldn't find it there.
Now that you mentioned it, I checked and found the "11/12/2023 11:13 to timestamp" to be available there right in raycast as well

Adding this brings counterpart of the other command in toolbox, "Date to Timestamp"

**Comment by pernielsentikaer** [comment]
Makes sense @kkange do you mind checking this 🙂

**Comment by kkange** [comment]
It seems to be working fine 👍

**Pull request merged**
