### PR TITLE
trovu extension

### PR DESCRIPTION
**Pull request by georgjaehnig**
## Description

This extension allows using [trovu.net](https://trovu.net) from Raycast, including the instant suggestions.

Trovu allows you to search 1000+ websites in a command-line way, with

- [curated](https://trovu.net/docs/editors/) and [personal shortcuts](https://trovu.net/docs/users/advanced/),
- organized by [namespaces](https://trovu.net/docs/shortcuts/namespaces/),
- allowing [multiple and typed arguments](https://trovu.net/docs/shortcuts/url/),
- with [maximum privacy](https://trovu.net/docs/privacy/).

It's like [DuckDuckGo bangs](https://duckduckgo.com/bangs), but on steroids. And it's [free](https://github.com/trovu/trovu/blob/master/LICENSE).

### Examples

- [`gd london, liverpool`](https://trovu.net/process/index.html#query=gd+london%2Cliverpool) – find a route on Google Directions from London to Liverpool.
- [`gfl1 ber, lpa, 1`](https://trovu.net/process/index.html#query=gfl1+ber%2Clpa%2C1) - search one-way flights with Google from Berlin to Las Palmas, on the first of next month
- [`bkg hh, 1, 3`](https://trovu.net/process/index.html#country=de&language=en&query=bkg+hh%2C1%2C3) - search accommodation on Booking.com in Hamburg from first to the third of next month

## Screencast

https://youtu.be/LCLKXdL-4_Y

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi! This is a new extension, correct? The word "update" drove me off a bit.
Is it ready for review? I saw a few commits after the initial one and I just wanted to make sure. 
If not ready, please mark as a draft.

**Comment by georgjaehnig** [comment]
Hi @mil3na! I only used `npm run publish` for the PR, so I don't know how the title got created. And yes, I've added some further commit after the first publish.

But now it is ready for review.

**Comment by mil3na** [comment]
Hello again!
I'm having trouble using your extension. I get the following error:
`build failed (src/core/Env.js:2:16 import pkg from "../../../package.json";): Could not resolve "../../../package.json"`
Do you mind checking what is going on?

**Comment by georgjaehnig** [comment]
Hi @mil3na, sorry for this bug. It was due to the fact that I developed the extension as part of my monorepo, and did not link all the imports. Locally, my `npm run build` was running fine.

I think I've fixed it now, the checks here did also pass.

**Review by mil3na — APPROVED** [review]
Thanks for fixing it!
LGTM!

**Pull request merged**
