### PR TITLE
Update jetbrains extension

### PR DESCRIPTION
**Pull request by gdsmith**
## Description

V2 Support for JB Toolbox

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by peppy** [comment]
Thanks for the quick update of this for the new toolbox format.

It seems to be working well for me except for Rider, for some unknown reason:

CleanShot 2023-08-17 at 03 36 09

I'm seeing the same thing on two different installs. Usually, all my recent rider projects would be listed but currently only projects from the other apps are listed. Let me know if I can provide any useful diagnostics.

**Comment by gdsmith** [comment]
> It seems to be working well for me except for Rider, for some unknown reason:

@peppy can you post this as a new issue?

**Comment by peppy** [comment]
Have posted at https://github.com/raycast/extensions/issues/8040.

**Pull request merged**
