### PR TITLE
Add pycharm-recent-projects extension

### PR DESCRIPTION
**Pull request by remarkov**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Isn't this already possible with [this extension](https://www.raycast.com/gdsmith/jetbrains)?

**Comment by remarkov** [comment]
Hi @pernielsentikaer and thanks for taking a look. Unfortunately no, the extension you refer to supports only JetBrains Toolbox installations and does not support stand-alone installations of JetBrains products. That was basically the main reason I decided to develop mine and I mention that in the README.md.

While JetBrains Toolbox is a nice tool especially if you need to manage different IDEs from JetBrains and their versions, there are developers out there who do not need all that functionality and prefer simple stand-alone installation of a single product.

**Comment by pernielsentikaer** [comment]
What do you think here @gdsmith

**Comment by remarkov** [comment]
@gdsmith Sorry for the late reply. Honestly, I'm not sure I will get any free time to contribute but I'm fine if anyone will care to include some code or ideas from my extension into yours. I'll close this PR than.

**Pull request closed without merging**
