### PR TITLE
Update speedtest extension

### PR DESCRIPTION
**Pull request by stevensd2m**
## Description

Fix for no internet connection. Also it now catches any exit that is not successful.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tonka3000** [comment]
@stevensd2m thanks for the contribution. I will review it in the next 24h.

**Review by tonka3000 — APPROVED** [review]

**Comment by pernielsentikaer** [comment]
The only thing I notice is that the metadata images should be with the same background, could you correct them both @stevensd2m 🙂

**Comment by stevensd2m** [comment]
@pernielsentikaer updated the no-internet-connection background the closest to the already existing one (did not want to actually replace the original one).

**Comment by pernielsentikaer** [comment]
We actually need to replace that one too, since it's showing the old design, do you mind doing that one too @stevensd2m  🙂

**Comment by stevensd2m** [comment]
@pernielsentikaer done :)

**Review by pernielsentikaer — APPROVED** [review]

**Comment by pernielsentikaer** [comment]
Thanks 👏

**Pull request merged**
