### PR TITLE
Update Dropshare Extension

### PR DESCRIPTION
**Pull request by tjosten**
## Description

Updating the existing Dropshare extension to add a new "URL shortener" action that helps accessing the configured Dropshare URL shortener.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Wouldn't it be better just to have it as a no-view instead 🙂

**Comment by tjosten** [comment]
I oriented myself on comparable integrations (like Dub), but sure, I'll happily update it.

**Comment by pernielsentikaer** [comment]
For me, it just feels like an annoying extra step. If you want to keep it as it is, that's also okay with me 🙂

**Comment by tjosten** [comment]
If the extension was a no-view, the user had no chance up update or replace the URL that might have been read from the clipboard before shortening, right? If so, then I'd personally prefer it the way it is.

**Comment by pernielsentikaer** [comment]
One solution could _maybe_ be that if you enters an argument you'll early `popToRoot()` and shorten in the script, that might be possible 🙂

**Comment by tjosten** [comment]
> One solution could _maybe_ be that if you enters an argument you'll early `popToRoot()` and shorten in the script, that might be possible 🙂

I was rather thinking about it from a UX point of view. The current flow is:

User selects "Shorten URL" action in Raycast, and can either directly provide a URL as argument, or just hit "return" and go into the action's view. There, the input field will either be pre-filled with a URL that the extension reads from the user's clipboard, or be empty, so that the user can enter a URL manually or copy & paste it from somewhere else. That way, it's always very clear what is about to happen, and the user will never be wondering where the URL has been read from when the action was triggered.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
