### PR TITLE
Add git-clone extension

### PR DESCRIPTION
**Pull request by JavaLangRuntimeException**
## Description

This pull request introduces a new Raycast extension for Git clone functionality. The extension enables users to easily clone Git repositories directly from within Raycast, streamlining developer workflows. Users can specify the branch to clone and the directory to clone into. Additionally, a default directory can be set to save typing. The extension includes features such as GitHub authentication using personal access tokens and customizable default clone paths, enhancing user convenience and productivity.

For detailed instructions on how to use this extension, please refer to the README file.

## Screencast

スクリーンショット 2024-07-23 0 46 35

スクリーンショット 2024-07-23 0 47 00

スクリーンショット 2024-07-23 0 47 14

スクリーンショット 2024-07-23 0 55 00

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koinzhang** [comment]
Hi @JavaLangRuntimeException  The [GitHub](https://www.raycast.com/raycast/github) extension already includes this feature

**Comment by JavaLangRuntimeException** [comment]
Thank you for your answer. However, the existing github extension does not have the function to git clone from GitHub in the local environment.
スクリーンショット 2024-07-23 14 33 22

**Comment by pernielsentikaer** [comment]
Sounds like an enhancement, let's hear what @thomaslombart thinks (and if it might be possible to add something like this)

**Comment by JavaLangRuntimeException** [comment]
A key feature of this extension is its intuitive interface for selecting a clone directory and a branch, as shown in the third screenshot. Users can easily specify the target directory for cloning and choose the desired branch, making the process more user-friendly and efficient compared to traditional command-line methods.

**Comment by pernielsentikaer** [comment]
It might be that it could be integrated if it's not too niche 🙂

**Comment by jfkisafk** [comment]
This feature is already present in "Search Repositories" command. Right now the `default clone path` and `IDE` is set in preferences:

https://github.com/raycast/extensions/blob/558194a7a60c235804352ae33035f47b82ed93f4/extensions/github/src/components/RepositoryActions.tsx#L118-L123

But we can always extend this action itself to push a _Form_ to provide `Clone Path` and `Branch` as your 3rd screenshot.

**Comment by JavaLangRuntimeException** [comment]
Is the ability to select and clone a branch already implemented?

**Comment by JavaLangRuntimeException** [comment]
I'm okay with adding it to an existing extension or creating a new one.

**Comment by thomaslombart** [comment]
Yeah, it’s likely worth adding this to the current extension since OAuth and repository searching are already integrated in it.

**Comment by pernielsentikaer** [comment]
I'd like that idea better since the connection is already made 🙂

**Comment by JavaLangRuntimeException** [comment]
Is there anything I can do to add more commands to an existing extension?

**Comment by pernielsentikaer** [comment]
You can install the current GitHub extension and use the action `Fork` to get started 🙂

Raycast 2024-07-24 at 14 11 43

**Comment by JavaLangRuntimeException** [comment]
I applied the changes to an existing github extension in raycast.
https://github.com/raycast/extensions/pull/13684

**Comment by pernielsentikaer** [comment]
Awesome, closing this PR then 🙂

**Pull request closed without merging**
