### PR TITLE
Add scaffold extension

### PR DESCRIPTION
**Pull request by JoshuaRileyDev**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Maybe add the possibility to add icon/color/subtitle since you can add multiple elements with the same name

- Seems like deleting is not deleting the files in scaffold but only the entry on the list

- What does the field `Output Folder` in `Create Template` do?

- Add `style={Action.Style.Destructive}` do delete action

- Add icons to actions

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Are you still around @JoshuaRileyDev 🙂

**Comment by JoshuaRileyDev** [comment]
Hello,

Yeah I’m around but unfortunately have to put this on hold for the time
being as I’ve been swamped with work

Best Regards,

Joshua Riley

**Comment by pernielsentikaer** [comment]
Closing for now, you can always request that we open it again when you have time 🙂

**Pull request closed without merging**
