### PR TITLE
Add gopass extension

### PR DESCRIPTION
**Pull request by bake**
## Description

Add an extension for the [gopass](https://www.gopass.pw/) password manager. It currently only supports copying and pasting passwords.

For pasting I use `Clipboard.paste` which for some reason doesn't seem to be working. Could you please have a look at it? I might be missing something. Copying is done by gopass itself.

I don't have a screen to create a 2000x1250 screenshot and Slack prints an error to its console when I try to login to your community, this will have to be added before merging.

## Screencast

screenshot

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @bake 👋 

Thanks for your contribution! 🔥 

I have some feedback ready for you:

- There is no validation If you don't have gopass, the loader keeps spinning forever, and no way for the user to understand what's going on:

CleanShot 2022-05-10 at 14 05 19@2x

- After installing it (without setup - which fails for me(?)) it still just loads.

I think we need to address this and update the README so it's able to read a bit more about it 😄 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by bake** [comment]
Hi @pernielsentikaer, thank you for the feedback.

The user _should_ have been notified when gopass isn't installed, but I missed that I can't use multiple `catch` on a promise. In case Raycast can not find gopass, a toast is shown.

I also added a minimal readme file.

Is the paste option working for you?

**Comment by bake** [comment]
Hi @pernielsentikaer, I hope I don't bother you and the review request worked. Did you have the time to check the updated version? :)

**Comment by pernielsentikaer** [comment]
I'm not sure why I missed this, sorry about that! I think that we should merge it and see how it goes 🔥

**Comment by pernielsentikaer** [comment]
I don't have `gopass` working but I tried to add this action `<Action title="Copy Password to Clipboard" onAction={() => Clipboard.paste("test")} />` and it works as expected, let's try to merge it and see how it goes 😄 

If you `await` works as it should, then it should be working fine 😄

**Comment by pernielsentikaer** [comment]
Let's get it merged, added metadata image and icons

**Comment by bake** [comment]
@pernielsentikaer Thank you so much for the support, icons and the screenshot!

**Pull request merged**
