### PR TITLE
[Bike] Add Search Rows and Copy Row URL commands

### LINKED ISSUE #4394: [Bike] Search the current outline and jump to a line
### Extension

https://www.raycast.com/HelloImSteven/bike

### Description

I would love to have functionality like the "Search Notes" feature of the Apple Notes extension; in the context of Bike, the desired functionality would be that to search the lines of the focused outline. When I hit "return", I want the selected line to be opened and focused in a new window. It might be useful to also have an action for copying a Bike link to the selected row.

### Who will benefit from this feature?

Users of Bike; this would make it much easier for me to use Bike's linking feature to create crossreferences between notes, etc.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by SKaplanOfficial**
## Description

This update resolves #4394 by adding two new commands and cleaning up the code a bit, producing greater stability overall. The new commands are "Search Rows", which searches the rows of the currently focused document for a user-provided query, and "Copy Row URL", which copies the URL of the currently focused row to the clipboard. The "Search Rows" command also provides actions for navigating to the target row, copying row URLs, and deleting rows.

This update also renames the "Copy URL" command to "Copy Document URL", to differentiate it from the new "Copy Row URL" command.

## Screencast

The screencast below shows the two new commands. See [the previous version's PR](https://github.com/raycast/extensions/pull/2815) for a video covering the other commands.

[Bike.webm](https://user-images.githubusercontent.com/7865925/214685418-3477bd5e-1937-44b2-b171-2ae951250932.webm)

[YouTube Video](https://www.youtube.com/watch?v=e2oiMkcaqhw)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by jonsterling** [comment]
I have just tried this out, and it looks great! But I noticed that at least on my machine, the Copy URL feature doesn't work. When I use this action, nothing gets added to my clipboard. Any ideas?

**Comment by SKaplanOfficial** [comment]
> I have just tried this out, and it looks great! But I noticed that at least on my machine, the Copy URL feature doesn't work. When I use this action, nothing gets added to my clipboard. Any ideas?

It might be a paid feature of Bike, unfortunately. Some of the AppleScript support is limited in the free version. I can take a closer look tomorrow 🙂

**Comment by jonsterling** [comment]
Ok! In case it helps, I have the paid version. Thanks!On Jan 30, 2023, at 7:44 PM, Stephen Kaplan ***@***.***> wrote:﻿

I have just tried this out, and it looks great! But I noticed that at least on my machine, the Copy URL feature doesn't work. When I use this action, nothing gets added to my clipboard. Any ideas?

It might be a paid feature of Bike, unfortunately. Some of the AppleScript support is limited in the free version. I can take a closer look tomorrow 🙂

**Comment by SKaplanOfficial** [comment]
@jonsterling Hmm, both the copy row URL and copy document URL commands are working for me with the latest versions of Bike, Raycast, and the extension, on Ventura 13.2. Are you on a different macOS version?

**Comment by jonsterling** [comment]
@SKaplanOfficial I am using Ventura 13.1 with the latest version of Raycast and the Bike 1.8.2 Preview (99) version.

**Comment by jonsterling** [comment]
https://user-images.githubusercontent.com/55057/215853802-16786816-95ea-406f-a7e1-ae246ac108e0.mov

**Comment by SKaplanOfficial** [comment]
Ah, thanks for the video -- I wasn't looking at the right thing. Yep, that's not working. I'll fix it and push out an update soon.

**Comment by jonsterling** [comment]
@SKaplanOfficial ah ok, thanks!!

**Pull request merged**
