### PR TITLE
Update stablecog extension

### PR DESCRIPTION
**Pull request by yekta**
## Description

It's a simple update with the following changes:

- Added a new AI model: Stable Diffusion 3
- Fixed API issues
- Updated dependencies

This update is important because our API changes caused the extension to break (some commands)

## Screencast

There are no user visible changes other than the addition of a new AI model: Stable Diffusion 3:
Screenshot 2024-07-10 at 07 10 49

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by yekta** [comment]
> Hi! Thank you for your contribution! My name is Milena and I will be reviewing it today.
> 
> You mentioned that you are bumping dependencies, but Raycast's you're bumping to 1.69. Do you mind updating it to the latest?

I'm updating and opening a new PR.

**Comment by mil3na** [comment]
Why are you opening a new PR for this update?

**Comment by yekta** [comment]
> Why are you opening a new PR for this update?

I thought the publish command didn't update the pull request that's why. The whole flow is a bit confusing. Pushed the changes you requested now.

**Comment by mil3na** [comment]
Not sure if consequence of this API change, but this is what I get when I select an image on the "Search Gallery" and "Search Your History" commands:

CleanShot 2024-07-10 at 10 13 49

**Pull request closed without merging**
