### PR TITLE
[Github-for-enterprise] dependency upgrades

### PR DESCRIPTION
**Pull request by LunaticMuch**
## Description

This PR deliver some dependency update to keep the code current.
Given the update to `@raycast/api`, a couple of changes in `Form` where introduced to fix the `onSubmit` action call which now is done as `Action.SubmitForm` ([reference](https://developers.raycast.com/api-reference/user-interface/actions#action.submitform)).

Changes have been thoroughly tested against Github Enterprise and also Github (just use the GH graphql API and personal token).

Build is successful.

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @LunaticMuch 👋 

I updated the code to remove all deprecated functions, could you have a look that I didn't break something 😄

@Kinbaum do you mind checking this PR?

**Comment by LunaticMuch** [comment]
> Hi @LunaticMuch 👋
> 
> I updated the code to remove all deprecated functions, could you have a look that I didn't break something 😄
> 
> @Kinbaum do you mind checking this PR?

Just verified. It's good to me. All works.

**Comment by Kinbaum** [comment]
lgtm

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Pull request merged**
