### PR TITLE
Add database kanban view

### PR DESCRIPTION
**Pull request by HenriChabrand**
## Description

Allow user to create a "Kanban" view from a database.

Screenshot 2021-12-24 at 17 28 28

## Type of change

- Bug fix / improvement for my extension

## Screencast

On a database, use `cmd + k` and search for `Set View Type...` :

Screenshot 2021-12-24 at 17 41 26

Then select `Kanban` and set each Kanban column status :

Screenshot 2021-12-24 at 17 41 13

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @HenriChabrand 👋 

Looks like another awesome extension you're doing, awesomely!

Can you look into the errors the linter is complaining about, let me know if you need help with them 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by HenriChabrand** [comment]
Hello @pernielsentikaer 👋 

I've fixed some type issue.

As mentioned on Slack, I think there's an issue with the `TagPicker` if we try to use it with "Controlled tag picker" type of code.

For example, the code available in the [documentation here doesn't work](https://developers.raycast.com/api-reference/user-interface/form#form.tagpicker).
The value are not initialised (it "blinks") and the onChange doesn't return the tag in the right order.

Here's a video of the issue:
https://www.loom.com/share/3225f9c36aad404680c581280a971cc5

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @HenriChabrand 👋 

Thanks for the feedback about the TagPicker, I have shared your feedback with the team to look into 💪 When it's resolved we could remove the custom code you did to handle this.

It looks like there is a “unique key warning” – can you look into that before merging?

sTOh1bEpS1SnZ75k

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by HenriChabrand** [comment]
Hello @pernielsentikaer 👋 

I've fixed the `key` issue and remove my custom code that intended to fix the TagPicker.
The experience was really buggy.

Now the experience is not great because the user as to set all kanban section on its own – but at least it is functional.

Is there a bug issue I can follow for the fix of the `TagPicker`?

**Review by pernielsentikaer — APPROVED** [review]
Hi @HenriChabrand 👋 

Much better now, well done! I'm going to accept it and then will my colleague do a final review before it's finally merged 🔥

**Review by mathieudutour — APPROVED** [review]
Looking good, thanks 👍

**Pull request merged**
