### PR TITLE
[Office Quotes] Update extension to work offline (API discontinued) (closes #12094)

### LINKED ISSUE #12094: [Office Quotes] Failed to load quotes getaddrinfo ENOTFOUND officeapi.dev
### Extension

https://www.raycast.com/braydoncoyer/office-quotes

### Description

image

### Steps To Reproduce

1. Install extension
2. Run extension's only command
3. See the error:
` Failed to load quotes getaddrinfo ENOTFOUND officeapi.dev`

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### PR DESCRIPTION
**Pull request by xmok**
This extension did not have a CHANGELOG so I created one and added dates using the PR history.

## Description

The API in use is no longer active. There are 2 or 3 other APIs but all have some issues e.g. one only allows you to fetch a single quote at a time, another allows you to fetch quotes but has a limited dataset, etc.

I merged the quotes from 3 of these sources to create a local `quotes.json`:

- https://github.com/joshkmartinez/Office-Quotes-as-a-Service/blob/master/api/quotes.json
- https://github.com/AkashRajpurohit/the-office-api/blob/main/data/quotes.json
- https://github.com/codythegreat/the-office-quotes-api/blob/master/quotes.json

## Screencast

https://github.com/raycast/extensions/assets/30526133/596a296d-4e5b-4ef2-acd6-f7b7f87a0f3c

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for taking the time to update this, @xmok. It sounds like a good solution 🔥

Is it intended that it flickers while entering the extension?

https://github.com/raycast/extensions/assets/38033107/af9beebf-d30b-494d-a1d4-4dcf570710bf

**Comment by xmok** [comment]
I've not changed the functionality so it seems like this is an intended feature i.e. the quotes are shuffled when you re-run the command. Previously they were fetched via API so a loading indicator could have been shown but an import is quick enough that loading indicator does not show.

**Comment by pernielsentikaer** [comment]
Could this be a solution @xmok

**Comment by xmok** [comment]
It's still pretty quick but overall that's a great suggestion thank you for the edit;

BEFORE:

https://github.com/raycast/extensions/assets/30526133/b16b0b23-328a-4bda-8c32-563a5509601d

AFTER:

https://github.com/raycast/extensions/assets/30526133/287eb666-76dc-4c9a-812e-096406dc951a

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
