### PR TITLE
[Todoist] Remove not needed markdown

### PR DESCRIPTION
**Pull request by kud**
## Description

Remove when not needed the markdown.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by AnishDe12020 — APPROVED** [review]

**Comment by thomaslombart** [comment]
What was the original problem?

**Comment by kud** [comment]
image

**Comment by thomaslombart** [comment]
This could be removed from the list of items as well. What do you think?

**Comment by kud** [comment]
@thomaslombart This is what I've done here https://github.com/raycast/extensions/pull/3980/files#diff-f68df24ddc16034c3bdb19998d30ce7a93101d526800bbe4444636bffbe0ed2aR85 ? or is it somewhere else?

**Comment by thomaslombart** [comment]
Oh yeah, that's what I meant. I didn't saw that 🙂

**Comment by kud** [comment]
Yeah sorry, the next time I will do an effort regarding the description and the screenshots 🙏🏻

**Comment by kud** [comment]
Is there something missing then to approve the PR @thomaslombart ?

**Review by thomaslombart — APPROVED** [review]
Nope, all good!

**Review by pernielsentikaer — APPROVED** [review]

**Comment by kud** [comment]
Yooooooohoooooooo 🥳

**Pull request merged**
