### PR TITLE
Update pomodoro extension

### LINKED ISSUE #15732: [Pomodoro] Daily Focus time and Cycles
### Extension

https://www.raycast.com/asubbotin/pomodoro

### Description

I want to see daily focus time and daily cycles. Currently, we can only see the total focus time and cycles for the whole period. I think this is more efficient than seeing the total focus time and cycles for the whole period.

### Who will benefit from this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ridemountainpig**
## Description
Add the weekly and daily statistics to the `View Pomodoro Stats` command.
Closes #15732

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by LitoMore** [comment]
Could you add a preference to allow users to turn off this feature?

Also the statistics data should cleared when the feature is turned off.

**Comment by ridemountainpig** [comment]
> Could you add a preference to allow users to turn off this feature?
> 
> Also the statistics data should cleared when the feature is turned off.

I have added the preference to control whether it is shown or not. Thank you.

CleanShot 2024-12-11 at 13 32 50

**Comment by pernielsentikaer** [comment]
Could you check again @LitoMore

**Review by LitoMore — APPROVED** [review]

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
