### PR TITLE
Update paperless-ngx extension

### PR DESCRIPTION
**Pull request by ibrikin**
## Description

Corrected issue where thumbnails for newly downloaded documents did not display in grid mode
Small code improvments

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Padamdam** [comment]
Hi @ibrikin 

Thanks for improving the code so much !

I suggest you split this one commit into several if possible so they have clearer intentions.

Other than that, looks good to me !

**Comment by pernielsentikaer** [comment]
What's the current plan here? Are we ready to review or are we splitting into more PRs?

**Comment by ibrikin** [comment]
@pernielsentikaer As far as I understand, yes.

@Padamdam, did you suggest splitting it into different PRs? I have split it into several commits.

**Comment by Padamdam** [comment]
@ibrikin 

Nope, i suggested splitting your commit into several with clearer message. It is just a suggestion.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
