### PR TITLE
Clamp: Add Calculate Linear Clamp Extension

### PR DESCRIPTION
**Pull request by teziovsky**
## Description

This extension can generate a responsive linear clamp function based on px or rem values.
It's created based on the [CSS Tricks article](https://css-tricks.com/linearly-scale-font-size-with-css-clamp-based-on-the-viewport/).

## Screencast

calculate-linear-clamp-01

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @teziovsky  👋 

Thanks for your contribution 🔥 

I would be nice with some validations in the two commands to ensure that. the input is not empty and only numbers

If I write "hello" and "you" in one of them I get this output: `clamp(NaNrem, NaNrem + NaNvw, NaNrem)`

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by teziovsky** [comment]
Hi @pernielsentikaer 👋🏼

It's my pleasure!

I recently added validation to all fields. I hope now this extension will be safer in use.

You can review this extension now 🔥

**Comment by teziovsky** [comment]
I think that it's a good idea, but for now, I don't see any use cases to extend. Maybe we could add another field for example select, to select bezier curves (not only linear).

**Comment by pernielsentikaer** [comment]
Then just keep it as it for now :)

**Comment by pernielsentikaer** [comment]
We could change the name/title of the extension to something like `CSS Calculations` and the folder to `css-calculations` instead?

**Comment by teziovsky** [comment]
Yes, of course, done 🚀

**Pull request merged**
