### PR TITLE
Fix max heap

### PR DESCRIPTION
**Pull request by edblancas**
## Description

Fix max heap error.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
It seems to work as expected unless it's the first time ever loading it, could you look into that? I just get endless loading until I unload the command and enter again, then it works

search-clojuredocs 2022-11-24 at 13 29 52

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @edblancas 👋 

Seems like the first load never stops loading, first when I close the command and go in again it seems to be cached, can you check if you can improve something?

I think I waited for around 20 seconds on first load just seeing a spinner 😊

**Comment by edblancas** [comment]
Well, that's weird, I only waited 1 second.
Can you try again, please?
Screen Shot 2023-01-18 at 16 53 54

**Comment by pernielsentikaer** [comment]
I'm still having this issue. Try this action in the action panel. - after clicking it, e-enter the extension

Raycast-cjPYHfIV@2x

**Comment by pernielsentikaer** [comment]
Could you remove `api-examples/src/typeahead-search.tsx` from the PR 😊

**Comment by pernielsentikaer** [comment]
You should not delete it, you should remove it from your commit 😊

Do you need help doing that?

**Comment by edblancas** [comment]
Sorry, now the file is omitted from the commits.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Pull request merged**
