### PR TITLE
fix(visual-studio-code-project-manager): Fix optional Projects Location setting

### PR DESCRIPTION
**Pull request by gadenbuie**
## Description

This PR is a follow up to #11383 with the intent of fixing #11520.

Prior to #11383, the extension used a `textField` for a path that should be _optionally provided_, and I replaced this setting with a `directory` type preference with `required: false` and without a default, hoping this would make the setting optional.

After some back and forth in this thread, we decided to keep the `directory` type preference. So this PR is now limited to improving the error screen that is shown when no projects are found or when the Projects Location field is invalid.

## Screencast

Projects Location points to an invalid location:

image

The VS Code extension is not installed or no projects are saved:

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by theherk** [comment]
I'm not sure I understand the fix. Well, I understand the fix, but I'm not clear on why it is warranted. It works as expected when no directory is selected, it works correctly when the correct directory is selected, but it doesn't work correctly when the wrong directory is selected? Is that correct? If so, isn't that expected behavior?

**Comment by gadenbuie** [comment]
@theherk You're totally right. My working theory is that optional directory-type preferences aren't well defined in Raycast. I noticed in testing that the directory setting would sometimes be filled with a value even if I had cleared it previously. I was testing this code path so I assumed it was that I had gotten into a weird state locally, but the user report changed my mind. 

If Raycast automatically fills in the directory option, though, it can break the extension in non-obvious ways, which is why it seems safer to use the `textField` type where it's very obvious that the value is or is not set.

**Review by theherk — APPROVED** [review]

**Comment by theherk** [comment]
Cool. Makes sense to me. It would be good if somebody in the Raycast team could comment on the expected behavior of the `directory` type preference.

**Comment by pernielsentikaer** [comment]
`directory` will return the path if the path exists, it can be removed since it was added to preferences so it would be better to check for that. Does that make sense?

**Comment by pernielsentikaer** [comment]
It should be possible to set `default:false` for directory, I just tried with this code and it works as expected

```
    {
      "name": "test",
      "type": "directory",
      "required": false,
      "label": "Test",
      "title": "Test",
      "description": "Test",
      "default": true
    }
```

I think it might be a good idea to open a new PR after this with the new stuff 🙂

**Comment by gadenbuie** [comment]
> It should be possible to set `default:false` for directory, I just tried with this code and it works as expected

Thanks. For me `"default": true` (or `false`) shows a type error squiggle (`Incorrect type. Expected "string".`)


I've figured out my confusion, though. For some reason I was landing on this screen

image

I didn't realize that I could a) clear the selection from this screen or b) move forward without picking a directory by activating "Continue".

I hear you that the `directory` type would be preferable and I'm hoping that's just because I got into a weird state during local dev. I just pushed an update to go back to the `directory` type preference.

**Comment by theherk** [comment]
So is there visually no difference between picking `/` and not picking a directory?

**Comment by pernielsentikaer** [comment]
I'd also like to know that @gadenbuie

**Comment by gadenbuie** [comment]
No, I can't really explain the `/` above or how I got into that state or why that screen appeared for me. To fix it, I'm pretty certain I first cleared the selection and _then_ moved forward, at which point everything worked like normal again. Having done that, I can't get the extension back into the weird state.

Now that things are working, though, there **is a difference** between picking `/` and not picking a directory. When `/` is selected..

image

...the extension now shows the new informative error screen because the expected json files don't exist there.

image

**Comment by pernielsentikaer** [comment]
Is the ready for a review?

**Comment by pernielsentikaer** [comment]
@MarkusLanger are you still around?

**Comment by MarkusLanger** [comment]
Yes, if it works, that's fine with me.

**Comment by pernielsentikaer** [comment]
I just tried to clear everything and start over; now I'm experiencing a crash.

vscode-project-manager 2024-04-22 at 14 11 31

Could you handle that gracefully, @gadenbuie?

**Comment by gadenbuie** [comment]
> I just tried to clear everything and start over; now I'm experiencing a crash. ... Could you handle that gracefully

Thanks for catching that @pernielsentikaer. It should be fixed now.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
