### PR TITLE
Add recent search articles to Wikipedia extension

### LINKED ISSUE #7346: [Wikipedia] ...
### Extension

https://www.raycast.com/vimtor/wikipedia

### Description

There should be a way to see a list of recently viewed articles for reopening from within the Search Page extension.
Screenshot 2023-06-30 at 6 15 40 PM

### Who will benefit from this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vimtor**
## Description

Closes #7346

## Screencast

https://github.com/raycast/extensions/assets/36263538/3b2aa766-53ef-49ad-b816-7519c1696de8

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Ek2100** [comment]
I have just fixed some issues including:

- Fixed unnsuccessful Checks
- Fixed Recent Searches not showing correctly. 

I adedd these changes to https://github.com/raycast/extensions/pull/7359 (please check that it works @vimtor)

**Review by thomaslombart — COMMENTED** [review]
Could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

**Comment by Ek2100** [comment]
> Could you add an entry in the `CHANGELOG.md` file? Here's our guidelines about that: [Version History](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history).

The changelog file has been updated and a issue was fixed in https://github.com/raycast/extensions/pull/7359

**Comment by thomaslombart** [comment]
Hey @Ek2100, thanks for your contribution. However, @vimtor is the original PR's author here, so I'll wait for his updates since the PR is relatively new. Feel free to review its code or comment the PR for suggestions.

**Comment by Ek2100** [comment]
> Hey @Ek2100, thanks for your contribution. However, @vimtor is the original PR's author here, so I'll wait for his updates since the PR is relatively new. Feel free to review its code or comment the PR for suggestions.

That’s a good point, 100%. The extensions owner should have complete authority over this so maybe if you want, push this PR and then I will try to get into touch with him about my PR.

**Comment by thomaslombart** [comment]
Closing it in favor of https://github.com/raycast/extensions/pull/7359 after seeing [this comment](https://github.com/raycast/extensions/pull/7359#issuecomment-1627067509).

**Pull request closed without merging**
