### PR TITLE
[Image Modification] Strip EXIF Data + Filter Previews

### LINKED ISSUE #8135: [Image Modification] ... JPEG option converts to a PNG and just uses a .jpg extension
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

I used the converter, and selected JPEG option, but it changed my .webp image to a png type with a .jpg extension. 
Screenshot 2023-08-29 at 10 43 45 AM

### Steps To Reproduce

1. Select .webp image file in finder
2. Select Convert to JPEG in raycast extension
3. open the resulting file in Preview, and look at the info of the image
4. the "file type" is shown as PNG, but the file itself has a .jpg extension in the file name.

### Current Behaviour

creates a png file disguised as a jpeg

### Expected Behaviour

to actually create a jpeg

### LINKED ISSUE #9399: Quick Option to Remove EXIF Metadata
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

Quickly remove EXIF data from images. Often I convert images to post to public websites and have to go through an image editor to remove the data when I just need to quickly convert and post an image online.

### Who will benefit from this feature?

People looking to post images anonymously on public websites quickly. Removing the metadata that often contains things like device type and location data would be extremely beneficial.

### Anything else?

_No response_

### LINKED ISSUE #9795: [Image Modification] svg files are not recognized as selected
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

Unable to convert SVG images from one format to another.
<details><summary>Image of the error</summary>

No image selected
</details> 

### Steps To Reproduce

1. Select any svg image
2. Try to convert to any format
3. Gives "No images selected" error

### Current Behaviour

_No response_

### Expected Behaviour

_No response_

### LINKED ISSUE #10313: [Convert Images] Can't convert to .webp
### Extension

https://www.raycast.com/HelloImSteven/sips

### Description

Using MacOS M1 on both machines. On both of them I have installed Raycast Pro. One machine doesn't have any issues when converting to webp, when the other one can't convert to this format only. (I didn't check all the others, cause Im interested mostly in webp)

### Steps To Reproduce

1. Click on the image
2. Run this extension
3. Pick webp

### Current Behaviour

Command failed: /Users/**user**/.config/raycast/extensions/7c158f0e-b70b-4922-8a1b-5c8a9ccb55d6/assets/webp/cwebp "/Users/**user**/Downloads/FAQ/image 3.png" -o "/Users/**user**/Downloads/FAQ/image 3.webp"
/bin/sh: /Users/**user**/.config/raycast/extensions/7c158f0e-b70b-4922-8a1b-5c8a9ccb55d6/assets/webp/cwebp: Bad CPU type in executable

### Expected Behaviour

Convert image to the given format.

### PR DESCRIPTION
**Pull request by SKaplanOfficial**
## Description

This update to the Image Modification extension adds a "Strip EXIF Data" command (closes #9399), real-time previews when applying filters, and some bug fixes. To strip EXIF data, the extension uses ExifTool(https://exiftool.org), which can be downloaded on first run if needed.

Closes #10313 by using architecture-specific libwebp binaries.

Resolves #8135 by adjusting arguments to dwebp commands.

Closes #9795 by improving selection detection when Finder/Path Finder is not the frontmost application. 

## Screencast

[sips-1.7.0-demo.webm](https://github.com/raycast/extensions/assets/7865925/ce0a66f5-99d0-4dfc-95d0-15f0d0153fef)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @SKaplanOfficial 👋 

Where do you have the binaries from?

**Comment by SKaplanOfficial** [comment]
Hi @pernielsentikaer, the cwebp and dwebp binaries are from [Google's WebP support site](https://developers.google.com/speed/webp/download), using the macOS arm64 and x86-64 downloads. ExifTool downloads directly from its [website](https://exiftool.org).

The webp binaries are small enough that I figured it makes sense to just keep them as assets. They're 7.4 MB in total and about half that once the CPU architecture is determined.

**Comment by pernielsentikaer** [comment]
That makes sense. I just needed to make sure that the binaries haven't been tampered with 🙂

**Comment by pernielsentikaer** [comment]
Would it make sense to make this new command disabled by default (or maybe some of the others) It will only affect new users installing it - just so we don't end up with users being a bit overwhelmed - like our Spotify extension with more than 25 commands, only 5 are enabled by default 🙂

Did you ever think of that?

**Comment by SKaplanOfficial** [comment]
Hm, I'm not sure. Looking at other extensions I've installed, there are quite a few with the same or more commands (e.g. Timers, GitHub, GitLab, Deepcast, as well as some of my other extensions such as Bike and iWork). I don't think 11 is too many given the broad scope of the "image modification" name.

I also think having commands disabled by default causes some confusion, for instance, I've replied to multiple Slack threads where the solution to a missing feature was enabling a command disabled by default.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by hujunfeng** [comment]
@SKaplanOfficial Strip EXIF Data command always failed for me. Not sure if I'm missing anything.

JH_SCR 2024-03-14 at 11 11 00 AM

```
Command failed: "/Users/jh/Library/Application Support/com.raycast.macos/extensions/7c158f0e-b70b-4922-8a1b-5c8a9ccb55d6/Image-ExifTool-12.74/exiftool" -all= -o "/Users/jh/Downloads/Screenshot 2024-03-12 at 4.00.41 PM.jpeg" "/Users/jh/Downloads/Screenshot 2024-03-12 at 4.00.41 PM.jpeg"
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LC_ALL = "en_US@rg=sgzzzz-u-hc-h12-u-ca-gregory-u-nu-latn",
	LANG = (unset)
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Error: '/Users/jh/Downloads/Screenshot 2024-03-12 at 4.00.41 PM.jpeg' already exists - /Users/jh/Downloads/Screenshot 2024-03-12 at 4.00.41 PM.jpeg
```

**Pull request merged**
