### PR TITLE
[GitHub] Brought back fast browsing to cloned repos.

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- [#13872](https://github.com/raycast/extensions/issues/13872): Brought back the feature for Raycast to act as a fast brower to open cloned repo.
- Re-added _Clone Path_ preference without any default value this time. If no value is provided, user will need to specify directory with the form.
- If a value for _Clone Path_ preference is specified, the old behavior of cloning the repo (or opening if it exists) is enacted.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

* closes https://github.com/raycast/extensions/issues/13872

### CODE REVIEW

**Comment by jfkisafk** [comment]
Hello @thomaslombart , can you please take a look when you find some time? 🔥

**Comment by jfkisafk** [comment]
Hello @thomaslombart, can we please get some traction here when you have some time?

**Comment by LitoMore** [comment]
@jfkisafk It's better not to ping them in the pull request. They will review your code when they have time.

They have other things to do at work. Let's not disrupt their work schedule.

**Comment by jfkisafk** [comment]
> It's better not to ping them in the pull request. They will review your code when they have time.

Noted. I don't want them to review it pronto - but sometimes things drop out of the radar in a fast-paced environment. So re-escalating every 5/6 days has helped me get traction with other PRs. But I don't wanna do this continuously as I agree that it can get annoying. Safe to say, the review SLA of "within five business days" might need revisiting.

**Comment by thomaslombart** [comment]
I agree with @LitoMore. I'm well aware of the PRs I need to review, and pinging me adds more noise in the GitHub notifications. I'm busier at the moment, giving me less time for reviews.

**Comment by jfkisafk** [comment]
Sorry about the disruption! I misinterpreted the situation.

**Comment by thomaslombart** [comment]
No worries!

**Review by thomaslombart — APPROVED** [review]
🚀

**Pull request merged**
