### PR TITLE
feat: add React DevTools

### PR DESCRIPTION
**Pull request by gutenye**
## Description

This extension simplifies the process of opening command-line applications by integrating them with Raycast. Normally, to open a command-line app, you would need to open a terminal and type the corresponding command. With this tool, you can easily open these applications through Raycast, making it more efficient and seamless.

For Android Emulator applications, the extension goes a step further. It automatically lists all available emulators, allowing you to select and launch the desired one with a few clicks, eliminating the need for manual command entry.

## Screencast
screenshot-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution 🔥

It feels like a funny mix of commands. What's the use case for this? The Android Emulator is already available [here](https://www.raycast.com/mibrahimdev/android), and I think most of the other commands are also possible

**Comment by gutenye** [comment]
I found the Scrcpy extension, but I wasn’t able to find the React DevTools extension. I could remove the Android Emulator and Scrcpy, and keep React DevTools. Does that sound good?

**Comment by pernielsentikaer** [comment]
Then it's just a command starting a terminal comment, right?

**Comment by gutenye** [comment]
Yes, we currently have Scrcpy and Android Emulator extensions for starting terminal commands, but we’re missing React DevTools. If you prefer, I can rename the extension to “React DevTools.”

**Comment by pernielsentikaer** [comment]
I guess it could make sense to change the name since it's only one thing now, could you also provide me a screencast of the flow?

**Comment by gutenye** [comment]
https://github.com/user-attachments/assets/989d6d19-2f82-4bc6-ba7f-e5a1843a0013

**Comment by gutenye** [comment]
@pernielsentikaer the code is updated

**Comment by gutenye** [comment]
I plan to add a new one, open iOS simulator from raycast, it will list the simulator names for you to choose. Should I create a new extension for it?

**Comment by pernielsentikaer** [comment]
Isn't that already possible with:
* https://www.raycast.com/noppefoxwolf/simulator-control
* https://www.raycast.com/okwasniewski/minisim

**Comment by gutenye** [comment]
@pernielsentikaer You're right. I missed them. The PR is ready for review, could you review it? Thanks

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
