### PR TITLE
[2fa]: chase code support

### PR DESCRIPTION
**Pull request by iloveitaly**
## Description
Added chase 2fa code support

## Screencast
NA

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by navtoj** [comment]
> Thank you for your contribution! 🎉
> 
> 🔔 @yuercl @thomaspaulmann @arronhunt @ronaldheft @navtoj @hitolaus you might want to have a look.

@raycastbot
@thomaspaulmann

How do I remove myself from this list?

I do not wish to be tagged every time a pull request is made for the [`imessage-2fa`](https://www.raycast.com/yuercl/imessage-2fa) extension.

**Comment by erics118** [comment]
@navtoj You can move your username from `contributors` to `pastContributors`. For some reason, it's not documented in the [Manifest docs](https://developers.raycast.com/information/manifest) (idk why), but it is in the [json schema](https://www.raycast.com/schemas/extension.json)

@pernielsentikaer also mentioned it in https://github.com/raycast/extensions/pull/12385#issuecomment-2117492709

**Comment by pernielsentikaer** [comment]
I'll make sure to update the manifest docs 🙂 It's because we're still missing a few things to make it work everywhere 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by yuercl — COMMENTED** [review]
nice work

**Pull request merged**
