### PR TITLE
Update mattermost extension

### PR DESCRIPTION
**Pull request by Ernest0-Production**
## Description

I corrected the error that occurred when authorizing via login / password.

with such authorization, a temporary token is created and it can be invalidated some time later.

I added a 401 check and re-login to refresh the token

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @Ernest0-Production 👋 

Thanks for your contribution 💯 

Could you look into this CI error here?

**Comment by Ernest0-Production** [comment]
Hi! Planned to do this over the weekend

**Comment by pernielsentikaer** [comment]
Awesome @Ernest0-Production

**Comment by Ernest0-Production** [comment]
> Awesome @Ernest0-Production 

Hi! I fix all errors)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
