### PR TITLE
Add wevm-utilities extension

### PR DESCRIPTION
**Pull request by jxom**
## Description

Adds Wevm Utilities extension – a Collection of Ethereum Utilities for Raycast – starting with:
- Search Chains
- Convert Units
- Search EIPs
- Search Ethereum Signatures

## Screencast

wevm-utilities-1
wevm-utilities-2
wevm-utilities-3

## Checklist

- [ x I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

There is a similar extension [in the store](https://www.raycast.com/destiner/ethereum-utils). Could you check that out? Maybe it would be better to enhance that one instead

**Comment by jxom** [comment]
Thanks! Admittedly only saw that extension halfway through building this one. There are quite a few noticable behavior/UX/UI/asset differences between these extensions. Will we need to liase with the Author of the existing extension if we want to diverge the behavior/UI/UX/assets of existing Commands? We are also planning on extending to more Commands beyond the ones in the existing extension as well.

**Comment by pernielsentikaer** [comment]
Are you still around @Destiner 🙂

**Comment by jxom** [comment]
Might close this for now... Thanks for reviewing!

**Pull request closed without merging**
