### PR TITLE
Add golden-ratio extension

### PR DESCRIPTION
**Pull request by monchfun**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Whats the difference between this and https://github.com/raycast/extensions/pull/13011 🙂

**Comment by monchfun** [comment]
> Whats the difference between this and #13011 🙂

I'm not very clear about the difference between the main branch and the branches. 13011 was done on the main branch, but I've already deleted it.

**Comment by pernielsentikaer** [comment]
I hit the merge button by accident, do you mind making a followup PR with:

- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

- Maybe add support for [argument](https://developers.raycast.com/information/lifecycle/arguments) for faster access

**Comment by monchfun** [comment]
> I hit the merge button by accident, do you mind making a followup PR with:
> 
> * Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension
> * Maybe add support for [argument](https://developers.raycast.com/information/lifecycle/arguments) for faster access

No problem. I'll submit it later

**Pull request merged**
