### PR TITLE
feat: new extension for tailwind cheatsheet

### PR DESCRIPTION
**Pull request by cy-98**
## Description
cheat sheet for tailwindcss

It‘s not completely.
**Any one can help me complete rest classnames**
**Any one has better way to add all tailwind classnames automatically ?**

截屏2022-05-11 23 49 04

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by cy-98** [comment]
I wish all of us can contribute this extension, and make it better together.

**Comment by pernielsentikaer** [comment]
Hi @cy-98 👋 

Did you check [this extension](https://www.raycast.com/vimtor/tailwindcss) - it looks like we already have such extension

**Comment by cy-98** [comment]
> 

Yes, already have tailwind extension, it can open document website, this can show the tailwind classnames and style without open website.

**Comment by pernielsentikaer** [comment]
Hi @cy-98 👋 

It would actually be better to move your enhancements into the current so we don't end up with multiple extensions with the exact same purpose 😄 We can hear what @vimtor thinks about is, since he is the original author 😄

**Comment by cy-98** [comment]
> Hi @cy-98 👋
> 
> It would actually be better to move your enhancements into the current so we don't end up with multiple extensions with the exact same purpose 😄 We can hear what @vimtor thinks about is, since he is the original author 😄

You are right. I will pull request to the origin extension.

**Comment by cy-98** [comment]
@vimtor  But I don't know how to code my feature in the `tailwindcss` extension. Can you give some suggestions ?

**Comment by pernielsentikaer** [comment]
@vimtor are you able to help out?

**Comment by cy-98** [comment]
@pernielsentikaer There is no reply, I made the same extension in team. If can add it into raycast's extensions please tell me. Thanks for your attention !

**Comment by vimtor** [comment]
Hey there! Sorry for the late reply.
I would love to add this to the current Tailwind CSS extension ❤️

How should we manage this? Should I add it to the Tailwind CSS extension?

**Comment by pernielsentikaer** [comment]
It just has to be merged, and create a new PR with the corrections into the current Tailwind extension 🙂

**Pull request closed without merging**
