### PR TITLE
feat(days-until-christmas): add status and menubar commands

### PR DESCRIPTION
**Pull request by erics118**
## Description

switch from a view command to a no-view, which can be used as a status command
also added a few more emojis

## Screencast

CleanShot 2023-11-15 at 22 23 22

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the contribution @erics118, maybe we could also add a simple menubar (and a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry) 🙂

What do you say @MEGApixel23 - are you okay with this 🙂

**Comment by MEGApixel23** [comment]
@

> Thanks for the contribution @erics118, maybe we could also add a simple menubar (and a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry) 🙂
> 
> What do you say @MEGApixel23 - are you okay with this 🙂

Looks good :)

**Comment by erics118** [comment]
Added a super simple menu bar command.

CleanShot 2023-11-16 at 18 18 21

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
