### PR TITLE
Lucide icons

### PR DESCRIPTION
**Pull request by aeither**
## Description

Update version and deprecated. Update and add Lucide icons to latest 905 Icons.

## Screencast

screenshot

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the contribution @aeither 🔥 

Do you have time to check this @gBasil

**Comment by pernielsentikaer** [comment]
If you can improve this into your extension 😊

**Comment by pernielsentikaer** [comment]
Yes, but since you're the author you're allowed to deny updates if it doesn't fit

**Comment by aeither** [comment]
@gBasil Those json are not used. I run your `prebuild.js` script and those metadata got fetched. Added a filter in the script and removed json files.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
