### PR TITLE
feat(safari): add pinyin support to safari tab searching

### PR DESCRIPTION
**Pull request by ChangeHow**
## Description

- feature: Add `pinyin` support for searching tab
- improve:
  - add cache for formatted string
  - reduce re-render times for `CloudTabs`

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by ChangeHow** [comment]
@pernielsentikaer Hi, Could you take a look for this PR? It's a supper efficiency improvement for me.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for your contribution 🔥

Why do we call it LooseTab instead of just Tab?

@loris can you check this 🙂

**Comment by ChangeHow** [comment]
> Thanks for your contribution 🔥
> 
> 
> 
> Why do we call it LooseTab instead of just Tab?
> 
> 
> 
> @loris can you check this 🙂

That my fault, I edit in a early version but forget change it.

I'll fix it.

**Comment by pernielsentikaer** [comment]
Sounds reasonable, let's wait for @loris

**Comment by pernielsentikaer** [comment]
Are you still around @loris

**Comment by loris** [comment]
Sorry for the delay; I missed your earlier mention. This is a very nice PR. While it does make the codebase more complex, the changes are very well thought out.

**Comment by pernielsentikaer** [comment]
Thanks for checking @loris 🔥

**Review by pernielsentikaer — APPROVED** [review]
Let's get it live and see how it goes 🙂

**Pull request merged**
