### PR TITLE
Add GitHub Codespaces extension

### PR DESCRIPTION
**Pull request by mkwng**
## Description

This adds the GitHub Codespaces extension to the Raycast extension store

## Screencast

https://user-images.githubusercontent.com/1319241/189608073-a65bd13c-5b79-41e6-9e71-c1f48b4ef230.mov

Current functionality allows for launching, renaming, modifying backing compute, deleting.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mkwng** [comment]
I'm stumped why this test is failing. Not doing anything with useSQL or wasm. Any thoughts?

image

**Comment by clnhs** [comment]
Hey, I just had the same issue with my PR. I think you're missing the `.prettierrc.json` file.

**Comment by pernielsentikaer** [comment]
Gave review feedback on [Slack](https://www.raycast.com/community)

**Comment by mkwng** [comment]
Insiders support is a preference setting
image

**Comment by mkwng** [comment]
Anything I can do here to speed along the process? :)

**Review by pernielsentikaer — APPROVED** [review]
Hi @mkwng 

Awesome updates 🔥 No, we're just investigating the spike you told me about. In the meantime, I think we can merge it, but we might get back to it later to fix something 🙂

The next thing could be letting the user select what the primary(and secondary) action is 🙂

**Pull request merged**
