### PR TITLE
Add quick-notes extension

### PR DESCRIPTION
**Pull request by biknandy**
## New Extension: Quick Notes

Create simple markdown notes in Raycast stored locally. No integrations required!

### Features

- View, create, and delete markdown notes
- Search by note title, body, or tag
- Draft and auto-save if you accidentally exit out while creating/editing a new note
- Export notes to a folder to use in another application
- Setup auto-save to a folder of your choice, set in preferences
- Tag manager

If you’d like, you can export or sync your notes as markdown to a directory to use in a 3rd-party app like Obisidian, VS Code, or Notion. This is completely optional though and notes will still save locally.

### New Commands

View Notes
- View and edit your notes
- Create a new note `⌘ + N`
- Delete a note `^ + ⇧ + X`
- Filter by tag `⌘ + T`
- Create a new tag `⇧ + ⌘ + T`
- Delete tags `^ + ⇧ + T`

Export Notes
- Set a directory to export your notes once
- This can be automated in extension preferences

## Technical Implementation
- Uses `fs` to filesync with extension directory to save JSON format of notes
- Jotai used to save state and get/set using the filesync
- Slugify package used to create save filenames for export

## Screencast

Demo:

https://github.com/raycast/extensions/assets/68867182/b0a78b4c-c720-4ba2-bf76-f64749d26d4f

Exporting Notes:

https://github.com/raycast/extensions/assets/68867182/159e2ad4-54f0-46a2-8c35-222a447898b5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @biknandy 👋 

Sorry for the late response, easter vacation delayed the queue a bit 🫠

Have you tested out [SnapJot](https://www.raycast.com/k41531/snap-jot) by @k41531  - it feels kinda similar it feels like they're in the same alley

**Comment by biknandy** [comment]
> Hi @biknandy 👋
> 
> Sorry for the late response, easter vacation delayed the queue a bit 🫠
> 
> Have you tested out [SnapJot](https://www.raycast.com/k41531/snap-jot) by @k41531 - it feels kinda similar it feels like they're in the same alley

Hey there! Yea I thought this was a bit cleaner of a solution as it includes drafts, categories, and export to VSCode/Obsidian features w/ live sync there.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Can you make so it's possible maintainers to edit this PR

**Comment by biknandy** [comment]
> Can you make so it's possible maintainers to edit this PR

Done thanks!

**Comment by pernielsentikaer** [comment]
Thanks 🙂

**Pull request merged**
