### PR TITLE
Claris Snippets

### PR DESCRIPTION
**Pull request by eluce2**
## Description

An extension to create/use clipboard snippets for Claris (FileMaker) Pro.

FileMaker allows you to copy/paste its proprietary objects from the clipboard, but these objects never work with traditional clipboard managers because they are not plain text. This extension leverages an existing [community-built set of AppleScript files](https://github.com/DanShockley/FmClipTools) to translate those objects into text for saving for later, and translating back to FileMaker XML so it can function like a proper snippet library.

**Note for Maintainers:** Either Claris Pro or FileMaker Pro ([free trial link](https://www.claris.com/trial/)) may be required to fully test this extension (if you want to create your own snippets). DM me on Slack if you have trouble with downloading or getting a free trial of this software. If you do not wish to install FileMaker, I can also send you sample .json files to seed your snippet library.

## Screencast

https://share.cleanshot.com/VDk4FK

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @eluce2 👋 

It looks pretty cool; the only issue that I can see is when adding a new folder, Raycast closes, which unloads the module, so after selecting a folder, nothing happens (since when you open it's just in the root)

Do you have a good idea to tackle that one?

**Comment by eluce2** [comment]
I can't replicate this... I do notice Raycast close when I move focus to the file picker, but it opens back up once I select a folder.

I had originally wanted to wait until we get a native file/folder picker field in the API since I know what I have now is kinda a hack. Should I just remove the AppleScript and release v1 without that feature? You'd have to type the path to a folder in manually

**Comment by pernielsentikaer** [comment]
Hi @eluce2 👋 

Strange, it's like GitHub removed my uploaded image 😊. Can you try to check with this setting?

image

**Comment by eluce2** [comment]
Hmm, I see what you mean now. I must not have had the issue because of the setting where Raycast can stay open always during development. I'm not sure how to fix it though—do you have any suggestions? Or should I just remove this ability to choose a path via AppleScript until it's available in the API?

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
