### PR TITLE
Jotoba Extension Update

### PR DESCRIPTION
**Pull request by clnhs**
## Description

- Fixed search term not erasing.
- Fixed common words priority display order.
- Added setting option (default) to toggle the displaying of common words first in search results. 
- Raycast API bump to 1.45.1.
- Changelog update.
- Readme typo fix.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* When deleting the last letter in the search field, it doesn't go back to the default empty view; could you look into this?

https://user-images.githubusercontent.com/38033107/210308193-3e8760dd-7f3c-4706-b982-114782e33395.mp4



I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by clnhs** [comment]
@pernielsentikaer 

Thank you for catching this!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
You have some Japanese in `KanjiListItem.tsx:13-16` could you change this?

At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

**Comment by clnhs** [comment]
> You have some Japanese in `KanjiListItem.tsx:13-16` could you change this?
> 
> At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

Done.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
