### PR TITLE
Add scss-compile extension

### PR DESCRIPTION
**Pull request by SuoweiHu**
## Description

This extension helps developers to compile SCSS file into CSS file, 
hope you will like it （　´∀｀）

## Screencast/Video

https://github.com/raycast/extensions/assets/35317549/ae01eb69-80ae-451f-97c0-04e62801d766

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
It this view, what's the `Watch Changes` for?

scss-compile 2024-06-20 at 10 47 45

How do I test with and without that enabled?

**Comment by SuoweiHu** [comment]
This 

> It this view, what's the `Watch Changes` for?
> 
> scss-compile 2024-06-20 at 10 47 45
> 
> How do I test with and without that enabled?

Hello @pernielsentikaer, this option allows user to directly "watch" the "scss" file when they save the file. Please see below video as demonstration: 

https://github.com/raycast/extensions/assets/35317549/4e6d7b36-4d6b-4fd0-9e81-112a8ba12b5e

But I can tell where you confusion comes from, they are able to turn on "watch" after save easily, so putting an extra configuration here isn't quite necessary, do you recon it is better to remove it ?

**Comment by pernielsentikaer** [comment]
I think it's fine to keep it as is 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
