### PR TITLE
Add raytaskwarrior extension

### PR DESCRIPTION
**Pull request by AltamimiYasser**
## Description
Raycast integration with Taskwarrior.

## Screencast
Raycast 2023-05-27 at 06 36 03

raytaskwarrior-1

raytaskwarrior-2

raytaskwarrior-3

raytaskwarrior-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Do you mind fixing the linter after I changed .prettierrc since we would like to follow the same structure among extensions 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by AltamimiYasser** [comment]
Thanks for reviewing my extension!
I've fixed the Prettier style errors as requested.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by AltamimiYasser** [comment]
Thanks!!, @pernielsentikaer 🔥

**Pull request merged**
