### PR TITLE
Add raycast-sink extension

### PR DESCRIPTION
**Pull request by foru17**
## Description

Raycast Sink is a powerful extension that seamlessly integrates [Sink](https://github.com/ccbikai/sink), a simple, speedy, and secure link shortener powered by Cloudflare, into your Raycast workflow. This extension empowers users to effortlessly manage short links directly from their MacOS command bar.

## Screencast
raycast-sink-2
raycast-sink-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

In preferences, don’t add a default value for API Token

It doesn’t make sense to have a custom settings form, just keep it to preferences

Maybe have two commands instead? One for listing and one for creating?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by foru17** [comment]
Thank you @pernielsentikaer for the detailed feedback! I've made the following improvements based on your suggestions:

1. Removed the default API token value from preferences
2. Simplified the configuration by removing the custom settings form and keeping everything in preferences
3. Separated the functionality into distinct commands for better user experience
4. Overall streamlined the interaction flow and removed redundant elements

For testing purposes, you can use these example configurations:
- Host: https://sink.cool
- Site Token: SinkCool

The extension is ready for another review whenever you have time.
Please let me know if you'd like to see any additional adjustments or have any questions. Thanks again for helping improve the extension! 🙏

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
- API token should maybe be a password field?

- Maybe use [useFetch](https://developers.raycast.com/utilities/react-hooks/usefetch) or [useCachedPromise](https://developers.raycast.com/utilities/react-hooks/usecachedpromise) for fetching since both caches and have built-in loader (Since yours is always false)

- Add loader to your form when submitting

- Use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) for the form which handles validation, errors and states

**Comment by pernielsentikaer** [comment]
When you create a new link, I would suggest showing a toast with an option to copy it instead of pushing it to the new view, as escaping returns to the form, which is a bit unexpected?

**Comment by pernielsentikaer** [comment]
Accepted 🙂

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
