### PR TITLE
fix(linear): Fixing the search issues results for newly created issue 

### PR DESCRIPTION
**Pull request by harsh-devx**
## Description

- When creating the issue it takes time to create the issue and doesn't show up in results of command `search issues` immediately.
- using local storage to update the issues list basis flag.

### BEFORE
https://github.com/user-attachments/assets/43175e76-391b-4e3c-898c-9f952f402758

### AFTER
https://github.com/user-attachments/assets/cc90e609-a787-4e0a-b01e-30d3f26003d5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by thomaslombart** [comment]
I'm not sure I understood the initial problem. Could you send a before-and-after recording to make it clearer?

**Comment by harsh-devx** [comment]
> I'm not sure I understood the initial problem. Could you send a before-and-after recording to make it clearer?

Sure, have attached the videos for reference.

**Comment by harsh-devx** [comment]
@thomaslombart I hope you had the chance to go through the demo. Let me know your thoughts on the same.

**Comment by pernielsentikaer** [comment]
I have now reviewed its functionality, and while I can see the potential advantages, I am going to reject this update.

Since we always have had a loading indicator in commands, our users are accustomed to waiting until a command finishes. In this case, it's only happening before we execute the next command while the current one is still finishing. Sometimes it's really fast, and other times it can take a second. It depends on many factors in both ends on the line

Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions regarding this

**Pull request closed without merging**
