### PR TITLE
[Sonarr] HTTPS & URL Base Support

### PR DESCRIPTION
**Pull request by tdeverx**
## Description

Made a small modification to allow connections that require HTTPS & URL Base.

## Screencast

N/A

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @tdeverx 👋 

Thanks for your contribution 🔥 

@Aayush9029 do you mind checking this?

**Comment by Aayush9029** [comment]
@tdeverx While you're at it 

I recommend making the entire url a required input 😀

This way users can use https + custom baseURL, if they want 🎉

**Comment by tdeverx** [comment]
> I recommend making the entire url a required input 😀

You think that would be better? I personally prefer the ability to fine tune each section because it just looks better visually and provides a better UX.

Take a look at Sonarr (or Overseerr), even they have these options separated. Surly another box at the top to select http/https be better? If not for simply looking better, but keeping a cohesive experience across apps?

I mean, it’s not the end of the world if you’d prefer a single URL Box, but I had to ask just in case. Let me know and I’ll make the necessary changes 😊

**Comment by Aayush9029** [comment]
> Surly another box to select http/https would be better?

This sounds great. I chose option requiring least amount of changes for you to implement. 😅

**Comment by Aayush9029** [comment]
@pernielsentikaer  Looks great! 🚀

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
