### PR TITLE
Allow to add multiple co-authors at once

### PR DESCRIPTION
**Pull request by mateusjunges**
## Screencast

https://github.com/raycast/extensions/assets/19756164/189efbc3-cf14-4df5-9c72-df0d24de4e52

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mateusjunges** [comment]
@pernielsentikaer should I update the changelog?

**Comment by pernielsentikaer** [comment]
@mateusjunges yes please 🙂

@nickradford do you mind checking this?

**Comment by mateusjunges** [comment]
@pernielsentikaer done 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by mateusjunges** [comment]
Thanks @pernielsentikaer!

**Pull request merged**
