### PR TITLE
Add World Cup extension language support 

### PR DESCRIPTION
**Pull request by djpowers**
## Description

Added support for additional langauges by detecting locale. Links to FIFA initially always used "ES" language, and this change supports most of the ones listed on fifa.com (in the right-hand side of the footer). Tested with each language included in the PR.

~As a bonus it also uses the translation from the API when showing the group info.~

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Looks good to me, @ismamz do you want to verify?

**Comment by ismamz** [comment]
@djpowers It looks great! We can also add locale for date string: 

image

**Comment by djpowers** [comment]
> @djpowers It looks great! We can also add locale for date string:

Thanks @ismamz! And good suggestion. I pushed a change to pass the locale when using the date-fns translation function. I intentionally left the "finished" and "now" text unchanged as they would need to be manually translated, but I think this should suffice for now.
world-cup 2022-11-22 at 09 57 49

Also I suppressed a TypeScript error I was getting, but I'm not super familiar with TS so not sure if there's a better way of handling it.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
At the moment, Raycast doesn't support localization and only supports US English. Therefore, please avoid introducing your custom way to localize your extension.

The link is okay since it's not a part of the UI, could we remove that to not break the rules?

**Comment by djpowers** [comment]
Thanks for the reminder @pernielsentikaer. I updated the PR so that no UI or language changes are made to the extension, and to only use the system locale to determine which language version the outgoing link should use.

**Review by ismamz — APPROVED** [review]

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
