### PR TITLE
Add stablecog extension

### PR DESCRIPTION
**Pull request by yekta**
## Description

It's an extension for using Stablecog via Raycast. It lets you create images with AI, upscale them, search your history and our gallery.

## Screencast

https://youtu.be/8SRbdNVgrds

https://github.com/raycast/extensions/assets/40706601/1897c809-8d91-4aee-b7f5-f6a1c65595bc

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
I accidentally merged this PR without noticing the [CI error](https://github.com/raycast/extensions/actions/runs/6466967834/job/17556062116), could you DM @pedro on [Slack](https://www.raycast.com/community) to resolve it?

**Comment by yekta** [comment]
I tried to reach out the first time I saw the CI error (about 2 weeks ago). I got an answer about 2 hours ago so DMed upon Pedro’s request to answer the questions.

**Comment by peduarte** [comment]
@yekta I am looking into this 🙂

**Pull request merged**
