### PR TITLE
Add foundry-cast-cli extension

### PR DESCRIPTION
**Pull request by merklefruit**
## Description

This extension adds commands for [Foundry Cast CLI](https://book.getfoundry.sh/cast/), a powerful tool for Ethereum developers.

## Screencast
foundry-cast-cli-1
foundry-cast-cli-3
foundry-cast-cli-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* You could maybe check if Foundry was installed, something like how [Eagle](https://www.raycast.com/Yukai/eagle) is doing it

* I don't have any knowledge here so I just entered some random numbers, could you look into dying gracefully instead?

foundry-cast-cli 2023-05-23 at 12 56 43

* Do you mind creating a screencast of the extension so I can see the flow?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by merklefruit** [comment]
Thanks for the review!

> You could maybe check if Foundry was installed, something like how [Eagle](https://www.raycast.com/Yukai/eagle) is doing it
> I don't have any knowledge here so I just entered some random numbers, could you look into dying gracefully instead?

Ok, I added an error message, so now if you try to use the extension without the binary installed it will warn you.

> Do you mind creating a screencast of the extension so I can see the flow?

Sure! 

https://github.com/raycast/extensions/assets/48695862/7e2c9e5f-c1ca-4ecd-a800-56033983a3df

**Comment by merklefruit** [comment]
Hey @pernielsentikaer can I have another review please?

**Comment by pernielsentikaer** [comment]
Do you think that it could make sense to have "commands" inside one like [Toolbox](https://www.raycast.com/Kang/toolbox) doing it? Or maybe grouped into a few commands - 26+ commands is a lot 🙂

Again, I'm not the right audience, so let me know what you think

**Comment by merklefruit** [comment]
I can look into that for sure

**Comment by merklefruit** [comment]
hi @pernielsentikaer 

I've been trying to push updates to this branch but getting this error upon calling `yarn publish`:

```
error -  getting fork
fork extensions repo: Error Body: {"message":"refusing to allow an OAuth App 
to create or update workflow `.github/workflows/pull_request_merge.yml` without `workflow` scope",
"documentation_url":"https://docs.github.com/rest/branches/branches#sync-a-fork-branch-with-the-upstream-repository"}
```

Any idea what I might be doing wrong?

**Comment by merklefruit** [comment]
Hi @pernielsentikaer 

I've taken your advice and put all the commands under a list, it's much cleaner now. The extension only exports 1 command.
Here's a video of how it looks:

https://github.com/raycast/extensions/assets/48695862/ad4dc117-f30b-4032-8b38-5472d64e6d8f

**Comment by merklefruit** [comment]
Hi @pernielsentikaer would love a review when you can! Been stale for 10 days :)

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
