### PR TITLE
Update 1password extension

### PR DESCRIPTION
**Pull request by justspacedog**
## Description

This adds the feature request https://github.com/raycast/extensions/issues/6669

## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Davidwalser** [comment]
Nice one! Also really like letting the user choose if he/she wants that feature!

**Comment by justspacedog** [comment]
> Wouldn't it be better to opt-in to this so old users are not getting confused about why it's suddenly closing the window (And maybe combine with [popToRoot](https://developers.raycast.com/api-reference/window-and-search-bar#poptoroot)

For me it is definitely the more natural way, so I think it should be the standard. Also the 1Password Quick Access does disappear automatically after copying a password.

**Comment by pernielsentikaer** [comment]
That's a fair point, what about the popToRoot - could that make sense?

**Comment by justspacedog** [comment]
> That's a fair point, what about the popToRoot - could that make sense?

Not for me - I would use context if I had to open the item in 1Password. Also the 1Password Quick Access does not clear the search.

**Comment by pernielsentikaer** [comment]
Is it intended that you removed [henrik-dmg](https://www.raycast.com/henrik-dmg) from the package.json file 🙂

**Comment by justspacedog** [comment]
> Is it intended that you removed [henrik-dmg](https://www.raycast.com/henrik-dmg) from the package.json file 🙂

I guess not 🙈

**Comment by pernielsentikaer** [comment]
re-added him 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
