### PR TITLE
[code-stash] Import action

### PR DESCRIPTION
**Pull request by ben-greenwood**
## Description
Adds a new action to allow users to import code stashes. Can either be a single .txt file or a folder containing multiple files. It will ignore any files that are not .txt extension

## Screencast

https://user-images.githubusercontent.com/32043941/213522638-e045ad1e-a467-4594-92b9-af804f31c3df.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Is there a reason why only .txt files can be imported?

Would it maybe be better to make a filter with known types?

**Comment by ben-greenwood** [comment]
> Is there a reason why only .txt files can be imported?
> 
> Would it maybe be better to make a filter with known types?

Mostly because thats what the export action exports to, but I can see value in being able to import a code file directly. Is there a way to limit the files that users can select directly from the FilePicker API? Or would I need to manually filter them?

**Comment by pernielsentikaer** [comment]
For now, it's something you'll have to do yourself - could be a preference with comma-separated extensions

**Comment by ben-greenwood** [comment]
> For now, it's something you'll have to do yourself - could be a preference with comma-separated extensions

I've updated the logic to check that its a non-media file. Think it would be cumbersome to keep a list of all valid file extensions since there would be many.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by timcastillogill** [comment]
Nive one @ben-greenwood ! Thanks for implementing. Love this extension

**Pull request merged**
