### PR TITLE
[toggl-track] Add ability to "Create Simmilar Time Entry" on entries list

### PR DESCRIPTION
**Pull request by teziovsky**
## Description

Enhanced functionality to prefill a new form entry with the details of a selected entry. This feature proves beneficial when users aim to create an entry with similar attributes such as name, project, client, etc., but with varying tags. 🚀

## Screencast

Raycast 2024-05-17 at 20 44 16

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by bkeys818** [comment]
I love it! I have a few very minor notes.
1. It'd be best to rename the PR to something more descriptive. The template that most use for Raycast extensions is this:
   - > [extension-name] Concise description.
2. I'd recommend changing the action's title to "Open Form with Time Entry's Properties"
   - I think the wording matches other Raycast action titles and better describes the action. That being said, that's solely my opinion. I'd love to hear what @franzwilhelm thinks. 
4. You might consider using `⌘ ↩` as the shortcut. It's the standard shortcut for secondary actions, and I think that this makes a lot of sense as a secondary action.

**Review by franzwilhelm — CHANGES_REQUESTED** [review]
@teziovsky Great work! I agree with @bkeys818's suggestions above.

On 2. I suggest to rename to "Create Similar Time Entry"
On 3. Apply shortcut change as @bkeys818  proposes

**Comment by teziovsky** [comment]
> @teziovsky Great work! I agree with @bkeys818's suggestions above.
> 
> On 2. I suggest to rename to "Create Similar Time Entry" On 3. Apply shortcut change as @bkeys818 proposes

Done 😎

**Comment by bkeys818** [comment]
One more request. It will take some work, but it's important.

Could you move the `tsconfig.json` and `.prettierrc` changes, corresponding import reformatting, and the addition of the Prettier plugin into a different PR?

I love the new configuration, but combining changes in PR is generally bad practice. I've been guilty of doing the same thing. It makes reviews and backtracking much harder. I definitely want to keep the changes, but could you move them to a new PR?

**Comment by teziovsky** [comment]
Oh of course 😎 Just give me some time to do this

**Comment by teziovsky** [comment]
> One more request. It will take some work, but it's relatively important.
> 
> Could you move the `tsconfig.json` and `.prettierrc` changes, corresponding import reformatting, and the addition of the Prettier plugin into a different PR?
> 
> I love the new configuration, but combining changes in PR is generally bad practice. I've been guilty of doing the same thing. It makes reviews and backtracking much harder. I definitely want to keep the changes, but could you move them to a new PR?

Done. After merging this pull request, I'll create another with `tsconfig.json` and `.prettierrc` changes 😎

**Review by franzwilhelm — APPROVED** [review]
🙌

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
