### PR TITLE
[Keyboard Brightness] Add separate increase/decrease brightness commands

### LINKED ISSUE #11592: [Keyboard Brightness] Add "Increase brightness" and "Decrease brightness" actions
### Extension

https://www.raycast.com/huzef44/keyboard-brightness

### Description

I would like to assign a keyboard shortcut to increase or decrease the keyboard brightness since they were removed. 

I'm new to Raycast but my understanding is that we would need an action for each action. That would be a welcome addition versus the "Adjust brightness" which cannot be linked to keyboard shortcut directly.

### Who will benefit from this feature?

Any user of a keyboard that doesn't have the keys for keyboard brightness.

### Anything else?

Thank you for your work!

### PR DESCRIPTION
**Pull request by belyakov-am**
## Description
Add separate increase/decrease brightness commands in order to support convenient keyboard shortcuts for both actions.

Closes #11592

## Screenshot

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by neo773** [comment]
@belyakov-am 
Hi,
Thank you for your contribution. this looks good just needs one more change could you completely remove "Sync" command? It's confusing for new users and doesn't have much of a use case.

**Comment by belyakov-am** [comment]
Hi @neo773, thanks for the review

I've removed `sync` command

**Comment by neo773** [comment]
LGTM!

Can we get this merged? @pernielsentikaer

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
