### PR TITLE
feat: add open in browser option for project navigation

### PR DESCRIPTION
**Pull request by mingo023**
## Description
Add `Open in Browser` option in project navigation
## Screencast
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by macbookandrew** [comment]
LGTM!

**Comment by pernielsentikaer** [comment]
Can you check this @tonka3000 😊

**Comment by Loskir** [comment]
Hmm receipt icon? I like something like ArrowRight more, though it's not ideal either

**Comment by pernielsentikaer** [comment]
Couldn't find a good one, feel free to suggest one - was also looking on `Desktop` maybe `ArrowRight` is better 😁

**Comment by immint023** [comment]
Hi @pernielsentikaer , @Loskir 

I tried `AppWindowList`, and that is what it looks like. Do you have any idea?

image

**Review by tonka3000 — CHANGES_REQUESTED** [review]
Looks good to me. Can you please add this for Milestones and Lables as well.

**Review by tonka3000 — APPROVED** [review]

**Pull request merged**
