### PR TITLE
Brew fixes

### LINKED ISSUE #3528: [Brew] ...
# Extension – [Brew](https://github.com/raycast/extensions/tree/78ec4dfe8b316b05dade29da7bfe6cc2a807ab22/extensions/brew/)
Author: @nhojb

## Description

Search command fails with "Something went wrong"

image

## Error:
```
Error: Parser cannot parse input: expected an object key

o1._processBuffer:search.js:2:4613

---
1: "use strict";var n6=Object.create;var le=Object.defineProperty;var o6=Object.getOwnPropertyDescriptor;var u6=Object.getOwnPropertyNames;var c6=Object.getPrototypeOf,f6=Object.prototype.hasOwnProperty;var u=(e,p)=>()=>(p||e((p={exports:{}}).exports,p),p.exports),h6=(e,p)=>{for(var a in p)le(e,a,{get:p[a],enumerable:!0})},$p=(e,p,a,d)=>{if(p&&typeof p=="object"||typeof p=="function")for(let t of u6(p))!f6.call(e,t)&&t!==a&&le(e,t,{get:()=>p[t],enumerable:!(d=o6(p,t))||d.enumerable});return e};var Z=(e,p,a)=>(a=e!=null?n6(c6(e)):{},$p(p||!e||!e.__esModule?le(a,"default",{value:e,enumerable:!0}):a,e)),v6=e=>$p(le({},"__esModule",{value:!0}),e);var Mp=u((N3,jp)=>{"use strict";var y={};jp.exports=y;function qp(e){return e<0?-1:1}function w6(e){return e%1===.5&&(e&1)===0?Math.floor(e):Math.round(e)}function c1(e,p){p.unsigned||--e;let a=p.unsigned?0:-Math.pow(2,e),d=Math.pow(2,e)-

... [trimmed because it's too long for github] ...

({stdout:e,stderr:p,all:a,error:d,signal:t,exitCode:i,command:m,escapedCommand:s,timedOut:l,isCanceled:n,killed:v,parsed:{options:{timeout:S}}})=>{i=i===null?void 0:i,t=t===null?void 0:t;let x=t===void 0?void 0:u9[t].description,V=d&&d.code,A=`Command ${c9({timedOut:l,timeout:S,errorCode:V,signal:t,signalDescription:x,exitCode:i,isCanceled:n})}: ${m}`,C=Object.prototype.toString.call(d)==="[object Error]",J=C?`${A}
5: ${d.message}`:A,G=[J,p,e].filter(Boolean).join(`
---

o1._transformBuffer:search.js:1:312346
Transform._write:transform:175:8
writeOrBuffer:writable:392:12
```

## Steps To Reproduce

1. Open Raycast
2. Type Brew
3. Select "Search" and hit Enter

### Raycast version
Version: 1.43.2

### LINKED ISSUE #3534: [Brew] Extension hangs if you type while the list is loading
# Extension – [Brew](https://github.com/raycast/extensions/tree/78ec4dfe8b316b05dade29da7bfe6cc2a807ab22/extensions/brew/)
Author: @nhojb

## Description

If you start typing before the list is loaded you'll get this:

CleanShot 2022-11-15 at 18 49 34@2x

## Steps To Reproduce

1. Start typing before the list is loaded.

## The current behavior

The extension hangs.

## The expected behavior

Filter the list after it loads.

### Raycast version
Version: 1.43.2

### PR DESCRIPTION
**Pull request by nhojb**
## Description

- Improve error handling for invalid json cache
Fixes #3528, #3535

- Ensure cache is fetched only once (avoids memory errors).
Fixes #3534

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by mathieudutour — APPROVED** [review]
sounds good but I'm wondering if you should abort the current search if you have a new one - otherwise you might run into race conditions. Happy to look at it if you'd like

**Comment by nhojb** [comment]
> sounds good but I'm wondering if you should abort the current search if you have a new one
> Happy to look at it if you'd like

That's a good idea! If you have the time to look into this that would be much appreciated 😄 

It might be better to merge this PR now - because it addresses some crashes users are reporting - then create a new PR to address the search issue?

**Comment by mathieudutour** [comment]
yeah absolutely, let's merge and I'll have a look when I have a moment

**Review by pernielsentikaer — APPROVED** [review]
That sounds like a good plan, I tested that all commands are still working 🔥

**Comment by pernielsentikaer** [comment]
You're so fast 😊 I was almost done with the CHANGELOG 😁

**Comment by nhojb** [comment]
> You're so fast 😊 I was almost done with the CHANGELOG 😁

Opps! I _always_ forget about the CHANGELOG 😥

**Comment by pernielsentikaer** [comment]
Added! 😁

**Comment by nhojb** [comment]
TBH I am never quite sure where to find CHANGELOG for extensions in Raycast. Might be useful if it was linked from the extensions's preferences? It's really hidden away in the Store detail `View Version History` action.

**Pull request merged**
