### PR TITLE
feat: add `checkout-b` extension

### PR DESCRIPTION
**Pull request by devjiwonchoi**
## Description

This extension creates a branch name based on users' preference. Also includes creating a random branch name.

## Screencast

https://github.com/raycast/extensions/assets/120007119/620400b3-0494-445d-8589-56a9f8fef829

https://github.com/raycast/extensions/assets/120007119/63594aa2-e58c-4243-bd82-e2da89143601

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @devjiwonchoi  👋

Thanks for your contribution 🔥

Did you see https://www.raycast.com/mbonner/git-branch-name-generator by @michaelbonner before creating this, maybe it could be some kind of enhancement instead?

**Comment by devjiwonchoi** [comment]
@pernielsentikaer Yes! I did try it but generating random names, including git commands on clipboard, output conventions, etc. seem to be apart, is the reason why I proposed as a separate extension.

**Comment by devjiwonchoi** [comment]
cc @pernielsentikaer

@michaelbonner I'm willing to merge the extension for enhancement, what do you think?

**Comment by michaelbonner** [comment]
@devjiwonchoi Yeah, they seem different enough to me. I'm happy to collaborate to unify the two extensions if you think that's better.

**Comment by pernielsentikaer** [comment]
I don't think they are that much different, are they? This has a bit more features but the outcome is almost the same

**Comment by devjiwonchoi** [comment]
Yea I think we can merge it, mind if we use my branch types? e.g. chore, fix, feat, etc.

**Comment by devjiwonchoi** [comment]
Ported to #13155

**Pull request closed without merging**
