### PR TITLE
Add Ruby Evaluate Extension

### PR DESCRIPTION
**Pull request by obahareth**
## Description

Adds an extension that allows live evaluation of Ruby code, and copying either the code or the result.

This is inspired by @selfish's Node Evaluate extension.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

## Help
I tried my best attempt at making the screenshots follow the guidelines but I am not sure if I managed it successfully or not. This isn't my strongest area.

I also asked for help on this in the Raycast community.

### CODE REVIEW

**Comment by selfish** [comment]
@obahareth this is superb!
I was planning to add Ruby, and Go but I had little time for it recently.
Thank you! 🤩

**Comment by alextrueman** [comment]
@obahareth it looks awesome! 🤓
Should be vertical helpful tool! 👏👏👏

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @obahareth 👋 

Like the other extension, I think we should implement a preference to turn on auto evaluation that is off by default to ensure that the user understands what he is doing. Could you look into this?

**Comment by obahareth** [comment]
Hey @pernielsentikaer, sure!

**Comment by kudrykv** [comment]
Would it be better to use the form and text field? 🤔

What I'm looking for is multiline editing. Sometimes what you need are a few additional lines.

**Comment by obahareth** [comment]
@kudrykv What do you think of adding that to the slow evaluation mode? (e.g. you have to press enter to have the code evaluated).

**Comment by kudrykv** [comment]
@obahareth pressing enter feels like a fast mode to me :)
It's my two cents, and you can disregard that it doesn't make sense.

**Comment by pernielsentikaer** [comment]
Just checking here, what's the status? It's been a while since last time 🙂

**Comment by pernielsentikaer** [comment]
I'm closing this due to inactivity; feel free to open it again or comment in the thread when you're ready to continue working on it 🙂

You can also catch me here or in [Slack](https://www.raycast.com/community) if you want to discuss 😄

**Comment by selfish** [comment]
Unfortunate. I was waiting to see it in the store 😞

**Comment by obahareth** [comment]
Sorry guys I just started a new job and couldn't get around to making the requested changes, I will try to find the time in a few weeks.

**Comment by obahareth** [comment]
@pernielsentikaer I don't see an option to reopen the pull request, what should I do when I am ready to work on it again?

**Comment by pernielsentikaer** [comment]
It's open again @obahareth :)

**Comment by obahareth** [comment]
Sorry for the delay everyone, apparently I did the changes while I was on vacation and totally forgot about it 💀 

@pernielsentikaer does this look alright to you now?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
