### PR TITLE
Add trek extension

### PR DESCRIPTION
**Pull request by opti21**
## Description

Manage your projects and todos from Basecamp directly in Raycast.

## Screencast

https://github.com/user-attachments/assets/4f345c7f-f0db-4d72-b0c9-d15d80f102ed

Assignments
CleanShot 2024-11-15 at 16 52 14@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
There is a mix of `Trek` and `Basecamp` going on. What's Trek? Wouldn't it be better to use the real name for it to make its purpose more clear?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
- Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

**Comment by opti21** [comment]
I tried running `npx @raycast/api@latest pull-contributions`

But that doesn't seem to change anything? And after running it I still get the same error.

**Comment by opti21** [comment]
Ran the git command that errored and it gave this error:
```
fatal: Not a valid commit name 224c620199d62254c4b13390f63eeb3403d754b8
```

**Comment by pernielsentikaer** [comment]
Can you send me the emails, and I'll add them? It sounds like GitHub is having some hiccups

**Comment by pernielsentikaer** [comment]
Is everything added so I can review?

**Comment by opti21** [comment]
Oh sorry yes everything is added

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
