### PR TITLE
feat: 3rd party Surge extension

### PR DESCRIPTION
**Pull request by ysj151215**
## Description

[Surge](https://nssurge.com/) is a web development and proxy utility. It is designed for developers and therefore requires professional knowledge to use.

**Surge for Raycast** is an **unofficial** launcher extension to help you handle specific Surge features from Raycast app.

## Type of change

New extension

## Screencast

Surge for Raycast screenshot

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @ysj151215 👋 

Thanks for your contribution 🔥 

I have some feedback for the extension:

- If other ActionPanel items has icons, so should yours 😄 

KghqOWlyvy7R3ue2

- When an error occurs (like wrong configuration), could you then stop the loader and show "No results" instead 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by ysj151215** [comment]
Hi @pernielsentikaer 👋

Thanks for your feedback and suggestions! 😉

In the latest commits, I have:
- Added default warning icons for all ActionPanel items. [see the 1st image attached]
- Added a new Detail with "No results". [see the 2nd image attached]

bugfix 1
bugfix 2

**Comment by pernielsentikaer** [comment]
Thank you for the update, much better! 🔥 

I'm going to accept it and then will my colleague do a final review before it's finally merged.

**Comment by ysj151215** [comment]
@pernielsentikaer Appreciated!

**Pull request merged**
