### PR TITLE
Add Aleph Tools extention

### PR DESCRIPTION
**Pull request by d7mtg**
## Description

Aleph Tools, a set of specific text tools that work for Hebrew typesetter and designers. For more, see https://d7m.tg/aleph/V2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by d7mtg** [comment]
Just checking in, generally how long does it take for an extension to be published to the store?

**Comment by mil3na** [comment]
Hi @d7mtg ! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

Right now, your extension expects the user to have selected text to use as input. Have you considered also getting text input from the input bar? Otherwise, explain on a README file or the error action bar that you expect the input to be the selected text. I wonder if it would be better from a usability point of view.

**Comment by d7mtg** [comment]
I have considered it, more as a V2. Is it fine to launch as is and 

I’d that functionality later?

If so, what would I be writing in the readme?

**Comment by d7mtg** [comment]
My current error says “Encode failed: no text selected”

**Comment by mil3na** [comment]
A one-sentence saying what your extension does (like on the description of your PR) and adding that it will work with the selected text. That would suffice for me.

**Comment by d7mtg** [comment]
@mil3na How's this? 

https://github.com/d7mtg/extensions/tree/main/extensions/aleph

**Review by mil3na — APPROVED** [review]
Better than I expected! And TIL about Niqqud. Thanks for your effort :)

**Comment by d7mtg** [comment]
Thanks a lot!

1. How long until it's live on the store?
2. Any pointers to make the extension work with input text/fallback commands?

**Comment by mil3na** [comment]
1. It is already live! Take a look at the look above :)
2. There are many ways to go about this. My suggestion is to check if there's anything selected and, if not, instead of outputting an error, redirect to a [form](https://developers.raycast.com/api-reference/user-interface/form). You can also find an extension that does something similar and get inspired :)

**Pull request merged**
