### PR TITLE
Add preferred format check for LogSearch

### PR DESCRIPTION
**Pull request by yishus**
## Description

Add org files support for LogSearch by fetching preferred format from Logseq config

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@futantan could you look into this PR and give a review?

**Comment by yishus** [comment]
Bumping this

**Comment by pernielsentikaer** [comment]
Wrote the author

**Comment by futantan** [comment]
Anything I can help?

**Comment by futantan** [comment]
image

**Comment by futantan** [comment]
@yishus @pernielsentikaer 
Sorry, my bad, I forgot to submit the review. 16 days ago...

**Comment by pernielsentikaer** [comment]
Thanks for taking your time @futantan 🔥

**Review by futantan — APPROVED** [review]
LGTM

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
