### PR TITLE
fix: custom endpoin setting and switch

### PR DESCRIPTION
**Pull request by Nauxscript**
## Description

fixed the problem in #6643 , have no setting to input custom api.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Could you check this @abielzulio 🔥 

There seems to be a linter error @Nauxscript - could you resolve this?

**Comment by Nauxscript** [comment]
> Could you check this @abielzulio 🔥
> 
> There seems to be a linter error @Nauxscript - could you resolve this?

of course! I am working on it 😀

**Comment by Nauxscript** [comment]
I dont know what problems in `package.json` 😂, could u help me? @pernielsentikaer

**Comment by Nauxscript** [comment]
It's all done, can't wait to use it😂

**Review by abielzulio — APPROVED** [review]

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by HatsuneMK00** [comment]
@Nauxscript  Hi!. I'm trying to set custom api but get this error. The same url works fine in another app that using openAI api. Could you please help me locate where is wrong? I have "https://myurl.top" in the apiEndpoint and have the useApiEndpoint checked.
=====================
Error: Request failed with status code 404

gt.exports:createError.js:16:14
yt.exports:ask.js:2:7730
IncomingMessage.<anonymous>:ask.js:7:11799
IncomingMessage.emit:node:events:525:35

**Pull request merged**
