### PR TITLE
Update lodash extension

### PR DESCRIPTION
**Pull request by rushi**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by rushi** [comment]
@vimtor The `lodash.json` was quite out-of-date and I relied on this extension quite a bit so I decided to bring it up to date. 

I wasn't sure how you generated the original JSON file, so after quite a bit of hacking around I landed on using the Lodash's markdown generating logic to output a JSON file instead. I tried my best to keep the diff simpler, but there are a few key changes:

1. Changes from using `var` to `const`
2. Semi-colons are used in examples. So `_.before(foo);` instead of `_.before(foo)`
3. Show default values for the parameters
4. Several parameters have changed from `optional: false` to `optional: true` and vice-versa

**Comment by vimtor** [comment]
Thanks for the contribution @rushi!

Could you add the script you used as an npm script so we can run it in the future?

**Comment by rushi** [comment]
@vimtor To generate the JSON file, I cloned [Lodash](https://github.com/lodash/lodash) and replaced `node_modules/docdown/lib/generator.js` with a modified file that I have uploaded here https://gist.github.com/rushi/26bb0ed6669037e5a3f55ee595d039e6. Then run `node lib/main/build-doc.js` to generate the file

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
