### PR TITLE
Update web-audit extension

### PR DESCRIPTION
**Pull request by flornkm**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Nothing happens when I open/close tips - what is supposed to happen? 😊

**Comment by floriandwt** [comment]
@pernielsentikaer the issue should be fixed now 😊

**Comment by pernielsentikaer** [comment]
The only thing I miss is a loading indicator, maybe something like:

```
      {loading && <Detail isLoading={true} navigationTitle="Analyzing..." />}
      {result && !loading && (
      ...
```

And then set the initial state to `true` for `loading`

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
