### PR TITLE
Sourcegraph: Search fixes, hover tooltips

### PR DESCRIPTION
**Pull request by bobheadxi**
## Description

- **search**: Internal improvements to mitigate stuttering when typing search queries.
- **search**: Icons, titles, and subtitles in the main search results list are now all hoverable to see more details.
- **batch-changes**: Some list elements are now hoverable for additional details.
- **notebooks**: Some list elements are now hoverable for additional details.

## Screencast

Hover tooltips:

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi @bobheadxi 👋 

Thanks for the update, it works as expected - I do have a question:

- Don't we have a better title to show? Tooltips are meant to be more subtle. Seems like most of this data should be added in a Detail view instead.

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
And an example of what I mean:
CleanShot 2022-04-29 at 21 34 27@2x

**Comment by bobheadxi** [comment]
Thanks you for the review @pernielsentikaer , I'll make an update to address your specific scenario and similar ones!

Is the example in the PR description (expanding a short description) okay? I would like to keep that specific behaviour if possible

**Comment by bobheadxi** [comment]
@pernielsentikaer I have made some updates to make some of the tooltips more subtle, see https://github.com/bobheadxi/raycast-sourcegraph/commit/fbdc1f0d893778567a60fa340fb6006e4dd362fc :

image

**Review by pernielsentikaer — APPROVED** [review]
I think it's much better than before, let's go with that and see if there is anything we can improve later on 🔥

**Pull request merged**
