### PR TITLE
Update 1password extension

### PR DESCRIPTION
**Pull request by luizvergennes**
## Description

Fixes the bug for when users have multiple accounts in the 1Password app. Now it shows an account selection screen where users are able to select the user they want to use. Which can be later on switched using the action "Switch Account".

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by kjeldahl** [comment]
@Luk4h I cannot change account unless I reset the cache.

The account drop down is not populated, the spinner is just spinning:
image

**Comment by Luk4h** [comment]
@kjeldahl there should be an action "Switch account", which signs out and allows you to select another account. What is the flow where you are currently getting problems

**Comment by kjeldahl** [comment]
@Luk4h it is when I use the switch account action.
I open My Passwords press Cmd-k and choose Switch account. It opens the dialog I pasted an image of above, but the selector is never populated and the spinner keeps going.

**Comment by daninfpj** [comment]
Thanks for this, was looking forward to it!

However, it’s currently not working for me.

The dropdown is displayed correctly with my accounts, but when trying to “Sign In” to either of them, I get:

> Command failed: /usr/local/bin/op signin --account xxx
[ERROR] 2024/05/22 10:46:56 found no accounts for filter "xxx"

If I run `op account list` in my terminal I don’t see that ID. The list of IDs there seem to be stable, whereas every time I load the accounts in the extension they seem to have a different ID.

Maybe a workaround would be to refer to the account by URL?

**Comment by Luk4h** [comment]
Hey @daninfpj, Do you mind testing the latest PR? #12510 There are instructions there to how you can test it!

**Pull request merged**
