### PR TITLE
Update pokedex extension

### PR DESCRIPTION
**Pull request by miguel-felix1**
## Description

Fix Learnset information crashing the extension due to missing or undefined information coming from PokeAPI

Fixes: #12410

## Screencast

Before:
Screenshot 2024-05-17 at 01 04 58

After:
Screenshot 2024-05-17 at 01 05 16

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by anhthang** [comment]
@miguel-felix1 thanks for the fixes

**Comment by miguel-felix1** [comment]
> @miguel-felix1 thanks for the fixes

No problem ! Love your extension and use it extensively while playing !
Hey I have an extension of my own and I wanted to ask first because it could be on your radar/todo list, it features type effectiveness charts kinda like how Bulbapedia has for each Pokemon detail, would it be ok if I add (and adapt using your code style/layout design) this feature ? Another thing I had planned for my own extension was type matchups between Pokemon, you select a Pokemon A and a Pokemon B and it shows their weaknesses/effectiveness, I think it could enrich this already amazing extension, really digging the design btw ! Here's mine, I'm still an amateur :D

Screenshot 2024-05-17 at 09 03 28

**Comment by pernielsentikaer** [comment]
Let's merge this but you can keep commenting in the thread 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by anhthang** [comment]
> No problem @anhthang ! Love your extension and use it extensively while playing ! Hey I have an extension of my own and I wanted to ask first because it could be on your radar/todo list, it features type effectiveness charts kinda like how Bulbapedia has for each Pokemon detail, would it be ok if I add (and adapt using your code style/layout design) this feature ? Another thing I had planned for my own extension was type matchups between Pokemon, you select a Pokemon A and a Pokemon B and it shows their weaknesses/effectiveness against each other, I think it could enrich this already amazing extension, really digging the design btw ! Here's mine, I'm still an amateur :D

Hi @miguel-felix1 Feel free to reuse the code style and layout design from this extension in your own projects!

I originally planned to add a feature highlighting weaknesses and effectiveness, but due to time constraints and limitations, I wasn't able to implement it effectively.

If you're interested in contributing, I believe we could easily add this functionality by creating sub-actions for things like "Entries" and "Learnset."

image

I'd be happy to have you involved. If you do make changes, I'd really appreciate it if you could sync them back to [my repository](https://github.com/anhthang/raycast-pokedex) for this extension.

**Pull request merged**
