### PR TITLE
New Extension: Add NATO Phonetic Alphabet

### PR DESCRIPTION
**Pull request by jesse-c**
## Description

Something I wish I had when I was on a telephone call and was needing to spell something out.

It adds 2 commands, one to see the full alphabet, and one to transform a term (alphanumeric only) to the NATO phonetic alphabet equivalent, with pronunciation.

## Screencast

**Full alphabet**

image

**Transformed term**

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
That's an excellent extension. Could you support `space` so it's possible to write a sentence?

I crashes pretty hard if I add a space 😊

**Comment by jesse-c** [comment]
Sure thing. I thought about doing it a first.

image

**Comment by pernielsentikaer** [comment]
Awesome work @jesse-c 🔥 

I added a few things, do you mind check if you're okay with them 😊

**Comment by jesse-c** [comment]
@pernielsentikaer: Thanks mate! The changes look good in general and I've tweaked them more to my liking. :)

**Comment by pernielsentikaer** [comment]
If I spell the word as `Boat` it fails

Raycast-Zsqja9hs@2x

Can you look into this @jesse-c

**Comment by jesse-c** [comment]
Done, it handles uppercase now. Good to be approved? ;)

**Review by pernielsentikaer — APPROVED** [review]
Yes! 🎉

**Comment by jesse-c** [comment]
Woo, thank you @pernielsentikaer!

**Pull request merged**
