### PR TITLE
[Update] [Wi-Fi] Add new menubar command

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

- Wi-Fi Signal: Show Wi-Fi signal strength in the menubar

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
When I click on the menubar it makes a bit jump, could you look into this?

Raycast-D9gHMCJF

**Comment by koinzhang** [comment]
Hi @pernielsentikaer. I think it's a Raycast bug, even if I don't update the datasource, it still blinks.

**Comment by koinzhang** [comment]
Hi @pernielsentikaer. I've submitted a commit that fixes the icon flickering when clicking on the menu bar icon

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
