### PR TITLE
Add the Ukrainian language to the Deepcast extension

### PR DESCRIPTION
**Pull request by Popalay**
## Description

Adds the Ukrainian language to the Deepcast extension
https://www.deepl.com/ru/docs-api/translate-text/

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you have a raycast handle? If so, you might add it to package.json under contributors

**Comment by Popalay** [comment]
> Do you have a raycast handle? If so, you might add it to package.json under contributors

Updated

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
