### PR TITLE
Add screen-math extension

### PR DESCRIPTION
**Pull request by hcancelik**
## Description

This extension helps you quickly sum up the numbers on the screen without copying them to a file. It uses the Vision framework to convert the text to numbers. 

## Screencast

https://github.com/raycast/extensions/assets/5788410/4d3f95c7-d417-4dbc-ac73-feb9dc3825dc

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

I just tested this and can't get it to work, when opening the extension I get the selection tool, when selecting numbers nothing else happens. 

It might be because it needs a unique structure, could you look at how swift files are placed in [Coler Picker](https://www.raycast.com/thomas/color-picker)

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by hcancelik** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> I just tested this and can't get it to work, when opening the extension I get the selection tool, when selecting numbers nothing else happens.
> 
> It might be because it needs a unique structure, could you look at how swift files are placed in [Coler Picker](https://www.raycast.com/thomas/color-picker)
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Hi @pernielsentikaer 

Thanks for your feedback. 

Do you see a notification in HUD display after selecting the numbers? 
Or right after selecting the area can you trigger the Raycast to see the numbers?

I couldn't find a way to re-trigger the raycast window to display the number so I'm using HUD to display the total but they are also available right after the screenshot is taken.

**Comment by hcancelik** [comment]
@pernielsentikaer 

Also not sure why but I'm getting this error. My email is celik@me.com

Screenshot 2023-08-21 at 11 18 46

**Comment by hcancelik** [comment]
@pernielsentikaer I updated to code to reopen the ray cast window after the screenshot, which should be more user-friendly now.

**Comment by pernielsentikaer** [comment]
This still fails if you have pop to root search set to immediately - maybe a HUD like color picker (and copy to clipboard) is the best way for now, or maybe combine with a menubar with the results?

**Comment by hcancelik** [comment]
@pernielsentikaer Interesting. `showHUD` doesn't run when pop to root is set to immediately and command mode is set to `view`. Not sure if this is an internal bug but I will do more research what I can do. 

I will let you know when it is ready. Thanks for your feedback.

**Comment by pernielsentikaer** [comment]
Not sure how it's done, but it seems to work fine in Pick Color actually, also with that pop to root value

**Comment by hcancelik** [comment]
> Not sure how it's done, but it seems to work fine in Pick Color actually, also with that pop to root value

Pick Color doesn't display a view after the color is picked. It uses `no-view` for the pick color command.

I would like to display the numbers that are being recognized after the screenshot is taken. (if possible :) )

**Comment by hcancelik** [comment]
@pernielsentikaer 

I changed the extension to use `no-view` like Pick Color until I find a solution for displaying the numbers on Raycast Detail view. 

After the calculation, it shows HUD and copies all the numbers (along with the total) to the clipboard. 

I hope this meets the requirements. Please let me know if there is anything else I need to change.

**Comment by hcancelik** [comment]
@pernielsentikaer Is there anything else I need to do to get this PR moving?

**Comment by hcancelik** [comment]
@pernielsentikaer Can you test this in stable macOS version to see if that's working?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
