### PR TITLE
Add miti-raycast extension

### PR DESCRIPTION
**Pull request by Parajulibkrm**
## Description
It adds two commands
- Menu Bar to Show Current Bikram Sambat Calendar (Nepal uses a different calendar system 57 years ahead of AD calendar) 
- Converter command to convert between AD to BS and vice versa

## Screencast

image
image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
I don't know anything about the subject, so sorry if my answer here is all wrong 🙂

Is this related to this: https://www.raycast.com/amin_saedi/jalali-date-convertor

**Comment by Parajulibkrm** [comment]
@pernielsentikaer Not at all, it's an entirely different calendar system.

**Comment by Parajulibkrm** [comment]
https://www.raycast.com/beedhan/nepali-date-converter
This is the closest one available in Raycast but this one takes a completely different approach like Menu bar

**Comment by Parajulibkrm** [comment]
@pernielsentikaer  any update on this?

**Comment by pernielsentikaer** [comment]
What about enhancing the current setup? We all want the best possible extensions. We can ask @Beedhan what he thinks :)

**Comment by Parajulibkrm** [comment]
Still think it's best published as a separate one, the features are entirely different and the approach is different. Also this one consumes some endpoints from https://github.com/PoskOfficial/Miti project and contains some Miti Branding? Not sure if replacing the entire code, functionality and adding Miti branding would do justice to @Beedhan's project?

**Comment by Beedhan** [comment]
I developed the Nepali Date Converter because I couldn’t find any existing extension. If an instant (no-view mode) date converter, like mine, I no longer see the need for my version. In that case, I think it’s better to remove my extension now, as Miti offers much more.

**Comment by Parajulibkrm** [comment]
@pernielsentikaer can we have this merged?

**Comment by pernielsentikaer** [comment]
What about instead of removing your extension we just override with this extension so all current users will get the new version?

So basicly you need to override the files in the current extension, does that make sense @Parajulibkrm

**Comment by Parajulibkrm** [comment]
@pernielsentikaer I still don't see the point in that, I'm not sure why that would be a good idea. Is there no other way to this can go through?

**Pull request closed without merging**
