### PR TITLE
Added mlb-score extension

### PR DESCRIPTION
**Pull request by jso8910**
## Description

This is an extension to view the day's current MLB games extremely quickly. Pressing enter while hovering over a list item will bring you to a view which contains a summary of the game and some extra info if it is currently ongoing. If a game is yet to start, you will be told when the game starts in your own timezone.

## Screenshots
This is a pretty simple extension so I am just adding 3 screenshots:

Screenshot
Screenshot (1)
Screenshot (2)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by sxn** [comment]
hey @jso8910 , congrats on the new extension! Looks like the extension's manifest is missing a [description](https://developers.raycast.com/information/manifest#extension-properties), which is causing CI to fail. Mind adding one? 😉

**Comment by pernielsentikaer** [comment]
Hi @jso8910 👋 

If the game is canceled, then it shouldn't show undefined (or show something else) 

NLNUZ4qEksrudxLZ - Can you look into this?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by jso8910** [comment]
I'm not around my laptop rn so I can't quite change it but that is weird. I
thought my code contained a check for if it was undefined. I think I had it
set to show 0 instead of undefined. By the way, that game is likely just a
game which hasn't started yet.

**Comment by pernielsentikaer** [comment]
Hi @jso8910 👋 

The game says canceled in the list. Do you have time in the nearest future to look into this? 💪

**Comment by jso8910** [comment]
I can look into this, however I don't have my laptop with me. This might be
a simple fix that I can implement on my phone so I'll look at the code.

**Comment by jso8910** [comment]
Apologize, I don't know how but I accidentally deleted a file then committed. I will add it back promptly.

**Review by pernielsentikaer — APPROVED** [review]
Hi @jso8910 👋 

I ran Prettier on the file and moved the changelog; I hope it's okay 😄 

It looks much better now, thanks! I'm going to merge it now, and then you can always clean and make it better in a new PR 💪 

Thanks for your contribution 💯

**Pull request merged**
