### PR TITLE
Add Brand.dev extension

### PR DESCRIPTION
**Pull request by xmok**
## Description

This is a Raycast extension to get a company's brand logos, colors, slogan, socials, and more via the Brand.dev API.
Similar to the [Brandfetch extension](https://www.raycast.com/dilutedev/brand-fetch).

## Screencast

https://github.com/raycast/extensions/assets/30526133/8d35e05b-2d99-4d27-9439-284f805a7a80

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

At first glance, I think the UX of your extension can do a bit better. My suggestions are the following:
- Have a list command with all the brands you already searched
- The list command would be a panel divided into list of brands and details
- Inspiration on how to show each brand:
CleanShot 2024-07-05 at 11 59 36

- The search brand command could be an inline form where the result would be shown in a detail view like on the list OR incorporate search on the list command and do the search in case the brand the user submitted is not found.

Please, take a look at my comments and tell me what you think :)

**Comment by xmok** [comment]
Hi mil3na,

Your suggestions made a lot of sense and I have updated the extension to show the stored items first. For Search I went with a Form rather than using the List Search because I don't want a user to accidentally fetch and use up their limited API calls.

Here's an updated screencast:

https://github.com/raycast/extensions/assets/30526133/02b0ec1a-0caf-4cb9-af5f-90209a52db91

**Comment by mil3na** [comment]
I still think the presentation can be better. On the left side, you can have headers and separators, so it is not just a bunch of text thrown at the user's face. Also, Description is duplicated, but cut on the right side. The colors have potential to be on the right side, etc. 

CleanShot 2024-07-09 at 10 42 50

**Review by mil3na — APPROVED** [review]
Looks way better now! Thanks for your effort!

**Pull request merged**
