### PR TITLE
Change Case Extension Improvement

### PR DESCRIPTION
**Pull request by yug2005**
## Description

Added some features to the change case extension that I think everyone would find useful. 
* Added a list detail view for a better view of the modified text
* Added the option to choose your primary action:  copy to clipboard or paste to active app
* Added the ability to pin cases 
* Added recent cases (up to 4 cases that were used most recently)

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you mind checking this @es183923 😊

**Comment by pernielsentikaer** [comment]
Hi @yug2005 🔥 

Do you mind adding a CHANGELOG entry and resolving the conflict?

@es183923 do you have time to check this yet?

**Comment by yug2005** [comment]
@pernielsentikaer done. lmk if CHANGELOG is good

**Comment by pernielsentikaer** [comment]
awaiting @es183923 😊

**Comment by es183923** [comment]
Looks pretty cool! LGTM

**Pull request merged**
