### PR TITLE
[New Extension] Phosphor Icons

### PR DESCRIPTION
**Pull request by SKaplanOfficial**
## Description

This is a new extension for searching [Phosphor Icons](https://phosphoricons.com/). It works very similarly to other icon search extensions such as css.gg, Heroicons, etc.

## Screencast

[phosphor-icons-demo.webm](https://github.com/raycast/extensions/assets/7865925/de456ced-8083-47ac-92ec-a77efe708073)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @SKaplanOfficial 👋 

When it was around 45% I got the error, can you look into this? Let me know if you need more to debug it

phosphor-icons 2024-02-01 at 11 44 41

**Comment by pernielsentikaer** [comment]
Would also be nice with some `inset` since they fill the box 100%

phosphor-icons 2024-02-01 at 11 46 18

**Comment by SKaplanOfficial** [comment]
Hi @pernielsentikaer, I reverted to having icons in the assets folder as errors kept arising when making so many requests to GitHub, and I would have to update the phosphor-icons dependency for any significant changes to show anyway, so it doesn't seem worth it. Also added an inset.

**Comment by pernielsentikaer** [comment]
Hi @SKaplanOfficial 👋 

Much better 👏 

Can we do something with the extension icon in darkmode?

Raycast07022024-KDeDKGTM png@2x

Request a new review when you ready 🙂

**Comment by SKaplanOfficial** [comment]
@pernielsentikaer The icon should always have a yellow background. There's no transparent asset, so I'm not sure why it's displaying that way for you. Any ideas?

Raycast 2024-02-07 at 07 29 07

**Comment by pernielsentikaer** [comment]
I think it's because there are so many icons in the PR, which is not ideal.

Could we do something like getting images from an npm package and move them to the assets folder on build?

**Comment by SKaplanOfficial** [comment]
@pernielsentikaer I'm not able to work on this at this time, so please move forward with #10618

**Pull request closed without merging**
