### PR TITLE
fix: unknown filter_type

### PR DESCRIPTION
**Pull request by k8scat**
## Description

`Undefined` label showed after searching images which was caused by the undefined `filter_type`.

## Screencast

Before fix:

image

After fix:

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by k8scat** [comment]
The local lint via `npm run lint` is already ok, why the [workflow](https://github.com/raycast/extensions/runs/6589414055?check_suite_focus=true) still failed?

**Comment by pernielsentikaer** [comment]
Hi @k8scat 👋 

It's because the used API version was so old that it was not possible to lint better, I updated the extension to the newest API, could you give it a quick spin?

**Comment by k8scat** [comment]
Thanks. Is there any other review?

**Review by pernielsentikaer — APPROVED** [review]
No, let's get it merged 🔥

**Pull request merged**
