### PR TITLE
feat: 🎸 first version of Bitcoin price

### PR DESCRIPTION
**Pull request by futantan**
## Description

Add extension to show the price of bitcoin

## Screencast
CleanShot 2022-09-30 at 10 10 16@2x

CleanShot 2022-09-30 at 10 10 31@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @futantan 👋 

Thanks for your contribution, however, it looks exactly like [this one](https://www.raycast.com/peduarte/ethereum-price) - seems like you had the same idea

**Comment by futantan** [comment]
@pernielsentikaer Yes, I mentioned that in the readme.
The extension you mentioned is about ETH, this extension is about BTC. They are different.

I considered to contribute to that extension, but the name of the extension is `Ethereum Price`, so it's not suitable to include BTC in that extension.
Any suggestions?

**Comment by futantan** [comment]
cc @peduarte

**Review by pernielsentikaer — APPROVED** [review]
Thanks for the contribution 💯 

For now, I have removed the metadata images since we haven't tackled this part yet.

We're planning a new Figma template to support extensions that only have a menubar, but we're not yet ready with that; I'll try to keep you updated when we have a good solution for this 🙂

**Pull request merged**
