### PR TITLE
Update pipedrive extension

### PR DESCRIPTION
**Pull request by ahpatel**
- Updated to allow search of contact and organizations, in addition to deals.  Libraries and dependencies also updated
- Initial commit

## Description

- Adds ability to search across Pipeline deals, contacts and organizations.
- Add ability to easily copy search result details (i.e,. name, email, phone number of a contact)
- Refreshed the Pipedrive icon per the latest media kit (green  logo)
- Updated dependencies

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by ahpatel** [comment]
@stephendolan  @wimsy - I tried submitting some of these changes a few months ago, but I've cleaned up some code on the local instance I was using and thought I'd try pushing the enhancements again.  

Would you consider merging these into your original plugin or is it no longer being maintained?

**Comment by wimsy** [comment]
Hey @ahpatel I'm technically a contributor because I submitted one very small update a couple of months ago, but I don't think I'm the guy to review the extensive (but useful!) changes you're proposing.

**Comment by pernielsentikaer** [comment]
@stephendolan are you able to check this PR?

**Comment by stephendolan** [comment]
@pernielsentikaer Unfortunately we've no longer got an active Pipedrive subscription, so I don't have a way to test this code (aside from also not really having the motivation to act as the maintainer for this extension).

It's been a while since I've written a Raycast Extension, but the changes seem okay to me!

**Comment by pernielsentikaer** [comment]
@stephendolan all good 🤗 Thanks for everything you done 🔥

Do you want @ahpatel to be the new owner of this extension so you're getting all removed?

**Comment by stephendolan** [comment]
@pernielsentikaer Yes, I’m good with that!

**Comment by pernielsentikaer** [comment]
@ahpatel what do you need `react-dom` for?

**Comment by ahpatel** [comment]
> @ahpatel what do you need `react-dom` for?

@pernielsentikaer  Not needed.  A remnant that can be removed from the dependencies.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
