### PR TITLE
[ChatGPT] Allow to hide model selector when asking a question

### PR DESCRIPTION
**Pull request by irangarcia**
## Description

Allow to hide model selector when asking a question

## Screencast

| -  | Configuration  | UI |
|---|---|---|
|**Default behavior**| hidden-disabled | Screenshot 2024-03-09 at 15 42 47 |
| **Changed behavior** | hidden-enabled | hidden |

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Same as the other, rely on raycast-env.d.ts instead 🙂

**Comment by bxb100** [comment]
@irangarcia I don't think it's a good idea because there are already a lot of configurations.

**Comment by irangarcia** [comment]
> @irangarcia I don't think it's a good idea because there are already a lot of configurations.

Could you ellaborate on that? Why would be a problem?

**Comment by bxb100** [comment]
IMHO it introduces a new configuration and does nothing

**Comment by pernielsentikaer** [comment]
I might agree, since it's only hiding the field in a view where you won't spend many seconds.

**Pull request closed without merging**
