### PR TITLE
Update GitHub Gist extension

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

Fix text errors

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by fe9lix** [comment]
Hey @koinzhang – could you please rebase on top of main?

**Comment by koinzhang** [comment]
> Hey @koinzhang – could you please rebase on top of main?

Hi @fe9lix
Is it ok now, I don't know if I did it right, please let me know if there are still problems

**Comment by fe9lix** [comment]
@koinzhang The deletion of CHANGELOG.md of the pipe-commands extension should be excluded from the PR.

**Comment by fe9lix** [comment]
@koinzhang Now the lowercase changelog.md is added to the PR 🙃 (this was actually deleted on main since we had both the lowercase and uppercase version). Might be easiest to backup your Gist extension updates and force reset the forked branch to match the current main, then reapply your changes.

**Comment by pomdtr** [comment]
Hey, why I am I mentionned by the @raycastbot ?

**Comment by fe9lix** [comment]
@pomdtr I guess because the changelog of the pipe-commands extension is part of the PR, see above...

**Comment by fe9lix** [comment]
Closing since #1333 has been opened instead

**Pull request closed without merging**
