### PR TITLE
add warp launch configuration extension

### PR DESCRIPTION
**Pull request by joetannenbaum**
## Description

This is a new Raycast extension that allows you to open a [Warp](https://www.warp.dev/) [Launch Configuration](https://docs.warp.dev/features/sessions/launch-configurations) directly from Raycast.

## Screencast

Here is a link to a screencast I made: [https://share.cleanshot.com/lfJfR2Rd](https://share.cleanshot.com/lfJfR2Rd)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by joetannenbaum** [comment]
I'm a little confused as to why the extension check is failing saying that I have an invalid "owner" key, I'm using the one specified in Raycast. Any insights? 

CleanShot 2023-03-08 at 10 19 50@2x

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* I have both `Warp` and `Warp Preview` installed but the extension crashes, could you handle this gracefully?

Raycast-eLCbIdjY@2x

I don't think I have any profiles in `Warp` 😊 I have the right permissions set 👍 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by joetannenbaum** [comment]
@pernielsentikaer thanks for reviewing! Sorry about that crash. I believe all errors should be handled gracefully now. Let me know how things look on your end!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Looks good to me, approved 🔥

**Pull request merged**
