### PR TITLE
Add titledoo extension

### PR DESCRIPTION
**Pull request by rafaelrinaldi**
## Description

Add "titledoo", an extension that does one thing: capitalize your title according to [The Chicago Manual of Style](https://www.chicagomanualofstyle.org/home.html).

Based on [title.sh](https://title.sh).

**Note**
Name originally was simply `title` but the publish script kept telling me there was already an extension with that name, even though I could not find one. Naming things is hard, so I just named it `titledoo` because it sounds funny.

## Screencast

https://github.com/raycast/extensions/assets/87162/464c699e-77c4-4dc3-a8bd-ca9c01ae6871

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hey @rafaelrinaldi ! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today.

We have an extension for changing case [here](https://www.raycast.com/es183923/change-case). Would it make sense to add the Chicago Style to it? Or does it  already cover the use case as well?

**Comment by rafaelrinaldi** [comment]
Hey @mil3na! Thanks for pointing out that extension, I didn't know about it. Even though it does something similar, it seems like it is slightly different as in theirs seems to be more focused on programming and mine on grammar.

**Comment by rafaelrinaldi** [comment]
@mil3na Thanks for chiming in. I originally had implemented it with `Form` but it felt like an overkill as it is intended to only be used for titles. The example you gave should be unrealistic as it looks more like body text than title.

I understand if you don't want to include this but The Chicago Manual of Style has very specific rules and is a bit more complex than simply using title case.

Let me know if you want me to close the PR.

**Comment by mil3na** [comment]
@rafaelrinaldi I understand your point, and I can see the use case for an extension focused on grammar rather than programming. What I'm suggesting here is to conform to good practices and usability rules.  You never know what your users are going to input. 

With that said, I don't want you to close your PR, but rather change it a bit to make it broader for extreme use cases. I hope you understand my point of view. Let me know if you wanna discuss it. I'm on the [Slack community](https://www.raycast.com/community).

**Comment by rafaelrinaldi** [comment]
@mil3na No problem at all! Whenever I have some free time I will switch it back to using `Form` and send it your way. Thanks for bearing with me!

**Comment by mil3na** [comment]
Thank you as well, just ping me if anything :)

**Pull request closed without merging**
