### PR TITLE
feat(gif-search): add infinite scroll

### LINKED ISSUE #9180: [Gif Search] Infinite Scroll
### Extension

https://raycast.com/josephschmitt/gif-search

### Description

Will fetch more results when scrolling to the bottom

### Who will benefit from this feature?

Everyone

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tmwrnr**
## Description

Currently, the user must press ⌘ + ⇧ + L to load more gifs. These updates will introduce infinite scroll to the search and trending sections.

If the user selects an item from the last row, additional gifs will be loaded.

Furthermore, the fetched gifs are checked against the already loaded items to avoid duplicate `Grid.Item` IDs. This check is necessary to prevent two `Grid.Item` components from having the same ID, which could cause the view to crash.

Fixes #9180

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution, @josephschmitt / @thomaslombart do you mind checking this?

**Review by thomaslombart — COMMENTED** [review]
Awesome change! It looks good to me. I would suggest removing the "load more" action with this update. What do you think?

**Comment by tmwrnr** [comment]
Thank you @thomaslombart!

I've considered it, and I agree with you that the action won't be used anymore after this change. I'll remove it after work.

**Review by thomaslombart — APPROVED** [review]
🎉

**Comment by alex-cory** [comment]
Thanks for adding this!

**Pull request merged**
