### PR TITLE
[New Extension] Apple Mail

### PR DESCRIPTION
**Pull request by yug2005**
## Description

Hey there, I have been working on an extension for Apple Mail. I have implemented a ton of features that I think will be useful for everyone: 

* Go through any mailbox for any account
* See important mail quickly
* See recent unread messages
* Read messages in Raycast or open them in mail app
* Reply, reply all, forward or redirect messages
* Compose a new message
* For new messages, you can specify the following fields: 
   * Choose the account from which to send the message
   * Choose the to, cc, and bcc recipients
   * Specify the subject and the content of the message
   * Select attachments for the message
* Quickly share selected items in the finder through a new message 
* Mark messages as read or unread
* Move messages to junk or trash
* Delete messages from the trash
* Tell mail to check for new mail for all accounts

## Screencast

Commands:

Raycast 2022-12-27 at 16 45 04

See all mail accounts:

mail 2022-12-27 at 16 46 37

See mail in all mailboxes:

mail 2022-12-27 at 16 48 58

Read messages in Raycast:

mail 2022-12-27 at 16 49 31

Compose a new message:

Raycast 2022-12-27 at 16 45 30

Add attachments:

mail 2022-12-27 at 16 46 26

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @yug2005 👋 

I gave it a quick spin and I can't get it to work, here are some of the errors:

Raycast 2023-01-09 at 05 36 06

mail 2023-01-09 at 05 35 54

mail 2023-01-09 at 05 35 37

It seems like nothing works. Do you have a clue? I'm on Ventura 13.2

```
05:36:36.788 Error: Command failed with exit code 1: osascript -e 
    set output to ""
    tell application "Mail"
      set mailAccounts to every account
      repeat with mailAcc in mailAccounts
        set accId to id of mailAcc
        set accName to name of mailAcc
        set accUser to user name of mailAcc
        set fullName to full name of mailAcc
        set accEmail to email addresses of mailAcc
        set numUnread to unread count of (first mailbox of mailAcc whose name is "All Mail")
        set output to output & accId & "," & accName & "," & accUser & "," & fullName & "," & accEmail & "," & numUnread & "
"
      end repeat
    end tell
    return output
  
371:383: execution error: Mail got an error: Can’t get mailbox 1 of account id "7BBE5125-7931-46E7-874A-D8E596D1D386" whose name = "All Mail". Invalid index. (-1719)
    at makeError (/Users/pernielsentikaer/.config/raycast/extensions/mail/see-recent-mail.js:1084:17)
    at handlePromise (/Users/pernielsentikaer/.config/raycast/extensions/mail/see-recent-mail.js:1847:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runAppleScript (/Users/pernielsentikaer/.config/raycast/extensions/mail/see-recent-mail.js:11555:22)
    at async getMailAccounts (/Users/pernielsentikaer/.config/raycast/extensions/mail/see-recent-mail.js:14678:25)
    at async /Users/pernielsentikaer/.config/raycast/extensions/mail/see-recent-mail.js:15073:25 {
  shortMessage: 'Command failed with exit code 1: osascript -e \n' +
    '    set output to ""\n' +
    '    tell application "Mail"\n' +
    '      set mailAccounts to every account\n' +
    '      repeat with mailAcc in mailAccounts\n' +
    '        set accId to id of mailAcc\n' +
    '        set accName to name of mailAcc\n' +
    '        set accUser to user name of mailAcc\n' +
    '        set fullName to full name of mailAcc\n' +
    '        set accEmail to email addresses of ma<…>
```

**Comment by yug2005** [comment]
I can't get reply to all to work with applescript. I did get reply to work but I don't know how to set the reply to all property of the command to true. Anyone know how to do this?

image

**Comment by zisra** [comment]
Will this be added anytime soon?

**Comment by ikupenov** [comment]
FYI, I've fixed all of the issues (at least the obvious ones) in this PR https://github.com/raycast/extensions/pull/6464. Due to AppleScript taking its time, it's fairly slow until the cache has been populated 😞.

**Comment by pernielsentikaer** [comment]
Closing since #6464 superseeds

**Pull request closed without merging**
