### PR TITLE
[Spotify Player] Add new actions in the album panel: `Add To Library` and `Remove From Library`

### PR DESCRIPTION
**Pull request by badta5te**
## Description

Hi, I use the Spotify extension extensively. When exploring new artists, I often come across albums that I would like to add to my library for later listening. Unfortunately, this option is not currently available in the extension.

## Screencast

CleanShot 2024-04-05 at 21 41 24

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaslombart — COMMENTED** [review]
Thanks for the PR! Could you make it possible to hide the actions if the album is already saved in the library or not?

**Comment by badta5te** [comment]
> Thanks for the PR! Could you make it possible to hide the actions if the album is already saved in the library or not?

@thomaslombart should work 🙌

**Comment by thomaslombart** [comment]
@badta5te I updated the codebase to use the same approach as with liked tracks. Let me know if that works for you 🙂

**Comment by badta5te** [comment]
> @badta5te I updated the codebase to use the same approach as with liked tracks. Let me know if that works for you 🙂

Cool, looks much better 😁 Thank you!

**Pull request merged**
