### PR TITLE
Add Visual Studio Code

### PR DESCRIPTION
**Pull request by tonka3000**
## Description

Add Visual Studio Code extension.

### Commands

Search and trigger commands directly from Raycast. This command requires that the `Raycast for VSCode` extension is installed in VSCode. If not the user will get an action to do so.
VSCode has some internal API limitations and therefore not all command aliases can be shown. If this is the case the command ID will be shown instead.

User can also store the VSCode command as quicklink (using URL schemas in the background) which makes it accessible from the root menu of raycast.

CleanShot 2022-12-30 at 12 56 01@2x

CleanShot 2022-12-30 at 12 56 57@2x

CleanShot 2022-12-30 at 12 57 45@2x

### Show Installed Extensions

Show locally installed extensions.

CleanShot 2022-12-30 at 13 00 02@2x

CleanShot 2022-12-30 at 13 00 42@2x

### Install Extensions

Install Extension in VSCode.

CleanShot 2022-12-30 at 13 01 29@2x

CleanShot 2022-12-30 at 13 01 44@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Will you support other branches? I only use insiders build and it's not working 😊

**Comment by tonka3000** [comment]
@pernielsentikaer I will add that for you.

**Comment by tonka3000** [comment]
@pernielsentikaer I add Insiders build support

**Comment by pernielsentikaer** [comment]
Hi 👋 

It works as expected, two things:

* Is there a way to get `Commands` running without your extension behind it?
* Maybe we should find another icon since it covers more versions (Since it could also cover VSCodium)

WDYT?

**Comment by tonka3000** [comment]
@pernielsentikaer would make sense to call the merged extension just visual-studio-code

**Comment by pernielsentikaer** [comment]
Yes, we would rename [Visual Studio Code Recent Projects](https://www.raycast.com/thomas/visual-studio-code) to Visual Studio Code and merge if things fit in, so we don't end up with too many extensions for the same application.

I already spoke with @thomaspaulmann about it, and it makes sense to do it.

Could you change this PR into a modification or make a new PR if it's easier 😊

**Comment by thomaspaulmann** [comment]
FYI I did a [bigger refactoring of the recent projects extension](https://github.com/raycast/extensions/pull/4479). Please make sure to build on top of it.

**Comment by 7assq** [comment]
Hassan

**Comment by 7assq** [comment]
شكرا

**Comment by pernielsentikaer** [comment]
Are you still up for this @tonka3000 - in this PR or another 😊

**Comment by tonka3000** [comment]
@pernielsentikaer I will do it in another PR.  Right now very busy, will take some time.

**Comment by pernielsentikaer** [comment]
Closing this due to a new PR will be opened, let me know if you want this open @tonka3000 and I'll reopen it

**Comment by eduwass** [comment]
Great work @tonka3000 👏  will keep my eyes peeled for this one!

**Comment by thomaspaulmann** [comment]
Definitely looking forward to that one as well. @tonka3000 let us know how we can be helpful.

**Comment by tonka3000** [comment]
@thomaspaulmann @eduwass #6329 PR is now pushed

**Pull request closed without merging**
