### PR TITLE
Update doccheck extension

### PR DESCRIPTION
**Pull request by justspacedog**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

We have just fixed a bug that caused the `puslish` command to publish all files as new in some edge cases, the fix should be included in the next release which is `1.50.0`.

Until the fix is out, do you have the possibility to only add the changed files (checkout from main) manually and update this PR or close this PR and only add the changed files manually

**Comment by pernielsentikaer** [comment]
Could you please only push the new additions 😊

**Comment by pernielsentikaer** [comment]
How many files did you actually change, do you know that? You could make a manually PR instead

**Comment by justspacedog** [comment]
> How many files did you actually change, do you know that? You could make a manually PR instead

GitHub indicated that three files have conflicts that need to be resolved, so I presume those are the changes. How can I do this manually or can I just publish it again since 1.5 is out?

**Comment by pernielsentikaer** [comment]
You should be able to just close this PR and make a new PR with the publish command, or manually uploaded the few files to a PR

**Comment by justspacedog** [comment]
> You should be able to just close this PR and make a new PR with the publish command, or manually uploaded the few files to a PR

Okay, new pull request is https://github.com/raycast/extensions/pull/6270 - hope this helps. :)

**Pull request closed without merging**
