### PR TITLE
Update: Home Assistant `⌘` + `=` instead of `⌘` + `+`

### PR DESCRIPTION
**Pull request by samuelthng**
## Description

Fixes unusable shortcut with lights and fans by replacing:
<kbd>⌘</kbd> + <kbd>+</kbd> with <kbd>⌘</kbd> + <kbd>=</kbd>.

## Screencast

Not a new extension, just updating shortcut keys on an action.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by tonka3000** [comment]
@samuelthng Why should `CMD` + `+` not work? I checked it and they work normally.

**Comment by samuelthng** [comment]
Thanks for the reply!

Doesn't seem to work for me on a MacBook en-US keyboard where there is no dedicated <kbd>+</kbd> key.

You'd have to hit <kbd>shift</kbd> to get the + keystroke, and in that case you'd be adding another modifier, which also doesn't trigger the action.

Can you verify if this is the case for you as well @tonka3000?

**Comment by tonka3000** [comment]
Can not(!) confirm that. In my case (de-at) layout `+` is a "direct" key and `=` would require shift.

The main problem here that I would be good to have support for alternative shortcuts in raycast, because not every layout is the same.

**Comment by samuelthng** [comment]
Agree with your opinion. Either that or allow customised shortcut overrides for actions.

In the mean time, since there might not be much demand for this, I'll close the PR and just make the change locally.

Thank you for taking a look at the PR anyway @tonka3000, appreciate it.

**Pull request closed without merging**
