### PR TITLE
Add visual-studio-code-manager extension

### PR DESCRIPTION
**Pull request by Ninnka**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥 

What's the purpose of this? Seems like we have [Projects](https://www.raycast.com/ajaypremshankar/projects) in the store which might be something similar?

**Comment by Ninnka** [comment]
> Hi 👋
> 
> Thanks for your contribution 🔥
> 
> What's the purpose of this? Seems like we have [Projects](https://www.raycast.com/ajaypremshankar/projects) in the store which might be something similar?

Hi 👋, The purpose of this extension is to better manage the windows of VS Code. It allows for real-time and quick searching of projects within some specified directories, as well as opening a new window quickly. Additionally, it enables opening a corresponding terminal for a specified directory.
As far as i know, some similar extensions not allow real-time search, so i implement it in a totally different way.

**Comment by Ninnka** [comment]
> I can see that one of your two commands already exists in the current I can see that one of your two commands already exists in the current Visual Studio Code extension, which also has Recents.
> 
> I can't see the use case where this would be smarter. How are you using it?

I have combined the "recent" project with "all" projects together, which makes it more convenient to select. More important 
point is that this extension does not rely on the built-in plugins of VS Code and provides real-time project search. These were the issues I encountered while using the other one plugin. However, modifying the other extension would almost re-implementing the entire code, so I decided to create a new extension to implement my idea.

**Comment by Ninnka** [comment]
@pernielsentikaer
case 1: search project, including recent project
visual-studio-code-manager 2024-02-05 at 10 16 59

case 2: open new vscode window
image

**Comment by pernielsentikaer** [comment]
As a end user I would be pretty confused about what's the difference is between yours and [this one](https://www.raycast.com/thomas/visual-studio-code) since both have:

* Open New Window
* Search Recent Projects

What's not in the other one (listing directories in a folder) is possible with other extensions. I don't see how an end user would benefit from having to choose. You could always open a feature request to get it added in the other extension if the author thinks it's a good idea.

**Comment by Ninnka** [comment]
> As a end user I would be pretty confused about what's the difference is between yours and [this one](https://www.raycast.com/thomas/visual-studio-code) since both have:
> 
> * Open New Window
> * Search Recent Projects
> 
> What's not in the other one (listing directories in a folder) is possible with other extensions. I don't see how an end user would benefit from having to choose. You could always open a feature request to get it added in the other extension if the author thinks it's a good idea.

I forget introduce some additional features and capabilities, this extension also supports quickly opening specified directories in iTerm, it is useful for user who usually open vscode and terminal.
visual-studio-code-manager 2024-02-05 at 17 36 53

**Comment by pernielsentikaer** [comment]
That's also a feature in the current extension

Raycast05022024-oI7INjHK png@2x

**Pull request closed without merging**
