### PR TITLE
Added a lot of new features and fixed bugs for CanvasCast!

### PR DESCRIPTION
**Pull request by yug2005**
## Description

Added a lot of new features for canvascast : 
* All modules were not showing previously due to limit of get request. Fixed this by getting the module items within the same request for the module. 
* All of the assignments were also not displaying. Fixed this by fetching the assignments individually for the courses rather than the todo. 
* Added back the open in browser action for the module page. 
* The default action for the announcements shows the announcement message. The option to open in browser is still there. 
* The default action for the assignments shows the assignment description. The option to open in browser is still there. 
* You can now download files right away. This is right now being done using the `open` module. This opens the download link in a new tab (in the background). However you still need to close this tab. 
* You can see the date that the announcement was posted and the due dates for the assignments. 
* Added list empty views for indicating if the user has an incorrect api key or domain.

## Screencast

You can see the dates for announcements and assignments : 

Metadata

Assignment description page : 

Metadata-2

Read the announcement : 

Metadata-3

Invalid API key : 

Metadata-4

Invalid Domain : 

Metadata-5

See assignments and announcements for individual courses : 

Metadata-6

Download files : 

Metadata-7

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by YodaLightsabr** [comment]
This looks great! Give me a bit to take a look at the code.

**Comment by yug2005** [comment]
@garyhtou Have a look too!

**Comment by pernielsentikaer** [comment]
Hi @YodaLightsabr 

Did you have time to have a look yet?

**Comment by YodaLightsabr** [comment]
Yep, this looks great!

**Comment by YodaLightsabr** [comment]
I have a few features to add as well but I'll do it after this PR merges.

**Comment by pernielsentikaer** [comment]
@YodaLightsabr can you give it a new spin? I was about to merge when new pushed arrived 😄

**Review by garyhtou — COMMENTED** [review]
Amazing! Thank you so much for working on this

**Review by YodaLightsabr — APPROVED** [review]
Looks good!

**Review by pernielsentikaer — APPROVED** [review]
Let's get it merged 🔥

**Pull request merged**
