### PR TITLE
New Put.io extension

### PR DESCRIPTION
**Pull request by EpaL**
## Description

This Raycast extension allows you to interact with your Put.io account, browse files and transfers, and perform customizable actions on your files, such as downloading them to your computer. Put.io is a cloud storage and download manager that enables you to fetch content from various sources and store it in your private and secure cloud space.

## Screencast

https://share.cleanshot.com/MMXc9V6j

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by EpaL** [comment]
Hi, is anyone available to review the most recent changes?

**Comment by pernielsentikaer** [comment]
I'm still not sure about the wget / aria2c commands, is there no way to have them fixed? Potentially it could be dangerous since you can run all such of user commands

**Comment by pernielsentikaer** [comment]
Are you ready for another review @EpaL

**Comment by sxn** [comment]
I guess we can close this PR since https://github.com/raycast/extensions/pull/6936 was merged?

**Comment by pernielsentikaer** [comment]
Yes! 🙂

**Pull request closed without merging**
