### PR TITLE
Add swift-command extension

### PR DESCRIPTION
**Pull request by aaronlinv**
## Description

Efficiently manage and access Linux command snippets for faster execution:
- Easily add and locate commands
- Supports custom placeholders within commands
- Chinese Pinyin fuzzy search functionality
- Sync commands across devices by hosting the data file with WebDAV tools

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution 🔥

@koinzhang have you seen a similar extension in the store, I think I have but I can't find it (I saw one from you about history which is not the same)

**Comment by aaronlinv** [comment]
Hello @pernielsentikaer, did you mean this [Shell History](https://www.raycast.com/koinzhang/shell-history) extension? I’ve tried it, and it’s very useful. However, they serve different purposes. The **Shell History** extension is designed for quickly searching local command history from zsh or bash, while **Swift Command** focuses on managing personal command snippets.

**Swift Command** is ideal for those who need to type long commands or work across multiple machines or environments. Since different environments can’t share their command history, an extension like this is the best choice.

Before I built this extension, I tried many others related to commands, Linux, or snippets available in the store. I never found one that allowed me to create and use commands quickly; they were designed for code snippets rather than commands, which don’t require a lot of input. Less is more. That’s why I decided to create this extension. It has significantly improved my work efficiency, and I hope it can help others who need to operate multiple machines.

**Comment by pernielsentikaer** [comment]
Makes sense, a few things to look into:

- It looks like you have [Empty State Flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) - could you add `isLoading={}` to your `<List />`

- Add `style={Action.Style.Destructive}` to delete command

**Comment by pernielsentikaer** [comment]
One thing that could be nice would be to use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) for the form, this gives you validation, states and error handling 🙂

**Comment by aaronlinv** [comment]
Thanks! I’ve fixed the two issues you mentioned. Could you please review it?

**Comment by aaronlinv** [comment]
Yes, I initially used `useForm` because it’s simpler. However, I needed to add or remove `TextField` parameters dynamically when the command input changes. `useForm` caused some issues with that, so I switched to using `Without Utils Validation`.

**Comment by pernielsentikaer** [comment]
Makes sense 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
