### PR TITLE
Add note-in-google-doc extension

### PR DESCRIPTION
**Pull request by mnttnm**
## Description

This Raycast extension seamlessly integrates with Google Docs, allowing users to manage and send notes right from their Raycast interface effortlessly. This makes it super easy to store quick notes on the cloud, making it convenient to have persistent notes. This is like toggle focus notes but integrated with Google Docs.

## Screencast

https://github.com/raycast/extensions/assets/8184277/15b68a22-98df-4c6a-ae5f-641ae46e30b1
https://github.com/raycast/extensions/assets/8184277/73b4fb8b-3ff7-466f-b223-6387bfe94f8e

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- When adding a note it would be nice to have a loading toast (Before showing the success toast) so I know that something is happening 🙂 (Same for creating a new document)

- Maybe `popToRoot()` after adding the note?

- Ensure that form fields are `Title Cased`

- Ensure that all actions have icons 🙂 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by mnttnm** [comment]
> 1

Done with the changes.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by mnttnm** [comment]
> Hi 👋
> 
> Looks good to me, approved 🔥

Thank you 🙏

**Pull request merged**
