### PR TITLE
Add Mastodon extension

### PR DESCRIPTION
**Pull request by sevi418**
## Description

**Raycast Extension for [Mastodon](https://joinmastodon.org/)**

commands

**Features**:
- Write status with markdown support.(Only if the instant supports Markdown)
- Publish simple status with text.
- Publish scheduled status with natural date format.
- Publish status with attachments (image, video, files); add alt text to the image when only one image is attached.
- Save draft status.
- View your bookmarked statuses.
- View your latest statuses.
- Open the latest published status that was published from Raycast through the actions.

### Login

Input your Mastodon instance's URL, then click the "Continue" button in the bottom-right corner.

### Mark status as sensitive 
Toggle the "Sensitive" checkbox to mark the attached image as sensitive, or add a content warning to the status.

### Write status with markdown
Toggle the "Markdown" checkbox to render markdown in the text file. Markdown shortcuts are also supported (e.g., pressing `⌘` + `B` will add `**bold**` around the selected text, `⌘` + `I` will make the selected text italic, etc.).

## Available Settings

If the instance supports Markdown, please select the `Built-in Markdown Support` checkbox. 

### Status limit
Based on performance considerations, the number of statuses displayed is limited, with the default being 20. You can adjust this limit in the extension settings.

## Actions 

search limit 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
@BasixKOR has been working on #5001 for some time and it seems like it’s almost ready.

Now we also have #6117 and #6156 in the queue, we need to decide what to do with all three, are you up for selecting the best version and going with that and improving with the feature respectably from the other PRs?

**Comment by BasixKOR** [comment]
Assistance would be very appreciated (as you may have noticed). It seems like your extension has markdown features for Glitch or other forks and attachments. Those features are currently missing in my PR, but I'd happily implement them for my extension.

Would you mind if I took some of your code to implement those?

**Comment by Sevichecc** [comment]
> Assistance would be very appreciated (as you may have noticed). It seems like your extension has markdown features for Glitch or other forks and attachments. Those features are currently missing in my PR, but I'd happily implement them for my extension.
> 
> Would you mind if I took some of your code to implement those?

Never mind. Feel free to do whatever you like with this codebase.

**Comment by pernielsentikaer** [comment]
Are we going with this or yours @BasixKOR as base?

**Pull request closed without merging**
