### PR TITLE
Update port-manager extension

### PR DESCRIPTION
**Pull request by Sheraff**
## Description

Add `known-ports` command to input "nicknames" for known ports. This is particularly useful when working on the same setup for a long time (for example: dev at a single-product company).

## Screencast

Known ports will display their "nickname" in the list of ports. They are also sorted to the top.
port-manager 2023-11-21 at 12 18 33

In the detailed view, the "nickname" is displayed as a tag on the top right, so as to preserve the layout between known and non-known ports
port-manager 2023-11-21 at 12 19 03

Known ports are also displayed by name in the menu bar version, sorted to the top.
Screenshot 2023-11-21 at 12 16 37

The `known-ports` command is a `Form` whose data is stored in `LocalStorage`. A "known port" is represented by a pair of inputs: name and port. Leaving a pair empty will remove it on submission. If all pairs are filled, a new empty one is added at the bottom, allowing the user to add as many as they need.
port-manager 2023-11-21 at 12 19 48

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- ~~[ ] I checked that files in the `assets` folder are used by the extension itself~~ [unchanged]
- ~~[ ] I checked that assets used by the `README` are placed outside of the `metadata` folder~~ [unchanged]

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you have time to check this @lucaschultz

**Comment by Sheraff** [comment]
Just commenting to keep this alive

**Comment by Sheraff** [comment]
Not stale

**Comment by pernielsentikaer** [comment]
Hi 👋

I just checked this again and have some minor feedback:

* Could you add a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry?
* Maybe add the name of known ports to keywords={} array so I can search for it?

**Comment by lucaschultz** [comment]
Hi there,

Sorry for the late reply.

I really like the idea, but I think we might want to improve some of the details. I went ahead and implemented most of the changes I would suggest:

1. Instead of a dynamic `Form`, I suggest we use a `List` to show the named ports, as I think this might be more in line with how the `Form`/`List` components are meant to be used:

port-manager 2024-01-02 at 19 08 09
port-manager 2024-01-02 at 19 05 05
port-manager 2024-01-02 at 19 19 27

2. I worked on an update of the extension in the last few months, which is using tags to show the open ports in the list item accessories. I would suggest we add the port name to the port tag. That way, we also avoid collisions in case a process is using multiple named ports:

port-manager 2024-01-02 at 19 17 20
port-manager 2024-01-02 at 19 17 30
port-manager 2024-01-02 at 19 18 38

3. I also reworked the menubar command and implemented the named port feature:

Bildschirmfoto 2024-01-02 um 19 22 59

I would suggest @pernielsentikaer, to cancel this PR as I already included the suggested changes in [this PR](https://github.com/raycast/extensions/pull/9966). I also went ahead and added you as a contributor, @Sheraff. I hope that is alright 🙂

**Comment by pernielsentikaer** [comment]
Closed as requested

**Pull request closed without merging**
