### PR TITLE
Add battery-menubar extension

### PR DESCRIPTION
**Pull request by panrafal**
## Description

This extension adds a battery percentage icon to the menu bar that will change it's color when estimated time left on battery drops below a configurable amount, or when a lot of power is being used.

I find it very valuable, as even on the M chipsets, high brightness and a bunch of Chromium and Electron apps can kill the battery in no time. This adds a visual cue that you might need to reduce the draw to survive the day.

## Screencast

It's just an icon in the menu bar with a short info menu when clicked. Battery stats are updated every 30 seconds.

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by panrafal** [comment]
How can I make a readable, nice-looking screenshot of a Menu Bar icon that is as big as required? That would be mostly my wallpaper - should I do it so?

**Comment by pernielsentikaer** [comment]
I can try to help you with that later today, you'll need 2000 x 1250 pixels image showing the menubar - let me know if you want my help doing do 🙂

**Comment by panrafal** [comment]
@pernielsentikaer I've updated the shots - should be fine now

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋 

Thanks for the new images 🔥 I just checked the store and can see that we have a [similar](https://www.raycast.com/o1y/battery-health) extension, do you think it makes sense to contribute to that extension instead?

**Comment by panrafal** [comment]
I believe it focuses on a different thing - it's about the batter health, mine is about the power draw, so amps being drawn and CPU usage. It could (should?) be extended into this direction

**Comment by panrafal** [comment]
@pernielsentikaer just bumping this. I really believe the functionality and purpose of these two extensions is different

**Comment by panrafal** [comment]
@pernielsentikaer any chance of looking at this?

**Comment by pernielsentikaer** [comment]
Yes, I'll look now, actually though it was resolved

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
