### PR TITLE
[AWS] Support master credentials use case

### PR DESCRIPTION
**Pull request by JonathanWbn**
## Description

There are different ways to use `aws-vault`. The current solution supports [use case 1](https://github.com/99designs/aws-vault/blob/master/USAGE.md#use-case-1-aws-vault-is-the-executor-and-provides-the-environment). This PR adds support for [use case 2](https://github.com/99designs/aws-vault/blob/master/USAGE.md#use-case-2-aws-vault-is-a-master-credentials-vault-for-aws-sdk).

This had been pointed out by @themanontv in https://github.com/raycast/extensions/issues/3022?notification_referrer_id=NT_kwDOATEjULM0NDc1ODM2NDU0OjE5OTk3NTIw#issuecomment-1531118745

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by ciryon** [comment]
@JonathanWbn I'm not sure it's related to this PR but since very recently the AWS extension won't load any data at all for me anymore. Trying to load lambdas or pipelines and nothing is found. I see no error logged from Raycast. (I can create a real bug report if you'd like too ofc)

**Comment by JonathanWbn** [comment]
@ciryon Yes, I have heard similar reports since this got released. I will check this today.

**Comment by JonathanWbn** [comment]
@ciryon It's being fixed in https://github.com/raycast/extensions/pull/6358

**Pull request merged**
