### PR TITLE
[World Cup] Show live time for current match

### PR DESCRIPTION
**Pull request by ismamz**
## Description

Fetch current match live time (refresh every minute).

## Screencast

Metadata

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @ismamz 👋 

Now that we fetch the time, can we also fetch the score?

**Comment by ismamz** [comment]
> Hi @ismamz 👋
> 
> Now that we fetch the time, can we also fetch the score?

Do you mean update the score every minute? Yes, we can.

We can add also the who did the goals and the exact minute, maybe for details section.

Don't you think it would be better to leave the details closed by default?

**Comment by pernielsentikaer** [comment]
> Do you mean to update the score every minute? Yes, we can.

That would make sense, right? Would be weird only to update the time 😊

> We can also add who did the goals and the exact minute, maybe for the details section.

That's also a cool idea, a lot of ideas left like players, etc, we might need to push to a new view with all that data.

> Don't you think it would be better to leave the details closed by default?

Fine with me 😊

**Comment by ismamz** [comment]
@pernielsentikaer i've pushed some changes:

- Show live time and **score** for current match
- Reversed the list for previous matches
- Fixed time for matches about to start
- Added goals information
- Added animated GIF for empty view

Metadata-3

Metadata-4

https://user-images.githubusercontent.com/3452011/203845301-655fdbf6-f925-4211-9f22-7dcf6f30ac9b.mov

**Comment by peduarte** [comment]
🔥

**Review by peduarte — APPROVED** [review]
Let's gooo ⚽ ⚽ ⚽ ⚽

**Pull request merged**
