### PR TITLE
[Cal.com] Visual refresh for "View Bookings" and "Share Meeting Links" commands

### PR DESCRIPTION
**Pull request by jfkisafk**
## Description

- Visual refresh for "View Bookings" and "Share Meeting Links" commands
- Using optimistic updates during mutation and updated dependencies

## Screencast

Diff contains the new screenshots

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

* closes https://github.com/raycast/extensions/issues/12597 (should have already been closed as these features are already implemented)

### CODE REVIEW

**Comment by mil3na** [comment]
Hi!
Thank you for your contribution! My name is Milena and I will be reviewing it today.

@eluce2 do you want to take a look before we merge this PR?

**Comment by eluce2** [comment]
looks good to me 👍🏻

**Review by mil3na — APPROVED** [review]
Awesome! :)

**Comment by AlexIsMaking** [comment]
@jfkisafk hey, could you please share the source of the image that you're using as your wallpaper for app screenshots? I've just finished an update and I'd rather not recreate all of the screenshots, as only one has changed 🙌

**Comment by jfkisafk** [comment]
Hey @AlexIsMaking , here it is: https://wallhaven.cc/w/l8oxxr

**Comment by AlexIsMaking** [comment]
@jfkisafk great, thanks!

**Pull request merged**
