### PR TITLE
Add baidu-screenshot-ocr extension

### PR DESCRIPTION
**Pull request by zhsama**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi! Is this ready for review?

**Comment by zhsama** [comment]
> Hi! Is this ready for review?

yep

**Comment by zhsama** [comment]
> Hi! Thank you for your contribution! My name is Milena and I will be reviewing it today.
> 
> What would be the difference between your extension and this one? https://www.raycast.com/Humber/baidu-ocr/commands Also, your README is not in Englsih, could you please translate that?

That plugin can only read the first item in the clipboard for OCR recognition. If the first item is not a picture, an error will be reported. 

This project uses switf to call the system screenshot function, and automatically performs OCR recognition after the screenshot, which is easy to use.

i will translate readme later

**Comment by mil3na** [comment]
Hey! Is this ready for another review or do you need more time?

**Pull request closed without merging**
