### PR TITLE
Update myip extension

### PR DESCRIPTION
**Pull request by j3lte**
## Description

- Remove `axios`, rewritten fetch using `node-fetch` & `@raycast/utils`
- Bugfix where ip lookup was not working properly (#11290)
- Updated dependencies

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the rewrite, for me it works as expected 🔥 

@kkange can you check this?

**Comment by kkange** [comment]
The code has been nicely enhanced. That's excellent.

I do have a question though. I understand that https://api64.ipify.org/ is considered a Universal API that supports both IPv4 and IPv6 simultaneously. Is there a reason why it was divided into two separate APIs?

It's possible that it's just a temporary issue, but in my environment, I'm unable to connect to https://api.ipify.org/ and receive error messages.

**Comment by pernielsentikaer** [comment]
@j3lte could you check the review from @kkange

**Comment by j3lte** [comment]
@kkange I checked apify docs, you're right. API64 is the universal one. I'll remove the dedicated ipv4 and update the PR

**Comment by pernielsentikaer** [comment]
Could you check it again @kkange 🙂

**Comment by kkange** [comment]
It works perfectly. Thank you 😀

**Review by pernielsentikaer — APPROVED** [review]
Thanks for an awesome update @j3lte

**Pull request merged**
