### PR TITLE
Add material-icons-search extension

### PR DESCRIPTION
**Pull request by 201549BL**
## Description

Extension for viewing, searching and copying [Material Icons](https://fonts.google.com/icons)

## Screencast

material-icons-search-1
material-icons-search-2
material-icons-search-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @201549BL 👋 

Thanks for your contribution 🔥 

How is this compared to [this extension](https://www.raycast.com/creasty/material-icons)

**Comment by 201549BL** [comment]
@pernielsentikaer 

My extension is forked from [the extension you mention](https://www.raycast.com/creasty/material-icons). Biggest differences is that it uses the grid view and some of the newer hooks from raycast. 

I prefer the grid view and didn't know how to keep the list view and the grid. Therefore I submitted the extension as it's own thing.

**Comment by 201549BL** [comment]
@pernielsentikaer 

I added the Grid view as a second Command to @creasty's extension. I'll send a new PR to merge my changes into his extension.

**Comment by creasty** [comment]
Great!

> I prefer the grid view and didn't know how to keep the list view and the grid

We just didn't have the grid view 2 years ago, so I personally don't mind discarding the list view altogether.

**Comment by creasty** [comment]
Beware of the potential conflict with https://github.com/raycast/extensions/pull/8761

**Comment by 201549BL** [comment]
@creasty new PR added #8793

**Comment by pernielsentikaer** [comment]
So we can close this PR in favor of #8793 ?

**Comment by 201549BL** [comment]
> So we can close this PR in favor of #8793 ?

@pernielsentikaer  Yep 👍🏻

**Pull request closed without merging**
