### PR TITLE
fix(airpods-noise-control): main function fixed and 'off' mode added

### LINKED ISSUE #8591: [AirPods Noise Control] ...
### Extension

https://www.raycast.com/chrahe/airpods-noise-control

### Description

Hey there! Thank you for granting me the extension. I wanted to let you know that with the latest iOS and MacOS releases, a new noise control mode was added. Could you please set this up? As of now, it is only possible to switch between two of them.
CleanShot 27 09 2023 at 12 43 28@2x

### Who will benefit from this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by iamyeizi**
## Description

- #9467
- Main function fixed
#8591
#8581
_I can't test the "Adaptive" mode with another mode because I don't have the Airpods with that mode, but I trust my little applied logic haha_.
_If you can try it, I would appreciate it._
- I checked to see if it worked correctly in French
#9854
CleanShot 2024-01-03 at 2  23 46

## Screencast

CleanShot 2024-01-03 at 1  28 24

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @iamyeizi 👋 

Thanks for taking your time to enhance this extension 🔥 

@chrahe do you want to check this?

**Comment by pernielsentikaer** [comment]
Pinging a last time, are you interested in checking this @chrahe 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by iamyeizi** [comment]
@pernielsentikaer can you test toggle to Adaptive and if Conversation Awareness works? I can't test it 'cause don't have the AirPods Pro 2 😅

**Comment by pernielsentikaer** [comment]
I don't have them either (forgot them at my parents) 😆

**Comment by iamyeizi** [comment]
No problem jaja, I'll wait for them to create an issue if it doesn't work 😁

**Comment by wbeeftink** [comment]
@iamyeizi Just wanted to say thank you for these changes. I can't test adaptive mode either, but the switch between transparency and noice cancellation works perfectly for me. Cheers!

**Comment by iamyeizi** [comment]
Glad to hear that!  Cheers! @wbeeftink

**Pull request merged**
