### PR TITLE
Add RelaGit extension

### PR DESCRIPTION
**Pull request by TheCommieAxolotl**
## Description

Add [RelaGit](https://rela.dev) extension which allows users to search and perform basic git operations on their repositories, as well as manage and view their workflows.

## Screencast

https://github.com/raycast/extensions/assets/87679354/0097797a-5d16-46bb-b7b8-72d92c42f6e1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

It looks like your commands suffers from [Empty State Flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states) - maybe add a real isLoading state instead 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by TheCommieAxolotl** [comment]
Hey there, just wondering about the merge delay? Don't want to rush anything, just curious.

**Comment by pernielsentikaer** [comment]
Can you enable so our bot can modify images? Looks like you moved a checkmark when creating the PR 🙂

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by TheCommieAxolotl** [comment]
Hmm, looks like because the fork is owned by the @relagit org and not me that checkbox doesn't exist:
Screenshot 2024-05-10 at 8 25 16 pm

**Comment by pernielsentikaer** [comment]
Do you mind running all metadata images through some compression, if you can do that we can skip the bot check 🙂

**Comment by TheCommieAxolotl** [comment]
Done, ~80% removed

**Comment by pernielsentikaer** [comment]
Thanks 🤗

**Pull request merged**
