### PR TITLE
Chrome open url

### PR DESCRIPTION
**Pull request by HenriChabrand**
## Description

Add a URL parser to be able to open URL in a new tab.

## Type of change

- Bug fix / improvement for somebody else's extension. Extension author: @pernielsentikaer 

## Screencast

Screenshot 2021-11-08 at 15 44 51

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @HenriChabrand 

Thanks for the update, it's going to be a nice addition 💪 

Something is not quite right yet, if searching and deleting afterward, it's not getting cleared correctly, see this example

https://user-images.githubusercontent.com/38033107/140979933-7883538c-4857-4571-9f38-1b2a9d4dd190.mp4

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by pernielsentikaer** [comment]
Hi @HenriChabrand 👋 

Do you need any help? 💪

**Comment by HenriChabrand** [comment]
Hello @pernielsentikaer 👋
Sorry for the delay – it should work now 🙌

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @HenriChabrand 👋 

I'm not sure what's causing it yet, but when I use  “New Tab” and “Search Tab” I get this error, it's nothing that I have encountered before.

sGnZANcgz3FvreCQ


```
Error: Command failed with exit code 1: osascript -e
      set _output to ""
      tell application "Google Chrome"
        set _window_index to 1
        repeat with w in windows
          set _tab_index to 1
          repeat with t in tabs of w
            set _title to get title of t
            set _url to get URL of t
            set _favicon to execute of tab _tab_index of window _window_index javascript ¬
                    "document.head.querySelector('link[rel~=icon]').href;"
            set _output to (_output & _title & "~~~" & _url & "~~~" & _favicon & "~~~" & _window_index & "~~~" & _tab_index & "\134n")
            set _tab_index to _tab_index + 1
          end repeat
          set _window_index to _window_index + 1
          if _window_index > count windows then exit repeat
        end repeat
      end tell
      return _output

103:764: execution error: Google Chrome got an error: Can’t get every window. (-1728)

		error = new Error(message);
		        ^

Error: Command failed with exit code 1: osascript -e
      set _output to ""
      tell application "Google Chrome"
        set _window_index to 1
        repeat with w in windows
          set _tab_index to 1
          repeat with t in tabs of w
            set _title to get title of t
            set _url to get URL of t
            set _favicon to execute of tab _tab_index of window _window_index javascript ¬
                    "document.head.querySelector('link[rel~=icon]').href;"
            set _output to (_output & _title & "~~~" & _url & "~~~" & _favicon & "~~~" & _window_index & "~~~" & _tab_index & "\134n")
            set _tab_index to _tab_index + 1
          end repeat
          set _window_index to _window_index + 1
          if _window_index > count windows then exit repeat
        end repeat
      end tell
      return _output

103:764: execution error: Google Chrome got an error: Can’t get every wind<…>
```

**Comment by fe9lix** [comment]
Closing this PR due to inactivity – feel free to reopen later.

**Pull request closed without merging**
