### PR TITLE
[Trello] Add creating Trello todo to extension

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
## Description

A new command allows you to create a to do with the Trello extension.

## Screencast

https://user-images.githubusercontent.com/42080/218082437-00887e2f-4138-413a-9580-d2037f0b8b78.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
After this is merged, will do a bit of a tidy and refactor PR

**Comment by ChrisChinchilla** [comment]
Thanks to help from @brittanyjoiner15

**Comment by ChrisChinchilla** [comment]
Bleh, where did all this git noise come from :(

**Comment by pernielsentikaer** [comment]
Can you look into the prettier errors @ChrisChinchilla

**Comment by ChrisChinchilla** [comment]
@pernielsentikaer prettier fixed, but now there's another error I don't understand or get locally.

**Comment by pernielsentikaer** [comment]
Hi @ChrisChinchilla 👋 

I tried to update the extension, do you mind testing that I didn't break anything :D

**Comment by ChrisChinchilla** [comment]
@pernielsentikaer Still works! 👏

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
