### PR TITLE
Add calist extension

### PR DESCRIPTION
**Pull request by astrit**
## Description

This extension consists of two commands, Calendar and Time. The Calendar command displays a calendar with the current date highlighted and very flexible navigation shortcuts. The Time command displays the current time and optional extra timezone. Both commands have a variety of settings that can be customised to your liking.

## Screencast

https://github.com/raycast/extensions/assets/2398447/6683e1cf-0e24-4b23-87b8-921ff8809d88

# Features 

## 🤯 Searching

In the search field you can type in `July 1992` and it will change the date to that.
If you type in the number of the month it will change the month to that.

## 🧭 Navigation

Nagivation is a breez since you can use shortcuts such as `shift + w` to toggle the week column, `shift + v` to change the density, and `shift + t` to toggle the time.

You can also use the shortcuts `shift + left` and `shift + right` to navigate to the previous and next month, respectively. Or use dropdowns to navigate to a specific month or year.

- **Go to current month** — `shift + c`
- **Go to current year** — `shift + y`
- **Go to previous month** — `shift + left`
- **Go to next month** — `shift + right`
- **Go to previous year** — `shift + up`
- **Go to next year** — `shift + down`

## ⌘ Commands

- **Calendar**
- **Time**

## 🗓️ Configuration for Calendar

- **Show Week Column**
  - Toggle using the shortcut `shift + w`
- **Show Weekday Names**
- **Show Event Count**
- **Show Month Name**
- **Enable Month Dropdown**
  - Enable or disable the month dropdown for cleaner UI

## 🌄 Density

- Normal (Value: normal)
- Comfortable (Value: comfortable)
- Compact (Value: compact)

  > Shortcut: `shift + v`

## ⏰ Time Settings

- **Enable or disable time**
  > Shortcut: `shift + t`
- **Seconds** — Enable or disable seconds in real time
- **Title** — Hide title for distraction free view, applies to the Time command as well
- **AM/PM** — Change time format to 12 hours

## 🌎 Timezone

- **Secondary Timezone**
  - Enable or disable the secondary timezone
  - **Offset** — Second timezone offset in hours

## 🔎 Search

- **Search Custom Placeholder**

## 📝 Navigation Title

- **Custom Window Title Text** — When in use will remove weather and date from the title
- **Show Date** — Hide the date from the Nav Title
- **Show Weather** — Shows real time weather in the bottom left corner and command subtitle
- **Show Week Number** - Show week number in the Nav Title

## 🎨 **Theme**

Customize the look and feel by using themes with colors built in Raycast, applies to current day, weekends and dropdown current month

- Themes:
  - Default
  - Blue
  - Green
  - Magenta
  - Orange
  - Purple
  - Red
  - Yellow

## 🚀 **Icon Type**

Choose between Avatar, Raycast Icons, Font icons
  - Avatar
  - Raycast Icons
  - Font ( Default ) 

## 📰 Icon Type Font Configuration

- **Font Weight**
  - Normal (default)
  - Bold
- **Font Family**
  - Sans Serif (default)
  - Serif
  - Monospace

## ☔ **Custom Colors**

Forgranular control over the colors you can have custom colors in hex format for the following:

- **Current Day Color**
- **Custom Color for Weekends**

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @astrit 👋

I just checked the extension out, and both commands are crashing for me. Do you have any idea why? I didn't change any settings at all.

calist 2024-04-12 at 10 11 20

calist 2024-04-12 at 10 11 14

**Comment by astrit** [comment]
> I just checked the extension out, and both commands are crashing for me. Do you have any idea why? I didn't change any settings at all.
>  

That is definitely odd, just tested out and working on my end, will do some test and see what is going on!

**Comment by astrit** [comment]
@pernielsentikaer pushed a fix, it was due to the default values which for me was working since I had already set, deleted the extension and re-import had same issue and fixed it by defining the default values which apparently I had forgotten 😂

Thanks for the feedback and let me know how it looks this time around 🤘

**Comment by pernielsentikaer** [comment]
It's not crashing the same place anymore, now it's a new place (Same issue in both commands) 🙂

calist 2024-04-12 at 11 53 55

**Comment by astrit** [comment]
@pernielsentikaer 

> It's not crashing the same place anymore, now it's a new place (Same issue in both commands) 🙂
> 

Is the build failing ? 
Could it be some cashed settings from previous version, if you don't mind to uninstall, clear local storage and re-build. 
In my end is working on this version.

**Comment by pernielsentikaer** [comment]
I always start with a clean build of the extension so there is nothing from previous 🙂

It looks like `console.log(timeStr);` gives me this output:

12:47:07.656 [ '0.47.07', 'pm' ]

**Comment by astrit** [comment]
@pernielsentikaer I added some checks! Hopefully good to go now ✌️

**Comment by astrit** [comment]
@pernielsentikaer did you have a chance to check the last update!

**Comment by pernielsentikaer** [comment]
Seems like it's still crashing, ping me on Slack if you want to go deeper with the debug

calist 2024-04-16 at 09 27 12

**Comment by pernielsentikaer** [comment]
I got some more feedback for you 🙂

- daynames doesn't fit If you switch between textsizes

https://github.com/raycast/extensions/assets/38033107/ae8443ec-7dcb-40b0-83d8-50c12c85e16f

- Current date is always highlighted (when going to other months)

calist 2024-04-17 at 09 39 20

- We should not use navigationTitle to set dynamic data, you can see a bit more about [it here](https://developers.raycast.com/basics/prepare-an-extension-for-store#navigation-title) - not sure where the best data is for that actually besides in the commands subtitle as you already have.

- The time command has the same actions as the calendar, it might be a leftover 🙂

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by astrit** [comment]
Thanks for the feedback. 

I did push changes accordingly! 

----

> * daynames doesn't fit If you switch between textsizes

- [x] Optimised this to check for the textsize and add spaces to accommodate 

----

> * Current date is always highlighted (when going to other months)

- [x] For this one I actually was inspired by the Input field type date which keeps highlighted current day on all months but removed it so is highlighted only on the current month - [Date Input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)

----

> * We should not use navigationTitle to set dynamic data, you can see a bit more about 

- [x] I understand that the specification indicates not to use if but If possible to still have it there would appreciate otherwise, I removed it since don't know any other place where I could have it! 

----

> * The time command has the same actions as the calendar, it might be a leftover 🙂

- [x] Remove the actions from this command! 

----


@pernielsentikaer I pushed the updates, let me know if you have more feedback ✌️

**Comment by pernielsentikaer** [comment]
Awesome update, I'll reply in Slack now 🙂

**Comment by pernielsentikaer** [comment]
Could we make the same naming here?

image

I think the right thing is to sentence case them 🙂

**Comment by astrit** [comment]
@pernielsentikaer updated the labels all are sentence case now ✌️

**Comment by pernielsentikaer** [comment]
I think we're about to be ready to merge, do you mind changing above commit to sentence case 😉

> Sentence case is a text formatting style where the first letter of the first word is capitalized, and the rest of the text is written in lowercase, except for proper nouns and other exceptions that typically require capitalization. This style is commonly used in English for writing titles, headings, and sentences in general.

**Comment by astrit** [comment]
Oh snap! My bad I did misunderstand it 

Updated to sentence case now!

CleanShot 2024-04-23 at 13 16 45@2x


CleanShot 2024-04-23 at 13 17 47@2x

**Comment by astrit** [comment]
@pernielsentikaer  Oh snap! My bad I did misunderstand it
 Updated to sentence case now! 

 CleanShot 2024-04-23 at 13 16 45@2x

CleanShot 2024-04-23 at 13 17 47@2x

**Comment by pernielsentikaer** [comment]
Sorry for the confusion. Some fields, like "title," need the Apple Style Guide, and checkbox values need sentence cases. I corrected 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
