### PR TITLE
Deleting my extension ig

### PR DESCRIPTION
**Pull request by johan-perso**
## Description

Deleting my extension from the Raycast Store 🥲 I stopped working on the project and eventually shut down the backend

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Sorry to hear that 🙁

Instead of deleting, could you do like it's done in  #11942

**Comment by johan-perso** [comment]
Sure.

**Comment by johan-perso** [comment]
It should be good

**Comment by pernielsentikaer** [comment]
Could you re-add `package-lock.json` 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

Sorry to ehar that you're letting go of it

**Pull request merged**
