### PR TITLE
Cypress docs

### PR DESCRIPTION
**Pull request by robertguss**
## Description

Added a new extension that allows people to search and open the official Cypress.io docs in their browser.

## Screencast

https://www.loom.com/share/a26b77085d0947b7900ca3fcb69e42f6

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — APPROVED** [review]
Hi @robertguss 👋 

Thanks for your contribution 💯

**Comment by robertguss** [comment]
@pernielsentikaer I have logos for both light and dark backgrounds, but not one that looks good on both unfortunately. I have to use the brand approved logos and can't tweak them myself.

It would be nice if we could provide logo-light.png and a logo-dark.png or something similar and raycast could dynamically display the correct logo when the user switches themes. Not a big deal or really that important feature, but a nice to have.

**Comment by pernielsentikaer** [comment]
> @pernielsentikaer I have logos for both light and dark backgrounds, but not one that looks good on both unfortunately. I have to use the brand approved logos and can't tweak them myself.
> 
> It would be nice if we could provide logo-light.png and a logo-dark.png or something similar and raycast could dynamically display the correct logo when the user switches themes. Not a big deal or really that important feature, but a nice to have. 

Hi 👋

We do have support for both appereance, check here: https://developers.raycast.com/information/manifest#extension-properties same goes for icons in list items: https://developers.raycast.com/api-reference/user-interface/icons-and-images#image.source 💪🤟🤙

**Comment by robertguss** [comment]
@pernielsentikaer amazing! I will submit a new PR soon then ;) 

Thank you.

**Pull request merged**
