### PR TITLE
Bitwarden new "Create Send" command

### PR DESCRIPTION
**Pull request by gio8tisu**
## Description

Added a new command to Bitwarden extension to create shareable secrets through Bitwarden's Send feature.
See issue #1942.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pomdtr** [comment]
Hey, congrats for the great work.

I found a bug in the current code: when the user is not log in, the form is displayed but cannot but submitted:

image

**Comment by pomdtr** [comment]
We might need to abstract the authentication logic in order to be able to share it between the send and list commands.

**Comment by andreaselia** [comment]
Great work on your first contribution @gio8tisu 🎉

**Comment by jomifepe** [comment]
Looks great, good job 🚀

**Comment by pernielsentikaer** [comment]
@pomdtr Is this ready for merge or are we still awaiting something?

**Comment by pernielsentikaer** [comment]
Just wanted to make sure that I was correct, thanks 😄

**Pull request closed without merging**
