### PR TITLE
Update torr-manager extension

### PR DESCRIPTION
**Pull request by danniuz**
## Description
Manager for torrents for [https://github.com/YouROK/TorrServer](https://github.com/YouROK/TorrServer)

you have to selfhost it, provide VPS url, login/pass to my extension and then you could do this:
## Screencast

https://github.com/user-attachments/assets/972ecad9-0198-4c24-8692-18211a1e9788

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by dannius** [comment]
Oh, my bad, let me provide you with test credentials to my VPS in case you would like to check it.
Fill free to do mess a bit with torrents, not a problem :D

Screenshot 2024-10-14 at 18 12 22

url:          http://45.131.60.99:7443
login:      raycast
pass:      raycast

* I checked it with video players IINA and VLC, so i hope you have one of this 2
** you also can use same url and credentials in your browser to check what happens in UI

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

Thanks for your contribution 💪

I have now tested your extension and have some feedback ready for you:

-  Some actions are missing icons; could you add those 🙂

torr-manager 2024-10-16 at 10 03 33

-  It keeps failing when I try to list torrents

torr-manager 2024-10-16 at 10 06 00

-  I'm also encountering an error when I try to add one. Do you have any idea why?

torr-manager 2024-10-16 at 10 04 30

-  We don't support illegal torrents, but you can use this to list legal things like Linux distros and other items (so metadata images should contain legal content)

I'm looking forward to testing this extension again 🔥

Request a new review when you are ready. Feel free to contact me here or on [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by dannius** [comment]
@pernielsentikaer  thanks for the review!

Ready for one more round)

Here is my changes:
1) first of all i realize that people paste links with '/' at the end, so i handle this case
2) remove build in "parser" url and make it as preference param (legal perspective)
3) adjust response errors to make it human readable, like "not found" and etc
4) added icons for menu items
5) Added 'Test connection command' to be sure if user connected (to be able CRUD torrents to server)
image

same credentials for you:

url: http://45.131.60.99:7443/
login: raycast
pass: raycast

for parser you can enter this url:
https://jacred.xyz

here is my setup 
image

you also can visit same url in browser and use same login and pass to check if it works for you.

PS. if search still looks illegal - we can remove this command at all, but now its just input to url, so looks legal from my perspective :D

**Comment by dannius** [comment]
[@pernielsentikaer](https://github.com/pernielsentikaer) thanks for the review!
Ready for one more round)

Here is my changes:
1. first of all i realize that people paste links with '/' at the end, so i handle this case
2. remove build in "parser" url and make it as preference param (legal perspective), also change parser to most popular https://github.com/Jackett/Jackett?tab=readme-ov-file
3. adjust response errors to make it human readable
4. added icons for menu items
5. Added 'Test connection command' to be sure if user connected (to be able CRUD torrents to server)

image


TESTING:
same credentials for you:
url: http://45.131.60.99:7443/
login: raycast
pass: raycast

New parser api:
parserUrl: http://45.131.60.99:6443/
parserApiKey: utk8jkibhw7lf68tco66szrisd04ix1m

(if u going to check parser please use something popular, i added only 1 tracker to my server).
Probably 'breaking bad' or 'how i met your mother' could be good choice for fast uploading

here is my setup:
image

**Comment by pernielsentikaer** [comment]
Is this ready for another go?

**Comment by dannius** [comment]
@pernielsentikaer  ready! added also some minor changes, looks good now

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Can we put readme-image-*.png in assets (and only one torrent (legal, right) and remove torr-manager-1.png and update the two other images 🙂

**Comment by dannius** [comment]
hi @pernielsentikaer i added required fixes and updated all screenshots

For screenshots i used legal torrent indexer 'linuxtracker.org'

also added categories feature, before now users could search only movies/tv/series, but now they could search also for some fresh linux images :)

image

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
