### PR TITLE
Add later extension

### PR DESCRIPTION
**Pull request by Ross249**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Ross249** [comment]
> I tried this, but when using `Later - Read It Later`, I ended up with this error (was using Arc at the time)
> 
> ```
> 09:59:59.189 Error: Command failed: osascript -e  
> 0:9: execution error: Variablen undefined er ikke defineret. (-2753)
> 
>     at ChildProcess.exithandler (node:child_process:422:12)
>     at ChildProcess.emit (node:events:514:28)
>     at ChildProcess.emit (node:domain:488:12)
>     at maybeClose (node:internal/child_process:1105:16)
>     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
>   code: 1,
>   killed: false,
>   signal: null,
>   cmd: 'osascript -e  ',
>   stdout: '',
>   stderr: '0:9: execution error: Variablen undefined er ikke defineret. (-2753)\n'
> }
> ```
> 
> Do you have any idea what might be causing this?

Thank you for your finding. There are some details I want you to provide:
1. Arc version code
2. Did your Arc open or not while using `Later - Read It Later` Command
3. Did this problem appear in other browsers like`Microsoft Edge, Chrome`?

**Comment by pernielsentikaer** [comment]
Yes, it also happens with Chrome (and Arc of course), both in the newest versions. I'm having the browser in front before running the command.

Nothing changed besides the error in the console

**Comment by pernielsentikaer** [comment]
I was able to do some more testing:

- The error is occurring because I use [Velja](https://sindresorhus.com/velja) as middleware for the browser. Maybe we should let the user set their preferred browser in preferences instead?

- use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) in the form for adding new entries since it comes with validation and haldling of states 🙂

- The delete action should maybe have `style={Action.Style.Destructive}` and a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert)?

**Comment by Ross249** [comment]
> I was able to do some more testing:
> 
> * The error is occurring because I use [Velja](https://sindresorhus.com/velja) as middleware for the browser. Maybe we should let the user set their preferred browser in preferences instead?
> * use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) in the form for adding new entries since it comes with validation and haldling of states 🙂
> * The delete action should maybe have `style={Action.Style.Destructive}` and a [confirmAlert](https://developers.raycast.com/api-reference/feedback/alert#confirmalert)?

I think if I got the user's default browser, saving links and opening links would be intuitive and out of the box. Appending a preference view for choosing a default browser is another good solution, I will make a tradeoff about that. Thank you for advising.

**Review by pernielsentikaer — COMMENTED** [review]
You should add the [preferences](https://developers.raycast.com/api-reference/preferences) the right place, you shouldn't use a command for that 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
