### PR TITLE
Add naver-search-engine extension

### PR DESCRIPTION
**Pull request by kw-lee**
## Description

naver-search-engine extension

An extension for [Naver](https://naver.com) search with autosuggestions.
This extension is inspired by [alfnaversearch : Naver Search Workflow for Alfred](https://github.com/Kuniz/alfnaversearch).

Note: I want to resubmit an extension that I had [previously stopped submitting](https://github.com/raycast/extensions/pull/895). Since another extension which has same name was registered in the meantime, I renamed the extension to `naver-search-engine` from `naver-search`

## Screencast

naver-search-engine-general
naver-search-engine-kor-eng
naver-search-engine-korean
naver-search-engine-shopping
naver-search-engine-sino-korean

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Isn't Naver [shutting down](https://www.koreaherald.com/view.php?ud=20210204001068) very soon?

**Comment by kw-lee** [comment]
The link you posted is Naver's "popular search keyword chart", which has nothing to do with this extension. This extension aims to search for the words you want.

**Comment by pernielsentikaer** [comment]
Yeah, I just figured it out, it was actually Neeva I was referring to 🙂

**Comment by pernielsentikaer** [comment]
I can see that we already have a [Naver Search](https://www.raycast.com/magneto/naver-search) in the store, how is this compared with that? It might make more sense to improve the current one instead

**Pull request closed without merging**
