### PR TITLE
Update cratecast extension

### PR DESCRIPTION
**Pull request by BalliAsghar**
## Description

Added abilty search symbols, e.g Structs, Enums etc

## Screencast

https://github.com/raycast/extensions/assets/14165223/37204249-6e37-4820-9a3a-44677dd0033a

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by BalliAsghar — COMMENTED** [review]
thanks

**Comment by BalliAsghar** [comment]
Added Dropdown.

Metadata-3

**Comment by pernielsentikaer** [comment]
@gleich could you check this 🙂

**Comment by pernielsentikaer** [comment]
@gleich just checking if you had time to check this 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
