### PR TITLE
[Chess.com] Add more time controls

### PR DESCRIPTION
**Pull request by tomassliz**
## Description

Add more time controls for the Chess.com extension:
 - 10 | 5
 - 15 | 10
 - 20 min
 - 60 min

## Screencast

Screenshot 2024-11-21 at 14 23 27
Screenshot 2024-11-21 at 14 23 37

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by joshfarrant** [comment]
LGTM :shipit: Appreciate you improving the extension @tomassliz 💖

I might have a look at some point to see if there's a nice way to let users add their own times too. Not looked at the Raycast API docs in a while, but I imagine it will be straightforward enough 🤔

**Review by joshfarrant — APPROVED** [review]

**Comment by tomassliz** [comment]
@joshfarrant, do you know if there’s anything else I need to do to merge this pull request? The process seems to be very slow.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by tomassliz** [comment]
@pernielsentikaer Is there anything else I need to do to merge this PR, please?

**Comment by pernielsentikaer** [comment]
Sequoia

**Pull request merged**
