### PR TITLE
Add worktrees extension

### PR DESCRIPTION
**Pull request by canac**
## Description

New extension to view, add, and remove git worktrees.

## Screencast

https://github.com/raycast/extensions/assets/3740187/e130cc42-930e-4776-925e-a71127f732a4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- When I try to submit the form without entering anything there is no feedback, even a simple toast could help (or the error when you hover/blur the `New Branch Name` field

Maybe you could use [useForm](https://developers.raycast.com/utilities/react-hooks/useform) for that form

worktrees 2023-06-05 at 13 31 56

worktrees 2023-06-05 at 13 33 43
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* 

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by canac** [comment]
Thanks for the feedback @pernielsentikaer! I refactored to use `useForm` like you suggested. I ran into what I believe is a bug in the API that is currently preventing my form from being quite as polished as it could be: https://github.com/raycast/extensions/issues/7016.

**Review by thomaslombart — CHANGES_REQUESTED** [review]
I've noticed there's no `README.md` or `CHANGELOG.md`. Is that intentional? Could you add them?

**Comment by canac** [comment]
@thomaslombart Sorry, I added a changelog now. [This section](https://developers.raycast.com/basics/prepare-an-extension-for-store#provide-readme-if-additional-configuration-required) in the docs seems to say that a `README.md` is only necessary in advanced configuration is necessary or has a non-trivial use case, which I don't believe applies to my extension. I don't think there would be much meaningful information to add to a readme. Let me know if I you think I actually do need one to merge.

**Review by thomaslombart — APPROVED** [review]
Awesome! Let's ship this extension 🚀

**Pull request merged**
