### PR TITLE
Update word-search extension

### PR DESCRIPTION
**Pull request by j3lte**
## Description

- Added a preference to open details by default (#14920) 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by RishabSwift** [comment]
Can we have it so that the details view is not enabled by default? I think the toggle is a good option in preferences but seeing all definitions at once might be better

**Comment by j3lte** [comment]
@RishabSwift by default it is off

**Comment by pernielsentikaer** [comment]
Another approach could be using `useCachedState` to remember if it's open or not. This way, it wouldn't require a new setting. Would that be a good idea?

**Comment by j3lte** [comment]
@pernielsentikaer agreed, I'll update the PR

**Comment by j3lte** [comment]
@RishabSwift @pernielsentikaer I updated the code. Removed the introduced setting and instead just cache the 'Show Details' state

**Comment by pernielsentikaer** [comment]
Awesome 👏 That feels like a better solution - do you agree @RishabSwift

**Comment by RishabSwift** [comment]
That’s awesome, I like this solution!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
