### PR TITLE
Add raycast-g4f extension.

### PR DESCRIPTION
**Pull request by XInTheDark**
## Description

Add the raycast-g4f ("GPT4Free") extension. The code base is derived from the raycast-gemini extension. However, for response generation, this extension uses the [g4f-ts](https://github.com/VictorMRojas/g4f-ts) module. The default provider used is https://chatgpt.ai/, with options to switch to Bing or ChatBase. The default model used is `gpt-4-32k`.

This extension follows the terms of services of the aforementioned provider, as it provides the functionality solely for personal, non-commercial use.

[Update: Image generation capabilities have also been added. It is powered by the same g4f-ts module.] 

## Screencast
raycast-g4f-1
raycast-g4f-2
raycast-g4f-3
raycast-g4f-4
raycast-g4f-5

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by XInTheDark** [comment]
Extension is ready for review :-)

**Comment by pernielsentikaer** [comment]
Hi 👋

Thank you for your contribution 🔥

Why does this extension not require an API key? It appears to be leveraging GPT-4 and other paid models.

**Comment by XInTheDark** [comment]
Hi! The extension does not use OpenAI as the host, instead the model is hosted by http://chatgpt.ai/. The service is free for the public and it does not require an API key. This can be verified in the source code of the g4f-ts package I used.

**Comment by pernielsentikaer** [comment]
I just checked that site and as a free user (after signing up) I got 6 queries in total a day 🙂

**Comment by XInTheDark** [comment]
Hmm, I don't know about the restrictions on the site itself. It is possible that the provider added it in order to rate limit users, but the API I used (offered with g4f-ts) is not affected - at least I was not rate limited during the testing of my extension.

**Comment by XInTheDark** [comment]
Update: please see https://github.com/VictorMRojas/g4f-ts/blob/main/src/Providers/ChatCompletion/GPT.ts#L20 for the implementation of the provider code in g4f-ts. The README specifies that the GPT provider is powered by chatgpt.ai, but the actual URL called is "https://nexra.aryahcr.cc/api/chat/gpt". Their terms of service allow for free usage of the API for any purpose: https://nexra.aryahcr.cc/terms.

So insofar as this extension is concerned, it is in fact only calling the above URL and is not really connected to chatgpt.ai directly. ToS wise, I don't think there's a problem. 🙂

**Comment by pernielsentikaer** [comment]
Thanks for the explanation.

I'm still not sure about having this extension in our store.

Some of the concerns:

* I still don't see how this can be free, given that models like OpenAI’s have a significant cost
* The server isn’t public, so it’s unknown what happens to user’s prompts

**Comment by XInTheDark** [comment]
> The server isn’t public, so it’s unknown what happens to user’s prompts

This applies for a lot of API based extensions, and it's not feasible for the host to open source their model, so for all LLM extensions this issue is probably unresolvable

> I still don't see how this can be free, given that models like OpenAI’s have a significant cost

I don't really know the hosting process (see above), but looking at some repo creation dates, these free chatGPT providers have been running for many months now, so their hosting is quite sustainable for them at least.

**Comment by XInTheDark** [comment]
> Do you know more about this npm package?

Unfortunately not, I found this package after searching for gpt for free on npm, and it was the best choice for this extension. I'll check if there are other possibly more reputable packages that provide the required functionality, but most of them probably also utilize endpoints similar to this one.

**Pull request closed without merging**
