### PR TITLE
Add Storyblok extension

### PR DESCRIPTION
**Pull request by RobErskine**
## Description

We use [Storyblok](https://storyblok.com), a headless CMS, a lot at my [current outfit](https://stellarelements.com). I am always bopping around between different client spaces, development sandboxes, etc. This extension brings the power of Storyblok to Raycast to quickly open up those spaces, as well as accessing info without needing the Storyblok web interface. You can access stories (content), assets, users, and space activity all from within this command.

## Screencast

https://github.com/raycast/extensions/assets/1895120/de9c83cd-4f0e-4ee1-a907-ebe07927581d

User preferences:
-2024-04-01-15 38 57@2x

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
sextensionsstoryblok-2024-04-01-15 16 43
sextensionsstoryblok-2024-04-01-15 17 10

- [n/a] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by xmok** [comment]
Hi Rob Erskine 👋.

I am *NOT* a member of the Raycast team.

I was also working on an extension for Storyblok and I'm glad I can stop because yours is phenomenal 👌.

I notice you are using `useFetch` but you might be interested in the approach I took; though definitely a work-in-progress I used `storyblok-js-client` as it exposes types and I created my own custom hook [Link to Hook in Repo](https://github.com/xmok/raycast-extensions/blob/ext/storyblok/extensions/storyblok/src/hooks/useStoryblok.ts) that works like `useFetch` but has the benefit of returning errors which might be helpful in the future.

I look forward to installing your extension from the store!

Best.

**Comment by RobErskine** [comment]
@xmok thanks for the heads up on the custom hook. I will take a look at this for v1.1. I want to get it live and see how people use it and then improve on it; this hook looks like a great start.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Looks awesome @RobErskine 

Could you add at least one [screenshot](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) of the extension

**Review by RobErskine — COMMENTED** [review]
Woops, that's embarrassing. Sorry about that; I forgot to `git add` them. They are added in the `metadata` folder now, @pernielsentikaer. Would you mind taking a look now?

**Comment by LitoMore** [comment]
Better to use some mock data instead of mosaics on the screenshot.

**Comment by RobErskine** [comment]
@LitoMore I hear you, but Storyblok is a paid service, and getting the full scope of what's possible on a free account to create mock data is a bit tricky.

It's not impossible, so if the recommendation is to use mock data instead (some of the screenshots will be more limited in what they show), I can do that.

**Comment by pernielsentikaer** [comment]
If there is no sensitive data it's okay to use it, but many uses some mock data - is there any sensitive data @RobErskine

**Comment by RobErskine** [comment]
@pernielsentikaer the information mosaicked out in the screenshots in `metadata` are client/brand names in our Storyblok Partner space and subsequent customer names / their emails. 

Do you recommend swapping what I posted with a fake account / mock data instead of censoring those private strings? I know the [Do's and Don'ts](https://developers.raycast.com/basics/prepare-an-extension-for-store#dos-and-donts) say not to use censored data, which is why I have the censored out.

If it's better to use mock data, I can spin up a new Storyblok account, create a bunch of fake data, hook the extension up to that access token, and take new screenshots this evening.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
