### PR TITLE
[Gitignore] Add store metadata

### PR DESCRIPTION
**Pull request by daniel-stoneuk**
## Description

Added store metadata:

* Category: Developer Tools
* Screenshots
* changelog.md

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `media` folder

### CODE REVIEW

**Review by mattisssa — APPROVED** [review]

**Comment by daniel-stoneuk** [comment]
Cheers for merging this! Just to check, is the filename `CHANGELOG.md` preferred over `changelog.md`? If it is, I can create a PR to update the docs.

**Comment by mattisssa** [comment]
Hey, as far I as know it's more common to keep the file name with a capitalised text for changelogs or readme. 
What docs do you mean by the way?

**Comment by daniel-stoneuk** [comment]
I've seen the capitalised README / CHANGELOG more often as well, though the Raycast API docs uses the lowercase filename. https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history

I suppose Raycast's implementation won't mind either way :)

**Comment by mattisssa** [comment]
Oh yeah, you might be right. Let's bring it back to the lowercase until I discuss it with the team.

**Pull request merged**
