### PR TITLE
Add Sentry Reporting

### PR DESCRIPTION
**Pull request by SandyGifford**
## Description

Adds error reporting to Sentry (we needed a little more info than was available in `/extension-issues`)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by clayton-knapp** [comment]
LGTM!

**Comment by clayton-knapp** [comment]
New changes LGTM!

**Comment by pernielsentikaer** [comment]
It seems like there is some changes in main branch thats conflicting, can you rebase and resolve them? I'm not able to help since we can't modify it - could you untick that next time 🙂

**Comment by SandyGifford** [comment]
Closed in favor of https://github.com/raycast/extensions/pull/14936 (`reclaim-ai:main` was being held up for this PR)

**Pull request closed without merging**
