### PR TITLE
[Restart Raycast] Init Extension

### PR DESCRIPTION
**Pull request by koinzhang**
## Description

- Restart Raycas

## Screencast

restart-raycast-1

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @koinzhang 👋

What's the reason for making this extension? Do you struggle with Raycast 😊

**Comment by koinzhang** [comment]
Hi @pernielsentikaer 

When I was developing extensions, if I needed to change the extension's icon, I needed to restart the Raycast app for it to take effect, so I created this extension
Also, I've had problems with Raycast's memory usage spiking, which can be temporarily solved by restarting Raycast

**Comment by pernielsentikaer** [comment]
Sorry for the longer response time than usual. I had to discuss it internally.

We have decided not to add this to the store as it is right now, but feel free to use it as a local extension, I hope you understand.

1) Regarding extensions, the icon cache is something we're looking into.
2) Memory usage spiking is something we want to fix rather than having users restart

**Comment by koinzhang** [comment]
That's okay. I hope you can get these issues resolved sooner rather than later.

**Comment by pernielsentikaer** [comment]
I agree 🙂

**Pull request closed without merging**
