### PR TITLE
Update chatgpt extension

### PR DESCRIPTION
**Pull request by bxb100**
## Description

add a new `Summarize` command to summarize website and YouTube video

inspired by https://www.reddit.com/r/raycastapp/comments/1cdhrsw/comment/l1hn90s/

## Screencast

image

image

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋

Just a quick question, is there a reason why I can only see GPT-3.5 models when I'm trying to create a new model?

**Comment by bxb100** [comment]
maybe you enable the `custom model` that was introduced by #11716

image

**Comment by pernielsentikaer** [comment]
I don't have that setting enabled, weird! I have to dig a bit deeper, but I suppose I should see more models here

Raycast02052024-zlZPsHKP png@2x

**Comment by bxb100** [comment]
```
setOption(models.filter((m) => m.id.startsWith("gpt")).map((x) => x.id));
``` 
code filter the non-gpt start models

**Comment by pernielsentikaer** [comment]
Looks like your'e right, it's something in my end and it's not something changed by this PR

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
