### PR TITLE
Update openinterpreter extension

### PR DESCRIPTION
**Pull request by Cobular**
## Description

Run Open Interpreter from the comfort of Raycast! The last Raycast command you'll ever need - do anything you can imagine on your computer!

Note on the last item on the checklist - can I use one of the product screenshots that need to be in metadata in my readme without duplication?

## Screencast

https://github.com/raycast/extensions/assets/22972550/06973f4b-7ef5-4a5a-a8c5-994d4fd8d0e8

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by Cobular** [comment]
Hey! Don't close this, I'm waiting on a response from staff. Any updates @mil3na ?

**Review by pernielsentikaer — COMMENTED** [review]
Hi @Cobular 👋 

I apologize for the delayed response. It's a big extension, and I have some things to figure out. Perhaps you can assist me?

I don't believe it's a good idea for it to perform tasks automatically, as the end user may not be aware of its actions. For instance, when I asked it to delete a file, it simply disappeared. I guess the "AI" also could get confused and do something different than the user expects it to.

Perhaps there should be a designated action to "trigger" it instead to avoid something unexpected happening could solve this?

**Comment by Cobular** [comment]
Yeah! I believe it's supposed to be pausing for approval - I'll check on that, because I agree.

**Comment by xilopaint** [comment]
> Yeah! I believe it's supposed to be pausing for approval - I'll check on that, because I agree.

@Cobular Any news here?

**Pull request closed without merging**
