### PR TITLE
[Update] GitHub extension

### PR DESCRIPTION
**Pull request by Angelk90**
## Description

- Fix fork view
- Change notification display

## Screencast

Before:
Screenshot 2023-11-02 alle 21 22 10

After:
Screenshot 2023-11-02 alle 21 19 28

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @Angelk90 👋 

Could you fix the CI errors [reported here](https://github.com/raycast/extensions/actions/runs/6742960121/job/18329969552?pr=9081) and add a [CHANGELOG](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) entry?

**Comment by thomaslombart** [comment]
It seems you have some conflicts here. Also, why changing the notification display? It feels less readable if the repository is set as the list's title.

**Comment by thomaslombart** [comment]
@Angelk90 As you can see in GitHub's screenshot, the notification's title still takes a larger place instead of the actual repository. I, for example, pay much more attention to the title than the repo itself mostly because most of my notifications come from the same repository.

**Comment by thomaslombart** [comment]
Sorry, but I'm not really convinced that this would lead to a better UX. I've often seen an extension being modified to better fit someone's workflow, and issues being opened right after the change because people actually liked the default workflow.

However, as you said, we can add a preference to know which one should come first. It should be title by default to avoid disrupting the experience for other users. I invite you to make these changes.

**Pull request closed without merging**
