### PR TITLE
[Railway] rename icon so it shows in store + cache + minor refactor + update deps

### PR DESCRIPTION
**Pull request by xmok**
## Description

- A `Failure` toast is shown if something goes wrong
 - The API Token is now `required`
 - Cache the project by using `useCachedPromise`
 - Rename icon so it shows up properly in Raycast Store (this is how it looks right now 👇)
Screenshot 2024-08-06 at 12 31 26 AM

## Screencast

BEFORE

https://github.com/user-attachments/assets/20a5e420-7bb9-4dbd-9f59-dcfd0da221f5

AFTER

https://github.com/user-attachments/assets/d675b8b4-6616-49f7-87de-5eff3434f03c

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for the update @xmok - @coffee-cup can you have a look here?

**Comment by nagauta** [comment]
I've wanted to fix the icon thanks!
I'll take a look soon

**Comment by pernielsentikaer** [comment]
Thanks for taking a look @nagauta 🔥

**Comment by nagauta** [comment]
it did work thanks! (I checked as far as I can check)
スクリーンショット 2024-08-14 16 41 38

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
