### PR TITLE
[Jisho] Add Search History 

### PR DESCRIPTION
**Pull request by mmtftr**
## Description

PR for #4120 

I refactored the search command with new Raycast utils and then added a Search History command. 

The Search History command is pretty simple, it shows the previous searches by the user. Previous searches are saved when the user runs an action (copy/open in browser) on a search result and also when the search bar is cleared (this can be toggled off in the extension preferences).

Saved search results will be shown with as much info as they have. For search results, we show the result directly. For saved search queries, only the query is shown. Search entries are deduplicated such that any entry that gets re-added will only be moved up to the top of the history (not added twice).

I also changed the search command to allow for initial search queries. This is used when a user selects a previous search query to launch the search command with the initial query set.

Just realized that there is no delete functionality and no manual add, I'll add these two things before pushing for a merge.

## Screencast

Screenshot 2023-01-28 at 19 48 12

## Checklist

- [ x ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ x ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ x ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ x ] I checked that files in the `assets` folder are used by the extension itself
- [ x ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mmtftr** [comment]
@dmacdermott this should be ready for merge, let me know if you have any questions. I don't really know the procedure for review here at Raycast.

**Comment by mmtftr** [comment]
I moved from launchCommand to Action.Push since that provides a way for the user to navigate back to the search history and continue from there. I'm not sure which one is preferred.

**Comment by mmtftr** [comment]
Done 👍

**Comment by mmtftr** [comment]
@dmacdermott is this ready for merge?

**Comment by dmacdermott** [comment]
@mmtftr Yeh looks good ok to me 👍

@pernielsentikaer Is it possible if this pr can get merged? Cheers

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Tested with success, let's go! 🧑‍🚒

**Pull request merged**
