### PR TITLE
[Set Audio Device] Fix for macOS Ventura

### LINKED ISSUE #3542: [Set Audio Device] ...
# Extension – [Set Audio Device](https://github.com/raycast/extensions/tree/9705ba94af72208cff790222ee3ce28e02231825/extensions/audio-device/)
Author: @benvp

## Steps To Reproduce

1. Set a favourite device in Raycast Settings -> Extensions -> Set Audio Device
2. Use raycast to select Set output device to Favourite

## The current behavior
Fails with message "Favourite output audio device could not be set"

## The expected behavior
Audio output is set to the favourite device

### Raycast version
Version: 1.43.2

### PR DESCRIPTION
**Pull request by gkoberger**
## Description
Closes #3542 #3415 #3446 #3479 #3526 #3540 #3349

Extension: https://www.raycast.com/benvp/audio-device
Author: @benvp 

This updates Set Audio Device to work with macOS Ventura 13. The issue was that the Settings panel was redesigned in the upgrade, so the Apple Script that powers this when Airplay is checked on (and also powers the Favorite command) no longer works.

**🚨 NOTE:** There is one big problem, which is that it opens the Settings modal rather than doing it behind the scenes. I'm still trying to figure out if it's possible to hide it in Ventura, but maybe @benvp knows how to do that?

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
HI @gkoberger 👋 

I just tested this in the latest beta os macOS 13 (13.1 Beta 3) and I don't see anything that pops or flashes - do you?

@benvp do you mind checking this

**Comment by gkoberger** [comment]
@pernielsentikaer thanks for checking it out!

Based on my understanding of the original code, most of the time it uses the `audio-devices` binary in `audio-device.ts`, which works like a charm. However, there's two situations when it uses an Applescript: when "Airplay" is checked in the settings, or when using the "Favourite" feature.

My assumption is that because Airplay devices don't show up in the binary being used, the original authors decided an Applescript was the best/only way to do it.

So! You can try to cause it by using "Set Output Device to Favorite" to trigger the Applescript. If that works without a flash, then there's no problem!

(It's very possible there's just something weird on my computer, and for everyone else it works great!)

**Comment by jdsimcoe** [comment]
When I remove the toggle my output devices display normally again.

**Comment by gkoberger** [comment]
@jdsimcoe are you using this PR, or the extension in general? What version of macOS are you on? I'll try to help track down the issues for ya!

**Review by FezVrasta — APPROVED** [review]

**Comment by jdsimcoe** [comment]
@gkoberger I'm using the extension in general, not this PR. Hopeful that it actually fixes things for me. I'm on macOS `13.1 Beta (22C5050e)`. Once it gets merged, I'm assuming I'll be able to update via Raycast and try the fix?

**Comment by gkoberger** [comment]
@jdsimcoe Ah yes, this should fix it hopefully! Admittedly I don't know how Raycast extensions update behind the scenes, but I imagine it will.

(There's one caveat I mentioned before, which is that it opens the Settings modal, which is super annoying. I haven't been able to find a way around it, though. This only happens if Airplay is checked.)

**Comment by gkoberger** [comment]
Hey @benvp just wanted to check in and see if you had any thoughts!

**Comment by gkoberger** [comment]
Also fixes #3771

**Comment by pernielsentikaer** [comment]
When I enable `Airplay` and opens Set Output Device is newer stops loading, is that intended?

**Comment by benvp** [comment]
Just tried it out and it's not working for me on Ventura. When running the apple script version it's stuck at the "Appearance" system settings window. 

I'm sorry but I absolutely have no experience using AppleScript and the AppleScript based implementation was done by @FezVrasta.

Right now, I can't help with that.

**Comment by benvp** [comment]
@gkoberger Based on your script, the following works for me, but will need some tweaking. It currently steals the focus of the raycast window and therefore hides raycast for me. When opening it up again, the audio devices appear in the list properly.

```
do shell script "open x-apple.systempreferences:com.apple.Sound-Settings.extension"

set devices to {}

tell application "System Events" to tell application process "System Settings"
	repeat until exists window "Sound"
		delay 0.3
	end repeat
	if value of radio button 1 of tab group 1 of group 2 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Sound" is not 1 then
		click radio button 1 of tab group 1 of group 2 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Sound"
		repeat until value of radio button 1 of tab group 1 of group 2 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Sound" is 1
			delay 0.3
		end repeat
	end if
	
	tell table 1 of scroll area 1 of group 2 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Sound"
		set selected_row to (first UI element whose selected is true)
		set currentOutput to value of static text of group 1 of UI element 1 of selected_row as text
	end tell
	
	set theRows to rows of table 1 of scroll area 1 of group 2 of scroll area 1 of group 1 of group 2 of splitter group 1 of group 1 of window "Sound"
	
	repeat with r in theRows
		try
			set deviceName to value of static text of group 1 of UI element 1 of r as text
			set deviceType to value of static text of group 1 of UI element 2 of r as text
			set end of devices to {deviceName, deviceType}
		end try
	end repeat
end tell

if application "System Settings" is running then
	tell application "System Settings" to quit
end if

return [devices, "currentOutput", currentOutput]
```

**Comment by gkoberger** [comment]
Okay, I have another attempt, this time not using an AppleScript (since it feels so hacky). I use 3 different sources for getting audio output sources (the included binary, [airplayer](https://www.npmjs.com/package/airplayer) and `system_profiler SPBluetoothDataType`).

There's two things I don't love:

- [ ] The output still opens up the System menu... it's annoying but doesn't break the flow like the old version does
- [ ] I had to use a setTimeout to collect Airplay, which I don't like at all

I think I can live with the Sound settings menu still opening, because it only happens once you make a selection. I find the setTimeout to be super flaky (for example, sometimes 3 seconds isn't long enough and sometimes 1 second is long enough), I just don't know what other options we have here. (I imagine we could refactor it so that as the listener reports new devices, the react list could update?)

For a larger refactor, I would suggest:
- [ ] Combine `audio-device` and `utils` into one, because it's really confusing to have two similar functions that operate differently
- [ ] Merge the Bluetooth stuff into `audio-device.ts`, because it's able to pick up Bluetooth devices that are connected but not active (but it can't currently go there because it doesn't have a device.id)
- [ ] Fix it so that based on the source (the binary, Bluetooth or airplay) it knows how to switch the device (the binary can use itself, however bluetooth/airplay have to pop open the settings)

(Also, fixes #3942)

**Comment by gkoberger** [comment]
I think these typescript errors might be where I tap out here :/ I might come back to this later, but it's working for me locally now and I'm not sure I'll be able to get TS definitions done for the two packages I pulled in.

**Comment by pernielsentikaer** [comment]
I gave it another spin, and when I had AirPlay enabled, I just got `No Results`

Raycast-iioWg6yr@2x

When disabling it, I get results.

Raycast-nYEmO9IC@2x

Can I help with some debugging?

**Pull request closed without merging**
