### PR TITLE
Fetch all paginated AWS resources

### PR DESCRIPTION
**Pull request by JonathanWbn**
## Description

This starts fetching all AWS resources by using pagination. This was already achieved for the Cloudformation stacks with #1030. This PR also introduces it for the Queues, EC2 Instances, and Codepipelines.

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @vimtor 👋 

Did you thumb up because you tested it out working? I don't have AWS so would like some help if possible 😄

**Comment by vimtor** [comment]
> Hi @vimtor 👋
> 
> Did you thumb up because you tested it out working? I don't have AWS so would like some help if possible 😄

Hi @pernielsentikaer I did not thumbs up the comment. I think you confused me with @victor-falcon 
Any way I have an AWS account I could help you if you want ❤️

**Comment by Hodglim** [comment]
@pernielsentikaer - Just tested out this PR with my AWS credentials and it looks good! 👍

**Comment by pernielsentikaer** [comment]
Ah @vimtor, sorry 😄 You're always on my mind 🎹

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @JonathanWbn 👋 

It works as expected, thanks for the update! 😄 

Do you by any chance have the possibility to add [screenshots](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots), [changelog](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) and [categories](https://developers.raycast.com/basics/prepare-an-extension-for-store#categories) in this PR, or could it be added soon? 😄 

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by JonathanWbn** [comment]
Hi, @pernielsentikaer

Sure, I added a changelog and categories, screenshots were already added with #1259.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @JonathanWbn 👋 

I'm so sorry, thanks, I was totally blind! 😄 

Could you change the format of the changelog, we changed [changelog format](https://developers.raycast.com/basics/prepare-an-extension-for-store#version-history) and set a date on the first item in the changelog too?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Pull request merged**
