### PR TITLE
Add toggle-menu-bar extension

### PR DESCRIPTION
**Pull request by iamyeizi**
## Description

Toggle auto hide/show menu bar: "In Full Screen Only" / "Always"

## Screencast

SCR-20230507-rcsj

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
This looks like something that's included in [Dock Tinker](https://www.raycast.com/koinzhang/dock-tinker), could you check that

**Comment by iamyeizi** [comment]
image

According to what I see in that extension only modifies the Dock functionalities, instead, my extension only modifies the Menu Bar, in this case show/hide the menu bar.


Do you think I should give more details in the extension name, command or description?

My extension only switches between "Always" and "In Full Screen Only".
image

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by pernielsentikaer** [comment]
Ah yeah, let's get this merged 🫶

**Comment by iamyeizi** [comment]
Cheers from Argentina! 👋🏽

**Comment by ronaldland** [comment]
@iamyeizi how do I modify it to toggle between "In Full Screen Only" and "Never"?

**Comment by iamyeizi** [comment]
> @iamyeizi how do I modify it to toggle between "In Full Screen Only" and "Never"?

I found the "Never" option illogical because for that I would set it from Settings directly if you are interested in some widgets from the status bar on the right, also with the included Raycast extension ("Search Menu Items") you can navigate through the menus of the current app.

When I have time I will add all the toggle options from Settings.

**Comment by ronaldland** [comment]
@iamyeizi I see, thanks! You think it's possible to do the "in full screen" only and "never" combination? When using apps in full screen I would like to see the menu bar, but when watching a video in safari quickly hiding the menu bar using the shortcut would be nice.

**Comment by iamyeizi** [comment]
@ronaldland At the moment, I don't think so.
I'll see if macos's settings allows me to do that or if I need to make a backend for that.

**Pull request merged**
