### PR TITLE
Update screenshot extension

### PR DESCRIPTION
**Pull request by nirtamir2**
## Description

This PR add command to copy screenshot window to clipboard. I use clipboard most of the time - so this will be helpful.
I use the same icon as the copy-window command.

## Screencast

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Could you check this @Aayush9029 🙂

@nirtamir2 thanks for your contribution, could you also add a changelog entry

**Comment by Aayush9029** [comment]
Thank you for your contribution @nirtamir2, looks nice!

Like @pernielsentikaer said, all you need is to make changes to the changelog.md file.

**Comment by nirtamir2** [comment]
I updated the changelog

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
