### PR TITLE
Swift evolution update 3

### PR DESCRIPTION
**Pull request by BProg**
## Description
issue https://github.com/raycast/extensions/issues/11375

## Screencast

Screenshot 2024-05-10 at 15 28 09

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by BProg** [comment]
@pernielsentikaer ready for review

**Comment by pernielsentikaer** [comment]
Works as expected for me, @dehesa do you want to check it?

**Comment by dehesa** [comment]
No, I am good

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
