### PR TITLE
Update port-manager extension

### PR DESCRIPTION
**Pull request by lucaschultz**
## Description

- Improved menu bar commands
- Removed the preference to use `sudo` for listing and killing processes
- Added the "named ports" feature (special thanks to @Sheraff)
- Made command names more concise

## Screencast

https://github.com/raycast/extensions/assets/45899273/bc6c5a7e-4af1-431f-ad60-4c8d43132fcc

Bildschirmfoto 2024-01-02 um 19 42 45

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
It seems like there is something with the `isLoading` prop in the menubar command, for some reason I can't debug it at the moment, can you take a stab? It's like its not unloading correctly @lucaschultz 

Raycast-LAaugQmX@2x

**Comment by Sheraff** [comment]
@lucaschultz @pernielsentikaer Should I try and take a stab at it? I don't think I'll be able to commit to the repo but maybe I can find the issue and we can finally merge this?

**Comment by lucaschultz** [comment]
> @lucaschultz @pernielsentikaer Should I try and take a stab at it? I don't think I'll be able to commit to the repo but maybe I can find the issue and we can finally merge this?

@Sheraff, sorry, I'm a bit short on time at the moment. Thank you for your patience and for keeping the issue alive.


> It seems like there is something with the `isLoading` prop in the menubar command, for some reason I can't debug it at the moment, can you take a stab? It's like its not unloading correctly @lucaschultz
> 
> Raycast-LAaugQmX@2x

@pernielsentikaer, I used to use a hack (1-second timeout) to give the processes enough time to load. This might have created a race condition. I refactored the process retrieval to use the `useCachedPromise` hook and am now utilizing the `isLoading` property of the hook. Does this solve the problem?

**Comment by pernielsentikaer** [comment]
Much better 🙂

**Review by pernielsentikaer — APPROVED** [review]
Aawesome @lucaschultz

**Comment by Sheraff** [comment]
Is the prettier check preventing a release? It doesn't seem to have been updated in the store and there wasn't a slack notification

**Comment by lucaschultz** [comment]
@pernielsentikaer can we do anything to get this released to the store?

**Comment by Sheraff** [comment]
> @pernielsentikaer can we do anything to get this released to the store?

It actually got released today at some point.

**Comment by pernielsentikaer** [comment]
I manually ran it @Sheraff 🙂

**Pull request merged**
