### PR TITLE
🐛 Fixed menubar command bug and changed onsubmit textarea behaviour to clear (Typefully)

### PR DESCRIPTION
**Pull request by DanielFerguson**
## Description

- Changed draft textarea to clear upon submission
- Fixed menu bar command bug calculating title length

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @DanielFerguson 👋 

Can you check the merge conflicts? 😊

**Comment by DanielFerguson** [comment]
Absolutely, @pernielsentikaer

**Comment by DanielFerguson** [comment]
Done-zo-washington, @pernielsentikaer. 🚀

**Review by pernielsentikaer — APPROVED** [review]
Thanks 🔥

**Pull request merged**
