### PR TITLE
Add Bundesliga extension

### PR DESCRIPTION
**Pull request by anhthang**
## Description

The latest table, results and stats for clubs in 2021-2022 in Bundesliga can be found in this extension

## Screencast

bundesliga-01
bundesliga-02
bundesliga-03
bundesliga-04
bundesliga-05
bundesliga-06

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @anhthang 👋 

This extension is suffering from the same issues as I reported in #1235 - can you look into this one too?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 👋 

It's fixed. Match details also added from local repository. Please review again.

**Comment by pernielsentikaer** [comment]
Hi @anhthang 👋 

Awesome update 🔥 I have the last feedback for this one now:

- Could you add icons to [ActionPanel](https://developers.raycast.com/api-reference/user-interface/actions#api-reference) items? As it is right now have 1/3 commands image in the [ActionPanel](https://developers.raycast.com/api-reference/user-interface/actions#api-reference), it would be nice if they all had 😄 

- There is a huge chunk of leftover code in components/matchday.tsx, can it be removed?

- Could you format with Prettier 😄 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by anhthang** [comment]
Hi @pernielsentikaer 👋 

All is fixed 💪

**Comment by pernielsentikaer** [comment]
Hi @anhthang 👋 

Awesome work 🔥

We could consider switching "Open in Brower" and "Squad" in the details for the club. What do you think about that?

I'll merge it in 30 minutes or if you request it earlier 🚀

**Review by pernielsentikaer — APPROVED** [review]
🥳

**Pull request merged**
