### PR TITLE
Show Desktop extension

### PR DESCRIPTION
**Pull request by zyxscientist**
## Description

This Extension will minimize all window and make user back to desktop is just one click, just like back to desktop on Windows PC.

## Checklist

- [✅ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ✅] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [✅ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [✅ ] I checked that files in the `assets` folder are used by the extension itself
- [ ✅] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋 

It seems like the same thing as [this does](https://www.raycast.com/peduarte/hide-all-apps) 😊

**Comment by zyxscientist** [comment]
Yeah, but Show Desktop run faster in any device any condition, it minimize all windows after you hit the ENTER which is a feature that all Raycast user need.
[this does](https://www.raycast.com/peduarte/hide-all-apps) runs slow in Intel Mac, user need to wait for about 1 sec.
I'm sorry by saying so but with all due respect.

**Comment by pernielsentikaer** [comment]
Then we should aim to enhance the current; instead, we want the fastest way - are you up for that?

**Comment by zyxscientist** [comment]
OK then, thanks for your reviewing & wish u a good day.

**Comment by pernielsentikaer** [comment]
Sounds like a good update. Do you mind changing your PR to enhance the current one and be a contributor?

**Comment by zyxscientist** [comment]
Yeah might do it later! Happy to make some good little extension for the community.
I will close this stuff first.

**Pull request closed without merging**
