### PR TITLE
Add brawlstars extension

### PR DESCRIPTION
**Pull request by MaximeGuiliani**
## Description

This extension helps Brawl Stars players to get data on specific brawlers.
You can also search for players and clubs.
## **API Key**

You must get an API key from [Brawl Stars API](https://developer.brawlstars.com/#/).
### **Search**

You can search for players, clubs, and brawlers. The search result will be displayed in the table below.

## Screencast

Screenshot of the extensions : 

# List of commands :
image

# **Player**

image

# **Clubs**

image

# **List Of Players From A Club**

image

# **Brawler LIST**
image

# **Brawler INFO**

image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by mil3na** [comment]
Hi! Thank you so much for your contribution to Raycast!
My name is Milena and I will be reviewing your extension today :)

I tried your extension and, on my first player query, it gave me this error:

CleanShot 2023-06-28 at 15 14 54@2x

However, it started working after trying again. Do you mind investigating it? Also, do you really need jsons with more than a thousand lines on your extension? Can't you have this info pulled from the API?

**Comment by MaximeGuiliani** [comment]
> Hi! Thank you so much for your contribution to Raycast! My name is Milena and I will be reviewing your extension today :)
> 
> I tried your extension and, on my first player query with the id below, it gave me this error:
> 
> Screenshot 2023-06-28 at 15 20 14
> CleanShot 2023-06-28 at 15 14 54@2x
> 
> However, it started working after trying again, with the id on your screenshot. Do you mind investigating it? Also, do you really need jsons with more than a thousand lines on your extension? Can't you have this info pulled from the API?

Sure I will look at it (never had this issue, I might not have tested enough :/ )

And for the JSON :
I keep it to not query to API too much as she is open to every open without needing an API key and the value in the JSON only changes once a month so I thought it was a good idea to just update the JSON once a month but I sure can call the API for retrieving the data.

Thanks for your return have a great day. 😃

**Comment by MaximeGuiliani** [comment]
### **Everything should work as excepted now:**

- Fix 2 bugs while searching with the char "#"

- Remove JSON for list of brawlers: Usage of Brawlify API ( it looks actually faster now than before with the JSON files)

- Fix bug when player is not in a club

**Comment by MaximeGuiliani** [comment]
> ### **Everything should work as excepted now:**
> * Fix 2 bugs while searching with the char "#"
> * Remove JSON for list of brawlers: Usage of Brawlify API ( it looks actually faster now than before with the JSON files)
> * Fix bug when a player is not in a club ( Added text "Not in a club and also remove action "Show club"
> 
> brawlstars 2023-06-28 at 20 42 39

**Comment by MaximeGuiliani** [comment]
@mil3na Hey, I corrected the major bug that you notice me and a few other minors while searching with the char '#'.

I also remove error console logging to use it in my errors component.
And some code refactoring.

I tested the command with an empty club (Example:#8QQLUGG)
image


Player not in a club :
brawlstars 2023-06-29 at 11 50 12

Thanks for your reviews have a great day 😃.

**Review by mil3na — APPROVED** [review]
It looks good to me! Great job and thanks for your effort :)

**Pull request merged**
