### PR TITLE
Add hyrule-compendium-search extension

### PR DESCRIPTION
**Pull request by Macko-pp**
## Description

This extension allows you to conveniently search and access information from the Hyrule Compendium. It uses the Hyrule Compendium API by [Aarav Borthakur](https://github.com/gadhagod). The extension uses fuzzy search (fuse.js) to search for the entry you inputted, it doesent matter if you made a typo or didnt use the complete name, it still works!

## Screencast

image1
image2
image3
image4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Don't show any content before isLoading is set to false, right now it shows `undefined` a few places while loading

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Is this ready for another review?

**Comment by Macko-pp** [comment]
I believe so, yes.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
