### PR TITLE
New extension: Korean Spelling Checker

### PR DESCRIPTION
**Pull request by jcha0713**
## Description

This PR adds a new extension with a command to check Korean spelling/grammar errors in user's text.

## Screencast

https://user-images.githubusercontent.com/29053796/210115761-db9e8204-8530-4dd5-9c0b-cba5bf8c22b2.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by jcha0713** [comment]
Here's the text I used in my examples:

```
이 곳은 막다른 장소였다. 더 이상 나아갈 수 없는, 여기 남아있을 생각이 아니라면 반드시 돌아가야만 하는 모양새였다. 작은 창문 하나 달려있지 않은 걸 보아 복도 끝이라는 느낌은 들지 않았는데, 그렇다면 무엇 때문에 이런 장소를 만들었을까? 여기엔 어떤 문도 보이질 않았다. 단지 막다른 길 뿐이었다. 굳이 사용할 용도를 찾아보자면 동아리방을 찾지 못한 활동적인 동아리들이 무언가의 연습을 할 용도로 찾아올 수는 있을까? 평범하게 학교를 다닌다면 한 번도 지나갈 일이 없는, 모든 동선으로부터 유리된 곳이었다. 그리고 여기엔 이상하게도, 우산걸이가 하나 놓여 있었다. 열 개 정도의 우산을 걸 수 있을 정도로 크기가 꽤 있는 우산걸이였다. 우산걸이의 왼쪽 끝에서 조금 오른쪽에는, 우산 하나가 걸려 있었다. 중간 크기의 검정색 장우산이. 비가 오지 않은 지 벌써 두 달 여가 지났다.
```

and there should be a total of six grammatical errors in this text.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Review by pernielsentikaer — APPROVED** [review]

**Comment by ImBada** [comment]
This isn't working now.

**Comment by pernielsentikaer** [comment]
Since this is about a public extension not built by us but maintained by our community, you should use the `Report Bug` action in Raycast action panel while having the extension selected in order to create an issue for it, so the author of the extension or someone else can help you out

**Pull request merged**
