### PR TITLE
Update footy-report extension

### PR DESCRIPTION
**Pull request by thuoe**
## Description

A new command to search across domestic competitions and display current table standings. From there, you can be directed to view team details

## Screencast

https://github.com/raycast/extensions/assets/15982721/57ae06f5-a453-44f5-ab28-41f3eebb86e9

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Thanks for your contribution 🔥 

If I search for eg `s` in the new command it crashes 🫠

footy-report 2024-01-17 at 00 03 54

Could you look into that?

**Comment by thuoe** [comment]
@pernielsentikaer 
Thanks again for the review. Once more I forgot to address error handling for this particular hook response 🤦 
This should now be resolved ✅ 
As for the install button, I have included it as part of my independent repo, separate to the extensions repo to direct developers to the main Raycast Store.

**Comment by pernielsentikaer** [comment]
We already include a button both in the app and in the web store, so having it double doesn't make sense. Can we for now remove it until we finder a better solution for this?

**Comment by thuoe** [comment]
> We already include a button both in the app and in the web store, so having it double doesn't make sense. Can we for now remove it until we finder a better solution for this?

@pernielsentikaer 
Apologies, I was looking at examples of other extensions published that have separate repos (see example [here](https://github.com/ThatNerdSquared/timers-for-raycast)) that include an install button as part of their `README` file but if this is not good practice I can still remove it 👍

**Comment by pernielsentikaer** [comment]
I'll look into removing it from that extension too, it's not meant to be there 🙂

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
