### PR TITLE
Warp support for terminal finder

### PR DESCRIPTION
**Pull request by dannyneup**
## Description

Hey, I've added [warp](https://www.warp.dev) support for the terminalfinder extension and tied it up by adding a terminal app selection via preferences rather than having multiple commands for each one. 

## Screencast

https://user-images.githubusercontent.com/82511759/209607274-aaa6472f-e926-4ee1-8fc1-b5cf20d2f410.mov
(macOS terminal and Iterm stayed the same)

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Thanks for your contribution @dannyneup 🔥 

I might not agree that it's a good idea to only have one command, since I use all three terminals based on the purpose and then I won't be able to use it - I'd rather see more commands here 😊

**Comment by dannyneup** [comment]
Ah, ok. Sorry, it was just a suggestion. Im happy as long as the Warp integration makes it into Raycast (no matter how)! :)

Greetings from Germany! :D

**Comment by pernielsentikaer** [comment]
Could you add it as new commands to the existing one instead? Then I think we're good to go 😊

**Comment by pernielsentikaer** [comment]
Let me know if you need any assistance

**Comment by dannyneup** [comment]
@pernielsentikaer 
Thanks but I think that should be it. :)

**Comment by pernielsentikaer** [comment]
Awesome! @yedongze can you have a look too?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Comment by pernielsentikaer** [comment]
Could you remove `package-lock.json` @dannyneup

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Pull request merged**
