### PR TITLE
Add python extension

### PR DESCRIPTION
**Pull request by ahmedivy**
## Description

This new extension allows to search for PyPI packages from raycast, it uses PyPI api. It also allows to launch Python Interpretor.

## Screencast

python-1
python-2
python-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- It seems like there are some dependencies that's not used and some is declared but not added, could you fix that?

Raycast26062024-YWB4dHpE png@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by ahmedivy** [comment]
Hi @pernielsentikaer, you can test it now

**Comment by pernielsentikaer** [comment]
What about `turndown` in `/src/types.d.ts`

**Comment by ahmedivy** [comment]
@pernielsentikaer Is it ok now?

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
