### PR TITLE
Add larajobs-search extension

### PR DESCRIPTION
**Pull request by JustSteveKing**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @JustSteveKing 👋 

I updated the code a bit, are you okay with that? 🙂

**Comment by pernielsentikaer** [comment]
Is there something you don't like we need to change before adding it to the store 🙂

**Comment by JustSteveKing** [comment]
@pernielsentikaer more than ok with it! It's my first raycast extension! Also I don't usually write JavaScript/TypeScript - so it's much appreciated!

**Comment by pernielsentikaer** [comment]
I think I'm done now, added a screenshot and added automatically refresh of data every 5 minutes so it feels faster 🙂

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
