### PR TITLE
Jira Search (self-hosted) - add "status" field as new filter for searching issues in Jira 

### PR DESCRIPTION
**Pull request by koseduhemak**
## Description

Added the possibility to filter against ticket status (one or more) using "!" (exclamation mark):

```
# using two statuus (they will be concatenated with OR - same behavior as for other implemented filters)
my search @myproject !open !ready

# using status containing spaces with double quotes
my fancy search @myproject !"in progress"
```

## Screencast

status_done
in_progress

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by koseduhemak** [comment]
@svenwiegand changed the order accordingly ;)

**Comment by emanguy** [comment]
I'll pull this down today and make sure it works on my end. Stay tuned.

**Comment by koseduhemak** [comment]
> Hi all 👋
> 
> I updated the API to 1.36.0 and updated all deprecated functions. Please test it out again that I didn't break something 😄
> 
> Do you or anyone of you have time to make some [metadata images](https://developers.raycast.com/basics/prepare-an-extension-for-store#adding-screenshots), otherwise I might be able to help out (By either borrowing me a demo account or fake data)

I sadly cannot as all the data in the Jira instance I tested with is confidential... Thats the reason why I removed the sensitive information from the screenshots... 
Maybe someone else can create these with fake data as you proposed?

**Comment by emanguy** [comment]
Update: I may not be able to get around to this until Wednesday. Sorry for the delays!

**Comment by pernielsentikaer** [comment]
@emanguy would be awesome, could you open a PR with the metadata images when you're ready?

Did you test my update @emanguy, @koseduhemak, and @svenwiegand 

Do we need anything else in this PR?

**Comment by emanguy** [comment]
LGTM!

Screen Shot 2022-06-15 at 4 40 38 PM

**Review by emanguy — APPROVED** [review]

**Comment by emanguy** [comment]
I also have the same problem and cannot upload full informational images as the issue titles are sensitive 😞

**Comment by pernielsentikaer** [comment]
Let's tackle that later, I can maybe fake some data later 😄

**Review by pernielsentikaer — APPROVED** [review]
Hi @koseduhemak 👋 

Let's get this merged 🚀 Thanks for your contribution 💪

**Pull request merged**
