### PR TITLE
Update manga-calendar extension

### PR DESCRIPTION
**Pull request by edwin-olivo**
## Description

In the latest updates, new features were added including a new `Comic browse` command and new entries to the .gitignore file.

Several changes were also made: 
- The raycast/api in package.json was updated.
- Types were refactored and their names were changed to more generic ones.
- Component imports were also refactored, and their names were updated. 
- CollectionListView and DetailsView components underwent refactoring. 

## Screencast

manga-calendar 2024-01-26 at 21 36 12

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋

I can't get the `Latest Publications` command to work

Raycast 2024-01-31 at 12 37 21

```
12:38:15.007 Error: Internal Server Error
    at Object.defaultParsing [as current] (/Users/pernielsentikaer/.config/raycast/extensions/manga-calendar/index.js:4132:15)
    at /Users/pernielsentikaer/.config/raycast/extensions/manga-calendar/index.js:4154:39
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by MrOlivo** [comment]
Hello 🖖.
I just noticed it. Its seems that section is down on their website.  I contacted the developers of the original website, and their answer was that they don't have an estimated date for putting it back into operation.

I think it would be better remove or disable that **functionality** until further notice.

Captura de pantalla 2024-01-31 a la(s) 13 11 58

**Comment by pernielsentikaer** [comment]
You decide, I guess they'll fix it soon - so either keep it or remove - let me know when I can do the review again before shipping 🙂

**Comment by pernielsentikaer** [comment]
Is this ready for another review?

**Comment by MrOlivo** [comment]
> Is this ready for another review?

Oh, sorry. I forgot about it 😖. It's ready for review.

**Review by pernielsentikaer — APPROVED** [review]

**Pull request merged**
