### PR TITLE
Feat: Coinbase Pro Extension

### PR DESCRIPTION
**Pull request by farisaziz12**
## Description

Created an extension that uses the Coinbase Pro API. At a glance you can view all the Cryptocurrencies in your portfolio (refreshes every 10 seconds) along with toggling between USD, EUR and GBP. You can also quickly launch the Coinbase Pro webpage with your desired Cryptocurrency view.

## Type of change
- New extension

## Screencast

https://user-images.githubusercontent.com/53216647/141521965-4a63d874-0ec0-412b-825f-44d379b1ab1e.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I checked that extension's icon has size of `512x512`

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @farisaziz12 

Awesome extension, it looks very nice!

A few comment from the very quick spin I gave it:

The UX for faulty credentials could be improved. When entering wrong credentials, it would be better to show “no results” screen and. The first 10 seconds is only showing “USD: 0”, and the loading indicator and a toast with the error. After 10 seconds it shows the “invalid key”.

Do you think we can do something to improve this part?

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by farisaziz12** [comment]
Hey @pernielsentikaer! Thanks for looking and the extension. I appreciate the feedback. I have now fixed the loading and no results UX issue. It looks like this now when the API keys are incorrect:

https://user-images.githubusercontent.com/53216647/141540527-38aee7a1-9f0e-4b2f-ab62-c5112e0f7d7e.mov

**Comment by pernielsentikaer** [comment]
Awesome @farisaziz12 💪 

That helps a lot on the UX already 💯  — You could style the “No Results” view a bit more and make it something like this as some other extensions is doing it.

CSAq87DjzGMsaCV6

**Comment by farisaziz12** [comment]
Hey @pernielsentikaer! Thanks for the suggestion 😄. I have now implemented it along with a few more tweaks to improve UX. Let me know if you spot anything else!

**Comment by pernielsentikaer** [comment]
Hi @farisaziz12 👋 

I have to check with the team about refreshing intervals, normally it's handled by an ActionPanel item with a refresh action.

For now, I found a bug, if landing on “Invalid key” screen and just clicking outside the Raycast window, then the window will open with focus every 10 seconds. That's also one of the reason intervals might be a bad idea.

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by farisaziz12** [comment]
Hey @pernielsentikaer  👋

Thanks for spotting that. I have now removed the refresh interval. 
It might be nice to add it back in the future. Do you have any suggestions as to how to go about it without causing the bug? It doesn't really impact the main feature of the extension but is a nice to have. 

Am happy to have it merged in without this and can work on a future update that adds something like this without causing any issues. 😄

**Comment by pernielsentikaer** [comment]
Hi @farisaziz12 👋 

Yes it's pretty strange, I'll check it tomorrow if I can see what's causing it (I'm not at my primary machine).

- Is there a way I can test this extension with a valid set of credentials? Feel free to contact me at [Slack](https://raycastcommunity.slack.com/) in the #extenion channel, if not it's also fine, just easier to check with them

**Comment by farisaziz12** [comment]
Hey @pernielsentikaer,
No worries. Am just curious about the cause of the issue 🤔.

I use my own set of credentials to  test the extension. I don't think it would be wise to share those. However, if you have any test cases in mind I am more than happy to go through those flows and share screen recordings in this PR 😁.

**Comment by pernielsentikaer** [comment]
Hi @farisaziz12 👋 

Thanks for the chat about the extension in Slack, it was a pleasure 💪

**Pull request merged**
