### PR TITLE
[Facetime]: Add dropdown for contacts and possibility for audio calls

### PR DESCRIPTION
**Pull request by arthur-fontaine**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
It looks like a nice update, but you removed the possibility insert a number manually - could we still keep that?

**Comment by arthur-fontaine** [comment]
> It looks like a nice update, but you removed the possibility insert a number manually - could we still keep that?

Thank you for your feedback! Sorry for the delay, I was very busy. I agree that it's important to keep the ability to manually input a number. What I wanted to do initially was to replace the `No results` message with a `Call [typed number]` suggestion if the entered number is not registered. However, I couldn't find a way to do this using the Raycast components. Do you have any suggestions?

Capture d’écran 2024-10-17 à 14 35 30

**Comment by arthur-fontaine** [comment]
> It looks like a nice update, but you removed the possibility insert a number manually - could we still keep that?

Thanks for your feedback! Sorry for the delay, I've been very busy. This was originally what I wanted to do, but I couldn't find a way to do it the first time I worked on it. With the latest commit, if a number is not in the user's contacts, it will show `Call [what you typed]`.

Capture d’écran 2024-10-17 à 15 24 13
Capture d’écran 2024-10-17 à 15 24 22

**Comment by pernielsentikaer** [comment]
Can we support phone numbers with just 8 digits too?

**Comment by arthur-fontaine** [comment]
> Can we support phone numbers with just 8 digits too?

In fact it does. It's just for the icon. But can you give me an example? (in my country there is no 8 digit phone number, I don't see what it looks like) I will edit the regex. I took it on ihateregex.io, I thought it would be adapted for all the world.

**Comment by pernielsentikaer** [comment]
A number here is just like this: 30123454

**Comment by pernielsentikaer** [comment]
Are you still around @arthur-fontaine

**Comment by arthur-fontaine** [comment]
oops forgot this one... just pushed a commit (it should be there in few minutes)

**Comment by arthur-fontaine** [comment]
instead of checking if the input is a phone number, i just show the email icon if the input contains a character other than a number, a `+`, a `-` or a space

**Comment by pernielsentikaer** [comment]
Looks good, let's do that

**Pull request merged**
