### PR TITLE
GitHub: Add category preferences to select which pull requests to show in the menu bar

### PR DESCRIPTION
**Pull request by qeude**
## Description

I think most of us have some preferences on which pull requests we would like to have in the menu bar, that's why I added the possibility to select categories we want to include.

## Screencast

image
image
image

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by thomaslombart — COMMENTED** [review]
Thanks for the PR. It's a great addition. I don't see how the icon count categories are useful. I think the count should simply reflect the number of items you have in your menu bar.

For example, when I tested it, I only had 2 PRs for the icon count, but when I saw the list, I noticed 12 PRs, which was confusing. It would also simplify the preferences and the code.

**Comment by qeude** [comment]
Thanks for your review @thomaslombart! 🙏
I think that the icon count depends a lot on individual needs. 
Personally, I lean towards having a count of PRs that require my attention—be it for a review, assignments, or mentions. It serves more like a notification badge for me, meaning I don't want notifications about the PRs I've opened. 
Yet, I still like the convenience of quickly accessing these PRs from the menu bar list. 
I understand, though, that preferences can differ; some folks might prefer a broader view, encompassing all ongoing PRs, regardless of whether they've been opened or are awaiting review. 
That's precisely why I've made it fully customizable.

**Comment by qeude** [comment]
Is there anything else I can help you with so we can merge that PR @thomaslombart?

**Comment by thomaslombart** [comment]
I was on vacation last week, so I couldn't reply. We can keep both preferences but they should at least have the same defaults so that it's not initially confusing. What do you think?

**Review by thomaslombart — APPROVED** [review]
🚀

**Pull request merged**
