### PR TITLE
Fixes #1642 : send-to-flomo support IME input 

### LINKED ISSUE #1642: [Send to flomo] ...
# Extension – [Send to flomo](https://github.com/raycast/extensions/tree/de047f2e9ad02d2c79a526f2291f64f74aca05b6/extensions/send-to-flomo/)
Author:

## Description

IME now working with this extension

## Steps To Reproduce

1. open extension
2. try type Chinese with IME( e.g. 搜狗输入法)， nothing show up

### PR DESCRIPTION
**Pull request by fankaidev**
## Description

change "value" to "defaultValue" in react input, such that it could properly handle IME input 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
I'm not sure what this PR is doing? For me it works with the Store version and this PR, nothing changes at all

image

Can you maybe help me understand @fankaidev

**Comment by fankaidev** [comment]
> I'm not sure what this PR is doing? For me it works with the Store version and this PR, nothing changes at all
> 
> image
> 
> Can you maybe help me understand @fankaidev

hi, sorry I only tried macOS systems, and the store version doesn't seems to work. What system are you using ?

**Comment by pernielsentikaer** [comment]
@ahonn can you check this? Does this work for you fine in the Store version?

**Comment by pernielsentikaer** [comment]
@fankaidev I'm on macOs 12.4 - can you maybe send me a video where you show both scenarios?

**Comment by fankaidev** [comment]
@pernielsentikaer thanks for moving forward~ just tried the store version on my macOS 12.4 and it works fine now

**Comment by pernielsentikaer** [comment]
Glad to hear that it works as expected now - you're welcome 🙂

**Pull request merged**
