### PR TITLE
Initial checkin for Readymetrics Raycast extension.

### PR DESCRIPTION
**Pull request by chadbutz**
## Description

Lists upcoming and past check-ins in Readymetrics - a tool for managing employee/manager one-on-ones.

## Screencast

readymetrics-raycast

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @chadbutz 👋 

Awesome extension, it looks rad 🔥 

I have some feedback for you:

- If a wrong token is used it dies, could you make it die gracefully instead with an empty array as data and maybe show an error toast instead?

CleanShot 2022-08-29 at 14 41 17@2x

**Comment by chadbutz** [comment]
@pernielsentikaer thanks for the review!  Added a failure toast on unsuccessful API request.

**Comment by chadbutz** [comment]
> Hi @chadbutz 👋
> 
> Awesome extension, it looks rad 🔥
> 
> I have some feedback for you:
> 
> * If a wrong token is used it dies, could you make it die gracefully instead with an empty array as data and maybe show an error toast instead?
> 
> CleanShot 2022-08-29 at 14 41 17@2x

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by thomaspaulmann** [comment]
Thanks for the review @pernielsentikaer

**Comment by chadbutz** [comment]
Indeed, thanks @pernielsentikaer!

**Pull request merged**
