### PR TITLE
add get ssh key

### PR DESCRIPTION
**Pull request by tc9011**
## Description

get your local SSH key quickly

## Screencast

https://user-images.githubusercontent.com/18380140/221825412-6a71a5a8-858d-477f-a11e-bb78463a52b5.mov

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Potentially this will `cat` multiple keys, is this as intended?

**Comment by tc9011** [comment]
hi, @pernielsentikaer, thanks for reviewing. As this article says ( [Checking for existing SSH keys - GitHub Docs](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/checking-for-existing-ssh-keys)), there are three kinds of public SSH key names,  so I changed `cat ~/.ssh/id_rsa.pub` to `cat ~/.ssh/id_*.pub`.  The `*` is used for compatibility with the key name that may appear later.

**Comment by pernielsentikaer** [comment]
But the extension is called `Get SSH Key`, which might give you a lot of keys `cat'ed` into one string?

**Comment by tc9011** [comment]
Oh, I know your point, and most developers may only have one public key in their local computer, and for those who have multi kinds of public keys, how about just copying the first `.pub` file?  like `cat $(find ~/.ssh/ -maxdepth 1 -name "*.pub" -print -quit) | pbcopy`

**Comment by pernielsentikaer** [comment]
One crazy idea could also be if there is more than one, show them in a list and let the user pick. 🚀

**Comment by tc9011** [comment]
Great idea!

**Comment by pernielsentikaer** [comment]
Hi @tc9011 👋 

What do you think about this einhancement?

**Comment by tc9011** [comment]
wow! It looks great! Thanks for helping me enhance this extension!

**Comment by pernielsentikaer** [comment]
I'm glad you like the enhancement @tc9011 🔥

**Review by pernielsentikaer — APPROVED** [review]
Hello 👋

I gave it a quick spin, works as expected, approved 🔥

**Pull request merged**
