### PR TITLE
Add openvpn extension

### PR DESCRIPTION
**Pull request by benekuehn**
## Description
Created a new extension for OpenVPN based on the script command. I decided to create a new extension because (a) the script command was not working anymore and (b) because for me as a new user, the store was the first place to search for anything I needed, not a GitHub repo. Hence the submission for this new extension.

## Screencast
(The browser window is just opening as my OpenVPN config requires browser sign-in.)

https://github.com/raycast/extensions/assets/41262108/cb083e72-3cbd-4dec-8216-4d3695fcd9e7

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @benekuehn 👋 

Seems like it works as expected, is there a way to not open the OpenVPN menu in the menu bar? It takes a second or two with this visible before it's turning it either on or off 🙂

Does it always just connect to the current profile?

**Comment by benekuehn** [comment]
> Hi @benekuehn 👋
> 
> Seems like it works as expected, is there a way to not open the OpenVPN menu in the menu bar? It takes a second or two with this visible before it's turning it either on or off 🙂

Sadly, I haven't found any. The "CLI" if you can even call it that from OpenVPN is limited, to say the least. So for now the best possible option I found was to use the UI. But let me check on the weekend, maybe I find another way.

> Does it always just connect to the current profile?
Yes, to keep things simple, it will just use the current profile for now.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by SaneHe** [comment]
@benekuehn I am using openvpn in multiple environments and cannot establish a connection; I am using openvpn in the form of multiple environment configuration files. 
step: open openvpn client => Import Profile

**Pull request merged**
