### PR TITLE
Add natural-language-discord-timestamps extension

### PR DESCRIPTION
**Pull request by FarazPatankar**
## Description

The extension allows users to enter a date and/or time in natural language and responds with 3 different variations of Discord timestamps which when entered in Discord create a dynamic message. The dynamic message makes it so that the viewer sees the time in their own timezone based on the format selected by the user.

## Screencast

A demo I had shared on Twitter: https://x.com/farazpatankar/status/1802322814642393139

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi 👋

Thanks for your contribution 🔥

How is this compared to [Discord Timestamps](https://www.raycast.com/theshadowdev/discord-timestamps) by @thewilloftheshadow, it looks like they serve the same purpose but might be a slighty different approach 🙂

**Comment by FarazPatankar** [comment]
Hey, thanks for the review. 

I tried the other one first and felt like it does a bit too much and iirc, you need to open the command action before you can enter natural language. 

Comparatively, the one I've created allows you to do that from the get go + is restricted to a single functionality!

**Comment by pernielsentikaer** [comment]
Hi 👋

That part could be revised; perhaps it could be combined?

If we added optional arguments, they would be used if set. If not, the script would check if the selected text is a valid date and use that. Failing that, it would check the clipboard for the same thing and fallback to nothing 🙂

It would be best to have just one extension for this purpose, as it would reduce confusion among end users by preventing multiple extensions with the same function.

**Comment by FarazPatankar** [comment]
Hmm, I understand. Sadly, I don't have the bandwidth/cycles to update the other extension. I basically built this at the airport on the way to my vacation which I am now back from.

My teammates would still like to use this, IIRC there's an option to publish this only to my team, correct?

**Comment by pernielsentikaer** [comment]
That's correct, you can always add it to your team store, you simply need a few more fields before publishing it

```
  "author": "thomas",
  "owner": "raycast",
  "access": "private",
```

**Pull request closed without merging**
