### PR TITLE
Update wifi-share extension

### PR DESCRIPTION
**Pull request by robinsrk**
## Description

This extension gets saved wifi password from mac and creates a qr code which can be scanned by mobile phones to connect to same network.
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Could you look into the title, is it how you want it, otherwise please correct and move to changelog and readme 🙂

**Comment by robinsrk** [comment]
> Could you look into the title, is it how you want it, otherwise please correct and move to changelog and readme 🙂

Ok i can change the title and push again

**Comment by pernielsentikaer** [comment]
Thanks, there is a mi of different titles so would be nice to settle on one 🙂

**Comment by pernielsentikaer** [comment]
Are you still around @robinsrk

**Comment by robinsrk** [comment]
> Are you still around @robinsrk 

Sorry for being inactive for long time. I will update it tomorrow

**Comment by pernielsentikaer** [comment]
Is this ready for the final review?

**Comment by robinsrk** [comment]
> Is this ready for the final review?

Yes sir

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by robinsrk** [comment]
> Hi 👋
> 
> Looks good to me, approved 🔥

Thanks sir. 😃

**Pull request merged**
