### PR TITLE
Add Holodex extension

### PR DESCRIPTION
**Pull request by uetchy**
## Description

Add extension for [Holodex](https://holodex.net)

## Screencast

Screenshot5

Screenshot

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @uetchy 👋 

I have tested your extension and I have some questions:

- What is the API Key used for? I wrote `hello` in the field and everything seems to work(?)
- Metadata images are not aligned correctly according to [screenshot guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots).

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by uetchy** [comment]
@pernielsentikaer Thank you for taking your time!

> What is the API Key used for? I wrote hello in the field and everything seems to work(?)

Currently there's no limitations for not passing API key or giving the wrong API key. But in the future we may make the API return an error if you don't give your API key correctly.

> Metadata images are not aligned correctly according to [screenshot guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots).

Can you give me the part of the guideline you are referring to?

**Comment by pernielsentikaer** [comment]
> @pernielsentikaer Thank you for taking your time!
> 
> > What is the API Key used for? I wrote hello in the field and everything seems to work(?)
> 
> Currently there's no limitations for not passing API key or giving the wrong API key. But in the future we may make the API return an error if you don't give your API key correctly.
Makes sense, thanks for the clarification 😄 

> > Metadata images are not aligned correctly according to [screenshot guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots).
> 
> Can you give me the part of the guideline you are referring to?

image

If you struggle to get the right paddings, let me know and I'll help you! 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by uetchy** [comment]
@pernielsentikaer I'm 100% sure my screenshots are in accordance with this spec🤔
I even used your Figma template for making them.

CleanShot 2022-05-02 at 21 30 53@2x

**Comment by pernielsentikaer** [comment]
Hi @uetchy 👋 

It's almost as it should be, but there is too much padding on both top and bottom, the sides are looking good.

CleanShot 2022-05-03 at 05 49 48

Do you want some help with this?

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by uetchy** [comment]
> Do you want some help with this?

Yes, can you update the template to match the actual size of Raycast interface?

**Comment by uetchy** [comment]
CleanShot 2022-05-03 at 13 27 40@2x

It's literally impossible to match a screenshot to your template.

**Comment by uetchy** [comment]
@pernielsentikaer I found out why there was a gap between the template and my screenshot. It was because I changed the settings for the text size of Raycast interface. Updated the screenshots.

Anyways, I'd add PSA for those who want to publish their extensions and have changed the UI text size to the doc.

**Review by pernielsentikaer — APPROVED** [review]
Hi @uetchy 👋 

Much better 🔥

**Pull request merged**
