### PR TITLE
[New Extension] Microsoft OneNote

### PR DESCRIPTION
**Pull request by alewandows**
## Description

The PR adds a new extension _OneNote_ to search/browse/preview/open notes in Microsoft OneNote.

## Screencast
onenote-1
onenote-2

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

* Could we handle it if OneNote is not installed? 

image

* What is supposed to happen in `Browse Notes` when it's installed? It just opens the current view when I use `Open in OneNote`

* The icon color in `Browse Notes` is not a good match; you might use `Color.Purple` or use the value from the `item`

Raycast-O61ryUOm@2x

* I'm a bit confused about this view; it feels messy. Can we do something? I.e., group in sections? New sections seem to be the only one switching in OneNote

Raycast-UUPyaEZJ@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by alewandows** [comment]
Thanks a lot for the detailed review! It really helped me to improve the extension.
I've made some changes : 

- it now checks first if OneNote is installed, 
- corrected the bad Color of some list items
- kept only one command (Search OneNote) for clarity
- added possibility to group results by item type (notebooks, sections, items), or to keep all results flatten
- improved the navigation inside notebooks or sections : pressing `tab` or `enter` enters the element 
- "open in onenote" action only appears in the note preview 
- added a callback action when search gives no result inside a notebook or section: create a note with search text

onenote 2023-02-08 at 19 51 48

Hope it will provide better user experience!

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for all the corrections; it works much better now for sure 🔥 

It would be better to use useSql from @raycast/utils instead, could you try to use that instead since it also handles a lot more edge cases 😊

**Comment by alewandows** [comment]
Hi 👋

With the help of some slack fellows, I managed to use of useSQL from @raycast/utils  for my select requests 👍.
Remaining sql code is for database creation only.

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋

Approved; let's 🚢 it!

**Pull request merged**
