### PR TITLE
Add vivapb extension

### PR DESCRIPTION
**Pull request by codrkoaz**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — COMMENTED** [review]
Hi 👋

I don't have Vivaldi installed and I just get never-finishing loader, can you look into making a check for this and show a HUD? Extensions like [Eagle](https://www.raycast.com/Yukai/eagle) does that

Maybe also make the command a no-view instead 🙂

**Comment by pernielsentikaer** [comment]
Is this ready for another review?

**Comment by pernielsentikaer** [comment]
Could you test this like you don't have Vivaldi installed? When I open the command nothing happens except it freezes for a few seconds

https://github.com/raycast/extensions/assets/38033107/6d9a2468-bf65-45a0-be25-782b2435042a

**Comment by codrkoaz** [comment]
> Could you test this like you don't have Vivaldi installed? When I open the command nothing happens except it freezes for a few seconds
> 
>  Raycast29012024-xRqFymrp.png.mp4

thank you for the visual i’ll try this to see what I can do about this.

**Comment by pernielsentikaer** [comment]
Is this ready to be tested again?

**Comment by codrkoaz** [comment]
> Is this ready to be tested again?

yes it is
SCR-20240209-cxlf

**Comment by pernielsentikaer** [comment]
Do you have everything pushed? Nothing happens when I open the command. 

Raycast09022024-gvqCEw37 png@2x

You can see more about no-view format here: https://developers.raycast.com/information/lifecycle

**Comment by codrkoaz** [comment]
> Are you still around @codrkoaz

Yes i’m still around things came up. it’s weird how its not working on your end

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Comment by codrkoaz** [comment]
> Hi 👋
> 
> Looks good to me, approved 🔥

AWESOME!!! And can i make commits to this if i want to add more?

**Pull request merged**
