### PR TITLE
Add image-base64 extension

### PR DESCRIPTION
**Pull request by VitorLostada**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by vitorLostadaC** [comment]
> Hi 👋
> 
> Thanks for your contribution 💪
> 
> I have now tested your extension, and I have some feedback ready for you:
> 
> * Using `qwer` passes the validation, should it?
> 
> I'm looking forward to testing this extension again 🔥
> 
> Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

Hi @pernielsentikaer, it's a valid base64 haha, however, it's not true for images, so I added a minimum length and some improvements to work with MB and KB, please let me know if you find another thing.

**Comment by pernielsentikaer** [comment]
Is this ready for review, or are you still working 🙂

**Comment by vitorLostadaC** [comment]
> Is this ready for review, or are you still working 🙂

its ready 😁

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
