### PR TITLE
anonaddy - Add extension

### PR DESCRIPTION
**Pull request by httpjamesm**
## Description

Added an extension that interacts with the [AnonAddy](https://anonaddy.com) [API](https://app.anonaddy.com/docs). It allows users to list, generate and edit their aliases using Raycast. 

## Screencast

AnonAddy commands

Due to the amount of personal information this extension displays, I have not provided any screencast.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪

I have some comments for you:

- When wrong credentials is used it dies, could you make it die gracefully and return an empty array and maybe use a error toast to explain.

image

- I think I would make the command `Generate Alias` a no-view command and just copy the e-mail to the clipboard.

- `List Aliases` should make use of <List `isLoading` property

- `Edit Alias` here I get this error, do you need help solving it?

```
10:41:12.213 The Form Item `email` is changing from an uncontrolled input to be controlled. This is likely caused by the value changing from `undefined` to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
```

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by httpjamesm** [comment]
@pernielsentikaer I have made the changes you suggested and hopefully resolved that bug.

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @httpjamesm 👋 

Awesome, thanks for the fix 🔥 I changed a few things and switched to Raycast default search engine in `List Aliases`, I found something that I couldn't do, when I tried to activate a deactivated alias I got this error `Method Not Allowed`

Can you also check that I didn't break anything 😊

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by httpjamesm** [comment]
@pernielsentikaer I've fixed the endpoints for the activation and deactivation features!

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
