### PR TITLE
Add markdown-to-plain-text extension

### PR DESCRIPTION
**Pull request by skyline-123**
## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @skyline-123 👋 

I'm a bit confused, is this an update to a current extension in the store or a new one?

**Comment by skyline-123** [comment]
> Hi @skyline-123 👋
> 
> I'm a bit confused, is this an update to a current extension in the store or a new one?

Sorry, I have changed the title and it's a brand new plugin now.

**Comment by pernielsentikaer** [comment]
What do you think about the corrections I made, are you okay with that?

**Comment by skyline-123** [comment]
> What do you think about the corrections I made, are you okay with that?

Very good, you have considered more comprehensively and raised exception reminders. Thank you for your supplement.

**Pull request merged**
