### PR TITLE
Sourcegraph: Batch Changes, revamped previews, and refined behaviour

### PR DESCRIPTION
**Pull request by bobheadxi**
## Description

- **batch-changes**: "Manage Batch Changes" is a new command that allows you to browse, view, publish, merge, and retry changesets for [Sourcegraph Batch Changes](https://about.sourcegraph.com/batch-changes)! This is only supported on Sourcegraph Self-Hosted. ([#11](https://github.com/bobheadxi/raycast-sourcegraph/pull/11), [#13](https://github.com/bobheadxi/raycast-sourcegraph/pull/13))
- **search**, **notebooks**: The default action on results is now to always open a preview in Raycast, rather than opening in browser directly, for consistency. Previously, results with single matches would open in the browser directly.
- **search**: Search results now have a new drilldown action to query within the result's repository or file using the `Cmd-S` shortcut. For example, on a repository result, `Cmd-S` will start a search with the `repo:` filter.
- **search**: The default context is now explicitly pre-populated in the search bar, instead of being implicit.
- **search**: You can now apply suggestions directly with an action.
- **search**: Path result previews (e.g. from `type:path` or `select:file`) now render a preview of the file contents.
- **search**: Repo result previews (e.g. from `repo:` or `type:repo`) now render the repository's `README.md`.
- **search**: Some search result types now leverage metadata details.
- **search**: An experimental dropdown for selecting the search pattern type to use can now be enabled under the extension preferences.
- **search**: Potential fix for issue with connecting to self-hosted Sourcegraph instances. (closes [raycast/extensions#1126](https://github.com/raycast/extensions/issues/1126))
- **notebooks**: Notebook view now leverage metadata details and support the new Symbol block type.
- **prefs**: Fixed issue with self-hosted instance URLs that have trailing slashes. ([#12](https://github.com/bobheadxi/raycast-sourcegraph/pull/12))

Commits: https://github.com/bobheadxi/raycast-sourcegraph/compare/b0db17c...933682d

## Screencast

See new `metadata/` screenshots of updated commands: https://github.com/bobheadxi/raycast-sourcegraph/tree/main/metadata

Quick demo of the new [Batch Changes](https://about.sourcegraph.com/batch-changes/) command, which is only available on Self-Hosted Sourcegraph and requires a bit of setup externally:

https://user-images.githubusercontent.com/23356519/160303311-7140b07c-76fb-4ccd-88b8-ad654016fa22.mp4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed in the `metadata` folder

### CODE REVIEW

**Comment by bobheadxi** [comment]
@pernielsentikaer @sxn any chance we might be able to release this update?

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @bobheadxi 👋 

Thanks for the huge update, it's going to be awesome! 😄 

I have some feedback ready for you to look into:

- Seems like the metadata images are not having the right space (150 top/bottom and 250 in sides) – Could you correct it, let me know if you need any help.

- Not all errors are handled gracefully, could you look into this?

Idc1eQHoSAXNRd8H

Request a new review when you are ready, feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by bobheadxi** [comment]
Error handling fixed:

image

**Comment by bobheadxi** [comment]
@pernielsentikaer I've updated the screenshots in [`9df3502` (#1228)](https://github.com/raycast/extensions/pull/1228/commits/9df3502e8169cb815ff8dfd4cf086ce521bc7595)

**Pull request merged**
