### PR TITLE
Spotify: Support "Your Library" as a fallback command

### PR DESCRIPTION
**Pull request by ksunats**
## Checklist

- [ ] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [ ] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [ ] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [ ] I checked that files in the `assets` folder are used by the extension itself
- [ ] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by apaofficial** [comment]
Hi, this is just a minor change to allow playing specific playlist through quicklink context query - something I consider a basic usecase and something I saw multiple discussions about dating back to 2022. Hope it's OK. Thanks!

**Review by thomaslombart — COMMENTED** [review]
Thanks for the PR! What is this solving exactly? I thought it was to support `Your Library` as a fallback command but it seems to already work without these changes.

**Comment by thomaslombart** [comment]
Hey there, thanks for the PR! The extension is designed to be in line with Spotify, so for consistency reasons, we'll keep it as `Your Library` ☺️

**Comment by erics118** [comment]
From my experience, it seems that Raycast automatically supports adds in support for commands that don't explicitly support being fallback commands. I've experienced this with numerous commands. Not sure if this is the correct behavior though.

**Comment by thomaslombart** [comment]
> From my experience, it seems that Raycast automatically supports adds in support for commands that don't explicitly support being fallback commands. I've experienced this with numerous commands. Not sure if this is the correct behavior though.

Yeah, it's expected on our end, which is why I'm wondering what's the goal of this PR 🙂

**Pull request closed without merging**
