### PR TITLE
Harvest

### PR DESCRIPTION
**Pull request by eluce2**
## Description

Update for v1.37.1
Add support for automatically focusing the next field after selecting a project or task

## Screencast

https://share.cleanshot.com/yZ0BkA

## Checklist

- [X] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [X] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [X] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [X] I checked that files in the `assets` folder are used by the extension itself
- [X] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Hi @eluce2 👋 

I'm not so sure this is the way to go, it would be the only thing in Raycast with this behavior, this would cause a really weird UX

Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by eluce2** [comment]
@pernielsentikaer This is the behavior I wanted when I first built the extension, but it wasn't possible until a recent API update. I better matches the Harvest Desktop app, which is what most people would be coming from when they try this extension. It has always felt very unnatural to me to remain focused on the field after selecting something from a drop-down menu.

If those arguments don't convince you, could I keep this feature behind a preference that is disabled by default?

**Comment by eluce2** [comment]
@pernielsentikaer I have reverted this change, now this PR is to simply update to the latest version of the API.

While it saddens me to not have this behavior, in my experience using it over the past few weeks it hasn't always worked in the way I would expect it to, so I'm ok with reverting

**Comment by pernielsentikaer** [comment]
Hi @eluce2 👋 

Sorry for the long response time. I'm on vacation and only checking from time to time 😄 

Yes, I could imagine there are some drawbacks since it's not made for that; let's keep it as is for now.

Approved! 🔥

**Pull request merged**
