### PR TITLE
Update zotero extension

### PR DESCRIPTION
**Pull request by sadanand-singh**
## Description

1. Make open PDF as default Action
2. Use dropdown filter for collections
3. Update icons

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- Maybe you should update metadata and media images to have the same look, do you need help with that?

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pernielsentikaer** [comment]
Do you know you can use our [metadata image tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) tool which is built into Raycast? That should remove all development icons and make them in an ease

**Comment by sadanand-singh** [comment]
> Do you know you can use our [metadata image tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) tool which is built into Raycast? That should remove all development icons and make them in an ease

No, I didn't know about it. I will try using it. Thanks

**Comment by sadanand-singh** [comment]
> Do you know you can use our [metadata image tool](https://developers.raycast.com/basics/prepare-an-extension-for-store#screenshots) tool which is built into Raycast? That should remove all development icons and make them in an ease

Thanks @pernielsentikaer I have updated all screenshots with the metadata image tool.

**Comment by sadanand-singh** [comment]
sorry for the last commit. it was low hanging fruit, that I just added. I am done with the changes in the PR. Please go ahead with your review. Thanks

**Pull request merged**
