### PR TITLE
Add 0x0 extension

### PR DESCRIPTION
**Pull request by pseudobun**
## Description

0x0 extension allows users to select and upload a file to https://0x0.st. Meant for a quick share of media that can be published publicly.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi 👋 

Thanks for your contribution 💪 

I have now tested your extension, and I have some feedback ready for you:

- I would either use [popToRoot()](https://developers.raycast.com/api-reference/window-and-search-bar#poptoroot), [useForm](https://developers.raycast.com/utilities/react-hooks/useform) or the [Imperative API](https://developers.raycast.com/api-reference/user-interface/form#methods-imperative-api-1) to reset the fields if not choosing [popToRoot()](https://developers.raycast.com/api-reference/window-and-search-bar#poptoroot)

- Add some validation since it's possible to upload without a file, this is also something [useForm](https://developers.raycast.com/utilities/react-hooks/useform) can handle.


I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://www.raycast.com/community) if you have any questions.

**Comment by pseudobun** [comment]
Hey @pernielsentikaer!

I finally found some time to update the extension according to your feedback! I used `useForm` instead and am now successfully validating the required FIle picker field in the form.

**Comment by pseudobun** [comment]
Hey @pernielsentikaer. I see you've made some additonal changes. Is there anything else waiting to be updated from my side?

**Review by pernielsentikaer — APPROVED** [review]
No, let's get the first version out in the store 🚀

Looks good to me, approved 🔥

**Pull request merged**
