### PR TITLE
Update raycast explorer extension

### PR DESCRIPTION
**Pull request by xilopaint**
## Description

I believe there's a mistake in the example of the custom prompt. Please check it out.

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by xilopaint** [comment]
https://github.com/raycast/extensions/blob/4f6630aaa6c1b1828f7c41e9f5cf0380f532e023/extensions/raycast-explorer/src/data/prompts.ts#L1335

@thomaslombart @mil3na Is the `Use English language` part really intended here?

**Comment by mil3na** [comment]
> https://github.com/raycast/extensions/blob/4f6630aaa6c1b1828f7c41e9f5cf0380f532e023/extensions/raycast-explorer/src/data/prompts.ts#L1335
> 
> @thomaslombart @mil3na Is the `Use english language` part really intended here?

Yes. That's how the prompt was built. We don't officially support languages other than English yet.

**Comment by xilopaint** [comment]
> > https://github.com/raycast/extensions/blob/4f6630aaa6c1b1828f7c41e9f5cf0380f532e023/extensions/raycast-explorer/src/data/prompts.ts#L1335
> > 
> > @thomaslombart @mil3na Is the `Use english language` part really intended here?
> 
> Yes. That's how the prompt was built. We don't officially support languages other than English yet.

But it works with other languages anyway. I can't see what this instruction adds to the prompt when working with English, not to mention that it might worsen the performance when working with other languages, apart from adding unnecessary tokens, which I believe incurs costs to Raycast.

Anyway, could you review the PR? My question was not related to the changes.

**Comment by mil3na** [comment]
Sure. If you want to discuss your question further, just ask on #raycast-ai channel on Slack. The people who created the prompt might have more context on it.

**Pull request merged**
