### PR TITLE
Discord Extension

### PR DESCRIPTION
**Pull request by Aayush9029**
## Description

Send message to a Discord channels using Web hooks.

## Screencast

CleanShot 2022-04-11 at 01 02 24a

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Review by pernielsentikaer — CHANGES_REQUESTED** [review]
Hi @Aayush9029 👋 

Awesome extension 🔥 

I have some feedback for you:

- The icon for [List.EmptyView](https://developers.raycast.com/api-reference/user-interface/list#list.emptyview) should be 64x64, could you resize a copy to that size?

- The command `Send Message` suffer from [Empty state flicker](https://developers.raycast.com/basics/prepare-an-extension-for-store#empty-states)

- When toggling items as favorites it pops to root, it would be much better to redraw the list.

- Shouldn't it be named `Delete Webhook" instead?

CleanShot 2022-04-25 at 10 52 01@2x

I'm looking forward to testing this extension again 🔥 

Request a new review when you are ready. Feel free to contact me here or at [Slack](https://raycastcommunity.slack.com/) if you have any questions.

**Comment by Aayush9029** [comment]
> When toggling items as favorites it pops to root, it would be much better to redraw the list.

@pernielsentikaer is there an extension or Raycast documentation  you can point me to? I can't seem to figure it out by myself! 😄

**Comment by pernielsentikaer** [comment]
Hi @Aayush9029 👋 

I did it in #1405 - take a peek there 😄

**Comment by Aayush9029** [comment]
@pernielsentikaer I've removed the toggle favourites for now 😄 
It shouldn't hinder extension's functionality in anyway! 
lmk if there's anything else that needs to be changed!

**Review by pernielsentikaer — APPROVED** [review]
Hi @Aayush9029 👋 

Let's get it merged, but I would like to see the favorite feature added again later. This functionality should be used with the delete function which also pops to root 😄 

It could also be fantastic with a custom No Results screen 😄

**Comment by ashishbhateja** [comment]
Hi, thanks for this extension. Can you add an option to send message to threads instead of channel?

**Pull request merged**
