### PR TITLE
Add london-live-arrivals extension

### PR DESCRIPTION
**Pull request by ichikmarev**
## Description

This extension uses the TFL public API to provide information about upcoming arrivals. The command itself displays the nearest 3 arrivals from the selected station, while opening the extension will show the next 5 arrivals.

Additionally, you can select new stations in the supported transport types around the area.

As a newcomer to TypeScript, any feedback would be appreciated. The next plan is to add more API support, improve empty states, implement search functionality, and allow customization of the number of entries displayed.

## Screencast

london-live-arrivals-1
london-live-arrivals-2
london-live-arrivals-3

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Thanks for your contribution 🔥 

How is this compared to the [one we have in the store](https://www.raycast.com/haneenmahdin/tfl)?

**Comment by ichikmarev** [comment]
> Thanks for your contribution 🔥
> 
> How is this compared to the [one we have in the store](https://www.raycast.com/haneenmahdin/tfl)?

Hey, thanks for asking @pernielsentikaer 

The key differences are:
- My extension searches stations in a different way, so the one you are pointing at, for example, is missing some of the stations (try Wapping).
- My extension uses a different data format for displaying the time and date, while the mentioned extension does not display the time with minutes.
- My extension allows you to specifically select the concrete stations.
- My extension supports bus stops.

To conclude, even though they serve the same purpose, my extension has more features and is updated to the latest TFL API.

**Comment by ichikmarev** [comment]
Hey @pernielsentikaer what's out next actions?

**Comment by pernielsentikaer** [comment]
Sorry for the long response time, somehow a few of my notifications disappeared from the notification center

I still think it would be better to enhance the current one by @haneenmahd instead of creating a similar extension since it always ends up confusing the end user about which extension to use.

I'm sure @haneenmahd is up for contributions 🙂

**Pull request closed without merging**
