### PR TITLE
Add support for Bear 2 to the bear extension

### PR DESCRIPTION
**Pull request by lucaschultz**
## Description

I added support for the new Bear 2 (see #5407, #5502 and #5510) which is [currently in beta](https://beta.bear.app/t/the-bear-2-beta-is-here/9115). If the extension detects a certain error (missing table when reading the bear database) the extension shows an empty layout which prompts the user to select the the correct bear version in the extension preferences.

I also added a _Search Query_ argument to the _Search Notes_ command and migrated to the lates API version.

### The New Argument

Raycast 2023-03-23 at 15 40 28

### The Prompt To Select The Bear Version

bear-4

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by lucaschultz** [comment]
@hmarr Hmm hadn't thought about that to be honest. Should be possible by just running the V1 queries and switching to the V2 versions if the `no such table` error is thrown.

**Comment by hmarr** [comment]
@lucaschultz you should be able to read the schema programmatically by querying the [schema table](https://www.sqlite.org/schematab.html). As long as there are schema differences (e.g. tables or columns that have changed) you could decide which query to use based on that.

**Comment by lucaschultz** [comment]
Hmm since Bear 2 is a beta I think it would be safe to assume most people are still using V1. If we do something like this:

```ts
  getNotes(searchQuery: string): Note[] {
    let statement: Statement;
    try {
      const bearVersion = this.cache.get("bearVersion");
      statement = this.database.prepare(bearVersion === "2" ? SEARCH_NOTES_V2 : SEARCH_NOTES_V1);
    } catch (error) {
      if (error instanceof Error && error.message === "no such table: Z_7TAGS") {
        statement = this.database.prepare(SEARCH_NOTES_V2);
        this.cache.set("bearVersion", "2");
      } else if (error instanceof Error && error.message === "no such table: Z_5TAGS") {
        statement = this.database.prepare(SEARCH_NOTES_V1);
        this.cache.set("bearVersion", "1");
      } else throw error;
    }
    statement.bind({ ":query": searchQuery });
    const results: Note[] = [];
...
```

We avoid an extra query. Since we cache the last used Bear version using the Raycast cache the error should happen only once per version change. What do you think @hmarr?

**Comment by hmarr** [comment]
That approach also looks fine, as long as the error messages are stable and predictable. We'll need to be slightly careful if we tweak the queries in the future—e.g. you could imagine that if we joined against another table, that table's name might appear in the error message rather than the tags table.

**Comment by lucaschultz** [comment]
> That approach also looks good, as long as the error messages are stable and predictable. We'll need to be slightly careful if we tweak the queries in the future—e.g. you could imagine that if we joined against another table, that table's name might appear in the error message rather than the tags table.

That's a great point! I implemented the solution using a query to the `sqlite_master` table! 🙂

**Comment by lucaschultz** [comment]
@raycastbot please open this issue. @pernielsentikaer if @hmarr agrees this is ready to merge.

**Comment by pernielsentikaer** [comment]
Looks like I can't reopen it 😞

Raycast-0eMiEnPm@2x

**Comment by ttuygun** [comment]
@pernielsentikaer can you try?
https://stackoverflow.com/questions/62479813/github-how-to-re-open-a-pull-request-when-the-branch-has-no-more-history-in-com

**Comment by lucaschultz** [comment]
> Looks like I can't reopen it 😞
> 
> Raycast-0eMiEnPm@2x

Hmm, I force pushed from my local repository to `ext/bear` on my branch. Seems that doesn't work. What is the correct workflow for this?

I created a new fork of the extension, deleted my fork of the repository and copied the files over. However I still can't `npx ray publish`:

CleanShot 2023-04-01 at 11 48 01

**Comment by lucaschultz** [comment]
Okay, I ended up creating a new fork, cloning the fork, copy and pasting my changes in the new clone, committing everything and creating a new pull request #5706 ... maybe someone of the Raycast team could explain what wen't wrong here? 

I read the in the GitHub UI that I could add further changes by pushing to the `ext/bear` branch of the `lucaschultz/raycast-extensions` fork which was created after forking the extension in Raycast. I added the fork as remote to the local repository and tried pushing my changes to the branch. Since that didn't work I force pushed. This immediately closed this pull request because of unrelated histories. What would have been the correct workflow?

**Comment by pernielsentikaer** [comment]
Looks like GitHub was down at the moment, did you ever experience this again?

**Pull request closed without merging**
