### PR TITLE
[unsplash]  Fixed background updates not working.

### PR DESCRIPTION
**Pull request by kkange**
## Description

>  Fixed background updates not working.
- #6214 

## Checklist

- [x] I read the [extension guidelines](https://developers.raycast.com/basics/prepare-an-extension-for-store)
- [x] I read the [documentation about publishing](https://developers.raycast.com/basics/publish-an-extension)
- [x] I ran `npm run build` and [tested this distribution build in Raycast](https://developers.raycast.com/basics/prepare-an-extension-for-store#metadata-and-configuration)
- [x] I checked that files in the `assets` folder are used by the extension itself
- [x] I checked that assets used by the `README` are placed outside of the `metadata` folder

### CODE REVIEW

**Comment by pernielsentikaer** [comment]
Do you mind checking this @eggsy

**Comment by eggsy** [comment]
> Do you mind checking this @eggsy

Seems fine 🤷‍♂️, just a change that combines if statements. Though I don't have any idea how this "fixes" anything as it doesn't change the way the code operates (this is just the display message part).

**Comment by pernielsentikaer** [comment]
Ah, I can see - @kkange do you commit all changes?

**Comment by kkange** [comment]
@pernielsentikaer  Yes, I have committed all changes.

**Comment by pernielsentikaer** [comment]
Can you see the comment from @eggsy - what does it fix? Looks like it's only about some messages?

**Comment by kkange** [comment]
@pernielsentikaer Removed the code that was terminating the function when it ran in the background and changed it to work correctly

**Review by pernielsentikaer — APPROVED** [review]
Hi 👋 

Looks good to me, approved 🔥

**Pull request merged**
